### ISSUE TITLE
why the winrate of recent 10b networks are mostly Close to 0.5 

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1000]
nearly no network's rate large than 0.7 or less than 0.3

**Comment by odeint** [comment]
why anyone can open Issue when is no issue? TensorFlow correct shuffle buffer makes Training not Fail.

**Comment by chillacile** [comment]
@l1t1 please, github issues are not like your posts in your Baidu Tieba.
See if there were similar issues, before you ask questions to avoid a duplicated issue.
And post "a issue" here when there is an issue, instead of those just "questions".

**Comment by l1t1** [comment]
thanks
