### ISSUE TITLE
[Feature request] command line parameter to disable tuner

### ISSUE THREAD

**Issue by pnprog** [gcp/leela-zero#1001]
Hi!

As I distribute Leela Zero as part of GoReviewPartner, with the latest already configured to run Leela Zero, I would like to have a command line parameter to disable auto tuner.

Without that, someone running GRP with Leela Zero for the first time will have to wait for several minutes before the analysis start, without knowing what's happening.

Then, I would write in the GRP documentation that Leela Zero needs tuning, and how to do, but that would be up to the user to do it manually.

There is that other project, [lizzie](https://github.com/CamWagner/lizzie) from @CamWagner that would also benefit from that feature I guess.

An extra option like **--no-tune** would be just fine :)

**Comment by bastiaf** [comment]
You can create a file leelaz_opencl_tuning with the settings which you think are the best defaults.

**Comment by odeint** [comment]
How much does the tuning depend on the details of the system?  I suspect knowing the GPU is already enough, but LZ recognises the type of GPU and CPU during startup. Could we have correct presets for the most common combinations and a general one for the rest? I'm positive that people would be happy to post their configuration and the resulting tuning.

**Comment by gcp** [comment]
This was suggested during the initial tuner development, but nobody has done the work for it yet.

Note that the tuner also detects which configurations do not work correctly with the GPU driver.

**Comment by Cabu** [comment]
If such a project is started, here is my modest contribution fully tuned with the last network:
```
0;XgemmBatched;128;100;128;16; -DKWG=16 -DKWI=8 -DMDIMA=16 -DMDIMC=16 -DMWG=64 -DNDIMB=16 -DNDIMC=8 -DNWG=64 -DSA=1 -DSB=1 -DSTRM=1 -DSTRN=1 -DVWM=4 -DVWN=4;OpenCL: NVIDIA Corporation GeForce GTX 960M @ 1176MHz
0;XgemmBatched;128;100;128;16; -DKWG=16 -DKWI=8 -DMDIMA=16 -DMDIMC=8 -DMWG=64 -DNDIMB=16 -DNDIMC=8 -DNWG=64 -DSA=1 -DSB=1 -DSTRM=1 -DSTRN=1 -DVWM=4 -DVWN=4;OpenCL: Intel(R) Corporation Intel(R) HD Graphics 530 @ 1050MHz
0;XgemmBatched;128;100;128;16; -DKWG=16 -DKWI=2 -DMDIMA=16 -DMDIMC=16 -DMWG=16 -DNDIMB=16 -DNDIMC=8 -DNWG=64 -DSA=0 -DSB=0 -DSTRM=0 -DSTRN=0 -DVWM=1 -DVWN=4;OpenCL: Intel(R) Corporation Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz @ 2600MHz
```

NVIDIA Corporation GeForce GTX 960M @ 662.9 GFLOPS
Intel(R) Corporation Intel(R) HD Graphics 530 @ 119.8 GFLOPS
Intel(R) Corporation Intel(R) Core(TM) i7-6700HQ CPU @ 115.8 GFLOPS

**Comment by odeint** [comment]
NVIDIA Corporation NVS 5400M
`0;XgemmBatched;128;100;128;16; -DKWG=32 -DKWI=2 -DMDIMA=8 -DMDIMC=8 -DMWG=32 -DNDIMB=16 -DNDIMC=16 -DNWG=64 -DSA=1 -DSB=1 -DSTRM=0 -DSTRN=0 -DVWM=4 -DVWN=4;OpenCL: NVIDIA Corporation NVS 5400M @ 950MHz`

**Comment by pnprog** [comment]
@grp,
So for the previous versions were no tuner was used, what was the defaults settings?

**Comment by Ttl** [comment]
The previous version without the tuner used completely different convolution implementation that didn't have tuners.

There should already be relatively safe parameters in the opencl files if tuners are not passed in defines:

https://github.com/gcp/leela-zero/blob/bdc3abe7bbd08d1c3a4d5e5ad2068ea81c99237e/src/clblast_level3/xgemm_part1.opencl#L44-L45

However note that performance without tuning can be bad. It can be more than 50% slower depending on the GPU so running the tuner when possible is highly recommended.

**Comment by StanTraykov** [comment]
Why not just run leelaz --tune-only during installation to get a good config? A bad tuning is a LOT slower than just half-speed on the two GPUs I've tested (GTX 1080Ti, GTX670)--it seems to completely kill the purpose of running a strong program.

**Comment by pnprog** [comment]
@StanTraykov , that would require to tune for all sort of filter sizes during the installation. It would take quite a long time.

Thanks everybody for your answer. At this point, I think the best solution for me it to read Leela Zero stderr and guess is the tuner is running, in order to tell the user to be patient :)
