### ISSUE TITLE
Make autogtp clean up after itself

### ISSUE THREAD

**Issue by Dorus** [gcp/leela-zero#1005]
Over the course of the project, autogtp left gigabytes of network files on my pc. I cleaned them up yesterday, but it would be nice if autogtp cleaned up after itself.

I suggest autogtp stores 3 networks: Latest self play, and 2 nets from the latest match. This should result in 1, 2 or 3 actually stored networks (some clients do not run match games and most of the time, self play net will be part of the latest match). It should delete networks when they are replaced by a new match or self play network.

Possibly this might be a command line argument, some people will want to keep the network files. If we make it so autogtp only removes a net if it remembered it downloaded it itself, we dont mess with existing files in the directory.

Also, network files could get their own directory that would making manual cleanup a lil easier.

**Comment by marcocalignano** [comment]
It is actually a good Idea. At the moment  am really Ill so I have no strength to go into it I will work on it when I feel better.

**Comment by WhiteHalmos** [comment]
@marcocalignano I'll work on some autogtp cleanup if you'll review it. 😃

**Comment by l1t1** [comment]
it is because your pc is strong.my pc only saves  best files

**Comment by marcocalignano** [comment]
I am testing the clean up version now. Need still some time for a PR.

**Comment by gcp** [comment]
Fixed by https://github.com/gcp/leela-zero/commit/41ea2d6dcdaa70dead1173ae870dc00b7a850852 I assume.
