### ISSUE TITLE
Wrong hyperlink

### ISSUE THREAD

**Issue by lige74** [gcp/leela-zero#1010]
There is a wrong hyperlink on the webpage:  https://github.com/gcp/leela-zero
It links to  “Mastering the game of Go with deep neural networks and tree search”, which is the first nature article of Alphago.

**Comment by TFiFiE** [comment]
I think all three papers, i.e. including the AlphaZero one, should be linked to.

**Comment by gcp** [comment]
Fixed in next branch.
