### ISSUE TITLE
Leela Zero strength progression; main net now stronger than zediir's 20x256

### ISSUE THREAD

**Issue by StanTraykov** [gcp/leela-zero#1011]
Leela Zero has become quite a bit stronger over the past month, esp. with the new 0.12 engine and 10x128 nets. From being hopeless against (non-zero) Leela and barely beating KGS's limited-playouts HiraBot 5-6d (when running on much better hardware), it now thrashes Leela (time-limited no-ponder match on same hardware, 1080Ti/i7-8700k) and even came out on top (23:17) in a 40-game match against zediir's Tygem-9d-trained 20x256 network (with hitherto highest Leela Zero CGOS rating of 3465, though it's not really from "zero" a.k.a. tabula rasa, see #884).

Don't know if this is the best place for this, but here are my test results. Perhaps they will save some GPU cycles towards running self-play matches or at least satisfy curiosity.

**Conclusion:** While we can't be reasonably certain that the current net is really stronger than zediir's Tygem-trained Leela "Zero", it's definitely in the same league (likely stronger), and it seems Leela Zero is destined to overtake several AIs and perhaps become one of the top CGOS players (if promotions continue at a similar rate).

**Note:** All games played 3min+10x15s, LZ on full strength.

#### vs Hirabot 5-6d on KGS (Hirabot limited to 15K playouts)

```
Jan 31:	 7-game match	Hirabot won 4:3
Feb 05:	10-game match	Hirabot won 6:4
Feb 11:	10-game match	LZero-cde9 won 6:4
Feb 17:	10-game match	LZero-e11+6c8 won 9:1	* hybrid net (e11+6c8)/2
Feb 24:	10-game match	LZero-8ee4 won 9:1
```

#### vs (non-zero) Leela 0.11.0 (same hardware [1080Ti], noponder)

```
Feb 18: 16-game match	Leela 0.11.0 won 15:1	* leelaz 0.11
Mar 09: 20-game match	LZero-545c won 16:4	* leelaz 0.12; see game note 1
```

#### vs zediir's Tygem9d 20x256 (same hardware [1080Ti], noponder)

```
Mar 10: 40-game match	LZero-545c won 23:17	* both 0.12; see game notes 2 and 3
```

## Game notes:

1. KGS results show 15:5 but Leela 0.11.0 won one game by incorrectly marking as dead a group of opponent's stones in seki. LZero-545ca6 did not (or could not) dispute this but this isn't counted against it and the correct game result is included in the final tally (16:4). See [eidogo](http://eidogo.com/#H95CCRrb) | [SGF from KGS archives](http://files.gokgs.com/games/2018/3/10/LeelaZBlow-LeelaZXXXX-3.sgf).
2. Tygem-trained Leela Zero (LeelaZdrTy) made two curious self-ataris ala #936
	1. one game-deciding (it would have won otherwise), see [eidogo](http://eidogo.com/#v35oJhoD) | [SGF from KGS archives](http://files.gokgs.com/games/2018/3/10/LeelaZBlow-LeelaZdrTy-8.sgf)
	2. one is unclear at first glance (0.5-pt game with ko), see [eidogo](http://eidogo.com/#2SLRqRK20) | [SGF from KGS archives](http://files.gokgs.com/games/2018/3/10/LeelaZBlow-LeelaZdrTy-10.sgf)
3. [One game](http://files.gokgs.com/games/2018/3/11/LeelaZBlow-LeelaZdrTy-8.sgf) is unfinished. Tygem-trained 20x256 Leela Zero bot crashed but it shouldn't be counted against it as we're comparing networks (Tygem vs 545c), not engines+networks. An extra game was played to bring total games to 40.

## Games:

* 40-game LZero win against Tygem-trained Leela "Zero" http://gokgs.com/gameArchives.jsp?user=LeelaZdrTy&year=2018&month=3
* 20-game LZero win against Leela http://gokgs.com/gameArchives.jsp?user=LeelaZXXXX&year=2018&month=3
* 16-game Leela win against LZero http://gokgs.com/gameArchives.jsp?user=LeelaZXXXX&year=2018&month=2
* For HiraBot games, see LeelaZBlow's archives http://gokgs.com/gameArchives.jsp?user=LeelaZBlow

## Setup:

* Leela and Leela Zero ran on Win64, GTX 1080 Ti/i7-8700k. GTX1080Ti was slightly overclocked (2050MHz) and with Nvidia driver 391.01 for games vs plain Leela and Tygem-trained Leela.
* All games vs all opponents played with 3min+10x15s time for each player (and --noponder when on same hardware).
#### Leela 0.11.0
```
engine=C:\\...\\Leela0110GTP_OpenCL.exe -g -b 140 --noponder
```
#### LZero-545c
```
engine=C:\\...\\leelaz.exe --noponder -g -b 140 --timemanage on -w C:\\..\\545ca6d6d67169785598ec0185a9210190631916234d11441f75c781194c7114
```
#### LZero-ZdrTygem
```
engine=C:\\...\\leelaz.exe --noponder -g -b 140 --timemanage on -w C:\\...\\TygemLeela.txt
```
#### LZero-545c vs Leela
```
0;XgemmBatched;128;100;128;16; -DKWG=16 -DKWI=8 -DMDIMA=16 -DMDIMC=16 -DMWG=32 -DNDIMB=32 -DNDIMC=8 -DNWG=64 -DSA=1 -DSB=1 -DSTRM=1 -DSTRN=0 -DVWM=2 -DVWN=2;OpenCL: NVIDIA Corporation GeForce GTX 1080 Ti @ 1683MHz
```
#### LZero-545c vs LZ-ZdrTygem
```
0;XgemmBatched;128;100;128;16; -DKWG=16 -DKWI=8 -DMDIMA=16 -DMDIMC=16 -DMWG=32 -DNDIMB=32 -DNDIMC=8 -DNWG=64 -DSA=1 -DSB=1 -DSTRM=1 -DSTRN=0 -DVWM=2 -DVWN=2;OpenCL: NVIDIA Corporation GeForce GTX 1080 Ti @ 1683MHz
0;XgemmBatched;256;100;256;16; -DKWG=32 -DKWI=2 -DMDIMA=16 -DMDIMC=16 -DMWG=64 -DNDIMB=8 -DNDIMC=8 -DNWG=32 -DSA=1 -DSB=1 -DSTRM=0 -DSTRN=0 -DVWM=4 -DVWN=4;OpenCL: NVIDIA Corporation GeForce GTX 1080 Ti @ 1683MHz
```

**Comment by hydrogenpi** [comment]
I recall that zediir's 20x256 is procalimed to be around 3500 cgos ELO. that would be that 
http://www.yss-aya.com/cgos/19x19/cross/LZ-545ca6-t2-nolim.html
should be stronger than
http://www.yss-aya.com/cgos/19x19/cross/LZH256x20-t4-nolim.html
however its not

**Comment by StanTraykov** [comment]
@hydrogenpi That LZ-545ca6-t2-nolim you link to may be much stronger than its current rating, 3377? (note the question mark). It has not played enough games (and only lost twice vs an opponent lower than 3400). It may also be on weaker hardware.

**Comment by MartinDevelopment** [comment]
We should not look at CGOS elo, but instead at the Bayes elo provided. Even then it is still quite inaccurate.

**Comment by gcp** [comment]
Thanks for running these tests. I am happy that Leela Zero has become stronger than Leela 0.11. I would have felt a bit embarrassed if the engine I open sourced turned out to be weaker than my closed source one.

**Comment by roy7** [comment]
Perhaps one day Leela v12 will feature Leela Zero networks for 19x19 and 9x9, but with the ladder playout code/etc that Leela can do which Leela Zero can't. :)

**Comment by d7urban** [comment]
Played a 35 game match between LZ(18827) and Leela11, with both players having 30 minutes on the clock. Results just in: 27-8 to LeelaZero!
Of the eight losses, two were caused by failed ladder reading. The other six were all lost semeai fights.

**Comment by StanTraykov** [comment]
@d7urban what CPU/GPU?

**Comment by d7urban** [comment]
@StanTraykov It's a i7-3770K at 3.5 GHz and a GTX 1060

**Comment by ThomasCabaret** [comment]
Good news!, last network (b7768081) is now 300 elo better than the one used for this test!, days are counted for LZ to reach the CGOS top!.  Does anyone know what are the pegasus/hercules/cronus programs etc.. on the CGOS page top?
