### ISSUE TITLE
Got new selfplay command for network before it was accepted as new network

### ISSUE THREAD

**Issue by bastiaf** [gcp/leela-zero#1017]
The new network 18827fa7 was accepted at 20:44, but I had already received two selfplay commands some minutes before (21:37). Why? And what would happen if the network had been rejected?

At the time the network was added to the best networks table, it had already about 70 selfplay games.

**Comment by alreadydone** [comment]
Isn't 20:44 the "upload date", the time when the matches between 18827fa7 and the previous best began? Isn't 21:37 later than 20:44? When I refreshed the page I actually saw 18827fa7 with only 45 self-play games; maybe you refreshed a bit later than me?

**Comment by bastiaf** [comment]
Ups, I only looked at the minutes, because at 21:37 the match games were still played. ;-) You are totally right.

Nevertheless the network has not passed at the time the selfplay games using it started. Or to be more exact: even after a page refresh no “PASS” was shown. Is the web-page data updated in real-time? Or maybe the network was already accepted according to SPRT?

I don't want to say something is wrong, I am only trying to understand what happens.

**Comment by jkiliani** [comment]
I think what happened is that the net passed and was promoted to best-network. Afterward, loss results came in, making it undecided again, but it already was promoted at the time. This happens very frequently by the way. In the end, it got enough win results to get a pass rating once more.

**Comment by bastiaf** [comment]
That makes sense. :) Thank you.
