### ISSUE TITLE
wrong final score?

### ISSUE THREAD

**Issue by pw31** [gcp/leela-zero#1018]
The following game end position is entirely symmetric, obtained via mirror go with komi 0.5, chinese rules, see https://online-go.com/game/12009038. Obviously, the final score is B+0.5, because B has an extra stone on the board.  However, LZ playing W is super-confident throughout the game with winning probability = 100%. Is this a bug or a feature?

**Comment by alreadydone** [comment]
Mirroring by black is just bad because of komi (7.5, so white won by 6.5).

2018年3月11日 18:17，"PeterWoitke" <notifications@github.com>写道：

**Comment by joseph-ireland** [comment]
leela is trained with komi 7.5, she doesnt know how to play with 0 komi. She thinks she's easily winning by 7 points.

**Comment by pw31** [comment]
@joseph-ireland : Thanx, I see.  So LZ always chooses her moves assuming komi=7.5, no effect whatsoever how actual komi is. Is komi=7.5 also applied in handicap games then, where normally komi=0.5?

**Comment by CamWagner** [comment]
yes it is. so each a 3 stone game is sort of like a 2.5 rank difference since white gets komi back.

**Comment by alreadydone** [comment]
Related: how to properly set up LZ to play handicapped games on a server https://github.com/gcp/leela-zero/issues/955
