### ISSUE TITLE
-m command have bug

### ISSUE THREAD

**Issue by ringworld3702** [gcp/leela-zero#1019]
this is -m 0
https://i.imgur.com/n13uk8Q.png

this is -m 2
https://i.imgur.com/0fCTln5.png

In the first picture, the time is normally shortened.
But in the second picture, time is not shortened although the second stone is over.

**Comment by killerducky** [comment]
Please see leela --help and read the --timemanage description.

**Comment by alreadydone** [comment]
Allowed options of leelaz:
  -h [ --help ]                 Show commandline options.
  -g [ --gtp ]                  Enable GTP mode.
  -t [ --threads ] arg (=2)     Number of threads to use.
  -p [ --playouts ] arg         Weaken engine by limiting the number of
                                playouts.Requires --noponder.
  -v [ --visits ] arg           Weaken engine by limiting the number of visits.
  --timemanage arg (=auto)      [auto|on|off] Enable extra time management
                                features.
                                **auto = off when using -m, otherwise on**
  -b [ --lagbuffer ] arg (=100) Safety margin for time usage in centiseconds.
  -r [ --resignpct ] arg (=-1)  Resign when winrate is less than x%.
                                -1 uses 10% but scales for handicap.
  **-m [ --randomcnt ] arg (=0)   Play more randomly the first x moves.**
  -n [ --noise ]                Enable policy network randomization.
  -s [ --seed ] arg             Random number generation seed.
  -d [ --dumbpass ]             Don't use heuristics for smarter passing.
  -w [ --weights ] arg          File with network weights.
  -l [ --logfile ] arg          File to log input/output to.
  -q [ --quiet ]                Disable all diagnostic output.
  --noponder                    Disable thinking on opponent's time.
  --gpu arg                     ID of the OpenCL device(s) to use (disables
                                autodetection).
  --full-tuner                  Try harder to find an optimal OpenCL tuning.
  --tune-only                   Tune OpenCL only and then exit.

Hopefully no one confuse this with -m option of autogtp.

**Comment by ringworld3702** [comment]
I got it :)

**Comment by alreadydone** [comment]
Just some more clarification: -m is used in self-play games to increase diversity in the first 30 moves. --timemanage is disabled in self-play games because we don't want to stop early when we determine what move to play; we also want to use all 3200 visits to get more accurate visit counts which are used to train the policy head of the neural network.
