### ISSUE TITLE
Long Ladder from selfplay today

### ISSUE THREAD

**Issue by jungsup824** [gcp/leela-zero#1021]
![selfplay ladder](https://user-images.githubusercontent.com/34597284/37285810-2bd4c666-263b-11e8-818e-7c0eee5ae2f9.png)

**Comment by Cabu** [comment]
Nothing to see here :) Leela still get trapped into losing ladders :) We still hope it will get better with time :)

**Comment by Eddh** [comment]
It rarely happens in self play so that's good news. An example that the next net can potentially learn from.

**Comment by Splee99** [comment]
Just saw another one.

http://zero.sjeng.org/view/e56ab7bf24b15ec76df356d61611ccc00dfe13d2d34f46d605e24591f7e0797f?viewer=wgo

**Comment by gcp** [comment]
Note that it might do this in self-play matches even if it understands it's bad (the randomness can cause a worse move to be selected, and once the bot is IN the ladder, it will keep going).
