### ISSUE TITLE
selfplay never stop until no empty space remain

### ISSUE THREAD

**Issue by jungsup824** [gcp/leela-zero#1022]
![continue play](https://user-images.githubusercontent.com/34597284/37287730-7197a240-2640-11e8-9482-98ac40387baf.png)

**Comment by jungsup824** [comment]
Move count is 416 but still continue. It may go until 600

**Comment by zediir** [comment]
20% of selfplay has resignation disabled. That can result in long games. The cut of is at 19*19*2 = 722 moves.

**Comment by jungsup824** [comment]
Resignation 10% is too low. Resignation 30% below might be fine.

**Comment by jkiliani** [comment]
There was a detailed analysis only recently why resignation at 10% is a good choice for the moment. 30% is way too high, leading to a large number of incorrect resignations.

**Comment by lightvector** [comment]
If someone could implement Benson's algorithm + provable area-scoring territory, it might speed things up a little in the resignation-disabled games, leading to a small overall speedup. Unless Leela Zero already naturally plays this "cleanup" stage of the game super-fast?

Basically, use Benson's to compute all the pass-alive groups. Then, consider all maximal connected non-white regions (i.e. maximal connected regions consisting of only black stones or empty spaces) - if all locations in that region are adjacent to a pass-alive white group, then that region is white territory. Similarly for black. If one side has enough provable territory to win, you can terminate the game.

**Comment by TFiFiE** [comment]
That has its own issue: #670
