### ISSUE TITLE
How does learning work when Leela Zero don't know the outcome?

### ISSUE THREAD

**Issue by as0770** [gcp/leela-zero#1024]
Should be easy to find out the result in the end position but Leela Zero reoprts a wrong result:

(;GM[1]FF[4]SZ[19]AP[SmartGo:3.1]CA[UTF-8]
GN[w-leelaz-b-leela-1]
PW[Leela Zero]
PB[Leela]
DT[2018-03-11]
KM[6.5]
RE[B+0.5]
C[Black command: /../usr/games/leela_gtp_opencl --gtp --threads 4 --noponder
White command: /home/alex/Programme/Engines/Go/leelaz --gtp --threads 4 --w /home/alex/Programme/Engines/Go/Leelaz_best-network_2018_03_09 --noponder
Black version: 0.11.0
White version: 0.12
Result[Black\]: B+0.5
Result[White\]: W+43.5
Host: alex-Aspire-VN7-791 (Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz)
Date: March 11, 2018 9:19:00 AM CET]
;B[qp];W[dd];B[pc];W[dp];B[fq];W[eq];B[fp];W[dn];B[nq];W[qe];B[ph];W[od]
;B[pd];W[pe];B[oe];W[oc];B[ob];W[nb];B[pb];W[of];B[ne];W[md];B[me];W[ld]
;B[le];W[kd];B[qg];W[pg];B[oh];W[qh];B[qi];W[rh];B[og];W[pf];B[ri];W[rg]
;B[rd];W[re];B[mb];W[nc];B[na];W[rc];B[rb];W[qd];B[qc];W[sd];B[kb];W[jc]
;B[jb];W[ic];B[ib];W[gc];B[mg];W[mc];B[lb];W[oo];B[op];W[qo];B[po];W[pn]
;B[pp];W[ok];B[mk];W[pi];B[pj];W[oi];B[oj];W[ni];B[nj];W[mi];B[li];W[ng]
;B[mh];W[nh];B[lj];W[mm];B[ql];W[mj];B[nk];W[lk];B[ll];W[kk];B[ji];W[qm]
;B[lm];W[rl];B[jk];W[kl];B[ln];W[jl];B[ik];W[jn];B[im];W[kn];B[lo];W[qk]
;B[pl];W[jj];B[ij];W[kj];B[ki];W[il];B[hl];W[ii];B[in];W[jo];B[ih];W[hi]
;B[hk];W[hh];B[ig];W[io];B[ho];W[hp];B[go];W[hr];B[gr];W[jq];B[ir];W[iq]
;B[hs];W[hq];B[kp];W[kg];B[jp];W[ip];B[kf];W[lh];B[jh];W[jf];B[if];W[jr]
;B[is];W[lf];B[ie];W[ke];B[hd];W[hc];B[ff];W[fh];B[df];W[dh];B[cd];W[cc]
;B[ce];W[dc];B[bc];W[bb];B[dk];W[cg];B[gg];W[fk];B[gh];W[gi];B[fi];W[ei]
;B[fj];W[ej];B[gj];W[gk];B[hj];W[hm];B[hg];W[gm];B[hn];W[fn];B[fo];W[lr]
;B[er];W[dr];B[do];W[eo];B[ep];W[co];B[dq];W[cq];B[cr];W[eq];B[kq];W[dq]
;B[kr];W[js];B[gs];W[es];B[ks];W[jm];B[gq];W[gn];B[ko];W[sb];B[ra];W[fr]
;B[km];W[oa];B[ma];W[qb];B[qa];W[rp];B[ro];W[rn];B[qn];W[gl];B[qo];W[qj]
;B[pk];W[rk];B[pm];W[rm];B[ci];W[ch];B[bi];W[ek];B[be];W[bg];B[ab];W[so]
;B[rq];W[cb];B[ga];W[fa];B[af];W[ag];B[fd];W[fc];B[eg];W[eh];B[sn];W[gd]
;B[ha];W[gb];B[kh];W[mf];B[sp];W[sm];B[ee];W[ed];B[ge];W[de];B[cf];W[hb]
;B[ia];W[fe];B[cm];W[dj];B[cj];W[bn];B[fd];W[id];B[fe];W[he];B[eb];W[fb]
;B[sa];W[bf];B[ae];W[sc];B[je];W[fs];B[gp];W[jg];B[hf];W[hd];B[fg];W[ba]
;B[so];W[aa];B[ac];W[dg];B[kc];W[jd];B[lc];W[dl];B[ec];W[db];B[se];W[sf]
;B[ca];W[ea];B[ds];W[er];B[bk];W[si];B[dm];W[el];B[bm];W[cl];B[bl];W[aj]
;B[em];W[en];B[fm];W[am];B[cn];W[bo];B[ai];W[lg];B[bh];W[ck];B[ak];W[fl]
;B[bj];W[an];B[sj];W[rj];B[sk];W[al];B[ri];W[sl];B[br];W[di];B[bq];W[cs]
;B[bp];W[ap];B[cp];W[ah];B[bs];W[aj];B[aq];W[ar];B[ds];W[do];B[ao];W[cs]
;B[as];W[ap];B[ds];W[da];B[ao];W[cs];B[pa];W[ap];B[ds];W[qf];B[ao];W[cs]
;B[em];W[ap];B[ds];W[nf];B[ao];W[cs];B[sj];W[ap];B[ds];W[nd];B[ao];W[cs]
;B[sh];W[ap];B[ds];W[qi];B[ao];W[cs];B[dm];W[ap];B[ds];W[si];B[ao];W[cs]
;B[cm];W[ap];B[ds];W[sg];B[ao];W[cs];B[ap];W[cn];B[ds];W[sk];B[fm];W[cs]
;B[bl];W[bm];B[ds];W[on];B[mn];W[cs];B[bj];W[ar];B[bk];W[ak];B[bi];W[ai]
;B[ci];W[bh];B[em];W[cj];B[dm];W[kf];B[fm];W[cm];B[em];W[dm];B[bp];W[ap]
;B[bq];W[cp];B[br];W[bs];B[aq];W[cr];B[aq];W[fm];B[bp];W[bq];B[ef];W[];B[]
TB[ga][ha][ia][ja][ka][la][ma][na][oa][pa][qa][ra][sa][ab][ib][jb][kb][lb][mb][ob][pb][qb][rb][ac][bc][kc][lc][pc][qc][ad][bd][cd][fd][pd][ae][be][ce][ee][fe][ge][ie][je][af][cf][df][ef][ff][gf][hf][if][eg][fg][gg][hg][ig][gh][hh][ih][jh][kh][fi][gi][hi][ii][ji][ki][li][fj][gj][hj][ij][jj][kj][lj][nj][oj][pj][hk][ik][jk][kk][lk][mk][nk][ok][pk][hl][il][jl][kl][ll][ml][nl][ol][pl][ql][im][jm][km][lm][mm][nm][om][pm][hn][in][jn][kn][ln][mn][nn][on][pn][qn][sn][fo][go][ho][io][jo][ko][lo][mo][no][oo][po][qo][ro][so][ep][fp][gp][hp][ip][jp][kp][lp][mp][np][op][pp][qp][rp][sp][fq][gq][hq][iq][jq][kq][lq][mq][nq][oq][pq][qq][rq][sq][gr][hr][ir][jr][kr][lr][mr][nr][or][pr][qr][rr][sr][gs][hs][is][js][ks][ls][ms][ns][os][ps][qs][rs][ss]
TW[aa][ba][ca][da][ea][fa][bb][cb][db][eb][fb][gb][hb][nb][sb][cc][dc][ec][fc][gc][hc][ic][jc][mc][nc][oc][rc][sc][dd][ed][gd][hd][id][jd][kd][ld][md][nd][od][qd][rd][sd][de][he][ke][le][me][ne][oe][pe][qe][re][se][bf][jf][kf][lf][mf][nf][of][pf][qf][rf][sf][ag][bg][cg][dg][jg][kg][lg][mg][ng][og][pg][qg][rg][sg][ah][bh][ch][dh][eh][fh][lh][mh][nh][oh][ph][qh][rh][sh][ai][bi][ci][di][ei][mi][ni][oi][pi][qi][ri][si][aj][bj][cj][dj][ej][mj][qj][rj][sj][ak][bk][ck][dk][ek][fk][gk][qk][rk][sk][al][bl][cl][dl][el][fl][gl][rl][sl][am][bm][cm][dm][em][fm][gm][hm][qm][rm][sm][an][bn][cn][dn][en][fn][gn][rn][ao][bo][co][do][eo][ap][bp][cp][dp][aq][bq][cq][dq][eq][ar][br][cr][dr][er][fr][as][bs][cs][ds][es][fs]
DB[ad][bd][hh][gi][hi][ii][jj][kj][kk][lk][il][jl][kl][ml][nl][ol][jm][nm][om][jn][kn][nn][io][jo][mo][no][hp][ip][lp][mp][np][rp][hq][iq][jq][mq][oq][pq][qq][sq][hr][jr][nr][or][pr][qr][rr][js][ns][os][ps][qs][rs]
V[0.5])

**Comment by MaxMaki** [comment]
I'm not 100% sure, but after installing smartgo and opening it up it seems that Leela did not clear the board.
This, as well as the komi being set incorrectly i think.

If i've understood correctly Leela plays Tromp-Taylor, which means that any stone on the board is alive, they need to be removed. 
So you had the two bots playing under two different rulesets and therefor they don't agree on the result.

Secondly, if i've understood correctly LeelaZero only plays komi 7.5, you have it set to 6.5, which will again cause incorrect wins/losses.

**Comment by as0770** [comment]
Are you sure about that? If I ask list_commands Leela Zero answers with komi among others.

**Comment by MartinDevelopment** [comment]
LZ is trained on 7.5 komi so it will only play like it has that.

**Comment by as0770** [comment]
thx
