### ISSUE TITLE
Failed to resign

### ISSUE THREAD

**Issue by roy7** [gcp/leela-zero#1027]
Bot was running without -r, so it should be 10% by default scaled for handicap. However in this game:

https://online-go.com/game/12025174

Move 432 and on, there are some moves with win rates of < 10% that didn't resign. No handicap was involved in this game. 

Log file: http://termbin.com/cfsq

Oh wait I see. It's because "passing wins". (It doesn't really, it only wins under TT scoring.) So I guess not a bug?

**Comment by bood** [comment]
I think you forgot to use the `-d` to disable the `smart passing`, which is not smart at all :-)
