### ISSUE TITLE
How to limit a number of played game?

### ISSUE THREAD

**Issue by ringworld3702** [gcp/leela-zero#1029]
https://i.imgur.com/Y4OPxYb.png

Can I have CGOS.bat automatically shut down after AI achieve 100 games?

Below is currently my setting
tclkitsh.exe cgosGtp.tcl -c config.txt -k

**Comment by WhiteHalmos** [comment]
You can parse the webpage like here: https://github.com/WhiteHalmos/leela-zero/blob/scripts/scripts/cgos/parse.py#L9

**Comment by ringworld3702** [comment]
Thank you
