### ISSUE TITLE
Leela-Zero requires OpenCL 1.2.(?)

### ISSUE THREAD

**Issue by fishcu** [gcp/leela-zero#103]
The Readme says "An OpenCL capable device, preferably a very, very fast GPU, with drivers (OpenCL 1.2 support should be enough, even OpenCL 1.1 might work)".
From the reddit thread [here](https://www.reddit.com/r/baduk/comments/7dg219/psa_you_can_help_training_leelazero_without_a/), there have been two different people that have reported OpenCL version 1.1. running on their system, using the software "GPU Caps Viewer". For both of them, leelaz crashes. That would indicate that OpenCL 1.2. is required. I don't know anything about OpenCL, but I guess if these people with very old GPUs want to help, it is best if they wait for the CPU version? Thank you for the support.

**Comment by gcp** [comment]
Which OpenCL version is required depends on which OpenCL features the program uses, not whether *some* driver implementation that happens to only support OpenCL 1.1 (and thus - realistically - is going to be rather old, buggy, and not updated) works or not.

The configuration for Leela is set so only OpenCL 1.1 features can be used, or 1.2 features that can be emulated on top of 1.1, IIRC: https://github.com/gcp/leela-zero/blob/12faa8fde5315686344c2cd4c973eb18865bfb6e/src/OpenCL.h#L24
