### ISSUE TITLE
Anybody with 2 or more AMD GPUs?

### ISSUE THREAD

**Issue by ihavnoid** [gcp/leela-zero#1038]
In case there are people not looking at pull requests, we need somebody with two or more AMD GPUs to test the multithread scalability.  Any help?

https://github.com/gcp/leela-zero/pull/1026

**Comment by pickcherry** [comment]
I have a MacPro with 2 AMD FirePro D700

**Comment by ihavnoid** [comment]
@pickcherry - can you compile and test how the multi-GPU (#1026) branch works on your machine?  e.g., does anything unusual or funny when both GPUs are used to play a game.

**Comment by pickcherry** [comment]
will try. I am using Windows system on my Mac. The performance of AMD FirePro D700 for training seems not that good.

**Comment by ihavnoid** [comment]
Related PR is closed, so this issue should be closed, too. Perhaps.
