### ISSUE TITLE
Does we support Multi-GPU training with tensorflow now?

### ISSUE THREAD

**Issue by pangafu** [gcp/leela-zero#1040]
Seem only 1 gpu working when training, how to config to use multi-gpu for train?

**Comment by WhiteHalmos** [comment]
@pangafu How do you configure your training? Mine keeps using only CPU...

**Comment by pangafu** [comment]
Does your other tensorflow application can use gpu?

**Comment by bjiyxo** [comment]
@WhiteHalmos Did you pip tensorflow-gpu? The tensorflow in requirements will only use CPU.

**Comment by pheasant75** [comment]
FYI, my computer has two titan xp cards and I use the command "./autogtp -p 2 -u 0 -u 1"
Which means I ran 2 processes per GPU on both gpu 0 and gpu 1.  Total of 4 training games simultaneously.

This is on Linux but you can try these command switches on windows.

**Comment by Alderi-Tokori** [comment]
@pheasant75 They're talking about the actual net training though, not self-play generation. And to answer your question @pangafu , no, multi-gpu is not yet supported in the tensorflow training code.

**Comment by WhiteHalmos** [comment]
Thanks @bjiyxo! That was my problem, I just did `pip install -r requirements.txt`.

**Comment by gcp** [comment]
The answer is no, there's no support for multi-GPU training.
