### ISSUE TITLE
The size of the raw data is not proportional to the amount of games.

### ISSUE THREAD

**Issue by bjiyxo** [gcp/leela-zero#1042]
#167
I'm currently training 20b256f. However, I found some raw data is unusually small and that will impact on the training stability.

| Num | Hash | Games | Size of Raw Data |
| --- | --- | --- | --- |
82 | 0fb6 | 133198 | 8.4GB
83 | af9c | 176753 | 11.3GB
89 | 53f4 | 160925 | *4.0GB
91 | b3b0 | 136777 | 7.5GB
100 | 545c | 164559 | *3.8GB

Some raw data (with *) looked somehow small. Is there any reason?

**Comment by bjiyxo** [comment]
Another interesting thing.
The size of raw data of 10b games (~334k games before 3/9) is ~11.8GB, which is close to af9ce63c (~177k games).

**Comment by gcp** [comment]
These might be incomplete uploads (i.e. uploads that were done before all games were collected). I'll redo them. I believe a missing one was pointed out in #167 too.

**Comment by Marcin1960** [comment]
What  are these 2 matches? "2095 match games in past 24 hours, 2 in past hour"

Why not just zero?

**Comment by roy7** [comment]
Some extremely slow clients finally turned in match results.

**Comment by Marcin1960** [comment]
8e3bd net 20x128 is fast! More playouts than 10x192

**Comment by bjiyxo** [comment]
@gcp 
It looks like the size of 10b raw data is smaller than 6b. For example, the amount of 0fb68ccf(82) & 193437be(104) games is 133k & 142k, but the size of raw data is 8.4GB & 5.1GB. However, the amount of games between 193437be : 0f6a8c5f : d996fdc3 (and they are uploaded a day ago) is about 4:2:1, and the size of raw data is 5.1GB : 2.6GB : 1.1GB, which looks quite reasonable. Do you change any settings about the raw data?

**Comment by alreadydone** [comment]
@bijyxo I think this has to do with the change from playouts to visits. With 3200 visits, all search probabilities in training data are multiples of 1/3199, so gzip compression is more effective. The resign threshold was also raised, resulting in shorter games.

**Comment by bjiyxo** [comment]
@alreadydone You got the point. That makes sense. I'll close the issue.
