### ISSUE TITLE
Two questions about leelaz when using -q command and -r command

### ISSUE THREAD

**Issue by pcengine** [gcp/leela-zero#1047]
When I run leelaz in sabaki with -q command, it disables all the diagnostic info. Is there a way to ask  it to only show some part of the info such as winrate % after each move, but not showing other diagnostic  info such as n/s, playouts, and possible variations? I ask this because when I play against Leela, I'd like to know the winrate changes immediately after each move, but don't want to see the variations leelaz provides (it would be more fun if I can think of some following moves on my own, rather than reading the variations leelaz provides. It is really hard not to see it when it shows on GTP console). 

Another question is related to -r command. When I play handicap games against leela, It usually resigns at around move 90 or 92 even I set r 1.  I have also tried -r -1 but it still resign at around move 90. Can we force leela to keep playing to the end, even if its winrate is lower than 1%? Is there a "never resign" command available? If no, is it difficult to add that function in the future?  Sorry if I have asked some dumb questions.

**Comment by OmnipotentEntity** [comment]
To answer your first question, not at this time.

To answer your second, -r 0

**Comment by pcengine** [comment]
> To  answer your first question, not at this time. To answer your second, -r 0
Thank you very much.

**Comment by pcengine** [comment]
Thank you very much.

2018年3月18日 上午5:54，"OmnipotentEntity" <notifications@github.com>寫道：
