### ISSUE TITLE
Double pass doesn't stop the net from exploring deeper?

### ISSUE THREAD

**Issue by Alderi-Tokori** [gcp/leela-zero#1050]
I skimmed through the log file from the recent game against Haylee (https://raw.githubusercontent.com/CamWagner/files/master/log.txt), and I saw something peculiar:

```raw
pass ->      42 (V:  0.04%) (N:  0.17%) PV: pass Q14 R13 K2 L2 H2 K1
```

When the net explores pass, it seems it continues exploring deeper after the opponent's pass in response. You can see this happening often in the log file. But it should stop exploring after two passes.

**Comment by TFiFiE** [comment]
There is no double pass there. The child move is repeated in the PV.

**Comment by Alderi-Tokori** [comment]
Aaaaah right, my bad :)
