### ISSUE TITLE
-t option: documentation or better defaults or tuning?

### ISSUE THREAD

**Issue by StanTraykov** [gcp/leela-zero#1055]
We can probably expect from enthusiasts setting up pro games or running bot matches on $50K rigs to experiment around and find the best Leela Zero settings for their scenario. But I think normal users without in-depth knowledge (many of whom contribute cycles, too) also deserve to enjoy LZ at (or near) her best on their standard PCs with 1-2 GPUs.

The only(?) two options that can make LZ stronger are ``--timemanage`` and ``--threads``/``-t``. The former defaults to ``auto`` which I assume does the job. The latter defaults to 2 and there is no documentation to be found on what might work best.

I did some tests on my 1xGPU home PC: ``netbench 10000`` and ``netbench 50000`` (intermixed) for 1-12 threads (intermixed), for a total of 6 runs (6x12x2=144 netbenches, see results & PC config below). Surprisingly, ``-t 12`` comes out on top. The change from ``-t 1`` to ``-t 2`` (the default) is decent (+>20%) but the change from ``-t 2`` to ``-t 12`` is dramatic: +~65%.

Now, I know there's more going on in LZ than what ``netbench`` tests and that not all of it is parallelizable, so I'm wondering how good an estimate of real-world strength this benchmark truly is—do we know?

If it's a good one (at least for the usual case, a typical PC with a modern GPU or two), then perhaps LZ should offer to tune itself? If it's not that useful, maybe at least some documentation with suggestions for ``-t`` should be provided (short of adding another benchmark that better approximates real-world strength)?

If some real-world testing is required, maybe it could be coordinated somewhere here? (I started a test for ``-t 2`` vs. ``-t 12`` on my system and can also do others.) Or maybe the answer is already known and the difference between having ``-t`` at 2 vs something closer to the max (=number of virtual cores) is not as dramatic as it seems? In that case, @gcp, could we please include some minimal documentation somewhere (FAQ, README, in --help).

#### ``netbench`` results (minimum, median, maximum) of 6 intermixed runs (i7-8700k/1x1080Ti/Win10).

<details>
<summary>netbench.bat</summary>

```
echo off
FOR /L %%r in (1,1,6) DO (
	echo ==== run %%r ====
	FOR %%t in (1 12 2 11 3 10 4 9 5 8 6 7) DO (
		echo %%t threads:
		(echo netbench 10000 & echo netbench 50000) | leelaz.exe -t %%t -g -w 80fbeef.txt 2>&1 | findstr "evaluations")
	)
)
```
</details>

![net10K chart](https://raw.githubusercontent.com/StanTraykov/S/master/img/net10K.png)
![net50K chart](https://raw.githubusercontent.com/StanTraykov/S/master/img/net50K.png)

**Comment by OmnipotentEntity** [comment]
It's interesting that your GPU was able to have a little bit left even with that many threads.  However, you should keep in mind that even though you're visiting more nodes with 12 threads, due to the way that multithreading is handled to reduce contention and eliminate duplicate work you might not be exploring the best parts of the tree as much, and as a result your 12 thread version might be weaker than your 8 thread version.  And to figure out *that* requires a lot of testing.  There's not really a single best answer.

**Comment by StanTraykov** [comment]
What kind of testing would be best? E.g. take 2 threads (current default) as a base and do some time-limited no-pondering matches vs. 4, 8, and max threads on the same system?

I could do this for my setup, maybe someone with something different could do as well? If the difference between the optimal and the current default (2) turns out to be small(ish), then the whole question is moot. But if not, it seems it'd be useful to have something as a guide, esp. for the larger community (think go players wanting to play, not computer people willing to tinker around, whether they understand the methods used in the program or not).

**Comment by OmnipotentEntity** [comment]
Yeah, you'd need to perform a match series and see which parameters perform the best.  Unfortunately, they'll be very close to each other, so you'll need a lot of matches to see much of a difference, and because these will need to be time limited matches they'll take a while.  Finally, there's no reason to think that the setting that works best for 10 seconds of think time also works best for 30.

**Comment by thynson** [comment]
Short answer: When leelaz played with fixed playout or visit, i.e. -p 1600 or -v 3200, use -t1. In other situation use the default 2 thread is best for most machine, unless you have an ultimate GPU setting, i.e. 4x1080Ti.

As @OmnipotentEntity said above, multi-threading tree search use virtual loss technology to reduce contention, resulting that the best branch get less visited than expected according to UCT formular. In other world, more threading lead to less optimal allocation of comptuational resource. 

However, if we only use -t 1, GPU will be idle when CPU is working, or vice-versa, which is not optimal in in timed game. So leelaz default to -t 2, which is a balanced point that won't let GPU idle too much while minimalize the side effect of virtual loss.

For people who has more than one GPU, I suggest to use -t N+1 or N+2, it may not be the most optimal setting but should perform very well.

**Comment by pcengine** [comment]
@thynson   Some questions:  You said that use 2 threads should be best for most machine.  Is this still mostly true for different time settings? How many threads do you suggest to use if I want leelaz to play 15 or 20 seconds per move?  I ask this because @OmnipotentEntity  mentioned that : 
> there's no reason to think that the setting that works best for 10 seconds of think time also works best for 30.

**Comment by OmnipotentEntity** [comment]
For background, the reason I said that was because of the way the tree is expanded.  It occurred to me that it might be the case that having more threads is more damaging at the beginning than later on.

Threading interferes with the tree search by forcing threads to explore different parts, but this might matter less when the tree is more fully explored.

In any case, the approach I've taken is to use just enough threads to hit 100% utilization on my GPUs for timed games, and -t 1 for playout limited games.

**Comment by pcengine** [comment]
@OmnipotentEntity  Thank you very much for your kindly explanation, but there is still one thing I don;t quite get it. How do we know or check whether the tree is fully explored? To see the playout #? or the visit #?  Also,  I'm using a 12 threads cpu and a 1080Ti GPU, even when I set -t 12, the GPU usage is still only around 75% - 80%. In that case, if I want leelaz to play stronger, should I set it to -t 2 or -t 12?

**Comment by OmnipotentEntity** [comment]
The tree is never fully explored until every end state from this point is visited.  I said "more fully explored." ;)

If you want to test whether or not Leela Zero is stronger in any particular configuration I would recommend doing a series of test matches.

**Comment by thynson** [comment]
@pcengine When you can't increase the utilization of your GPU any more, less thread is better. Some guys (in the Chinese Leela Zero User Group on Tencnt QQ) has made the test. Remember that GPU is always the bottleneck of leelaz, unless this is not your case, too much thread is meaningless.

**Comment by pcengine** [comment]
@OmnipotentEntity  Oh, yes, I misread that. Thanks again. 
@thynson OK, thanks a lot. I have observed my GPU usage, and I found that if I use 2 threads, the GPU usage is about 25% to 30%, but if I use all 12 threads, the GPU usage is around 75% to 80%. So in my case, maybe 12 threads is better ( judged by using more GPU) than 2 threads?

**Comment by thynson** [comment]
Yes, -t 12 is better than -t 2 for your case. Through I guess -t 6 might already be enough for 1080 Ti.

**Comment by StanTraykov** [comment]
As mentioned above, I'm currently doing some tests on a fairly standard gaming rig: 6-core i7-8700k CPU & 1x1080Ti GPU. The first test--2 vs 12 threads--is almost done (90 of 100 games) and the preliminary results (54:36 in favor of 12 vs 2) indicate a significant difference. That's a 60% win rate/70 ELO difference. You could also say that it's approx. "2 promotions worth" of strength increase but in fact it's not so clear whether ELO differences with self-play really tell the truth here. That is why one of my next tests will be vs. another bot (perhaps AQ), to see if the strength difference translates. Before that, I will test 6 threads (and maybe others) as I have a feeling that it might be even stronger than 12 on my system.

**Comment by StanTraykov** [comment]
I'm continuing my tests and will post more detailed results later but for the benefit of those running bots right now: It appears that **GPU usage is NOT a good indicator of when to stop adding threads** (at least as displayed in windows task manager).

First, the 100 game test results (12 vs 2 threads):
<details>
<summary><strong>12 threads: wins vs. 2 threads 60:40 => ELO diff 70, winrate 60%</strong> <em>(click me)</em></summary>

```
Black wins: 46
White wins: 54
LZ-12T: 60
LZ-12T wins as W: 31
LZ-12T totl as W: 48
LZ-12T wins as B: 29
LZ-12T totl as B: 52
LZ-02T: 40
LZ-02T wins as W: 23
LZ-02T totl as W: 52
LZ-02T wins as B: 17
LZ-02T totl as B: 48
```
**Setup:** i7-8700k/1x1080Ti/Win10 noponder -t12 vs -t2
**Matches:** https://www.gokgs.com/gameArchives.jsp?user=LeelaZBl12
<details>
<summary><strong>Counting script</strong> <em>(click me)</em></summary>

```
var nodes = window.document.getElementsByClassName('grid')[0].childNodes
var results = {}
results["Black wins"] = 0;
results["White wins"] = 0;
for(childNodeIndex in nodes) {
  var tds = nodes[childNodeIndex].childNodes;
  if(nodes[childNodeIndex].localName === "tr" && tds[1].localName === "td") {
    var white = tds[1].innerText.substr(0,tds[1].innerText.indexOf("[") - 1);
    var black = tds[2].innerText.substr(0,tds[2].innerText.indexOf("[") - 1);
    if(results[black] === undefined) {      
      results[black] = 0;
      results[black + " wins as W"]	= 0;
      results[black + " totl as W"] = 0;
      results[black + " wins as B"] = 0;
      results[black + " totl as B"] = 0;
    }
    if(results[white] === undefined) {            
      results[white] = 0;
      results[white + " wins as W"] = 0;
      results[white + " totl as W"] = 0;
      results[white + " wins as B"] = 0;
      results[white + " totl as B"] = 0;
    }
    results[white + " totl as W"]++;
    results[black + " totl as B"]++;
    var result = tds[6].innerText[0]
    if(result == "B") {
      results[black]++;
      results["Black wins"]++;
      results[black + " wins as B"]++;
    }
    if(result == "W") {
      results[white]++;
      results[white + " wins as W"]++;
      results["White wins"]++;
    }
  }
}
for(resultIndex in results) {  
  console.log(resultIndex + ': ' + results[resultIndex])
}
```
</details>
</details>

Now, the surprising part: The 2-threaded version ran at 49-51% (peak) GPU usage, while the stronger, 12-threaded version stayed below 20-22%!. This seemed fishy at first sight, so I made task manager display the command line (incl. the ``-t`` parameter) and thread count, to make sure I'm not mixing something up. The following are typical values (with ``-t`` parameter & GPU usage for the currently working ``leelaz`` instance highlighted in red; total threads can also be seen: 33 and 23):

<details>
<summary><strong>Screenshots 1, 2</strong> <em>(click me)</em></summary>

![lz-working](https://raw.githubusercontent.com/StanTraykov/S/master/img/lz-working.png)

</details>

The detailed GPU analysis in task manager (under performance) shows how this comes to be. You can select & monitor different engines there. The only two things that ``leelaz`` moves are ``Compute_0`` and ``Copy``. Both the 12-thread and 2-thread version bring and hold ``Compute_0`` at near 100% but this is NOT calculated into the GPU usage summary displayed by the task manager in all the usual places (processes, details, left side of performance tab). Only the copy engine is calculated in the total. This means that when running Leela Zero, *GPU usage* equals *copy engine usage*, as can be seen here:
<details>
<summary><strong>Screenshot 3</strong> <em>(click me)</em></summary>

![lz-working](https://raw.githubusercontent.com/StanTraykov/S/master/img/lz-gpucopy.png)

</details>

From the screenshot above, you can also see that
* ``Compute_0`` is near 100% for both 12-threaded and 2-threaded LZs (rhythmic Compute_0 chart)
* ``Copy`` engine usage is 50%ish for 2-threaded Leela Zero and 20%ish for 12-threaded Leela Zero.

**Comment by StanTraykov** [comment]
t12 and t6 tests (vs the default t2) done so far. Normalized winrate = (winrate as W + winrate as B) / 2. Strange spike of white win rate with 12 threads, will repeat.
```
	win	as W	tot W	as B	tot B	WR	WR as W	WR as B	normalized
t12	60	31	48	29	52	60.00%	64.58%	55.77%	60.18%
t6	58	24	41	34	59	58.00%	58.54%	57.63%	58.08%
```

**Comment by StanTraykov** [comment]
Just a final update on my tests before I close this issue. It will take some time to confirm these results. Once I have better confidence, I will make a separate post/issue with overall stats.

I made three 100-game KGS runs at 3min main+15s/move (eff. 13.6s/move with 1.4s buffer) and some local runs using a [GTP arbiter](https://github.com/StanTraykov/dumbarb) at 5s/move (eff. 4s/move with default 1s buffer).

So far, I can make these conclusions:

* It's *certain* that GPU usage (as reported in windows task manager) is **not** a good indicator of when to stop adding threads. In Leela Zero's case, it only takes copy engine usage into account (and seems to peak at ~50% for 2 threads, at least for my two consumer Nvidia units, GTX670 and GTX1080Ti, it may be more useful with other configurations/card vendors).
* It's also *pretty certain* that ``Compute_0`` usage (as reported under performance/GPU in task manager) is **not** a good indicator of when to stop adding threads. It reached 100%ish at 1 threads on the slow GTX670 and at 2 threads on the very fast 1080Ti, yet it's clear that adding more threads helps (not that clear for GTX670 in the table, but I'm yet to compare 1 thread, which already brings ``Compute_0`` to 100%, vs 2 and 3).
* A higher thread count than the default (2) will *very likely* result in a significant strength increase, esp. on better graphics cards, and even on single-GPU systems.

60% WR is 70 ELO or around 2 "promotions worth" of strength increase. I will make further tests to see if strength increase is really monotonous for 2-12 threads on 1080Ti. I will also test against another program to see how this strength difference translates from the self-play tests. Once I have these results, I will make a suggestion to either add something to README/FAQ and/or change the default.

Results so far (vs default 2 threads):
```
       | - total games -  |       --- wins ---      |       ----- win rate -----
run/   |B wins      total |     as W      as B      |      WR           WR as B
threads|     W wins       |wins    totAsW    totAsB |          WR as W        normalized
                              *** i7-8700k-1080Ti ***
--------------------------|-------------------------|-----------------------------------
KGS 12 |    46   54   100 |  60   31   48   29   52 |  60.00%   64.58%   55.77%   60.18%
KGS  6 |    51   49   100 |  58   24   41   34   59 |  58.00%   58.54%   57.63%   58.08%
KGS  1 |    44   56   100 |  37   21   49   16   51 |  37.00%   42.86%   31.37%   37.11%
ARB 12 |    24   38   62* |  39   23   31   16   31 |  62.90%   74.19%   51.61%   62.90%
                              *** i7-3700k-GTX670 ***
--------------------------|-------------------------|-----------------------------------
ARB  8 |    45   55   100 |  47   26   50   21   50 |  47.00%   52.00%   42.00%   47.00%
ARB  4 |    77   73   150 |  82   40   75   42   75 |  54.67%   53.33%   56.00%   54.67%

* still running
```
