### ISSUE TITLE
Export weights to JS

### ISSUE THREAD

**Issue by d180cf** [gcp/leela-zero#106]
It would be useful to feed the learned NN weights to a JS program, implement inference and use the raw NN output, without MCTS, to predict the move. In the AlphaGo paper it was mentioned that strenght of such bot is 3000 elo.

Evaluating the NN should be possible in JS. If we are talking about 40 residual blocks with two convolutions 3×3 19×19 256×256 per block, inference takes 40×2×19×19×3×3×256×256=80×400×10×64000=20 billions multiply-add operations. Then divide by 4 (the number of CPUs) and by 100-900 MFlops (JS perf on Core i7 and Xeon) and we get a reasonable number: 30 seconds per move.

**Comment by cheshirecats** [comment]
@d180cf You might be interested in https://github.com/BlinkDL/BlinkDL ... It's my project for running policy network in JS. Just dump the weights to a binary file and you are ready to go.

**Comment by gcp** [comment]
You can send a pull request to add a section like "Useful links" or "related projects" to the README, with your repos in it.

I closed the issue here because it's not related to Leela-Zero development in itself.

**Comment by cheshirecats** [comment]
@gcp Thanks. I've created a pull request.
