### ISSUE TITLE
Leela Zero loses very badly on superhigh playouts even on next branch with the bugfix. 

### ISSUE THREAD

**Issue by hydrogenpi** [gcp/leela-zero#1062]
https://archive.org/details/AQLZMillion

Leela Zero loses to AQ very badly even when given 1 million playouts per move and AQ is only given 120 seconds time per move. This is after the next branch was compiled and the latest BLAS used. And includes the multigpu merge changes. 

See logs attached. 
[log_AQ.txt](https://github.com/gcp/leela-zero/files/1829364/log_AQ.txt)
[log_LZ.txt](https://github.com/gcp/leela-zero/files/1829366/log_LZ.txt)
[gogame.sgf.txt](https://github.com/gcp/leela-zero/files/1829370/gogame.sgf.txt)

**Comment by Eddh** [comment]
```
Q17 ->  327059 (V: 53.88%) (N:  7.10%) PV: Q17 R3
  C4 ->  298556 (V: 53.88%) (N:  6.76%) PV: C4 P16
  Q3 ->  138982 (V: 53.83%) (N: 11.15%) PV: Q3 R4
  R4 ->  125649 (V: 53.82%) (N: 11.21%) PV: R4 C4 Q17 P3 Q6 R15 O16 F4 C17 D17 C16 C14 C15 D15 B14 C18 B18 B13 D18 D13 E18 R12 M3 J3 O4 R3 S3 S2 Q3
  Q4 ->   42469 (V: 53.46%) (N: 22.50%) PV: Q4 Q17 C4 R3 R4 Q3 P3 P2 O2 O3 P4 N2 Q2 O1 R2 E3 R15
  D3 ->   36063 (V: 53.74%) (N:  6.73%) PV: D3 Q3 Q17 C5 F4 R15 O16 Q6 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 C8
 R16 ->   26936 (V: 53.68%) (N:  6.92%) PV: R16 Q3 C4 E3 D6 P17 Q14 Q6 C17 C16 D17 E17 E18 F18 F17 E16 G18 D18 F19 C18 R8 C8 Q4 P4 R4 R3 S3 O3 S5 H4 D3 E4 C7 D8 F6
 Q16 ->   25101 (V: 53.53%) (N: 11.29%) PV: Q16 R4 C4 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 E3 D6 P4 C17 C16 D17 E17 E18 F18 F17 E16 G18 D18 F19 C18
  D4 ->   19675 (V: 53.44%) (N: 11.00%) PV: D4 Q3 Q17 C3 D3 C4 C5 B5 B6 C6 D5 B7 B4 A6 B3 R15 O16 Q6 C17 C16 D17 E17 E18 F18 F17 E16 G18 D18 F19 C18 F16 R12 R16 Q15 O14 M17 N17
 C17 ->     611 (V: 53.00%) (N:  0.67%) PV: C17 D17 C16 C14 C15 D15 B14 C18 B18 B13 D14 C13 D18 E18 C19 E14
```
Looks like this bug https://github.com/gcp/leela-zero/issues/956

**Comment by OmnipotentEntity** [comment]
@Eddh He had asked about this on /r/cbaduk, and I had referenced that bug, which had been labeled as fixed.  He's posting here because he's on the next branch now and still having difficulties.  I agree it looks like the same thing.  Has the bug been fixed?

**Comment by gcp** [comment]
>This is after the next branch... includes the multigpu merge changes.

So it's not the next branch.

**Comment by Eddh** [comment]
It is supposed to be fixed by this https://github.com/gcp/leela-zero/pull/963 on next

**Comment by barrtgt** [comment]
For self-play, using 100K playouts will reach the 100M node cap after a few dozen moves.

**Comment by gcp** [comment]
Real Leela Zero does not and cannot behave like that log shows. The fix done for #956 will cause an abort after about 280k-300k searched nodes because the tree size limit is hit.

This is how the current "next" branch behaves with the exact same commands (but a different network). Note that it will not reach 1 million playouts - it cannot do so without increasing the maximum memory usage.

The build that this person is using is broken and has the fix for #956 removed.

```
Playouts: 294376, Win: 52.31%, PV: Q4 R3 Q3 R4 R5 S5 S6 R6 Q5 S7 S4 T6 S3 R16 D4 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 O16 C17 C16 D17 E17 E18 F18 F17 E16 G18 D18 F19 C18 R10 R13 P7 Q9 Q10 P9 P10 O9 O10 N9

  Q4 ->  113309 (V: 52.36%) (N: 22.40%) PV: Q4 R3 Q3 R4 R5 S5 S6 R6 Q5 S7 S4 T6 S3 R16 D4 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 O16 C17 C16 D17 E17 E18 F18 F17 E16 G18 D18 F19 C18 R10 R13 P7 Q9 Q10 P9 P10 O9 O10 N9
 Q16 ->   50629 (V: 52.35%) (N: 11.73%) PV: Q16 R4 D4 R17 R16 Q17 P17 P18 O18 O17 P16 N18 Q18 O19 R18 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 O4 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 G5 J4 D14 C10 R9 C12 N15 L16 R6
  D4 ->   45233 (V: 52.34%) (N: 11.26%) PV: D4 Q3 Q16 C3 D3 C4 C5 B5 B6 C6 D5 B7 B4 A6 B3 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 Q6 C17 C16 D17 E17 E18 F18 F17 E16 G18 D18 F19 C18 P13 Q11 F16 K17 L3 H17 J16
  Q3 ->   19802 (V: 52.22%) (N: 10.59%) PV: Q3 Q17 D4 R5 O4 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 Q14 C17 C16 D17 E17 E18 F18 F17 E16 G18 D18 F19 C18 R12 R9 Q16 R16 R15 Q15 P16 R17 R14 Q13 Q12 O15 O16
  R4 ->   18805 (V: 52.21%) (N: 10.20%) PV: R4 C4 Q16 P3 Q6 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 F4 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 H3 L3 D4 D3 E3 E4 D5 C3 F3 G4 H4 E6 J2
 Q17 ->   11867 (V: 52.18%) (N:  7.45%) PV: Q17 R4 D4 R15 O16 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 O4 C17 C16 D17 E17 E18 F18 F17 E16 G18 D18 F19 C18 R12 R10 Q14 R17 R18 S18 R16
 R16 ->   11607 (V: 52.19%) (N:  6.80%) PV: R16 R4 D4 P17 Q14 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 O4 C17 C16 D17 E17 E18 F18 F17 E16 G18 D18 F19 C18 M3 N3 M4 O6 H3 F4 H5 H2 J3 F6 G7 R12
  D3 ->   11471 (V: 52.20%) (N:  6.56%) PV: D3 Q3 Q16 C5 F4 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 Q6 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 R8 R7 Q8 O6 R12 Q14 P12 S12 R11 H3 P14
  C4 ->   11193 (V: 52.18%) (N:  6.91%) PV: C4 Q3 Q16 E3 D6 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 Q6 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 H3 K3 F4 C3 B3 B2 D3
 C17 ->    1042 (V: 51.93%) (N:  1.25%) PV: C17 C16 D17 E17 E18 F18 F17 E16 G18 D18 F19 C18 Q17 C4 Q4 R3 Q3
  R3 ->      54 (V: 51.86%) (N:  0.07%) PV: R3 C4 Q16 R17 Q17 R16 R15
23.2 average depth, 57 max depth
233745 non leaf nodes, 1.26 average children
295013 visits, 100000036 nodes, 295012 playouts, 619 n/s
```

**Comment by hydrogenpi** [comment]
The build is correct, I included the multigpu merges and used the "next" branch and built it myself in VS2017.

If this is deterministic build these are the hashes of the exe

< C:\lz\leelaz.exe >
  SHA-1: 52E4F3763A8982D380FE0983C00347CF896CB50F
  SHA-512: 1BEADCBB14287249979B2466A4ECD6A861B7672BA6225170BF4E576522FA25875BADE6790161BC300D551F87832581343CB342EC15B280279C3FD912D05A0ECC

**Comment by killerducky** [comment]
@hydrogenpi what does `git rev-parse HEAD` show?

**Comment by killerducky** [comment]
I don't see either of those SHAs, I think something is wrong with your repo.

```
git show F352C12974D6207B79035F0BE66E5BCD772C2C1A
fatal: bad object F352C12974D6207B79035F0BE66E5BCD772C2C1A
git show 049944E37EE47156FBD46AA9F37C89B36243C996
fatal: bad object 049944E37EE47156FBD46AA9F37C89B36243C996
```

**Comment by gcp** [comment]
If he manually merged in the multi-GPU pull request it won't match anything, that's why I said early on "ok so you are *not* on next".

**Comment by gcp** [comment]
>then someone let me know where/what

It's not like anyone knows what you changed. Why not use the actual next branch? The multi-GPU scaling wasn't merged because it's not clear it actually helps.

**Comment by hydrogenpi** [comment]
This is what I did, got the Windows 10 LTSB iso and in VMware workstation created a brand new VM from scratch. Installed Visual Studio 2017 Community edition in this VM. Downloaded the NEXT branch as zip from on github. Extracted to root. Opened up with compiler, set to release x64, compiled the Leelaz in release. No errors. Used that compiled leelaz and the dependencies in the x64 release folder and pointed Sabaki to it with the following parameters:



Ran a game with against AQ, giving AQ 120 seconds per move.... 

Same issue happens again...

**Comment by gcp** [comment]
Which flags did you launch with?

**Comment by hydrogenpi** [comment]
here is where I went wrong, I forgot to change the path in Sabaki so it was still pointing to the old location of the old Leelaz. 

can confirm that this new one solves the issue. 

one thing is that its capping itself at around 300000 playouts... and won't really ever go above it anymore

**Comment by gcp** [comment]
You can increase MAX_TREE_SIZE in UCTSearch.h to increase the memory limit. There's a bunch of proposals to reduce the memory usage (and thus increase this) but nothing stable enough to pull in.

**Comment by hydrogenpi** [comment]
Okay thanks, yes I have got it from the 64 folder so it is the 64bit build. at 300000 its hardly using any memory as far as I can tell. I have 192gb ran on this machine so I'll run a test tonight at 5 million playouts to make sure it is working.

**Comment by hydrogenpi** [comment]
for some strange reason five million playouts seem to be way slower than just  1 million, far more than just five times. In any case, 1 million playouts seems to be fully working now. it seems to be giving back to memory right after each time LZ makes a move and its AQ's turn,then I noticed it had to the trees that it had already calculated  in the previous steps, which is an utter waste of time and effort. I guess that is the outcome when the network doesn't know what over moves to pick to examine and it is forced to do a high # of playouts its just does uncessarily work 

![3212018](https://user-images.githubusercontent.com/35181396/37694686-747ba712-2c86-11e8-9508-76c7db4833b7.jpg)

**Comment by roy7** [comment]
Is this still an actual bug? LZ's disaster move vs Golaxy someone said was related to this bug.

http://portal.yikeweiqi.com/online/golive/detail?id=8326
