### ISSUE TITLE
1ccb7342 pass or fail ?

### ISSUE THREAD

**Issue by NodosDsnn** [gcp/leela-zero#1063]
in http://zero.sjeng.org/
tell
2018-03-19 17:20 | 1ccb7342 VS b7768081 | 237 : 198 (54.48%) | 435 / 400 | **fail**
but 1ccb7342 **pass**

Then pass or failed? It's a bug ?

**Comment by jkiliani** [comment]
It passed first and was promoted, but later arriving loss results caused it to go below 55% winrate, so it is now shown as failed. For what it's worth I don't agree with showing these cases as failed since they were promoted after all, but that's the way the server is programmed. It happened in many cases already.

**Comment by roy7** [comment]
At some point we changed the server graph/table to show > 400 with win rate < 55% as a fail. So there are no "unknown" status any more. I could always change it back if people dislike this.

**Comment by jonlave** [comment]
Maybe create a new status for these such as "FailedOK" to indicate that it was promoted even if winrate drops below the threshold.

**Comment by Mardak** [comment]
@roy7, if you don't want to re-query the networks table from server.js, you could just change the text client side:
```js
const promoted = new Set([...document.querySelectorAll(".networks-table a")].map(v => v.textContent));
[...document.querySelector(".matches-table").rows].forEach(row => {
  const network1 = row.querySelector("a");
  if (network1 && promoted.has(network1.textContent)) {
    row.lastChild.firstChild.textContent = "promote";
  }
})
```

Tested to work in Firefox, Chrome, Safari. Here's a screenshot with a dummy in-progress/unknown state at the top:
![screen shot 2018-03-20 at 12 10 51 pm](https://user-images.githubusercontent.com/438537/37677509-7d66c828-2c38-11e8-8af4-b18a2bc57135.png)

**Comment by gcp** [comment]
There's a ton of issues about the same problem with the site, so closing this one.
