### ISSUE TITLE
[Question] subscribe for new best promoted notification

### ISSUE THREAD

**Issue by Heiseikiseki** [gcp/leela-zero#1065]
Sorry to Ask a question which is not a issue.
I often open the refresh the http://zero.sjeng.org/ one day many many times to check the latest match result. Is is able to notice the user who just want to know there is a new best net promoted? like use email or rss feature.

**Comment by StanTraykov** [comment]
This is more for the server-side, but I do think it'll be very useful to have canonical URLs, at least for leelaz-win64-gpu-latest, best-network, etc. These can then be used in guides or checked for changes / modification date in scripts, etc.

**Comment by bood** [comment]
Use `discord` seems to be a good idea. I plan to write a tool parsing the page and push a notification to `discord` when there is a network got passed.

**Comment by SebastienFaurite** [comment]
You have a twitter bot that does this job : @Razzamataz99

**Comment by stephenmartindale** [comment]
I'd personally love an RSS version of the page. That doesn't need any sort of sign-up, like Discord or Twitter or wotnot. Just make http://zero.sjeng.org/network.rss or something and serve some low-tech XML when that's requested -- way, way easier than writing a parser or scraper.

**Comment by Heiseikiseki** [comment]
@SebastienFaurite  Looks like that twitter bot is stop working.

**Comment by roy7** [comment]
@stephenmartindale Added by https://github.com/gcp/leela-zero-server/pull/58.
