### ISSUE TITLE
Is it a desired behaviour? Miscount after two mutual passes.

### ISSUE THREAD

**Issue by Marcin1960** [gcp/leela-zero#1069]
Seems that Leela leaves games  before territories are clearly divided.

[LeelaZeroT-daigo.zip](https://github.com/gcp/leela-zero/files/1832686/LeelaZeroT-daigo.zip)

**Comment by StanTraykov** [comment]
This is not a LZ issue: bots communicating via GTP can be asked what they think the "final status" of stones is. The server decides how to use this. Some servers do the scoring all by themselves. KGS lets the user have the final world in free games. That is, you can lose by 100 points and mark some stones as dead and still win. In ranked games, KGS lets the bot have the final word under Japanese rules or asks it to cleanup the stones it thinks are dead under area-scoring rules (Chinese/NZ/AGA).

**Comment by Marcin1960** [comment]
Thanx
