### ISSUE TITLE
Minor suggestion: Use YYYY-MM-DD on the status page.

### ISSUE THREAD

**Issue by jgkwok** [gcp/leela-zero#107]
There's a lot of numbers on the page.
It's an international effort, nice to have international date formats.

A clear date is nice. ISO 8601 is the way to go. https://en.wikipedia.org/wiki/ISO_8601

**Comment by roy7** [comment]
Easy enough, I changed the date on there to this format.

**Comment by tux3** [comment]
@roy7 It doesn't seem right though, it says "2011-11-19" !

**Comment by roy7** [comment]
Thanks. I think it's my bedtime.

**Comment by tux3** [comment]
Awesome, thanks for the quick fix!
