### ISSUE TITLE
hybrid gpu intel/nvidia on linux arch, i have some question about how to use it.

### ISSUE THREAD

**Issue by enricoT** [gcp/leela-zero#1070]
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
01:00.0 3D controller: NVIDIA Corporation GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] (rev a1)

i can run on Intel the leelaz-zero gpu, but i cant find a way to run nvidia, wich should be faster.
so my questions:
Can i use the 2 gpu at the same time? (that would be a good feature for old computers)
How can i run leelaz with nvidia gpu? using PRIME nouvea? using PRIME nvidia, or bumblebee? Do i have other options? 
thanks for help

**Comment by afalturki** [comment]
I think you use --gpu 0 --gpu 1

**Comment by gcp** [comment]
But you should test if using the CPU isn't faster. Both GPU are extremely slow and really only serve as monitor-connection-electronics.

**Comment by enricoT** [comment]
the gpu detected is only intel:
./leelaz --gpu 0 --gpu 1 --gpu 2 -w best-network-leelaz -t 4 
RNG seed: 2878447383141256724
Leela Zero  Copyright (C) 2017-2018  Gian-Carlo Pascutto and contributors
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

Detecting residual layers...v1...128 channels...10 blocks.
Initializing OpenCL.
Detected 2 OpenCL platforms.
Platform version: OpenCL 2.0 beignet 1.3
Platform profile: FULL_PROFILE
Platform name:    Intel Gen OCL Driver
Platform vendor:  Intel
Device ID:     0
Device name:   Intel(R) HD Graphics IvyBridge M GT2
Device type:   GPU
Device vendor: Intel
Device driver: 1.3
Device speed:  1000 MHz
Device cores:  16 CU
Device score:  620
Platform version: OpenCL 1.2 LINUX
Platform profile: FULL_PROFILE
Platform name:    Intel(R) OpenCL
Platform vendor:  Intel(R) Corporation
Device ID:     1
Device name:   Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz
Device type:   CPU
Device vendor: Intel(R) Corporation
Device driver: 1.2.0.37
Device speed:  1700 MHz
Device cores:  4 CU
Device score:  512
Selected platform: Intel Gen OCL Driver
Selected device: Intel(R) HD Graphics IvyBridge M GT2
with OpenCL 2.0 capability.
Loaded existing SGEMM tuning.
Wavefront/Warp size: 8
Max workgroup size: 512
Max workgroup dimensions: 512 512 512 
Selected platform: Intel(R) OpenCL
Selected device: Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz
with OpenCL 1.2 capability.
Loaded existing SGEMM tuning.
Wavefront/Warp size: 256
Max workgroup size: 8192
Max workgroup dimensions: 8192 8192 8192 
Selected platform: Intel Gen OCL Driver
Selected device: Intel(R) HD Graphics IvyBridge M GT2
with OpenCL 2.0 capability.
Loaded existing SGEMM tuning.
Wavefront/Warp size: 8
Max workgroup size: 512
Max workgroup dimensions: 512 512 512 
BLAS Core: SANDYBRIDGE

but there are 2 gpu maybe is not supported?

udo lshw -C display
[sudo] password for enrico: 
  *-display                 
       description: 3D controller
       product: GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list rom
       configuration: driver=nouveau latency=0
       resources: irq:26 memory:72000000-72ffffff memory:40000000-4fffffff memory:50000000-51ffffff ioport:4000(size=128) memory:52000000-5207ffff
  *-display
       description: VGA compatible controller
       product: 3rd Gen Core processor Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:30 memory:73000000-733fffff memory:60000000-6fffffff ioport:5000(size=64) memory:c0000-dffff

what im missing about hybrid gpu on linux?
thanks for help ^^

**Comment by ihavnoid** [comment]
AFAIK you should have the nvidia properitary driver.  I don't think nouveau supports OpenCL, but I am not completely sure.  Given the weak performance of laptop-integrated GPUs I am not sure the additional GPU will actually help, though.

**Comment by enricoT** [comment]
after a proper install (nvidia drivers) using 2 gpu (intel+nvidia) the playout result after go command : +60%; however the number remains low, indecently. :)
