### ISSUE TITLE
[Question] Leela vs Leelaz on Mac.

### ISSUE THREAD

**Issue by jslechasseur** [gcp/leela-zero#1073]
If I can run the OpenCL version of Leela on my macbook flawlessly, should I be able to do the same with Leelaz?

I'm aware of #9 . I also ran into mysterious driver errors. Anyone has managed to solve this?

**Comment by jkiliani** [comment]
I run Leelaz on a Mac, and since I do have OpenCL problems, I simply use the CPU build. Not much point to GPU anyway if it's an integrated Intel one.

**Comment by hydrogenpi** [comment]
Well GPU is needed really but also if it works on MAC, check out this Deep learning on a stick usb module from Intel

https://techcrunch.com/2017/07/20/movidius-launches-a-79-deep-learning-usb-stick/

**Comment by Cabu** [comment]
@hydrogenpi Does leela zero support the movidius? It look like it need some complementary development to be able to use the stick...

**Comment by gcp** [comment]
>If I can run the OpenCL version of Leela on my macbook flawlessly, should I be able to do the same with Leelaz?

Yes.

macOS has many driver issues, but if Leela works reliably, the drivers are likely good enough for Leela Zero too.
