### ISSUE TITLE
How to use leela-zero-0.5-windows with -k?

### ISSUE THREAD

**Issue by chucklu** [gcp/leela-zero#108]
PS D:\ChuckLu\ProgramFiles\leela-zero-0.5-windows> .\autogtp.exe -k
Missing value after '-k'.

What value -k needed?

**Comment by chucklu** [comment]
maybe the path to save sgf files？
PS D:\ChuckLu\ProgramFiles\leela-zero-0.5-windows> .\autogtp.exe -k .
autogtp v3

**Comment by roy7** [comment]
You have to tell it the path you want the games saved to per https://github.com/gcp/leela-zero/pull/69

**Comment by chucklu** [comment]
@roy7  the games saved to? as sgf?

**Comment by roy7** [comment]
Yes. Try something like -k . or -k \full\path\ or .\sgf, I'm not sure.

**Comment by chucklu** [comment]
@roy7  @gcp I  have played a game on my computer, but can not find the sgf file.

**Comment by bood** [comment]
if . does not work, try a full path

**Comment by chucklu** [comment]
@bood  full path not working, can not find the sgf file either

**Comment by godmoves** [comment]
autogtp.exe -k sgf，try this

**Comment by chucklu** [comment]
@godmoves  it's working and create a subfolder with the input parameter
I am using kifu as the folder name to save sgf files.

PS D:\ChuckLu\ProgramFiles\leela-zero-0.5-windows> .\autogtp.exe -k kifu

**Comment by jillybob** [comment]
Step 1: Make a folder called kifu in your LeelaZero folder.
Step 1. Open up Windows PowerShell
Step 2. Type in "CD" followed by the path to your LeelaZero folder.
Example: " CD C:\Users\Jillybob\Desktop\leela-zero-0.5-windows"
Step 3: Type ".\autogtp.exe -k kifu" and press the enter button

**Comment by chucklu** [comment]
@jillybob  first step can be skipped, the exe will create the sub-folder automatically
