### ISSUE TITLE
"Solved" Visual Studio. What do I wrong?

### ISSUE THREAD

**Issue by Marcin1960** [gcp/leela-zero#1080]
I decided to install VS 2015 and tried to build Leelaz.exe. I got these errors:

1>------ Build started: Project: leela-zero, Configuration: Release Win32 ------
1>  FastBoard.cpp
1>  Network.cpp
1>C:\Users\HP\Desktop\leela-zero-master\msvc\packages\opencl-nug.0.777.12\build\native\include\CL/cl2.hpp(6518): warning C4018: '<': signed/unsigned mismatch
1>C:\Users\HP\Desktop\leela-zero-master\msvc\packages\opencl-nug.0.777.12\build\native\include\CL/cl2.hpp(7323): error C2719: 'fillColor': formal parameter with requested alignment of 16 won't be aligned
1>C:\Users\HP\Desktop\leela-zero-master\msvc\packages\opencl-nug.0.777.12\build\native\include\CL/cl2.hpp(7357): error C2719: 'fillColor': formal parameter with requested alignment of 16 won't be aligned
1>C:\Users\HP\Desktop\leela-zero-master\msvc\packages\opencl-nug.0.777.12\build\native\include\CL/cl2.hpp(7391): error C2719: 'fillColor': formal parameter with requested alignment of 16 won't be aligned
1>  NNCache.cpp
1>..\..\src\NNCache.cpp(58): warning C4244: 'argument': conversion from 'uint64_t' to 'const unsigned int', possible loss of data
1>  OpenCL.cpp
1>C:\Users\HP\Desktop\leela-zero-master\msvc\packages\opencl-nug.0.777.12\build\native\include\CL/cl2.hpp(6518): warning C4018: '<': signed/unsigned mismatch
1>C:\Users\HP\Desktop\leela-zero-master\msvc\packages\opencl-nug.0.777.12\build\native\include\CL/cl2.hpp(7323): error C2719: 'fillColor': formal parameter with requested alignment of 16 won't be aligned
1>C:\Users\HP\Desktop\leela-zero-master\msvc\packages\opencl-nug.0.777.12\build\native\include\CL/cl2.hpp(7357): error C2719: 'fillColor': formal parameter with requested alignment of 16 won't be aligned
1>C:\Users\HP\Desktop\leela-zero-master\msvc\packages\opencl-nug.0.777.12\build\native\include\CL/cl2.hpp(7391): error C2719: 'fillColor': formal parameter with requested alignment of 16 won't be aligned
1>..\..\src\OpenCL.cpp(998): warning C4244: '+=': conversion from 'float' to 'int', possible loss of data
1>  OpenCLScheduler.cpp
1>C:\Users\HP\Desktop\leela-zero-master\msvc\packages\opencl-nug.0.777.12\build\native\include\CL/cl2.hpp(6518): warning C4018: '<': signed/unsigned mismatch
1>C:\Users\HP\Desktop\leela-zero-master\msvc\packages\opencl-nug.0.777.12\build\native\include\CL/cl2.hpp(7323): error C2719: 'fillColor': formal parameter with requested alignment of 16 won't be aligned
1>C:\Users\HP\Desktop\leela-zero-master\msvc\packages\opencl-nug.0.777.12\build\native\include\CL/cl2.hpp(7357): error C2719: 'fillColor': formal parameter with requested alignment of 16 won't be aligned
1>C:\Users\HP\Desktop\leela-zero-master\msvc\packages\opencl-nug.0.777.12\build\native\include\CL/cl2.hpp(7391): error C2719: 'fillColor': formal parameter with requested alignment of 16 won't be aligned
1>  Random.cpp
1>  Training.cpp
1>..\..\src\Training.cpp(43): fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory
1>  Tuner.cpp
1>C:\Users\HP\Desktop\leela-zero-master\msvc\packages\opencl-nug.0.777.12\build\native\include\CL/cl2.hpp(6518): warning C4018: '<': signed/unsigned mismatch
1>C:\Users\HP\Desktop\leela-zero-master\msvc\packages\opencl-nug.0.777.12\build\native\include\CL/cl2.hpp(7323): error C2719: 'fillColor': formal parameter with requested alignment of 16 won't be aligned
1>C:\Users\HP\Desktop\leela-zero-master\msvc\packages\opencl-nug.0.777.12\build\native\include\CL/cl2.hpp(7357): error C2719: 'fillColor': formal parameter with requested alignment of 16 won't be aligned
1>C:\Users\HP\Desktop\leela-zero-master\msvc\packages\opencl-nug.0.777.12\build\native\include\CL/cl2.hpp(7391): error C2719: 'fillColor': formal parameter with requested alignment of 16 won't be aligned
1>..\..\src\Tuner.cpp(397): warning C4244: '=': conversion from 'float' to 'unsigned int', possible loss of data
1>  UCTNode.cpp
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Splee99** [comment]
The file msvc\packages\opencl-nug.0.777.12\build\native\include\CL/cl2.hpp shouldn't be included in the project. Instead, the file cl2.hpp under src\CL should be included. Maybe your project file should be fixed.

**Comment by Marcin1960** [comment]
" Maybe your project file should be fixed."

It is not my project file, I did not modify anything
I just downloaded it from  the code base here .  (nuget package got downloaded automatically by VC)

**Comment by Splee99** [comment]
OK. I have installed VC2017 and there is no problem. The project file for VC2015 needs to be fixed by adding one line (or more?). I'm wondering why we need both in the system. The VC2017 is free anyway.

**Comment by Marcin1960** [comment]
@Splee99 " I'm wondering why we need both in the system. The VC2017 is free anyway."

Couple  reasons. Many have invested time and work to establish development platforms, used also for other vital projects. Some distrust Microsoft too much to do every new upgrade,

On my system VC2017 failed to install properly.

**Comment by gcp** [comment]
If there's nobody updating or maintaining the MSVC2015 project files, and they're broken as shipped, I see little reason to keep them.

**Comment by Marcin1960** [comment]
OK, I am uninstalling VC 2015. Next I will try 2017.  :(

**Comment by hydrogenpi** [comment]
@Marcin1960 you can do it in a VM, like using VMware workstation and then just snapshot different versions.

**Comment by Marcin1960** [comment]
I failed. I have no clue how to generate  Win32 executable. If I change to Win32, I still get the output:

Projektleela-zero, Konfiguracja: Release x64

**Comment by hydrogenpi** [comment]
why not generate x64 and only 32bit? that can only handle 4GB ram so you cannot get decent playouts etc

**Comment by Marcin1960** [comment]
Because my Windows 7 is 32 bit.

**Comment by Marcin1960** [comment]
A partial "success". I took leela-zero-next branch, From VS2017 opened VS2015 project, Removed autgtp,
set solution/project release/debug to Win32/86 without coppying settings from64 (empty). Removed 64 stuff, saved. Ran Restore NuGet Packages from solution right click menu.

Then compiled project leela-zero

Go one fatal error, no executables

c:\users\hp\desktop\leela-zero-next\src\training.cpp(43): fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory

Then commented out zlib.h in Training.cpp
====
Compiled and got this:

1>------ Build started: Project: leela-zero, Configuration: Release Win32 ------
1>FastBoard.cpp
1>Training.cpp
1>c:\users\hp\desktop\leela-zero-next\src\training.cpp(114): error C3861: 'gzopen': identifier not found
1>c:\users\hp\desktop\leela-zero-next\src\training.cpp(120): error C3861: 'gzwrite': identifier not found
1>c:\users\hp\desktop\leela-zero-next\src\training.cpp(125): error C3861: 'gzclose': identifier not found
1>Tuner.cpp
1>Generating Code...
1>Done building project "leela-zero.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by zediir** [comment]
I think you need to get the 32 bit version of zlib from nuget

**Comment by Marcin1960** [comment]
Yes, I did it.

I used Manage NuGet Packages for the Solution to find zlib-msvc-x86 (name from Internet),
found it, cliked checked boxes on and got this output (positive)

Attempting to gather dependency information for package 'zlib-msvc-x86.1.2.11.8900' with respect to project 'leela-zero', targeting 'native,Version=v0.0'
Gathering dependency information took 621,57 ms
Attempting to resolve dependencies for package 'zlib-msvc-x86.1.2.11.8900' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'zlib-msvc-x86.1.2.11.8900'
Resolved actions to install package 'zlib-msvc-x86.1.2.11.8900'
Retrieving package 'zlib-msvc-x86 1.2.11.8900' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/zlib-msvc-x86/1.2.11.8900/zlib-msvc-x86.1.2.11.8900.nupkg
  OK https://api.nuget.org/v3-flatcontainer/zlib-msvc-x86/1.2.11.8900/zlib-msvc-x86.1.2.11.8900.nupkg 593ms
Installing zlib-msvc-x86 1.2.11.8900.
Adding package 'zlib-msvc-x86.1.2.11.8900' to folder 'C:\Users\HP\Desktop\leela-zero-next\msvc\packages'
Added package 'zlib-msvc-x86.1.2.11.8900' to folder 'C:\Users\HP\Desktop\leela-zero-next\msvc\packages'
Added package 'zlib-msvc-x86.1.2.11.8900' to 'packages.config'
Successfully installed 'zlib-msvc-x86 1.2.11.8900' to leela-zero
Executing nuget actions took 3,8 sec
Time Elapsed: 00:00:05.1633218
========== Finished ==========

**Comment by Marcin1960** [comment]
Next I tried to compiled the solution and it did most of the stuff to fail at:

1>Generating Code...
1>LINK : fatal error LNK1104: cannot open file 'libboost_program_options-vc141-mt-1_65_1.lib'
1>Done building project "leela-zero.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
