### ISSUE TITLE
Using a SWA-network to generate games

### ISSUE THREAD

**Issue by ThePokerDude** [gcp/leela-zero#1081]
What about the follwing idea:

when the progress is stalling we could "promote" a network trained with the SWA method so it generates self play games. 
With this games we train networks with the SGD method an let it play test matches against the previous best SGD-network.
This way we would avoid a problem @gcp mentioned:

> The problem is having an SGD network with SWA self-play data beating an SWA network: it's not necessarily possible.

> 

because the new SGD network would have to beat an old SGD network

**Comment by Tsun-hung** [comment]
Agree with you

**Comment by gcp** [comment]
Needs implementation on the server, and serves no purpose.
