### ISSUE TITLE
Some ideas hopefully to contribute a little bit to the development of Leela Zero!

### ISSUE THREAD

**Issue by Friday9i** [gcp/leela-zero#1086]
I'd like to share some ideas to continue to develop, and possibly to accelerate, this wonderful Leela Zero project. Hopefully it will help!
And first of all, congratulations to all the contributors, you did an amazing job: thanks to you, we all can get a Pro players at home, amazing!!!
(note: I'm not a developer, so not in a position to help technically speaking. But on the idea 1 below, I could help a little bit : project members, tell me if you are interested). 
 
_Idea 1: make more ‘advertising’ for LZ_
The page http://zero.sjeng.org/ could quite easily be more attractive and with up-to-date information.
For example, we could:
- Advertise the performance already achieved, around “LZ has now a pro level and it scored 2-0 against 3p and 6p!”, give the links, ...
- Include links to articles & tutorials.
- Links to Deepmind articles
- Include links to cbaduk on reddit, to the Leela-Zero page on github, to cgos, …
- Explain the development process : “we are currently testing various larger networks like 20x128 and 10x192, but not selecting them yet”, …
- Possibly explain the probable next steps ('next branch', ...)
- Possibly some technical details
I could have a try on it if you are interested.

_Idea 2: Simplify the process for ‘non-geek’ people and make it attractive!_
Currently, I think ‘non-geek’ people simply cannot participate: this is a pity. Without some computer experience, you can just get a command window (not optimized in terms of speed) and the list of moves played, without any possibility to look at the games: that's unattractive ; -(
Hence, I really think we should propose a simplified process for 'non-geeks', with an ‘easy-to-install’ and complete configuration (for Windows):
- Proposing by default the installation of Sabaki (or another one, if possible integrated with Leela) to take a look at the games and to play against any version of LZ (with an integrated feature to download simply the network file) and easily adjusting parameters (playout/time)
- Make a user interface to launch and optimize the process (and mask the autogtp.exe + .bat file with complicated commands): opening the ‘command’ is probably 'too geek' for 90% of the people!
- Saving by default the games in a folder, with a direct access from the UI above
- Including an option to easily take a look at the game currently played on the machine, if possible with some details (eg winrate)

_Idea 3: Standardize the name of networks!_
Network names should be easy-to-understand and easy-to-remember! Hash names such as 1ccb7342 are not easy to remember...
Proposition: LZ#.
Hence, the current best network, 1ccb7342, would simply be labelled LZ108: easy and simple : -).
And networks tested against LZ108 could be labelled LZ108_test1, LZ108_test2, … until one is selected and becomes LZ109!

Then, regarding the algorithm itself, some ideas too:
_Idea 4: Reinforce the randomness in the choice among good moves_
Aim is to increase the variety of play, and possibly/probably learn even faster!
For example, I feel there are way too much 3-3 invasions, all followed by the exact same joseki: that's both painful to look at and probably not ideal for LZ in terms of learning.
From what I read here, you are already working on it (through FPU reduction, noise, ...): nice!
The simple idea I had (before seeing you work on it): choose the move to be played quite randomly among moves within 1% of the win rate of the best move. Example: if the best move has a win rate of 60%, choose randomly any move above 60 * 0,99 = 59.4%. If best move has a 10% win rate, choose any move above 10 * 0.99 = 9.9%.
It should also include some criteria in terms of exploration, to avoid choosing moves with good winrate but almost not analyzed (what criteria to use: at least 1/5 visits vs the best move?)

_Idea 5: Include symmetries by default._
Some could argue that this is not really the ‘Zero spirit’, but IMHO basic symmetries cannot be reasonably qualified as ‘human knowledge added into the program’, so it is compatible with the Zero spirit. And hopefully it should improve things significantly

_Idea 6: Include match games in the training pipelines (if possible)_
It would add games with various errors (such as failing ladders, as we can see in many match games :-), which is probably be useful to learn faster and to avoid mistakes. And I guess it would break ‘cycles of learning': the program learns ladders, doesn’t play failing ladders anymore but then, as it goes out of the training window, it forgets them…: including match games should hopefully solve that (for ladders, but also for other mistakes).
Finally, it would also add a few % more games in the training pipeline for free: not bad.

_Idea 7: Modify the network selection process_ (ie the 55% threshold to get promoted as the current best network).
Let’s call:
- CN: the Current best Network
- TN: the Tested Network
- PN: a Pool Network (defined below)

The TN can be the result of various processes (training from selfplay, average of networks, Net2Net, …), that doesn’t really matter, it has to be tested:
- If TN is a clear winner in match games (ie above 55%): easy, it becomes the new CN! And the process begins again, with new networks being tested.
- If TN is below 55% but good enough after 400 games, let’s say above 47% (I did some stats and think it is reasonable as a first guess), then include this TN in a list of PN. From there:
 o Play selfplay games with the CN and also with all the PN, splitting the number of selfplay games according to the strength of the networks (proposition: if there is the CN + 2 PN networks having 48% and 53% winrates against the CN, then give a weight of 3 to the PN with 53%, a weight of 2 to the CN and a weight of 1 to the PN network with 48%: the 3 networks will play respectively 50%, 33% and 17% of the selfplay games). That will give a strong panel of selfplay games, with more variety than today.
 o From the selfplay games, train new networks (and try some WA networks, Net2net, …) 
 o Test these new networks against the CN (+ the pool of PN if there are some). A modification of the PASS test is needed to take into account the pool of networks (CN + PN) and the averaged strength of these networks. Eg if we get the CN and 2 PN, then the TN will play match games split equally between these 3 networks. And if the 2 PN achieves 51% and 52% against the CN, the weighted average strength of the pool is 51%, so the PASS must be modified: the threshold should be 54% instead of the standard 55%. And to join the pool, the threshold should be 46% (and not 47%) against the pool. (note: I approximated the calculation in the example above, but exact thresholds are very close to these %, so it doesn't matter).

**Comment by Marcin1960** [comment]
And append 10x192 or something like that,

Old text can be removed to make space.

**Comment by Marcin1960** [comment]
And append 10x192 or something like that,

Old text can be removed to make space.

**Comment by Marcin1960** [comment]
And append 10x192 or something like that,

Old text can be removed to make space.

**Comment by Dorus** [comment]
@Marcin1960 You're looping.

**Comment by jonlave** [comment]
We need to fix the move output from autogp to recognize which game/thread is being displayed when more than one game is self-playing. Otherwise, the visualizer will break or not be accurate. A simple fix would be to prepend the move with the game/thread number. 

As an example, I have 2 self-play games running at once, and this is a small snippet of the output:
   1 (B R4) 201 (B J5) 2 (W D17) 202 (W K5)

If we change the format to be "[THREAD_ID]-[MOVE_NUM] ([COLOR] [COORD])" then the above would look like:

   1-1 (B R4) 2-201 (B J5) 1-2 (W D17) 2-202 (W K5)

Then if we had a UI on top of autogp (not talking about sabaki or leela visualizer), we could show previews of the multiple games being run, similar to what OGS shows on player profile pages, and clicking one of them will maximize it to fill the window.

**Comment by gcp** [comment]
3, 4, 5, 6 and 7 are just bad ideas or not practical. The reasons why have already been explained in various issues here.

1 and 2 require someone to do the work. Unless someone is willing to got ahead and do the work, it's pointless to say that "this and that should be done", because it's not going to happen.

**Comment by gcp** [comment]
>Basically, Leela the non-zero versions have been sunset and days are expired. 

Unless you want something that is easy to install, has a GUI, supports handicap, different komi, different board sizes, usable analysis tools, and so on.

I mean it's weird to say that and then to say:

>And that is by making a great UI and offering it as a free teaching tool and analysis tool. This will make it have practical utility and applicability.

Leela hasn't been updated to Leela Zero's strength because, well, I'm busy working on Leela Zero. I might not bother if there were GTP UI's with the quality you see in the chess scene. Sabaki has been improving, but it's not there yet.

**Comment by gcp** [comment]
I'm going to close this because I don't see how it can possibly end up being constructive.

If you're interested in (1), see https://github.com/gcp/leela-zero-server/issues and note you can create pull requests with improvements.

As for (2), go ahead and make a project for a GUI/installer, there's no point in merging that with the engine.

For the others, browsing through already existing issues should reveal the problems with the proposals.

**Comment by Dorus** [comment]
> 1 and 2 require someone to do the work. Unless someone is willing to got ahead and do the work, it's pointless to say that "this and that should be done", because it's not going to happen.

Tbh, doing this kind of work is far easier than many people think. It does require a bit of dedication to get it all together, but everything you need to know is freely available. Many parts of what you need ar already developed and just need gluing together, and there are many people that are willing to help out with specific details if you get stuck on those. For example i'm usually hanging out in various online chats helping people with specific libraries i'm knowledgeable about. Doing so cost me very little time and usually saves those people hours of figuring it all out them self.

Just dont be afraid to get started, start small, make baby steps and slowly work towards a goal. Open source projects like this always have too many people popping up with ideas and too few actually getting their hands dirty. Nobody is more motivated about implementing your ideas than yourself, and it would be great to have more people adding actual value. Even if you arn't a hardcore coder, half these things do not require coding or require only relative simple steps, and you can still help out with them.

**Comment by alreadydone** [comment]
[Lizzie](https://github.com/featurecat/lizzie) as a GUI for LZ looks more popular than Sabaki. People have been using it to analyze pro ongoing or historical games with pro or AI. It is under active development and already has [two](https://github.com/cngoodboy/lizzie) [forks](https://github.com/aerisnju/mylizzie).
