### ISSUE TITLE
Incorrect Leela version for v0.13

### ISSUE THREAD

**Issue by aTan-aka-Xellos** [gcp/leela-zero#1096]
Seems like version of leela and AutoGTP display incorrectly?
0.12 instead of 0.13 and 14 instead of 15.

Release:
Leela Zero 0.13 + AutoGTP v15
![087 25-mar-18 01 18](https://user-images.githubusercontent.com/7886823/37869938-c5b354f8-2fca-11e8-9f8e-9f5dd8bd29ba.jpg)

**Comment by roy7** [comment]
Those values are in a message from the server which tells your client the minimum allowed values.
