### ISSUE TITLE
How to Run on Windows with Sabaki 

### ISSUE THREAD

**Issue by wqssyq** [gcp/leela-zero#11]
C:\Users\ZCH>F:\weiqi\leela-zero-0.2-windows\leelaz.exe --gtp -w F:\weiqi\leela-zero-0.2-windows\weights.txt
Using 1 thread(s).
Initializing OpenCL
Detected 2 OpenCL platforms
Platform version: OpenCL 2.0
Platform profile: FULL_PROFILE
Platform name:    Intel(R) OpenCL
Platform vendor:  Intel(R) Corporation
Device ID:     0
Device name:   Intel(R) HD Graphics 5500
Device type:   GPU
Device vendor: Intel(R) Corporation
Device driver: 10.18.15.4248
Device speed:  900 MHz
Device cores:  24 CU
Device score:  620
Device ID:     1
Device name:   Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
Device type:   CPU
Device vendor: Intel(R) Corporation
Device driver: 5.2.0.10039
Device speed:  2200 MHz
Device cores:  4 CU
Device score:  520
Platform version: OpenCL 1.2 CUDA 8.0.0
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     2
Device name:   GeForce 840M
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 376.54
Device speed:  1124 MHz
Device cores:  3 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce 840M
with OpenCL 1.2 capability
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64
Detecting residual layers...v1...128 channels...6 blocks
Transferring weights to GPU...done
BLAS Core: Nehalem

I set Sabaki parameters:
[103101.png](https://github.com/wqssyq/leela-zero/blob/master/img/103101.png)

What i will to do ?

**Comment by gcp** [comment]
What is the problem exactly? The description you give looks OK.

**Comment by wqssyq** [comment]
Can't run. I don't know the next to do what.

**Comment by wqssyq** [comment]
I am in windows 10.

**Comment by gcp** [comment]
I tested this configuration and it seems to work correctly.

Is the question how _Sabaki_ works? After you have added the engine with "Manage Engines", you can do Engines->Attach.

**Comment by a22063821** [comment]
When will the training data be sent to you automatically?

**Comment by gcp** [comment]
See issue #1 for the latest news. Server and tooling is in testing. autogtp tool was just added to the repository.

**Comment by wqssyq** [comment]
Thank you. I have done. When i attach the engine, not use default manual, must select the leelaz.

Thank you again.

**Comment by Sivous** [comment]
Hi，why my friend told me that Leela using AMD will be better than NVIDIA？Is that true?

**Comment by Sivous** [comment]
He said that Leela uses RX580 po12000, but GTX1080ti po8000, and I happen to have GTX1080ti

**Comment by Sivous** [comment]
RX VEGA64 po20000 I can't believe

**Comment by kingvagabond** [comment]
The original master branch check out, maven build version, run under JDK 10, got font data error. The provided download version shows Leelaz Process ended. then done.
JDK 10.0.1 Windows 10
