### ISSUE TITLE
Cannot visit http://zero-test.sjeng.org now?

### ISSUE THREAD

**Issue by michaelnix** [gcp/leela-zero#110]
When I use IE to visit http://zero-test.sjeng.org/ to see the total training num and client num, but there is a error, "502 Bad Gateway , nginx/1.13.6", any problem in nginx?

**Comment by killerducky** [comment]
You should use the live one, not the test one:
http://zero.sjeng.org/

**Comment by laisc7301** [comment]
我的也是这样子，求解决啊
