### ISSUE TITLE
a strange game Score: B+185.5

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1108]
D:\tool\leela12>autogtp -k sga
AutoGTP v14
Using 1 thread(s) for GPU(s).
Starting tuning process, please wait...
Net filename: 85c6f2ada691baf9ba942ecd1460a5229684ce16349be1fd792c26a64907cd0a
net: 85c6f2ada691baf9ba942ecd1460a5229684ce16349be1fd792c26a64907cd0a.
./leelaz --tune-only -w 85c6f2ada691baf9ba942ecd1460a5229684ce16349be1fd792c26a64907cd0a
Using 2 thread(s).
RNG seed: 9810912414191264952
Detecting residual layers...v1...128 channels...10 blocks.
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 8.0.0
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce GT 730
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 376.62
Device speed:  901 MHz
Device cores:  2 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GT 730
with OpenCL 1.2 capability.
Loaded existing SGEMM tuning.
Tuning process finished
Starting thread 1 on GPU 0
Got previously stored file
Engine has started.
Infinite thinking time set.
Loading 00a567e908074be48df8b604ac33ebf8.sgf
Loading 00a567e908074be48df8b604ac33ebf8.train
523 (B B4) 524 (W E8) 525 (B C13) 526 (W D3) 527 (B A2) 528 (W H13) 529 (B K1) 530 (W B5) 531 (B F1) 532 (W A5) 533 (B N
16) 534 (W E6) 535 (B E17) 536 (W C4) 537 (B pass) 538 (W B10) 539 (B A8) 540 (W pass) 541 (B F7) 542 (W F8) 543 (B B1)
544 (W pass) 545 (B H17) 546 (W G18) 547 (B L13) 548 (W O13) 549 (B J10) 550 (W G9) 551 (B Q12) 552 (W J8) 553 (B K12) 5
54 (W G16) 555 (B M12) 556 (W J18) 557 (B J14) 558 (W N12) 559 (B E10) 560 (W N13) 561 (B N11) 562 (W F19) 563 (B M9) 56
4 (W H9) 565 (B N10) 566 (W G19) 567 (B P18) 568 (W K10) 569 (B B19) 570 (W pass) 571 (B E2) 572 (W K8) 573 (B H1) 574 (
W G10) 575 (B B15) 576 (W L11) 577 (B O10) 578 (W G17) 579 (B B7) 580 (W G1) 581 (B E5) 582 (W L12) 583 (B B8) 584 (W C2
) 585 (B F6) 586 (W J11) 587 (B A4) 588 (W A5) 589 (B H15) 590 (W J9) 591 (B G3) 592 (W F2) 593 (B D16) 594 (W D6) 595 (
B A18) 596 (W C3) 597 (B P15) 598 (W E4) 599 (B D5) 600 (W C4) 601 (B Q16) 602 (W B9) 603 (B D3) 604 (W pass) 605 (B G12
) 606 (W H13) 607 (B H18) 608 (W G16) 609 (B L17) 610 (W G17) 611 (B M13) 612 (W pass) 613 (B A3) 614 (W G19) 615 (B F19
) 616 (W O13) 617 (B S1) 618 (W pass) 619 (B E6) 620 (W O1) 621 (B E8) 622 (W P1) 623 (B P16) 624 (W R2) 625 (B T1) 626
(W pass) 627 (B G13) 628 (W T3) 629 (B A1) 630 (W T2) 631 (B N12) 632 (W Q1) 633 (B B5) 634 (W T4) 635 (B N13) 636 (W pa
ss) 637 (B H8) 638 (W Q2) 639 (B R4) 640 (W S5) 641 (B J18) 642 (W G10) 643 (B T17) 644 (W R17) 645 (B T16) 646 (W S2) 6
47 (B G18) 648 (W G17) 649 (B Q3) 650 (W S4) 651 (B A7) 652 (W S1) 653 (B R3) 654 (W J9) 655 (B D6) 656 (W R1) 657 (B J8
) 658 (W G9) 659 (B H13) 660 (W pass) 661 (B S17) 662 (W R6) 663 (B L16) 664 (W S3) 665 (B A5) 666 (W R3) 667 (B F8) 668
 (W R4) 669 (B pass) 670 (W pass) Game has ended.
Score: B+185.5
Winner: black
Uploading game: 05e49887a022405884abb2013fee2db3.sgf for network 0f6a8c5f42489b4b954208e794acbf20819e1b57039a0584171e20b
d4c8225a2
Game data ead13d7e0b869ac97bb03f86bba977fda5bd02b7a359a79ee8d61342335568b8 stored in database
1 game(s) (1 self played and 0 matches) played in 57 minutes = 3470 seconds/game, 23445 ms/move, last game took 3463 sec
onds.

**Comment by l1t1** [comment]
online view http://zero.sjeng.org/view/ead13d7e0b869ac97bb03f86bba977fda5bd02b7a359a79ee8d61342335568b8?viewer=eidogo

**Comment by l1t1** [comment]
Leela Zero options: -p 0 -v 3200 -r 0 -m 30 -t 1 -d -n --noponder -s 10380881778371349982 -g -q -w 0f6a8c5f42489b4b954208e794acbf20819e1b57039a0584171e20bd4c8225a

-r 0 means "resignation_percent": "0"?

**Comment by afalturki** [comment]
I don't really see anything strange about it. Could you explain what you mean please?

**Comment by rchs819** [comment]
Yes, -r 0 means no resign is allowed, the game will end when

1. Both players passed
2. OR, game move exceed 722 (or some similar number)

P.S. You client is outdated, there is new [release](https://github.com/gcp/leela-zero/releases)

**Comment by HenryHo2006** [comment]
why LeelaZero kill self on no resign mode? LeelaZero has not been learned "two eyes live"?

**Comment by afalturki** [comment]
It was already losing. It didn't make a difference.

**Comment by tterava** [comment]
If the evaluation is 0.00% no matter what move LZ picks, then it can't differentiate which move is "better". It doesn't have the same honor as human players do, where it still tries to maximize its score when it knows it will lose. It simply plays stones where it feels like. That might be filling its own eyes or playing stones into atari. This is all normal and intended behavior.

**Comment by Alderi-Tokori** [comment]
@tterava I don't know about "intended", let's just say we can't do anything about it due to how MCTS works and in a real game it's expected to resign before starting to do these moves.
