### ISSUE TITLE
"Glider in the stratosphere" analogy? What do you think?

### ISSUE THREAD

**Issue by Marcin1960** [gcp/leela-zero#1114]
I suspect that Leela Zero project is approaching "glider in the stratosphere" barrier.
Gliders, especially unmanned, use method of finding currents of rising air. At certain height it is increasingly harder as the air becomes thinner

LZ is approaching pro level, could it be that the analog of stratosphere is being reached?

If so, increasing the net size no necessarily will help much. Maybe new approaches are needed, like improving speed and efficiency of playouts, or something entirely different and creative?

What do you think?

**Comment by Eddh** [comment]
We are already trying new approaches with disabling fpu reduction at root, and gcp will switch to SWA soon. So we can wait and see what happens from that already. Anyway AGZ reached much higher levels than what we have now. Who knows maybe we are in a kind of bad local optimum because of the bugs at the beginning, and the fact that learning rate was decreased before using larger net sizes.

**Comment by Marcin1960** [comment]
"AGZ reached much higher levels"

Is a powerful hardware the key factor there?

**Comment by Ishinoshita** [comment]
Not so long  ago (and probably still now, I didn't check lately), a good proportion of early resigned match games (typically the ones resigned after 92-93 moves) were 'ladder' games, i.e. games were one side misread a ladder. Plus there are still some match games lost on failure to read L&D or semeai on large groups. So, no, training probably not over. Net size increase and other items regarding possible shortcomings of current selfplay / training processes will probably  help breaking the apparent glass ceiling (imho). BTW, I note that AGZ policy alone (nnet greedy play, no search) almost matched Fan Hui level, thus pro level (ELO ~3000).

**Comment by Marcin1960** [comment]
Where is this duplicate?

**Comment by hydrogenpi** [comment]
LZ is already pro level... but Pro level is very wide range. 3000 Elo is pro. But top pro is closer to 4000 Elo

The thing of it is, Google spent 25 million dollars on computing AGZ with 5000 TPU. 
LZ is commnituy based and only has a tiny fraction of the commputer resources as Google did for AGZ.

So, given that, I think it already did quite well. 

But yes I would like to see it approach or even surpass top pro levels.
