### ISSUE TITLE
Why some selfplay training game doesn't not show the correct networkname?

### ISSUE THREAD

**Issue by Heiseikiseki** [gcp/leela-zero#1118]
I noticed this for a while. 
For example:
http://zero.sjeng.org/view/6847cc60fc8a62d349b1bcd41a4d611890b3b381088260e2db69af41742cb939?viewer=wgo

The black is the "Leela Zero 0.12 networks" look very strange.
Is it a normal release or some of the client uses the broken software?

**Comment by alreadydone** [comment]
https://github.com/gcp/leela-zero/pull/1053#comment-374567259

**Comment by gcp** [comment]
This was fixed in the current release: https://github.com/gcp/leela-zero/commit/f4cfa8f68be431702ccd9c9c8dd2a40a0f866bbc
