### ISSUE TITLE
Early pass exist in self play for 4c7dd

### ISSUE THREAD

**Issue by fell111** [gcp/leela-zero#1119]
http://zero.sjeng.org/view/44d6458ab085d5e706e6ebcf7a6eb3e8d412171da5c24bf7873c03601cf776c7?viewer=wgo
While going through the self play, I found that white passed at move 2. I'm not sure whether it was caused by new network or some bad client. Could somebody verify that? My laptop is not on hand righr now.

**Comment by rchs819** [comment]
Due to recent [PR](https://github.com/gcp/leela-zero/pull/1083#issuecomment-375916261) increasing diversity in the first 30 moves.

There is nothing wrong playing `pass` at move 2.

**Comment by fell111** [comment]
The client is still 0.12. I think that PR only affect 0.13.

**Comment by rchs819** [comment]
Yes, true, increasing diversity only affect 0.13+

But for 0.12, randomisation is already in place.

**Comment by WhiteHalmos** [comment]
Hmm... v0,12 shouldn't. With fpu reduction such nodes hardly get any playouts. That's why it was changed.

**Comment by alreadydone** [comment]
1. Pass isn't much worse than first-line moves, so it's not so unlikely to be picked. However there are many first-line moves but only one pass move...
2. Even if a move has zero prior probability, Dirichlet noise can raise it to at most 0.25.
3. I compiled on Big Red II after PR #1083 but before the official release, so it may show as v0.12 even it's in essence v0.13.
