### ISSUE TITLE
[Documentation] Alphago zero cheat sheet

### ISSUE THREAD

**Issue by ThomasCabaret** [gcp/leela-zero#1124]
Hi, I just remark that the very good alphago zero cheat sheet is not mentioned in the github home. I find this document very useful and maybe not everyone is aware of its existence. It's gold for lazy people like me. Here it is:
https://applied-data.science/static/main/res/alpha_go_zero_cheat_sheet.png

**Comment by TFiFiE** [comment]
To give credit where credit is due, any link should instead go to [the article from which it came](https://medium.com/applied-data-science/alphago-zero-explained-in-one-diagram-365f5abf67e0).
