### ISSUE TITLE
--timemanage on appears to affect playing strength depending on net

### ISSUE THREAD

**Issue by Hersmunch** [gcp/leela-zero#1127]
Running this:
`validation.exe -b leelaz -n 85c6f2ad -o "-g -v 3200 --noponder -t 1 -q -d -r 10 --timemanage on -w" -b leelaz -n 85c6f2ad -o "-g -v 3200 --noponder -t 1 -q -d -r 10 --timemanage off -w"`
gives:
```
The first net is worse than the second
85c6f2ad v 85c6f2ad ( 137 games)
              wins        black       white
85c6f2ad   57 41.61%   24 40.00%   33 42.86% (--timemanage on)
85c6f2ad   80 58.39%   36 60.00%   44 57.14% (--timemanage off)
                       60 43.80%   77 56.20%
```
I found this by accident whilst trying to optimise some code in #967 (there wasn't any optimisation in the end). The 'less clean' results using other networks from that PR are:
`validation.exe -b leelaz_next -n 5ac1d898-o "-g -p 1600 --noponder -t 1 -q -d -r 0 -w" -b leelaz_opt_uct_select -n 5ac1d898-o "-g -p 1600 --noponder -t 1 -q -d -r 0 -w"`
```
5ac1d898 v 5ac1d898 ( 140 games)
                 wins        black       white
next             59 42.14%   28 41.79%   31 42.47% (effectively --timemanage on)
opt_uct_select   81 57.86%   39 58.21%   42 57.53% (effectively --timemanage off)
                             67 47.86%   73 52.14%
```

`validation.exe -b leelaz_next -n 75603ad2 -o "-g -v 3200 --noponder -t 1 -q -d -r 10 -w" -b leelaz_opt_uct_select -n 75603ad2 -o "-g -v 3200 --noponder -t 1 -q -d -r 10 -w"`
```
75603ad2 v 75603ad2 ( 165 games)
                 wins        black       white
next             72 43.64%   43 44.33%   29 42.65% (effectively --timemanage on)
opt_uct_select   93 56.36%   54 55.67%   39 57.35% (effectively --timemanage off)
                             97 58.79%   68 41.21%
```

`validation.exe -b leelaz_opt_fixed -n 1ccb7342 -o "-g -v 3200 --noponder -t 1 -q -d -r 10 -w" -b leelaz_opt_broke -n 1ccb7342 -o "-g -v 3200 --noponder -t 1 -q -d -r 10 -w"`
```
1ccb7342 v 1ccb7342 ( 226 games)
                      wins        black       white
leelaz_opt_fixed  104 46.02%   45 45.45%   59 46.46% (effectively --timemanage on)
leelaz_opt_broke  122 53.98%   54 54.55%   68 53.54%  (effectively --timemanage off)
                               99 43.81%  127 56.19%
```

So I went back and looked at #968 in which @sethtroisi did some validation testing (with unspecified weights):
> With 1600 playouts
> ```
> leelaz-next v leelaz-pull968 (200/200 games)
> board size: 19   komi: 7.5
>                  wins              black         white        avg cpu
> leelaz-next        85 42.50%       35 35.00%     50  50.00%     99.79
> leelaz-pull968    115 57.50%       50 50.00%     65  65.00%     98.59
>                                    85 42.50%     115 57.50%
> ```

So I'm also currently running a validation run for a net that was the best network at around the time of the comment:
`validation.exe -b leelaz -n 1a198f8d -o "-g -v 3200 --noponder -t 1 -q -d -r 10 --timemanage on -w" -b leelaz -n 1a198f8d -o "-g -v 3200 --noponder -t 1 -q -d -r 10 --timemanage off -w"`
It is currently at:
```
152 wins, 145 losses
297 games played.
Status: 0 LLR -0.807074 Lower Bound -2.94444 Upper Bound 2.94444
```

This suggests that the effect of `--timemanage on` is weights and/or network architecture dependent. It may be prudent to disable it for matches until the mechanism for the effect is understood further (it is already disabled for self-play). 
I think that the change to the distribution of playouts for each network may simply cause a strength increase if the network happens to "particularly like" good moves or a decrease if it doesn't. That being said, if both networks in the match have the same option then perhaps it is fine for them to be compared.

**Comment by killerducky** [comment]
That is strange. The original version of timemanage should be guaranteed to select the same move outside randomness. After that prune_noncontenders was added, which seems like it could only help. 

Random thought: Recent nets seems to resign too early, so maybe lowering to `-r 5` would help?

**Comment by WhiteHalmos** [comment]
Tree reuse is definitely more effective with --timemanage off. I think you want to redo this test with the same time limits for the two instead, i.e. --timemanage on will give more time for subsequent moves.

Gomill would allow you to do this.

**Comment by killerducky** [comment]
It's true with equal time timemanage will be even stronger. But with equal `-v3200` timemanage should be the same (with the original version) or possibly stronger (due to prune_noncontenders). Something strange is happening.

**Comment by WhiteHalmos** [comment]
But with equal `-v3200` and timemanage stops after 1600 visits, it is not getting a bigger tree when it comes time to reuse that tree after the opponent moves, effectively reducing the number of visits. Its opponent's tree would always be 3200 visits so it is much larger.

**Comment by killerducky** [comment]
Yes less treereuse. But for every root node where you are making a decision on what move to play, `-v3200` guarantees to collect the same amount of information (3200 visits). It doesn't matter if that information came from the previous move or the current move.

**Comment by WhiteHalmos** [comment]
Thought about it some more, yes, since it's visits rather than playouts, the result technically shouldn't change.

**Comment by Hersmunch** [comment]
So I decided to step through a seeded game with and without time management just to see what I could see (other options set to `-w 8fc22bca --noponder -v500 -r 5 -s 1 -t 1 `). I also made the random network rotation selection always pick rotation 0 to keep them as similar as possible.
The point at which the games diverged in terms of moved played looked like:
`--timemanage off`:
```
Leela: genmove b
Thinking at most 49.5 seconds...
NN eval=0.785019

 D10 ->     489 (V: 79.61%) (N: 86.18%) PV: D10 C9 B12 J11 H11 K11 H12 G11 H10 D
9 B10 E10 A11 E11 Q2 R6 R7
 B12 ->      10 (V: 70.61%) (N:  7.12%) PV: B12 E11 D10 D9 E10 F10
9.6 average depth, 18 max depth
374 non leaf nodes, 1.33 average children
500 visits, 126966 nodes, 250 playouts, 221 n/s

= D10
...
Leela: genmove w
Thinking at most 49.6 seconds...
NN eval=0.796117

  C9 ->     182 (V: 19.03%) (N: 47.77%) PV: C9 B12 J11 H11 K11 H12 G11 H10 D9 B1
0 E10 A11 E11 Q2 R6 R7
  D9 ->     163 (V: 23.23%) (N:  4.74%) PV: D9 B10 E10 E11 F10 G11 H11 G10 H10 G
9 J11 C9 B4 G2 H2 C7
 B12 ->     138 (V: 18.62%) (N: 39.12%) PV: B12 C9 B10 D8 B8 C7 B7 C6 B6 B4 B5 A
3 C5 Q2
 J11 ->      16 (V: 21.90%) (N:  1.63%) PV: J11 H11 K11 H12 C9 B12 G11 H10
8.8 average depth, 17 max depth
373 non leaf nodes, 1.34 average children
500 visits, 126882 nodes, 11 playouts, 183 n/s

= C9
```
`--timemanage on`:
```
Leela: genmove b
Thinking at most 49.6 seconds...
NN eval=0.785374
49.5s left, stopping early.

 D10 ->     250 (V: 78.78%) (N: 86.18%) PV: D10 C9 B12 J11 H11 K11 H12 G11 H10 D
9 B10 E10 A11 E11
 B12 ->       7 (V: 69.37%) (N:  7.12%) PV: B12 E11 D10 D9
8.5 average depth, 15 max depth
190 non leaf nodes, 1.35 average children
258 visits, 65784 nodes, 28 playouts, 233 n/s

= D10
...
Leela: genmove w
Thinking at most 49.6 seconds...
NN eval=0.787806
48.8s left, stopping early.

  D9 ->     193 (V: 23.01%) (N:  4.74%) PV: D9 B10 E10 E11 F10 G11 H11 G10 H10 G
9 J11 C9 B4 G2 H2 C7 K2
  C9 ->     186 (V: 18.80%) (N: 47.77%) PV: C9 B12 J11 H11 K11 H12 G11 H10 D9 B1
0 E10 A11 E11 Q2 R6 R7
 B12 ->     115 (V: 18.10%) (N: 39.12%) PV: B12 C9 B10 D8 B8 C7 B7 C6 B6 B4 B5 A
3 C5 Q2
8.9 average depth, 18 max depth
372 non leaf nodes, 1.33 average children
495 visits, 125559 nodes, 245 playouts, 310 n/s

= D9
```
So in this case it looks like timemanage off spent all its visits on a fairly forced move and then didn't have enough on the next move to spot the "better choice". timemanage on was able to refocus its search and pick the other option. 
I realise that the tree is reused between players in this case but I imagine similar situations are still possible with two separate trees. This example may also be flawed because it looks like the game is "already won".

So my thoughts are that having --timemanage on should be able to pick more promising moves and therefore maybe the effect I'm seeing is another symptom of bad positional judgement/value estimation, much like the early resignations that are being observed.

> Random thought: Recent nets seems to resign too early, so maybe lowering to -r 5 would help?

I agree that to early resignations could be clouding the issue. I'm thinking that using -r 1 is probably better. Also, do we know of a net that has a very low incorrect resign rate to compare to?

I'm going away camping all of next week so won't be able to report back for a couple of weeks...

**Comment by roy7** [comment]
@gcp I already lowered -r to 5 for selfplay and matches by default, would you like me to drop selfplay to 1?

**Comment by WhiteHalmos** [comment]
@roy7 the current nets haven't been trained yet on -r5 self play games yet. My data doesn't show -r5 is too bad.

**Comment by Hersmunch** [comment]
@roy7, ahh I meant using -r 1 for a test validation run only!

**Comment by roy7** [comment]
Ah ok. So I'll leave it all at 5 for now?

**Comment by gcp** [comment]
If I understand correctly, the problem is that for a fixed number of visits, having timemanage on will simply mean that a bunch of those playouts are never done, which causes a strength drop because the policy predictions and ensuing tree reuse are very good.

To make it makes most sense to disable timemanage with fixed visits then (including noncontenders)? So 3200 visits really means 3200 visits.

**Comment by billyswong** [comment]
So the timemanage thing doesn't cut off the playouts early only if it is sure it can't find a better move than current candidate even if the playouts/visits in plan or in time-estimation are exausted? Or I misunderstood the nature of "visit" and LZ's strength when specified in visit count is not truly independent of tree reuse?

**Comment by gcp** [comment]
>So the timemanage thing doesn't cut off the playouts early only if it is sure it can't find a better move than current candidate even if the playouts/visits in plan or in time-estimation are exausted?

What you describe is what it does.

After thinking more about it, I think the only way this can cause problems with --visits is due to pruning unpromising contenders? That would cause a difference even with fixed visits.

Would be good to redo the tests with only that heuristic disabled.

**Comment by gcp** [comment]
It's interesting that the original testing even showed an improvement with --playouts https://github.com/gcp/leela-zero/pull/968#issuecomment-370189810 even though one would expect tree reuse to make that worse.

**Comment by Hersmunch** [comment]
I forgot to report back that I quit:
`validation.exe -b leelaz -n 1a198f8d -o "-g -v 3200 --noponder -t 1 -q -d -r 10 --timemanage on -w" -b leelaz -n 1a198f8d -o "-g -v 3200 --noponder -t 1 -q -d -r 10 --timemanage off -w"`
at this point:
```
242 wins, 219 losses
461 games played.
Status: 0 LLR -0.0233505 Lower Bound -2.94444 Upper Bound 2.94444
```
i.e. also showing an improvement with `--timemanage on` for the originally tested net using a visits limit.

Just before my time away I tried a more recent 128x10 net (the best at the time):
```
2e3863ed v 2e3863ed ( 124 games)
              wins        black       white
2e3863ed   80 64.52%   38 65.52%   42 63.64% (--timemanage on)
2e3863ed   44 35.48%   20 34.48%   24 36.36% (--timemanage off)
                       58 46.77%   66 53.23%
```

This also shows an improvement. So this reinforces my view that the change is net dependent.
I tabulated these results against incorrect resign rates from #1100 and #971 but can't see any obvious correlation from these few data points. I still think this could just be the result of nets having differently shaped policy distributions i.e. from the board states it gets into most often, how biased it is toward spreading it's initial visits toward better/worse moves.
I would expect the effect of `--timemanage on` to improve over time as we are selecting best networks with this on. However, it could regress if the network learns something else very beneficial or whenever we net2net to change architecture. Hmm.

> After thinking more about it, I think the only way this can cause problems with --visits is due to pruning unpromising contenders? That would cause a difference even with fixed visits.
> 
> Would be good to redo the tests with only that heuristic disabled.

Note that the validation run I did with 5ac1d898 using my bugged implementation from #967 was accidentally effectively testing `--timemanage `on vs `--timemanage on` but without pruning.
I will make a local mod to disable just the pruning and run matches for `--timemanage `on vs `--timemanage on` but without pruning for each of 2e3863ed and 85c6f2ad (hopefully the quickest to finish).

**Comment by Hersmunch** [comment]
I've updated the title to clarify a bit as well as my running results.
It isn't clear but it might be leaning toward the effect being due to stopping the search once all but one nodes have been pruned.
Note that @roy7 (@OmnipotentEntity) are thinking this might be worth effectively removing this for byoyomi https://github.com/gcp/leela-zero/pull/883#issuecomment-383572916

**Comment by Hersmunch** [comment]
So the most recent runs are all showing no change. sigh. 
I'm rerunning plain next with `--timemanage on/off` for 2e3863ed and so far:
```
42 wins, 62 losses
104 games played.
Status: 0 LLR -2.5718 Lower Bound -2.94444 Upper Bound 2.94444
```
This is the other way around compared to last time. I think I have been the victim of chance/SPRT :(

**Comment by gcp** [comment]
What a clusterfoo!

Now, we know for sure that thinking longer will not make the engine weaker. So time management off losing to time management on can only be due to prune_noncontenders.

It may be useful at this point to do a test with only that enabled (but no early exit), vs timemanagement off, for fixed visits and fixed playouts.

I'm tempted at this point to disable time management in fixed visits and playouts (in auto mode, still allowing an override), but I think that would need to above test, which hopefully shows that prune_noncontenders does help and should still be enabled in that case.

**Comment by Hersmunch** [comment]
So I'm running:
`validation.exe -b leelaz_next -n 2e3863ed -o "-g -v 3200 --noponder -t 1 -q -d -r 1 --timemanage off -w" -b leelaz_no_prunestop -n 2e3863ed -o "-g -v 3200 --noponder -t 1 -q -d -r 1 --timemanage on -w"`
but I'm unsure what it can tell us if a run can give us 60:40 and 40:60 using exactly the same options. Should I have set the SPRT hypothesis different to default to avoid stopping early?

**Comment by OmnipotentEntity** [comment]
Because it's relevant here, I've been running a match using byoyomi time only for the past few days. (time_settings 0 10 1)  Using engine git revision 5b2460c (which was current when I started) and net e8601c38. 

Thus far the result is 141-132 (off vs on), which is not a significant result in either direction.

```
leelaz-next-on v leelaz-next-off (273/400 games)        
board size: 19   komi: 7.5                              
                  wins              black          white        avg cpu                                         
leelaz-next-on     132 48.35%       57  41.61%     75  55.15%   1850.87                                         
leelaz-next-off    141 51.65%       61  44.85%     80  58.39%   1855.90                                         
                                    118 43.22%     155 56.78%  
```

**Comment by roy7** [comment]
It surprises me the cpu usage is almost identical when most byoyomi periods time-mange on should be using about half the playouts. I assume pondering is off?

**Comment by gcp** [comment]
>It surprises me the cpu usage is almost identical when most byoyomi periods time-mange on should be using about half the playouts.

Correct, this is very strange.

**Comment by OmnipotentEntity** [comment]
Pondering is on.

**Comment by roy7** [comment]
I think the test needs to be pondering off to test the goal? Otherwise, timemanage on or not, they are both actually using the same amount of time.

**Comment by OmnipotentEntity** [comment]
They are, the purpose of this particular test was testing the efficacy of ponder time vs thinking time.  In theory ponder time should be less valuable, but there was some argument over how much less valuable it is.

**Comment by roy7** [comment]
Ahh ok. :) Well then mystery of the high cpu is solved.

**Comment by OmnipotentEntity** [comment]
```
leelaz-next-on v leelaz-next-off (400/400 games)        
board size: 19   komi: 7.5                              
                  wins              black          white        avg cpu                                         
leelaz-next-on     206 51.50%       93  46.50%     113 56.50%   1843.38                                         
leelaz-next-off    194 48.50%       87  43.50%     107 53.50%   1848.33                                         
                                    180 45.00%     220 55.00% 
```

Final results from the match.  Inconclusive.  It seems that time manage off vs on is more or less the same, perhaps results would be different if pondering were turned off and/or if it were fighting someone other than a mirror image of itself.

**Comment by gcp** [comment]
I did a test where timemanage was turned off but prune_noncontenders was kept enabled:

```
leelaz-next-v3200 v leelaz-ntm-v3200 (181/1000 games)
board size: 19   komi: 7.5
                    wins              black         white        avg cpu
leelaz-next-v3200     93 51.38%       42 46.15%     51  56.67%   1090.19
leelaz-ntm-v3200      88 48.62%       39 43.33%     49  53.85%   1377.59
                                      81 44.75%     100 55.25%

leelaz-next-p1600 v leelaz-ntm-p1600 (181/1000 games)
board size: 19   komi: 7.5
                    wins              black         white        avg cpu
leelaz-next-p1600     59 32.60%       24 26.37%     35  38.89%    786.63
leelaz-ntm-p1600     122 67.40%       55 61.11%     67  73.63%   1424.19
                                      79 43.65%     102 56.35%
```

**Comment by gcp** [comment]
Based on this, I think timemanage auto and on should use prune_nocontenders but not exit early when playout limits are enabled (this is also *logically* what one would expect).

I'll keep the old behavior in timemanage fast.
