### ISSUE TITLE
two good promotions wasted had variable gating been implemented?

### ISSUE THREAD

**Issue by hydrogenpi** [gcp/leela-zero#1133]
twice now a 54.xx would have rounded up to 55..

so combined we just threw away a 60% for no good reason?

**Comment by hydrogenpi** [comment]
The reason I bring this up is because last time during the debate many pundits stated that "well we never really get a borderline anyway", but now in recent times we have gotten at least three of them if not more.

**Comment by Mardak** [comment]
How did you get a "combined 60%?"

**Comment by hydrogenpi** [comment]
5% + 5% is  10 %

**Comment by Mardak** [comment]
Just making sure I'm understanding your math, if there were 10 almost 55% networks that did not promote from the current best network, if we did take all 10 of them, there should be a 100% win rate against the current best? (5% + 5% + 5% + 5% + 5% + 5% + 5% + 5% + 5% + 5% = 50% higher than an even match -> 100%?)

**Comment by hydrogenpi** [comment]
More or less, yes.
