### ISSUE TITLE
$500 offer for anyone willing to do a 20b 256f network based from 2e3863ed (#114) and with at least latest 1.5 mil games. 

### ISSUE THREAD

**Issue by hydrogenpi** [gcp/leela-zero#1135]
Serious offer, $500 USD, half up-front and the second half when work is completed and results published online to the open public community. Basically it will be more or less a redo of bjiyxo's 20b 256f network here ( https://github.com/gcp/leela-zero/issues/1113 ) but starting with the current latest 10-block network as opposed to the very old one he used. Will have to incorporate at least the latest 1.5 Million games and trained with meaningful number of steps. (maybe not as many steps as bjiyxo used but certainly more than the one gcp used) 

I don't know linux and its impossible to get this to work in Windows (I blame Google's TensorFlow incompat with Windows) 

Payment will be made via paypal. If you agree, you send me an invoice with a mutual agreed upon written agreement and I'll pay the first half immediately.  

I know this is more work and effort than $500 USD, however this is geared towards those who have the ability and already have a slight inclination to do this exercise anyway, so for someone in that position, this is merely an impetus to push someone to actually go through with doing it. 

bochen777@protonmail.com
972.737.7771

Contact me if interested

**Comment by hydrogenpi** [comment]
I"m not talking about autogtp. I'm talking about using the already generated self playing games of the last 1.5 Mil games after a net2net... this is something has already been done before, just on a very old net and on old games.

**Comment by bjiyxo** [comment]
Actually, there's some severe issue in my 20b 256f net, and the most important thing is that it cannot read most ladder in <10000 po. I'm not sure how to solve this. Another important issue is that n2n may produce a lot of zero in the net, and it is hard to change those zero.  Luckily, swa can solve this issue, and change the zero there. And I'm still observing whether there are other issues in swa.
I think only is these important issue can be well-solved and we cannot solve the issue by the net currently existing, we may re-train a net. So I don't think it's a good way to re-train right now.

**Comment by hydrogenpi** [comment]
10000 po is nothing for the purposes of using the net to play against pros, since I would say 150,000 is the bare minimum... Do you know if these issues with ladders disappear for good after the 150,000 po mark? if so, then what is there to "solve". since its not like a 20b 256f net is meant to be used on low end machines anyhow.

**Comment by bjiyxo** [comment]
You're right in most of the situation. However, there are some joseki that have great connections to ladders, and if leela zero doesn't know the ladders multi moves before, it will be in a really bad spot. That's not a problem against other AI's for sure, but it can be a bad shortcoming if facing human. 
BTW, I'm not sure why do you want to train a new net instead of using my net. (I will update it.)

**Comment by hydrogenpi** [comment]
i think if you start from scratch and net2net the latest network into a 256 by 20 that you wont have the ladder problems. in any case ive you can be willing to do it email me a paypal invoice.

**Comment by hydrogenpi** [comment]
so you will do it from scratch with latestest or you still training the old one

**Comment by bjiyxo** [comment]
I will train the old one. I don't see any difference between training a new one from 2e3863ed and training the old one to 2e3863ed.

**Comment by hydrogenpi** [comment]
the diff is you said it yourself on just 1 gtx1080ti you cant catch up.

**Comment by hydrogenpi** [comment]
a net2net of the latest 10 block and traininf latest 1.5 mil rather than an obosolete network and running the red queens race.... thats the difference

**Comment by hydrogenpi** [comment]
network 78 that you initially n2n is a preladder 6 block. that my theory is it permanelty stunts its growth, so training with starting with latest 10 block might boost strap it correctly

**Comment by hydrogenpi** [comment]
also if you start anew with latest swa nets it will help the roots build stronger linkages and overlay better filament structure... and latesr games have more diversity

**Comment by bjiyxo** [comment]
But AlphaGo trained from zero elo, so it doesn't matter if I start from a lower elo. Although I cannot win the race, the amount of games still affect the strength of Leela. So I'm not going to re-train a net now.

**Comment by hydrogenpi** [comment]
AlphaGo also didnt use any  net2net, which means ni possubility of glitches being introduced. i think going from 6 b to 20b was too much of an inflation and caused issues. a 10 to 20b would be more scale invariant

**Comment by bjiyxo** [comment]
It's anybody's guess.

**Comment by davidye2020** [comment]
anyone else can do this since bjiyxo obviously for whatever reasons stated he does not want to try?

**Comment by davidye2020** [comment]
AQ just got a mobile version and I think Leela needs to come up with something innvotive or different to complete successfully

**Comment by dtracers** [comment]
LeelaZ is already successful.

But anyways tensorflow works just fine on Windows it is fairly easy to setup just make sure you are using the correct cudann library.
Also if you have Windows you could always install Linux along side it and then run it in Linux.

Additionally I do think we should do n2n from the lastest SWA nets.  In alpha zero each net was based on the immediately preceding net and we should follow the same.

**Comment by hydrogenpi** [comment]
Yes, I agree LZ is already successful, so perhaps I did poor choice of words. I want LZ to become even more stronger, and the ideal is to be the first open source, open weights, free go AI bot to reach superhuman status, or to get as close to it as possible anyway. (while being the more commonly used, massly adopted, program out there) 

I'm not sure why so many people seem to be against the idea of redoing what the OP in that other thread already did, but just for a more recent thread. Sure it might not be much stronger, but what harm is it to do it and test to see?

**Comment by AncalagonX** [comment]
> Actually, there are some severe issues in my 20b 256f net, and the most important thing is that it cannot read most ladder in <10000 po. I'm not sure how to solve this.

@bjiyxo Are you saying your net can't generate an accurate ladder sequence reading in <10k playouts? Or that it won't select a DIFFERENT move than just playing out the ladder?

I did a "failed ladder" test with your posted 20x256 net, using 1) vanilla LZv13 unmodified, and 2) a slightly modified version of my own that values winrate more than visit count. In my tests, your bot had read the ladder sequence as fast as any other net (within a few hundred playouts).

````Playouts: 707, Win: 31.44%, PV: G14 F13 F12 G13 H13 G12 G11 H12 J12 H11 H10 J11 K11 J10 J9 K10 L10 K9 K8 L9 M9 L8 L7 M8 N8 M7 M6 N7 O7 N6 N5 O6 P6 O5 O4 P5 Q5 P4 Q4 P3 Q3````

Using LZv13 unmodified, your bot pointlessly played the failed ladder to the end and resigned, just like every single 10x128 LZ net and otherwise.

Using my modified LZ version, your bot read the ladder and instead played a ladder breaker clear across the board and forced the other player to capture the ladder. Your bot kept a 5% winrate by playing this move instead of the ladder, and built this up into an 8% winrate after several dozen more moves (at which point I stopped the test).

I don't think your net's ladder problem is a problem with the net--it's a problem with MCTS move selection.

**Comment by idoavidan** [comment]
keep in mind a new network have +-30% winrate variance so you kind of bet your money

**Comment by gcp** [comment]
> its impossible to get this to work in Windows (I blame Google's TensorFlow incompat with Windows)

TensorFlow works perfectly on Windows, the failing is all yours.

**Comment by gcp** [comment]
I don't think this kind of offer is appropriate here, FWIW. This is not a job board.

**Comment by hydrogenpi** [comment]
@ AncalagonX  weren't u gonna update yhour post with teh code fix?
