### ISSUE TITLE
New promotion scheme - a simple idea 

### ISSUE THREAD

**Issue by hydrogenpi** [gcp/leela-zero#1136]
An idea would be that if no new net has promoted within the last 24 hours span, then out of all the ones that failed, look at the ones that were at least 50% and above, and pick the highest ranked one and play that out to 1000 games and if it is still above 50% then promote it.  or alternatively play the last three highest % to 1000 games and without question, whichone ends up with the highest % will getr automatically promoted. 

This means unless there is some massive failure, we will almost always get at least one new net a day.

**Comment by StanTraykov** [comment]
What is the primary aim of this suggestion? To increase the rate of promotions or to increase the rate of actually improving? The former is not an end in itself. The latter does not follow directly, so why do you think it will be influenced positively with high certainty? Currently, SPRT and the 55%/400 rule promote when there is pretty high confidence. An additional >50%/1000 rule, as suggested, would allow nets to be promoted for which there is little confidence that they are actually better (just a higher likelihood).

**Comment by hydrogenpi** [comment]
So imagine this analogy, pretend we set promotion to 90%, had we done that, right now LZ will still be stuck in low dan level... by getting closer to the 51% mark, and difficulty becomes higher, it is more efficenct. 55% gating is not efficent when progress is glacier.

**Comment by hydrogenpi** [comment]
https://github.com/ymgaq/AQ/issues/97

**Comment by hydrogenpi** [comment]
what happened to all the talks about lowering gating, removing gating and switching to always promote, going to 192 filters, going to 20 blocks, etc etc ? @alreadydone

**Comment by herazul** [comment]
It takes a lot of times to understand things, test ideas, train new net, ....
You can't throw money and frustration at things until it's done, you have to be a little patient and trust GCP.

**Comment by hydrogenpi** [comment]
![image](https://user-images.githubusercontent.com/35181396/38220005-1f5c75f2-368d-11e8-8c7d-09465dc865f0.png)

**Comment by nathanloop** [comment]
"If the new player wins by a margin of > 55% (to avoid selecting on noise alone) then it becomes the best player αθ∗ , and is subsequently used for self-play generation, and also becomes the baseline for subsequent comparisons."

https://deepmind.com/documents/119/agz_unformatted_nature.pdf

**Comment by Mardak** [comment]
![image](https://user-images.githubusercontent.com/35181396/38221750-07299f60-3696-11e8-964d-bc6ed2aa9f63.png)

Thanks for the graph. There's been someone complaining about a flatline for what feels like months now, but clearly the red lines show a positive slope. Hopefully this graph gets to that person so we can stop hearing all the constant complaints.

**Comment by holicst** [comment]
I won't be surprised if Hydrogenpi would be quantum_entropy from /cbaduk subreddit :DDD

He thinks that a car should accelerate from 300 km/h just like from 0 🤡

**Comment by gcp** [comment]
We will try always promote if regular progress stalls, I see no reason to believe other methods are superior, particularly more complicated ones that don't bring any benefit.
