### ISSUE TITLE
Parameters for Playing Against Other Bots/Setup for Sabaki

### ISSUE THREAD

**Issue by laefsky** [gcp/leela-zero#1142]
What are the current setup details and gtp parameters to play leelaz as one of the bots in Sabaki.  A separate issue is Norton autodeletes some of the leelaz components as "dangerous"

**Comment by bastiaf** [comment]
I use these arguments:
`--gtp --threads 8 --noponder --weights networks/2e3863edbb0e18f198e2e76d50529931c17f17f01c7468c992afd9b33f4d5379`

For the threads parameter the number of CPU cores works fine for me. You can also test which number of threads give you the best result by calling leelaz with the benchmark option:
`./leelaz.exe --benchmark --weights networks/2e3863edbb0e18f198e2e76d50529931c17f17f01c7468c992afd9b33f4d5379 --threads 8`

Additionally you can add an initial GPG command in Sabaki, for example to define some time settings:
`time_settings 0 30 1`
(0 seconds main time, 30 seconds byoyomi, 1 period)

**Comment by Tsun-hung** [comment]
I tried the argument --benchmark just now, and something funny arises.
![qq 20180404083628](https://user-images.githubusercontent.com/33803485/38282658-e6c17b22-37e3-11e8-8a17-a7c5139448a7.png)
I make a mental calculation and find It will take one month : )

**Comment by laefsky** [comment]
I am having a problem with genmove b on the first move with leelaz using the 

Parameters below: I have no such problem with leela 11 or other engines like AQ or GnuGo

I use these arguments:
--gtp --threads 8 --noponder --weights networks/2e3863edbb0e18f198e2e76d50529931c17f17f01c7468c992afd9b33f4d5379

For the threads parameter the number of CPU cores works fine for me. You can also test which number of threads give you the best result by calling leelaz with the benchmark option:
./leelaz.exe --benchmark --weights networks/2e3863edbb0e18f198e2e76d50529931c17f17f01c7468c992afd9b33f4d5379 --threads 8

Additionally you can add an initial GPG command in Sabaki, for example to define some time settings:
time_settings 0 30 1
(0 seconds main time, 30 seconds byoyomi, 1 period)

**Comment by gcp** [comment]
Closing because another issue with the same problem was filed.
