### ISSUE TITLE
Norton Security Autodeletes Part of Leela Zero

### ISSUE THREAD

**Issue by laefsky** [gcp/leela-zero#1143]
Norton Security quarantines and autodeletes leelaz and autogtp and some dlls from leela after I unzip the files, any suggestions?

**Comment by Friday9i** [comment]
Change your AV : -)

**Comment by ihavnoid** [comment]
I guess you should contact Symantec?

**Comment by billyswong** [comment]
1. Change setting to deny/quarentine and never autodelete (there are multiple settings that will trigger such stupid behaviour, dig all of them out)
2. Add the whole folder which the files extracted to as scanning exception

**Comment by hydrogenpi** [comment]
Choose a better product or don't use that sort of AV

Cylance is better. 
Or just scan everything with virustotal and don't even bother with AV

**Comment by gcp** [comment]
This is a bug in Norton, not in Leela Zero.
