### ISSUE TITLE
genmove B on first move sabaki leelaz 0.13

### ISSUE THREAD

**Issue by laefsky** [gcp/leela-zero#1144]
I am having a problem with genmove B on the first move with leelaz using the 
Parameters below: I have no such problem with leela 11 or other engines like AQ or GnuGo
I use these arguments:
--gtp --threads 8 --noponder --weights networks/2e3863edbb0e18f198e2e76d50529931c17f17f01c7468c992afd9b33f4d5379
For the threads parameter the number of CPU cores works fine for me. You can also test which number of threads give you the best result by calling leelaz with the benchmark option:
./leelaz.exe --benchmark --weights networks/2e3863edbb0e18f198e2e76d50529931c17f17f01c7468c992afd9b33f4d5379 --threads 8
Additionally you can add an initial GPG command in Sabaki, for example to define some time settings:
time_settings 0 30 1
(0 seconds main time, 30 seconds byoyomi, 1 period)

**Comment by laefsky** [comment]
GTP says connection error on leela zero even if I give full command path for weights RE: [gcp/leela-zero] genmove B on first move sabaki leelaz 0.13 (#1144)

**Comment by hydrogenpi** [comment]
see screenshot try to make this for kicks I just tested so I know its working

![image](https://user-images.githubusercontent.com/35181396/38288620-b1e2966e-3786-11e8-9d25-e9d319bab4c0.png)

**Comment by hydrogenpi** [comment]
try "-w" instead of "-weights"

**Comment by laefsky** [comment]
tried -w tried renaming to network still getting "connection error" on gtp console on sabaki with leelaz

**Comment by laefsky** [comment]
Fixed Command path error for leelaz.exe YAY RE: tried -w tried renaming to network still getting "connection error" on gtp console on sabaki with leelaz RE: [gcp/leela-zero] genmove B on first move sabaki leelaz 0.13 (#1144)

 

From: Ira Laefsky [mailto:laefsky@comcast.net] 
Sent: Wednesday, April 4, 2018 12:48 AM
To: 'gcp/leela-zero' <reply@reply.github.com>; 'gcp/leela-zero' <leela-zero@noreply.github.com>; 'Ira Laefsky' <laefsky@comcast.net>
Cc: 'Author' <author@noreply.github.com>
Subject: tried -w tried renaming to network still getting "connection error" on gtp console on sabaki with leelaz RE: [gcp/leela-zero] genmove B on first move sabaki leelaz 0.13 (#1144)

 

tried -w tried renaming to network still getting "connection error" on gtp console on sabaki with leelaz

**Comment by d7urban** [comment]
That error is given when you give the wrong parameters (or even if you give
the right ones more than once). I suggest running leelaz.exe -h to see
which are supported.

**Comment by AncalagonX** [comment]
1) Download the weights file from the server.
2) Unzip the file you downloaded.
3) Take the .txt file from the folder, put it somewhere (recommend same folder as leelaz.exe)
4) --weights nameofweightfile.txt <--- DON'T FORGET THE .txt EXTENSION
5) It will work now
