### ISSUE TITLE
leelaz (next) fails to build on linux mint 18.3

### ISSUE THREAD

**Issue by ashinpan** [gcp/leela-zero#1147]
What follows is the log:

========================

pan@pan-desktop ~/devel-leela/src $ make
Detected OS: Linux
make CC=gcc CXX=g++ \
	CXXFLAGS='-I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG'  \
	LDFLAGS=' -flto -g' \
	leelaz
make[1]: Entering directory '/home/pan/devel-leela/src'
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Network.o Network.cpp
In file included from OpenCL.h:27:0,
                 from OpenCLScheduler.h:26,
                 from Network.cpp:45:
./CL/cl2.hpp:5855:63: warning: ignoring attributes on template argument ‘cl_int {aka int}’ [-Wignored-attributes]
     typename std::enable_if<!std::is_pointer<T>::value, cl_int>::type
                                                               ^
./CL/cl2.hpp:6155:22: warning: ignoring attributes on template argument ‘cl_int {aka int}’ [-Wignored-attributes]
         vector<cl_int>* binaryStatus = NULL,
                      ^
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o FullBoard.o FullBoard.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o KoState.o KoState.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Training.o Training.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o TimeControl.o TimeControl.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o UCTSearch.o UCTSearch.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o GameState.o GameState.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Leela.o Leela.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o SGFParser.o SGFParser.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Timing.o Timing.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Utils.o Utils.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o FastBoard.o FastBoard.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o SGFTree.o SGFTree.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Zobrist.o Zobrist.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o FastState.o FastState.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o GTP.o GTP.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Random.o Random.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o SMP.o SMP.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o UCTNode.o UCTNode.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o UCTNodeRoot.o UCTNodeRoot.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o OpenCL.o OpenCL.cpp
In file included from OpenCL.h:27:0,
                 from OpenCL.cpp:22:
./CL/cl2.hpp:5855:63: warning: ignoring attributes on template argument ‘cl_int {aka int}’ [-Wignored-attributes]
     typename std::enable_if<!std::is_pointer<T>::value, cl_int>::type
                                                               ^
./CL/cl2.hpp:6155:22: warning: ignoring attributes on template argument ‘cl_int {aka int}’ [-Wignored-attributes]
         vector<cl_int>* binaryStatus = NULL,
                      ^
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o OpenCLScheduler.o OpenCLScheduler.cpp
In file included from OpenCL.h:27:0,
                 from OpenCLScheduler.h:26,
                 from OpenCLScheduler.cpp:23:
./CL/cl2.hpp:5855:63: warning: ignoring attributes on template argument ‘cl_int {aka int}’ [-Wignored-attributes]
     typename std::enable_if<!std::is_pointer<T>::value, cl_int>::type
                                                               ^
./CL/cl2.hpp:6155:22: warning: ignoring attributes on template argument ‘cl_int {aka int}’ [-Wignored-attributes]
         vector<cl_int>* binaryStatus = NULL,
                      ^
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o NNCache.o NNCache.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Tuner.o Tuner.cpp
In file included from OpenCL.h:27:0,
                 from Tuner.cpp:33:
./CL/cl2.hpp:5855:63: warning: ignoring attributes on template argument ‘cl_int {aka int}’ [-Wignored-attributes]
     typename std::enable_if<!std::is_pointer<T>::value, cl_int>::type
                                                               ^
./CL/cl2.hpp:6155:22: warning: ignoring attributes on template argument ‘cl_int {aka int}’ [-Wignored-attributes]
         vector<cl_int>* binaryStatus = NULL,
                      ^
g++ -flto -g -o leelaz Network.o FullBoard.o KoState.o Training.o TimeControl.o UCTSearch.o GameState.o Leela.o SGFParser.o Timing.o Utils.o FastBoard.o SGFTree.o Zobrist.o FastState.o GTP.o Random.o SMP.o UCTNode.o UCTNodeRoot.o OpenCL.o OpenCLScheduler.o NNCache.o Tuner.o  -lboost_program_options -lpthread -lz -lopenblas -lOpenCL
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `void std::_Destroy<UCTNodePointer>(UCTNodePointer*)':
/usr/include/c++/7/bits/stl_construct.h:98: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `void std::_Construct<UCTNodePointer, UCTNodePointer>(UCTNodePointer*, UCTNodePointer&&)':
/usr/include/c++/7/bits/stl_construct.h:75: undefined reference to `UCTNodePointer::UCTNodePointer(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `void std::_Destroy<UCTNodePointer>(UCTNodePointer*)':
/usr/include/c++/7/bits/stl_construct.h:98: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/usr/include/c++/7/bits/stl_construct.h:98: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/usr/include/c++/7/bits/stl_construct.h:98: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `NodeComp::operator()(UCTNodePointer const&, UCTNodePointer const&)':
/home/pan/devel-leela/src/UCTNode.cpp:294: undefined reference to `UCTNodePointer::get_visits() const'
/home/pan/devel-leela/src/UCTNode.cpp:294: undefined reference to `UCTNodePointer::get_visits() const'
/home/pan/devel-leela/src/UCTNode.cpp:295: undefined reference to `UCTNodePointer::get_visits() const'
/home/pan/devel-leela/src/UCTNode.cpp:295: undefined reference to `UCTNodePointer::get_visits() const'
/home/pan/devel-leela/src/UCTNode.cpp:299: undefined reference to `UCTNodePointer::get_visits() const'
/home/pan/devel-leela/src/UCTNode.cpp:304: undefined reference to `UCTNodePointer::get_eval(int) const'
/home/pan/devel-leela/src/UCTNode.cpp:304: undefined reference to `UCTNodePointer::get_eval(int) const'
/home/pan/devel-leela/src/UCTNode.cpp:300: undefined reference to `UCTNodePointer::get_score() const'
/home/pan/devel-leela/src/UCTNode.cpp:300: undefined reference to `UCTNodePointer::get_score() const'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `__insertion_sort':
/usr/include/c++/7/bits/stl_algo.h:1850: undefined reference to `UCTNodePointer::UCTNodePointer(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `__copy_move_b':
/usr/include/c++/7/bits/stl_algobase.h:548: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `__insertion_sort':
/usr/include/c++/7/bits/stl_algo.h:1852: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `__unguarded_linear_insert':
/usr/include/c++/7/bits/stl_algo.h:1825: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/usr/include/c++/7/bits/stl_algo.h:1825: undefined reference to `UCTNodePointer::UCTNodePointer(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `NodeComp::operator()(UCTNodePointer const&, UCTNodePointer const&)':
/home/pan/devel-leela/src/UCTNode.cpp:295: undefined reference to `UCTNodePointer::get_visits() const'
/home/pan/devel-leela/src/UCTNode.cpp:295: undefined reference to `UCTNodePointer::get_visits() const'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `__unguarded_linear_insert':
/usr/include/c++/7/bits/stl_algo.h:1830: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `NodeComp::operator()(UCTNodePointer const&, UCTNodePointer const&)':
/home/pan/devel-leela/src/UCTNode.cpp:294: undefined reference to `UCTNodePointer::get_visits() const'
/home/pan/devel-leela/src/UCTNode.cpp:294: undefined reference to `UCTNodePointer::get_visits() const'
/home/pan/devel-leela/src/UCTNode.cpp:299: undefined reference to `UCTNodePointer::get_visits() const'
/home/pan/devel-leela/src/UCTNode.cpp:304: undefined reference to `UCTNodePointer::get_eval(int) const'
/home/pan/devel-leela/src/UCTNode.cpp:304: undefined reference to `UCTNodePointer::get_eval(int) const'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `__unguarded_linear_insert':
/usr/include/c++/7/bits/stl_algo.h:1834: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `NodeComp::operator()(UCTNodePointer const&, UCTNodePointer const&)':
/home/pan/devel-leela/src/UCTNode.cpp:300: undefined reference to `UCTNodePointer::get_score() const'
/home/pan/devel-leela/src/UCTNode.cpp:300: undefined reference to `UCTNodePointer::get_score() const'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `__insertion_sort':
/usr/include/c++/7/bits/stl_algo.h:1850: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `__move_merge':
/usr/include/c++/7/bits/stl_algo.h:2647: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `NodeComp::operator()(UCTNodePointer const&, UCTNodePointer const&)':
/home/pan/devel-leela/src/UCTNode.cpp:294: undefined reference to `UCTNodePointer::get_visits() const'
/home/pan/devel-leela/src/UCTNode.cpp:294: undefined reference to `UCTNodePointer::get_visits() const'
/home/pan/devel-leela/src/UCTNode.cpp:295: undefined reference to `UCTNodePointer::get_visits() const'
/home/pan/devel-leela/src/UCTNode.cpp:295: undefined reference to `UCTNodePointer::get_visits() const'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `__move_merge':
/usr/include/c++/7/bits/stl_algo.h:2652: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `__copy_m':
/usr/include/c++/7/bits/stl_algobase.h:343: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/usr/include/c++/7/bits/stl_algobase.h:343: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `__move_merge':
/usr/include/c++/7/bits/stl_algo.h:2647: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `NodeComp::operator()(UCTNodePointer const&, UCTNodePointer const&)':
/home/pan/devel-leela/src/UCTNode.cpp:294: undefined reference to `UCTNodePointer::get_visits() const'
/home/pan/devel-leela/src/UCTNode.cpp:294: undefined reference to `UCTNodePointer::get_visits() const'
/home/pan/devel-leela/src/UCTNode.cpp:295: undefined reference to `UCTNodePointer::get_visits() const'
/home/pan/devel-leela/src/UCTNode.cpp:295: undefined reference to `UCTNodePointer::get_visits() const'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `__move_merge':
/usr/include/c++/7/bits/stl_algo.h:2652: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `__copy_m':
/usr/include/c++/7/bits/stl_algobase.h:343: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/usr/include/c++/7/bits/stl_algobase.h:343: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `NodeComp::operator()(UCTNodePointer const&, UCTNodePointer const&)':
/home/pan/devel-leela/src/UCTNode.cpp:299: undefined reference to `UCTNodePointer::get_visits() const'
/home/pan/devel-leela/src/UCTNode.cpp:304: undefined reference to `UCTNodePointer::get_eval(int) const'
/home/pan/devel-leela/src/UCTNode.cpp:304: undefined reference to `UCTNodePointer::get_eval(int) const'
/home/pan/devel-leela/src/UCTNode.cpp:300: undefined reference to `UCTNodePointer::get_score() const'
/home/pan/devel-leela/src/UCTNode.cpp:300: undefined reference to `UCTNodePointer::get_score() const'
/home/pan/devel-leela/src/UCTNode.cpp:299: undefined reference to `UCTNodePointer::get_visits() const'
/home/pan/devel-leela/src/UCTNode.cpp:304: undefined reference to `UCTNodePointer::get_eval(int) const'
/home/pan/devel-leela/src/UCTNode.cpp:304: undefined reference to `UCTNodePointer::get_eval(int) const'
/home/pan/devel-leela/src/UCTNode.cpp:300: undefined reference to `UCTNodePointer::get_score() const'
/home/pan/devel-leela/src/UCTNode.cpp:300: undefined reference to `UCTNodePointer::get_score() const'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `void std::_Construct<UCTNodePointer, UCTNodePointer>(UCTNodePointer*, UCTNodePointer&&)':
/usr/include/c++/7/bits/stl_construct.h:75: undefined reference to `UCTNodePointer::UCTNodePointer(UCTNodePointer&&)'
/usr/include/c++/7/bits/stl_construct.h:75: undefined reference to `UCTNodePointer::UCTNodePointer(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `__ucr':
/usr/include/c++/7/bits/stl_tempbuf.h:201: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `void std::_Destroy<UCTNodePointer>(UCTNodePointer*)':
/usr/include/c++/7/bits/stl_construct.h:98: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `void __gnu_cxx::new_allocator<UCTNodePointer>::construct<UCTNodePointer, int const&, float const&>(UCTNodePointer*, int const&, float const&)':
/usr/include/c++/7/ext/new_allocator.h:136: undefined reference to `UCTNodePointer::UCTNodePointer(short, float)'
/usr/include/c++/7/ext/new_allocator.h:136: undefined reference to `UCTNodePointer::UCTNodePointer(short, float)'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `void std::_Destroy<UCTNodePointer>(UCTNodePointer*)':
/usr/include/c++/7/bits/stl_construct.h:98: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `void __gnu_cxx::new_allocator<UCTNodePointer>::destroy<UCTNodePointer>(UCTNodePointer*)':
/usr/include/c++/7/ext/new_allocator.h:140: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/tmp/cc9dMwb5.ltrans1.ltrans.o: In function `void std::_Destroy<UCTNodePointer>(UCTNodePointer*)':
/usr/include/c++/7/bits/stl_construct.h:98: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/usr/include/c++/7/bits/stl_construct.h:98: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/tmp/cc9dMwb5.ltrans2.ltrans.o: In function `void std::_Destroy<UCTNodePointer>(UCTNodePointer*)':
/usr/include/c++/7/bits/stl_construct.h:98: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/tmp/cc9dMwb5.ltrans2.ltrans.o: In function `tree_stats_helper':
/home/pan/devel-leela/src/UCTSearch.cpp:214: undefined reference to `UCTNodePointer::get_visits() const'
/tmp/cc9dMwb5.ltrans2.ltrans.o: In function `void std::_Destroy<UCTNodePointer>(UCTNodePointer*)':
/usr/include/c++/7/bits/stl_construct.h:98: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/tmp/cc9dMwb5.ltrans2.ltrans.o: In function `get_best_root_child':
/home/pan/devel-leela/src/UCTNode.cpp:321: undefined reference to `UCTNodePointer::inflate() const'
/tmp/cc9dMwb5.ltrans2.ltrans.o: In function `find_child':
/home/pan/devel-leela/src/UCTNodeRoot.cpp:148: undefined reference to `UCTNodePointer::get_move() const'
/home/pan/devel-leela/src/UCTNodeRoot.cpp:150: undefined reference to `UCTNodePointer::inflate() const'
/tmp/cc9dMwb5.ltrans2.ltrans.o: In function `uct_select_child':
/home/pan/devel-leela/src/UCTNode.cpp:242: undefined reference to `UCTNodePointer::valid() const'
/home/pan/devel-leela/src/UCTNode.cpp:243: undefined reference to `UCTNodePointer::get_visits() const'
/home/pan/devel-leela/src/UCTNode.cpp:244: undefined reference to `UCTNodePointer::get_visits() const'
/home/pan/devel-leela/src/UCTNode.cpp:245: undefined reference to `UCTNodePointer::get_score() const'
/home/pan/devel-leela/src/UCTNode.cpp:268: undefined reference to `UCTNodePointer::get_eval(int) const'
/home/pan/devel-leela/src/UCTNode.cpp:270: undefined reference to `UCTNodePointer::get_score() const'
/home/pan/devel-leela/src/UCTNode.cpp:271: undefined reference to `UCTNodePointer::get_visits() const'
/home/pan/devel-leela/src/UCTNode.cpp:262: undefined reference to `UCTNodePointer::active() const'
/home/pan/devel-leela/src/UCTNode.cpp:267: undefined reference to `UCTNodePointer::get_visits() const'
/home/pan/devel-leela/src/UCTNode.cpp:283: undefined reference to `UCTNodePointer::inflate() const'
/tmp/cc9dMwb5.ltrans2.ltrans.o: In function `inflate_all_children':
/home/pan/devel-leela/src/UCTNodeRoot.cpp:162: undefined reference to `UCTNodePointer::inflate() const'
/tmp/cc9dMwb5.ltrans2.ltrans.o: In function `get_best_root_child':
/home/pan/devel-leela/src/UCTNode.cpp:321: undefined reference to `UCTNodePointer::inflate() const'
/tmp/cc9dMwb5.ltrans2.ltrans.o: In function `inflate_all_children':
/home/pan/devel-leela/src/UCTNodeRoot.cpp:162: undefined reference to `UCTNodePointer::inflate() const'
/tmp/cc9dMwb5.ltrans3.ltrans.o: In function `void std::_Destroy<UCTNodePointer>(UCTNodePointer*)':
/usr/include/c++/7/bits/stl_construct.h:98: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/tmp/cc9dMwb5.ltrans4.ltrans.o: In function `std::enable_if<std::__and_<std::__not_<std::__is_tuple_like<UCTNodePointer> >, std::is_move_constructible<UCTNodePointer>, std::is_move_assignable<UCTNodePointer> >::value, void>::type std::swap<UCTNodePointer>(UCTNodePointer&, UCTNodePointer&)':
/usr/include/c++/7/bits/move.h:198: undefined reference to `UCTNodePointer::UCTNodePointer(UCTNodePointer&&)'
/usr/include/c++/7/bits/move.h:199: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/usr/include/c++/7/bits/move.h:200: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/usr/include/c++/7/bits/move.h:198: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/usr/include/c++/7/bits/move.h:198: undefined reference to `UCTNodePointer::UCTNodePointer(UCTNodePointer&&)'
/usr/include/c++/7/bits/move.h:199: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/usr/include/c++/7/bits/move.h:200: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/usr/include/c++/7/bits/move.h:198: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/usr/include/c++/7/bits/move.h:198: undefined reference to `UCTNodePointer::UCTNodePointer(UCTNodePointer&&)'
/usr/include/c++/7/bits/move.h:199: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/usr/include/c++/7/bits/move.h:200: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/usr/include/c++/7/bits/move.h:198: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/usr/include/c++/7/bits/move.h:198: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/tmp/cc9dMwb5.ltrans5.ltrans.o: In function `_ZSt11__remove_ifIN9__gnu_cxx17__normal_iteratorIP14UCTNodePointerSt6vectorIS2_SaIS2_EEEENS0_5__ops10_Iter_predIZN7UCTNode13kill_superkosERK7KoStateEUlRKT_E_EEESE_SE_SE_T0_.isra.31':
/usr/include/c++/7/bits/stl_algo.h:871: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans5.ltrans.o: In function `UCTNodePointer* std::__copy_move<true, false, std::random_access_iterator_tag>::__copy_m<UCTNodePointer*, UCTNodePointer*>(UCTNodePointer*, UCTNodePointer*, UCTNodePointer*)':
/usr/include/c++/7/bits/stl_algobase.h:343: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans5.ltrans.o: In function `void std::_Destroy<UCTNodePointer>(UCTNodePointer*)':
/usr/include/c++/7/bits/stl_construct.h:98: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/tmp/cc9dMwb5.ltrans5.ltrans.o: In function `UCTNode::count_nodes() const [clone .part.15]':
/home/pan/devel-leela/src/UCTNode.cpp:330: undefined reference to `UCTNodePointer::get_visits() const'
/tmp/cc9dMwb5.ltrans5.ltrans.o: In function `count_nodes':
/home/pan/devel-leela/src/UCTNode.cpp:330: undefined reference to `UCTNodePointer::get_visits() const'
/tmp/cc9dMwb5.ltrans5.ltrans.o: In function `std::reverse_iterator<__gnu_cxx::__normal_iterator<UCTNodePointer*, std::vector<UCTNodePointer, std::allocator<UCTNodePointer> > > > std::__move_merge<UCTNodePointer*, std::reverse_iterator<__gnu_cxx::__normal_iterator<UCTNodePointer*, std::vector<UCTNodePointer, std::allocator<UCTNodePointer> > > >, __gnu_cxx::__ops::_Iter_comp_iter<NodeComp> >(UCTNodePointer*, UCTNodePointer*, UCTNodePointer*, UCTNodePointer*, std::reverse_iterator<__gnu_cxx::__normal_iterator<UCTNodePointer*, std::vector<UCTNodePointer, std::allocator<UCTNodePointer> > > >, __gnu_cxx::__ops::_Iter_comp_iter<NodeComp>)':
/usr/include/c++/7/bits/stl_algo.h:2647: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans5.ltrans.o: In function `__copy_m':
/usr/include/c++/7/bits/stl_algobase.h:343: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/usr/include/c++/7/bits/stl_algobase.h:343: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans5.ltrans.o: In function `std::reverse_iterator<__gnu_cxx::__normal_iterator<UCTNodePointer*, std::vector<UCTNodePointer, std::allocator<UCTNodePointer> > > > std::__move_merge<UCTNodePointer*, std::reverse_iterator<__gnu_cxx::__normal_iterator<UCTNodePointer*, std::vector<UCTNodePointer, std::allocator<UCTNodePointer> > > >, __gnu_cxx::__ops::_Iter_comp_iter<NodeComp> >(UCTNodePointer*, UCTNodePointer*, UCTNodePointer*, UCTNodePointer*, std::reverse_iterator<__gnu_cxx::__normal_iterator<UCTNodePointer*, std::vector<UCTNodePointer, std::allocator<UCTNodePointer> > > >, __gnu_cxx::__ops::_Iter_comp_iter<NodeComp>)':
/usr/include/c++/7/bits/stl_algo.h:2652: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans5.ltrans.o: In function `std::enable_if<std::__and_<std::__not_<std::__is_tuple_like<UCTNodePointer> >, std::is_move_constructible<UCTNodePointer>, std::is_move_assignable<UCTNodePointer> >::value, void>::type std::swap<UCTNodePointer>(UCTNodePointer&, UCTNodePointer&)':
/usr/include/c++/7/bits/move.h:198: undefined reference to `UCTNodePointer::UCTNodePointer(UCTNodePointer&&)'
/usr/include/c++/7/bits/move.h:199: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/usr/include/c++/7/bits/move.h:200: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/usr/include/c++/7/bits/move.h:198: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/usr/include/c++/7/bits/move.h:198: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/tmp/cc9dMwb5.ltrans5.ltrans.o: In function `void std::_Construct<UCTNodePointer, UCTNodePointer>(UCTNodePointer*, UCTNodePointer&&)':
/usr/include/c++/7/bits/stl_construct.h:75: undefined reference to `UCTNodePointer::UCTNodePointer(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans5.ltrans.o: In function `void std::_Destroy<UCTNodePointer>(UCTNodePointer*)':
/usr/include/c++/7/bits/stl_construct.h:98: undefined reference to `UCTNodePointer::~UCTNodePointer()'
/tmp/cc9dMwb5.ltrans5.ltrans.o: In function `__copy_m':
/usr/include/c++/7/bits/stl_algobase.h:343: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans5.ltrans.o: In function `__move_merge_adaptive_backward':
/usr/include/c++/7/bits/stl_algo.h:2351: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/usr/include/c++/7/bits/stl_algo.h:2361: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans5.ltrans.o: In function `__copy_m':
/usr/include/c++/7/bits/stl_algobase.h:343: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans5.ltrans.o: In function `__move_merge_adaptive':
/usr/include/c++/7/bits/stl_algo.h:2312: undefined reference to `UCTNodePointer::operator=(UCTNodePointer&&)'
/tmp/cc9dMwb5.ltrans5.ltrans.o:/usr/include/c++/7/bits/stl_algo.h:2317: more undefined references to `UCTNodePointer::operator=(UCTNodePointer&&)' follow
collect2: error: ld returned 1 exit status
Makefile:64: recipe for target 'leelaz' failed
make[1]: *** [leelaz] Error 1
make[1]: Leaving directory '/home/pan/devel-leela/src'
Makefile:4: recipe for target 'default' failed
make: *** [default] Error 2
pan@pan-desktop ~/devel-leela/src $

**Comment by Mardak** [comment]
Probably #1140

**Comment by ashinpan** [comment]
@Mardak  I have tried to use cmake, but failed again: 

"CMake Error at /usr/share/cmake-3.5/Modules/FindBLAS.cmake:681 (message):
  A required library with BLAS API not found.  Please specify library
  location.
Call Stack (most recent call first):
  CMakeLists.txt:33 (FIND_PACKAGE)"

But I have already installed openblas 0.2.18 (both base and development files).

**Comment by ashinpan** [comment]
Perhaps the culprit is this commit: https://github.com/gcp/leela-zero/commit/8a1a3f448583903aef9857ae1fe9b1455a102a3a
