### ISSUE TITLE
Out of range exception in leela-zero

### ISSUE THREAD

**Issue by Cabu** [gcp/leela-zero#1149]
Building the DEBUG version of leela zero in VS 2017. I have an array subscript out of range exception in void Network::winograd_transform_in on line 484 of network.cpp.
```
T1[0][3] = in_pad[yin + 0][xin + 3] - in_pad[yin + 2][xin + 3];
```
Where yin = 0 and xin = 18 
But in_pad[yin+0] and in_pad[yin+2] contain only 21 elements each...

Not understanding what that function does, I can't go further :(

**Comment by gcp** [comment]
Ugh, gcc doesn't bounds check std::arrays when they are used with [].

**Comment by gcp** [comment]
Does backing out https://github.com/gcp/leela-zero/commit/35464338b02036754660fe431df00499ed819bfd fix this?

**Comment by gcp** [comment]
@Hersmunch you might want to have a look.

**Comment by Cabu** [comment]
Reverting 3546433 only for the function Network::winograd_transform_in doesn't trigger any error during a game.

@Hersmunch 
One more note: The error is not systematically triggered. But should be during the play of the first 3 moves of a game started without limiting Playouts or Visits.

**Comment by gcp** [comment]
It's in the CPU code, so it gets triggered when a self-check is done. You should be able to force it always when disabling USE_OPENCL.

**Comment by gcp** [comment]
I have a feeling std::array<std::array<float, W + 2>, H + 2> in_pad; should have used ```+WINOGRAD_ALPHA``` instead of +2 but I'm not sure nothing else was missed here.

**Comment by Hersmunch** [comment]
I’m away camping so can’t do anything until Monday or Tuesday.

I missed that the padded array needs to be one larger in each dimension as the top edge tiles cover two on the board squares and two zeros (not one like the bottom edges). I don’t know how the winograd alpha is related to how many squares the tiles overlap so I’m not sure how to size the padding array.
Sorry about this and that I can’t help out much right now.
