### ISSUE TITLE
Golaxy vs LeelaZero - matchs discussion (old mascot thread)

### ISSUE THREAD

**Issue by herazul** [gcp/leela-zero#1150]
I ask because of the reddit thread. I know GCP use a nibbler pick, but is this the official project's mascot ? Is this legal if used elsewhere for publicity ? (copyright law isn't famous for being nice and understanding)

**Comment by herazul** [comment]
Ok, i get it.

The thread was made because there is a chinese match coming between leelaZero and Golaxy, a new chinese bot.
And the logo they used for leelaZ is... well... funny at least :D 

![Golaxy VS LeelaZero](https://i.imgur.com/VQOYxYK.png "Golaxy VS LeelaZero")

**Comment by bood** [comment]
@herazul When LeelaZero bot account was created at yikeweiqi.com, they asked for a avatar, so this one is used since it was the favorite joseki of LeelaZero at that time. LOL

**Comment by herazul** [comment]
@bood Whoever had the idea is a genius :D

**Comment by roy7** [comment]
I find the use of that joseki as LZ's avatar for that match appropriate and funny. :) I assume they'll load in whatever the most recent official network is right before the start of the match? There are stronger networks like 00335835 but those aren't "official" ones in actual use though.

**Comment by herazul** [comment]
I don't know what they will use. I can't contact them to ask, i don't speak Chinese at all =)

**Comment by gcp** [comment]
>There are stronger networks like 00335835

It's very questionable they are stronger in real conditions, see the latest test I posted. They're weaker in real match conditions.

**Comment by bood** [comment]
> I don't know what they will use. I can't contact them to ask, i don't speak Chinese at all =)

I can update the status of the match here, maybe in a separate issue when things are more clear.

> It's very questionable they are stronger in real conditions, see the latest test I posted. They get 5 times less playouts and this hurts strength a lot.

I think it is possible to be stronger than the 10x128 network if a minimum playouts is reached, say 10k? Just my guess.

**Comment by herazul** [comment]
I don't think that's true on big hardware. I assume they are gonna use something big like amazon 4xV100 or something, where the 20x256 is gonna crush the 10x128 whatever the timesetting is.

**Comment by roy7** [comment]
I assume it'll be using normal time rules and no visit/playout cap at all. So it just comes down to how much thinking it can fit into the byoyomi clock each move once main time is gone.

**Comment by peppercrab** [comment]
@herazul It's not so hard to learn Chinese actually. but anyway, we can translate for you . I'm from Yikeweiqi.com.....

**Comment by gcp** [comment]
>where the 20x256 is gonna crush the 10x128 whatever the timesetting is.

And this is based on what data?

**Comment by peppercrab** [comment]
the match （LeelaZeroVSGolaxy）probably is considered as fast game since both sides need sleep ：）40mins+60sec/1 move

**Comment by herazul** [comment]
@peppercrab Cool ! Do you know what hardware and net is gonna be used for the match ?

@gcp i did some testing at high playouts (with the V4SWA, 8ed44722, and some averaged nets of my own).
I didn't manage to get good averaged nets, but V4SWA was clearly better than 8ed44722 with 1/4 playouts at high playout. I tested at 15k visits vs 60k visits if i remember correctly for V4SWA matching (I have a NVidia 1080). I didn't test with time-settings however.
I wanted to try to train a 20*256 net for fun but i wanted to start from a net2net 10*128 averaged net better than current champ, but didnt managed to get one, despite A LOT of averaged nets, with different params and matched against each other at raw network, low playout, high playout,... but no luck for now :'(

**Comment by roy7** [comment]
Here's some official links I pulled from reddit.

http://www.yikeweiqi.com/banner/43328
https://share.yikeweiqi.com/gonews/detail/id/16672

**Comment by herazul** [comment]
@peppercrab Interesting. And do you know who will be managing and running leelaZ side ?

**Comment by herazul** [comment]
@peppercrab Thx a lot, looking forward to the match, will be interesting for sure !

**Comment by peppercrab** [comment]
@gcp we are exciting to see how good LZ can be in the game.

**Comment by Mezoka** [comment]
![banner](https://user-images.githubusercontent.com/17486912/38377023-8276deec-392c-11e8-9bbe-2f87f4b6b120.png)

**Comment by peppercrab** [comment]
One way to watch those game: 
Download yikeweiqi App (弈客围棋）from google play or some chinese app market (http://android.myapp.com/myapp/detail.htm?apkName=com.indeed.golinks&ADTAG=mobile). 

or you can open http://portal.yikeweiqi.com/online/golive/index.html to find it. 

the application was only for mandarin version. But we are translating it to english version these days. I think the one in google play can display maybe 80% of english text:)

 @herazul

**Comment by herazul** [comment]
@peppercrab I almost don't use my smartphone but this will interest people for sure. The web link is nice and seems to work very well, this will do just great thanks !

**Comment by roy7** [comment]
Thanks for the link. Turns out LZ is currently even in a match, I spotted the flower joseki avatar. :D

**Comment by diadorak** [comment]
They will use a stronger machines if a weaker one is defeated. They started with 1070. Then it will go to 1080ti, 1080ti*2, 1080ti*4, and Titan v*4. http://www.yikeweiqi.com/banner/42902/ So far LZ has lost only one or two games? I am not sure.

**Comment by roy7** [comment]
@amj Tagging you in case this thread is of interest or if AGA wants to have any commentary lined up.

**Comment by hydrogenpi** [comment]
are they still on 1070 or switched over to higher nets yet

**Comment by godmoves** [comment]
@hydrogenpi LZ is running a 1080ti now

**Comment by hydrogenpi** [comment]
@godmoves thanks for the update. seems like interesting to see how much improvement it can get as it climbs to 2x, 4x and then 4x titan... maybe they should go ahread and rent out the 8xV100 on aamzon aws lol

**Comment by hydrogenpi** [comment]
so based on lack of news it didnt go well or yes

**Comment by diadorak** [comment]
there is no news because the match against Golaxy is scheduled on April 8th.

**Comment by peppercrab** [comment]
the annouce for the schedule will be delayed for few days

**Comment by amj** [comment]
@roy7i heard they play at 4:30am PST, so, probably no AGA livestream ;)

**Comment by peppercrab** [comment]
DZG just finished last game 5mins ago. http://portal.yikeweiqi.com/online/golive/index.html

**Comment by diadorak** [comment]
I heard the games with Golaxy is delayed until 4/14. They are going to play 1 game per day for 7 days...

**Comment by davidsoncolin** [comment]
[Link to a game I found](http://portal.yikeweiqi.com/online/golive/detail?id=8222)

extracted sgf:
[leela2.sgf.txt](https://github.com/gcp/leela-zero/files/1886634/leela2.sgf.txt)

**Comment by hydrogenpi** [comment]
so its delayed confirmed? what happened

**Comment by diadorak** [comment]
The series will start on 4/14. One game will be played everyday starting from 7:30 PM in China. 
Golaxy will use 10x1080ti and LZ will use 4xTitan V.

**Comment by Mezoka** [comment]
Details are here : [link](http://www.yikeweiqi.com/news/topline/43472)

**Comment by peppercrab** [comment]
@hydrogenpi It's confirmed the first match will be played 4/14 1930PM (PEKING time)。 You should found the live broadcast in http://portal.yikeweiqi.com/online/golive/index.html

**Comment by alreadydone** [comment]
> Golaxy will use 10x1080ti and LZ will use 4xTitan V.

I think those were provided as an example ("如").

More details: positional superko enforced. Hardware, network depth, weight file version number, whether trained with human games, etc. of both sides need to be announced in advance. The side leading the match by *n* games must play the first *n* moves above or on the 6th lines.

**Comment by carljohanr** [comment]
Love the handicap rules, that is a great idea!

**Comment by billyswong** [comment]
How come the robot become the "logo", I thought that's a joke? 😂

**Comment by billyswong** [comment]
@alreadydone That handicap setting is strange. To implement such strange handicap, one probably need a modded version of LeelaZero or human intervention? On the other hand, a unmodded LeelaZero can handle 3 handicap stones fine as long as the komi value is subtracted by 3 to counteract the "handicap compensation".

**Comment by roy7** [comment]
@billyswong I was really getting a kick out of the LZ-joseki logo. :)

**Comment by hydrogenpi** [comment]
golaxy is using ONE or TEN 1080ti? was that a typo

**Comment by alreadydone** [comment]
> golaxy is using ONE or TEN 1080ti? was that a typo @alreadydone

Golaxy team tested that ten 1080ti and four Titan V yield similar performance. So there is a real possibility that this will be the actual hardware they use.

> How come the robot become the "logo", I thought that's a joke? 😂

Yeah, Leela is not Bender...

> That handicap setting is strange. To implement such strange handicap, one probably need a modded version of LeelaZero or human intervention? 

I think human intervention is allowed for the placement of handicapped stones, but for LZ you can just choose the move above all sixth lines with the most visit count (or policy prior if none is visited). People think this rule allows more fine-grained strength comparison and more varied opening.

**Comment by hydrogenpi** [comment]
Does this means we will get the weights to golaxy?

![image](https://user-images.githubusercontent.com/35181396/38535050-905944ca-3c36-11e8-948c-c7f229ff1a71.png)

**Comment by billyswong** [comment]
@hydrogenpi Not necessarily. It asks for the "version number" of the weight and also its "network depth". Effectively this pinpoints which weight file LeelaZero is using. But if Golaxy is not intended to be open source, "version number" is meaningless and thus we can only know its network size, assuming it's using a AGZ-alike deep learning architecture.

**Comment by billyswong** [comment]
@peppercrab There seems to be some misunderstanding and that robot is **not** the mascot of LeelaZero. It is a character in Futurama cartoon so there is copyright issue. And gcp has never adopted nor agreed that of course.

**Comment by gcp** [comment]
This thread is hilarious.

**Comment by LetterRip** [comment]
Still haven't seen a move, and it is past 7:30 China time...

**Comment by roy7** [comment]
@LetterRip It's a placeholder for a big match. Starts tomorrow USA time. So about 11 hours from now.

**Comment by diadorak** [comment]
4xTitan V  vs. 10x1080Ti confirmed.    The Leela Zero side is still testing which weight is the strongest .

**Comment by LetterRip** [comment]
Doh! misread - thanks :)

**Comment by roy7** [comment]
@diadorak A new LZ network just appeared tonight too. ;) If they are sticking with 'official' ones.

**Comment by killerducky** [comment]
@herazul since this seems to be the defacto place for discussing the match can you change the title?

**Comment by herazul** [comment]
Done. Hype \o/

**Comment by diadorak** [comment]
@roy7 I think they are a little worried that Golaxy may design some “traps” specifically for the official network. So they will announce it right before the game. 

http://www.yikeweiqi.com/banner/43672/    Golaxy owner and LZ volunteers enjoy a dinner together before the match:)

**Comment by roy7** [comment]
No trouble for us, we don't use it. :) LZ has a new logo on the match screens now anyway on that site.

**Comment by Matuiss2** [comment]
Where will the game be showed?

**Comment by roy7** [comment]
The live match itself is at http://portal.yikeweiqi.com/online/golive/index.html. I don't know what streaming will take place, if any.

**Comment by hydrogenpi** [comment]
was the learning rate lowered? why we got a 57% new net right on the eve of this match with golaxy?
they will use net 122?

**Comment by godmoves** [comment]
> I don't know what streaming will take place, if any.

@roy7 I think the first game will start at 7:30 PM in China. And there is a live in English at YiKe.

> they will use net 122?

Sure. (Unless there is a new network :wink:)

**Comment by alreadydone** [comment]
PC: http://portal.yikeweiqi.com/online/golive/detail?id=8326 Chinese: http://portal.yikeweiqi.com/online/golive/detail?id=8318
mobile: https://share.yikeweiqi.com/golive/detail/id/8326 Chinese: https://share.yikeweiqi.com/golive/detail/id/8326

**Comment by herazul** [comment]
>No trouble for us, we don't use it. :) LZ has a new logo on the match screens now anyway on that site.


You overestimate copyright lawyers, i think it's safe in court of course, but GCP could still receive a nice lawyer letter telling him to stop using futurama pics ^^

**Comment by diadorak** [comment]
![qq 20180414061059](https://user-images.githubusercontent.com/37359584/38767164-f804eada-3faa-11e8-8280-2ac1e3e27755.png)

Golaxy's network has 19 blocks.

LZ will use the official network #122

**Comment by godmoves** [comment]
Match will begin in hafl an hour. :octocat:

**Comment by diadorak** [comment]
https://share.yikeweiqi.com/gonews/detail/id/16941 

Golaxy is slighted favored.

**Comment by roy7** [comment]
English 2P commentary page:

http://portal.yikeweiqi.com/online/golive/detail?id=8326

**Comment by billyswong** [comment]
Non-commentary real time game (commentary pages looks delayed): http://portal.yikeweiqi.com/online/fight/online?id=3437834

**Comment by herazul** [comment]
I dont hear the commentary, how do you do it ?

**Comment by godmoves** [comment]
@herazul I think there is text only.

**Comment by roy7** [comment]
Yeah noone is streaming sadly.

**Comment by tterava** [comment]
68 moves in and LZ is already winning by a big margin. It's very unlikely that it could be this mistaken this early in the game. I'm already calling it: RIP Golaxy

**Comment by herazul** [comment]
I hope golaxy can win some game versus leela, because if it get rekt by leela, the match versus ke jie is gonna be akward.

**Comment by hydrogenpi** [comment]
where are the logs. i think they gimped leela, since my version played much stronker when is following along. smells fishy like fake pr for golaxy false flag op

**Comment by godmoves** [comment]
Move 150 is a mistake of the lining software, and Leela Zero doesn't have enough time to correct the it, then lost by time. But at this time, its win rate is 39% only.
