### ISSUE TITLE
Pondering prevents tree reuse

### ISSUE THREAD

**Issue by tterava** [gcp/leela-zero#1159]
I've noticed some inconsistent behavior with tree reuse. I'm not sure if this is bug or intended behavior so I figured I'd ask.

Here LZ is playing black and pondering. It correctly guesses the opponent move and therefore its playouts starts from where it was left with pondering. I've trimmed out the moves with low playouts.

LZ 20s> play W R13
= 
 R13 ->   28831 (V: 17.84%) (N:  2.63%) PV: R13 F6 G7 E11 N4 O5 R15 H8 F7 S15 S14 S16 J11 J12 H11 H12 J14 H13 E9 E10 H10 F9 J7 N15 N6 M8 P16 P17
 R15 ->    2352 (V: 17.50%) (N:  1.90%) PV: R15 S15 R13 S14 J11 J12 H11 H12 E10 K11 H9 K13 S13 G9 H8 H7 J9 G7 J7 N4
15.3 average depth, 29 max depth
○ LZ 20s> genmove B
= F6
25883 non leaf nodes, 1.32 average children
34108 visits, 5481918 nodes
Thinking at most 14.0 seconds...
NN eval=0.774130
Playouts: 26892, Win: 81.76%, PV: F6 G7 E11 N4 O5 R15 H8 F7 S15 S14 S16 J11 J12 H11 H12 J14 H13 E9 E10 A10 H4 J4 J7
Playouts: 28957, Win: 81.86%, PV: F6 G7 E11 N4 O5 R15 H8 F7 S15 S14 S16 J11 J12 H11 H12 J14 H13 E9 E10 A10 H4 J4 J7

However sometimes it looks like even with a successful guess the entire tree is scrapped and LZ starts from 0 playouts:

○ LZ 20s> play W R15
= 
 R15 ->    7698 (V: 11.37%) (N: 43.26%) PV: R15 H8 F9 H10 F7 S15 S14 S16 P16 P17 O15 N15 N14 Q16 N6 M8 J7 Q15 R14 M12 O11
  E5 ->    5988 (V: 11.96%) (N:  9.27%) PV: E5 F4 R15 S15 S14 H9 F7 S16 P16 P17 O15 N15 N14 J7 E6 N3 M4 N6 Q16 T15
12.6 average depth, 35 max depth
23094 non leaf nodes, 1.35 average children
31117 visits, 4597418 nodes
○ LZ 20s> genmove B
= H9
Thinking at most 14.0 seconds...
NN eval=0.691656
Playouts: 2003, Win: 85.66%, PV: H9 F7 S15 S14 S16 P16 P17 N15 N16 J7 O15 O14 Q16 Q15 N6 M8 N8 A10 A9
Playouts: 3387, Win: 84.74%, PV: H9 F7 S15 S14 S16 P16 P17 N15 N16 J7 O15 O14 Q16 Q15 N6 M8 N8 A10 A9
Playouts: 4726, Win: 84.20%, PV: H9 K13 K12 F9 S15 S14 S16 G9 J10 K11 H10 H8 J7 P16 P17 O15 N15 N14 N6 Q16 T15
 H9 ->    4255 (V: 85.55%) (N: 10.23%) PV: H9 K13 K12 F9 S15 S14 S16 G9 J10 K11 H10 H8 J7 P16 P17 O15 N15 N14 N6 Q16 T15
  H8 ->     205 (V: 80.12%) (N: 24.11%) PV: H8 F7 S16 S15 T16 P16 P17 O15 N15 N14 M12 O11 N6 J7

Sometimes this behavior is extremely blatant, where there's effectively only 1 move which gets pondered on and it gets tens of thousands of playouts, then LZ starts from 0 playouts when opponent plays that move. There's also some weird behavior where it sometimes seems like LZ starts from scratch but reports as if it calculates 10x faster than normal and is clearly reusing the calculations from pondering. Is this an issue or what's going on here?

**Comment by gcp** [comment]
>There's also some weird behavior where it sometimes seems like LZ starts from scratch but reports as if it calculates 10x faster than normal and is clearly reusing the calculations from pondering. 

This happens if all neural network computation can be retrieved from the NNCache, even if the tree itself wasn't reused.

How are you interacting with Leela Zero? Are you using Sabaki?

**Comment by tterava** [comment]
Yes, using latest version of Sabaki and current release version of LZ.
Command line: -g -r 5 -t 7 -d --gpu 0 --gpu 1 -w networks\leelaz-model-swa-16-768000.txt
Initial commands: time_settings 0 15 1

**Comment by gcp** [comment]
I'm going to guess the loss of tree reuse might be due to how sabaki sets/resets the position the engine sees. 

As you have observed, the NNCache significantly lowers the impact even if it goes wrong, though.

**Comment by tterava** [comment]
Unless Sabaki does some weird stuff in the background, it seems in the log it only sends following commands during a game:

play W E10
genmove B
play W J12
genmove B
....

Also it doesn't quite explain why tree reuse usually works but not always. I would imagine it never works if there was an issue with Sabaki. I'm also currently running a test with the 256x20 network on CGOS, i'll see if the issue is there as well.

**Comment by tterava** [comment]
Seems it is indeed an issue with Sabaki. Playing on CGOS tree gets reused every time. Also LZ is extremely fast and snappy in CGOS while Sabaki is a lot more sluggish. Usually there's 1-2 second delay on Sabaki after a move before LZ starts to calculate. I guess I'll need to find a new GUI.

**Comment by SebastienFaurite** [comment]
Have you tried Lizzie ?
https://github.com/featurecat/lizzie

**Comment by tterava** [comment]
It seems you can't set custom time settings in lizzie.

**Comment by SebastienFaurite** [comment]
Lizzie is in active development so I am pretty sure you can open an issue there.

**Comment by tterava** [comment]
@killerducky realized that ponder throws away the tree.

Adding this line at the end of ponder makes it retain the tree and it gets successfully reused next move:
m_last_rootstate = std::make_unique<GameState>(m_rootstate);

**Comment by Marcin1960** [comment]
@killerducky  "Adding this line at the end of ponder"

You mean at the very end of this function?

void UCTSearch::ponder()

**Comment by tterava** [comment]
Yes, I already made a pull request for it. I've been using the fix 2 days now and I haven't had any issues with it, works like a charm.

**Comment by Marcin1960** [comment]
I got this:

1>------ Build started: Project: leela-zero, Configuration: Release Win32 ------
1>UCTSearch.cpp
1>c:\users\hp\desktop\leela-zero-0.13\src\uctsearch.cpp(657): error C2672: 'std::make_unique': no matching overloaded function found
1>c:\users\hp\desktop\leela-zero-0.13\src\uctsearch.cpp(657): error C2783: 'std::unique_ptr<_Ty,std::default_delete<_Ty>> std::make_unique(_Types &&...)': could not deduce template argument for '_Ty'
1>c:\program files\microsoft visual studio\2017\community\vc\tools\msvc\14.13.26128\include\memory(2597): note: see declaration of 'std::make_unique'
1>Done building project "leela-zero.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Marcin1960** [comment]
@tterava 

Is it what you meant instead ?

m_last_rootstate = std::make_unique<GameState>(m_rootstate);

**Comment by tterava** [comment]
m_last_rootstate = std::make_unique<GameState>(m_rootstate);

Try this, you can also check #1170.

**Comment by Marcin1960** [comment]
I got it, crazy Github. 

"m_last_rootstate = std::make_unique<GameState>(m_rootstate);"

**Comment by tterava** [comment]
I finally understand the importance of formatting comments properly
`
m_last_rootstate = std::make_unique<GameState>(m_rootstate);
`

**Comment by Marcin1960** [comment]
How did you do it :)
