### ISSUE TITLE
Slight Performance Increase on NVIDIA GPU with Modified Visual Studio Setting

### ISSUE THREAD

**Issue by Splee99** [gcp/leela-zero#1162]
I have compiled the next branch with the Opencl.lib provided by NVIDIA (CUDA 9.1) instead of the Opencl.dll in the 0.13 release, following the procedure outlined here:

https://medium.com/@pratikone/opencl-on-visual-studio-configuration-tutorial-for-the-confused-3ec1c2b5f0ca

I observed a slight performance increase. Also in the project setting, C/C++ optimization section, I selected the "favor fast code" option, but I'm not sure how significant that is.

**Comment by gcp** [comment]
The OpenCL.dll should be almost completely irrelevant because that's not doing any of the computation or is it the actual driver. Are you sure you didn't just see measurement error?

**Comment by Splee99** [comment]
I used benchmark to measure and saw less than 10% increase in speed. Maybe it's the next branch which is faster than the previous release? The code size is certainly smaller, 714k instead of more than 2200k, but it's not related to opencl. Anyway, it's just my opinion, you may close this issue if you like.

**Comment by gcp** [comment]
>Maybe it's the next branch which is faster than the previous release?

Yes, there are several optimizations in next.

I'll close this unless there's some indication there is indeed a speedup there, but again, as OpenCL does not do computation and isn't the actual driver, it's extremely unlikely to influence speed.
