### ISSUE TITLE
the graph of 116# network's winrate shows some oscillatory periods

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1169]
WR | NO
-- | --
36.84 | 69
50 | 68
43.79 | 67
34.83 | 66
53.25 | 65
43.21 | 64
48.58 | 63
42.38 | 62
49.85 | 61
43.16 | 60
48.41 | 59
35.59 | 58
45.34 | 57
47.29 | 56
40 | 55
48 | 54
36.55 | 53
48.77 | 52
47.67 | 51
45.82 | 50
48.03 | 49
45.41 | 48
38.56 | 47
50.15 | 46
40.88 | 45
50.15 | 44
38.71 | 43
37.98 | 42
42.93 | 41
35.71 | 40
40.58 | 39
49.44 | 38
45.21 | 37
47.04 | 36
42.11 | 35
42.23 | 34
27.27 | 33
52.58 | 32
40.23 | 31
43.94 | 30
51.65 | 29
40.16 | 28
44.79 | 27
49.49 | 26
50.53 | 25
43.19 | 24
47.87 | 23
43.75 | 22
37.6 | 21
49.68 | 20
42 | 19
45.82 | 18
38.93 | 17
49.55 | 16
23.81 | 15
50.45 | 14
43.68 | 13
34.38 | 12
51.96 | 11
41.84 | 10
41.09 | 9
48.8 | 8
46.92 | 7
36.69 | 6
44.83 | 5
44.35 | 4
38.1 | 3
52.07 | 2
49.83 | 1

![116](https://user-images.githubusercontent.com/23301704/38480728-c1ea186c-3bf9-11e8-8231-0a3b8be09d40.png)

**Comment by l1t1** [comment]
and most 2nd(swa) is stronger than 1st of same netwrok?
eg. a9133037  > 8df9579e, 
and 72bc8a98  > 08de7351 
 etc

**Comment by l1t1** [comment]
if that is true, can we omit 1st of same network match to speed up the progress?

**Comment by l1t1** [comment]
seems true

b|Start Date | Network Hashes | Wins / Losses | Games | SPRT
--|-- | -- | -- | -- | --
32k2|2018-04-09 05:29 | 41b093c3  VS  39d46507 | 121 : 134 (47.45%) | 255 / 400 | fail
32k1|2018-04-09 05:29 | 73e91f20  VS  39d46507 | 68 : 90 (43.04%) | 158 / 400 | fail
16k2|2018-04-09 03:49 | cd78a0da  VS  39d46507 | 159 : 160 (49.84%) | 319 / 400 | fail
16k1|2018-04-09 03:49 | d56bdb52  VS  39d46507 | 75 : 96 (43.86%) | 171 / 400 | fail
8k1|2018-04-09 02:59 | 331751a3  VS  39d46507 | 31 : 58 (34.83%) | 89 / 400 | fail

**Comment by zxd0226** [comment]
20b256f  up up!

**Comment by l1t1** [comment]
192*150has up

**Comment by gcp** [comment]
This seems completely meaningless to me. Is there some point to this observation, aside from that's how random noise looks?

**Comment by l1t1** [comment]
it's not noise, it shows most 2nd(swa) is stronger than 1st of same netwrok, so did in 192 block matchs.
in following 7 red pairs, 5 swa is stronger , so just skip normal networks to save time
![2018-04-11_101631](https://user-images.githubusercontent.com/23301704/38593125-67994764-3d72-11e8-88ad-efe35744dd31.jpg)

**Comment by l1t1** [comment]
Start Date | Network Hashes | Wins / Losses | Games | SPRT
-- | -- | -- | -- | --
2018-04-10 21:06 | 6fa25368  VS  8c67ecdc | 80 : 68 (54.05%) | 148 / 400 |

**Comment by Mardak** [comment]
You're comparing win rates where there's significant amounts of overlap in their margin of errors. For example d1c4c962 shows 46.56% win rate with 262 games while 6c6c8b61 shows 43.84% with 203 games.

That means with ~95% confidence, the actual win rate for each of those is somewhere between:
d1c4c962: 40.39% to 52.74%
6c6c8b61: 36.82% to 50.86%

Is one stronger than the other? Probably. Which one? Unclear.
