### ISSUE TITLE
Should clear_board reset RNG seed?

### ISSUE THREAD

**Issue by StanTraykov** [gcp/leela-zero#1172]
Skimming through LZ's code, I realized my testing methods had a flaw:  the LZ engines were playing against each other using the same RNG seed for an entire match (leelaz invocation).

While it's very easy to change my testing methods to compensate for that, isn't it something that Leela Zero should be doing anyway? Right now, it just uses the same seed (changed up a bit for each thread) for all games played during a GTP session. This was probably easiest originally, and logical to leave as is when the ``-s`` switch was introduced. But I think the expectation by clients would be for Leela Zero to play without such bias when the board is reset for a new game (and there was no ``-s`` supplied in the command line, obviously).

Games against itself--but also against other engines--would be more balanced if this was done. It's not purely academical either: I had two different LZ networks [repeat a whole game](https://github.com/gcp/leela-zero/issues/1113#issuecomment-377779726), from start to finish, during one of my tests (with very low n/s due to 2s time limit and old GPU, GTX670). I have since then always produced move-list checksums to test uniqueness... I guess even human opponents could notice a difference in the variety of openings, e.g. if they play the same bot on a go server (theoretically, the GTP session could never be reset, even on server disconnects, etc.).

**Comment by gcp** [comment]
I don't understand. If you reset the board, the RNG is not reset, so the seeding doesn't matter for the next game?

Resetting the RNG would make no sense as it would play the same game over and over again.

**Comment by StanTraykov** [comment]
Ah, of course, the whole issue was a thinko, as nothing gets restarted with the starting seed at game begin!
