### ISSUE TITLE
Should promotion matches use lower MCTS visits / playouts?

### ISSUE THREAD

**Issue by Mardak** [gcp/leela-zero#1177]
So far, promotion matches have used the same number of visits / playouts as self-play games, but is that actually desired? Currently for both it's set to 3200 visits while the AGZ paper says 1600 simulations. (To be clear, self-play games should still have higher searching to learn when training.)

In particular, does having a relatively higher amount of search bias towards networks that have lower quality value output and good-enough policy output? Where a lower amount of searching would generally mean both value and policy output need to be of higher quality to be strong enough for promotion?

This come from some analysis of the ladder behavior in https://github.com/gcp/leela-zero/issues/838#issuecomment-377746272 where it looks like "understanding ladders" currently means a network needs to bias (both value and policy) towards correctly searching a complete ladder to then correct itself if it actually is a losing position. So the dynamic runtime search is effectively being used to override a poor static-ish / search-less evaluation. Where potentially if matches were run with less searching, it could lead to finding networks that handle situations like ladders more efficiently.

**Comment by hydrogenpi** [comment]
@plus at network size increases, this means it can save time on running matches esp if it takes many matches to find a good one

**Comment by gcp** [comment]
>Currently for both it's set to 3200 visits while the AGZ paper says 1600 simulations

These were tuned to take about the same time, but 3200 visits is slightly more efficient than 1600 playouts.

The matches are there to ensure the quality of the self-play data so running those with different playouts would be totally pointless.

**Comment by gcp** [comment]
>Where a lower amount of searching would generally mean both value and policy output need to be of higher quality to be strong enough for promotion?

In real games, you're generally going to use MORE searching, aren't you? This idea seems completely backwards. The search is exactly there as an **improvement** operator on the neural network. The whole idea is that it extracts better data out of it, which includes determining that the initial value network was not good enough and generating data to correct it.

**Comment by Mardak** [comment]
> In real games, you're generally going to use MORE searching, aren't you? 

I was implying (potentially incorrectly?) that being efficient at searching with fewer visits would mean when there's more searching in real games, it could find even better results. E.g., a network that would only complete a ladder search in 3200 visits would not have enough visits to find an alternative, but if it could do the same in half the visits, it should be stronger?

> The search is exactly there as an improvement operator on the neural network.

The value of additional search is clear for self-play + training as well as real games, but I'm questioning its appropriate value for evaluation matches to promote networks.

Maybe in other words, having a lower / restricted search in evaluation matches sets a higher passing requirement for a new best network. So to be clear, this would probably slow down the rate of promotions, which is the opposite direction of "always promote."

**Comment by gcp** [comment]
>that being efficient at searching with fewer visits would mean when there's more searching in real games, it could find even better results

How can this possibly ever be an argument to test with LESS visits then?

>having a lower / restricted search in evaluation matches sets a higher passing requirement for a new best network

I am not sure. If the network has a better value part but a worse policy part, you could consider the requirement to be lowered.

**Comment by Mardak** [comment]
After thinking a bit more about this and perhaps just restating what you've said -- the argument for keeping match visits and self-play visits the same is that a matched network can prove that it's capable of playing stronger with 3200 visits. One doesn't need to worry about a network that is strong with 1600 visits might be weaker with 3200 visits (i.e., a poor network for generating self-play games with 3200 visits).

If a network turns out to be more efficient at searching, then that probably translates into increased win rates similar to how we've used twice-as-fast = 200 ELO.

**Comment by tapsika** [comment]
The original idea of more search puts less weight on value and more on policy seems correct to me (and it may also mask some cases of flawed net output if rare enough), but I still doubt there is much to gain here. Some data on winrate correlation at higher vs lower playouts would be interesting. IOW is there a significant chance A is stronger than B at 500 but weaker at 5000 - were something like this tested somewhere?

In the unlikely case that such scenario would be common, one option would be to run eval matches at varying playouts (like half of them lower the other half higher), since this is how the network will be used in the real world if promoted.
