### ISSUE TITLE
why force leela13 since leela 12 can play 192block?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1178]
Got new job: selfplay
net: ba748d402af1bdd101212cbd217025dee866b3fcc996bd16d1a3134d5591a501.
Engine has started.
Infinite thinking time set.
1 (B R16) 2 (W C4) 3 (B C16) 4 (W R4) 5 (B E3) 6 (W D6) 7 (B P3) 8 (W E17) 9 (B D14) 10 (W P17) 11 (B Q14) 12 (W Q6) 13
(B C8) 14 (W H3) 15 (B E8) 16 (W C7) 17 (B C3) 18 (W B3) 19 (B D4) 20 (W C2) 21 (B C5) 22 (W D3) 23 (B B4) 24 (W C3) 25
(B D5) 26 (W B8) 27 (B C9) 28 (W F6) 29 (B F4) 30 (W B6) 31 (B B5) 32 (W E2) 33 (B F2) 34 (W F1) 35 (B G1) 36 (W E1) 37
(B G5) 38 (W G2) 39 (B G6) 40 (W F7) 41 (B H8) 42 (W B9) 43 (B C10) 44 (W B10) 45 (B C11) 46 (W F8) 47 (B F9) 48 (W G9)
49 (B G8) 50 (W B11) 51 (B B12) 52 (W C12) 53 (B D12) 54 (W E9) 55 (B D7) 56 (W C6) 57 (B F10) 58 (W G10) 59 (B F11) 60
(W E5) 61 (B E4) 62 (W G7) 63 (B H7) 64 (W H6) 65 (B J6) 66 (W H5) 67 (B H4) 68 (W J5) 69 (B J4) 70 (W K5) 71 (B K4) 72
(W L5) 73 (B M3) 74 (W N4) 75 (B A6) 76 (W N3) 77 (B K8) 78 (W A7) 79 (B A5) 80 (W G3) 81 (B E6) 82 (W E7) 83 (B D8) 84
(W B7) 85 (B F5) 86 (W E6) 87 (B G4) 88 (W L4) 89 (B A11) 90 (W C13) 91 (B B13) 92 (W D11) 93 (B C14) 94 (W J9) 95 (B J8
) 96 (W K9) 97 (B L8) 98 (W L9) 99 (B M8) 100 (W G11) 101 (B A10) 102 (W M9) 103 (B A9) 104 (W R12) 105 (B Q17) 106 (W P
16) 107 (B R13) 108 (W Q12) 109 (B O14) 110 (W L17) 111 (B G17) 112 (W Q13) 113 (B R14) 114 (W P14) 115 (B P15) 116 (W P
13) 117 (B O15) 118 (W Q16) 119 (B Q15) 120 (W R17) 121 (B S17) 122 (W Q18) 123 (B S18) 124 (W N8) 125 (B N17) 126 (W N1
6) 127 (B M17) 128 (W resign) Game has ended.
Score: B+Resign
Winner: black
Uploading game: 4acc264aab4a477da8dd4f8328e54702.sgf for network ba748d402af1bdd101212cbd217025dee866b3fcc996bd16d1a3134
d5591a501
Game data aa95a9df68bdc6ce57aa19ed0c8ed3b44bcf201b1f79e8bc03d7784f839a6056 stored in database
24 game(s) (24 self played and 0 matches) played in 2345 minutes = 5863 seconds/game, 24687 ms/move, last game took 5970
 seconds.
{
    "cmd": "selfplay",
    "hash": "ba748d402af1bdd101212cbd217025dee866b3fcc996bd16d1a3134d5591a501",
    "leelaz_version": "0.13",
    "options": {
        "noise": "true",
        "playouts": "0",
        "randomcnt": "30",
        "resignation_percent": "5",
        "visits": "3200"
    },
    "options_hash": "695b4e",
    "random_seed": "6238966335137164504",
    "required_client_version": "15"
}

Required client version: 15

Server requires client version 15 but we are version 14
Check https://github.com/gcp/leela-zero for updates.

D:\tool\leela12>

**Comment by roy7** [comment]
These strings are being changed in the next version of leela to try and reduce this never ending confusion.

"leelaz_version": "0.13" is the minimum version of leela allowed.
"required_client_version": "15" is the minimum protocol version allowed.

Leela 0.14 will have both of these renamed to be more clear.

**Comment by l1t1** [comment]
@roy7 your answer seems for another question.
In my example, the leela first played two game of network196, when it got the 3rd job, sever refuse it.

**Comment by roy7** [comment]
Is the current client not using version 15?

**Comment by fell111** [comment]
Please just upgrade to lz 0.13 to run the self play. lz 0.13 improves the varieties which will contribute to the training. 
Of course you can also use lz 0.12 for analyzing/playing in other situations. But for the self play, please upgrade it.

**Comment by gcp** [comment]
You need to update because important bugs were fixed which affect training data.
