### ISSUE TITLE
the server is overload

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1180]
Length: 39859777 (38M) [application/octet-stream]
Saving to: '02e663b00ec1994d1348cbeffd2c0632e52dbbbbf1f0b9ada7ecf68bc86d862e.gz'

           02e663b00ec1994d13   0%[                                                  ]     100  0.95 B/s    eta 465d

**Comment by hydrogenpi** [comment]
quick someone page him

**Comment by hydrogenpi** [comment]
btw the trainding data is not refreshed 
https://github.com/gcp/leela-zero/issues/167

**Comment by hydrogenpi** [comment]
![image](https://user-images.githubusercontent.com/35181396/38530898-1b1193ac-3c22-11e8-8aa4-71604f733403.png)


iof they both win who is getting prpomoted?

**Comment by Tsun-hung** [comment]
@roy7  It isn't a wrong, 02e failed at 400th match, so 470 begin the match with ba7 immediately, but 02e passed later

**Comment by roy7** [comment]
Oh ok so it was a "fake" fail. We call anything that didn't promote by 400 a fail now instead of leaving it "???". So was probably just a few games away from promotion. 4700 down to 53%, so maybe it'll solve itself.

**Comment by gcp** [comment]
The network downloads aren't linked to the node server so this is more likely a problem at your end.
