### ISSUE TITLE
Per-game random seed

### ISSUE THREAD

**Issue by WhiteHalmos** [gcp/leela-zero#119]
1. Generate random seed on client (or fetch from server, either way works).
2. Pass random seed to leelaz
3. Log random seed used for the game
4. Upload random seed to server alongside sgf

Would help greatly in reproducing and fixing regressions like #117 
Also allows independent verification if ever necessary

**Comment by gcp** [comment]
This isn't going to do you much good unless you run the engine in single thread mode too.

**Comment by WhiteHalmos** [comment]
Ah, yes, you're right. This depends on a fix for #109 to switch to single thread mode.

**Comment by WhiteHalmos** [comment]
Closing the issue for now, see https://github.com/gcp/leela-zero/issues/117#issuecomment-345793660 for reference.
