### ISSUE TITLE
Show move number

### ISSUE THREAD

**Issue by Victor-Ch** [gcp/leela-zero#1192]
Is it possible to show current move number in the output?
Would be much easier to find the wanted move in the log.

**Comment by godmoves** [comment]
I wrote a small tool to covert the log to a sgf with comments in my fork, maybe it can help you:)

**Comment by Victor-Ch** [comment]
Sorry @godmoves, can't find this tool - could you give link?

**Comment by Victor-Ch** [comment]
Thanx!
