### ISSUE TITLE
Inefficient GPU usage with multiple autogtp running at the same time

### ISSUE THREAD

**Issue by Matuiss2** [gcp/leela-zero#1195]
The GPU usage with 1 autogtp running is 20%, with 2 it splits 10% - 10%, and the more I open more it splits totalizing 20% usage(weird), I thought at first that the CPU was the limiter but it's not, it's on 15% per autogtp open(and not spliting the usage). So I want tips for fixing that, I want to use the full potential of mine GPU.

Mine Specs are:
i5 8600K 4.8GHz
GTX 1070ti
8GB ram 2133

**Comment by ihavnoid** [comment]
This may sound a bit silly, but I had a similar incident when one of the graphics card fans were stuck.  Did you see what temperature your GPU was when running autogtp?  Plus, did you make sure your GPU's external power connector is properly connected?

By the way, what OS are you using?

**Comment by l1t1** [comment]
no picture bad chating

**Comment by marcocalignano** [comment]
Just start autpgtp in multitasking mode 
`./autogtp -g 6` 
it starts 1 autogtp with 6 threads at the same time. see also 
`autogtp --help`

**Comment by Cabu** [comment]
Check with tools like GPU-Z. My GPU is limited by the thermal dissipation of my laptop. When I run leela, my GPU goes in thermal protection in the following seconds. My fan are good and clean, its the thermal dissipation of my laptop who is crap :(  (ACER Aspire V Nitro with a GT 960M).

Windows say that my GPU is used at 20% from time to time, GPU-Z said it is used at 98% continuously. I would put more faith in GPU-Z about the numbers.

**Comment by Matuiss2** [comment]
Thank you guys, I already discovered the limiter, it was the compute_0 from the GPU(whatever it is), I can only run 2 autogtp instances at the same without losing efficiency.
one instance-
![image](https://user-images.githubusercontent.com/31539494/38722879-cb73b99a-3ed5-11e8-9f52-3473077bc2a2.png)
two instances-
![image](https://user-images.githubusercontent.com/31539494/38722922-eecff070-3ed5-11e8-94cc-78324bb61d6c.png)
