### ISSUE TITLE
why all the matchs are paused?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1196]
(2963 match games in past 24 hours, **0 in past hour**.)
as ususal, the 2nd 32k network should be played soon.
![2018-04-13_141012](https://user-images.githubusercontent.com/23301704/38719382-43361b00-3f24-11e8-90a3-e3c0dd89cc83.png)

**Comment by afalturki** [comment]
It's not paused, there's just no matches to play.

**Comment by l1t1** [comment]
I see
