### ISSUE TITLE
could you merge weiight 116 into leela gui to build a standalone software

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1199]
some reason
1 the file size is acceptable
2 the strength is better than leela 0.11
3 leela is not updated for long time
4 self play function is welcome to students

**Comment by hydrogenpi** [comment]
I suggest drop Leela 11 altogether and consolidate into leela zero as the only project going forward.

**Comment by ThorAvaTahr** [comment]
did you try [lizzie](https://github.com/featurecat/lizzie)?

**Comment by Marcin1960** [comment]
@hydrogenpi "drop Leela 11 altogether and consolidate into leela zero"

Leela 11 is a private software created and owned by GCP, long before LZ started. Let it be.

**Comment by gcp** [comment]
This is offtopic here.
