### ISSUE TITLE
the king is bron by chance

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1205]
we now see f3231682
 VS Regular Match c0cb605b
231 : 194 (54.35%),
but I saw 221:180 a few minutes ago.
so if the win game finished earlyer, the network

**Comment by l1t1** [comment]
has more chance to be promoted, is it fair ?

**Comment by Cabu** [comment]
It is know. It is not the first and certainly not the last to pass under 55%. It's not a problem in itself.
