### ISSUE TITLE
Contributing training games with higher number of visits

### ISSUE THREAD

**Issue by kuba97531** [gcp/leela-zero#1213]
At the moment I contribute some computing power through autogtp, but  I would like to run several selfplay games on higher number of playouts - e.g. 30k.
1) Would it be valuable to contribute those games to the training data?
2) If yes than would it be possible to add to autogtp an argument "minimum number of visits", which I could specify to run selfplay games on my computer with higher number of visits that current default.
3) If not than would be it be ok if I made the local change to autogtp and contribute the games with this modified version?

**Comment by kuba97531** [comment]
I don't think these games will be worth any more - I'm sorry if that was not clear. I just plan to run several of these games anyways for my entertainment. The question is that given I will run say 10 of these selfplay games anyways - does it make sense to contribute them to the data or not.

**Comment by gcp** [comment]
Why not use something like gomill's ringmaster for these kind of tests?

**Comment by kuba97531** [comment]
I don't suffer from lack of way to generate these entertaiment self-play games. My question was if it makes sense to add them to training data given that I already have them.
I think I now agree with your concerns so will not modify anything.
