### ISSUE TITLE
 Leela Zero vs Golaxy ,the 4th game (LZ win)

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1216]
sga http://duiyi.sina.com.cn/cGibo/20184/leela4-golaxy180417.sgf

**Comment by bood** [comment]
Some info on this game:

Network 3217 is used (20x256 v9), binary is compiled from https://github.com/ihavnoid/leela-zero/tree/atomic_uct_node_pointer with ponder on

Move 191 is commented as the winning move by pro player (https://share.yikeweiqi.com/gonews/detail/id/17001)

Log file and win rate below:

[20180417_Golaxy_v9.txt.gz](https://github.com/gcp/leela-zero/files/1922217/20180417_Golaxy_v9.txt.gz)
[20180417_Golaxy_v9.sgf.gz](https://github.com/gcp/leela-zero/files/1922218/20180417_Golaxy_v9.sgf.gz)
![20180417_golaxy_v9](https://user-images.githubusercontent.com/1168942/38907768-e3d814ea-42ef-11e8-9950-ebaf44e7d286.png)

**Comment by hydrogenpi** [comment]
Is there a english commentary version?

**Comment by alreadydone** [comment]
Is there log for game 3? People are [curious](https://www.reddit.com/r/cbaduk/comments/8cmnur/lizzie_vs_galaxy_game_3_link_5d_english_commentary/dxg3ncc/) about the two 3-3 LZ played.

**Comment by hydrogenpi** [comment]
Game 5 who won? I can't read Chinese.

**Comment by larrywang30092** [comment]
Game 5: Galaxy (B) vs. Leela Zero (W) First B move (m,n) with m,n>5

Result: Leela Zero won. Galaxy time

**Comment by hydrogenpi** [comment]
I also heard conflicting reports that it was score of B+2.5 , so that means had it not timed out the golaxy would have won ?

**Comment by kuba97531** [comment]
My leela was reporting close to 99% winrate when black resigned. Also after playing the rest of endgame myself score was W+0.5.

**Comment by hydrogenpi** [comment]
@kuba thanks for the info. So there is two matches left. Its time to have LZ use the same quality of hardware that Golaxy is afforded to use, and a real official net, and no handicap.

**Comment by hydrogenpi** [comment]
I heard that, but oczam rasor. if its so similiar (which I'm not necessarily disputing) why not just ues exactly the same to remove all doubt and be more scientific as control and fixed control etc

In points of fact, one of the matches at least, its LZ only used 5x 1080Ti where Golaxy used 10x1080Ti, and then they stated "titanV not optimized" (not sure if that talking about the Nvidia issue with titanv where its calculations get messed up, or that the team can't get LZ to play optimillay on the TitanV or combination of all of the aboves etc) so I don't see how it can be similar if its at 50% and then buggy

**Comment by hydrogenpi** [comment]
So wasn't it said after the seven games Golaxy was gonna play ke jie? 

Why can't LZ also play Ke Jie?

**Comment by roy7** [comment]
I'd imagine Ke Jie is being paid to attend and play. Top pros don't do public exhibition matches for free. :)

**Comment by bjiyxo** [comment]
> ? You mean they can't go on aws and rent out 8x V100 for a match or two?

You must be really rich. Renting 8xV100 costs 42$/hr. So we will cost 42 $/hr * 3 hr * 7 d = 882 $. I would rather save 882$ and buy a GTX 1080 to produce tens of thousands of games.

**Comment by alreadydone** [comment]
Scenes of Golaxy running: http://www.yikeweiqi.com/banner/43832/
Company behind Golaxy: http://www.yikeweiqi.com/banner/43862/
Where did you get the impression that Golaxy is run by volunteers?

**Comment by hydrogenpi** [comment]
Oh my mistake... I didn't know Golaxy was a company....

btw @bjiyxo not sure where you got your $42, its actually $24/hr
https://aws.amazon.com/ec2/pricing/on-demand/
p3 instance

**Comment by l1t1** [comment]
5 http://duiyi.sina.com.cn/cgibo/20184/leela5-golaxy180418.sgf

**Comment by bjiyxo** [comment]
@hydrogenpi It seems that renting V100 in East Asia costs much more than in US. You may see $42 or $40 in Tokyo and Seoul.

**Comment by hydrogenpi** [comment]
they got bribed by glolsxy
match 6 only three 1080

**Comment by kuba97531** [comment]
I think there was an operator misclick today. Leela played the "obvious" joseki move which according to the recent network is a 15% mistake.
https://gyazo.com/0b737ff9eb61355b036f71eae2ac60ba

**Comment by herazul** [comment]
@hydrogenpi seriously, you got to stop reacting like a crazy tinfoil hat person without knowing anything about context or facts.
If they can't have 10 1080ti for the match, so be it, they are not a rich company, they are passionate people trying to put a good show against golaxy, that's all.

**Comment by hydrogenpi** [comment]
prob next excuse our computer rebooted midgame cause of OS update

**Comment by hydrogenpi** [comment]
serious question who misclicks 2 games out of only 7

**Comment by l1t1** [comment]
I was opposed to the weight of 20B. 15B before the debut 20B weighted more than 80% of the 10B win rate, hardware configuration enough to play; now the 20B to the official 15B winning rate never reached Qi Cheng, and this 60% win rate is still more than double the amount of computing to achieve The hardware that is required to use or not to defeat or even exceed 15B is too high. Did not find out this sector to reduce the use of 20B, is sent in vain.  **from https://tieba.baidu.com/**

**Comment by l1t1** [comment]
https://tieba.baidu.com/p/5656679866?lp=5028&mo_device=1&is_jingpost=0&pn=0&

**Comment by hydrogenpi** [comment]
@l1t1 that translation was hard to read. apparently if I understood correctly, someone was opposed to using the combination of higher sized network ike the 20block in conjunction with minimial hardware like the 3x 1080, but the advice was sent in vain because no one listened and then they lost to a misclick or aka error of the connector of the operator l

**Comment by bood** [comment]
Yes, the computation power is for sure imbalanced we know. But what can we do if we do not have such a configure, what can you do if one of volunteers is sick one day? What if the 0.13 release still has a pondering bug you didn't notice? The main point of this match is just for fun, people behind it do it for free, so why are you so mean about it? Who can guarantee to hold a match first time without any issue?

If you do not like it, please do not waste your precious time watching, organize your own match instead, with whatever configuration you've got, I don't care.

Talk is cheap.

**Comment by hydrogenpi** [comment]
@bood When LZ volunteer team decided on their own volition to schedule and then announce to the broader general public these sets of games, it set itself on the trajectory of creating certain reasonable expectations as par the course of the typical kind of Go match. Had I know ahead of time all the things that would go wrong, all the shenanigans that would be pulled, then maybe that information would have been vital to my deciding how much of my own time and attention I would like to dedicate to watching this unfold, and I’m sure the same or similar could apply to other people in the public community as well.  Once again, when they started the game with the explanation that they had tested 4xTitanV to be equal to performance of 10xGTX1080Ti, they mentioned nothing about the possibility that the rest of the games would have LZ using MUCH LESS hardware specs than its Golaxy opponent. By first giving the impression of a ‘fair’ match by stating that after extensive testing the 4xTitanV basically == 10x GTX1080Ti on perf parity and then only later on mid match flip flopping (for whatever reason or excuse, valid or invalid, but I call it as it is, and this was a bona fide flip flop) by using half and then 3/10th the power, this at the very least FEELS like a bait and switch in which they in which they used a ruse to get people invested emotionally and then did a roundabout by not delivering on almost every metric and standard.

**Comment by herazul** [comment]
@hydrogenpi I don't know if someone can get ban of a github and what rules are in place, but if it was up to me you would get ban.
There is a pretty big difference between giving feedback or criticism and being straight up rude and mean.

At my work someone who would behave like that to their coworkers on a project would be fired.

**Comment by hydrogenpi** [comment]
@herazul if you want to talk about "rules" of github then per the license and per the rules they (the volunteer LZ team) have to release the modified networks to the public afaik.

**Comment by gcp** [comment]
I'm not so much bothered about the disparity in hardware (which of course makes it unfair, but that is capitalism for you), but about the fact that settings/networks/hardware are apparently being changed mid match. 

This means a simple thing: it was not tested properly. *Before* you play the match or tournament, you figure out the optimal configuration. If you are even so much as tempted to change the configuration during the games, it means you did not test properly, because what information can you possibly have gotten in that time period that invalidates your prior test for the optimal configuration?

Now, given that 

- this match is apparently not to be taken seriously, due to the above, and it seems even operator errors stand(?!) 
- people are starting to lose their shit over it
- there's no usable info for the development of LZ due to the above and lack of transparency

I'll just close this discussion. There's no use to bother or care about this.

**Comment by gcp** [comment]
>have to release the modified networks to the public afaik

The license only covers distribution.
