### ISSUE TITLE
could you supply the links of strongest  network of each architectures?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1218]
for favorite keep and  balance of strength and speed.
for example, the one of 128*10 is 2c169585
whose link is
http://zero.sjeng.org/networks/2c1695859e9a8ced4fff57ad8ff267742b910d6e4b838a14a77e584dfd2265f6.gz

it beat last best network of 128*10 39d46507 by 52.96%

**Comment by Tsun-hung** [comment]
No, the strongest 128*10 network is b96
http://zero.sjeng.org/networks/b9639fe49a1bf450903abf065c5cfcd1dac39307836c02a5f1667230a12bbd50.gz

**Comment by Tsun-hung** [comment]
The best 128*6 is 76f
####### 64*5 is  5748

**Comment by gcp** [comment]
Might be worthwhile filing this against the server, to get this + Elo for each net.
