### ISSUE TITLE
Can we estimate the correlation between internal and external ELO ?

### ISSUE THREAD

**Issue by kris-computer-go** [gcp/leela-zero#1225]
I'm observing similar project for Chess lczero.org
One guy id doing some kind of rating list for it by repeated matches between StockFish and each LeelaChess network. You can see it there: https://docs.google.com/spreadsheets/d/18UWR4FVhPi0vNwwPreu_avd9ycujGQ5ayR2LzJOWP4s/edit#gid=1674297534
there is a sheet called Rating Correlation from which you can estimate that IntELO = ExtELO * 0.6 - 600
so for example 5.000 IntELO is equivalent to about 2.400 ExtELO, 6.000 to 3.000, 7.000 to 3.600 and so on

Anybody has an idea how to estimate LeelaZero ext ELO similar way?

**Comment by gcp** [comment]
I think that has been done several times in other issues here by using CGOS.

**Comment by kris-computer-go** [comment]
OK so what is equivalent of 10.500 IntELO that LeelaZero has right now?

**Comment by herazul** [comment]
The best information we have about LZ level is cgos ELO : 
http://www.yss-aya.com/cgos/19x19/bayes.html

There is a lot of LZ weights running there.

**Comment by kris-computer-go** [comment]
So the best result is LZ_g7_t14   3.987 bayes ELO but what is the hardware (7 * GPU ?? 14 threads) and what is the line parameter we don't know, how many visits?
I can only say that it is similar to Zen-14.7-2c1g
