### ISSUE TITLE
an observe about network whose b are less than 64k

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1230]
in most cases, their winrate are smaller than 0.5,
while the others' winrate are bigger than that.

**Comment by l1t1** [comment]
![obs](https://user-images.githubusercontent.com/23301704/39082343-1a5af50c-4541-11e8-9b9d-ba16346051d6.png)

sorry for confuse, I made an xls file to clear it.

**Comment by Eddh** [comment]
It's probably SWA needing enough steps to be useful. I think it might be worth it to test 256k steps SWA too, even if the training time would be much longer.

**Comment by Marcin1960** [comment]
1560 match games in past 24 hours, 0 in past hour

**Comment by afalturki** [comment]
192k steps could be a nice middle-way that's not as long as 256k but can still give us an idea if SWA is much better for >128k

**Comment by gcp** [comment]
I made another change: to take SWA dumps every 4k.

**Comment by alphaladder** [comment]
@gcp  great idea！ let us see.

**Comment by l1t1** [comment]
so 3f6c8dd8 wouldnt have b 96 160 etc？
