### ISSUE TITLE
is it possible to make a program that anti leelazero speical weight file?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1235]
I read it at http://m.newsmth.net/article/Weiqi/615938.
the post is created by golaxy author, and babypig ask:
3. 为啥一定要公开leelazero的权重编号？要知道leelazero要你们的权重编号毫无意义，但是你们拿到了leelazero的权重编号，完全可以后台做个实时anti leelazero权重的程序，毕竟leelazero是公开的。

translate by google

3. Why do you have to disclose leelazero's weight number? To know that leelazero wants your weight numbers to be meaningless, but you get the weight numbers of leelazero, and you can do a real-time anti leelazero weight program in the background. After all, leelazero is open.

**Comment by pheasant75** [comment]
LZ is currently weaker than golaxy, we need to admit it and move on with our effort to improve LZ.  Is it possible? Maybe.  Is it reasonable? No.  I don’t think it worth their effort to create such program.  Their goal is to beat Ke Jie.  That is a bigger publicity stunt than beating LZ.
