### ISSUE TITLE
Leela Zero next crash in dump_stats on line 222

### ISSUE THREAD

**Issue by Cabu** [gcp/leela-zero#1241]
To reproduce:
1) Start Leela next in GTP mode "leelaz --gtp -w mynetwork"
2) Enter the command "time_left B 0 0"
3) Try to enter any other command eg: "quit"
At that moment Leela will start to dump the stats, but will crash after some lines.

**Comment by gcp** [comment]
This works correctly for me, in both release and debug mode.

**Comment by gcp** [comment]
a) Is this the current next branch without local changes?
b) Can you reproduce under GDB and get a backtrace?

**Comment by Cabu** [comment]
Thanks ! My next branch was not completely up-to date. Updating it solved the problem !
