### ISSUE TITLE
How to build a static binary file in macOS?

### ISSUE THREAD

**Issue by zhanzhenzhen** [gcp/leela-zero#1243]
I've built leelaz on one Mac (this Mac has boost), but I also want it to run on another Mac, where I don't want to install boost. So boost must be included in the binary. I'm new to C++. Could anyone tell me how?

**Comment by zhanzhenzhen** [comment]
@gcp Can't find `/usr/local/lib/libboostblah-mt.a`. In fact it doesn't have to be static. I just don't want to install brew, which will significantly modify the permissions of everything inside the `/usr/local` directory. Also, I'd prefer to place boost in my user directory, not in `/usr/local` directory. If that can be achieved, dynamic is also fine.

So, today I downloaded the source code of boost and copied "boost_1_67_0/boost" to "leela-zero/src/boost", then make. Boost is successfully included but, finally it says this error:

```
g++ -flto -g -o leelaz Network.o FullBoard.o KoState.o Training.o TimeControl.o UCTSearch.o GameState.o Leela.o SGFParser.o Timing.o Utils.o FastBoard.o SGFTree.o Zobrist.o FastState.o GTP.o Random.o SMP.o UCTNode.o UCTNodeRoot.o OpenCL.o OpenCLScheduler.o NNCache.o Tuner.o  -framework Accelerate -framework OpenCL -lboost_program_options -lpthread -lz
ld: library not found for -lboost_program_options
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [leelaz] Error 1
make: *** [default] Error 2
```

**Comment by tterava** [comment]
I actually struggled with this a bit just a few days ago. Did you notice that boost_program_options is one of the libraries that has to be compiled before it can be used?

**Comment by zhanzhenzhen** [comment]
@tterava Yes, I've looked into the Getting Started tutorial. It says `Boost.ProgramOptions` must be separately built. But after separately built, how to modify the "Makefile" of leelaz? I'm not familiar with C++.

**Comment by zhanzhenzhen** [comment]
@tterava Have you finally solved this?

**Comment by gcp** [comment]
>Can't find /usr/local/lib/libboostblah-mt.a.

You have to replace "blah" by the libs that are used, in Leela's case libboost_program_options-mt.a Just do that on the machine with boost installed, and the resulting executable will be dynamically linked but have the boost lib statically linked in.

**Comment by zhanzhenzhen** [comment]
@gcp Oh thank you 😆
