### ISSUE TITLE
counting issue or normal ?

### ISSUE THREAD

**Issue by wonderingabout** [gcp/leela-zero#1246]
Hi everyone,

I was looking at b908a080 's matches vs network 127 , and i have 2 questions about this game 

![manual scoring](https://user-images.githubusercontent.com/38690718/39185825-c0ed6254-47c8-11e8-938d-e0eadd39f9ba.PNG)

1) final score is written as B+7.5 : 
http://zero.sjeng.org/viewmatch/88f9c9afc299c27ba15a212c12787fbbbafccc33b056b57d688550eda7ad2648?viewer=wgo

however, the R8 group was not captured (and some white stones too), so i manually cleaned it by capturing all the stones, and i get final result : B+0.5

detail : b = 140+44=184 , w = 136+40+7.5 = 183.5

Was leela zero too "lazy" to clean the stones since it knew it still lost by 0.5 ?
or did it think the R8 group was alive, which would mean it counted wrong ?
or is it just related to how endgame cleaning works ?

2) EDIT : solved .
2nd question : is black a8 a seki move at bottom left ?

Thanks for explaining, i really love the leela zero project, keep up !

**Comment by l1t1** [comment]
please edit # 127 , it is wrong linked, you may use hash value instead

**Comment by wonderingabout** [comment]
done, i also edited other parts of the comment, thank you

**Comment by Friday9i** [comment]
For question 2, black A8 is followed by White B7, which gives 1 eye for White, allowing the kill of black stones: hence, it is fully alive, not a seki. For question 1, not sure (I'd say it was lazzy)

**Comment by wonderingabout** [comment]
@Friday9i 

yes you're right about the b7 move, so it's not a seki indeed, i'll edit the question :slightly_smiling_face: 

so the question left is about scoring

**Comment by tterava** [comment]
LZ probably knew it would lose but the evaluation wasn't low enough for it to resign. It's often around 20% if it's a 0.5 point win. Clearing the stones probably would have made it more sure so it chose not to do it.

As long as LZ doesn't throw a won game to something stupid, everything is possible.
