### ISSUE TITLE
Building Validation.exe on Windows

### ISSUE THREAD

**Issue by tterava** [gcp/leela-zero#1247]
I would like build LZ's validation executable to test games on windows environment. Are there any instructions on how to do it or would it be possible to add the executable under Releases?

I've tried installing Qt, but it doesn't find boost libraries no matter what I try.

**Comment by gcp** [comment]
Building Validation shouldn't require boost?

How are you trying to build?

**Comment by tterava** [comment]
Here's the steps required. Big thanks to @kuba97531 for helping me out!

```
- Install QT with MSVC integration
- In MSVC go Open -> CMake. Find CMakeLists.txt under validation folder
- If it doesn't find Qt5::core, add the following lines:
set (CMAKE_PREFIX_PATH "C:\Qt\5.10.1\msvc2017_64")
find_package( Qt5CORE )
- CMake -> Build Only -> Validation.exe
```

It should appear under C:\users\USERNAME\CMakeBuilds

**Comment by l1t1** [comment]
could you attatch the exe in this post ?

**Comment by tterava** [comment]
[validation.zip](https://github.com/gcp/leela-zero/files/1955577/validation.zip)

**Comment by l1t1** [comment]
is the exe file for win64 or win32? my anti-v tool 360 said it was a Trojan.

**Comment by tterava** [comment]
It's Win64. Build it yourself if you don't trust it.

**Comment by l1t1** [comment]
I copy it into leelaz 0.13's directory, and run it with following errmsg
![2018-05-02_094047](https://user-images.githubusercontent.com/23301704/39501300-a9725e70-4dec-11e8-878d-c9eb90d2f933.png)

```
2018/03/25  05:21           222,720 autogtp.exe
2017/10/23  13:55           236,061 curl-ca-bundle.crt
2017/10/23  13:55         3,157,504 curl.exe
2017/08/31  20:17           102,640 gzip.exe
2018/03/25  05:12         2,313,216 leelaz.exe
2018/04/09  19:20               416 leelaz_opencl_tuning
2015/12/29  06:25           120,334 libgcc_s_dw2-1.dll
2018/01/08  21:34        30,533,118 libopenblas.dll
2015/12/29  06:25         1,540,622 libstdc++-6.dll
2015/12/29  06:25            79,360 libwinpthread-1.dll
2017/10/05  21:34         2,983,837 msys-2.0.dll
2017/08/31  20:17           112,382 msys-gcc_s-1.dll
2018/05/02  07:50    <DIR>          networks
2018/01/08  01:03           103,424 OpenCL.dll
2018/04/26  08:07            49,910 OpenCL.zip
2017/11/09  17:08         6,097,408 Qt5Core.dll
2017/12/07  19:52               350 README.txt
2018/05/02  08:26    <DIR>          sga
2018/04/24  19:17           158,208 validation.exe
```

**Comment by tterava** [comment]
It's probably using some optimization your CPU is lacking. I still recommend you just build it yourself, as Visual Studio Community 2017 is free and easy to install.

**Comment by genleung** [comment]
Can LZ benefit from using Intel TBB & Intel IPL64 interfaces ?
