### ISSUE TITLE
A very long  sequence of winner b908

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1248]
I found a long sequence
![2018-04-24_201616](https://user-images.githubusercontent.com/23301704/39186365-bb7f7334-47b9-11e8-922e-f640dbae38ba.png)
 of winner b908 netwrok at http://zero.sjeng.org/match-games/5adf0172eb7c9575993a9525.
Is it all done by chance?

**Comment by l1t1** [comment]
![2018-04-24_202658](https://user-images.githubusercontent.com/23301704/39186710-de55a6fc-47ba-11e8-9817-11369c76d1ce.png)
it is clear the fast clients got too many tasks, for example, client no.12 got about 1/10 games of all 79 clients, so its effect are much bigger than others, is it fair?

**Comment by gcp** [comment]
>Is it all done by chance?

Probably, this happens a lot. It doesn't even have to be chance, some networks win a lot of games in the opening so results come in in batches. That's one reason we now require 100 games to pass.

**Comment by gcp** [comment]
>is it fair?

Faster clients finish more games, yes. There's a number of pull requests on the server side now to ensure that clients can't send in match results they weren't asked about, and the allocation of matches depends on finishing self-play games.

Unless you have some concrete indication something is wrong, these posts are totally pointless.

**Comment by l1t1** [comment]
I see.

**Comment by l1t1** [comment]
http://zero.sjeng.org/match-games/5adf2243eb7c9575993a9526 ,is the  client no.4 the same one of prior match's no.12?
