### ISSUE TITLE
Training steps

### ISSUE THREAD

**Issue by Hisairnessag3** [gcp/leela-zero#1253]
Arent we at this point and time taking many more steps to reach the same performance when compared to alphazero? If so, why is that?

**Comment by afalturki** [comment]
I think he means the number of games.

**Comment by Hisairnessag3** [comment]
^ Essentially yes. See figure 1 of the alphazero paper for reference

**Comment by gcp** [comment]
But graph 1 of the Alpha Zero paper refers to training steps, not games.

The training steps aren't comparable. The mini batch size is different, the speed between clients and training server isn't constant, and training is reset after every 128k steps.
