### ISSUE TITLE
can leelaz run on mobile phone?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1254]
I saw a news at https://sports.sina.cn/others/qipai/2018-04-24/detail-ifzqvvsa7119699.d.html?from=wap .
I wonder how did the man do it?

**Comment by gcp** [comment]
#779

**Comment by roy7** [comment]
If he's wearing headphones too and not actually pulling his phone out to make moves which would be very suspicious, maybe the phone' camera is on streaming to a friend and the friend is telling him moves over the phone/headphones.

**Comment by l1t1** [comment]
the sgf http://duiyi.sina.com.cn/gibo_new/giboviewer/giboviewer.asp?gibo=http://duiyi.sina.com.cn/cgibo/20184/ls2018qy2-180424h.sgf&gibonum=45016&bimg=&wimg=huyiqing.jpg

**Comment by l1t1** [comment]
@gcp your link is a cpu version,
but from the article,  he use a higher version.

**Comment by l1t1** [comment]
https://tieba.baidu.com/p/5669858358 shows how to use mobile phone to read board

**Comment by l1t1** [comment]
https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android maybe help
