### ISSUE TITLE
i want to use more resource of my computer,how can i add paramter to autogtp

### ISSUE THREAD

**Issue by hilbertcao** [gcp/leela-zero#1256]
windows exe

**Comment by hydrogenpi** [comment]
You mean to help train LZ network? I don't know about parameters I'll leave that to others, but my own advise is if you want to help more, then get a more powerful gpu and spread the word. simple as that.

**Comment by hilbertcao** [comment]
@hydrogenpi  tks your answer

**Comment by Mardak** [comment]
To actually answer your question, see #614. You can create a .bat and pass in `-g 2` to run 2 at a time. Alternatively, just run 2 instances of autogtp.exe
