### ISSUE TITLE
my computer has two gpu,how to use all of them?more thread will helpful for train leela?

### ISSUE THREAD

**Issue by hilbertcao** [gcp/leela-zero#1258]

**Comment by Mardak** [comment]
As in setting parameters for #1256, you can specify the gpu index with `-u`. Check the output to see what the gpu index is. The options:

https://github.com/gcp/leela-zero/blob/97c2f8137a3ea24938116bfbb2b0ff05c83903f0/autogtp/main.cpp#L50-L79

**Comment by hilbertcao** [comment]
@Mardak tks
