### ISSUE TITLE
Time Control: Save time on first few moves

### ISSUE THREAD

**Issue by bood** [gcp/leela-zero#1259]
Currently, each move is given remaining_time/moves_remaining in main time. See:
https://github.com/gcp/leela-zero/blob/next/src/TimeControl.cpp#L186-L190
and
https://github.com/gcp/leela-zero/blob/next/src/TimeControl.cpp#L220-L227

This seems to be not optimal for Go in the first few moves. For example, in a 15 minutes match with time management on, first move would be given 15*60/(19*19/9) = ~22 seconds. Noticing several moves have almost the same visits so time management cannot help here.

Some hack code could be written like giving first 5 - 10 moves a max thinking time. But I wonder if there is a general way to optimize this a bit and save time for later use.

```
Leela: genmove b
Thinking at most 22.5 seconds...
NN eval=0.476264
Playouts: 87, Win: 47.78%, PV: C16 Q4 R3 Q3 R4
Playouts: 188, Win: 47.79%, PV: C16 Q4 R3 R4 Q3 P3
Playouts: 298, Win: 47.75%, PV: D17 Q4 R3 R4 Q3 P3 P2
Playouts: 411, Win: 47.77%, PV: D3 Q16 R17 R16 Q17 P17 P18 O18
Playouts: 565, Win: 47.77%, PV: Q17 D4 C3 C4 D3 E3 E2 F2
Playouts: 690, Win: 47.78%, PV: Q17 D4 C3 C4 D3 E3 E2 F2
Playouts: 814, Win: 47.78%, PV: D3 Q16 R17 R16 Q17 P17 P18 O18
Playouts: 964, Win: 47.78%, PV: D17 Q4 R3 R4 Q3 P3 P2 O2 O3

 D17 ->     129 (V: 47.77%) (N:  9.83%) (LCB: 34.20%) (UCB: 61.58%) PV: D17 Q4 R3 Q3 R4 R5 S5 S6 R6
  D3 ->     127 (V: 47.81%) (N:  9.51%) (LCB: 34.13%) (UCB: 61.72%) PV: D3 Q16 R17 R16 Q17 P17 P18 O18 O17
 R16 ->     127 (V: 47.79%) (N:  9.63%) (LCB: 34.12%) (UCB: 61.70%) PV: R16 D4 C3 D3 C4 C5 B5 B6 C6
 Q17 ->     126 (V: 47.80%) (N:  9.50%) (LCB: 34.08%) (UCB: 61.77%) PV: Q17 D4 C3 D3 C4 C5 B5 B6 C6
 C16 ->     124 (V: 47.78%) (N:  9.55%) (LCB: 33.94%) (UCB: 61.85%) PV: C16 Q4 R3 Q3 R4 R5 S5 S6 R6 Q5
  C4 ->     123 (V: 47.81%) (N:  9.32%) (LCB: 33.92%) (UCB: 61.94%) PV: C4 Q16 R17 Q17 R16 R15 S15 S14 R14
  R4 ->     123 (V: 47.79%) (N:  9.38%) (LCB: 33.90%) (UCB: 61.92%) PV: R4 D16 C17 D17 C16 C15 B15 B14 C14
  Q3 ->     119 (V: 47.76%) (N:  9.29%) (LCB: 33.65%) (UCB: 62.13%) PV: Q3 D16 C17 C16 D17 E17 E18 F18 F17
  D4 ->      31 (V: 47.77%) (N:  2.70%) (LCB: 21.41%) (UCB: 75.06%) PV: D4 Q16 R17 R16 Q17 P17 P18
 D16 ->      30 (V: 47.67%) (N:  2.79%) (LCB: 20.96%) (UCB: 75.39%) PV: D16 Q4 R3 Q3 R4 R5 S5
 Q16 ->      30 (V: 47.67%) (N:  2.78%) (LCB: 20.96%) (UCB: 75.38%) PV: Q16 D4 C3 D3 C4 C5 B5
  Q4 ->      29 (V: 47.69%) (N:  2.68%) (LCB: 20.59%) (UCB: 75.82%) PV: Q4 D16 C17 C16 D17 E17 E18
5.2 average depth, 11 max depth
727 non leaf nodes, 1.54 average children
1119 visits, 400422 nodes, 1118 playouts, 50 n/s
```

**Comment by Cabu** [comment]
One of the tools that save a lot of time in the first moves of a game is called an opening book. There is a very good one generated by the Alpha Zero team (https://alphagoteach.deepmind.com/dist/files/book.sgf). 
Even if only the first move is taken from the book before the other player deviate from the book, it is still 2% of a 20min game saved to think on another trickier move further in the game.

**Comment by bood** [comment]
AQ uses the following strategy, seems to be more reasonable:
https://github.com/ymgaq/AQ/blob/master/src/search.cpp#L1097-L1100

It assumes the moves_remaining to be `95 - current_move_count` if current_move_count is below 50, and remains 55 afterwards. It actually reduces the time being used in first 50 moves. It looks more reasonable.

LC0 on the other hand seems borrowed the time control system from Stockfish, which is out of my scope:
https://github.com/glinscott/leela-chess/blob/master/src/TimeMan.cpp

**Comment by bood** [comment]
Made a quick move for anyone interested (not resource for testing):
https://github.com/bood/leela-zero/tree/tc_tune

A new option `--fastmove N` is added to allow making first N moves to be fast a bit (change expected moves to `100-movenum`), after move N, it falls back to the current time control. Default N is set to 20.

**Comment by gcp** [comment]
Thanks. I'll set up a tuning run and see if we get a gain from this.

**Comment by Marcin1960** [comment]
Would it be possible to train nets only for the first moves,  to discover new josekis?

**Comment by MaxMaki** [comment]
@Marcin1960 We already are, and we already are discovering new joseki, and Leela Zero has shown since the starts that it's capable of  discovering, learning, perfecting and discarding josekis on its own.

You can easily verify this by downloading the self-play games and match games and go through them from the days of the 5x64 networks, to today. You'll notice that new joseki first start appearing in self-play, then they become more popular or get discarded. Once they've been in the self-play for quite a bit they start appearing in matches. Josekis come into favour and go out of favour with Leela Zero. 

In the AlphaGo Zero paper as well, you can see in their charts that josekis came into favour and then went out of favour. It's working exactly like that.

**Comment by OmnipotentEntity** [comment]
Thus far this looks very promising. (450 seconds total think time)

```
leelaz-next v leelaz-tc (101/400 games)                 
board size: 19   komi: 7.5                              
              wins              black         white       avg cpu                                               
leelaz-next     37 36.63%       16 31.37%     21 42.00%    666.70                                               
leelaz-tc       64 63.37%       29 58.00%     35 68.63%    665.53                                               
                                45 44.55%     56 55.45% 
```

**Comment by gcp** [comment]
Yes, tuning is running but this looks like it could be a huge Elo gainer.

**Comment by roy7** [comment]
I don't know where your post was about testing the scaling strength of extra moves, but it was impressive how strong doubling the visit count was at all of those steps. For fixed time clocks (30 minute CGOS comes to mind) all of these time saving tools seem super valuable. I'm so used to seeing byoyomi based games though that I wonder how much impact it'd have in "real life". Or even in visit capped selfplay training/matches.

**Comment by OmnipotentEntity** [comment]
```
leelaz-next v leelaz-tc (163/400 games)                 
board size: 19   komi: 7.5                              
              wins              black         white       avg cpu                                               
leelaz-next     63 38.65%       27 32.93%     36 44.44%    672.69                                               
leelaz-tc      100 61.35%       45 55.56%     55 67.07%    671.84                                               
                                72 44.17%     91 55.83%
```

This is a 35 elo SPRT pass.  So I'm stopping the test.  It's definitely worth it for fixed time.

**Comment by bood** [comment]
Given the promising test result, should I submit a PR for this? @gcp

**Comment by Eddh** [comment]
Maybe the optimum depends on how much nodes/second you can get with your hardware ? I'm thinking for example ladders can happen within the first 40 moves, and if you have high node/s you can avoid them despite shorter time. On the other hand on slow hardware thinking fast in the early games might lead to big mistake.

**Comment by gcp** [comment]
>Given the promising test result, should I submit a PR for this? @gcp

I would like to see the comparison if 60 makes a difference, and if I can get a good value for 9x9, we can come up with something to cover all board sizes. So yes, we should add this, but give us a few moments to make it as good as we can.

**Comment by gcp** [comment]
>Maybe the optimum depends on how much nodes/second you can get with your hardware ?

You can always throw up the question about time controls or portability across networks for any change made to the program, but this will mostly lead to not making much progress :-)

Given that tests show fairly constant Elo gains per speed doubling, I see no reason to doubt this change is fairly solid. We can see it in self-play so ladders shouldn't be an issue. I think it's more likely that having extra time when fighting breaks out is what ends up helping.

**Comment by gcp** [comment]
After seeing that CLOP tuning to 60 mean that the transition between both was very smooth, I changed the code to:

```
    // Note this is constant as we play, so it's fair
    // to underestimate quite a bit.
    auto base_remaining = (m_boardsize * m_boardsize) / board_div;

    // Don't think too long in the opening.
    if (movenum < cfg_fastmove_cnt) {
        return (base_remaining + cfg_fastmove_cnt) - movenum;
    } else {
        return base_remaining;
    }
```

Which should have the same effect, but easier to tune for 9x9 (and intermediate boards) too.

**Comment by gcp** [comment]
Tuning for boardsize 9 showed negligible gain, and fastmove optimal around 16.

**Comment by gcp** [comment]
I pushed this as a branch: https://github.com/gcp/leela-zero/tree/tc_tune

It would be really good to recheck this against bood's branch (using fastmoves=20).

**Comment by roy7** [comment]
@gcp @bood Do we feel like I should merge in tc_tune for the game vs Haylee this Sunday? And use --fastmoves=20?

**Comment by gcp** [comment]
Yes, definitely at least bood's branch. I'm not sure I'll get a good test result from mine in time.
