### ISSUE TITLE
The file is missing to me.(leels zero)

### ISSUE THREAD

**Issue by pplhost** [gcp/leela-zero#1263]
normal file(leela zero)
autogtp.exe
curl.exe
curl-ca-bundle.crt
gzip.exe
leelaz.exe
leelaz_opencl_tuning
leelaz-model-swa-16-128000-.txt
libgcc_s_dw2-1.dll
libopenblas.dll
libstdc++-6.dll
libwinpthread-1.dll
msys-2.0.dll
msys-gcc_s-1.dll
OpenCL.dll
Qt5Core.dll
README.txt

But, I don't have three files. 
leelaz_opencl_tuning
leelaz-model-swa-16-128000-.txt
OpenCL.dll

How can I download three files?

**Comment by l1t1** [comment]
leelaz_opencl_tuning  -- run autogtp
leelaz-model-swa-16-128000-.txt  -- run autogtp will download latest best network file
OpenCL.dll --- see attachment
[OpenCL.zip](https://github.com/gcp/leela-zero/files/1949216/OpenCL.zip)

**Comment by gcp** [comment]
OpenCL.dll should be included in the release .zip? Is it missing?

**Comment by pplhost** [comment]
It was not included in the downloaded file.

**Comment by gcp** [comment]
What did you download and from where? I checked the official release and the file seems to be there?
