### ISSUE TITLE
Windows binary of Validation.exe

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1268]
for example, my computer is slow, so I won't got 88ccb0fa   VS  158603eb task, but I want download them and play, thanks

**Comment by hydrogenpi** [comment]
test

**Comment by gcp** [comment]
The validation tool is able to do this.

It's not in the binary releases, though.

**Comment by l1t1** [comment]
yes, could you supply a windows exe?

**Comment by kuba97531** [comment]
There are instructions on how to build validation.exe on windows in #1247

**Comment by l1t1** [comment]
I download it from https://github.com/gcp/leela-zero/issues/1247 , but my auti-v tool 360 said it was a Trojan.

**Comment by l1t1** [comment]
glad to see it is included in  https://github.com/gcp/leela-zero/releases/download/v0.14/leela-zero-0.14-cpuonly-win32.zip

**Comment by gcp** [comment]
Fixed in 0.14.
