### ISSUE TITLE
Live stream for 2018 AI Go Competition in Fuzhou start from 10:00 UTC+8 (in Chinese)

### ISSUE THREAD

**Issue by fell111** [gcp/leela-zero#1270]
This is the only link I could find for watching LZ playing in the AI Go Competition. The live stream will lasts for 8 hours from 10:00 to 18:00 UTC+8. It will cover both AI matches and the match between Ke Jie and Golaxy.
MobilePhone https://live.bilibili.com/h5/94534
DesktopBrowser https://live.bilibili.com/94534?from=search&seid=17818747972810790144

Also the live match could be found in YikeWeiQi website.
http://portal.yikeweiqi.com/online/golive/index.html

round 1 LZ vs Golois
http://portal.yikeweiqi.com/online/golive/detail?id=8555

round 2 LZ vs DolBaram 
http://portal.yikeweiqi.com/online/golive/detail?id=8558

round 3 LZ vs Fine Art
http://portal.yikeweiqi.com/online/golive/detail?id=8571

round 4 LZ vs Phoenix Go (BensornDarr)
http://portal.yikeweiqi.com/online/golive/detail?id=8579 

round 5 LZ vs HEROZ Kishin
http://portal.yikeweiqi.com/online/golive/detail?id=8582

The hardware for LZ is 6 x 1080ti. But the weight file is not decided yet. The report (in Chinese) could be found here http://www.yikeweiqi.com/news/topline/44206/

**Comment by roy7** [comment]
Do you know of an easy way to find the actual game links, not the ones from the golive/ page? ie: Ones that make sounds every time a stone is placed?

**Comment by l1t1** [comment]
game 1 http://duiyi.sina.com.cn/gibo_new/live/viewer.asp?sno=6

**Comment by l1t1** [comment]
![2018-04-27_104039](https://user-images.githubusercontent.com/23301704/39341737-1ed3308e-4a07-11e8-95dc-05dc66991cf8.png)

leelaz win 1 game

**Comment by l1t1** [comment]
the sgf of game 1 http://duiyi.sina.com.cn/cgibo/20184/1brjy1-180427ll.sgf

--------------------------------------------

(
TE[1届贝瑞基因杯世界AI预赛1]
RD[2018-04-27]
PC[福州滨海新城网龙基地]
TM[30分钟包干]
LT[]
LC[]
KO[7.5]
RE[黑中盘胜]
PB[LeelaZero]
BR[]
PW[Golois]
WR[]
GK[1]
TC[]


;B[qp];W[cc];B[pd];W[dq];B[co];W[dm];B[eo];W[fp];B[np];W[cp];B[bp];W[bq];B[fo];W[gp]
;B[go];W[hp];B[dp];W[cq];B[dj];W[fm];B[ho];W[hm];B[el];W[em];B[jo];W[ip];B[gl];W[gm]
;B[io];W[kq];B[ce];W[jm];B[il];W[im];B[lp];W[ec];B[kp];W[kk];B[bc];W[qj];B[cd];W[hc]
;B[qg];W[nc];B[ql];W[qc];B[pc];W[qd];B[pe];W[pb];B[ob];W[qb];B[oc];W[qe];B[qf];W[of]
;B[pi];W[ne];B[pf];W[pl];B[pm];W[pk];B[om];W[nk];B[mh];W[nb];B[og];W[ng];B[nh];W[oh]
;B[oi];W[pg];B[ph];W[og];B[mg];W[lf];B[nd];W[md];B[mc];W[od];B[oe];W[nf];B[nd];W[qm]
;B[ld];W[od];B[mb];W[mf];B[qn];W[nd];B[na];W[mj];B[jc];W[ni];B[je];W[kd];B[ic];W[jg]
;B[kg];W[lc];B[lb];W[kh];B[ig];W[ih];B[jf];W[jh];B[le];W[lg];B[dc];W[kc];B[kb];W[eh]
;B[kf];W[lh];B[dh];W[qq];B[eg];W[eb];B[pq];W[pr];B[rq];W[lr];B[db];W[he];B[lq];W[mr]
;B[jq];W[qr];B[nr];W[pp];B[oq];W[rp];B[qo];W[rr];B[hb];W[gc];B[ir];W[pa];B[oa];W[dd]
;B[de];W[ei];B[di];W[ck];B[ep];W[eq];B[bn];W[dn];B[do];W[hr];B[cl];W[dk];B[dl];W[ek]
;B[ej];W[fk];B[fl];W[fj];B[hl];W[bl];B[cm];W[bm];B[cn];W[or];B[jl];W[fg];B[kl];W[dg]
;B[cg];W[ef];B[bh];W[kr];B[jp];W[mq];B[nq];W[mp];B[no];W[mo];B[mn];W[is];B[ln];W[ro]
;B[rm];W[ri];B[ed];W[rf];B[rg];W[sf];B[gb];W[fd];B[qh];W[ll];B[lm];W[bi];B[df];W[ee]
;B[fb];W[dd];B[ea];W[cj];B[eg];W[if];B[ed];W[dg];B[fc];W[ch];B[eg];W[ie];B[jd];W[dg]
;B[re];W[rd];B[eg];W[nn];B[nm];W[dg];B[sg];W[se];B[eg];W[on];B[oo];W[dg];B[sd];W[sc]
;B[eg];W[me];B[ke];W[dg];B[js];W[jr];B[eg];W[iq];B[dg];W[fe];B[ci];W[lo];B[kn];W[bj]
;B[hd];W[gd];B[id];W[ij];B[jk];W[rk];B[aq];W[ar];B[ap];W[an];B[br];W[cr];B[as];W[ml]
;B[kj])

**Comment by roy7** [comment]
Any eta or info on round 2? I see they are using max_lcb_root. :)

**Comment by PhilipFRipper** [comment]
Live stream doesn't work for me, any other options?  Sorry have difficulty understanding the chinese sites.

**Comment by l1t1** [comment]
visit http://duiyi.sina.com.cn/gibo/new_gibo.asp
and input  LeelaZero to find all her games

**Comment by l1t1** [comment]
round 2 http://duiyi.sina.com.cn/gibo_new/live/viewer.asp?sno=12

**Comment by roy7** [comment]
Thanks @l1t1. I'll try streaming it https://www.twitch.tv/jroy7.

**Comment by roy7** [comment]
Is http://portal.yikeweiqi.com/online/golive/index wrong web site?

**Comment by l1t1** [comment]
your site is right, but you should choose from tab to find leelazero @roy7 
http://portal.yikeweiqi.com/online/golive/detail?id=8558

**Comment by roy7** [comment]
Is this game 2? http://portal.yikeweiqi.com/online/golive/detail?id=8558

If so can someone find a link with timers and board sound effects?

**Comment by roy7** [comment]
Ok I'm streaming game but if you can give me link for the real game with timers and sound effects it makes things much much much easier for me to stream it.

**Comment by l1t1** [comment]
http://duiyi.sina.com.cn/gibo_new/live/viewer.asp?sno=12 is advanced about 3 moves than  http://portal.yikeweiqi.com/online/golive/detail?id=8558

**Comment by roy7** [comment]
https://www.twitch.tv/jroy7/

**Comment by l1t1** [comment]
I can hear the sound at sina site
![2018-04-27_110756](https://user-images.githubusercontent.com/23301704/39342549-1721d486-4a0b-11e8-8fe3-5369f64c0cf9.png)
 , if you cannot, click the speaker icon at bottom to open

**Comment by alreadydone** [comment]
https://live.bilibili.com/94534

**Comment by l1t1** [comment]
![2018-04-27_133149](https://user-images.githubusercontent.com/23301704/39346117-0beab1d2-4a1f-11e8-8188-3f1670abfbd0.png)
leelaz cost more time at round3
