### ISSUE TITLE
Benchmarking requests - USE_HALF, faster tuner

### ISSUE THREAD

**Issue by gcp** [gcp/leela-zero#1273]
This is for people who are able to compile their own Leela Zero and have a GPU. Get the latest next branch. Get the latest network.

Run a ./leelaz -w network --benchmark -t 4 
(For a single card, using more than 4 threads doesn't tend to make a difference for me)

Now:
a) in your leelaz_opencl_tuning file, look for -DVWM=x -DVWN=y

Is any of x or y == 1?
If so, go to: https://github.com/gcp/leela-zero/blob/master/src/Tuner.cpp#L228 and remove "1" from the VWM and VWN lists.

Delete the tuning, retune, and rerun the benchmark. Does it have any significant impact on performance?

My theory is that there exist no cards for which using 1 is faster than the alternatives, barring random noise. 

b) in your leelaz_opencl_tuning file, look for SA=x, SB=y

Is any of x or y == 0?
If so, what card is this?
If so, go to: https://github.com/gcp/leela-zero/blob/master/src/Tuner.cpp#L228 and remove 0 from SA/SB. Delete tuning, retune, rerun benchmark. What is the impact on performance?

My theory is that there exist no (modern? non-AMD?) cards for which using 0 is faster than the alternatives, barring random noise. 

c) Wipe output dir, undo any source code changes from previous steps, rerun cmake but add -DUSE_HALF=1. Rerun the benchmark. What speed gain do you get?

**Comment by rchs819** [comment]
I got false for a) & b) do I proceed c) ?
(GTX970 on Windows 7)

**Comment by gcp** [comment]
Yes, it's 3 independent things to find out.

**Comment by radha** [comment]
My setup: GTX 1060, cuda 8, debian 9
Got a no for a and b
"0;XgemmBatchedHalf;192;100;192;16; -DKWG=32 -DKWI=2 -DMDIMA=16 -DMDIMC=16 -DMWG=64 -DNDIMB=8 -DNDIMC=8 -DNWG=64 -DSA=1 -DSB=1 -DSTRM=0 -DSTRN=0 -DVWM=4 -DVWN=4;OpenCL: NVIDIA Corporation GeForce GTX 1060 @ 1670MHz"
first benchmark: 510 n/s
second benchmark with -DUSE_HALF=1: 627 n/s

**Comment by akdtg** [comment]
Intel Graphics HD 620, Linux 4.14
OpenCL: OpenCL 1.2 beignet 1.3

Initial leelaz_opencl_tuning:
0;XgemmBatched;192;100;192;16; -DKWG=32 -DKWI=2 -DMDIMA=16 -DMDIMC=16 -DMWG=64 -DNDIMB=8 -DNDIMC=8 -DNWG=64 -DSA=0 -DSB=0 -DSTRM=0 -DSTRN=0 -DVWM=4 -DVWN=2;OpenCL: Intel Intel(R) HD Graphics Kabylake ULT GT2 @ 1000MHz

a) -DVWM=4 -DVWN=2
3204 visits, 1130274 nodes, 3203 playouts, 36 n/s

b) -DSA=0 -DSB=0 ==> -DSA=1 -DSB=1
3205 visits, 1130662 nodes, 3204 playouts, 36 n/s

c) -DUSE_HALF=1
3210 visits, 1132423 nodes, 3209 playouts, 33 n/s

**Comment by gcp** [comment]
@akdtg Thanks, that's very useful and the kind of thing that is interesting for me. It shows that there would be penalty forcing the card to use SA=1/SB=1, but that it does slow down a bit from USE_HALF.

**Comment by TFiFiE** [comment]
>b) in your leelaz_opencl_tuning file, look for SA=x, SB=y

I assume you meant to write `DSA` and `DSB` here.

I have a GeForce GTX 750 Ti: a) and b) didn't apply and I went from about 188 to 239 nodes per second.

**Comment by Cabu** [comment]
GeForce GTX 960M
Windows 10

a) no: -DVWM=4 -DVWN=4  @ 151 n/s
b) no: -DSA=1 -DSB=1  @ 151 n/s
c) How can I do it with Visual Studio 2017?

**Comment by kuba97531** [comment]
a) I had  VWN =1 for the 128 net so I tried benchmark on this net. After retuning the value was 2 instead of 1, but performance was exactly the same.
b) no
c) I have 2 GPU and there is a big difference between performance on t=4 and t=7 and also I have found that performance for the 128x10 network scales differently than performance of the most recent net. So I have created a test with the last 128x10 network (39d46507) and the most recent 192x15 (158603eb) for t=4,5,6,7 with and without USE_HALF. System is windows, release 64bit build.
1965 -> 2039 (+3%) means that without USE_HALF flag increased n/s from 1965 to 2039 so a 3% increase

network | t=4 | t=5 | t=6 | t=7
------- | --- | --- | --- | ---
128x10  (39d46507) | 1965 -> 2039 (+3%) | 2258 -> 2565 (+13%) | 2527 -> 2743 (+8%)  | 2700 -> 2999 (+11%)
192x15 (158603eb)  | 1004 -> 1030 (+2.5%)| 1057 -> 1139 (+8%)| 1107 -> 1229  (+11%) | 1170 -> 1319 (+12%)

**Comment by gcp** [comment]
> I have 2 GPU and there is a big difference between performance on t=4 and t=7

Yes, this (and there being a difference between the net sizes) makes sense. It's about keeping the GPUs fed. I was more or less assuming testing a single GPU at once for the above tests.

**Comment by kuba97531** [comment]
@Cabu
1) Go to leela-zero project properties -> Configuration Properties -> C/C++ -> Command Line -> Additional Options. Type /DUSE_HALF=1
2) in config.h change 
#include <half/half.hpp>
to 
#include "half/half.hpp"



and fix include <half/half.hpp>
#include "half/half.hpp"

**Comment by gcp** [comment]
I commited a fix for that to next.

**Comment by kuba97531** [comment]
Regarding my results: It seems that if I haven't specified --gpu 0 --gpu 1 explicitely than it runs benchmark on a single GPU. So my results are from single GPU. I could rerun the test for 2 GPU's if you're interested.

**Comment by gcp** [comment]
It's more interesting to know what CPU it was :-)

**Comment by kuba97531** [comment]
It's 1080Ti.

**Comment by Ka-zam** [comment]
Ubuntu 18.04, Intel G3900, GTX750Ti (don't laugh, office computer)

A) FALSE
B) FALSE
C) 
    USE_HALF=1:  3201 visits, 1128204 nodes, 3200 playouts, 218 n/s
    USE_HALF=0:  3206 visits, 1129783 nodes, 3205 playouts, 169 n/s

**Comment by gcp** [comment]
>GTX750Ti (don't laugh, office computer)

The first Leela with a DCNN was trained on a GTX 750 non-Ti.

**Comment by MartinDevelopment** [comment]
Google Colab:
a) false
b) false
c)
USE_HALF=1:  351 n/s
USE_HALF=0:  347 n/s

**Comment by Ka-zam** [comment]
@csuji According to this:[https://github.com/plaidml/plaidml/issues/29](Link) 
There should be native packed fp16 support for Vega already in or on the way. This promises 2x speedup if properly implemented. Could you tinker a little bit and try to glean some information? I would be very interested to go Radeon for my next build if this pans out. A little sick of proprietary extensions and artificially crippled hardware.

**Comment by csuji** [comment]
@Ka-zam is this USE_HALF benchmark about fp16 on GPU?  Nvidia GTX10x0 cards do not offer that and some users here report a notable speedup?! I thought about trying to use MIOpen library from AMD (their NN library) but do not really know where to start or if this would result in an improved performance of LZ considering the amount of work to put into (for me as I never used it and only browsed LZ source).

**Comment by Ka-zam** [comment]
@csuji That is my understanding. On CPU the IEEE half precision library is used for math functions and on GPU these are hardware implemented. This allows packed math, i.e doing two FP16 operations for every FP32. 

However, even though their hardware supports it Nvidia has chosen to not support this, actually disable it, for their consumer branded cards and instead they want to sell you the Titan V. This annoys me to no end.

So, if you can get the OpenCL libraries working and if fp16 packed math is enabled in the AMDGPU-PRO driver then 2x speedup should be possible. I understand that this may not be the case yet though.

**Comment by csuji** [comment]
Well, according to clinfo fp16 support is implemented:
```  Preferred / native vector sizes                 
    char                                                 4 / 4       
    short                                                2 / 2       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 1 / 1        (cl_khr_fp16)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (cl_khr_fp16)
```
So I am wondering why I only get a speedup of ~6% ?!

**Comment by gcp** [comment]
USE_HALF currently only changes the **storage** of the coefficients, not the actual computation. Basically any card supports fp16 storage. You get a nice speedup on some NVIDIA cards because they are internally bottlenecked on memory access, bit less so on the AMD ones.

Actually using fp16 for computation is tricky. Support may not mean the card is fast at it. Even if it supports it in a fast manner, we use algorithmic optimizations that are themselves worth more than a 2x speedup but require the computation to be done with sufficient precision. It's not clear fp16 is enough for that. You might note that the Tensor Cores that were added to modern DL cards use intermediate fp32 storage, partly to avoid problems like this. (And even so, when I tested cards with tensor cores with NVIDIA's own libs, it still disabled some maths optimizations and got a lot less speedup than expected)

**Comment by gcp** [comment]
For example, this is a Polaris card (RX560):

```
  Preferred / native vector sizes                 
    char                                                 4 / 4       
    short                                                2 / 2       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 1 / 1        (cl_khr_fp16)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (cl_khr_fp16)
 ```

Polaris has some minor fp16 optimizations but it most definitely does not run fp16 at twice the fp32 rate (Rapid Packed Math).

**Comment by csuji** [comment]
@cgp Ok, thank you. Besides fp16 what do you think the speedup for LZ would be if the SGEMM is twice as fast as it is now? Looking at results from hand optimized OpenCL vs. cublas (https://cnugteren.github.io/tutorial/pages/page12.html) this could be possible. AMD has also handcrafted Vega asm instructions for their kernels in MIOpen. So perhaps same speedup is achievable?!  (wild guess as I have not used it)

**Comment by SebastienFaurite** [comment]
On ubuntu GTX 1070
a) false
b) false
c)
USE_HALF=0 : 3207 visits, 1131198 nodes, 3206 playouts, 876 n/s
USE_HALF=1 : 3208 visits, 1131599 nodes, 3207 playouts, 1137 n/s

30% increase, quite nice !

**Comment by Ka-zam** [comment]
Home computer: Ubuntu 18.04, Ryzen 2700X, GTX1080

A) FALSE
B) FALSE
C)
`USE_HALF=0: 3203 visits, 1128378 nodes, 3202 playouts, 979 n/s`
`USE_HALF=1: 3206 visits, 1129406 nodes, 3205 playouts, 1335 n/s`

**Comment by hydrogenpi** [comment]
1901 -> 1979

**Comment by ChinChangYang** [comment]
Ubuntu 18.04, GeForce GTX 1050

A) FALSE
B) FALSE
C)
USE_HALF=0: 3204 visits, 1130215 nodes, 3203 playouts, 286 n/s
USE_HALF=1: 3205 visits, 1130690 nodes, 3204 playouts, 333 n/s

**Comment by Ka-zam** [comment]
@tterava What's your CPU? Did anyone figure out why Win10 performance is 25% lower compared to Linux on identical hardware?

I did some tests by  compiling my own OpenBlas (both stable and develop) that properly recognizes my Zen core but I found that although there were some gains it wasn't very much. I did not compile OpenBlas on Win10 though.

I dual boot this computer (2700X, GTX1080) and consistently get better performance on Linux.

Slightly off topic: Ryzen 2700X is excellent value and really has great performance.

**Comment by Ka-zam** [comment]
Win10, Ryzen 2700X, GTX 1080

A) FALSE
B) FALSE
C)
`USE_HALF=0: 3205 visits, 1130630 nodes, 3204 playouts, 905 n/s`
`USE_HALF=1: 3206 visits, 1130951 nodes, 3205 playouts, 1083 n/s`

**Comment by tterava** [comment]
@Ka-zam Ryzen7 1700 @ 3825 MHz. No idea what the reason could be. I use latest Nvidia drivers and the libopenblas.dll from the LZ release package. With full tune and half precision I now get 1329 n/s with --benchmark.

Are you using the same -t X for both tuning and playing? If I use different thread count than what I tuned for, i get really bad n/s.

**Comment by Ka-zam** [comment]
@tterava I redid the Windows results and made sure I used -t4 in both cases. Updated the results but still I get only 1113 n/s with fp16.

🤷‍♂️

**Comment by genleung** [comment]
UbuntuLinux16.04+CUDA8 GTX1070 with opencl+MKL enabled

a) none

b) none

c) original:
without -DUSE_HALF=1
3209 visits, 1131916 nodes, 3208 playouts, 775 n/s

with -DUSE_HALF=1
3205 visits, 1130597 nodes, 3204 playouts, 1057 n/s

36% speed increased.

**Comment by MartinDevelopment** [comment]
Redid my test, because I didn't use --ful-tuner in my previous one.
a) false
b) false
c)
without -DUSE_HALF=1
10001 visits, 3495273 nodes, 10000 playouts, 382 n/s

with -DUSE_HALF=1
10001 visits, 3495562 nodes, 10000 playouts, 356 n/s

6.8% decrease

**Comment by gcp** [comment]
>Did anyone figure out why Win10 performance is 25% lower compared to Linux on identical hardware?

Apparently it's related to the video driver model causing a much larger call overhead, and perhaps the OpenCL drivers being more optimized for Linux because that's where the big scientific users sit.

**Comment by gcp** [comment]
> LZ eventually won but I'm not sure if the half precision could generate some side effects. I didn't observe such big winrate variation with "normal" precision for the same game.

If you make an issue with the game we can have a look. There was some preliminary testing USE_HALF doesn't make the engine weaker at fixed playouts, but not enough games to be 100% sure,

**Comment by hydrogenpi** [comment]
@Ka-zam sorry for late reply, I could not state answer for part A nor part B because they are not applicable. I myself on gaming pc only have 1080Ti, (like everyone else here) the 4xTitanV (actually 4xV100) on aws doesn't seem to be giving performance I expected (max 5000 GFLOP even on full tuning) and 
[leelaz_opencl_tuning.zip](https://github.com/gcp/leela-zero/files/1958349/leelaz_opencl_tuning.zip)  as you can see it doesn't apply to neither part A nor B. 

I tried USE_HALF=1 and got 1979 or thereabouts whereas previous to the compile on the original next branch baseline was around 1900... so there is some improvement but marginal on the aws instance.

**Comment by Ka-zam** [comment]
@hydrogenpi No problems.

Looked at your tuning file and seems both A and B are FALSE for V100 as well. So that's data!

**Comment by Marcin1960** [comment]
I did all steps, all went fine (including tuning)  until I run benchmark :

[C:\Program Files\LeelaZero_0.13]leela-zero-USE_HALF.exe  -t 2 --benchmark -w f3231

Got NOTHING in return:

[C:\Program Files\LeelaZero_0.13]

================

Then I tried to do bench from text interface and got the error

[C:\Program Files\LeelaZero_0.13]leela-zero-USE_HALF.exe  -t 2  -w f3231
Using 2 thread(s).
[...]

Loaded existing SGEMM tuning.
Error building kernels: "C:\Users\Win7\AppData\Local\Temp\OCL4860T1.cl", line 3: error: dire
          type "half" requires OpenCL extension cl_khr_f16 (not supported)
      typedef half net_t;
      ^

"C:\Users\Win7\AppData\Local\Temp\OCL4860T1.cl", line 94: warning: variable
          "width" was declared but never referenced
          const int width = BOARD_SIZE;
                    ^

"C:\Users\Win7\AppData\Local\Temp\OCL4860T1.cl", line 95: warning: variable
          "height" was declared but never referenced
          const int height = BOARD_SIZE;
                    ^

"C:\Users\Win7\AppData\Local\Temp\OCL4860T1.cl", line 187: warning: variable
          "H" was declared but never referenced
      const int H = BOARD_SIZE;
                ^

"C:\Users\Win7\AppData\Local\Temp\OCL4860T1.cl", line 275: warning: variable
          "KPpad" was declared but never referenced
      const int KPpad = Kpad * Ppad;
                ^

"C:\Users\Win7\AppData\Local\Temp\OCL4860T1.cl", line 927: warning:
          unrecognized #pragma
    #pragma promote_to_registers
            ^

"C:\Users\Win7\AppData\Local\Temp\OCL4860T1.cl", line 929: warning:
          unrecognized #pragma
    #pragma promote_to_registers
            ^

"C:\Users\Win7\AppData\Local\Temp\OCL4860T1.cl", line 931: warning:
          unrecognized #pragma
    #pragma promote_to_registers
            ^

1 error detected in the compilation of "C:\Users\Win7\AppData\Local\Temp\OCL4860T1.cl".
Frontend phase failed compilation.

**Comment by Ka-zam** [comment]
Didnt mean to step on any toes.

But 30% performance increase for everyone except the very few who still run legacy hardware is a little steep to just throw away.

But two solutions exist of course
1 Maintain separate fp16 and fp32 builds
2 Make data type a runtime setting

THe only problem is that now you have a lot of build configurations all of a sudden.

**Comment by Marcin1960** [comment]
@Ka-zam  "Didnt mean to step on any toes."

You did.

@Ka-zam "30% performance increase for everyone except the very few " "Win7 actually came out 2009. Feels like an eternity!"

If one is to trust Microsoft (I don't) "Windows 7 is 38 in USA and 46 percent globally".
I do not like Win 10, and I am not going to adopt it.

**Comment by tychota** [comment]
Card: AMD AMD Radeon Pro 450 Compute Engine (mac book pro card)

Next without change: `0;XgemmBatched;192;100;192;16; -DKWG=32 -DKWI=8 -DMDIMA=8 -DMDIMC=16 -DMWG=64 -DNDIMB=8 -DNDIMC=16 -DNWG=64 -DSA=0 -DSB=0 -DSTRM=1 -DSTRN=1 -DVWM=1 -DVWN=4;OpenCL: AMD AMD Radeon Pro 450 Compute Engine @ 800MHz`

--> 3206 visits, 1131266 nodes, 3205 playouts, 94 n/s

a) -DVWM=1 -DVWN=1

Benchmark TBD

b) -DSA=0 -DSB=0

Benchmark TBD

c) TBD

**Comment by gcp** [comment]
>Maybe a 15 year old OS running in 32-bit mode is where we draw the line? 

That's not the issue. The issue is that if the card/drivers can't do fp16, it doesn't matter what OS he runs.

**Comment by gcp** [comment]
>Or should FP16 be a runtime setting perhaps.

This would be nice, so patches welcome :-P

**Comment by gcp** [comment]
@tychota Thanks, so for this card removing those options from the tuner would actually have been faster? That's great to know. I've noticed performance profiling fluctuates a lot on my AMD card too, and this makes the job of the tuner harder.

**Comment by gcp** [comment]
> anyway to apply USE_HALF in Makefile directly ?

Changing config.h for example works. Or add -DUSE_HALF in CXXFLAGS somewhere.

**Comment by fishcu** [comment]
Sorry, I don't have time to run A) and B). Here are the results for C):

With default params, built from current "next" branch: 
`3203 visits, 1130235 nodes, 3202 playouts, 1323 n/s`; 
2nd run: 
`3204 visits, 1130585 nodes, 3203 playouts, 1324 n/s`


After recompiling with `-DUSE_HALF=1`: 
`3204 visits, 1130656 nodes, 3203 playouts, 1417 n/s`; 
2nd run: 
`3205 visits, 1130907 nodes, 3204 playouts, 1387 n/s`

OS: Ubuntu 16.04

GPU: TITAN Xp, driver 390.48.

**Comment by Ka-zam** [comment]
> Apparently it's related to the video driver model causing a much larger call overhead, and perhaps the OpenCL drivers being more optimized for Linux because that's where the big scientific users sit.

I and @tterava did some tests and found that the --benchmark option is not reliable. When specifying -p10000 and executing 'genmove b' we get reproducible results and now I actually get identical results on both OS.

**Comment by Marcin1960** [comment]
@Ka-zam "Could you try the Crimson driver from this page?"

Of course I did.The last good driver is Catalyst 15.7.1, newer ones are broken.

Why do you ask?

**Comment by Ka-zam** [comment]
> Why do you ask?

Because as I mentioned there is nothing in your hardware that prevents FP16 from working as it can be simply promoted to FP32 by the driver. So perhaps they fixed it in the Crimson series. But you tried and it didn't work so that's not the answer. 

As for builds it's not simply fp16 on/off. You now have:
* CPU/GPU
* FP16/FP32
* 32/64 OS

So that's 8 combinations already.

**Comment by Marcin1960** [comment]
@So perhaps they fixed it in the Crimson series. 

They are worse. 

"CPU/GPU, FP16/FP32,32/64 OS So that's 8 combinations already."

No comment.

**Comment by gcp** [comment]
Thanks for all the results. Defaulting USE_HALF looks like it's a bit tricky, but I made the changes to the default/fast tuner.

**Comment by tychota** [comment]
@gcp Notice I use full-tuner and still got `-DVWM=1 -DVWN=1 -DSA=0 -DSB=0` which was 25% less performant !

Can it be considered to apply this to full-tuner too ?

(btw, I update https://github.com/gcp/leela-zero/issues/1273#issuecomment-385293259 and USE_HALF improvement not relevant: 6% but also maybe related to me closing idea IDE, xCode, and so and the tuner picking `-DSA=1 -DSB=1` correctly.)

**Comment by tterava** [comment]
@gcp I wouldn't say it's unreliable, but with fast cards 3200 visits is quite a small sample, especially with high end cards. I think you get a more accurate picture with more playouts. At least I get significantly larger n/s when thinking 10k instead of 3.2k visits.
