### ISSUE TITLE
what if make latest weights accessible only by those  who contribute to the project

### ISSUE THREAD

**Issue by higherdim** [gcp/leela-zero#1277]
For example: only distributed clients do the training can automatically download the weights from server. Might be a good way to encourage more contribution...

**Comment by l1t1** [comment]
interesting

**Comment by stevevista** [comment]
cannt agree

**Comment by higherdim** [comment]
@stevevista,  cannt agree _more_?  :dagger:

**Comment by MartinDevelopment** [comment]
Not going to happen, we can't force people that just want to play and/or can't contribute to contribute and what is to prevent someone from just running autogtp untill the weight is downloaded and close autogtp?

**Comment by AlexanderMisel** [comment]
The weight should be public, for testing and playing. It's impossible for my old machine to train the network. But using the weights with few visits can run LZ on my machine.

**Comment by Atarust** [comment]
The weights should be public, because they should be!
