### ISSUE TITLE
client didn't check the checksum of network file

### ISSUE THREAD

**Issue by fell111** [gcp/leela-zero#128]
If the download of value network file is incomplete, the client will quit immediately after start engine. 
There is no check or retry for the network file. Every time you execute the client, it will fail.

**Comment by KarlMaoChina** [comment]
Same problem here. Incomplete value file downloaded and the autogtp quit after trying to generate first move. Fix this by manually download the network.

**Comment by alreadydone** [comment]
Yes, the client failed to download the network for many Chinese volunteers. Fortunately some other volunteers uploaded the network to a cloud drive like pan.baidu.com and they got it there.
