### ISSUE TITLE
request of develope a android version of leelaz

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1285]
I think it the time to release a android version of leelaz now, since it is proved strong enough to beat/help people in recent matchs(https://github.com/gcp/leela-zero/issues/1276).

an AQ android app has been released at https://tieba.baidu.com/p/5635955232 ,it just copied the AQ 2.1.1 network file, and when it run on a 3G-32G qualcomm 808 cpu phone, it cost about 30s per move.
so the speed of that is acceptable.
 
@bood has developed a cpu version at https://github.com/gcp/leela-zero/issues/779 ,
and one can use gpu with opencl on android, just like https://github.com/WhiteIsClosing/Android-OpenCL-Sobel-Filter .
so it  will be a very useful tool for all go players.
for people who have strong phones, autogtp is also possible.

**Comment by Ka-zam** [comment]
There should be an OpenCL NEON lib somewhere, right?
And Mali GPU I know exists. But don't have a clue regarding performance

**Comment by hydrogenpi** [comment]
The guy who made the AQ app gave up on trying to port a LZ one for andriod stating on 15 block he was only getting performance of 6 po/sec on his test phones. Not sure if what can be optimized bit he seem to suggest AQ raw network was easier to port out the box and a lot natively faster when on a phone.

**Comment by fell111** [comment]
for 100 visits, LZ could be 5D or more. I think that is enough for a mobile phone. The problem is that you need to download the latest network every few days :)

**Comment by tterava** [comment]
With very low visit counts it's actually best to use as large a network as possible.

**Comment by gcp** [comment]
>With very low visit counts it's actually best to use as large a network as possible.

The achievable visit count is related to the network size, so that's a rather meaningless statement.

**Comment by gcp** [comment]
>may be the last 128*10 best network is suitable for a phone

You could train a new 128x10 on the latest training data from 192x15 networks, it would likely be stronger than the current best 128x10.

**Comment by Eddh** [comment]
I think he's talking about the scaling tests, which went down before going up.

**Comment by gcp** [comment]
>There should be an OpenCL NEON lib somewhere, right?

You should not use OpenCL on CPUs. Leela Zero already has an optimized CPU implementation. You just need a good BLAS lib. I think OpenBLAS does have Android support, but it may not be so easy to get compiled.

@bood has been working on this: https://github.com/gcp/leela-zero/issues/779

**Comment by gcp** [comment]
Better to continue discussion in existing issues.
