### ISSUE TITLE
LZ's ladder issue 

### ISSUE THREAD

**Issue by zxo102** [gcp/leela-zero#1288]
LZ can not handle simple ladder issues. Here are two sgf files from the games against AQ2.1.1:

1. https://pan.baidu.com/s/1ogyw3j72IboQoxr0gENDog
2. https://pan.baidu.com/s/1dO-Yst-fR41XdZ5XLAbgsw

**Comment by Ka-zam** [comment]
You mean the current network can't handle this situation, perhaps? Networks are still in training. So there's no bug to "fix".

**Comment by hydrogenpi** [comment]
AQ has ladders hard coded. To be fair, even AQ falls for simple mistakes time to time WITH the hardcoding, or rather I should say because of the artificial tweaking, see their github. 

I think its on more reason why larger net sizes and more training is needed to better refine and perfect LZ. And precisely why during high PR matches to Always use as much hardware as possible.

**Comment by zxo102** [comment]
Is it possible to feed lz with ladder patterns? So lz can handle ladder patterns correctly earler

**Comment by MaxMaki** [comment]
@zxo102 No, the whole point of a zero approach is that it learns by itself. If you start entering in custom data you risk just making it weaker.

Remember that ladders most likely don't work on/have been shown not to work on: low playouts, handicap games, games that are lost anyway

If i remember correctly there were also some tests where people were forcing LeelaZero to play a certain position and it couldn't avoid the ladder. But if you backed up 5 moves and then let it play, it never got in the ladder situation in the first place.

**Comment by csuji** [comment]
First game current net # 129 would not play the ladder with sufficient visits and even "sees" it in early analysis:
![lizzie_84](https://user-images.githubusercontent.com/22214791/39407898-f3ca6c40-4bcd-11e8-83b1-da53410e5376.png)
![lizzie_analysis_86](https://user-images.githubusercontent.com/22214791/39407901-ffc4b500-4bcd-11e8-88a4-7cff309d4f8a.png)
Second game is a handicap game with 3 stones and that LZ has problems with these everyone knows.

**Comment by MartinDevelopment** [comment]
@hydrogenpi The learning rate wasn't lowered. Only the maximum amount of steps was increased from 128k to 192k before resetting a couple days ago.

**Comment by roy7** [comment]
As it turns out, this new network was a 192K one.

**Comment by MartinDevelopment** [comment]
@roy7 Since it seems 192K might be worth it, how about testing 265K in a couple days?

**Comment by roy7** [comment]
Training is totally @gcp's area. :)

**Comment by gcp** [comment]
Yes, I'll extend the max steps.
