### ISSUE TITLE
Code question to GCP?  To be closed after answer.

### ISSUE THREAD

**Issue by Marcin1960** [gcp/leela-zero#1292]
Didn't you mean to change numbers for "cfg_sgemm_exhaustive" too, in the Tuner.cpp?

**Comment by gcp** [comment]
No. That code lists the values that will be tried. Exhaustive already tries all of them, and should still try all of them. Else it wouldn't be very "exhaustive" nor provide a good fallback in case some old/weird GPU prefers the other configuration.

**Comment by Marcin1960** [comment]
I understand. I meant to improve "exhaustive" parameters, like removing really obvious and adding promising new.

But as you said "some old/weird GPU" [might] prefer the other configuration". Yet, maybe there is a better choice, even if not faster.
