### ISSUE TITLE
Can the project start an official 9 by 9 training?

### ISSUE THREAD

**Issue by hydrogenpi** [gcp/leela-zero#1298]
Now that its shown NN is scale invariant at this size, I imagine it wouldnt siphone too many client cycles away from the main 19 by 19 and could easily be done within a few weeks and we can get a superhuman 9 by 9... and if that works then move to do a 13 by 13.

**Comment by l1t1** [comment]
maybe let another project do it is better

**Comment by hydrogenpi** [comment]
why? for lz it would only take a few days to do it at 700 clients per 24 hours

**Comment by TableCarpet** [comment]
It exists https://online-go.com/player/481097/

**Comment by john45678** [comment]
Minigo is pro  strength at 9x9.
https://github.com/tensorflow/minigo/pull/99/commits/a2ef1b857904b1242408ad0f46e83c7f27e2579c
http://www.cloudygo.com/v3-9x9/eval-graphs

**Comment by hydrogenpi** [comment]
yeah but its not at the top of the cgos chart.

**Comment by PhilipFRipper** [comment]
What does that have to do with anything?

**Comment by fell111** [comment]
Seems somebody reacted with thumbs down to everyone who has a different idea? Please be polite in the community. 

If you want to play with strong 9x9 AI, the minigo already provides it. If you want to prove LZ arch is also suitable in 9x9, there is a private weight training for 9x9 already proved it #1291

So what's your purpose for official 9x9? To be the world strongest 9x9 program?

**Comment by hydrogenpi** [comment]
I'm open to being corrected if I misinterpreted the stated goals of the Leela Zero project, but between the Readme, the FAQ and other open literature it doesn't appear that the Leela Zero project explicitly states that its zero development of Go program is directly limited to only 19 by 19 board size. And just because a zero 9 by 9 has already been done before does not in and of itself preclude the possibility of LZ doing the same or similar, after all if that was the case then the same standard of logic and rationale could be applied in a consistent manner to say, for example, MiniGo should no longer pursue a strong 19 by 19 since we already have a top pro LZ 19 by 19, or that no other newer/later open source zero Go projects should come into existence because "its already been done before".

**Comment by Marcin1960** [comment]
@hydrogenpi 

MiniGo is doing fine:  "It beat Hajin Lee 4p 4-1 on kgs" Two months ago!

https://old.reddit.com/r/cbaduk/comments/7y4i0x/minigos_9x9_models_games_and_training_data_posted/

**Comment by gcp** [comment]
I don't see the point in doing 9x9 at this time.

a) Other projects have produced publicly available weight files that could probably be converted to LZ if needed. (MiniGo)
b) Someone got the highest rated 9x9 bot doing it all by himself with LZ and made the result available. The server source is public, so the people who are interested in pushing that further with a parallel effort could do so easily.
c) Not many people play 9x9 seriously, as far as i know.
d) Although LZ may or may not be superhuman on fast hardware, it certainly isn't yet on modest hardware or something like a phone. So I think it makes sense to continue for quite a while.

I haven't given given much thought yet what we should do beyond our current run, but for example a network at komi 0.5 would be very useful for a lot of people, I'd think.

**Comment by gcp** [comment]
Closing this to reflect that the main effort will keep on 19x19 for now to push that a further.
