### ISSUE TITLE
reverse rotate after nn forwarding ?

### ISSUE THREAD

**Issue by stevevista** [gcp/leela-zero#13]
In Network.cpp, 
`
for (size_t idx = 0; idx < outputs.size(); idx++) {
...
            auto rot_idx = rev_rotate_nn_idx(idx, rotation);
            auto val = outputs[rot_idx];
            int x = idx % 19;
            int y = idx / 19;
            int vtx = state->board.get_vertex(x, y);
`
as input matrix has been rotated, should we use `rot_idx` instead of `idx` to get_vertex ?

**Comment by gcp** [comment]
No, we are mapping the rotated output vtx back into the regular orientation. vtx is the regular point we are considering and rot_idx is where we look for it in the rotated board output.

**Comment by gcp** [comment]
https://github.com/gcp/leela-zero/blob/8507cb47528f43729d6bd723b3890f637ce9e576/src/Network.cpp#L426
For consistency vtx should probably be named rot_idx there.

The neural network board at x contains planes[rotate_nn_idx(x)].

The output board at x will look for net_board[rev_rotate_nn_idx(x)].

x = rev_rotate_nn_idx(rotate_nn_idx(x)) so output and planes have the same orientation.

**Comment by gcp** [comment]
I guess this code would be easier to understand and simpler if we change it so the regular board is always on the left-hand side and the network board is on the right-hand side. Then one can probably get rid of rev_rotate_nn_idx as well.

(In image rotation one typically has to "sit at the output" and look for the corresponding input to get non-90° angles right, but that's not necessary here)

**Comment by stevevista** [comment]
> vtx is the regular point we are considering and rot_idx is where we look for it in the rotated board output.
>
my mistake
