### ISSUE TITLE
suggest to continue increase more steps in one trainning set

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1305]
from the result of match between 7.135M+32.0k and 7.100M+256k and more matchs.

``
2282afee 7.135M+32.0k VS 18e6a6c5 7.100M+256k |76 : 87 (46.63%) |163 / 400 
 ``
 
it seems steps are more useful than training games amount, new 32K and 64 K are usually weaker than last 128K,192K and 256K.

since the training time of new 64 and old last+64 are similar, can we try 320K,384K?

**Comment by MartinDevelopment** [comment]
I think 265K steps is the max we should do, otherwise it will take too long before we use new games in the training. However, it might be something to test for a couple days to see what happens.

**Comment by gcp** [comment]
Martin is basically correct here. See also the SWA topic.

**Comment by l1t1** [comment]
which SWA topic?
