### ISSUE TITLE
suggest to change network format to xz

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1308]
http://ftp.tsukuba.wide.ad.jp/software/gcc/releases/gcc-8.1.0/ says
``
gcc-8.1.0.tar.gz 2018-05-02 17:51  108M   
[ ] gcc-8.1.0.tar.xz 2018-05-02 17:49  60M   
``
obviously, xz format's compres rate is much higher
could save download time and diskspace

**Comment by l1t1** [comment]
btw, http://storage.sjeng.org/zero/ already use the xz format

**Comment by odeint** [comment]
I checked different compression algorithms a while back:
https://github.com/gcp/leela-zero/issues/591#issuecomment-363462728

**Comment by gcp** [comment]
We were going to use zstd initially but there were problems with backwards compat. 

Don't really remember why we didn't use xz.

**Comment by roy7** [comment]
Maybe since I'd never heard of it, lol. ;) Before this project I didn't know about zlib either. Since my programming date were in the distant past, I still think of "gzip" as state of the art and "bzip2" as the new kid on the block.

**Comment by l1t1** [comment]
7z with ppmd algorithms is about 23 smaller than gz

116,224,200 18e6a6c53d61359a922b36a5f3fb078aa7514cfe0050ccf3cae37f8584154d89
 30,654,858 18e6a6c53d61359a922b36a5f3fb078aa7514cfe0050ccf3cae37f8584154d89.7z
 34,525,464 18e6a6c53d61359a922b36a5f3fb078aa7514cfe0050ccf3cae37f8584154d89.xz
39,987,813 18e6a6c53d61359a922b36a5f3fb078aa7514cfe0050ccf3cae37f8584154d89.gz
