### ISSUE TITLE
Could leelaz best utilize Telsa V100?

### ISSUE THREAD

**Issue by zhanzhenzhen** [gcp/leela-zero#1309]
I'm new to deep learning. I'm curious if the OpenCL in leelaz can utilize tensor cores, which is in V100 and Titan V. If it couldn't, could I write my own code that better utilizes these GPUs, while still using leelaz's network weights?

**Comment by gcp** [comment]
a) No, I'm not sure this is possible from OpenCL.

b) Yes, the weights are public domain. For the chess version, someone did a complete re-implementation that uses cuDNN. There is a cuDNN port of leela-zero, but performance was so-so: https://github.com/Ttl/leela-zero/commit/11a254cf06a5577abcf6de97fdc2d72de90d0d62

**Comment by zhanzhenzhen** [comment]
@gcp Thank you. I have another question: In leelaz all weights are in single float. I guess it can only achieve the best performance in V100 if using half precision float, am I correct? I know it's impossible for leelaz because most of our GPUs do not support half float. I searched Deepmind's paper but they didn't mention the precision.

**Comment by gcp** [comment]
It is possible that the mixed precision fp32/fp16 mode that the Tensor Cores use is good enough. We at least know fp16 weight storage is good enough.

That said, the Winograd optimization that we use requires good precision, and when I tested cuDNN with Tensor Cores, I saw it disabled Winograd when Tensor Cores were enabled. So, it is possible that the fp16 computation is not accurate enough.

**Comment by zhanzhenzhen** [comment]
thank you @gcp
