### ISSUE TITLE
Validation.exe missing in Windows binaries. Can it be included?

### ISSUE THREAD

**Issue by Ikfes** [gcp/leela-zero#1310]
Can it be included in the next version? or even current one.

There are tons of windows users running this 24/7 from their desktops. I personally tried to build this with visual studio, but I keep getting errors myself. The Windows binary attached in another issue was also invalid, since I get the same error running it.

It would be nice if the original compiler could do another compile with the validation.exe included.

**Comment by l1t1** [comment]
agree

**Comment by gcp** [comment]
#1268

**Comment by Ikfes** [comment]
Gcp, the version in validation.zip on the other issue is nonworking.

**Comment by Ikfes** [comment]
Besides, this is a request to include it in windows binaries, im not asking just the .exe

**Comment by gcp** [comment]
>Gcp, the version in validation.zip on the other issue is nonworking.

I know, I can read.
