### ISSUE TITLE
optimize uct_select_child

### ISSUE THREAD

**Issue by petgo3** [gcp/leela-zero#1315]
While debugging for some reason, i eventually stepped through uct_select_child.
Best child is selected by this code in a loop over all childs:

        auto psa = child.get_score();
        auto denom = 1.0 + child.get_visits();
        auto puct = cfg_puct * psa * (numerator / denom);
        auto value = winrate + puct;
... here
        if (value > best_value) {
            best_value = value;
            best = &child;
        }

In my first visits puct was allways 0, which is not surprising, because numerator is defined earlier (outside of the loop) as:
numerator = std::sqrt(double(parentvisits));
(only once for the parent)

If we imagine now an empty board, first move first visit of the function, we get the first child in the loop automaticly as best. It's the move 361 [one of the corners]. 
Wouldn't it be better to add this code (... here):

if (numerator == 0.0f) {
 // add small amount to get good move in new node
 value += psa / 10000;
}

**Comment by Eddh** [comment]
I think it's sorted by policy.

**Comment by gcp** [comment]
>I think it's sorted by policy.

Yes:
https://github.com/gcp/leela-zero/blob/f867489a4054418fb10559cb66dc799a33fc8e82/src/UCTNode.cpp#L134
