### ISSUE TITLE
When the elf self play games  could be released?

### ISSUE THREAD

**Issue by alphaladder** [gcp/leela-zero#1319]
The self play games maybe more important than the weight itself? I don 't know if someone can supply a stable cloud drive for them?

**Comment by l1t1** [comment]
or use a torrent file

**Comment by jillybob** [comment]
We can supply a hard drive for @jma127  and @yuandong-tian to place the files onto this hard drive and return it to the Leela Zero Volunteer. The Volunteer can then upload the data via torrent or on online-go.com for everyone to use.

**Comment by gcp** [comment]
I have no idea why you are asking here. The ELF project is: https://github.com/pytorch/elf
