### ISSUE TITLE
A way to stop and restart the game?

### ISSUE THREAD

**Issue by ashinpan** [gcp/leela-zero#132]
If we have to turn off the computer in the middle of self-play games of autogtp, the half-played game is entirely lost. 

If we have a way to stop and restart a game, it can save a lot of time.

**Comment by alreadydone** [comment]
also if we want to switch to a new version of the client..

**Comment by Mardak** [comment]
This was fixed in #769 available since autogtp 14 https://github.com/gcp/leela-zero/releases/tag/v0.12
