### ISSUE TITLE
Graph on http://zero.sjeng.org/ is less accessible.

### ISSUE THREAD

**Issue by Marcin1960** [gcp/leela-zero#1321]
I use 3 different machines (2 different Internet providers) to access http://zero.sjeng.org/
with different browsers
Several weeks ago I could not see graph on one, then after some enhancement on two,
then with the last was gone with the latest changes.

Good news - I can see it with a specific browser that  is not my default or preferred one.
And the new graph is excellent.

It is not a big problem for me, as I can live without the graph :)

But I think that a growing segment of visitors, might never see the graph,
what would cripple the promotion of LZ.

**Comment by gcp** [comment]
You should:

a) Report this to the server code: https://github.com/gcp/leela-zero-server/issues
b) Be more specific so they can check where it broke.
c) Try force-refreshing with Sift-F5? I don't see the new graph unless I do.

**Comment by Marcin1960** [comment]
Me favored is PaleMoon, but it worked on one system until recent change.

Shift-F5?  did not help.

Maybe I will repost it on https://github.com/gcp/leela-zero-server/issues, but

I am all set - Yandex browser shows the graph perfectly, I will set yandex home page for the http://zero.sjeng.org/
I just was worried that many visitors will not inquire farther and wanted to make developers aware.

**Comment by Marcin1960** [comment]
OK, I posted it on https://github.com/gcp/leela-zero-server/issues

**Comment by gcp** [comment]
Thanks!
