### ISSUE TITLE
why the green bars of each games are different?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1323]
![2018-05-04_184759 png](https://user-images.githubusercontent.com/23301704/39624474-f025bb4e-4f88-11e8-856b-4a9c9dad744b.jpg)

**Comment by gcp** [comment]
Indicates how close to PASS/FAIL it is.

**Comment by l1t1** [comment]
btw, if the attached image file ext name is png, it often upload fail, while rename it to jpg, it upload successful, why?
