### ISSUE TITLE
does  current promote and fail standard includes these points?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1324]
1 if less than 400 games, it got very high or  very low winrate, eg. pass Probability <0.05 or lose games>=180, then stop macth
2 if winrate less than 0.55 at 400 games , then try some(maybe 20)more games, if >=0.55 at one point, promote,

**Comment by gcp** [comment]
1. That's the SPRT condition.
2. The code doesn't try more than 400 games, but it happens because clients are slow, don't respond, etc. It can happen.
