### ISSUE TITLE
leela elf version beat fineart and Phoenix  go

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1325]
https://tieba.baidu.com/mo/q---201F473D94EAB63FDB35A35D15FF7BAB%3AFG%3D1-sz%40320_240%2C-1-3-0--2--wapp_1521159228408_109/m?kz=5683394036&is_bakan=0&lp=5010&pinf=1_2_0

**Comment by jkiliani** [comment]
While this sounds interesting, a link to a Chinese language site is not very helpful for the majority of people here...

**Comment by l1t1** [comment]
there are some board graphs too

**Comment by l1t1** [comment]
It is said nearly all AI began to use ELF weight https://tieba.baidu.com/p/5686313000

**Comment by l1t1** [comment]
it is said fineart change version during a match, https://tieba.baidu.com/p/5683394036

**Comment by l1t1** [comment]
a collection of elf leelaz and goreviewpartner chinese edition https://tieba.baidu.com/p/5686431263
