### ISSUE TITLE
Unnaturally slow self-play games on my machine

### ISSUE THREAD

**Issue by ashinpan** [gcp/leela-zero#133]
I am running Linux Mint (18.3), Core i5-6500 CPU 3.20GHz, and Geforce GT 610. Granted, the cpu is not exactly top of the line, and the gpu sucks. But I suspect autogtp games are much slower than I would expect. Here is the log of a game just completed:

----------------------------------
Score: W+38.5
Winner: white
Writing 521662be8c3749c38ee08a8f307879a3.sgf
Dumping 521662be8c3749c38ee08a8f307879a3.txt
Stopping engine.
curl -F networkhash=857b975eb796de20c0eb4243c5998715ef1de2465427dc474cf6c860a24378f2 -F clientversion=4 -F sgf=@521662be8c3749c38ee08a8f307879a3.sgf.gz -F trainingdata=@521662be8c3749c38ee08a8f307879a3.txt.0.gz http://zero.sjeng.org/submit
Game data cc841b7fb927011b705596675787ccd8387e0288c5944e8b6ac0d862a17dfc97 stored in database
1 game(s) played in 423 minutes = 25437 seconds/game, last game took 25437 seconds.

---------------------------------------

If it is not a bug, OK. I'd be happy to continue contributing my two cents to the project. If it is a bug, developers should look into it.

**Comment by marcocalignano** [comment]
How many moves?

**Comment by ashinpan** [comment]
505 moves, and both sides passed.

**Comment by OmnipotentEntity** [comment]
Did you compile it yourself?  If so did you specify Release as the CMAKE_BUILD_TYPE?

**Comment by marcocalignano** [comment]
How much memory has the GPU?

**Comment by Matuiss2** [comment]
It just took 2 hours to make 121 moves in mine pc here too, after the  change to 5 blocks x 64 filters, I dont think its a bug, its probably thats our computer is not fit to this kind of task

**Comment by marcocalignano** [comment]
on my GTX 760 one game of 506 moves takes 866 seconds. looking at benchmarks with a G 619 1024 MB  my GPU is ~ 17 Times faster that brings to 14700 seconds I have aa CPU an I-7 3.8 GHz but I do not know if that can account for the difference. Probably because of OpenCL that factor 17 is bigger if you have more core in the GPU so this would account for the difference.

**Comment by qysnn** [comment]
Since you have a NVIDIA graphic card, you can run `nvidia-smi` in terminal to check the utilization rate of your graphic card. If it's above 90%, it means your graphic card is already fully occupied by Leela Zero. If it's not, then there may be something wrong.

**Comment by ashinpan** [comment]
@OmnipotentEntity I compiled the latest git version, by opening a terminal in the src folder and running default make. 

@marcocalignano  My gpu has 2GB memory.

**Comment by ashinpan** [comment]
@qysnn According to nividia-smi, my gpu usage is around 55% only.

**Comment by marcocalignano** [comment]
If you can compile try to change this line in Game.cpp 

`cmdLine.append(" -g -q -n -d -m 30 -r 0 -w ");`
to 
`cmdLine.append(" -g -q -t 4 -n -d -m 30 -r 0 -w ");`

and see if your GPU usage goes up

**Comment by ashinpan** [comment]
@marcocalignano  I have recompiled autogtp with the changes you suggest, and now the GPU usage has slowly gone up from the original 55%. It is at 64% now. I will wait and see if it reduces the play time.

**Comment by marcocalignano** [comment]
Like I thought! The CPU is too slow to feed data to the GPU. In the normal autogtp you have two thread feeding the GPU with the change I gave you you have now 4 thread, so you are using all 4 cores of your I5 and the GPU usage went up only 20% I guess you need an upgrade.

**Comment by ashinpan** [comment]
@marcocalignano  Now the GPU usage is running between 60% and 70% exclusive.

**Comment by ashinpan** [comment]
@marcocalignano  You mean, the cpu needs to be upgraded?

**Comment by marcocalignano** [comment]
Yes the CPU is too slow to use all the GPU capacity.

**Comment by lithander** [comment]
@ashinpan I don't think your CPU needs an upgrade! I'm running an older CPU with a much faster GPU (GTX 960) and calculating a move takes about 2 seconds. (e.g. multiple games per hour)

**Comment by ashinpan** [comment]
@marcocalignano  I am a little confused. I cannot find it again, but I remember @gcp saying somewhere that while networks are small, the CPU would be the bottleneck but when they are bigger, the GPU would become the bottleneck. If this is true, won't it make sense to wait for a little while, and upgrade the GPU?

**Comment by marcocalignano** [comment]
Then I do not know, maybe @gcp can add some input

**Comment by lithander** [comment]
http://gpuboss.com/gpus/GeForce-GTX-1060-vs-GeForce-GT-610 See how abysmal a GT 610 compares with modern 300€ cards? An upgrade would give a 5000% speedup! Whereas a 6 year old CPU (a Core i5 2500k in my case) has maybe 30% slower single-core speed then what you get today for the same price. Your CPU is fine!

**Comment by gcp** [comment]
Yeah this GPU is very slow and pretty old. Not sure why you don't see 100% utilization on it to be honest, but who knows how nvidia-smi calculates that.

**Comment by gcp** [comment]
https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units
GT 610 has a performance of 155 GFLOPS. I think this may even be slower than your CPU because it's harder for the GPU to run at peak theoretical efficiency.

Modern entry cards are like 2000 GFLOPS.

**Comment by ashinpan** [comment]
@gcp Thanks. I would upgrade the GPU soon.

**Comment by ashinpan** [comment]
Now, the play time is almost halved:

"1 game(s) played in 235 minutes = 14123 seconds/game, last game took 14123 seconds."

This shows @marcocalignano's hack works.

**Comment by OmnipotentEntity** [comment]
@ashinpan the default make compiles with debug information and without optimizations.  Use cmake build process and specify release.

**Comment by ashinpan** [comment]
I have upgraded to Gigabyte GTX 1050 G1 2G card. And the result? 

"188 game(s) played in 1271 minutes = 405 seconds/game, last game took 382 seconds." 

It has been about 1 game per 7 minutes, compared to the previous state of about 1 game per 4 or 5 hours. Therefore, great improvement!

(I know the issue has been closed by gcp, but just for those who might want to know)
