### ISSUE TITLE
question about 0.14's time manage

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1330]
it says
Slowed down play, more consistent time usage from opening to middle game.
will it increase the chance of lose by timeout in a fixed total time match? or it will use less time in final stage of game,leads to not best moves?

**Comment by gcp** [comment]
Are you seriously asking whether we changed the engine so it would be worse?

I got a feeling something was lost in translation here.

For more details about changes see the links in the commits:
https://github.com/gcp/leela-zero/commit/5bd244394a13f241b6e95a6f025d0e8e6e2fe519
https://github.com/gcp/leela-zero/commit/7e8ab1c266f53810e01312b509fc90bb6c70ab7b
https://github.com/gcp/leela-zero/commit/50e7dc60c82b70d739dfd63c9ae031097a55081f
https://github.com/gcp/leela-zero/commit/1890590f2ffbcc492b318dd6fdfd64e6685c1278

**Comment by l1t1** [comment]
thanks
