### ISSUE TITLE
strange graph on zero.sjeng.org

### ISSUE THREAD

**Issue by AlexanderMisel** [gcp/leela-zero#1332]
The graph looks strange
![default](https://user-images.githubusercontent.com/7542439/39658130-6eacdc86-5042-11e8-8498-2f5ebd49fe82.png)
and so do the best network hash table.

**Comment by hydrogenpi** [comment]
http://archive.is/BHBOz

and the ELF games are all gone!!!

**Comment by hydrogenpi** [comment]
https://github.com/gcp/leela-zero/issues/1333

**Comment by roy7** [comment]
All cleared  up now. In future please post web site issues to the server github. :)
