### ISSUE TITLE
Website broken?

### ISSUE THREAD

**Issue by hydrogenpi** [gcp/leela-zero#1333]
The ELF games are gone from the list (it had stacked up to 45+ games) and now everything is wierdly out of order

http://archive.is/BHBOz

**Comment by hydrogenpi** [comment]
https://github.com/gcp/leela-zero/issues/1332

**Comment by roy7** [comment]
Yes we had some work to do. Should be all better now.

In future please post web site issues to the server Github instead of here.

**Comment by hydrogenpi** [comment]
ok thanks for reminding, I'll close it.
