### ISSUE TITLE
ask the usage of validation to test two networks

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1335]
it the one first appear plays black?
C:\leela-zero-0.14-win32>validation -n LZ92.gz -n LZ97.gz
validation v1
SPRT : 0.0:35.0 h0 0 h1 35
Engine has started.
Infinite thinking time set.
Engine has started.
Infinite thinking time set.
starting:
./leelaz.exe  -g  -p 1600 --noponder -t 1 -q -d -r 0 -w  LZ97.gz
vs
./leelaz.exe  -g  -p 1600 --noponder -t 1 -q -d -r 0 -w  LZ92.gz
1 (B C16)

**Comment by l1t1** [comment]
and i suspend it since my notebook is hot.
glad to see q command also works. so another quesion
**if i didn't stop it, will it continue to run infinite games?**
1 (B C16) 2 (W Q4) 3 (B C4) 4 (W Q16) 5 (B E4) 6 (W E17) 7 (
W R5) 15 (B S5) q
storeSprt
LZ92.gz  v LZ97.gz  ( 0 games)
              wins        black       white
LZ92.gz     0   nan%    0   nan%    0   nan%
LZ97.gz     0   nan%    0   nan%    0   nan%
                        0   nan%    0   nan%
0 games played.
Status: 0 LLR 0 Lower Bound -2.94444 Upper Bound 2.94444
16 (W S6)

**Comment by l1t1** [comment]
it  also support self-play by -n w1 -n w1
C:\leela-zero-0.14-win32>validation -n LZ92.gz -n LZ92.gz
validation v1
SPRT : 0.0:35.0 h0 0 h1 35
Initial Statistics
LZ92.gz  v LZ92.gz  ( 0 games)
              wins        black       white
LZ92.gz     0   nan%    0   nan%    0   nan%
LZ92.gz     0   nan%    0   nan%    0   nan%
                        0   nan%    0   nan%
0 games played.
Status: 0 LLR 0 Lower Bound -2.94444 Upper Bound 2.94444
Engine has started.
Infinite thinking time set.
Engine has started.
Infinite thinking time set.
starting:
./leelaz.exe  -g  -p 1600 --noponder -t 1 -q -d -r 0 -w  LZ92.gz
vs
./leelaz.exe  -g  -p 1600 --noponder -t 1 -q -d -r 0 -w  LZ92.gz
1 (B Q4) 2 (W D16)

**Comment by pcengine** [comment]
@l1t1 how to use validations? I double clicked the validation.exe but nothing showed.

**Comment by MartinDevelopment** [comment]
@l1t1 Validation will keep running untill it passes or fails the SPRT settings you specified, or the default(same as at zero.sjeng.org matches).

**Comment by l1t1** [comment]
@MartinDevelopment thanks

**Comment by l1t1** [comment]
@pcengine open a cmd console, then input comands as my post

**Comment by barrtgt** [comment]
How do you change options for the binary? I'm trying to use different playouts. Does anyone have an example?

**Comment by barrtgt** [comment]
Here is what I have tried: 

validation.exe -n ba7 -n eca -o -p 1
validation v1
SPRT : 0.0:35.0 h0 0 h1 35
Engine has started.
Infinite thinking time set.
GTP: ERROR: the argument ('ba7') for option '--playouts' is invalid

**Comment by Mardak** [comment]
```
  -o, --options <opt_string>        Options for the binary given by -b (default
                                    '-g -p 1600 --noponder -t 1 -q -d -r 0 -w').
```
You need to give it a string. Look at the default value for reference. You'll want to end the options with `-w` as the network is appended.

**Comment by barrtgt** [comment]
Sorry I'm confused. I did this:
validation.exe -n ba7 -n eca -o -g -p 1600 --noponder -t 1 -q -d -r 0 -w

and I got this:
Unknown options: p, noponder, t, q, d, r, w.

How exactly do I give it a string?

**Comment by Hersmunch** [comment]
With 's:
`validation.exe -n ba7 -n eca -o '-g -p 1600 --noponder -t 1 -q -d -r 0 -w'`

**Comment by barrtgt** [comment]
@Hersmunch that gives me:
Unknown options: p, noponder, t, q, d, r, w, '.

Found out it needs quotes instead of the apostrophe as shown as default. So it needed to be this instead:
validation.exe -n ba7 -n eca -o "-g -p 1600 --noponder -t 1 -q -d -r 0 -w"

Thanks!
