### ISSUE TITLE
OpenGo-v0 use puct=1.5 rather than 0.8 (LZ default)

### ISSUE THREAD

**Issue by yuandong-tian** [gcp/leela-zero#1336]
Hi all, 

I checked the commit: 
https://github.com/gcp/leela-zero/commit/f867489a4054418fb10559cb66dc799a33fc8e82

It seems that there is no change in terms of puct when using OpenGo-v0 weights. When we train it we use puct=1.5. This might partly explain why Leela-ELF is weaker, or did I miss anything?

Also we use virtual_loss=1 when playing.  

Thanks!

Best,
Yuandong

**Comment by hydrogenpi** [comment]
@yuandong-tian can you upload the last (latest /newest) one million trained self play games? or even just a couple gigabytes worth. As you know, the LZ project is now using LZ-ELF as a games generator and mixing it with its own games as a strength gainer to quickly catch up. thx :P

**Comment by Ttl** [comment]
It seems that ELF uses winrate in range -1 to 1 for UCT formula, but LZ scales the winrate to 0 - 1 range. When scaling the winrate puct should also be scaled to maintain the same sorting order. 1.5 puct in ELF should correspond to 0.75 puct in LZ.

**Comment by yuandong-tian** [comment]
@Ttl Thanks!
