### ISSUE TITLE
Leela Zero 0.14 + AutoGTP v16  BUG?

### ISSUE THREAD

**Issue by zxd0226** [gcp/leela-zero#1337]
http://zero.sjeng.org/view/2cfab967fb2d0ea0d8e7a052fa38762c7d1d6099d4d5a2210c3bf3e8a8aa26da?viewer=wgo
http://zero.sjeng.org/view/7c227ca8597e76e39900491c05c38abd0cd3ea40b4c428cad61d9f058aa2e7e0?viewer=wgo

CPU   E3-1231 v3
GPU   AMD RX580

**Comment by l1t1** [comment]
what bug?

**Comment by Mardak** [comment]
Both those games resign after move 91. Those happen to use the 62b5417b ELF network.

Here's 2 games with ecab83bb that also resigned relatively early:
http://zero.sjeng.org/view/f4c9691d956a890055a5841a3893dadd3b5235ce764fdcaa79c3be5e71deeeee?viewer=wgo
http://zero.sjeng.org/view/f9a0ffe252c61459f32f0d0373cb37cb698e26a424740b7fea319b663255492e?viewer=wgo

I wonder if the resign rate should be lowered from 5% now that moves can be random throughout the game and not just the first 30? I'm guessing both 62b5417b and ecab83bb networks realize their random plays are bad and stops early.

**Comment by jkiliani** [comment]
I think it's an unavoidable consequence of both using the even more value-stratified ELF net and switching to t=1, which makes blunders and thus, objectively early decided games more common. We could try lowering the resign threshold, but the problem should actually fix itself once the majority of games in the training window use t=1. At that point, the value stratification will quickly decrease and games at the same resign threshold will consequently become longer again.

**Comment by Mardak** [comment]
Just checking the win rates at various moves (for white) using lz131-ecab83bb to analyze:
```
http://zero.sjeng.org/view/2cfab967fb2d0ea0d8e7a052fa38762c7d1d6099d4d5a2210c3bf3e8a8aa26da?viewer=wgo
10: 0.515810
20: 0.491268
30: 0.060986
40: 0.001055
50: 0.000134
60: 0.000000
70: 0.000000
80: 0.000000
90: 0.000019

http://zero.sjeng.org/view/7c227ca8597e76e39900491c05c38abd0cd3ea40b4c428cad61d9f058aa2e7e0?viewer=wgo
10: 0.535037
20: 0.476996
30: 0.608238
40: 0.731194
50: 0.848813
60: 0.818784
70: 0.245454
80: 0.000001
90: 0.020343

http://zero.sjeng.org/view/f4c9691d956a890055a5841a3893dadd3b5235ce764fdcaa79c3be5e71deeeee?viewer=wgo
10: 0.425678
20: 0.424737
30: 0.433754
40: 0.463286
50: 0.787219
60: 0.858679
70: 0.894944
80: 0.868541
90: 0.983123

http://zero.sjeng.org/view/f9a0ffe252c61459f32f0d0373cb37cb698e26a424740b7fea319b663255492e?viewer=wgo
10: 0.805043
20: 0.999782
30: 0.999979
40: 1.000000
50: 1.000000
60: 1.000000
70: 1.000000
80: 1.000000
90: 1.000000
```

So lowering resign percentage probably wouldn't have helped in that last game.

**Comment by fell111** [comment]
even not help for this case, decreasing resign threshold would be a good idea. The are lot of blunders coming from end of the game. And it could reverse the final result with just a mistake taken from the other side.

**Comment by gcp** [comment]
We'll have to reanalyze suitable resign thresholds, but right now this is pretty much working as designed.

(Early resign counts as lowering t=1 to t=0 in the endgame which isn't a terrible thing either)
