### ISSUE TITLE
Where is Linux-x86_64 binary release?

### ISSUE THREAD

**Issue by GD-fix** [gcp/leela-zero#1339]
Where is possible to get Linux-x86_64 binary release (such [this one](https://www.sjeng.org/leela.html))?

Thanks in advance.

**Comment by MartinDevelopment** [comment]
Just follow the steps in the README for linux, it's not difficult.

**Comment by MartinDevelopment** [comment]
@GD-fix I uploaded them here for you with commit e1284477eb0c66d41af8c80088cbb488caf20341 of next branch. 

GPU: https://drive.google.com/open?id=1A_pVDgTaPdwtQmy7S4By4uGj8R0z0r2X
CPU-only: https://drive.google.com/file/d/131gyjsdacFRgUF5iXzEBG3ibd_pIwnlW/view?usp=sharing

**Comment by GD-fix** [comment]
Thanks!

I will try CPY-only version soon...

**Comment by gcp** [comment]
Ask someone to provide packages for your distribution, or actually listen to what I say in that issue and upgrade your outdated compiler.
