### ISSUE TITLE
an idea of reverse lz format weight file to elf format

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1349]
then put it into https://github.com/pytorch/elf 's opengo, will they training faster than this project?

**Comment by hydrogenpi** [comment]
sure, if u can get fb to put their 2000 gpu to work for two weeks to train it.

**Comment by l1t1** [comment]
so if they kept doing so, we will never catch up with them:( 
until all of the bots touch the upper limit of go game(maybe the reason that alphago zero gave up).

**Comment by hydrogenpi** [comment]
your right, eventually it hits upper bound no matter what is used. THis is also why deep machine learning is not going to become AGI/ SIngularity etc
