### ISSUE TITLE
It is reasonable to add random noise all along the whole self-play game?

### ISSUE THREAD

**Issue by genleung** [gcp/leela-zero#1351]
When I run the new released Autogtp(v16) & leelazero(0.14) client, I've noticed this self-play game setting with **"randomcnt: 999"**, so that  all moves will be added with random noise. 
> {
    "cmd": "selfplay",
    "hash": "62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9",
    "leelaz_version": "0.13",
    "options": {
        "noise": "true",
        "playouts": "0",
        **"randomcnt": "999",**
        "resignation_percent": "5",
        "visits": "3201"
    },
    "options_hash": "df715e",
    "random_seed": "18016116125402580508",
    "required_client_version": "15"
}

Here is the game's sgf: http://zero.sjeng.org/view/cffe3b07ea5d020d01040236321e75e61a690aa6fa021fe32765c73dadb1bfd7?viewer=wgo

It looks like meesed up. I don't know is it reasonable?

**Comment by Hersmunch** [comment]
See https://github.com/gcp/leela-zero-server/pull/81

**Comment by Mardak** [comment]
There's more than just the sgf that gets sent to the server for selfplay games. The training data for the selfplay game isn't viewable, but it contains a lot of valuable information about what other moves were considered even if the actually selected random move is bad.

**Comment by Friday9i** [comment]
It seems we've got a new network coming with around 60% winrate: if confirmed, I'd have to admit  I was totally wrong ;-(.
I thought it was way too random and games looked like crap beginner games, but it doesn't block Leela from learning many new efficient things. Congrats!
