### ISSUE TITLE
suggest to test alphazero method

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1353]
I notice in recent 8 matchs, 6 is failed at over 51% winrate, we got 30K self-games in two days, it isn't very successful.
elf's author @yuandong-tian
said in https://zhuanlan.zhihu.com/p/36355033 and https://github.com/pytorch/pytorch/issues/5801

----

First we wrote an AZ version, the effect is not very good; then write AGZ, the effect is still; until I found a PyTorch bug (see KLDivLoss behaves differently on CPU/GPU · Issue #5801 · pytorch/pytorch, GPU gradient down Wrong, the CPU is normal.) After repairing, the AI level rushes up like a wild horse. It's amazing. Finally, **in order to accelerate the speed and replaced by AZ**.

---
maybe we also can speed the trainning by using the AZ method.

btw, i wonder if  the games of match is incuded in the training?

**Comment by roy7** [comment]
Match games aren't in training, that has been discussed many times in the past.

**Comment by l1t1** [comment]
i forgot it again and again

**Comment by l1t1** [comment]
glad to see the new best network is produced, the winrate is 0.58, it is a rather high value
