### ISSUE TITLE
Validation.exe saving progress

### ISSUE THREAD

**Issue by tterava** [gcp/leela-zero#1354]
I noticed Validation has some functions where it saves and loads .bin file if the program is quit. This doesn't seem to work correctly in Windows environment. Could this be fixed?

**Comment by l1t1** [comment]
i also ifound it

**Comment by marcocalignano** [comment]
How do you quit the Validation program?

**Comment by tterava** [comment]
I tried both "X" upper corner and Ctrl+C.

**Comment by marcocalignano** [comment]
Ok try q+Enter in the console where you get output and see if that works.

**Comment by tterava** [comment]
Pressing Q + enter works. It saves the file and continues from it next time it is launched.

Would be cool if this was documented somewhere, maybe in leelaz.exe --help?

**Comment by marcocalignano** [comment]
OK so this is no bug. Good!
