### ISSUE TITLE
Why did black resign in this match game?

### ISSUE THREAD

**Issue by Splee99** [gcp/leela-zero#1356]
In this recent match game:
http://zero.sjeng.org/viewmatch/d5311ef6f631331b87d14a788822a7c4c368dd0d8284d5396819811096b15f18?viewer=wgo#player={"goto":{"m":160}}

white connected at f12, black could just fill the liberty at D8 and win the capture race. However, black resigned right away.

**Comment by Friday9i** [comment]
All the top right seems dead if black tries to capture white with D8, and it seems White has more territory. (I'm not 9D, so you should check with Lizzie : -)

**Comment by Splee99** [comment]
Yes, I was to quick. There was a ko going on which I didn't notice.
