### ISSUE TITLE
how many elf selfplay games are  played now

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1357]
please show the number and detail of last game on webpage

**Comment by l1t1** [comment]
also wonder when the new weight base on elf can be produced and how much it would improve

**Comment by AlexanderMisel** [comment]
Just came to know that some selfplay games are using ELF weights. So it means we are using ELF weights to train our 192x15 network? Interesting. Though it might be slower than getting the selfplay games directly from Facebook.

**Comment by gcp** [comment]
First part is a server issue, second question is already answered in the ELF thread.

**Comment by l1t1** [comment]
could you tell me which thread  is the ELF thread? @gcp
