### ISSUE TITLE
some open source AI goes apply the ELF weight

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1358]
1. https://github.com/zakki/Ray/releases
rlo-0.1.1 (formly rn-4.32)

@zakki zakki released this 20 hours ago
Assets

    83.2 MB
    Rn.zip
    Source code (zip)
    Source code (tar.gz)

Ray + LeelaZero's NN evaluation.
Put LZ weights (or ELF OpenGo weights) as uct_params/lz.bin.

**Comment by hydrogenpi** [comment]
Let me guess? AQ is next? lol

**Comment by fell111** [comment]
AQ has the same structure as AlphaGo Lee. It's not easy to apply opengo's weight file.
DolBaram seems to have opengo's weight file adopted.

**Comment by Splee99** [comment]
This becomes weird. Suppose Leela Zero calls for an open challenge match, lots of AI come back with similar "weights".

**Comment by l1t1** [comment]
@hydrogenpi @Splee99 We witnessed history but was swallowed by history. so said

**Comment by ashinpan** [comment]
@hydrogenpi  I am still optimistic. We have already witnessed such struggles between open source vs. commercial softwares---e.g., LibreOffice vs. MS Office, etc. The role of open source has always been to raise the bar for commercial competitors, and to replace the latter if there is no money to be made and accordingly big companies refuse to invest. 

The only difference in our case is: the struggle happens to be between the open source community and the PR machines of big companies. The community effort can still survive even when company PR machines have lost interest. 

Moreover, as far as I have seen, LZ project has adopted the ELF weights only to produce self-play games for training, not the weights themselves. It means that even if LZ and other AIs using big company weights are more or less equal in strength, LZ can still carry its own unique style of playing, and thereby benefitting the go community in its own way.

**Comment by l1t1** [comment]
@roy7 is this true that **ELF weights only to produce self-play games for training**?

**Comment by l1t1** [comment]
@ashinpan the quesion is other software can focus on feature enhance, then wait LZ or ELF release new weights, it's a pity fot this project that LZ has no time to improve those.

**Comment by l1t1** [comment]
gcp said in https://github.com/gcp/leela-zero/issues/1113#issuecomment-386784813

As just explained, we can't train the ELF network right now, so I'm not sure I agree.

It might be useful to continue training 256x20 and eventually put the ELF selfplay games which are now being generated in it and will be in the next training updates. This way, the training code won't need changes. We'll have to see a bit how quickly Leela's nets learn from seeing ELF play.
