### ISSUE TITLE
The -g option is no longer working?

### ISSUE THREAD

**Issue by DonMathi** [gcp/leela-zero#1365]
I tried to apply the -g option to the latest version 14, but I couldn't get it to work.
Has it been switched off?

**Comment by gcp** [comment]
Are we talking about AutoGTP or Leela Zero?

**Comment by DonMathi** [comment]
I tried "autogtp.exe -g games" but the program hang and I had to quit it

**Comment by DonMathi** [comment]
I had created the folder already

**Comment by gcp** [comment]
-g specifies how many games to play at once.
-k specifies where to store them.

Did you get that mixed up?

**Comment by DonMathi** [comment]
I must have
