### ISSUE TITLE
Extreme slow down because of long running games

### ISSUE THREAD

**Issue by bastiaf** [gcp/leela-zero#1367]
Hello,

I saw that there are a lot of games with 600 or 700 moves. On a GTX 1080 with two processes a single game needs one or two hours, and the needed seconds/move is significantly greater than the average.

For example these two games with 709 and 687 moves:

```
Uploading game: 38fe8f5c0da3474b8db871e66be015c9.sgf for network 2fb02cfe21d5de064176bad19dac5bd09ab4e773e5b8f7ce8f6990d135d6dc63
Game data 1e1540d496608f0e824f8f529c69f5736dc7533d1eef6f2d52973333284a337b stored in database
19 game(s) (19 self played and 0 matches) played in 238 minutes = 751 seconds/game, 3588 ms/move, last game took 6574 seconds.
```

```
Uploading game: 2f82f769e28d4832a27afba470e19720.sgf for network 62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9
Game data 3139e98a4de3b4599473b0e05fd5417cebf8dc0062e0fa1d6af1df242edba709 stored in database
21 game(s) (21 self played and 0 matches) played in 280 minutes = 802 seconds/game, 3730 ms/move, last game took 6525 seconds.
```

I wonder why they need about 10s/move. I started autogtp with `-g 2`, but usually both processes got equal computation time, and the total number of games per hour was better than with `-g 1`. Maybe  it's an issue now with the 20b OpenGo network? But it cannot be the full explanation I think. (But I will try it with -g 1 tomorrow.)

And isn't it possible to reduce the number of visits if the moves are very random anyway?

**Comment by Hersmunch** [comment]
See #1348.
