### ISSUE TITLE
Total submitted games drop on zero.sjeng.org

### ISSUE THREAD

**Issue by gcp** [gcp/leela-zero#137]
This is a bug in the counting on the server, the games aren't lost. @roy7

**Comment by gcp** [comment]
I fixed this up manually for now. Looks like the new counting code wasn't deployed correctly to the production server.

**Comment by roy7** [comment]
How odd. I have no idea what happened. When I stopped working on this yesterday I thought I had the aggregate/sum new counting code live and in place.

**Comment by roy7** [comment]
My mistake was fetching the count from the database in two different locations and only one was updated to the new way we store lifetime count stats. I removed the 2nd db query and just use the cached value now.
