### ISSUE TITLE
what is the parameter of match task the server send?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1370]
as my machine is poor, i cannot get match tasks.
i use validation.exe to do it,
```validation -n 05b7 -n 62b5 > 05b7_62b5.log```
it shows

---

validation v1
SPRT : 0.0:35.0 h0 0 h1 35
Engine has started.
Infinite thinking time set.
Engine has started.
Infinite thinking time set.
starting:
./leelaz.exe  -g  -p 1600 --noponder -t 1 -q -d -r 0 -w  62b5
vs
./leelaz.exe  -g  -p 1600 --noponder -t 1 -q -d -r 0 -w  05b7
1 (B D4) 

but i don't know if it is same as offical task?

**Comment by gcp** [comment]
No. The server only sends matches to clients that are reasonably fast, to prevent matches from "hanging" (and thus promotion being delayed) while the slowest clients get their results in.

validation.exe is a standalone tool that can be used for development. I added a binary because of 
#1268
