### ISSUE TITLE
an interesting thing that happen in validation two networks

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1372]
**game 1**
```validation -n 05b7 -n 62b5 > 05b7_62b5.log```
validation v1
SPRT : 0.0:35.0 h0 0 h1 35
Engine has started.
Infinite thinking time set.
Engine has started.
Infinite thinking time set.
starting:
./leelaz.exe  -g  -p 1600 --noponder -t 1 -q -d -r 0 -w  62b5
vs
./leelaz.exe  -g  -p 1600 --noponder -t 1 -q -d -r 0 -w  05b7
1 (B D4) 2 (W Q16) 3 (B D16) 4 (W Q4) 5 (B O17) 6 (W C3) 7 (B D3) 8 (W C4) 9 (B C6) storeSprt
05b7     v 62b5     ( 0 games)
              wins        black       white
05b7        0   nan%    0   nan%    0   nan%
62b5        0   nan%    0   nan%    0   nan%
                        0   nan%    0   nan%
0 games played.
Status: 0 LLR 0 Lower Bound -2.94444 Upper Bound 2.94444
10 (W C5) 

----

i press q to quit the game, and then input

---

**game 2**
```validation -n 05b7 -n 62b5 -k sga >> 05b7_62b5.log```
validation v1
SPRT : 0.0:35.0 h0 0 h1 35
Initial Statistics
05b7     v 62b5     ( 0 games)
              wins        black       white
05b7        0   nan%    0   nan%    0   nan%
62b5        0   nan%    0   nan%    0   nan%
                        0   nan%    0   nan%
0 games played.
Status: 0 LLR 0 Lower Bound -2.94444 Upper Bound 2.94444
Engine has started.
Infinite thinking time set.
Engine has started.
Infinite thinking time set.
starting:
./leelaz.exe  -g  -p 1600 --noponder -t 1 -q -d -r 0 -w  62b5
vs
./leelaz.exe  -g  -p 1600 --noponder -t 1 -q -d -r 0 -w  05b7
1 (B Q4) 2 (W D16) 3 (B Q16) 4 (W D4) 5 (B F3) 6 (W R17) 7 (B Q17) 8 (W R16) 9 (B R14) 

----

do you see? all the steps of game2 are axial symmetric  with game1

**Comment by gcp** [comment]
Without noise or using move selection randomness the games are fairly deterministic, yes.
