### ISSUE TITLE
a very long time selfplay game has a strangge score with resignation_percent=0

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1378]
View your most recent self-play game: http://zero.sjeng.org/view/826dc93316962b46f786b02aa0751104493cd950588164e998eadd09c3da39a8?viewer=eidogo

---

{
    "cmd": "selfplay",
    "hash": "2fb02cfe21d5de064176bad19dac5bd09ab4e773e5b8f7ce8f6990d135d6dc63",
    "leelaz_version": "0.13",
    "options": {
        "noise": "true",
        "playouts": "0",
        "randomcnt": "999",
        "resignation_percent": "0",
        "visits": "3201"
    },
    "options_hash": "7aaaeb",
    "random_seed": "6275586492970458719",
    "required_client_version": "15"
}

---

[game_log.txt](https://github.com/gcp/leela-zero/files/1986105/game_log.txt)
G11) 590 (W H16) 591 (B L13) 592 (W pass) 593 (B pass) Game has ended.
Score: W+187.5
last game took 102060 seconds.

**Comment by l1t1** [comment]
since there is some points that black can move at last, why it passes?

**Comment by rchs819** [comment]
# "randomcnt": "999"
Random move is now all game long, why it passes? because it's random.

**Comment by l1t1** [comment]
another elf selfplay game score is **normal** with resignation_percent=0 too
http://zero.sjeng.org/view/8e8349595b96d7f6cd04562c8a1639983bc8e86b2ad918f6525df3d65a241b05?viewer=eidogo

---

O17) 250 (W B4) 251 (B S17) 252 (W N3) 253 (B R16) 254 (W O2) 255 (B S8) 256 (W O5) 257 (B pass) 258 (W pass) Game has ended.
Score: W+16.5
last game took 33989 seconds.

**Comment by l1t1** [comment]
@rchs819 you means that pass actions  are also random?

**Comment by rchs819** [comment]
Yes, policy head has 19 x 19 (Board moves) + 1 (Pass) = 362 outputs.
Leela is smart enough to decide when to pass.

Regarding the score, 
>Score: W+187.5
>Score: W+16.5

They are both **normal**, because we use [Tromp-Taylor](https://senseis.xmp.net/?TrompTaylorRules) scoring

**Comment by l1t1** [comment]
thanks @rchs819
