### ISSUE TITLE
Potential OpenCL calculation error self-play ELF game

### ISSUE THREAD

**Issue by Mardak** [gcp/leela-zero#1382]
I've been opening various recent self-play games to see if there's any patterns, but this one seems to be more random than the usual random noise:

http://zero.sjeng.org/view/fc8fa170d7479f0f64aed0062b879dbeb30408e053f806804281ea3a618cecc1?viewer=wgo

![screen shot 2018-05-09 at 1 44 30 am](https://user-images.githubusercontent.com/438537/39805115-c5776be0-532a-11e8-978c-ad3535416853.png)

The game stops at the maximum number of moves.

It happens to be with ELF network, so it might be related to #1342. Although it sounds like checks might be made less strict for that issue.

While for this one, we might want to adjust how often it's checked? Is it possible to do a one-time check for a known failure case? Would it be reasonable to have "go knowledge" sanity checks now that the networks shouldn't be playing *so* randomly?

Although perhaps these are infrequent enough to not warrant any additional attention.

**Comment by gcp** [comment]
Could it just be that the winrate is so lopsided here that play becomes random? Combined with a no-resignation game?

**Comment by Eddh** [comment]
Even if it was the case it's sad to think about how much computation is being wasted on these kind of game. I don't see any "pure" solution though. It would have to be a passing hack ?

**Comment by Ishinoshita** [comment]
"Could it just be that the winrate is so lopsided here that play becomes random?"
If I got it right, selfplay game data record visits count for all positions but not the win rate. Is there any way to check but to replay the game with the ELF nn starting from a point where the losing side is clearly adrift ?

**Comment by jkiliani** [comment]
I posted a potential explanation for this phenomenon here: https://github.com/gcp/leela-zero/issues/1361, not sure if it's the right one.

**Comment by Mardak** [comment]
Trying to replay the game with `-p 0 -v 3201 -r 0 -m 999 -t 1 -d -n --noponder -s 10767846532915678936 -w 62b5417b` on master. Here's the top 4 moves and… the selected one.
```
move 1
  D4 ->     723 (V: 49.25%) (N: 18.44%) PV: D4 Q4 D16 Q17 R15 R16 Q15 O17 R6 O3 R4 R3 S3 R5 S4 Q5 Q3 S5 P3 O4 R10 F3 H3 C17 C16
 D16 ->     686 (V: 49.21%) (N: 18.23%) PV: D16 D4 Q16 R4 P3 Q3 P4 R6 F3 C6 D3 C3 C2 E3 D2 E4 C4 E2 C5 D6 K3 C14 C12 R17 Q17
  Q4 ->     682 (V: 49.21%) (N: 18.05%) PV: Q4 D4 Q16 D17 C15 C16 D15 F17 C6 F3 C4 C3 B3 C5 B4 D5 D3 B5 E3 F4 C10 O3 M3 R17 R16
 Q16 ->     655 (V: 49.14%) (N: 18.33%) PV: Q16 D16 Q4 D3 C5 C4 D5 F3 C14 F17 C16 C17 B17 C15 B16 D15 D17 B15 E17 F16 C10 O17 M17 R3 R4 Q3
…
  A1 ->       1 (V:  0.29%) (N:  0.06%) PV: A1 

move 2
 Q16 ->     241 (V: 99.73%) (N:  6.93%) PV: Q16 D16 Q3 D4 R6 R17 R16 Q17 P16 O18
  Q4 ->     221 (V: 99.73%) (N:  6.39%) PV: Q4 Q16 D17 D4 C14 R3 R4 Q3 P3 P2
  Q3 ->     208 (V: 99.75%) (N:  5.90%) PV: Q3 Q16 C16 D4 F17 R5 P4 R8
 D16 ->     201 (V: 99.72%) (N:  5.82%) PV: D16 Q16 Q3 D4 R6 C17 C16 D17
…
 Q17 ->     174 (V: 99.76%) (N:  4.92%) PV: Q17 Q4 C16 D4 R14 E17 D17 E16

move 3
  Q4 ->     556 (V:  0.24%) (N: 16.22%) PV: Q4 C16 D4 R14 E17 D17 E16 C14 D15 C15 J16 R3
 D16 ->     529 (V:  0.24%) (N: 15.46%) PV: D16 Q3 D4 R14 R5 R4 Q5 O3 Q9 F17 E17
  D4 ->     194 (V:  0.24%) (N:  5.68%) PV: D4 Q3 D16 R14 R5 R4 Q5 O3
  R4 ->      59 (V:  0.25%) (N:  1.72%) PV: R4 D17 D4 P3 Q3 P4 Q6
…
 L19 ->       4 (V:  0.18%) (N:  0.13%) PV: L19 D17 Q4 D4

move 4
 D17 ->     166 (V: 99.84%) (N:  4.94%) PV: D17 Q4 D4 R15 P16 C15 C16 D15 F17 E16 E17 B16
  R4 ->     133 (V: 99.84%) (N:  3.94%) PV: R4 D16 D4 C4 C5 D5 C6
 C16 ->     132 (V: 99.83%) (N:  3.94%) PV: C16 Q4 D4 R15 R16 Q15 O17 P16 P17
 D16 ->     131 (V: 99.83%) (N:  3.91%) PV: D16 Q4 D4 R15 R16 Q15 O17 P16 P17 S16
…
  E7 ->       7 (V: 99.84%) (N:  0.22%) PV: E7 Q4 D17 D4 R15 C15

move 5
  Q4 ->      56 (V:  0.17%) (N:  1.67%) PV: Q4 D17 D4 R15 C15 C16 D15 F17 E16 E17
 D16 ->      25 (V:  0.16%) (N:  0.76%) PV: D16 R4 R15 R16 Q15 O17 P16 P17
 R15 ->      17 (V:  0.20%) (N:  0.50%) PV: R15 R4 P16 P17 O16 O17
  Q3 ->      16 (V:  0.17%) (N:  0.48%) PV: Q3 D17 D4 R15 C15 R5 E16
…
  P5 ->       8 (V:  0.18%) (N:  0.23%) PV: P5 C16 E17 R4 P3 Q3 Q2

move 6
 C16 ->     119 (V: 99.83%) (N:  3.53%) PV: C16 E17 R4 P3 Q3 Q2 R2 Q4
 D17 ->      96 (V: 99.83%) (N:  2.83%) PV: D17 R4 R15 D4 F3 F4 G4 F5 E3 D3
 D16 ->      94 (V: 99.82%) (N:  2.81%) PV: D16 R4 R15 D4 C7 D6 D7 C6 E6 E5 B6
  R4 ->      90 (V: 99.83%) (N:  2.67%) PV: R4 Q3 R3 P2 R7 R2 S2 S1
…
 M18 ->       9 (V: 99.83%) (N:  0.27%) PV: M18 D16 R4 P3 Q6 Q5 R5

move 7
 D16 ->      32 (V:  0.17%) (N:  0.99%) PV: D16 R4 P3 Q6 Q5 R5 R6
  Q3 ->      17 (V:  0.17%) (N:  0.51%) PV: Q3 D17 D4 F3 F4 G4 F5
 C16 ->      17 (V:  0.17%) (N:  0.51%) PV: C16 R4 Q3 R3 P2 R7 R2 S2
  R4 ->      17 (V:  0.16%) (N:  0.53%) PV: R4 D17 D4 C7 C15 C16 D15
…
  E4 ->       8 (V:  0.17%) (N:  0.26%) PV: E4 C16 E17 Q3 R5

move 8
 C16 ->     174 (V: 99.83%) (N:  5.15%) PV: C16 E17 Q3 R5 O4 P4 P3
 D17 ->     165 (V: 99.83%) (N:  4.88%) PV: D17 R4 C4 C3 B3 D3 C6 B2 C14 R15
 D16 ->     135 (V: 99.82%) (N:  4.05%) PV: D16 R4 C4 C3 B3 D3 C6 B2 L3 N3
  R4 ->     132 (V: 99.84%) (N:  3.90%) PV: R4 Q3 R3 Q4 R6 D16 C4 C3 B3 D3 C7
…
 C11 ->       8 (V: 99.85%) (N:  0.24%) PV: C11 D16 Q3 R5 O4

move 9
 D16 ->      63 (V:  0.16%) (N:  1.92%) PV: D16 R4 Q3 R3 P2 R7 R2 S2 S1
 D17 ->      42 (V:  0.17%) (N:  1.27%) PV: D17 R4 Q3 R3 P2 R7 R2 S2
 C16 ->      26 (V:  0.17%) (N:  0.80%) PV: C16 Q3 R5 O4 P4 P3
  R4 ->      19 (V:  0.16%) (N:  0.60%) PV: R4 D17 R15 C4 C3 B3 D3 C6 B2 L3 N3
…
 P10 ->      10 (V:  0.20%) (N:  0.29%) PV: P10 R4 Q3 R3 P2 R7
```

So other than move 2, looks like all of these moves happened to pick a relatively low visit move. And for black, its best move seems to not be concentrated very much, so its moves are going to be more random.

And it looks like the triggering move is the very first move A1 with 1 visit. So that is already fixed in #1376.

**Comment by Eddh** [comment]
@gcp Would reducing the maximum number of moves be an option to consider ? Looking at match games for example : http://zero.sjeng.org/match-games/5af28e2016f17a34cef84793 no game is above 400 move count. Adding a margin, 500 moves max seems reasonable.

**Comment by Mardak** [comment]
> Even if it was the case it's sad to think about how much computation is being wasted on these kind of game

Indeed. We could have gotten 8 ELF games that resign at 91 with the same computation! ;) But more seriously, it would be nice to have some finer control between 91 and 723. :)

**Comment by jkiliani** [comment]
Even with 1-visit exclusion, it would make sense to me to only play ELF games with resignation enabled. For endgame training, regular LZ nets simply produce better data.

**Comment by roy7** [comment]
Yeah I saw someone on Discord as well but @jkiliani beat me to it. Perhaps the 50% of games from ELF need normal resign on all games to avoid this. 723 moves on the biggest/slowest network when the game is already decided 600 moves earlier is painful. Let alone ELF's bad play in late game when ahead vs LZ's.

**Comment by gcp** [comment]
OK for me. I'm also OK with dropping the total % of ELF games a bit. We saw a huge jump even with a trickle of them.

**Comment by roy7** [comment]
@gcp I dropped ELF to 25% of selfplay, and it will always have -r 5.  https://github.com/gcp/leela-zero-server/commit/8af4a81fe04440fcb8b9dc83def3cce593bd2d42

**Comment by Mardak** [comment]
From analyzing the moves, it does look possible (although somewhat low probability: 0.03%) that all of the randomness was caused by black's A1 first move. And this is already fixed in `next` with skipping single-visit moves for random choice.

So it's not OpenCL related.

And the "wasted" 600+ moves is fixed by the server only requesting ELF games with resignation.

Looks FIXED to me.
