### ISSUE TITLE
can't build in VS2015, error 

### ISSUE THREAD

**Issue by waylenz** [gcp/leela-zero#1383]
Hi，
 Today I build the leela-zero , I get these errors
1>------ 已启动生成: project: leela-zero, configuration: Release x64 ------
1>GameState.obj : error LNK2001: unresolved external symbol "public: __cdecl UCTNodePointer::~UCTNodePointer(void)" (??1UCTNodePointer@@QEAA@XZ)
1>UCTNode.obj : error LNK2001: unresolved external symbol "public: float __cdecl UCTNodePointer::get_eval(int)const " (?get_eval@UCTNodePointer@@QEBAMH@Z)
1>UCTNode.obj : error LNK2001: unresolved external symbol "public: bool __cdecl UCTNodePointer::active(void)const " (?active@UCTNodePointer@@QEBA_NXZ)
1>UCTNode.obj : error LNK2001: unresolved external symbol "public: float __cdecl UCTNodePointer::get_score(void)const " (?get_score@UCTNodePointer@@QEBAMXZ)
1>UCTNode.obj : error LNK2001: unresolved external symbol "public: int __cdecl UCTNodePointer::get_visits(void)const " (?get_visits@UCTNodePointer@@QEBAHXZ)
1>UCTNode.obj : error LNK2001: unresolved external symbol "public: bool __cdecl UCTNodePointer::valid(void)const " (?valid@UCTNodePointer@@QEBA_NXZ)
1>UCTNode.obj : error LNK2001: unresolved external symbol "public: void __cdecl UCTNodePointer::inflate(void)const " (?inflate@UCTNodePointer@@QEBAXXZ)
1>UCTNode.obj : error LNK2001: unresolved external symbol "public: class UCTNodePointer & __cdecl UCTNodePointer::operator=(class UCTNodePointer &&)" (??4UCTNodePointer@@QEAAAEAV0@$$QEAV0@@Z)
1>UCTNode.obj : error LNK2001: unresolved external symbol "public: __cdecl UCTNodePointer::UCTNodePointer(class UCTNodePointer &&)" (??0UCTNodePointer@@QEAA@$$QEAV0@@Z)
1>UCTNode.obj : error LNK2001: unresolved external symbol "public: __cdecl UCTNodePointer::UCTNodePointer(short,float)" (??0UCTNodePointer@@QEAA@FM@Z)
1>UCTNodeRoot.obj : error LNK2001: unresolved external symbol "public: int __cdecl UCTNodePointer::get_move(void)const " (?get_move@UCTNodePointer@@QEBAHXZ)

------------------------------------------------------------------------
Are some packages miss？

**Comment by gcp** [comment]
You need to add UCTNodePointer.cpp to tthe sln file. I don't think anyone is maintaining the MSVC2015 build files.

**Comment by waylenz** [comment]
thank gcp,  I  add UCTNodePointer.cpp to sln,  the issue have solved
