### ISSUE TITLE
Are long ELF games valuable? 

### ISSUE THREAD

**Issue by diadorak** [gcp/leela-zero#1387]
There seems to be a non-negligible portion of ELF games that are super long (some hit 723 moves). It seems to be because the ELF network does not know when to pass. Since we are not training the ELF network, it won't learn forever. Is the information generated by such long games that useful? If not, should we limit the length of the game to a lower number, e.g., 400?   We could use the saved time to generate more meaningful games for training.

**Comment by gcp** [comment]
https://github.com/gcp/leela-zero-server/commit/8af4a81fe04440fcb8b9dc83def3cce593bd2d42
