### ISSUE TITLE
Shall we develop autogtp with Python?

### ISSUE THREAD

**Issue by earthengine** [gcp/leela-zero#139]
Currently autogtp uses Qt and I know it is widely available in the *nix world, even macOS, but it is not the case for Windows. The offline package to download for this is 2G big, that is too much at least for me , as I only have 10G free space in C drive currently (I will replace my computer in 2 months though).

Also, I am thinking unlike the real engine, autogtp is only a client and it does not require full speed of CPU to perform. A good script language like Python are both widely available across platforms (although you still need to install in Windows, it is already a standard configuration for developers nowadays) and suitable for such a task.

It would not be too hard to re-write the code in Python, so shall we start?

**Comment by gcp** [comment]
Writing it in Python makes the installation much more problematic on Windows, particularly for people that are not developers.
