### ISSUE TITLE
deepmind new paper, is it useful to leelazero?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1390]
https://www.technologyreview.com/s/611105/robots-may-someday-explore-the-world-using-features-borrowed-from-your-brain/

https://finance.yahoo.com/news/neural-networks-solve-mazes-mammal-170000967.html?guccounter=1
Source: Nature
http://nature.com/articles/doi:10.1038/s41586-018-0102-6

**Comment by gcp** [comment]
Can you please stop filing issues for every random thing that pops into your head. You've been asked before...

**Comment by l1t1** [comment]
sorry, I forget it.
