### ISSUE TITLE
Why did LZ take this preventable ko fight?

### ISSUE THREAD

**Issue by Splee99** [gcp/leela-zero#1391]
While ELF won 94.2% of the match games again with the latest weight, I was curious to see what happened exactly. In the first game here:

http://zero.sjeng.org/viewmatch/0d50f73ffe39d3c04a5a621fc98cdedbb83e82cdf282925dad0b794c26485af8.sgf

I see LZ made a preventable ko fight on the upper left corner, just like it did many many times before. If b A17 is played instead of B16, there will be no ko at all and black will live in the corner happily ever after. I also replayed the game and got the following log:
```text
Leelaz-latest> genmove B
= B16
Thinking at most 14.0 seconds...
NN eval=0.527654
Playouts: 277, Win: 54.22%, PV: B16 B19 A18 D14 P14 Q16 Q15 R15 P15 S16 R17 S17 R14 S15 R18 Q13
Playouts: 568, Win: 54.73%, PV: B16 B19 A18 D14 P14 Q16 Q15 P15 R15 O15 Q13 P16 L17 R17 S17 S18 Q17 R18
Playouts: 874, Win: 55.04%, PV: B16 B19 A18 D14 P14 Q16 Q15 P15 R15 O15 Q13 P16 L17 R17 S17 S18 Q17 R18 P17 S16 S15
Playouts: 1167, Win: 54.90%, PV: B16 B19 A18 D14 P14 Q16 Q15 P15 R15 O15 Q13 P16 L17 R17 S17 S18 Q17 R18 P17 S16 S15 T17 O13
Playouts: 1475, Win: 54.81%, PV: B16 B19 A18 D14 P14 Q16 Q15 P15 R15 O15 Q13 P16 L17 R17 S17 S18 Q17 R18 P17 S16 S15 T17 O13 K15 K16 L15
 B16 ->    1479 (V: 55.51%) (N: 55.42%) PV: B16 B19 A18 D14 P14 Q16 Q15 P15 R15 O15 Q13 P16 L17 R17 S17 S18 Q17 R18 P17 S16 S15 T17 O13 K15 K16 L15 J15
 A17 ->     136 (V: 50.60%) (N: 25.23%) PV: A17 B19 B16 A18 A19 Q16 Q17 A18 Q4 P4 A19 R15 S16 A18 Q5
 D18 ->      23 (V: 41.71%) (N: 10.84%) PV: D18 B15 C19 B16 C18 B12 D14 F15 E15 F16 E16
11.1 average depth, 28 max depth
1182 non leaf nodes, 1.39 average children
1639 visits, 531362 nodes, 1638 playouts, 117 n/s
```
Can anyone please explain why A17 got a lower score than B16? How many more self play games will LZ have to play to learn that this ko is bad and totally preventable?

**Comment by Splee99** [comment]
I think it may depend again on the heatmap rotations. I certainly saw it played such move well before 0.14.

**Comment by fell111** [comment]
We have 0.15 already. Why not try it on the latest version?

**Comment by gcp** [comment]
There are no relevant changes in 0.15 at all.

The program's behavior varies from run to run because random rotations are used. This is not a bug.

**Comment by grolich** [comment]
> I think it may depend again on the heatmap rotations. I certainly saw it played such move well before 0.14

oh for sure it happened a lot before, and there (at lower visits). that's just something the net still needs a bit more search for. There will always be things it won't find without searching a bit more. 

Was only wondering about the exact same net + exact same visits but different move.
