### ISSUE TITLE
B63 lost most of the games in a similar opening at first 30 match

### ISSUE THREAD

**Issue by Tsun-hung** [gcp/leela-zero#1392]
![51](https://user-images.githubusercontent.com/33803485/39846523-b4e1dbf8-542e-11e8-87db-9944f3eb8958.JPG)
The similar opening makes up large proportion in the match against 62B , 10 of the first 30 games.
http://zero.sjeng.org/viewmatch/0d50f73ffe39d3c04a5a621fc98cdedbb83e82cdf282925dad0b794c26485af8?viewer=wgo
http://zero.sjeng.org/viewmatch/4d2e652942447b945d944557c36bc5d3a34ad8596a3cb11110b3e7772ab5ef94?viewer=wgo
http://zero.sjeng.org/viewmatch/ca08640c430c243bc896ae4db6b430a3d9a01d4ff6343bf15e769ac3583b5d55?viewer=wgo
http://zero.sjeng.org/viewmatch/665ff0609bc450f45460498b8543fd1f660346e9682b56f237cee340559bfba7?viewer=wgo
http://zero.sjeng.org/viewmatch/05cfc27a1a2c661ee65b44f262256a73682f51db07da920d219d500b35d3c46d?viewer=wgo
http://zero.sjeng.org/viewmatch/15d361f5470a5fb8b4fab0f0424ca03ad2a738285e70b396042dff9ef431e0c9?viewer=wgo
http://zero.sjeng.org/viewmatch/0b3c7058c578cc09c00a1b87532b1325401ae67aabe7250770c68215e1de1def?viewer=wgo
http://zero.sjeng.org/viewmatch/f1f7d7b997c661a141295b39b9997228c00023b1dc706956fb845b9e1ef24f2b?viewer=wgo
http://zero.sjeng.org/viewmatch/24445b14becc9cec5825fa60fd74d4b3ff37061d4bdd78524fdcd1e18381e5b3?viewer=wgo
http://zero.sjeng.org/viewmatch/ce19e6d45238ddecd8dc2c7839eaaa88df5e7ac317a7b40dbde3ba14189b8505?viewer=wgo

It seems that B63 makes mistake(analyzed by lizzie) in this joseki, the win rate of B63 collaps suddently when 62B atari. I haven't checked all the games, but I think the result of match is bias.

**Comment by AlexanderMisel** [comment]
A possible guess is, as Leea Zero grows (esp. with ELF training), it tries some different josekis that LZ cannot fully handle.

**Comment by roy7** [comment]
Haylee could study these LZ vs ELF matches for insights into LZ's weaknesses in the opening. :)

**Comment by Mardak** [comment]
@roy7 asked for some more details on the opening, and basically it looks like pre-ELF-192x15 doesn't prefer this joseki while ELF highly prefers it, so post-ELF-192x15 is starting to learn it. The 256x20 weights did not learn from self-play with the joseki, so it is similar to pre-ELF-192x15 results.

Here's a quick look at low visits of move 30 with averaged symmetries from the first linked match http://zero.sjeng.org/viewmatch/0d50f73ffe39d3c04a5a621fc98cdedbb83e82cdf282925dad0b794c26485af8?viewer=wgo:
```
expect: A18, move: 30, who: w, visit: 10, symmetry: x̄
weight: ecab83bb
 B19 ->       9 (V: 44.49%) (N: 81.67%) PV: B19 A17 G15 H15
 A18 ->       0 (V:  0.00%) (N:  4.78%) PV: A18 
weight: 192x15
 B19 ->       9 (V: 43.76%) (N: 74.36%) PV: B19 A18 G15 H15 G14
 A18 ->       0 (V:  0.00%) (N: 13.25%) PV: A18 
weight: 224x20
 A18 ->       9 (V: 60.92%) (N: 99.67%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 B17
 B19 ->       0 (V:  0.00%) (N:  0.16%) PV: B19 
weight: 256x20
 B19 ->       9 (V: 43.05%) (N: 84.79%) PV: B19 A18 G15 P14
 A18 ->       0 (V:  0.00%) (N:  7.02%) PV: A18 
```
ELF says A18 prior is nearly 100% while pre-ELF doesn't event check A18 at very low visits because its prior is only 5%. Current 192x15 is starting to learn about A18 and has almost 3x the prior for that move.

Looking at the same move but with 3200 visits, we can see that 192x15 would have learned this joseki itself with enough training data:
```
expect: A18, move: 30, who: w, visit: 3200, symmetry: x̄
weight: ecab83bb
 A18 ->    2746 (V: 53.69%) (N:  4.78%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 P4 A19 R15 S16 A18 R3 R4 Q5 R5 A19 R17 P16 Q15 S17 R18 S18 A18 P3 Q2 A19 Q18 P17 A18
 B19 ->     433 (V: 45.24%) (N: 81.67%) PV: B19 A18 G15 H15 G14 G16 E13 P14 Q16 Q17 Q15 R17
 G15 ->       9 (V: 42.19%) (N:  2.38%) PV: G15 H15 G14 H14
 Q16 ->       7 (V: 42.51%) (N:  1.80%) PV: Q16 Q17 B19 A18 R15
 D14 ->       4 (V: 39.12%) (N:  1.40%) PV: D14 P14 Q16 Q17
weight: 192x15
 A18 ->    2834 (V: 54.05%) (N: 13.25%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 P4 A19 R15 S16 A18 R3 R4 Q5 R5 A19 R17 P16 Q15 S17 R18 S18 A18 P3 Q2 A19 Q18 P17 A18 O4 P5
 B19 ->     350 (V: 44.65%) (N: 74.36%) PV: B19 A18 G15 H15 G14 G16 E13 P14 Q16 Q17 Q15 R17
 G15 ->       7 (V: 42.72%) (N:  1.89%) PV: G15 H15 G14 G16
 Q16 ->       6 (V: 42.44%) (N:  1.74%) PV: Q16 Q17 B19 A17 G15
 D14 ->       2 (V: 39.33%) (N:  0.88%) PV: D14 P14
weight: 224x20
 A18 ->    3199 (V: 66.91%) (N: 99.67%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 P4 A19 R15 S16 A18 R3 R4 Q5 R5 A19 R17 P16 Q15 S17 A18 P3 Q2 O4 P5 Q6 O3 R7 S7 S8 Q7 P6 R8 O5 P2
 B19 ->       0 (V:  0.00%) (N:  0.16%) PV: B19 
weight: 256x20
 A18 ->    2877 (V: 54.94%) (N:  7.02%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 P4 A19 R15 S16 A18 R3 R4 Q5 R5 A19 P3 D18 E18 C19 D14 H3 G14 L3 J15 D3
 B19 ->     312 (V: 42.76%) (N: 84.79%) PV: B19 A18 G15 H15 G13 H14 F13 P14 Q16
 D14 ->       7 (V: 39.76%) (N:  2.50%) PV: D14 P14 Q16 Q17 Q15
 G15 ->       3 (V: 44.57%) (N:  0.92%) PV: G15 E12 B19
```
And just to be clear, if this were a self-play in this board position, 192x15 would learn that instead of a 13.25% prior for A18, it should be closer to 2834/3200 = 89%, and that is much closer to what 224x20 knows without any searching with its ~100% prior.

**Comment by roy7** [comment]
Which weight is "192x15"? b6337c69?

**Comment by Mardak** [comment]
And looking a bit closer at the current state of 192x15 (b6337c69) in each symmetry:
```
expect: A18, move: 30, who: w, weight: 192x15, visit: 10
symmetry: 0
 B19 ->       9 (V: 44.43%) (N: 70.07%) PV: B19 A18 G15 H15 G14 G16
 A18 ->       0 (V:  0.00%) (N: 15.71%) PV: A18 
symmetry: 1
 B19 ->       9 (V: 43.75%) (N: 83.87%) PV: B19 A18 G15 H15 G14
 A18 ->       0 (V:  0.00%) (N:  4.25%) PV: A18 
symmetry: 2
 B19 ->       9 (V: 43.63%) (N: 78.72%) PV: B19 A17 G15 H15 G14
 A18 ->       0 (V:  0.00%) (N: 11.15%) PV: A18 
symmetry: 3
 B19 ->       9 (V: 43.15%) (N: 93.28%) PV: B19 A17 G15 H15 G14
 G15 ->       0 (V:  0.00%) (N:  1.34%) PV: G15 
symmetry: 4
 B19 ->       7 (V: 44.29%) (N: 68.21%) PV: B19 A18 G15 H15
 A18 ->       2 (V: 43.06%) (N: 21.32%) PV: A18 A17
symmetry: 5
 B19 ->       9 (V: 42.33%) (N: 69.81%) PV: B19 A18 D14 P14 Q16
 A18 ->       0 (V:  0.00%) (N: 12.14%) PV: A18 
symmetry: 6
 B19 ->       6 (V: 46.54%) (N: 48.11%) PV: B19 A17 E18 P14
 A18 ->       3 (V: 45.27%) (N: 34.30%) PV: A18 A17 B19
symmetry: 7
 B19 ->       9 (V: 43.35%) (N: 82.80%) PV: B19 A18 G15 H15 G14
 A18 ->       0 (V:  0.00%) (N:  6.33%) PV: A18 

expect: A18, move: 30, who: w, weight: 224x20, visit: 10
symmetry: 0
 A18 ->       9 (V: 58.76%) (N: 99.53%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 P4
 Q16 ->       0 (V:  0.00%) (N:  0.21%) PV: Q16 
symmetry: 1
 A18 ->       9 (V: 62.69%) (N: 99.87%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 B17
 B19 ->       0 (V:  0.00%) (N:  0.08%) PV: B19 
symmetry: 2
 A18 ->       9 (V: 59.69%) (N: 99.45%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 B17
 B19 ->       0 (V:  0.00%) (N:  0.32%) PV: B19 
symmetry: 3
 A18 ->       9 (V: 63.29%) (N: 99.78%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 B17
 Q16 ->       0 (V:  0.00%) (N:  0.08%) PV: Q16 
symmetry: 4
 A18 ->       9 (V: 59.87%) (N: 99.66%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4
 B19 ->       0 (V:  0.00%) (N:  0.13%) PV: B19 
symmetry: 5
 A18 ->       9 (V: 61.81%) (N: 99.77%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 B17
 Q16 ->       0 (V:  0.00%) (N:  0.15%) PV: Q16 
symmetry: 6
 A18 ->       9 (V: 60.91%) (N: 99.82%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 B17
 B19 ->       0 (V:  0.00%) (N:  0.14%) PV: B19 
symmetry: 7
 A18 ->       9 (V: 61.31%) (N: 99.47%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 B17
 B19 ->       0 (V:  0.00%) (N:  0.33%) PV: B19 
```
So some symmetries for 192x15 have learned to give a much higher prior enough to have some visits to A19 even with 10 total visits, but the value head believes the win rate is only around 45%. Whereas ELF knows to play A18 in every symmetry as well as having a win rate around 60%. Notably 192x15 symmetry 3 has a very low prior for A18 -- only 0.81%, but see below…

And just to confirm again, 192x15 right now with 3200 self-play visits will learn this joseki all by itself after learning from ELF to increase its consideration of this move:
```
expect: A18, move: 30, who: w, weight: 192x15, visit: 3200
symmetry: 0
 A18 ->    2881 (V: 54.41%) (N: 15.71%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 P4 A19 R15 S16 A18 R3 R4 Q5 R5 A19 R17 P16 Q15 S17 R18 S18 A18 P3 Q2 A19 Q18 P17 A18 O4 P5 A19
 B19 ->     300 (V: 44.10%) (N: 70.07%) PV: B19 A18 G15 P14 Q16 Q15 R15 P15 S16 R17 S17 R14 S15 R18 Q13 R13
 G15 ->      11 (V: 42.32%) (N:  2.87%) PV: G15 E12 B19 A18 H15
 Q16 ->       7 (V: 41.26%) (N:  2.31%) PV: Q16 Q17 B19 A18 G15
symmetry: 1
 A18 ->    2786 (V: 52.88%) (N:  4.25%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 P4 A19 R15 S16 A18 R3 R4 Q5 R5 A19 R17 P16 Q15 S17 R18 S18 A18 P3 Q2 A19 Q18 P17 A18 O4 P5
 B19 ->     399 (V: 43.41%) (N: 83.87%) PV: B19 A18 G15 H15 G14 G16 H14 J14 J13 K13 K14 J15
 Q16 ->       8 (V: 40.73%) (N:  2.00%) PV: Q16 Q17 B19 A18 R17 Q15
 G15 ->       6 (V: 42.78%) (N:  1.43%) PV: G15 H15 G14 G16
symmetry: 2
 A18 ->    2812 (V: 53.98%) (N: 11.15%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 P4 A19 R15 S16 A18 R3 R4 Q5 R5 A19 P3 D14 A18 C11 B17 D12 A16 B15 D11 B12 C10
 B19 ->     373 (V: 44.64%) (N: 78.72%) PV: B19 A18 G15 H15 F13 P14 Q16 Q17 Q15 R17 O15
 G15 ->       9 (V: 41.92%) (N:  2.64%) PV: G15 H15 B19 A17 G14
 Q16 ->       3 (V: 40.57%) (N:  1.16%) PV: Q16 Q17 B19
 D14 ->       2 (V: 39.14%) (N:  0.93%) PV: D14 P14
symmetry: 3
 A18 ->    1700 (V: 51.24%) (N:  0.81%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 P4 A19 R15 S16 A18 R3 R4 Q5 R5 A19 R17 P16 Q15 S17 R18 S18 A18 P3 Q2 A19 Q18 P17
 B19 ->    1489 (V: 44.23%) (N: 93.28%) PV: B19 A18 G15 H15 G13 H14 F13 P14 Q16 Q15 R15 P15 S16 R17 S17 R14 S15
 G15 ->      10 (V: 42.07%) (N:  1.34%) PV: G15 H15 G14 G16
symmetry: 4
 A18 ->    2901 (V: 56.17%) (N: 21.32%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 P4 A19 R15 S16 A18 R3 R4 Q5 R5 A19 R17 P16 Q15 S17 R18 S18 A18 P3 Q2 A19 Q18 P17 A18 O4 P5 A19 N17
 B19 ->     286 (V: 45.71%) (N: 68.21%) PV: B19 A18 G15 H15 G14 G16 E13 P14 Q16 Q17 Q15
 G15 ->       6 (V: 44.13%) (N:  1.64%) PV: G15 H15 G14
 Q16 ->       6 (V: 43.22%) (N:  1.68%) PV: Q16 Q17 B19 A17 D14
symmetry: 5
 A18 ->    2835 (V: 52.71%) (N: 12.14%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 P4 A19 R15 S16 A18 R3 R4 Q5 R5 A19 P3 D18 D14 H3 E18 C19 Q11 L3
 B19 ->     346 (V: 43.79%) (N: 69.81%) PV: B19 A18 D14 P14 Q16 Q17 Q15 R17 O15 P12 R12 Q11
 D14 ->       9 (V: 41.92%) (N:  2.23%) PV: D14 P14 Q16 Q17 Q15
 Q16 ->       9 (V: 41.28%) (N:  2.51%) PV: Q16 Q17 B19 A18 D14
symmetry: 6
 A18 ->    2973 (V: 56.53%) (N: 34.30%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 P4 A19 R15 S16 A18 R3 R4 Q5 R5 A19 R17 P16 Q15 S17 R18 S18 A18 P3 Q2 A19 Q18 P17 A18 P5 O4
 B19 ->     205 (V: 46.45%) (N: 48.11%) PV: B19 A17 A18 A19 Q16 Q17 A18 B17 E18 B12 C11 G14 F13
 Q16 ->       8 (V: 43.55%) (N:  2.44%) PV: Q16 Q17 B19 A17 G15 H15
 G15 ->       8 (V: 41.69%) (N:  2.95%) PV: G15 H15 G14 H14
 D14 ->       5 (V: 40.32%) (N:  2.19%) PV: D14 P14 Q16 Q17 Q15
symmetry: 7
 A18 ->    2858 (V: 55.29%) (N:  6.33%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 P4 A19 R15 S16 A18 R3 R4 Q5 R5 A19 R17 P16 Q15 S17 R18 S18 A18 P3 Q2 A19 Q18 P17 A18 O4 B17 P5
 B19 ->     331 (V: 44.09%) (N: 82.80%) PV: B19 A18 G15 H15 G14 H14 G13 H13 G12 P14 Q16 Q17 R15 S16
 Q16 ->       5 (V: 41.94%) (N:  1.48%) PV: Q16 Q17 B19 A17
 G15 ->       5 (V: 40.88%) (N:  1.84%) PV: G15 H15 G14 H14
```
As highlighted earlier, symmetry 3 has a 0.81% prior, but if this were self-play, it would learn that A18 should have closer to 1700/3200 = 53% prior. And similarly all the other symmetries would learn too. Kinda neat to see 192x15 learning in action! 😄

**Comment by roy7** [comment]
I love this sort of analysis @Mardak. And the fact we can already in just a few days of ELF data being added in see the effect in a "real life" situation where LZ is blundering but is already starting to learn it's way out of the mess is awesome.

Thanks to @Tsun-hung for spotting and sharing this frequent occurrence.

**Comment by Mardak** [comment]
And just one more analysis of the progression of the recent 192x15 networks with increasing prior for A18:
```
expect: A18, move: 30, who: w, visit: 100, symmetry: x̄
weight: ecab83bb
 B19 ->      94 (V: 45.01%) (N: 81.67%) PV: B19 A18 G15 H15 G14 G16 E13 P14 Q16
 A18 ->       5 (V: 45.50%) (N:  4.78%) PV: A18 A17 B19 A19 Q16
weight: 3737d7ce
 B19 ->      86 (V: 44.22%) (N: 82.10%) PV: B19 A18 G15 H15 G14 G16 E13 P14 Q16
 A18 ->      13 (V: 51.54%) (N:  5.65%) PV: A18 A17 B19 A19 Q16 Q17 A18 B17 D14
weight: 4be6f310
 B19 ->      72 (V: 44.72%) (N: 80.16%) PV: B19 A18 G15 H15 G14 G16 E13 P14
 A18 ->      27 (V: 51.21%) (N:  8.08%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 B17 R3 A16 P3
weight: 2fb02cfe
 B19 ->      71 (V: 44.43%) (N: 79.76%) PV: B19 A18 G15 H15 G14 G16 E13 P14
 A18 ->      28 (V: 50.84%) (N:  8.01%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 B17 R3 A16 P3
weight: 05b723d0
 B19 ->      67 (V: 44.15%) (N: 77.82%) PV: B19 A18 G15 H15 G14 G16 E13 P14
 A18 ->      32 (V: 51.52%) (N:  9.33%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 B17 R3 A16 P3
weight: b6337c69
 B19 ->      59 (V: 44.49%) (N: 74.36%) PV: B19 A18 G15 H15 G14 G16 E13 P14
 A18 ->      40 (V: 51.47%) (N: 13.25%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 P4 A19 R15 S16 A18
```

**Comment by roy7** [comment]
At this rate of progress, another network or two and N might be high enough to avoid the error when playing ELF. And if all of these opening joseki errors go away... maybe we can crawl into a 10%+ win rate? ;)

**Comment by Mardak** [comment]
They are trying to learn! But apparently maybe regressed in other aspects leading to not passing 55%. Here's the latest 192x15 b6337c69 plus most recent 4 192x15 networks:
```
expect: A18, move: 30, who: w, visit: 100, symmetry: x̄
weight: b6337c69
 B19 ->      59 (V: 44.49%) (N: 74.36%) PV: B19 A18 G15 H15 G14 G16 E13 P14
 A18 ->      40 (V: 51.47%) (N: 13.25%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 P4 A19 R15 S16 A18
weight: d7fa1517e9956c3049c6672af8d228de88fc95fb66c4634c47ada963bef90343.gz
 B19 ->      58 (V: 44.72%) (N: 72.92%) PV: B19 A18 G15 H15 G14 G16 E13 P14
 A18 ->      41 (V: 51.95%) (N: 14.80%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 P4 A19 R15 S16 A18
weight: dab1e8c32fc26a8363ad0de0de1e319cde120e1421cab9e06f8620c27f0e3aa7.gz
 B19 ->      57 (V: 44.65%) (N: 74.09%) PV: B19 A18 G15 H15 G14 G16 E13
 A18 ->      42 (V: 52.04%) (N: 14.87%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 P4 A19 R15 S16 A18
weight: abb45125896a69cea31a075ce590a4d61e9ec224b18620a821c61ec426765115.gz
 B19 ->      60 (V: 44.08%) (N: 74.26%) PV: B19 A18 G15 H15 G14 G16 E13 P14
 A18 ->      39 (V: 50.88%) (N: 13.81%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 B17 R3 A16 P3 Q2 P2
weight: 9aeac1f7eea45f779d296414432601afc13bc0b5c0978678a3d64358c2e2275f.gz
 B19 ->      56 (V: 43.86%) (N: 71.88%) PV: B19 A18 G15 H15 G14 G16 E13 P14
 A18 ->      43 (V: 51.51%) (N: 16.01%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 B17 R3 A16 P3 Q2 P2
```

**Comment by Mardak** [comment]
Comparing V12 to V13 of 256x20 https://github.com/gcp/leela-zero/issues/1113#issuecomment-388195497, looks like there was some pre-ELF self-play that was already starting to learn this joseki:
```
expect: A18, move: 30, who: w, visit: 10, symmetry: x̄
weight: bef701e8
 B19 ->       9 (V: 43.05%) (N: 84.79%) PV: B19 A18 G15 P14
 A18 ->       0 (V:  0.00%) (N:  7.02%) PV: A18 
weight: 756542bf
 B19 ->       9 (V: 44.94%) (N: 78.29%) PV: B19 A18 G15 H15 G13
 A18 ->       0 (V:  0.00%) (N: 14.89%) PV: A18 
```

**Comment by Mardak** [comment]
I updated https://github.com/gcp/leela-zero/issues/1392#issuecomment-388178833 with even more recent 192x15 networks, and at least the last two (7.268M+128k and 7.268M+256k) have priors high enough to pick A18 even with only 100 visits! This means it'll be easier for moves several moves ahead plan for this joseki during search. Although, those networks did not pass, so a new batch of training from the current best will now start, but looking at the increases of priors, it seems clear there's plenty of self-play data that favors increasing it.

**Comment by Mardak** [comment]
There's a new training cycle with `7.315M+32.0k` now. Looking back at each of the last 3 sets so far, `7.252M` across its 6 training steps started with (N:  7.29%) and gained 1.5pp per network on average. `7.268M` started (N: 14.87%) gaining 2.0pp on average. And `7.291M` started (N: 21.44%) gaining 2.5pp on average.

With this new cycle `7.315M`, could we estimate that it'll gain 3.0pp on average with its +256k having N: 45%?

```
weight: + 32k 3e362cb0d5e001b49687e9484dbb0b5c8c260a5761f215e25c2d7260a62cb5ee.gz
 A18 ->      60 (V: 53.44%) (N: 29.89%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 B17 R3 A16 P3 Q2 P2 R4
 B19 ->      39 (V: 46.13%) (N: 57.47%) PV: B19 A18 G15 H15 G14 H14
```

And if we don't promote from current best 192x15 with (N: 13.25%) and reset training to that with the new training window, the most recent 3 sets have started with a +32k network increasing by 1.6pp, 8.2pp, and 16.6pp respectively. So projecting that out linearly to the next set should start with 37% with +32k and end with 55% with +256k?

**Comment by Mardak** [comment]
New promoted net LZ137 90560d92 (7.315M + 192k) is being used for training a new `7.337M` set:
```
weight: 90560d92
 A18 ->      67 (V: 52.87%) (N: 37.98%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 B17 R3 A16 P3 Q2 P2 R4 R2 Q5
 B19 ->      32 (V: 45.12%) (N: 50.39%) PV: B19 A18 G15 H15 G14 G16

weight: + 32k d0a8647e2379493d4923e7d390e34a421ad81af4bee54e46c6b6ebd20429c1e6.gz
 A18 ->      77 (V: 53.22%) (N: 50.33%) PV: A18 A17 B19 A19 Q16 Q17 A18 Q4 B17 R3 A16 P3 Q2 P2 R4 R2 Q5
 B19 ->      22 (V: 44.34%) (N: 40.44%) PV: B19 A17 G15 H15 G14 H14
```

In just 32k steps, the prior has increased 12.35pp! I'll keep updating with new nets from this set.

**Comment by Mardak** [comment]
Looks like LZ139 / +256k a39b64cc is pretty confident in finding ELF's move 30 A18 now, so I started looking at just 2 moves earlier, and looks like 192x15 did not expect ELF to play B17 in the LZ136 b6337c69 vs ELF. http://zero.sjeng.org/viewmatch/0d50f73ffe39d3c04a5a621fc98cdedbb83e82cdf282925dad0b794c26485af8?viewer=wgo

The next promoted after that match up started to find the move with 100 visits, but before that, even with 3200 visits, B17 is unvisited with around 0.3% prior.
```
expect: B17, move: 28, who: w, visit: 100, symmetry: x̄
weight: 224x20
 B17 ->      99 (V: 60.35%) (N: 98.78%) PV: B17 B16 A18 A17 B19 A19 Q16 Q17 A18 Q4 P4 A19 R15 S16 A18 R3 R4 Q5 R5 A19 P3 D18
 E18 ->       0 (V:  0.00%) (N:  0.82%) PV: E18 

weight: ecab83bb
 E18 ->      98 (V: 50.40%) (N: 81.16%) PV: E18 C19 G15 E12 H15 D14 D10 F16 G16
 G15 ->       1 (V: 49.34%) (N:  3.58%) PV: G15 
 B17 ->       0 (V:  0.00%) (N:  0.3?%) PV: B17
weight: 3737d7ce
 E18 ->      99 (V: 50.28%) (N: 83.31%) PV: E18 C19 G15 E12 H15 D14 D10 F16 G16 F17
 G15 ->       0 (V:  0.00%) (N:  3.28%) PV: G15 
 B17 ->       0 (V:  0.00%) (N:  0.3?%) PV: B17
weight: 4be6f310
 E18 ->      99 (V: 50.52%) (N: 83.72%) PV: E18 C19 G15 E12 H15 D14 D10 F16 G16
 G15 ->       0 (V:  0.00%) (N:  3.38%) PV: G15 
 B17 ->       0 (V:  0.00%) (N:  0.3?%) PV: B17
weight: 2fb02cfe
 E18 ->      99 (V: 50.02%) (N: 83.06%) PV: E18 C19 G15 E12 H15 D14 D10 F16 G16 F17
 G15 ->       0 (V:  0.00%) (N:  3.45%) PV: G15 
 B17 ->       0 (V:  0.00%) (N:  0.3?%) PV: B17
weight: 05b723d0
 E18 ->      94 (V: 49.65%) (N: 82.29%) PV: E18 C19 G15 E12 H15 D14 D10 F16 G16 F17
 G15 ->       5 (V: 50.75%) (N:  3.84%) PV: G15 H15 G14 H14
 B17 ->       0 (V:  0.00%) (N:  0.4?%) PV: B17
weight: b6337c69
 E18 ->      94 (V: 50.01%) (N: 81.63%) PV: E18 C19 G15 E12 H15 D14 D10 F16 G16
 G15 ->       5 (V: 50.45%) (N:  4.15%) PV: G15 H15 G14 H14
 B17 ->       0 (V:  0.00%) (N:  0.68%) PV: B17
weight: 90560d92
 E18 ->      86 (V: 50.77%) (N: 70.70%) PV: E18 C19 G15 E12 H15 D14 D10 F16 G16 F17
 G15 ->       7 (V: 51.26%) (N:  5.02%) PV: G15 H15 G14 H14
 B17 ->       6 (V: 46.65%) (N:  9.35%) PV: B17 B16 B19 A17
weight: d8214630
 E18 ->      67 (V: 50.90%) (N: 56.11%) PV: E18 C19 G15 E12 H15 D14 D10 F16 G16 F17
 B17 ->      25 (V: 49.71%) (N: 24.17%) PV: B17 B16 A18 A17 B19 A19 Q16 Q17 A18 Q4
 G15 ->       7 (V: 51.55%) (N:  5.75%) PV: G15 H15 G14 H14
weight: a39b64cc
 E18 ->      59 (V: 50.82%) (N: 51.62%) PV: E18 C19 G15 E12 H15 D14 D10 F16 G16 F17
 B17 ->      34 (V: 50.47%) (N: 30.13%) PV: B17 B16 A18 A17 B19 A19 Q16 Q17 A18 Q4 B17 R3
 G15 ->       6 (V: 51.67%) (N:  5.25%) PV: G15 H15 G14 G16
```

It looks like this is a positive reinforcement move for the latest 192x15 network as it now is pretty confident of searching for the winning move 30 `A18 (V: 53.29%) (N: 70.55%)` vs losing `B19 (V: 45.34%) (N: 21.35%)` (and move 29 is basically a forced move), so both 192x15 and ELF self-play's 3200 visits will want to search B17 more leading to training data that increases the prior:
```
expect: B17, move: 28, who: w, weight: 192x15, visit: 100, symmetry: x̄
 E18 ->    1685 (V: 51.67%) (N: 51.62%) PV: E18 C19 G15 E12 H15 D14 D10 F16 G16 F17 G17 F18 G18 E19 C8 H3 B6 F4 F3
 B17 ->    1206 (V: 51.92%) (N: 30.13%) PV: B17 B16 A18 A17 B19 A19 Q16 Q17 A18 Q4 B17 R3 A16 P3 Q2 P2 R4 R2 Q5 P4 Q10 G3 C9 G5 C3
 G15 ->     181 (V: 51.71%) (N:  5.25%) PV: G15 H15 G14 G16 E18 C19 E13 P14 Q16 Q17
 Q16 ->     106 (V: 51.78%) (N:  3.02%) PV: Q16 Q17 E18 C19 R15 S16 R17 P16 Q15 S17 R18 S18 G15 H15 G14
 G14 ->      14 (V: 50.87%) (N:  0.69%) PV: G14 E12 D14 P14
 O15 ->       7 (V: 48.13%) (N:  0.76%) PV: O15 D14 E18 C19 E12 G14
```

**Comment by Tsun-hung** [comment]
@Mardak I like your analysis works, the result show LZ is better at this joseki if I comprehend correctly.

**Comment by Mardak** [comment]
With the latest ELF vs LZ141 match up, I don't see this opening anymore, so LZ has learned to avoid playing into it. There's some games with something like this "double wall" except it's ELF that's on the side outside the wall:

http://zero.sjeng.org/viewmatch/3a3578ab8fa6e059ab42873ae5e06d5702435ecc20e8a5ea76c94a003ec83e9b?viewer=wgo
http://zero.sjeng.org/viewmatch/8ef323ec0475926eba4b88b9c81c7f7e860da5a17205cdbc35026bbb3a6bc85c?viewer=wgo

![screen shot 2018-05-20 at 2 16 19 pm](https://user-images.githubusercontent.com/438537/40283772-93f81df0-5c38-11e8-931c-c8a583dba2ab.png)

62b5417b  VS  11057dd7 | 375 : 44 (89.50%) | 419 / 400 | PASS

Looks like this is "RESOLVED" !

**Comment by Tsun-hung** [comment]
Wonderful!

**Comment by alreadydone** [comment]
[Here](https://www.youtube.com/watch?v=tiYq2b2Hcog) (videos in Chinese) are some "horrendous winrates" particularly surprising from traditional viewpoint of professional Go players. If no one is willing to analyze them using ELF and LZ, I plan to do so in the near future. The pros were not certain about the proper continuations after where AlphaGo Teach ends, so such analysis would add to the study of Go.
