### ISSUE TITLE
GTP issue on Mac

### ISSUE THREAD

**Issue by ThomasDeb** [gcp/leela-zero#1396]
My Leela Zero seems to be working fine: when I run 
src/leelaz --weights src/data/best_network.txt
it's able to generate moves. However, things go sideways when I try to enable GTP support: when I run
src/leelaz --gtp  --weights src/data/best_network.txt 
I get the following:

Using 2 thread(s).
RNG seed: 4570727737298692762
Detecting residual layers...v1...192 channels...15 blocks.
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 (Oct 31 2017 18:30:00)
Platform profile: FULL_PROFILE
Platform name:    Apple
Platform vendor:  Apple
Device ID:     0
Device name:   Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
Device type:   CPU
Device vendor: Intel
Device driver: 1.1
Device speed:  2500 MHz
Device cores:  4 CU
Device score:  512
Device ID:     1
Device name:   HD Graphics 4000
Device type:   GPU
Device vendor: Intel
Device driver: 1.2(Dec 19 2017 21:05:48)
Device speed:  1100 MHz
Device cores:  16 CU
Device score:  612
Selected platform: Apple
Selected device: HD Graphics 4000
with OpenCL 1.2 capability.
Loaded existing SGEMM tuning.
Wavefront/Warp size: 8
Max workgroup size: 512
Max workgroup dimensions: 512 512 512 

and it just freezes at that point. I don't understand much about the whole thing, but my conclusion is that there is somehow an issue with GTP support. Any ideas ?

**Comment by Mardak** [comment]
What are you trying to do with GTP? If you want to help generate games:
https://github.com/gcp/leela-zero#macos-and-linux

> it just freezes at that point

It's waiting for a command, e.g., "genmove black"

**Comment by ThomasDeb** [comment]
Oh right, sorry for the dumb question... I can indeed generate moves as before. I'm trying to run LZ with Sabaki, and since I was having issues there, I assumed that was the source of the problem. It's probably because I'm doing something wrong with Sabaki tough.
