### ISSUE TITLE
tree_reduction, why does it work?

### ISSUE THREAD

**Issue by ThorAvaTahr** [gcp/leela-zero#1398]
Please refer to #1397

I have performed an experiment with a version that has a reduced tree branching factor (hard limit). I have validated its performance against the master branch on the following settings: -g -v 3201 --noponder -t 1 -q -d -r 0 -w

The result was 9 wins vs 2 losses. (After that the experiment was interrupted unfortunately). I thought there would be an improved performance by reducing the number of re-evaluations of previously visited nodes. However, in reflection it is strange to me that this works, as with the above settings the number of visits is fixed and reevaluations of previously visited nodes don't count as visits.

Is there any apparent explanation? (Perhaps someone could repeat the experiment to confirm).

**Comment by gcp** [comment]
You can look in the literature and search for things such as progressive widening. These ideas aren't new. FPU reductions as they're done right now act as a soft version of this, but unlike the harder pruning they don't lose the property that the search eventually converges.

You are modifying the order and distribution with which the search explores the tree and sometimes it's possible to get something better. But 11 games are completely meaningless.

**Comment by ThorAvaTahr** [comment]
Thx, point taken,

Unfortunately on my hardware on larger experiments take far too long to be practical. 

Though my original problem lies not with fpu or with the search or move selection side of UCT, but with how we deal with running low on memory (MAX_TREE_SIZE). 

Nevertheless it breaks the theorethical convergence to optimal play as you point out, so i understand your position.
