### ISSUE TITLE
AutoGTP-produced SGF files have the players named as Leela Zero and Human

### ISSUE THREAD

**Issue by Walther** [gcp/leela-zero#140]
Expected: both players named as LeelaZero (with version information)
Actual: other player is called "Human".

![image](https://user-images.githubusercontent.com/2943750/33127680-32597aa4-cf92-11e7-84a0-db6098a9cadb.png)

**Comment by gcp** [comment]
See #90. Probably not worth fixing, can be cleaned up by a script afterwards.

**Comment by billyswong** [comment]
Is it possible to leave the player two name as blank? Then we don't need to fix things at the wrong level while the name won't mislead/displease any people.

**Comment by zjuwyz** [comment]
This is not a big problem as long as we can recognize which version of LeelaZero generated them.

**Comment by gcp** [comment]
This is fixed in the "next" branch on the autogtp side.
