### ISSUE TITLE
Start game from chosen position

### ISSUE THREAD

**Issue by dzhurak** [gcp/leela-zero#1401]
Is there a possibility to pass a position from which autogtp starts playing? For example I want to run some matches with most popular openings and compare the overall score with the probability LZ gives to it. Or to create something similar to alphagoteach database.

**Comment by abc0922001** [comment]
You can try Sabaki or lizzie to play what you want.

autogtp is auto-gtp, you know? auto

**Comment by marcocalignano** [comment]
Why do you need `autogtp` for this? If you use Leelaz you can use the command loadsgf and then continue from there.

**Comment by dzhurak** [comment]
>You can try Sabaki or lizzie to play what you want.
I want to run it once and wait few days when 1k games will be ready. What's not _auto_ with this?

>Why do you need autogtp for this? If you use Leelaz you can use the command loadsgf and then >continue from there.

Ok, I got it. This functionality exists in GTP mode. Thanks.

**Comment by roy7** [comment]
autogtp is specifically intended to run games and upload them to the server. Please be careful not to use it with your experiments and upload data to the servers with it that aren't legit games. Someone was doing that last month by accident.

**Comment by roy7** [comment]
What I'd do in your shoes is install gomill/ringmaster and edit the initial gtp command option to do the loadsgf. That might get exactly what you want.

**Comment by dzhurak** [comment]
> autogtp is specifically intended to run games and upload them to the server
Yeah, got it. I will use gogui-twogtp tool for my experiments.
