### ISSUE TITLE
0 GPU usage on NVIDIA driver 397.64

### ISSUE THREAD

**Issue by jamesho8743** [gcp/leela-zero#1402]
Usually I use Sabaki to do some matches between different engines, like ELF vs LEELA weight.
I got around 25-29% CPU usage and 13%-15% GPU usage per instance.
After I upgrade my driver to the latest release 397.64 tonight, the CPU and GPU usages become abnormal.
The GPU usage is almost 0% and the CPU usage become very high to 80% or 90%.
My equipment:
Intel i5 4670  32GB DRAM  MSI GTX 1070 8GB Windows 10 x64 1803(Spring Creator Update)
Leela Zero 0.15
Setting: ( very simple, all default)
leelaz.exe --gtp -w v136.gz    
no Initial commands
I also tried to use 0.14 and the result is the same.

Only reverting back to 397.31 or 391.35 fixes this.
Could anyone confirm this?

**Comment by miguno** [comment]
- Windows 10
- Leela Zero 0.15 w/ AutoGTP v16

FWIW I didn't notice a drop of GPU usage, but (1) much higher CPU usage (similar to you) and (2) leelaz seems to be have become prone to crashing. I attempted to run autogtp unattended but observed that the process apparently died 2-3 times, requiring a restart.

Unfortunately, there's not much more information I could share at this point to help the discussion.

**Comment by gcp** [comment]
@miguno related to issue #1342?

**Comment by gcp** [comment]
There are known bugs in the latest NVIDIA driver series, see #1360.

**Comment by miguno** [comment]
@gcp: 

> @miguno related to issue #1342?

I will monitor the next runs.

For the record, my command line is:

```
autogtp.exe -g 2 --gpus 1 --erase
```

In https://github.com/gcp/leela-zero/issues/1360 the thread starter also mentioned the use of `-g 2`.

**Comment by miguno** [comment]
I also added my environment info (GTX 1080) to my first comment above.  Copied below as well.

```
Device ID:     0
Device name:   Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
Device type:   CPU
Device vendor: Intel(R) Corporation
Device driver: 5.2.0.10094
Device speed:  3500 MHz
Device cores:  8 CU
Device score:  512
Platform version: OpenCL 1.2 CUDA 9.2.81
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     1
Device name:   GeForce GTX 1080
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 397.31
Device speed:  1784 MHz
Device cores:  20 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GTX 1080
with OpenCL 1.2 capability.
```

**Comment by miguno** [comment]
> There are known bugs in the latest NVIDIA driver series, see #1360.

Ack. Updated to latest NVIDIA driver 397.64 then.

**Comment by AncalagonX** [comment]
Oh, I'm glad this was posted, because I've been experiencing the exact same problems in #1360.
