### ISSUE TITLE
Phoenix Go open sources

### ISSUE THREAD

**Issue by bjiyxo** [gcp/leela-zero#1405]
https://github.com/Tencent/PhoenixGo

And their weights here.

https://github.com/Tencent/PhoenixGo/releases

**Comment by AncalagonX** [comment]
They released their 20-block weights only. According to the .step file, there were 639,200 steps performed on this individual set of weights.

We're entering the Golden Age of Go right before the computers fully take over. I'm glad the Chess world lived through this before, so we can know confidently that the Go community will survive this and even become better for it.

**Comment by AncalagonX** [comment]
We've already set the precedent by including the much stronger "Elf weights" as a teacher. Let's now do the same with these weights if they were also truly AGZ'ed from the start.

**Comment by fell111** [comment]
Can we convert the weight file to fit for Leela Zero even if there is no training source code? We could have another anchor for our target. That's great!

**Comment by sbbdms** [comment]
"cronus" on CGOS = PhoenixGo

**Comment by Matrok** [comment]
Are we confident that they are based on the AGZ approach? I mean, the program probably is (they claim it is), but how has it been trained?

**Comment by jillybob** [comment]
How does this program compare to ELF?

**Comment by 22nsuk** [comment]
Is it compatible?

**Comment by Ttl** [comment]
Looks like the network is slightly different from LZ. Input planes are the same as in AGZ but the network uses pre-activation architecture where batch norm and relu are before the convolution. Modifications are needed in the OpenCL code if we want to use the weights in LZ.

**Comment by l1t1** [comment]
nice job

**Comment by jkiliani** [comment]
Is PhoenixGo any easier to compile and run than ELF OpenGo? If so, it would be nice to know how good those weights actually are, i.e. if making LZ compatible for these would be worth the effort...

**Comment by l1t1** [comment]
This time we open source PhoenixGo source code and a 20 block model. Training source code and other source code are not open source because they are deeply coupled with the cloud computing platform within WeChat.

----
http://sports.sina.com.cn/go/2018-05-11/doc-ihamfahw3402974.shtml

这次我们开源PhoenixGo对弈源码和一个20 block的模型。训练源码和其它源码由于跟微信内部的云计算平台耦合较深、不易分离，暂不开源。

**Comment by TableCarpet** [comment]
LZ needs more than 20 blocks to be able to become stronger than best 20 blocks programs.

**Comment by hydrogenpi** [comment]
AGZ next week

**Comment by Ishinoshita** [comment]
@TableCarpet "LZ needs more than 20 blocks to be able to become stronger than best 20 blocks programs."
Any evidence to propose that blocks number is the bottleneck of current best programs ? I mean, that's an easy bet that I would readily do as well, but better level through better selfplay training scheme cannot be ruled out based on existing publicly available data, or correct me if I'm wrong.

**Comment by dzhurak** [comment]
I suspect that well trained LZ networks should perform better than ELF and Golaxy with LZ engine. Just because it was trained to play better with those specific parameters.

**Comment by john45678** [comment]
Great times for computer go. Thanks to Tencent. @dzhurak I'd say your right, hopefully for LZ with help from ELF (and maybe PhoenixGo), the final product will far exceed the sum of the parts.

**Comment by hydrogenpi** [comment]
it seems like the ELF team also had no idea that cronus was PheonixGo ....
So now that top bot on cgos is open sourced.

**Comment by jthack** [comment]
@hydrogenpi are we sure that cronus isn't stronger than agz?

**Comment by john45678** [comment]
Minigo have started their 7th version of 19x19, hopefully they will succeed this time. http://www.cloudygo.com/v7-19x19/eval-graphs

**Comment by hank93304** [comment]
Who is Pegasus_v1.0 on cgos? I am curious about that.

**Comment by john45678** [comment]
Theres a few Greek Legend named bots.

**Comment by hydrogenpi** [comment]
any stats of elf vs pheonix games yet.

**Comment by dzhurak** [comment]
We don't know the hardware it was running on.

**Comment by diadorak** [comment]
Tian said that the president bot on CGOS is much weaker than the one they shared.

**Comment by john45678** [comment]
No its actually stronger see: https://github.com/gcp/leela-zero/issues/1311
"@Friday9i The best bot appeared on CGOS (monroe, 3944) is not our strongest bot.. Our released bot is probably 80% winrate stronger than it."

**Comment by qucheng** [comment]
Also Monroe is only 3944 because random server errors causing timeouts. If you lose against a weak bot because of timeouts you lose a lot of rating.

**Comment by hydrogenpi** [comment]
qucheng give us a 40 block

**Comment by baduk1** [comment]
These weights are non compatable with lizzie so far. Not converted yet?

**Comment by hydrogenpi** [comment]
someone got it to compile natively. no conversion yet.

i heard rumors AGZ dropping before june

**Comment by l1t1** [comment]
tencent is going to hold a new AI go Competition, but it seems elf  isn't eligible. so if we use LZ131 or older, it is good, what about else ?
Registration eligible:

  (1) go strength: The entrants need to obtain the top 8 results of the World Artificial Intelligence Go Tournament (last 3 years), or the Chess strength is on the 9p and above of the Tencent Wild Fox Go platform;

  (2) Originality: The procedure needs to be original and has the source code of the program (if it is open source software, it can only be the original author or authorizer, and one open source software can only register one team).
---

http://sports.sina.com.cn/go/2018-05-12/doc-ihamfahw9125206.shtml
报名条件：

 （一）棋力：参赛程序需要获得过世界人工智能围棋比赛（最近3年）前8名的成绩，或者棋力在腾讯野狐围棋平台9段及以上；

 （二）原创性：参赛程序需要具有原创性并拥有程序源代码（如果是开源软件则只能是原作者或授权人参加，一种开源软件最多只能报名1支队伍）。
-----

**Comment by hydrogenpi** [comment]
[Golaxy-vs-Top-Players.zip](https://github.com/gcp/leela-zero/files/1997681/Golaxy-vs-Top-Players.zip)

**Comment by godmoves** [comment]
Six test matches are made between LZ ELF and PhoenixGo, and it seems LZ ELF is stronger. Even using 6×80ti, PhoenixGo was still beaten by LZ ELF (2×80ti). I will upload the games later.

**Comment by diadorak** [comment]
So we don't have to convert the Phoenix Go network 👍

**Comment by fohristiwhirl** [comment]
It would still be great to be able to use the Phoenix weights on the LZ engine, if that's within technical possibility.

**Comment by fell111** [comment]
Adopted to Phoenix's weight is great. Once they move to 60 blocks or more, they might release the weight for 40 blocks. And we don't need to add the adaptation at that time.

**Comment by gcp** [comment]
>is GCP interested in this weight？

Not really, it's weaker than ELF and the architecture would need larger changes in LZ.

Discussion about Phoenix Go should probably go to their issue tracker, unless there's a concrete connection with LZ.

**Comment by alreadydone** [comment]
Could anyone check the winrate when white passes its first, first two, and first three moves? 
LZ-ELF gives 0.5%, 0.2% and 0.1%
[Fine Art](https://www.leiphone.com/news/201801/USSgte0iVN16E7X7.html): 7%, 1%, 0.1%
(40-block dual-resnet, bootstrapped from human games and self-played millions of games)
LZ-ecab83: 18%, 3%, 0.3%
LZ-b6337c6: 18%, 3%, 0.1%

**Comment by l1t1** [comment]
the win64 gtp version
https://github.com/Tencent/PhoenixGo/releases/tag/win-x64-cpuonly-v1
