### ISSUE TITLE
Should noise / self-play explore every move at the root first?

### ISSUE THREAD

**Issue by Mardak** [gcp/leela-zero#1408]
@Eddh provided http://www.yss-aya.com/cgos/viewer.cgi?19x19/SGF/2018/05/11/424110.sgf for me to analyze move 306 where white blunders with B10 allowing black 307 to capture with H10. LZ136 played B10 because it evaluating move 307 for black shows basically 0% prior for H10. Only `heatmap 2` shows even a 1 for move 307 H10.

Taking a look at the crystal ball for future LZ.. I mean using ELF network, turns out even with 3200 visits, ELF fails to spot the capture in 2 symmetries. Here's the top move according to ELF:
```
expect: H10, move: 307, who: b, weight: 224x20, visit: 3200
symmetry: 0 H10 ->    2884 (V: 99.57%) (N:  1.15%) PV: H10 J5 H5 A3 J9 S1 R2 T2 T1
symmetry: 1  A1 ->     693 (V:  1.86%) (N:  3.75%) PV: A1 A3 C1 A11 A1 A2 S1 M18 N13 K18
symmetry: 2 H10 ->    2903 (V: 99.71%) (N:  1.25%) PV: H10 G10 G11 J5 H5 S1 T2 R2 J9 R1 K8 S3 pass T1
symmetry: 3 H10 ->    3180 (V: 99.81%) (N:  4.23%) PV: H10 G10 G11 S1 T1 T2 J9 A3 T1 H9 R1
symmetry: 4 H10 ->    3184 (V: 99.67%) (N:  4.74%) PV: H10 G10 G11 J5 H5 A3 J9 A1 K8 C1 H7 S1 R2
symmetry: 5  A1 ->     238 (V:  1.27%) (N:  3.98%) PV: A1 A3 A1 A11 T1 A2 C1 D1 C1
symmetry: 6 H10 ->    3194 (V: 99.56%) (N: 31.68%) PV: H10 J5 H5 S1 R2 T2 T1 H11 G11 T2 J9
symmetry: 7 H10 ->    3187 (V: 99.76%) (N:  7.95%) PV: H10 G10 G11 J5 H5 J4 J9 A3 K8 A1 T1 C1
```

For ELF priors for H10, `heatmap 1` shows 1 while `heatmap 5` shows 0.

Doing a quick test by reverting https://github.com/gcp/leela-zero/commit/cab4e924b00cb6e3108ef2641649348a5158c193 fix for #1374 shows that even with low ~400 visits, LZ136 would have found H10 when playing as black:
```
expect: H10, move: 307, who: b, weight: 192x15, visit: 400, noised with wrong alpha
symmetry: 0 H10 ->     313 (V: 99.96%) (N:  0.56%) PV: H10 M18 J9 K18 K8 A3 J5 A1 pass C1
symmetry: 1 H10 ->     156 (V: 99.95%) (N:  0.37%) PV: H10 M18 J9 K18 K8 A3 J5 C1 pass A1
symmetry: 2 H10 ->     223 (V: 99.86%) (N:  0.41%) PV: H10 A3 J9 A1 K8 C1 J5 K18 pass M18
symmetry: 3 H10 ->      95 (V: 99.85%) (N:  0.30%) PV: H10 A3 J9 S1 R2 T2 T1 H9
symmetry: 4 H10 ->     267 (V: 99.90%) (N:  0.54%) PV: H10 K18 J9 M18 K8 A3 J5 C1 pass
symmetry: 5 H10 ->     140 (V: 99.96%) (N:  0.34%) PV: H10 C1 J9 A3 K8 A1 J5 K18 pass M18
symmetry: 6 H10 ->     285 (V: 99.86%) (N:  0.53%) PV: H10 K18 J9 M18 K8 A3 J5 C1 pass A1
symmetry: 7 H10 ->      37 (V: 99.98%) (N:  0.26%) PV: H10 A3 J9 A1 K8 C1 J5 M18 pass
```
If this were self-play training, even the lowest noised prior with symmetry 7 would be valuable to increase from 0% to closer to 9% prior. And this is only with 400 visits. Most likely if I evaluated this noised result with 3200 visits, the additional 2800 visits would all go into H10, so symmetry 7 would appear as 2827 / 3200 = 89% training data!

I'm not suggesting that the fix for #1374 be reverted, as that's clearly wrong. But the behavior of a very flat noise effectively allowed a losing position to try every move until it found one that worked.

So one way to directly get at that desired behavior is to have noised games have the root visit every single child **before** searching deeper.

Otherwise, we might end up in a future like ELF where as strong as it is, it's still blind to self-atari in some cases…

**Comment by Mardak** [comment]
One thing to note: naively, this will also cause training data to include ~1/3200 0.03% to every position. I'm not sure if that's much of a difference vs training data with 0s. But I believe with fpu reduction, it won't really matter anyway?

Additionally, in the future if self-play visits drops from 3200 to something closer to 400, then the numbers will definitely start to skew more.

**Comment by AncalagonX** [comment]
Towards the very end of March I did a quick little test with the then-reigning LZ weights, by forcing LZ to visit every intersection of the board once. Then I reran with 10x visits per intersection, then 100x per intersection, and finally 1000x visits per intersection for roughly 361,000 visits plus an extra thousand visits for "pass".

The maximum difference in changed win percentage between 1 visit and 1000 visits was only 3% for two moves. All other moves differed less than 3% from their original 1-visit evals after 1000 more visits.

Visiting each square once costs 361+1 visits, but the eval results that get returned to us are surprising accurate. If someone has good reason for having LZ know the evals of every 19x19 intersection of the board, then it might be a beneficial inclusion from this perspective.

**Comment by roy7** [comment]
I think @AncalagonX played with that once, having every root child get a visit before anything else happened. (In fact he also experimented with his high visit count bot doing 50 or 100 visits of every root child before MCTS started.)

Keep in mind even if correctly working noise totally misses this, eventually a similar situation will happen again and the noise might hit it that time. Just the nature of how we're using the noise.

However, it's an interesting thought if self-play games should do a single visit to every child at the root node. FPU would then only be used for deeper in the tree. In Chess terms, no "one move checkmate" is ever overlooked during selfplay training no matter how how the prior.

If we don't want to weaken our selfplay games in general by using up visits from our 3200, we could add custom training code to not found the root child evals under the 3200.

**Comment by jkiliani** [comment]
The concept is interesting, but we should then probably exclude 1-visit nodes from the training data like we recently removed them from move selection. If we force a visit for every root child, having this visit is no longer any recommendation for quality.

**Comment by Mardak** [comment]
I suppose an important question to ask is that even though we've had the wrong alpha (361x larger) for so long, why hasn't it helped train the network to find the capture in this case?

Without answering that, an alternative to enforcing 1 visit at the root to not change the search algorithm is just to tweak the priors just as what happened with the wrong alpha. Increasing priors makes them searchable if all other options look bad, so this would only help find "the single good move" (from a losing position) as opposed to helping find a better move in general. Below are various most visited move in each symmetry when adjusting priors and searching 3200 visits:

The relatively flat noise with wrong alpha finds the capture:
```
0: H10 ->    3113 (V: 99.93%) (N:  0.56%) PV: H10 M18 J9 K18 K8 A3 J5 A1 pass C1 pass
1: H10 ->    2956 (V: 99.96%) (N:  0.37%) PV: H10 M18 J9 K18 K8 A3 J5 C1 pass A1 pass
2: H10 ->    3023 (V: 99.84%) (N:  0.41%) PV: H10 A3 J9 A1 K8 C1 J5 K18 pass M18
3: H10 ->    2895 (V: 99.86%) (N:  0.30%) PV: H10 A3 J9 A1 K8 C1 J5 K18 pass M18
4: H10 ->    3067 (V: 99.93%) (N:  0.54%) PV: H10 K18 J9 M18 K8 A3 J5 C1 pass A1
5: H10 ->    2940 (V: 99.94%) (N:  0.34%) PV: H10 C1 J9 A3 K8 A1 J5 K18 pass M18 pass pass
6: H10 ->    3085 (V: 99.88%) (N:  0.53%) PV: H10 K18 J9 M18 K8 A3 J5 C1 pass A1 pass pass
7: H10 ->    2837 (V: 99.96%) (N:  0.26%) PV: H10 A3 J9 A1 K8 C1 J5 M18 pass K18 pass
```

The correct 0.03 alpha misses some symmetries:
```
0: H10 ->    3030 (V: 99.93%) (N:  0.05%) PV: H10 M18 J9 K18 K8 A3 J5 A1 pass C1 pass
1:  T1 ->     626 (V:  0.01%) (N: 19.81%) PV: T1 A11 J5 K18 pass M18 pass pass
2: H10 ->    2558 (V: 99.83%) (N:  0.11%) PV: H10 A3 J9 A1 K8 C1 J5 K18 pass M18
3: H10 ->    3124 (V: 99.86%) (N:  0.84%) PV: H10 A3 J9 A1 K8 C1 J5 K18 pass M18
4: M18 ->     472 (V:  0.18%) (N: 14.32%) PV: M18 A11 N18 L18 pass K18 pass M19
5: E10 ->     643 (V:  0.29%) (N: 18.49%) PV: E10 A11 pass F9 J5 K18 pass M18
6: H10 ->     918 (V: 99.91%) (N:  0.01%) PV: H10 K18 J9 M18 K8 A3 J5 C1 pass A1 pass
7: M18 ->     383 (V:  0.16%) (N: 11.44%) PV: M18 A11 K18 L18 L19 J18 K19 J19 M19
```

An alpha 20x larger = 0.6 finds the move:
```
0: H10 ->    3103 (V: 99.93%) (N:  0.39%) PV: H10 M18 J9 K18 K8 A3 J5 A1 pass C1 pass
1: H10 ->    2392 (V: 99.95%) (N:  0.12%) PV: H10 M18 J9 K18 K8 A3 J5 C1 pass A1 pass
2: H10 ->    2551 (V: 99.83%) (N:  0.11%) PV: H10 A3 J9 A1 K8 C1 J5 K18 pass M18
3: H10 ->    1707 (V: 99.86%) (N:  0.07%) PV: H10 A3 J9 A1 K8 C1 J5 K18 pass M18
4: H10 ->    2974 (V: 99.93%) (N:  0.35%) PV: H10 K18 J9 M18 K8 A3 J5 C1 pass A1
5: H10 ->    3087 (V: 99.94%) (N:  0.69%) PV: H10 C1 J9 A3 K8 A1 J5 K18 pass M18 pass pass
6: H10 ->    2848 (V: 99.91%) (N:  0.19%) PV: H10 K18 J9 M18 K8 A3 J5 C1 pass A1 pass pass
7: H10 ->    1903 (V: 99.96%) (N:  0.08%) PV: H10 A3 J9 A1 K8 C1 J5 M18 pass K18 pass
```

Or perhaps not as elegant as using just a noise function but directly setting a minimum score of 0.04% (`child->set_score(std::max(0.0004f, score))`) finds the move that a 0.03 alpha would have missed:
```
0: H10 ->    3030 (V: 99.93%) (N:  0.05%) PV: H10 M18 J9 K18 K8 A3 J5 A1 pass C1 pass
1: H10 ->     717 (V: 99.95%) (N:  0.04%) PV: H10 M18 J9 K18 K8 A3 J5 C1 pass A1
2: H10 ->    2558 (V: 99.83%) (N:  0.11%) PV: H10 A3 J9 A1 K8 C1 J5 K18 pass M18
3: H10 ->    3124 (V: 99.86%) (N:  0.84%) PV: H10 A3 J9 A1 K8 C1 J5 K18 pass M18
4: H10 ->    1251 (V: 99.91%) (N:  0.04%) PV: H10 K18 J9 M18 K8 A3 J5 C1 pass A1
5: H10 ->     695 (V: 99.98%) (N:  0.04%) PV: H10 C1 J9 A3 K8 A1 J5 K18 pass M18
6: H10 ->    1980 (V: 99.92%) (N:  0.04%) PV: H10 K18 J9 M18 K8 A3 J5 C1 pass A1 pass pass
7: H10 ->     598 (V: 99.91%) (N:  0.04%) PV: H10 A3 J9 A1 K8 C1 J5 M18 pass K18
```

**Comment by roy7** [comment]
> The concept is interesting, but we should then probably exclude 1-visit nodes from the training data like we recently removed them from move selection. If we force a visit for every root child, having this visit is no longer any recommendation for quality.

Yes, if we were to do a "visit every root child 1 time" start to each search, we could also do a "subtract 1 visit from the total of each node when calculating the proportions and calling dump_training. So it'd have no actual change except replacing root children FPU guesses with real evals.

**Comment by Mardak** [comment]
> If we force a visit for every root child, having this visit is no longer any recommendation for quality.

@jkiliani I agree that the training data will result in a higher search probability for these forced visits, but is there a practical change that affects future self-play or match games?

In the extreme case where all 3200 visits would have gone into a forced move, 19*19 - 1 visits would have unnecessarily gone to a different move. This means the training data would show 2840/3200 = 88.75% for the one move and 1/3200 = 0.03% for all the other moves, so networks should converge towards that search probability for its priors assuming that is the one correct move for a board state.

So statically, the priors are different, but in actual dynamic move selection, would the root child selection with fpu_reduction and non-root child selection actually be different?

**Comment by Mardak** [comment]
With the proposal in #1416 to reduce self-play visits from 3200 to 800, the forced visits at root would definitely start skewing training data if they're counted towards the total visits. A move that would normally get 100% of 800 visits would then only 440 appearing as 55% for training data while the forced single visits would be 0.125% training data.

**Comment by jkiliani** [comment]
Agreed, forcing root visits would be theoretically viable for 3200 total visits, but for just 800 I have my doubts. I think this proposal is not really compatible to the idea of lowering visits substantially, but on the other side, more games with the now correct Dirichlet noise should achieve the same exploration even if not every root move is explored.

**Comment by gcp** [comment]
The idea of noise is that eventually every move gets explored at the root, just not all every position in every game. I don't think it makes sense to diverge further from A(G)Z here.

**Comment by gcp** [comment]
By the way, I'm not sure closing these kind of issues is the right thing to do or not, but if I don't their number gets out of hand and it gets impossible to track anything. Basically my view is "without data this is a better, it's not going to happen" but that doesn't mean this can't be discussed of course. Feel free to reopen if you think they should stay open.

**Comment by Mardak** [comment]
@gcp as an alternative to forcing a visit for every move on every root, how about some alternatives from https://github.com/gcp/leela-zero/issues/1408#issuecomment-388541302 where search algorithm is untouched except for where it's already in a losing position and search naturally tries to find other moves?

E.g., increase alpha by 20x to 0.6f (but not the previously wrong 361x larger) or something like setting a minimum prior when noised ([`child->set_score(std::max(0.0004f, score))`](https://github.com/gcp/leela-zero/blob/9e903eda6e93fb65375ea03127e4f62268913175/src/UCTNodeRoot.cpp#L100)). Where the former reduces the peak to give enough to other moves and the latter just bumps things up (ignoring the fact that ∑Psa > 1).

Or something a bit more different is getting rid of the "mathematically nice noise" with a step function where say one random move get much higher noised priors and all other moves get enough when weighted ε noise is enough to get visited in a losing position: noise = [0.28, 0.002, 0.002, 0.002, …] so after ε = 25% means even a 0% prior ends up with an adjusted score of 0.0005.

It seems that these self-atari positions did not come up often in self-play for ELF or LZ with T=1 for first 30 moves. Maybe they might happen more in the no-resign self-play with T=1 for all moves now. But at least with the current 0.03f alpha noise behavior, some symmetries would have missed the correct play. And that just seems a bit unfortunate to miss out on a great learning moment of a rare position. (But on the flip side, if these positions are that rare, perhaps even with valuable training data, it won't move the network that much anyway…)

**Comment by Mardak** [comment]
It still goes through `uct_select_child` where in most positions (non-0% win rate) will tend to favor high winrate moves, so the added non-negligible prior is effectively negligible. Only when all moves have basically 0% win rate will puct with usually-negligible prior allow selection.

**Comment by gcp** [comment]
Ah, so the underlying reasoning is that it's safe to swing wildly when you're losing anyway? But that seems sub-optimal for handicap games.

**Comment by Mardak** [comment]
Yes, so only for noised self-play games to try to find the better move for training data.

**Comment by Eddh** [comment]
Given that these self ataris seem to be a constant problem for all these zeros bot, I expect it will be hard to correct it without changing network architecture or using 40+ layers. Personally I think adding a "legal moves" plane wouldn't constitute human knowledge since legal moves are part of the rules of the game, but I guess that is up for debate ?

Otherwise we will need to go beyond what Deepmind did and change the architecture to something new for a later training run. Someone already made some experiments, some of which are promising https://github.com/lightvector/GoNN
I particularly like the dilated filters architecture since it is very light computationally, and is based on a computer vision paper. It might be a bit tricky to implement in OpenCL though (maybe, I'm no expert).

Apart from that there are also other new residual architectures which haven't been tried for go yet. I'm thinking mostly of this https://arxiv.org/abs/1605.07146. this should be the most complicated to implement though.

What are your thoughts about that ?
