### ISSUE TITLE
MacOS leelaz stops frequently with multiple threads

### ISSUE THREAD

**Issue by Mardak** [gcp/leela-zero#141]
I noticed that from time to time, `autogtp` (including v4) would just stop with a print out something like:
```
1 (J16) 2 (L3) 3 (E9) 4 (R11) 1 game(s) played in 0 minutes = 23 seconds/game, last game took 23 seconds.
```

I have it automatically restart, and I tried playing around with `-t #` in `Game.cpp`'s `cmdLine`. Appending `-t 1` seems to make all played games submittable without stopping.

I tried to see what configuration would result in a higher submission rate:
```
1x -t 8: 8.4 game/hr, 1.0 submission/hr (~ 5.0 hours)
1x -t 4: 4.4 game/hr, 1.6 submission/hr (~ 2.5 hours)
1x -t 2: 20. game/hr, 2.0 submission/hr (~ 2.0 hours)
1x -t 1: 2.2 game/hr, 2.2 submission/hr (~10.1 hours)
4x -t 1: 4.8 game/hr, 4.8 submission/hr (~ 8.0 hours)
```

Where in these tests, it looks like running 4 single-threaded instances seems to result in the highest submission rate.

2.9 GHz Intel Core i7, 16 GB 2133 MHz LPDDR3, Radeon Pro 460 4 GB + Intel HD Graphics 530 1536 MB

**Comment by isty2e** [comment]
It helped me a lot, I appreciate. Before this, I also suffered from frequent stop of the autogtp.

**Comment by Mardak** [comment]
I tried running with various number of `autogtp`s singlethreaded (no crashes):

4x -t 1: 15 + 14 + 12 + 13 submitted ~690 minutes -> 4.7 submission/hr
5x -t 1: 9 + 8 + 8 + 8 + 8 ~435 minutes -> 5.7 submission/hr
6x -t 1: 4 + 4 + 5 + 3 + 4 + 5 ~280 minutes -> 5.4 submission/hr
8x -t 1: 3 + 2 + 3 + 3 + 3 + 3 + 3 + 4 ~305 minutes -> 4.7 submission/hr

I guess I'll leave it running in 5 instances on my machine.

**Comment by Mardak** [comment]
Is this not a bug or enhancement, so working as intended on mac?
