### ISSUE TITLE
Error on Compiling and Running Leelaz on Archlinux with gcc and gcc-fortran version 8.1.0

### ISSUE THREAD

**Issue by cdqz2014** [gcp/leela-zero#1411]
I am veteran trainer and user of LZ for half a year. All things went smoothly before. However, the situation changed after the usual rolling updating of my Arch Linux recently. I noticed that both package `gcc` and `gcc-fortran` have been automatically upgraded to **8.1.0**, and many related libraries of GFORTRAN_7 are no longer supported. In fact, when I compiled leelaz on my Arch to catch up with the version your released, errors reflected
```
/usr/bin/ld: warning: libgfortran.so.4, needed by /usr/lib/gcc/x86_64-pc-linux-gnu/8.1.0/../../../../lib/libopenblas.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/x86_64-pc-linux-gnu/8.1.0/../../../../lib/libopenblas.so: undefined reference to `_gfortran_compare_string@GFORTRAN_7'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.1.0/../../../../lib/libopenblas.so: undefined reference to `_gfortran_etime@GFORTRAN_7'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.1.0/../../../../lib/libopenblas.so: undefined reference to `_gfortran_concat_string@GFORTRAN_7'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:64: leelaz] Error 1
make[1]: Leaving directory '/home/hxd/leela-zero/src'
make: *** [Makefile:5: default] Error 2
```
The former version of leelaz still exists on my directory. But when I tried to run it instead, errors also occurred
```
AutoGTP v16
Using 1 thread(s) for GPU(s).
Starting tuning process, please wait...
net: b6337c693d5cc6e6bace8c3107520df97e23f61f2c25a264e1e558b1021c3f2f.
./leelaz --tune-only -w networks/b6337c693d5cc6e6bace8c3107520df97e23f61f2c25a264e1e558b1021c3f2f
./leelaz: error while loading shared libraries: libgfortran.so.4: cannot open shared object file: No such file or directory
Tuning process finished
```
I wonder how to solve this without downgrading **ALL packages** on my computer. Because you know, the rolling updating strategy of Arch Linux is that, one cannot downgrade one single package but the whole system...

**Comment by nshiff** [comment]
Well, this is a dumb hack solution. But you could grab `libgfortran.so.4` from somewhere else and manually place it in /usr/lib, or maybe just in the leela-zero project. 

As far as working within the package management system, you might be better served on a forum dedicated to Arch. I don't know very much about Arch, but I know their wiki is thorough. I imagine someone out there wants to run gcc 7 and gcc 8 on the same machine, so perhaps there is a way.

**Comment by cafaxo** [comment]
Have you tried to rebuild **[libopenblas](https://aur.archlinux.org/packages/libopenblas/)** since the gcc update? The [aur package for leela-zero](https://aur.archlinux.org/packages/leela-zero/) is working for me.

**Comment by cdqz2014** [comment]
@cafaxo Oh, thanks, It did work! After I rebuilding this seemingly irrelevant **aur/libopenblas** package, everything went alright again. I thought there may be some dependency problems on Archlinux : )
