### ISSUE TITLE
Build on windows (with msvc , MKL)

### ISSUE THREAD

**Issue by FeelF** [gcp/leela-zero#1414]
How can I build on windows?
 (with msvc2017 , Math Kernel Library 2018 Update 1)

MKL: https://software.intel.com/en-us/mkl

**Comment by John-Yu** [comment]
enable USE_MKL and disable USE_OPENBLAS  in config.h
delete OpenBlas packages 
maybe need  get MKL lib from https://github.com/intel/mkl-dnn/releases/mklml_win_2018.0.3.20180406.zip

**Comment by FeelF** [comment]
Math Kernel Library Update 1 for windows: https://software.intel.com/en-us/mkl
Leela zero: https://codeload.github.com/gcp/leela-zero/tar.gz/v0.15

1-Edit **leela-zero-0.15\src\config.h** change:
```
#if !defined(__APPLE__) && !defined(__MACOSX)
#define USE_OPENBLAS
#endif
```
```
//#define USE_MKL
```
```
#ifndef USE_CPU_ONLY
#define USE_OPENCL
#endif
```
to
```
#if !defined(__APPLE__) && !defined(__MACOSX)
// #define USE_OPENBLAS
#endif
```
```
#define USE_MKL
```
```
#ifndef USE_CPU_ONLY
//#define USE_OPENCL
#endif
```
2-  **Properties -->Intel Performance Libraries --> Use Intel MKL**
![image](https://user-images.githubusercontent.com/22231104/39967469-32252b76-56ee-11e8-9292-6507e3fda072.png)
3- **Properties --> VC++ Directories**
```
Executable Directories: C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.1.156\windows\redist\intel64_win\mkl
Inclide Directories: C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.1.156\windows\mkl\include
Library Directories: C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.1.156\windows\compiler\lib\intel64_win
Library Directories: C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.1.156\windows\mkl\lib\intel64_win
```
![image](https://user-images.githubusercontent.com/22231104/39967488-6f578552-56ee-11e8-93af-084943789677.png)
4-  **Build**
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
5- 
```
Leven@Leven MINGW64 /e/ProjectAll/CPlusPlus/leela-zero-0.15/msvc/x64/Release
$ ./leelaz.exe --weights best_v1_weights.txt
E:/ProjectAll/CPlusPlus/leela-zero-0.15/msvc/x64/Release/leelaz.exe: error while loading shared libr aries: api-ms-win-crt-locale-l1-1-0.dll: cannot open shared object file: No such file or directory
```
![image](https://user-images.githubusercontent.com/22231104/39967502-c8a774f0-56ee-11e8-80ef-6bfdc69e4e36.png)

**Comment by Tsun-hung** [comment]
Do you build the 32-bit version?

**Comment by FeelF** [comment]
**PATH:** msvc/x64/Release 
**Add .dll:** 
libiomp5md.dll ; 
mkl_core.dll ; 
mkl_def.dll ; 
mkl_intel_thread.dll ; 
mkl_avx.dll
![image](https://user-images.githubusercontent.com/22231104/39969131-37a75d3c-570a-11e8-8a8b-79ad952a1043.png)

**Comment by gcp** [comment]
You should use serial MKL, not parallel. LZ tries to force the library to serial in any case.

**Comment by genleung** [comment]
Can LZ benefit from using Intel TBB & Intel IPL64 interfaces ?

**Comment by FeelF** [comment]
> You should use serial MKL, not parallel. LZ tries to force the library to serial in any case. (She has her own parallelism which is more efficient)

Thank you for your valuable advice.

![image](https://user-images.githubusercontent.com/22231104/39996471-30085e3e-57b2-11e8-873c-3b679100133e.png)
![image](https://user-images.githubusercontent.com/22231104/39996524-5963f90a-57b2-11e8-9c0f-3ea00ebde296.png)
