### ISSUE TITLE
Some performance test results about the best number of threads for leela zero

### ISSUE THREAD

**Issue by qysnn** [gcp/leela-zero#142]
I see people discussing how different number of threads impact the performance of leela zero as in #133 #141 and #86. So I ran some preliminary tests about that. Here's the result. It turns out the default configuration is the best one if you are running only one instance. Maybe I will run more tests when the multiple games feature get implemented in the future. Before that, I think it's still recommended to run multiple instances to get the highest productivity instead of using more threads.

**number of threads**|**average time per move (s）**|**1st game move**|**1st game time**|**2nd game move**|**2nd game time**|**3rd game move**|**3rd game time**|**total move**|**total time**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
1|0.894327894|540|479|467|419|280|253|1287|1151
2(default)|0.535626536|606|324|489|263|533|285|1628|872
3|0.666666667|498|328|202|136|491|330|1191|794
4|0.590909091|476|281|363|214|371|220|1210|715
5|0.651449275|564|369|373|239|443|291|1380|899
7|0.724309001|481|350|501|362|429|310|1411|1022
10|0.876882197|503|448|351|300|275|242|1129|990
40|1.224416517|321|384|294|355|499|625|1114|1364

Test   environment: Ubuntu 16.04, GeForce GTX 1080 Ti X4, Intel(R) Xeon(R) CPU   E5-2630 v4 @ 2.20GHz X2

**Comment by marcocalignano** [comment]
@qysnn if you are able to build your autogtp you can try the version in the next branch. We also would like to have it test on multiple GPUs

**Comment by Azirine** [comment]
I'm running two instances, each set to use two cores on i5-2500K (and GTX 1060). Each instance generates moves at a rate of 1.7 s/move for a total of 0.85 s/move. This seems quite slow compared to what you got. CPU usage is at 75% while GPU is at 65% so I don't think it's an issue of my computer not being fast enough. It'll be good if we can figure out a way of maximizing the rate of move production.

**Comment by Alderi-Tokori** [comment]
@Azirine the gtx 1060 is at 4.4TFLOPS while the gtx 1080 ti is over 10TFLOPS, so his GPU is basically more than twice as fast as yours. This could explain the difference in speed.

**Comment by qysnn** [comment]
@marcocalignano I tried the `next` branch. But I failed to use the `u` option. No matter I use command line like `./autogtp -u 1` or `./autogtp --u 1`, I always get 
```
autogtp v4
Best network hash: 1ac2638de9d4d3f9eef43f2afb6b1b4c090a7c350fde4d2d77e00e39eba6fde0
Required client version: 2 (OK)
Already downloaded network.
GTP: Leela Zero  Copyright (C) 2017  Gian-Carlo Pascutto

*ERROR*: Error in GTP response.
```
Can you update the readme file accordingly to explain the usage of these new options?

**Comment by Ttl** [comment]
There's a bug in the program with -u option. In Production.cpp line 56 "-gpu" should be "--gpu". If you change that the "-u" option should work.

Note that "-u" option takes an ID of GPU to use. GPU IDs start from 0. If you have more than one GPU and want to use the first two the correct argument is "-u 0 -u 1"

Use "-g" option to play multiple games on one GPU.

**Comment by marcocalignano** [comment]
@Ttl Thanks! I did a pull request that fix the bug you found. 
@qysnn the command line should look like this 

`autogtp -g 3 -u 0 -u 1 -u 2 -u 3 `

this will start autogtp with 3 games for each GPU you put in the list

**Comment by qysnn** [comment]
@marcocalignano I have compiled the latest version of `next` branch and it runs smoothly. However, there is a tiny problem that the output of each move are mixed with the output of a ended game. The graphic utilization is shown below.
![image](https://user-images.githubusercontent.com/27019112/33174338-76e9b650-d00c-11e7-9e9c-d6aebdbcf03a.png)

**Comment by marcocalignano** [comment]
@qysnn can you make an average how many game you can do per hour with the multi GPU games and without?

**Comment by qysnn** [comment]
@marcocalignano I tested with config `autogtp -g 4 -u 0 -u 1 -u 2 -u 3` on two different machines. 
The one with 4X 1080 Ti played 148 game(s) played in 163 minutes = 66 seconds/game.
The one with 4X 1080 played 269 game(s) played in 163 minutes = 36 seconds/game.
They are both equipped with E5-2630 v4 @ 2.20GHz X2. I really have no idea why there is such a difference in performance. I will run a benchmark later when I have more spare time.

**Comment by WhiteHalmos** [comment]
Same CPU?

**Comment by godmoves** [comment]
@marcocalignano It seems that when  we use `-g 4` parameter, the number of short games will increase. Is this a problem？For example, if I use `-g 1`,  the size of the sgf files generated is about 2-3k, but when I use `-g 4`, the files are all 1k.

**Comment by marcocalignano** [comment]
Can you collect 50 games with each option and make an avarage. If they are really ALWAYS smaller can you look inside and check if the game makes sense?

**Comment by godmoves** [comment]
@marcocalignano Yes, the game ended after two passes and everything is right except it is really short ( about 30-50 moves)

**Comment by Ttl** [comment]
@godmoves What operating system you are using?

**Comment by godmoves** [comment]
@Ttl  We test on Windows 7, and it works fine on Ubuntu

**Comment by marcocalignano** [comment]
@godmoves can you try without -g option at all.
I am running my autogtp with -g 3 and the games are usually more than 350 moves sometimes even 500 moves

**Comment by Ttl** [comment]
I looked at some stats of the games earlier. Only 2 games out of 143 are shorter than 100 moves and the average is 411 moves (standard deviation 97).

![lengths](https://user-images.githubusercontent.com/544240/33242617-93282898-d2e0-11e7-82e1-0b9403087652.png)

**Comment by qysnn** [comment]
@marcocalignano @Ttl I think it is because some previous networks will tend to pass as early as they can as white and hope black will pass so that they have a free win. In the current version of network it is rare to see games less than 100 moves.

**Comment by marcocalignano** [comment]
@gcp are you going to release the next branch version of autogtp? I wonder if the multigame option will accelerate the game production.
