### ISSUE TITLE
Increasing convergence to ELF by oversampling  moves early in the game?

### ISSUE THREAD

**Issue by csuji** [gcp/leela-zero#1420]
I compared the heatmaps of LZ136 and ELF net on the games in test match http://zero.sjeng.org/match-games/5af357d349f4244893ebd4f3.

Only looking at the starting position it is clear that move selection differs a lot:
![elflz_move0](https://user-images.githubusercontent.com/22214791/39995943-2e1c099c-577e-11e8-9dda-4c0775700043.png)
I plotted the mean abs difference of all heatmaps per move number and it seams that especially in the first ~ 50 moves the differences are especially large:
![heatmap_diff](https://user-images.githubusercontent.com/22214791/39995991-60f38962-577e-11e8-8f67-710d8760f50a.png)
 Would it make sense to oversample the early positions in training to get a faster convergence to ELF style of play?

**Comment by Marcin1960** [comment]
Why would you want that?

**Comment by csuji** [comment]
ELF plays stronger than LZ? And moves early in the game are more important.

**Comment by csuji** [comment]
Well by using ELF games you already "tell" LZ what moves are "good". Only difference of my suggestion is to emphasize opening moves. Regarding "Convergence to something" is not good: as far as I know @gcp would have used ELF net if possible but because of different training pipeline did not do it.

**Comment by gcp** [comment]
There's no way I'm going to do a hack like this for no clear reason or benefit. If we really cared we'd fix the training to support ELF, not do something like this.

**Comment by jkiliani** [comment]
I personally find the ELF policy priors a bit narrow, i.e. its opening style is somewhat monotonous. Hopefully our strategy of mixing the training data and using temperature will give us comparable playing strength to ELF without also adopting its weaknesses (handicap play, only 4-4 opening)

**Comment by gcp** [comment]
Not to mention we are training with T=1 to get away from ELF's rigidity, and this goes in the opposite direction.

Edit: basically what @jkiliani says

**Comment by csuji** [comment]
Hate to say it but 4-4 might be boring but is perhaps best first move:
![screenshot from 2018-05-14 14-51-04](https://user-images.githubusercontent.com/22214791/39998440-62617446-5786-11e8-90f9-5979134e45df.png)
If you want a versatile playing style that is not necessarily the best move use an opening book.

**Comment by roy7** [comment]
I love the fact LZ plays 4-3 and reads out ladders, whereas ELF does neither.

**Comment by herazul** [comment]
>Hate to say it but 4-4 might be boring but is perhaps best first move:

Maybe. Maybe not. Nobody can know that for now, it's impossible.

**Comment by csuji** [comment]
Well I do not see a connection of reading ladders and having to play 4-3  ;)

**Comment by Mardak** [comment]
There's some tracking of a joseki that 192x15 is learning from ELF https://github.com/gcp/leela-zero/issues/1392#issuecomment-388178833

Short story is that 192x15 has learned enough to finish learning the joseki with its own training. The combination with additional ELF means it'll just learn it faster, and that has shown up as a higher prior for each of the additional training steps.

**Comment by csuji** [comment]
Indeed convergence is happening. Did the same calculation for last pre-ELF net LZ130 and compared it to LZ136:
![lz130_136](https://user-images.githubusercontent.com/22214791/40013979-795cd57c-57af-11e8-8768-268a6db2d099.png)
So I am winning anyway ;-)
