### ISSUE TITLE
why lz 20x256 without elf weight is stronger than lz with 30000+ elf

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1422]
https://github.com/gcp/leela-zero/issues/1409

**Comment by jkiliani** [comment]
Why not? It's a larger network so it makes sense it can get stronger at equal visits. ELF data would likely have helped considerably, but it's not surprising that the 256x20 network is stronger than current 192x15 nets. This doesn't currently seem to hold for equal time matches though.

**Comment by gcp** [comment]
The 20x256 nets have always been ahead of the smaller LZ's.
