### ISSUE TITLE
what's wrong here?

### ISSUE THREAD

**Issue by jun63cn** [gcp/leela-zero#1424]
D:\Downloads\leela-zero-579fa66cdd687acdcf436e480a642950534a217c\msvc\x64\Release>leelaz.exe -g -p 2 -w dab.gz --noponder
Using 2 thread(s).
RNG seed: 5135019919352209738
Detecting residual layers...v1...192 channels...15 blocks.
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 9.2.81
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce GTX 1060 3GB
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 397.64
Device speed:  1759 MHz
Device cores:  9 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GTX 1060 3GB
with OpenCL 1.2 capability.

Started OpenCL SGEMM tuner.
Will try 290 valid configurations.
(1/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.1667 ms (707.5 GFLOPS)
(2/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.1434 ms (822.9 GFLOPS)
(4/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.1396 ms (844.7 GFLOPS)
(5/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.1081 ms (1091.0 GFLOPS)
(8/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0946 ms (1246.7 GFLOPS)
(127/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 0.0831 ms (1420.0 GFLOPS)
(137/290) KWG=16 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 0.0775 ms (1521.4 GFLOPS)
(170/290) KWG=16 KWI=8 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 0.0769 ms (1534.6 GFLOPS)
(264/290) KWG=16 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=4 0.0759 ms (1553.8 GFLOPS)
(282/290) KWG=16 KWI=8 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=4 0.0740 ms (1595.0 GFLOPS)
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64
BLAS Core: Prescott

name
= Leela Zero

version
= 0.15

list_commands
= protocol_version
name
version
quit
known_command
list_commands
boardsize
clear_board
komi
play
genmove
showboard
undo
final_score
final_status_list
time_settings
time_left
fixed_handicap
place_free_handicap
set_free_handicap
loadsgf
printsgf
kgs-genmove_cleanup
kgs-time_settings
kgs-game_over
heatmap
lz-analyze
lz-genmove_analyze

genmove b
Thinking at most 36.3 seconds...
NN eval=0.467362

  D4 ->       3 (V: 67.79%) (N: 17.31%) PV: D4 C3
  D3 ->       1 (V: 78.73%) (N: 13.74%) PV: D3
2.2 average depth, 3 max depth
2 non leaf nodes, 2.00 average children
5 visits, 1799 nodes, 3 playouts, 43 n/s

= P?

genmove w
Thinking at most 36.7 seconds...
NN eval=0.225249

  Q4 ->       2 (V: 21.94%) (N: 17.43%) PV: Q4 C16
 D16 ->       1 (V: 22.31%) (N: 15.86%) PV: D16
2.0 average depth, 3 max depth
2 non leaf nodes, 1.50 average children
4 visits, 1436 nodes, 3 playouts, 60 n/s

= P?

**Comment by gcp** [comment]
Did you compile from next? It looks like #1388 broke it.

**Comment by gcp** [comment]
Should be fixed.
