### ISSUE TITLE
Missing separator for lz-analyze

### ISSUE THREAD

**Issue by bittsitt** [gcp/leela-zero#1425]
Commit 9fd7542d puts each move on different lines, but that makes it much harder to parse and maintain results since the client controller/gui doesn't know which results belongs together. Previously it could just throw away the old data, and replace it with the new data (from one line).  Now it has to maintain a list, and search it every time it receives new data to see if it is a new move, or if he just has to update the data of an existing move. This is much more cumbersome and complicated. 

The original Lizzie used a special token (begin/end) to group analysis results, but as you need to maintain some extra state, I put everything on one line to simplify. 

I therefore suggest to revert 9fd7542d.

PS.I assume LZ guarantees that if a move has been searched at least once, it will be maintained so that the doesn't have to check if a move has disappeared (which would be a real pain as you would need some concept of time or something..).

**Comment by gcp** [comment]
This was intentional and according to the proposals in #1388.

> since the client controller/gui doesn't know which results belongs together

Why should "results belong together"? I think this is already betraying some assumptions that might perhaps hold in current LZ, but not in a generic Go engine. 

It's certainly possible to have a design that searches one move at a time, or only transmits updates for one move, i.e. the one it just searched and thus knows to be the only one whose values are changed.

>Now it has to maintain a list, and search it every time it receives new data to see if it is a new move, or if he just has to update the data of an existing move.
>This is much more cumbersome and complicated.

I think that's a reasonable thing to do. Can't you just store the move info in a hashtable?

>PS.I assume LZ guarantees that if a move has been searched at least once, it will be maintained so that the doesn't have to check if a move has disappeared

I think that's going to be true for LZ for now, but to say it's a guarantee? If a move was selected early, got some playouts, and then didn't get any more attention for a few million visits (because it's a self-atari that loses instantly), do you still want to display it?

I think it would be entirely reasonable for the engine to not post search updates for moves it hasn't searched in the last interval, BTW.

**Comment by bittsitt** [comment]
I just think a stateless protocol where neither the client or leela zero needs to remember what has happened before is a lot easier for both parties. "These are the moves I currently consider the best". Finito.

The alternative has some implications:
- Only report those that has been updated => LZ will have to keep track of what has already been reported to the client, or report every time something changes (the latter I suspect could be a lot of data which seems unnecessary(?)). What about initial state? If the engine is busy investigating the second best move, how long will it take before the gui is informed what the best move is?

- Moves disappearing => A move involving a ladder is considered the best move and reported as such. The engine discovers that (*drumroll*) the ladder is unfavourable, and the move drops from being the best to instant loss. At the next "update", it is no longer considered at all by the engine. How do you make sure that the gui is informed that this is a bad move? With commit 9fd7542, you don't. The move just disappears, UNLESS LZ always report on a move that it has previously reported on (which I assume it currently does?).

IF it just disappears, how do you know? Keep track of time somehow and say that if a move hasn't been reported on in n seconds, it was probably a bad move? How do we then choose n? If it is to small, we risk that the best move disappears at regular intervals, if it is to large, we display stale data). (Which is why I wrote that I assumed that a move that has been reported once will be reported again)

If we want a stateful protocol where you only report what is updated, that's fine I guess, but it adds complexity in LZ (as well as in the client). Reporting every change doesn't make sense at it generates a lot more data/overhead than reporting full state every 100 milliseconds (I guess). 

It is not that it is difficult to implement, a hashtable is easy enough, but why add complexity if it doesn't achieve anything?

**Comment by gcp** [comment]
>I just think a stateless protocol where neither the client or leela zero needs to remember what has happened before is a lot easier for both parties. 

I like stateless protocols, but the thing under discussion doesn't add any meaningful state. If the GUI wants to remember what to display, it has to do so, regardless of either choice here. If it doesn't, it doesn't need to, again regardless of either choice. Whether or not the moves arrive as a group or one by one is completely tangential to that.

>LZ will have to keep track of what has already been reported to the client

It wouldn't necessarily have to keep track of anything extra. It depends on the search implementation. One that iterates over the moves one by one would naturally send them one by one. One that has them all available (what we have now) can do either. Note that form the former, sending all moves on every update gets very cumbersome.

>What about initial state? If the engine is busy investigating the second best move, how long will it take before the gui is informed what the best move is?

I'm not sure this question makes any sense. If the engine is not busy with the best move, it won't have anything meaningful to send regardless of whether moves arrive in group or one by one.

>Which is why I wrote that I assumed that a move that has been reported once will be reported again

I think this is a key aspect. Given that this is about the only thing we agree on, I'll tackle that in the next post.

>Reporting every change doesn't make sense at it generates a lot more data/overhead than reporting full state every 100 milliseconds (I guess).

You can do both at once, i.e. not report more than every 100 millis and only report things that change. 

>why add complexity if it doesn't achieve anything?

It avoids complexity in client implementations that aren't exactly like LZ is right now, and it doesn't add any to the GUI.

**Comment by gcp** [comment]
>IF it just disappears, how do you know? Keep track of time somehow and say that if a move hasn't been reported on in n seconds, it was probably a bad move? How do we then choose n? If it is to small, we risk that the best move disappears at regular intervals, if it is to large, we display stale data). (Which is why I wrote that I assumed that a move that has been reported once will be reported again)

By sending all moves on one line, we are adding a grouping. The question is now what that grouping is supposed to convey? It does not currently convey any kind of temporal coherence. Perhaps it could convey "moves the engine still thinks are interesting"? But what does that mean? If we make an early exit (in genmove_* mode) because we see other moves are not contenders, should it only report one move? It does mean hat "this move is not interesting after all" can now be *implicitly* signaled by not sending it any more, rather than having to repeat it every time. But it doesn't seem like much of an advantage, if it is one at all?

If the grouping is "all moves I have ever investigated", then it doesn't seem to convey any additional information to me, and some changes in LZ implementation could mean that remembering this suddenly has to happen explicitly, and we're required to dump all moves even if we only have updates on one. So, complexity for no gain.

**Comment by bittsitt** [comment]
I'll focus on the dropped move first. We might agree completely, I just want to make sure..

> It does mean that "this move is not interesting after all" can now be implicitly signaled by not sending it any more, rather than having to repeat it every time.

I agree on this as long as the gui is informed that the winrate for that move dropped from 60% (making it the "best" move) to 4% at least once. I'm worried about a stream like this:
C4 60%
C5 45%
D4 46%
D3 42%
D4 47%
C5 44%

Somewhere, C4 drops to 4% and is not interesting anymore. How would the gui know? How does the gui know it is not reported anymore? After all, LZ could just be busy analysing other moves? 

If the LZ instead report the drop once, there is no doubt. After that, it doesn't have to report on it anymore. Agreed?

> A problem that we currently don't tackle is that the GUI has no idea which move the engine considers best, BTW.
This is a big one actually. Right now, Lizzie just assumes that the move with most playouts is considered best. I'm not familiar with LZ, but this might not hold true (if it discovers a ladder after 40k playouts, it will take some time for a move with 5k playouts to catch-up)?

Does LZ have a concept of "best move" at all times? If so, it should probably be reported. Replace info with best for the move considered best e.g?

**Comment by jkiliani** [comment]
Maybe Lizzie could use the root PUCT term as a proxy for what LZ currently finds interesting? It can be calculated after all from the root move policy priors, visit counts, and evaluation scores.

**Comment by gcp** [comment]
This requires lizzie to know what the exact formula and coefficients are. And note the top PUCT term is not necessarily the best move, and often far from it.

**Comment by bittsitt** [comment]
I think the order tag is a very good idea. More information is always better if possible.

This also is in favor of the everything on one line approach, as order needs to be consistent.

**Comment by bittsitt** [comment]
Or, we could just sort it (requires grouping of course, but if we include order, grouping is the only thing that makes sense I guess)... 

I am not familiar with the LZ, but after a quick glance, it looks like number of visits is the deciding factor for order? Is that correct? In that case, I could have a quick go at a PR that either sorts or includes order (or both - if you have one, the other I think is trivial).

What was the conclusion on the above discussion? Everything on one line? If we add order, and sort, we could put everything on separate lines, because you will know that you have a new set of data when you see order 1. However, you don't know when there is no more data is, so gui will probably not update the results before he gets the next set of data. Because of this, I prefer everything on one line.

**Comment by gcp** [comment]
I'd put order tags and everything on one line.

>after a quick glance, it looks like number of visits is the deciding factor for order? Is that correct?

Right now, yes.
