### ISSUE TITLE
Do we need to start testing non-SWA weights again?

### ISSUE THREAD

**Issue by kfc51151271** [gcp/leela-zero#1434]
According to gcp, the Dirichlet noise bug was introduced in version 0.13, which was released on March 25. And I notice that the first SWA best network appeared on March 28 (4c7dd084), according to the timeline of the official website http://zero.sjeng.org
Perhaps the reason why non-SWA weights do not perform well is caused by the noise bug? Is this worth a test?

**Comment by jkiliani** [comment]
Can't see what one could possibly have to do with the other. The rate of self-play is already slow enough, without testing additional networks...
