### ISSUE TITLE
Quantized selfplay

### ISSUE THREAD

**Issue by yunxing** [gcp/leela-zero#144]
Hi, just a drive by comment without looking very deep in this project. Have we considered quantized selfplay? This can enable people to contribute via cpu efficiently and can improve training speed in general. I believe this is also what alpha zero did with TPU.

**Comment by yunxing** [comment]
It can also reduce network data needed to download weights.

**Comment by gcp** [comment]
Nobody cares about the bandwidth to download weights, they're tiny and the best network so far only updates once every 1 or 2 days.

**Comment by yunxing** [comment]
I'm talking about mapping a 32 bit weight to 8 bit form so it becomes a fixed point integer number -- CPU will be able to handle integer arithmetics, including convolution, very effectively. 

The tradeoff here is since we are shrinking a 32 bit fp number to a 8 bit integer number, we will loss tons of representability of the number -- the NN becomes less precise in the end. But how a NN behaves in a quantized environment really depends on the model. 

In the alpha-zero paper, they mentioned they were doing self-play on TPUs, and TPU essentially is executing quantized computations (https://arxiv.org/pdf/1704.04760.pdf, search for the work "quantization"). I think that's a good indication that applying the same quantization technique here in self play will work and will save tons of computation resources.
