### ISSUE TITLE
Tracking "Final" 3-3 Point Knight's Move Joseki

### ISSUE THREAD

**Issue by Mardak** [gcp/leela-zero#1442]
I've been tracking in https://github.com/gcp/leela-zero/issues/1392 the progress of networks learning a joseki that was played against ELF network, but the most recently promoted LZ138 played some matches that reminded me of the "final" non-human joseki that was published with AGZ paper:
![screen shot 2018-05-16 at 10 15 25 pm](https://user-images.githubusercontent.com/438537/40157999-f5be5fd4-5956-11e8-9a09-7f9b999d5078.png)

I started with a LZ138 match game http://zero.sjeng.org/viewmatch/880962d5a4947f08188f66b564df638fef3272f3cc0f31088d3c3a561adbf278?viewer=wgo and modified the sgf from move 24 to finish the joseki (with S16) to get the prior numbers for this following graph showing the progress from pre-ELF 192x15 to current 192x15 to ELF:
![screen shot 2018-06-27 at 10 29 04 am](https://user-images.githubusercontent.com/438537/41990233-ac4803c6-79f6-11e8-9103-b89f1775a91e.png)

Basically it looks like the only thing missing from the current 192x15 network is step 12 of the joseki to play S16 instead of the P19 that it did play. Pre-ELF would have preferred N18 for the previous step 11, but now current 192x15 already plays P18 instead. A note about step 9 where the networks all have a lower ~80% prior is that they consider continuing at a different corner instead of finishing top-right.

Looking closer at step 12, it looks like the increases is exclusively from ELF self-play data as the value head for 192x15 currently does not favor searching S16 more:
```
expect: S16, move: 24, who: w, visit: 3200, symmetry: x̄
weight: d8214630
 P19 ->    1480 (V: 55.13%) (N: 30.52%) PV: P19 N18 Q18 N17 S3 S2 N2 S4 N4 O5 O4 S5 O15 Q12 L15 K16 K15 J16
 Q18 ->    1296 (V: 54.70%) (N: 39.16%) PV: Q18 N18 P19 N17 S3 S2 N2 O4 N3 S4 S5 T3 O5 C12 O15 Q12 L15 K16 K15 J16
 O16 ->     272 (V: 54.30%) (N: 10.59%) PV: O16 N17 Q18 N18 O15 S15 T17 M15 S3 S2 N2 O4 N3 S4 S5 T3 O5
 S16 ->     151 (V: 52.27%) (N: 12.56%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14 O15 N16 M16 N15 N14 M15 L15 M14 M13 L14 K14 L13 L12 K13

weight: 224x20
 S16 ->    3103 (V: 53.56%) (N: 96.31%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14 O14 Q12 C3 C4 D3 E4 F2 O15 N15 P15 N16 D11 Q13 P12 R13 Q15 R10 S11 P10 R8 C9 E9 C6
 P19 ->      44 (V: 53.21%) (N:  1.73%) PV: P19 N18 Q18 N17 O15 Q12 R10 Q10 Q9 P10 R11
 O16 ->      26 (V: 53.36%) (N:  0.94%) PV: O16 N17 Q18 N18 O15 M15 S3 S2 P2 S4 R2
 Q18 ->      26 (V: 53.22%) (N:  1.01%) PV: Q18 N18 O16 N17 O15 M15 S3 S2 P2 S4
```

Notice that for 192x15 (d8214630), its search tends to avoid putting more visits (just 5%) into S16, so training data will teach new networks to favor the move less while 224x20 puts almost all visits (97%). I wonder if there's other issues from networks trying to learn from diverging training data… ?

There's some discussion in https://github.com/gcp/leela-zero/issues/1403 for a way to maybe improve the value head faster, but perhaps there's other ways that would help 192x15 learn the joseki by itself sooner?

**Comment by Mardak** [comment]
Here's the recent progress for step 11 P18 and step 12 S16 of promoted networks:
```
expect: P18, move: 23, who: b, visit: 100, symmetry: x̄
128x6    P18 ->       4 (V: 46.39%) (N:  6.41%) PV: P18 Q18 N18 P19
128x10   P18 ->      17 (V: 43.30%) (N: 19.68%) PV: P18 Q18 N18 O16 N17 O15 S15
224x20   P18 ->      88 (V: 45.77%) (N: 87.50%) PV: P18 S16 R18 T17 Q18 S17 N18 O16 N17 R14 O14 Q12 C3 C4 D3 E4 F2 O15 N15 P15 N16 D11 Q13 P12

256V13   P18 ->      54 (V: 45.47%) (N: 51.00%) PV: P18 Q18 N18 O16 N17 O15 S15 T17 M15 S3 S2 N2

ecab83bb P18 ->      45 (V: 45.40%) (N: 42.19%) PV: P18 Q18 N18 O16 N17 O15 S15 P19 M15 O13
3737d7ce P18 ->      49 (V: 45.10%) (N: 46.27%) PV: P18 Q18 N18 O16 N17 O15 S15 T17 M15 S16 Q14
4be6f310 P18 ->      52 (V: 45.61%) (N: 50.26%) PV: P18 Q18 N18 P19 N17 S3 S2 N2 O4 N3
2fb02cfe P18 ->      52 (V: 45.57%) (N: 50.91%) PV: P18 Q18 N18 P19 N17 S3 S2 N2 O4 N3
05b723d0 P18 ->      52 (V: 45.48%) (N: 49.30%) PV: P18 Q18 N18 O16 N17 O15 S15 T17 M15 S16 Q14
b6337c69 P18 ->      50 (V: 45.13%) (N: 46.93%) PV: P18 Q18 N18 O16 N17 O15 S15 T17 M15 S16 Q14
90560d92 P18 ->      54 (V: 44.54%) (N: 52.15%) PV: P18 Q18 N18 O16 N17 O15 S15 T17 M15 S3 S2
d8214630 P18 ->      56 (V: 44.35%) (N: 54.33%) PV: P18 Q18 N18 O16 N17 O15 S15 T17 M15 S3
```
```
expect: S16, move: 24, who: w, visit: 100, symmetry: x̄
128x6    S16 ->      27 (V: 50.77%) (N: 24.11%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14 O15 S3
128x10   S16 ->      18 (V: 55.19%) (N: 14.09%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14 O15 N16
224x20   S16 ->      99 (V: 54.23%) (N: 96.31%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14 O14 Q12 C3 C4 D3 E4 F2 O15 N15 P15 N16 D11 Q13 P12

256V13   S16 ->       4 (V: 52.51%) (N:  4.92%) PV: S16 R18 T17 Q18

ecab83bb S16 ->      10 (V: 54.58%) (N:  9.36%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14 O15
3737d7ce S16 ->      10 (V: 54.92%) (N:  8.28%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14 O15
4be6f310 S16 ->       9 (V: 54.35%) (N:  8.55%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14
2fb02cfe S16 ->       9 (V: 54.41%) (N:  8.20%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14
05b723d0 S16 ->       9 (V: 54.55%) (N:  7.99%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14
b6337c69 S16 ->      10 (V: 54.75%) (N:  8.88%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14 O15
90560d92 S16 ->      11 (V: 56.02%) (N:  9.66%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14 O15 N16
d8214630 S16 ->      13 (V: 55.50%) (N: 12.56%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14 O14 S3
```

I'll update as we get more networks 192x15 or 256x20 or others.

**Comment by csuji** [comment]
Same observation with use of sum of absolute differences of heatmaps to ELF net:
![elf_conv](https://user-images.githubusercontent.com/22214791/40240325-a0312b2e-5ab8-11e8-8788-978f08efbbbc.png)
Especially policy for fuseki moves (move 4) converging to ELF net.

**Comment by carljohanr** [comment]
I think that graph could be really interesting, but it would help with additional annotations. Why does the difference "converge" to 0.25? Is it because the heatmaps are specified differently? Might be nice to normalize. Is this based on one or many games? What does it look like for older networks? How do you explain the oscillations in early middle game? is it because there are many candidate moves, or is it because it is more ambiguous what the right move is?

**Comment by csuji** [comment]
This is a follow up on #1420 Calculation is based on around 400 games  = ~ 100k positions.
All heatmaps are normalized to sum to 1 before calculating the sum of all absolute differences. This is divided by 2. Per move the mean of this differences is calculated (so mean over ~ 400 positions). Difference for empty board is easy to see because heatmaps are static. Bigger differences in the early game are due to preference for different fusekis I would guess (from my observations ELF usually prefers to approach from outside than to invade immediate on 3-3). For later moves it's difficult to interpret because of the averaging. Did not check it but 0.25 difference could be because ELF has a more "complex" heatmaps in the same position because of higher net parameters. In late end game difference converge to 0 because of less number of possible good moves.

**Comment by alreadydone** [comment]
I think these "top ten" selections from AlphaGo Teach could be something people would also be interested to track: https://www.youtube.com/watch?v=UTmBbuald-g https://www.youtube.com/watch?v=tiYq2b2Hcog

**Comment by Tsun-hung** [comment]
The winrate of the moves in AlpaGo Teach is given by master taking 10 minutes per move,I think it's of little value to compare the selections between LZ and master. In contrast, it's a logical choice to observe where LZ  is in finding joseki.

**Comment by Tsun-hung** [comment]
The joseki appear in the latest self-play(057), this is a good sign!
![1](https://user-images.githubusercontent.com/33803485/40484855-810cb886-5f8f-11e8-9c34-c8f754a68936.JPG)

**Comment by alreadydone** [comment]
I checked https://www.youtube.com/watch?v=fk3Mts-hlAI, but neither current LZ nor ELF could find any of the moves, so maybe it's not a good idea. (Max playouts tested were ~36k).
I found a very curious thing though: prior to move 22 in [08.sgf.txt](https://github.com/gcp/leela-zero/files/2087582/08.sgf.txt), ELF thinks the winrate is only 25-30% for white, while AGM thought it's 43.96%, and LZ # 148 thinks it's ~46%. Apparently ELF thinks move 14 is bad and winrate drops below 30% there.

**Comment by Mardak** [comment]
I was thinking of resolving / closing this issue now that 192x15 has all the moves in this joseki as its highest prior move, but doing a extra check on the initially reported issue of value preferring other moves, that still seems to be the case:
```
weight: 12692a83, expect: S16, move: 24, who: w, visit: 3200, symmetry: x̄
 P19 ->    1719 (V: 55.05%) (N: 34.42%) PV: P19 N18 Q18 N17 S3 S2 N2 S4 N4 O5 O4 S5 O15 Q12 F3 C12 C8 E12 L14 C6
 S16 ->     935 (V: 53.63%) (N: 46.29%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14 O14 Q12 C6 O15 N15 P15 N16 C12 Q13 R13 P12 P11 Q11 R12
 Q18 ->     493 (V: 54.61%) (N: 13.70%) PV: Q18 N18 P19 N17 S3 S2 N2 S4 N4 O5 O4 S5 O15 Q12 F3 C12 C8 E12 L14
 O16 ->      55 (V: 53.64%) (N:  2.75%) PV: O16 N17 Q18 N18 O15 M15 Q12 P14 N14 P12 P15 R14
```

This means 192x15 is not in a positive feedback cycle to favor S16 and with ELF games being phased out of the training window, it seems quite likely the network will train to favor P19 instead and avoid playing this joseki.

Although 192x15 value head does seem to be moving in the desired direction to learn the joseki by itself. Compared to when this issue was initially filed, P19 had a win rate of 55.13% and S16 52.27% (where ELF believes those to be around P19 53.21% and S16 53.56%). Now those win rates for the latest 192x15 decreased for P19 to 55.05% and increased for S16 to 53.63%.

**Comment by jokkebk** [comment]
Just a philosophical side thought: it might depend on playing style after opening which joseki ends up as "final" version. I could imagine some form of go AI playing a different type of game than AGZ but even on higher level, and not "finding" this particular joseki.

**Comment by Mardak** [comment]
Looks like at some point, 192x15 learned to have at least a mostly-neutral instead of very-negative feedback cycle for the "critical S16 move 24." In my previous comment, I noted how LZ152 12692a83 would generate training data to prefer P19 instead with S16 prior going from 46% towards 29%.

Here's the search for LZ152 through the newly promoted 256x20 LZ158 using average symmetry and 3200 visits:
```
weight: 12692a83
 P19 ->    1769 (V: 55.06%) (N: 34.42%) PV: P19 N18 Q18 N17 S3 S2 N2 S4 N4 O5 O4 S5 O15 Q12 F3 C12 C8 E12 L14 C6
 S16 ->     911 (V: 53.64%) (N: 46.29%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14 O14 Q12 C6 O15 N15 P15 N16 C12 Q13 R13 P12 P11 Q11 R12
 Q18 ->     465 (V: 54.60%) (N: 13.70%) PV: Q18 N18 P19 N17 S3 S2 N2 S4 N4 O5 O4 S5 O15 Q12 F3 C12 C8 E12 L14
 O16 ->      54 (V: 53.64%) (N:  2.75%) PV: O16 N17 Q18 N18 O15 M15 Q12 P14 N14 P12 P15 R14

weight: e1d466aa
 P19 ->    1645 (V: 54.56%) (N: 33.44%) PV: P19 N18 Q18 N17 S3 S2 N2 S4 N4 O5 O4 S5 O15 Q12 F3 C12 C8 E12 L14 C6 E8
 S16 ->    1088 (V: 53.44%) (N: 49.20%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14 O14 Q12 C6 O15 N15 P15 N16 C12 Q13 C5 D6 F4 C10 S3 S2
 Q18 ->     422 (V: 54.15%) (N: 12.45%) PV: Q18 N18 P19 N17 S3 S2 N2 S4 N4 O5 O4 S5 O15 Q12 F3 C12 C8 E12 L14
 O16 ->      44 (V: 53.30%) (N:  2.13%) PV: O16 N17 Q18 N18 O15 M15 S3 S2 N2 S4 N4 O5

weight: 7ff174e6
 S16 ->    1490 (V: 53.32%) (N: 66.86%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14 O14 Q12 C6 O15 N15 P15 N16 C12 Q13 C5 D6 F4 C10 S3 S2 N2 S4
 P19 ->    1466 (V: 54.62%) (N: 23.67%) PV: P19 N18 Q18 N17 S3 S2 N2 S4 N4 O5 O4 S5 O15 Q12 F3 C12 C8 E12 L14 C6 E8
 Q18 ->     216 (V: 54.04%) (N:  6.25%) PV: Q18 N18 P19 N17 S3 S2 N2 S4 N4 O5 O4 S5 O15 Q12 F3 C12 C8 E12 L14
 O16 ->      27 (V: 53.47%) (N:  1.13%) PV: O16 N17 Q18 N18 O15 M15 Q12 P14 N14 P12

weight: 834f35fa
 S16 ->    1464 (V: 53.64%) (N: 64.07%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14 O14 Q12 C6 O15 N15 P15 N16 C12 Q13 C5 D6 F4 C10 C8 D8 D9
 P19 ->    1441 (V: 54.90%) (N: 23.19%) PV: P19 N18 Q18 N17 S3 S2 N2 S4 N4 O5 O4 S5 F3 C12 O15 Q12 C8 E12 L14 C6 E8
 Q18 ->     259 (V: 54.15%) (N:  8.48%) PV: Q18 N18 P19 N17 S3 S2 N2 S4 N4 O5 O4 S5 O15 Q12 F3 C12 C8 E12 L14
 O16 ->      35 (V: 53.43%) (N:  1.72%) PV: O16 N17 Q18 N18 O15 M15 S3 S2 N2 S4 N4

weight: 050375ce
 S16 ->    1677 (V: 54.13%) (N: 65.62%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14 O14 Q12 C6 O15 N15 P15 N16 C12 Q13 C5 D6 F4 C10 S3 S2 N2 S4
 P19 ->    1299 (V: 55.08%) (N: 23.40%) PV: P19 N18 Q18 N17 S3 S2 N2 S4 N4 O5 O4 S5 O15 Q12 F3 C12 C8 E12 L14 C6 E8
 Q18 ->     194 (V: 54.23%) (N:  7.09%) PV: Q18 N18 P19 N17 S3 S2 N2 S4 N4 O5 O4 S5 O15 Q12 F3 C12 C8 E12 L14
 O16 ->      29 (V: 53.58%) (N:  1.46%) PV: O16 N17 Q18 N18 O15 M15 Q12 P14 N14 P12

weight: d351f06e
 S16 ->    2330 (V: 54.58%) (N: 66.78%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14 O14 S3 S2 N2 S4 N4 O5 O4 S5 F3 C12 C8 E12 C17 C18 D16 E17 G14
 P19 ->     722 (V: 54.37%) (N: 23.43%) PV: P19 N18 Q18 N17 S3 S2 N2 S4 N4 O5 O4 S5 O15 Q12 F3 C12 C8 E12 L14 C6 E8
 Q18 ->     124 (V: 53.61%) (N:  6.19%) PV: Q18 N18 P19 N17 S3 S2 N2 S4 N4 O5 O4 S5 O15 Q12 F3 C12 C8
 O16 ->      23 (V: 53.29%) (N:  1.35%) PV: O16 N17 Q18 N18 O15 M15 S3 S2 N2 S4

weight: dc011d01
 S16 ->    1906 (V: 53.62%) (N: 61.35%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14 O14 Q12 C6 O15 N15 P15 N16 C12 Q13 C5 D6 F4 C10 S3 S2 N2 O4
 P19 ->    1125 (V: 53.89%) (N: 29.27%) PV: P19 N18 Q18 N17 S3 S2 N2 S4 N4 O5 O4 S5 F3 C12 O15 Q12 C9 E12 E9 C6 C5
 Q18 ->     140 (V: 53.30%) (N:  5.52%) PV: Q18 N18 P19 N17 S3 S2 N2 S4 N4 O5 O4 S5 F3 C12 O15 Q12 C9 E12
 O16 ->      28 (V: 53.06%) (N:  1.26%) PV: O16 N17 Q18 N18 O15 M15 S3 S2 N2 S4 N4
```

In fact, the last 192x15 had a positive feedback cycle for the move wanting to increase from 66.78% prior towards 2330/3200 = 72.81%!

The 256x20 with 1600 visits would generate something similar to:
```
 S16 ->     945 (V: 53.37%) (N: 61.35%) PV: S16 R18 T17 Q18 S17 N18 O16 N17 R14 O14 Q12 C6 O15 N15 P15 N16 C12 Q13 C5 D6 F4 C10 S3 S2 N2 O4
```
So towards 59% instead of 61%.. but hopefully this means it will remember to play this "final joseki" for a while.
