### ISSUE TITLE
can amd cpu plus gtx 705 run gpu version leelazero?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1444]
i run autogtp it can download network file but exit immediately after following msg, windows7 64

---

Engine has started.
Infinite thinking time set.

**Comment by genleung** [comment]
I guess what you mean is a GTX750, the answer is YES. You can try to run leelaz.exe in a CMD window, and check what is happening.

**Comment by gcp** [comment]
The GTX 705 also exists and is based on a much older design. I wouldn't count on the drivers being maintained and it's slower than most CPUs.

A GTX 750 should work perfectly. Leela was developed on one!
