### ISSUE TITLE
Is 7.385M set of training based off LZ138 d8214630 instead of LZ139 a39b64cc?

### ISSUE THREAD

**Issue by Mardak** [gcp/leela-zero#1449]
@gcp did the new 7.385M training set use LZ138 (7.360M+128k) as a base instead of LZ139 (7.360M+256k)? From the joseki analysis in #1392, it looks like the prior decreased from LZ139 to 417efd19 (7.385M+32.0k) for some symmetries (**bolded** below), but I would expect most of the training data to increase the priors this particular move 30 A18.

It looks like LZ139 (the +256k of the previous set) was promoted about 1.1 hours after being uploaded, so it's quite possible for the next training set to have missed the promotion.

I suppose even if training did start from LZ138 instead of LZ139, it's not that far behind, and it'll just be ~30 more hours to finish up this set to then switch to LZ139 (unless a LZ140 gets promoted before 7.385M+256k).

symmetry | LZ138 | LZ139 | +32k | +64k
-- | -- | -- | -- | --
0 | 66.04% | 75.72% | **72.95%** | 76.67%
1 | 72.15% | 73.95% | 75.93% | 75.57%
2 | 80.67% | 82.97% | 85.07% | 85.97%
3 | 24.50% | 35.48% | 46.43% | 48.33%
4 | 75.09% | 80.95% | **79.00%** | 82.36%
5 | 64.87% | 75.76% | **71.41%** | 82.60%
6 | 68.10% | 75.45% | 80.71% | 76.36%
7 | 56.50% | 64.16% | 76.07% | 71.83%

**Comment by jkiliani** [comment]
I think this is usually the case if the last network in a training run promotes. The next training cycle can't wait on the decision whether the network will pass or not, so it will simply start training from the previous passing network.

**Comment by Mardak** [comment]
> The next training cycle can't wait on the decision whether the network will pass or not

I agree that the next set should not be blocked on waiting for the +256k match up to finish. But there could be a slight race that could potentially be adjusted to squeeze in a promoted +256k network. From my estimates, each 32k training steps takes about 4.5 hours to train and upload. The very first +32k step takes 5.75 hours from when +256k appears. I'm guessing the extra 1.25 hours is to download the training data from the server and other start-of-set behaviors. (???)

Potentially if the current training cycle is:
1. download best network
2. download training data
3. apply training and upload network for desired batches
4. repeat from step 1

Flipping steps 1 and 2 could allow a fast-passing +256k network to be used right away for the next training set.

**Comment by gcp** [comment]
It already works this way.

**Comment by gcp** [comment]
I don't know what the new networks are based off, generally speaking, unless it happens to be in the scrollback logs.

In this case: ```best network: a39b64cced7224e29565ef9b0745eabd3a501571a58249d4a790d4fdb0b01af8```

**Comment by Mardak** [comment]
Okay sounds good. It looks like LZ139 promoted in 1.1 hours this time faster than the 1.25 hours before the usual 4.5 hours of 32k training. But as noted earlier, in general, there isn't much we should do to specially wait longer just in case +256k might promote.
