### ISSUE TITLE
Ask for help about configure of bot on COGS

### ISSUE THREAD

**Issue by Tsun-hung** [gcp/leela-zero#1451]
I know LZ doesn't have option such as `--no-early-pass`, she will play "pass" when she thinks the game is over.I note a bot(LZ_b6337c69_p1600) on CGOS plays meaningless moves when games come to the end.

http://www.yss-aya.com/cgos/viewer.cgi?19x19/SGF/2018/05/18/426612.sgf
http://www.yss-aya.com/cgos/viewer.cgi?19x19/SGF/2018/05/18/426517.sgf

I am a green hand at configuring for starting the game on CGOS, searching the introductions but no gain. I suppose there are some arguments(e.g. never pass unless time out ) could be used in the configure file. **Could anyone tell me?**

**Comment by Cabu** [comment]
Probably because of --resignpct 0

**Comment by Tsun-hung** [comment]
> Probably because of --resignpct 0

Nope. I have test the arg but not implement.

**Comment by Mardak** [comment]
> http://www.yss-aya.com/cgos/viewer.cgi?19x19/SGF/2018/05/18/426612.sgf

Checking the game with the same b6337c69 network, all symmetries have the top move as pass with everything else much lower:
```
expect: pass, move: 270, who: w, weight: b6337c69, visit: 3200
pass ->    1858 (V: 100.00%) (N: 36.17%) PV: pass 
 L14 ->      60 (V: 100.00%) (N:  1.19%) PV: L14 pass pass
 L15 ->      47 (V: 100.00%) (N:  0.92%) PV: L15 pass pass
…
```

Similarly @bood linked to a game in https://github.com/gcp/leela-zero/issues/1446#issuecomment-390230649
> http://www.yss-aya.com/cgos/viewer.cgi?19x19/SGF/2018/05/18/426628.sgf

```
expect: pass, move: 285, who: b, weight: b6337c69, visit: 3200
pass ->     396 (V: 100.00%) (N: 11.34%) PV: pass 
 B17 ->     155 (V: 99.98%) (N:  4.52%) PV: B17 pass A16 pass A18 pass B19 pass A19 pass C19
 A17 ->     147 (V: 100.00%) (N:  4.24%) PV: A17 pass A19 pass C19 pass pass
 E12 ->     126 (V: 100.00%) (N:  3.61%) PV: E12 pass pass
```

So the network knows to pass. I'm not sure what configuration you can set to turn off passing though…

**Comment by Tsun-hung** [comment]
> So the network knows to pass. I'm not sure what configuration you can set to turn off passing though…

Yes, I feel confused

**Comment by Mardak** [comment]
@Tsun-hung are you running that bot? What's the command line arguments you're running with?

**Comment by Tsun-hung** [comment]
@Mardak  Not me. I run another one to test the timemanagement, the invoke is the same as usually.

**Comment by gcp** [comment]
You need to send ```kgs-genmove_cleanup``` instead of ```genmove``` when playing on CGOS if you want to remove all dead stones.

I would think that the default, i.e. with dumbpass disabled, also should not pass early: https://github.com/gcp/leela-zero/blob/9e903eda6e93fb65375ea03127e4f62268913175/src/UCTSearch.cpp#L386

It might leave dead stones, but never enough to change the winner of the game.

**Comment by Tsun-hung** [comment]
@gcp Yes, -d oppotion makes no mistake. But I don't know how to send the command for the autocontrol after the bat is runned.The sample of configure file is as follow:
sample of config.txt
```
#--------------------------------------------------------
# config file
# Bot name must be within 18 characters.
# Port is 6809 in 9x9, 6819 in 19x19.
# -------------------------------------------------

%section server
    server yss-aya.com
    port 6809

%section player
     name      GnuGoTest
     password  xxxxxxxx
     invoke    gnugo.exe --mode gtp --capture-all-dead --chinese-rules --positional-superko
     priority  7
#---------------------------------------------------------
```
The arg of my bot is `-g --noponder -r 0 -d -w network -l log` in invoke line, unable to set initial command arg
