### ISSUE TITLE
At least 10 of 253 lz139 vs a625 games, whose first 30 moves are identical?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1453]
http://zero.sjeng.org/viewmatch/3e72a1627da97c220cad8efda6f7e43fa5d1b9de24f0ae425867dce8131a97bc.sgf

http://zero.sjeng.org/viewmatch/1ebd49fa3f0264aeb756f60f0cf02fe88cc4a60405f17ee0839449b59c7d9b42.sgf

I saw the options was " -p 0 -v 3200 -r 5 -m 0 -t 1 -d --noponder -s 8991203097250361990 -g -q -w networks/a39b64cced7224e29565ef9b0745eabd3a501571a58249d4a790d4fdb0b01af8",  so there is no random moves but has noise, 
why the noise dosen't take effect in so many moves?

**Comment by l1t1** [comment]
and more http://zero.sjeng.org/viewmatch/ce5ed0552633c50c9b34ba107c9428ea935d6688997d7915491a3dc016845703.sgf
I saw these all by changes, if one can program to find all Symmetrical situation, the proportion shoud higher.

**Comment by l1t1** [comment]
and these games of match lz138 vs lz137

http://zero.sjeng.org/viewmatch/297b1d075e001f1447f7dbd251e8377d064693c63c7e49de36115442e6814778.sgf

http://zero.sjeng.org/viewmatch/4f023c59273b49322fef95a28b1421f93cf719d5c596794c869454620f2dbd6d.sgf
are also identical?

should we ***introduce some random in match***?

**Comment by WYVYW** [comment]
A match has another function as a self-play game.

**Comment by marcocalignano** [comment]
Absolutely not! The matches are done to learn which network is better. If they play the same moves then they are the same strength! Plus the first 30 moves are usually open moves and joseki and since our networks are really similar it is very likely that these moves are the same. If you look at professional games probably you found also a lot of games that are the same in the first 30 moves especially from players that have the same style of playing.

**Comment by alreadydone** [comment]
Matches don't have Dirichlet noise at root either. You need `-n` for that.

**Comment by l1t1** [comment]
rotate oard is helpful to slove this  https://github.com/gcp/leela-zero/pull/1421

**Comment by l1t1** [comment]
and lz140 also learn the joseki
http://zero.sjeng.org/viewmatch/2b11cc9b72a66890be5f9cb0884e20393af94804c79b71ebc91e1900f7d6fc39.sgf
http://zero.sjeng.org/viewmatch/fb274e91461479a9e9d1ea5f7324ee924f67acee8b93418c78f7e2dc38fc9319.sgf
http://zero.sjeng.org/viewmatch/516a292081d5184a96c824e5c3707e8f82ec0547a1e640ac24ec21a6f59dbab1.sgf

these games are all win by points.

**Comment by l1t1** [comment]
find the minimal string sgf
```
#include<cstdio>
#include<cstring>
char a[4000]="x";
char b[4000]="x";
char minb[4000]="x";
int sz=19; //19
char t[3]="";
char fn[100]="";
int main(int argc, char* argv[])
{
    FILE *fi,*fo;
    fi=fopen(argv[1],"rb");
    int c=fread(a,sizeof(char),3999,fi);
    memcpy(minb,a,c);
    fclose(fi);
    char x,y,x2,y2;
    for(int r=1; r<=7; r++) //find the minimal
    {
        int j=0; //b pos
        for(int i=0; i<c; i++)
        {
            if(a[i]==';' && (a[i+1]=='B'|| a[i+1]=='W') && a[i+2]=='[')
            {
                x=a[i+3],y=a[i+4];
                memcpy(b+j,a+i,3),j+=3;
                t[0]=x,t[1]=y;

                switch(r)
                {
                case 1: //up-down
                    x2=x,y2=sz-(y-'a')+'a'-1; //ok
                    break;
                case 2: //left-right
                    x2=sz-(x-'a')+'a'-1,y2=y; //ok
                    break;
                case 3:  //rotate a-clock 90
                    x2=y,y2=sz-(x-'a')+'a'-1;
                    break;
                case 4:  //rotate a-clock 180
                    x2=sz-(x-'a')+'a'-1,y2=sz-(y-'a')+'a'-1;
                    break;
                case 5:  //rotate clock 90
                    x2=sz-(y-'a')+'a'-1,y2=x;
                    break;
                case 6:  //rotate by line 135
                    x2=y,y2=x;
                    break;
                case 7:  //rotate by line 45
                    x2=sz-(y-'a')+'a'-1,y2=sz-(x-'a')+'a'-1;
                    break;
                }
                if(t[0]<'t')
                    t[0]=x2,t[1]=y2;

                memcpy(b+j,t,2),j+=2;

                i+=5;
                memcpy(b+j,a+i,1),j+=1;
            }
            else
                memcpy(b+j,a+i,1),j+=1;
        }
        if(strcmp(b,minb)<0)
            memcpy(minb,b,c);
    }
    sprintf(fn,"%s_min.sgf",argv[1]);
    fo=fopen(fn,"wb");
    fwrite(minb,sizeof(char),c,fo);
    fclose(fo);
    printf("%d\n",c);
}
```

**Comment by l1t1** [comment]
if the opening do has very few petterns, why not send client a random opening sgf and start game in the mid to save time, since match game is not use for training ? @gcp

**Comment by l1t1** [comment]
if we focus on the win games of lz 141 vs elf, can we use it to enforce the learning of lz?
