### ISSUE TITLE
a question in int SGFTree::string_to_vertex function?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1456]
```  
 if (c1 >= 'A' && c1 <= 'Z') {
        cc1 = 26 + c1 - 'A';
    } else {
        cc1 = c1 - 'a';
    }
    if (c2 >= 'A' && c2 <= 'Z') {
        cc2 = bsize - 26 - (c2 - 'A') - 1;
    } else {
        cc2 = bsize - (c2 - 'a') - 1;
    }
    // catch illegal SGF
    if (cc1 < 0 || cc1 >= bsize
        || cc2 < 0 || cc2 >= bsize) {
        throw std::runtime_error("Illegal SGF move");
    }
```
if c1 is a upper letter, cc1 always between 26 and 52, it seems wrong.
I run loadsgf command with a simple file as following

(;GM[1]FF[4]CA[UTF-8]AP[Sabaki:0.31.4]KM[6.5]SZ[19]PB[leela14]
;B[DD]
;W[dp]
;B[pp]
;W[pd]
;B[cq]
;W[cc]
;B[dq]
;W[dc]
;B[ep]
)
it shows
```Leela: loadsgf sga/s1.sgf
? cannot load file
```
if i modify ;B[DD] to ;B[dd], it works fine.

I lookup https://www.red-bean.com/sgf/user_guide/index.html, and did not find anyting about upper letter of move.

**Comment by sheeryjay** [comment]
Everything works as it should. What you linked is just a sgf user guide.

The specification is at https://www.red-bean.com/sgf/index.html and the relevant part is https://www.red-bean.com/sgf/go.html - go moves are defined using board moves up to 52 size and in case of >26 then it uses uppercase letter.

LZ parsing in SGFTree is correct in refusing your move B[DD] which would be on 30th intersection which is impossible on 19x19 board (defined by SZ[19]).

**Comment by l1t1** [comment]
thanks @sheeryjay
