### ISSUE TITLE
Question about engine arguments

### ISSUE THREAD

**Issue by Hayden2018** [gcp/leela-zero#1457]
I am new to Leelazero (And Github as well) I am currently using the following arguments on Sabaki:
-g --noponder --playout 1000 -t2 -w elf_converted_weights

I copy them some where from the web with little idea what it means. I can see that -w stands for weights and --playout stands for playput per move.

But are there any arguments that can disable engine resignation or set time limit per move?
Are there a full list of arguments that I can use out there?

**Comment by Tsun-hung** [comment]
Run ./leelaz.exe -h to get the help infromation

**Comment by alreadydone** [comment]
and refer to GTP documentation for time_settings.

**Comment by Hayden2018** [comment]
I got it now. Thanks!
