### ISSUE TITLE
Do cases matter where one color wins with Tromp-Taylor but would lose with almost every other rule set?

### ISSUE THREAD

**Issue by SharlatanY** [gcp/leela-zero#146]
I assume it's not a problem in the grand scheme of things because it won't happen too often and white passing was a very bad move anyway.

But is there a chance this could become some kind of problem? The scoring in this peculiar case is a correct Tromp-Taylor counting but in this case, the result is way off the real count and it's actually a game that white would have won "in the real world": http://go.ba.net/playgo/go.html?sgf=3PhVZestM.sgf

If anyone wants to look at the original game, it's 7fe63aef36c94b56b97af613c77fbd31.sgf

**Comment by gcp** [comment]
According to the AGZ paper "every other rule set" doesn't have solid rules for scoring such positions so that makes the issue immediately moot.
Even if that were false it is no longer applicable once the program learns what territory is.

**Comment by SharlatanY** [comment]
I see! Thanks for the inisght! Really didn't know that (as well as the thing about the file name, obviously.

Thanks for all your hard work, by the way!

**Comment by Dorus** [comment]
The game you linked refers to a game where black plays 1 random stone, and then both players pass.

Both in Japanese and Chinese rules, black would win that game by over 350 points. Black has 1 living group and white has none, blacks group surround 360 empty area, so under area scoring that would be 361 points - komi. Under Territory scoring that would be 360 points - komi.

As far as i know, Tromp-Taylor scoring is identical to Chinese (area) scoring, as long as you bother to remove all dead stones.

**Comment by SharlatanY** [comment]
Hm, you might be right. I did some additional googling and I unfortunatelly couldn't find a clear definition for what counts as "surrounding" in Japanese/Chinese rules in such unusual cases. My gutfeeling told me (didn't even really consider the question at that point in time, I have to admit). That you can't surround something by playing just at one single point, because well.. 1 point is just that, a point and not a geometrical shape, which would be needed for a border. Ok, you could argue that "all the edges" are your borders but can you surround something by playing in the middle of it?

Anyway, it doesn't matter and unfortunately I didn't find any specific rules for this situation. If they are written down somewhere and I haven't found them, I'm sorry.

**Comment by Dorus** [comment]
Well the thing is, this only works on an empty board. As soon as white also plays a move, every point on the board will be connected to both a white and black stone(s), so they are considered neutral. After that you need at least 2, 3 or 4 stones to surround territory (in the corner, edge, or middle of the board respectively). However, you are still allowed to use the edge of the board to surround your territory, it is never required to fill the edge so that all territory is only surrounded by your stones.
