### ISSUE TITLE
how can I install autogtp on OS X?

### ISSUE THREAD

**Issue by elensar92** [gcp/leela-zero#1460]
fatal error:
      'QString' file not found
#include <QString>

->

I already installed qt5.9 library using Port.

leelaz work well.  when I tried to build autogtp
I can show the error message. 

when I made "build" directory on ~/autogtp and try "cmake .." 
Also this meesage was shown.

-- Generating done
-- Build files have been written to: /Users/cenovis/Desktop/leela-zero-0.15/autogtp
Cenoviss-MacBook-Pro:build cenovis$ cmake ..
-- Configuring done
CMake Error at CMakeLists.txt:4 (add_executable):
  Target "autogtp" links to target "Qt5::Core" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

**Comment by Mardak** [comment]
There were some updated mac instructions here:
https://github.com/gcp/leela-zero/pull/1415/files

This seems to work for me:
```
$ cd autogtp
$ /usr/local/opt/qt/bin/qmake
$ make
$ ln -s ../src/leelaz
$ ./autogtp
```

**Comment by elensar92** [comment]
@Mardak Thx for your reply. lt works well
