### ISSUE TITLE
Question regarding the resign threshold and winrate calculation during self-play

### ISSUE THREAD

**Issue by Splee99** [gcp/leela-zero#1463]
I'm not sure how the self-play games are stored, but I have downloaded the html file for the self-play game generated on my computer with the ELF weight. The training game ID is b1a376cf243ef5c75b51ed54ad493d81a6502460e2c2d04e03094fb0a24e9f56.
It finished by black resign after move 122. However when I loaded the game and analyzed the game with ELF weight the winrate was 35%. I know the resign threshold is 5%. So my question is, could winrate be so much different than during the actual selfplay when you load a sgf file?

**Comment by roy7** [comment]
Here's the game in question until it's swept out of database to the training server. :)

http://zero.sjeng.org/view/b1a376cf243ef5c75b51ed54ad493d81a6502460e2c2d04e03094fb0a24e9f56?viewer=wgo

**Comment by Mardak** [comment]
Different symmetries will lead to different win rates, but they all do seem to be closer to 35% than 5%…

Here's the sgf:
```
(;GM[1]FF[4]RU[Chinese]DT[2018-05-20]SZ[19]KM[7.5]PB[Leela Zero 0.15 62b5417b]PW[Leela Zero 0.15 62b5417b]RE[W+Resign]C[Leela Zero options: -p 0 -v 3201 -r 5 -m 999 -t 1 -d -n --noponder -s 4352098325433026605 -g -q -w networks/62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9];B[dd];W[dp];B[pp];W[pd];B[cn];W[fq];B[nc];W[qf];B[pc];W[qc];B[qb];W[oc];B[pb];W[od];B[ob];W[qq];B[qp];W[pq];B[nq];W[oq];B[op];W[nr];B[nd];W[qi];B[pg];W[qg];B[fc];W[np];B[mq];W[mr];B[lq];W[no];B[rq];W[rr];B[qr];W[rp];B[or];W[sq];B[pr];W[rq];B[lr];W[pn];B[pi];W[co];B[oh];W[gd];B[qj];W[ri];B[pm];W[rc];B[dn];W[gc];B[qd];W[rd];B[fd];W[jc];B[kc];W[kb];B[lc];W[lb];B[oe];W[pe];B[pf];W[qe];B[mb];W[fe];B[ge];W[fb];B[eb];W[gb];B[jd];W[id];B[ic];W[he];B[jb];W[gf];B[df];W[ch];B[cj];W[eg];B[cb];W[ei];B[ef];W[fg];B[qn];W[qo];B[on];W[oo];B[po];W[pn];B[hq];W[bn];B[bm];W[bo];B[ek];W[nn];B[po];W[nl];B[ok];W[bf];B[be];W[fo];B[eo];W[iq];B[hp];W[hr];B[gr];W[jr];B[gq];W[fp];B[jo];W[kp];B[lo];W[ip];B[io];W[ho];B[fr];W[lp];B[jp];W[kq];B[jq];W[kr])
```

Here's checking symmetries for move 123, and none are close to resigning:
```
0:  J2 ->    2620 (V: 30.90%) (N: 45.64%) PV: J2 N4 D2 E6 E7 F6 J14 D5 J12 J15 K15 C14 C15 B11 B10 O9 N10 O10 O11 L10
1:  J2 ->    2996 (V: 33.56%) (N: 52.35%) PV: J2 N4 D2 E6 E7 F6 J14 J15 K14 D5 C8 C14 C15 B11 B10 O9 B3 C3
2:  J2 ->    2423 (V: 33.82%) (N: 51.63%) PV: J2 N4 D2 E7 E6 D3 C2 F6 F7 F8 G7 E8 C8 D9 B12 H6 H7 J6 H9 G9 C13 C11 B11 C9 B9 D10 B10 J8 J7 K7 H8 K6
3:  J2 ->    3145 (V: 37.14%) (N: 64.08%) PV: J2 N4 D2 E7 E6 D3 C2 F6 F7 F8 G7 E8 C8 D9 B12 H6 H7 J6 H9 G9 C13 C11 B11 C9 B9 D10 B10 K8 J10 K10 G10 K11
4:  J2 ->    2834 (V: 33.21%) (N: 69.23%) PV: J2 N4 D2 E7 E6 D3 C2 F6 F7 F8 G7 E8 C8 D9 B12 H6 G8 F9 J8 B11 C11 B13 D12
5:  J2 ->    3078 (V: 32.59%) (N: 41.22%) PV: J2 L5 D2 E7 O1 R1 E6 D3 C2 F6 F7 F8 G7 E8 C8 D9 B12 H6 D12 J8 D11 D10 D13 K12
6:  J2 ->    2700 (V: 31.98%) (N: 55.28%) PV: J2 N4 D2 E6 E7 F6 J14 C3 J12 J15 K15 O9 B13 B12 C14 H11 C8
7:  J2 ->    1934 (V: 38.36%) (N: 61.28%) PV: J2 N4 D2 E7 E6 D3 C2 F6 F7 F8 G7 E8 C8 D9 B12 H6 H7 J6 H9 G9 G10 F10 C13 C11 B11 C9 B9 D10
```

So something does seem to be wrong… ?

**Comment by gcp** [comment]
Resignation is calculated on the move *chosen*, not the best move from the search. So what happened is that t=1 selected a blunder, and the engine resigned before actually playing it.

This is more or less working as designed.

**Comment by Mardak** [comment]
Ah, resigning based on the randomly selected move would explain things. Here's the moves (excluding 95 two-visit and 144 one-visit moves) from symmetry 0:
```
  J2 ->    2620 (V: 30.90%) (N: 45.64%) PV: J2 N4 D2 E6 E7 F6 J14 D5 J12 J15 K15 C14 C15 B11 B10 O9 N10 O10 O11 L10
  O1 ->      51 (V: 10.63%) (N: 24.62%) PV: O1 J2 G5 H6 G6 H7 D3 C3 D2 E4 C2 E7 G7
  N6 ->       6 (V:  1.25%) (N:  4.55%) PV: N6 J2 G5 H6
  M1 ->       5 (V:  4.60%) (N:  3.22%) PV: M1 J2 N4 L5
  R4 ->       5 (V:  0.72%) (N:  4.01%) PV: R4 J2 G5 H6
  D2 ->       3 (V:  9.49%) (N:  1.72%) PV: D2 D3 J2
  N1 ->       3 (V:  4.96%) (N:  1.99%) PV: N1 J2 G5
  C8 ->       3 (V:  3.60%) (N:  2.03%) PV: C8 J2 G5
 J11 ->       3 (V:  2.05%) (N:  2.18%) PV: J11 J2 G5
```

In this case, with T=1, would have picked a move with under 5% win rate with 215 / 3200 probability = ~7%.

**Comment by Splee99** [comment]
Thanks for answering my question. If. Lz chooses random moves I can imagine it may have trouble learning the situation when there's only one winning move, such as ladder, punishing self Atari, etc. Sorry can't resist to make this comment.

**Comment by Mardak** [comment]
The training data from self-play contains more than just the played move. From the searched moves list I provided in the previous comment, J2 was visited 2620 times out of 3200 when its prior indicated that same move should be searched with 45.64% probability. The training data from this game could teach the network that it should have a prior probability closer to 2620/3200 = 81.88%.

Similarly, for one-winning move positions, even if T=1 causes the wrong move to be played in the sgf, the training data would likely have a lot of visits go in to the expected one move assuming the network correctly evaluates the win rate of the move. So when the network is trained and played in a match game, it'll know to play that one move if in a similar position.
