### ISSUE TITLE
How to force a move (for code testing).

### ISSUE THREAD

**Issue by Marcin1960** [gcp/leela-zero#1465]
What is the simplest way to force LZ to make a move (a line or couple in the code?) like for example "move D11"

**Comment by l1t1** [comment]
play b d11?

**Comment by genleung** [comment]
You should talk to the Go engine(leelaz -g) via the GTP protocol's interface which is normally implemented by the standard input and output file descriptor of the engine's process.

**Comment by Marcin1960** [comment]
@genleung 

I mean directly from the code in certain concrete situations "if something == 1234 than move D11"

**Comment by d7urban** [comment]
I think he’s looking for a way to tell the engine to stop thinking and make
a move NOW.

**Comment by Marcin1960** [comment]
@d7urban

A specific dynamically defined move.

**Comment by genleung** [comment]
@Marcin1960 What I was talking about is the basic idea of 'talking to the engine' in your code. If you are using Linux, the detailed procedure could be like this:
> 1. Use socketpair() to create a socket pair, say fd[0] & fd[1]
> 2. fork() a new process for the GTP engine
> 3. Use dup2() to redirect the GTP engine process's stdin & stdout to one of the fd[0..1]
> 4. Use execv() to replace the current process image to GTP engine's, and run.
> 5. Now, you can send your GTP  command to  the engine from your code by simply write to the fd[0..1]

**Comment by Marcin1960** [comment]
@genleung 

I have my kludgy way to 'talking to the engine'. My question how to say in the code "place stone at D11, now"

**Comment by TFiFiE** [comment]
What about any of the following member functions of `GameState`?
https://github.com/gcp/leela-zero/blob/8daa7e76e7c2961c045ad2413f883db8acc56855/src/GameState.h#L51-L54

**Comment by gcp** [comment]
Just look at the code that implements the "play" command: https://github.com/gcp/leela-zero/blob/9e903eda6e93fb65375ea03127e4f62268913175/src/GTP.cpp#L321

which calls game.play_textmove(color, vertex)

**Comment by Marcin1960** [comment]
@gcp 

Thanx a lot

**Comment by Marcin1960** [comment]
Similar question. How to order engine to make an alternative move.

Let us say, the engine wants to play x,y and you order engine to pick NEXT best move.

Engine: play x,y?
You: no, play next best x2,y2 !

**Comment by roy7** [comment]
This happens at https://github.com/gcp/leela-zero/blob/8daa7e76e7c2961c045ad2413f883db8acc56855/src/UCTSearch.cpp#L354. You can see later in the functional how noise can cause a different sort. To choose 2nd best moves, you'd need to take the 2nd move in the list if it's a valid move instead of the first move. Keep in mind in forced move situations, the first move might get virtually all of the search.
