### ISSUE TITLE
A client generated a lot of games with unexpected seeds

### ISSUE THREAD

**Issue by Mardak** [gcp/leela-zero#1466]
I happened to load the http://zero.sjeng.org/self-plays page to see a lot of "???" duration games, and almost all of them were from a single client. This client had submitted 202 out of 400 recent games. And of those 202, 35 had "???" started/durations.

A quick glance at the ??? sgf files shows seeds with values like 688149150 and 3940164525. Whereas the same client's non-??? games had seeds like 2426559199808005554 and 5132477179988485684.

The client must have requested the games relatively recently as it used LZ141 11057dd7.

Client | Version | Self-Play Hash | Network | Move Count | Winner | Started | Duration
-- | -- | -- | -- | -- | -- | -- | --
3 | 16 | bd78c814ea1850f74d80910dd8446e82af74526375f86dd7e7720e01785d7088 | 11057dd7 | 662 | white | 201.6 minutes ago | 169.4 minutes
3 | 16 | bf9db6bf72ab72bbd679382b1092123cb7474dc4f77d55dedd8169ffe4ef0bf9 | 11057dd7 | 93 | white | 30.7 minutes ago | 8.4 minutes
3 | 16 | b9e8b22d8eadffcc31a18413c2958354b825a4e225dfa9c14204cd3566837fc4 | 11057dd7 | 93 | white | ??? | ???
3 | 16 | be6c33eacd6da52a36bed1ef1e7a6b26e2a77b5cf92376cc9cb7550c2a55d49e | 11057dd7 | 96 | black | ??? | ???

**Comment by gcp** [comment]
What feature determines the ??? duration? Could this be saved/resumed games? Is storing the seeds there broken?

**Comment by roy7** [comment]
I believe this client ID is @alreadydone. Maybe he hadn't upgraded the client before sending in a fresh batch if he's been away for a bit?

**Comment by Mardak** [comment]
Okay, that would explain the high number of games, and he does have some custom code to run so many distributed games. The ??? is not really a big issue as the server would use the timestamp information to determine fast-turnaround clients to potentially direct match games, but this cluster won't be playing match games anyway with a hardcoded `get-task/0` request.

**Comment by alreadydone** [comment]
I think those seeds were more likely generated by the client when connection to server failed.

**Comment by Mardak** [comment]
Ah indeed:
https://github.com/gcp/leela-zero/blob/9e903eda6e93fb65375ea03127e4f62268913175/autogtp/Management.cpp#L458

In any case, the server doesn't currently do anything differently because the seed is different, but good to be aware of this possibility.
