### ISSUE TITLE
it looks weight 3ef8 (142+) forget avoid ladder at game vs PhoenixG

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1476]
weight http://zero.sjeng.org/networks/3ef8222750fef4625c9558ad40ea05ce7366f844b3cd80ec2b37ec122ab6863d.gz

gogui command 
```
gogui-twogtp.exe -black "D:\tool\valid14\leelaz.exe -g -w D:\tool\valid14\3ef8" -white  "D:\tool\PhoenixGo\bin\mcts_main.exe --config_path=D:\tool\PhoenixGo\etc\mcts_cpu.conf --gtp --log_dir=D:\tool\PhoenixGo\log --v=1" -auto -sgffile lz_pg -komi 7.5 -games 10
```
the sgf file
[lz_pg_sgf.zip](https://github.com/gcp/leela-zero/files/2034241/lz_pg_sgf.zip)

in game 2,6,7,8 they played a very long ladder, and in some games (eg, game 2), ladder is not acceptable, but the PhoenixGo regisned

**Comment by ThorAvaTahr** [comment]
game 2 is correct resign for Phoenix, at the end the ladder is bent to the side and black (leelaz) wins it.

**Comment by ThorAvaTahr** [comment]
All the ladder's are correct. It seems LeelaZ has some strength in dealing with long ladders and is playing them when they work.

**Comment by l1t1** [comment]
![ladd2](https://user-images.githubusercontent.com/23301704/40471872-8536db82-5f6a-11e8-89ee-b80978d5c97d.png)

I contiute play game 2 , and white 120 capture black 115, what's wrong with me? @ThorAvaTahr

**Comment by fohristiwhirl** [comment]
117 should be at 118.

**Comment by l1t1** [comment]
@fohristiwhirl thanks
