### ISSUE TITLE
Aiming at winning with small margin

### ISSUE THREAD

**Issue by DonMathi** [gcp/leela-zero#1485]
Some of the training games with 0% resign level look strange, because it simply continues to play. And it even fill in own eye making leving group dead. But since I know how the scoring is setup I know this is what the computer is supposed to do.

That lead me to think if the aiming of scoring could be done differently. Instead of aiming at winning with a small margin, then aim at achieving a position with a scoring higher than the current.

So if the computer should instead try to shift its current position to a position with a better score. So even if the computer is winning with 100 point it should try to win with 101 points.

Maybe this could eliminate the strange behaviour filling own eyes.

What do you think?

**Comment by PhilipFRipper** [comment]
You can do this but it has been shown to make the engine much weaker.
