### ISSUE TITLE
Please consider donating some money to make LZ stronger

### ISSUE THREAD

**Issue by zhanzhenzhen** [gcp/leela-zero#1487]
Hi everybody! I'm the author of [wei7.com](https://wei7.com/). Yesterday I added a feature of running autogtp in the server background so it can be used for training. This is the screenshot:

![github-wei7-donate](https://user-images.githubusercontent.com/731796/40622836-13bcb1ec-62d6-11e8-8187-f003bed51856.png)

I'm still not sure how to maintain this website (by donating or by making some features paid). Currently it's totally free. Your donation will be used solely for purchasing GPU spot instances on AWS. Anyone interested?

**Comment by gcp** [comment]
I don't think this is appropriate here.

**Comment by zhanzhenzhen** [comment]
Sorry. OK. Since there're very few people interested, I've removed this feature.
