### ISSUE TITLE
Error when running on windows

### ISSUE THREAD

**Issue by GaijinFizz** [gcp/leela-zero#149]
Hi, I get the following error: https://imagebin.ca/v/3iEbcLvSqa5W

**Comment by dongcijie** [comment]
Because your graphics card （GPU） doesn't support OpenCL 1.2

**Comment by qysnn** [comment]
Maybe it is better to provide more user-friendly error message indicates the GPU doesn't meet the requirement instead of just have the leelaz crash.

**Comment by gcp** [comment]
If the program crashes, it has no way to indicate an error message, does it? If the OpenCL support is insufficient, it will exit. But if the drivers are so broken they crash instantly, nothing can be done.

**Comment by GaijinFizz** [comment]
Hi, I installed OpenCl and it did solve the problem. Thanks

**Comment by qysnn** [comment]
Frankly I have no experience in OpenCL programming so I don't know whether it's possible to catch and handle the error that causes the crash or not. What I am trying to say is that if we can provide more information to users when there is an error we can help them better in locating and solving their problems.

**Comment by gcp** [comment]
The crash dialog comes from Windows, not Leela. Leela isn't crashing intentionally, it will handle OpenCL errors and display the error message. I'm saying this is likely a crash in the OpenCL driver which it can do nothing about, let alone report an error. Or else some error handling was missed, but that can't really be told from the image.
