### ISSUE TITLE
Strange winrate for lost game

### ISSUE THREAD

**Issue by petgo3** [gcp/leela-zero#1493]
This is a game lz 0.15 vs. elf on KGS:

[petgo3-ELF.zip](https://github.com/gcp/leela-zero/files/2055527/petgo3-ELF.zip)

This is played out quite to the very end. Still lz had a winrate above 20% (with net 0ddef953).
Elf passes and lz plays on. Winrate was not changing, game was clearly lost by 1.5 points.
Can someone explain this behavior?

[I got the message "Passing wins :-)" on the console]

**Comment by Eddh** [comment]
Maybe it thinks that this is a no resign training game and T=1 lead to 20% chance of winning the game ? Seems still very weird but I can't think of anything else

**Comment by gcp** [comment]
> Is it possible that the net learn to recognize ELF games to get a better accuracy ?

This would be tricky because the positions from ELF games are mixed with normal games. It's possible the net is learning something like "ELF like structure" vs "non ELF like structure", though. But with the amount of randomness we throw in, it's hard to imagine this being a strong effect?

**Comment by Eddh** [comment]
Maybe things like joseki can clue it in ? I agree it's hard to imagine it being a strong effect though. But it puts into question using mixtures of nets in training. It is also the case in normal training, but in that case they are more similar to each other.

**Comment by petgo3** [comment]
It seems to be a possible inaccuracy.
