### ISSUE TITLE
AutoGTP game refused to resign, 657 moves, B+258.5

### ISSUE THREAD

**Issue by Nazgand** [gcp/leela-zero#1494]
This seems to be a waste of computation, and thus should be fixed.

[markgerads@localhost autogtp]$ ./autogtp -s -u 1 -k sgf
AutoGTP v16
Using 1 thread(s) for GPU(s).
Starting tuning process, please wait...
net: b69158ea816e75b7ffea06142d90d2b1199b48265e75e292f3d5bd3c081d78ee.
./leelaz --tune-only -w networks/b69158ea816e75b7ffea06142d90d2b1199b48265e75e292f3d5bd3c081d78ee --gpu=1
Using 2 thread(s).
RNG seed: 17354126947394623631
Detecting residual layers...v1...192 channels...15 blocks.
Initializing OpenCL.
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
Detected 4 OpenCL platforms.
Platform version: OpenCL 2.0 beignet 1.3
Platform profile: FULL_PROFILE
Platform name:    Intel Gen OCL Driver
Platform vendor:  Intel
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
Device ID:     0
Device name:   Intel(R) HD Graphics Skylake Halo GT2
Device type:   GPU
Device vendor: Intel
Device driver: 1.3
Device speed:  1000 MHz
Device cores:  24 CU
Device score:  620
Platform version: OpenCL 1.2 CUDA 9.1.84
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     1
Device name:   GeForce GTX 980M
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 390.59
Device speed:  1126 MHz
Device cores:  12 CU
Device score:  1112
Platform version: OpenCL 1.2 pocl 1.1 RelWithDebInfo, LLVM 6.0.0, SPIR, SLEEF, DISTRO, POCL_DEBUG
Platform profile: FULL_PROFILE
Platform name:    Portable Computing Language
Platform vendor:  The pocl project
Device ID:     2
Device name:   pthread-Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Device type:   CPU
Device vendor: GenuineIntel
Device driver: 1.1
Device speed:  3500 MHz
Device cores:  8 CU
Device score:  512
Platform version: OpenCL 1.1 Mesa 18.0.2
Platform profile: FULL_PROFILE
Platform name:    Clover
Platform vendor:  Mesa
Error getting device(s): clGetDeviceIDs: -1
Selected platform: NVIDIA CUDA
Selected device: GeForce GTX 980M
with OpenCL 1.2 capability.
Loaded existing SGEMM tuning.
Tuning process finished
Starting thread 1 on GPU 0
{
    "cmd": "selfplay",
    "hash": "b69158ea816e75b7ffea06142d90d2b1199b48265e75e292f3d5bd3c081d78ee",
    "minimum_autogtp_version": "16",
    "minimum_leelaz_version": "0.15",
    "options": {
        "noise": "true",
        "playouts": "0",
        "randomcnt": "999",
        "resignation_percent": "0",
        "visits": "3201"
    },
    "options_hash": "7aaaeb",
    "random_seed": "1844581347265279458",
    "required_client_version": "16"
}

Got new job: selfplay
net: b69158ea816e75b7ffea06142d90d2b1199b48265e75e292f3d5bd3c081d78ee.
Engine has started.
Infinite thinking time set.
1 (B Q3) 2 (W D16) 3 (B C4) 4 (W Q16) 5 (B R6) 6 (W E3) 7 (B F7) 8 (W D5) 9 (B D3) 10 (W D2) 11 (B C2) 12 (W D4) 13 (B C3) 14 (W C5) 15 (B E2) 16 (W F2) 17 (B D1) 18 (W F4) 19 (B R14) 20 (W O17) 21 (B G3) 22 (W F3) 23 (B C17) 24 (W C16) 25 (B D17) 26 (W F17) 27 (B E17) 28 (W E16) 29 (B F18) 30 (W B17) 31 (B B18) 32 (W G18) 33 (B B16) 34 (W B15) 35 (B G17) 36 (W F16) 37 (B H18) 38 (W A16) 39 (B G19) 40 (W D9) 41 (B K4) 42 (W F10) 43 (B C8) 44 (W D7) 45 (B D8) 46 (W E8) 47 (B C9) 48 (W E7) 49 (B C12) 50 (W D10) 51 (B C10) 52 (W R15) 53 (B Q14) 54 (W B13) 55 (B B7) 56 (W B6) 57 (B B12) 58 (W M3) 59 (B L5) 60 (W M5) 61 (B M6) 62 (W R10) 63 (B M4) 64 (W R12) 65 (B O14) 66 (W R8) 67 (B P7) 68 (W O11) 69 (B P9) 70 (W R4) 71 (B Q4) 72 (W R5) 73 (B Q6) 74 (W S6) 75 (B S7) 76 (W J5) 77 (B S5) 78 (W K2) 79 (B S14) 80 (W S15) 81 (B N3) 82 (W P10) 83 (B M14) 84 (W L3) 85 (B N4) 86 (W M16) 87 (B J3) 88 (W B4) 89 (B P16) 90 (W P17) 91 (B O16) 92 (W N16) 93 (B Q15) 94 (W R17) 95 (B Q11) 96 (W Q12) 97 (B Q10) 98 (W P13) 99 (B R11) 100 (W S11) 101 (B S10) 102 (W S13) 103 (B R9) 104 (W F1) 105 (B E1) 106 (W B2) 107 (B B3) 108 (W A3) 109 (B A2) 110 (W A1) 111 (B B1) 112 (W M12) 113 (B L13) 114 (W C1) 115 (B L12) 116 (W D11) 117 (B C13) 118 (W C14) 119 (B C11) 120 (W M11) 121 (B B1) 122 (W K10) 123 (B J14) 124 (W H4) 125 (B P14) 126 (W T14) 127 (B H12) 128 (W S19) 129 (B A2) 130 (W P5) 131 (B Q5) 132 (W Q1) 133 (B J2) 134 (W K5) 135 (B L4) 136 (W T3) 137 (B K7) 138 (W E10) 139 (B E13) 140 (W L19) 141 (B H7) 142 (W N19) 143 (B H10) 144 (W O5) 145 (B K18) 146 (W L1) 147 (B G2) 148 (W S4) 149 (B T6) 150 (W A10) 151 (B P4) 152 (W K11) 153 (B A4) 154 (W C7) 155 (B B8) 156 (W R2) 157 (B R3) 158 (W A12) 159 (B S3) 160 (W T9) 161 (B F12) 162 (W J16) 163 (B F5) 164 (W T10) 165 (B G4) 166 (W A13) 167 (B F8) 168 (W B5) 169 (B N5) 170 (W N17) 171 (B L11) 172 (W D15) 173 (B D12) 174 (W T11) 175 (B T4) 176 (W H13) 177 (B J13) 178 (W F14) 179 (B L10) 180 (W E4) 181 (B E6) 182 (W E19) 183 (B D18) 184 (W F13) 185 (B O6) 186 (W H8) 187 (B G11) 188 (W B11) 189 (B A18) 190 (W P12) 191 (B O9) 192 (W J8) 193 (B J7) 194 (W Q7) 195 (B L18) 196 (W T12) 197 (B S8) 198 (W K13) 199 (B K14) 200 (W B14) 201 (B H6) 202 (W O12) 203 (B M10) 204 (W J10) 205 (B K8) 206 (W G8) 207 (B O3) 208 (W A14) 209 (B M18) 210 (W F6) 211 (B F9) 212 (W J18) 213 (B G16) 214 (W G10) 215 (B G9) 216 (W G1) 217 (B H1) 218 (W T1) 219 (B L9) 220 (W N2) 221 (B O2) 222 (W A8) 223 (B A7) 224 (W N15) 225 (B S2) 226 (W D6) 227 (B G6) 228 (W R19) 229 (B N14) 230 (W N7) 231 (B J19) 232 (W H16) 233 (B J17) 234 (W O7) 235 (B K1) 236 (W C18) 237 (B N1) 238 (W C15) 239 (B L7) 240 (W P8) 241 (B L15) 242 (W H17) 243 (B A17) 244 (W P3) 245 (B H11) 246 (W P6) 247 (B R4) 248 (W H3) 249 (B H2) 250 (W J9) 251 (B N12) 252 (W L16) 253 (B G15) 254 (W O13) 255 (B R16) 256 (W D19) 257 (B E18) 258 (W S16) 259 (B J6) 260 (W M17) 261 (B E12) 262 (W T2) 263 (B M7) 264 (W R7) 265 (B N18) 266 (W J4) 267 (B B10) 268 (W R18) 269 (B N13) 270 (W O18) 271 (B F11) 272 (W S12) 273 (B O8) 274 (W O19) 275 (B L8) 276 (W A6) 277 (B T15) 278 (W H15) 279 (B K16) 280 (W M15) 281 (B H14) 282 (W Q18) 283 (B B16) 284 (W A5) 285 (B E11) 286 (W O10) 287 (B P18) 288 (W K17) 289 (B S4) 290 (W K3) 291 (B B19) 292 (W K15) 293 (B A1) 294 (W F19) 295 (B A3) 296 (W P11) 297 (B Q9) 298 (W T16) 299 (B Q19) 300 (W M19) 301 (B G12) 302 (W S9) 303 (B J18) 304 (W D14) 305 (B R1) 306 (W H9) 307 (B E9) 308 (W N9) 309 (B M5) 310 (W K19) 311 (B B17) 312 (W J12) 313 (B K6) 314 (W N10) 315 (B M13) 316 (W D9) 317 (B O4) 318 (W M2) 319 (B Q13) 320 (W P7) 321 (B N8) 322 (W Q8) 323 (B G18) 324 (W G13) 325 (B G14) 326 (W N11) 327 (B L14) 328 (W G10) 329 (B M8) 330 (W D10) 331 (B E10) 332 (W G7) 333 (B D13) 334 (W M1) 335 (B J11) 336 (W T7) 337 (B T8) 338 (W H5) 339 (B O1) 340 (W E15) 341 (B S1) 342 (W S17) 343 (B Q2) 344 (W P15) 345 (B O15) 346 (W P1) 347 (B R10) 348 (W K16) 349 (B R5) 350 (W J1) 351 (B K9) 352 (W G5) 353 (B N6) 354 (W G2) 355 (B T1) 356 (W E14) 357 (B T5) 358 (W T15) 359 (B F15) 360 (W R16) 361 (B A9) 362 (W Q17) 363 (B A11) 364 (W C6) 365 (B D2) 366 (W N7) 367 (B A15) 368 (W R13) 369 (B D11) 370 (W O5) 371 (B F16) 372 (W L17) 373 (B T17) 374 (W T13) 375 (B C14) 376 (W H2) 377 (B R2) 378 (W H13) 379 (B T7) 380 (W D10) 381 (B D14) 382 (W M9) 383 (B D16) 384 (W A13) 385 (B P8) 386 (W T19) 387 (B S6) 388 (W E5) 389 (B R7) 390 (W T3) 391 (B F6) 392 (W Q8) 393 (B E14) 394 (W E15) 395 (B G13) 396 (W L2) 397 (B Q7) 398 (W P5) 399 (B R8) 400 (W P7) 401 (B A10) 402 (W O7) 403 (B D15) 404 (W F14) 405 (B F13) 406 (W T18) 407 (B A12) 408 (W J15) 409 (B K12) 410 (W G4) 411 (B J2) 412 (W G3) 413 (B F10) 414 (W C15) 415 (B D9) 416 (W B14) 417 (B C1) 418 (W J3) 419 (B J9) 420 (W B15) 421 (B H13) 422 (W P19) 423 (B C16) 424 (W pass) 425 (B C19) 426 (W J8) 427 (B B9) 428 (W K1) 429 (B L6) 430 (W A14) 431 (B pass) 432 (W H8) 433 (B P15) 434 (W K10) 435 (B F14) 436 (W E19) 437 (B C18) 438 (W P18) 439 (B T2) 440 (W J10) 441 (B K11) 442 (W H1) 443 (B pass) 444 (W J10) 445 (B A19) 446 (W Q19) 447 (B G7) 448 (W D19) 449 (B P6) 450 (W H9) 451 (B Q8) 452 (W N7) 453 (B A8) 454 (W O5) 455 (B B13) 456 (W T17) 457 (B A13) 458 (W C15) 459 (B T3) 460 (W B14) 461 (B J12) 462 (W P7) 463 (B F17) 464 (W pass) 465 (B D10) 466 (W B15) 467 (B S18) 468 (W T10) 469 (B K17) 470 (W T16) 471 (B N10) 472 (W Q18) 473 (B P19) 474 (W T11) 475 (B M11) 476 (W P10) 477 (B O7) 478 (W T14) 479 (B T17) 480 (W K15) 481 (B H19) 482 (W J15) 483 (B T9) 484 (W M17) 485 (B G10) 486 (W S19) 487 (B T18) 488 (W O12) 489 (B K16) 490 (W R18) 491 (B R17) 492 (W T12) 493 (B R15) 494 (W O19) 495 (B N17) 496 (W T19) 497 (B J2) 498 (W L16) 499 (B Q19) 500 (W Q12) 501 (B O17) 502 (W K1) 503 (B H17) 504 (W Q16) 505 (B K3) 506 (W R13) 507 (B N19) 508 (W C5) 509 (B B2) 510 (W P17) 511 (B J16) 512 (W F1) 513 (B S17) 514 (W S15) 515 (B P7) 516 (W A5) 517 (B H5) 518 (W O10) 519 (B A6) 520 (W C7) 521 (B R19) 522 (W Q17) 523 (B J4) 524 (W M19) 525 (B N15) 526 (W K5) 527 (B E8) 528 (W S11) 529 (B G8) 530 (W S13) 531 (B S12) 532 (W M1) 533 (B E5) 534 (W P18) 535 (B J5) 536 (W P13) 537 (B P12) 538 (W B4) 539 (B E3) 540 (W D6) 541 (B T19) 542 (W N16) 543 (B N11) 544 (W R12) 545 (B F3) 546 (W G3) 547 (B C6) 548 (W S19) 549 (B D4) 550 (W H1) 551 (B K2) 552 (W R16) 553 (B H15) 554 (W P11) 555 (B M9) 556 (W P19) 557 (B K10) 558 (W Q19) 559 (B J3) 560 (W L17) 561 (B G1) 562 (W T13) 563 (B L2) 564 (W H8) 565 (B B11) 566 (W P12) 567 (B J1) 568 (W J8) 569 (B L19) 570 (W O18) 571 (B E4) 572 (W D7) 573 (B B6) 574 (W L1) 575 (B R19) 576 (W M15) 577 (B A14) 578 (W M2) 579 (B M19) 580 (W L3) 581 (B S9) 582 (W S16) 583 (B T15) 584 (W T16) 585 (B K15) 586 (W B5) 587 (B Q19) 588 (W S12) 589 (B J10) 590 (W B15) 591 (B E16) 592 (W E7) 593 (B K13) 594 (W G5) 595 (B S16) 596 (W P18) 597 (B Q18) 598 (W O19) 599 (B G2) 600 (W G4) 601 (B P17) 602 (W Q17) 603 (B N7) 604 (W O18) 605 (B N9) 606 (W H2) 607 (B P2) 608 (W H4) 609 (B D5) 610 (W Q16) 611 (B E15) 612 (W Q1) 613 (B R18) 614 (W B14) 615 (B P19) 616 (W H3) 617 (B M3) 618 (W E7) 619 (B B5) 620 (W O18) 621 (B P1) 622 (W O11) 623 (B J15) 624 (W O19) 625 (B F19) 626 (W D19) 627 (B L3) 628 (W D7) 629 (B A16) 630 (W C7) 631 (B S19) 632 (W pass) 633 (B S15) 634 (W pass) 635 (B C15) 636 (W F2) 637 (B A5) 638 (W G1) 639 (B R16) 640 (W F4) 641 (B D6) 642 (W Q16) 643 (B E19) 644 (W B15) 645 (B P5) 646 (W C7) 647 (B B14) 648 (W pass) 649 (B P3) 650 (W pass) 651 (B H16) 652 (W E7) 653 (B O5) 654 (W pass) 655 (B H9) 656 (W pass) 657 (B pass) Game has ended.
Score: B+258.5
Winner: black
Uploading game: eaba4b5caf9047f2afc2eb3c7bf94482.sgf for network b69158ea816e75b7ffea06142d90d2b1199b48265e75e292f3d5bd3c081d78ee
Game data 1627da5524e7c868fb4d89381f0145b9de08ab07fea023d8f032fe35738c3693 stored in database
1 game(s) (1 self played and 0 matches) played in 112 minutes = 6722 seconds/game, 10231 ms/move, last game took 6719 seconds.
Program ends: quitting current worker.
Storing current game ...
Management: waiting for workers
Management: Worker 1 ended
[markgerads@localhost autogtp]$

**Comment by Hersmunch** [comment]
> {
> "cmd": "selfplay",
> "hash": "b69158ea816e75b7ffea06142d90d2b1199b48265e75e292f3d5bd3c081d78ee",
> "minimum_autogtp_version": "16",
> "minimum_leelaz_version": "0.15",
> "options": {
> "noise": "true",
> "playouts": "0",
> "randomcnt": "999",
> **"resignation_percent": "0",**
> "visits": "3201"
> }

Some games are played with resignation disabled.
