### ISSUE TITLE
autogtp causes other programs to lag

### ISSUE THREAD

**Issue by Nazgand** [gcp/leela-zero#1495]
I would like to limit leelaz GPU utilization to e.g. 80% because leelaz causes e.g. scrolling in Firefox to lag. I looked around and did not find any settings to limit leelaz, thus I request this be added as setting/flag for the autogtp program.

[markgerads@localhost autogtp]$ nvidia-smi
Wed May 30 14:09:09 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.59                 Driver Version: 390.59                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980M    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   87C    P0    91W /  N/A |   1267MiB /  4043MiB |     97%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1916      G   /usr/libexec/Xorg                             71MiB |
|    0      2294      G   /usr/bin/gnome-shell                          45MiB |
|    0      2653      G   /usr/libexec/Xorg                            583MiB |
|    0      2764      G   /usr/bin/gnome-shell                         376MiB |
|    0      4280      G   /usr/bin/vlc                                  19MiB |
|    0     19011      C   ./leelaz                                     156MiB |
+-----------------------------------------------------------------------------+

**Comment by ihavnoid** [comment]
I tried to do something about this but ended up determining this is an uphill battle.  For various reasons that cannot be understood, the lag persisted even when the displayed utilization is only 50%.  Who knows what nvidia's internal drivers are doing - but anyway it seemed like a puzzling hide-and-seek problem.  I ended up just buying another GPU for display only purposes

Anybody with a better idea what to do...?

**Comment by Nazgand** [comment]
I realized I could use the Intel CPU integrated GPU without lagging by using the -u 0 flag when running autogtp. The Intel(R) HD Graphics Skylake Halo GT2 only has ~117Gigaflops, which is super slow, yet at least it doesn't lag my browser.

**Comment by marcocalignano** [comment]
First of all your other program lag bacause the nvidia driver needs CPU to work so buing another GPU won't help, Using the Intel GPU solve your problem because you use another driver and CPU is use differently. 
Second I already notice the nvidia driver 390.59 use way too much CPU respect to the 390.48 (that I currently use). So I suggest you to switch to the 390.48 driver. 
Then consider using X on the Intel GPU and leave the nvidia card for autogtp that also help reducing CPU usage.
