### ISSUE TITLE
can program learn from learning process by itslef?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1496]
As so far, all the program done is obey the order of code to learn some  knowledge that people wanted.
to leelazero, people define the 0.55 winrate at 400 games, each 32k steps a weight, 10% resignation, random moves number, the time point of upgrade  blocks and flilters, blocks and flilters numbers, and so on.
Are there a method to let program itselef to collect all useful information, such as  cpu and gpu speed and number, the time and winrate of games that clients returned, etc, to deceide the value of these magic number and adjust them on demand, to get the strongest weight as soon as possible?

**Comment by Ttl** [comment]
Finding the optimal hyperparameters as you suggest is not really possible efficiently using the current machine learning methods. Usually people just try different choices and choose what works best.
