### ISSUE TITLE
Colab: *ERROR*

### ISSUE THREAD

**Issue by WYVYW** [gcp/leela-zero#1498]
Colab does not seem to work anymore- I noticed the following two error messages:
terminate called after throwing an instance of 'cl::Error'
*ERROR*: Could not talk to engine after launching.

here is the full cell-log:
AutoGTP v16
Using 1 thread(s) for GPU(s).
Starting tuning process, please wait...
Net filename: networks/b69158ea816e75b7ffea06142d90d2b1199b48265e75e292f3d5bd3c081d78ee
net: b69158ea816e75b7ffea06142d90d2b1199b48265e75e292f3d5bd3c081d78ee.
./leelaz --tune-only -w networks/b69158ea816e75b7ffea06142d90d2b1199b48265e75e292f3d5bd3c081d78ee
Using 2 thread(s).
RNG seed: 1285965190520881544
Detecting residual layers...v1...192 channels...15 blocks.
Initializing OpenCL.
OpenCL: clGetPlatformIDs
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Tuning process finished
Starting thread 1 on GPU 0
{
    "cmd": "selfplay",
    "hash": "b69158ea816e75b7ffea06142d90d2b1199b48265e75e292f3d5bd3c081d78ee",
    "minimum_autogtp_version": "16",
    "minimum_leelaz_version": "0.15",
    "options": {
        "noise": "true",
        "playouts": "0",
        "randomcnt": "999",
        "resignation_percent": "5",
        "visits": "3201"
    },
    "options_hash": "df715e",
    "random_seed": "1528456635994884208",
    "required_client_version": "16"
}

Got new job: selfplay
net: b69158ea816e75b7ffea06142d90d2b1199b48265e75e292f3d5bd3c081d78ee.
*ERROR*: Could not talk to engine after launching.

**Comment by alphaladder** [comment]
use this code 
!kill -9 -1

**Comment by WYVYW** [comment]
Where am I supposed to enter that code?

**Comment by WYVYW** [comment]
I still don't know where to enter the kill code, 
but I made a new copy of the notebook after deleting the cells and the notebook, 
and I still get the same failure.
Is anybody else using colab for LZ (with success or without)?

**Comment by alphaladder** [comment]
press + code button to input

**Comment by 3kakakhel** [comment]
I still use it a couple days a week. I tried it today and had the same error. I pressed the `+ code` button which made an empty cell at the top. I put the command `!kill -9 -1` in that cell and ran all the cells. I still ended up with the same error again.

**Comment by WYVYW** [comment]
I tried the kill command at every cell without any effect.

**Comment by trunterzx** [comment]
I am also experiencing the same issue. Even though I am contributing using my own computer also, I thought it would be better to do more through the Colab as well.

Does anybody have an idea how to solve this issue?

**Comment by iteachcs** [comment]
May want to check if GPU is selected in your Notebook Settings under Edit.

**Comment by trunterzx** [comment]
@iteachcs yes it is enabled. It was running well a few days ago...

<img width="1469" alt="screen shot 2018-06-03 at 8 01 56 pm" src="https://user-images.githubusercontent.com/36939338/40886369-14361810-6769-11e8-9517-2a9015cfa932.png">

**Comment by jest** [comment]
According to [this thread on LCZero Google Group](https://groups.google.com/d/msg/lczero/AmBfQw04o2k/0V6wRzN1AAAJ), there is a problem with cohesive versioning of NVIDIA packages in Ubuntu. Instead, [this colab document](https://colab.research.google.com/drive/1Zu63keeotpE0X9ddnY79f3EW0EVISium) uses a different set of commands to install packages that work for me:

```
!wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1704/x86_64/cuda-repo-ubuntu1704_9.0.176-1_amd64.deb
!apt-get install -y --fix-missing --no-install-recommends dirmngr
!dpkg -i cuda-repo-ubuntu1704_9.0.176-1_amd64.deb
!apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1704/x86_64/7fa2af80.pub
!apt-get update
!mkdir /usr/lib/nvidia
!apt-get install -y --fix-missing --no-install-recommends linux-headers-generic nvidia-384=384.111-0ubuntu1 nvidia-opencl-dev nvidia-opencl-icd-384=384.111-0ubuntu1 opencl-headers
!apt-get install -y --fix-missing --no-install-recommends clinfo cmake git libboost-all-dev libopenblas-dev zlib1g-dev
!clinfo
```

Replace the standard set of instructions in the first cell of document linked from Wiki:

```
!apt-get update
!apt --fix-broken install
!apt-get install -y --fix-missing clinfo cmake git libboost-all-dev libopenblas-dev nvidia-cuda-toolkit opencl-headers libboost-dev libboost-program-options-dev libopenblas-dev opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev zlib1g-dev qt5-default qt5-qmake curl
!clinfo
```

with the above commands and leela starts working again.

**Comment by WYVYW** [comment]
I tried the above but get now a failure in the third cell. Is that code for LZ or only for LCZ?
![image](https://user-images.githubusercontent.com/38362247/40891804-6b5e923e-678c-11e8-85f1-a5e87499dca2.png)

**Comment by jest** [comment]
Right, I probably had those Qt dependencies already installed in the runtime from previous experiments.

**Comment by Tsun-hung** [comment]
I enter the codes that @jest  and @jfsamper  list above alltogether, it runs well, which command is most important?

**Comment by jest** [comment]
All of them :-)

Mine correctly install OpenCL and is required during runtime for Leela to find GPU and schedule work there.

@jfsamper is required for building AutoGTP, which is done in previous cells.

Altogether, it's in my copy of Colab document: https://drive.google.com/file/d/13GHYkXpbDSZcff9mlD1ND6-xg__l9zKV/view?usp=sharing

**Comment by WYVYW** [comment]
Autotuning took a long time but it works. The instruction on github or the linked notebook should be updated.

**Comment by trunterzx** [comment]
@jest Your copy is working very well! Thank you! :D

**Comment by WYVYW** [comment]
Colab seems to be broken again. The first error messages appear in the first cell this time.

dpkg: error processing archive /tmp/apt-dpkg-install-zGerob/48-linux-headers-4.13.0-43_4.13.0-43.48_all.deb (--unpack):
 corrupted filesystem tarfile - corrupted package archive

**Comment by jest** [comment]
I had this today ~12h ago. I killed the machine (`!kill -9 -1`), added

```
!apt-get update
!apt --fix-broken install
```

before other installation steps to make sure the initial state is fine, and re-run all. Works for me.

**Comment by WYVYW** [comment]
works again!

**Comment by WYVYW** [comment]
Colab is again broken. Chess-Colab seems to have the same problem.

**Comment by WYVYW** [comment]
After some experimenting I achieved to go get collab working. Here is my setup for the first cell:

!wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1704/x86_64/cuda-repo-ubuntu1704_9.0.176-1_amd64.deb
!apt-get install -y --fix-missing --no-install-recommends dirmngr
!dpkg -i cuda-repo-ubuntu1704_9.0.176-1_amd64.deb
!apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1704/x86_64/7fa2af80.pub
!mkdir /usr/lib/nvidia
!apt-get update
!apt-get install -y --fix-missing --no-install-recommends linux-headers-generic nvidia-384=384.111-0ubuntu1 nvidia-opencl-dev nvidia-opencl-icd-384=384.111-0ubuntu1 opencl-headers
!apt --fix-broken install
!apt-get install -y --fix-missing clinfo cmake git libboost-all-dev libopenblas-dev nvidia-cuda-toolkit opencl-headers libboost-dev libboost-program-options-dev libopenblas-dev opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev zlib1g-dev qt5-default qt5-qmake curl
!clinfo

**Comment by WYVYW** [comment]
After working a few hours it is again broken. :(

**Comment by WYVYW** [comment]
I am not sure, what exactly the problem was/is but after some experimenting, I got it running again with following code (try this only, if you the above solutions did not work for you):

![image](https://user-images.githubusercontent.com/38362247/41192769-2ad6de08-6c03-11e8-83e9-6f56c0ed1b85.png)

!wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1704/x86_64/cuda-repo-ubuntu1704_9.0.176-1_amd64.deb
!apt-get install -y --fix-missing --no-install-recommends dirmngr
!dpkg -i cuda-repo-ubuntu1704_9.0.176-1_amd64.deb
!apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1704/x86_64/7fa2af80.pub
!apt-get update
!mkdir /usr/lib/nvidia
!apt-get install -y --fix-missing --no-install-recommends linux-headers-generic nvidia-384=384.111-0ubuntu1 nvidia-opencl-dev nvidia-opencl-icd-384=384.111-0ubuntu1 opencl-headers
!apt --fix-broken install
!apt-get install -y --fix-missing --no-install-recommends clinfo cmake git libboost-all-dev libopenblas-dev zlib1g-dev
!apt --fix-broken install
!apt-get install -y --fix-missing clinfo cmake git libboost-all-dev libopenblas-dev nvidia-cuda-toolkit opencl-headers libboost-dev libboost-program-options-dev libopenblas-dev opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev zlib1g-dev qt5-default qt5-qmake curl
!apt --fix-broken install
!clinfo

**Comment by WYVYW** [comment]
While Colab was running without hassle in the past, it recently started to fail at some point. 
When I restart colab these days I need to use the "!kill -9 -1" command before restarting the  code.

**Comment by WYVYW** [comment]
Broken again...
I give up trying to run Colab.

**Comment by jest** [comment]
I don't know... Probably you messed up too much. My notebook runs just fine, every time I try.

**Comment by WYVYW** [comment]
Good time Knie, thanks. Ich will try IT again

**Comment by WYVYW** [comment]
Thank you Jest. It's working again (let's see how long).
