### ISSUE TITLE
Can you give me the first weights.txt ?

### ISSUE THREAD

**Issue by wqssyq** [gcp/leela-zero#15]
With it, leela zero play with all random?

**Comment by gcp** [comment]
You can easily generate this yourself (the format is described in the README). Distributed effort will offer it automatically when that is ready.

**Comment by wqssyq** [comment]
Before I ask, i had try some time, but false.

**Comment by gcp** [comment]
Calculating offhand:

1 line with "1" (format version)

(1 input layer)
1 line with 18 inputs x 9 filter weights x 1 output = 162 random numbers
1 line with 1 random number (bias for the 1 output channel)
1 line with 1 random number (batchnorm mean for 1 output)
1 line with 1 random number (batchnorm variance for 1 output)

(1 residual layer - 1st convnet)
1 line with 1 input x 9 filter weights x 1 output = 9 random numbers
1 line with 1 random number (bias for the 1 output channel)
1 line with 1 random number (batchnorm mean for 1 output)
1 line with 1 random number (batchnorm variance for 1 output)
(1 residual layer - 2nd convnet)
1 line with 1 input x 9 filter weights x 1 output = 9 random numbers
1 line with 1 random number (bias for the 1 output channel)
1 line with 1 random number (batchnorm mean for 1 output)
1 line with 1 random number (batchnorm variance for 1 output)

(policy head)
1 line with 1 input x 9 filter weights x 2 output = 18 random numbers
1 line with 2 random numbers (bias for the 2 output channels)
1 line with 2 random numbers (batchnorm mean for 2 outputs)
1 line with 2 random numbers (batchnorm variance for 2 outputs)
1 line with 2 x 361 inputs x 362 outputs = 261364 random numbers (https://github.com/gcp/leela-zero/blob/2df22d20053e2acd804fff9c110ae9932c00ea99/src/Network.cpp#L71)
1 line with 362 random numbers (innerproduct output bias)

(value head)
1 line with 1 input x 9 filter weights x 1 output = 9 random numbers
1 line with 1 random number (bias for the 1 output channel)
1 line with 1 random number (batchnorm mean for 1 output)
1 line with 2 random number (batchnorm variance for 1 output)
1 line with 1 x 361 inputs x 256 outputs = 92416 random numbers https://github.com/gcp/leela-zero/blob/2df22d20053e2acd804fff9c110ae9932c00ea99/src/Network.cpp#L80
1 line with 256 random numbers (innerproduct output bias)
1 line with 1 x 256 inputs x 1 output = 256 random numbers
1 line with 1 random number

No guarantee this is correct.

**Comment by gcp** [comment]
>(policy head)
>1 line with 1 input x 9 filter weights x 2 output = 18 random numbers

>(value head)
>1 line with 1 input x 9 filter weights x 1 output = 9 random numbers

This is wrong. The convolution filter at the start of the heads is a 1x1 filter, so it is only 1 filter weight, not 9.

**Comment by gcp** [comment]
As a final remark, the OpenCL code probably wants to number of filters/residual outputs to be divisible by 2, or even 8 preferably.
