### ISSUE TITLE
only one step then game over

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#150]
Best network hash: 1ac2638de9d4d3f9eef43f2afb6b1b4c090a7c350fde4d2d77e00e39eba6fde0
Required client version: 2 (OK)
Already downloaded network.
Engine has started.
Infinite thinking time set.
1 (J8) 2 (pass) 3 (pass) Game has ended.
Score: B+353.5
Winner: black
Writing fd8ca029ba9249cda369c5f6bd3eed76.sgf
Dumping fd8ca029ba9249cda369c5f6bd3eed76.txt
Stopping engine.
curl.exe -F networkhash=1ac2638de9d4d3f9eef43f2afb6b1b4c090a7c350fde4d2d77e00e39eba6fde0 -F clientversion=4 -F sgf=@fd8c
a029ba9249cda369c5f6bd3eed76.sgf.gz -F trainingdata=@fd8ca029ba9249cda369c5f6bd3eed76.txt.0.gz http://zero.sjeng.org/sub
mit
Game data 679816a923ff1d4596bf0a0a8a742d66a30b967a384eff2727f8cf6f35600360 stored in database
9 game(s) played in 1775 minutes = 11839 seconds/game, last game took 38 seconds.

**Comment by gcp** [comment]
So what?

**Comment by l1t1** [comment]
if one moves J8 then game finished，I think it maybe a bug.

**Comment by sbbdms** [comment]
This is not a bug.
Leela will learn that she shouldn't make a "pass" too early by learning this kind of demos.

**Comment by l1t1** [comment]
and 0 step
<b>
Best network hash: 92c658d7325fe38f0c8adbbb1444ed17afd891b9f208003c272547a7bcb87909
Required client version: 4 (OK)
Already downloaded network.
Engine has started.
Infinite thinking time set.
1 (pass) 2 (pass) Game has ended.
Score: W+7.5
</b>
