### ISSUE TITLE
Petgo3 (Leela Zero bot on KGS) has issue with seki?

### ISSUE THREAD

**Issue by betafj** [gcp/leela-zero#1501]
Here is a link to a game that petgo lost

http://eidogo.com/#3R7gjH6jg 

Why did Leela Zero self-atari at move 407? Is the move pass not considered by the search for some reason?

**Comment by Ishinoshita** [comment]
Would Black (Petgo3) have passed instead, it would also  have lost (W83.5/B77 with Japanese rules, should be close to Chinese in this position). So same result (=loss). Thus all moves are equal.

**Comment by Splee99** [comment]
@Ishinoshita have you counted prisoners?

**Comment by Ishinoshita** [comment]
@Splee99 I did, but based on Eidogo final position prisoners count, not with pass move ;-). My mistake !

**Comment by gcp** [comment]
>have you counted prisoners?

Prisoners don't count in Chinese rules.``

**Comment by Splee99** [comment]
So petgo3 has no issue with seki, but with pass.

**Comment by Splee99** [comment]
@tapsika On my computer LZ played PASS after several moves from the formation of the top left seki. So I think in the settings of petgo3 somehow the PASS move was disabled.
