### ISSUE TITLE
why 0cb7 passed and promoted so early

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1504]
only 230 games, and step 8 and 16,16 weight join the match again

**Comment by Friday9i** [comment]
It was above 60% after 200 games...: 121 to 79!
But surprisingly, it's now down to 54%: 166 to 142!!!
It means that on the last 108 games, it scored 45 to 63, ie barely 40%!?!
These variations are so strange, hard to admit the random role to give so erratic results. But it seems to be real anyway, as strange as it is.

**Comment by strngtn** [comment]
Do we have any restricts on the playing settings --like po? Some variant may be strong with a small po limit but the others may be stronger when po increased.   i.e. If a large set of powerful machines/clients turn on/shut down, the play result may change significantly.

The other interesting thing may be the geo-distribution of hardware.  It may be interesting if we can show a computing power dashboard.  Given a weight(e.g.  po per second) of each client, show the sum/average of all the clients in a dashboard.

**Comment by WYVYW** [comment]
auto-gtp uses infinite thinking time, so the power of machines does not matter.
