### ISSUE TITLE
old match info disappeared

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1505]
http://zero.sjeng.org/match-games/5b1133f3888bab42e3cde090

shows

No match found for id undefined

**Comment by l1t1** [comment]
it was ee8b18f7 VS b69158ea

**Comment by l1t1** [comment]
they all disappeared, include the latest http://zero.sjeng.org/match-games/5b1305344bd933175ded43a4 ,0cb74be2 VS b69158ea

**Comment by roy7** [comment]
Database server currently offline.
