### ISSUE TITLE
Website Down?

### ISSUE THREAD

**Issue by smy20011** [gcp/leela-zero#1506]
Hey, I tried to download the best network for leela zero but gives me 502 error. Is website down right now?

**Comment by roy7** [comment]
Yes appears mongodb crashed. @gcp needs to restart it.

**Comment by l1t1** [comment]
did someone hacked the project? many strange things occured.

**Comment by davidye2020** [comment]
@smy20011 if you had autogtp it still downloads the latest network automatically why would you need to go directly to the website for the latest best network?!

**Comment by smy20011** [comment]
@davidye2020 I just start following the instruction of `Example of compiling and running - macOS` section, the wget gives me empty network

**Comment by roy7** [comment]
Server is offline but the nginx is still running so you can get the network from http://zero.sjeng.org/networks/

**Comment by smy20011** [comment]
@roy7 Thank you so much!

**Comment by davidye2020** [comment]
it could be featurecat tit for tat

![image](https://user-images.githubusercontent.com/29236792/40881803-44981464-6696-11e8-8a38-c994d9c12563.png)

**Comment by roy7** [comment]
I have no idea what your post is talking about.

**Comment by Nazgand** [comment]
The game uploads fail. Should I stop generating games? Will the games be uploaded after the website is up?

**Comment by l1t1** [comment]
i think we should have a rest today. @Nazgand

**Comment by gcp** [comment]
>Should I stop generating games? 

No.

>Will the games be uploaded after the website is up?

Yes.
