### ISSUE TITLE
Leelaz MacOS Compiling

### ISSUE THREAD

**Issue by Dreamkeeper66666** [gcp/leela-zero#1507]
Here is the info of my system
![screen shot 2018-06-03 at 4 25 06 pm](https://user-images.githubusercontent.com/35905034/40884666-bec9caca-674a-11e8-8347-df793a4c3e1c.png)
I was just following the instructions to compile the leelaz. And I got the following warnings. The resulting leelaz works just fine, but when I used some GTP engines like sabaki and lizzie, there seemed to have several issues. So, does anybody know how to solve the problem? Besides, is there someone being able to send me a well compiled leelaz 0.15?, thanks a lot! 

`Using 2 thread(s).
RNG seed: 16698411642183868850
Leela Zero 0.15  Copyright (C) 2017-2018  Gian-Carlo Pascutto and contributors
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

Detecting residual layers...v2...224 channels...20 blocks.
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 (Mar 15 2018 21:59:37)
Platform profile: FULL_PROFILE
Platform name:    Apple
Platform vendor:  Apple
Device ID:     0
Device name:   Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
Device type:   CPU
Device vendor: Intel
Device driver: 1.1
Device speed:  1600 MHz
Device cores:  4 CU
Device score:  512
Device ID:     1
Device name:   Intel(R) Iris(TM) Graphics 6100
Device type:   GPU
Device vendor: Intel Inc.
Device driver: 1.2(Mar 15 2018 22:04:25)
Device speed:  950 MHz
Device cores:  48 CU
Device score:  612
Selected platform: Apple
Selected device: Intel(R) Iris(TM) Graphics 6100
with OpenCL 1.2 capability.
Loaded existing SGEMM tuning.
Wavefront/Warp size: 16
Max workgroup size: 256
Max workgroup dimensions: 256 256 256 

Passes: 0            Black (X) Prisoners: 0
Black (X) to move    White (O) Prisoners: 0

   a b c d e f g h j k l m n o p q r s t 
19 . . . . . . . . . . . . . . . . . . . 19
18 . . . . . . . . . . . . . . . . . . . 18
17 . . . . . . . . . . . . . . . . . . . 17
16 . . . + . . . . . + . . . . . + . . . 16
15 . . . . . . . . . . . . . . . . . . . 15
14 . . . . . . . . . . . . . . . . . . . 14
13 . . . . . . . . . . . . . . . . . . . 13
12 . . . . . . . . . . . . . . . . . . . 12
11 . . . . . . . . . . . . . . . . . . . 11
10 . . . + . . . . . + . . . . . + . . . 10
 9 . . . . . . . . . . . . . . . . . . .  9
 8 . . . . . . . . . . . . . . . . . . .  8
 7 . . . . . . . . . . . . . . . . . . .  7
 6 . . . . . . . . . . . . . . . . . . .  6
 5 . . . . . . . . . . . . . . . . . . .  5
 4 . . . + . . . . . + . . . . . + . . .  4
 3 . . . . . . . . . . . . . . . . . . .  3
 2 . . . . . . . . . . . . . . . . . . .  2
 1 . . . . . . . . . . . . . . . . . . .  1
   a b c d e f g h j k l m n o p q r s t 

Hash: 9A930BE1616C538E Ko-Hash: A14C933E7669946D

Black time: 01:00:00
White time: 01:00:00`

`Detected OS: Darwin
/Library/Developer/CommandLineTools/usr/bin/make CC=gcc CXX=g++ \
		CXXFLAGS='-I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG'  \
		LDFLAGS=' -flto -g' \
		leelaz
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Network.o Network.cpp
In file included from Network.cpp:46:
In file included from ./OpenCLScheduler.h:26:
In file included from ./OpenCL.h:27:
./CL/cl2.hpp:4581:25: warning: 'clCreateImage2D' is deprecated: first deprecated
      in macOS 10.8 [-Wdeprecated-declarations]
            object_ = ::clCreateImage2D(
                        ^
/System/Library/Frameworks/OpenCL.framework/Headers/cl.h:1170:1: note: 
      'clCreateImage2D' has been explicitly marked deprecated here
clCreateImage2D(cl_context              /* context */,
^
In file included from Network.cpp:46:
In file included from ./OpenCLScheduler.h:26:
In file included from ./OpenCL.h:27:
./CL/cl2.hpp:4848:3: warning: 'weak_import' attribute only applies to variables
      and functions [-Wignored-attributes]
} CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED;
  ^
/System/Library/Frameworks/OpenCL.framework/Headers/cl_platform.h:63:57: note: 
      expanded from macro 'CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED'
        #define CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED   CL_EXTENSION_WEA...
                                                        ^
/System/Library/Frameworks/OpenCL.framework/Headers/cl_platform.h:49:57: note: 
      expanded from macro 'CL_EXTENSION_WEAK_LINK'
    #define CL_EXTENSION_WEAK_LINK       __attribute__((weak_import))
                                                        ^
In file included from Network.cpp:46:
In file included from ./OpenCLScheduler.h:26:
In file included from ./OpenCL.h:27:
./CL/cl2.hpp:5014:25: warning: 'clCreateImage3D' is deprecated: first deprecated
      in macOS 10.8 [-Wdeprecated-declarations]
            object_ = ::clCreateImage3D(
                        ^
/System/Library/Frameworks/OpenCL.framework/Headers/cl.h:1180:1: note: 
      'clCreateImage3D' has been explicitly marked deprecated here
clCreateImage3D(cl_context              /* context */,
^
In file included from Network.cpp:46:
In file included from ./OpenCLScheduler.h:26:
In file included from ./OpenCL.h:27:
./CL/cl2.hpp:5104:21: warning: 'clCreateFromGLTexture3D' is deprecated: first
      deprecated in macOS 10.8 [-Wdeprecated-declarations]
        object_ = ::clCreateFromGLTexture3D(
                    ^
/System/Library/Frameworks/OpenCL.framework/Headers/cl_gl.h:116:1: note: 
      'clCreateFromGLTexture3D' has been explicitly marked deprecated here
clCreateFromGLTexture3D(cl_context      /* context */,
^
Network.cpp:132:54: warning: suggest braces around initialization of subobject
      [-Wmissing-braces]
    const auto G = std::array<float, WINOGRAD_TILE>{ 1.0,  0.0,  0.0,
                                                     ^~~~~~~~~~~~~~~~
                                                     {
Network.cpp:611:21: warning: suggest braces around initialization of subobject
      [-Wmissing-braces]
                    temp_m[0][0] + temp_m[0][1] + temp_m[0][2] +
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    {
Network.cpp:611:21: warning: suggest braces around initialization of subobject
      [-Wmissing-braces]
                    temp_m[0][0] + temp_m[0][1] + temp_m[0][2] +
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    {
Network.cpp:617:21: warning: suggest braces around initialization of subobject
      [-Wmissing-braces]
                    temp_m[1][0] + temp_m[1][1] + temp_m[1][2] -
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    {
Network.cpp:617:21: warning: suggest braces around initialization of subobject
      [-Wmissing-braces]
                    temp_m[1][0] + temp_m[1][1] + temp_m[1][2] -
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    {
Network.cpp:611:21: warning: suggest braces around initialization of subobject
      [-Wmissing-braces]
                    temp_m[0][0] + temp_m[0][1] + temp_m[0][2] +
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    {
10 warnings generated.
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o FullBoard.o FullBoard.cpp
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o KoState.o KoState.cpp
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Training.o Training.cpp
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o TimeControl.o TimeControl.cpp
TimeControl.cpp:61:25: warning: suggest braces around initialization of subobject [-Wmissing-braces]
    m_remaining_time = {m_maintime, m_maintime};
                        ^~~~~~~~~~~~~~~~~~~~~~
                        {                     }
TimeControl.cpp:62:22: warning: suggest braces around initialization of subobject [-Wmissing-braces]
    m_stones_left = {m_byostones, m_byostones};
                     ^~~~~~~~~~~~~~~~~~~~~~~~
                     {                       }
TimeControl.cpp:63:23: warning: suggest braces around initialization of subobject [-Wmissing-braces]
    m_periods_left = {m_byoperiods, m_byoperiods};
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
                      {                         }
TimeControl.cpp:64:16: warning: suggest braces around initialization of subobject [-Wmissing-braces]
    m_inbyo = {m_maintime <= 0, m_maintime <= 0};
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               {                               }
4 warnings generated.
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o UCTSearch.o UCTSearch.cpp
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o GameState.o GameState.cpp
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Leela.o Leela.cpp
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o SGFParser.o SGFParser.cpp
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Timing.o Timing.cpp
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Utils.o Utils.cpp
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o FastBoard.o FastBoard.cpp
FastBoard.cpp:40:5: warning: suggest braces around initialization of subobject [-Wmissing-braces]
    4 * (1 << (NBR_SHIFT * BLACK)),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    {
FastBoard.cpp:45:5: warning: suggest braces around initialization of subobject [-Wmissing-braces]
    WHITE, BLACK, EMPTY, INVAL
    ^~~~~~~~~~~~~~~~~~~~~~~~~~
    {                         }
2 warnings generated.
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o SGFTree.o SGFTree.cpp
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Zobrist.o Zobrist.cpp
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o FastState.o FastState.cpp
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o GTP.o GTP.cpp
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Random.o Random.cpp
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o SMP.o SMP.cpp
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o UCTNode.o UCTNode.cpp
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o UCTNodePointer.o UCTNodePointer.cpp
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o UCTNodeRoot.o UCTNodeRoot.cpp
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o OpenCL.o OpenCL.cpp
In file included from OpenCL.cpp:22:
In file included from ./OpenCL.h:27:
./CL/cl2.hpp:4581:25: warning: 'clCreateImage2D' is deprecated: first deprecated in macOS 10.8
      [-Wdeprecated-declarations]
            object_ = ::clCreateImage2D(
                        ^
/System/Library/Frameworks/OpenCL.framework/Headers/cl.h:1170:1: note: 'clCreateImage2D' has been explicitly marked
      deprecated here
clCreateImage2D(cl_context              /* context */,
^
In file included from OpenCL.cpp:22:
In file included from ./OpenCL.h:27:
./CL/cl2.hpp:4848:3: warning: 'weak_import' attribute only applies to variables and functions [-Wignored-attributes]
} CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED;
  ^
/System/Library/Frameworks/OpenCL.framework/Headers/cl_platform.h:63:57: note: expanded from macro
      'CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED'
        #define CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED   CL_EXTENSION_WEAK_LINK AVAILABLE_MAC_OS_X_VERSION_10_7_A...
                                                        ^
/System/Library/Frameworks/OpenCL.framework/Headers/cl_platform.h:49:57: note: expanded from macro
      'CL_EXTENSION_WEAK_LINK'
    #define CL_EXTENSION_WEAK_LINK       __attribute__((weak_import))
                                                        ^
In file included from OpenCL.cpp:22:
In file included from ./OpenCL.h:27:
./CL/cl2.hpp:5014:25: warning: 'clCreateImage3D' is deprecated: first deprecated in macOS 10.8
      [-Wdeprecated-declarations]
            object_ = ::clCreateImage3D(
                        ^
/System/Library/Frameworks/OpenCL.framework/Headers/cl.h:1180:1: note: 'clCreateImage3D' has been explicitly marked
      deprecated here
clCreateImage3D(cl_context              /* context */,
^
In file included from OpenCL.cpp:22:
In file included from ./OpenCL.h:27:
./CL/cl2.hpp:5104:21: warning: 'clCreateFromGLTexture3D' is deprecated: first deprecated in macOS 10.8
      [-Wdeprecated-declarations]
        object_ = ::clCreateFromGLTexture3D(
                    ^
/System/Library/Frameworks/OpenCL.framework/Headers/cl_gl.h:116:1: note: 'clCreateFromGLTexture3D' has been explicitly
      marked deprecated here
clCreateFromGLTexture3D(cl_context      /* context */,
^
4 warnings generated.
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o OpenCLScheduler.o OpenCLScheduler.cpp
In file included from OpenCLScheduler.cpp:23:
In file included from ./OpenCLScheduler.h:26:
In file included from ./OpenCL.h:27:
./CL/cl2.hpp:4581:25: warning: 'clCreateImage2D' is deprecated: first deprecated in macOS 10.8
      [-Wdeprecated-declarations]
            object_ = ::clCreateImage2D(
                        ^
/System/Library/Frameworks/OpenCL.framework/Headers/cl.h:1170:1: note: 'clCreateImage2D' has been explicitly marked
      deprecated here
clCreateImage2D(cl_context              /* context */,
^
In file included from OpenCLScheduler.cpp:23:
In file included from ./OpenCLScheduler.h:26:
In file included from ./OpenCL.h:27:
./CL/cl2.hpp:4848:3: warning: 'weak_import' attribute only applies to variables and functions [-Wignored-attributes]
} CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED;
  ^
/System/Library/Frameworks/OpenCL.framework/Headers/cl_platform.h:63:57: note: expanded from macro
      'CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED'
        #define CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED   CL_EXTENSION_WEAK_LINK AVAILABLE_MAC_OS_X_VERSION_10_7_A...
                                                        ^
/System/Library/Frameworks/OpenCL.framework/Headers/cl_platform.h:49:57: note: expanded from macro
      'CL_EXTENSION_WEAK_LINK'
    #define CL_EXTENSION_WEAK_LINK       __attribute__((weak_import))
                                                        ^
In file included from OpenCLScheduler.cpp:23:
In file included from ./OpenCLScheduler.h:26:
In file included from ./OpenCL.h:27:
./CL/cl2.hpp:5014:25: warning: 'clCreateImage3D' is deprecated: first deprecated in macOS 10.8
      [-Wdeprecated-declarations]
            object_ = ::clCreateImage3D(
                        ^
/System/Library/Frameworks/OpenCL.framework/Headers/cl.h:1180:1: note: 'clCreateImage3D' has been explicitly marked
      deprecated here
clCreateImage3D(cl_context              /* context */,
^
In file included from OpenCLScheduler.cpp:23:
In file included from ./OpenCLScheduler.h:26:
In file included from ./OpenCL.h:27:
./CL/cl2.hpp:5104:21: warning: 'clCreateFromGLTexture3D' is deprecated: first deprecated in macOS 10.8
      [-Wdeprecated-declarations]
        object_ = ::clCreateFromGLTexture3D(
                    ^
/System/Library/Frameworks/OpenCL.framework/Headers/cl_gl.h:116:1: note: 'clCreateFromGLTexture3D' has been explicitly
      marked deprecated here
clCreateFromGLTexture3D(cl_context      /* context */,
^
4 warnings generated.
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o NNCache.o NNCache.cpp
g++ -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Tuner.o Tuner.cpp
In file included from Tuner.cpp:33:
In file included from ./OpenCL.h:27:
./CL/cl2.hpp:4581:25: warning: 'clCreateImage2D' is deprecated: first deprecated in macOS 10.8
      [-Wdeprecated-declarations]
            object_ = ::clCreateImage2D(
                        ^
/System/Library/Frameworks/OpenCL.framework/Headers/cl.h:1170:1: note: 'clCreateImage2D' has been explicitly marked
      deprecated here
clCreateImage2D(cl_context              /* context */,
^
In file included from Tuner.cpp:33:
In file included from ./OpenCL.h:27:
./CL/cl2.hpp:4848:3: warning: 'weak_import' attribute only applies to variables and functions [-Wignored-attributes]
} CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED;
  ^
/System/Library/Frameworks/OpenCL.framework/Headers/cl_platform.h:63:57: note: expanded from macro
      'CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED'
        #define CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED   CL_EXTENSION_WEAK_LINK AVAILABLE_MAC_OS_X_VERSION_10_7_A...
                                                        ^
/System/Library/Frameworks/OpenCL.framework/Headers/cl_platform.h:49:57: note: expanded from macro
      'CL_EXTENSION_WEAK_LINK'
    #define CL_EXTENSION_WEAK_LINK       __attribute__((weak_import))
                                                        ^
In file included from Tuner.cpp:33:
In file included from ./OpenCL.h:27:
./CL/cl2.hpp:5014:25: warning: 'clCreateImage3D' is deprecated: first deprecated in macOS 10.8
      [-Wdeprecated-declarations]
            object_ = ::clCreateImage3D(
                        ^
/System/Library/Frameworks/OpenCL.framework/Headers/cl.h:1180:1: note: 'clCreateImage3D' has been explicitly marked
      deprecated here
clCreateImage3D(cl_context              /* context */,
^
In file included from Tuner.cpp:33:
In file included from ./OpenCL.h:27:
./CL/cl2.hpp:5104:21: warning: 'clCreateFromGLTexture3D' is deprecated: first deprecated in macOS 10.8
      [-Wdeprecated-declarations]
        object_ = ::clCreateFromGLTexture3D(
                    ^
/System/Library/Frameworks/OpenCL.framework/Headers/cl_gl.h:116:1: note: 'clCreateFromGLTexture3D' has been explicitly
      marked deprecated here
clCreateFromGLTexture3D(cl_context      /* context */,
^
4 warnings generated.
g++ -flto -g -o leelaz Network.o FullBoard.o KoState.o Training.o TimeControl.o UCTSearch.o GameState.o Leela.o SGFParser.o Timing.o Utils.o FastBoard.o SGFTree.o Zobrist.o FastState.o GTP.o Random.o SMP.o UCTNode.o UCTNodePointer.o UCTNodeRoot.o OpenCL.o OpenCLScheduler.o NNCache.o Tuner.o  -framework Accelerate -framework OpenCL -lboost_program_options -lpthread -lz`

**Comment by Dreamkeeper66666** [comment]
Is there someone being able to send me a well compiled leelaz 0.15? Thanks a lot

**Comment by nathanloop** [comment]
> but when I used some GTP engines like sabaki and lizzie, there seemed to have several issues

What issues?

**Comment by csuji** [comment]
Did a virtual machine Mac OS X compile with the next branch for a friend. This should work with Lizzie v0.5. boost library is linked static so you should only need system libraries. Let me know if it works.
[leelaz.zip](https://github.com/gcp/leela-zero/files/2066421/leelaz.zip)
MD5 (leelaz) = 20f45420d33dad3be55b4423bc4a351b

**Comment by Dreamkeeper66666** [comment]
@csuji Thank you so much, it works now. However, it generated several random moves as follows. It seems that there are still some bug. By the way, I am using the ELF converted network. Could you figure out the reason. Thanks a lot!
![screen shot 2018-06-04 at 7 03 36 am](https://user-images.githubusercontent.com/35905034/40892188-e6725878-67c5-11e8-89d0-7ca02c9f2b30.png)

**Comment by Dreamkeeper66666** [comment]
@nathanloop I just compiled a cpu-only version. It works for Sabaki now, but there were still some loading issues when I was using lizzie. --"Leela Zero is loading"
![screen shot 2018-06-04 at 6 09 09 am](https://user-images.githubusercontent.com/35905034/40892297-c7438d44-67c7-11e8-8675-383955167c28.png)

**Comment by csuji** [comment]
@Dreamkeeper66666  strange, are you using lizzie v0.5? Can you post your lizzie.properties file?

**Comment by Dreamkeeper66666** [comment]
@csuji I have just figured it out. It was because I compiled leelaz with master branch, not next branch. So something may go wrong. And It works with cpu version leelaz now. Thanks a lot!

**Comment by glen-ho** [comment]
@Dreamkeeper66666 Can you mind share your latest leelaz binaries?  Does it work with GPU in mac?
