### ISSUE TITLE
Leela Zero doesn't do anything?

### ISSUE THREAD

**Issue by Squaredj** [gcp/leela-zero#1508]
I'm trying to get Leela Zero (leela-zero-0.15-win64) to work with Sabaki, which it did just fine until I updated to the latest version of Sabaki (v0.34). Now I cannot get Leelaz to work (neither in Sabaki, nor on command prompt). Below is the result of the command I use to run it. After that the program just hangs? In my taskmanager I can see Leelaz.exe still running, but the GPU stays at 0%. 

**-- UPDATE: it seems a problem with v0.34 of Sabaki... After uninstalling and reinstalling v0.33.4 of Sabaki everything works again.**

Anybody any suggestions what I'm missing? Thanks.

leelaz.exe -g -t 1 --playouts 10 -w C:\path_to_weights\weights.txt --noponder

Using 1 thread(s).
RNG seed: 12381045048862987247
Detecting residual layers...v1...192 channels...15 blocks.
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 9.2.127
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce GTX 1060 3GB
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 397.93
Device speed:  1708 MHz
Device cores:  9 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GTX 1060 3GB
with OpenCL 1.2 capability.
Loaded existing SGEMM tuning.
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64
BLAS Core: Zen

**Comment by WYVYW** [comment]
I just found out that I have the same problem, but this is probably a Sabaki issue.

**Comment by Squaredj** [comment]
Ah, ok, so I'm not the only one. We'll we wait and see if someone else has
this issue.
What's weird is that I can't get Leela-Zero to run without Sabaki anymore
either though.


2018-06-03 12:01 GMT+02:00 WYVYW <notifications@github.com>:

**Comment by Squaredj** [comment]
Ha, you were right! I uninstalled version 0.34 of Sabaki and reinstalled
v0.33.4 and now it works again!



2018-06-03 12:01 GMT+02:00 WYVYW <notifications@github.com>:

**Comment by WYVYW** [comment]
@Squaredj  Sabaki 0.34 works for me again after reinstalling leelasabaki.
We should close this issue here and open it on sabaki, if the problem still exists.

**Comment by Marcin1960** [comment]
"Sabaki 0.34 works for me again after reinstalling leelasabaki"

leelasabaki? What is it?

**Comment by WYVYW** [comment]
@Marcin1960  leelasabaki was necessary to show heatmaps with Sabaki. 
https://github.com/SabakiHQ/LeelaSabaki

I assume that the latest Sabaki (v. 0.34) had a problem with the engine/weight settings, after leelasabaki was deinstalled together with the old Sabaki.

**Comment by yishn** [comment]
@Squaredj You mentioned you can't get Leela Zero to work in the command line?

**Comment by Squaredj** [comment]
@Yichuan Shen

Correct, after having installed version 0.34 of Sabaki and it didn't work
anymore in Sabaki, I tried the same command on the command prompt as used
in Sabaki.
The exact same thing happened on the command line as in the GPU-window of
Sabaki: it just hung after the "BLAS Core: Zen" line.
I am probably giving the wrong command. The autogtp.exe works fine on the
prompt.
I just thought I could use it the same way as in Sabaki, but on the prompt.




2018-06-03 15:01 GMT+02:00 Yichuan Shen <notifications@github.com>:

**Comment by yishn** [comment]
@Squaredj If you run Leela Zero in the command line, it's probably not hanging, but just awaiting input. After the `BLAS Core: Zen` line, type a command, e.g. `name`, and press enter to see if the engine is indeed hanging. 

Furthermore, can you please share your engine configuration in Sabaki? I have a hunch it might have something to do with the initial commands.

**Comment by Squaredj** [comment]
Ah, ok, makes sense. Indeed the name command returned Leela Zero ;-)  And
then I can used use GTP-commands, right? I had not understood, thanks.

About my engine configuration: what do you need?

In my Sabaki engine configuration I use the following 3 lines in version
0.33.4 (is that what you mean?):
K:\Documenten_Jan\GO-documenten\leela-zero-0.15-win64\leelaz.exe
-g -t 1 --playouts 10000 -w
K:\path_to_weight_file\leelaz-model-swa-24-192000.txt --noponder
time_settings 0 30 1;



2018-06-03 16:57 GMT+02:00 Yichuan Shen <notifications@github.com>:

**Comment by yishn** [comment]
Can you try removing the `;` in `time_settings 0 30 1`; that should hopefully fix it.

**Comment by Squaredj** [comment]
Yes, awesome! That did it :-)



2018-06-03 18:27 GMT+02:00 Yichuan Shen <notifications@github.com>:

**Comment by yishn** [comment]
There has been some changes and restructuring going on in the code base, so this is a new bug. I’ll release a patch today that’ll fix the problem. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
