### ISSUE TITLE
did the server down stop the match?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1510]
it is 10 hours after the server down and 3 hours after server up again, 
it usually took about 4 hours for a new 32k steps.

**Comment by l1t1** [comment]
new match began

**Comment by l1t1** [comment]
and why it jump 64, 96 to 128k?

**Comment by Ttl** [comment]
I guess they failed to upload because the server was offline. I don't think there is much point in rescheduling them anymore.
