### ISSUE TITLE
Should we favor the best, instead of the earliest, network among the same batch?

### ISSUE THREAD

**Issue by diadorak** [gcp/leela-zero#1511]
The current promoting procedure favors earlier networks in the same batch. For example, if the +32k network is 35 elo stronger than the previous best and the +128k network is 65 elo stronger, the +32k would be promoted but the +128k won't since it's not 35 stronger than the +32k.  

This can be addressed by letting all networks in the same batch match against the best network up to the last batch. At the end of the run, if at least one network passes the SPRT, promote the one with the highest win rate against the previous best. In this way, all networks in the same batch are rated using the same benchmark. The "best" network is updated at most once per run. 

One additional benefit of this procedure is to guard against lucky networks that passes the SPRT by "accident." In the current run, for example, 0cb74be2 passes with a 53.75% win rate. The next network 95b2b, which seems stronger, lost the chance to challenge the previous best b69158ea. The tweaked procedure would promote 95b2b if it scores a higher win rate against the previous best at the end of the run.

One possible drawback of this tweak is that it might delay the stronger networks from generating self-play games immediately. This can be fixed too. We can, for example, create a new category called the "best_candidate," which is the network generating self-play games.  Once a network passes the SPRT, we immediately promote it to "best_candidate." At the end of the run, if the "best" networks changes, let "best_candidate" be the same as the "best" network. Essentially currently the "best" network serves the dual roles of (1) generating self-play games and (2) being the benchmark for new networks. We can split the two roles.

**Comment by l1t1** [comment]
or automatically promote the strongest after training n games, here n may be 50k

**Comment by marcocalignano** [comment]
So you would wait 38 Hours before even starts each tournament and then probably take anothe 5-6 hours before the results are in so about 45 Hours to gain at the end less that 35 Elo? 
To me does not seem like a big gain.

**Comment by l1t1** [comment]
@marcocalignano eg. I would promote 0ddef953 at June 1. though no weight has winrate 0.55 then, but it was strongest,

**Comment by l1t1** [comment]
I suggest test two parallell way at same time, one use current method, the other use promoted in time method, test for 10 days, to compare which method produced the stronger weight.

**Comment by diadorak** [comment]
@marcocalignano No. It's explained in the fourth paragraph above. A shorter version:

1. Test match a new network as soon as it's generated. If it passed the SPRT against the "best", promoted it to "best_candidate" and let it start generating self-play games immediately. But do not promote it to "best" yet.

2. At the end of the run of a batch, if at least one network passed the SPRT in this run, promote the one with the highest win rate against the previous "best" in this batch to "best."
