### ISSUE TITLE
ICGA Computer Olympiad 2018, New Taipei City

### ISSUE THREAD

**Issue by alreadydone** [gcp/leela-zero#1518]
http://www.tcga.tw/icga-computer-olympiad-2018/en/#top
http://icga.ntpu.edu.tw/icga2018/
https://zhuanlan.zhihu.com/p/36132041

@bjiyxo @billyswong Have you been aware of the event? Would you or anyone you know be interested in attending? Or maybe @gcp himself would be interested. As is well known @sbf2000 has trained strong 9x9 models using LZ, and he has switched to 13x13. One operator can probably take care of all three board sizes.

Registration Deadline: June 25, 2018
Date: July 9-11, 2018 (not sure, it says July 7-13 somewhere else on the same page)
Registration Fee: 50 Euro for first program, 25 Euro for second, third, etc. program. (so entering 19x19, 13x13 and 9x9 cost €100.)
Award: For each tournament, medals will be awarded to top-three programs if more than three programs participate, or top-two programs if three programs participate.
Multiple programs are allowed for one person.
Registration implies acceptance of the tournament rules.

Detailed rules from 2016 (bottom of page 5): https://icga.leidenuniv.nl/wp-content/uploads/2016/03/Rules-ICGA-events-2016-3.pdf
Each program must be the original work of the entering developers, possibly with the inclusion of game playing code and/or data from other sources for which the entering developers have a legal right of use. Developers whose code is derived from or includes (1) game-playing code; and/or (2) data written by others, must name (a) all the other developers of whom they are aware; and (b) the source of such code and/or data, in their tournament registration details.
(As far as I can tell "original work" refers to the code and the data (NN weights) and not the underlying idea
so I think LZ is eligible.)
A participant is expected to be an ICGA member (€40). (I think @gcp must be a member.)

Registered participants so far: http://www.tcga.tw/icga-computer-olympiad-2018/en/#tsignup
including Aurora, "a not very faithful re-implementation of Master".

-------------------
TCGA Computer 19x19 Go Tournament
Board Size 	    : 19X19
Rules               : chinese rules & Positional SuperKo(http://www.weddslist.com/kgs/past/superko.html)
Komi                : 7.5
Competition System  : round robin
Time Setting        : 30 minutes each program, no byo-yomi
Platform	    : KGS (https://www.gokgs.com/)
Score		    : The winning bot gets 1 points and each bot gets half point if the result is draw.

TCGA Computer 13x13 Go Tournament
Board Size 	    : 13X13
Rules               : chinese rules & Positional SuperKo(http://www.weddslist.com/kgs/past/superko.html)
Komi                : 7.5
Competition System  : round robin
Time Setting        : 20 minutes each program, no byo-yomi
Platform	    : KGS (https://www.gokgs.com/)
Score		    : The winning bot gets 1 points and each bot gets half point if the result is draw.

TCGA Computer 9x9 Go Tournament
Board Size 	    : 9X9
Rules               : chinese rules &  Positional SuperKo(http://www.weddslist.com/kgs/past/superko.html)
Komi                : 7
Competition System  : double round robin
Time Setting        : 10 minutes each program, no byo-yomi
Platform	    : KGS (https://www.gokgs.com/)
Score		    : The winning bot gets 1 points and each bot gets half point if the result is draw.

**Comment by bjiyxo** [comment]
Though I live in Taipei, the only award in the tournament is a trophy. Also, I need to pay EUR 50 and the winner doesn't award any cash prize at all. It looks worthless LUL.

**Comment by alreadydone** [comment]
Yes, this event doesn't offer any cash prize; it is associated to a conference and has more of a academic flavor. I see the value mainly in communication with the academia. Since @gcp has attended ICGA before, maybe he can decide whether it's worth it. If there's sufficient interest we can maybe crowdfund it. To show support, I'll donate at least €10. @sbf2000 what do you think?

**Comment by gcp** [comment]
I haven't been an ICGA member for many years.

**Comment by WYVYW** [comment]
There is a participant list. So far this seems less interesting than a self-play game.

Go 19x19	wingo	Hsin-Hung Chou	Chang Jung Christian University	Taiwan
Go 19x19	Aurora	Qi Zhang	Institute of Automation, Chinese Academy of Science	China
Go 19x19	MUC Go/下棋游戏	Zhe Liu	Minzu University of China	China
Go 9x9	wingo	Hsin-Hung Chou	Chang Jung Christian University	Taiwan
Go 9x9	tbot	JUN-YOU, ZHUO	National Dong Hwa University	Taiwan
Go 9x9	EzGo	Hung-Cheng Lin	National Taiwan University	Taiwan

**Comment by alreadydone** [comment]
> I haven't been an ICGA member for many years.

OK my bad, should have realized memberships have to be renewed. So I guess we need an additional €40 if no developer happens to be a member? That makes it less attractive.

In 2017, The participants were Zen, CGI, Golois, and the less well-known EZGO and Julie. https://icga.org/?page_id=2050
They are probably weaker than LZ now and are not yet registered, and the event on 19x19 certainly seems less exciting than the Tencent championship late June - late July, but the 9x9 and 13x13 events seem worthwhile.

**Comment by alreadydone** [comment]
Closing for now due to lack of interest. May update participants' info and results in the future.

**Comment by l1t1** [comment]
http://computer-go.org/pipermail/computer-go/2018-July/010900.html
