### ISSUE TITLE
Learning from short games?

### ISSUE THREAD

**Issue by ThePokerDude** [gcp/leela-zero#152]
Hi,

I noticed that even with the network after over 100K games still 1 or 2 move games occur.
As there have been a lot of such games already, so I assumed the network would adjust.  
What is the reason for these games to still occur?

Best network hash: 1ac2638de9d4d3f9eef43f2afb6b1b4c090a7c350fde4d2d77e00e39eba6fde0
Required client version: 2 (OK)
Already downloaded network.
Engine has started.
Infinite thinking time set.
1 (S3) 2 (C15) 3 (pass) 4 (pass) Game has ended.
Score: W+7.5
Winner: white
Writing a39ad1c5942c46349c6a5700ca53a114.sgf
Dumping a39ad1c5942c46349c6a5700ca53a114.txt

1 (D7) 2 (pass) 3 (pass) Game has ended.
Score: B+353.5
Winner: black
Writing 99f3a5f3eb3142ed8e47148ee7d017e2.sgf
Dumping 99f3a5f3eb3142ed8e47148ee7d017e2.txt

**Comment by jkiliani** [comment]
Those games are getting rarer with every new network. The self-play training process will eventually progress to the point this will not happen anymore at all, but one training cycle is evidently not sufficient for that.

**Comment by gcp** [comment]
I explained this elsewhere, but avoiding these games isn't just learning that pass is good or not. It's that "pass" is a bad move if you're behind on the count, and "pass-after-pass" is a winning move if you're ahead on the count. This is not so easy for the network at this time.

**Comment by ThePokerDude** [comment]
Thanks for the explanation. I'm pretty new to machine learnig so please correct me if I'm wrong. 
When I understood the AlphaGo Zero correctly the agent uses its network to determine the winnig probability (p) of its next move and chooses the one with the highest p (including some randomizition when p of different moves are close to each other. 

You said the agent doesn't know that: 

> "pass-after-pass" is a winning move if you're ahead on the count.

Is it because it cannot estimate the position correctly and therefore
"thinks" p of "pass" is higher than p of alternative moves even if p=0 in fact?
This would explain why agents which can estimate the position ("can count") i.e. "know" that p is either 1 or 0 after the 2nd pass start to go crazy when they see they're losing and never choose to pass.

Or is it a different reason?

**Comment by ThePokerDude** [comment]
By the way - in the two example games the agent 2nd pass was correct.

**Comment by malcolmsharpe** [comment]
What confuses me about the super early passing (which still happens sometimes) is why isn't it prevented by the tree search? Pass-then-pass is only a depth 2 sequence, and then I'd assume (maybe wrongly) that the resulting node would evaluated using scoring instead of the network, and would show as a loss.

**Comment by olbrichj** [comment]
gcp mentioned in some other issue to use a still some randomization. I guess he was referring to different moves. Furthermore white knows it's ahead, so it passes. Maybe the network is not really aware of two passes not being a good move? It might have to detect for the other player to have passed.
