### ISSUE TITLE
Run Leela Zero on Android

### ISSUE THREAD

**Issue by fell111** [gcp/leela-zero#1520]
Someone post this topic in Reddit. It's very interesting that we could run LZ on android via Go Gridmaster.  
https://www.reddit.com/r/baduk/comments/8omrs1/psa_leelazero_runs_on_android/

I just followed the steps and ran LZ successfully. But I'm not sure whether the app connect to 'real' LZ or not. If you are interest in it, please take a try and verify it.

**Comment by l1t1** [comment]
it is true lz, see #779

**Comment by fell111** [comment]
Oh, that's great :)
