### ISSUE TITLE
Why the white is always winning?

### ISSUE THREAD

**Issue by Marcin1960** [gcp/leela-zero#1526]
I am testing two nets against each other, 5b59a018 vs 10bc1042 and each time
white is winning, no matter which net,

On KGS, LeelaZeroT versus LeelaDan, 
each noponder, 2 treads, time manage off, at 1000 visits limit.

Now I changed to 2000 visits, and will watch if something changes.

**Comment by gcp** [comment]
How many games did you play?

**Comment by gcp** [comment]
FYI: http://zero.sjeng.org/match-games/5b16d624b7546357c2eb533b

**Comment by Marcin1960** [comment]
@gcp 

More than 20 with this setup. Twenty to zero might be statistically significant

But I will run it for longer time. Last couple games are with 2000 visits, instead of 1000.

**Comment by stephenmartindale** [comment]
I don't know if this is a specific issue that @Marcin1960 is having but I can confirm that it isn't a general one.

Earlier today, I had my iPython notebook that I created for #1212  open. I have been keeping the database up to date with the web site and now have nearly 300 matches in it. The bias towards white has not become more pronounced with recent networks.

![image](https://user-images.githubusercontent.com/6370145/41038901-0fad0764-6998-11e8-8ae4-a47bb0ab9268.png)
![image](https://user-images.githubusercontent.com/6370145/41038920-229b78d8-6998-11e8-8a07-2fd6c1cea47e.png)

In fact, it looks pretty consistent. The bias is there but it doesn't appear to be changing.

**Comment by gcp** [comment]
>More than 20 with this setup. Twenty to zero might be statistically significant

Yeah, probably. What command line settings did you use? Were the game starts identical?

As you can see above, the networks have fairly balanced outcomes, and as far as I know that's pretty independent on visit settings.

**Comment by Marcin1960** [comment]
Maybe, in my setup, slight bias is sufficient to make white win all games or most.

What is the source of bias shown in your graphs? If it is known, is there some trick to compensate?

**Comment by stephenmartindale** [comment]
The graphs are purely based on match results scraped from the Leela Zero training-graph web page. They reflect the facts only. Since Leela Zero is self-taught and cannot communicate, we can only guess as to the cause of the bias.

**Comment by gcp** [comment]
Komi I'd guess.

**Comment by stephenmartindale** [comment]
Some guesses are better than others.

**Comment by Marcin1960** [comment]
@gcp 

"Yeah, probably. What command line settings did you use? Were the game starts identical?"

They were identical. 

Only difference was a little different order of command line arguments like "-t 2" or "--timemanage off" 
Also I  assigned 2 separate cores to each net (1,3 and 2,4)

**Comment by gcp** [comment]
>If komi is the reason, what value should I set to get comparable number of white and black wins?

Leela Zero only supports 7.5.

**Comment by stephenmartindale** [comment]
If you want the raw results for your model, @Marcin1960, you can clone my iPython notebook: https://github.com/stephenmartindale/zerozeug/blob/master/Match-Statistics.ipynb and see the attached zip file for the database. (Of course, you can run it and it will create an empty database but only the last 100 matches are on the web page so it is better to use mine as a starting point.)

[leela-zero-data.zip](https://github.com/gcp/leela-zero/files/2076580/leela-zero-data.zip)

**Comment by Ishinoshita** [comment]
" @gcp : komi I'd guess

In this case, this is specific to LZ training, not intrinsic to the game of go. DM paper on AZ, table 1 page 5: 60 games between AZ vs AG0-3days, 31/19 vs 29/21 with AZ as White resp. as Black. Not the beginning of a significant komi effect at this claimed 5200 Elo.

**Comment by Marcin1960** [comment]
I have some other ideas to investigate in this experiment. My PC is slow, so  I will let this match to run for a while, and then I will introduce some modifications to see more.

**Comment by Marcin1960** [comment]
Unless something new and iteresting is found, I will keep it closed
