### ISSUE TITLE
Crash on trying to generate a move

### ISSUE THREAD

**Issue by gjm11** [gcp/leela-zero#1527]
I'm trying to run LZ 0.15 (released version, downloaded as binary, x64, not CPU-only) and finding that it crashes when I give it a genmove command.

This is a fairly ordinary PC running Windows 8.1. Its GPU is a (now rather old) GTX 750. I have the latest VC++ 2015 redistributable installed.

I am using the latest (v147) weights file.

GPU tuning proceeds fine; so, if that's already been done, does reading in existing tuning settings. I can tell Leela to play a specific move on the board. But as soon as I issue a genmove command, there is a crash. More precisely, about 0.5 seconds elapse and then Leela hits an unhandled exception.

The specific message I get (which I suspect is not useful, but you never know), running LZ inside Visual Studio, is this:

> Exception thrown at 0x00007FF9C1998EAC in leelaz.exe: Microsoft C++ exception: cl::Error at memory location 0x00000059ED5BBD40.
> Unhandled exception at 0x00007FF9C1998EAC in leelaz.exe: Microsoft C++ exception: cl::Error at memory location 0x00000059ED5BBD40.

The stack trace looks like this:

>	KernelBase.dll!RaiseException()	Unknown
> 	leelaz.exe!00007ff66ff23abd()	Unknown
> 	leelaz.exe!00007ff66fe5684f()	Unknown
> 	leelaz.exe!00007ff66fe37d3b()	Unknown
> 	leelaz.exe!00007ff66fe37b19()	Unknown
> 	leelaz.exe!00007ff66fe8664c()	Unknown
> 	leelaz.exe!00007ff66fe8beca()	Unknown
> 	leelaz.exe!00007ff66fe8f5f2()	Unknown
> 	leelaz.exe!00007ff66fe0a599()	Unknown
> 	leelaz.exe!00007ff66fe19ae5()	Unknown
> 	leelaz.exe!00007ff66fecec24()	Unknown

Nothing changes if I run with `-t 1`, or with `-t 1 --noponder`. (The memory location at the end of the error message changes sometimes.)

**Comment by gcp** [comment]
Your OpenCL drivers don't work. Make sure you have the latest video drivers installed.

**Comment by gjm11** [comment]
OK, will investigate. Is that really consistent with GPU tuning having apparently worked OK?

**Comment by gcp** [comment]
The tuner only tunes one single OpenCL kernel that is executed (he most speed critical one). It doesn't say anything about everything else working correctly.

**Comment by gjm11** [comment]
I can confirm that after updating my GPU drivers and rebooting, Leela runs without crashing. Thanks, and my apologies for asking what in retrospect was a kinda stupid question.
