### ISSUE TITLE
Compiling under MSVC2017 gives the errors listed below

### ISSUE THREAD

**Issue by andy-maginn** [gcp/leela-zero#1543]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "public: class UCTNodePointer & __cdecl UCTNodePointer::operator=(class UCTNodePointer &&)" (??4UCTNodePointer@@QEAAAEAV0@$$QEAV0@@Z) referenced in function "class std::reverse_iterator<class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class UCTNodePointer> > > > __cdecl std::_Buffered_merge_backward_unchecked<class std::reverse_iterator<class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class UCTNodePointer> > > >,class UCTNodePointer *,class std::reverse_iterator<class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class UCTNodePointer> > > >,class NodeComp>(class std::reverse_iterator<class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class UCTNodePointer> > > >,class std::reverse_iterator<class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class UCTNodePointer> > > >,class UCTNodePointer *,class UCTNodePointer *,class std::reverse_iterator<class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class UCTNodePointer> > > >,class NodeComp &,bool)" (??$_Buffered_merge_backward_unchecked@V?$reverse_iterator@V?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@VUCTNodePointer@@@std@@@std@@@std@@@std@@PEAVUCTNodePointer@@V12@VNodeComp@@@std@@YA?AV?$reverse_iterator@V?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@VUCTNodePointer@@@std@@@std@@@std@@@0@V10@0PEAVUCTNodePointer@@10AEAVNodeComp@@_N@Z)	leela-zero	C:\leela-zero\msvc\VS2015\UCTNode.obj	1	
Error	LNK2001	unresolved external symbol "public: __cdecl UCTNodePointer::~UCTNodePointer(void)" (??1UCTNodePointer@@QEAA@XZ)	leela-zero	C:\leela-zero\msvc\VS2015\UCTNodeRoot.obj	1	
Error	LNK2001	unresolved external symbol "public: __cdecl UCTNodePointer::~UCTNodePointer(void)" (??1UCTNodePointer@@QEAA@XZ)	leela-zero	C:\leela-zero\msvc\VS2015\UCTSearch.obj	1	
Error	LNK2001	unresolved external symbol "public: __cdecl UCTNodePointer::~UCTNodePointer(void)" (??1UCTNodePointer@@QEAA@XZ)	leela-zero	C:\leela-zero\msvc\VS2015\GameState.obj	1	
Error	LNK2001	unresolved external symbol "public: __cdecl UCTNodePointer::~UCTNodePointer(void)" (??1UCTNodePointer@@QEAA@XZ)	leela-zero	C:\leela-zero\msvc\VS2015\GTP.obj	1	
Error	LNK2001	unresolved external symbol "public: __cdecl UCTNodePointer::~UCTNodePointer(void)" (??1UCTNodePointer@@QEAA@XZ)	leela-zero	C:\leela-zero\msvc\VS2015\Leela.obj	1	
Error	LNK2001	unresolved external symbol "public: __cdecl UCTNodePointer::~UCTNodePointer(void)" (??1UCTNodePointer@@QEAA@XZ)	leela-zero	C:\leela-zero\msvc\VS2015\UCTNode.obj	1	
Error	LNK2019	unresolved external symbol "public: __cdecl UCTNodePointer::UCTNodePointer(class UCTNodePointer &&)" (??0UCTNodePointer@@QEAA@$$QEAV0@@Z) referenced in function "void __cdecl std::_Construct<class UCTNodePointer,class UCTNodePointer>(class UCTNodePointer *,class UCTNodePointer &&)" (??$_Construct@VUCTNodePointer@@V1@@std@@YAXPEAVUCTNodePointer@@$$QEAV1@@Z)	leela-zero	C:\leela-zero\msvc\VS2015\UCTNode.obj	1	
Error	LNK2001	unresolved external symbol "public: __cdecl UCTNodePointer::UCTNodePointer(class UCTNodePointer &&)" (??0UCTNodePointer@@QEAA@$$QEAV0@@Z)	leela-zero	C:\leela-zero\msvc\VS2015\UCTNodeRoot.obj	1	
Error	LNK2019	unresolved external symbol "public: __cdecl UCTNodePointer::UCTNodePointer(short,float)" (??0UCTNodePointer@@QEAA@FM@Z) referenced in function "public: void __cdecl std::allocator<class UCTNodePointer>::construct<class UCTNodePointer,int const &,float const &>(class UCTNodePointer *,int const &,float const &)" (??$construct@VUCTNodePointer@@AEBHAEBM@?$allocator@VUCTNodePointer@@@std@@QEAAXPEAVUCTNodePointer@@AEBHAEBM@Z)	leela-zero	C:\leela-zero\msvc\VS2015\UCTNode.obj	1	
Error	LNK2001	unresolved external symbol "public: class UCTNodePointer & __cdecl UCTNodePointer::operator=(class UCTNodePointer &&)" (??4UCTNodePointer@@QEAAAEAV0@$$QEAV0@@Z)	leela-zero	C:\leela-zero\msvc\VS2015\UCTNodeRoot.obj	1	
Error	LNK2019	unresolved external symbol "public: void __cdecl UCTNodePointer::inflate(void)const " (?inflate@UCTNodePointer@@QEBAXXZ) referenced in function "public: class UCTNode & __cdecl UCTNode::get_best_root_child(int)" (?get_best_root_child@UCTNode@@QEAAAEAV1@H@Z)	leela-zero	C:\leela-zero\msvc\VS2015\UCTNode.obj	1	
Error	LNK2001	unresolved external symbol "public: void __cdecl UCTNodePointer::inflate(void)const " (?inflate@UCTNodePointer@@QEBAXXZ)	leela-zero	C:\leela-zero\msvc\VS2015\UCTNodeRoot.obj	1	
Error	LNK2019	unresolved external symbol "public: bool __cdecl UCTNodePointer::valid(void)const " (?valid@UCTNodePointer@@QEBA_NXZ) referenced in function "public: class UCTNode * __cdecl UCTNode::uct_select_child(int,bool)" (?uct_select_child@UCTNode@@QEAAPEAV1@H_N@Z)	leela-zero	C:\leela-zero\msvc\VS2015\UCTNode.obj	1	
Error	LNK2019	unresolved external symbol "public: int __cdecl UCTNodePointer::get_visits(void)const " (?get_visits@UCTNodePointer@@QEBAHXZ) referenced in function "public: bool __cdecl NodeComp::operator()(class UCTNodePointer const &,class UCTNodePointer const &)" (??RNodeComp@@QEAA_NAEBVUCTNodePointer@@0@Z)	leela-zero	C:\leela-zero\msvc\VS2015\UCTNode.obj	1	
Error	LNK2001	unresolved external symbol "public: int __cdecl UCTNodePointer::get_visits(void)const " (?get_visits@UCTNodePointer@@QEBAHXZ)	leela-zero	C:\leela-zero\msvc\VS2015\UCTSearch.obj	1	
Error	LNK2019	unresolved external symbol "public: float __cdecl UCTNodePointer::get_score(void)const " (?get_score@UCTNodePointer@@QEBAMXZ) referenced in function "public: bool __cdecl NodeComp::operator()(class UCTNodePointer const &,class UCTNodePointer const &)" (??RNodeComp@@QEAA_NAEBVUCTNodePointer@@0@Z)	leela-zero	C:\leela-zero\msvc\VS2015\UCTNode.obj	1	
Error	LNK2019	unresolved external symbol "public: bool __cdecl UCTNodePointer::active(void)const " (?active@UCTNodePointer@@QEBA_NXZ) referenced in function "public: class UCTNode * __cdecl UCTNode::uct_select_child(int,bool)" (?uct_select_child@UCTNode@@QEAAPEAV1@H_N@Z)	leela-zero	C:\leela-zero\msvc\VS2015\UCTNode.obj	1	
Error	LNK2019	unresolved external symbol "public: float __cdecl UCTNodePointer::get_eval(int)const " (?get_eval@UCTNodePointer@@QEBAMH@Z) referenced in function "public: bool __cdecl NodeComp::operator()(class UCTNodePointer const &,class UCTNodePointer const &)" (??RNodeComp@@QEAA_NAEBVUCTNodePointer@@0@Z)	leela-zero	C:\leela-zero\msvc\VS2015\UCTNode.obj	1	
Error	LNK2019	unresolved external symbol "public: int __cdecl UCTNodePointer::get_move(void)const " (?get_move@UCTNodePointer@@QEBAHXZ) referenced in function "public: class std::unique_ptr<class UCTNode,struct std::default_delete<class UCTNode> > __cdecl UCTNode::find_child(int)" (?find_child@UCTNode@@QEAA?AV?$unique_ptr@VUCTNode@@U?$default_delete@VUCTNode@@@std@@@std@@H@Z)	leela-zero	C:\leela-zero\msvc\VS2015\UCTNodeRoot.obj	1	
Error	LNK1120	11 unresolved externals	leela-zero	C:\leela-zero\msvc\x64\Debug\leelaz.exe	1	
Error	MSB8036	The Windows SDK version 10.0.16299.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".	autogtp	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets	36

**Comment by Splee99** [comment]
Are you using VC2017 or VC2015? If you have MSVC2017 installed, you should open the project in VS2017.

**Comment by andy-maginn** [comment]
I am compiling with VC2015 using the solution ‪C:\leela-zero\msvc\leela-zero2015.sln and getting the following output.
1>------ Rebuild All started: Project: leela-zero, Configuration: Debug x64 ------
1>  Zobrist.cpp
1>  Utils.cpp
1>c:\leela-zero\leela-zero\src\utils.cpp(65): warning C4800: 'DWORD': forcing value to bool 'true' or 'false' (performance warning)
1>  UCTSearch.cpp
1>c:\leela-zero\leela-zero\src\uctsearch.cpp(136): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>c:\leela-zero\leela-zero\src\uctsearch.cpp(588): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>  UCTNodeRoot.cpp
1>  UCTNode.cpp
1>  Tuner.cpp
1>c:\leela-zero\leela-zero\src\tuner.cpp(135): warning C4244: '*=': conversion from 'unsigned __int64' to 'int', possible loss of data
1>c:\leela-zero\leela-zero\src\tuner.cpp(143): warning C4244: '/=': conversion from 'unsigned __int64' to 'int', possible loss of data
1>c:\leela-zero\leela-zero\src\tuner.cpp(291): warning C4267: '*=': conversion from 'size_t' to 'int', possible loss of data
1>c:\leela-zero\leela-zero\src\tuner.cpp(413): warning C4244: '=': conversion from 'float' to 'unsigned int', possible loss of data
1>  Training.cpp
1>c:\leela-zero\leela-zero\src\training.cpp(119): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
1>c:\leela-zero\leela-zero\src\training.cpp(150): warning C4800: 'const float': forcing value to bool 'true' or 'false' (performance warning)
1>  Timing.cpp
1>c:\leela-zero\leela-zero\src\timing.cpp(26): warning C4244: 'return': conversion from '__int64' to 'int', possible loss of data
1>  TimeControl.cpp
1>  SMP.cpp
1>  SGFTree.cpp
1>  SGFParser.cpp
1>  Random.cpp
1>  OpenCLScheduler.cpp
1>  OpenCL.cpp
1>c:\leela-zero\leela-zero\src\opencl.cpp(1016): warning C4244: '+=': conversion from 'float' to 'int', possible loss of data
1>  NNCache.cpp
1>  Network.cpp
1>c:\leela-zero\leela-zero\src\network.cpp(217): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data
1>c:\leela-zero\leela-zero\src\network.cpp(371): warning C4267: 'argument': conversion from 'size_t' to 'const int', possible loss of data
1>c:\leela-zero\leela-zero\src\network.cpp(378): warning C4267: 'argument': conversion from 'size_t' to 'const int', possible loss of data
1>c:\leela-zero\leela-zero\src\network.cpp(405): warning C4267: 'argument': conversion from 'size_t' to 'const int', possible loss of data
1>c:\leela-zero\leela-zero\src\network.cpp(421): warning C4267: 'argument': conversion from 'size_t' to 'const int', possible loss of data
1>c:\leela-zero\leela-zero\src\network.cpp(426): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
1>c:\leela-zero\leela-zero\src\network.cpp(433): warning C4267: 'argument': conversion from 'size_t' to 'const int', possible loss of data
1>c:\leela-zero\leela-zero\src\network.cpp(436): warning C4267: 'argument': conversion from 'size_t' to 'const int', possible loss of data
1>c:\leela-zero\leela-zero\src\network.cpp(443): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
1>c:\leela-zero\leela-zero\src\network.cpp(448): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
1>c:\leela-zero\leela-zero\src\network.cpp(449): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
1>c:\leela-zero\leela-zero\src\network.cpp(651): warning C4267: 'argument': conversion from 'size_t' to 'const int', possible loss of data
1>c:\leela-zero\leela-zero\src\network.cpp(652): warning C4267: 'argument': conversion from 'size_t' to 'const int', possible loss of data
1>c:\leela-zero\leela-zero\src\network.cpp(778): warning C4267: 'argument': conversion from 'size_t' to 'const int', possible loss of data
1>c:\leela-zero\leela-zero\src\network.cpp(790): warning C4267: 'argument': conversion from 'size_t' to 'const int', possible loss of data
1>c:\leela-zero\leela-zero\src\network.cpp(799): warning C4267: 'argument': conversion from 'size_t' to 'const int', possible loss of data
1>c:\leela-zero\leela-zero\src\network.cpp(1000): warning C4244: '=': conversion from 'float' to 'int', possible loss of data
1>c:\leela-zero\leela-zero\src\network.cpp(1010): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>c:\leela-zero\leela-zero\src\network.cpp(1083): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>c:\leela-zero\leela-zero\src\network.cpp(672): warning C4267: 'argument': conversion from 'size_t' to 'const int', possible loss of data
1>  c:\leela-zero\leela-zero\src\network.cpp(805): note: see reference to function template instantiation 'void convolve<1>(const std::size_t,const std::vector<float,std::allocator<_Ty>> &,const std::vector<_Ty,std::allocator<_Ty>> &,const std::vector<_Ty,std::allocator<_Ty>> &,std::vector<_Ty,std::allocator<_Ty>> &)' being compiled
1>          with
1>          [
1>              _Ty=float
1>          ]
1>c:\leela-zero\leela-zero\src\network.cpp(691): warning C4267: 'argument': conversion from 'size_t' to 'const blasint', possible loss of data
1>  Leela.cpp
1>  KoState.cpp
1>  GTP.cpp
1>  Generating Code...
1>  Compiling...
1>  GameState.cpp
1>  FullBoard.cpp
1>  FastState.cpp
1>  FastBoard.cpp
1>  Generating Code...
1>UCTNodeRoot.obj : error LNK2001: unresolved external symbol "public: __cdecl UCTNodePointer::~UCTNodePointer(void)" (??1UCTNodePointer@@QEAA@XZ)
1>UCTSearch.obj : error LNK2001: unresolved external symbol "public: __cdecl UCTNodePointer::~UCTNodePointer(void)" (??1UCTNodePointer@@QEAA@XZ)
1>GameState.obj : error LNK2001: unresolved external symbol "public: __cdecl UCTNodePointer::~UCTNodePointer(void)" (??1UCTNodePointer@@QEAA@XZ)
1>GTP.obj : error LNK2001: unresolved external symbol "public: __cdecl UCTNodePointer::~UCTNodePointer(void)" (??1UCTNodePointer@@QEAA@XZ)
1>Leela.obj : error LNK2001: unresolved external symbol "public: __cdecl UCTNodePointer::~UCTNodePointer(void)" (??1UCTNodePointer@@QEAA@XZ)
1>UCTNode.obj : error LNK2001: unresolved external symbol "public: __cdecl UCTNodePointer::~UCTNodePointer(void)" (??1UCTNodePointer@@QEAA@XZ)
1>UCTNode.obj : error LNK2019: unresolved external symbol "public: __cdecl UCTNodePointer::UCTNodePointer(class UCTNodePointer &&)" (??0UCTNodePointer@@QEAA@$$QEAV0@@Z) referenced in function "void __cdecl std::_Construct<class UCTNodePointer,class UCTNodePointer>(class UCTNodePointer *,class UCTNodePointer &&)" (??$_Construct@VUCTNodePointer@@V1@@std@@YAXPEAVUCTNodePointer@@$$QEAV1@@Z)
1>UCTNodeRoot.obj : error LNK2001: unresolved external symbol "public: __cdecl UCTNodePointer::UCTNodePointer(class UCTNodePointer &&)" (??0UCTNodePointer@@QEAA@$$QEAV0@@Z)
1>UCTNode.obj : error LNK2019: unresolved external symbol "public: __cdecl UCTNodePointer::UCTNodePointer(short,float)" (??0UCTNodePointer@@QEAA@FM@Z) referenced in function "public: void __cdecl std::allocator<class UCTNodePointer>::construct<class UCTNodePointer,int const &,float const &>(class UCTNodePointer *,int const &,float const &)" (??$construct@VUCTNodePointer@@AEBHAEBM@?$allocator@VUCTNodePointer@@@std@@QEAAXPEAVUCTNodePointer@@AEBHAEBM@Z)
1>UCTNode.obj : error LNK2019: unresolved external symbol "public: class UCTNodePointer & __cdecl UCTNodePointer::operator=(class UCTNodePointer &&)" (??4UCTNodePointer@@QEAAAEAV0@$$QEAV0@@Z) referenced in function "class std::reverse_iterator<class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class UCTNodePointer> > > > __cdecl std::_Buffered_merge_backward_unchecked<class std::reverse_iterator<class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class UCTNodePointer> > > >,class UCTNodePointer *,class std::reverse_iterator<class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class UCTNodePointer> > > >,class NodeComp>(class std::reverse_iterator<class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class UCTNodePointer> > > >,class std::reverse_iterator<class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class UCTNodePointer> > > >,class UCTNodePointer *,class UCTNodePointer *,class std::reverse_iterator<class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class UCTNodePointer> > > >,class NodeComp &,bool)" (??$_Buffered_merge_backward_unchecked@V?$reverse_iterator@V?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@VUCTNodePointer@@@std@@@std@@@std@@@std@@PEAVUCTNodePointer@@V12@VNodeComp@@@std@@YA?AV?$reverse_iterator@V?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@VUCTNodePointer@@@std@@@std@@@std@@@0@V10@0PEAVUCTNodePointer@@10AEAVNodeComp@@_N@Z)
1>UCTNodeRoot.obj : error LNK2001: unresolved external symbol "public: class UCTNodePointer & __cdecl UCTNodePointer::operator=(class UCTNodePointer &&)" (??4UCTNodePointer@@QEAAAEAV0@$$QEAV0@@Z)
1>UCTNode.obj : error LNK2019: unresolved external symbol "public: void __cdecl UCTNodePointer::inflate(void)const " (?inflate@UCTNodePointer@@QEBAXXZ) referenced in function "public: class UCTNode & __cdecl UCTNode::get_best_root_child(int)" (?get_best_root_child@UCTNode@@QEAAAEAV1@H@Z)
1>UCTNodeRoot.obj : error LNK2001: unresolved external symbol "public: void __cdecl UCTNodePointer::inflate(void)const " (?inflate@UCTNodePointer@@QEBAXXZ)
1>UCTNode.obj : error LNK2019: unresolved external symbol "public: bool __cdecl UCTNodePointer::valid(void)const " (?valid@UCTNodePointer@@QEBA_NXZ) referenced in function "public: class UCTNode * __cdecl UCTNode::uct_select_child(int,bool)" (?uct_select_child@UCTNode@@QEAAPEAV1@H_N@Z)
1>UCTNode.obj : error LNK2019: unresolved external symbol "public: int __cdecl UCTNodePointer::get_visits(void)const " (?get_visits@UCTNodePointer@@QEBAHXZ) referenced in function "public: bool __cdecl NodeComp::operator()(class UCTNodePointer const &,class UCTNodePointer const &)" (??RNodeComp@@QEAA_NAEBVUCTNodePointer@@0@Z)
1>UCTSearch.obj : error LNK2001: unresolved external symbol "public: int __cdecl UCTNodePointer::get_visits(void)const " (?get_visits@UCTNodePointer@@QEBAHXZ)
1>UCTNode.obj : error LNK2019: unresolved external symbol "public: float __cdecl UCTNodePointer::get_score(void)const " (?get_score@UCTNodePointer@@QEBAMXZ) referenced in function "public: bool __cdecl NodeComp::operator()(class UCTNodePointer const &,class UCTNodePointer const &)" (??RNodeComp@@QEAA_NAEBVUCTNodePointer@@0@Z)
1>UCTNode.obj : error LNK2019: unresolved external symbol "public: bool __cdecl UCTNodePointer::active(void)const " (?active@UCTNodePointer@@QEBA_NXZ) referenced in function "public: class UCTNode * __cdecl UCTNode::uct_select_child(int,bool)" (?uct_select_child@UCTNode@@QEAAPEAV1@H_N@Z)
1>UCTNode.obj : error LNK2019: unresolved external symbol "public: float __cdecl UCTNodePointer::get_eval(int)const " (?get_eval@UCTNodePointer@@QEBAMH@Z) referenced in function "public: bool __cdecl NodeComp::operator()(class UCTNodePointer const &,class UCTNodePointer const &)" (??RNodeComp@@QEAA_NAEBVUCTNodePointer@@0@Z)
1>UCTNodeRoot.obj : error LNK2019: unresolved external symbol "public: int __cdecl UCTNodePointer::get_move(void)const " (?get_move@UCTNodePointer@@QEBAHXZ) referenced in function "public: class std::unique_ptr<class UCTNode,struct std::default_delete<class UCTNode> > __cdecl UCTNode::find_child(int)" (?find_child@UCTNode@@QEAA?AV?$unique_ptr@VUCTNode@@U?$default_delete@VUCTNode@@@std@@@std@@H@Z)
1>C:\leela-zero\leela-zero\msvc\x64\Debug\leelaz.exe : fatal error LNK1120: 11 unresolved externals
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by Splee99** [comment]
UCTNodePointer.cpp needs to be added to the project (2015).

**Comment by alreadydone** [comment]
I fixed VS2015 a while ago. It's in /next branch now.

**Comment by gcp** [comment]
Already fixed in the development version.
