### ISSUE TITLE
The link for “raw sgf files” downloading is broken

### ISSUE THREAD

**Issue by alphaladder** [gcp/leela-zero#1545]
We could not download any training raw sgf file now.
http://storage.sjeng.org/zero/

**Comment by l1t1** [comment]
http://zero.sjeng.org/self-plays can download sgf

**Comment by alphaladder** [comment]
No, we still need batch downloading

**Comment by gcp** [comment]
The storage server seems to be down.

https://github.com/gcp/leela-zero/issues/167#issuecomment-391907547

**Comment by 2OJOS** [comment]
Link still down? Oh, no! I lost my database, damn it...
