### ISSUE TITLE
why  the amount of  lzs'  is much more than elfs' in recent long-moves self-games?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1546]
in those moves more than 360, only 1 elf, 46 lz

Self-Play Hash | Network | Winner | Move Count | Started | Duration | Download | Client | Version
-- | -- | -- | -- | -- | -- | -- | -- | --
08555ba6f4026428a09a96490e655f51 | d0187996 | white | 723 | 75.7 minutes ago | 71.4 minutes | sgf | 39 | 16
95423648b6fe7faab7ebd06284a03db0 | d0187996 | white | 723 | 56.7 minutes ago | 51.9 minutes | sgf | 40 | 16
427e26d59ba007a0220d62c0921c19d2 | d0187996 | black | 723 | 112.4 minutes ago | 104.0 minutes | sgf | 29 | 16
a077978500db224f145b1bf06af81a7e | d0187996 | black | 723 | 169.1 minutes ago | 158.2 minutes | sgf | 32 | 16
57f780435df8e35cf34371e4c3a18cdb | d0187996 | white | 723 | 161.7 minutes ago | 149.1 minutes | sgf | 1 | 16
122177bf55e18399f469d9baedc0881f | d0187996 | black | 723 | 155.4 minutes ago | 138.8 minutes | sgf | 1 | 16
50fd155b4f8d1177c9a81c141b0cccfc | d0187996 | black | 723 | 187.5 minutes ago | 170.5 minutes | sgf | 1 | 16
78132e17d3cea5d8505331f400aa2270 | d0187996 | black | 723 | 167.3 minutes ago | 149.7 minutes | sgf | 1 | 16
022df47e0fb3632a5c28dea0a657b83a | d0187996 | white | 723 | 183.1 minutes ago | 163.4 minutes | sgf | 1 | 16
37e47ce152dc98e7376c16303465dc68 | d0187996 | white | 720 | 170.8 minutes ago | 151.8 minutes | sgf | 1 | 16
86ece9617a749e7279614177a2b3b642 | d0187996 | white | 717 | 155.1 minutes ago | 147.0 minutes | sgf | 65 | 16
8b7c1591cb8506a5469fd805094c0705 | d0187996 | black | 714 | 167.3 minutes ago | 154.4 minutes | sgf | 1 | 16
8b5f59b41c15060fb6d9ea880dd682d7 | d0187996 | black | 703 | 155.9 minutes ago | 142.2 minutes | sgf | 1 | 16
e58fb384ab9f6d811696d44b3fd71005 | d0187996 | white | 700 | 175.1 minutes ago | 165.1 minutes | sgf | 1 | 16
c44302133438c380af5284d4e8269e9f | d0187996 | black | 692 | 165.7 minutes ago | 153.8 minutes | sgf | 1 | 16
bb8897a7ca86635b42bed6769bc3d447 | d0187996 | white | 679 | 163.5 minutes ago | 148.3 minutes | sgf | 104 | 16
c627e8a666a3ba3862094f8e0f98cee7 | d0187996 | black | 666 | 148.1 minutes ago | 146.8 minutes | sgf | 1 | 16
21827db8aa4afaeb4c9777b8b8b1fc97 | d0187996 | black | 661 | 151.2 minutes ago | 148.1 minutes | sgf | 1 | 16
70b2745c568c2c0b90071a80c15c2332 | d0187996 | black | 651 | 147.1 minutes ago | 127.9 minutes | sgf | 1 | 16
e7413a3682e41af5157b1d996261a373 | d0187996 | white | 650 | 167.4 minutes ago | 160.1 minutes | sgf | 1 | 16
5e0aec8ca1bb996cf3587537b3847fff | d0187996 | white | 646 | 135.1 minutes ago | 133.9 minutes | sgf | 1 | 16
5494db48024c28f369f49aec6f65815e | d0187996 | white | 638 | 247.2 minutes ago | 239.9 minutes | sgf | 48 | 16
c4132306bd579c87528b17c0f5d5fe1f | d0187996 | white | 627 | 531.3 minutes ago | 513.0 minutes | sgf | 115 | 16
e3514414de0a7655b55bb1f296688108 | d0187996 | black | 621 | 165.7 minutes ago | 156.4 minutes | sgf | 1 | 16
924334b616aa407a190358a07e15ffdc | d0187996 | black | 616 | 148.1 minutes ago | 129.3 minutes | sgf | 1 | 16
09a49806e1fceb76d2f1093a5c2e661f | d0187996 | white | 605 | 145.9 minutes ago | 133.0 minutes | sgf | 1 | 16
8b019ad2b8074058b28b6c622d1e0878 | d0187996 | white | 598 | 137.4 minutes ago | 117.5 minutes | sgf | 1 | 16
c0fabe8e58313283672b3cf1fcdc4f71 | d0187996 | white | 594 | 130.3 minutes ago | 127.8 minutes | sgf | 21 | 16
7aa02da8dfc9960e6f06a64cc6fb67dd | d0187996 | white | 586 | 147.0 minutes ago | 135.7 minutes | sgf | 1 | 16
0aef71316f695e53406e0b07276aaa2d | d0187996 | black | 577 | 124.8 minutes ago | 113.1 minutes | sgf | 1 | 16
4f53390b734ef80ca245a88572526912 | d0187996 | black | 571 | 98.6 minutes ago | 88.9 minutes | sgf | 81 | 16
189df08f884f1ef94ac8af33648414f5 | d0187996 | black | 548 | 109.6 minutes ago | 102.7 minutes | sgf | 1 | 16
2772ead585e1fbc2168fc8ee380774a1 | d0187996 | black | 528 | 116.2 minutes ago | 110.8 minutes | sgf | 1 | 16
ea5473b5819e7b3b9c845f4838b00dbb | d0187996 | white | 528 | 400.8 minutes ago | 392.7 minutes | sgf | 64 | 16
4c9c01c27976e32412f9abc7b26f7a45 | d0187996 | black | 517 | 57.8 minutes ago | 50.5 minutes | sgf | 57 | 16
57574fb84ba7e2b1b7577e43833aa096 | d0187996 | black | 506 | 105.6 minutes ago | 85.7 minutes | sgf | 29 | 16
7d05f5aa061ae61dd91127ba9d8a6a58 | d0187996 | black | 504 | 119.1 minutes ago | 105.9 minutes | sgf | 1 | 16
b780a3bc94d133a52946ff0fe71aa9c2 | d0187996 | white | 503 | 103.8 minutes ago | 100.4 minutes | sgf | 1 | 16
177039f3debcdd0f0fe4a699c1e22866 | d0187996 | black | 488 | 117.7 minutes ago | 110.5 minutes | sgf | 1 | 16
156532ecfb883ff6fd39382fcf2b72e5 | d0187996 | black | 451 | 93.7 minutes ago | 81.5 minutes | sgf | 1 | 16
ec4f4d542c33e54de6e5020ee6d3cd2d | d0187996 | white | 445 | 38.9 minutes ago | 34.1 minutes | sgf | 41 | 16
2c8c78728cdfe60e9d611862ce7810d2 | d0187996 | white | 443 | 88.8 minutes ago | 82.7 minutes | sgf | 1 | 16
0ab7163d4fd073989be2623172dcf07b | d0187996 | black | 437 | 91.3 minutes ago | 88.2 minutes | sgf | 1 | 16
7341d7b5debbbd29cb8650bd84af6df1 | d0187996 | white | 426 | 106.2 minutes ago | 89.7 minutes | sgf | 1 | 16
f9bf593f986109ae3d2d3ba1c45a286f | d0187996 | black | 408 | 54.8 minutes ago | 49.3 minutes | sgf | 49 | 16
eed5e7f22231c2caadba04232960e452 | d0187996 | white | 388 | 83.3 minutes ago | 72.3 minutes | sgf | 1 | 16
7fa55dbb9aafa1c899e6d92a7f993aef | 62b5417b | black | 374 | 36.7 minutes ago | 35.8 minutes | sgf | 8 | 16

**Comment by l1t1** [comment]
open http://zero.sjeng.org/self-plays in firefox, then click on move count header

**Comment by rchs819** [comment]
it's because ELF games always have resign threshold set to 5
Due to ELF's sharp value head, these games are likely to be shorter than normal LZ games.

```
        if ((req.params.autogtp >= 16 || req.params.leelaz >= 0.14) && Math.random() < 0.25) {
            task.hash = ELF_NETWORK;
            options.resignation_percent = "5";
        }
```

**Comment by l1t1** [comment]
thanks @ rchs819
