### ISSUE TITLE
AQ android version supports leelaz and elf weight

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1556]
https://tieba.baidu.com/p/5746619226

**Comment by l1t1** [comment]
2 months ago, it only support AQ file
https://github.com/gcp/leela-zero/issues/1285

**Comment by l1t1** [comment]
the weight in the apk file
![2018-06-15_101047](https://user-images.githubusercontent.com/23301704/41446856-7b2b6970-7084-11e8-8ddd-338118097672.png)
i am curious how did it supports two different format weight?

**Comment by rchs819** [comment]
@l1t1 
> i am curious how did it supports two different format weight?

Maybe you should ask this question on baidu thread.

**Comment by l1t1** [comment]
thanks @rchs819

**Comment by l1t1** [comment]
use dex2jar and jd-gui, find some class related leelaz
![2018-06-15_123559](https://user-images.githubusercontent.com/23301704/41450153-61539220-7098-11e8-9bb4-7bf03393a8c2.png)

**Comment by l1t1** [comment]
2018-6-18 09:47
When it comes to home use, try to use the latest 1.2.0.5, the previous version has obvious BUG. The performance of things I roughly talk about, I use the low-end play dragon 660 test a bit, the latest version of open 30 seconds to run the official weight of 30 seconds under the time limit is about 350PO calculations, if you use 10B mixed little weight 2.5 times faster. If you use ELF weights, it's about half as slow as official power. In the case of chess power, if the calculation is made at each step of 30 seconds, under normal circumstances, no matter whether it is the official power or the small weight of the 10B mixed blood, the ELF weights are not. However, ELF's sign is really bad, so long as it is attacked, it will not be saved. The weight of official powers and mixed-bloods was originally higher than that of ELF plus more calculations per unit of time, so the sign performance was much better than ELF. So how to choose it needs to be mastered.
If it is the latest 845 chip, theoretical value should be more than 2 times stronger than 660. It is estimated that loading ELF weights will look like 400PO within 30 seconds. In addition, I asked the author about the GPU version. He replied that due to some special features of the mobile phone GPU version, there are still difficulties in implementation.

**Comment by l1t1** [comment]
![screenshot_2018-06-20-16-58-13-0732119940](https://user-images.githubusercontent.com/23301704/41648565-da4699d6-74ab-11e8-93e1-6bd9882ad84f.png)
![screenshot_2018-06-20-16-57-51-1549513776](https://user-images.githubusercontent.com/23301704/41648567-dac739ec-74ab-11e8-88ba-3e64e75ea6a8.png)
820 4g 2n/s elf weight

**Comment by herazul** [comment]
So what is better to play on smartphone ? GridMaster or AQ ?

**Comment by l1t1** [comment]
new version  http://www.flygo.net/bbs/forum.php?mod=viewthread&tid=106968&extra=page%3D1&mobile=2

**Comment by l1t1** [comment]
for Chinese user, as GridMaster doesn't support Chinese language now, it's better to use AQ.

**Comment by l1t1** [comment]
the AQ android edition auther says only support arm64-v8a cpu now

**Comment by l1t1** [comment]
![2018-06-21_091548](https://user-images.githubusercontent.com/23301704/41692525-5d68cdb6-7533-11e8-9702-765127028ef2.png)
add one weight file
