### ISSUE TITLE
Compiling under Ubuntu 16.04

### ISSUE THREAD

**Issue by as0770** [gcp/leela-zero#1559]
I have had no problems compiling the official releases so far. After compiling the latest source I get following error message:
```
./leelaz
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::logic_error> >'
  what():  character conversion failed
```

**Comment by gcp** [comment]
I've had this error before. It's related to old objects, your compiler, or the boost installation. I forgot which, though.

It's not related to Leela itself.

**Comment by as0770** [comment]
Just tried to compile v0.15, and indeed it doesn't work anymore. Something has changed here, I'll take a look. Thanks.
