### ISSUE TITLE
Does Leela 0110 use "Last Good Reply"?

### ISSUE THREAD

**Issue by panda0307** [gcp/leela-zero#1562]
Hi,
Does Leela 0110 use "Last Good Reply"?
Thanks.

**Comment by gcp** [comment]
No, AFAIK it's more useful for MC based programs. It didn't even really work in Leela 0.11 IIRC. But there are many variations possible.

**Comment by gcp** [comment]
I replied to this assuming the question was about Leela Zero, obviously.
