### ISSUE TITLE
Test match of Leela Master?

### ISSUE THREAD

**Issue by pondturtle** [gcp/leela-zero#1563]
So this guy used human games to "enhance" LZ network

https://github.com/pangafu/LeelaMasterWeight

I ran couple games on my PC against LZ and quite often LM seems to create big semeais LZ tends to lose more often then not. 

I understand this is out of the scope of LZ project, but could you maybe run match batch of 400 games with "experimental network" tag? Would be very interesting to see how they compare in strength.

**Comment by roy7** [comment]
@pondturtle 15 or 20 block network?

**Comment by pondturtle** [comment]
The stronger one preferably? I assume that is 195x15 one?

**Comment by roy7** [comment]
I have no idea which is stronger, I've never used them. :)

**Comment by roy7** [comment]
192x15 it is.

**Comment by roy7** [comment]
Whew, had to follow these instructions 

https://stackoverflow.com/questions/48133080/how-to-download-a-google-drive-url-via-curl-or-wget

to get this command line

> curl -L -o weights.zip "https://drive.google.com/uc?export=download&id=1lfyetw8ohJZg-bSkUirDllVdVMpXMX9a"

to do a remote download. Grr. :)

**Comment by john45678** [comment]
I,m not sure which is stronger, but the last few updates were the 15B nets. Its at least a month since the last 20B (W11) was made available.

**Comment by roy7** [comment]
Web site says 20B is "completed".

**Comment by pondturtle** [comment]
That is why I made uneducated guess 195x15 is the stronger one. Also because I know it can at least match current LZ net.

**Comment by PhilipFRipper** [comment]
the 20x128 is much weaker than the 15x192.  iirc the 20x128 was already tested against an LZ 10x128.  But I don't think the 15x195 LM has ever been tested.

**Comment by roy7** [comment]
Ok I think I added it right.

**Comment by diadorak** [comment]
According to the instructions, G13 of 15x192 is trained with 800,000 games prior to #146 (0cb74be2) + 30% human games. The current learning is 0.0005, higher than 0.0002, the rate of the official training.

G13训练的棋谱利用是#146(0cb74be2)之前的80w盘棋谱随机采样+30%的人谱掺杂而成，目前学习率在0.0005，高于官权的0.0002的学习率。

**Comment by Splee99** [comment]
Just run a game of G13 with latest LZ weight. It seems that LM is good at life and death with ko. Happened twice in one game and eventually LM killed one of LZ's group (and won). Test setup was 15 seconds per move, about 1700 playouts per move.

**Comment by roy7** [comment]
Here's the full match results so it's easier to find in the future after it scrolls away.

http://zero.sjeng.org/match-games/5b26c77d48e3e5462acf0c4a

**Comment by roy7** [comment]
There was a couple newer once than the github had linked. I'll run a test match on the actual latest 15 block one tomorrow.

**Comment by WYVYW** [comment]
Is it possible to feed LZ just with human-handi-cap games?

**Comment by l1t1** [comment]
it seems as strong as the bot only weight

**Comment by pangafu** [comment]
Hello every one~ I did leela master weight and I notice it has been test today, thanks @roy7 @pondturtle .
Very pleasure to see mix with the human sgf,  the weight is not very weaker than the only zero one, when you play with leela master, you will see it more move like human does.

**Comment by pondturtle** [comment]
Thank YOU for making it. Pretty neat to have something more human style to play against.

It tends to be very agressive though. I wonder if that is because human games are tygem sourced. Do you think there could be different, more didactic play style if games were sourced from more civilized place like pandanet for example?

**Comment by 22nsuk** [comment]
@pangafu 
I wonder if you can share raw sgf files with training files.
Apart from this, I am using your network very well. Thanks!

**Comment by pangafu** [comment]
@pondturtle @22nsuk 
My human sgf is mainly download from https://github.com/yenw/computer-go-dataset
I used AI, Professional, TYGEM, Tom and CGOS game, mix with leelazero sgf.

G01 - G03 : 90% leelazero sgf + 10% human style game
G04 - G08 : 80% leelazero sgf + 20% human style game
G09 - G13 : 70% leelazero sgf + 30% human style game
The training set is keeping change by random sample in each 256k step. 

And I will keep to increase human style game percent to see when the strength of weight will decent, and in our test, the style of leela master weight changed very frequently between every weight, and the strength is almost same. So you can test each weight to find the style you love.

In my test, ELO of the weight:
G09 - G13 > G04 - G08 > G01 - G03 > W > E

**Comment by pcengine** [comment]
@pangafu Could you please check your google drive? It seems there are only E-series and W-series left. I couldn't see any weights of G-series. Thanks again.

**Comment by pangafu** [comment]
@pcengine
G-series is still there~ please reload your web browser

**Comment by pcengine** [comment]
@pangafu Thanks, I refreshed my browser and it's back. It must be my browser's problem.

**Comment by pangafu** [comment]
@pcengine please enjoy human style go game.
