### ISSUE TITLE
Is there an option to not resign, and pass instead of making foolish moves in the end?

### ISSUE THREAD

**Issue by zhanzhenzhen** [gcp/leela-zero#1564]
Is there an option to not resign, and pass instead of making foolish moves in the end?

**Comment by TFiFiE** [comment]
What happens if you combine `--resignpct 0` with `--dumbpass`?

**Comment by alphaladder** [comment]
Your suggestion is not reasonable

**Comment by zhanzhenzhen** [comment]
@TFiFiE with `--dumbpass` it passes earlier. This basically meets my requirements, though still not as early as I expect. But that's OK.
@alphaladder Why it's not reasonable?

**Comment by gcp** [comment]
With ```--dumbpass``` disabled, passing and resigning are often the same thing...

**Comment by zhanzhenzhen** [comment]
@gcp So if using `-r 0` we should always also use `--dumbpass`?

**Comment by gcp** [comment]
No. I'm pointing out that without --dumbpass, the engine will pass even when this loses instantly, so it's really the same as resigning.

What you're trying to do is not supported by the bot because it makes little sense. So the question is: what are you *really* trying to achieve?

**Comment by zhanzhenzhen** [comment]
@gcp I want it to never resign, and end normally (make passes after all points are occupied).

But I did what @TFiFiE suggested. Adding `--dumbpass` really can make it pass earlier.

**Comment by zhanzhenzhen** [comment]
When not combining with `--dumbpass`, `-r 0` makes it make mad moves in the end when losing. But combining with `--dumbpass`, it seems it just makes a little such moves, and soon starts to pass.
