### ISSUE TITLE
Tensor flow is updated recently and someone had used  to speed lz chess . How about our lz?

### ISSUE THREAD

**Issue by alphaladder** [gcp/leela-zero#1566]
Leela Chess engine had applied the latest tensor flow techniques now and the training speed is increased very fast! Shall we use it on our lz.
![19415ea9-989e-4e72-a140-b09bf9f7e0f0](https://user-images.githubusercontent.com/38591796/41514818-c63a40c2-725e-11e8-862e-349026dcc372.jpeg)

**Comment by alphaladder** [comment]
Here is the link：http://testserver.lczero.org/

**Comment by Eddh** [comment]
My understanding is that for this gain you need CUDA, and it would imply a change in the license of LeelaZero.

**Comment by gcp** [comment]
>for this gain you need CUDA

CUDA is fine, the problem is cuDNN. The gain is from a combination of cuDNN + batching. Batching is much more important for chess because it has much smaller boards.
