### ISSUE TITLE
Maybe we can make all 256k pass automatically and cancel the test matchs.

### ISSUE THREAD

**Issue by ainixingo** [gcp/leela-zero#1568]
Enter file name to read: 118.txt

count = [ 10357481 ], positive number = [ 4784494 ] [ 0.4619 ] , sum = -9093.700383, avg = -0.000878
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 48083 ] [ 4310649 ] [ 322879 ] [ 102883 ]    [ 121072 ] [ 331704 ] [ 5066864 ] [ 53347 ] Score:[ 7.34 ]

Enter file name to read: 122.txt

count = [ 10357481 ], positive number = [ 4793326 ] [ 0.4628 ] , sum = -8769.472504, avg = -0.000847
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 42357 ] [ 4308511 ] [ 336110 ] [ 106348 ]    [ 124124 ] [ 345437 ] [ 5046470 ] [ 48124 ] Score:[ 7.60 ]

Enter file name to read: 125.txt

count = [ 10357481 ], positive number = [ 4803212 ] [ 0.4637 ] , sum = -8467.218693, avg = -0.000817
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 37252 ] [ 4305298 ] [ 350922 ] [ 109740 ]    [ 127663 ] [ 359771 ] [ 5023484 ] [ 43351 ] Score:[ 7.88 ]

Enter file name to read: 127.txt

count = [ 10357481 ], positive number = [ 4806224 ] [ 0.4640 ] , sum = -8362.373981, avg = -0.000807
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 35339 ] [ 4303491 ] [ 356560 ] [ 110834 ]    [ 130321 ] [ 365716 ] [ 5013692 ] [ 41528 ] Score:[ 8.00 ]

Enter file name to read: 131.txt

count = [ 10357481 ], positive number = [ 4824019 ] [ 0.4658 ] , sum = -7830.147648, avg = -0.000756
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 27981 ] [ 4293064 ] [ 383882 ] [ 119092 ]    [ 136547 ] [ 394312 ] [ 4968333 ] [ 34270 ] Score:[ 8.56 ]

Enter file name to read: 135.txt

count = [ 10357481 ], positive number = [ 4832739 ] [ 0.4666 ] , sum = -7522.055070, avg = -0.000726
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 24834 ] [ 4287009 ] [ 398801 ] [ 122095 ]    [ 140973 ] [ 409556 ] [ 4943144 ] [ 31069 ] Score:[ 8.85 ]

Enter file name to read: 137.txt

count = [ 10357481 ], positive number = [ 4838702 ] [ 0.4672 ] , sum = -7313.373181, avg = -0.000706
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 22666 ] [ 4282343 ] [ 408622 ] [ 125071 ]    [ 143248 ] [ 420289 ] [ 4926403 ] [ 28839 ] Score:[ 9.05 ]

Enter file name to read: 140.txt

count = [ 10357481 ], positive number = [ 4844083 ] [ 0.4677 ] , sum = -7146.185834, avg = -0.000690
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 20932 ] [ 4279924 ] [ 416708 ] [ 126519 ]    [ 144941 ] [ 427049 ] [ 4914229 ] [ 27179 ] Score:[ 9.19 ]

Enter file name to read: 143.txt

count = [ 10357481 ], positive number = [ 4849213 ] [ 0.4682 ] , sum = -6955.744161, avg = -0.000672
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 19061 ] [ 4277319 ] [ 424516 ] [ 128317 ]    [ 146786 ] [ 436279 ] [ 4899819 ] [ 25384 ] Score:[ 9.35 ]

Enter file name to read: 145.txt

count = [ 10357481 ], positive number = [ 4849202 ] [ 0.4682 ] , sum = -6950.052242, avg = -0.000671
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 18861 ] [ 4276233 ] [ 425207 ] [ 128901 ]    [ 147598 ] [ 435759 ] [ 4899704 ] [ 25218 ] Score:[ 9.37 ]

Enter file name to read: 147.txt

count = [ 10357481 ], positive number = [ 4849543 ] [ 0.4682 ] , sum = -6881.080303, avg = -0.000664
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 17987 ] [ 4272408 ] [ 429389 ] [ 129759 ]    [ 148471 ] [ 441260 ] [ 4893842 ] [ 24365 ] Score:[ 9.45 ]

Enter file name to read: d01879964d578b676714251164f7289da023f14c0063b1721e5e3cd2e8d51ae0.txt

count = [ 10357481 ], positive number = [ 4851675 ] [ 0.4684 ] , sum = -6803.885949, avg = -0.000657
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 17408 ] [ 4269582 ] [ 433069 ] [ 131616 ]    [ 149220 ] [ 443970 ] [ 4888828 ] [ 23788 ] Score:[ 9.53 ]

-------------------------------------------------------------------------------------------------------------------
Here is a trend of 32k-256k in a group

Enter file name to read: 8913bff0365e29c89c99afe60398c1f96abb909c39f32f2edbe67c76d2928ed6.txt    32k

count = [ 10357481 ], positive number = [ 4852641 ] [ 0.4685 ] , sum = -6781.008793, avg = -0.000655
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 17267 ] [ 4270511 ] [ 433693 ] [ 131170 ]    [ 149051 ] [ 444647 ] [ 4887494 ] [ 23648 ] Score:[ 9.53 ]

Enter file name to read: ecd7439fee9329a869ef37c99e46293091f9d1a3337b60ecf0aae0f64306edb4.txt    64k

count = [ 10357481 ], positive number = [ 4852476 ] [ 0.4685 ] , sum = -6764.912973, avg = -0.000653       
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 17137 ] [ 4269917 ] [ 434257 ] [ 131165 ]    [ 149604 ] [ 445338 ] [ 4886529 ] [ 23534 ] Score:[ 9.54 ]

Enter file name to read: 50626328a9d4157a3920846f09caf1103e2c44f156f5b2041a73ff607ba75205.txt   96k

count = [ 10357481 ], positive number = [ 4852436 ] [ 0.4685 ] , sum = -6752.858620, avg = -0.000652    
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 17033 ] [ 4269393 ] [ 435161 ] [ 130849 ]    [ 150249 ] [ 445758 ] [ 4885628 ] [ 23410 ] Score:[ 9.56 ]

Enter file name to read: b49ffca8d23b401f278298d0df041de5093048b160406a589cf30280956b6823.txt   128k

count = [ 10357481 ], positive number = [ 4852757 ] [ 0.4685 ] , sum = -6742.435231, avg = -0.000651
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 16931 ] [ 4268982 ] [ 435302 ] [ 131542 ]    [ 150157 ] [ 446337 ] [ 4884930 ] [ 23300 ] Score:[ 9.57 ]

Enter file name to read: d008dbb5672d956f0527abcf44cc66efe1bba01be6c2cf571f98fff8254bee0b.txt

count = [ 10357481 ], positive number = [ 4852880 ] [ 0.4685 ] , sum = -6716.328567, avg = -0.000648  192k
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 16734 ] [ 4267747 ] [ 436811 ] [ 131588 ]    [ 150279 ] [ 448547 ] [ 4882699 ] [ 23076 ] Score:[ 9.60 ]

Enter file name to read: 17fc540f7581c619bf10f116d3d5be307b16c5476dba3e5ebb959c8a4726624a.txt

count = [ 10357481 ], positive number = [ 4853159 ] [ 0.4686 ] , sum = -6692.260780, avg = -0.000646  256k
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 16583 ] [ 4267178 ] [ 437637 ] [ 131761 ]    [ 150546 ] [ 450462 ] [ 4880404 ] [ 22910 ] Score:[ 9.62 ]
-------------------------------------------------------------------------------------------------------------------
Another group:
Enter file name to read: f4a31c8b265341e8a0124eeac2eebc806ef44b24337787cc1d01e1c2753c551a.txt   64k

count = [ 10357481 ], positive number = [ 4851712 ] [ 0.4684 ] , sum = -6775.889046, avg = -0.000654
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 17152 ] [ 4269523 ] [ 433373 ] [ 131664 ]    [ 150510 ] [ 444931 ] [ 4886838 ] [ 23490 ] Score:[ 9.56 ]

Enter file name to read: 910e78d17cdf268f19ee57bbd55e6be3ef37936b0924acffa6611f20261d1076.txt   96k

count = [ 10357481 ], positive number = [ 4852299 ] [ 0.4685 ] , sum = -6759.902483, avg = -0.000653
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 17053 ] [ 4268803 ] [ 434739 ] [ 131704 ]    [ 149862 ] [ 446177 ] [ 4885749 ] [ 23394 ] Score:[ 9.56 ]

Enter file name to read: 7e079dfcc7d30d6c256e28c4b06ae7db21aaab6b8294d50ecee1002dfbf8e02a.txt  128k

count = [ 10357481 ], positive number = [ 4852873 ] [ 0.4685 ] , sum = -6744.690384, avg = -0.000651
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 16931 ] [ 4268357 ] [ 435436 ] [ 132149 ]    [ 150255 ] [ 446375 ] [ 4884692 ] [ 23286 ] Score:[ 9.58 ]

Enter file name to read: b3761685bd97083406b54e7ecb83adc50fc7a1f574e0de8af4d12cccdf43e567.txt  192k

count = [ 10357481 ], positive number = [ 4853576 ] [ 0.4686 ] , sum = -6718.364891, avg = -0.000649
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 16764 ] [ 4266773 ] [ 437169 ] [ 132870 ]    [ 150383 ] [ 447819 ] [ 4882619 ] [ 23084 ] Score:[ 9.62 ]
-------------------------------------------------------------------------------------------------------------------
Score Calculation method:

#include <stdio.h>
#include <math.h>
int main()
{
    FILE *weights;
    printf("Enter file name to read: ");
    char filename[20];
    scanf("%s",&filename);
    fflush(stdin);
    double q1,q2,q3,q4,q5,q6,q7,q8,q9,count,sum;
    float num,pos,min,max,first,sd;
        weights = fopen(filename, "r");
        if (weights != NULL)
        {for (sum = count = first = 0;
            fscanf(weights, "%f", &num) == 1;sum += num,++count)
                if (num > 0.05)
                {++q1;}
                else if (num > 0.001)
                {++q2;}
                else if (num > 0.0002)
                {++q3;}
                else if (num > 0)
                {++q4;}
                else if (num > -0.0002)
                {++q5;}
                else if (num > -0.001)
                {++q6;}
                else if (num > -0.05)
                {++q7;}
            fclose(weights);
            pos=q1+q2+q3+q4;
            q8=count-q1-q2-q3-q4-q5-q6-q7;
            q9=(q4/count*161+q5/count*161+q3/count*61+q6/count*61);
            printf("\ncount = [ %.0f ], positive number = [ %.0f ] [ %.4f ] , sum = %f, avg = %f\n",count,pos,pos/count,sum-2,(sum-2)/(count-1));
            printf("10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10\n");
			printf("[ %.0f ] [ %.0f ] [ %.0f ] [ %.0f ]    [ %.0f ] [ %.0f ] [ %.0f ] [ %.0f ] Score:[ %.2f ]\n\n",q1,q2,q3,q4,q5,q6,q7,q8,q9);
        }
        else
        {
            printf("Unable to read file.\n\n" );
        }
    return main();
}

**Comment by ainixingo** [comment]
The other two 256k weights seem very powerful

Enter file name to read: 4634d903208699367a32af011d48d5f218397e909a79ffc1e3f00ecca1748293.txt

count = [ 10357481 ], positive number = [ 4853351 ] [ 0.4686 ] , sum = -6660.375827, avg = -0.000643
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 16508 ] [ 4263294 ] [ 440402 ] [ 133147 ]    [ 151448 ] [ 450921 ] [ 4879044 ] [ 22717 ] Score:[ 9.67 ]

Enter file name to read: 20b39d420d1a55e871c326fae97ce7580aac53c1b9019f1d48dab88d07555ba7.txt

count = [ 10357481 ], positive number = [ 4853664 ] [ 0.4686 ] , sum = -6663.407112, avg = -0.000643
10  --  0.05  --  0.001  --  0.0002   --   0   --   0.0002  --  0.001  --  0.05  --  10
[ 16503 ] [ 4263971 ] [ 440562 ] [ 132628 ]    [ 151200 ] [ 451579 ] [ 4878311 ] [ 22727 ] Score:[ 9.67 ]

**Comment by alreadydone** [comment]
Is there a correlation between your score and the Elo?

**Comment by alreadydone** [comment]
Sad, I thought you discovered a way to determine the strengths of networks by directly looking at the weights, since you talked about "powerful", etc. So what exactly are you claiming with the numbers/numerology?

**Comment by Tsun-hung** [comment]
Deserves to be considered

**Comment by Friday9i** [comment]
The net just tested was 256K and failed at 37.5% win rate, so it may not be such a good idea... Pity, as it would have been nice, but this result by itself seems to show it is a bad idea.

**Comment by ainixingo** [comment]
Maybe a strong network can't be reflected in -v3200

**Comment by Friday9i** [comment]
@ainixingo what do you mean exactly, should it be played with more or less visits, and why should it reflect its intrinsic strength? IMHO, significantly more visits seems unrealistic (as it would be very slow and painful) and significantly less visits seems not realistic of true "high-level games" conditions...

**Comment by ainixingo** [comment]
I means - v3200 in the test match is not enough. However , cancel the test match and pass the weights automatically could improve efficiency.

**Comment by Friday9i** [comment]
What supports your point "v3200 in test match is not enough"? I'd rather go the opposite (v800 or v1600), but it's just a feeling, I don't see clear arguments (those from #1416 seemed quite convincing, but were apparently not enough to generate a change). 
And your proposition "pass the weights automatically could improve efficiency" is contradicted by the last 256K network which did 38%: unless extremely unlucky, it is much weaker than current net, so using it would be bad...

**Comment by Friday9i** [comment]
With 123 games, typical error is about 4%, so it's 90% likely within +/-8%, ie between ~30% and 46% win rate: hence, it's enough to say it is very probably a bad network (and quite probably a very bad network).
