### ISSUE TITLE
The question about "Computing Cloud "

### ISSUE THREAD

**Issue by KID1412999** [gcp/leela-zero#157]
One of mine friend want to participate in the Leela Zero Go project,he used the "Computing Cloud (Windows 2008 server ,NIVIDA GRID M60-1Q)" ,unluckly, he was failed.
Can you give some directions to solve this problem? Thank you very much !

**Comment by jgkwok** [comment]
To help, you probably need to provide more information on what cloud computing platform he used and describe how it failed.

**Comment by odeint** [comment]
Sorry to hear that it failed! The description is too general to tell you why. If I had to guess, probably the Win 2008 doesn't have new enough OpenCL drivers installed. I'm not sure if they're available. If possible, find our the driver version and check the release notes for OpenCL support. It should be >= 1.2 to work.

**Comment by billyswong** [comment]
Looks like M60-8Q supports OpenCL while M60-1Q does not. 

http://images.nvidia.com/content/grid/pdf/GRID-vGPU-User-Guide.pdf
> 1.5. GRID vGPU features
> This release of GRID vGPU includes support for:
> ‣ DirectX 12, Direct2D, and DirectX Video Acceleration (DXVA)
> ‣ OpenGL 4.5
> ‣ NVIDIA GRID SDK (remote graphics acceleration)
> CUDA and OpenCL are supported on these virtual GPUs:
> ‣ GRID M60-8Q
> ‣ GRID M10-8Q
> ‣ GRID M6-8Q
> ‣ GRID M60-8A
> ‣ GRID M10-8A
> ‣ GRID M6-8A
