### ISSUE TITLE
Clear NNCache and search tree when komi is changed?

### ISSUE THREAD

**Issue by alreadydone** [gcp/leela-zero#1576]
I implemented [the idea](https://github.com/gcp/leela-zero/issues/1553#issuecomment-398649576) of [using color planes for komi](https://github.com/Chicoryn/dream-go/issues/25#issuecomment-381417656) at https://github.com/alreadydone/lz/tree/patch-16 (diffs: https://github.com/gcp/leela-zero/compare/next...alreadydone:patch-16). The winrate as a function of komi isn't very reasonable ~~(changes slowly near 7.5 and -7.5 but quickly between 0.5 and 1.5)~~, but it may be of some help in handicap games and may serve as a satisfactory initialization to generate self-play games in other komi. ~~(For example, after some search it thinks 3 black stones and 46.5 komi is roughly 50% winrate.)~~ ~~One may worry about endgame performance but current LZ isn't good at counting anyway; for example network d018 thinks white is winning in this game [lee019.sgf.txt](https://github.com/gcp/leela-zero/files/2122629/lee019.sgf.txt) between Zero and Lee (B+1.5).~~ (I was using the wrong formula.)

When testing this patch, I find it annoying that the NNCache and the search tree isn't cleared after changing komi (GTP command `komi 0.5`, etc.); I can edit UCTNode.cpp to set skip_cache = true, but that's just a temporary solution. Also the search tree keep getting reused and I haven't found a way to destruct it yet. Lizzie doesn't yet support GTP commands (MyLizzie does) and I'll file an issue with them; but maybe we can take komi as a command line option as well?

Since @gcp [would like to support different komi](https://github.com/gcp/leela-zero/issues/1553#issuecomment-398090110), eventually we have to deal with the problem. Is what I propose in the title the correct way to solve the problem? (I can see that if you want to dynamically adjust komi as you catch up in handicap games, you probably don't want to throw away the tree, but mixing up winrates with different komi wouldn't be sound.) Since I am not yet familiar with those parts of the code, would anyone take up the task of implementing them? I look forward to your opinions.

<details><summary>(Wrong!) Initial winrate (pure network without search) with color planes used for komi:</summary>

komi | winrate
---- | ----
46.5 | 0.047709
41.5 | 0.131447
36.5 | 0.200566
31.5 | 0.253469
26.5 | 0.325810
25.5 | 0.349543
24.5 | 0.373569
23.5 | 0.395164
22.5 | 0.410198
21.5 | 0.422089
16.5 | 0.443617
15.5 | 0.445169
14.5 | 0.445716
13.5 | 0.447277
12.5 | 0.448988
11.5 | 0.449948
10.5 | 0.450970
9.5 | 0.452125
8.5 | 0.453357
7.5 | 0.454554
6.5 | 0.455646
5.5 | 0.456762
4.5 | 0.457956
3.5 | 0.459269
2.5 | 0.461013
1.5 | 0.499029
0.5 | 0.584092
0 | 0.626206
-0.5 | 0.642766
-1.5 | 0.660542
-2.5 | 0.675055
-3.5 | 0.685991
-4.5 | 0.695529
-5.5 | 0.704723
-6.5 | 0.712431
-7.5 | 0.719309 ( = white winrate when black passes first move)
-8.5 | 0.726163
-9.5 | 0.733093
-10.5 | 0.740042
-11.5 | 0.747712
-12.5 | 0.755776
-13.5 | 0.765403
-14.5 | 0.775509
-15.5 | 0.785854
-16.5 | 0.796473
-21.5 | 0.854831
-26.5 | 0.904935
-31.5 | 0.944281
</details>

**Comment by TFiFiE** [comment]
I think you meant to do:
```
    const net_t plus_komi = 0.5f + (state->get_komi()) / (7.5f * 2);
    const net_t minus_komi = 0.5f - (state->get_komi()) / (7.5f * 2);
```

**Comment by alreadydone** [comment]
@TFiFiE Good catch! So many conclusions in the original post are invalid. I made the corrections and now am testing.

**Comment by gcp** [comment]
I vaguely remember fixing this already? Or maybe it was in the TTable when we still had that.

**Comment by alreadydone** [comment]
OK thanks, skip_cache = true actually works perfectly; the hash index to NNCache must already include the komi. It also seems that changing komi immediately create a new root state, since I see that the visit count is cleared. However, komi change only affects subsequently created states/nodes: when you undo you need to change the komi again.
