### ISSUE TITLE
Distributed Network training

### ISSUE THREAD

**Issue by dwt** [gcp/leela-zero#158]
Hi there,

I recently noticed this paper: [Large Scale Distributed Deep Networks](https://static.googleusercontent.com/media/research.google.com/de//archive/large_deep_networks_nips2012.pdf) which seems like it could be a really nice fit to train the networks faster - especially if the grow  much bigger.

I haven't found good implementations of this paper yet - there seems to be (AkkaDistBelief)[https://github.com/alexminnaar/AkkaDistBelief], but thats in Scala...

What do you think? Worth a shot?

**Comment by gcp** [comment]
Cluster of machines on a fast local interconnect is something entirely different from a herd of heterogeneous boxes over an unreliable, slow, high latency interconnect like the internet.

The successor of DistBelief is TensorFlow, which is what we're using. It also doesn't magically work over slow links, as has been pointed out many times already.

**Comment by dwt** [comment]
Well, it sems I linked the wrong paper. I probably meant this one: (Communication-Efficient Learning of Deep Networks from Decentralized Data)[https://arxiv.org/pdf/1602.05629.pdf].

I would be surprised if this is already obsoleted? Can you link me to some relevant source?

**Comment by gcp** [comment]
I was talking about the paper you originally linked. Not aware of practical results with the second one.

**Comment by dwt** [comment]
[Google seems to have an implementation on top of TensorFlow for it's keyboard](https://research.googleblog.com/2017/04/federated-learning-collaborative.html).

Sadly I haven't been able to find an example implementation though.
