### ISSUE TITLE
Runtime selection of fp16/fp32

### ISSUE THREAD

**Issue by ihavnoid** [gcp/leela-zero#1582]
https://github.com/ihavnoid/leela-zero/tree/runtime_fp16

While working on NN code restructuring, I created a patch where we can choose from fp16 and fp32 net evaluation as a command line option (instead of compile time option).  Didn't put a PR yet because this will create a PR that is too huge, so my intention is to create a series of PRs...

**Comment by gcp** [comment]
Nice! I plan to catch up on reviews today.

**Comment by ihavnoid** [comment]
Okay, runtime_fp16 is now in PR.  I will close this for now and let's continue on #1649
