### ISSUE TITLE
why 192 match is running again after 256 match finished?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1583]
just now
![2018-06-23_185022](https://user-images.githubusercontent.com/23301704/41808844-491bcb14-76d3-11e8-8541-5b128b31798b.png)
a few hours ago
![2018-06-23_185218](https://user-images.githubusercontent.com/23301704/41808851-79c357f0-76d3-11e8-95fe-e0654ecab9ea.png)

**Comment by l1t1** [comment]
is it because this game?
336 51.49%  8429b562a03dfcb8ad1f4476619f04af 71e55c75 W+Resign 203 616.2 minutes  sgf 1 16

**Comment by l1t1** [comment]
it fail again
145 : 156 (48.17%)	301 / 400	fail
2018-06-23 00:53	71e55c75
 VS  2b80a9db
188 : 173 (52.08%)	361 / 400	fail

**Comment by nutpen85** [comment]
Games that long were either run on bad hardware (maybe CPU-only) or the PC went to energy saving mode inbetween. And so the last +192K match was finished after the last +256K match. Doesn't look like a problem to me. Can be closed?

**Comment by l1t1** [comment]
thanks, it's ok at most time, but if a machine returns a dealyed result that effect promoted?
eg., a weight fails at 54.91%(246 of 448),and other weight passes after that, then the slow result return 1 win so  passed at 55.01%(247 of 449). what shall we do?
should a timeout value be set?
