### ISSUE TITLE
did the elf selfplay policy adjust?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1586]
I only got 1 task in last 2 days.
C:\Users\aaa\Downloads>find "net:" log.txt

---------- LOG.TXT
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.
net: 62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9.
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.
net: 2b80a9db004a7b05e6e389677a00f31d2c445fb3671c7f2127a9f5bb979002c9.

**Comment by rchs819** [comment]
No, I believe nothing has changed on the server side.

What's the concern here?

**Comment by l1t1** [comment]
thanks
could you post the elf  Ratio of your tasks?

**Comment by rchs819** [comment]
https://github.com/gcp/leela-zero-server/blob/f8a51f48c6c88dae8d10dd6c2bcad597c25d8b2b/server.js#L1474

ELF games are allocated at 25%

**Comment by l1t1** [comment]
thanks
