### ISSUE TITLE
c010f034 20 blocks seems promising

### ISSUE THREAD

**Issue by grolich** [gcp/leela-zero#1589]
Now that a 20b LZ (c010f034) beat the best 15b by over 61% - will we be planning a switchover to 20b, or do we want to wait until the current 15b network completely stalls? 

Is there a compelling reason not to switch to 20b now that it's stronger?

Sorry if that has been discussed in other topics. Searched and couldn't find anything concrete.

**Comment by TFiFiE** [comment]
#1113

**Comment by grolich** [comment]
Apologies then, hard to track every issue from a few months ago... 
Seems like possible good news :)
