### ISSUE TITLE
performance issue ?

### ISSUE THREAD

**Issue by Paiguru** [gcp/leela-zero#159]
I am running it on windows, it took me about half an hour to play 7 moves, is this normal ?
It is showing Infinite time set.
I have an i5-6200U, it's supposed to use the GPU but when I run autogtp.exe, the CPU is running 100%.

Thanks

**Comment by KID1412999** [comment]
Maybe you should shift the typle of GPU

**Comment by gcp** [comment]
What GPU do you have? If you mean the internal GPU in the i5-6200U, it's uselessly slow.

**Comment by Paiguru** [comment]
Thanks guys, yes it is an internal GPU. I thought the CPU could do something but as you said it's useless
