### ISSUE TITLE
om

### ISSUE THREAD

**Issue by larrywang30092** [gcp/leela-zero#1594]

**Comment by Ishinoshita** [comment]
You meant 'omg'? ;-)

**Comment by jokkebk** [comment]
Or maybe "om nom" and he did not have time to write "nom" because his stones got eaten?

**Comment by Eddh** [comment]
I think this is a good idea. Need to implement it.

**Comment by john45678** [comment]
Maybe this: https://theyogahub.ie/wp-content/uploads/2018/06/Om.jpg

yoga chanting :)
