### ISSUE TITLE
why 6f16 weight lost 18 games in a batch

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1598]
http://zero.sjeng.org/match-games/5b38051acad7d44c24375cf4

**Comment by l1t1** [comment]
![2018-07-01_081121](https://user-images.githubusercontent.com/23301704/42129967-d064d5b6-7cc3-11e8-87d1-430e4199f67c.png)

**Comment by PhilipFRipper** [comment]
Because in 8 million games all kinds of random things are bound to happen.

**Comment by l1t1** [comment]
thanks
