### ISSUE TITLE
Would you consider switching to the MIT license?

### ISSUE THREAD

**Issue by passstab** [gcp/leela-zero#160]
Moving to a [copyfree license](http://copyfree.org/standard) would encourage more trainers to join the network and possibly attract code contributors.  
Thank you

**Comment by gcp** [comment]
No, absolutely not. Your argument is extremely weak, as exactly the opposite could happen too.

Note that data produced is public domain. I'll make this explicit in the README.

**Comment by sethtroisi** [comment]
I don't think you ever added that note, but this issue makes the same statement

https://github.com/leela-zero/leela-zero/issues/167
