### ISSUE TITLE
http://zero.sjeng.org/ server down?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1600]
ping timeout

C:\leela-zero-0.14-win32>ping **zero**.sjeng.org

Pinging zero.sjeng.org [138.201.118.121] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 138.201.118.121:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

C:\leela-zero-0.14-win32>ping **www**.sjeng.org

Pinging www.sjeng.org [138.201.118.121] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 138.201.118.121:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

but this one is working

C:\leela-zero-0.14-win32>ping **storage**.sjeng.org

Pinging storage.sjeng.org [107.189.49.107] with 32 bytes of data:
Reply from 107.189.49.107: bytes=32 time=785ms TTL=51
Reply from 107.189.49.107: bytes=32 time=606ms TTL=51
Reply from 107.189.49.107: bytes=32 time=825ms TTL=51
Reply from 107.189.49.107: bytes=32 time=524ms TTL=51

Ping statistics for 107.189.49.107:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 524ms, Maximum = 825ms, Average = 685ms

**Comment by l1t1** [comment]
autoftp also fail
C:\leela-zero-0.14-win32>autogtp -k sga
AutoGTP v16
Using 1 thread(s) for GPU(s).
Starting tuning process, please wait...
Network connection to server failed.
NetworkException: Curl returned non-zero exit code 7
Retrying in 30 s.

**Comment by l1t1** [comment]
returned

**Comment by gcp** [comment]
Was an issue at the ISP.
