### ISSUE TITLE
can this project write a paper to summary some methods that  AlphaGo Zero paper did  not mention

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1602]
such as
1 swa weight
2 add elf games to train lz
3 use new bigger weights games to train smaller weights
4 komi/handicap
5 batching

so many games and weights enable us do many study on differnt aspects

**Comment by gcp** [comment]
With "this project", do you mean "can I"? Then sure!

I might get around to writing some of this up for the European Go congress presentation. But (4) is still entirely in the air as to what the best method is, and (5) was already in all DeepMind papers, we just never implemented it.

**Comment by l1t1** [comment]
I  see the https://egc2018.it/files/schedule.html, when will you make the presentation?
