### ISSUE TITLE
(possible) bug of the 2-pass rule

### ISSUE THREAD

**Issue by zhanzhenzhen** [gcp/leela-zero#1603]
![3-pass](https://user-images.githubusercontent.com/731796/42326237-28a3aac4-809b-11e8-8fa4-7237832af91d.png)

Black to move. Black plays at A. Then white must pass. Then black also passes and win. But actually black should lose because the top-right corner is dead. This is just a bug of the rule itself. I don't know if it affects Leela.

**Comment by gcp** [comment]
>black should lose because the top-right corner is dead

Then white should capture it. That's how Trump Taylor rules work.

**Comment by zhanzhenzhen** [comment]
> Then white should capture it. That's how Trump Taylor rules work.

@gcp How could white capture the top-right corner then?

**Comment by zhanzhenzhen** [comment]
oh, just viewed tromp-taylor rule and I see it mentions 4-passes?

**Comment by gcp** [comment]
Leela Zero does get this "wrong" in the sense that she assumes the game is over after 2 passes, which makes for handier playing with Chinese style rules. 

I don't know if this ever matters in practice.

**Comment by rchs819** [comment]
IMO, W indeed lost in the situation like this, because W is out of KO threat, I reckon this is not a pass bug. 

I believe LZ is smart enough to prevent herself getting into situations like this. Top right corner should be handled before end game.

**Comment by TFiFiE** [comment]
This (kind of academic) issue with superko is actually brought up in [_On the Rules of Go_](http://gobase.org/studying/rules/ikeda/) by Ikeda Toshio, [here](http://gobase.org/studying/rules/ikeda/?sec=e3030001) to be precise.
