### ISSUE TITLE
Save computation on no-resignation games

### ISSUE THREAD

**Issue by Nazgand** [gcp/leela-zero#1604]
I was watching a no-resignation game, and 1 player passed because they had no legal move on the board. Player 2 could have passed to win the game, yet instead chose to capture a group which made the game 50+ moves longer.

I propose that every time Leela Zero's opponent passes, Leela Zero should be forced to pass if doing so results in a win.

**Comment by Nazgand** [comment]
I think this is probably the game, and after looking closer, black actually had a legal move when it passed at 453. If white passed instead of playing S16, white should win by 70.5 points when counting all stones on the board as alive. Instead, the game continued 269 more moves than needed.

What is the reasoning behind --dumbpass for self-play games? The 269 moves are enough to get a whole game at 5% resignation.
If a good reason exists to not automatically pass when doing so results in a win, then perhaps I should modify autogtp to reject no-resignation games so that I fell that I am not wasting computation. Also, watching no-resignation games is boring.

[2018-07-05T03_21_04.423Z.sgf.txt](https://github.com/gcp/leela-zero/files/2169252/2018-07-05T03_21_04.423Z.sgf.txt)

**Comment by gcp** [comment]
Adding the heuristics that are outside dumbpass mode means the engine gets "help" in counting the score, which is why it isn't enabled.

**Comment by Nazgand** [comment]
Okay, then I suggest having heavier weights for the training from games which end sooner. This would also save computation in the long run, as LeelaZero would eventually learn to not prolong games.
