### ISSUE TITLE
OpenCL error  "in function XgemmBatched [..] unsupported initializer for address space"

### ISSUE THREAD

**Issue by dvdkhlng** [gcp/leela-zero#1612]
Hi,

trying to run leela-zero using the open source driver mesa-opencl-icd 17.3.9 (backports on Debian Stretch), leela zero fails to compile the opencl code, failing with:

    Failed to find a working configuration.
    Check your OpenCL drivers.
    terminate called after throwing an instance of 'std::runtime_error'
      what():  Tuner failed to find working configuration.
    Aborted

I added some code to dump the actual opencl compile error, which gives this error:

> <unknown>:0:0: in function XgemmBatched void (i32, i32, i32, <2 x float> addrspace(1)*, <2 x float> addrspace(1)*, <2 x float> addrspace(1)*): unsupported initializer for address space

After some trial and error I found out that it is the "volatile" keyword in xgemm_part3.opencl that causes the problem:

```c
  #if SA == 1 || SB == 1
    volatile int tid = get_local_id(0) + MDIMC*get_local_id(1);
  #endif
```
Commenting "volatile" out makes the code run (as does setting SA and SB zero via the tuner).  I still have some stability issues, though where leelaz somtime aborts with "Error in OpenCL calculation" after some time.

Not sure what the volatile here is supposed to do anyway.  I don't have any prior opencl experience, "volatile" on a local variable in this context does not make any sense to me.

cheers,

David

**Comment by infinity0** [comment]
I am a Debian Developer trying to package this for Debian and get the same problem with mesa-opencl-icd 18.1.3-1 in Debian. Removing "volatile" makes the tests work, as described by OP. Is it safe to apply the workaround in Debian?

**Comment by gcp** [comment]
>get the same problem with mesa-opencl-icd 18.1.3-1 in Debian

That's strange. I had success with Mesa 18.0, though this was on an Arch machine.

>Removing "volatile" makes the tests work, as described by OP. Is it safe to apply the workaround in Debian?

I would recommend against it since it will make performance worse for people that have correctly working drivers.

**Comment by infinity0** [comment]
> I added some code to dump the actual opencl compile error, which gives this error:

@dvdkhlng can you show me the code you used to do the dumping? Perhaps my error with 18.1.3 is different from what yours was.

**Comment by infinity0** [comment]
On second thoughts, probably not, since your workaround *did* work for me too...

**Comment by infinity0** [comment]
@gcp Can you try again on your Arch machine? Debian's [mesa 18.1.3 patches](https://sources.debian.org/src/mesa/18.1.3-1/debian/patches/) and Arch's [mesa 18.1.3 patches](https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/mesa) are slightly different but the differences don't seem related. So I don't know why it would work for you but not me.

My gfx card is AMD Radeon RX 580 Series (POLARIS10, DRM 3.23.0, 4.16.0-1-amd64, LLVM 6.0.1) using [these Debian drivers](https://packages.debian.org/sid/xserver-xorg-video-amdgpu) from March 2018, not sure if that makes a difference.

How significant is the performance hit? If not too significant I will probably have to keep this workaround, we in Debian generally need to keep things non-dependent on proprietary drivers where possibly, and slower > not-working.

**Comment by gcp** [comment]
I had:

```
Platform version: OpenCL 1.1 Mesa 18.0.4
Device name:   Radeon RX 560 Series (POLARIS11 / DRM 3.23.0 / 4.16.13-1-MANJARO, LLVM 6.0.0)
```

And this worked.

**Comment by gcp** [comment]
I upgraded that system and now:

```
Platform version: OpenCL 1.1 Mesa 18.1.3
Device name:   Radeon RX 560 Series (POLARIS11, DRM 3.23.0, 4.16.18-1-MANJARO, LLVM 6.0.0)
```

Also just works.

Is this a bug in the POLARIS10 backend only? Or are we looking at the wrong software component? Does Manjaro have some extra patch?

**Comment by dvdkhlng** [comment]
>>>>> "Gian-Carlo" == Gian-Carlo Pascutto <notifications@github.com> writes:

> I had: Platform version: OpenCL 1.1 Mesa 18.0.4 Device name: Radeon RX
> 560 Series (POLARIS11 / DRM 3.23.0 / 4.16.13-1-MANJARO, LLVM 6.0.0)

here it's:

  Platform Version                                OpenCL 1.1 Mesa 17.3.9

  Device Name                                     AMD KABINI (DRM 2.49.0 / 4.9.0-6-amd64, LLVM 5.0.1)

**Comment by infinity0** [comment]
I can confirm patch is not required with beignet-opencl-cid version 1.3.2-2+b1 with `Intel(R) HD Graphics Kabylake Desktop GT1.5`, so it does seem to be a Mesa issue, maybe to do with polaris 10. I linked Manjaro vs Debian patches to Mesa above, I'm not familiar with the code but the patch differences seem unrelated.

**Comment by infinity0** [comment]
I've filed the issue upstream to the CLBlast author, maybe he has some more ideas about this.

**Comment by gcp** [comment]
Let's do a test if removing this causes any degradation on current AMD/NVIDIA hardware. If we don't see any, it can go.

**Comment by gcp** [comment]
Filed as https://bugs.freedesktop.org/show_bug.cgi?id=107369

**Comment by gcp** [comment]
@infinity0 Upstream requested some debugging information, can you peek in the freedesktop bug mentioned above?

**Comment by gcp** [comment]
@infinity0 upstream has identified this as a problem caused by a change Debian made to the libclc build setup. (But it's possible those should have worked, and the problem is still elsewhere)

**Comment by infinity0** [comment]
Nice, thanks. Sorry I was slow in getting around to the data dumps but I guess they're not needed now the cause has been found. Will comment further in the mesa bug report.

**Comment by gcp** [comment]
@infinity0 I think they'd still like the dumps:

```If anyone can upload the different libclc bitcode it should be easy to spot.```

**Comment by gcp** [comment]
Debian updated the package:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=904718
