### ISSUE TITLE
Problem install on mac by terminal

### ISSUE THREAD

**Issue by kaelkael09** [gcp/leela-zero#1613]
After copy in terminal mac

git clone -b next https://github.com/gcp/leela-zero
		cd leela-zero/src
		brew install boost
______________________________________

Message error

-bash: stall: command not found

What do you do?

**Comment by gcp** [comment]
Where is it failing?

There's nothing in leela-zero that should produce that error AFAIK, so this looks like a problem with Homebrew.

**Comment by MarcelGruenauer** [comment]
I assume that the "stall" is the last part of the word "install" and that something got lost in the copy-paste.
