### ISSUE TITLE
700+ move games with plays on first line

### ISSUE THREAD

**Issue by qzq1** [gcp/leela-zero#1617]
I hope posting a question here isn't clogging things up, but I'm curious about something.  I have been running autogtp successfully via Colab.  I have seen a number of instances in which a game runs for more than 700 moves, exhausting all legal moves by one side.  These games also (always?) have a number of early moves on the first line, distant from any other stones.  I have a few questions, in my admittedly substantial ignorance:  one, is there is a reason to expect that these two things (early first-line moves and exhausting all legal moves) should go together?  Two, is there really a benefit in training with a game like that?  And three, doesn't the very first demonstrably terrible first-line move indicate that the weights in question are bad?
Lastly - is there a forum elsewhere in which methodological questions are discussed, or is all that enshrined here?  Thanks.  Such terrific work you all have done on this project!

**Comment by Hersmunch** [comment]
See the most recent discussion about this https://github.com/gcp/leela-zero/issues/1608

**Comment by Hersmunch** [comment]
I should have also mentioned that first line moves occur during self-play games due to added noise and randomness to the move selection. This allows a wide variety of games for the training to be performed on and therefore the knowledge learned has more chance of being generalised.
