### ISSUE TITLE
Anyone's help to look into the MCTS?

### ISSUE THREAD

**Issue by Vandertic** [gcp/leela-zero#162]
To give my contribution (I am a mathematician) I would like to check on the implementation of the MCTS, but I am weak on c++. I ask anyone (possibly without bothering gcp), to:

* direct me to the code lines that actually do the MCTS

and/or read the code for me and tell...

* what are the parameters used to generate the tree for MCTS? (number of nodes in the tree, confidence thresholds, ...)
* if the tree sees a double pass, does it use the value network or does it score the board to see who wins?
* what is the temperature used to finally choose the move?

Thank you

**Comment by Vandertic** [comment]
Thank you  for you comments. I checked the code at the best of my C++ understanding, I everything seems done according to the AGZ paper.

Just two more questions. 

1) Where did you get the value of Puct=2.8? I couldn't find it on the AGZ paper.

2) You say that the number of simulations is 1000. The paper says 1600 if I am not mistaken, but I couldn't find this 1000 bound in the code, so maybe it is 1600 already?

**Comment by fishcu** [comment]
> 2.
The number of playouts (simulations) is passed to leela zero as a command line argument here: https://github.com/gcp/leela-zero/blob/master/autogtp/Game.cpp#L38

**Comment by justinwong098** [comment]
> 2. You say that the number of simulations is 1000. The paper says 1600 if I am not mistaken, but I couldn't find this 1000 bound in the code, so maybe it is 1600 already?

gcp addressed this here:
https://github.com/gcp/leela-zero/issues/50

**Comment by Alderi-Tokori** [comment]
@Vandertic For AlphaGo Lee the Puct was 5 according to their paper, we don't know if they kept the same value for Alpha Zero. At first Leela zero used a Puct of 5 too but at some point it got reduced to 2.8. In the end this parameter is mainly a matter of trial and error, trying to see what value works best for a balance between fast and good convergence.

**Comment by gcp** [comment]
I picked this based on tuning the playing strength with CLOP with the network learned from supervised learning that is in the README. According to the paper, AGZ did a similar optimization step.

My tuning also indicated the influence on playing strength is very small, as long as it's in the right magnitude. So 2.8 or 5.0 or a bit more or less doesn't really matter.
