### ISSUE TITLE
Questions about 224x20 net?

### ISSUE THREAD

**Issue by Marcin1960** [gcp/leela-zero#1627]
I decided to give a try to 224x20 net (smaller than 256x20) - 62b5417b with 75% win

I downloaded it, and unfortunately I found that it is 192x15 net. Something got misplaced?

**Comment by Hersmunch** [comment]
It is fine for me.

**Comment by Marcin1960** [comment]
It is fine now, indeed

**Comment by Marcin1960** [comment]
It is fine

**Comment by Marcin1960** [comment]
Why this net has creation date ‎may ‎3 2018, ‏‎20:45:32

**Comment by alreadydone** [comment]
This is the Facebook ELF OpenGo net.

**Comment by Marcin1960** [comment]
@alreadydone "This is the Facebook ELF OpenGo net."

I see.
