### ISSUE TITLE
why a game between  two 64x5 weights cost about 2 hours, any parameters are wrong?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1628]
```gogui-twogtp.exe -black "D:\tool\valid14\leelaz.exe -g -w D:\leelaz-model-1448000.txt -v3200 --noponder -m4 -t1 -s1" -white  "D:\tool\valid14\leelaz.exe -g -w D:\best_5b.txt -v3200 --noponder -m4 -t1 -s1" -auto -alternate -sgffile 5bo_5bb -komi 7.5 -games 100```

```
# Black: Leela Zero
# BlackCommand: D:\tool\valid14\leelaz.exe -g -w D:\leelaz-model-1448000.txt -v3200 --noponder -m4 -t1 -s1
# BlackLabel: Leela Zero:0.15
# BlackVersion: 0.15
# Date: July 17, 2018 1:48:28 PM CST
# Host: PC
# Komi: 7.5
# Referee: -
# Size: 19
# White: Leela Zero
# WhiteCommand: D:\tool\valid14\leelaz.exe -g -w D:\best_5b.txt -v3200 --noponder -m4 -t1 -s1
# WhiteLabel: Leela Zero:0.15
# WhiteVersion: 0.15
# Xml: 0
#
#GAME	RES_B	RES_W	RES_R	ALT	DUP	LEN	TIME_B	TIME_W	CPU_B	CPU_W	ERR	ERR_MSG
0	W+R	W+R	W+R	0	-	414	3326.2	3314.8	0	0	0	
1	W+R	W+R	W+R	1	-	269	2861.6	2862.2	0	0	0	
2	W+81.5	W+81.5	?	0	-	411	3351.2	3326.5	0	0	0	
3	W+R	W+R	W+R	1	-	315	3083.2	3054.1	0	0	0	
4	W+82.5	W+82.5	?	0	-	469	3435.5	3426.3	0	0	0	
5	W+81.5	W+81.5	?	1	-	401	3329	3302.5	0	0	0	
6	W+180.5	W+180.5	?	0	-	487	3459.9	3451	0	0	0	
7	W+R	W+R	W+R	1	-	291	3044.5	3011	0	0	0	
8	W+R	W+R	W+R	0	-	314	3123.9	3096.7	0	0	0	
9	W+141.5	W+141.5	?	1	-	528	3483	3486.2	0	0	0	
```

[5bo_5bb-0.sgf.txt](https://github.com/gcp/leela-zero/files/2200693/5bo_5bb-0.sgf.txt)

**Comment by l1t1** [comment]
link of two weights tested 
https://userscloud.com/u6q3dpakis87

**Comment by l1t1** [comment]
slower than lz156 vs 20x256 v19
https://github.com/gcp/leela-zero/issues/1113#issuecomment-405794807

**Comment by l1t1** [comment]
@as0770  
no time options, all the command line is  the 1st line of the issue.

**Comment by as0770** [comment]
Thinking about this... Is this true?

When I start Leela with -v X command line option it says: "Thinking at most 36  seconds. Looks to me like Leela interrupts the search also if visits X are not reaches. Is this supposed to be like that?

**Comment by gcp** [comment]
>Is this supposed to be like that?

Yes. The time control is always respected.

**Comment by l1t1** [comment]
I  notice the average moves of 64x6  is higher than that of lz156
maybe the weight  is not so good, so leelaz doesn't know when to resign,  and my machine is weak, it need so much time.

**Comment by l1t1** [comment]
I test a game of lz157 and best_6b, the time cost is  lower than that of two 6b weights,
and more, the time of white is much lower
```
# Black: Leela Zero
# BlackCommand: D:\tool\valid14\leelaz.exe -g -w D:\lz157.gz -v3201 --noponder -m4 -t1 -s1
# BlackLabel: Leela Zero:0.15
# BlackVersion: 0.15
# Date: July 25, 2018 1:15:28 PM CST
# Host: PC
# Komi: 7.5
# Referee: -
# Size: 19
# White: Leela Zero
# WhiteCommand: D:\tool\valid14\leelaz.exe -g -w D:\best_5b.txt -v3200 --noponder -m4 -t1 -s1
# WhiteLabel: Leela Zero:0.15
# WhiteVersion: 0.15
# Xml: 0
#
#GAME	RES_B	RES_W	RES_R	ALT	DUP	LEN	TIME_B	TIME_W	CPU_B	CPU_W	ERR	ERR_MSG
0	B+R	B+R	B+R	0	-	187	2511.5	2152.2	0	0	0	
1	B+R	B+R	B+R	1	-	174	2303.3	1530.2	0	0	0	

```

**Comment by as0770** [comment]
There is an issue with twogtp and alternating colours resulting in wrong results. Always check the results manually or better don't alternate and make 2 runs.
