### ISSUE TITLE
Training with CPU only

### ISSUE THREAD

**Issue by wonderkid27** [gcp/leela-zero#163]
How can I change the training file to train with CPU only?

**Comment by Alderi-Tokori** [comment]
If you're talking about the tensorflow training file, then you have to use the "with tf.device('/cpu:0'):" kind of code around the construction of the graph, but you're aware that on CPU the training will be at least an order of magnitude slower, right?

**Comment by cngoodboy** [comment]
CPU speed is slower than the GPU speed of nearly an order of magnitude, the need for 10 CPU equivalent to a GPU.
