### ISSUE TITLE
GPU autodetection no longer working correctly

### ISSUE THREAD

**Issue by Mardak** [gcp/leela-zero#1632]
@ihavnoid with #1558, autodetection seems to pick the first / CPU device then crashes. This might be mac only?

```
Selected device: Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
with OpenCL 1.2 capability.

Started OpenCL SGEMM tuner.
Will try 290 valid configurations.
Failed to find a working configuration.
Check your OpenCL drivers.
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Tuner failed to find working configuration.
Abort trap: 6
```

Reverting 6ec5c5824dbc0fbbc12d7582919eadc92da28a09 or explicitly selecting a device with `--gpu` does not crash.

**Comment by ihavnoid** [comment]
Oops.  I see what might be going on.  Yes it seems that I missed autodetect.  I'll have a look.

**Comment by ihavnoid** [comment]
@Mardak - please have a look at #1633 and see if this fixes your problem.

**Comment by Mardak** [comment]
Yup! With aaf5392, no more crashing.
