### ISSUE TITLE
Is Zhang Qi one of the Leela Zero Contributions

### ISSUE THREAD

**Issue by yuanfengpang** [gcp/leela-zero#1636]
Since my lab organized this small competition, boss asked me to check if every soft is original. I noticed that Leela Zero joined yesterday.

http://hp.vector.co.jp/authors/VA012620/cgf2018/list2018.html

**Comment by theleapfaith** [comment]
9x9?We should not have official 9x9 weights.Maybe a personal training program.

**Comment by gcp** [comment]
Someone ran LZ in 9x9 for a few months and produced a 9x9 network that was on top of CGOS. It's linked from my site: http://storage.sjeng.org/zero/9x9-20-128.txt.gz

That's about as official as we have now.

**Comment by gcp** [comment]
Zhang Qi is not a Leela Zero contributor, but he operated Leela Zero for us in some tournaments in China. (With eh, "mixed success")

**Comment by l1t1** [comment]
is this Zhang Qi the same person of Aurora's author?

**Comment by gcp** [comment]
Aurora was 张旗 and the operator was 章琦.

The translation of the name in Latin script was the same but because of the above I think it's a different person?

**Comment by diadorak** [comment]
Indeed, their names are totally different in Chinese.

**Comment by l1t1** [comment]
张旗 master degree paper wrote about go game ai and his software win champion at 9x9 ai competition before leelaz's  birthday
