### ISSUE TITLE
error of leela-zero on linux

### ISSUE THREAD

**Issue by syys96** [gcp/leela-zero#164]
I want to run leela-zero on my linux machine. When I followed the instructions step by step, everything was fine until the last step:
root@iZwz9dxmwcuitwtyywf7oxZ:~/leela/leela-zero# src/leelaz --weights weights.txt
Leela Zero  Copyright (C) 2017  Gian-Carlo Pascutto
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

Initializing OpenCL
OpenCL: clGetPlatformIDs
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Aborted

Could someone help me out? I turned to google and found some answers but it still doesn't work.

**Comment by bood** [comment]
I guess it is because your machine does not have a GPU

**Comment by Mocramis** [comment]
It is probably because you do not have the hardware component package of opencl. You can find the list of these packages here: https://wiki.archlinux.org/index.php/GPGPU#OpenCL_Runtime (you'll have to use an equivalent for your distro though)

**Comment by marthinwurer** [comment]
If you're on Ubuntu like I am, I followed the instructions found [here.](https://askubuntu.com/questions/850281/opencl-on-ubuntu-16-04-intel-sandy-bridge-cpu)

**Comment by syys96** [comment]
Thank you for your advice@marthinwurer@Mocramis! I installed the dependent packages of opencl and this time leela-zero can run normally.
