### ISSUE TITLE
It seems that someone upload some bad games

### ISSUE THREAD

**Issue by hzyhhzy** [gcp/leela-zero#1641]
For example
http://zero.sjeng.org/view/b4cc5b1b912b11444a3c67b10a2a0ce29a55991b9da312dbf8ff44c0a6b7a947?viewer=wgo

**Comment by hzyhhzy** [comment]
They are usually 92 or 93 moves

**Comment by hzyhhzy** [comment]
I guess that someone use leelaz.exe by @alreadydone(Dynamical komi) to run self-plays.

**Comment by Ishinoshita** [comment]
Hi @hzyhhzy : Sorry, but can you be more specific on what makes you believe your example game is abnomal ? It's not obvious to me, at least. White blundered in the bottom right corner very early in the game, withe win rate droped so low that white started to play somewhat random moves. Then resigned once the 92 minimum moves limit was reached. Just the effect of randomness, no ? What's wrong ?

**Comment by hzyhhzy** [comment]
There are usually only several strange moves.But in this one ,after 50 moves,almost no move is strange.If you are good at playing Go,it's obviously that this game is really strange.

**Comment by hzyhhzy** [comment]
You are right.When the winrate is so low or high,it will almost randomly play.I tried it just now.

**Comment by hzyhhzy** [comment]
You are right.When the winrate is so low or high,it will almost randomly play.I tried it just now.
 
But I saw someone try to use leelaz.exe by alreadydone to run self-plays.(He is new to Leelazero).I suggest that leelaz.exe should be checked when running self-plays.
