### ISSUE TITLE
Winograd (4x4,3x3), USE_HALF and 256x20

### ISSUE THREAD

**Issue by gcp** [gcp/leela-zero#1645]
The combination doesn't seem to work:

```
Started OpenCL SGEMM tuner.
Will try 290 valid configurations.
Failed to find a working configuration.
Check your OpenCL drivers.
```

@ihavnoid @Ttl

**Comment by cjohnchen** [comment]
We alreday can use this new version now!

**Comment by cjohnchen** [comment]
[LZWinograd(avx2).zip](https://github.com/gcp/leela-zero/files/2222786/LZWinograd.avx2.zip)

**Comment by ihavnoid** [comment]
I tried 224x20 elf weight, and it seems that the error increased a bit to 1.1%.  Probably bumping up the error margin to let's say, 2% will solve the problem.

I think it's either we tweak the random data generation to represent something more representative, or we increase the error margin.  @gcp any thoughts?

**Comment by gcp** [comment]
Increasing the error margin is fine.
