### ISSUE TITLE
Let self-play game starts from mid-game?

### ISSUE THREAD

**Issue by thynson** [gcp/leela-zero#1651]
The opening of leelaz is actually very bored if `-n -m 999` is not applied, so I think that:
1. The number of reasonable position of opening is less than mid-game.
2. Suppose the number of reasonable game position increase as number of stones grows, we should pay more resource to mid-game than openinng. 
3. Althrough AlphaGoZero/AlphaZero's approach is start self play from begining to the end, but for our situation it may not be the most optimal. Especially there're plan of moving to 20B.

Initially we could dispatch a truncated sgf of a position randomly selected from a game to the autogtp client, which is randomly selected from the uploaded self-play, so no human games here. 
Later we could find some way to better decide what sgf to dispatch, to save power as much as possible.

**Comment by gcp** [comment]
```
if -n -m 999 is not applied
```

That's what all self-play uses now though.

**Comment by thynson** [comment]
No, I never implied the opening won't change, I stated that the opening might be already very optimal compares to leelaz mid-game performance. Even if we only train the mid-game, its opening might also be affected if search is deep enough.

**Comment by Eddh** [comment]
Personally I like the idea of taking sample positions from games, in particular, positions that are looked at by the tree search but not played because something else is picked, and using them as starting point for new games. The main point would be to allow for great exploration, without any need for temperature = 1. It could be useful on top of temp=1, or possibly replace its function as diversity booster. 

It would also force the net be usable in set up positions which don't have any history, for which currently there is no guarantee that the net will behave properly (although it seems to do fine most of the time).

Of course, the issues is all the work necessary to gather these positions, store them on the server, and send them to clients.

**Comment by thynson** [comment]
@Eddh Yeah, that is my point. And actually we have all the play history if we send the client a sgf(without moves after some position in the origin game)

**Comment by gcp** [comment]
>It would also force the net be usable in set up positions which don't have any history, for which currently there is no guarantee that the net will behave properly (although it seems to do fine most of the time).

For what it's worth, another project pointed out a simple trick to fix this: during the training, wipe the history of some percentage of positions.

**Comment by gcp** [comment]
In our current setup where we normalize on visits, positions where the program is very highly opinionated are almost "free". In the opening, this means that even at the very first moves you're really spending most of your search effort on the first positions where the network has alternatives.

So this isn't going to save as much as you think, IMHO. The tree search already handles it.

**Comment by Friday9i** [comment]
To get more diversity of moves, we could randomnly change the number of visits... Either game by game (eg one game with 800 visit, the next one with 1500, the next one with 10000, with a chosen average and distribution) or move by move within the game... In the opening, that would for sure lead to more diversity, and I don't see why it wouldn't be the case in the middle game too.

**Comment by thynson** [comment]
That is not about diversity but saving power so more game could be geneareted.
It's like do self play with 1 playout to some position and then changed to 3200visit. But actually 1 visit does not generate much variation as 3200 visit does, and since we already stored all the game, the server just "sample" one position and dispatch to autogtp client.
Another way could be changed `-m ` to select child propotionally to its prior score if there is no child visited yet. And let it plays with 1 playout in the opening for the several moves.

**Comment by gcp** [comment]
>It's like do self play with 1 playout to some position and then changed to 3200visit. .. Another way could be changed -m to select child propotionally to its prior score if there is no child visited yet

The tree search right now distributes effort according to the priors, and (barring huge differences in winrate), this means -m selection already is mostly proportional to winrate.

As I said, I think you're misunderstanding how efficient the tree search already is right here. It's really not spending a lot of time in the opening, even if calculating on the opening position.
