### ISSUE TITLE
Welcome to Randomness Island! - A journey on LZ policy training data landscape

### ISSUE THREAD

**Issue by Ishinoshita** [gcp/leela-zero#1656]
Tired of bootstrapping capricious networks? Let have a break on Randomness Island! :
![intro](https://user-images.githubusercontent.com/37498331/43223885-cb4fbca4-9054-11e8-8b0a-d472be0fdd15.jpg)

*Kind of a clickbait title and a teaser introduction figure, I must admit ;-).*

### The question of the quality of no-resign games ("-r 0"):
As I understand it, LZ implements resignation in self-play games as explained in AlphaGo Zero paper: "In order to save computation, clearly lost games are resigned. The resignation threshold V_resign is selected automatically to keep the fraction of false positives (games that could have been won if AlphaGo had not resigned) below 5%. To measure false positives, we disable resignation in 10% of self-play games and play until termination. [...] AlphaGo Zero resigns if its root value and best child value are lower than a threshold value V_resign."

However, I still do not understand if and how no-resign games are actually used on server side (discussed here: https://github.com/gcp/leela-zero/issues/421#issuecomment-405085101).

I regularly have a look at the last 400 self-play games on Sjeng.org, scrolling through the games to have a feel of their content. Like many others here, I observed that, past some point in a no-resign games,  when one side clearly start losing, this losing side starts playing more and more often weird/random-like moves (first line moves e.g., but not tesuji ones!), the winning side doing the same to a less extend and after some delay. And this can go on for hundreds of moves.

Blunders in self-play games, in particular in no-resign games/high move count positions, is an ever-recurring topic here and, if I got it well, is generally explained by the deleterious combination of:
* (1) Intrinsic poor behavior of MCTS search under extreme win rates, flattening the prior distribution of the raw policy network; 
* (2) Addition of 25% of Dirichlet noise, which worsens the effect of (1) when raw policy is already flat, pushing too high the prior for some random moves; 
* (3) Randomness in move selection, i.e. randomly picking moves proportionally to their number of visits, aka temperature=1

Seems like MCTS is no more an "improvement operator" for the policy network under extreme win rate. Particularly under injection of Dirichlet noise.

### Analysis of LZ policy training data
With no-resign games quality at aim, I've done some analysis of recent LZ policy training data distribution. I've downloaded training data file train_7ff174e6.zip (LZ156 only, no ELF games) uploaded on training server on 18-Jul-2018).

I wrote a little python script to process the training samples of the 174 chunks. Taking advantage of the fact that sequential samples correspond to sequential moves in the same game (new game detected by zeros only in input planes 1 and 8), it reconstructs the game number and the move count. It also processes the 362 values of policy vector to compute 5 basic statistical indicators, the cumulated probabilities of top1, top2, top3, top5 and top10 moves, intended to assess the sharpness/flatness of the policy training data. 

Here after, Top1 is named 'Policy Max' in line with the analysis already done by @Ttl here https://github.com/gcp/leela-zero/issues/1591#issuecomment-400783643  (to compare LZ123 and ELF policies). @ThorAvaTahr suggested to refine the analysis further by going done to move count class (~ opening / middle game / end game). What suggested me the present analysis.

I'm using the term 'policy' as a shortcut, although these indicators do not represent LZ actual *policy* but the *training targets* produced by the MTCS search and used to train LZ policy. Maybe 'visits' would have been more appropriate. 

*Since I plan to analyze these training samples with LZ/Sabaki in the future, and since I don't know how to associate a training sample to a its sgf file (nor even where this sgf can be found, actually), I'm currently rewriting my script to also reconstruct the board position and the full sgf (I need the game history since I want LZ to to search/replay the position in more or less the same condition), but I'm not done with that yet. Would love to see the training data include in the future the root action value and/or best child score, just after the game outcome, at least for data mining purpose.*

I was a bit lazy and decided to use Excel pivot tables for the graphs, so my analysis is limited by Excel capability to the first 1M samples of this training file, i.e. the first 1M positions, corresponding to 4985 self-play games, which is still statistically significant.

I also did some experiments with LZ, to check that the drops in MCTS search moves policy coincide more or less to drops in win rate and the hit of the resign threshold. I also several times sampled 400 of the last self-play games, published on sjeng.org, to compare the length of no-resign games vs resign-games (yes, opening all 400 sgf one by one to check the “-r “ argument …), and study some of them with LZ.

Here after are a few samples of screen shots from my analysis of LZ156 training data. You can also directly scroll through all the figures in this PowerPoint and draw your own conclusions.
[train_7ff174e6 - Policy analysis.pptx](https://github.com/gcp/leela-zero/files/2229367/train_7ff174e6.-.Policy.analysis.pptx)
*Edit:  move count / game lenght mistakenly start at 0 instead of 1*   

**Policy Max vs Move Count:**
![policy max vs move count](https://user-images.githubusercontent.com/37498331/43224570-f619c946-9056-11e8-86d8-d7451fe8d70c.jpg)

*P_best3 vs Move Count:*
![p_best3 vs move count](https://user-images.githubusercontent.com/37498331/43224721-5895999c-9057-11e8-8830-9f4615f04116.jpg)

*Policy Max vs Game Length:*
![policy max vs game length](https://user-images.githubusercontent.com/37498331/43224805-aa4148b8-9057-11e8-8036-fd25794a14e7.jpg)

Although these kind of representations are very often misleading, I couldn't resist plotting these landscapes with the 'Surface Chart' of Excel:

*Policy Max vs Move Count:*
![policy max vs move count bis](https://user-images.githubusercontent.com/37498331/43224878-e6d0586e-9057-11e8-96ab-142b933e8d9d.jpg)

*Game Length distribution:*
![game length](https://user-images.githubusercontent.com/37498331/43224932-1a52a458-9058-11e8-864f-8bd8e668c608.jpg)

**Games trajectory**

I initially intended my introduction picture just as a clein d'oeil, a probably misleading representation, suggesting that a game would start somewhere on some 'Common Sense Go Lands', then would crash on 'Randomness Island' through the isthmus, past the resign threshold, and that it would stay on that island until game end. There are actually a few high policy moves played all along any game, even well beyond the 380 move count, and those moves are missing on the 'Surface Chart' representation (but are visible in standard 3D charts), so some games actually switch from 'Randomness Island' to other locations with high policy value (close to 1.0). There are also some overlap in policy value between 'Randomnes Island' and ‘Mainland’. One could not a priori rule out that some game trajectories switch back and forth for a while through the so-called ismuth. So the 'travelling point' analogy might be a bit misleading.

I anyway tried to figure out if there is a typical game trajectory in terms of policy distribution. I picked some resign games and no-resign games, splitting the moves between black and white, and although my data don't have the winner side (they could have had, but I overlooked that value in my python script, unfortunately), there seems to be a very regular pattern in games trajectory, in terms policy: 

![game trajectory 1](https://user-images.githubusercontent.com/37498331/43225022-63c22f14-9058-11e8-9d87-6fbf5695cbb5.jpg)

At some point in the game, the (I assume) losing side sees its policy dropping sharply (policy max below 0.1, P_best10 below 0.3), followed suit by the (I assume) winning side, but with some delay and less sharply. Then both sides’ policies exhibit one or more slow rises, followed by sharp falls. I have not yet verified but I assume these may in part correspond to a pattern that I have observed in sgf, where the losing side is progressively filling or trying to leave inside a big opponent territory, with the urgency of some key moves rising over time (living / killing), then big capture happening, that propels the win rate even further down and resets the policy to very flat distribution. Then the process restart again until the next capture of two pass. *(Pure guess)*.

Game resigned early (@92 moves) have the very same pattern (in their falling part at least) as longer ones:
![game trajectory 2](https://user-images.githubusercontent.com/37498331/43225093-97863016-9058-11e8-9618-6b2943bbbf16.jpg)

So it's not a matter of move count/long game, just a matter of the MCTS producing very flat move policy once the win rate has collapsed below some threshold.

For my part, based on this graphs and my previous investigations on no-resign games, here are my main:

**Takeaways/conclusions:**
* No-resign (“-r 0” argument) self-play games accounts for ~15% of the total number of self-play games.
* They typically last 525 moves on average (up to 720 max), vs 165 moves for resign games ("-r 5" argument), that is they are +360 moves longer on average.
* Since they are no different from resign-games by essence but for being continued past the resign threshold, it means that in each of these 15% of no-resign games, 360 moves are played beyond the resign threshold, on average. This accounts for 25% of the total number of self-play moves overall generated / computing resource of the project / training samples used for training new networks.
* The distribution of policy vs move count exhibit a very clear double population, with ~20-30% of positions out of the main distribution, with much flatter policy. This proportion matches the 25% of positions being played beyond the resign threshold.

**Hypothesis/suggestions:**
* Training positions past the resign threshold might not be necessary for LZ to learn how to correctly play endgame. There are enough long games in the resign-games for the policy to learn what is has to learn regarding endgame.
* Such training samples may even hinder LZ progress by adding too few gradient / too much noise to the gradient.
* As a minimum, if some long games are deemed necessary, no-resign games should not be really "-r 0" games but should use some non-null value (1 ot 2% e.g), to stop the games earlier,  so as to save computing resources, and, more importantly, so as to prevent generating a too long ‘tails’ of questionable training data. And removing/reducing Dirichlet noise level in the course of the game past the resign threshold could be considered also.

**Open questions:**
* What is the exact temporal correlation between win rate collapse and policy flattening?
* What part of the tail should be retained in the training data so that LZ can ‘watch the movie untill the end' such as being exposed to sufficiently diverse positions in terms of value span?

The drop in the policy maximum value seems sharper and deeper than the drop I usually observed on LZ win rate chart. I suspect that MCTS with high visits (like 3200) tends to amplify the reaction of the visits distribution to a shift of value towards extreme high/low win rate values. And that while raw policy tends to flatten, the Dirichlet noise amplitude keeps the same (25%). Dirichlet noise can be quite peaky with current alpha. When raw network policy (heat map) is quite flat, Dirichlet noise has higher relative amplitude vs raw network values compared to higher policy sistuation, so noise can propel some random moves high in the prior hierarchy of the search. Under 'normal' win rate value situation, the action-value of the move would prevail over the prior in the course of the 3200v search and these random moves would receive few visits if they were truly bad moves.

In some experiment with LZ/Sabaki, this is not what I observed when position value is a low as 0.02 and Policy Max as low as 0.05. Genuine blunders (I assume picked by Dirichlet noise, there were so bad moves that I can't imagine anything else with my 6kyu go player level) can end-up in the top 5 moves, providing bad training signal to the networks.

### Conclusions:

Having some 'random' moves in the games is not an issue in itself, since what matters for training is the visits distribution, not the move picked. And it's on purpose, to add variety to the games. But having too many random moves is a clear symptom of a too flat move policy, with possibly two negative impacts:
* (1) If the endgame is dominated by randomness, then the game trajectory is no more representative of high level of play (some move sequences reminded me of moves played by early versions of LZ infancy, in 2017! Can we seriously expect much of such part of the games?).
* (2) The corresponding 20%+ training samples have probably very few useful signal and lot of noise.

I'm aware that LZ has climbed to human pro-level using the current training pipeline settings, so if there is a *real* issue with game positions beyond resign threshold, it is definitely not that *serious* an issue. I also note that AGZ/AZ paper does not mention such *issue* although AZ reached top of the sky level. So, if this matters, this is not a show-stopper.

However, it might be that it don’t *prevent* LZ progress but just *slows it down*. It at least slows it down by the 25%+ amount of computing time it takes to process those positions (yielding  on average +165 ‘normal’ training samples and + 360 weird training samples; what is balance/return?). A slowdown that other projects having access to big corporate computing resources may be insensitive to.

So my point is just that these out-of-distribution data representing 25% of the training data, investigating a bit more their quality / usefulness / possible negative impact could be worth.

A simple way (but beyond my reach, with my CPU-only PC!) to test the influence of having these positions in the training dataset would be to take an older network a few versions ago and retrain it over the last million games with and without no-resign games (with equal number of training samples).

Has anyone bit the bait? ;-)

*I’m not optimistic, there are so many networks to be trained these days…*

*Next steps:  ELF value head is said to be much sharper than LZ’s one. I expect that it should play no-resign games even worse than LZ. I will download a few chunks and compare. I also plan some qualitative evaluation of a few sample positions with LZ, to confirm/infirm some of my hypothesis.*

**Comment by NhanHo** [comment]
We don't know which games in the training data is the one with no resign though. That seems to be only available in the sgf

**Comment by Ishinoshita** [comment]
@Nhanho: Correct. With these data, it's not possible to assert a one to one correspondance between the low policy population and the no-resign game population. However:
* Based on other analysis (opening all 400 sgf from the last self-play games on sjeng.) I've seen that very few resign-games go beyond 300 moves. So the vast majority of that 'island' comes de facto only from no-resign games. 
* I just sampled long games (>360 moves) which have a high average P_best10 for one side and they were all games will high policy all along the game but for fall happening for side only, and close to the end. I would bet these games belong to the tail of resign-games.
*Sorry, can't attach example pictures from my smartphone. I'll post later on. *

**Comment by l1t1** [comment]
nice job

**Comment by Ishinoshita** [comment]
@ThorAvaTahr: Thank you for your positive feedback. 

Regarding your point:
"On the other hand, it could also mean that our network has intrinsicly learned to spend it's resources on games that are roughly even and takes no effort to learn what to play in games that are out of balance.

I have done other experiments that I didn't reported here yet, that tend to confirm that the raw network is still very proficient in very late endgame positions. 

I have sampled dozens of no-resign games and let LZ 'replay' them starting from 300 move count till end, with various settings. Most of this games were already out of balance and NN value very low (<0.05 typically). 

Starting from 300 move count, finishing the game with 25v/no randomness instead of 3200v (x128 speed-up) yielded exactly the same outcome (win/loss) than in the actual games, and most of the time led to shorter games and a closer results. Even very tight results (like W+1.5, B+0.5) were correctly reproduced with this setting.
 
Surprisingly (or unsurprisingly for me in fact), even 1po self-play also correctly reproduced the game outcome most of the time.That is no surprise if you consider that LZ policy alone (1po) is at least amateur 4d-5D and that the starting point is each time a position well advanced in the game (+300 moves) in which one side is clearly winning. You would expect two amateurs 5D to be able to clearly count the game or to safely play it flawlessly till end in most cases.

On the qualitative side, I noted that these self-play endgames with 25v or 1p looked very natural from a human perspective. Even if the situations were desperate (losing side was forced to play inside big enemy groups), 1po played locally very decent/meaningful moves (shape move to try to live or steel eyes, decent ko battles, etc....). And that the final position/ score was much closer to what a human player would predict (or that Sabaki would estimate with the 'Estimate' command').

From these preliminary experiments (not yet statistically significant however), I'm inclined to think that the raw network knows how to play very decent endgame, even at unusually high move counts, and that it's the search combined with the randomness that corrupt it.

So I would say that, although we continuously feed him with poor training data regarding endgame, the network generalizes well enough from what he learns from other parts of the game, so as to play decent endgame.

**Comment by gcp** [comment]
>Training positions past the resign threshold might not be necessary for LZ to learn how to correctly play endgame. There are enough long games in the resign-games for the policy to learn what is has to learn regarding endgame
...
>As a minimum, if some long games are deemed necessary, no-resign games should not be really "-r 0" games but should use some non-null value (1 ot 2% e.g), to stop the games earlier, so as to save computing resources, and, more importantly, so as to prevent generating a too long ‘tails’ of questionable training data.

Given that our resign analysis is set at a level where we know there's a certain percentage of games that nevertheless flip, we know that nevertheless it must necessarily still make "total" mistakes, i.e. that it's scoring games as 95% won and then losing them regardless. And the setting is exactly such that this amount can still be measured in percentages. The resignation is there to find and learn out of those.

Without this procedure, you can't really discover the mistakes, no?

Said differently, the resign threshold isn't set arbitrarily. It's set at the lowest value that doesn't produce too much mistakes. The *amount* of no resign games is another matter, we have no data on what works aside from the AGZ paper. But at least one person reported that not doing no resign games caused serious problems, IIRC.

**Comment by gcp** [comment]
If I had to try for a fundamental fix, I'd try to re-weight the policy loss versus the value loss in such positions. But to go from that idea to something more concrete that works...

**Comment by ThorAvaTahr** [comment]
- Said differently, the resign threshold isn't set arbitrarily. It's set at the lowest value that doesn't produce too much mistakes.

**Comment by Ishinoshita** [comment]
@gcp : I think I got well the reasons behind the need to monitor the resign threshold using some no-resign games. We want the value target to be reliable even for resign game (less than 5% false-positive). However, what I still fail to figure out  is:
* Do the project actually use the no-resign self-play games of the training for the purpose of monitoring the resign threshold ? 
I understand that the script resign-analysis.py requires the log of the games, what the training data don't have of course, so that resign analysis are done completely off-line by generating a bunch of new self-play games with autogtp with --debug option, then by running the script on those games (like here https://github.com/gcp/leela-zero/issues/1100#issue-308343409). Am I wrong ? If not, then I don't see the relationship between the need to monitor the resign threshold validity and the 15% of no-resign self-play games generated by the clients and used for training.

*  Isn't the notion of false positive a little bit more *relative* for LZ with current settings than for AGZ ? Randomness introduced in move picking (proportionally to visit, τ = 1) randomizes the move policy and thus introduce some variance in the game outcome.
   * AGZ used:
> For the ﬁrst 30 moves of each game, the temperature is set to τ = 1; this selects moves proportionally to their visit count in MCTS, and ensures a diverse set of positions are encountered. For the remainder of the game, an inﬁnitesimal temperature is used, τ→ 0.

   * For AGZ, suppose that in a game, after 25 moves, black has a lead after the opening and should win. But at move 26, temperature select a suboptimal move for black and the game is flipped. Black=loss will be used as value target for all positions in the game including the 25 first for which black was leading. But this may happen only for the first 30 moves, so, for the vast majority of positions, game outcome will have less/no variance (but for Dirichlet noise ?).

   * LZ uses  τ = 1 all game long (--randomcnt =999) for self-play games. This means that suboptimal moves can be played at any time in the game and can make it flip several times. Suppose a black has a sure lead @200 moves count (win rate high), but by small score margin (say 5.5pts). At move 201, temperature causes black to screw and endgame local sequence and the game flipped. Then "black=loss" will be applied as training target for all positions, including the 200 first positions.

    * This also affects the resign analysis, which uses self-play  games generated with the 'ordinary' autogtp command. I.e. randomness is present all game long and is intrinsically causing some false positives. Strictly speaking, for resign analysis purpose, shouldn't a resign threshold be set *a priori* and , in the self-play game, and temperature turned off once this threshold is reached ?

**Comment by qzq1** [comment]
@Ishinoshita, your presentation was extremely interesting and helpful to me.  Your summaries of the LZ methodological underpinnings, the data and issues are very clear.  Thanks.  
When I notice that my process has drawn a selfplay with resign=0, my heart sinks, because I know it will be interminable, with mostly uninteresting moves.  While your analysis suggests that at least some of that is likely to be wasted effort, I appreciate better the value of such games.

**Comment by Ishinoshita** [comment]
@qzq1 

> While your analysis suggests that at least some of that is likely to be wasted effort,

I'm not that affirmative, I don't have any evidence to say so. I just say that given their proportion and difference, it would be worth to evaluate their  impact/usefulness. I'm bound to just 'suggest' because unfortunately I can't contribute to the answer, having neither the hardware nor the proficiency to test it my self.

**Comment by Ishinoshita** [comment]
**Just an update: LZ156 vs ELF:**
*I recrafted my analysis on LZ156 (capturing side to play, winner/loser, and pass move policy), sampling other chunks for checking consistency vs previous analysis (answer: yes) and I did compare with ELF. ~1M positions for each net.*

* See details in PowerPoint:  [LZ156 vs ELF.pptx](https://github.com/gcp/leela-zero/files/2246639/LZ156.vs.ELF.pptx)

* ELF self-play games are shorter on average: 
![image](https://user-images.githubusercontent.com/37498331/43479932-08629380-9502-11e8-8f24-c76433d97344.png)

*  And more ELF self-play games are resigned early (20% vs 9%) @92 moves (artifact):
![image](https://user-images.githubusercontent.com/37498331/43479796-92b713ea-9501-11e8-8a19-32a512ff16ea.png)

* Policy Max distribution
![image](https://user-images.githubusercontent.com/37498331/43480019-4ede0e20-9502-11e8-863c-081c3ccfe076.png)
Let aside 'flat policy' secondary population, LZ156's policy is more spread towards low values than ELF's one, less peaky compared to ELF. ELF is more opinionated, one could say.

* Top10 move cumulated policy:
![image](https://user-images.githubusercontent.com/37498331/43480138-a0346724-9502-11e8-85d9-bffa204635ca.png)
* ELF is not 'allowed' to play no-resign games (https://github.com/gcp/leela-zero/issues/1540#issuecomment-395999346):
> The quality of the endgames was terrible, since ELF has a much more stratified value head than regular LZ networks, and plays very poorly when it's certain it's losing. 

However, there are 'clandestine' no-resign games withion ELF self-play games in the form of games lost very early by one side but continued until the minimum of 92 moves is reached. They exhibit the very same drop in Policy_max/P_best10 as LZ56, and produce the beginning of a secondary distribution with much flatter policy (so called 'island'). So, for both nets, this secondary distribution seems definitively more driven by a search-flattening effect under low/high win rate rather than something intrinsic to the policy head.
![image](https://user-images.githubusercontent.com/37498331/43480949-f25e420c-9504-11e8-947b-89651a3ebca0.png)

* Pass move probability:
Most of LZ156 games (but not 100% of) exhibit a surge in pass move policy once the policy max/policy_best10 starts collapsing. This can be observed on some ELF games (like the @92 moves games) but not on the majority of the games.

**Comment by Ishinoshita** [comment]
Addition of a fraction of ELF self-play games in the training window has proved beneficial.
ELF self-play games differ from LZ self-play games in 3 ways:
(1) they are played by a different network (diversity)
(2) they are played by a stronger network (mentoring)
(3) they are not played beyond 5% resign threshold (no 'no-resign' games, no flat policy data)

(1) and (2) are widely admitted as the reasons explaining why ELF games help. (3) has never been discussed AFAIK. When ELF appeared and it was considered to use it to generate self-play games for training LZ, it has quickly been ruled at some point that ELF endgames were so terrible that including no-resign self-play games would hurt. And de facto, implicitely, ruled that LZ endgames were good enough and that including LZ no-resign self-play game wouldn't hurt (to be more exact, it has been implicitely ruled that *continuing* to include them wouldn't hurt, since this is what has been done since the beginning).

Testing the effect of (3) alone by re-training an old 15b network on resign games only is not very attractive. We have now jumped to 20b, 15b is the past, training a 15b net would be 'just for science'. Morever, there is practically no way to sort out past training data by resign threshold. Dedicated code would be needed to reconstruct the move count and sorting out training samples with move count higher than some arbitrary cutoff value (like 350 moves). The more I think to it, the less I find probable that anyone with training capability would do it.

An alternative way to test the effect of (3), that would required zero line of code,  just changing a constant at training server side, would be to turn off no-resign self-play games during some time (1 or 2 weeks) and seee what happens. The drawback is that this is a 'live' test.

I don't advocate this right now of course. There are already big changes on-going, testing this probably needs some reliable baseline.
