### ISSUE TITLE
3D-printing LeelaZero's networks?

### ISSUE THREAD

**Issue by Roman102** [gcp/leela-zero#1663]
Hi,

I just wanted to know, whether it would be useful to 3d-print LeelaZero's network?

https://www.the-scientist.com/news-opinion/ai-object-recognition-system-operates-at-speed-of-light--64569

Would there be any benefit if this was possible? What are the possibilities of this approach?

**Comment by gcp** [comment]
I saw references of both 91% and 95% accuracy, which given that they seem to be talking about MNIST, is terrible.
