### ISSUE TITLE
the winrate of the 1st 20x256 weight (generated by training 9.04M+32K) is about 0.2

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1667]
it seems a bit weak
![2018-07-29_140710](https://user-images.githubusercontent.com/23301704/43363507-d6b5287e-92f5-11e8-8d01-4b1761816318.png)

**Comment by l1t1** [comment]
it's winrate is very like @bjiyxo v20 and @gcp v1
![2018-07-29_141401](https://user-images.githubusercontent.com/23301704/43363574-2162215a-92f7-11e8-908c-40a206dad48f.png)

**Comment by l1t1** [comment]
if v21-96k or v21-128k could PASS, can one of them be force promoted?

**Comment by BITINT** [comment]
**### THIS IS NOT GOOD. THIS IS FUCKING NOT GOOD AT ALL!!!!!!!!!!!!!!!!!!!!**
