### ISSUE TITLE
Please return to 15blocks

### ISSUE THREAD

**Issue by ainixingo** [gcp/leela-zero#1668]
The current self-play spectrum is 20*256 of v1600
The previous self-war spectrum is 15*192 of v3200

Obviously, the quality of the current game is not as good as before, if the visits are lowered
Is it true that test match should also use 20*256(v1600) vs 15*192(v3200)

Maybe back to 15blocks
Change the condition of pass of 52%/53% to effectively improve the chess power of LZ?

The premise of adding blocks is that the quality of the new self-war spectrum must be higher than the old ones?

Running a lot of low-quality games will only drag leelazero, wasting power

**Comment by ainixingo** [comment]
Continue to use this
 64cb819d8.991M+256k192x15  VS Regular Match d351f06e8.729M+192k192x15 | 211 : 187 (53.02%)

just change the pass rate by 55% to 52% or 53% and continue to run 15b192f

**Comment by jkiliani** [comment]
Bootstrap nets regularly need training on their own self-play games to become stronger. 192x15 was stalled, we just need to have some patience with 256x20.

**Comment by kennychenfs** [comment]
I also agree.

**Comment by wonderingabout** [comment]
15b is stalling, unless you put a lot of computing power on it its going to be very slow to improve any further, the time we waited in june-july makes it quite clear now

to gain more strength, and more generally develop deeper and more complex playstyle, a network naturally has to grow wider

also dont forget leela zero is a project, this idea can be tried and if it doesnt work well then its alwaays possible to go back and try something else, and we'll gain knowledge and experience from this experiment (but in the end, the natural path is to grow wider)

what i'm wondering about is if an abnormal regression was accidentally introduced in some way in the 20b training, and if we didnt promote it too, but if thats the case, it will be clear soon or later, so just watch the experiment and enjoy it

**Comment by kennychenfs** [comment]
I think its winning percentage seems to be worse than expected, so I just
said so.

wonderingabout <notifications@github.com> 於 2018年7月29日 週日 20:09 寫道：

**Comment by hzyhhzy** [comment]
I think it's 1600v that caused this situation.When use 1600v,the quality of self-play games become much worse.So the new weights are not good.When 6b to 10b and 10b to 15b,the first weight is much stronger.It produced many good games .So many new weights passed in the first several days.

**Comment by jkiliani** [comment]
That the change In visits has anything to do with the quality of current trained nets defies logic: When this training run was started, no or very few 256x20 self-play games were available yet. This run is not even using the self-play games at 1600 visits, so could they possibly affect anything?

We have to be more patient than this. The next training run, first one with the 256x20 games, is when we might at least begin to evaluate how the bootstrap with change in visit number is working out.

**Comment by kfc51151271** [comment]
The decline in the quality of the self-play game is obvious, for the #157 at 3200v (we have ran nearly 257k games in this setting!) beat #158 at the same visit. And then we started using a weaker network(#158) to run at a lower visit (1600v), right? I don't quite understand how it would be helpful to reduce the quality of the games in training if you failed to train a strong network with the stronger games...

Of course, I support switching networks because it seems that the progress of 15x192 is stalling, but maybe not 20x256? The well-trained 20x224 network (elf) can only reach a winning rate of 75% at the same visit. Maybe 20 block is not a very efficient choice? Just a guess...

**Comment by Ishinoshita** [comment]
Given the length of the stall and of discussions in #1113 and #1625, we can assume @gcp and other devs have made a thoughtful and much weighted decision, even if success is never guaranted *in advance*. Rushing to say it is a wrong or a bad choice just after 24h is futile and pointless. Let us all just be a bit patient. And we will see what happens.
