### ISSUE TITLE
Leela Zero will be absent from the coming tournament.

### ISSUE THREAD

**Issue by bjiyxo** [gcp/leela-zero#1678]
Hello everyone. We are the team members who represented Leela Zero to play in the last two tournaments (“2018 World AI Baduk Tournament” and “2018 Tencent World AI Weiqi Competition”). We would like to apologize to the supporters/fans of Leela Zero that we will be absent from the coming tournament (2018 second CITIC Securities Cup World Intelligent Open Go Tournament #1573).

Zhang Qi(章琦), who has asked the authorization from gcp, the original author of Leela Zero, for the past two tournaments is one of our team members. However, Zhang Qi did not have the authorization from gcp for the coming tournament, and he registered the team under the name “Super Leela” with the first author being himself. All other team members were not aware this until recently. We do not agree the participant of Leela Zero in this format, and we believe that supporters/fans will not accept it, either. Therefore, we will be absent from this tournament. Here we would like to clearly clarify that Leela Zero and the team played in the past two tournaments have no business with the participant/result of the team “Supper Leela” represented by Zhang Qi.

Joint declaration from the Leela Zero team: 轰轰烈烈死(bjiyxo), 榜爷, 三喵无敌, 飞, Mankit Pang.

**Comment by diadorak** [comment]
So the two guys named "Zhang Qi" are no different after all.

**Comment by denniscxc** [comment]
where will 40B be released？

**Comment by kfc51151271** [comment]
So "Zhang Qi" used LeelaZero(rename to "superLeela") to participate in the tournament and claimed to be the first author, right? @gcp  What do you think about this? Anyway, I am happy to see that 40b is about to be released...

**Comment by l1t1** [comment]
https://github.com/gcp/leela-zero/issues/1636

**Comment by gcp** [comment]
>What do you think about this?

It's up to the tournaments to set rules regarding program originality and make sure they can verify authorship.

Leela Zero is open source code, and the restrictions the license places are on distribution. I can't stop anyone from entering derived works into tournaments, nor can I magically see from a distance what code a non-public program is based on.

**Comment by alphaladder** [comment]
support the real LZ group! And GCP is the 1st author for our LZ,not this Qi Zhang coming from somewhere,who is even  a layman with zero knowledge in the computer science .

**Comment by ChangweiZhou** [comment]
I think you meant "Super Leela", right? Anyway I saw the notifcation online. Thanks for all the hard work.

**Comment by l1t1** [comment]
suggest relase the 40b weight as gz format, that is more convenient.

**Comment by l1t1** [comment]
and use 7z.exe to max compression gz to save space

**Comment by zhanzhenzhen** [comment]
oh 40b!!! really?

**Comment by herazul** [comment]
yeah 40b hype \o/

**Comment by ainixingo** [comment]
40b?

**Comment by gcp** [comment]
I'm going to close this topic because there are two sides to every story, and it's impossible for me to determine who is right or telling the truth.

I received a request from @bjiyxo for permission to play in this tournament with LZ, and not from anyone else, so I gave it.

**Comment by bjiyxo** [comment]
@gcp 
I was informed from the Naning committee that

1.They disqualified “super leela”.
2.They finally decided to refuse Leela Zero register as a new team since the deadline passed quite a while.

Anyway, I am still very grateful for your willingness to believe me and give me your permission in a short time.

**Comment by bjiyxo** [comment]
Only when gcp wants to start 40b
.

**Comment by l1t1** [comment]
http://sports.sina.com.cn/go/2018-08-12/doc-ihhqtawx4163654.shtml
fineart also exit

**Comment by l1t1** [comment]
misunderstood?
https://tieba.baidu.com/p/5839171293
