### ISSUE TITLE
Caffe prototxt files

### ISSUE THREAD

**Issue by OmnipotentEntity** [gcp/leela-zero#1684]
Just double-checking something, because I don't understand why it is the way it is.

In the zero.prototxt is intended to be a 40x256 network description.  There are 39 residual blocks marked by comments.

In the zero_mini.prototxt is intended to a 12x256 network description.  There are 12 residual blocks marked by comments.

I figured when I saw the first one that there was one non-residual block not marked by a comment, but when I checked the second one I became very confused.  Can someone clarify this for me?

**Comment by gcp** [comment]
It's probably just me who wasn't sure yet at that point whether to include the input layer in the count or not. Don't read anything into it. Those Caffe files were used to train networks to test the original code (hence the mini and nano!) based on a very hacked up version of Leela that incorporated Caffe parts, before I had finished writing the TensorFlow code.
