### ISSUE TITLE
Windows 10 GPU stats

### ISSUE THREAD

**Issue by bvandenbon** [gcp/leela-zero#1685]
Here I have LeeLa Zero running on 2 different computers.
Since the latest Windows 10 update, there is a GPU monitor added in the task manager.

**1) Desktop computer with NVidea GTX 970** 
note, the 22% , why not 100% ?

![gtx 970](https://user-images.githubusercontent.com/20482760/43614268-056ecca4-96b3-11e8-99ed-dfe92d283378.png)

**2) A laptop with NVidea GT 630M**
0% for 3D , but 100% for "Compute_0" ?
--> slower than running it in CPU mode. 
but hey it's just a laptop, right ?

![2018-08-03_000852](https://user-images.githubusercontent.com/20482760/43614274-0ad0f546-96b3-11e8-9b11-faff4e67cad4.jpg)

I was just wondering if some of these stats indicate a driver issue ?
In particular I find it a little strange that for the GTX 970, it runs at around 22% (why not more ?)
And it's strange by contrast that for the mobile GPU, the "3D" (whatever that may be) is not used at all.

Anybody has a clue/understands what is going on ?

**Comment by thalessa** [comment]
"M" class GPUs are low-power mobile chips and basically terrible, and the 630s are old. I checked synthetic benchmarks and it's slower than a modern integrated GPU. Your 970 is about 15x faster.

On the desktop, how many threads are you running?

**Comment by diadorak** [comment]
Use GPU-Z. 

The built-in GPU monitor of Windows 10 always under reports GPU usage.

**Comment by gcp** [comment]
Switch the display from "3D" to "Compute_0".

**Comment by bvandenbon** [comment]
I'll give that a try, whenever I have the chance.
Thanks
