### ISSUE TITLE
next: --keep isn't respected in Validation mode

### ISSUE THREAD

**Issue by gcp** [gcp/leela-zero#169]
./autogtp -g 8 -c -n 265k.txt -n 137k.txt -k games

The games don't seem to be saved. @marcocalignano

**Comment by jkiliani** [comment]
Would this have anything to do with https://github.com/gcp/leela-zero/commit/4b34742566a531d53fb86e879ff56056516ac048 ?

**Comment by gcp** [comment]
Maybe, though "-k" also needs to respect the directory give, so I'm not sure it's that exact code without looking.

**Comment by jkiliani** [comment]
Obviously it should, but from what I saw in the code, Validation.cpp doesn't accept the -k parameter.

**Comment by marcocalignano** [comment]
I did a pull request to fix this bug

**Comment by marcocalignano** [comment]
#171
