### ISSUE TITLE
Next branch crashes my graphics driver and hangs without an error message

### ISSUE THREAD

**Issue by ThorAvaTahr** [gcp/leela-zero#1690]
Next branch crashes my graphics driver. I get a black screen, the screen recovers and than i get a message that my graphics driver had crashed. Leelaz consequently hangs. It seems to occur after tuning,  see log below.

I am on windows, compiled with visual studio 15. i5 with internal gpu.

> Using 2 thread(s).
RNG seed: 5710141151861584013
Detecting residual layers...v1...64 channels...5 blocks.
Initializing OpenCL (autodetect precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 
Platform profile: FULL_PROFILE
Platform name:    Intel(R) OpenCL
Platform vendor:  Intel(R) Corporation
Device ID:     0
Device name:   Intel(R) HD Graphics 4400
Device type:   GPU
Device vendor: Intel(R) Corporation
Device driver: 9.18.10.3324
Device speed:  400 MHz
Device cores:  20 CU
Device score:  612
Selected platform: Intel(R) OpenCL
Selected device: Intel(R) HD Graphics 4400
with OpenCL 1.2 capability.
Half precision compute support: NO

Started OpenCL SGEMM tuner.
Will try 290 valid configurations.
(1/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.5602 ms (13.2 GFLOPS)
(2/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.4209 ms (17.5 GFLOPS)
(3/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.3682 ms (20.0 GFLOPS)
(5/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.3057 ms (24.1 GFLOPS)
(6/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.2780 ms (26.5 GFLOPS)
(14/290) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.2605 ms (28.3 GFLOPS)
(15/290) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.2308 ms (31.9 GFLOPS)
(197/290) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=4 0.2159 ms (34.1 GFLOPS)
Wavefront/Warp size: 8
Max workgroup size: 512
Max workgroup dimensions: 512 512 512 
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 
Platform profile: FULL_PROFILE
Platform name:    Intel(R) OpenCL
Platform vendor:  Intel(R) Corporation
Device ID:     0
Device name:   Intel(R) HD Graphics 4400
Device type:   GPU
Device vendor: Intel(R) Corporation
Device driver: 9.18.10.3324
Device speed:  400 MHz
Device cores:  20 CU
Device score:  612
Selected platform: Intel(R) OpenCL
Selected device: Intel(R) HD Graphics 4400
with OpenCL 1.2 capability.
Half precision compute support: NO

Started OpenCL SGEMM tuner.
Will try 290 valid configurations.
(1/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.3584 ms (20.6 GFLOPS)
(4/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.3104 ms (23.8 GFLOPS)
(5/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.3059 ms (24.1 GFLOPS)
(21/290) KWG=16 KWI=2 MDIMA=16 MDIMC=16 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.2955 ms (24.9 GFLOPS)
(22/290) KWG=16 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.2914 ms (25.3 GFLOPS)
(27/290) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.2808 ms (26.3 GFLOPS)
(32/290) KWG=32 KWI=2 MDIMA=32 MDIMC=32 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.2684 ms (27.5 GFLOPS)
(125/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 0.2360 ms (31.2 GFLOPS)
(136/290) KWG=16 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 0.2080 ms (35.5 GFLOPS)
(281/290) KWG=16 KWI=8 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=4 0.2079 ms (35.5 GFLOPS)
Wavefront/Warp size: 16
Max workgroup size: 512
Max workgroup dimensions: 512 512 512 
BLAS Core: Haswell

**Comment by jkiliani** [comment]
Connected to #1672 maybe? Seems suspicious, to have this type of crash so shortly after half-precision support is merged...

**Comment by ThorAvaTahr** [comment]
it seems there is  a relation,

I have reverted all changes since 28-7-2018 and the result is different now. It get's through the tuning and allows me to enter the genmove command, but then the same behavior: crash of graphics driver and hangs

**Comment by gcp** [comment]
The video drivers seem to be over 5 years old.

In any case, if the graphics driver crashes, guess where the bug is...

**Comment by ThorAvaTahr** [comment]
> In any case, if the graphics driver crashes, guess where the bug is...

not very helpful :( 
I spent a day figuring out how to update my drivers for this company-managed laptop that has an OEM managing the drivers. I managed to update the driver, but problem persists.
Perhaps superfluous to mention, but master branch works just fine (and has some double the GFlops in the quick-tuning)
