### ISSUE TITLE
[Poll] Should it be "filters x blocks" or "blocks x filters"?

### ISSUE THREAD

**Issue by TFiFiE** [gcp/leela-zero#1696]
Right now, the website reports network sizes in the format "filters x blocks" (e.g. 256x20), but I think "blocks x filters" makes more sense, as a network consists of blocks of filters and also because it's the number of filters that tend to be left out as a shorthand.

Before following through at [the proper place](../../leela-zero-server) for such a change, I'd like to hold an informal poll on this here (this being the more visible and active repository):

- If the format should be changed to "blocks x filters" (e.g. 20x256), give this comment a thumbs-up: :thumbsup:
- If it should stay "filters x blocks" (e.g. 256x20), give it a thumbs-down: :thumbsdown:

**Comment by Ishinoshita** [comment]
I'm confident a 20x256 network will beat a 256x20 network consistently. By 55.0001% I would say.

**Comment by Crazyeight101** [comment]
Don't bother trying to force the issue; just let people express it whichever way they like.  The meaning gets across either way, so this is a pretty innocuous issue...

**Comment by Diapa** [comment]
I think both make sense
20x256:   20 times 256
256x20:   256, 20 times
