### ISSUE TITLE
why 20b weights step jump from 256k to 384k?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1700]
step |diff
-|-
32|
64|32
96|32
128|64
192|64
256|64
384|128
512|128 ?

**Comment by alphaladder** [comment]
just a test

**Comment by l1t1** [comment]
if diff was 64, there would be 2more weights maybe pass

**Comment by 2ji3150** [comment]
See? Your issue which is not an issue has been closed again and again. Stop Annoying

**Comment by l1t1** [comment]
if you know why then you answer, if you don't know your reply also Annoying
