### ISSUE TITLE
evil is continuing uploading problematic games!

### ISSUE THREAD

**Issue by alphaladder** [gcp/leela-zero#1711]
This evil now began to change the parameter from  r6 to r5 to circumvent the inspection.And continuing to upload trash games!

If next time evil change to basic time from 60 min to 0 ,there is nothing I could do. 1/10 games have similar problem,all of which are old zero self play games.

Some mafia plan to destroy the whole leela program due to commercial interest.

http://zero.sjeng.org/view/8a7f417b62d3d72a9f5bab09ffb2b15594fe6a13288c7ba5ddb63d5c0ffe134a?viewer=

http://zero.sjeng.org/view/ecbcc3cd2e2a4976dfbb2be81a006285d9a37bb2ca55fc0b3c6cf8b0eaa1e149?viewer=wgo

http://zero.sjeng.org/view/984319467fd043c7fe398fb9d48345d6d703d5ba3ab16a4fc786b2cc190a999d?viewer=wgo

http://zero.sjeng.org/view/5bd064416ae667eaf3b11a35c3feebf81ab2d4dedb46b79adbccde3afdfe58db?viewer=wgo

It is obviously that that evil had modified the Leeaz.exe and  batchy upload those old junk or old zero games.

**Comment by roy7** [comment]
I'm unsure how you are concluding these games are problematic. Can you clarify? The IP address these come from I recognize and I know this is not an attacker.

**Comment by Eddh** [comment]
Yeah this time it looks like the usual no-resign games played to the max :/

**Comment by alphaladder** [comment]
@roy7 ok，thank  you for your confirmation
.will close it.

**Comment by roy7** [comment]
Thanks. Remember training games use lots of randomness.
