### ISSUE TITLE
Where are there so many games with basic time 60 minutes?

### ISSUE THREAD

**Issue by hzyhhzy** [gcp/leela-zero#1712]
Are they uploaded by that bad guy who uploaded pro games?

**Comment by hzyhhzy** [comment]
If not,why it happens?

**Comment by fame872toe857** [comment]
-r 0

**Comment by hzyhhzy** [comment]
-r0 has nothing to do with 60 minutes basic time

**Comment by heqikun** [comment]
Do you mean the default of each step for 60 seconds?

**Comment by gcp** [comment]
AutoGTP by default should set infinite time with time_settings 0 1 0. Did that get broken or did someone modify it on his client?

**Comment by gcp** [comment]
See issue #1705.
