### ISSUE TITLE
the proportion of elf v1 selfplay games is too high

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1717]
from http://zero.sjeng.org/self-plays snapshot
lz 162+ lz 163 games only 118, and elf v1 =400-118=282, about 2.4 times of 118.
[self-plays.zip](https://github.com/gcp/leela-zero/files/2276507/self-plays.zip)

**Comment by l1t1** [comment]
[self-plays2.zip](https://github.com/gcp/leela-zero/files/2276514/self-plays2.zip)
this 400 games, lz 162+ lz 163 games only 100, and elf v1 =300, 3 times of 100.

**Comment by l1t1** [comment]
[self-plays4.zip](https://github.com/gcp/leela-zero/files/2277020/self-plays4.zip)
most of the elf v1 games played on 1 client.

**Comment by kfc51151271** [comment]
It's really strange that this client is generating games too quickly, and almost all are elf-v1 self-play games(very few LZ#162 games, no LZ#163) with the Duration of these games displayed as "????" minutes.

**Comment by jkiliani** [comment]
Agreed, this client looks suspicious. I wonder if only the ratio of ELF games to regular ones is off, or if there is also something wrong with those ELF games? At first glance, I couldn't immediately see a problem with the games however.

**Comment by Ishinoshita** [comment]
ELF v0 played shorter *self-play* games compared to LZ (more sensitive to temperature effect, value collapsing faster?). Maybe v1 value head is even more sensitive and leads to even more shorter games.

**Comment by kfc51151271** [comment]
It seems that the client is still mass producing ELF games... I  can almost see a new ELF game from that client in 1 second. This speed is unreasonable. The _-s_  in  the option of these ELF games is obviously shorter than the other games(e.g.  -s 550006535, one of these games), does it show anything?

**Comment by roy7** [comment]
These are coming from the supercomputer that helps us out now and then. It has over 600 GPUs.

**Comment by diadorak** [comment]
Is it a coincidence that BR is only producing ELF v1 games?

**Comment by roy7** [comment]
I'm not sure where that conclusion is coming from. The log files show in the last 9 days it has done 33K ELF V1 games and 16K a438 games. Note a438 only promoted 18 hours ago. So we're getting just under 1K self-play games per hour on LZ163,

**Comment by roy7** [comment]
Oh interesting, I see what you mean. http://zero.sjeng.org/self-plays shows every game from client #4 is ELF. But looking at my logs I see non-ELF results going out,. And I see prior non-ELF results coming in. But at this second it's all ELF results coming in. I don't have an explanation for that one, maybe @alreadydone can check it.

**Comment by roy7** [comment]
It's also possible the system is set up to do some generation of self plays apart from get-task requests. I'm not sure how it works. I just know now and then the games pour in. :)

In past 10 days or so we've had 46K uploaded ELF games and 80K uploaded non-ELF games from the supercomputer. But I'm not sure why they run in spurts, where all games atm are only ELF.

**Comment by roy7** [comment]
You are correct, thanks for reporting this. There was a problem downloading the latest LZ network weights file. He's working on it.

**Comment by alreadydone** [comment]
Thank you all for spotting the problem. AutoGTP (without modification) falls back to the previous network and generates a seed by itself when downloading the latest networks fails. AutoGTP output show that BR failed to download the network a438 (connection to server failed etc.), but the actual problem seems to be that unzipping failed, for unidentified reason. Now BR is generating a438 self-play games after manual downloading and unzipping a438, but I'm not sure whether the problem will reappear in the future.

**Comment by gcp** [comment]
One reason why unzipping would fail is if the download is corrupted? We added hash checks in AutoGTP, but I'm not sure those are applied in that sequence.
