### ISSUE TITLE
How to compile autogtp as a static executable?

### ISSUE THREAD

**Issue by foreverpokemongo** [gcp/leela-zero#1718]
I have successfully compiled leelaz as a static executable by twisting the method in #1379, but I failed to do so for autogtp. I have added '-static' flag to CXXFLAGS, CFLAGS, and LFLAGS in the Makefile in autogtp folder. Executing 'make' gives the following error message:

/usr/bin/ld: cannot find -lQt5Gui
/usr/bin/ld: cannot find -lQt5Core
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
Makefile:168: recipe for target 'autogtp' failed
make: *** [autogtp] Error 1

Any suggestions?

**Comment by marcocalignano** [comment]
To do that you need a static version of all the necessary QT library. Usually to do this you have to have a commercial QT license and compile the library from the source code.

**Comment by foreverpokemongo** [comment]
For the record, I tried 'a bit' harder and resolved this myself.

@marcocalignano Yes, you are right. I need to build static QT library myself.

After downloading that huge opensource version of Qt and building all static Qt libraries (which took quite a while), I modify the 'LIBS =' field in the Makefile located in autogtp folder as follows (in addition to the changes mentioned above):

change
`LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5Gui -lQt5Core -lGL -lpthread`

to

`LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -L ~/my_Qt5_static_lib_path  -lQt5EventDispatcherSupport -lQt5Gui -lQt5Core -lqtpcre2 -lglib-2.0 -lpthread -lz -ldl`

Then everything works as intended. I can `make` sucessfully, and run the compiled autogtp on another linux machine without trouble. 

Perhaps one does't need to build the whole Qt but only those listed in that LIBS field.
