### ISSUE TITLE
Question about target policy

### ISSUE THREAD

**Issue by TimYuenior** [gcp/leela-zero#1719]
I was under the impression that the target policy would change according to the given temperature with the same formula as for the search: N^(1/t). I noticed in training.cpp that the target labels are always N/sum(N), which is the case where t=1. Wouldn't the case of t=0 yield a vector with all zeros except for one entry that is one? 
I was curious if there is a reason why the target labels are always a simple weighted pick and/or if there has been experimentation with applying max(N) to the case of t=0 for the target policy.

**Comment by Ishinoshita** [comment]
IIUC, in LZ as in AlphaZero, the policy is trained to predict the outcome of the search guided by that policy (and the value head). Without any annealing (t=1).

Using a lower temperature for annealing the visits counts would make the policy more sharp/deterministic but would possibly make the search weaker (see initial AG paper where engine was weaker when using the reinforcement learning policy compared to when using the supervised learning policy). For self-learning, exploration is necessary and too selective policy wouldn't help discover new concepts.

Using a higher temperature would make the policy ans thus the search less selective, and would weaken the level of play.

There is probably a sweat spot in terms of temperature and what is a good policy to guide and learn new stuff. Is it exactly t=1 or should it be 0.8 or 1.2? I don't recall anybody mentioning experiment regarding the effect of that parameter. It's an hyperparameter of the self-play training process itself, so it's hard to investigate but for trying on the main project itself I guess.

**Comment by gcp** [comment]
@Ishinoshita's explanation is very good. With t=0 the policy becomes very selective. A simple example is the search finding one move is 50.0% winrate and another 50.1%, after having spent ~50% of the search effort on each move. Do you want to train to only ever search the 50.1% move and don't look at the 50% move at all, or is keeping to search them both approximately equally better? I suspect the latter and the experience from AlphaGo Lee Sedol also suggests so.
