### ISSUE TITLE
Why did c910dee9 passed despite a relatively low winrate? 

### ISSUE THREAD

**Issue by maxinjapan** [gcp/leela-zero#1730]
Hi. Sorry for the very naive question, but I was wondering why c910dee9 VS 61c4a1b4 passed despite having only a 50.62% winrate after 403 games 
https://www.dropbox.com/s/ydjz0p2ioolsa0x/Screenshot%202018-08-13%2012.57.33.png?dl=0 
while be200aa3 VS a438382b failed despite winning 227 games out of 417 (54.44% winrate). 
Could you please clarify? Thank you

**Comment by jkiliani** [comment]
Look into the sequence of reported game results and you'll see why. At game 112, c910dee9 had 65.18% winrate, which is enough to pass SPRT. The losses started coming soon after that, but the network had already promoted at that point.

**Comment by maxinjapan** [comment]
thanks for the clarification :-)
