### ISSUE TITLE
The server downloads are slow

### ISSUE THREAD

**Issue by alphaladder** [gcp/leela-zero#1731]
@gcp.    I try to start self  play in my computer but it stuck to “starting tuning process “ for 2hrs.Any problem on lz server?restart needed？

Clients drop from 1000 to 45 in the last 2-3 hrs.

**Comment by fell111** [comment]
maybe failed to download the 40b network? The matches amount between 40b and 20b is still 0 after 2 hours.

**Comment by arondes** [comment]
we could use BitTorrent feature to accelerating downloading.

**Comment by alphaladder** [comment]
We can not download weight by autogtp automatically. Big problem!

**Comment by l1t1** [comment]
the matchs are also slow down, maybe  the weights are too big to download

**Comment by diadorak** [comment]
Many Google Colab users are having trouble downloading the networks...

**Comment by Hayden2018** [comment]
Yes. Something is definitely wrong with the server. Download speed is ridiculously slow. It took me 5 hours to download a 50MB weight file. Mean while, I can already download at least a 20GB file. Please fix it.

**Comment by l1t1** [comment]
40b matchs were only played by 4 clients

**Comment by alphaladder** [comment]
There is only 33 clients now!

**Comment by l1t1** [comment]
the new weight to be tested is also delayed

**Comment by roy7** [comment]
It seems to be speeding up some now and there are about 14 clients who have submitted matches. Could needing to download two different 40 block networks overloaded the download speed of the server perhaps? @gcp

**Comment by alphaladder** [comment]
@roy7 No,that is not the case.
The problem had been there for several hours even before the 40b was queued.

**Comment by l1t1** [comment]
should the 40b match be stopped and let normal match start?

**Comment by d7urban** [comment]
I get "Got a new job: match" and then it just hangs. Match is between c910dee and 409bee.

**Comment by l1t1** [comment]
please pause new test matchs until the server is healthy

@bjiyxo

**Comment by bjiyxo** [comment]
Sorry, I don't know how to pause the test matches. @roy7 Need technical helps.

**Comment by ihavnoid** [comment]
Tried manually downloading files, getting 4kb/sec.  Is this a server capacity issue?

**Comment by nukee86** [comment]
Still have a problem with downloading networks - 4-10kB/s on colab, 50kB/s on my PC. It's definitely something on server side, cause both download other sources at >10MB/s

**Comment by roy7** [comment]
Yes the server got throttled, @gcp will investigate when he can, he's away for a bit. Looks like it wasn't a problem with these networks per se but a big spike in traffic earlier this month for some weird reason.

**Comment by l1t1** [comment]
![2018-08-15_071152](https://user-images.githubusercontent.com/23301704/44123373-8ff4deb2-a05a-11e8-8b88-36ee7209f9d6.png)
the number selfplay games  is less than match games in last 24h, is it really?

**Comment by l1t1** [comment]
when the weights get bigger, the chance of download failure is increase.
does the autogtp curl support resume from break-point? if not, all fail clients will try to download again and again,so produce much bigger traffic.
can you try to redirect the latest weights to some cdn server?

**Comment by fell111** [comment]
Maybe we need to do some p2p when download the weight file. All clients get weight file from server at the same time might be the bottleneck.

**Comment by alphaladder** [comment]
@gcp could you mind save the lastest weight in other drive  or server? e.g Google drive. The current bottleneck is that the colab user could not download weight from your server and be stuck there.

**Comment by ChangweiZhou** [comment]
After a lot of effort I am able to download the newest 40b weight file. Here are two public links:

https://www.dropbox.com/s/y168vrzmew9x69a/super2.zip?dl=0
https://drive.google.com/file/d/1AXJfeNTw_Q2v6pY2GV7CTYrdaiDPBFOv/view?usp=sharing

I am okay if @gcp use it as the default download link.

**Comment by ChangweiZhou** [comment]
I re-named the file and used *.zip instead *.gz as it is easier to unzip.

**Comment by roy7** [comment]
Note the client can use the gzip'ed weights directly, they don't need to be unzipped. :)

**Comment by gcp** [comment]
Same for all proposals to semi-manually mirror files, that's not workable, there is no point in proposing this.

>for max save traffic, I also suggest again to move self-paly sgf.xz to other place and split it to pieces of each weights, just as the training data did, as people are more interested in recent games.

This also has been offloaded a long time ago to a separate server. The traffic is all from the last few networks.

**Comment by gcp** [comment]
>can you try to redirect the latest weights to some cdn server?

This is what we're doing now FYI.

**Comment by gcp** [comment]
>I am okay if @gcp use it as the default download link.

Please, please try to understand the traffic we're talking about here before commenting. Dropbox will cut you off at 20 GB per day. We are generating over 2500 GB of traffic per day.

If I would use this link, your account is going to be disabled in a matter of hours.

**Comment by gcp** [comment]
It looks like about 2/3rd of our traffic is hitting cache now, which is good (and the caches easily max out my connection). 

What is not so good is that for regions where things aren't in cache yet, it won't even finish downloading. I was hoping that the above would leave enough bandwidth to resolve the issues. I'm already talking to my hoster to see the best options here to get the main server uncapped.

**Comment by ChangweiZhou** [comment]
Do you think Google also has a download limit? Thanks for the feedback.

**Comment by gcp** [comment]
>Do you think Google also has a download limit? Thanks for the feedback.

Almost certainly. Pulling 75 TB of traffic costs real money.

**Comment by l1t1** [comment]
do you check the fail rate of different file size? consider to split one 20b file into 2 files and merge them at client?

**Comment by gcp** [comment]
Again, this needs updates to the server code and AutoGTP client code and doesn't solve anything whatsoever traffic wise.

**Comment by ihavnoid** [comment]
Current situation:
- Selfplay seems to run fine - network download is very quick
- When playing match games, it is trying to download 3b5a964 and that gets back to super-slow.  Hence all my autogtp processes are stuck trying to download match game nets.  I am not an expert on CDNs, but is it that there are some nets that are not cached in the CDN yet?

**Comment by l1t1** [comment]
clients 300+ last hour

**Comment by PhilipFRipper** [comment]
@gcp "Pulling 75 TB of traffic costs real money."

Is distributed effort still a cost realistic goal?  We don't want you personally suffering to provide us with so much.  Please take care of yourself.

**Comment by gcp** [comment]
> I am not an expert on CDNs, but is it that there are some nets that are not cached in the CDN yet?

Yes, that is the problem. CDN caches are local to regions, so it may be fast in some places and slow in others.

**Comment by gcp** [comment]
>Is distributed effort still a cost realistic goal?

Yes, we (=me + donations, prize money, etc) can afford this. But that doesn't mean I'm not trying to be cost-conscious here.

My point was more that you can't normally get such bandwidth for free, and that services like Dropbox etc. will cut you off if you pull that kind of traffic.

I saw a number somewhere that 350 TB/month = maxing out a 1 GBps network interface. So if you have a 100Mbps server with unlimited traffic, that's not actually good enough.

**Comment by gcp** [comment]
The server is uncapped again.

I'll monitor how efficiently the CDN works and make a decision what to do with hosting when there's a bit more data on what we require now.

**Comment by l1t1** [comment]
it looks the server is healthy now
current match, receive 85 clients in 100+ games
![2018-08-15_203840](https://user-images.githubusercontent.com/23301704/44148583-8ade17e2-a0cb-11e8-8224-1518cc862e8e.png)

last match, receive 85 clients in 300+ games
![2018-08-15_204005](https://user-images.githubusercontent.com/23301704/44148631-ae808b3a-a0cb-11e8-9e11-0e28769a1117.png)

**Comment by liujn2018** [comment]
@gcp , we have manually mirrored the latest network files in google drive and almost all the Chinese Google Colab users (hundreds of g accounts) are using the mirrors.
Let's see what will happen.

**Comment by dayun110** [comment]
@gcpI noticed that you are checking the server traffic flow. Hereby, I'd like to remind you the following two facts that might cause you mis-count on server traffic volume of these two days. To deal with the very slow download speed; as @liujn2018  said, (i) for Google Colab users, they are downloading latest network files from google drive. Five people are responsible for downloading ELF, latest passed network and current match network and upload to Google drive. Around 700-1100 clients are taking this way.  ii) for personal computer users, they are running autogtp by downloading latest network files to local machine.  Around 100 clients I knew are doing this way.  These temporary measures work fine, downloading 3 network files only takes less than 5 seconds within Google servers. But it takes too much manpower to monitor the LZ website to check network updating,, downloading from LZ website and uploading to Google drive, and updating running code. It would be great if this could be done automatically. Moreover, we also worried about that google side might block those accounts with extreme increase in traffic.  Thanks.

**Comment by foreverpokemongo** [comment]
> 40 block nets are a bit less than 200M a piece. We do about 5 test matches per day. Maximum amount of clients per day is typically <1500 (but the majority of them won't see all tests, so say less than half?). So realistically with 40 blocks I'd expect to see 750G to 1.5 TB per day max. Not 2.5 TB.

Such phenomenon suggests that many traffic are not created by autogtp, but (perhaps) by direct download from links in the homepage. This is not surprising because now people are aware that leela-zero can beat pro-players. I believe not only professionals but also more and more amateur go players are downloading the most recent best-network frequently.

Assuming my speculation is correct, my suggestion is to replace all the links explictly provided in the homepage with torrent files, so as to offload traffic created by those who are not contributing computational power to P2P network. Maybe such people are able to enjoy faster downloading speed from P2P network.

**Comment by MartinDevelopment** [comment]
> can easily verify this by comparing the IP addresses of those uploading games and those downloading weightings?
Not possible since we don't store any personal information.

**Comment by foreverpokemongo** [comment]
> Not possible since we don't store any personal information.

Didn't know that. :)

I think the IP addresses of game-uploaders are logged; otherwise we cannot block malicious uploaders.

Anyway, the purpose is just differentiating self-play contributors from pure-downloaders. Maybe we can compare SHA3 hash of IP addresses. There must be one way or another to do so, without (seriously) compromising privacy.

**Comment by gcp** [comment]
>consider only keep weights not finally failed yet and current best and elf as a benchmark?

We already do this. Most of the old weights are on the storage server.

**Comment by gcp** [comment]
>Not possible since we don't store any personal information.

We do log (and are allowed to log) IPs for a short period of time to handle abuse and keep the server functioning. I've asked roy7 if he has some time to dig in what happened.

**Comment by gcp** [comment]
>my suggestion is to replace all the links explicitly provided in the homepage with torrent files, so as to offload traffic created by those who are not contributing computational power to P2P network

If this project makes it (even) hard(er) for Go players to use Leela Zero, it would have failed at its purpose.

**Comment by gcp** [comment]
I currently see a hitrate on the CDN of 85% and it's still rising. So we should be fine hosting-wise with a regular solution, or maybe even our current one, as traffic dropped by a factor >x6.

This also means that downloads for most of you who aren't in Europe (where the server is!) should be significantly faster, i.e. West Coast USA and China/Japan/Korea. I'm curious how the speed is for people inside China. From what I understand, there is no CDN location inside China (because this requires specific agreements) but the location you're downloading from should still be much closer to there.

**Comment by dayun110** [comment]
@gcp, I am using 100Mbps which is below average level in China. The network download speed is about 0.5Ms/ to 1M/s.

**Comment by l1t1** [comment]
in my pc
```
C:\>e:\wget http://zero.sjeng.org/networks/c
4d760dadf7979b740b52ff932ba00207adf25d84ae03bb93b00fe642e7d9407.gz
--2018-08-17 07:37:15--  http://zero.sjeng.org/networks/c4d760dadf7979b740b52ff9
32ba00207adf25d84ae03bb93b00fe642e7d9407.gz
Resolving zero.sjeng.org... 104.27.188.119, 104.27.189.119
Connecting to zero.sjeng.org|104.27.188.119|:80... failed: Connection timed out.

Connecting to zero.sjeng.org|104.27.189.119|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 93589184 (89M) [application/octet-stream]
Saving to: `c4d760dadf7979b740b52ff932ba00207adf25d84ae03bb93b00fe642e7d9407.gz'


 0% [                                       ] 127,150     6.34K/s  eta 4h 11m
```

**Comment by MartinDevelopment** [comment]
@l1t1 I am not having any problems, I am getting ~24MB/s which is around my limit.

**Comment by Ikfes** [comment]
@gcp You should try OVH servers. They have good peering around the world and come with unmetered 500 Mbps port with 1Gbps burst speed. This means 161 - 322 TB/m. I have SP-64 in GRA and im currently serving ~85-120 TB/m with it without any issues.

**Comment by Ikfes** [comment]
On top of that you can buy https://www.ovh.com/world/dedicated-servers/bandwidth-upgrade.xml for quite cheap if you need more traffic.

**Comment by ihavnoid** [comment]
Downloading 3c8f6488 is incredibly slow as of now. Are we back to hitting the throttling?

**Comment by MartinDevelopment** [comment]
@ihavnoid Probably just you, it is nearly an instant download for me.

**Comment by gcp** [comment]
>You should try OVH servers.

I looked at OVH but our current provider actually has better offerings if you stay below ~75TB / month, which we definitely do now.

**Comment by gcp** [comment]
>Are we back to hitting the throttling?

It's no longer possible to get throttled. In any case traffic to the real server is minimal.

I think this thread can be summarized by this picture:
https://sjeng.org/dl/traffic.png

**Comment by gcp** [comment]
>and if i type http://zero.sjeng.org/networks/ in browser,it is redirect to https://leela.online-go.com/networks/ , the 2nd address is faster...and the pages https://leela.online-go.com/networks/ is stale, its best-networks is very old

The networks are now split between the main server (which is normally fastest) which has the latest networks, and is CDN cached, and the storage server (which has slow but big disks). If you try to fetch a network from the main server but it's no longer there, you'll get forwarded to the storage server.

I should probably try to make that mirroring automatic, so the "index" of networks/ works as expected.

**Comment by gcp** [comment]
>6.34K/s  eta 4h 11m
>The network download speed is about 0.5M/s to 1M/s.

So still pretty sad.

**Comment by gcp** [comment]
>I should probably try to make that mirroring automatic, so the "index" of networks/ works as expected.

This is now mirrored automatically every day.

**Comment by alphaladder** [comment]
@roy7 @gcp

One more problematic game

http://zero.sjeng.org/view/be2518f025fe1000bdd907ba790547c06886a1eb036c5f8a3ba26e277ecda30e?viewer=wgo
