### ISSUE TITLE
Some potential pitfall in the training of future 40b(safe engine is needed)

### ISSUE THREAD

**Issue by alphaladder** [gcp/leela-zero#1738]
My friend found that someone can upload problematic games with alreadydone ‘s endgame or Komi engine at the fixed winrate  50% ,which would destroy the whole 40b easily if so. Otherwise the winrate of lz will be a disaster.

@gcp @roy7  could you mind assign a safe training engine only for the coming 40b? The modified lz engine could upload any junk and nobody has the energy to maintain at all times. Thanks.

**Comment by gcp** [comment]
I have no idea what "assign safe training engine" means but yes anyone can upload whatever junk.

**Comment by gcp** [comment]
See discussion in #1705 too.
