### ISSUE TITLE
Feature test: View games

### ISSUE THREAD

**Issue by roy7** [gcp/leela-zero#174]
I've added some things to the test server.  I want to have a few random people try it before I actually move it to the live server to be sure I won't break anything. If you load

http://zero-test.sjeng.org/

right now, you should get a message "View your most recently submitted game." Clicking it will take you to a game viewer. The game viewer can view any game if you know the hash of the game you want to see. It's possible you won't see this message, I noticed the server listens to both IPv4 and IPV6 and sometimes the IPv4 is converted to IPv6 with leading ::ffff:: but sometimes it isn't. I don't know why this varies. If the logged game's ip address doesn't match up, then it won't find your recent game.

Viewing any game uses this format:

http://zero-test.sjeng.org/view/3b3d4e63ee6edd2a383b3c64a89d922486d2686ac48025a9cea1aadaaa61c792

That's a game I uploaded a few minutes ago.

**Comment by Matuiss2** [comment]
It worked here, thats a nice feature, congrats. Next good feature now, is seeing how many games one person already contributed to the project

**Comment by godmoves** [comment]
Yes, it works for me.

**Comment by isty2e** [comment]
Seems like it is working fine for me.

**Comment by roy7** [comment]
@Matuiss2 I was worried a count might discourage someone if their dynamic IP address changes and they might think all of their work was lost or something. Also since the IPv4 vs IPv6 thing can vary, it's possible games might be split between two "different" addresses as well.

**Comment by Matuiss2** [comment]
@roy7 You could explain that on the page

**Comment by godmoves** [comment]
maybe we can ask people to create an account before they start the training, so they can view their own games using that account?

**Comment by l1t1** [comment]
I visit http://zero-test.sjeng.org/view/3b3d4e63ee6edd2a383b3c64a89d922486d2686ac48025a9cea1aadaaa61c792
and only see a blank bord without grid and some breif info, no stones

**Comment by roy7** [comment]
@l1t1 Without images turned on there will be virtually nothing to see, not sure what I could do about that. :)

**Comment by roy7** [comment]
I'm going to go ahead and deploy it and watch for a bit then get to bed. Thanks everyone.

**Comment by marcocalignano** [comment]
A coupple of remark on  http://zero.sjeng.org/.
On my browser the page title is "Error", that does not seem that cool.
I read in another question that the Graph should start at -3500 why don't you shift it down then?

**Comment by roy7** [comment]
If you had an error, it'll retain that name in the future since I don't actually have a title for the web page. I'll go add one. :) The graph is made by @gcp so he'd have to tweak that if he wants.

**Comment by l1t1** [comment]
I found https://online-go.com/ can show grid and stones without setting show image on browser.
