### ISSUE TITLE
Training working correctly?

### ISSUE THREAD

**Issue by jkiliani** [gcp/leela-zero#1742]
As with the last training set, the number of parsed games shown on graph and tooltip did not increase. Is there a persistent problem with the game parsing on the training server?

**Comment by gcp** [comment]
Hmm, the DB in the training machine does have newer games, and I see some new matches have already been queued, so those should be OK as soon as they appear.

The number in that label is a direct count from the training machine DB, so it's strange that went wrong for one cycle.

**Comment by jkiliani** [comment]
This issue seems to have recurred with the current training set.
