### ISSUE TITLE
is there a plan to upgrade the leela zero verion 

### ISSUE THREAD

**Issue by denniscxc** [gcp/leela-zero#1743]
since  Leela Zero 0.15 + AutoGTP v16. running for a bit long time, my concern goes to the title.
another question is how to set the parameters correctly in order to get the higher performance, I guess is it possible to provide the parameters setting configuration associated with the elo rating

**Comment by tterava** [comment]
There aren't so many simple things to improve on anymore, so it takes longer to find and implement performance upgrades. Optimal parameters are machine independent and you will have to run the tuner to find them. You can do 

> leelaz.exe -t X --full-tuner --tune-only -w W

Where X is the number of CPU threads you plan to use and W is the weight file you are using. Each weight file of different size should be tuned independently.

**Comment by denniscxc** [comment]
hi, tterava

thanks for the instant reply, now I understtod

Best regards
Dennis

2018年8月18日 下午05:39，tterava <notifications@github.com> 写道：

There aren't so many simple things to improve on anymore, so it takes longer to find and implement performance upgrades. Optimal parameters are machine independent and you will have to run the tuner to find them. You can do

leelaz.exe -t X --full-tuner --tune-only -w W

Where X is the number of CPU threads you plan to use and W is the weight file you are using. Each weight file of different size should be tuned independently.

**Comment by l1t1** [comment]
@denniscxc did you reply the post using an email?

**Comment by ihavnoid** [comment]
There already is quite a bit of change (especially performance upgrades) on the next branch.  We have a  new set of winograd transformation code, we have half-precision baked in (which is another boost of performance) and other numerous big and small changes.  I guess it is up to @gcp to determine when to call it a new "master" version...

**Comment by gcp** [comment]
I want to be sure the new run-time detection of half support isn't causing any breakage any more. That's fairly new code.

**Comment by gcp** [comment]
Answer to the question: yes there is a plan.

>another question is how to set the parameters correctly in order to get the higher performance

The defaults should be best, there is no need to tweak anything.

**Comment by denniscxc** [comment]
yes

2018年8月18日 下午07:52，l1t1 <notifications@github.com> 写道：

@denniscxc did you reply the post using an email?

**Comment by denniscxc** [comment]
thanks for the clear reply

2018年8月20日 上午03:17，Gian-Carlo Pascutto <notifications@github.com> 写道：

Answer to the question: yes there is a plan.

another question is how to set the parameters correctly in order to get the higher performance

The defaults should be best, there is no need to tweak anything.

**Comment by denniscxc** [comment]
here is the result after execute the following command 
leelaz.exe -t X --full-tuner --tune-only -w W


then,is there any operation needed?


2018年8月18日 下午05:39，tterava <notifications@github.com> 写道：

There aren't so many simple things to improve on anymore, so it takes longer to find and implement performance upgrades. Optimal parameters are machine independent and you will have to run the tuner to find them. You can do

leelaz.exe -t X --full-tuner --tune-only -w W

Where X is the number of CPU threads you plan to use and W is the weight file you are using. Each weight file of different size should be tuned independently.
