### ISSUE TITLE
Let's start the 40b training program, shall we?

### ISSUE THREAD

**Issue by heqikun** [gcp/leela-zero#1747]
Let's start the 40b training program, shall we?The 40b is about as good as the elf open go, and with a little more training it can be surpassed.20B training hasn't been going well for so long.There's no need to waste time and effort.

**Comment by jokkebk** [comment]
Obviously 40b would be 2x bigger downloads, which will limit people running the client from slow locations (btw. has anyone considered a binary format like I think Leela Chess did for their larger nets?).

However, I have understood that 40b vs 20b is 2x slower, so unless there are non-linear memory or performance issues with CPU or low-end GPUs, I would imagine we have already lost most users with transition to 20b already. And seeing that my mid-end GTX 1060 pushes a move every second or so, I would for example tolerate 2x slowdown (I don't know if we could drop visits even further with 40b in training games to offset some of the burden?).

I'm not in particular hurry for 40b, and I think actually a more interesting proposition for short term might be to generate part of the games with 40b but continue training a 20b net.

I would be curious to see what proportion of training games we are getting from low-end contributors. My gut feeling is that something like 90%+ games are created by people with recent Nvidia or ATI cards and Google Colab and the like, so impact of slowing down CPU contributors would be small in terms of training games. Of course, larger contributor base serves other purposes, like word-of-mouth, new code contributors etc. But still, if you are now doing 20b games at 20s per move, 40s per move will not change things much.

**Comment by 22nsuk** [comment]
https://www.lifein19x19.com/viewtopic.php?f=18&t=15718&start=80

40 blocks seem stronger than 20 blocks. But it is not as strong as we thought. Unless you are a very high-end computer, 15 blocks are still the strongest at the same time. It seems that 40 blocks do not have to jump too quickly in a situation where they are not stronger than any other block.

**Comment by gcp** [comment]
40 blocks was blocked on the server issues. I assume the next updates will be queued for a promotion match soon. This was explained in the thread about the 40b net.

Most of those tests use extremely small amounts of games (<= 20) so the results are just random.
