### ISSUE TITLE
Nvidia RTX "Turing" Release Announcement 1800 CEST, 20 August

### ISSUE THREAD

**Issue by thalessa** [gcp/leela-zero#1749]
Nvidia "BeForTheGame" stream at 18.00 CEST on 20 August (Central European Summer Time) from Gamescom (a video game trade show) in Germany.

https://www.twitch.tv/nvidia

Expected content is specifications, benchmarks and availability dates for the new GPU.

**Comment by gcp** [comment]
The real question for us is if there are going to be Tensor Cores on the consumer modules.

**Comment by thalessa** [comment]
Just announced:

TensorCore
110 TFlops FP16
220 TOPS INT8
440 TOPS INT$

**Comment by Friday9i** [comment]
Eh eh, 110 TFlops fp16, that looks extremely promising, isn't it?

**Comment by gcp** [comment]
The question is what the "marketing factor" is that those have to be divided by :)

**Comment by roy7** [comment]
Here's some detailed specs and prices.

https://wccftech.com/nvidia-geforce-rtx-2080-ti-and-rtx-2080-custom-model-roundup-preorder/

**Comment by ihavnoid** [comment]
If cudnn has problems we can implement our own NN code, if we have a CUDA backend and we use cublas.  Will be a crazy amount of code rewrite but still doable (hopefully) if people are interested rewriting more code.

**Comment by fell111** [comment]
For single precision:
2080TI (13.4T)> 1080ti (11.5T)> 2080 (10.1T) >1080 (8.9T) > 2070 (7.5T)≈ 1070ti (8.1T)

As the fp16 precision is not support for opencl on nvida card. The users who doesn't need training could select 1080ti or 1070ti. That's much cheaper.

**Comment by gcp** [comment]
>If cudnn has problems we can implement our own NN code

It's a problem for redistribution, but you could still add support to the source. Good point that if Tensor Cores are in play, a drop in for cuBLAS might give a huge amount of the speedup while bypassing cuDNN, though.

**Comment by gcp** [comment]
>As the fp16 precision is not support for opencl on nvida card.

Is it certain that the 2000 series won't have this? The older ones didn't, but it is not clear that situation will persist.

**Comment by Cabu** [comment]
I could understand that this situation persist, what if OpenCL is as powerful as CUDA on nvidia cards. You can 'easily' have x2 performance with a CUDA implementation of the same OpenCL algorithm just because when using you are using CUDA you have access to 2 times more registers to store locally your temporary variables reducing read/writes to the shared memory. Not having access to FP16 from OpencCL is one more reason to implement your things in CUDA and one more reason to not buy graphic cards from other vendors....

**Comment by hred6** [comment]
For single precision:
2080TI (13.4T)> 1080ti (11.5T)> 2080 (10.1T) >1080 (8.9T) > 2070 (7.5T)≈ 1070ti (8.1T)
1060=？

**Comment by gcp** [comment]
>You can 'easily' have x2 performance with a CUDA implementation of the same OpenCL algorithm just because when using you are using CUDA you have access to 2 times more registers to store locally your temporary variables reducing read/writes to the shared memory.

Why would that be? 

>Not having access to FP16 from OpencCL

OpenCL can use fp16 via cl_khr_fp16.

>Not having access to FP16 from OpencCL is one more reason to implement your things in CUDA and one more reason to not buy graphic cards from other vendors....

Stop spreading FUD.
