### ISSUE TITLE
Strength graph of webpage can't show

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#175]
from wherever google cannot be accessed

**Comment by isty2e** [comment]
It has perfectly fine for me, and I can't imagine any case you can't connect to Google... Does it have something to do with your browser possibly?

**Comment by zhu-jz** [comment]
google is blocked in China

**Comment by isty2e** [comment]
Oh...

**Comment by axaj** [comment]
This is the current one, up to 315k network. ![strengthgraph26112017](https://user-images.githubusercontent.com/23060459/33244305-342abce2-d2f5-11e7-8cdc-0e1b553775dd.png)
