### ISSUE TITLE
Am I doing something wrong with self training? 

### ISSUE THREAD

**Issue by maxinjapan** [gcp/leela-zero#1755]
Hi. I finally managed to run AutoGTP and in the very first self-play game I got this game http://zero.sjeng.org/view/b23a22b5c54e868bbc9fc229786cedd1ae34a2f3c97ac4e0491156ed35b7faaf?viewer=wgo which ended at move 536 in 81 minutes with a B+124.5 win. What's happened???
Is this mess supposed to happen from time to time or did I make some mistake in setting up the game? 
Thanks for the clarification

PS: FWIW, the following games seem to be going much better

**Comment by Ishinoshita** [comment]
@maxinjapan : This is 'no-resign' game, as you can see from the game info, below the Result ( '-r0 stands for resign threshold = 0, i.e. the game continues until two consecutive pass moves or the move count exceed the maximum of 722 moves).

'Ordinary' games currently use 5% resign threshold (when, at the end of the search, 'bestscore'  goes below that value, the corresponding side resigns). Check for argument '-r5' when autogtp launch the game, or in the .sgf.

No-resign games account for ~15% of the self-play game. They are intended to provide a proportion of very late endgame positions in the training data.

**Comment by maxinjapan** [comment]
Thanks for the explanation, Ishinoshita. 
I understand why we want some games to keep going until the very end, but in case of the linked SGF it is clear that all moves after #211 (black! passes) are not good ones. What sort of training do we get from there? I cannot help wondering if this is of any help at all...

**Comment by Ishinoshita** [comment]
You're not the the only one wondering. See e. g. #1656

**Comment by gcp** [comment]
>What sort of training do we get from there?

We learn that white really was indeed winning.

**Comment by maxinjapan** [comment]
> You're not the the only one wondering. See e. g. #1656

Thanks. Interesting reading.


> We learn that white really was indeed winning.

Except it was Black ;-) Just kidding. Thanks for the explanation. 
At least I know I can keep going (move 537 and counting as we speak...)
