### ISSUE TITLE
Where do I find a missing selfplay game? 

### ISSUE THREAD

**Issue by maxinjapan** [gcp/leela-zero#1761]
Hi. Sorry for yet another silly question, but I cannot seem to be able to find a self-play game played yesterday. 

From AutoGTP I received the message
 `Game data 2635487cff0a6853e40fb311178a11f1cf11ab793b028506924ae3a831e573f7 stored in database`
But if I look at [http://zero.sjeng.org/view/2635487cff0a6853e40fb311178a11f1cf11ab793b028506924ae3a831e573f7?viewer=wgo
](http://zero.sjeng.org/view/2635487cff0a6853e40fb311178a11f1cf11ab793b028506924ae3a831e573f7?viewer=wgo) (in the same way I can do for many other games) I receive the error
 `No selfplay game was found with hash 2635487cff0a6853e40fb311178a11f1cf11ab793b028506924ae3a831e573f7`

Am I missing something?

**Comment by l1t1** [comment]
mine is fine
http://zero.sjeng.org/view/04e1fa4f65efc147d742a12748a0fb52dd79c3738d00d2b3fd191a958af5f0ff?viewer=wgo

**Comment by gcp** [comment]
>Am I missing something?

The (web)server only stores a limited amount of games, and they are cleaned out regularly after being copied to the training server.

**Comment by maxinjapan** [comment]
perfect. thanksl for the clarification
