### ISSUE TITLE
leelaz core dump

### ISSUE THREAD

**Issue by ashinpan** [gcp/leela-zero#1767]
Leelaz (next) core dumps on latest Linux Mint. The GPU is GTX 1050, and the network is the latest official one (170). The following is the terminal output: 

 pan@pan-desktop:~/devel-leela/autogtp$ ./leelaz -w networks/e4466f1c7fd044d4a863af5d9849266f07af8736cf91aab0f0885d11cba4e206 --tune-only --full-tuner
Using 2 thread(s).
RNG seed: 15166729637688802906
Leela Zero 0.15  Copyright (C) 2017-2018  Gian-Carlo Pascutto and contributors
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

BLAS Core: Haswell
Detecting residual layers...v1...256 channels...20 blocks.
Initializing OpenCL (autodetect precision).
OpenCL: clGetPlatformIDs
OpenCL: clGetPlatformIDs
Both single precision and half precision failed to run
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to initialize net
Aborted (core dumped)

**Comment by Ttl** [comment]
Check your drivers.

**Comment by ashinpan** [comment]
@Ttl  Yeah, you are right. When I thought about it, I remembered that I haven't rebooted my machine after updating the nvidia drivers. So I reboot, and now its working again. Thanks a lot.

**Comment by pint1022** [comment]
Hello
I ran into the same issue on ubuntu 18 with 1050 GPU. The nvidia driver is 418.56.  OpenCL is /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1. Which version of dirver should be installed?

thanks,
