### ISSUE TITLE
LZ next fulltuner reduces compute speed of 40b network by 33%

### ISSUE THREAD

**Issue by jillybob** [gcp/leela-zero#1768]
I had downloaded b75dafd2 9.816M  256x40 bjiyxo 40b-167a-120k quantized network.  I then ran full tuner using the current release of LZ and got 1500 GFLOPS speed on GTX 970. I then compiled LZ next, and ran fulltuner on the same network. I got only 1,028 GFLOPS on the same network.  This is a significant decrease in play speed.  Can I get others to run full tuner with current release of LZ on the b75 network, then run full tuner on the b75 network with [compiled Leela Zero Next ](https://drive.google.com/open?id=19kChzADAa_ZIWQN6aY58usHIcqPemL23) and tell me if they get a 30% decrease in compute speed?

**Comment by isty2e** [comment]
Presumably it is due to the half precision support? I don't know why, but the FLOPS values of single and half precision kernels are not to be compared in parallel. Would you test both versions (master and next) with netbench?

**Comment by jillybob** [comment]
--benchmark of next. I tried using leelaz.-exe --netbench but that didn't work. I'll need to get documentation for netbench

Thinking at most 2678400.0 seconds...
NN eval=0.539626
Playouts: 170, Win: 54.23%, PV: C4 D3 F3 E3 E4 F2 Q4 D16 P17 Q17 P16 R14 F17 C14 D17 C17 C18 E17
Playouts: 309, Win: 54.16%, PV: C4 D3 F3 E3 E4 F2 Q4 D16 P17 Q17 P16 R14 F17 C14 D17 C17 C18 E17 D18 E16 C16 E18
Playouts: 561, Win: 54.17%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6
Playouts: 824, Win: 54.19%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6
Playouts: 1009, Win: 54.19%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5
Playouts: 1277, Win: 54.20%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5 Q5 S6
Playouts: 1464, Win: 54.20%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5 Q5 S6 R2 S2
Playouts: 1736, Win: 54.21%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5 Q5 S6 R2 S2 S5 Q2
Playouts: 1929, Win: 54.21%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5 Q5 S6 R2 S2 S5 Q2
Playouts: 2210, Win: 54.22%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5 Q5 S6 R2 S2 S5 Q2 S3
Playouts: 2395, Win: 54.23%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5 Q5 S6 R2 S2 S5 Q2 S3 R1
Playouts: 2673, Win: 54.23%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5 Q5 S6 R2 S2 S5 Q2 S3 R1 S4
Playouts: 2948, Win: 54.23%, PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5 Q5 S6 R2 S2 S5 Q2 S3 R1 S4 R2

  D3 ->    1561 (V: 54.47%) (N: 36.81%) PV: D3 C4 C6 C5 D5 B6 D16 Q4 P17 Q14 C2 B2 B7 D2 D7 E6 D6 E2 R3 Q3 R4 R6 R5 Q5 S6 R2 S2 S5 Q2 S3 R1 S4 R2 S7
  C4 ->    1363 (V: 54.20%) (N: 40.25%) PV: C4 D3 F3 E3 E4 F2 Q4 D16 P17 Q17 P16 R14 F17 C14 D17 C17 C18 E17 D18 E16 C16 E18 C15 D14 K17 R6 B14 R3
  Q4 ->     135 (V: 52.95%) (N:  7.72%) PV: Q4 C4 D5 C5 D6 D16 D3 B7 P17 Q15 F17 M17 C17 D17 C16
 D16 ->      96 (V: 53.05%) (N:  5.33%) PV: D16 D3 E4 E3 F4 Q4 C4 G2 P17 Q14 D10 C17 C16
 D17 ->      44 (V: 53.21%) (N:  2.29%) PV: D17 D3 E4 E3 F4 Q4 C4 G2 P17
16.1 average depth, 35 max depth
2497 non leaf nodes, 1.28 average children
3200 visits, 1100289 nodes, 3199 playouts, 91 n/s

**Comment by Ttl** [comment]
next branch uses Winograd F(4x4, 3x3) convolution which uses smaller matrix size in sgemm than F(2x2, 3x3) in master. GFLOPs in tuner is expected to be slower, but it should be faster in actually evaluating nodes.

**Comment by Ttl** [comment]
Based on you results it's actually faster with the next branch. Tuner GFLOPs don't matter and shouldn't be used as indication of performance. Only nodes per second actually matter.
