### ISSUE TITLE
Leela Zero wins Iwamoto Award

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1769]
https://lifein19x19.com/viewtopic.php?f=18&t=15987

could someone post the text here?

**Comment by apetresc** [comment]
I'm not completely certain, but I think you're asking someone to paste the contents of the Facebook link posted to L19 here on GitHub, presumably because you don't have a Facebook account. In that case, here it is:

> We are proud to present the three winners of this year's Worldwide Iwamoto Awards. decided through a voting system by our independent Jury panel of 8 go connaisseurs from all over the world.
> 
> It was a close call at the top of the scoring-table, with ultimately three clear winners:
> 1st place: "Go Future" by Marc Oliver Rieger (from Germany).
> 2nd place: "Leela Zero" by Gian-Carlo Pascutto (from Italy).
> 3rd place: "Go Game in Every Math Classroom" by Xinming Simon Guo (from the USA).
>
> Congratulations!
>
> We would like to thank all participants for their hard work and their wonderful initiatives for the game of Go. We hope you all continue your efforts and that you will compete in the Iwamoto Awards again in the future!
> Below some pictures from the official announcement of the winners during the European Go Congress in Pisa. Photos by EuroGoTV and Misha Krylov.


(Followed by some photos)

**Comment by l1t1** [comment]
thank you

**Comment by jokkebk** [comment]
My thought process on the images:
"Wow GCP is really tall!"
"Oh wait that's some German guy who won the 1st prize"
"What, middle one is GCP? I've thought him as a guy! She's lot prettier than I expected based on github sketch..."
"Ah, it's someone accepting it on his behalf..."

😉

**Comment by alreadydone** [comment]
Italy..?

**Comment by maxinjapan** [comment]
Leela Town, Italy :-)

**Comment by l1t1** [comment]
http://www.iwamoto-awards.com/Awards/Portfolio.php?A=27037

**Comment by gcp** [comment]
It seems they corrected it to Belgium. Logical to assume from my name :-)
