### ISSUE TITLE
shall we decrease the match frequency in the future 

### ISSUE THREAD

**Issue by alphaladder** [gcp/leela-zero#1771]
Currently we have so many matches at 32k, 64k,96k,128k,192k, 256k. Shall we only keep part of them ?
Not very sure, just a suggestion.

**Comment by MartinDevelopment** [comment]
Last promotion was at 32k, so I don't think we should change anything atm.

**Comment by TFiFiE** [comment]
It doesn't seem matches are the bottleneck.

**Comment by alphaladder** [comment]
Thanks@tfifie@martinsevelopment.
