### ISSUE TITLE
3 networks in 20 hours, what was changed?

### ISSUE THREAD

**Issue by jillybob** [gcp/leela-zero#1774]
Was there some back-end changes to cause this improvement in networks?

**Comment by Mardak** [comment]
Well… multiple times the past, whenever gcp posted on github that we would be moving on to a larger size, the current network size ends up getting some promotions. Looks like this time was no different. 😉

**Comment by fame872toe857** [comment]
I highly doubt that someone uploads fake game.
Plz use ELF to benchmark the 172 weights.

**Comment by l1t1** [comment]
@Mardak
The old dynasty refused to end easily.

**Comment by kfc51151271** [comment]
It seems our artificial intelligence has learned to realize that we want to give him up:)
> I highly doubt that someone uploads fake game.
any evidence?

**Comment by Splee99** [comment]
With equal think time the 172 is still weaker than 157 (the last 15b weights).

**Comment by Crazyeight101** [comment]
There's some kind of trend occurring where the more we use the 20b and ELFv1 training games, the better our networks perform against ELF and previous 20bs, but they either perform about the same as or worse compared to the top 15b or earlier versions of the 40b.

**Comment by l1t1** [comment]
With equal think time seems more fair than equal visits, can future matchs run in this method?

**Comment by roy7** [comment]
We can't use equal time on Match Games because we have no control over the users systems. If they're playing a video game or doing other GPU things at the same time it may not actually be equal for each side of the match. The only dependable way to make sure both sides have equal power is to limit the number of visits or play outs.

**Comment by jillybob** [comment]
@roy7  It may be possible to benchmark 20b network 172, against a current 40b network, to find out the ratio of playouts that allows for a 50% win.  This ratio is then applied to 1600 visits.

Example
Network 172 needs 4000 visits, to defeat 40b at 1500 visits, 50% of the time. 

This creates a ratio of 2.67:1 visits between 172 and 40b, this provides us a "time parity" equivalent.

instead of sending think time, this ratio can be sent. so for 1600 visits 40b, the client needs to be send the calculation of 2.67*1600 = 4267 visits required on 172 compared to 1600 visits on 40b to make for time parity.

**Comment by gcp** [comment]
Was just a bit of luck. A now a bit of bad luck!

**Comment by Mardak** [comment]
> A now a bit of bad luck!

**Immediately** after gcp comments, LZ173 33986b7f promoted. 😉
