### ISSUE TITLE
Time losses on CGOS

### ISSUE THREAD

**Issue by hwj-111** [gcp/leela-zero#1776]
Hello,

I ran into an issue when I run LZ on CGOS.  I run LZ with the options like below.
-g -t 4 -w network.gz -r 5 --gpu 2 --gpu 3 -b 90 --noponder

Some very low rank bot (ELO~1400) never resign, and playing shitty moves until my LZ client run out of time (because LZ run slower at first few minutes).  I don't know how to deal with this.

Is there a solution to let LZ figure out low level opponent and speedup her move?

Thanks a lot

**Comment by hwj-111** [comment]
http://www.yss-aya.com/cgos/19x19/cross/lz171_1050ti1060hw.html

**Comment by gcp** [comment]
The question is why LZ is losing on time in the first place. It should never do that. Is there server lag or is Leela Zero moving too slowly?

**Comment by gcp** [comment]
The strength of the opponent is completely irrelevant - the bot should respect the timecontrol.

One time loss that can't be avoided would be if the GPU is very slow and the network very big. It has to be evaluated at least once per move, no way around this. But I'm not sure this is the case you hit.

**Comment by tterava** [comment]
I've noticed the same issue back when I did some testing in CGOS. There's always some lag so it's very difficult to avoid this without making the time control very conservative. CGOS should implement 1 second byo-yomi. It makes no sense to play go with absolute time when there's lag involved.

**Comment by Cabu** [comment]
If I understand well the problem, any stupid bot that could play instantaneously a legal move will win against any other intelligent bot by Time losses? Hum, I should write such a bot to top CGOS ranks 🗡 Perhaps having such a bot topping their rankings, the CGOS admin would implement a 1s byo-yomi, to ensure that such bots will lose on the points in the end....

**Comment by tterava** [comment]
@Cabu If you are using the python client for CGOS, you could use LZ normally, but then have the client send "time_settings 0 1 1" if you are losing after ~150 moves or so. You would win against weak and fast bots, and have a backup against strong and slow bots.

**Comment by nerai** [comment]
> If I understand well the problem, any stupid bot that could play instantaneously a legal move will win against any other intelligent bot by Time losses? Hum, I should write such a bot to top CGOS ranks 🗡 Perhaps having such a bot topping their rankings, the CGOS admin would implement a 1s byo-yomi, to ensure that such bots will lose on the points in the end....

I understand CGOS adds a small time after each submitted move, so moving quickly enough should work well enough against instant movers.

**Comment by nerai** [comment]
> The strength of the opponent is completely irrelevant - the bot should respect the timecontrol.

As this is t>2, it seems related to #1161 ?

Also, I don't remember if this was reported before (should I open this as a separate ticket?), but I've had quite some trouble with KGS GTP erroring out dubiously (eofexception) with the prebuilt version. This also caused lost games due to timing out from the repeated reconnections. But it is not clear if this is at all related to this ticket - just noting this so the GTP logs would be checked to make sure.

**Comment by hwj-111** [comment]
My thought is that if LZ can tell if the her opponent's  level is too low to use time normally.  Say, in first 30 moves, the win rate estimation goes to 95% or higher (that indicates the very weak opponent, probably).  So LZ can use much less time in rest of this game to avoid time-forfeit loss.

    On Saturday, September 15, 2018, 6:26:37 PM PDT, Sebastian <notifications@github.com> wrote:  
 
 

If I understand well the problem, any stupid bot that could play instantaneously a legal move will win against any other intelligent bot by Time losses? Hum, I should write such a bot to top CGOS ranks 🗡 Perhaps having such a bot topping their rankings, the CGOS admin would implement a 1s byo-yomi, to ensure that such bots will lose on the points in the end....


I understand CGOS adds a small time after each submitted move, so moving quickly enough should work well enough against instant movers.

**Comment by alreadydone** [comment]
My branch https://github.com/alreadydone/lz/tree/1t-batch-fastexit is optimized for instant response to time control. It comes with batching (default --batchsize 5 and you may want to increase it to maximize pos/s displayed after each genmove), and you'll need to specify precision (`--precision half` recommended).
Also,
https://github.com/gcp/leela-zero/blob/4fd6e694ead45b7cbb14ea76c5bdfcbfa662304b/src/TimeControl.cpp#L229
changing this to a smaller number will help LZ spend less time for each move and save more time for late-game moves in long games.
