### ISSUE TITLE
someone still update not leela zero’s sgf to server

### ISSUE THREAD

**Issue by storyer9999** [gcp/leela-zero#1777]
From QQ group found it

http://zero.sjeng.org/view/1881bbe5737d6b5c4f3c1875a445bb0aff4d115bb3cbb5eee18e474ce52eb0ec?viewer=wgo

its AlphaGoZero VS AlphaGoMaster No7 sgf and changed lastest step,

I am worried that if the matchs is controlled by fake games, leela zero will fall into false growth.

**Comment by MartinDevelopment** [comment]
Not really a problem for match games, since they don't contain that much randomness. So, if we want we can check them whenever we want.

**Comment by roy7** [comment]
Deleted it. Thanks.
