### ISSUE TITLE
Choice of new graphic card for self-play games

### ISSUE THREAD

**Issue by ashinpan** [gcp/leela-zero#178]
I am not a gamer per se, so I have been content with my obsolete GT 610 for occasional movies. But I intend to upgrade my GPU card with the sole purpose of contributing to this project. 

Googling tells me that the most important factor for GPUs used in machine learning is memory bandwidth, followed by processing power (number of cuda cores x clock speed of each core) and VRAM size. 

But for this very specific case of producing self-playing games for  leela zero, I am not sure if the rule of thumb above is still correct or not. 

Please someone in the know enlighten me so that I can get the best available one within my budget.

**Comment by OmnipotentEntity** [comment]
What is your budget?

And this rule of thumb is pretty good.  But you also need a decent CPU for right now because there's some board transformations that happen on CPU before feeding to the GPU, but as the network gets more complex this becomes less of a factor.

**Comment by ashinpan** [comment]
@OmnipotentEntity  My cpu is Core i5-6500  (3.20GHz), so I think it is decent enough.

**Comment by ashinpan** [comment]
@OmnipotentEntity  I am trying to choose between gtx 1050 2gb and 1050ti 4gb. They have the same memory bandwidth, and if VRAM size difference is not important, I would choose 1050 instead. For in my location, these two have a big difference in price point.

**Comment by Azirine** [comment]
vRAM size doesn't matter but the speed of the GPU matters a lot. 1060 3GB is almost twice as fast as 1050 so I would recommend that if you can afford it. In my opinion 1070 is a waste because you're paying for 8GB of vRAM that wouldn't be used in the generation self-play games.

**Comment by OmnipotentEntity** [comment]
You can pick up a used 780 Ti for about the same price as a 1050.  This will work much better than a 1050 Ti.  It's faster than a 1060 but slower than a 1070.

**Comment by Azirine** [comment]
Be aware that older generations of graphics cards are inefficient and wastes a lot of energy, for example the 780 Ti uses 250W while the 1050 uses 75W, the 1060 uses 120W and 1070 uses 150W.

**Comment by ashinpan** [comment]
@Azirine In my location, 1060 3gb has a price almost double of 1050 2gb. 
@OmnipotentEntity I wish I could. But in my place, there is no reliable market of second hand items. People usually buy new things, and use them until they become entirely unusable.

**Comment by Azirine** [comment]
@ashinpan In that case 1050 2GB is a good choice.

**Comment by ashinpan** [comment]
@Azirine  I think so too.
