### ISSUE TITLE
Rock–paper–scissors of 20b elf and 40b

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1785]
line|Network Hashes | Network Hashes | Winrate
-- |-- | -- | --
1|c9d70c41(40b 167) | b1c37640(20b 172)| 0.78
2|c9d70c41(40b 167) | e2be4815(40b 157))| 0.49
3|62b5417b(elf 0) | b1c37640(20b 172)|0.69
4|d13c4099(elf 1) | b1c37640(20b 172)|0.70
5|d13c4099(elf 1) | e2be4815(40b 157)) |0.57

from L2, 40b 157 > 40b 167, so  40b 157 : 20b 172 should >0.78(L1)
from L5, elf1 > 40b 157, so  40b 157  : 20b 172 should <0.7(L4)

**Comment by wonderingabout** [comment]
there are many statistical inconsistencies, among recent ones elf v0 and elf v1 having same winrate against b1c3 while its different against 9c56 (and we know elf v1 is stronger)

my guess is that 400 games are significant enough for match games and test games, but for significant statistical strength comparison between networks, you'd need thousands of games at least (something like 5 000 -10 000 games)
