### ISSUE TITLE
Some unpromoted 40b self-play with modified settings submitted

### ISSUE THREAD

**Issue by Mardak** [gcp/leela-zero#1786]
Two of the 3 submitted games I currently see from http://zero.sjeng.org/self-plays:

![screen shot 2018-08-28 at 11 25 02 am](https://user-images.githubusercontent.com/438537/44733244-2b79b880-aab5-11e8-9958-94cc48ccb1e2.png)

http://zero.sjeng.org/view/625ef4852a15be9c2cbef16013011a705bb3f001074093c662694b6b3350231c?viewer=wgo
http://zero.sjeng.org/view/cd0b813c357a157672ab28eaba123a3efc7e285e25d4a70c1ee6957c0294bf99?viewer=wgo

The sgf contains:
```
40b:
(;GM[1]FF[4]RU[Chinese]DT[2018-08-28]SZ[19]KM[7.5]TM[3600]PB[Leela Zero 0.15 c9d70c41]PW[Leela Zero 0.15 c9d70c41]RE[B+Resign]C[Leela Zero options: -p 0 -v 1601 -r 5 -m 999 -t 1 -d -n --noponder -s 6842916572684327666 -g -q -w networks/c9d70c413e589d338743bfa83783e23f378dc0b9aa98940a2fbd1d852dab8781];B[pd];

20b:
(;GM[1]FF[4]RU[Chinese]DT[2018-08-28]SZ[19]KM[7.5]PB[Leela Zero 0.15 d13c4099]PW[Leela Zero 0.15 d13c4099]RE[W+Resign]C[Leela Zero options: -p 0 -v 1601 -r 5 -m 999 -t 1 -d -n --noponder -s 4809663731472884186 -g -q -w networks/d13c40993740cb77d85c838b82c08cc9c3f0fbc7d8c3761366e5d59e8f371cbd];B[pp]
```

So the 40b has a "TM[3600]" that is different.

It appears as 2 different clients, but might just be IP proxy.

**Comment by Mardak** [comment]
The same seed 6842916572684327666 used in the two 40b games are not from the server.

**Comment by kfc51151271** [comment]
Recently I can often see some strange self-play games, for example, I can see a self-play game from LZ#169 now...
http://zero.sjeng.org/view/f7c0b3413cf118e5f4cb7d221504517b40f53c87aa42bfd3e65494687f85d778? Viewer = wgo

By the way, this ELF game also has a TM [3600]，is that normal？
http://zero.sjeng.org/view/e377013e931a99b224be12fba623f4f5186bdc4b72706e0050595278b195242d?viewer=wgo

**Comment by Mardak** [comment]
Looks like games are still coming in:

http://zero.sjeng.org/view/4851cc97db7a80ca81161a1192c23f9f7eda79f8ce22dd7b1ed11130f9d91651?viewer=wgo

Also has the bad seed and TM[3600]

**Comment by roy7** [comment]
I can tell you 4851cc, e377013e, 625ef4852, cd0b813c3 all come from different IP addresses. However 3 appear to be coming from Google Compute Cloud.

Is it possible the people using large #s of GCP instances aren't using the normal client with normal settings?

**Comment by maxinjapan** [comment]
Anything to do with this? 
<img width="463" alt="screenshot 2018-08-28 17 11 38" src="https://user-images.githubusercontent.com/32621200/44736127-516b8100-aae6-11e8-8596-c61b4dda055b.png">

**Comment by roy7** [comment]
Ah I didn't realize they were uploading them as self play games. Yes that's coming from an altered client that is not obeying server instructions.

**Comment by roy7** [comment]
Banning individual Colab IPs might be pointless but banning all of it might be too extreme. Annoying.

**Comment by storyer9999** [comment]
add update user id ……

**Comment by MartinDevelopment** [comment]
It seems a 40 block network(# 173) got promoted and isn't getting any self play games?

**Comment by jkiliani** [comment]
Maybe self-play games on the server might have to be checked on whether their network is actually a valid promoted net. Without hacked clients that would be redundant, but it seems we have further proof of modified clients now...

**Comment by l1t1** [comment]
lz 173 is strange, only 4 games now,and no new in hours

**Comment by roy7** [comment]
It wasn't promoted. Someone forced their client to upload those.

**Comment by alphaladder** [comment]
@roy7 all these fake games show that” basic time =60min”

**Comment by roy7** [comment]
It's possible someone was using Colab for remote use and accidentally ran autogtp with the wrong client program or something.

**Comment by l1t1** [comment]
can the webpage  check  whether the weight show in game info is promoted?

**Comment by PhilipFRipper** [comment]
http://zero.sjeng.org/viewmatch/42b0f4955461a391a22cc43b98f6d3a260af5834301784804fd9ea8f19d19109?viewer=wgo  this is listed as the most recent MATCH game... definitely not right

**Comment by kfc51151271** [comment]
Ah, maybe I understand how the TM3600 game is generated. When I used q+ENTER to save the game and then modified the save file, I successfully got a game with TM3600.
http://zero.sjeng.org/view/10d6e731a179a03d8d368a824c44c16047a995544256a6ee971fc8b8784ce272?viewer=wgo
For testing, I changed the visit to 1 and it runs quickly and uploads successfully.. I am sorry, please delete it
