### ISSUE TITLE
bad move for the scenario of "live without eyes"

### ISSUE THREAD

**Issue by fa15073** [gcp/leela-zero#1792]
![issue](https://user-images.githubusercontent.com/4413183/44865228-5847ee80-acb4-11e8-9ee4-24d556216bdd.jpg)

Playouts: 4094, Win: 95.07%, PV: G4 K2 G3 L1 C5 C7 K1 J13 J2 R13 S13 S12 R12 Q13 S11 S14 T12 R15 Q14 Q15

**Comment by kuba97531** [comment]
The report value would be much highers if you provided more info.
What is the exact leelaz version, 
exact command line parameters, 
any additional parameters, 
network used,
was it an even game played by engine from the beginning,
etc.

**Comment by fa15073** [comment]
no handicap, not selfplay, default parameters. repro-ed on several recent best network e.g.
--gtp -w c910dee9c057d144efaafb603ce69d564825ca316dd8129ce0f05c1231d1f9bc.gz

it might be worth considering to add some kind of acceptance test suite to ensure the quality of the weights

**Comment by Ishinoshita** [comment]
We know that LZ is still far from perfect play and that it has some holes in its play. This 'hole' you found is indeed shocking for an engine which is close to top amateurs with this number of playouts. Such a test suite would be very interesting to monitor the training progress from a human perspective, indeed. But:

(1) The spririt of the project is self-learning from zero ("Go engine with no human-provided knowledge, ..."). So, the network promotion/selection process must be based only on an objective criteria of competition between network of successive generations, without any human tempering. We must be patient and faithfull that the training process will progressively fill the gaps.
 
(2) The other reason we should refrain from tweaking the selection process is that we might prevent LZ progress! Indeed, by rejecting the network here above on what humans can see (even an amateur can understand why) we would also reject improvement that humans cannot see (please consider that even top pros are still puzzled by how Alphago Master was always ahead after just 30-50). And thus arbitrate between improvements based our shortsighted human knowledge.

Contrary to classic AB chess engines, the recent progress of computer go engines 'à la Alphago' is not based just on very deep tactical reading but on improved positional judgement (not visible at first sight as in the position above). The very same thing is happening right now in computer chess, were Lc0 is quietly closing the gap with top AB engines thanks to his good positional judgement. While still blundering some 'easy' endgame position.

This been said, even if 'blunders' are not a priori bugs, some might still be bug-related (like bugs in the tree search e.g.). A suite might provide a basis for doing sanity checks, if someone is willing to do them.

**Comment by ajcsimons** [comment]
About the actual go mistake here, when I was studying in China some years ago one of our strong amateur teachers was playing on KGS and he managed to persuade his opponent into making this same blunder of double shortage of liberties pushing through a bamboo joint.

**Comment by Ishinoshita** [comment]
Would you please share the sgf leading to the here above position?

**Comment by fa15073** [comment]
I don't have the original file. Some sequences might not be original. But it should be enough to reproduce the position
[game.txt](https://github.com/gcp/leela-zero/files/2340842/game.txt)

**Comment by ThorAvaTahr** [comment]
>  I'm surprised none was proposed so far.

It was proposed before and this is implemented as an open source project, though support from the Community has been limited thusfar.

#905

**Comment by Ishinoshita** [comment]
@ThorAvaTahr Thanks. I had missed this thread.

**Comment by Eddh** [comment]
If the network is not provided history nothing is guaranteed.
