### ISSUE TITLE
HELP! MedStar frames "Chinaman" to protect white supremacist and child pornographer Richard Hoover

### ISSUE THREAD

**Issue by qanon3301** [gcp/leela-zero#1796]
https://medstarrichardhoover.wordpress.com/

MedStar frames "Chinaman" to protect white supremacist and child pornographer Richard Hoover

**Comment by Crazyeight101** [comment]
@qanon3301 What is this?  It has absolutely nothing to do with Leela Zero...

**Comment by gjm11** [comment]
It's spam, obviously. https://en.wikipedia.org/wiki/QAnon may be relevant given the username.
