### ISSUE TITLE
A version for amateur player

### ISSUE THREAD

**Issue by pheasant75** [gcp/leela-zero#1799]
One of the issue with the current Leelaz is that it is too strong for human players, esp amateur players.  While there is a great progress for the handicap games, I am wondering if the following approach would work:
Have leelaz always choose the move that is around 50%-60%.
Note the details can be adjusted, like the range of winrates, whether randomly pick a move or have some strategies (like the win rate chosen is slowly creeping up).  The strategy could even be influenced by the win rate change after the opponent’s move to make it more “human”.  We could have a GUI or configuration file for user to specify the strategy.  I am wondering whether the playing style from this setting would be ok for amateur player to practice with.

**Comment by l1t1** [comment]
leela 0.11 https://sjeng.org/leela.html

**Comment by Ishinoshita** [comment]
Already on the #1599 wish list. You can keep an eye on the works of @alreadydone and @AncalagonX . They are working hard to please amateurs ;-)

**Comment by arondes** [comment]
you may use 5 Block version

**Comment by pheasant75** [comment]
The 5 block version may suffer from ladder or other simple life and death issue.

The idea is that the program will adapt to the level of play of its opponents.  So you only need one version of program and it will cover all levels.

**Comment by john45678** [comment]
What about this:
https://github.com/avysk/dumbstone

**Comment by pheasant75** [comment]
Exactly!  Thanks for the heads up.

**Comment by 5525345551** [comment]
I use the 10 block E08 master version from pangafu. I take 2 or 3 stones handicap, white gets 7.5 komi.
I get a good close game from this at 1000 playouts.
An occasional ladder happens, so it would be good if there was ladder code, rayn / aq with lz weight?

**Comment by gcp** [comment]
See issues about dynamic komi etc.
