### ISSUE TITLE
weird training game

### ISSUE THREAD

**Issue by pw31** [gcp/leela-zero#1804]
The latest training games of the new 256x40 net c9d70c41 look partly very strange,
with 2/3 corner openings and apparently random play in the centre, for exampe
http://zero.sjeng.org/view/a0841bfb87d186a13daaeb84ca12486d0930a4b7c1c3e9607d72abe42005029c?viewer=wgo

**Comment by roy7** [comment]
Self play games have a lot of randomness. Consider this one. ;)

http://zero.sjeng.org/view/57aa2913aea1875a5b8879d9286aa493dad4fc50a379e3ab8e48326867d78193?viewer=wgo

**Comment by Crazyeight101** [comment]
Those are some unusual ones, but the self-play games from the 40b that was just promoted are super interesting!
