### ISSUE TITLE
Release a win version of leelazero it   simultaneously please

### ISSUE THREAD

**Issue by tanguocn** [gcp/leela-zero#181]
I prefer leela  with a graphical interface version.   Could you  simultaneously release a win version of leelazero it   simultaneously    , for example, leelazero137k, leelazero292k

**Comment by CamWagner** [comment]
You can use Sabaki (http://sabaki.yichuanshen.de/) to get a GUI. Or play with it on KGS.

To watch it train, check http://reddit.com/r/cbaduk for some programs. Someone asked the same question.
