### ISSUE TITLE
pass - pass at move 167 with the game still open?

### ISSUE THREAD

**Issue by maxinjapan** [gcp/leela-zero#1812]
HI. I've just looked at [this training game](http://zero.sjeng.org/view/c71573670d1ad45709bb45fb1b77a9dd922015d2d89dc5311dbe1e116decfff4?viewer=wgo) where both players passed at move 167 despite the game still being not finished. 
![screenshot 2018-09-06 08 16 46](https://user-images.githubusercontent.com/32621200/45141255-40d59d80-b1ad-11e8-8c6d-54447cf51a25.png)
How is this possible?

**Comment by MartinDevelopment** [comment]
Because of randomness. If one player passes due to randomness and the other player wins if he also passes the game will end. Otherwise the game will continue.

**Comment by maxinjapan** [comment]
A weird (to me) way to use randomness, but it kind of makes sense. Thanks for the explanation
