### ISSUE TITLE
[Question] Is Tensor Core useful for neural network for Go?

### ISSUE THREAD

**Issue by y-ich** [gcp/leela-zero#1817]
Hi.
This question is not about leela-zero but Go AI with convolution neural networks.

Now GeForce RTX series would have Tensor Core like V100 with reasonable price.
 Is Tensor Core useful for current neural networks for Go?

According to the article ["Programming Tensor Cores in CUDA 9"](https://devblogs.nvidia.com/programming-tensor-cores-cuda-9/) by NVIDIA, "Both input and output channel dimensions must be a multiple of eight." This seems not fit for 19x19 Go.

If you think just about numbers of specs, Tensor Core of two 2080Tis reaches 432TOPS for INT8, which is larger than 4 * TPU v1(368 TOPS).
So a PC with Two 2080Tis will be more than AlphaGo Zero. However it is not true if Tensor Core is not suitable for Go AI.

Would you give me you guys' opinions?
Thanks.

**Comment by Ttl** [comment]
LZ can't currently use tensor cores. That would require using cuda.

Number of channels refers to number of filters, not board size. LZ already requires that number of filters is multiple of eight so all LZ networks are compatible with tensor cores.

**Comment by y-ich** [comment]
If you are right, I really want a board of RTX series^^
I grepped ELF OpenGo source code. They did not use Tensor Core even though they use V100.

Anyway, this question is not for Leela Zero, so I close it.
Thank you for your comment!

**Comment by zhanzhenzhen** [comment]
Anyone has written code that runs the LZ network using tensor core?
