### ISSUE TITLE
How to deal the "UCTNode.obj : error LNK2001 " error ?

### ISSUE THREAD

**Issue by xiarx2016** [gcp/leela-zero#1821]
Thank you develop this wonderful AI .Leelazero is really great!
But when I download the code ,and try to build it in msvc 2015，I see these  error tips. May I make some mistakes somewhere ? And How to deal with it ? Thanks very much again!

1>UCTNode.obj : error LNK2019: 无法解析的外部符号 "public: __cdecl UCTNodePointer::UCTNodePointer(class UCTNodePointer &&)" (??0UCTNodePointer@@QEAA@$$QEAV0@@Z)，该符号在函数 "void __cdecl std::_Construct<class UCTNodePointer,class UCTNodePointer>(class UCTNodePointer *,class UCTNodePointer &&)" (??$_Construct@VUCTNodePointer@@V1@@std@@YAXPEAVUCTNodePointer@@$$QEAV1@@Z) 中被引用
1>UCTNodeRoot.obj : error LNK2001: 无法解析的外部符号 "public: __cdecl UCTNodePointer::UCTNodePointer(class UCTNodePointer &&)" (??0UCTNodePointer@@QEAA@$$QEAV0@@Z)
1>UCTNode.obj : error LNK2019: 无法解析的外部符号 "public: __cdecl UCTNodePointer::UCTNodePointer(short,float)" (??0UCTNodePointer@@QEAA@FM@Z)，该符号在函数 "public: void __cdecl std::allocator<class UCTNodePointer>::construct<class UCTNodePointer,int const &,float const &>(class UCTNodePointer *,int const &,float const &)" (??$construct@VUCTNodePointer@@AEBHAEBM@?$allocator@VUCTNodePointer@@@std@@QEAAXPEAVUCTNodePointer@@AEBHAEBM@Z) 中被引用
1>UCTNode.obj : error LNK2019: 无法解析的外部符号 "public: class UCTNodePointer & __cdecl UCTNodePointer::operator=(class UCTNodePointer &&)" (??4UCTNodePointer@@QEAAAEAV0@$$QEAV0@@Z)，该符号在函数 "class std::reverse_iterator<class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class UCTNodePointer> > > > __cdecl std::_Buffered_merge_backward_unchecked<class std::reverse_iterator<class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class UCTNodePointer> > > >,class UCTNodePointer *,class std::reverse_iterator<class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class UCTNodePointer> > > >,class NodeComp>(class std::reverse_iterator<class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class UCTNodePointer> > > >,class std::reverse_iterator<class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class UCTNodePointer> > > >,class UCTNodePointer *,class UCTNodePointer *,class std::reverse_iterator<class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class UCTNodePointer> > > >,class NodeComp &,bool)" (??$_Buffered_merge_backward_unchecked@V?$reverse_iterator@V?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@VUCTNodePointer@@@std@@@std@@@std@@@std@@PEAVUCTNodePointer@@V12@VNodeComp@@@std@@YA?AV?$reverse_iterator@V?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@VUCTNodePointer@@@std@@@std@@@std@@@0@V10@0PEAVUCTNodePointer@@10AEAVNodeComp@@_N@Z) 中被引用
1>UCTNodeRoot.obj : error LNK2001: 无法解析的外部符号 "public: class UCTNodePointer & __cdecl UCTNodePointer::operator=(class UCTNodePointer &&)" (??4UCTNodePointer@@QEAAAEAV0@$$QEAV0@@Z)
1>UCTNode.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl UCTNodePointer::inflate(void)const " (?inflate@UCTNodePointer@@QEBAXXZ)，该符号在函数 "public: class UCTNode & __cdecl UCTNode::get_best_root_child(int)" (?get_best_root_child@UCTNode@@QEAAAEAV1@H@Z) 中被引用
1>UCTNodeRoot.obj : error LNK2001: 无法解析的外部符号 "public: void __cdecl UCTNodePointer::inflate(void)const " (?inflate@UCTNodePointer@@QEBAXXZ)
1>UCTNode.obj : error LNK2019: 无法解析的外部符号 "public: bool __cdecl UCTNodePointer::valid(void)const " (?valid@UCTNodePointer@@QEBA_NXZ)，该符号在函数 "public: class UCTNode * __cdecl UCTNode::uct_select_child(int,bool)" (?uct_select_child@UCTNode@@QEAAPEAV1@H_N@Z) 中被引用
1>UCTNode.obj : error LNK2019: 无法解析的外部符号 "public: int __cdecl UCTNodePointer::get_visits(void)const " (?get_visits@UCTNodePointer@@QEBAHXZ)，该符号在函数 "public: bool __cdecl NodeComp::operator()(class UCTNodePointer const &,class UCTNodePointer const &)" (??RNodeComp@@QEAA_NAEBVUCTNodePointer@@0@Z) 中被引用
1>UCTSearch.obj : error LNK2001: 无法解析的外部符号 "public: int __cdecl UCTNodePointer::get_visits(void)const " (?get_visits@UCTNodePointer@@QEBAHXZ)
1>UCTNode.obj : error LNK2019: 无法解析的外部符号 "public: float __cdecl UCTNodePointer::get_score(void)const " (?get_score@UCTNodePointer@@QEBAMXZ)，该符号在函数 "public: bool __cdecl NodeComp::operator()(class UCTNodePointer const &,class UCTNodePointer const &)" (??RNodeComp@@QEAA_NAEBVUCTNodePointer@@0@Z) 中被引用
1>UCTNode.obj : error LNK2019: 无法解析的外部符号 "public: bool __cdecl UCTNodePointer::active(void)const " (?active@UCTNodePointer@@QEBA_NXZ)，该符号在函数 "public: class UCTNode * __cdecl UCTNode::uct_select_child(int,bool)" (?uct_select_child@UCTNode@@QEAAPEAV1@H_N@Z) 中被引用
1>UCTNode.obj : error LNK2019: 无法解析的外部符号 "public: float __cdecl UCTNodePointer::get_eval(int)const " (?get_eval@UCTNodePointer@@QEBAMH@Z)，该符号在函数 "public: bool __cdecl NodeComp::operator()(class UCTNodePointer const &,class UCTNodePointer const &)" (??RNodeComp@@QEAA_NAEBVUCTNodePointer@@0@Z) 中被引用
1>UCTNodeRoot.obj : error LNK2019: 无法解析的外部符号 "public: int __cdecl UCTNodePointer::get_move(void)const " (?get_move@UCTNodePointer@@QEBAHXZ)，该符号在函数 "public: class std::unique_ptr<class UCTNode,struct std::default_delete<class UCTNode> > __cdecl UCTNode::find_child(int)" (?find_child@UCTNode@@QEAA?AV?$unique_ptr@VUCTNode@@U?$default_delete@VUCTNode@@@std@@@std@@H@Z) 中被引用
1>C:\leela-zero-master\msvc\x64\Debug\leelaz.exe : fatal error LNK1120: 11 个无法解析的外部命令

**Comment by ihavnoid** [comment]
I don't know which SHA you checked out, but can you see if UCTNodePointer.cpp is also compiled or not?

**Comment by xiarx2016** [comment]
Thanks for your help. 
It works well in msvc 2017,may be the .sln file in msvc 2017 is wrong, because I can't find the UCTNodePointer.cpp file.
Thanks again!

**Comment by gcp** [comment]
Should be fixed now.
