### ISSUE TITLE
LNK1104	cannot open 'libboost_filesystem-vc140-mt-x64-1_68.lib' VC2015

### ISSUE THREAD

**Issue by aa22063821** [gcp/leela-zero#1822]
use VC2015 compiler

LINK1104  cannot open 'libboost_filesystem-vc140-mt-x64-1_68.lib'	

How to solve?

**Comment by aa22063821** [comment]
ok thx already solve

**Comment by TarunaYadav** [comment]
> ok thx already solve

Can you please share how you solved this issue? I am facing the same error in VS2015.
