### ISSUE TITLE
Should Q=0 / FPU=0.5 be used for self-play to follow AGZ paper?

### ISSUE THREAD

**Issue by Mardak** [gcp/leela-zero#1829]
In investigating https://github.com/LeelaChessZero/lc0/issues/344, I noticed that leela related self-play has never used Q=0 and had various iterations going from 1.1 to parent Q to fpu reduction, etc. At first glance, Q=0 seems wrong for strong play as losing positions end up searching wider (while winning positions generally focus on higher prior moves), and this leads to inefficient usage of visits in matches. But potentially, these two search behaviors is actually desired to generate two different types of training data from a single self-play game -- in particular, losing positions help discover potentially good moves, and winning positions validate which of these "potentially good moves" are actually good.

Rebasing my position analysis scripts for "snapbacks" #877 and "self-atari" #1007, it looks like the much smaller 128x10 networks could have easily generated self-play data to learn these moves.

```diff
diff --git a/src/UCTNode.cpp b/src/UCTNode.cpp
--- a/src/UCTNode.cpp
+++ b/src/UCTNode.cpp
@@ -267,3 +267,3 @@ UCTNode* UCTNode::uct_select_child(int color, bool is_root) {
     // Estimated eval for unknown nodes = original parent NN eval - reduction
-    auto fpu_eval = get_net_eval(color) - fpu_reduction;
+    auto fpu_eval = is_root ? 0.5f : get_net_eval(color) - fpu_reduction;
 
```
E.g., https://online-go.com/game/11943777 with latest 128x10 LZ116 39d46507 trying to find D3 with 800 visits:
```
FPU = parent Q - fpu reduction
symmetry: 0
  M4 ->     342 (V:  1.04%) (N: 33.02%) PV: M4 L3 K3 B14 A12 A3 F8 D3 E9 K1 M13
symmetry: 1
  M4 ->     311 (V:  1.89%) (N: 29.70%) PV: M4 L3 K3 B14 A12 A3 F8 D3 E9 K1 M13
symmetry: 2
  M4 ->     251 (V:  1.21%) (N: 22.81%) PV: M4 L3 K3 B14 A12 A3 F8 K1 E9 D3
symmetry: 3
  M4 ->     270 (V:  0.98%) (N: 23.16%) PV: M4 L3 K3 B14 A12 A3 F8 K1 E9 D3 M13 L18
symmetry: 4
  M4 ->     212 (V:  1.12%) (N: 23.43%) PV: M4 L3 K3 B14 A12 A3 F8 K1 E9 D3
…
  D3 ->      64 (V: 100.00%) (N:  0.63%) PV: D3 B14 M4 L3 A12 K3 F8 K1 E9
symmetry: 5
  M4 ->     318 (V:  1.38%) (N: 29.17%) PV: M4 L3 K3 A3 A12 B14 F8 K1 E9 L18 M13
symmetry: 6
 A12 ->     225 (V:  1.42%) (N: 18.73%) PV: A12 B14 M4 L3 K3 A3 F8 L18 E9 K19 M13 F17 O12
symmetry: 7
  M4 ->     294 (V:  1.13%) (N: 25.65%) PV: M4 L3 K3 B14 A12 A3 F8 K1 E9 L18 M13

FPU = 0.5
symmetry: 0
  D3 ->     760 (V: 100.00%) (N:  0.27%) PV: D3 B14 M4 L3 A12 K3 F8 K1 E9 L18 A3 K19
  M4 ->       7 (V:  1.34%) (N: 33.02%) PV: M4 L3 K3 B14 A12
symmetry: 1
  D3 ->     678 (V: 100.00%) (N:  0.12%) PV: D3 K3 M4 L3 A12 B14 F8 K1 E9 F17 A3 E16
  M4 ->       6 (V:  1.48%) (N: 29.70%) PV: M4 L3 K3 B14 A12
symmetry: 2
  D3 ->     718 (V: 100.00%) (N:  0.17%) PV: D3 B14 M4 L3 A12 K3 F8 K1 E9 F17 A3 E16
  M4 ->       5 (V:  0.75%) (N: 22.81%) PV: M4 L3 K3 B14 A12
symmetry: 3
  D3 ->     703 (V: 100.00%) (N:  0.17%) PV: D3 B14 M4 L3 K3 A12 F8 K1 E9 L18 A3
  M4 ->       5 (V:  0.81%) (N: 23.16%) PV: M4 L3 K3 B14 A12
symmetry: 4
  D3 ->     781 (V: 100.00%) (N:  0.63%) PV: D3 B14 M4 L3 A12 K3 F8 K1 E9 L18 A3 K19
  M4 ->       5 (V:  1.44%) (N: 23.43%) PV: M4 L3 K3 B14 A12
symmetry: 5
  D3 ->     677 (V: 100.00%) (N:  0.07%) PV: D3 B14 M4 L3 A12 K3 F8 K1 E9 L18 A3 K19
  M4 ->       6 (V:  1.57%) (N: 29.17%) PV: M4 L3 K3 A3 A12
symmetry: 6
  D3 ->     679 (V: 100.00%) (N:  0.07%) PV: D3 B14 M4 L3 K3 A12 F8 L18 E9 K19 A3
 A12 ->       4 (V:  0.90%) (N: 18.73%) PV: A12 B14 M4 L3
symmetry: 7
  D3 ->     679 (V: 100.00%) (N:  0.03%) PV: D3 B14 M4 L3 A12 K3 F8 K1 E9 L18 A3 K19
  M4 ->       5 (V:  0.60%) (N: 25.65%) PV: M4 L3 K3 B14 A12
```

Here, the current behavior of FPU=parent Q focuses search on higher prior moves and has a hard time finding the correct <1% prior move, and FPU=0.5 causes search to try to visit every move until it finds a >50% win rate move. To be clear, even with FPU=parent Q, leela with 3200 visits would generate good training data for symmetry 4 above, so the higher visits can eventually find the right move, but the FPU=0.5 behavior in this case directs over 80% of the visits in every symmetry towards the correct move.

Yes, I realize this is just one position, and even including the other "leela did something wrong" positions that FPU=0.5 seems to "fix" is not sufficient to show it's the better way to generate better quality training data.

But as we have learned in the past with #1083 and other issues, optimized match strength may not be ideal for optimized training quality. The example above is just to show that the quality of training data can be quite different from what it has been.

Aja Huang's response to FPU questions:
http://computer-go.org/pipermail/computer-go/2017-December/010567.html
> All I can say is that first-play-urgency is not a significant technical detail, and what's why we didn't specify it in the paper.

That seems like it could imply DeepMind did not try adjusting FPU/reduction and were able to get good/excellent results with what they documented in the AGZ paper, i.e., Q=0.

**Comment by roy7** [comment]
Just a reminder for newcomers to this topic that AlphaGo used priors of (-1, 1) and we use (0, 1). So their Q=0 would be our .5.

**Comment by roy7** [comment]
Once upon a time I think we had a belief that stronger play (through adjustments like FPU etc) means better example games to learn from, and thus better training success for strong networks. I can't say that's wrong, but as we've seen from changes like adding temperature all game long the strength of the Zero training pipeline isn't just in stronger example games, but more exploration as well.

**Comment by Mardak** [comment]
Jotting down some discord comments from @amj:

> The "Q=0" in the paper is the first thing that initially looked like a straight-up mistake
but now i'm wondering if it might've been right all along.
The behavior, as roy said, causes search to be very wide when losing and very narrow when winning, which seems "incorrect"
but in retrospect, it is closer to the behavior in the original paper 1, which positively reinforced the moves made by the winning side (via one-hot) and negatively reinforced the moves made by the losing side
having the losing side 'try everything once' will mostly cancel out -- the probability mass accruing on most moves being not more than a cursory check -- but it would have the effect of rapidly discovering any moves unknown to the current policy that would bring the game back into balance.
I dunno. It seemed clearly wrong at first and now i'm coming around to wondering if it was correct as printed.
it seems like if that's the intended effect, then the dirchlet noise's role is slightly different than originally understood?

And my initial investigation with noise and Q=0 shows that noise might be even more important because Q=0 in winning positions will highly favor its highest prior move and in losing positions will highly favor the first move (sorted by prior) that happens to be over 50% win rate. Noise causes "parallel" instances of self-play to "shuffle" the ordering of priors so that if there are multiple good moves, each self-play's training data might result in all possible good moves having high visit probabilities for a single move and the resulting averaged training learns that there are multiple good moves.

**Comment by Mardak** [comment]
Well, now that roy spoiled my secret plan on discord 😉 😛 

My example code above intentionally only applies FPU=0.5 for root, and I believe training data will be better doing that only for noised root search instead of Q=0 for all levels. The reasoning behind this is Q=0 everywhere causes the winning side MCTS to also search wide when thinking of the opponent's move, and this will likely be visit-inefficient as described above but more importantly discover the correct move for the losing side then causing the winning side to play a different move.

If instead Q=0 is only at the root, search at non-root levels tries to be "accurate" with the best effort guidance of the current policy head / and parent Q value, so the winning side will believe the losing side will play its "usual" move and play right into a bad position, so when the losing side searches wide with Q=0, it'll quickly find the correct move and generate valuable training data.

**Comment by gcp** [comment]
There's been a ton of discussion on this already, which lead to the current choices. This most definitely won't be changed unless there's data a new method is stronger.

**Comment by gcp** [comment]
Also, please don't make arguments about single positions, I've already explained several times why this is almost guaranteed to lead to wrong conclusions. A single positions is not data.

**Comment by Mardak** [comment]
I've looked through existing issues, and they mostly focus on match strength and not training data quality.

FPU interaction with randomize #1355 
There @Ttl initially thought ELF was trained with Q=0, but the code actually uses dynamic parent Q (as opposed to leela-zero's static parent Q from the network). @gcp pointed out that 3 runs from DeepMind used FPU=50% and seems to have avoided the randomize issue, and the outcome of the issue was to exclude single visit moves from randomize selection.

Disable FPU reductions at a noised root. #1083
@gcp here even points out there will be more exploration without FPU reduction and that noise and temperature are the mechanisms to discover new moves. The argument there is very much in line of what I'm pointing out for Q=0 where the losing side's purpose is to explore more to find potentially overlooked moves.

First play urgency https://github.com/glinscott/leela-chess/issues/160
@jkiliani implemented FPU reduction to chess and there were some comments about whether it's appropriate to use it for self-play. @gcp noted that policy softmax, noise, puct can be adjusted to increase exploration; however, AZ did not need to or at least didn't document needing to change those values -- potentially because Q=0 provided the exploration needed to find good moves.

Replace fpu reduction with best child eval #836
@WhiteHalmos attempted to change FPU reduction but was rejected for not gaining match strength. Nothing about training data there.

Change first-play-urgency. #238
@killerducky introduced FPU=parent and there was indeed quite a bit of discussion about Q=0; however, the analysis there was again with match strength and incorrectly assumed Q=0 meant FPU=0 but should have used FPU=50%.

Tune first play urgency ? #696 
@Eddh opened up this issue leading to a lot of things to tune including constant 0.5 (where people did correctly point out Q=0 means FPU=0.5) where match performance of that constant was close to the worst. As this was a tuning issue to increase strength, pretty much all analysis ignored training data quality although @Eddh did note:

> So this seems to prove there is more to generating good quality self play games than strength.

I've renamed the issue to be about FPU=0.5 at noised root (and keeping the existing FPU for children and match games). The strength results of FPU=0.5 are bad probably similar to comparing leela with noise and move randomness versus leela without randomness. And that's entirely the point of this issue of strongest play doesn't mean best training data.

Are there other discussions I've missed that actually discussed the quality of training data with Q=0?

**Comment by gcp** [comment]
>I've looked through existing issues, and they mostly focus on match strength and not training data quality.

Yes, but those things are closely related. There's no evidence that the data is generally "better" in some vague way, but we know it will be weaker, and so clearly worse in that aspect.

You can't just blindly turn MCTS into a brute force search and now argue that it's more likely to discover things...

**Comment by gcp** [comment]
> I don't think there is any evidence supporting that it leads to a better dataset.

The gain from the MCTS is an important factor for the reinforcement learning procedure to work. It's true that making it entirely unable to recover from blind spots is likely not good, but there's certainly no evidence making it arbitrarily more brute force is good.

**Comment by Ttl** [comment]
Here is some data on how the visit distribution looks like. I played self-play game with self-play settings using parent FPU and Q=0 at root FPU.

This is how 1 visit move distribution with parent FPU looks like:
![visit1_count](https://user-images.githubusercontent.com/544240/45502076-a9171700-b78b-11e8-99bb-143bb49e03bc.png)

And here same with Q=0 at root:

![visit1_count_q0](https://user-images.githubusercontent.com/544240/45502009-81c04a00-b78b-11e8-990e-81813c73e946.png)

With the parent winrate initialization when high prior moves turn out to have winrate lower than parent, the unvisited moves with parent FPU look very good in comparison and the net visits each of them once.

With Q=0 the losing side tends to visit every possible move at the root. Since the current networks have already very good policy most of them turn out to be really bad and they stay at 1 visit. The winning side expands much less moves. This means that losing side is forced to waste visits to checking all moves at the root and is essentially playing at 200 less visits.

For Q=0 to make sense the about 200 visits at every move for the losing side for checking every possible move at root should be worth more than spending those visits at moves the network suggests. This could have been true when the networks were weak and there were issues with snapbacks and self-ataris, but it's hard to imagine that this would be beneficial with the latest already very strong networks.

This mostly just seems to cause that the side that gets early lead is much more likely to win. Visit distribution imbalance also doesn't work well with the proportional move selection as the losing side is much more likely to play a blunder due to higher number of moves with low number of visits.

**Comment by Mardak** [comment]
To be clear, I think the existing FPU is quite important for grandchildren visits in self-play because it represents the likely play of strong search. Searching wider at all losing positions will cause strangeness to the average action Q value.

In both losing and winning positions, optimized search FPU allows for accurate evaluation of children whether that's to determine if an "unknown" move from losing is actually good or confirming that a high prior move frmo winning is actually good.

**Comment by Mardak** [comment]
Thanks for running that analysis @Ttl. That does appear as the expected behavior of losing side searching wider leading to many 1-visit moves that confirm the play is actually bad. Fortunately with single-visit move exclusion from temperature, the rate of blundering won't be that much higher.

Yes, the wide-at-root search then potentially wastes 200 visits for the losing side, but for training, at least it attempted to find a better move. As you pointed out, an already strong network would effectively be generating self-play at 1600 visits vs 1400 visits favoring the winning side. Although from a very quick estimate from your FPU=parent graph being "half" as spikey, self-play is already at a disadvantage for the losing side, say 1600 visits vs 1500 visits.

**Comment by Ttl** [comment]
It's actually distributed very evenly with parent FPU. Black has 8754 1-visit moves and white 9216.

With Q=0 black has 20177 1-visit moves and white has 785.

**Comment by Mardak** [comment]
Thanks @Ttl for the plotting script. I ran a "self-play" with 192x15 (LZ157 d351f06e) with 3200 visits and Q=0 then replayed the moves with combinations of Q={0,parentQ} and visits={3200,1600,800}. Interestingly, the visit-efficiency of parentQ allows it to search wider when it needs to, and basically finds the same moves that Q=0 finds. The game happens to favor white the whole game as indicated with the "black always searches all remaining moves" behavior of Q=0 with 3200 visits:

![192x15 3200 ratio black q0 - 17 9 3 1](https://user-images.githubusercontent.com/438537/45519426-d9e65480-b769-11e8-8ef0-4f3164502c0a.png)

![192x15 3200 ratio black qp - 17 9 3 1](https://user-images.githubusercontent.com/438537/45519429-deab0880-b769-11e8-9c37-63caeb8d3d62.png)

The above 2 graphs show that for this game, both Q=0 and Q=parentQ at 3200 visits finds the exact same low prior moves with the highest ratio of max-prior-to-best-move-prior around 20 (26.50% / 1.27% = 20.87). Counting the number of "significant learnable moves" where the ratio is over a certain amount: 17 spikes over 2 ratio, 9 over 5, 3 over 10, 1 over 20.

The next 4 graphs are again for Q={0,parentQ} but for lower visits={1600,800}. The give-away for which is Q=0 is the long linear decreasing total moves visited from root.

Q=0, visits=1600, 15 spikes over 2 ratio, 6 over 5, 2 over 10, 1 over 20
![192x15 1600 ratio black q0 - 15 6 2 1](https://user-images.githubusercontent.com/438537/45519457-fb474080-b769-11e8-850a-e350fee75768.png)

Q=parentQ, visits=1600, 16 spikes over 2 ratio, 6 over 5, 2 over 10, 1 over 20
![192x15 1600 ratio black qp - 16 6 2 1](https://user-images.githubusercontent.com/438537/45519459-fda99a80-b769-11e8-868e-9a176247e0c3.png)

Q=0, visits=800, 10 spikes over 2 ratio, 3 over 5, 1 over 10, 1 over 20
![192x15 800 ratio black q0 - 10 3 1 1](https://user-images.githubusercontent.com/438537/45519500-2af64880-b76a-11e8-873a-e240216d5019.png)

Q=parentQ, visits=800, 12 spikes over 2 ratio, 3 over 5, 1 over 10, 1 over 20
![192x15 800 ratio black qp - 12 3 1 1](https://user-images.githubusercontent.com/438537/45519512-38133780-b76a-11e8-8437-6fa1a1dda1f3.png)

One overall note is as @Ttl already showed, Q=parentQ already ends up searching wide in certain situations as shown in the graph of some segments of the gradual linear decrease corresponding to the total number of remaining moves.

In this case of an already strong 192x15 network that doesn't have significant "tactical blindness," it looks like there isn't too much difference between the different Q initialization for unvisited root children.

Perhaps somewhat also confirming #1416, at least from this game, 800 visits found ~11 moves that had unfavorable priors (at least half of highest prior) while doubling the number of visits to 1600 only found 5 additional moves, and another doubling to 3200 visits only found 2 more moves.

**Comment by Mardak** [comment]
Here's a quick analysis of a not-so-mature 128x10 network (LZ116 39d46507) again with 3200 visits. The game goes from white winning to black to white, so notice Q=0's linear decrease matching available moves gets broken up in the middle.

Q=0, visits=3200, 43 spikes over 2 ratio, 22 over 5, 12 over 10, 6 over 20
![128x10 3200 ratio black q0 - 43 22 12 6](https://user-images.githubusercontent.com/438537/45520359-dfde3480-b76d-11e8-9117-7b90bc5de5fb.png)

Q=parentQ, visits=3200, 39 spikes over 2 ratio, 21 over 5, 12 over 10, 6 over 20
![128x10 3200 ratio black qp - 39 21 12 6](https://user-images.githubusercontent.com/438537/45520387-013f2080-b76e-11e8-98ad-19c3f638f32f.png)

Overall, there's a lot more moves being found and the ratios they're being found at are much higher -- some well over 100 (31.78% / 0.24% = 132). Again, both ways of initializing Q find these at 3200 visits as that's the natural behavior of MCTS searching longer. In this game, Q=0 does find a few more moves than Q=parentQ.

**Comment by Mardak** [comment]
Here's another example but using 64x5 (LZ57 c83e1b6e) again with 3200 visits. Note that the game is a bit shorter than the previous examples. But overall, looks like Q=0 and Q=parentQ find roughly the same number of low prior moves with Q=0 finding 1 more extremely low prior move for each black and white.

black, Q=0, 14 spikes over 2 ratio, 10 over 5, 7 over 10, 2 over 20
![64x5 3200 ratio black q0 - 14 10 7 2](https://user-images.githubusercontent.com/438537/45528067-78d37680-b793-11e8-964b-576bc3801a45.png)

black, Q=parentQ, 13 spikes over 2 ratio, 8 over 5, 5 over 10, 1 over 20
![64x5 3200 ratio black qp - 13 8 5 1](https://user-images.githubusercontent.com/438537/45528041-59d4e480-b793-11e8-82ec-3d4df269822f.png)

white, Q=0, 16 spikes over 2 ratio, 10 over 5, 8 over 10, 5 over 20
![64x5 3200 ratio white q0 - 16 10 8 5](https://user-images.githubusercontent.com/438537/45528083-930d5480-b793-11e8-9e35-022865f0d652.png)

white, Q=parentQ, 15 spikes over 2 ratio, 9 over 5, 7 over 10, 4 over 20
![64x5 3200 ratio white qp - 15 9 7 4](https://user-images.githubusercontent.com/438537/45528036-55a8c700-b793-11e8-9843-479f62a819ae.png)
