### ISSUE TITLE
Start training from existing weights file

### ISSUE THREAD

**Issue by roy7** [gcp/leela-zero#183]
One thing I don't understand from the README, is it possible to run training with the weights from best-network as a starting point? Instead of completely from scratch.

**Comment by jkiliani** [comment]
I think it would be quite possible to do so, but @gcp has doubts that the reinforcement learning process started this way will converge to the same strength as when you build it from the ground up. Personally I think it's likely that it will, but there's just not sufficient information to say for sure. It will surely be tried eventually, as far as I understand there's no reason other groups couldn't set up another distributed training pipeline, either with LeelaZ or another reimplementation of Alphago Zero.

For the purpose of learning just how and especially, why Deepmind's Zero concept works, recreating it faithfully as @gcp is doing probably works best. If the aim is only to get a strong network quickly, I guess starting from a SL network and improving it with reinforcement learning would be a good bet.

**Comment by roy7** [comment]
In case I was unclear, I meant using Leela Zero's current best network weights, not something from Leela or human related. It's no different than training a network from scratch and then resuming training each time you add new games to your training data. Except you can skip the initial time it'd take to just catch up to the existing network, was my thinking.

Unfortunately my strong GPU machine is tied up playing Go on OGS and I can't bring myself to leave it training 24/7.

**Comment by jkiliani** [comment]
As far as I understand from previous posts, that is already what @gcp has been doing the whole time, at least when not increasing the network size.

**Comment by roy7** [comment]
Yes, but how do we do that ourselves when we run the training locally? :) I know I can train from scratch, and I can resume training at any time. I'm just not sure how to initially begin training with best-network instead of random weights.

**Comment by jkiliani** [comment]
I think you have to run parse.py in such a way that tfprocess.py is triggered. It looks from the code as if parse.py tries to find an existing weights file from the command line argument, and if not successful, trains from random weights instead.

I'd suggest putting in testing commands in your versions of parse.py and tfprocess.py to see if it can find your existing weights file. Maybe @gcp can give you more specific advise. I can't try it myself, lacking any machine with a good enough GPU for training.

**Comment by Alderi-Tokori** [comment]
Looking at the code, it seems a command like "python parse.py <path to games> leelaz-model-<step number>" will restore the checkpoint leelaz-model-<step number> and train from this point.

**Comment by roy7** [comment]
I believe that only works to resume from work you've already done though. If you want to start fresh using the best-network weights, you don't have a model file. Or can you just rename the best network to leelaz-model-0.weight (or similar) and run with leelaz-model-0 and the missing model file is ok?

**Comment by Alderi-Tokori** [comment]
Ah I get what you want to do. You'd have to write your own function restoring the model from an exported weight file to do that, tensorflow by itself doesn't know how to read the "leelaz" format.

**Comment by gcp** [comment]
Yes, you'll need to write some extra TensorFlow code for that. Basically inverting the code that writes out the tensorflow variables to leela's format.

**Comment by bood** [comment]
If I understand correctly, this `delta training` approach could significantly reduce the training time of the new network? How long does it take to train a new network now with a decent GPU?

**Comment by roy7** [comment]
Thank you @ttl.
