### ISSUE TITLE
It is recommended to stop pk after pass, and use the computing power for training

### ISSUE THREAD

**Issue by a270709570** [gcp/leela-zero#1830]
Passing the 176 with 100 innings, then the 300-inning test is meaningless, because it has passed anyway.
After the pass, the power is used for training, which is more meaningful.

**Comment by wonderingabout** [comment]
it is not meaningless, a lot of information is fed back to us from completing the 400 games

we saw many times in the past a net passing with 60% winrate at 150 games, then falling to 50% at 400 games, so playing the entire match gives us reliable statistics
also, one can go through the sgf and compare the differences between games, and there are as well many other useful information that can be extracted

however, playing a failed match until 400 games is not very useful, so it is fine to stop at 100-150 games if the winrate is low enough (45-50%), this efficiently saves ressources, and covers the majority of situations (we have a lot of fails, but very few pass, so it is worth playing the few pass to gain valuable information, and worth ending the majority of fails to save computer ressource)

**Comment by l1t1** [comment]
good answer

**Comment by alphaladder** [comment]
nice answer

**Comment by wonderingabout** [comment]
i humbly thank you all for your comments

**Comment by l1t1** [comment]
this paper https://deepmind.com/blog/population-based-training-neural-networks/  ? @Crazyeight101

**Comment by alreadydone** [comment]
> we saw many times in the past a net passing with 60% winrate at 150 games, then falling to 50% at 400 games, so playing the entire match gives us reliable statistics and elo

This is mostly due to one network winning more short games and the other winning more long games; even if we stop the match after passing, the long games will still come in. So completing 400 games will make Elo slightly more accurate but has little other practical use.
