### ISSUE TITLE
Interesting (?) results from 61c6d735 VS b0a601d9

### ISSUE THREAD

**Issue by maxinjapan** [gcp/leela-zero#1831]
I was a little bit surprised to see a test match between 61c6d735 and b0a601d9, but now that I see its results I am even more surprised. 
In theory 61c6d735 is slightly stronger or at least on par (51.69%) with dabff367, which in turn is supposed to be significantly stronger than b0a601d9 (59.06%).
So why did we get 61c6d735 VS b0a601d9 100 : 121 (45.25%)? 
Does it mean that 400 games and/or 55% gating are not enough?

**Comment by kfdekkers** [comment]
could be rock < paper < scissors < rock

**Comment by l1t1** [comment]
if the result was pass, what shall we do?

**Comment by Crazyeight101** [comment]
I'll take a look at the match games and see if anything weird pops out at me.

**Comment by Crazyeight101** [comment]
It appears our 40 blocks have a serious issue with resigning won games...
