### ISSUE TITLE
It is recommended to set randomcnt<100 in the self-game.

### ISSUE THREAD

**Issue by baicat** [gcp/leela-zero#1832]
It is recommended to set randomcnt<100 in the self-game.
Can be set to be the same as agz. Or a little bigger. After the whole game is random, the end-game advancement is slower. Weight replacement relies entirely on the advancement of opening and middle-game.

**Comment by thynson** [comment]
There is nothing between "slower end-game progress" and randomcnt. Some of the selfplay games is played with `-r 0`, which means no resign is permitted, as we need to test how many false positive resign in normal selfplay.

**Comment by wind68** [comment]
It is recommended to change 2*361 of -r 0 . It is too long. How about 361*1.2?

**Comment by cjohnchen** [comment]
Agree!

**Comment by cjohnchen** [comment]
300 is enough

**Comment by ChinChangYang** [comment]
Disagree. In AZ paper, Dirichlet noise was added to the prior probabilities in the root node during training.

The training should discover various moves to avoid blind points in opening, middle, and endgame.

If AZ paper is wrong, then we need data to prove.

**Comment by gcp** [comment]
Please read past discussion to understand how the current parameters were chosen before talking abot replacing them, thanks.

**Comment by thynson** [comment]
Through @baicat 's conclusion is lack of evidence, but his observation probabaly right that leelaz advances very slowly at the ending stage of the game. And compares with ELF, we can found that LZ's neteval may be greately different from ELF's.
I guess the noise may be too large for 1600 visit, cause the eval not as accurate as before, and this affects ending stage much more than opening. 
As visit count has been decreased from 3200 to 1600, we may need to consider decrease the noise fractor to a reasonable value?
