### ISSUE TITLE
can leelaz code run on iphone and ipad?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1833]
Apple announced the A12 soc, https://www.apple.com/iphone-xs/a12-bionic/
"with our next-generation Neural Engine, delivers incredible performance. It uses real-time machine learning "
seems suitable for training.

**Comment by odeint** [comment]
Using a mobile phone for training is silly. How can a 5W device (if that) possibly compete with a real graphics card at 100+W? Even 3 technology generations cannot make up that difference. It doesn't make sense, who would want their phone battery drained all the time even if it worked? Finally, iPhones aren't cheap, so performance per dollar is also much higher just buying a GPU.

Also, OpenCL isn't GPU-accelerated on iOS as far as I know, if the drivers work properly at all.

**Comment by l1t1** [comment]
thank you

**Comment by herazul** [comment]
Also you can't know and understand anything from a marketing realease or annoucement.
There is no technical details in here, just a load of random numbers without any meaning.
For all we know, they may just be advertising a similar product to google lens.
