### ISSUE TITLE
OpenCL fails to compile after dd95caba4641c800bdf28a80376d73ec19d93740

### ISSUE THREAD

**Issue by dvdkhlng** [gcp/leela-zero#1837]
Commit dd95caba4641c800bdf28a80376d73ec19d93740 ("Make Winograd matrices global") breaks OpenCL compilation for me (Debian Stretch, Mesa 18, AMD A12 APU):

     Error building kernels: input.cl:319:25: error: casting '__constant real *' (aka '__constant float *') to type 'real2 *' (aka 'float2 *') changes address space of pointer
     input.cl:340:25: error: casting '__constant real *' (aka '__constant float *') to type 'real2 *' (aka 'float2 *') changes address space of pointer
     input.cl:437:25: error: casting '__constant real *' (aka '__constant float *') to type 'real2 *' (aka 'float2 *') changes address space of pointer
     input.cl:458:25: error: casting '__constant real *' (aka '__constant float *') to type 'real2 *' (aka 'float2 *') changes address space of pointer
     [..]
     Error building kernels: input.cl:293:28: warning: double precision constant requ
     ires cl_khr_fp64, casting to single precision
     input.cl:51:15: note: expanded from macro 'SQ2'
     input.cl:293:51: warning: double precision constant requires cl_khr_fp64, casting to single precision
     input.cl:51:15: note: expanded from macro 'SQ2'
     input.cl:294:28: warning: double precision constant requires cl_khr_fp64, casting to single precision
     input.cl:51:15: note: expanded from macro 'SQ2'
     input.cl:294:51: warning: double precision constant requires cl_khr_fp64, casting to single precision
     input.cl:51:15: note: expanded from macro 'SQ2'
     input.cl:295:28: warning: double precision constant requires cl_khr_fp64, casting to single precision
     input.cl:51:15: note: expanded from macro 'SQ2'
     input.cl:295:51: warning: double precision constant requires cl_khr_fp64, casting to single precision
     [..]
     input.cl:319:25: error: casting '__constant real *' (aka '__constant half *') to type 'real2 *' (aka 'half2 *') changes address space of pointer
     input.cl:340:25: error: casting '__constant real *' (aka '__constant half *') to type 'real2 *' (aka 'half2 *') changes address space of pointer
     input.cl:437:25: error: casting '__constant real *' (aka '__constant half *') to type 'real2 *' (aka 'half2 *') changes address space of pointer
     input.cl:458:25: error: casting '__constant real *' (aka '__constant half *') to type 'real2 *' (aka 'half2 *') changes address space of pointer

     Both single precision and half precision failed to run

**Comment by Ttl** [comment]
Should be fixed in #1838. Re-open if that's not the case.
