### ISSUE TITLE
computer-chess-championship

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1840]
https://www.chess.com/computer-chess-championship
leela chess zero now at 5th

**Comment by Friday9i** [comment]
Yeah, that's nice as it is already sure to be selected for the second round as one of the 8 best engines! And it's a quite an old version of LC0 (ie an old network, quite far from the best)
Unfortunately, it's not possible to update for the second round, so it has very little chances of beating current top engines (Stockfish, Komodo and Houdini). But for next tournament in a few months, it may win...

**Comment by l1t1** [comment]
https://github.com/LeelaChessZero/lc0/releases

**Comment by john45678** [comment]
For a review of some games played by Leela Chess at CCCC see Kingscrusher yt:  https://www.youtube.com/user/kingscrusher

**Comment by l1t1** [comment]
it seeems publish software include cuda dll is permitted

Release lc0-windows-cuda.zip package now contains NVdia CUDA and cuDNN .dlls.

**Comment by thalessa** [comment]
This is an achievement, however when comparing the ML engines to A/B engines, the hardware isn't equal for this event. 

CPU Engines:
CPUs: 2 x Intel Xeon Platinum 8168 @ 2.70 GHz 33 MB L3
Cores: 48 physical (96 logical)
RAM: 256GB DDR4-2666 ECC Registered RDIMM
SSD: 2x Crucial MX300 (1TB) in RAID1
OS: Windows Server 2016

GPU Engines:
GPU: 4x Tesla V100 (64 GB GPU memory)
CPU: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30 GHz
Cores: 16 physical (32 virtual)
RAM: 256 GB

**Comment by l1t1** [comment]
@thalessa what config did lc0 use in the championship?

**Comment by jkiliani** [comment]
@thalessa The hardware used may not be equal in purchasing price, but:
- The GPU server is rented, and obviously determined by availability of preconfigured GPU servers on the cloud, with sufficient stability that they could be sure the TCEC debacle wouldn't be repeated
- Even though V100 are very expensive to buy, the newly released RTX 2080Ti provides only very slightly less performance for a fraction of the price
- Lc0 doesn't currently scale all that well with multiple GPUs. The improvement from 2x V100 to 4x V100 is actually marginal

So the argument that Leela Chess Zero had an unfair hardware advantage actually falls flat on closer inspection. Just because those GPU servers were used doesn't mean that a setup with almost equal performance wasn't available, or at least won't be available in the very near future.

**Comment by tapsika** [comment]
I don't think hardware prices has any significance here, only performance (gflops/mips). You can even compare the number of cores (orders of magnitude difference) to get a very rough idea.

**Comment by l1t1** [comment]
I got it
http://blog.lczero.org/2018/08/cccc-starts.html
***Leela will play on four Tesla V100 GPUs*** while the other engines on 46 threads of a 2 x Intel Xeon Platinum 8168, 2.70 GHz that has 48 logical cores and 96 threads.

**Comment by gcp** [comment]
>it seeems publish software include cuda dll is permitted

The situation is massively more complicated than this. a) lc0 has an NVIDIA engineer contributing, and he apparently got permission for bundling b) the lc0 client was re-licensed to include a license exemption for linking with cuDNN.

**Comment by gcp** [comment]
Leela Chess Zero has its own github, this is totally offtopic here.

**Comment by thalessa** [comment]
> @thalessa 
> So the argument that Leela Chess Zero had an unfair hardware advantage actually falls flat on closer inspection. Just because those GPU servers were used doesn't mean that a much cheaper setup with almost equal performance wasn't available, or at least won't be available in the very near future.

Why did you assume I thought it was unbalanced towards Leela? 

I think the comparison is invalid.

**Comment by l1t1** [comment]
lc0 now at 4th

**Comment by l1t1** [comment]
![2018-09-22_164536](https://user-images.githubusercontent.com/23301704/45915423-0d00a600-be44-11e8-8c76-755f53fbb4f2.png)

**Comment by Matuiss2** [comment]
andscacs is not weak at all

**Comment by l1t1** [comment]
stockfish is INVINCIBLE
Houdini & Komodo both win more games than lc0, but also lost more games.

**Comment by l1t1** [comment]
lc0 lost to fire, the 6th program

**Comment by thalessa** [comment]
> andscacs is not weak at all

It's at the bottom of the table. Compartively speaking, it is.

**Comment by l1t1** [comment]
lc0 lost two games to andscacs

**Comment by l1t1** [comment]
I wonder why the opensource stockfish is stronger than some closesource program? Is the weight file published?

**Comment by l1t1** [comment]
lc0 is 4th now, also has more draw games than the 3rd

**Comment by l1t1** [comment]
![2018-09-26_092841](https://user-images.githubusercontent.com/23301704/46055011-87029900-c17c-11e8-87fe-0630d48739dc.png)
finished

**Comment by TFiFiE** [comment]
> The random Leela loss to the weak engine Andscacs. I guess that's their equivalent of "10 dan that can't read ladders"?

With respect to chess, the tactical blind spot in an otherwise superstrong zero engine seems to be [discovered attacks](https://en.wikipedia.org/wiki/Discovered_attack), although LCZero has seemingly moved past that now.

**Comment by l1t1** [comment]
![2018-09-28_101924](https://user-images.githubusercontent.com/23301704/46184330-b5f94600-c307-11e8-9fd8-cb6debb23bcf.png)
stockfish got a fail

**Comment by l1t1** [comment]
![2018-09-30_080748](https://user-images.githubusercontent.com/23301704/46251554-fa135480-c487-11e8-8873-19898fdbbfe3.png)
why didn't black resign? 
is there  win by resign in a match of chess ?

**Comment by roy7** [comment]
The bots aren't set up to resign, they always fight to the bitter end.

**Comment by thalessa** [comment]
Resignation will be a tournament rule set by the tournament. Sometimes its when both engine evals are heavily in one side, sometimes it's by tablebase (a database of endgames).

However I think that in a game with neural net engines, the ending should be played, as they sometimes miss tactics (the ladder problem).

**Comment by l1t1** [comment]
![2018-10-02_153229](https://user-images.githubusercontent.com/23301704/46334923-5c4d9000-c615-11e8-8926-8275f28afe35.png)
lc0 3:0 leading

**Comment by l1t1** [comment]
lc0 seems too optimistic to evaluate 
![2018-10-02_195701](https://user-images.githubusercontent.com/23301704/46347278-8bc2c380-c63a-11e8-97b0-3f999b31f6dc.png)
the position

**Comment by l1t1** [comment]
![2018-10-03_110158](https://user-images.githubusercontent.com/23301704/46388031-7640ae80-c6b9-11e8-9307-005b08114cd0.png)
komodo underestimate

**Comment by l1t1** [comment]
lc0 win
![2018-10-03_141037](https://user-images.githubusercontent.com/23301704/46393052-240c8700-c6d3-11e8-876d-4f0e80b08053.png)

**Comment by l1t1** [comment]
lc0 beat stockfish
![2018-10-04_103118](https://user-images.githubusercontent.com/23301704/46450069-e7966500-c77e-11e8-8919-1cb44b751478.png)

**Comment by l1t1** [comment]
![2018-10-05_093700](https://user-images.githubusercontent.com/23301704/46511666-62bf5000-c83f-11e8-8fc4-656b0921ce33.png)
lc0 lost too much games this time

**Comment by l1t1** [comment]
lc0 got wrost result

**Comment by l1t1** [comment]
![2018-10-12_075524](https://user-images.githubusercontent.com/23301704/46840080-e820a280-cdf3-11e8-8e2c-5904f6b2cb5c.png)
lc0 18.1

**Comment by l1t1** [comment]
LCZero blog


2018-10-19

Leela beats Fire promoting to Semi-Final of TCEC Cup!




 Leela in a classic drama style, promoted in TCEC Cup Semi-Finals and it will face Stockfish today!
While in CCCC blitz tournament she is still at 3rd place ahead of Komodo, Ethereal and Fire and behind Stockfish and Houdini.

Read more »
