### ISSUE TITLE
Does Leela Zero support eGPU?

### ISSUE THREAD

**Issue by trunterzx** [gcp/leela-zero#1844]
I am considering getting an eGPU to help run my Leela Zero.

Currently, I am using a relatively old model of Mac with limited capabilities.
The question is, would Leela Zero be able to run on an external GPU attached to the Mac?
I read somewhere that the eGPU would only work for certain applications, so I'm not sure Leela Zero.

Any help would be appreciated! I would not want the money to go to waste...

**Comment by gcp** [comment]
Do eGPU support OpenCL?

**Comment by isty2e** [comment]
I am currently using GTX1080 enclosed in Aorus gaming box. In short, yes eGPU works, though NVIDIA eGPU support for OS X is non-native. In windows, it works out of the box, and there was no problem getting LZ working with a decent speed.

**Comment by trunterzx** [comment]
I'm considering getting Blackmagic eGPU as it has direct compatibility with Mac, and my other family members who also use Mac can use it when I'm not using it as well.

https://9to5mac.com/2018/07/16/blackmagic-egpu-review-macbook-pro-video/

Did a quick search, and it does seem like it supports OpenCL.
Is that the only consideration that is needed to see whether it supports Leela Zero?

**Comment by isty2e** [comment]
I believe so; I can't imagine of any singular reason for OpenCL supporting device to be unable to run LZ.

**Comment by trunterzx** [comment]
Thank you for the replies! Now I know it should work with no issues if it supports OpenCL.

I will consider other options as well before actually settling on one.
