### ISSUE TITLE
Network 2b0ac291 playing a new joski

### ISSUE THREAD

**Issue by dvdkhlng** [gcp/leela-zero#1848]
(Apologies if any of you consider this inappropriate content for the issue tracker)

Just wanted to point out that network 2b0ac291 which closely "failed" with merely 53.49% wins against dec5b9d8 seems to sometimes play (with black, during matches) a different opening than dec5b9d8, starting a 3-3 invasion already on move three:

http://zero.sjeng.org/viewmatch/cd1483199fb24c4e89b16c9945e9c9184b520d1415c1090da19d9faabe71bbff?viewer=wgo
http://zero.sjeng.org/viewmatch/7d278d14c134c1a85e2e9cb468d018982032c66c5cf16e518b518ad92292f00a?viewer=wgo

Both those games it won against dec5b.

**Comment by Glrr** [comment]
The value head considers the invasion is good, but this knowledge has not reached the policy head (yet).

Something similar may happen for the first move: the value head has a very slight preference for 4-3, but the policy head has a strong preference for 4-4. Hence LZ always plays 4-4. But the policy head may eventually learn to love 4-3.

**Comment by 1-punchMan** [comment]
dec5b9d8 has played this opening in previous match games. Take dec5b9d8 VS dabff367,
http://zero.sjeng.org/viewmatch/f982339b9cda68a1c95d66b883858f03b7ca41ee4bd97796527a59b7d4ee442d?viewer=wgo
http://zero.sjeng.org/viewmatch/4f206422a799bd720395892bb739e3a906e75bda6cda37d707db2c568f94ca9e?viewer=wgo

**Comment by Glrr** [comment]
seems that 58d1222a doesn't like 4-3 anymore.
