### ISSUE TITLE
Assertion failure in UCTNode::wait_expanded()

### ISSUE THREAD

**Issue by dvdkhlng** [gcp/leela-zero#1849]
Compiling leela zero for debugging (make debug) results in assertion failures on GTP command "auto":

    ./leelaz -w networks/dec5b9d88877fe876a308b42370335c8f5465235d0104c889bdda3b42993aa28.gz 

(entering "auto" <enter>)

    [..]
      update_root, 1185058 -> 263105 nodes (22.2% reused)
    Thinking at most 36.3 seconds...
    NN eval=0.538457
    leelaz: UCTNode.cpp:386: void UCTNode::wait_expanded(): Assertion `v == ExpandState::EXPANDED' failed.
    leelaz: UCTNode.cpp:386: void UCTNode::wait_expanded(): Assertion `v == ExpandState::EXPANDED' failed.
    Aborted

**Comment by ihavnoid** [comment]
I think I know why.  We are returning nodes to INITIAL state before a new move, which is assert-failing when we call get_pv because it assumes nodes are expanded if we want to print it out.

Will come with a fix, but the easiest workaround for now would be not printing anything, that is, don't call dump_analysis nor output_analysis in the middle of think().

**Comment by ihavnoid** [comment]
Pushed a patch.  I think it addresses possible failures.  It seemed to be more than what I initially thought - please have a look.

**Comment by ihavnoid** [comment]
FYI it probably won't help #1823

**Comment by gcp** [comment]
Hmm, not too fond of that patch.

What the error case exactly? Some thread is in wait_expanded() and it gets surprised because the node gets reset to INITIAL underneath it?

But how can this happen as count_nodes_and_clear_expand_state() is supposed to be called when we're single threaded?

**Comment by gcp** [comment]
Ah, I get it. It passes the .load() immediately because the node *isn't* in EXPANDING, but then expects the result of a note not being in EXPANDING to be EXPANDED, whereas it simply wasn't (re)EXPANDED.

**Comment by gcp** [comment]
I suggest we take your patch to not reset fully expanded nodes, and change the logic so get_pv bails out if the node isn't fully expanded (which we only expect *really* deep in the PV).

**Comment by gcp** [comment]
This should be fixed now.
