### ISSUE TITLE
Possibly negative winrate estimation

### ISSUE THREAD

**Issue by Vandertic** [gcp/leela-zero#1850]
https://github.com/gcp/leela-zero/blob/9e903eda6e93fb65375ea03127e4f62268913175/src/UCTNode.cpp#L264
In some cases fpu_eval may result negative, which I think is unintended behaviour, as this should be a pessimistic but reasonable estimate of an unknown winrate. 

I suggest maxing or softmaxing it with 0.

**Comment by gcp** [comment]
This is intentional, IIRC, and clamping it to zero was no better or even worse. Could be rested.

**Comment by Vandertic** [comment]
Thank you for the clarification. I don't think it could make much of a difference myself.
