### ISSUE TITLE
Consider decrease noise a bit as we changed from -v3200 to -v1600 in selfplay

### ISSUE THREAD

**Issue by thynson** [gcp/leela-zero#1853]
Some context: #1832 
And my thought:
>Through @baicat 's conclusion is lack of evidence, but his observation probabaly right that leelaz advances very slowly at the ending stage of the game. And compares with ELF, we can found that LZ's neteval may be greately different from ELF's.
I guess the noise may be too large for 1600 visit, cause the eval not as accurate as before, and this affects ending stage much more than opening.
As visit count has been decreased from 3200 to 1600, we may need to consider decrease the noise fractor to a reasonable value?

**Comment by Ishinoshita** [comment]
Hi @thynson
>As visit count has been decreased from 3200 to 1600, we may need to consider decrease the noise fractor to a reasonable value?

From what I have observed, I think randomness in endgames past resignation threshold (I assume we are talking about a - r0 game) would be exacerbated with 3200v compared to 1600v. When value is extreme, the more the number of visits, the flatter and the more spread the search policy (visits distribution after search), the more likely the temperature will pick a very low rank move. On the contrary, with say 25 visits for instance, the search policy would be much more dominated by the raw policy (head), the main randomness contribution being dirichlet noise. Adding visits would just flatten the distribution, increasing the impact of the second major randomness factor, the temperature.

So, although your point might be valid in itself, I feel that the argument of visits reduction is not relevant here, quite the opposite. Just based on my own (and not statistical) experiments, though.

**Comment by thynson** [comment]
@Ishinoshita 
I believe picking a low score move contributed by noise should not hurt the training. But the noise hurts the evaluation. As a bad noise can be very peaky up to 0.25 for a bad move, it could consume up to 100+ visit with low score that average down the eval of the search root. This could be the reason why LZ's value head did not advance much after 20B.  

One the other hand, althrough part of the games which Leela zero is trained from was generated by ELFv0 and ELFv1, the ending-stage net eval does not catch up with ELF. Maybe it implies the some of parameter could be improve.

An other solution could be, as we already cut off some bad child-nodes when choosing a move, we may also need to cut off the score of bad moves from the score of the root for training to improve the neteval accuracy.

**Comment by Ishinoshita** [comment]
> As a bad noise can be very peaky up to 0.25 for a bad move, it could consume up to 100+ visit with low score that average down the eval of the search root.  This could be the reason why LZ's value head did not advance much after 20B.

Q value at root is certainly affected by dirichlet noise, but the value head is not trained againt Q  but against the game outcome. So noisiness of Q doesn't matter for training, no ? My concern would be more the noise introduced in the game outcome  by the overall randomness of move picking. But this has already been discussed at length and the rationale behind the current setting re-explained many time by @gcp.
