### ISSUE TITLE
A suicide move by leela zero (network 157)  -- a bug?

### ISSUE THREAD

**Issue by hwj-111** [gcp/leela-zero#1854]
http://www.yss-aya.com/cgos/viewer.cgi?19x19/SGF/2018/09/20/470799.sgf

I turned on "kgs_genmove".  How come such strong engine could not avoid such mistake at the end game? Due to the block of black stones too big for 192x15 network?

**Comment by ihavnoid** [comment]
Well, I tried the latest net and it had no problem figuring out what to do.  It didn't make the mistake.  Let's face it - smaller nets make life-death mistakes when involving large nets and it has been re-confirmed multiple times.

In this particular situation with this particular net, it took roughly 8k playouts to avoid the blunder.  I guess this re-confirms why we need decent number of playouts to avoid these situations...

**Comment by hwj-111** [comment]
powerful, but sometime not smart still (same strategy used from the beginning to the end)
