### ISSUE TITLE
Are there any strength differences between the master branch and the next branch?

### ISSUE THREAD

**Issue by zhanzhenzhen** [gcp/leela-zero#1856]
Are there any strength differences between the master branch and the next branch?

I want it to play some self-play games to compare 2 networks (e.g. the best 15b 1600-po vs the current 40b 400-po). But I don't know if the result (the win rate of one network) differs when choosing different branches.

**Comment by jillybob** [comment]
Yes, the next branch has increased performance (nodes per second) over the current master branch.

**Comment by zhanzhenzhen** [comment]
Thanks. But if it's fixed playouts, like `-p 1600`, are there any performance difference?

**Comment by zhanzhenzhen** [comment]
Sorry, I mean, if it's a comparison between fixed playouts (15b 1600-po vs 40b 400-po), are there any difference of the winrate?

**Comment by zhanzhenzhen** [comment]
@Ttl Thanks.
