### ISSUE TITLE
will the client version effect the match result?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1857]
as my tests, next branch is about 1 time faster than the master,  38718 ms/move vs  68007 ms/move
so
1)  if a game bwteen two version clients with same weights and same machine, and that is setting to equal time, the next branch will win.

2)  if a game bwteen next clients with different weights ( eg, 178 vs elf ) and same machine, and that is setting to equal time, the weight need shorter time  will win.

**Comment by Friday9i** [comment]
Nice, 2 times faster is a huge boost!
Any info regarding the availability of a new master version (including theses evolutions already in next)?

**Comment by uestccokey** [comment]
oh, I think you are right, maybe this will really affect the result of the competition.

**Comment by gcp** [comment]
We are using fixed visits, so no.

Of course if you play somewhere else with timecontrols, the next version is stronger because it's faster (if it works).
