### ISSUE TITLE
Phoronix has CUDA and OpenCL benchmarks for the RTX 2080 Ti

### ISSUE THREAD

**Issue by thalessa** [gcp/leela-zero#1858]
It's not 100% tailored to Leela's workload, but the article is still useful.

https://www.phoronix.com/scan.php?page=article&item=nvidia-rtx2080ti-compute

**Comment by l1t1** [comment]
thanks

**Comment by l1t1** [comment]
https://www.phoronix.com/scan.php?page=news_item&px=LLVM-7.0-Clang-7.0-Released

**Comment by merlinpan** [comment]
Someone on talkchess mentioned:

with cudnn 7.3 and 411.63 driver available at nvidia.com 
minibatch-size=512, network id: 11250, go nodes 1000000

             fp32    fp16    
Titan V:     13295   29379
RTX 2080:     9708   26678
RTX 2080Ti:  12208   32472

This is lc0 (aka, leela chess with cudnn, batching, etc.)

go's network is bigger though (aka, chess's 256x20 is smaller than go's 256x20, let alone 256x40).  But in general, ~par with titan v's tensor units at <50% of the price.

Just as a reference, alphazero on TPUs are doing ~80k/s (chess).  So fp16 on 2x 2080ti is pretty close.

**Comment by l1t1** [comment]
I also saw it at http://blog.lczero.org/2018/09/guide-setting-up-leela-on-chess-gui.html

**Comment by Friday9i** [comment]
Maybe LC0 team has some contacts with Phoronix and may ask him to bench Leela Zero with a RTX2080Ti? That would be really nice ;-)

**Comment by thalessa** [comment]
I've yet to see a good benchmarking suite for GPU compute (unless you count coin miners). Perhaps it's because it's still very new and specialised.

How difficult is it to create a benchmarking standard or define the tests that should be included?

**Comment by l1t1** [comment]
here it is a 2080
https://github.com/gcp/leela-zero/issues/1871

**Comment by gcp** [comment]
Closing this because the Phoronix stuff isn't that useful for us.
