### ISSUE TITLE
Suggestion for training progress

### ISSUE THREAD

**Issue by petgo3** [gcp/leela-zero#1859]
On time parity still weight (157, best 15x192) seems the strongest LZ configuration. Might it be proper to mix in some selfplay games with (157, best 15x192) and lets say 6400 visits? These games should be of higher quality (at least at some aspects) and are quicker to generate. Is this a way to speed up training?
Perhaps I'm misunderstanding something.

**Comment by Crazyeight101** [comment]
The data would probably be of a lower quality, even with increased visits.  The best ways to hasten training progress are to recruit more clients and to continue improving the performance of the client itself.

I mean, the progress is nice and quick and steady with the 40b as it stands.  Even as we're producing less training games, we're still getting a promotion once every 3-4 days.

**Comment by Marcin1960** [comment]
@Crazyeight101 " The best ways to hasten training progress are to recruit more clients"

How do you this? Perhaps taking into account their wishes would help?

@Crazyeight101 "the progress is nice and quick and steady with the 40b as it stands"

I wonder, what does it mean: "58d1222a  VS  d13c4099 | 182 : 180 (50.28%)"?
 Isn't this same ELF net that was tested long time ago?
