### ISSUE TITLE
Elo calculation

### ISSUE THREAD

**Issue by pliuphys** [gcp/leela-zero#1862]
I looked at the Elo rating differences of a couple recent networks, and it seems that they are directly computed from the matches that resulted promotions. It seems to me that this would have a bias overestimating the improvement.

I tested a simple scenario: assume the true win probability of a new network is drawn from uniform distribution from 0.45-0.55. In this case one is always overestimating. I've seen quite a few networks promoted winning fractions a little larger than 55%, so I think this is not totally unrealistic. From a simple Monte Carlo code I see 10.6% of the new networks would get promoted, with average of 53.4% true win probability, and 56.5 measured probability (out of 1m samples).
 
If I move the distribution to 0.45-0.60, I get 34.4% promotion, observed avg win probability 0.580, true win probability 0.568.

The Elo difference, for win prob around 50% is pretty linear. So this would mean progress is overestimated by 90% and 17%, respectively. It's beyond my ability to immediately suggest how to fix this, but I think this implies we should take a grain of salt for the current Elo scores.

Edit: the median of the Elo increase from one best network to the next is 46, which translates to a 56.5% win probability.
Edit 2: I didn't simulate the SPRT. For each match I simply drew from the binomial distribution, with 400 games. I was selecting with win rate>55%, and has edited the number so I use games won>=220. The change is minimal.

**Comment by ThorAvaTahr** [comment]
Thanks for doing Some math on this topic. Is there anything you recommand ( that does not waste too much resources)? 

The fact that self-ELO as done here gives an overestimation is well-known. In fact there is hardly Any use in this value. It is even that True strength could well decrease with increasing self-ELO (think rock-scissor-paper). However we use it as a measure of progress, nothing else. We do have some anchors though, eg elf weights though No ELO is known for them either ( what would it even mean without fixing hardware?).

**Comment by pliuphys** [comment]
I'm not aware of any easy solution. If we measure the win rates again, after promotion, obviously there won't be such bias. Assuming self-Elo differences are additive, perhaps we can do matches with a couple pairs with a relatively large Elo gap (maybe 300?) and see how big the effect actually is. Recently many networks were promoted winning just a little more than 55% of the games, so I think the effect is large for the recent months.

AGZ also started at 0, but they only improved by ~7000 Elo in the whole training process. So it could be somehow they don't have this overestimation.

**Comment by alreadydone** [comment]
Check out "panel evaluation" in https://arxiv.org/pdf/1809.03928.pdf

**Comment by tapsika** [comment]
The "true" differences likely have a distorted normal-ish distribution instead of uniform, with a heavier positive side, and with a center and deviation that also depends on match visits. This latter is an important factor in how much luck is necessary for promotion.

Increasing visits amplify the differences between networks (without affecting the random noise, so less relative noise). The move from 3200 to 1600 had the opposite effect, that's why it is hardly possible to pass now without significant luck, so the Elo inflation got a bit worse.

On the other hand nobody takes these Elo values seriously, and as long as there are regular promotions and most promoted networks are better than the old one, there is no significant problem to fix (just somewhat slower progress).

**Comment by pliuphys** [comment]
I tested 20 games with network 160 against 173. I chose this period because the promotions are mostly close to the cutoff, and so the bias would be large. The Elo gap, according to the homepage, is 12278-11871=407 (8.76% win prob for 160). Network 160 won 8 of the games. 40% win probability would mean Elo gap of 70.4 The standard error of winning probability from my games are sqrt(0.4*0.6/20)=0.11, and this translates to a standard error for Elo 79.3. So Elo+2sigma is 229.0. For this pair of networks, it seems the Elo inflation is at least of order 100%.

PS: the match was ran with gogui-twogtp, and the results are for b/w for the zeroth game (https://lifein19x19.com/forum/viewtopic.php?f=18&t=5325)
[160_173_test1.zip](https://github.com/gcp/leela-zero/files/2409599/160_173_test1.zip)

**Comment by alreadydone** [comment]
There's a formula internal = cgos * 3.2 - 1074 posted at https://www.reddit.com/r/cbaduk/comments/7uba63/lz_cgos_rating_superimposed_over_internal_elo/

**Comment by pliuphys** [comment]
@alreadydone Thanks for pointing me to this. The fit is interesting, but only has data up to internal Elo ~7000. It could well be that the bias is worse now, since for the early period there are fewer failed networks for each passed one.

**Comment by roy7** [comment]
If someone was willing to download the networks and get with the Minigo people on how to run it, we could run their strength testing system to get a graph like:

https://www.cloudygo.com/leela-zero-v1/eval-graphs

which is based on networks playing many different older networks, not just the most recent one. So the relative strengths would be more accurate.

**Comment by pliuphys** [comment]
@gcp Could you point out a previous issue or two where this is discussed? All I found is https://github.com/gcp/leela-zero/issues/354 ,which is different from what I'm raising. Thanks.

**Comment by pliuphys** [comment]
I'll close this now and if I manage to calculate the current ELO by running matches myself I'll open another one.
