### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by Kev511** [gcp/leela-zero#1865]
I am on mac (OS X El Capitan version 10.11.6).

When I try to compile Leela Zero from the next branch, I get the following error: 

Detected OS: Darwin
/Library/Developer/CommandLineTools/usr/bin/make CC=gcc CXX=g++ \
		CXXFLAGS='-I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Headers -I. -Wall -Wextra -Wno-ignored-attributes -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG'  \
		LDFLAGS=' -flto -g' \
		leelaz
g++ -flto -g -o leelaz Network.o FullBoard.o KoState.o Training.o TimeControl.o UCTSearch.o GameState.o Leela.o SGFParser.o Timing.o Utils.o FastBoard.o SGFTree.o Zobrist.o FastState.o GTP.o Random.o SMP.o UCTNode.o UCTNodePointer.o UCTNodeRoot.o OpenCL.o OpenCLScheduler.o NNCache.o Tuner.o CPUPipe.o  -framework Accelerate -framework OpenCL -lboost_system -lboost_filesystem -lboost_program_options -lpthread -lz
undef: __ZN7NNCache15MIN_CACHE_COUNTE
Undefined symbols for architecture x86_64:
  "NNCache::MIN_CACHE_COUNT", referenced from:
      Network::initialize(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in lto.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [leelaz] Error 1
make: *** [default] Error 2

**Comment by Kev511** [comment]
I tried to get the master branch instead of the next branch. The compilation works fine now but when I try to launch Lizzie, I get a screen with "Leela Zero is loading" but it nevers ends. I waited for two hours and it was still loading. In the terminal, I see: 
Creating config file config.txt
Creating config file persist

Any Idea how to solve this issue ?

**Comment by gcp** [comment]
>when I try to launch Lizzie...Any Idea how to solve this issue ?

Ask in the Lizzie github.

**Comment by gcp** [comment]
The compilation issue should be fixed by dac5a1fe98d57ef02afb4578b52b850ba751b6bf

**Comment by Kev511** [comment]
It works now. Thanks a lot for yout help !
