### ISSUE TITLE
printsgf response violates GTP protocol

### ISSUE THREAD

**Issue by zhanzhenzhen** [gcp/leela-zero#1875]
I opened an issue in one of Sabaki's repo:

https://github.com/SabakiHQ/gtp/issues/2

But the author found that this is a Leela Zero issue, because a GTP response ends with two consecutive new lines, and Leela Zero introduces two consecutive new lines before the SGF ends.

**Comment by gcp** [comment]
Hmm, OK. Basically the SGF can't have an empty line in it.
