### ISSUE TITLE
Changing the playout amount during the game?

### ISSUE THREAD

**Issue by chucklu** [gcp/leela-zero#1877]
Hi,
Currently I can reset the time interval by command `time_settings 0 10 1`.
However , I did not find a command to reset the playouts.
Could you tell me how to make it?
related to https://github.com/SabakiHQ/Sabaki/issues/447

**Comment by gcp** [comment]
What do you mean exactly by "reset the playouts"?

**Comment by chucklu** [comment]
I can manage the Engine in sabaki with parameters --playouts 300.
![image](https://user-images.githubusercontent.com/3004057/46064687-ad3b2f80-c1a2-11e8-931b-b920cda486a3.png)
I hope you can provide a command to modify the playouts during the game.

When the game start in 100 steps, I only want to set the playouts to 50 which can generate the move faster.
But after the 100 steps of the go game, I would like to run the leela zero with playouts 200.
And after 200 steps, I would like to set the playouts to 300.

Currently I can only set the playouts of the go Engine at the begining  of  game, I want to modify the playouts during the game like I can modify the time internal by `time_settings` command

**Comment by gcp** [comment]
>I hope you can provide a command to modify the playouts during the game.

Yes. This is the final thing I want to add for v0.16.

LZ right now has a ```lz-setoption``` command which allows you to set the max memory usage. It should be extended to handle more options, especially visits, playouts, time management, lag buffer, resignation percentage, pondering...

Changing threads on-the-fly might be harder.

So the idea is that you would be able to do ```lz-setoption name Playouts value 2000``` and have the new setting take effect. The format is also such that a GUI can parse it (it is modeled after UCI for chess engines).

**Comment by cjohnchen** [comment]
I hope you can provide a command to change the networks during the game.

**Comment by gcp** [comment]
>I hope you can provide a command to change the networks during the game.

Like threads this might be a bit trickier to do on the fly. Changing the network could cause there to be no tuning available. So this won't be for v0.16 for sure.

**Comment by gcp** [comment]
This has been implemented and will be in v0.16.

Only playouts, visits and some other settings. Threads and networks are more complicated.
