### ISSUE TITLE
Suggestion: add to autogtp a parameter for lag

### ISSUE THREAD

**Issue by lwins-lights** [gcp/leela-zero#188]
Though most of people would like to see the training program running as fast as possible, it is not harmful to add this function to autogtp. For me, my laptop would be overheated due to full-speed operation of my GPU. Furthermore, enabling autogtp to run with partial computing resource would be friendly to other applications running on the same machine.

**Comment by gcp** [comment]
If your hardware is broken and overheating I recommend not running autogtp at all. 

Selecting the number of threads used or reducing the priority will probably be added at some point, but adding arbitrary delays is just bad.
