### ISSUE TITLE
Speed Estimation

### ISSUE THREAD

**Issue by arondes** [gcp/leela-zero#1884]
I am trying to find a simple way to estimate the speed of leelaz based on the feature of weights.

By using commands like follows:
`leelaz -w 20b.txt --gpu 0 --gpu 1 -t 8 --benchmark`
I got a number of benchmark results with different weights.

block | filter | n/s
-- | -- | --
40 | 256 | 229
40 | 256 | 229
20 | 256 | 385
20 | 256 | 391
19 | 256 | 498
19 | 256 | 502
20 | 224 | 528
20 | 224 | 533
15 | 192 | 733
15 | 192 | 739
10 | 128 | 1835
10 | 128 | 1843
6 | 128 | 3113
6 | 128 | 3118
5 | 64 | 5836
5 | 64 | 6060

After some experiments, I found that this formula works well to fit the data:

log(n/s) = Intercept + A * log(block) + B * log(filter)

For my data, the parameter estimates are: Intercept = 13.9967, A = -1.0520, B = -0.8528

i.e. n/s = constant * 1/block * 1/(filter^0.85)

The following table shows the true vs fitted values. Is it reasonable?

n/s | fitted value
-- | --
229 | 219
229 | 219
385 | 453
391 | 453
498 | 478
502 | 478
528 | 508
533 | 508
733 | 784
739 | 784
1835 | 1697
1843 | 1697
3113 | 2905
3118 | 2905
5836 | 6355
6060 | 6355

**Comment by tapsika** [comment]
Depth and filters affect speed on different powers, but your formula is not aware of this.

**Comment by arondes** [comment]
> Depth and filters affect speed on different powers, but your formula is not aware of this.

I think the powers are different with -1 and -0.85 roughly

**Comment by tapsika** [comment]
Sorry I somehow missed your log scale.

Theoretically depth has linear and filters quadratic effect, but OC this is not the case in practice because of various optimizations. Still 0.85 seems strangely close to linear.

**Comment by gcp** [comment]
The memory on the GPU also plays a large factor. Depth is linear, but if you start filling up GPU RAM some devices will plummet in performance. Not sure this can be estimated well by simple formulas.
