### ISSUE TITLE
Compilation error: Header file Eigen/Dense missing

### ISSUE THREAD

**Issue by seopsx** [gcp/leela-zero#1885]
> Network.cpp:34:23: fatal error: Eigen/Dense: No such file or directory
>  #include <Eigen/Dense>
>                        ^
> compilation terminated.

Compilation fails on next branch.

**Comment by ihavnoid** [comment]
Me too - are we supposed to add some more dependencies or is this that we are missing some files?

**Comment by ChinChangYang** [comment]
See #1882 and #1692 for reference.

**Comment by gcp** [comment]
You need to run the instructions from the README, i.e. update the git submodules.

**Comment by ihavnoid** [comment]
Oops, forgot to read the changed build instructions.  Works like a charm. :)

**Comment by mbc44** [comment]
> You need to run the instructions from the README, i.e. update the git submodules.

This is not enough for MSVC 2015.

**Comment by ChinChangYang** [comment]
@mbc44 See my pull request https://github.com/gcp/leela-zero/pull/1900 for MSVC 2015.

**Comment by mbc44** [comment]
@ChinChangYang OK.
