### ISSUE TITLE
suggest to make something for the leelaz project anniversary celebrations

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1886]
1. a standalone gui program as leela.
2. a detaled blog post or article to record the whole grow process.
3. a weight significant stronger than elf v1
4. some speical versions for amd and nv cards

**Comment by l1t1** [comment]
lc0 released a 2080 version just now
https://github.com/LeelaChessZero/lc0/releases/download/v0.18.0-rc2/lc0-v0.18.0-rc2-windows-cuda10.0-cudnn7.3-for-2080.zip

**Comment by l1t1** [comment]
a useful tool like this https://github.com/geovens/AQ-PS/releases

**Comment by thalessa** [comment]
In the west it is traditional to make a cake for birthdays.

There's a particular type of cake called a "layer cake" .

I'd suggest this [Belgian waffle layer cake](http://www.foodnetwork.co.uk/recipes/belgian-waffle-layer-cake.html), since Leela is at least partly Belgian.

**Comment by gcp** [comment]
A v0.16 release would be nice :-)
