### ISSUE TITLE
Precision autodetection chooses single precision when half precision is faster

### ISSUE THREAD

**Issue by seopsx** [gcp/leela-zero#1887]
The performance boost (193 -> 313 n/s) seems to imply that my GPU (GTX 1070) has half precision support. However, auto-detection says otherwise. Is is possible to manually set half precision for autogtp? I could find the setting only for leelaz.

Leelaz benchmark executed with manually set half precision:

> ./leelaz --precision half --benchmark -t 6 -w autogtp/networks/58d1222a3102e1689d20162f105c80c68b0b5d5cdfb922fc0adf20b5bee5f579.gz
> Thinking at most 2678400.0 seconds...
> NN eval=0.534770
> Playouts: 713, Win: 53.67%, PV: D3 C4 D5 C5 D6 B7 D16 Q4 P17 Q15 R6 O3 R4 R3 S3 R5 S4 Q5 S5 R2 Q6
> Playouts: 1501, Win: 53.68%, PV: C4 D3 E4 E3 F4 G2 Q4 D16 P17 Q15 F17 C14 D17 C17 C18 E17 D18 E16 E18 B17 F16 G18 F18 L17 J17
> Playouts: 2323, Win: 53.70%, PV: C4 D3 E4 E3 F4 G2 Q4 D16 P17 Q15 F17 C14 D17 C17 C18 E17 D18 E16 E18 B17 F16 G18 F18 L17 J17 O16 C12
> Playouts: 3151, Win: 53.73%, PV: C4 D3 E4 E3 F4 G2 Q4 D16 P17 Q15 F17 C14 D17 C17 C18 E17 D18 E16 E18 B17 F16 G18 F18 L17 J17 O16 C12 E14
> 
>   C4 ->    1333 (V: 53.90%) (N: 35.77%) PV: C4 D3 E4 E3 F4 G2 Q4 D16 P17 Q15 F17 C14 D17 C17 C18 E17 D18 E16 E18 B17 F16 G18 F18 L17 J17 O16 C12 E14
>   D3 ->    1243 (V: 53.84%) (N: 35.52%) PV: D3 C4 D5 C5 D6 B7 D16 Q4 P17 Q15 R6 O3 R4 R3 S3 R5 S4 Q5 S5 R2 Q6 S7 S6 R8
>   Q4 ->     303 (V: 53.06%) (N: 12.15%) PV: Q4 C4 D5 C5 D6 D16 D3 B7 P17 Q15 F17 M17 O16 J17 C17 D17
>  D16 ->     296 (V: 53.22%) (N: 10.78%) PV: D16 D3 E4 E3 F4 Q4 C4 G2 P17 Q15 D10 M17 O16 M15 O14
>  D17 ->      28 (V: 53.51%) (N:  0.84%) PV: D17 D3 E4 E3 F4 Q4 C4 G2 P17 C15 Q15 R15
>   R4 ->       7 (V: 53.53%) (N:  0.20%) PV: R4 C4 D5 C5
> 14.5 average depth, 29 max depth
> 2491 non leaf nodes, 1.29 average children
> 3211 visits, 1109269 nodes, 3210 playouts, **313 n/s**

Leelaz benchmark run with automatic detection:

> ./leelaz --benchmark -t 6 -w autogtp/networks/58d1222a3102e1689d20162f105c80c68b0b5d5cdfb922fc0adf20b5bee5f579.gz
> Thinking at most 2678400.0 seconds...
> NN eval=0.534728
> Playouts: 433, Win: 53.66%, PV: D3 C4 D5 C5 D6 B7 D16 Q4 P17 Q15 R6 O3 R4 R3 S3 R5 S4 Q5 S5
> Playouts: 907, Win: 53.70%, PV: C4 D3 E4 E3 F4 G2 Q4 D16 P17 Q15 F17 C14 D17 C17 C18 E17 D18 E16 E18 B17 F16 G18 F18
> Playouts: 1405, Win: 53.70%, PV: C4 D3 E4 E3 F4 G2 Q4 D16 P17 Q15 F17 C14 D17 C17 C18 E17 D18 E16 E18 B17 F16 G18 F18 L17 J17
> Playouts: 1913, Win: 53.71%, PV: C4 D3 E4 E3 F4 G2 Q4 D16 P17 Q15 F17 C14 D17 C17 C18 E17 D18 E16 E18 B17 F16 G18 F18 L17 J17 O16 C12
> Playouts: 2418, Win: 53.73%, PV: C4 D3 E4 E3 F4 G2 Q4 D16 P17 Q15 F17 C14 D17 C17 C18 E17 D18 E16 E18 B17 F16 G18 F18 L17 J17 O16 C12
> Playouts: 2925, Win: 53.73%, PV: C4 D3 E4 E3 F4 G2 Q4 D16 P17 Q15 F17 C14 D17 C17 C18 E17 D18 E16 E18 B17 F16 G18 F18 L17 J17 O16 C12 E14
> 
>   C4 ->    1364 (V: 53.93%) (N: 35.80%) PV: C4 D3 E4 E3 F4 G2 Q4 D16 P17 Q15 F17 C14 D17 C17 C18 E17 D18 E16 E18 B17 F16 G18 F18 L17 J17 O16 C12 E14
>   D3 ->    1199 (V: 53.79%) (N: 35.82%) PV: D3 C4 D5 C5 D6 B7 D16 Q4 P17 Q15 R6 O3 R4 R3 S3 R5 S4 Q5 S5 H3 Q6 H5 N4 P6 N3
>  D16 ->     314 (V: 53.36%) (N: 10.56%) PV: D16 D3 E4 E3 F4 Q4 C4 G2 P17 Q15 D10 M17 O16 F17 P14 Q13 J17
>   Q4 ->     294 (V: 53.03%) (N: 12.07%) PV: Q4 C4 D16 D5 P17 Q15 M17 R3 R4 Q3 O3 P3 P4 O2
>  D17 ->      32 (V: 53.74%) (N:  0.82%) PV: D17 D3 E4 E3 F4 Q4 C4 G2 P17 C15 Q15 R15
>   R4 ->       7 (V: 53.76%) (N:  0.20%) PV: R4 C4 D5 C5 D6
> 14.7 average depth, 33 max depth
> 2470 non leaf nodes, 1.30 average children
> 3211 visits, 1108368 nodes, 3210 playouts, **193 n/s**

Autogtp output:

> $ ./autogtp -s
> AutoGTP v16
> Using 1 thread(s) for GPU(s).
> Starting tuning process, please wait...
> net: 58d1222a3102e1689d20162f105c80c68b0b5d5cdfb922fc0adf20b5bee5f579.
> ./leelaz --tune-only -w networks/58d1222a3102e1689d20162f105c80c68b0b5d5cdfb922fc0adf20b5bee5f579.gz
> Leela Zero 0.15  Copyright (C) 2017-2018  Gian-Carlo Pascutto and contributors
> This program comes with ABSOLUTELY NO WARRANTY.
> This is free software, and you are welcome to redistribute it
> under certain conditions; see the COPYING file for details.
> 
> Using 2 thread(s).
> RNG seed: 6148014072603257724
> BLAS Core: built-in Eigen 3.3.5 library.
> Detecting residual layers...v1...256 channels...40 blocks.
> Initializing OpenCL (autodetecting precision).
> Detected 2 OpenCL platforms.
> Platform version: OpenCL 1.2 CUDA 9.1.84
> Platform profile: FULL_PROFILE
> Platform name:    NVIDIA CUDA
> Platform vendor:  NVIDIA Corporation
> Device ID:     0
> Device name:   GeForce GTX 1070
> Device type:   GPU
> Device vendor: NVIDIA Corporation
> Device driver: 390.48
> Device speed:  1771 MHz
> Device cores:  15 CU
> Device score:  1112
> Platform version: OpenCL 1.2 pocl 1.1 None+Asserts, LLVM 6.0.0, SPIR, SLEEF, DISTRO, POCL_DEBUG
> Platform profile: FULL_PROFILE
> Platform name:    Portable Computing Language
> Platform vendor:  The pocl project
> Device ID:     1
> Device name:   pthread-Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz
> Device type:   CPU
> Device vendor: GenuineIntel
> Device driver: 1.1
> Device speed:  3900 MHz
> Device cores:  8 CU
> Device score:  512
> Selected platform: NVIDIA CUDA
> Selected device: GeForce GTX 1070
> with OpenCL 1.2 capability.
> **Half precision compute support: No.**
> Loaded existing SGEMM tuning.
> Found Leela Version : 0.15
> Tuning process finished

**Comment by Ttl** [comment]
Your GPU doesn't have half precision compute support. Instead there is a bug with the auto precision that chooses single precision even if half precision was faster.

**Comment by seopsx** [comment]
This bug concerns also Tesla V100 which is becoming popular with the free google cloud trial.

V100 single:
> 3200 visits, 1104537 nodes, 3199 playouts, 298 n/s
V100 half:
> 3200 visits, 1104899 nodes, 3199 playouts, 384 n/s

**Comment by gcp** [comment]
Should be fixed.
