### ISSUE TITLE
Parameters used in old matches?

### ISSUE THREAD

**Issue by pliuphys** [gcp/leela-zero#1892]
Where can I find the parameters used in old matches? It seems they are saved in games after ~network 50. I had LZ5 played 200 games with LZ6, using version 0.15, -g -q -p 0 -v 1600 --noponder -t 1 -d -r 0, and LZ5 won 4 games. I thought it might be because I was using a new version. With Leela Zero 0.9, LZ5 (-g -q -p 1600 --noponder -t 1 -d -r 0 -w) won 2 out of 81 games. In comparison, official match shows 18 win in 153 games (~12%).

**Comment by gcp** [comment]
You would need to reset the source back to the current version at that data, as there were many bugfixes so you probably can't get the same result just changing parameters.

**Comment by pliuphys** [comment]
The problem might be that I don't have infinite thinking time set. I saw the thinking at most x seconds x increasing as the time goes on, but I'm not sure it's good for 500 move games.

I think I'll have to use the validation tool in the next branch, as it allows initial gtp commands.
