### ISSUE TITLE
the graph is strange when a  promoted weight is made by others

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1896]
![2018-09-30_095242](https://user-images.githubusercontent.com/23301704/46252081-61380580-c496-11e8-9770-4c19c06ccdfb.png)
maybe you should fix it

**Comment by l1t1** [comment]
![2018-09-30_100415](https://user-images.githubusercontent.com/23301704/46252173-d952fb00-c497-11e8-8670-2509acbf0f1c.png)

**Comment by roy7** [comment]
Sorry, was going to do it tomorrow, but I"ll adjust the dot location now.

**Comment by roy7** [comment]
Fixed.

**Comment by wonderingabout** [comment]
isnt there a better longterm solution that can avoid that ?

for example, is it possible for every match (not test) network to have at least the same game number than latest official network ?
this would fix the issue i think, but is it possible ?

**Comment by roy7** [comment]
I mentioned it to @bjiyxo that he can set a training count # when uploading networks, so it'll plot at the right space more in line with the nextworks gcp trains.

**Comment by wonderingabout** [comment]
ok, thank you
