### ISSUE TITLE
Lizzie not showing principal variations any more with latest leelaz from 'next'

### ISSUE THREAD

**Issue by dvdkhlng** [gcp/leela-zero#1899]
Hi,

yesterday when I tried to run the latest leelaz ('next') via Lizzie it seemed to run as usual, however, when holding my mouse over the colored move candidates shown, Lizzie would not show principal variations for those candidates any more.

I replaced the leelaz binary with one build from next at around Sep 2, and with that version Lizzie was working just normally.

Did anything change in the way leelaz outputs the variations so as to break Lizzie's expectations?

cheers,

David

**Comment by alreadydone** [comment]
I think it's due to recent lz-analyze output format change introducing another entry. Using Lizzie /next branch should fix it.

**Comment by dvdkhlng** [comment]
@alreadydone, the problem here is that Lizzie's 0.5 (linux) version explicitly tells users (in the readme file)" to download and compile leela-zero 'next' branch.  Now it looks like that is not really working any more.

**Comment by alreadydone** [comment]
It's been a long time and LZ /next keeps changing and now it's no longer compatible with Lizzie /master.

**Comment by betterworld** [comment]
Here's a workaround that works for me:

In Lizzie's directory, create an executable shell script `wrap-analyze`:

```
#!/bin/bash

"$@" | sed -Eu 's/winrate ([0-9]*) (N|prior) [.0-9]+ /winrate \1 /g'
```

Then edit config.txt and replace `./leelaz` with `./wrap-analyze ./leelaz` like this:

```
    "engine-command": "./wrap-analyze ./leelaz --gtp --lagbuffer 0 --weights %network-file --threads 2",
```

**Comment by hanamichigo** [comment]
If you can compile lizzie from source, I did the following to MoveData.java:

        coordinate = data[1];
        playouts = Integer.parseInt(data[3]);
        winrate = Integer.parseInt(data[5])/100.0;
        prior = Integer.parseInt(data[7]);
        order = Integer.parseInt(data[9]);

This will make the lizzie compatible with the current leela-zero next branch.

**Comment by dvdkhlng** [comment]
@hanamichigo: I compiled the 'next' branch from Lizzie and that seems to "just" work without doing any changes.  You mean using your changes lizzie's master would continue working?

@betterworld: nice script!

**Comment by gcp** [comment]
>I did the following to MoveData.java:

Yikes, I hope someone can fix lizzie to actually parse the tags and not assume that they are in any given order.

**Comment by kuba97531** [comment]
The next version of lizzie works well with the leela-zero-0.15.999.

It was done as part of a "Allow lizzie to work with alreadydone's dynamic komi."
https://github.com/featurecat/lizzie/pull/329
