### ISSUE TITLE
autogtp depends on msvc runtimes (0xc00007b error)

### ISSUE THREAD

**Issue by kityanhem** [gcp/leela-zero#19]
the application was unable to start correctly 0xc00007b. I meet this problem. I don't know how to play Leela Zero

**Comment by gcp** [comment]
What operating system, which video card and video drivers, how are you starting the program, what *exactly* are you doing...?

**Comment by kityanhem** [comment]
I use windows 7, AMD Radeon (TM) R7 360, 
I double click on autogtp.exe, first it need 2 file: msvcp140.dll, vcruntime 140.dll. I download two file on internet ,double click on autogtp again and it show this error box: the application was unable to start correctly 0xc00007b.

**Comment by gcp** [comment]
I'll check the autogtp compilation, but note this is a tool that's not supposed to be used directly. It just plays a single game between two Leela Zero's.

**Comment by kityanhem** [comment]
I see, thanks. If it can play with someone else or some AI else, it will be great.  Wait for a full version of Leela Zero . And if you can, can you make it show it strength like ELO? When I play with Leela before, I really don't know how strong it is.

**Comment by gcp** [comment]
You can use any GTP interface with the program. What you have is already the "full version". Strength depends on the weights file.

**Comment by kityanhem** [comment]
Can you make it play the other size board: 9x9 and 13x13?

**Comment by gcp** [comment]
The policy and value heads of the network are specific to 19x19. This comes directly from the AlphaGo Zero design. 

From experience, a network trained for 19x19 does not play very well on 9x9 anyway.

**Comment by kityanhem** [comment]
ok i fixed, forgot to install Visual C++ 2015 Redistributable x86. Before i just install Visual C++ 2015 Redistributable x64. But where is the board? img: https://goo.gl/PfodMd

**Comment by gcp** [comment]
What board? autogtp just lets the program play a game against itself, as already explained above.

**Comment by kityanhem** [comment]
Sr, I see. Now I have another problem, The file Leelaz.exe I open, it immediately close. I already put the file weights in same the folder. img: https://goo.gl/UkFgwE

**Comment by gcp** [comment]
Please see the README.md. You need:

--gtp -w weights.txt

(I assume it's named .txt, your screenshot has the full name hidden)

This will still only give you a text window. You need a real GTP interface that shows the board etc.

**Comment by gcp** [comment]
This should be fixed in v0.4, by building the proper runtime DLLs.
