### ISSUE TITLE
How to enable the infinite time set?

### ISSUE THREAD

**Issue by chucklu** [gcp/leela-zero#1902]
Hi ,
  I find the auto gtp was running leela zero with infinite time.
  How can I make it when I use it to play game?
  I have tried `time_settings 0 0 1`, but the command think the second 0 is valid.

**Comment by chucklu** [comment]
@gcp What's the best configuration for leela zero? like playouts, visits and time setting? maybe nodes?

```
13.5 average depth, 31 max depth
8844 non leaf nodes, 1.25 average children
11028 visits, 3853523 nodes, 7111 playouts, 120 n/s
```

**Comment by alreadydone** [comment]
infinite time is 0 1 0 IIRC.
Use GTP time settings for maximal strength under time constraint, playouts or visits for fixed strength across machines. (playouts uses roughly equal time for each move.) Have you read `leelaz -h`?

**Comment by pliuphys** [comment]
@alreadydone 
Is there a difference between using 0 1 0 and timemanage off?

**Comment by chucklu** [comment]
Yes, I have read the parameters info for leelaz.exe, but can not find the info about how to use infinite time setting. Thanks for your reply.
```
E:\Go\leela-zero-0.15-cpuonly-win64> .\leelaz.exe -h
Leela Zero 0.15  Copyright (C) 2017-2018  Gian-Carlo Pascutto and contributors
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.


Generic options:
  -h [ --help ]                  Show commandline options.
  -g [ --gtp ]                   Enable GTP mode.
  -t [ --threads ] arg (=8)      Number of threads to use.
  -p [ --playouts ] arg          Weaken engine by limiting the number of
                                 playouts. Requires --noponder.
  -v [ --visits ] arg            Weaken engine by limiting the number of
                                 visits.
  -b [ --lagbuffer ] arg (=100)  Safety margin for time usage in centiseconds.
  -r [ --resignpct ] arg (=-1)   Resign when winrate is less than x%.
                                 -1 uses 10% but scales for handicap.
  -w [ --weights ] arg           File with network weights.
  -l [ --logfile ] arg           File to log input/output to.
  -q [ --quiet ]                 Disable all diagnostic output.
  --timemanage arg (=auto)       [auto|on|off|fast] Enable time management
                                 features.
                                 auto = off when using -m, otherwise on
  --noponder                     Disable thinking on opponent's time.
  --benchmark                    Test network and exit. Default args:
                                 -v3200 --noponder -m0 -t1 -s1.

Self-play options:
  -n [ --noise ]                 Enable policy network randomization.
  -s [ --seed ] arg              Random number generation seed.
  -d [ --dumbpass ]              Don't use heuristics for smarter passing.
  -m [ --randomcnt ] arg (=0)    Play more randomly the first x moves.
  --randomvisits arg (=1)        Don't play random moves if they have <= x
                                 visits.
  --randomtemp arg (=1)          Temperature to use for random move selection.

```

**Comment by pliuphys** [comment]
As long as you're in the gtp mode you can probably use this
https://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html

arguments | main_time byo_yomi_time byo_yomi_stones
-- | --
  | int main_time - Main time measured in seconds.
  | int byo_yomi_time - Byo yomi time measured in seconds.
  | int byo_yomi_stones - Number of stones per byo yomi period.
effects | The time settings are changed.
output | none
fails | syntax error
comments | The interpretation of the parameters is discussed in section 4.2. The engine must accept the requested values. This command gives no provision for negotiation of the time settings.

**Comment by chucklu** [comment]
@alreadydone  thanks, it works
