### ISSUE TITLE
Optimization: Using the opponent's time to continue MCTS

### ISSUE THREAD

**Issue by foreverpokemongo** [gcp/leela-zero#1903]
I am wondering if the following optimizations have been implemented:

1) While waiting for the opponent's next move, continue MCTS (even when maximum thinking time is exceeded);
2) When the opponent's move is chosen (which is likely to have been evaluated preliminarily when deciding the previous move), reuse part of the MCTS evaluation done in the previous move.

**Comment by Vandertic** [comment]
Both are implemented from the beginning. The first one is "pondering" which may be disabled by the command line option --noponder.
