### ISSUE TITLE
suggest play a match of funny positions

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1915]
I saw 
![2018-10-06_115841](https://user-images.githubusercontent.com/23301704/46567142-206c4080-c91d-11e8-84d7-af8fce569352.png)
from https://www.chess.com/computer-chess-championship
it did not obey the chess oepning rule.
so I draw a position like this, 
![2bug](https://user-images.githubusercontent.com/23301704/46567151-4265c300-c91d-11e8-93a2-4258a3753724.png)
let the each pair of bots play both white and black, should be interesting

**Comment by arondes** [comment]
Start with this
![2](https://user-images.githubusercontent.com/17297973/46571282-a1224f80-c9a4-11e8-947e-9113cefc6d76.PNG)

End with
![3](https://user-images.githubusercontent.com/17297973/46571291-b8f9d380-c9a4-11e8-8c14-8ca76c7a5aa0.PNG)

**Comment by l1t1** [comment]
lc0 failed in such games,  as those position wont appear in self play games

**Comment by l1t1** [comment]
it is also told at http://blog.lczero.org/2018/10/tcec-cup-started-cccc-variants.html?m=1#more

**Comment by Hersmunch** [comment]
I'm not a huge fan of starting from particularly silly positions for matches but I think the idea of having some variation in the openings would provide an wider performance evaluation. I mean that surely testing out each network in a larger variety of situations is more likely to show more strengths and weaknesses. As a side benefit (in my opinion) it would produce more interesting go to look through.
What would be the most fair way to do this though? T=1 for a small number of moves?

If it would help I could have a look at refactoring autogtp to allow for different command line options and gtp commands to be passed to each of the engines for matches. This could be used to alternate which side has more randomness to allow the effect to be evenly divided between the two.
