### ISSUE TITLE
Question regarding python script resign_analysis.py

### ISSUE THREAD

**Issue by Ishinoshita** [gcp/leela-zero#1917]
In resign_analysis.py, the process flow indicated is:
```
Run autogtp with debug on:
    autogtp -k savedir -d savedir
Unzip training and debug files:
    gunzip savedir/*.gz
Analyze results with this script:
    ./resign_analysis.py savedir/*.debug.txt.0
```

Running "autogtp -k savedir -d savedir" generates mostly -r 5 games and only 10% (expected) of -r 0 games. To accumulate, say 100 -r0 games to have some statiscally meaningful result, it would take to generate 1000 self-play games, which is very long...

Is there a way to generate *only* -r0 games, with autogtp (I mean with training data and debug info) ? Kind of weird, sadomasochist request, I must admit ! ;-)

Edit: Alternatively, if someone has a bunch of no-resign games on his PC, *along with training data files and debug files*, and can make me a zip, I would be even more grateful ;-)
![image](https://user-images.githubusercontent.com/37498331/46572616-6828b180-c989-11e8-9392-80b91d3f9f5f.png)

(Wanna do some analysis on wrongly resigned games at various resign threshold. But only have a GTX960 to generate the games ...)

**Comment by gcp** [comment]
It probably requires some modification to AutoGTP to ignore the server supplied resign threshold.

**Comment by Ishinoshita** [comment]
Thank you. I guessed so, but I asked in case there would have been some 'hidden ' command, not documented in the help.

**Comment by alreadydone** [comment]
https://github.com/gcp/leela-zero/blob/cd1de6efb5ca61ac0c9cbc043753ad8fa20d1f01/autogtp/Management.cpp#L263
change this line to `options.append(" -r 0 ");` should work
