### ISSUE TITLE
qmake -qt5 shows "Unknown option -qt5" when compiling autogtp

### ISSUE THREAD

**Issue by balabi0github** [gcp/leela-zero#1919]
Dear developers,

I try to install leela zero on ubuntu. Everything goes fine with leela-zero installation. But I got some problem with installation of autogtp. Accroding to https://github.com/gcp/leela-zero/blob/master/autogtp/README.md . After "sudo apt-get install...", when I run "qmake -qt5", it says

> ***Unknown option -qt5

What is wrong?

best regards

**Comment by ihavnoid** [comment]
What ubuntu version do you use?  I have no problem with 16.04 and 18.04 - can you check your qmake version?

**Comment by balabi0github** [comment]
@ihavnoid Thank you for quick reply. 
`qmake --version`
gives

> QMake version 3.0
> Using Qt version 5.6.2 in xxxxxx/anaconda3/bin/lib

and 

`lsb_release -a`

gives

> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 16.04.2 LTS
> Release:        16.04
> Codename:       xenial

'ls' in autogtp folder gives

> autogtp.pro     Game.cpp  Job.h         main.cpp        Order.cpp  Result.h
> CMakeLists.txt  Game.h    Keypress.cpp  Management.cpp  Order.h    Worker.cpp
> Console.h       Job.cpp   Keypress.h    Management.h    README.md  Worker.h

**Comment by joseph-ireland** [comment]
Try just `qmake` without `-qt5`, it seems to be using Qt 5 anyway without any flags.

**Comment by balabi0github** [comment]
@ihavnoid well, using "qmake" alone also doesn't work. It gives

> Could not find qmake configuration file linux-g++.
> Error processing project file: xxxxxxx/leela-zero/autogtp/autogtp.pro

**Comment by joseph-ireland** [comment]
what does `which qmake` give you? `xxxxxx/anaconda3/bin/lib` is a bit suspect. If it's showing `xxxx/anaconda3/bin/qmake`, then try running `/bin/qmake -qt5` or `/usr/bin/qmake -qt5`

There's another similar issue here: #62
