### ISSUE TITLE
68d7 got winrate 0.55 at 400 games but failed at games 411

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1922]
![734548993](https://user-images.githubusercontent.com/23301704/46773927-759bbe00-cd32-11e8-87ff-92bdca75ad2b.jpg)

please promote it by hands

**Comment by l1t1** [comment]
it is promoted now, is the delay a bug?

**Comment by alreadydone** [comment]
I guess a promoted network appears on the left when its first self-play game is stored in database.

**Comment by roy7** [comment]
That is correct. The server recognizes a network as being promoted if it has any self play games.

**Comment by l1t1** [comment]
but I think the table at right side should shows PASS when games >=400 and at least ONE winrate after 399 is equal or bigger than 0.55

**Comment by gcp** [comment]
Server not client issue.
