### ISSUE TITLE
Small questions to GCP about ELF games

### ISSUE THREAD

**Issue by herazul** [gcp/leela-zero#1937]
Are they officially out of the window now that we have more than 500K games of 40b net ?

I was also wondering, what is the current learning rate for the official training process ?

**Comment by gcp** [comment]
They're still in. I reduced the fraction a bit but it didn't do much, I'll just try again later on. We saw from the tests that the current nets are stronger but not that much.

The learning rate is still the same as when we switched: 0.0001 @ bs = 96.
