### ISSUE TITLE
Two new weirdness found in training data ? - LZ177

### ISSUE THREAD

**Issue by Ishinoshita** [gcp/leela-zero#1939]
**The reason of this new post**
1) Most of the so-called weird data ('anomaly' 1 : policy values not multiples of 1/1600th) I mentionned [here](https://github.com/gcp/leela-zero/issues/1904) have found a natural explanation in the fact that some clients already use next branch for self-play, which enables time management pruning also for self-play (see @Tll comment).

   *I took the opportunity to compare the policy distributions with time mgt pruning On and Off . See analysis results posted in the corresponding PR [here](https://github.com/gcp/leela-zero/pull/1497#issuecomment-430412729).*

2) HOWEVER, there are still **really weird** training data, not explained by 1), although in lesser proportion (2%-4% of training samples)

### Very concentrated policy, with (fake?) values p=0.252101 at move 0:

Described in details in this powerpoint:
[LZ177 training data - Anomaly 2.1 - Too concentrated policy.pptx](https://github.com/gcp/leela-zero/files/2485106/LZ177.training.data.-.Anomaly.2.1.-.Too.concentrated.policy.pptx)

Just to give a flavour:
![image](https://user-images.githubusercontent.com/37498331/47050360-5ffa1e80-d1a0-11e8-9f37-9e8a4cfc813b.png)

![image](https://user-images.githubusercontent.com/37498331/47050380-730cee80-d1a0-11e8-81fb-c5108268c85f.png)

Hard to believe that repeatedly getting 4 hoshi at ~25% proba, with 3 of them with exactly the same policy value, is something that can be achieved with 25% of Dirichlet noise ;-). 

But this not just a matter of starting position. Policy look way too much concentrated all through the game, often on 2-3 moves, if not on a single move with 100% proba, and with series of such 100% proba moves in a row. 

![image](https://user-images.githubusercontent.com/37498331/47050877-478b0380-d1a2-11e8-9627-394c9a988032.png)

I refer you to the document to see more statistics and why these games are very different in terms of policy distribution (contrary the data produced with time management pruning On). And to this sgf to have a feel: [chunk_1055_game_2.zip](https://github.com/gcp/leela-zero/files/2485128/chunk_1055_game_2.zip)

These games represent 1.8% of the positions in my sample (610k positions corresponding to chunks 1000 to 1099). I'm still wondering if they have some natural/unintentional explanation or if they are malevolently produced. Anyway, I find worrisome to have them in the training data. When 40b will reach a plateau and every Elo gain will be difficult, even a dilution with a few % of wrong data might hurt.

Edit: after checking another slice of training data (chunks 0 to 99), found 7 games using the famous value p_max=0.252101 for each of the 3 hoshi, at move 0, plus 117 games using another value, p_max=0.253968. Both clearly out of distribution (see powerpoint here above), and matching the other signatures (policy much more concentrated, typically over 3 to 5 moves, with high frequency of p=1 for a single move). This time, the proportion amounts to 124 games out of 3195, or 3.9% of the training data. No more pee in the ocean...

I didn't dig further on LZ177 data, but:
- I confirmed that LZ156 (network hash 7ff174e6 uploaded 18-Jul-2018) does not exhibit the issue (at least the slice I studied).
- I will now have a look at more recent training data, generated by LZ181 (hash 68824bcc) and made available by @gcp this Monday. It was claimed that it contains a lot of 'fake' self-play games, from human go players perspective at least. I will look at the numerical aspect.

### Picked move with 0 probability:

*I don't recall of any randomness mechanism allowing to pick a move that has recieved 0 visit during the search, so I basically assume picked move cannot have 0 policy value in the training data (if I'm wrong, then please dismiss all of the following).*

I incidently found some games in which one or more moves picked by temperature have 0 policy value (p_picked=0 hereafter) in my .csv stats table. I manually checked the raw training data (open with notepad, locate the game/position by counting the input planes and checking for game reset, convert input planes from hex to string, compare, count character and determine flat coordinate, etc..., all *manually*) and I didn't confirm the issue in the data. Just found there was a bug in my code (glitch when switching to a new game, in some conditions).

But after correction, still found a residual number of positions with p_picked=0. Although now totally negligible (308 positions/~610k, but still 119 games/3200) I was intrigued and checked again manually a few of these positions, this time confirming that the problem was at the data level.

See details here : [LZ177 training data - Anomaly 2.2 - Zero visit move picked.pptx](https://github.com/gcp/leela-zero/files/2485150/LZ177.training.data.-.Anomaly.2.2.-.Zero.visit.move.picked.pptx)

I may be doing something wrong again. If you want to double-check by yourself, see for example position 79 of game 1 of chunck 1079  (*NB: I'm counting positions starting at 0 but games starting at 1; and chunks by using the chunk number found in the training zip file*).

This 'weirdness' seems to indifferently affects games with time management Off or On, and games with or without the first issue mentioned hereabove (too concentrated policy). So I'm wondring if this is a bug / glitch in leelaz code or autogtp... I didn't do an in-depth analysis of possible difference in the policy distribution for this weirdness, but possibly found at least some:
![image](https://user-images.githubusercontent.com/37498331/47051159-59b97180-d1a3-11e8-8311-b2b79a5a464c.png)

#### Update - 08 Nov 2018
p_picked = 0 is a false issue due to a bug in my script. In fact due to my ignorance of an oddity in the input planes encoding, as explain [here](https://github.com/gcp/leela-zero/issues/2002#issuecomment-437132686).

**Comment by wonderingabout** [comment]
i dont understand all the technical data, but we saw in the past non zero games introduced several times, which (among these were alphago games, pro games, or more recently very short time games), which @gcp compared in the past polluted fake games in leela zero to a pee in the ocean

what if it was now a pee in a bathtub (or whatever smaller water container you can imagine :) )
contributors will never be able to check all games generated, so regardless of this issue, it may be time to add security filtering and checks to approve generated self play games (even if the checks are basic)

**Comment by Ishinoshita** [comment]
@wonderingabout  Maybe better first have some devs double check my work. Then see if there might be some logical explanation (bug or whatever) that can be fixed. If the final conclusion is a malevolent origin, then what you suggest will make sense.

**Comment by Ishinoshita** [comment]
@wonderingabout
>I dont understand all the technical data

I am aware that these statistical indicators that I defined by myself don't have an immediate intuitive meaning unless you have played yourself with the data.

Please refer to my [repo](https://github.com/Ishinoshita/Leela-Zero-Training-Data-Viewer/blob/master/README.md) for definitions, and feel free to ask regarding the more obscure aspects.

**Comment by Ishinoshita** [comment]
Regarding second issue (picking of move with 0 visits), is it possible that someone has compiled his own leela version with the following parameter:

   cfg_random_min_visits = 1

defaulted to 0 value instead? 

I also note that the following parameter could be 'cooked' (to freeze in fact ;-) to get some annealed, very concentrated policy, and achieve the weirdness of the first kind:

   cfg_random_temp = 1.0f

This was introduced by this [PR] ( https://github.com/gcp/leela-zero/pull/1376) if I got it correct.

I also noticed the mention by @Friday9 in another post of a command

   --random visits

but I was unable to retrieve it in the code.

**Comment by Ishinoshita** [comment]
### Update - LZ181 training data 'contaminated' as well (4% of weird data) with yet another signature: Black first move is a blunder, policy looks incredibly flat at move 0, Black/White win rate is unbalanced (80/20).

Sorry to bring bad news. I'm afraid we are facing a mutating agent (or an imaginative mischievous guy if you prefer). I just checked a slice of 3200 games (chunks 12xx). By the way, I have not yet came across the supposedly weird game with big L shape. But it's just 100 chunks out of 3400+...

Scroll through this ppt and through the sgf's in the zip to have a feel. 
[LZ181 - 12xx.pptx](https://github.com/gcp/leela-zero/files/2489519/LZ181.-.12xx.pptx)
[chunk 12xx - Sample of weird games.zip](https://github.com/gcp/leela-zero/files/2489520/chunk.12xx.-.Sample.of.weird.games.zip)


![image](https://user-images.githubusercontent.com/37498331/47119579-b3856e80-d26b-11e8-9a51-ac8211765c66.png)

**Comment by wind68** [comment]
http://zero.sjeng.org/view/0a1a006a68e9eb5897641931ab57045bcc141cff203e9ba977652bd89bda0bef?viewer=wgo
http://zero.sjeng.org/view/e251197168b61c927b2ea0cefaf10bb2b6d6038f9ae0791e312059e17415ee0b?viewer=wgo
http://zero.sjeng.org/view/2ad077785178722c98de7b9ce80f802dfc9815bf98369a0bb28f6a6da43bd453?viewer=wgo

**Comment by wind68** [comment]
see the games and the network

**Comment by Ishinoshita** [comment]
@wind68 
(1) These game are indeed definitively abnormal: sgf reports 60 minutes time control and 7c6588ce network hash (LZ142, 15x192 network from May 2018).
(2) However, just saying "see the games" is not sufficient in itself to understand why you think they are weird self-play games. Others don't necessarily see what you see. For instance, I dont immediately see why you think they are fake/weird. Particularly, move 4 (J9) in game 1 and move 74 (J13) in game 3 are totally 'legitimate' moves under self-play condition. Such moves are always an option, with noise + randomness. If I'm off topic and the weirdness is see is somewhere else (playing style, opening, etc..), then you have to state it, if you want others to be able to 'see' it ;-)

**Comment by wonderingabout** [comment]
@Ishinoshita 

we dont need to go that far

the simple fact that these games are played with abnormal networks, with 101 visits instead of 1600 is enough to flag them

the question is how such games could be produced

**Comment by wonderingabout** [comment]
another wrong game (101 visits again, should be same client) : 

https://zero.sjeng.org/view/856501fcfe3c125ce43481c2089cfc0f7017096dd06478198383cfb3811e0d35?viewer=wgo

**Comment by Ishinoshita** [comment]
-  Most weird data will probably stay un-explained.
-  the marginal observations of some games with p_picked = 0 was a bug in my code.
- I recently checked some LZ190 training data and didn't see anything obviously weird.
