### ISSUE TITLE
Different path of use: can I use leela to learn and evaluate position

### ISSUE THREAD

**Issue by kwccoin** [gcp/leela-zero#1944]
I note the heatmap of Sabaki leela zero program.  It would be nice i

(a) f one can start from any arbitrary position and ask leela-zero to evaluate it.  
(b) Even better it never execute any move but just tell us what it thinks!  

For the last 40 years playing go, I am more as an observer not a competitor.  Hence this will help when there is no commentator to help us what is going on.  I might even go back to check on Mr Ng's game with three-three, star and heaven-point.

Of course once we have that we have to ensure no computer equipment and google glass etc. be bought to tournament.  But I think the whole idea is not about.  But give us hint all the steps so we can study various moves.

**Comment by apetresc** [comment]
This is exactly what tools like Lizzie and Sabaki are for. They can both operate in exactly the mode you describe, and leela-zero has added the necessary GTP commands to support them.

**Comment by Atarust** [comment]
Lizzie is here: https://github.com/featurecat/lizzie/releases

Have fun!
