### ISSUE TITLE
leelaz can win 0.5 why  resign?

### ISSUE THREAD

**Issue by greatken999** [gcp/leela-zero#1947]
I tested a game with leelaz vs opengo , leelaz resigned after 303 moves.
but leelaz can wins by 0.5  points if count score.
leelaz version:0.15
system :ubuntu 16.04
sgf review [url:](http://www.gogo1.fun/scansgf.php?filename1=opengovsleelaz-2018-10-20-11-39-50-0)
maybe this is a bug .
![2018-10-23 10-51-04](https://user-images.githubusercontent.com/25077146/47352831-57986b00-d6ed-11e8-91af-7f2ceca1f132.png)

**Comment by MartinDevelopment** [comment]
We use Thromp Taylor rules to count the games.

**Comment by hanamichigo** [comment]
The leelaz network weights is trained on a 7.5 komi. If the komi used is 6.5, leelaz thinks she is 0.5 points behind and will eventually resign.

**Comment by hanamichigo** [comment]
I reviewed the game; leelaz is right to resign. She will require more stones (enough to lose) in order to kill black's left group.

**Comment by greatken999** [comment]
@hanamichigo ，komi is 7.5.
to kill black's left group ,also black need follow moves too,,this is not correct.
I think this state of game correct process is result pass .

**Comment by ihavnoid** [comment]
Which net did you use?  I used a pretty recent net and it got things backwards, but an older net (58da6176)   seemed to correctly find it is winning. It seems the net itself is confusing itself on whether it is winning or not, especially when we are pretty close.

**Comment by greatken999** [comment]
> Which net did you use? I used a pretty recent net and it got things backwards, but an older net (58da6176) seemed to correctly find it is winning. It seems the net itself is confusing itself on whether it is winning or not, especially when we are pretty close.

game is use a53cd929

**Comment by ihavnoid** [comment]
Looking a bit more carefully, I think you used Japanese rules while leelaz is using Tromp-Taylor rules (hence Chinese rules).

Leelaz eventually says black wins by 1.5p.  I painfully calculated one by one and got W=176, B=185.

**Comment by alreadydone** [comment]
Apparently area and territory scoring don't agree here because white passed move 298.

**Comment by greatken999** [comment]
> Looking a bit more carefully, I think you used Japanese rules while leelaz is using Tromp-Taylor rules (hence Chinese rules).
> 
> Leelaz eventually says black wins by 1.5p. I painfully calculated one by one and got W=176, B=185.

your point is leelaz win when use japanese rules,and opengo win when use chinese rules?

**Comment by greatken999** [comment]
> Apparently area and territory scoring don't agree here because white passed move 298.

so leelaz estimate it's winner when 298 move,and leelaz estimate loss game when 303 move?

**Comment by ihavnoid** [comment]
No, leelaz uses Chinese rule only so it estimates it loses for both moves.

**Comment by greatken999** [comment]
> No, leelaz uses Chinese rule only so it estimates it loses for both moves.

so why 298 choice pass,,that is a winnerr's choice

**Comment by hanamichigo** [comment]
In Chinese rules, that black group on the left is considered alive. If there is disagreement after two consecutive passes (with White first to pass), the players will eventually be forced to place stones in order to settle the status of that black group, with White first to play.

**Comment by TFiFiE** [comment]
After move 284, the game is effectively finished with black winning by 1.5 points. Afterwards, both engines played a few more moves that have no effect under area (Chinese) scoring, but can waste points under territory (Japanese) scoring.
