### ISSUE TITLE
Error in OpenCL calculation with servere value mismatch

### ISSUE THREAD

**Issue by Jendker** [gcp/leela-zero#1951]
When playing in terminal with following options:
leelaz --noponder -t 4 --playouts 1 -w ../best-weights

I got following error:
Error in OpenCL calculation: expected -6.047833 got -66514627249526939283794135678451712.000000 (error=1099809204173870401369550064137011200.000000%)
Update your GPU drivers or reduce the amount of games played simultaneously.
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: OpenCL self-check mismatch.

I've seen this issue https://github.com/gcp/leela-zero/issues/849 but this is for sure something more severe.

**Comment by Jendker** [comment]
Detecting residual layers...v1...256 channels...40 blocks.
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 (May 24 2018 22:33:53)
Platform profile: FULL_PROFILE
Platform name:    Apple
Platform vendor:  Apple
Device ID:     0
Device name:   Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
Device type:   CPU
Device vendor: Intel
Device driver: 1.1
Device speed:  2300 MHz
Device cores:  8 CU
Device score:  512
Device ID:     1
Device name:   Intel(R) Iris(TM) Plus Graphics 655
Device type:   GPU
Device vendor: Intel Inc.
Device driver: 1.2(Aug 14 2018 19:16:17)
Device speed:  1050 MHz
Device cores:  48 CU
Device score:  612
Selected platform: Apple
Selected device: Intel(R) Iris(TM) Plus Graphics 655
with OpenCL 1.2 capability.
Loaded existing SGEMM tuning.
Wavefront/Warp size: 16
Max workgroup size: 256
Max workgroup dimensions: 256 256 256 

I am on the master branch.

Right now it is difficult for me to reproduce the problem, but I am not able to run leela zero in Sabaki with LeelaSabaki at all or run properly in terminal if I increase `playouts` parameter to some reasonable value. I found this issue: https://github.com/gcp/leela-zero/issues/1677 so I guess it is something more to do with leela zero to run properly on mac and maybe this what I observed is just one of the possible effects.

**Comment by gcp** [comment]
More broken Mac OpenCL drivers, yay.

>I am on the master branch.

The #1677 issue suggests to try to fall back to F(2x2, 3x3) as a workaround for broken drivers (really: MacOS machines), but if you're on the master branch you're already using that. I don't think there's a solution here besides using the CPU. Your GPU is unusable because it's drivers are too broken.
