### ISSUE TITLE
ridiculously short self play games, all by same user

### ISSUE THREAD

**Issue by wonderingabout** [gcp/leela-zero#1957]
![suspiciously short games 2](https://user-images.githubusercontent.com/38690718/47519005-cf50cc00-d88c-11e8-9b28-e4fee0d4071e.PNG)

as a Tesla V100 takes 5 minutes to generate a 150-200 moves game, i just dont see how it can be so fast

link to sgf : 

https://zero.sjeng.org/view/e5f7b93cd097d87fdd06feb3b01f95849146423e2be06ab4ab2c8824ce1198c1?viewer=wgo

https://zero.sjeng.org/view/2cd619ea6ccb38b9b05a4235c706472888460fa1d034012b3c12ecf842580dcd?viewer=wgo

https://zero.sjeng.org/view/aaa628d9752749aacd0c8bf1415ffd4c14d56bb042568e234e54ab729e347457?viewer=wgo

https://zero.sjeng.org/view/4ad247fe30143e349eb8fc0f1538e047b40effa99ddeeb48fde07bcbecdfa613?viewer=wgo

https://zero.sjeng.org/view/e4e24c3a089a85e5a3ed5d91f05cb344ed333427fe921ac3d668eac9430bda3f?viewer=wgo

https://zero.sjeng.org/view/c35713b78a6d038669f61e3670f6fd39658946f1881f0b542ceb4c7110878840?viewer=wgo

https://zero.sjeng.org/view/3b628317b3fbd2b59824d8f5cbed36ece4303833e1d108058550ff157d007d1d?viewer=wgo

https://zero.sjeng.org/view/a7804dd62cb68c21a2976bf234179617ecc2aaca9094f8dce02e1444de16177b?viewer=wgo

with a quick glance at the sgf, it seems as if these games were not random games

bad games again ?

**Comment by wonderingabout** [comment]
#1939 #1906

**Comment by wpstmxhs** [comment]
Another possible case is, that someone is running autogtp with V100 x8 from Google Cloud.

**Comment by wonderingabout** [comment]
i never used multi gpu on autogtp, but i'm almost sure if it was V100 x8, you'd get 8 games generated in 3,5-5 minutes mininutes minimum each

and again, the games look too clean to me, and different from our 40b self play games (which generally include a lot of ELF 4-4 4 approach joseki in more than 50% of selfplay, which i didnt see here at all)

if someone could watch selfplay gamedata sent it would be clear

**Comment by Ishinoshita** [comment]
@wonderingabout  New training data produced by LZ184 have been published (chunks 0 to 26xx now available). I studied the games n°2 and n°5 you linked here above. I looked in the training data for the hex string corresponding to the end positions of these two game. And got a hit each time. See both original sgf files and sgf reconstructed with train2sgf:

[Too fast to be true.zip](https://github.com/gcp/leela-zero/files/2536323/Too.fast.to.be.true.zip)     **Obviously FAKE data !**
  

*NB: chunks published on 26-Oct-2018 were chunks 0 to 894 and I didn't find anything. The suspicious games were in the very next chunks 9xx ! ;-)*

**Comment by wonderingabout** [comment]
@Ishinoshita 
thanks for putting this to light

more than only banning people and missing others,
i suggest we add automated validation of selfplay games
for example when a game is submitted by autogtp, it gets in the "pending" queue and will not be used until its policy has been analyzed by an automated tool (simple sanity checks)

is it possible @roy7 @gcp @alreadydone ?

**Comment by roy7** [comment]
Sure anything is possible if someone can code it up. But that's beyond my ability to contribute currently. :)

**Comment by wonderingabout** [comment]
@Ishinoshita @roy7 
i'm 95% sure these games (10 minutes ago) are all fake too (they look all not random at all)

![too fast](https://user-images.githubusercontent.com/38690718/47858031-67016d80-ddeb-11e8-8d28-1f545e9a8104.PNG)

**Comment by roy7** [comment]
Client 73 isn't anything I can identify. Coming from USA via a normal ISP it seems.

Client 23 is coming from "googleusercontent" so I'm assume that is Colab?

Client 1 is from China, can't tell any more than that.

**Comment by Ishinoshita** [comment]
@wonderingabout 
> analyzed by an automated tool (simple sanity checks)

The problem is that, on the long run, these sanity checks are are not at all simple to define, before considering automation. You don't know in advance what you're lookink for and anomalies signatures are numerous and/or evolving.

I personaly came across some anomalies just by chance, while doing various stats, looking at the data under different angles. Spot some strange pattern in the distribution, move from stats to raw data, try to find some 'objective' criterion for a supposed weirdness, flag the corresponding sub-population, run stats again to compare if this sub-population as a statistically significant difference in terms of policy, black win rate or whatever. Report and see if there is a known,  logical explanations. Moving from impression to certainty, before crying wolf, is time consuming. And result never guaranteed in advance.

**Comment by Ishinoshita** [comment]
@wonderingabout 
>i'd like @Ishinoshita to analyze a few of these games

I won't be able to retrieve these games before the latest LZ184 training data are published on https://leela.online-go.com/training/, what is not scheduled before next Monday (manually done by @gcp).

The process itself is painful. Practicaly, processing the sgf to generate an hex string key, then look for that string in hundreds of millions of text lines. I'll try for a few games.

**Comment by wonderingabout** [comment]
@Ishinoshita 

i understand, thanks again

**Comment by Ishinoshita** [comment]
@wonderingabout I had a look at some of the games you linked hereabove. They might be suspicious by the duration (I guess you picked the 2-3minutes games). But when I scroll through the sgf, I don't immedialely 'feel' they lack of randomness. Or that they have too much of it (just looks klike the usaul effect of temperature). Anyway, I have donwloaded the corresponding sgf on my disk (the https://zero.sjeng.org/view/ hyperlinks won't survived long enough) and I'll do some checks.

**Comment by wonderingabout** [comment]
@Ishinoshita 
i put all the ??? duration games

this one too for example just now : 
https://zero.sjeng.org/view/922010f3901e73436c4e77044072e7cec06b434b54d7f21a9c8396503d98dfc2?viewer=wgo

i can hardly believe our 40b would play like that even in selfplay

**Comment by Ishinoshita** [comment]
@wonderingabout Can you be more specific regarding what move(s) in particular you find susicious and for what reason, if that can be described? I'm just a 6k player, I don't necessarily see what might be obvious for you. And I'm not familiar enough with current 40b play style immediately recognize a weird style.
Just in case, if you refer to move 57 in particular, it is typically a blunder that can be pushed high enough  by Dirichlet noise in the prior policy, to be then picked by temperature.

![image](https://user-images.githubusercontent.com/37498331/47882045-6dfaa100-de28-11e8-8bbc-47fe7632cd70.png)

**Comment by wonderingabout** [comment]
@Ishinoshita 

i'm not much stronger than you myself, 1k-1d
it's just that leela zero would as far as i know almost never choose a 3-3 gote joseki

in this game, among others, moves 18 and 26 seem strange to me

**Comment by Glrr** [comment]
Nothing suspicious here. This joseki is becoming the new standard joseki of LZ after a 3-3 invasion.

**Comment by wonderingabout** [comment]
@Glrr

i hope you are right and this is not another (or the same) malicious user

**Comment by Ishinoshita** [comment]
@wonderingabout Regarding the game you just linked, I note that that game was played by LZ184 (hash  2da87ea8). It may have started 3 days ago, when LZ184 was the best network, but finished and uploaded only today. BTW, that may just be the reason for the "???" duration (devs may tell).

![image](https://user-images.githubusercontent.com/37498331/47956705-0fa8fc00-dfa9-11e8-87f2-ae0cd5e3716f.png)

Regarding the playing style, I'm no expert, see @Glrr comment.

And regarding the weird center move, nothing shocking, that keeps happening in very genuine self-play games, by the powerful combination of Dirichlet noise and temperature. Which effect is often underestimated. This kind of continuous surprise while watching LZ selfplay games on sjeng.org was the main motivation that drove me write my little script `train2sgf`. To be able to see behind the scene.

Now, with the moves on one side and the search policy values on the other side, I think I truly appreciate the real effect of LZ self-play games randomness. Sometimes, weird moves are in the top10, obviously pushed there by the Dirichlet noise (25% weight vs 75% for raw policy). Sometimes weird moves are picked outside the top10,  with very low policy and high rank in the search (a little bit of raw policy or a little bit of noise, enough to get at least one or a few visits; then let the temperature enter into play ...). 

As an example, please consider center move 41 of this (trusted ;-) game supplied to me by @tterava: [chunk_27_game_1.zip](https://github.com/gcp/leela-zero/files/2545311/chunk_27_game_1.zip)

![image](https://user-images.githubusercontent.com/37498331/47956965-ff475000-dfad-11e8-8477-da7ddb5d873e.png)

**Comment by Ishinoshita** [comment]
@wonderingabout I retrieved one of your game ('client1'):
[1a5b05a2f131aea3dfcfaeb0b4121b308e9815e01e4607da000169e3f7eb26bc.zip](https://github.com/gcp/leela-zero/files/2551797/1a5b05a2f131aea3dfcfaeb0b4121b308e9815e01e4607da000169e3f7eb26bc.zip)

I don't see from the training data why it would be obviously wrong/fake. See both original sgf and reconstructed one.

**Comment by wonderingabout** [comment]
@Ishinoshita 

thanks for checking

good news to hear that client 1 was not fake
how about clients 73 and 23 ? hopefully they wont be fake too

about my last link, yes indeed it is lz184, i carelessly assumed they were played today as they were still visible in self-play games link
however, i'm quite sure i definitely saw the same pattern (3-4 + 6-4 followed by the exact same center move)
i understand that this move can be any randomly generated move, but if my memory doesnt fail me it was always exactly the same after this opening, in the ??? games i linked yesterday :
https://zero.sjeng.org/view/4093528b3d08c45d88a8b51cabbb40f1b005a1e6a06f14b76105ccc1161d7f29?viewer=wgo

This is first game of client 23 that i linked a few days ago : 
https://zero.sjeng.org/view/4a088239e271f4d4554b05e5a43b15bc5f4fe2df23ee868aadb5856968d6f59e?viewer=wgo

and for some reason, today again, just now, i look at self-play duration games, and the only game i see with a ??? has the exact same opening..
https://zero.sjeng.org/view/de4a944ea02797b75388f4aa8459bf04d9caa79d2d0dbc9dbc1dd80119985f1e?viewer=wgo

looking at client 73 now, this game shows the same pattern again, that i sent a few days ago : 
https://zero.sjeng.org/view/494cdfe7f2972b944430fee2259f14b34e7d6d9c4ba014c4cd9390a8a39fc937?viewer=wgo

i also saw this opening with a much higher percentage in the other ??? games i saw from day to day, but i didnt save the links
i understand that these are legitimate openings and known josekis, but the percentage of these as compared to other clients is higher (while i was looking at lz 180+ networks, the opening q4 d16 q16 d4 would easily be >80% of all games

i'm just being careful with these ???, and again i hope to be proven wrong here
thanks again for your effort

**Comment by Ishinoshita** [comment]
@wonderingabout
(1) Retrieving this single game took a lot of time (downloading then unzipping Go of training data, scanning through the 3483 chunks (the game was in chunk 3479!)), I won't do it again. But I can document the method that @alreadydone gave me, along with the use of my `train2sgf` python script, so that anybody willing to do that can. 

(2) A conclusion can reached **only** if the data are *obviously fake* in some way. And it is not possible to conclude that data are *authentic*, IMHO.

**Comment by wonderingabout** [comment]
@Ishinoshita 
i totally understand how much time, energy, and motivation it takes

that's why i suggested to implement a bot that does quick sanity checks on all submitted self play games before validating them
easier said than done though, but we can't rule out the possibility of malicious pollution happening right now or again in the future while we are not aware of it

**Comment by wonderingabout** [comment]
another easy fix may be to reject all ??? games from database (as they are few, we will not lose much anyways)

**Comment by wonderingabout** [comment]
@Ishinoshita 

one other interesting thing
just now again i can see 3 ??? games on self-play games, by 3 different clients

**but !
only one out of 3 has the 60 minutes**, and this is precisely this one that i find the most suspicious
it seems not to have any randomness at all 

by client 82 : 

https://zero.sjeng.org/view/bd5269f76918948f73aa52179cd09d7c6fc4f2cbd89650715940b204370a0962?viewer=wgo

![today again](https://user-images.githubusercontent.com/38690718/48069722-6c3d2e80-e1d6-11e8-9185-84e8038ae05e.PNG)


the other 2 dont have the 60 minutes time per side : 

client 60 : 

https://zero.sjeng.org/view/08ef656ada90fd9a97211fece9cdd786356783d8608d3c87374d6c39b01f1a7b?viewer=wgo

client 57 : 

https://zero.sjeng.org/view/08ef656ada90fd9a97211fece9cdd786356783d8608d3c87374d6c39b01f1a7b?viewer=wgo

**Comment by Ishinoshita** [comment]
@wonderingabout You should asked devs if it is normal for a self-play game to have a 'Basic time' set (and set to 60').

This 'client 87' game is several days old... and is from the same network (LZ186) that I dowloaded/unzipped yesterday. So, I will have a look when back home ;-)

**Comment by Ishinoshita** [comment]
@wonderingabout My mistake. That game started days ago but ended only yesterday. LZ186 training data published yesterday morning don't include that game yet. Next Monday they should....

**Comment by wonderingabout** [comment]
@Ishinoshita 
if any see this, may be they can answer us what this 60 minute time is (is it the -t argument to avoid waste ?)

**Comment by alreadydone** [comment]
I think official clients can never produce games with 60-minute time setting. 60-minutes games have been discovered before and then were deleted from the training database IIRC.

**Comment by wonderingabout** [comment]
@alreadydone 

i see

is there no way to automatically exclude from training all games with ??? time ?

**Comment by alreadydone** [comment]
Games with ??? time has a legitimate cause and it may not be wise to exclude all of them. See https://github.com/gcp/leela-zero/issues/1466.

**Comment by wind68** [comment]
![image](https://user-images.githubusercontent.com/41324153/48453445-67880400-e7ee-11e8-9518-92933516687d.png)

**Comment by wind68** [comment]
someone upload games with special network....

**Comment by roy7** [comment]
It seems all but 2 of the ones with ??? in the time were uploads of self plays from 5 block networks. How strange. 3 different clients.

**Comment by wonderingabout** [comment]
@roy7 @alreadydone 

again, i think excluding all ??? games from training database seems like a safe and hassle free fix
these games are less than 1% of all games anyways

**Comment by wonderingabout** [comment]
https://github.com/gcp/leela-zero/issues/1939#issuecomment-440958165
