### ISSUE TITLE
Failed to find a working configuration

### ISSUE THREAD

**Issue by avdonin** [gcp/leela-zero#1958]
The program has been successfully compiled under Linux Fedora 28. 

`$src/leelaz --weights best-network`

The program has returned this error:
```
Failed to find a working configuration.
Check your OpenCL drivers.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Tuner failed to find working configuration.
Aborted (core dumped)
```

**Comment by ihavnoid** [comment]
What's your GPU?  Can you dump the full log?

**Comment by avdonin** [comment]
> What's your GPU? Can you dump the full log?

```
       description: VGA compatible controller
       product: 2nd Generation Core Processor Family Integrated Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:28 memory:e1400000-e17fffff memory:d0000000-dfffffff ioport:4000(size=64) memory:c0000-dffff
```

`Using 2 thread(s).
RNG seed: 11240150548186357303
Detecting residual layers...v1...256 channels...40 blocks.
Initializing OpenCL.
Detected 3 OpenCL platforms.
Platform version: OpenCL 1.2 pocl 1.1 RelWithDebInfo, LLVM 6.0.1, SPIR, SLEEF, DISTRO, POCL_DEBUG
Platform profile: FULL_PROFILE
Platform name:    Portable Computing Language
Platform vendor:  The pocl project
Device ID:     0
Device name:   pthread-Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
Device type:   CPU
Device vendor: GenuineIntel
Device driver: 1.1
Device speed:  3200 MHz
Device cores:  4 CU
Device score:  512
Platform version: OpenCL 2.0 beignet 1.3
Platform profile: FULL_PROFILE
Platform name:    Intel Gen OCL Driver
Platform vendor:  Intel
Error getting device(s): clGetDeviceIDs: -1
Platform version: OpenCL 1.1 Mesa 18.0.5
Platform profile: FULL_PROFILE
Platform name:    Clover
Platform vendor:  Mesa
Error getting device(s): clGetDeviceIDs: -1
Selected platform: Portable Computing Language
Selected device: pthread-Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
with OpenCL 1.2 capability.

Started OpenCL SGEMM tuner.
Will try 578 valid configurations.
1 error generated.
...numerous times...
1 error generated.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Tuner failed to find working configuration.
Aborted (core dumped)
`

**Comment by Hersmunch** [comment]
@TableCarpet that sounds like a different issue to the topic of this ticket. I suggest you raise a separate one with full details of the command line and weights used as well as the full log that gets printed etc.

**Comment by gcp** [comment]
Selected platform: Portable Computing Language
Selected device: pthread-Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz

You don't have any drivers for your GPU, so it's falling back to using OpenCL on the CPU, which is a very very very bad idea as it's much slower than using the CPU directly.

Also, the OpenCL "driver" for your CPU doesn't even work.
