### ISSUE TITLE
What's the meaning of 'Client' on http://zero.sjeng.org/self-plays ?

### ISSUE THREAD

**Issue by Ishinoshita** [gcp/leela-zero#1962]
I was checking for surprinsingly short self-play games (< 1 minute), as pointed [here](https://github.com/gcp/leela-zero/issues/1957) by @wonderingabout, and I took this snapshot, today 27-Oct-2018 at ~15:00 UCT+2:

![screenshot_2018-10-27](https://user-images.githubusercontent.com/37498331/47605043-b9b0e300-da01-11e8-9b00-c4c0902b4c71.png)

All very short games were played by Client #56.

When I checked again ~1/2h later, one of the game (hash 87961ec..., the third on here below snapshot) was still in the last 400 games window, but had changed of 'Client' number:

![screenshot_2018-10-27 - bis](https://user-images.githubusercontent.com/37498331/47605046-ca615900-da01-11e8-9650-127ba48e751d.png)

Thus, I'm wondering what 'Client' exactly means here. Did that client logged in in a first place and recieved token #56, then disconnected and then reconnected later on, where it got token #7, token that has been freed in between ?

**Comment by roy7** [comment]
There aren't client based tokens used to track people or any way to track a specific person on web site for privacy reasons. But any time you load the page, all games from the same IP address are given a client ID # at the time the page is made so you can tell if games are from the same client (or at least, same IP address) or not. From refresh to refresh there's no correlation really between the client numbers.

**Comment by wonderingabout** [comment]
i'm still wondering if it's fine to allow this very short games
are they really not harmful ?

**Comment by roy7** [comment]
I should probably look at them sometime but I've been spending my time on other things lately. :(

**Comment by wonderingabout** [comment]
hopefully some time you can, thanks for the feedback

**Comment by Ishinoshita** [comment]
@wonderingabout I personaly concur, as I *feel* these game lack some randomness. But only looking at the training data will tell us if they are fake (but only if obviously fake).

I have dowloaded the ones you mentioned plus a bunch more collected today. Now need to wait that LZ184 be demoted and its training data be published by @gcp. Then I will try to retrieve the corresponding chunks/games. If a LZ185 show up in the week-end, that might be feasible by next Monday. Otherwise, will have to wait 10 days.  Unless @roy7 can have a look before.

**Comment by Ishinoshita** [comment]
@wonderingabout 
Someone (@gcp ?, @roy7?) uploaded a preliminary portion of LZ184 (current best network) training data. I picked one of 'your' short game sgf, did a dump_supervised command on it (trick suggested by @alreadydone) to generate endgame position hex string representation. But I was able to locate this string among the available training chunks. Maybe these chunks do not contain Oct. 25th. self-play games 'your' game belongs to. I'll retry later on, when new LZ184 data will be released.

**Comment by wonderingabout** [comment]
@Ishinoshita 

when you do, can you also please check these 3 games ?

https://zero.sjeng.org/view/6145dd23f1a3873d14051de1cd31cc09294dd833e3c1500fc8a3bb28878d11bb?viewer=wgo
https://zero.sjeng.org/view/a79fad8303f93ac6ba63e28944ff4455d61706b182e76fc255e900363a1ed67a?viewer=wgo
https://zero.sjeng.org/view/fba01f4e001f1302e4cadc15acb7ce8986315d9efdb9585ef2094e74b767a5a9?viewer=wgo

thanks

**Comment by kwccoin** [comment]
Should have voluntary client token so help on this case and Id contribution.

**Comment by Ishinoshita** [comment]
@wonderingabout See answer in your one issue https://github.com/gcp/leela-zero/issues/1957.

**Comment by wonderingabout** [comment]
@Ishinoshita 
can you link me your answer please, i cant find it in the topic you mentionned
thanks

**Comment by Ishinoshita** [comment]
@wonderingabout I only retrieved two of your games. Then, found a pattern in their data that led me to discover an elephant in the room (240 such games/3200, https://github.com/gcp/leela-zero/issues/1957#issuecomment-434869061). That's why I didn't care to 'reversed' more of your 'ridiculously short games'. It was pointless, as I had discover a whole herd.

Such short games (<1 minute) have disappeared from sjeng.org page (does our guy read github?, most probably...). I have still seen such fake games in LZ184 chunks 25xx, but in much more proportion (1.3%, down from 7.5% on 07xx). There are still some short games (<3 minutes) for which we may have doubt but have no evidence either. I'll have a look ( I saved some), but there is a 1 week+ latency to get traing data (I'm definitively always behind here...).

At the moment, I'm after yet [another herd](https://github.com/gcp/leela-zero/issues/1963#issuecomment-434998420). Hopefully not malicious.

**Comment by wonderingabout** [comment]
@Ishinoshita 
i understand, thanks again for your continued effort

i saw another ??? minutes game that have the same pattern as other ??? minutes game, non zero fuseki, probably malicious, see : 
https://github.com/gcp/leela-zero/issues/1957#issuecomment-435605736

**Comment by Ishinoshita** [comment]
Initial question answered.

Further off-topic points were also discussed [here](https://github.com/gcp/leela-zero/issues/1957#issuecomment-434852075) and answered (??? duration games are OK; but very short games were indeed fake).
