### ISSUE TITLE
web site return an unknown error

### ISSUE THREAD

**Issue by kwccoin** [gcp/leela-zero#1966]
Not sure what is going but may be just a temporary issue as the autogtp continue to run without further prompt:

`Got new job: selfplay
net: 2da87ea8da0f54e87b70159e6bb82811b61d1c31091b6e019fbe62aeaa803b9c.
Engine has started.
Infinite thinking time set.
1 (B Q4) 2 (W D16) 3 (B Q16) 4 (W S4) 5 (B M3) 6 (W Q3) 7 (B P3) 8 (W R3) 9 (B P2) 10 (W D3) 11 (B R6) 12 (W S6) 13 (B R7) 14 (W S7) 15 (B R8) 16 (W S8) 17 (B R10) 18 (W S9) 19 (B C17) 20 (W C16) 21 (B D17) 22 (W F17) 23 (B E17) 24 (W E16) 25 (B F18) 26 (W R9) 27 (B C5) 28 (W C4) 29 (B D5) 30 (W F3) 31 (B J2) 32 (W C9) 33 (B G4) 34 (W G3) 35 (B H4) 36 (W E5) 37 (B B4) 38 (W B3) 39 (B D8) 40 (W D9) 41 (B F8) 42 (W P18) 43 (B E4) 44 (W R17) 45 (B E3) 46 (W K16) 47 (B D4) 48 (W C3) 49 (B E2) 50 (W R16) 51 (B B6) 52 (W P4) 53 (B G10) 54 (W O4) 55 (B N5) 56 (W O6) 57 (B Q14) 58 (W D12) 59 (B N6) 60 (W R15) 61 (B O7) 62 (W N3) 63 (B L17) 64 (W M2) 65 (B N2) 66 (W O2) 67 (B O3) 68 (W N4) 69 (B O1) 70 (W M4) 71 (B L3) 72 (W L4) 73 (B R5) 74 (W Q9) 75 (B O5) 76 (W K3) 77 (B L2) 78 (W K2) 79 (B M1) 80 (W K6) 81 (B L7) 82 (W K7) 83 (B K8) 84 (W J8) 85 (B L6) 86 (W J4) 87 (B H6) 88 (W J6) 89 (B H7) 90 (W L8) 91 (B K9) 92 (W resign) Game has ended.
Score: B+Resign 
Winner: black
Uploading game: fa03704cf843432b8e90162c97f26165.sgf for network 2da87ea8da0f54e87b70159e6bb82811b61d1c31091b6e019fbe62aeaa803b9c
<!DOCTYPE html>

 <html class="no-js" lang="en-US"> 
<head>

<title>zero.sjeng.org | 520: Web server is returning an unknown error</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>

</head>
<body>
<div id="cf-wrapper">

    

    <div id="cf-error-details" class="cf-error-details-wrapper">
        <div class="cf-wrapper cf-error-overview">
            <h1>
              
              <span class="cf-error-type">Error</span>
              <span class="cf-error-code">520</span>
              <small class="heading-ray-id">Ray ID: 471d2cf420c684c6 &bull; 2018-10-30 10:26:12 UTC</small>
            </h1>
            <h2 class="cf-subheadline">Web server is returning an unknown error</h2>
        </div>
        
        <div class="cf-section cf-highlight cf-status-display">
            <div class="cf-wrapper">
                <div class="cf-columns cols-3">
                  
<div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status ">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-browser"></i>
    <i class="cf-icon-status cf-icon-ok"></i>
  </div>
  <span class="cf-status-desc">You</span>
  <h3 class="cf-status-name">Browser</h3>
  <span class="cf-status-label">Working</span>
</div>

<div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status ">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-cloud"></i>
    <i class="cf-icon-status cf-icon-ok"></i>
  </div>
  <span class="cf-status-desc">Hong Kong</span>
  <h3 class="cf-status-name">Cloudflare</h3>
  <span class="cf-status-label">Working</span>
</div>

<div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-server"></i>
    <i class="cf-icon-status cf-icon-error"></i>
  </div>
  <span class="cf-status-desc">zero.sjeng.org</span>
  <h3 class="cf-status-name">Host</h3>
  <span class="cf-status-label">Error</span>
</div>

                </div>
              
            </div>
        </div>

        <div class="cf-section cf-wrapper">
            <div class="cf-columns two">
                <div class="cf-column">
                    <h2>What happened?</h2>
                    <p>There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>
                </div>
              
                <div class="cf-column">
                    <h2>What can I do?</h2>
                          <h5>If you are a visitor of this website:</h5>
      <p>Please try again in a few minutes.</p>

      <h5>If you are the owner of this website:</h5>
      <p><span>There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team.  Please include the Ray ID (which is at the bottom of this error page).</span> <a href="https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520">Additional troubleshooting resources</a>.</p>
                </div>
            </div>
              
        </div>

        <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>471d2cf420c684c6</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Your IP</span>: 138.19.78.169</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div>

    </div>
</div>
</body>
</html>
14 game(s) (14 self played and 0 matches) played in 255 minutes = 1094 seconds/game, 7185 ms/move, last game took 698 seconds.
{
    "cmd": "selfplay",
    "hash": "2da87ea8da0f54e87b70159e6bb82811b61d1c31091b6e019fbe62aeaa803b9c",
    "hash_gzip_hash": "11f2fdf61a20b3b52e7b4052e2819f2757fc514f45e9ab0f3e43bb69856b65e0",
    "minimum_autogtp_version": "16",
    "minimum_leelaz_version": "0.15",
    "options": {
        "noise": "true",
        "playouts": "0",
        "randomcnt": "999",
        "resignation_percent": "5",
        "visits": "1601"
    },
    "options_hash": "b37dca",
    "random_seed": "3305858645922165188",
    "required_client_version": "16"
}

Got new job: selfplaynet: 2da87ea8da0f54e87b70159e6bb82811b61d1c31091b6e019fbe62aeaa803b9c.
Engine has started.
Infinite thinking time set.
1 (B D4) 2 (W Q16) 3 (B R17) 4 (W R16) 5 (B Q17) 6 (W P16) 7 (B P17) 8 (W O16) 9 (B N18) 10 (W D16) 11 (B Q4) 12 (W C6) 13 (B R11) 14 (W C3) 15 (B C4) 16 (W D3) 17 (B E4) 18 (W B4) 19 (B B5) 20 (W B3) 21 (B C8) 22 (W C5) 23 (B C17) 24 (W D17) 25 (B C16) 26 (W C15) 27 (B B15) 28 (W B14) 29 (B C14) 30 (W D15) 31 (B B13) 32 (W B16) 33 (B A14) 34 (W B17) 35 (B C18) 36 (W B18) 37 (B P11) 38 (W O3) 39 (B O4) 40 (W P3) 41 (B P4) 42 (W Q3) 43 (B R3) 44 (W N4) 45 (B R2) 46 (W M3) 47 (B N2) 48 (W N3) 49 (B K13) 50 (W N6) 51 (B M16) 52 (W S17) 53 (B S18) 54 (W S15) 55 (B T17) 56 (W S5) 57 (B R5) 58 (W S4) 59 (B R4) 60 (W L4) 61 (B R7) 62 (W Q12) 63 (B R12) 64 (W E6) 65 (B B6) 66 (W B7) 67 (B C7) 68 (W A6) 69 (B Q13) 70 (W P13) 71 (B O13) 72 (W T16) 73 (B S16) 74 (W Q14) 75 (B R13) 76 (W S17) 77 (B T18) 78 (W P12) 79 (B O12) 80 (W Q11) 81 (B Q10) 82 (W P14) 83 (B P10) 84 (W M15) 85 (B N8) 86 (W Q6) 87 (B P6) 88 (W H5) 89 (B L15) 90 (W L12) 91 (B N15) 92 (W M14) 93 (B N16) 94 (W R14) 95 (B S13) 96 (W N14) 97 (B L13) 98 (W O15) 99 (B Q15) 100 (W S14) 101 (B T14) 102 (W resign) Game has ended.
Score: B+Resign 
Winner: black
Uploading game: f0ea689151ca42b68caf9a686f1e5940.sgf for network 2da87ea8da0f54e87b70159e6bb82811b61d1c31091b6e019fbe62aeaa803b9c
Game data 776c92749781b8d91763a254da6e775b30e33c1c08c38595bcbbf88142b5b4c1 stored in database
15 game(s) (15 self played and 0 matches) played in 264 minutes = 1059 seconds/game, 7110 ms/move, last game took 560 seconds.
{
    "cmd": "selfplay",`

**Comment by gcp** [comment]
WFM.
