### ISSUE TITLE
Increase the visit of self-play?

### ISSUE THREAD

**Issue by jamesho8743** [gcp/leela-zero#1969]
The current 40B is progressing slowly.
As LZ getting stronger, the quality of self-play games seems not enough to bootstrap himself.
Should we consider increasing visits of self-play games?
Anyway the higher quality the self-play games, the better chance our network get promoted. is that right?

**Comment by gcp** [comment]
Increasing the visits means less new games from stronger networks, which means even slower progress (maybe). There are absolutely no plans to change this.

**Comment by Hersmunch** [comment]
Maybe #1416 is of interest
