### ISSUE TITLE
How to compile leelaz in google colab?

### ISSUE THREAD

**Issue by wind68** [gcp/leela-zero#1971]

**Comment by wind68** [comment]
what is wrong about below?
Network.cpp:34:10: fatal error: Eigen/Dense: No such file or directory
 #include <Eigen/Dense>

**Comment by gcp** [comment]
See the README. You're missing:

``
submodule update --init --recursive
``

**Comment by wonderingabout** [comment]
@wind68 
leela-zero now uses eigen with cmake, not qmake with qt5 anymore

i wrote more intuitive instructions here if you want : 
https://github.com/wonderingabout/leela-zero#compiling-autogtp-andor-leelaz
