### ISSUE TITLE
somebody tested that clinet 0.16 run a match at TIME PARITY is much better than 0.15

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1982]
https://lifein19x19.com/viewtopic.php?f=18&t=15718&sid=fb37d44f3aa1a2a3ea70b983c62be586&start=180
If you run a match at TIME PARITY, I bet you'll see a big difference !

"True" time parity test - v16 vs v15 (3s per move, 2x1080ti, 184):
Code:
v15 : -t 12 --gpu 0 --gpu 1 --noponder
v16 : -t 12 --gpu 0 --gpu 1 --noponder --precision half

71 : 29

**Comment by gcp** [comment]
That's expected given the large amount of speedups, especially with fp16 support.
