### ISSUE TITLE
Solved

### ISSUE THREAD

**Issue by sysnotdown** [gcp/leela-zero#1984]
just my mistake, downloaded a wrong version.

**Comment by sysnotdown** [comment]
> 
> 
> What is the exact console output when you run leela zero?

./leelaz --benchmark -w ..... don't have any outputs.

**Comment by sysnotdown** [comment]
I guess I have found something.  lz0.15 don't have opencl.dll but lz0.16 have. this file should used for GPU, but I downloaded cpu version, the opencl.dll should not be called in this version. but lz0.16 calls it, so it crash. this machine don't have GPU.

**Comment by wonsiks** [comment]
@sysnotdown I've had the same problem and I solved it with --cpu-only option while using gpu version.
Anyway 0.16 has problem when using opencl of intel cpu embeded gpu.

**Comment by sysnotdown** [comment]
sorry! I made a mistake, I downloaded x64 version , not cpu-only version.

**Comment by anonymousAwesome** [comment]
You can close out the issues you created.

**Comment by sysnotdown** [comment]
> You can close out the issues you created.

how to close it? thanks.
