### ISSUE TITLE
40B Net seems over-sized

### ISSUE THREAD

**Issue by wpstmxhs** [gcp/leela-zero#1988]
I think that 40b net is not playing well although it's 40 blocked net.

How about trying Knowledge Distillation approach to reduce net size to smaller net, say, 15b, 20b?

Actually, in the real games, ELF v1 is still way stronger than current best network. I think It means 20 block is enough for LZ.

**Comment by Friday9i** [comment]
LZ is now much better than ELFv1 at equal visits... And it's improving much faster than a 20b net would be
True, Elf is still better at time parity but that shouldn't last long, be patient!

**Comment by wpstmxhs** [comment]
No. I think ELF is still stronger even on equal-visited condition.

ELF v1 on the half performanced computer always beats LZ 40b. It rarely loses.
So IMHO they were playing on the same playouts.

**Comment by wonderingabout** [comment]
@wpstmxhs 

- elf v1 is a close to max potential, well refined 20 blocks network
- leela zero 40 blocks is a young and promising 40 block networks, with a much bigger potential than elf v1 20 blocks
- alphago zero is a close to max potential 40 blocks, very very strong, and if we do it well, leela zero should ultimately reach the same strength (after a very long time)

i think this answers your question

for max strength, there is no reason to prefer 20 blocks over 40 blocks except reasons like low hardware (40 blocks can store much more knowledge than 20 blocks), etc
and if we had enough power, a 80 blocks network would be much stronger than a 40 blocks network too

**Comment by l1t1** [comment]
@wpstmxhs could you attach the LZ code  you changed

**Comment by TFiFiE** [comment]
I, for one, am curious to know what the performance of a 20-block trained on 40-block games would be and how it would scale.

**Comment by sysnotdown** [comment]
I think 60-block maybe better, or 80-block, 100-block. the more the better.

**Comment by wpstmxhs** [comment]
@wonderingabout 

In the theory, I agree all your answers. We should go with 40 blocks eventually for the max potential strength.

But I think we can go with smaller net like 15b or 20b for a while, with process of repeating 20b-40b switch, and when 20b net fails to copy 40b net knowledges, then go consistently with larger net.

Switching to the 20b net makes faster games twice.

**Comment by wpstmxhs** [comment]
@l1t1 

Not a big deal. I just changed the parameter **cfg_puct**.

**Comment by wpstmxhs** [comment]
@MartinDevelopment 

I think you referred the Leela Zero website's match game result. but that games were played on 3200 visits as I know.

I don't think that it's a true strength.

**Comment by MartinDevelopment** [comment]
@wpstmxhs Than what is a "true strenght". If we were to go with a smaller network we would be creating weaker games which will result in slower training. I believe that quality is more important than quantity when you are working with a set amount of games in your training window.

**Comment by wpstmxhs** [comment]
@MartinDevelopment But with knowledge distillation approach, is it possible to copy larger network with the smaller size?

Anyway, As far as I know, currently almost cheaters that is using 40b block lost by ELF v1 with tuned parameters. I test my AI for cheaters.

**Comment by MartinDevelopment** [comment]
@wpstmxhs Which cheaters are you talking about? Was everyone using the same hardware, settings, etc.? Where is that data, and is that data statistically significant? Nobody is going to make any changes without knowing all these things.

**Comment by Marcin1960** [comment]
@wonderingabout 

>    elf v1 is a close to max potential, well refined 20 blocks network

How do you know? Where is the evidence?

> 80 blocks network would be much stronger than a 40 blocks network too

Hmm ...

**Comment by arondes** [comment]
From my own experience ELF white is stronger than 40B black. But 40B white is stronger than ELF black. If the game is really long, usually ELF can win.

**Comment by Friday9i** [comment]
LZ183 won 56% against Elfv1 (ie 45 more Elo points) and since that we had 3 new nets and 116 additional selfplay Elo points, which generally means around 50 "true" Elo points: all in all, LZ186 should be around 100 Elo points stronger than ELFv1 (with 1600 visits for both nets), which should be around 62% winrate for LZ186 vs Elfv1

**Comment by Splee99** [comment]
Elf can't deal with ladders. That's already an indication of weakness of the knowledge structure. I don't think training can overcome everything.

**Comment by wonderingabout** [comment]
@Marcin1960 
i dont "know", it is just a statement that elf v1 is much more trained than our leela zero 20 blocks was
it may be stronger with a lot more training, but that wouldnt be efficient

@wpstmxhs 
i understand your point, but this would be a waste of energy and time
i think one should decide a network size, and train it until it reaches its limit or is not efficient to improve, then go to a bigger size, etc
your "knowledge distillation" may produce a stronger 20 blocks, but it will always be weaker than a strong 40 blocks, which will also be always weaker than a 80 blocks, etc

**Comment by l1t1** [comment]
please test a match of 187 vs elfv1

**Comment by gcp** [comment]
>I think ELF is still stronger even on equal-visited condition.

We already determined this is not true, so why do you say "I think"? We already know it is not true.
