### ISSUE TITLE
Error in convolve3: clSetKernelArg: -38  for Leela Zero 0.16 + AutoGTP v17

### ISSUE THREAD

**Issue by jiangwuyou** [gcp/leela-zero#1994]
Leela Zero 0.16 + AutoGTP v17. will throw 
Error in convolve3: clSetKernelArg: -38 

But Leela Zero 0.15 + AutoGTP v16 work normal.

Using 2 thread(s). 
RNG seed: 9200033520529232333 
BLAS Core: Atom Detecting residual layers
...v2...224 channels...20 blocks. 
Initializing OpenCL (autodetecting precision). 
Detected 1 OpenCL platforms. 
Platform version: OpenCL 1.1 
 Platform profile: FULL_PROFILE 
Platform name:    Intel(R) OpenCL 
Platform vendor:  Intel(R) Corporation 
Device ID:     0 
Device name:   Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz 
Device type:   CPU Device vendor: Intel(R) Corporation 
Device driver: 1.1 
Device speed:  3100 MHz 
Device cores:  4 CU 
Device score:  511 
Selected platform: Intel(R) OpenCL 
Selected device: Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz with OpenCL 1.1 capability. 
Half precision compute support: No. 
Detected 1 OpenCL platforms. 
Platform version: OpenCL 1.1  
Platform profile: FULL_PROFILE 
Platform name:    Intel(R) OpenCL 
Platform vendor:  Intel(R) Corporation 
Device ID:     0 
Device name:   Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz 
Device type:   CPU 
Device vendor: Intel(R) Corporation 
Device driver: 1.1
Device speed:  3100 MHz 
Device cores:  4 CU 
Device score:  511 
Selected platform: Intel(R) OpenCL 
Selected device: Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz with OpenCL 1.1 capability. 
Half precision compute support: No.  
Started OpenCL SGEMM tuner. 
Will try 290 valid configurations. 
(1/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 52.4057 ms (1.7 GFLOPS) 
(4/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 49.2760 ms (1.8 GFLOPS)
 (5/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 44.9057 ms (2.0 GFLOPS)
 (11/290) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 44.8587 ms (2.0 GFLOPS)
 (46/290) KWG=16 KWI=2 MDIMA=16 MDIMC=16 MWG=32 NDIMB=16 NDIMC=16 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 41.3663 ms (2.2 GFLOPS) 
(71/290) KWG=32 KWI=8 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 41.2509 ms (2.2 GFLOPS) 
(107/290) KWG=16 KWI=8 MDIMA=16 MDIMC=16 MWG=32 NDIMB=16 NDIMC=16 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 38.6415 ms (2.3 GFLOPS)
 (111/290) KWG=32 KWI=8 MDIMA=16 MDIMC=16 MWG=32 NDIMB=16 NDIMC=16 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 38.0032 ms (2.4 GFLOPS) 
(123/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 32.3776 ms (2.8 GFLOPS) (125/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 31.7605 ms (2.8 GFLOPS) 
(129/290) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 30.9762 ms (2.9 GFLOPS) 
(145/290) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=16 NDIMC=16 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 30.3055 ms (3.0 GFLOPS) 
(162/290) KWG=32 KWI=8 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 29.9280 ms (3.0 GFLOPS) 
(238/290) KWG=32 KWI=8 MDIMA=16 MDIMC=16 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=4 29.4418 ms (3.1 GFLOPS) 
(255/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=4 25.4864 ms (3.5 GFLOPS) 
(259/290) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=4 24.2053 ms (3.7 GFLOPS) 
(277/290) KWG=32 KWI=8 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=4 23.7363 ms (3.8 GFLOPS) 
Wavefront/Warp 
size: 64 Max workgroup 
size: 1024 Max workgroup 
dimensions: 1024 1024 1024  
Error in convolve3: clSetKernelArg: -38  
Started OpenCL SGEMM tuner. 
Will try 290 valid configurations.

**Comment by gcp** [comment]
>Selected device: Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz with OpenCL 1.1 capability.

Do not use OpenCL on the CPU.

Not only is it slow, your drivers are completely broken for it.

**Comment by gcp** [comment]
I wonder if we should just refuse to run with OpenCL when we detect that we're running on a CPU...

**Comment by gcp** [comment]
I implemented this, i.e. if Leela now detects that you are using the OpenCL version but don't have a real GPU or are missing the drivers for it, it will refuse to run. 

This can still be overruled by specifying the OpenCL device explicitly.

The recommended fix is to install any missing drivers, or use ```--cpu--only```.

**Comment by jiangwuyou** [comment]
Thanks.

**Comment by wonderingabout** [comment]
good initiative, will probably avoid many future issues
