### ISSUE TITLE
Failed to complete "Will try 290 valid configurations." for Leela Zero 0.16

### ISSUE THREAD

**Issue by jiangwuyou** [gcp/leela-zero#1995]
It will be halted to show more information after (n/290), and n is a value between 8 and 30.

Using 2 thread(s).
RNG seed: 2684870374544402606
BLAS Core: Haswell
Detecting residual layers...v2...224 channels...20 blocks.
Initializing OpenCL (autodetecting precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 2.1 
Platform profile: FULL_PROFILE
Platform name:    Intel(R) OpenCL
Platform vendor:  Intel(R) Corporation
Device ID:     0
Device name:   Intel(R) UHD Graphics 620
Device type:   GPU
Device vendor: Intel(R) Corporation
Device driver: 23.20.16.4973
Device speed:  1150 MHz
Device cores:  24 CU
Device score:  621
Device ID:     1
Device name:   Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
Device type:   CPU
Device vendor: Intel(R) Corporation
Device driver: 7.6.0.611
Device speed:  1800 MHz
Device cores:  8 CU
Device score:  521
Selected platform: Intel(R) OpenCL
Selected device: Intel(R) UHD Graphics 620
with OpenCL 2.1 capability.
Half precision compute support: Yes.
OpenCL: using fp16/half compute support.
Started OpenCL SGEMM tuner.
Will try 290 valid configurations.
(1/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 1.0950 ms (82.5 GFLOPS)
(5/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.5689 ms (158.7 GFLOPS)
(14/290) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.5669 ms (159.3 GFLOPS)

**Comment by gcp** [comment]
Broken GPU drivers, switch to the CPU version.

**Comment by gcp** [comment]
Or maybe your GPU is just very slow?

It will only print something when it finds a new best. On a slow card, completing the tuning will take a while.

**Comment by jiangwuyou** [comment]
Thanks. Because the older 0.15 failed too. It should be a broken GPU driver, and need to reinstall.
