### ISSUE TITLE
LZ 0.16  doesn't work (because of the i9 I think)

### ISSUE THREAD

**Issue by Vargooo** [gcp/leela-zero#1996]
LZ0.16 works with my laptop (GTX 965), my desktop (gtx 1080) but NOT with my gaming PC (win 10, i9-7920x, 2x1080Ti)
It always ends up in a blue screen and  "WHEA_UNCORRECTABLE_ERROR"  after 2-60 seconds, randomly, it seems.
I've tried with Sabaki (last version, and the one before) and with gogui-twogtp (1.4.9 and 1.4.10)

At life in 19x19, there's someone who has a PC with : Win10, 2x1080Ti , Xeon, and it works. That's why I think it's maybe something related to my i9.

Any idea ?

**Comment by l1t1** [comment]
try linux

**Comment by gcp** [comment]
>It always ends up in a blue screen

Reduce your overclock, check your cooling and temperatures.

Your computer is crashing because it's not stable under heavy load.

**Comment by Vargooo** [comment]
OK , thx anyway !
