### ISSUE TITLE
Compiling under Linux Mint 18.2 Sonya by changing Makefile

### ISSUE THREAD

**Issue by emdio** [gcp/leela-zero#2]
I was able to compile leelaz under Linux Mint 18.2 Sonya.

Other than installing dependencies I had to make these changes in the Makefile (I've commented the original line and added the one that worked on my system):
#CXXFLAGS += -I/opt/OpenBLAS/include
CXXFLAGS += -I/usr/include/openblas/
#LDFLAGS += -L/opt/OpenBLAS/lib
LDFLAGS += -L/usr/lib

**Comment by gcp** [comment]
Fixed by 5eba666a7d39a3c0c774e07b120c7c0670c8a396.

**Comment by emdio** [comment]
This fix doesn't seem to work on my computer:

$ make
make CC=gcc CXX=g++ \
	CXXFLAGS='-I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG'  \
	LDFLAGS=' -flto -g' \
	leelaz
make[1]: Entering directory '/home/milio/soft/git/leela-zero/src'
g++ -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Network.o Network.cpp
Network.cpp:41:10: fatal error: openblas/cblas.h: No such file or directory
 #include <openblas/cblas.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:51: recipe for target 'Network.o' failed
make[1]: *** [Network.o] Error 1
make[1]: Leaving directory '/home/milio/soft/git/leela-zero/src'
Makefile:2: recipe for target 'default' failed
make: *** [default] Error 2
milio@xubuntuco:~/soft/git/leela-zero/src$

**Comment by gcp** [comment]
What does "gcc -xc++ -E -v -" report?

**Comment by emdio** [comment]
$ gcc -xc++ -E -v -
Using built-in specs.
COLLECT_GCC=gcc
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.2.0-8ubuntu3' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3) 
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/7/cc1plus -E -quiet -v -imultiarch x86_64-linux-gnu -D_GNU_SOURCE - -mtune=generic -march=x86-64 -fstack-protector-strong -Wformat -Wformat-security
ignoring duplicate directory "/usr/include/x86_64-linux-gnu/c++/7"
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/7/../../../../x86_64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/c++/7
 /usr/include/x86_64-linux-gnu/c++/7
 /usr/include/c++/7/backward
 /usr/lib/gcc/x86_64-linux-gnu/7/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.

**Comment by gcp** [comment]
Ok that looks as expected.

/usr/include is in the path. We look for openblas/cblas.h, so that should find /usr/include/openblas/cblas.h. (Does that file exist?)

I'm a bit baffled here. Can you try a make clean, if you haven't already?

**Comment by emdio** [comment]
make clean && make just gives the same result.

cblas.h exists, and is placed here:

$ locate cblas.h
/etc/alternatives/cblas.h-x86_64-linux-gnu
/usr/include/x86_64-linux-gnu/cblas.h

**Comment by gcp** [comment]
Ok, I understand now. Previously, the 

CXXFLAGS += -I/usr/include/openblas/

line had no effect, but the cblas.h was picked up because it's in the default include path. I'll try a new fix.

**Comment by gcp** [comment]
I pushed b5405f4bc63a76dd4b69ff9de4e07c9dc99be6b3 which should make this work better.

**Comment by emdio** [comment]
That worked perfectly!
