### ISSUE TITLE
Where is leelaz_opencl_tuning in 0.16 linux version?

### ISSUE THREAD

**Issue by balabi0github** [gcp/leela-zero#2000]
Dear developers,

In 0.15 version, both windows and linux version will generate leelaz_opencl_tuning file. But for 0.16, I found only windows version generate leelaz_opencl_tuning. There is no leelaz_opencl_tuning generated for linux version? Without leelaz_opencl_tuning, how could leelaz know previous tuning result?

best regards

**Comment by gcp** [comment]
https://github.com/gcp/leela-zero/blob/6d1649774ac8a2524185d02b9c5aca2d4f3c30e1/src/Utils.cpp#L193

~/.local/share/leela-zero
