### ISSUE TITLE
Cannot build CPU only with #define USE_OPENCL commented out

### ISSUE THREAD

**Issue by ksafford** [gcp/leela-zero#2005]
Following the README I have commented out `#define USE_OPENCL` in the config.h file. And I have uncommented the `#define USE_BLAS`

Running `cmake ..` from leela-zero/build directory seems to work fine.

> cmake ..  
>                                                                                                                                             
> -- Boost version: 1.66.0
> -- Found the following Boost libraries:
> --   program_options
> --   filesystem
> --   system
> -- Using built-in matrix library.
> -- Configuring done
> -- Generating done
> -- Build files have been written to: path/leela-zero/build

Running `cmake --build ..` results in the following error:

> leela-zero/src/CPUPipe.cpp:28:10: fatal error: cblas.h: No such file or directory
>  #include <cblas.h>
>           ^~~~~~~~~
> compilation terminated.
> gmake[2]: *** [CMakeFiles/objs.dir/build.make:63: CMakeFiles/objs.dir/src/CPUPipe.cpp.o] Error 1
> gmake[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/objs.dir/all] Error 2
> gmake: *** [Makefile:152: all] Error 2

I do seem to have cblas.h, however:

> /usr/sbin/update-alternatives --config libblas.so.3   
>                                                                                               
> There are 2 choices for the alternative libblas.so.3 (providing /usr/lib64/libblas.so.3).
> 
>   Selection    Path                                  Priority   Status
> ------------------------------------------------------------
> * 0            /usr/lib64/blas/libblas.so.3           50        auto mode
>   1            /usr/lib64/blas/libblas.so.3           50        manual mode
>   2            /usr/lib64/libopenblas_pthreads.so.0   20        manual mode
> 
> Press <enter> to keep the current choice[*], or type selection number:

and

>locate cblas.h
>
>/usr/include/openblas/cblas.h

If I leave `#define USE_BLAS` commented out, the build throws a large number of errors, starting with:

> on_t::AUTO) {
>          ^~~~~~~~~~~~~
> /home/kevin/go-game/ai/LeelaZero/leela-zero/src/Network.cpp:383:9: note: suggested alternative: ‘select_precision’
>      if (cfg_precision == precision_t::AUTO) {

I'm on OpenSUSE Leap 15 running gcc version: gcc (SUSE Linux) 7.3.1 20180323 [gcc-7-branch revision 258812]

**Comment by alreadydone** [comment]
Dup of https://github.com/gcp/leela-zero/issues/1921, I suppose.

**Comment by ksafford** [comment]
Yes, that worked.
