### ISSUE TITLE
Need help with testing Modified FPU

### ISSUE THREAD

**Issue by petgo3** [gcp/leela-zero#2006]
I've tried out a modification in FPU reduction. After some games it seems to end up in more strength.
To have a significant result, can someone help with a bunch of selfplay games between modified version and original.

The mod was inspried by alreadydone to let lz play handicap proper 
and only modifies UCTNode::select_child:

UCTNode* UCTNode::uct_select_child(int color, bool is_root) { 
...
float pure_eval = get_raw_eval(color, 0);
    const auto numerator = std::sqrt(double(parentvisits));
    auto fpu_reduction = (is_root ? cfg_fpu_root_reduction : cfg_fpu_reduction) * std::sqrt(total_visited_policy)*pure_eval / 0.5f;
    // Estimated eval for unknown nodes = original parent NN eval - reduction
    const auto fpu_eval = pure_eval - fpu_reduction;
...
const auto puct = cfg_puct * psa * (numerator / denom) * pure_eval / 0.5f;
...

**Comment by alreadydone** [comment]
Seems it's not just FPU, puct is also changed?

**Comment by petgo3** [comment]
@alreadydone:  Right, its just a part of one of your handicap approaches. 

With this modification LZ (on GTX 1060) had won serveral games against elf (on GTX 1080Ti) on time parity, which was rarely before.

**Comment by Eddh** [comment]
Need hundred more games to be sure it's good.

**Comment by petgo3** [comment]
That is why i ask for help.

**Comment by fishcu** [comment]
Tell us what testing setup you want to have, and what tests you want to have run. Ideally with command line commands. I can help you by providing compute power.

I think it would also help if you had a branch for your changes.

**Comment by gcp** [comment]
Changed the topic to reflect that you need help, instead of claiming you found an improvement.

**Comment by jillybob** [comment]
If you give me the binary to run with instructions, I will provide compute power

**Comment by petgo3** [comment]
To have the two versions compared i tried this: 
gogui-twogtp.exe -black "C:\temp\lz\leelaz.exe --precision single -t 2 -g -w C:\temp\lz\weight --noponder -p 1600 -m 15" -white "C:\temp\pet\leelaz.exe --precision single -g -t 2 -w C:\temp\pet\weight --noponder -p 1600 -m 15" -games 200 -sgffile "C:\temp\sgf" -auto -komi 7.5

but this is taking long time on my laptop ... and then there need to be another go with changed colors ...

The one in \lz is the original lz in \pet the modified version.
Here is the modified .exe
[leelaz.zip](https://github.com/gcp/leela-zero/files/2590828/leelaz.zip)

Any help i would appreciate. Thx.

**Comment by MartinDevelopment** [comment]
Why are you adding -m 15? You don't want moves that are not optimal, according to the network, interfering with the result of the game.

**Comment by petgo3** [comment]
https://github.com/petgo3/leela-zero

**Comment by petgo3** [comment]
@MartinDevelopment : _I can see your point, but without_ m option we get a lot of identical games. Any better idea?

**Comment by alreadydone** [comment]
Maybe of help is https://github.com/gcp/leela-zero/issues/2003#issuecomment-437275025. I guess gogui sends clear_board? If we clear NNCache when clearing the board, I imagine random symmetry should be sufficient to avoid duplicates.

**Comment by fishcu** [comment]
I started the experiment with 400 games and `-alternate`. Command line options for the engine is in each case: 
```./leelaz --precision single -t 2 -g --noponder -p 1600 --randomtemp 0.5 -w best-network```

**Comment by alreadydone** [comment]
randomtemp has to be combined with -m to take effect, I think?

**Comment by fishcu** [comment]
I checked some of the generated .sgfs, and they're not identical.

**Comment by alreadydone** [comment]
https://github.com/gcp/leela-zero/blob/4fd6e694ead45b7cbb14ea76c5bdfcbfa662304b/src/UCTNodeRoot.cpp#L118-L122
I think randomtemp is not in effect (still choosing the move with the highest visits), but 1600 playouts are probably large enough for NNCache not to persist from one game's start to another game's, since NNCache is limited to 150000 entries, and 150000/1600 ~ 94.

**Comment by Splee99** [comment]
@petgo3 There seems to be some necessary changes missing to use get_raw_eval in uct_select_child. After compiled the source code in VC2017, it crashed before the first move was generated.

**Comment by alreadydone** [comment]
@Splee99 I think you do need some additional changes from https://github.com/gcp/leela-zero/pull/1435/files unless you use a single thread.

**Comment by fishcu** [comment]
The experiment is still running. I underestimated the time used: For selfplay games using autogtp, LZ can reuse the tree. This is not the case for this twogtp experiment. One game takes about 15 minutes. Currently at game 179.

**Comment by wpstmxhs** [comment]
Current running test. I stopped it now.

![matchgtp](https://user-images.githubusercontent.com/28377280/48770732-afcd8780-ed02-11e8-8124-8aec3ed2ce9c.png)

Test Condition:
- Used the most recent best LZ 40block net.
- Fought with the parameter '-w last40b.txt -g -r 25 -t 8 --gpu 0 --gpu 1 -v 12000 --noponder -m 8' on two Titan V cards.
- Each program plays black and white alternately.

Interpretation:
- Original next branch : FPU modified = 31 : 19.

**Comment by MarcelGruenauer** [comment]
> By the way, how do I get gogui-twogtp to produce better .sgf file names? It now names the games "-0.sgf", "-1.sgf", and so on. It's terrible to start file names with a dash in unix systems...

The twogtp.py from pachi has the "--sgfbase <filename>" to define a prefix; does the gogui-twogtp.py program have that as well?

**Comment by fishcu** [comment]
Thanks, I checked again and found `-sgffile prefix`, which defaults to an empty string. I will fix this with the next experiment.

BTW, any advantages of pachi's twogtp implementation over gogui's?

**Comment by Marcin1960** [comment]
@wpstmxhs 

50 matches? Not exactly conclusive.

**Comment by kuba97531** [comment]
@Marcin1960 
Actually it's quite conclusive. Assuming even players played 50 games chance that one of them scores less than 20 wins is approximately 5% so it's almost enough for SPRT rejection.

**Comment by Marcin1960** [comment]
@kuba97531

15%, not 5% Similar to get 6 from dice throw.

If it was in favor of modification certainly even more matches would not be accepted.

**Comment by Splee99** [comment]
Since alphago appeared people always talks about to run hundreds or even thousands games to be conclusive. However, I would not expect any of Chunlan cup or Samsung cup asks people to play that many games to reach the champion. For the old-fashioned go world three or five games are conclusive enough.

**Comment by MartinDevelopment** [comment]
@Splee99 We need hundreds of games, because we are trying to measure small differences in strength and to make sure that the result is as accurate as possible without using too many resources. Human competitions don't need that, since humans simply can't play that many games and they are not trying to measure small difference in strength.

**Comment by petgo3** [comment]
So far thank you all for your nice support :-)
The bad news is: This modification (as it stands) seems not better than the original one.
The good news is, i have integrated  the hint [https://github.com/gcp/leela-zero/issues/2003#issuecomment-437275025](url) of @alreadydone and had some small additional changes.
The most important seems in uct_select_child:
float pure_eval = get_raw_eval(color, **1**);  
The meaning is quite clear because the function will return a senseful result even for 0 visits.
To prevent another disappointing test, i have done myself 50 games with a smaller net (39d46507 best 10x128 as the modification does not depend on netsize) and 250 playouts and got the promising result of 30 wins for my modification.
This is not a prove, but i think a hint.

Here is the win leelaz.exe, if anyone would like to check with a recent net and decent playouts, please let me know your results.
[leelaz.zip](https://github.com/gcp/leela-zero/files/2601679/leelaz.zip)

Thx again so far! 
Peter

**Comment by WeirdConstructor** [comment]
I also ran 500 games: 195 (FPU mod) to 305 (vanilla) => 61% without FPU mod.
@petgo3 did you receive my mails?

**Comment by petgo3** [comment]
I did some further tests and got no sigificant success. Thank you all!

**Comment by alreadydone** [comment]
@fishcu Your game 1 and game 3 agree up to move 185; game 26 and 28 are identical, etc.
