### ISSUE TITLE
Connection problems since the update

### ISSUE THREAD

**Issue by ThePokerDude** [gcp/leela-zero#2009]
Since the update I get this messages after each game.
Would you like me to send you some log files?
If yes - how do I turn on logging?

NetworkException: Curl returned non-zero exit code 26
Retrying when next game is finished.
Upload failed. Curl Exit code: 26
Network connection to server failed.
NetworkException: Curl returned non-zero exit code 26
Retrying when next game is finished.

**Comment by Tsun-hung** [comment]
Update the client

**Comment by roy7** [comment]
It was because gzip was missing in the original zip file. If you re-download the client zip file it should work.
