### ISSUE TITLE
leelaz fails to work independently

### ISSUE THREAD

**Issue by ashinpan** [gcp/leela-zero#201]
I compile leelaz on linux mint (18.3). It works under autogtp, but does not work by itself. That is, when I try to run it using the command "leelaz -w weights.txt," it answers as follows:

Using 2 thread(s).
Leela Zero  Copyright (C) 2017  Gian-Carlo Pascutto
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

Initializing OpenCL
Detected 1 OpenCL platforms
Platform version: OpenCL 1.2 CUDA 9.0.229
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce GTX 1050
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 384.98
Device speed:  1531 MHz
Device cores:  5 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GTX 1050
with OpenCL 1.2 capability
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64 
Detecting residual layers...Could not open weights file: weights.txt

(PS: this is the same weight used by autogtp albeit with a different file name)

**Comment by gcp** [comment]
Are you sure it's ungzipped?

**Comment by ashinpan** [comment]
Well, now I see my mistake. But is it?

leelaz is in ~/myprograms/bin. This is on PATH, so I can call it from anywhere. The weights file is in the same folder. When I call leelaz from outside the bin folder, I have to give the path location of weights file explicitly. Otherwise, leelaz refuses to find the file, which is in the same folder. 

I don't know whether this is a bug or not.

**Comment by OmnipotentEntity** [comment]
This is not a bug.  If you use a relative path it is assumed to be relative to your pwd not to the program's bin directory.

**Comment by ashinpan** [comment]
OK. I understand. Thanks a lot. I will close the issue.
