### ISSUE TITLE
ELF2 in development by Facebook AI team. Will be their implementation of Alpha Zero. 

### ISSUE THREAD

**Issue by jillybob** [gcp/leela-zero#2012]
Checking some of the commits here, particularly 6th and 9th of November show that ELF2 is being worked on and is using the AlphaZero approach https://github.com/pytorch/ELF/commits/newtasks . 

Here in particularly AZ approach is compared to ELF2. https://github.com/pytorch/ELF/commit/2f4bdb74ea94e0fa432d1811968e8a30d737fc49

On reading a few of the commits, there is a 9x9 board and ChouFleur and Draughts game used in training.  The AI will be called Scan

**Comment by herazul** [comment]
It's really insteresting, because if they succeed or fail, either way we will have valuable information, especially if they answer questions afterward on their github !

**Comment by MarcelGruenauer** [comment]
Will this result in a network that can be used by Leela Zero or is it a different architecture?

**Comment by CheckersGuy** [comment]
Intresting choice of name :P There is a very strong draughts engine called "Scan"

**Comment by l1t1** [comment]
can you explain the purpose of new codes
