### ISSUE TITLE
leela-zero-0.16-phoenix-go

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#2013]
https://github.com/yenw/LeelaZero_PhoenixGo/releases/download/v3/leela-zero-0.16-phoenix-go.zip

**Comment by featurecat** [comment]
Is there an advantage to using Phoenix go? Is it stronger?

**Comment by l1t1** [comment]
can selfplay to training the weight

**Comment by l1t1** [comment]
it generated another style games, just like https://github.com/pangafu/LeelaMasterWeight does

**Comment by john45678** [comment]
@featurecat  gcp thinks Phoenix-go is not near as strong as Elf: 

> https://github.com/gcp/leela-zero/issues/1405#issuecomment-388741699

**Comment by gcp** [comment]
I just base myself on the reports that what they publicly released wasn't quite their best network and worse than our public stuff.
