### ISSUE TITLE
The server is crashed now.

### ISSUE THREAD

**Issue by bjiyxo** [gcp/leela-zero#2015]
Network connection to server failed.
NetworkException: JSON parse error: illegal value

**Comment by bjiyxo** [comment]
@roy7 @gcp may check the server.

**Comment by featurecat** [comment]
wrong repo

**Comment by ggroggs** [comment]
There's an SSL certificate problem which I suspect is the root cause: both started at the same time.

https://zero.sjeng.org/home is showing Error 526, Invalid SSL certificate, and I'm seeing the same error on an existing running autogtp when trying to upload a selfplay game.

**Comment by WeirdConstructor** [comment]
You can actually download and reach the site via HTTP (without S). http://zero.sjeng.org/

**Comment by wonderingabout** [comment]
nothing major,
we should get news soon or later, wait and see

**Comment by roy7** [comment]
The SSL certificate I'm afraid has to rely on @gcp, I'm clueless on that.

**Comment by ggroggs** [comment]
> You can actually download and reach the site via HTTP (without S). http://zero.sjeng.org/

Right, the site works fine without https; it's mostly autogtp that is affected for me right now, as that uses "curl https://zero.sjeng.org/get-task/" to get work orders, and that's returning the certificate error.

https:// on the main site is simply an easy way to observe the problem without running autogtp.

**Comment by l1t1** [comment]
31 match games, only 4 clients played

**Comment by roy7** [comment]
SSL should be fixed now.

**Comment by ggroggs** [comment]
> SSL should be fixed now.

Looks good, thanks!

**Comment by gcp** [comment]
Issue was forgetting to restart nginx after cert updates (which happened a while ago).
