### ISSUE TITLE
validation not saving sgf when binary is specified?

### ISSUE THREAD

**Issue by pliuphys** [gcp/leela-zero#2018]
I tried to run validation to test a modified lz and got no sgf. I then tested

validation -k kifu -n lz189.gz -n lz189.gz -o "-g -v 10 --noponder -t 1 -r 5 -d -w" -o "-g -v 10 --noponder -t 1 -r 5 -d -w" -- leelaz -- leelaz

with official win64 binaries, and got no sgf in the kifu folder. The folder is created, but empty. When I dropped the two "-- leelaz", I got sgf files in the folder.

**Comment by gcp** [comment]
I think this bug has been reported a few times.

**Comment by gcp** [comment]
@Hersmunch I think you last worked on this code, maybe you have an idea?

**Comment by Hersmunch** [comment]
I’ll take a look over the weekend. I’ve not been in good health lately so haven’t been up for doing much. Should have some time to spare though.

**Comment by Hersmunch** [comment]
Apologies, this was broken by my changes in #1652.
