### ISSUE TITLE
Request: release all trained networks

### ISSUE THREAD

**Issue by Shtanko-mephi** [gcp/leela-zero#202]
385k has an interesting style, different from current best 292k (even though 385k is weaker). It would be very interesting to see what "failed" networks learned, so if it's possible, please from now on release all networks, even weak ones.

**Comment by gcp** [comment]
Although I generally don't delete files and can probably collect them at some point, no promises here. Collection of the best networks in zero.sjeng.org/networks is automatic.

In theory one should be able to get the same effect by retraining from the public data, btw.
