### ISSUE TITLE
lz 190 weight should be promoted at 400 games but show fail

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#2025]
http://zero.sjeng.org/match-games/5bf068c3b4ea15180b5fe180

**Comment by l1t1** [comment]
ef09cd53

**Comment by gcp** [comment]
Guess the check is >55% and not >=55%?

In any case this is a server issue, not a lz bug.

**Comment by l1t1** [comment]
could you promote it? @gcp

**Comment by roy7** [comment]
Done, @l1t1

**Comment by l1t1** [comment]
thanks @roy7

**Comment by roy7** [comment]
This has been fixed here: https://github.com/gcp/leela-zero-server/pull/214
