### ISSUE TITLE
[Tournament] AI Ryusei 2018, December 15 & 16 at Nihon Ki-in

### ISSUE THREAD

**Issue by alreadydone** [gcp/leela-zero#2027]
Looks like a good opportunity for LZ to compete in her first tournament outside of China.

-------------------
From Hiroshi Yamashita, http://computer-go.org/pipermail/computer-go/2018-November/010920.html
Computer Go tournament, AI Ryusei2018 will be held on December 15th and 16th in Japan, Tokyo. This year, it will be held in Nihon-kiin.
Application deadline is November 30th.
https://www.igoshogi.net/ai_ryusei/01/en/
Last year's result.
https://www.igoshogi.net/ai_ryusei2017/01/en/result.html

**Comment by l1t1** [comment]
japanese rule Handicap
Even game. The first player starts with 6.5 points Komi.

**Comment by l1t1** [comment]
https://www.igoshogi.net/ai_ryusei/01/en/rules.html

**Comment by roy7** [comment]
If someone will be operating LZ for this event, I wonder if the Dynamic Komi version should be used to tweak the komi by 1 stone to be more Japanese-rules aware?

**Comment by l1t1** [comment]
@roy7 could you promote the weight 190, as it was failed by mistake https://github.com/gcp/leela-zero/issues/2025

**Comment by wonderingabout** [comment]
@alreadydone 

> Looks like a good opportunity for LZ to compete in _her_ first tournament outside of China.

> Looks like a good opportunity for LZ to compete in **its** first tournament outside of China.

please, let's just say "it", it's a bot
you are free to call it however you want though, but "she" for a bot always bugged me

**Comment by herazul** [comment]
I think it's a non-english speaker thing.
I tend to do it too, in some language you don't have an equivalent of "it" for objects

**Comment by Friday9i** [comment]
@l1t1 If it is ELF with 1000 or more visits, not a surprise at all... And a GTX1060 is enough for that, so anyone can setup a bot crushing LZ189@400 playouts.

**Comment by l1t1** [comment]
the bot "Winter-" always move 3-3 at its 2nd move

**Comment by l1t1** [comment]
the bot "Winter-" always move 3-3 at its 2nd move when play black, the behavior is very similar as lz 189 and lz 190's

**Comment by bjiyxo** [comment]
Due to personal issue, I cannot go to Japan. In fact, the most difficult problem is Japanese Rule, which means you have to pass at the proper time in the final game. If anyone wants to compete with leela zero, one must solve the issue.

**Comment by Vandertic** [comment]
In a future time, when a 19x19 version of [SAI](https://github.com/gcp/leela-zero/issues/1835) will be available (hopefully), this could be done. As SAI estimates points, it can check if the best move does not actually gain points with respect to pass. In fact we implemented a "weak Japanese mode" exactly in the sense of passing when it is the right time to do so. (And also something more like Japanese counting in the end.)
I don't suppose there is a 9x9 category in this tournament?

**Comment by Vandertic** [comment]
Maybe someone would like to try the following idea, that could very well work also with regular LZ.
Have the program force a 20% policy probability to the pass move, then look to the fraction of visits the move gets to decide whether to actually pass, disregarding the current best move.
From our experiments on SAI's Japanese mode, when the net is fully trained, this is a good way to predict whether it is time to pass. If there are still useful moves on the board, then even with 20% policy, the pass move will collect very few visits. If instead it is time to pass, it will get a good share of the visits.
For example, testing 7x7 SAI with 250 visits, the number of visits of the pass move would raise from 4-5 to 30-40 when it came the time to pass.
Maybe someone could experiment a little with 19x19 LZ nets to see if this effect is confirmed.

**Comment by TFiFiE** [comment]
This could be another way in which having a territory-estimating output would be beneficial; if passing doesn't cause the rounded evaluation of any intersection to drop to a lower category, then the game is probably played to completion. Apart from that, I don't envy anyone trying to make a bot conform as much as possible to Japanese rules.

**Comment by ThorAvaTahr** [comment]
> Apart from that, I don't envy anyone trying to make a bot conform as much as possible to Japanese rules.

y, including seki (wrs to counting) and bent four in the corner... the ruleset is a bit too convoluted, with rules that add little to the game of go. I wouldn't make it a priority.

**Comment by l1t1** [comment]
http://www.igoshogi.net/ai_ryusei/01/data/01.pdf
http://www.igoshogi.net/ai_ryusei/01/data/02.pdf
http://www.igoshogi.net/ai_ryusei/01/data/03.pdf
http://www.igoshogi.net/ai_ryusei/01/data/04.pdf
http://www.igoshogi.net/ai_ryusei/01/data/05.pdf
http://www.igoshogi.net/ai_ryusei/01/data/06.pdf
http://www.igoshogi.net/ai_ryusei/01/data/07.pdf
http://www.igoshogi.net/ai_ryusei/01/data/08.pdf

**Comment by barrtgt** [comment]
5: https://drive.google.com/open?id=18E2LTHy7qdOkowuWs1lHZDnFBZQ4M5qa

**Comment by Vandertic** [comment]
Thanks! (By the way... is Google Translate still this terrible!?)

**Comment by barrtgt** [comment]
The site I used must be using an older version of Google Translate. Using the official site gives a little better results. Unfortunately it only grabs the text.
5: https://drive.google.com/open?id=1M5pMg9jvldAMASImHQiF-nhW5tivIPLV4pVesfE_FgM

**Comment by l1t1** [comment]
http://www.igoshogi.net/ai_ryusei/01/en/list.html add 5 bots

http://www.igoshogi.net/ai_ryusei/01/data/11.pdf
http://www.igoshogi.net/ai_ryusei/01/data/12.pdf
http://www.igoshogi.net/ai_ryusei/01/data/13.pdf
http://www.igoshogi.net/ai_ryusei/01/data/14.pdf
http://www.igoshogi.net/ai_ryusei/01/data/09.pdf
http://www.igoshogi.net/ai_ryusei/01/data/10.pdf

No.11 ref zero.sjeng.org

**Comment by l1t1** [comment]
http://www.igoshogi.net/ai_ryusei/01/en/result.html the match is running

**Comment by l1t1** [comment]
bsk http://www.igoshogi.net/ai_ryusei/01/data/15.pdf

**Comment by l1t1** [comment]
http://www.igoshogi.net/ai_ryusei/01/result.html
最終結果　


プログラム名 / チーム名 
第1位　Golaxy / Jin Xing（中国） 
第2位　Rn/ 松崎憲介（日本） 
第3位　LeYouAI / Zhou You（中国） 
第4位　夏風 / 山下 宏（日本） 
第5位　Ray / 小林祐樹（日本） 
第6位　Akira / 渡辺順哉（日本） 
第7位　nlp / 若井建志（日本） 
第8位　Maru/ 武田敦志（日本） 
第9位　BSK / 神宮司直輝 
第10位　PyaqArgo / 市村豊 
第11位　勝也/ 清愼一（日本） 
第12位　Kugutsu / Tokumoto（日本） 

独創賞
BSK / 神宮司直輝（日本） 
新人賞
Golaxy / Jin Xing（中国）

**Comment by l1t1** [comment]
Eng version
Final result


program name / team name 
1st　Golaxy / Jin Xing (China)
2nd　Rn/ Kensuke MAtsuzaki(Japan)
3rd　LeYouAI / Zhou You (China)
4th　Natsukaze / Hiroshi Yamashita (Japan)
5th　Ray / Yuuki Kobayasi (Japan)
6th　Akira / Junya Watanabe (Japan)
7th　nlp / Kenshi Wakai (Japan)
8th　Maru/ Atsushi Takeda(Japan)
9th　BSK / Naoki Jinguji(Japan)
10th　PyaqArgo / Yutaka Ichimura (Japan)
11st　nlp / Kenji Iwai (Japan)
12nd　Kugutsu / Tokumoto (Japan)
13rd　Mayoigo / Masaki Murayama (Japan)
14th　Katsunari/ Shinichi Sei(Japan)

Creativity award
BSK / Naoki Jinguji(Japan) 
New face award
Golaxy / Jin Xing (China)

**Comment by alreadydone** [comment]
Although not participated by itself, I am glad that LZ is featured in some form in this tournament, and about Rn's performance. As the tournament is over, closing as stale.

**Comment by alreadydone** [comment]
From https://github.com/pasky/pachi/pull/96:
> For territory scoring came across an [old thread](http://computer-go.org/pipermail/computer-go/2010-April/000209.html) on computer go mailing list which was very insightful. **Didn't think deriving territory scoring from playouts' area scoring could be so elegant.** Still would need to handle eyes in seki for full japanese rules compliance but this is already really good. Pachi correctly passes when pass is the only move under japanese rules now.

... maybe someone wants to take a look.
