### ISSUE TITLE
Add permission under GPL v3 section 7 for linking with cuDNN/CUDA/TensorRT.

### ISSUE THREAD

**Issue by gcp** [gcp/leela-zero#2032]
For some background, see https://github.com/gcp/leela-zero/issues/2007#issuecomment-439654245.

In order to be able to distribute Leela Zero binaries with cuDNN/CUDA/TensorRT support together with the required DLLs we need to comply with both the GPL and NVIDIA's license terms. The GPL requires that all source for the program be available freely, whereas NVIDIA's libraries, including their headers, add a bunch of restrictions. 

There is a way around this by adding an additional permission as allowed by GPL v3 in section 7. An example for such an additional permission for CUDA is found here: [Gentoo Example](https://gitweb.gentoo.org/repo/gentoo.git/plain/licenses/GPL-3+-with-cuda-exception)

This can be done for all files currently in Leela Zero with the agreement of all contributors, so that Leela Zero with CUDA support can be distributed as a binary, together with the required DLLs.

The suggested text is the following:

```
Additional permission under GNU GPL version 3 section 7

If you modify this Program, or any covered work, by linking or
combining it with NVIDIA Corporation's libraries from the
NVIDIA CUDA Toolkit and/or the NVIDIA CUDA Deep Neural
Network library and/or the NVIDIA TensorRT inference library
(or a modified version of those libraries), containing parts covered 
by the terms of the respective license agreement, the licensors of 
this Program grant you additional permission to convey the resulting 
work.
```

**Comment by gcp** [comment]
These are the people whose code would be involved. So if you are listed here, read the above and say whether you're OK with it or not.

@marcocalignano 
@Ttl 
@sethtroisi 
@TFiFiE 
@ihavnoid 
@killerducky 
@bood 
@ywrt 
@WhiteHalmos 
@Hersmunch 
@earthengine 
@akdtg 
@barrybecker4 
@kuba97531 
@alreadydone 
@roy7 
@bittsitt 
@thynson 
@tux3 
@nerai 
@OmnipotentEntity 
@tterava 
@Alderi-Tokori 
@Eddh

**Comment by thynson** [comment]
Absolutely agreed. 👍

**Comment by bood** [comment]
I'm okay with this additional permission.

**Comment by nerai** [comment]
I'm ok with this.

**Comment by kuba97531** [comment]
I'm OK with this.

**Comment by ihavnoid** [comment]
I'm okay.

**Comment by Ttl** [comment]
Ok.

**Comment by tux3** [comment]
I'm okay with this.

**Comment by killerducky** [comment]
Ok.

**Comment by tterava** [comment]
Ok

**Comment by Alderi-Tokori** [comment]
I'm ok with this as well.

**Comment by marcocalignano** [comment]
I am OK with this.

**Comment by sethtroisi** [comment]
I'm ok with this

**Comment by roy7** [comment]
I pinged those I could locate on Discord to help out.

**Comment by alreadydone** [comment]
Of course I'm OK with this!

**Comment by Hersmunch** [comment]
Ok from me

**Comment by TFiFiE** [comment]
Permission granted.

**Comment by ywrt** [comment]
Permission granted.

**Comment by Eddh** [comment]
I'm OK with this !

**Comment by barrybecker4** [comment]
It's fine with me.

**Comment by hred6** [comment]
I'm OK with this !ok!

**Comment by AncalagonX** [comment]
I'm okay with this.

**Comment by gcp** [comment]
I sent the 3 people that are still missing an email.

**Comment by WhiteHalmos** [comment]
I'm OK with this. Thanks for sending the email!

**Comment by akdtg** [comment]
I'm ready to sign every @OmnipotentEntity's word https://github.com/gcp/leela-zero/issues/2032#issuecomment-440012423
Agreed, go ahead.

**Comment by wonderingabout** [comment]
when this issue is solved, please @ me

i already wrote instructions on how to install cuda, cudnn, tensorRT
will make a video tutorial

**Comment by roy7** [comment]
@bittsitt I hope you are still out there someplace. :)

**Comment by gcp** [comment]
I hope so too. The problem is that his contribution was pretty important: it's all the lz-analyze code that makes Lizzie work. We could do it the ffmpeg way and condition that code on not using CUDA, so people analyzing would be using the OpenCL version (perhaps with the PTX hack that @ihavnoid made), and clients running the training could just use CUDA. But obviously that's far from ideal and doesn't make it really easier for users.

Rewriting the code isn't trivial either, especially as you should absolutely avoid the current implementation as a reference (ideally it should be clean room-ed after writing a GTP spec about it).

So yeah. Finding @bittsitt would be preferable.

**Comment by roy7** [comment]
I'm unable to extract his email address from GitHub since his last commit was so long ago I think. I tried pinging them in a different repository.

**Comment by alreadydone** [comment]
Nice find! It seems he's still watching featurecat/lizzie though no longer watching his fork of lizzie and leela-zero. You can find the email addresses associated to commits by searching the name in gitk, and in one case bittsitt shows up with a gmail address; I think @gcp did something like this. I found his Twitch account and sent him a message but didn't get a response yet.

**Comment by OmnipotentEntity** [comment]
Re: Cleanroom implementation.  I'm about to graduate in a few days, and I'll finally have free time again.  If someone writes up a specification and creates a fork without this feature, I'll be happy to re-add it before attempting to to work on the binary file format shit that I've had on the backburner for months.

Though I have not read or looked at bittsitt's code, I cannot prove it, but considering that the code is published and freely available, it would be difficult for anyone to demonstrate that.

**Comment by roy7** [comment]
I tried dropping a note to the Gmail address. Lets hope they still check it. :)

**Comment by gcp** [comment]
>Though I have not read or looked at bittsitt's code, I cannot prove it, but considering that the code is published and freely available, it would be difficult for anyone to demonstrate that.

I'm sure that'd be fine. It's not like we'd be expecting to be sued over this and have to prove it. But it's just proper to respect another persons' copyright which means no peeking.

I'll take a look at documenting the GTP commands, this should be done anyhow.

**Comment by roy7** [comment]
Yay!

**Comment by wonderingabout** [comment]
what shall be done now @gcp ?

**Comment by gcp** [comment]
I'll update the licenses in the tree. This is awesome news.
