### ISSUE TITLE
the new weight for match is not appeared in time

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#2039]
more than 13 passed after last one(2018-11-22 19:42)

**Comment by Friday9i** [comment]
Yep, I posted it on discord 2 hours ago, and still nothing: probably a server problem (?)

**Comment by roy7** [comment]
This is normally training side from @gcp, not server side, if everything else server-related is still operating. :)

**Comment by gcp** [comment]
Training machine ran out of disk space and had to be restarted.

Those 256x40 nets are big when uncompressed and quickly fill up the SSD when I forget them. Should try to construct some cron job or similar.

**Comment by l1t1** [comment]
11.10M+32.0k 40x256 f2eef141 was matched at 2018-11-30 16:30 , 8 hours passed now since then

**Comment by l1t1** [comment]
11.11M+32.0k 40x256 1dfed21b was matched at 2018-12-01 6:28, why skip others
