### ISSUE TITLE
autogtp save other sgf file in current directory

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#205]
I use leelazwatch from https://github.com/fsparv/LeelaWatcher, It save sgf by defult, but the name rule is diff from that of leelaz.
<b>
and 1 game(s) played in 87 minutes = 5268 seconds/game, last game took 5268 seconds.
Best network hash: 92c658d7325fe38f0c8adbbb1444ed17afd891b9f208003c272547a7bcb87909
Required client version: 4 (OK)
Already downloaded network.
Engine has started.
Infinite thinking time set.Saving as:2017-11-29T01_49_16.575Z.sgf
</b>
and at same time, I run autogtk -k in same directory in another console window, it also save sgf file,
now they are both uploaded to sever, but not save to database as the corresponding txt file not exists.

I think the logic of autogtp should be only upload own sgf with txt.
<b>
Writing 8543821b210d4c6992a15e983ddae550.sgf
Dumping 8543821b210d4c6992a15e983ddae550.txt
Stopping engine.
curl.exe -F networkhash=92c658d7325fe38f0c8adbbb1444ed17afd891b9f208003c272547a7bcb87909 -F clientversion=4 -F sgf=@2017
-11-29T01_49_16.575Z.sgf.gz -F trainingdata=@2017-11-29T01_49_16.575Z.txt.0.gz http://zero.sjeng.org/submit
curl.exe -F networkhash=92c658d7325fe38f0c8adbbb1444ed17afd891b9f208003c272547a7bcb87909 -F clientversion=4 -F sgf=@8543
821b210d4c6992a15e983ddae550.sgf.gz -F trainingdata=@8543821b210d4c6992a15e983ddae550.txt.0.gz http://zero.sjeng.org/sub
mit
25 game(s) played in 3005 minutes = 7212 seconds/game, last game took 4351 seconds.
</b>

**Comment by gcp** [comment]
Sounds like an issue with LeelaWatcher, really.
