### ISSUE TITLE
could you give b8fb3a4a(54.92%) more match games?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#2050]
now it had 417, while
30bccf1d (54.10%) had 427
b38738aa (54.48%) had 424

**Comment by l1t1** [comment]
big thanks to the god,
192 2018-11-27 14:11 b8fb3a4a 40x256 0 61 11041573 
@gcp the elo seems wrong

230 : 188 (55.02%) 418 / 400 PASS 
418 55.02%  4948f01579fc059b677e7a5d36a02c69 b8fb3a4a W+Resign 239 1103.9 minutes  sgf 63 17

**Comment by alreadydone** [comment]
White winrate seems to have risen to 62.58%. Any stats on evolution of this?

**Comment by alreadydone** [comment]
I was referring to the results of # 192 vs # 191. these are match games, and the self-play games are more random so the trained initial winrate should not be too extreme. I haven't checked but it may still be around 55%?
