### ISSUE TITLE
Questions about FullBoard

### ISSUE THREAD

**Issue by barrybecker4** [gcp/leela-zero#206]
What is the significance of the initial ko value defined as the following? 
```
#ifdef _WIN32
    res = 0x1234567887654321UI64;
#else
    res = 0x1234567887654321ULL;
#endif
```
This is the same initial value used in calcKoHash and calcHash. Probably it should be a constant.
In getRotatedHashes you start with 0x1234567887654321ULL but without the ifdef for _WIN32. Is that an oversight? Seems like there should be the same ifdef that you did in the other places. Is that a potential bug on windows? If it is a bug, its one that would have been avoided by having this value as a constant.

What does this comment mean? "Tromp-Taylor has positional superko value"
For reference, this page describes superko - https://senseis.xmp.net/?Superko
How does it relate to the hash that is computed in calcKoHash?
		
There is some duplicated code when computing the hashes. 
There could be separate methods for calculating the base hashes and also the part that incorporates the prisoners into the hash.

The original version of Leela handles multiple board sizes - so it must do dynamic allocation. Is the code in Leela-zero very different? It must be. Sounds like having it handle different board sizes would be difficult.

I will attempt a PR after I see responses.

**Comment by gcp** [comment]
It's a random starting value. The #ifdef probably dates back to when Visual Studio didn't have proper C++ support.

>How does it relate to the hash that is computed in calcKoHash?

Search for Zobrist hashing.

>Is the code in Leela-zero very different?

It supports different board sizes in the core engine, but not in the neural network part.
