### ISSUE TITLE
Validation sometimes pauses game?

### ISSUE THREAD

**Issue by pliuphys** [gcp/leela-zero#2060]
When I run validation (0.16 win64 binary), sometimes the game stops progressing. I didn't specify the binary, so that defaults to leelaz.exe. The program stops showing new moves. But when I hit enter, moves start showing up again, at the original interval. The only input it takes that I know is q+enter. I tried to type a few letters (no q), to see if it's somehow stuck listening, and the game wasn't stopped. Is this a feature I don't understand? If not, any hint how to debug this?

**Comment by kuba97531** [comment]
You're mostly experiencing a Windows Console feature that if you select some text in the console window then the `stdout` of a process is blocked and the program waits on `printf()`.
So most likely it's not a leela-zero issue.

**Comment by pliuphys** [comment]
@kuba97531 That's exactly the case.  After selecting I see that one leelaz continues to consume CPU for some time, and stops. When I de-select the move shows up. And after selecting, if I left click the console I'm actually still selecting one letter, which I think is what I did. Thanks!
