### ISSUE TITLE
a no resign self play game took 50594 seconds 44651 ms/move

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#2068]
(;GM[1]FF[4]RU[Chinese]DT[2018-12-06]SZ[19]KM[7.5]PB[Leela Zero 0.16 9d4ac610]PW[Leela Zero 0.16 9d4ac610]RE[W+277.5]
C[Leela Zero options: -p 0 -v 1601 -r 0 -m 999 -t 1 -d -n --noponder -s 264342233451832021 -g -q -w networks/9d4ac61006eeaf7836ee2069602cbbbeb89cb8c18e7daa4509593cba654348da.gz]
;B[pp];W[pd];B[dp];W[dd];B[cf];W[cn];B[qc];W[qd];B[pc];W[od]
;B[nb];W[nq];B[fc];W[df];B[dg];W[ef];B[cd];W[cc];B[ce];W[dc]
;B[ci];W[gd];B[mc];W[dh];B[cg];W[ic];B[co];W[qn];B[pn];W[pm]
;B[on];W[om];B[oq];W[or];B[np];W[mp];B[qm];W[ql];B[rm];W[rl]
;B[rn];W[nn];B[mq];W[nr];B[lq];W[qo];B[qp];W[ro];B[rp];W[sn]
;B[mo];W[fq];B[nm];W[dn];B[er];W[do];B[ep];W[cp];B[cq];W[bo]
;B[nl];W[ok];B[bq];W[eq];B[fp];W[fr];B[gq];W[gr];B[hq];W[dr]
;B[dq];W[hr];B[ir];W[es];B[cl];W[fn];B[go];W[nk];B[eg];W[gn]
;B[ll];W[lk];B[kk];W[lj];B[me];W[kl];B[lm];W[cj];B[dk];W[dj]
;B[ej];W[ek];B[ei];W[ck];B[dl];W[bl];B[el];W[bk];B[of];W[rc]
;B[rb];W[qf];B[bi];W[gl];B[fk];W[di];B[eh];W[in];B[fd];W[ge]
;B[hb];W[ib];B[fe];W[ff];B[hc];W[id];B[hd];W[ie];B[de];W[ee]
;B[eb];W[ed];B[db];W[cb];B[ia];W[jb];B[he];W[hf];B[if];W[ip]
;B[gc];W[gf];B[je];W[jf];B[ig];W[ke];B[da];W[gh];B[jg];W[kf]
;B[hi];W[hh];B[kg];W[fa];B[kd];W[kc];B[ld];W[jd];B[ha];W[ec]
;B[fb];W[ga];B[lb];W[ja];B[kb];W[ca];B[km];W[oh];B[ka];W[ea]
;B[gb];W[fa];B[ap];W[kp];B[mg];W[lp];B[ho];W[kq];B[io];W[re]
;B[al];W[jo];B[hn];W[bm];B[ob];W[ea];B[bp];W[gj];B[rd];W[ni]
;B[ls];W[sb];B[jq];W[lr];B[jp];W[hm];B[kr];W[rg];B[sc];W[ga]
;B[gi];W[fl];B[em];W[en];B[il];W[gk];B[fi];W[ik];B[jj];W[ij]
;B[ii];W[jk];B[jl];W[kj];B[ji];W[kl];B[fm];W[gm];B[kk];W[ao]
;B[mr];W[kl];B[hj];W[hk];B[kk];W[im];B[ak];W[kl];B[pl];W[sm]
;B[kk];W[ch];B[bh];W[kl];B[da];W[kk];B[ar];W[lf];B[ps];W[jm]
;B[se];W[no];B[br];W[rj];B[gc];W[op];B[ih];W[so];B[lh];W[bj]
;B[bd];W[pk];B[ng];W[nd];B[rq];W[ds];B[fe];W[ln];B[sl];W[ma]
;B[qs];W[sr];B[oj];W[cs];B[ba];W[bb];B[ah];W[hl];B[fo];W[rs]
;B[kn];W[ms];B[lo];W[fg];B[ns];W[nc];B[mb];W[ko];B[ac];W[rh]
;B[nh];W[qr];B[as];W[pf];B[aj];W[lc];B[hp];W[os];B[ms];W[bg]
;B[po];W[mn];B[nf];W[ag];B[pi];W[le];B[ml];W[ph];B[qk];W[md]
;B[bn];W[hs];B[sg];W[kd];B[gp];W[pq];B[ne];W[rn];B[sp];W[db]
;B[gg];W[mo];B[ai];W[oa];B[aa];W[lo];B[js];W[sj];B[nj];W[fc]
;B[qa];W[mm];B[an];W[am];B[ae];W[ci];B[bf];W[ab];B[fh];W[qi]
;B[kh];W[co];B[ak];W[og];B[sf];W[lg];B[fj];W[pb];B[ba];W[je]
;B[la];W[dm];B[be];W[hg];B[mi];W[oc];B[mh];W[aj];B[il];W[rm]
;B[bn];W[qb];B[bh];W[pj];B[eo];W[jl];B[rr];W[fd];B[rf];W[np]
;B[na];W[sq];B[jh];W[qh];B[mf];W[si];B[bi];W[al];B[fb];W[il]
;B[bs];W[pe];B[is];W[cm];B[qe];W[rk];B[ks];W[re];B[sh];W[er]
;B[hb];W[he];B[rc];W[sd];B[ek];W[af];B[hc];W[pr];B[mj];W[ha]
;B[pa];W[rf];B[tt];W[sf];B[pb];W[ia];B[eb];W[ra];B[bc];W[oi]
;B[ah];W[li];B[qg];W[ld];B[ps];W[ai];B[hd];W[ak];B[oo];W[sh]
;B[ma];W[qm];B[ad];W[se];B[mk];W[jn];B[ss];W[an];B[af];W[sr]
;B[oe];W[gb];B[ag];W[cr];B[lr];W[fe];B[bg];W[jc];B[jr];W[iq]
;B[ms];W[tt];B[gs];W[fb];B[qb];W[sq];B[lr];W[ss];B[jq];W[oq]
;B[hb];W[sk];B[is];W[fs];B[tt];W[js];B[jr];W[pg];B[gc];W[aq]
;B[hn];W[go];B[hp];W[br];B[hq];W[ho];B[ol];W[pi];B[ns];W[sg]
;B[jp];W[mr];B[fp];W[qq];B[pp];W[da];B[tt];W[cq];B[rp];W[gp]
;B[as];W[hn];B[fo];W[qj];B[oo];W[sl];B[ap];W[bp];B[sp];W[oa]
;B[pn];W[hc];B[mc];W[rd];B[lb];W[qg];B[pa];W[ri];B[dq];W[ob]
;B[na];W[pb];B[on];W[ki];B[lq];W[hd];B[fk];W[lm];B[bf];W[rc]
;B[rr];W[bh];B[ac];W[ad];B[lh];W[ar];B[cg];W[nl];B[jg];W[kh]
;B[af];W[kb];B[bd];W[ih];B[nh];W[rb];B[ls];W[qk];B[pc];W[kg]
;B[ir];W[ol];B[dg];W[qs];B[qb];W[rq];B[nj];W[ej];B[hi];W[em]
;B[el];W[hj];B[jj];W[bg];B[dl];W[ll];B[ng];W[qe];B[de];W[gi]
;B[of];W[aa];B[fh];W[mf];B[ek];W[io];B[mj];W[me];B[mb];W[bs]
;B[ma];W[qc];B[eh];W[ml];B[la];W[mg];B[ne];W[fj];B[cd];W[eg]
;B[mh];W[cf];B[ei];W[eo];B[cg];W[gc];B[ka];W[kn];B[be];W[ah]
;B[ag];W[oe];B[dp];W[eb];B[ce];W[bi];B[ji];W[nm];B[jh];W[ap]
;B[ks];W[ba];B[ig];W[oj];B[js];W[hb];B[mk];W[gg];B[ae];W[gs]
;B[dk];W[rr];B[bc];W[fi];B[qp];W[sc];B[fh];W[pl];B[kr];W[ad]
;B[be];W[km];B[af];W[po];B[sp];W[bn];B[ei];W[nb];B[cd];W[bc]
;B[ae];W[mb];B[pn];W[ac];B[on];W[la];B[na];W[ep];B[ce];W[if]
;B[rp];W[mi];B[fo];W[ii];B[ag];W[dp];B[nj];W[sa];B[pp];W[hi]
;B[de];W[pc];B[mk];W[fm];B[ig];W[ji];B[jg];W[fp];B[bf];W[bq]
;B[tt];W[qa];B[tt];W[jh];B[jg];W[eh];B[tt];W[oo];B[pn];W[on]
;B[tt];W[dg];B[tt];W[ka];B[tt];W[qb];B[tt];W[fh];B[tt];W[cg]
;B[tt];W[pa];B[tt];W[ei];B[tt];W[jj];B[tt];W[ps];B[tt];W[lb]
;B[tt];W[fo];B[tt];W[tt])

**Comment by l1t1** [comment]
a human game of 325
(;CA[gb2312]LT[60]LC[5]KO[6.5]GK[1]TC[柯洁2比1夺第6个世界冠军，个人第13冠]TE[23]
AP[MultiGo:4.4.4]RD[2018-12-05]PC[高阳一山]PB[安国铉]BR[九段]PW[柯洁]WR[九段]TM[120]
RE[白胜5.5目]MULTIGOGM[1]
;B[pd];W[dp];B[pp];W[dd];B[cq];W[dq];B[cp];W[do];B[co];W[cn];B[bn];W[qq];B[pq];W[qp]
;B[po];W[rn];B[hq];W[cr];B[br];W[bm];B[dn];W[cm];B[dr];W[bo];B[cs];W[fn];B[en];W[em]
;B[eo];W[dm];B[fo];W[go];B[eq];W[cf];B[fm];W[fl];B[gn];W[gl];B[fc];W[nc];B[ic];W[qf]
;B[pf];W[pg];B[of];W[qc];B[qe];W[pc];B[qg];W[kc];B[db];W[hd];B[fe];W[hc];B[cc];W[cd]
;B[he];W[id];B[eh];W[ch];B[im];W[hn];B[hm];W[ln];B[lp];W[pr];B[or];W[qr];B[ll];W[nr]
;B[nq];W[os];B[ek];W[el];B[pm];W[oq];B[np];W[qj];B[qh];W[ql];B[ik];W[gi];B[fg];W[bc]
;B[bb];W[dc];B[cb];W[fd];B[gd];W[gc];B[ed];W[fb];B[bd];W[be];B[ac];W[ec];B[ih];W[lr]
;B[jq];W[nk];B[qm];W[rm];B[pk];W[gm];B[fn];W[ml];B[qk];W[lk];B[kl];W[kk];B[jl];W[ki]
;B[mj];W[mh];B[ni];W[mk];B[jj];W[nh];B[oi];W[kg];B[jf];W[rk];B[pl];W[ri];B[rl];W[sl]
;B[kf];W[pj];B[oj];W[ji];B[ii];W[og];B[rf];W[lf];B[le];W[mf];B[me];W[nf];B[od];W[mi]
;B[nj];W[pi];B[ph];W[oh];B[ok];W[mm];B[oc];W[ob];B[nb];W[mb];B[jg];W[mo];B[lq];W[na]
;B[rd];W[no];B[oo];W[kh];B[ck];W[dj];B[dk];W[cj];B[ej];W[bk];B[lj];W[kj];B[gj];W[kr]
;B[kn];W[fd];B[lo];W[li];B[fc];W[ie];B[fd];W[eb];B[bp];W[hf];B[hg];W[hs];B[ir];W[is]
;B[gs];W[jr];B[hr];W[rc];B[rh];W[if];B[gf];W[ig];B[nd];W[jh];B[ke];W[hl];B[il];W[an]
;B[sc];W[sb];B[sd];W[kq];B[kp];W[js];B[mr];W[ms];B[mq];W[ls];B[rb];W[ra];B[sa];W[jp]
;B[iq];W[sb];B[si];W[rj];B[sa];W[ae];B[ad];W[sb];B[ro];W[qo];B[qn];W[rp];B[sa];W[gr]
;B[fs];W[sb];B[sk];W[ql];B[sa];W[rl];B[qa];W[qb];B[dg];W[lm];B[km];W[om];B[op];W[ol]
;B[pn];W[fj];B[gk];W[fk];B[fi];W[cg];B[mc];W[lc];B[nb];W[ab];B[aa];W[nc];B[md];W[pa]
;B[nb];W[ra];B[lb];W[nc];B[or];W[ns];B[nb];W[hh];B[gg];W[nc];B[ps];W[qs];B[nb];W[jo]
;B[io];W[nc];B[bj];W[di];B[ei];W[bl];B[nb];W[fp];B[ep];W[nc];B[dh];W[ci];B[nb];W[ip]
;B[ma];W[gq];B[ko];W[in];B[sb];W[kb];B[jd];W[jc];B[jn];W[ho];B[fr];W[de];B[ee];W[df]
;B[ef];W[hk];B[hj];W[jk];B[ij];W[ne];B[on];W[nn];B[ap];W[oe];B[pe];W[da];B[ca];W[ea]
;B[ao];W[bn];B[sh];W[sj];B[ib];W[ka];B[ia];W[hb];B[oq];W[ha];B[ge];W[jb];B[mb];W[ja]
;B[fq];W[gp];B[kd])

**Comment by l1t1** [comment]
shall we reduce the ratio of no resign game or increate the thresholds from 0 to 0.1?

**Comment by Splee99** [comment]
I would suggest to finish game whenever one side plays PASS. If one side plays PASS and the opponent continues to play, it makes the game state extremely unbalanced. It also makes PASS more likely to be chosen as a "normal" move during training, which doesn't make sense. Has anybody seen ANY human game which has a PASS move middle in the game?

**Comment by Splee99** [comment]
I just downloaded a no resign game. White played first PASS at winrate about 2.6% (move 280) and black was leading by 28 points. There were many dead stones and white actually won according to tromp-taylor rule. So my previous suggestion won't work. However, we could set the next winrate threshold to 3%.

**Comment by Ishinoshita** [comment]
>  It also makes PASS more likely to be chosen as a "normal" move during training, which doesn't make sense. Has anybody seen ANY human game which has a PASS move middle in the game?

-  That's a tribute to be paid to let the network learn this by itself ('Zeroth' principle), exactly by playing such moves in selfplay games. No reason it couldn't learn that.
- It has most probably already learnt it, but noise still pushes Pass policy value high enough from time to time so that temperature can pick it.
* Search guided by policy value is supposed to quickly so it out, so that it won't receive any more visit; but when win rate is extreme (few 2%), this doesn't happen. The search us very flat, causing terrible moves (stealling own eyes e.g.) to receive visits, opening the door to temperature. So,  that will still happen in training games, under unbalanced situations,  even would LZ be 20D ;-)
-  Pass is not always tbe worst possible move. Still better than killing your own group or playing a catastrophic damezumari that causes a big capture of one of your group. That happens in kuy game (I can testify....). So, middle game Pass move probably shocking only from human perspective.

**Comment by Ishinoshita** [comment]
Disabling temperature in no resign self-play games, statically (-m 250 e.g.) or dynamically (when win rate goes below some threshold' say 5%), would increase the probabilitg to pick to consecutive Pass moves and end the game shorterly.

**Comment by Splee99** [comment]
I have replayed the no resign game I downloaded earlier with noise disabled. White plays PASS at exact the same move and black doesn't play PASS after because the tromp-taylor rule. So PASS is not noise related. You may verify this yourself.

**Comment by jokkebk** [comment]
I have many times played games where I pass when opponent tries to invade in a place where it will take consecutive moves to live/cut/kill/whatever, and the opponent does not see that (or chooses to ignore, and true, a few games they manage a tesuji and I lose). This gains point under Japanese rules, but I think not in Chinese. For Leela, learning these "you are silly" passes may not be necessary. :laughing:

**Comment by Ishinoshita** [comment]
@Splee99 : 
>Has anybody seen ANY human game which has a PASS move **middle in the game**?

I actually went a bit too fast assuming Pass move in middle game happening as a result of noise + temp.

In @l1t1's first game at top, first Pass happens at move 383. One can argue that since the game is 664 moves long, move 383 is still *middle game*. But that's obviously misleading and not "middle game" by any human standard. That game is sealed as won by White way before move 200. Thus, move 383 is far far endgame, where Pass move totally makes sense and sees its probability increase quickly in the raw policy (NN).

Same probably applies to the no resign game you're reporting ("winrate about 2.6% (move 280)"). At 280 move count and with 2.6% wr, the game is not in "middle game" under the usual sense of the expression. Hence the fact that Pass is still the best move even with no noise. Just MHO.

**Comment by l1t1** [comment]
lz version 0.16
```
Got new job: selfplay
net: 05d10f27e549f3d1e34bc449d406fba18014f262d395cd67cec957829ef399df.
Engine has started.
time_settings 0 1 0
Thinking time set.
1 (B D4) 2 (W Q16) 3 (B Q4) 4 (W D16) 5 (B R17) 6 (W R16) 7 (B Q17) 8 (W P16) 9 (B O18) 10 (W C6) 11 (B N17) 12 (W O3) 1
3 (B C14) 14 (W F3) 15 (B D6) 16 (W D7) 17 (B E6) 18 (W C4) 19 (B C7) 20 (W C5) 21 (B D8) 22 (W D3) 23 (B E7) 24 (W R6)
25 (B Q6) 26 (W Q7) 27 (B P6) 28 (W R4) 29 (B R3) 30 (W R5) 31 (B Q3) 32 (W R9) 33 (B N4) 34 (W M3) 35 (B O4) 36 (W D14)
 37 (B D13) 38 (W E14) 39 (B C16) 40 (W C17) 41 (B C15) 42 (W D17) 43 (B Q11) 44 (W N16) 45 (B M16) 46 (W O17) 47 (B M18
) 48 (W M15) 49 (B L16) 50 (W M4) 51 (B Q8) 52 (W Q9) 53 (B P7) 54 (W R8) 55 (B R7) 56 (W S7) 57 (B O11) 58 (W S17) 59 (
B S18) 60 (W P10) 61 (B P11) 62 (W S11) 63 (B N3) 64 (W N2) 65 (B O2) 66 (W M11) 67 (B N15) 68 (W N14) 69 (B O16) 70 (W
O14) 71 (B M12) 72 (W L11) 73 (B N11) 74 (W K13) 75 (B N9) 76 (W C9) 77 (B B8) 78 (W D11) 79 (B E13) 80 (W C12) 81 (B C1
3) 82 (W F11) 83 (B G13) 84 (W H11) 85 (B F16) 86 (W F18) 87 (B S10) 88 (W R10) 89 (B J4) 90 (W G5) 91 (B H8) 92 (W J5)
93 (B K4) 94 (W F8) 95 (B G6) 96 (W H6) 97 (B G7) 98 (W H4) 99 (B K5) 100 (W K6) 101 (B L6) 102 (W K7) 103 (B C10) 104 (
W D9) 105 (B B9) 106 (W B12) 107 (B D10) 108 (W E10) 109 (B E9) 110 (W F9) 111 (B C8) 112 (W L2) 113 (B M5) 114 (W J3) 1
15 (B K3) 116 (W K2) 117 (B J7) 118 (W M13) 119 (B J6) 120 (W H5) 121 (B H3) 122 (W J2) 123 (B F5) 124 (W F4) 125 (B C3)
 126 (W D5) 127 (B D2) 128 (W E4) 129 (B B3) 130 (W E2) 131 (B D15) 132 (W B6) 133 (B B2) 134 (W E1) 135 (B C1) 136 (W D
1) 137 (B J12) 138 (W H12) 139 (B J13) 140 (W H13) 141 (B J14) 142 (W H14) 143 (B J11) 144 (W J15) 145 (B K14) 146 (W G1
5) 147 (B F15) 148 (W G16) 149 (B G14) 150 (W J17) 151 (B S12) 152 (W R11) 153 (B R12) 154 (W Q13) 155 (B Q12) 156 (W S1
5) 157 (B T17) 158 (W N12) 159 (B L14) 160 (W L13) 161 (B O12) 162 (W L12) 163 (B Q14) 164 (W O15) 165 (B P17) 166 (W R1
4) 167 (B P13) 168 (W P14) 169 (B R13) 170 (W Q15) 171 (B S16) 172 (W Q13) 173 (B H7) 174 (W G4) 175 (B Q14) 176 (W N16)
 177 (B O13) 178 (W N13) 179 (B Q13) 180 (W O17) 181 (B F17) 182 (W G18) 183 (B O16) 184 (W M9) 185 (B K9) 186 (W L9) 18
7 (B K8) 188 (W M10) 189 (B S14) 190 (W O17) 191 (B B4) 192 (W T14) 193 (B R15) 194 (W B17) 195 (B F12) 196 (W R14) 197
(B O9) 198 (W L7) 199 (B M7) 200 (W L8) 201 (B A5) 202 (W B5) 203 (B A4) 204 (W H10) 205 (B E11) 206 (W E12) 207 (B D12)
 208 (W C11) 209 (B E11) 210 (W N18) 211 (B O16) 212 (W E12) 213 (B G17) 214 (W E11) 215 (B H17) 216 (W H18) 217 (B J16)
 218 (W K16) 219 (B H16) 220 (W H15) 221 (B K15) 222 (W K17) 223 (B B13) 224 (W B16) 225 (B G10) 226 (W G12) 227 (B G9)
228 (W B15) 229 (B A13) 230 (W F10) 231 (B F14) 232 (W F13) 233 (B A12) 234 (W A11) 235 (B F12) 236 (W E16) 237 (B E15)
238 (W F13) 239 (B B11) 240 (W B10) 241 (B F12) 242 (W D9) 243 (B C9) 244 (W F13) 245 (B J18) 246 (W K18) 247 (B F12) 24
8 (W G11) 249 (B G8) 250 (W A14) 251 (B E8) 252 (W J10) 253 (B K10) 254 (W E17) 255 (B O17) 256 (W S13) 257 (B F7) 258 (
W B14) 259 (B J9) 260 (W E14) 261 (B T12) 262 (W L5) 263 (B L4) 264 (W N5) 265 (B M6) 266 (W O5) 267 (B N7) 268 (W P4) 2
69 (B T13) 270 (W S3) 271 (B S2) 272 (W S4) 273 (B Q5) 274 (W Q7) 275 (B P8) 276 (W T11) 277 (B P2) 278 (W T2) 279 (B R2
) 280 (W F13) 281 (B A6) 282 (W D14) 283 (B E5) 284 (W L3) 285 (B L5) 286 (W C2) 287 (B B1) 288 (W O6) 289 (B O7) 290 (W
 O1) 291 (B B7) 292 (W D4) 293 (B P1) 294 (W N1) 295 (B A9) 296 (W L18) 297 (B P9) 298 (W L15) 299 (B N15) 300 (W M17) 3
01 (B L17) 302 (W N16) 303 (B M17) 304 (W K11) 305 (B N15) 306 (W M14) 307 (B S14) 308 (W T15) 309 (B Q2) 310 (W Q1) 311
 (B M8) 312 (W M12) 313 (B E13) 314 (W H2) 315 (B S19) 316 (W S6) 317 (B O19) 318 (W P19) 319 (B L1) 320 (W T9) 321 (B G
2) 322 (W Q10) 323 (B A16) 324 (W B19) 325 (B J16) 326 (W P15) 327 (B S9) 328 (W M1) 329 (B C15) 330 (W N19) 331 (B E15)
 332 (W D15) 333 (B R19) 334 (W H1) 335 (B T16) 336 (W P18) 337 (B G14) 338 (W A10) 339 (B E19) 340 (W N4) 341 (B D12) 3
42 (W B13) 343 (B T19) 344 (W A7) 345 (B S13) 346 (W G3) 347 (B A2) 348 (W N16) 349 (B D18) 350 (W L10) 351 (B K1) 352 (
W C18) 353 (B O8) 354 (W H17) 355 (B J8) 356 (W S5) 357 (B G19) 358 (W T10) 359 (B P5) 360 (W A19) 361 (B F14) 362 (W A1
3) 363 (B B18) 364 (W O10) 365 (B F6) 366 (W G17) 367 (B K19) 368 (W D19) 369 (B A3) 370 (W J19) 371 (B F19) 372 (W N10)
 373 (B P3) 374 (W E3) 375 (B S8) 376 (W D2) 377 (B A8) 378 (W C19) 379 (B F1) 380 (W N3) 381 (B R7) 382 (W Q19) 383 (B
N6) 384 (W T7) 385 (B C14) 386 (W Q18) 387 (B A1) 388 (W F16) 389 (B A17) 390 (W A12) 391 (B C16) 392 (W H16) 393 (B G1)
 394 (W H19) 395 (B G13) 396 (W L19) 397 (B M19) 398 (W A18) 399 (B R15) 400 (W T8) 401 (B S1) 402 (W N19) 403 (B T18) 4
04 (W J18) 405 (B N18) 406 (W S15) 407 (B T3) 408 (W J1) 409 (B D9) 410 (W F12) 411 (B S17) 412 (W T14) 413 (B N8) 414 (
W S10) 415 (B O4) 416 (W S8) 417 (B R18) 418 (W H3) 419 (B P4) 420 (W T6) 421 (B T1) 422 (W K19) 423 (B L1) 424 (W P19)
425 (B T15) 426 (W E18) 427 (B T14) 428 (W Q18) 429 (B E19) 430 (W A7) 431 (B Q7) 432 (W D18) 433 (B C3) 434 (W A2) 435
(B N15) 436 (W J16) 437 (B B1) 438 (W B3) 439 (B D13) 440 (W G19) 441 (B D7) 442 (W F17) 443 (B N19) 444 (W F2) 445 (B A
6) 446 (W G1) 447 (B H9) 448 (W B18) 449 (B Q19) 450 (W G2) 451 (B T4) 452 (W F19) 453 (B C1) 454 (W A1) 455 (B A4) 456
(W pass) 457 (B A3) 458 (W T5) 459 (B A7) 460 (W F15) 461 (B G14) 462 (W K12) 463 (B T2) 464 (W F14) 465 (B pass) 466 (W
 J11) 467 (B J12) 468 (W B2) 469 (B L14) 470 (W E19) 471 (B B4) 472 (W C3) 473 (B P12) 474 (W J14) 475 (B K14) 476 (W F1
) 477 (B C1) 478 (W K15) 479 (B pass) 480 (W K1) 481 (B R14) 482 (W C13) 483 (B N16) 484 (W M2) 485 (B K14) 486 (W S9) 4
87 (B D12) 488 (W C15) 489 (B E13) 490 (W A5) 491 (B F7) 492 (W J6) 493 (B A8) 494 (W D13) 495 (B S15) 496 (W A4) 497 (B
 E7) 498 (W B8) 499 (B F6) 500 (W D9) 501 (B E8) 502 (W G6) 503 (B C7) 504 (W B7) 505 (B K8) 506 (W H9) 507 (B A7) 508 (
W H7) 509 (B E9) 510 (W B4) 511 (B E6) 512 (W B9) 513 (B H8) 514 (W J13) 515 (B C8) 516 (W P18) 517 (B S17) 518 (W T17)
519 (B A9) 520 (W O17) 521 (B L16) 522 (W E15) 523 (B K10) 524 (W T12) 525 (B T16) 526 (W N17) 527 (B R13) 528 (W D10) 5
29 (B R17) 530 (W G8) 531 (B R15) 532 (W L14) 533 (B G9) 534 (W O18) 535 (B S12) 536 (W T19) 537 (B S13) 538 (W Q13) 539
 (B J9) 540 (W A3) 541 (B Q19) 542 (W B1) 543 (B S16) 544 (W C1) 545 (B N11) 546 (W S18) 547 (B D8) 548 (W L1) 549 (B D6
) 550 (W Q14) 551 (B R18) 552 (W M19) 553 (B O12) 554 (W J7) 555 (B T18) 556 (W B11) 557 (B P12) 558 (W K14) 559 (B C9)
560 (W C14) 561 (B R14) 562 (W M16) 563 (B O19) 564 (W G10) 565 (B P11) 566 (W T13) 567 (B N19) 568 (W R1) 569 (B O4) 57
0 (W K3) 571 (B M17) 572 (W M7) 573 (B R3) 574 (W P5) 575 (B N8) 576 (W R12) 577 (B T1) 578 (W R7) 579 (B R2) 580 (W T2)
 581 (B Q4) 582 (W pass) 583 (B N18) 584 (W P13) 585 (B N6) 586 (W T4) 587 (B K4) 588 (W Q8) 589 (B R19) 590 (W L17) 591
 (B M6) 592 (W O2) 593 (B K5) 594 (W O16) 595 (B D7) 596 (W J8) 597 (B N16) 598 (W T3) 599 (B Q2) 600 (W L6) 601 (B Q7)
602 (W pass) 603 (B T14) 604 (W J12) 605 (B pass) 606 (W M8) 607 (B Q6) 608 (W L5) 609 (B M5) 610 (W P8) 611 (B T15) 612
 (W O7) 613 (B P3) 614 (W N7) 615 (B N9) 616 (W S1) 617 (B J4) 618 (W S15) 619 (B O8) 620 (W E5) 621 (B Q5) 622 (W Q12)
623 (B G7) 624 (W Q17) 625 (B S19) 626 (W L4) 627 (B K5) 628 (W A6) 629 (B P9) 630 (W P17) 631 (B S14) 632 (W A9) 633 (B
 P4) 634 (W K9) 635 (B O13) 636 (W A8) 637 (B S15) 638 (W A15) 639 (B T19) 640 (W K4) 641 (B S18) 642 (W A17) 643 (B Q3)
 644 (W E13) 645 (B P1) 646 (W F5) 647 (B Q11) 648 (W G13) 649 (B M5) 650 (W C10) 651 (B C9) 652 (W E9) 653 (B M6) 654 (
W F7) 655 (B pass) 656 (W E6) 657 (B pass) 658 (W T17) 659 (B T18) 660 (W G14) 661 (B S17) 662 (W T1) 663 (B S19) 664 (W
 C8) 665 (B S14) 666 (W C7) 667 (B P6) 668 (W A16) 669 (B S13) 670 (W O11) 671 (B P7) 672 (W E7) 673 (B Q19) 674 (W T16)
 675 (B O13) 676 (W C16) 677 (B T14) 678 (W S15) 679 (B R13) 680 (W N6) 681 (B D8) 682 (W J4) 683 (B R17) 684 (W G7) 685
 (B S16) 686 (W K10) 687 (B pass) 688 (W O9) 689 (B S12) 690 (W G9) 691 (B T15) 692 (W T17) 693 (B S18) 694 (W P11) 695
(B pass) 696 (W F6) 697 (B T19) 698 (W J9) 699 (B S2) 700 (W A7) 701 (B D7) 702 (W P2) 703 (B M6) 704 (W Q4) 705 (B Q3)
706 (W P9) 707 (B P12) 708 (W R19) 709 (B T16) 710 (W P1) 711 (B T17) 712 (W N15) 713 (B Q2) 714 (W D12) 715 (B N8) 716
(W P4) 717 (B P6) 718 (W Q7) 719 (B N9) 720 (W R15) 721 (B R18) 722 (W E8) 723 (B R3) Game has ended.
Score: W+294.5
Winner: white
Uploading game: 70a729a00f214f60b22a9516f09cfd40.sgf for network 05d10f27e549f3d1e34bc449d406fba18014f262d395cd67cec9578
29ef399df
Game data 97e6604673c7b600a26af0a2f170f20f8af007bae8fa1d4dc83ac3ee8260bacc stored in database
9 game(s) (9 self played and 0 matches) played in 1395 minutes = 9304 seconds/game, 39059 ms/move, last game took 44492
seconds.
```
