### ISSUE TITLE
How to set up Leela better

### ISSUE THREAD

**Issue by wuchaopmp** [gcp/leela-zero#2073]
How to set up Leela better
Hello!
My computer: B450 motherboard, AMD R2700 CPU, 2*16G memory, RTX2070 graphics card.
When I use sabaki to play against Leela, I don't use other programs. Every 60-180 seconds, the GPU usage is less than 10%.
When running autogtp, the GPU usage is less than 10%.

To fully utilize the performance of the computer, how to configure it best?

My leelaStart_ELF file is as follows:
@echo off
Leelaz.exe -g -t2 --noponder -w networks/elf

**Comment by Splee99** [comment]
Maybe change -t2 to -t8.

**Comment by Ttl** [comment]
LZ should use 100% of GPU with default parameters. If you are using Windows task manager to check GPU use make sure to switch to compute_0 graph instead by clicking on small down arrow. The default graph doesn't measure compute use.

**Comment by gcp** [comment]
Going to close this on the assumption that the task manager had another victim.
