### ISSUE TITLE
can't load file or paste sgf.  it hangs

### ISSUE THREAD

**Issue by ericosman** [gcp/leela-zero#2075]
Hi,

Whenever I try to load an sgf file or paste in an sgf, it hangs.  Here's details:

I'm on windows 10.  I can start leela zero and it says something like

Leela zero is loading  . . .
press o for menu

As soon as I attempt to load an sgf file or paste an sgf, the "Leela zero is loading . . ." message is still there but the "press o for menu" is no longer there.  And, more importantly, I do not see the position I just attempted to load, AND the task manager shows that leela zero is using 30% of my machine.

Is this just a situation where I need to be patient and wait?

Or do I need to change a config?

**Comment by gcp** [comment]
>Leela zero is loading . . .
press o for menu

This isn't Leela Zero. What GUI are you using?

**Comment by ericosman** [comment]
As mentioned in the original comment, leela zero is hanging when I try to load an sgf file or paste in sgf.

In response to your questioning whether I really have leela zero, I loaded something called lizzie that I was told contains leela zero.  The UI says leela zero.

Here are pictures of my folder and the leela zero UI (let me know if you can't see them)
![image](https://user-images.githubusercontent.com/40031348/49949199-0f165600-fec3-11e8-89cc-9ae3deb148c1.png)

![image](https://user-images.githubusercontent.com/40031348/49949213-1b021800-fec3-11e8-971f-074e64f927c4.png)

**Comment by Ttl** [comment]
You are looking for: https://github.com/featurecat/lizzie.

**Comment by ericosman** [comment]
Hi Ttl.  Are you saying you looked at the picture of my folder and you don't think I used the correct lizzie download?

**Comment by roy7** [comment]
@ericosman They are saying Lizzie tech support is through the Lizzie github, Lizzie is a front end for Leela Zero (like Sabaki or others) but the Leela Zero github isn't the right place to solve Lizzie problems.
