### ISSUE TITLE
 consider use TensorFlow Lite  for mobile?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#2076]
https://github.com/gcp/leela-zero/issues/1679#issuecomment-446135294
@y-ich says 
iPhone 5s, 1.1 N/s
iPhone 6 Plus, 1.4 N/s
iPhone X, 13-15 N/s
iPhone Xs Max, 130-160 N/s
iPad Air 2, 2.6 N/s
for TensorFlow Lite
newer gpu can speed up very largely

**Comment by y-ich** [comment]
Hi.

These values are not by TensorFlow Lite, by Core ML.
In the case of Android, using TensorFlow Lite is maybe the easiest way to enable AI engines.
So I mentioned it.
My iOS app uses Core ML to enable Neural Network Engines.

**Comment by gcp** [comment]
Anyone can submit a backend and we'll integrate it if the licensing is appropriate. Just making topics about them doesn't achieve anything.
