### ISSUE TITLE
wrong move count or score of 2nd game?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#2079]
http://zero.sjeng.org/match-games/5c138ad7469ad81ed7b80260

w+7.5 28 moves

**Comment by Glrr** [comment]
First move on the first line! Indeed, there is something wrong with this game.

**Comment by l1t1** [comment]
got it, double PASS, so win by 7.5

**Comment by pliuphys** [comment]
Also game 32. There's something wrong with this client #2.

**Comment by wonderingabout** [comment]
there are 2 issues here : 

1) the known double pass issue : should not happen in leela zero match games (full strength no noise)
2) most likely a corrupted or malicious client uploading fake games

**Comment by l1t1** [comment]
http://zero.sjeng.org/view/05609508c5a98e5e0b6debbe9920b2c943df824c2ad398aa84935a16e2cdfc10?viewer=wgo
4 moves double pass w+7.5
