### ISSUE TITLE
suggest pause new match for lz195 and let it play more self games

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#2080]
since it has proved its strength, maybe new weights cannot win it in a short peroid, to save the computer power, we shorten useless match games and let it learn more from itself

**Comment by wonderingabout** [comment]
the benefit of saving match game resource is very marginal and minimal 

that would be 200-300x3 games/day : 
we would save arround 1000 selfplay games per day

really, it's not that big of a gain

**Comment by alreadydone** [comment]
Also note that if the challenger is far behind the match will be terminated early.

**Comment by l1t1** [comment]
223b is as good as lz195 in first 200 games

**Comment by l1t1** [comment]
6523 is as good as lz 195 now
