### ISSUE TITLE
autogtp + multiple graphics cards

### ISSUE THREAD

**Issue by mknippen** [gcp/leela-zero#2081]
Hello,

Does autogtp currently have support for multiple graphics cards? I happen to have some mining hardware with 6x GPU's that I would love to have help out on this. They're running linux and I can get them setup, I just want to know if it would be only using one card or all of them. I have machines with AMD and NVIDIA

**Comment by mknippen** [comment]
A similar question, can I use Leela-zero itself with multiple cards? For example, with analyzing a game with GoReviewPartner?

**Comment by alreadydone** [comment]
Just add `--gpu 0 --gpu 1 --gpu 2 --gpu 3 --gpu 4 --gpu 5` to the command (of either leelaz or autogtp).

**Comment by alreadydone** [comment]
And for autogtp, you may use `-g 2` for example to play 2 games at the same time (on each GPU, I think).
