### ISSUE TITLE
two strange games between lz 195 and elfv0

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#2082]
from http://www.yss-aya.com/cgos/19x19/cross/LZ_195_8b28_p1.html
1. http://www.yss-aya.com/cgos/19x19/SGF/2018/12/16/499107.sgf 195 win by kill a big dragon
2. http://www.yss-aya.com/cgos/19x19/SGF/2018/12/16/499167.sgf elf win by kill a lot

**Comment by l1t1** [comment]
it seems that lz 195 was set to no re-sign.

**Comment by gcp** [comment]
I don't get the point of posting CGOS games. They could be run by anyone with anything and any settings.
