### ISSUE TITLE
why weight 0b20 win lz 195 more at short  games?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#2086]
http://zero.sjeng.org/match-games/5c199f61469ad81ed7c1b29c
it is very similar as lz 195 win elfv1 more at short  games

**Comment by l1t1** [comment]
winner|substr(score,1,1)|mcnt/100|count(*)
0b203fd1|B|1|12
0b203fd1|B|2|42
0b203fd1|B|3|8
0b203fd1|W|1|50
0b203fd1|W|2|60
0b203fd1|W|3|10
8b28fe3c|B|1|13
8b28fe3c|B|2|32
8b28fe3c|B|3|17
8b28fe3c|W|1|36
8b28fe3c|W|2|50
8b28fe3c|W|3|30

**Comment by l1t1** [comment]
sqlite> .read d:/elfv1.sql
winner|substr(score,1,1)|mcnt/100|count(*)
8b28fe3c|B|0|27
8b28fe3c|B|1|54
8b28fe3c|B|2|37
8b28fe3c|B|3|5
8b28fe3c|W|0|38
8b28fe3c|W|1|67
8b28fe3c|W|2|36
8b28fe3c|W|3|2
d13c4099|B|1|10
d13c4099|B|2|41
d13c4099|B|3|11
d13c4099|W|1|8
d13c4099|W|2|54
d13c4099|W|3|12

**Comment by Marcin1960** [comment]
@l1t1 

What are "short games"?

**Comment by l1t1** [comment]
moves less than 200 is short

**Comment by thynson** [comment]
The 195th weight is trained by @bjiyxo, its value head seems to be more accurate in the ending stage.
Maybe only @bjiyxo could explain the reason.
