### ISSUE TITLE
some entries inconsistent in the elo graph data file

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#2092]
https://zero.sjeng.org/data/elograph.json
for test games,
some are pattern like these
{"rating":11909,"net":11400000.11909,"sprt":"TEST","hash":"92297f"},
{"rating":12467,"net":10106413.12467,"sprt":"TEST","hash":"61c6d7"},
but others are
{"rating":0,"net":11240000,"sprt":"TEST","hash":"8b28fe","best":false},
or
{"rating":12902,"net":11069138.12902,"sprt":"TEST","hash":"9d4ac6","best":false},

**Comment by roy7** [comment]
Those are probably ones uploaded by someone by hand, and they didn't set the best flag. Which doesn't matter for a test network anyway really.
