### ISSUE TITLE
would like to use "lz-setoption" if possible

### ISSUE THREAD

**Issue by hwj-111** [gcp/leela-zero#2099]
On CGOS, there is a gobot 
http://www.yss-aya.com/cgos/19x19/cross/LZ_195_8b28_p1.html
run with a "no-resign" settings, which means it plays a lot of "shitting" moves and wins by "TIME".

I would like to change my LZ setting (to a faster setting) on the fly when play with this "no-resign" bot (by hacking some cgos python client if possible).

Not sure if I can use "lz-setoption".  Could someone help on how to use this option (could not find a doc about the option)

**Comment by gcp** [comment]
Do something like 

```
lz-setoption name visits value 1000
```

**Comment by gcp** [comment]
These are the supported settings:

```
option name Maximum Memory Use (MiB) type spin default 2048 min 128 max 131072
option name Percentage of memory for cache type spin default 10 min 1 max 99
option name Visits type spin default 0 min 0 max 1000000000
option name Playouts type spin default 0 min 0 max 1000000000
option name Lagbuffer type spin default 0 min 0 max 3000
option name Resign Percentage type spin default -1 min -1 max 30
option name Pondering type check default true
```
