### ISSUE TITLE
Network.cpp:30:10: fatal error: 'boost/utility.hpp' file not found

### ISSUE THREAD

**Issue by wensdong** [gcp/leela-zero#21]

**Comment by gcp** [comment]
You need to install boost as described in the README.

**Comment by wensdong** [comment]
Installed as following:

"src wensdong12$ brew list |grep 'boost'
boost
boost-python"

**Comment by wensdong** [comment]
I also put a path and link with link "brew link boost"
echo $PATH
/usr/local/include:/usr/local/Cellar/boost/1.65.1/include:/usr/local/Cellar/boost/1.65.1/include/boost:/

**Comment by gcp** [comment]
Probably needs a 
CXXFLAGS += -I/usr/local/include/

in the Makefile?

**Comment by wensdong** [comment]
Thanks! that solved the issue.
