### ISSUE TITLE
Getting clinfo to list my graphics card on Linux Mint

### ISSUE THREAD

**Issue by Phelanpt** [gcp/leela-zero#2103]
This is not a Leela Zero problem per se, but I haven't been very successful finding help elsewhere, so maybe someone here might be able to help.
When I run clinfo, I get "Number of platforms   0", and when I run LZ's ./tests, I get `Running main() from gtest_main.cc
[==========] Running 11 tests from 2 test cases.
[----------] Global test environment set-up.
BLAS Core: built-in Eigen 3.3.5 library.
Detecting residual layers...v1...8 channels...1 blocks.
Initializing OpenCL (autodetecting precision).
OpenCL: clGetPlatformIDs
unknown file: Failure
C++ exception with description "clGetPlatformIDs" thrown in auxiliary test code (environments or event listeners).
`
lspci can see my card,  "lspci | grep VGA" gives me `01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV410/M26 [Mobility Radeon X700]
`
I've tried to install any possibly missing OpenCL packages as per the Debian step in this guide: https://wiki.tiker.net/OpenCLHowTo#Debian
but I'm not having any success. :/
Can anyone point me in the right direction? Is my graphics card not compatible with OpenCL? Is there another step I'm missing?

Will try to build the cpu only version in the meantime. :/

**Comment by ihavnoid** [comment]
I am not sure but RV410 seems to be a very old graphics card which predates OpenCL.  I don't think the GPU is capable of running this.

Is the hardware really a RV410 GPU or is it some artifact of some unsupported arcane hardware?

**Comment by Phelanpt** [comment]
It might be, this is an old laptop I was thinking of repurposing into a leela-zero server. It's a Toshiba Satellite M70-320, with a 2 Ghz single core Intel Pentium M processor, and 2 GB of RAM.
I tried compiling the cpu version, and it seems like it works, but it fails the ./tests with 
`Running main() from gtest_main.cc
[==========] Running 11 tests from 2 test cases.
[----------] Global test environment set-up.
BLAS Core: built-in Eigen 3.3.5 library.
Detecting residual layers...v1...8 channels...1 blocks.
Initializing CPU-only evaluation.
LOW MEMORY SETTINGS! Couldn't set default memory limits.
The network you are using might be too big
for the default settings on your system.
unknown file: Failure
C++ exception with description "Error setting memory requirements." thrown in auxiliary test code (environments or event listeners).
`
So it's probably too old for this. :/ I'll try to find another option.
