### ISSUE TITLE
Canadian time control

### ISSUE THREAD

**Issue by roy7** [gcp/leela-zero#2105]
The way OGS handles fisher time controls is to convert it into a Canadian byoyomi and tell the bot settings that will effectively work the same. I notice, though, if someone has a large main time (30 minutes) and a small period (20 seconds), Leela is willing to spend the entire main time on every move. Very unlike what it does with normal byoyomi.

For example:

> zeroslowgtp.js:570             [16149 15904111] 11:02:24 >>> kgs-time_settings canadian 1780 20 1
> zeroslowgtp.js:570             [16149 15904111] 11:02:24 >>> time_left black 1917 1
> zeroslowgtp.js:570             [16149 15904111] 11:02:24 >>> time_left white 824 1
> zeroslowgtp.js:570             [16149 15904111] 11:02:24 >>> genmove white
> zeroslowgtp.js:570             [16149 15904111] 11:02:24 <<< =
> zeroslowgtp.js:578             [16149 15904111] 11:02:24 stderr: Thinking at most 821.0 seconds...

The 3 seconds missing is from --lagbuffer. Is this working as intended, that zero main time will be saved? If I didn't have my 25000 visit cap on RoyalZeroSlow, it'd have been willing to think 30 minutes on move 1.

**Comment by roy7** [comment]
I notice timemanage isn't kicking in, even if a single forced move got all 25K visits. So I'm concluding Leela thinks we're already in byoyomi time and to ignore timemanage and trying to save main time for later.

In Canadian should we treat any time above the period time as 'main time' with timemanage and saving time logic still turned on?

I wonder if this was true Canadian, like 60 seconds to play 5 stones, how Leela would handle the time at that point.

**Comment by wonderingabout** [comment]
thats why i prefer fischer time

easier to play with, a lot less stressful, easier to program and manage
but that doesnt answer your question though

**Comment by gcp** [comment]
Going to mark this bug as it seems to at least warrant more investigation.

**Comment by Hersmunch** [comment]
Is this the problem? When the time is set there is a byoyomi stone included e.g. `time_left black 1917 1`. So from `GTP::execute()`:
```
...
    } else if (command.find("time_left") == 0) {
...
        cmdstream >> tmp >> color >> time >> stones;
...
            game.adjust_time(icolor, time * 100, stones);
```
and `TimeControl::adjust_time()`:
```
    m_remaining_time[color] = time;
...
    if (stones) {
        // stones are only given in byo-yomi
        m_inbyo[color] = true;
    }
```
Looking at the KGS GTP docs:
http://www.weddslist.com/kgs/how/kgsGtp.html

> time_left — Optional
> Used as normal.

and then GTP spec:
http://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html#SECTION00073000000000000000

> arguments | color time stones
> -- | --
>   | color color - Color for which the information applies.
>   | int time - Number of seconds remaining.
>   | int stones - Number of stones remaining.
> effects | none
> output | none
> fails | syntax error
> comments | While the main time is counting, the number of remaining stones is given as 0.

That looks like a bad command and no bug in leelaz to me.

**Comment by roy7** [comment]
AHHHHHHHH. Thank you! I need to rethink proper way to do this then.
