### ISSUE TITLE
Why did black resign in this match game?

### ISSUE THREAD

**Issue by trnaeo** [gcp/leela-zero#2108]
Match 8e04d0f1 VS 56becd72
Game 104
https://zero.sjeng.org/viewmatch/f9cae4e1103cb6ffe761af9f477dc0efda8ae6aaa35a22863528d12ee0849b45.sgf

When counting black wins by 0.5 point, why did black resign?

**Comment by tterava** [comment]
Final moves would be: B J6 - W L8 - B Q10 - W M16
White wins by 0.5 points.

**Comment by trnaeo** [comment]
Thank you!
