### ISSUE TITLE
why p400 win p1 more, but v1600 lost p1 more

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#2111]
http://www.yss-aya.com/cgos/19x19/cross/LZ_197_56be_p400.html
LZ_195_8b28_p1 2862 7 / 7 100.00 

http://www.yss-aya.com/cgos/19x19/cross/lz196_3ghwj_v016.html
LZ_195_8b28_p1 2864 1 / 14 7.14

**Comment by Glrr** [comment]
Are you sure this is v1600? v016 probably means version 0.16. I don't understand 3ghwj.

**Comment by Splee99** [comment]
One thing is for sure. p1 can't read any ladders. So it's hard to compare its strength with for example p400, because you never know when a ladder appears in a game.

**Comment by l1t1** [comment]
the 2nd and 3rd link shows 196v016 > 195p400 and 196v016 <195p1 and 195p400 >195p1

**Comment by l1t1** [comment]
could you tell me the parameter of http://www.yss-aya.com/cgos/19x19/cross/lz196_3ghwj_v016.html @hwj-111
https://github.com/gcp/leela-zero/issues/2099#issue-394080564

**Comment by hwj-111** [comment]
@l1t1 
My machine setup: CPU i7-2600 (@l1t1 3.4GHz) and 2xGTX1070 + 1xGTX1060
The command line:
**C:\LocalApp\leela-zero-0.16-win64\leelaz.exe -g -t 18 -w C:\LocalApp\leela-zero-0.16-win64\network196_20181221_939ebb.gz -r 5 --gpu 0 --gpu 1 --gpu 2 -b 30 --noponder --precision half**

**Comment by Ishinoshita** [comment]
@l1t1 For "196v016 <195p1", all boil down to a time control issue.

195p1 wins by time, each time, when 196v016's clock reaches 15'00'', absolute time limit (seems 195p1 does not resign, although far behind;  games stretch until 420+ moves, where v016 reaches time limit). 

Nothing to do with intrinsic strength of p1. The paradox of transitivity rule violation is just an artifact, here.

**Comment by hwj-111** [comment]
I don't understand  why the 195p1 owner uses the "never-resign" setting.  What kind of knowledge s/he can gain from the results of such settings？

**Comment by l1t1** [comment]
LZ_195_8b28_p1 setting finally beated your setting 
lz196_3ghwj_v016 3549 13 / 14 92.86 
lz188_3ghwj_v016 3473 4 / 5 80.00

**Comment by l1t1** [comment]
but those setting beated LZ_195_8b28_p1 
LZ_195_8b28_v1601 3297 1 / 16 6.25 
LZ_197_56be_p400 3260 0 / 23 0.00 
LZ_d13c_ELFv1_p800 3247 7 / 193 3.63 
LZ_62b541_ELF_p800 3213 2 / 37 5.41 
LZ_195_8b28_p400 3182 1 / 78 1.28 
LZ_198_87cb_p400 3145 0 / 8 0.00

**Comment by Ishinoshita** [comment]
@l1t1 I'm afraid it is very hazardous to draw any conclusion from cgos results unless you have clear evidence of what settings have been actually used to play those games. Just looking at raw results and guessing settings from the bot names doesn't provide such level of confidence, as examplified by LZ195p1'paradox' here above.
