### ISSUE TITLE
YOUTUBE SHARING! Use weight #198 with 16,000 visists analysis Agzero_vs_Agmaster game 1-20 

### ISSUE THREAD

**Issue by ainixingo** [gcp/leela-zero#2118]
1 https://www.youtube.com/watch?v=Zgp9Mv0wnoM&t=533s

2 https://www.youtube.com/watch?v=uLYxkeU7TnU&t=849s

3 https://www.youtube.com/watch?v=Q-CRidd3T44

4 https://www.youtube.com/watch?v=PGIBkRyb7ek

Welcome to subscribe!

**Comment by Ttl** [comment]
This isn't the right place for advertising your Youtube channel.
