### ISSUE TITLE
why one often pass and the other not do so

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#212]
Infinite thinking time set.
1 (Q10) 2 (H17) 3 (O17) 4 (S7) 5 (A4) 6 (J7) 7 (B16) 8 (S10) 9 (R18) 10 (R11) 11 (P3) 12 (B12) 13 (L12) 14 (A13) 15 (F9)
 16 (Q5) 17 (J18) 18 (Q3) 19 (L11) 20 (F16) 21 (H12) 22 (P11) 23 (F17) 24 (S8) 25 (N1) 26 (Q14) 27 (P6) 28 (R16) 29 (D7)
 30 (Q16) 31 (N2) 32 (T13) 33 (K12) 34 (L3) 35 (K5) 36 (Q8) 37 (Q2) 38 (P15) 39 (P17) 40 (R6) 41 (L19) 42 (R3) 43 (Q19)
44 (P18) 45 (Q12) 46 (J16) 47 (O12) 48 (R13) 49 (A15) 50 (Q13) 51 (K7) 52 (T16) 53 (N16) 54 (M9) 55 (L16) 56 (R5) 57 (M1
5) 58 (P12) 59 (L14) 60 (D17) 61 (G19) 62 (S12) 63 (H5) 64 (S15) 65 (F8) 66 (J17) 67 (H4) 68 (R2) 69 (J14) 70 (M6) 71 (D
15) 72 (M14) 73 (L6) 74 (D10) 75 (F11) 76 (B17) 77 (E4) 78 (P13) 79 (F3) 80 (K18) 81 (J8) 82 (M16) 83 (M13) 84 (D12) 85
(S4) 86 (A6) 87 (N14) 88 (B15) 89 (G4) 90 (J5) 91 (K15) 92 (G15) 93 (H15) 94 (J15) 95 (M7) 96 (N17) 97 (M17) 98 (Q6) 99
(M3) 100 (P4) 101 (N18) 102 (M4) 103 (G18) 104 (P2) 105 (Q11) 106 (F6) 107 (J6) 108 (N9) 109 (J4) 110 (C18) 111 (C4) 112
 (C16) 113 (L4) 114 (B14) 115 (H7) 116 (H16) 117 (M5) 118 (B1) 119 (N4) 120 (E5) 121 (G12) 122 (P7) 123 (N6) 124 (H18) 1
25 (O3) 126 (A3) 127 (O7) 128 (J9) 129 (D3) 130 (K9) 131 (L9) 132 (O8) 133 (E11) 134 (F5) 135 (K10) 136 (E18) 137 (C6) 1
38 (J11) 139 (G16) 140 (H14) 141 (E13) 142 (K19) 143 (B7) 144 (L8) 145 (N12) 146 (L10) 147 (B9) 148 (E19) 149 (D11) 150
(P10) 151 (D2) 152 (N10) 153 (H13) 154 (P19) 155 (G14) 156 (O11) 157 (J12) 158 (M8) 159 (Q17) 160 (G17) 161 (O2) 162 (T1
) 163 (K17) 164 (J19) 165 (B11) 166 (C13) 167 (M10) 168 (K8) 169 (C10) 170 (R4) 171 (M11) 172 (L9) 173 (L18) 174 (T6) 17
5 (H15) 176 (F14) 177 (E16) 178 (G8) 179 (C11) 180 (R8) 181 (E12) 182 (D16) 183 (N11) 184 (P1) 185 (E15) 186 (N7) 187 (C
14) 188 (B19) 189 (H10) 190 (Q4) 191 (C12) 192 (P5) 193 (L2) 194 (G13) 195 (H14) 196 (J3) 197 (D13) 198 (G16) 199 (N8) 2
00 (H8) 201 (E10) 202 (F12) 203 (P8) 204 (E7) 205 (F13) 206 (Q7) 207 (E14) 208 (G10) 209 (R9) 210 (C15) 211 (F15) 212 (G
9) 213 (B13) 214 (C9) 215 (C8) 216 (J2) 217 (S9) 218 (D6) 219 (E17) 220 (T3) 221 (D14) 222 (R10) 223 (S11) 224 (F18) 225
 (D12) 226 (J7) 227 (O9) 228 (C13) 229 (O8) 230 (H11) 231 (B13) 232 (L7) 233 (R12) 234 (H3) 235 (F7) 236 (B10) 237 (D8)
238 (H6) 239 (S13) 240 (pass) 241 (E8) 242 (C13) 243 (D9) 244 (B13) 245 (M12) 246 (Q9) 247 (R12) 248 (M2) 249 (Q12) 250
(O4) 251 (G6) 252 (N5) 253 (M4) 254 (H19) 255 (M6) 256 (J18) 257 (F12) 258 (G11) 259 (C9) 260 (O13) 261 (N3) 262 (J13) 2
63 (K13) 264 (J10) 265 (G7) 266 (A9) 267 (O5) 268 (T9) 269 (S9) 270 (Q11) 271 (R12) 272 (R9) 273 (A10) 274 (Q12) 275 (B1
0) 276 (R7) 277 (B8) 278 (P14) 279 (C7) 280 (S9) 281 (E6) 282 (F4) 283 (E7) 284 (R12) 285 (G5) 286 (Q1) 287 (A12) 288 (A
5) 289 (G3) 290 (A11) 291 (D5) 292 (M1) 293 (A12) 294 (L1) 295 (A11) 296 (H2) 297 (F14) 298 (F19) 299 (G18) 300 (N15) 30
1 (A8) 302 (D18) 303 (S6) 304 (C5) 305 (M16) 306 (K2) 307 (O6) 308 (K4) 309 (G2) 310 (O14) 311 (T12) 312 (G1) 313 (H6) 3
14 (K1) 315 (O15) 316 (G19) 317 (K3) 318 (T5) 319 (L17) 320 (T11) 321 (L2) 322 (S11) 323 (L3) 324 (M18) 325 (A9) 326 (T4
) 327 (M19) 328 (T12) 329 (P16) 330 (S14) 331 (P9) 332 (S1) 333 (H1) 334 (O10) 335 (Q18) 336 (T8) 337 (R14) 338 (T10) 33
9 (Q15) 340 (N13) 341 (C19) 342 (K11) 343 (R17) 344 (Q10) 345 (C1) 346 (A2) 347 (E1) 348 (R15) 349 (T17) 350 (S5) 351 (S
16) 352 (R14) 353 (T15) 354 (B6) 355 (N15) 356 (T18) 357 (T2) 358 (S19) 359 (B5) 360 (O1) 361 (M14) 362 (K16) 363 (J13)
364 (A19) 365 (T16) 366 (S6) 367 (A7) 368 (Q2) 369 (K14) 370 (N19) 371 (L13) 372 (S17) 373 (O19) 374 (T14) 375 (S16) 376
 (B4) 377 (T17) 378 (A18) 379 (A6) 380 (F4) 381 (S18) 382 (E3) 383 (K6) 384 (F10) 385 (T15) 386 (A1) 387 (R19) 388 (Q15)
 389 (F5) 390 (A17) 391 (pass) 392 (B18) 393 (pass) 394 (B2) 395 (O18) 396 (T7) 397 (F1) 398 (P18) 399 (P19) 400 (C3) 40
1 (O16) 402 (J8) 403 (D10) 404 (R1) 405 (N17) 406 (D19) 407 (S17) 408 (S3) 409 (N19) 410 (B3) 411 (C2) 412 (A3) <b>413 (pas
s) 414 (S13) 415 (A2) 416 (B1) 417 (pass) 418 (B2) 419 (pass) 420 (C17) 421 (B3) 422 (H9) 423 (pass) 424 (S2) 425 (E9) 4
26 (T2) 427 (A3) 428 (T16) 429 (pass) 430 (C19) 431 (pass) 432 (A14) 433 (pass) 434 (T15) 435 (pass) 436 (A16) 437 (pass
) 438 (B16)
</b>

**Comment by l1t1** [comment]
finally it did
439 (pass) 440 (H10) 441 (pass) 442 (S4) 443 (pass) 444 (pass) Game has ended.

**Comment by isty2e** [comment]
When one is ahead, it tends to pass frequently hoping its opponent to also pass thereby finishing the game. Since resignation is disabled at this point, the opponent does not like to resign and continue playing, so the games goes on and on until both players pass eventually.

**Comment by l1t1** [comment]
thank you
