### ISSUE TITLE
test match should passed at games 400,but show failed at games 420

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#2124]
http://zero.sjeng.org/match-games/5c2eb5427b7ec44f7cd494b0

**Comment by roy7** [comment]
8b23a0ea VS 92297ff2 was a test match between a new 15b and the old 15b. Test matches never promote. It can fall back under 55% as late games arrive, so it might not show 'PASS' anymore, but it doesn't affect anything since pass or fail has no effect on server if it's a test.

**Comment by l1t1** [comment]
I see, thanks

**Comment by l1t1** [comment]
normal match also has same quesion
https://zero.sjeng.org/match-games/5c2ffccd7b7ec44f7cd688ce
82a3e250 should pass at 409 or 410 , but failed yet

**Comment by l1t1** [comment]
and indeed, lz 199 is promoted, it's funny

**Comment by l1t1** [comment]
it shows 229 : 195 (54.01%) 424 / 400 PASS now ,
and showed 227 : 192 (54.18%) 419 / 400 fail at 5 min ago, is there a delay?

**Comment by roy7** [comment]
It's the most recent game from any match, not the match it won to promote. Right now it looks correct to me, if you still think it's wrong can you provide more detail or some screenshots?
