### ISSUE TITLE
Compile autoGTP under Visual Studio

### ISSUE THREAD

**Issue by earthengine** [gcp/leela-zero#214]
After the main engine was able to build under Visual Studio, I am looking at compiling autoGTP under Visual Studio. I have make it compiling however I have some issues to resolve. The following is the current status report.

* Two external executable are needed to run autoGTP: curl.exe and gzip.exe. As we only need a workable version, and the size is pretty small, I would like to have them reside in the solution folder (msvc), and make a build rule to copy them to the output folder.

* I can make it running with the above exes and it will download the network and self play. However, the saving code seem to have problem under windows (the effect is that no sgf/network dump being saved). Need to track this issue.

* So far I only run it without any command line arguments. A full test will need to see if all arguments works as expected.

**Comment by earthengine** [comment]
Meanwhile, there are requests to compile under Visual Studio 2013. This is not in my priority yet but anyone is welcome to contribute on it. I don't think it will be too hard to do; but my current machine is currently running out of space and didn't have Visual Studio 2013 installed.

**Comment by earthengine** [comment]
I look at the code of autogtp and I am afraid this is not its issue. It is leela-zero's. What it does is just send GTP command to the engine, but it is the engine's responsibility to save it. Now I have to look at the code to see what's wrong here

**Comment by brianprichardson** [comment]
Fiddling with MSVC 2013 was looking to me more difficult than just downloading MSVC 2017 Community Edition.  Note that the Build Tools are needed for Nuget in addition to the Visual Studio Community 2017 on the installer main menu.

**Comment by earthengine** [comment]
Build tools and Nuget additions, if not part of the out-of box MSVC 2013, it is the responsibility of the developer to install and configure them. What we can do is to provide a list of prerequisites and instructions to install them.

The committed code to help building on VS2013 therefore would assume those things are already available. So it will focus on getting the right Nuget packages, refer to the correct files, having the right compiling options etc.

**Comment by gcp** [comment]
Going to close this as the relevant projects were merged to master.
