### ISSUE TITLE
Weird games in testing

### ISSUE THREAD

**Issue by dzhurak** [gcp/leela-zero#2141]
This looks like a bug http://zero.sjeng.org/viewmatch/84ae1be3f2070da077a477be66737f8ef9693e4a8cb579fbd7cfab6898b555c0?viewer=wgo
It could be ok in train games but not in test.

**Comment by anonymousAwesome** [comment]
I've checked a few of the games from that client number (1) and they all seem to have the same problem.

https://zero.sjeng.org/viewmatch/84ae1be3f2070da077a477be66737f8ef9693e4a8cb579fbd7cfab6898b555c0?viewer=wgo

https://zero.sjeng.org/viewmatch/66b911a6c45508f21ba7184ee3b2f7d8541ab423740e66f84ba3e94220bb3673?viewer=wgo

https://zero.sjeng.org/viewmatch/78e4ef7b43697b69289a0e00a3415a0c8db83bd0538c379bd746cef28a98cfd6?viewer=wgo

https://zero.sjeng.org/viewmatch/eb630bf7599b29b10367db7d28a8c1a5960036b288439b2c247094837fe00d1f?viewer=wgo

https://zero.sjeng.org/viewmatch/b5a4f20afe040504dcfab7a918cfd2e95998f8e3f4b385315b19a2d44abc8aaf?viewer=wgo

etc. etc.  

Can we *please* get some sort of sanity-check implemented?  Even if it doesn't stop malicious actors, it could help in situations where somebody alters code, compiles it, then doesn't realize it's being sent to the network.

**Comment by anonymousAwesome** [comment]
Like, the server could quickly check each move against the most likely moves for that network (using the heatmap command?), and flag the network for manual inspection if too many of the generated moves are statistically unlikely.

**Comment by Ishinoshita** [comment]
What is very strange is that these games are weird only for Elf side. So, suspect a corrupted weight file. Or, this is really malicious client....

@anonymousawesome
>quickly check each move against the most likely moves for that network (using the heatmap command?)

Very computational heavy on server side, and would need substantial design /programming I suppose...

**Comment by dzhurak** [comment]
It happens again http://zero.sjeng.org/viewmatch/81367f13a17fc55f69bf137cedddea6f63c1010c2733035d7bb9ec1a2c3d1b04?viewer=wgo
