### ISSUE TITLE
CPU being used instead of GPU

### ISSUE THREAD

**Issue by thomasgha** [gcp/leela-zero#2149]
I'm using autogtp.exe to try to contribute to the project, but it just hammers my CPU while the GPU is cool. If I run 4 instances of it, it uses 100% of my 4-core, 64-bit 3.50 GHz Intel CPU. GPU seems not to be in use at all. 

The GPU is a Nvidia GeForce GTX 750 Ti. 

Any help would be appreciated.

**Comment by alreadydone** [comment]
Maybe you are using the cpuonly release (or compiled with USE_CPU_ONLY.

**Comment by thomasgha** [comment]
I'm using leela-zero-0.16-win64.zip

**Comment by gcp** [comment]
How are you determining that the GPU is not in use?

**Comment by langit7** [comment]
Check the compute0  graph from task manager not the 3d one

**Comment by thomasgha** [comment]
> How are you determining that the GPU is not in use?
> 
> If you run the engine by itself, it will print which GPU it selects.

Running autogtp.exe -t 16 the programs prints that it is 'Using 1 thread(s) for GPU'. GPU usage according to the ASUS software that came with the video card shows usage at 0.0 to 1 percent. Windows Task Manager < Performance shows the increase in CPU usage from ~4 percent to ~25 percent.

**Comment by thomasgha** [comment]
> 
> 
> Check the compute0 graph from task manager not the 3d one

**Comment by thomasgha** [comment]
How are you determining that the GPU is not in use?

If you run the engine by itself, it will print which GPU it selects.

Running autogtp.exe -t 16 the program prints that it is 'Using 1 thread(s) for GPU'. GPU usage according to the ASUS software that came with the video card shows usage at 0.0 to 1 percent. Windows Task Manager < Performance shows the increase in CPU usage from ~4 percent to ~25 percent.

**Comment by gcp** [comment]
AutoGTP doesn't have a -t option.

How does the compute0 graph in task manager look like? The GPU graph won't show anything if there's no on-screen rendering going on, you have to change the graph as described above.

**Comment by thomasgha** [comment]
Too much for me I guess. Good luck.
