### ISSUE TITLE
request only release main program

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#215]
dependence files are same in each version, so when upgrade, only need include autogtp.exe and leelaz.exe , make traffic smaller and save download time.

**Comment by Alderi-Tokori** [comment]
This goes against the spirit of what a release is, it should include everything needed to make the program run so someone only has to download the latest release to have a working program.

**Comment by l1t1** [comment]
in somewhere download 8MB file from github needs 20+ minutes and often fail

**Comment by Alderi-Tokori** [comment]
I see, maybe a second zip file only containing the binaries could be served at each release alongside the "complete" release (binaries + dependencies).

**Comment by l1t1** [comment]
or could you supply a mini version like https://github.com/ymgaq/AQ/releases does?

**Comment by roy7** [comment]
It makes sense for AQ to do that since his release is over 360M, whereas LZ is only 8M.

**Comment by Marcin1960** [comment]
There are new clients, who will not be bothered with _figuring out_ what they need. They get one package and can run it.

**Comment by PaulKlinger** [comment]
A better option might be to mirror the releases somewhere else, maybe on a Chinese server (I'm guessing that's where the problem is).

**Comment by l1t1** [comment]
[leelaz5.7z.zip](https://github.com/gcp/leela-zero/files/1544079/leelaz5.7z.zip)
let here as the mini version page
