### ISSUE TITLE
Go back to using LZ199_82a3e250 as it's stronger than LZ 200 or 201

### ISSUE THREAD

**Issue by jillybob** [gcp/leela-zero#2154]
Per V3 Eval graphs https://cloudygo.com/leela-zero-v3/eval-graphs , LZ199 is 81 ELO stronger than LZ network 201. Let's re-use 199 to create match games and be the new best network.

**Comment by sethtroisi** [comment]
@jillybob I'd suggest caution. I only played a handful of games (and with less than 1600 playouts) so the error on the chart is quite high.

I'll queue some more games between the last five models which should reduce uncertainty

**Comment by Friday9i** [comment]
@sethtroisi 
I'm currently testing LZ196 vs LZ195 @1600 visits after a panel of 2-moves openings (to avoid near-duplicate games and put nets in a wide diversity of situation): 200 games played already (ie 100 different 2-moves openings, balanced, and played twice with colors reversed):
- Without openings, LZ196 crushed LZ195 with a 58% winrate in the official match game
- With openings, it seems balanced and LZ196 doesn't seem to be better than LZ195...: 50.5% winrate only for LZ196 (200 games is a good start, but we'll know more with ~400 games in 2 or 3 days)

Would you mind to include LZ195 in your test too? That'll add a useful complementary view against a panel of nets ; -).

**Comment by sethtroisi** [comment]
@Friday9i Thanks for doing follow up testing. How do you play games with books openings + color reversed?

I'm using ringmaster and haven't seen that option.

**Comment by Friday9i** [comment]
Using Gogui (https://github.com/Remi-Coulom/gogui), recently updated and allowing openings to be used ; -). I'm using the following 120 openings (5 openings for 1st move, 115 openings for 1st+2nd move, all "balanced" with a winrate between 50% and 55% for white after move 2), cf https://github.com/gcp/leela-zero/issues/2104
Gogui is not very intuitive to use, but works very well once you understand it ; -)

**Comment by Friday9i** [comment]
Lol, there is no official paper, so "I'm not allowed to test" (methods used by all computer chess tournaments, with openings): is that your point @LL145?

**Comment by l1t1** [comment]
no weight can win every game, each has its weakness, some time learn sth but forget sth else

**Comment by sethtroisi** [comment]
@Friday9i I played some more games and the chart flattened out in a nice way

![image](https://user-images.githubusercontent.com/10172976/51281330-e9cfa880-1996-11e9-9cd0-07018494c3cc.png)

**Comment by Friday9i** [comment]
LZ185 is frigthening, barely weaker than LZ201 ; -(((
