### ISSUE TITLE
the effect of faster clients is too large in match games

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#2155]
in this match (http://zero.sjeng.org/match-games/5c3fccacf06758029e3f120d)
in the games played by client2 , cacf4cbf win 17 in 24 , winrate 70%
this result to int all games, cacf4cbf  win 85 in 145 , winrate 59%
in other words, other clients , cacf4cbf win 68 in 121 , winrate 56%
if the owner of cleint2 did somethig, it can easily effect the result.

**Comment by gcp** [comment]
Comparing the scores is meaningless due to the small sample size.
