### ISSUE TITLE
Autogtp segmentation fault in competition mode

### ISSUE THREAD

**Issue by Ttl** [gcp/leela-zero#216]
I ran autogtp with arguments:` -c -n <net1> -n <net2> -k <dir>` and it started up fine, but after necessary amount of games for SPRT were completed it printed:

```
60 wins, 26 losses
The first net is better than the second
QThread: Destroyed while thread is still running
QMutex: destroying locked mutex
*ERROR*: No 'leelaz' binary found.
Segmentation fault
```

I did have resignations enabled and playouts set to 500, but no other changes in the code. Code was compiled at the commit: 8610e62efc38aafe6320c7f6ff61667eb4a06308.

**Comment by Ttl** [comment]
Doesn't seem to work even when I reverted the resignation and playout changes.

**Comment by marcocalignano** [comment]
@Ttl I push some commits in my fork https://github.com/marcocalignano/leela-zero but no time to test them (I only made sure they compile) if you are brave enough to try them out.

**Comment by Ttl** [comment]
@marcocalignano I tested your changes:

```
Score: B+6.5
Winner: black
Stopping engine.
100 wins, 62 losses
QThread::wait: Thread tried to wait on itself
The first net is better than the second
QMutex: destroying locked mutex
```

Better than last time but still some errors. I tested 22373 vs 92c658 with playouts set to 1 to speed things up. Maybe you could try a similar test?

By the way is it correct that when one network always beats the other one it doesn't quit until the worse network has won at least one time? When I tested the latest network against the first one with one playout it didn't update the bounds and just kept playing the networks against each other:

```
50 wins, 0 losses
50 games played.
Status: 0 LLR 0 Lower Bound 0 Upper Bound 0
```
I think that 50-0 would be a statistically significant result that the first network is better?

**Comment by marcocalignano** [comment]
@Ttl So the new version is again in my next branch. Can you please test it you are much faster than me in that! Thanks

**Comment by gcp** [comment]
>I think that 50-0 would be a statistically significant result that the first network is better?

Yes. I don't know the correct fix for that in the SPRT calculation though.

**Comment by roy7** [comment]
If SPRT isn't working with one of the numbers to compare at 0, can you just run the calculation with max(wins, 1) vs max (losses, 1) instead? Worst case it is adding 1 win or loss where there aren't any, and X vs 0 is more significant than X vs 1, so if it says to stop at 50 vs max(0, 1) you're safe to do so.

**Comment by Ttl** [comment]
Works in next branch. There is a line at the end saying: "QMutex: destroying locked mutex", but the report is printed correctly.
