### ISSUE TITLE
There is something fundamentally wrong with the algorithm

### ISSUE THREAD

**Issue by DonMathi** [gcp/leela-zero#2166]
First of all thanks for the wunderful program. It is a real pleasure to use.
But I have to say that there is something fundamentally wrong with the algorithm.

The program performs a lot of play-out where it tries to find the best possible path at any given board setup. But often, when moving down this optimal path, the program suddenly discovers a better path.

And here come the problem:
When the initial path had been consolidated through a hugh number of play-out, then the new and better move has to come up with equal many play-out before it is considered the best move.
Under time constrains this will lead often to that the optimal path is not selected.

I think it is wrong (not optimal) that the number of play-out is the domminating selecting factor for the next move.

With high play-out counts it should not be the only selecting factor.

**Comment by barrtgt** [comment]
Did you try out the next branch? It includes a change that makes Leela Zero more exploratory with increased simulations. It might alleviate some of this behavior.

**Comment by thynson** [comment]
@DonMathi UCT formular will ensure better path get higher playout. Also nothing is better than playout-counts when comparing which path is **actually** better than the other ones.

**Comment by ihavnoid** [comment]
@DonMathi - can you suggest an alternative?

The UCT formula does it because it is picking the one that it has the highest confidence - that is, the path with most searches.  There is less confidence on the move you just found is really the best move, and it might make sense just to pick the less-than-best-but-higher-confidence move instead.

**Comment by DonMathi** [comment]
From https://en.wikipedia.org/wiki/Monte_Carlo_tree_search I found the descriptions:

"Although it has been proven that the evaluation of moves in Monte Carlo tree search converges to minimax, the basic version of Monte Carlo tree search converges very slowly."

And also:

"A disadvantage is that, faced in a game with an expert player, there may be a single branch which leads to a loss. Because this is not easily found at random, the search may not "see" it and will not take it into account. It is believed that this may have been part of the reason for AlphaGo's loss in its fourth game against Lee Sedol. In essence, the search attempts to prune sequences which are less relevant. In some cases, a play can lead to a very specific line of play which is significant, but which is overlooked when the tree is pruned, and this outcome is therefore "off the search radar"."

So the problem is known to other than me.

Maybe the most promissing move should be limited in search when it reach a high difference to the next move. Some kind of count-difference-factor that when it become large it will limit the search. But it should only limit it. Not stop it.

**Comment by thynson** [comment]
@DonMathi What the wiki states is about traditional MCTS. Alpha Go Zero, as well as Leela Zero, is using a modified version of MCTS that take prior-probability and position evaluation into accout. You need to read AlphaGo Zero paper first to argue for search algorithm.

**Comment by DonMathi** [comment]
Thank you. 
It is just my personal observation when using the program that leads my to belive that something could be improved.

**Comment by alreadydone** [comment]
Traditional way of dealing with this seems to be extendin the thinking time instead of changing search behavior. See "unstable evaluation" in the second paper in https://github.com/gcp/leela-zero/issues/1307#issuecomment-394921588.

**Comment by TFiFiE** [comment]
#883 is possibly relevant here.
