### ISSUE TITLE
The GTP command "lz-setoption name playouts value 2000" does not work

### ISSUE THREAD

**Issue by huangdade** [gcp/leela-zero#2167]
The GTP command **"lz-setoption name playouts value 2000"** does not work. And I followed the functions and found this in file **GTP.cpp**:

![image](https://user-images.githubusercontent.com/4537048/51544035-f02fba00-1e99-11e9-8d73-79195e65315b.png)

This is so strange for me.
Is this a special design or just a copy error?

**Comment by gcp** [comment]
I could swear I fixed this already, maybe I forgot to push the fix?

**Comment by Hersmunch** [comment]
#1989 :)

**Comment by alreadydone** [comment]
The first commit in https://github.com/gcp/leela-zero/commits/7f806f8f1803ff7a5b23ef375c308511bf45d76d/src/GTP.cpp probably wasn't included when /next was force-pushed at some occasion.
Current /next history: https://github.com/gcp/leela-zero/commits/next/src/GTP.cpp
