### ISSUE TITLE
the resource of minigo is so big, when will it get weights stronger than leelazeros

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#2175]
the minigo v16 (40x256): First 40 block run began at 2019-01-17 15:40 ,
and Last model update at 2019-01-27 02:42, total games 10474420.
and leelazero reached 11684518 total self-play games as so far, it tooks about 14 months. and those include all other Size weights games

**Comment by l1t1** [comment]
the latest weight
https://cloudygo.com/v16-19x19/eval-model/440?sorted=False Rating: 3009 ± 82.3
the strongest v15 weight 990
https://cloudygo.com/v15-19x19/eval-model/990?sorted=False  Rating: 4478 ± 24.9

**Comment by roy7** [comment]
I'm eager to see how well v16 does in comparison to v15. Keep us posted @amj once you beach vs v15 or LZ please. :)

**Comment by john45678** [comment]
Its great news how well MG is doing, the guys have put a fair bit of work into it in the last few months. My guess is that they may catch up to (and surpass) LZ with this 40b v16 run, of course, LZ is still important and hopefully will be continued for a few months yet and some interesting match ups between them.

**Comment by wonderingabout** [comment]
leela zero is contributed effort, minigo is not

no matter how good minigo becomes, being proud of what you did by yourself is priceless

**Comment by gcp** [comment]
You guys really need to find a discussion forum for this other than leela-zero's issues. May I suggest /r/cbaduk?

**Comment by wonderingabout** [comment]
its true that this issue is unrelated to leela zero development...

**Comment by l1t1** [comment]
463-foudroyant Rating: 4095 ± 43.0 Rank: 1

**Comment by l1t1** [comment]
650 is good

https://cloudygo.com/v16-19x19/eval-model/650?sorted=False

**Comment by l1t1** [comment]
665 is best, but only played 82 games
https://cloudygo.com/v16-19x19/eval-model/665?sorted=False
