### ISSUE TITLE
Intruducing cppunit?

### ISSUE THREAD

**Issue by earthengine** [gcp/leela-zero#218]
In my previous work I suspect the GTP command "printsgf" is not working in Windows MSVC compile.

As it will takes a while to run autogtp, finish a game and finally jump into the suspected code, it would be easier if we have a standard test facility like cppunit in hand (and have proper test codes written).

I can add some hack on the code (a new "test" argument to autogtp for example), However in the long term, a unit test facility would be definitely required.

Shall we start working on creating a unit test project?

**Comment by sethtroisi** [comment]
I have a test.sh scripts that verify compile and several NN eval as a "spot check before merge" but a formal framework would be nice

**Comment by bood** [comment]
I'm planning to build up a unit test framework with Travis + Google Test
Then and other people can start to add test cases, how does this sound? @gcp @sethtroisi @killerducky

**Comment by sethtroisi** [comment]
I love tests as a way of adding confidence that nothing is broken.

I've personally been running smoke tests as part of my pull requests to make sure nothing is really broken. If people want I can try to write some high level smoke tests (in bash for now) that play a couple of moves, pass, pass then verify game state (winner, approx playouts counts, captures, ...)

**Comment by bood** [comment]
@sethtroisi Yes, I think those smoke tests would be very helpful too, especially we don't have any unit test cases right now.
Could you give me some examples so I can start to look into it?
I think I will try https://github.com/sstephenson/bats for those smoke tests.

**Comment by gcp** [comment]
Google Test was merged. I need to look into setting up Travis I guess.
