### ISSUE TITLE
Why are there two kind of Minigo v15-990 Models Converted?

### ISSUE THREAD

**Issue by atoutw** [gcp/leela-zero#2182]
I downloaded ***_quantized's weight from the link below.

http://www.flygo.net/bbs/forum.php?mod=viewthread&tid=108919&extra=page%3D1&page=1

But that is just different from the weight downloaded from the link below.

https://cloudygo.com/converted_model/v15-19x19/models/

![image](https://user-images.githubusercontent.com/43053753/52023730-a0a85880-2541-11e9-9694-8eef0c26ab4a.png)
![image](https://user-images.githubusercontent.com/43053753/52024088-d437b280-2542-11e9-87ff-b07ce76ae3a0.png)

**Comment by roy7** [comment]
You may want to ask in Minigo's github instead. Those guys do visit here now and then but they likely won't get notified of every LZ issue posted, and the LZ team can't answer that since we don't have anything to do with generating those.

https://github.com/tensorflow/minigo

**Comment by atoutw** [comment]
Thanks for your answer:)
Please close the issue.

**Comment by sethtroisi** [comment]
I've answered the question on minigo side :)

**Comment by l1t1** [comment]
different  Precision

**Comment by l1t1** [comment]
you can view the weight precision by command as
```
D:\>tool\gz\gzip -d 989.gz -c |more
2
-0.0040276893 -0.0072807483 -0.0055340114 -0.0042089592 0.0029739158
```

**Comment by l1t1** [comment]
https://cloudygo.com/v16-19x19/eval-model/699?sorted=False
699-lively
Rating: 4318 ± 64.3
