### ISSUE TITLE
The argument "-g #num" of autogtp.exe don't fetch the best network

### ISSUE THREAD

**Issue by zhu-jz** [gcp/leela-zero#219]
I'm running autogtp on a windows server (command line: "autogtp -k sgf -g 3"), and the generated sgf files are uploaded to an azure cloud instance for backup every hour. 

I know the argument "-g 3" means playing three games at the same time against itself, but after the network was updated (22373747) on Dec 1st 05:29 (UTC + 8), there were only one game using the best network, and the rest still play games using previous network (92c658d7).

Sorted by "last modified time", the most right column is the network used, (from 05:00 AM to 10:00 AM) there are 33 games played by the current best network (22373747), and 55 games played by the network (92c658d7). Here is an overview of the generated sgf files, http://13.84.133.163/sgf/info.html

`9e910603333c44899582f0f619962d24.sgf	197	B+21.5	2017-12-01 09:58:10	1.29 KB	22373747
601798fc16d74b05bef1762d9caa3d36.sgf	429	W+40.5	2017-12-01 09:51:38	2.7 KB	92c658d7
31f47d7b64ef40a7aa0e44d915906ff5.sgf	457	B+55.5	2017-12-01 09:50:22	2.87 KB	92c658d7
238779bd9d654577a518cf228fed48a3.sgf	303	B+10.5	2017-12-01 09:42:18	1.93 KB	22373747
f8af85e6e07c4b3094c6333787cdbc17.sgf	393	B+33.5	2017-12-01 09:39:10	2.48 KB	92c658d7
9c7b3eeb390d42539b35140556112b12.sgf	401	B+37.5	2017-12-01 09:37:02	2.53 KB	92c658d7
52ac466dba9c456691de5bd033f284d6.sgf	259	B+11.5	2017-12-01 09:33:28	1.67 KB	22373747
e02c5e63e88340b38fba3ad1b7e95e66.sgf	237	B+11.5	2017-12-01 09:26:56	1.53 KB	92c658d7
ad205557488441f5b5536c1c15106a3d.sgf	445	B+86.5	2017-12-01 09:25:18	2.79 KB	22373747
27913031ac73468fb785c2c54f44cfaf.sgf	343	B+21.5	2017-12-01 09:24:54	2.18 KB	92c658d7
1e9e52d834de4dc18bfb592e3806d05c.sgf	287	B+1.5	2017-12-01 09:18:56	1.84 KB	92c658d7
1769dd7040b542c1a43b1aaf85b12391.sgf	489	B+55.5	2017-12-01 09:13:58	3.06 KB	92c658d7
e5f66aaa2bd24c90991a26c4f142d608.sgf	416	W+29.5	2017-12-01 09:11:44	2.62 KB	22373747
c3a82c0b91a74b5488cc80185889f623.sgf	523	B+61.5	2017-12-01 09:10:08	3.27 KB	92c658d7
28c046052fc548129d34e7410e27214c.sgf	429	B+34.5	2017-12-01 08:59:46	2.7 KB	92c658d7
4dea81aba27143f9b4e6d8615a788c9a.sgf	273	B+7.5	2017-12-01 08:59:38	1.75 KB	22373747
910fb09263fc4489bf02d74c80b5ec74.sgf	453	B+11.5	2017-12-01 08:54:58	2.84 KB	92c658d7
d7157eabc5754d0ca02b49b4702e1c7e.sgf	367	B+47.5	2017-12-01 08:51:36	2.32 KB	22373747
9d13f70439b04ca8a224a96d4db5d3f1.sgf	455	B+56.5	2017-12-01 08:47:18	2.85 KB	92c658d7
45925bf9892b4a309dd5bf9818337542.sgf	359	B+18.5	2017-12-01 08:41:50	2.27 KB	92c658d7
d571570208f9437bb9a8919660ae03cc.sgf	54	W+10.5	2017-12-01 08:40:56	0.43 KB	22373747
ab80236f986740349a055fe623d4c2fa.sgf	277	B+1.5	2017-12-01 08:39:12	1.78 KB	22373747
8d9ac904563b4d23add6201980c1e95b.sgf	468	B+19.5	2017-12-01 08:34:08	2.93 KB	92c658d7
827bab8c58d34d68b42a67953db4351a.sgf	465	B+58.5	2017-12-01 08:31:26	2.92 KB	92c658d7
abaa98c44ae0458aa364f8b4cbe153fd.sgf	277	B+0.5	2017-12-01 08:31:10	1.78 KB	22373747
6fb0c137a4d2434d9d527bbc2b9b6571.sgf	210	W+5.5	2017-12-01 08:23:06	1.37 KB	22373747
1339d36d23a742d0869f1cf7047d3545.sgf	315	B+15.5	2017-12-01 08:20:36	2.01 KB	92c658d7
3f88a12f906041bdb5e9476fae5174be.sgf	412	B+11.5	2017-12-01 08:17:52	2.59 KB	92c658d7
e45f709cc1cb4a368ad096504adc5547.sgf	325	B+12.5	2017-12-01 08:16:58	2.07 KB	22373747
336bab4733ad44639960f2bfa36efc1d.sgf	387	B+35.5	2017-12-01 08:11:24	2.44 KB	92c658d7
6b25e2a5b088446a92f3b0a747d026c8.sgf	161	B+1.5	2017-12-01 08:07:34	1.07 KB	22373747
1c5c5fbb9cf24ecab87c49b497d01964.sgf	331	B+9.5	2017-12-01 08:05:58	2.1 KB	92c658d7
f77fd627bc1e4ca4bf3af7a95288f8af.sgf	6	W+7.5	2017-12-01 08:02:44	0.13 KB	22373747
2a61f2578b4247379647d5630c4b5508.sgf	58	W+6.5	2017-12-01 08:02:28	0.45 KB	22373747
000a8047cd9b4357926ceb06066bdd23.sgf	171	B+2.5	2017-12-01 08:00:40	1.13 KB	22373747
8fdf7b112fe84b9fbcd5291e992a5a92.sgf	559	B+135.5	2017-12-01 08:00:08	3.48 KB	92c658d7
3d414e25fc6f4ba88c0fac39e9a0d9fb.sgf	423	W+38.5	2017-12-01 07:56:22	2.66 KB	92c658d7
cf2277060e9c4d7eba10ca9d90c548e4.sgf	243	B+6.5	2017-12-01 07:55:40	1.57 KB	22373747
abb8e0b95a87470fb7fcb244cd405a91.sgf	433	B+19.5	2017-12-01 07:48:24	2.72 KB	22373747
d6d141cb121c4f5c9c1f311f9abd9c45.sgf	417	B+11.5	2017-12-01 07:44:06	2.62 KB	92c658d7
e8cba5cf310847f68b697effc04a3c0f.sgf	472	W+88.5	2017-12-01 07:44:02	2.96 KB	92c658d7
dc03fcccb6a24bff9873af05ff59468b.sgf	463	B+84.5	2017-12-01 07:35:50	2.9 KB	22373747
2db592dc5a4f456f8f6a95bdefeb56d4.sgf	369	B+18.5	2017-12-01 07:32:04	2.33 KB	92c658d7
5a246a20854a4e148eae4a5b3fe3c390.sgf	447	B+98.5	2017-12-01 07:30:20	2.81 KB	92c658d7
fe43ba2fa2404543baff4bbb962ea986.sgf	207	B+4.5	2017-12-01 07:22:26	1.35 KB	22373747
b09d5b50db4d493c864c03b0838fb517.sgf	421	B+29.5	2017-12-01 07:21:20	2.65 KB	92c658d7
489ad57702e045b599758347d4fba879.sgf	331	B+17.5	2017-12-01 07:17:26	2.1 KB	92c658d7
5b23fe9d3ec0448cb94ab2f061d0d604.sgf	429	B+82.5	2017-12-01 07:16:18	2.7 KB	22373747
ff472dc7b7ae4419b3d16614ac3dd315.sgf	407	W+8.5	2017-12-01 07:09:00	2.56 KB	92c658d7
963cd936478e41b288548a8854c8f66e.sgf	385	B+37.5	2017-12-01 07:07:46	2.43 KB	92c658d7
6473be2e205b47efb697f22e51f625ac.sgf	188	W+6.5	2017-12-01 07:03:48	1.24 KB	22373747
e2382726fa3f4315a36e1964a15a7e88.sgf	201	B+4.5	2017-12-01 06:58:14	1.32 KB	22373747
93cd8a61bf0b4772952ea26b7d81dfa3.sgf	519	W+49.5	2017-12-01 06:57:14	3.24 KB	92c658d7
e94c3fb710d74317b1ab766cde7915bc.sgf	383	B+16.5	2017-12-01 06:56:36	2.42 KB	92c658d7
3e5b40764e7e47aabbcb60333d5e5933.sgf	481	B+89.5	2017-12-01 06:52:20	3.01 KB	22373747
85b379d62ec94e5298ecb12f829c9e6b.sgf	391	B+13.5	2017-12-01 06:45:24	2.47 KB	92c658d7
c1ee6711ad4f4bc9aced0b676e7d7695.sgf	421	B+26.5	2017-12-01 06:42:20	2.65 KB	92c658d7
df0f853f51964c9c922ca3127ce3997e.sgf	68	W+7.5	2017-12-01 06:38:26	0.51 KB	22373747
86eb826cdda2433bb2342032e99136ad.sgf	403	B+9.5	2017-12-01 06:36:20	2.54 KB	22373747
556a8ca0e1ae4f4a9f31715b8069f8b9.sgf	367	B+22.5	2017-12-01 06:33:48	2.32 KB	92c658d7
ba8bbe95e9ae4f8c9a4489ca26cd085c.sgf	295	B+2.5	2017-12-01 06:30:02	1.88 KB	92c658d7
defc1cd6eb1846659da14ea784760413.sgf	460	B+40.5	2017-12-01 06:24:32	2.89 KB	22373747
ed01f65546af4c7abce48fe03452a469.sgf	467	B+32.5	2017-12-01 06:23:04	2.93 KB	92c658d7
6a7e233a470e4c6e9223d41944786f55.sgf	260	W+22.5	2017-12-01 06:21:18	1.67 KB	92c658d7
0a480da9f3b14696b5e3ba3580a02142.sgf	351	B+18.5	2017-12-01 06:13:34	2.23 KB	92c658d7
add75870109f474eaa4eb25d4782d8a4.sgf	377	B+20.5	2017-12-01 06:11:10	2.38 KB	22373747
f042643255524028bfc7f7e8c9a8a06f.sgf	46	W+7.5	2017-12-01 06:09:26	0.38 KB	92c658d7
e3930dc082344eb2abe9e3526c8347e6.sgf	430	B+17.5	2017-12-01 06:07:50	2.7 KB	92c658d7
cdf7a0e9b0924add8703193fd30852f3.sgf	419	B+21.5	2017-12-01 06:03:22	2.64 KB	92c658d7
b6e56fe1606046239e6101106e628403.sgf	293	B+0.5	2017-12-01 06:00:10	1.87 KB	22373747
c436050ac3284fb69473e5f1eb8f81d9.sgf	261	B+0.5	2017-12-01 05:55:18	1.68 KB	92c658d7
bce41ba214a0425bb982baaa11bfbd0d.sgf	311	B+19.5	2017-12-01 05:51:38	1.98 KB	22373747
782a5896eca74616ba8a578666ce0ca9.sgf	283	B+4.5	2017-12-01 05:51:06	1.81 KB	92c658d7
fa2f6216aca94a34a39c01b73855975f.sgf	301	B+2.5	2017-12-01 05:47:38	1.92 KB	92c658d7
8d2cd1de78774784b82a5c4997a27c15.sgf	327	B+15.5	2017-12-01 05:42:50	2.08 KB	92c658d7
86208933fd1d45e6b952733362de9a91.sgf	181	B+11.5	2017-12-01 05:42:38	1.2 KB	22373747
77add9a38c884d94be5bc2ed3a5282f0.sgf	522	W+84.5	2017-12-01 05:38:50	3.26 KB	92c658d7
af18409a1835492a97eac938a6982c0a.sgf	153	B+7.5	2017-12-01 05:37:16	1.03 KB	22373747
01161da4e48c4a958f9e747aa06799ef.sgf	351	B+8.5	2017-12-01 05:33:22	2.22 KB	92c658d7
72b9d9ab6dd84bd58db0d2759d84b6e9.sgf	112	W+6.5	2017-12-01 05:32:44	0.78 KB	22373747
c10e615c64f942b8a20a7217defccc9a.sgf	329	B+15.5	2017-12-01 05:29:14	2.09 KB	92c658d7
4a3e8217958941c39ca79bf3ebe872d7.sgf	299	B+5.5	2017-12-01 05:23:44	1.91 KB	92c658d7
2a74e197815d4c40ac93727f3aba2408.sgf	473	B+54.5	2017-12-01 05:23:08	2.96 KB	92c658d7
7ab8555d95b74df78082c4a4ad0a3d48.sgf	481	B+96.5	2017-12-01 05:19:38	3.01 KB	92c658d7
116617255c59433d84fe97895fd785ad.sgf	293	B+13.5	2017-12-01 05:14:56	1.87 KB	92c658d7
881458500bcf4f83b514df2ea28a6052.sgf	10	W+7.5	2017-12-01 05:09:30	0.16 KB	92c658d7
955757432c64480bb08c20a0be28c07d.sgf	331	B+3.5	2017-12-01 05:09:04	2.1 KB	92c658d7
31d3521432834e70b138a2c6f16df9c5.sgf	365	B+34.5	2017-12-01 05:06:24	2.31 KB	92c658d7`

**Comment by zhu-jz** [comment]
I restarted the autogtp on about 10:00 AM, after that everything is OK. 
The problem may happen while the client autogtp is running, and server update the new network.

**Comment by sethtroisi** [comment]
From next branch: https://github.com/gcp/leela-zero/blob/next/autogtp/Production.cpp#L204
Production fetches the new network and sets it in m_network
ProductionWorker is never updated.

Even worse the game is uploaded with the new network hash (because production was updated)
https://github.com/gcp/leela-zero/blob/next/autogtp/Production.cpp#L325

**Comment by marcocalignano** [comment]
The new network is updated at the end of getResult and will sure the new
network in the next game. The games that are already playing will continue
to play with the old. But you are right the last n-1 games after a network
switch are sent with the new hash even if the network use was the old one.
I try to fix it, but I think it shouldn't be a big dea

On Dec 1, 2017 7:41 AM, "Seth Troisi" <notifications@github.com> wrote:

From next branch: https://github.com/gcp/leela-zero/blob/next/autogtp/
Production.cpp#L204
Production fetches the new network and sets it in m_network
ProductionWorker is never updated.

Even worse the game is uploaded with the new network hash (because
production was updated)
https://github.com/gcp/leela-zero/blob/next/autogtp/Production.cpp#L325

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gcp/leela-zero/issues/219#issuecomment-348414693>, or mute
the thread

**Comment by zhu-jz** [comment]
After the network switched, I generated more than fifty games which used the old network, (and 33 games with new network). 

There was only one client (autogtp) run on my computer, it appears to me that the program had trouble to update the network until I closed and restart it.

If not restart the autogtp manually, I'm sure I will get more games played by using the old network.

**Comment by sethtroisi** [comment]
ProductionWorker.m_network is never updated only Production.m_network

**Comment by marcocalignano** [comment]
Production.cpp#L142 and Production.h#L37

**Comment by sethtroisi** [comment]
Production.cpp#L142 only returns true for the first thread that updates the network

**Comment by sethtroisi** [comment]
Production.cpp#L90
"auto new_network" might be better named is_new_network.

**Comment by marcocalignano** [comment]
You are right about L142 I will fix it and I have an Idea also how to fix the segfault in #216

**Comment by sethtroisi** [comment]
Curious, what do you think is causing the segfault?
I was thinking maybe the user had deleted the leelaz binary file but seems like they would know they did that.

**Comment by marcocalignano** [comment]
the segmentation fault comes at the end and I suspect when the QThread::quit() is called 
I push some commit in my fork https://github.com/marcocalignano/leela-zero but no time to test them (I only made sure they compile) if you are brave enough to try them out. I am also not really sure how you can test  the network change.

**Comment by marcocalignano** [comment]
I think is solved by  #242
