### ISSUE TITLE
Game ends without resignation or passing

### ISSUE THREAD

**Issue by olbrichj** [gcp/leela-zero#221]
Was running autogtp just now build from current master branch. This is the output:

Infinite thinking time set.
1 (S13) 2 (P9) 3 (S14) 4 (L4) 5 (T9) 6 (L10) 7 (B17) 8 (A6) 9 (S16) 10 (F4) 11 (B10) 12 (O6) 13 (B15) 14 (R9) 15 (E6) 16 (D11) 17 (B19) 18 (M11) 19 (M9) 20 (E11) 21 (N10) 22 (Q3) 23 (O5) 24 (F19) 25 (R14) 26 (A19) 27 (S19) 28 (B7) 29 (J1) 30 (R16) 31 (P16) 32 (T16) 33 (J5) 34 (P5) 35 (C7) 36 (T2) 37 (E1) 38 (S1) 39 (T12) 40 (L16) 41 (A18) 42 (C12) 43 (A2) 44 (N4) 45 (B5) 1 game(s) played in 7 minutes = 449 seconds/game, last game took 449 seconds.

Any idea why the game ends?

**Comment by isty2e** [comment]
I found [this solution](https://github.com/gcp/leela-zero/issues/141) working well for me. Before you compile the source code, add cmdLine.append(" -t 1"); to the line 38 or somewhere of autogtp/Game.cpp. You can run multiple instances of autogtp so it wouldn't matter in terms of performance.

**Comment by marcocalignano** [comment]
Test the new autogtp with testing capabilities I found the problem mentioned here!! 
When one player resigned the Game is ended but the score string is empty and is not written into the output.
I'll try to make a fix and maybe someone can try to run the client with high percentage resignation rate.

**Comment by marcocalignano** [comment]
Please have a look at #262

**Comment by olbrichj** [comment]
This explains the missing output. But did you find on accident the reason for it stopping afterwards? It didn't start a new game

**Comment by isty2e** [comment]
@marcocalignano This happened with -r 0 (resignation disabled) so I think it is not that relevant to the issue. Also, if one resigns, it is printed like

>...44 (N4) 45 (B5) 46 (resign)

which is not the case here.

**Comment by Mardak** [comment]
This was fixed with #268 with `-t 1`
