### ISSUE TITLE
Leela-zero-0.6-windows: Error Could not talk to engine after launching

### ISSUE THREAD

**Issue by brianprichardson** [gcp/leela-zero#222]
C:\Downloads\leela-zero-0.6-windows>autogtp.exe
autogtp v4
Best network hash: 223737476718d58a4a5b0f317a1eeeb4b38f0c06af5ab65cb9d76d68d9abadb6
Required client version: 4 (OK)
Already downloaded network.
Engine has started.
*ERROR*: Could not talk to engine after launching.

C:\Downloads\leela-zero-0.6-windows>

**Comment by killerducky** [comment]
Try this to see if you can get more info on the problem:

leelaz.exe -w 223737476718d58a4a5b0f317a1eeeb4b38f0c06af5ab65cb9d76d68d9abadb6

I think on some systems the weight file might get a shorter name when you unzip it:
leelaz.exe -w 485kw.txt

**Comment by marthinwurer** [comment]
This sounds like there's something wrong with leelaz. When I got this error, the issue was that I didn't have the right drivers, so you should make sure that those are updated.

**Comment by brianprichardson** [comment]
It was running fine for days.  What changed was using the MSVC 2017 sln which did the Nuget.  Still running fine on another PC that has not been changed for days.  It crashes just after displaying
Initializing OpenCL
OpenCL: clGetPlatformIDs

**Comment by brianprichardson** [comment]
OK, I uninstalled the packages that Nuget did with the MSVC 2017 version and things are working again.

**Comment by gcp** [comment]
@earthengine sounds like potential OpenCL.dll issue to me :-)

**Comment by earthengine** [comment]
As I couldn't easily replicate this in my computer (my machine is Windows 10 with a Nvidia card), please provide the following information to help me diagnose.

* The operation system?
* How many video cards? Which brand?
* Can you locate opencl.dll inside %SYSTEM% folder?
* Which Visual Studio version you are using (2015/2017)
* Can you copy the opencl.dll from the package folder to solve this?

Meanwhile, I will try to use the compiled binary packages (excluding opencl.dll) in my other computer (a single board one, not good for development but good enough for test the binary) to see if I can replicate this.

**Comment by brianprichardson** [comment]
Win7 GTX770 MSVC2017Community
The MSVC2017 compiled .exe works after having removed the NuGet packages, so perhaps some .dll in the packages is not compatible

**Comment by earthengine** [comment]
Right, so even I manually add a rule to copy the Nuget package's opencl.dll would not help you. 

But I didn't fully understand what do you mean by removing the Nuget package. Do you mean you have to replace those packages with your native compile? or simply removed some dlls copied by the Nuget package rules?

Tonight I would try to make a Windows installer that ships all necessory dlls. As I don't have a list of "necessory dlls" I have to try and correct. The result msi will be put in my own website for download. After then you can try to see if the msi file will work straight away.

**Comment by earthengine** [comment]
I would like everyone try <http://earthengine.me/Leelaz.Installer.msi> for my first MSI built from VS2015. Once this proved to work I will continue on creating a pull request to create an msi.

**Comment by barrtgt** [comment]
@earthengine I got an insufficient priveleges error. Would it be possible to specify a directory?

**Comment by brianprichardson** [comment]
From MSVC 2017 I did Tools, NuGet Package Manager, Manage NuGet Packages for Solution and then clicked remove (or delete or uninstall, I can't recall exactly) for each one listed.  Things worked after that for me as I must already have had the proper versions since I had been running the Windows binary for some time before trying the Windows compile.

**Comment by earthengine** [comment]
ahh... I set it to install per user, but still specified ProgramFiles64Folder, because I was going to sleep and just quickly finish things. Shall fix tonight.

**Comment by earthengine** [comment]
I intended to create an MSI that only installs per user. However it requires extra work. I have now updated the msi and it will install to %LocalAppData%\Programs\Leelaz.Installer\

To allow change directory will be another pull requests. Current it is just prove of concept. Please try this out and see if it works.

After installation, run it in console and type in

%LocalAppData%\Programs\Leelaz.Installer\autogtp

I will create a shourtcut under the msi to automate this later.

**Comment by barrtgt** [comment]
It seems to install in the directory fine. This is the result in cmd:


Microsoft Windows [Version 10.0.16299.64]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\A>%LocalAppData%\Programs\Leelaz.Installer\autogtp
autogtp v5
Best network hash: ad8a1d025c81264d9dc14f655466f9303db0ea6de241c56bbe3122c71557e686
Required client version: 4 (OK)
curl.exe -s -O -J -w %{filename_effective} http://zero.sjeng.org/best-network
Curl filename: ad8a1d025c81264d9dc14f655466f9303db0ea6de241c56bbe3122c71557e686.gz
Net filename: ad8a1d025c81264d9dc14f655466f9303db0ea6de241c56bbe3122c71557e686
*ERROR*: No 'leelaz' binary found.

**Comment by earthengine** [comment]
I am running late today. And I don't have time tomorrow. Wait for Friday night then.

**Comment by earthengine** [comment]
Wait, I think my instruction above is wrong. 

autogtp refer to leelaz.exe through "./" prefix, so leelaz.exe have to be in the current folder. So try this:

```
cd %LocalAppData%\Programs\Leelaz.Installer
autogtp
```

**Comment by barrtgt** [comment]
That did it. It's playing now.
