### ISSUE TITLE
autogtp: Game:eatNewLine() does not guarantee to eat a '\n'

### ISSUE THREAD

**Issue by ljn917** [gcp/leela-zero#226]
This is the log I have with a few additional debug output. The printed "GTP:\n" after "sendGtpCommand: time_settings 0 1 0" means that the "\n" was not eaten by Game:eatNewLine(). We need to check that a "\n" actually is read in Game:eatNewLine(). Probably because the response of version, "= 0.6\n" and the "\n" later, arrived the buffer separately.

I will make a pull request later to fix this.

```
Best network hash: 223737476718d58a4a5b0f317a1eeeb4b38f0c06af5ab65cb9d76d68d9abadb6
Required client version: 4 (OK)
Already downloaded network.
Before GTP: cl_get_gt_device(): error, unknown device: 0

Enter GTP 
GTP: leela version= 0.6
Engine has started.
sendGtpCommand: time_settings 0 1 0

GTP: 

*ERROR*: Error in GTP response.
Infinite thinking time set.
*ERROR*: Error in GTP response.
Error read 3 '= 
'
*ERROR*: Error in GTP response.
Error read 1 '
'
^C
```

**Comment by killerducky** [comment]
Are you sure this is legal GTP? I think GTP protocol defines the end of a response as two consecutive newlines, so you ended the response but then output more stuff, which is illegal.

http://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html

> 2.6 Response Structure
> 
> If successful, the engine returns a response of the form
> =[id] result
> Here '=' indicates success, id is the identity number given in the command, and result is a piece of text ending with two consecutive newlines.
>

**Comment by ljn917** [comment]
Yes, the GTP was received from leelaz, and I checked that with -g.

**Comment by killerducky** [comment]
Oh sorry I thought you were adding additional debug outputs including extra (illegal) blank lines.

**Comment by ljn917** [comment]
The debug code is in pull request #244. I think it is better to have them in order to know where the error is.

**Comment by sethtroisi** [comment]
I was also seeing this error and "fixed" it  by following the advice here
https://github.com/nanopool/Claymore-Dual-Miner/issues/15#issuecomment-326846578

but I'd suggest moving instead of deleting the file
`sudo mv /usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1 /usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1.bck`

**Comment by ljn917** [comment]
I have done that already. It does not work. The issue is in intel beignet driver. My clinfo also prints errors like in this issue (https://bugzilla.redhat.com/show_bug.cgi?id=1478536)

**Comment by ljn917** [comment]
Running multiple autogtp instances, in my case the 5th one, can trigger this 100%. It is likely caused by delay in I/O when CPU is busy.
