### ISSUE TITLE
is the result calculated right?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#227]
http://zero.sjeng.org/view/e5cf54bca04654a512ffd62683f467fbcc3984f092674eafcb815961af607147
in step 389, white is dead all
and in step 385, white is live

**Comment by isty2e** [comment]
I can't even guess what you intend to say, but there is no known issue concerned with scoring. Note that we are using Tromp-Taylor scoring method.

**Comment by Vandertic** [comment]
I presume black wins, and in that case even if white fills out is second eye (move 489, not 389) the score changes, but the result does not. The target of the program is to win, not to maximize score difference.

**Comment by l1t1** [comment]
sorry for make confuse.
leelaz says Result:B+11.5, and I think if white stones are all dead, maybe B+(361-7.5=353.5)

**Comment by isty2e** [comment]
I strongly recommend you to read what Tromp-Taylor scoring is before further discussion.

**Comment by l1t1** [comment]
http://zero.sjeng.org/view/95d3595032e03a0ff9ef33a071865f35b65debdaf259485b6d039ccbeef2409b
how to count score by using  Tromp-Taylor scoring?
125 steps

**Comment by Prillan** [comment]
http://tromp.github.io/go.html
> A player's score is the number of points of her color, plus the number of empty points that reach only her color.
