### ISSUE TITLE
leelaz on Windows exits after ~80k playouts

### ISSUE THREAD

**Issue by eterevsky** [gcp/leela-zero#230]
On my configuration (Windows 10 + GTX 1080), leelaz stops after around 80000 playouts. To reproduce:

```
 ./leelaz.exe -w 223737476718d58a4a5b0f317a1eeeb4b38f0c06af5ab65cb9d76d68d9abadb6

time_settings 0 3600 1
genmove b
```

Leela runs the search and after the line
```
Playouts: 84573, Win: 65.99%, PV: S15 C17 S13 N2
```
it exits, presumably crashing. Similar thing happens in other positions as well.

If you could generate a debug build, I could run it and attach the stack trace.

**Comment by Ttl** [comment]
I can't reproduce the crash on Linux next-branch using debug build, but it seems that leelaz stops adding new playouts after 111203 playouts:

```
Playouts: 2889, Win: 65.11%, PV: N2 N18 B13
Playouts: 5973, Win: 65.18%, PV: G18 R11 S13
Playouts: 9113, Win: 65.30%, PV: G18 M3 N2
Playouts: 12192, Win: 65.47%, PV: Q15 J2 G2
Playouts: 15256, Win: 65.60%, PV: D15 S13 S7
Playouts: 18313, Win: 65.69%, PV: D15 S13 S7
Playouts: 21365, Win: 65.75%, PV: Q15 J2 G2
Playouts: 24447, Win: 65.79%, PV: Q15 A17 B7
Playouts: 27555, Win: 65.82%, PV: E2 A3 B13
Playouts: 30666, Win: 65.84%, PV: E2 A3 B13
Playouts: 33684, Win: 65.85%, PV: S15 C17 N18
Playouts: 36776, Win: 65.86%, PV: Q15 A17 B7
Playouts: 39820, Win: 65.87%, PV: S15 R3 G2
Playouts: 42848, Win: 65.87%, PV: B5 T3 S13
Playouts: 45679, Win: 65.87%, PV: S15 R3 G2
Playouts: 48658, Win: 65.86%, PV: S15 R3 G2
Playouts: 51690, Win: 65.86%, PV: S15 R3 G2
Playouts: 54757, Win: 65.85%, PV: S15 R3 G2 B7
Playouts: 57859, Win: 65.84%, PV: B5 T17 N18 S7
Playouts: 60969, Win: 65.87%, PV: B5 R3 S13 G18
Playouts: 64025, Win: 65.89%, PV: B5 R17 B7 G2
Playouts: 67180, Win: 65.92%, PV: E18 R3 B13 G18
Playouts: 70267, Win: 65.93%, PV: E18 R3 B13 G18
Playouts: 73351, Win: 65.95%, PV: E18 R3 B13 G18
Playouts: 76503, Win: 65.97%, PV: E18 R3 B13 G18
Playouts: 79691, Win: 65.98%, PV: E18 R3 B13 G18
Playouts: 82946, Win: 66.00%, PV: E18 R3 B13 G18
Playouts: 86117, Win: 66.01%, PV: B5 R17 B7 G2
Playouts: 89332, Win: 66.01%, PV: B5 R17 B7 G2
Playouts: 92560, Win: 66.02%, PV: B5 R17 B7 G2
Playouts: 95700, Win: 66.02%, PV: E18 C3 N18 S13
Playouts: 98782, Win: 66.03%, PV: E18 C3 N18 S13
Playouts: 101952, Win: 66.03%, PV: E18 C3 N18 S13
Playouts: 105093, Win: 66.04%, PV: E18 C3 N18 S13
Playouts: 108248, Win: 66.04%, PV: E18 C3 N18 S13
Playouts: 111203, Win: 66.07%, PV: S7 R18 R11 N18
Playouts: 111203, Win: 66.07%, PV: S7 R18 R11 N18
Playouts: 111203, Win: 66.07%, PV: S7 R18 R11 N18
Playouts: 111203, Win: 66.07%, PV: S7 R18 R11 N18
Playouts: 111203, Win: 66.07%, PV: S7 R18 R11 N18
Playouts: 111203, Win: 66.07%, PV: S7 R18 R11 N18
```
Win% or PV doesn't change even if I let it run longer. Interrupting on gdb stops in different places in UCTNode.cpp so it seems that it's still running the MCTS.

**Comment by eterevsky** [comment]
I ran the scenario on the next version, both Debug and Release on Windows. It ended up the same way, as in your case. Both versions stopped at 11120x playouts.

**Comment by eterevsky** [comment]
I figured it out. The search hits the `UCTSearch::MAX_TREE_SIZE` limit. It should just stop and return the result at this point, instead of the infinite loop. Also, I don't see any reason why this limit can't be dynamic, based on the available memory or user config. Let me have a look at the code.

**Comment by eterevsky** [comment]
Added a pull request. Leela actually doesn't have to stop once the maximum tree size has been reached. The tree has plenty of non-evaluated leaves, and we can continue to evaluate them, without expanding the tree. Implemented it in the PR above.

**Comment by roy7** [comment]
Do you handle the case when you've hit maximum tree size and all leaves have been evaluated?

**Comment by eterevsky** [comment]
@roy7 Nope, and it will be quite expensive to check.

What will happen is, the MCTS will continue to run, updating the playout counts and the evaluations of non-leaves. This is not particularly bad and will happen only in the unlikely event of a very limited tree size, and at the same time high time limit.

Another issue that I haven't yet handled is that we will re-run the network on already evaluated leaves. I just realized that we don't have to do it, since if the node is a leaf and has been evaluated, we can just take the evaluation from it and reuse, no need for an additional cache. I'll update the PR to do it.

**Comment by eterevsky** [comment]
> I'll update the PR to do it.
Done.

**Comment by gcp** [comment]
>Another issue that I haven't yet handled is that we will re-run the network on already evaluated leaves. I just realized that we don't have to do it, since if the node is a leaf and has been evaluated

FWIW it's useful to run every symmetry on a leaf node. It may be more useful to run all 8 symmetries on a critical leaf than it is to run the eval on all leaves of a node we know is irrelevant.

It would require keeping track of the "first symmetry" when you evaluate a leaf, i.e. the random one you picked in the first evaluation, and a counter.

**Comment by eterevsky** [comment]
I somehow thought that the network code already performs all rotations before evaluating.

It's hard for me to tell, what's actually more beneficial: to run more symmetries on the same leaf, or to evaluate some more of them. What do you usually do when you're faced with such a dilemma? Just build two binaries and make them play against each other a few games? Add this setting to config.h so that it could be re-evaluated later with new weights?

One thing that slightly worries me with the current approach is what happens when Leela decides to switch to a new shallow branch after the tree has stopped growing. Ideally it should start exploring moves in the new variation, but it can't do it because it can't grow the tree. One solution could be to stop the search altogether ones it hits the same leaf some predetermined number of times, like 10, so that we could avoid over-confident evaluations in shallow branches. WDYT?

**Comment by gcp** [comment]
>I somehow thought that the network code already performs all rotations before evaluating.

You can do that but in general the 8x slowdown isn't worth the increased accuracy.

> Just build two binaries and make them play against each other a few games?

Yes. Except "a few" should be "until you have a statistically significant result".

>WDYT?

Every solution once you hit the tree size limit is going to suck in some way. Just increasing the tree size isn't very clean either, i.e. the program is just gobbling up RAM with a tree for which many nodes are irrelevant. Some kind of "garbage collection" may be more sensible.

**Comment by gcp** [comment]
(I very much regret the current linked-list design FWIW, it would've been far cleaner to just put child nodes in a std::vector. I have some abandoned branch somewhere where I started work on this.)

Another approach is to make the TTable the sole place where the tree is stored, and just replace entries, but this is also requires some major program surgery.

**Comment by eterevsky** [comment]
I think it should be possible to bring down the size of non-expanded nodes to just 8 bytes. It would work as follows: for an expanded node, it'd be just a `unique_ptr` with a separate class for expanded node, for non-expanded it's a float with a probability from the network + a marker to distinguish it from a pointer. 

Expanded node would contain its children in a vector or an array, removing the necessity for a linked list.

If you're ok with this design, I can take a stab at this refactoring, though I probably won't have enough time to finish it before weekend.

**Comment by gcp** [comment]
Sure, sounds good. Anything to get rid of those manual pointer manipulations in the linked lists would be a big win. I'll close out this issue - the main bug is fixed.

Don't be too clever with trying to pack stuff into something and trying to disambiguate it from a pointer :-)

**Comment by roy7** [comment]
Is https://github.com/gcp/leela-zero/pull/236 in a windows release binary yet? Found someone on OGS that is having this same bug tonight.
