### ISSUE TITLE
Support for other board sizes than 19x19

### ISSUE THREAD

**Issue by wensdong** [gcp/leela-zero#24]
@gcp 

 Could you please point out where I can set the board to 9x9, so that I do some fast experiments?

Regards,

**Comment by gcp** [comment]
9x9 is not supported. The design of the policy head in the neural network is specific to 19x19.

It's possible to modify the source and design a new head of course, but this needs changes all over the source code.

**Comment by gooooloo** [comment]
I make some modification to allow 9x9 playing in my fork https://github.com/gooooloo/leela-zero/tree/9x9. It is still under testing so bugs can be expected. Anyone interested is welcome to play around with that, and any feedback/bugfix is welcome.

**Comment by gcp** [comment]
Nice!

**Comment by gcp** [comment]
I'll leave this issue open because the question comes up a lot and we can point people to your branch or perhaps merge back the changes at some point.

**Comment by Mardak** [comment]
This was fixed / made trivial with #928
