### ISSUE TITLE
GCP, Leela 0.12 ?

### ISSUE THREAD

**Issue by Marcin1960** [gcp/leela-zero#247]
Gian-Carlo, what about checking how Leela Zero methodology would work for your own private project?

You could provide one client executable on https://www.sjeng.org/leela.html - autoLeelaGTP.exe, combining functionality of autogtp and leelaz, that would allow you to enhance Leela 0.11 network.

The benefits:

1. Gaining some insights for Leela Zero project.
2. Possibly making Leela significantly stronger.
3. A lot of fun :)
4. And more ...

**Comment by gcp** [comment]
Please don't spam this tracker with offtopic requests on unrelated software.

**Comment by Marcin1960** [comment]
OK :(
