### ISSUE TITLE
Cerebration time: Keeping the 585k network as a milestone?

### ISSUE THREAD

**Issue by earthengine** [gcp/leela-zero#252]
It is the first network that beats the BeginerBot. And this is remarkable.

Whilst Leela-zero keep growing, this network will expire but it will still serve as a fantastic leaning tool for beginners including kids. I am thinking use this to train my 9yo on GO! One benifit of this kind of learning is that can avoid the long list of terms in the traditional GO books, and see if a young little can develop those terms independently. It would be an exciting observation and we all can learn a lot.

Once they beat this network, Leela-zero will grow as well and the learner will face a more powerful competitor. So they have to grow as well to beat it. For learning purpose, this is the ideal. 

So it is not only for fun, it is already really useful. We should mark some networks as "milestone" and leave it forever.

**Comment by gcp** [comment]
We'll have a track of all networks that were best at some time. If we can figure out approximate levels for them you'll have a set of "beginner/intermediate" player styles.
