### ISSUE TITLE
Strange resign rate debug output after pass

### ISSUE THREAD

**Issue by killerducky** [gcp/leela-zero#254]
I'm seeing some strange outputs in the debug log files I added while doing resign analysis. I haven't been able to figure out if it's just a bug in my additions to Training.cpp etc or if there is some other bug in the code. I also haven't been able to reproduce it in standalone leela runs. 

http://eidogo.com/#2ymdJUkqg:0,181
From this position the game continues: wPass, bM6. 

The corresponding line in the debug file for bM6 is:

step.netwinrate | step.root_uctwinrate | step.child_uctwinrate | step.bestmovevisits 
--|--|--|--
0.896203 | 0.882596 | 0 | 2

The netwinrate and root_uctwinrates make sense. I don't know why child_uctwinrate would be 0, or why bestmovevisits would be such a low value of 2, that seems impossible. I looked at a few different cases of this and they were all after white passed.

**Comment by killerducky** [comment]
I see a possible problem, UCTSearch::think calls dump_stats before Training::record. I was relying on that to do m_root.sort_root_children. But dump_stats got updated to not run if cfg_quiet, so now the children are not sorted. Is this a problem? Or should get_first_child() reliably get the best child even if sort_root_children has not been run?

Same question for the training data? It is also calling get_first_child().

**Comment by Ttl** [comment]
I have seen similar issue with low playouts when many moves are considered and pass just happens to have most visits while having 0 score:

This is with 100 playouts:
```
genmove b
Thinking at most 50.0 seconds...
NN eval=0.833009

pass ->       2 (V:  0.00%) (N:  0.434%) PV: pass 
  K5 ->       1 (V: 85.23%) (N:  0.297%) PV: K5 pass
  E4 ->       1 (V: 85.22%) (N:  0.312%) PV: E4 pass
 G10 ->       1 (V: 84.74%) (N:  0.300%) PV: G10 pass
  K7 ->       1 (V: 84.72%) (N:  0.309%) PV: K7 pass
  H7 ->       1 (V: 84.50%) (N:  0.315%) PV: H7 pass
  M3 ->       1 (V: 84.50%) (N:  0.328%) PV: M3 pass
  N9 ->       1 (V: 84.24%) (N:  0.303%) PV: N9 pass
  G8 ->       1 (V: 84.13%) (N:  0.305%) PV: G8 pass
 G16 ->       1 (V: 84.11%) (N:  0.325%) PV: G16 pass
 D13 ->       1 (V: 84.09%) (N:  0.321%) PV: D13 pass
  D5 ->       1 (V: 84.06%) (N:  0.308%) PV: D5 J2
  ...
```

**Comment by killerducky** [comment]
With 1000 playouts I think it should be impossible for the most visited node to have less than 3 visits?

**Comment by isty2e** [comment]
This seems very bizarre... Could it be the case that this happens for other moves other than pass?

**Comment by ljn917** [comment]
This is from master branch commit b0799267. Playouts are 1000.

```
Leela: genmove b
Thinking at most 50.0 seconds...
NN eval=0.854568
Playouts: 268, Win: 89.22%, PV: M6 pass K1 
Playouts: 531, Win: 88.68%, PV: M6 D11 J2 
Playouts: 791, Win: 88.38%, PV: M6 D11 J2 

  M6 ->      16 (V: 89.16%) (N:  1.1%) PV: M6 G1 pass 
 S17 ->      12 (V: 88.88%) (N:  0.9%) PV: S17 D11 pass 
 F12 ->      12 (V: 88.84%) (N:  0.9%) PV: F12 Q7 M6 
  A1 ->      12 (V: 87.50%) (N:  1.1%) PV: A1 Q7 J2 
 S19 ->      11 (V: 88.76%) (N:  0.9%) PV: S19 R7 J2 
  E7 ->      11 (V: 88.76%) (N:  0.8%) PV: E7 R7 A1 
...
```

**Comment by isty2e** [comment]
100 playouts is certainly not something to consider here... So I wonder what exactly does leela mean in
>I also haven't been able to reproduce it in standalone leela runs.
I assume it is leelaz? It can be due to difference in the source code (not sure what version @killerducky is running), something related with debug output, or actual bug in leelaz.

**Comment by ljn917** [comment]
I guess it is the next branch

**Comment by ljn917** [comment]
If the number of leaves on that node is 197, it means the nn has not learnt much about middle game.

**Comment by isty2e** [comment]
@ljn917 I think it is because of nonzero FPU, which was intended (at least in the master branch). There is a [PR](https://github.com/gcp/leela-zero/pull/238) which contains some discussion on this.

**Comment by ljn917** [comment]
I see

**Comment by gcp** [comment]
> Is this a problem? Or should get_first_child() reliably get the best child even if sort_root_children has not been run?

>Same question for the training data? It is also calling get_first_child().

Oh that sounds like a bad issue then.

**Comment by gcp** [comment]
>Same question for the training data? It is also calling get_first_child().

That is really for getting the first child though, not the best one. It doesn't need to know the best child, just traverse the list of all of them.

**Comment by bood** [comment]
How bad is this? Is white low winning rate related to this too?

**Comment by killerducky** [comment]
gcp, I just picked up your fix and verified it resolves the issue, thanks.

@bood No impact, the training part does not have a bug that was a false alarm on my part. Only the debug code I added had a problem which is only used to do some analysis on resign threshold setting.
