### ISSUE TITLE
When should LeelaZ start from fresh?

### ISSUE THREAD

**Issue by Yakago** [gcp/leela-zero#258]
With all the optimizations that have been (and will be) made, plus the various 'bug' fixes, could there some idea in starting over from scratch for example at this point?

I'm thinking that a potential issue could be that previous 'errors' will have a lasting effect on the future progress? Or is it more likely that the network will just progress and eventually 'forget' about the old trouble? - of course we can just wait and see.

I suppose starting over might be discouraging if it's not a restart with hopes of creating a 'final' version

**Comment by evanroberts85** [comment]
I would be tempted to start again from random, it would be a good test of how much the changes being made improve things, as we have the current run to compare to. I reckon we could get to the current elo level in just a week or less.

**Comment by isty2e** [comment]
During training I expect LZ to encounter all sorts of serious self-biases, but eventually get out of them somehow, and I believe that it is theoretically justified. Moreover, it is not certain if all serious errors and bugs are fixed at this moment, so even if we need to start over I feel like this is not the moment for that.

**Comment by gcp** [comment]
I don't see the point either. There's no evidence it has problems that got backed into a corner. There's a big imbalance which we think is due the passing game, but nothing really relevant changed there. (More playouts would make it less bad, but that just means it'll self correct very quickly)
