### ISSUE TITLE
Experiment request: multithreading

### ISSUE THREAD

**Issue by isty2e** [gcp/leela-zero#260]
I was really surprised to see that black's winrate is over 90% in [this comment](https://github.com/gcp/leela-zero/issues/78#issuecomment-349334079), since it never happened to me. For me, though black tends to win more, it was like somewhere between 60% and 70%.

One suspicious thing is that I always compile autogtp with m_cmdLine.append(" -t 1"); inserted in autogtp/Game.cpp, line 38 or somewhere. Otherwise it often crashes and self-play games are not terminated normally.

Could someone test the winrate of black/white with single/multithread? I'm afraid I can't, because as stated above multithreading results in frequent crashes for me.

**Comment by killerducky** [comment]
Can you post some information on the crash?

**Comment by isty2e** [comment]
@killerducky It's basically the same to what is printed in [here](https://github.com/gcp/leela-zero/issues/221). Somehow the games is terminated abnormally and autogtp won't start to play a new game.

**Comment by ljn917** [comment]
Do you mean it does not print the following?
```
... 200 (pass/resign) Game has ended.
Score: B+4.5
Winner: black
Writing dac050b703b048de908f9be7212da324.sgf
Dumping dac050b703b048de908f9be7212da324.txt
Stopping engine.
```

**Comment by isty2e** [comment]
@ljn917 For a game or two it works, terminates a game with a double pass or design, and prints the information such as you wrote there. But then somehow the self-play stops like this (which is taken from the issue I linked above):

>44 (N4) 45 (B5) 1 game(s) played in 7 minutes = 449 seconds/game, last game took 449 seconds.

So apparently the game ends without any double pass or resign, which implies that leelaz crashed, I suspect.

**Comment by ljn917** [comment]
I think so. It means game::waitForMove() returns false in the middle of the game. Probably you need to add some debug code to leelaz...

**Comment by ljn917** [comment]
It would be an issue if there is inconsistency.... I think the default is -t 2.

**Comment by isty2e** [comment]
I think given a fixed number of playouts, single threading presumably always results in stronger plays IIRC. So if we'd like to remain consistent, why not -t 1?

**Comment by ljn917** [comment]
I think -t 2 was chosen for performance consideration.

**Comment by gcp** [comment]
Using more threads for the same number of playouts always weakens the program. I suspect that it's not much for t=2 but it's unavoidable. MCTS-UCT does not have perfect parallel scaling.

**Comment by marcocalignano** [comment]
Please have a look at #262

**Comment by isty2e** [comment]
@gcp If multiple instances of autogtp can be created then I assume it would be always better to do so? It might be better for even submission rate, like tested [here](https://github.com/gcp/leela-zero/issues/141), and not to mention the strength. Also by multithreading I think we're deviating from the original AGZ, since self-play games are played by weaker MCTS routine than intended. If parallelism should be introduced, it doesn't have to be (and presumably shouldn't be) in form of multithreading in MCTS, I believe.

Anyway can please someone test this? Verifying single threaded version is not that lopsided (which was the case for me) wouldn't cost much, when statistical significance is considered.

**Comment by ihavnoid** [comment]
@isty2e - I looked through my runs overnight and none of them crashed like you described.  Can you give us an idea which git SHA you are using, and possibly what kind of CPU/GPU?

**Comment by isty2e** [comment]
It happened no matter what the version was; master, next, or master + some patches. I'm using 15-inch macbook pro 2017, so CPU is 7820HQ and GPU is Radeon Pro 560. I think this problem is somehow specific to macs, I guess?

**Comment by isty2e** [comment]
Anyway I care less about the crash issue (since I always compile with -t 1), and much more about the difference in strength with respect to threading. If the winrate of black differs so much depending on number of threads, that's really one thing we need to think about.

**Comment by sethtroisi** [comment]
I tested "-t 1" vs "-t 2" previously for 25 games and got a fairly even split back with the 137k network. Can repeat at some point if I get time

**Comment by isty2e** [comment]
@sethtroisi What about black's winrate of self-play, with -t 1 and -t 2? It is so peculiar that I'm the only person getting somewhat balanced results.

**Comment by sethtroisi** [comment]
@isty2e Running experiment for 30 minutes more (hoping for 50 games)

````
13 wins, 10 losses
23 games played.
Status: 0 LLR 0.188663 Lower Bound -2.94444 Upper Bound 2.94444
 -t 1 v  -t 2 (23 games)
            wins        black       white
 -t 1   13  56.5%   11  52.4%    2 100.0%
 -t 2   10  43.5%   10  47.6%    0   0.0%
                    21  91.3%    2   8.7%
````

**Comment by isty2e** [comment]
@sethtroisi I wonder if it will get statistical significance when more games are played... After that, could you please test the winrate of black, with -t 1 vs -t 1 and -t 2 vs -t 2? That's really the thing I eager to know about.

**Comment by isty2e** [comment]
This is confusing again... If this is not a thread issue, what could it be?

**Comment by isty2e** [comment]
@sethtroisi What are the version and OS you’re using for this test? Clearly it seems it isn’t a thread issue here.

**Comment by sethtroisi** [comment]
I'm on Linux using the next branch. I just discovered that the bool getScore() doesn't return winner, but instead returns if it was able to parse who won. Have to update my code and re run now :(

**Comment by isty2e** [comment]
With Mac/next I’m getting approximately 3:1 here with the latest net. The winners list is obtained by parsing stdout.

**Comment by sethtroisi** [comment]
```
**-t 1**
78 game(s) played in 231 minutes = 178 seconds/game, 1294 ms/move
              wins        black       white
ad8a1d02   72  92.3%   72 100.0%    0   0.0%
ad8a1d02    6   7.7%    0   0.0%    6 100.0%
                       72  92.3%    6   7.7%
```
```
**-t 2**
116 game(s) played in 227 minutes = 117 seconds/game, 466 ms/move
              wins        black       white
ad8a1d02   89  76.7%   89 100.0%    0   0.0%
ad8a1d02   27  23.3%    0   0.0%   27 100.0%
                       89  76.7%   27  23.3%
```
@isty2e Something weird is going on.

I used [two proportion z test](http://stattrek.com/hypothesis-test/difference-in-proportions.aspx?Tutorial=AP).

````
p = (p1 * n1 + p2 * n2) / (n1 + n2) = (72 + 89) / (78 + 116) = 0.83
SE = sqrt(0.83 * 0.17 * (1 / 78 + 1 / 116)) = 0.055
z_score = (p1 - p2) / SE = (72/78 - 89/116) / 0.055 = 2.833
|z| > 2.833 = 0.0046
````

**there's a difference!** between `-t 1` and `-t 2` on my computer (ubuntu, 1080Ti, next branch).

One thing I noticed was load on processor may play a part. I ran two instances of autogtp at the same time which can saturating my CPU, I'm rerunning on a different computer (with an older GPU) one at a time right now.

**Comment by isty2e** [comment]
There's a difference indeed... I feel dubious about the effect from CPU load though.

**Comment by sethtroisi** [comment]
I think one of us should summon gcp and ask what he thinks 

my theory (which I'm testing because it's simple to do so) is that under extraordinary CPU load -t 2 acts like -t 1 because the two threads never explore the tree at the same time..

**Comment by isty2e** [comment]
I have no idea about how resource is distributed over threads, maybe other people have some ideas as you said.

**Comment by gcp** [comment]
Your t=2 result claims to run more than twice as fast. Not much point in running these kind of tests with other stuff interfering.

FWI autogtp was changed to run with -t 1 because it supports the -g option now.

**Comment by isty2e** [comment]
Okay, though not everything has been made clear, anyway we're using -t 1. Closing this thread.
