### ISSUE TITLE
Illegal move played (suicide)

### ISSUE THREAD

**Issue by Dorus** [gcp/leela-zero#263]
The current network has gone completely haywire.

Just now i paired 585k network with 1k playouts (black) vs 3k playouts (white).

White still played pass moves a few times.
Black eventually did lose out.
Black made a suicide move. Isn't that supposed to be illegal?
Right after the suicide, white resigns!

https://imgur.com/a/lRAF1

sgf: http://eidogo.com/#2OZAdgyq0

Also engine settings:

Black: 
--gtp -w 6f274ab150b9c79a341cce67c97b9116a6fcf3b1a8c9a613f6f7a6709658750f --noponder -p 1000
White:
--gtp -w 6f274ab150b9c79a341cce67c97b9116a6fcf3b1a8c9a613f6f7a6709658750f --noponder -p 3000

**Comment by Phelanpt** [comment]
Tromp Taylor rules allow for multiple stone suicide, but doesn't allow for single stone suicide. However, leelaz is using modified rules, which seem to forbid suicide, yes:
https://github.com/gcp/leela-zero/issues/122#issuecomment-345986996

**Comment by gcp** [comment]
This is indeed a bug. It wasn't the intention to allow suicide even if TT allows it, to make the engine usable for normal Chinese rule games.

**Comment by Ttl** [comment]
I have seen similar issues with regular Leela when there is a mismatch between board state in GUI and GTP engine. This could just as well be a bug in the GUI.

**Comment by gcp** [comment]
I did a check and if I load the SGF to that position then S1 is not among the listed moves. So I believe @Ttl is right. GUI bug.

**Comment by Dorus** [comment]
I did try to save the sgf, and load it again in Sabaki to make sure i'm in a clean state. And it did it again.

However, i tried it now with GoGui, and it does play normal. In Sabaki gtp console it was also considering other illegal moves, in GoGui it does not.

The weird resignation the move after is also gone on GoGui. So yeah, closed ;)

**Comment by roy7** [comment]
Maybe you can report Sabaki bugs to them to fix. :)

**Comment by killerducky** [comment]
I ran into this problem awhile back. The problem is when you skip around the tree in sabaki and then ask the engine, sabaki does not replay the game in order to the engine. It plays all black move, and then all white moves. This confuses LeelaZero because it depends on the last 16 moves for history.

As a workaround I use the LeelaZero text GTP interface for my analysis. I hope someone can fix sabaki.

**Comment by earthengine** [comment]
Sabaki have nothing to fix. It have the right to re-order the game. The problem is that when you play two black move or two white moves you have to insert a pass in between. The network should be clever enough to know that although the same final position comes from different history, they mean the same.

**Comment by Phelanpt** [comment]
> Sabaki have nothing to fix. It have the right to re-order the game. The problem is that when you play two black move or two white moves you have to insert a pass in between. The network should be clever enough to know that although the same final position comes from different history, they mean the same.
That doesn't make sense, the reason why NN like Leela Zero take the last positions as input is primarily because of ko issues, I think. With the re-ordered moves, you lose any ko information.

**Comment by earthengine** [comment]
> That doesn't make sense, the reason why NN like Leela Zero take the last positions as input is primarily because of ko issues, I think. With the re-ordered moves, you lose any ko information.

Remember, re-ordering moves *may* results in lost ko information but not necessary. It is possible to analyse a game and re-order it in a way that remains its ko information. If you can prove that Sabaki does lost ko information in a specific game, then yes Sabaki have a bug to fix. Until then, it is Leela to handle re-ordered games properly.

**Comment by Dorus** [comment]
Sabaki 100% loses ko information. I just tried it:

![afbeelding](https://user-images.githubusercontent.com/4461459/34464672-d6c25310-ee8a-11e7-9d39-b1b267bd15c8.png)

**Comment by earthengine** [comment]
Glad to see that Sabaki 0.32.2 released. Let's see how it works. Cheers!

**Comment by roy7** [comment]
The change notes list:

> When updating engine boards, Sabaki will try to replay moves in game order first

So that might fix these sorts of issues. I also saw him link to https://github.com/yishn/LeelaSabaki which will integrate lots of extra info from Leela into the Sabaki client. Someone check it out and report back?

**Comment by Dorus** [comment]
I tried it. It does indeed input the game correctly now so LeelaZ knows how the board looks like.
