### ISSUE TITLE
Scoring question

### ISSUE THREAD

**Issue by tamubun** [gcp/leela-zero#264]
I have a question about Leela zero's scoring.

Leela zero often ends a game both black and white move pass even if there are many points to play.
And my understanding about Chinese rule, the score is the difference between the number of stones for both sides plus komi. But seeing the result of zero's self play (http://zero.sjeng.org/view/3329817c928a63806a417f5a3fe719c4bac08b635c1d086ca045c5e464a93b13), it seems somewhat different from that.

I counted stones of above linked game at final position: black 68 stones, white 59 stones, so I think the score should be 68-(59+7.5) = 1.5, but zero said the score is b+3.5. What's the difference?

**Comment by zediir** [comment]
It uses Tromp-Taylor scoring rules https://senseis.xmp.net/?TrompTaylorRules

**Comment by vitamancy** [comment]
You aren't counting the "territory" (open spaces that only connect to 1 color) -- black has 3 and white has 1, so that accounts for the two point difference between your computation and the score.

**Comment by tamubun** [comment]
Thanks for comments. The scoring rules sounds very reasonable, and I understand.
