### ISSUE TITLE
Proposal: Disable pass for 10% of the game

### ISSUE THREAD

**Issue by ljn917** [gcp/leela-zero#265]
This is inspired by the AlphaGo Zero paper, in which resignation was disabled for 10% of the game. Many people may argue that the net should eventually learn white cannot pass just hoping black also passes, but disabling pass can accelerate learning.

**Comment by isty2e** [comment]
It is essentially putting human knowledge in it, that passing is bad in general. Moreover, without pass the game should end with resign or reaching maximum number of moves (723), which might hinder fast game generation.

**Comment by ljn917** [comment]
@isty2e I agree that it is putting human knowledge. I am running a local version that does not allow passing before 300 moves. Considering it is only 10%, it won't be that bad, and we can disable it after white winning rate increases.

Currently, my doubt is whether white have a chance to win or not with no pass, because the net is completely on the black side.

**Comment by isty2e** [comment]
@ljn917 Regarding the black winrate issue, as I mentioned in other issues, it might be an issue with multithreaded MCTS, which isn't as strong as intended (single threaded) version. I really wish I could test it by myself...

**Comment by ljn917** [comment]
@isty2e If it is MCTS issue, why does it have a bias on one color? If you are right, I think it means the multithread MCTS has a bug. It would be better disable it for now.

**Comment by isty2e** [comment]
@ljn917 I'm not sure why, and in fact no one has tested it yet unfortunately so we don't know if that is even true. Anyway, it is not a bug, since when multithreaded MCTS becomes always weaker given a fixed number of playouts. Nonetheless, I do think that it is better to disable multithreading.

**Comment by ljn917** [comment]
I  would like to withdraw my doubt because I just saw white won after playing through the end.

**Comment by ljn917** [comment]
@isty2e I think there were some testing in other discussions, but I don't have a good understanding why it is weaker or has a bias. I have not tried to change the num of threads either.

Usually, people expect that multithreaded program should behave exactly like single threaded program, except the differences in speed. I don't know what is the issue here.

**Comment by earthengine** [comment]
This is like what I proposed in another thread. I suggested that passing early should be considered resign in the rule perspective, so it only affects the results and causes a immediate end of the game. The benifit of this is this "knowledge" is in the rule level, and can be considered an undocumented rule already applied to human games (think of you are playing with your friends and the game is just beginning and you have something else to do. Then you just tell your friend you are not going to take the next move and the game ends).

**Comment by isty2e** [comment]
@earthengine That real world example seems not that persuasive for me, as it is more like resignation than a pass. Also the distinction between early and late game is arbitrary and artificial here.

**Comment by isty2e** [comment]
@ljn917 I haven't witnessed such a test being performed. And multithreaded MCTS always does not behave exactly the same to single threaded one, so if people are expecting them to be identical, it is some kind of misconception.

**Comment by ljn917** [comment]
@isty2e Maybe we should also suggest disable multithread?

**Comment by isty2e** [comment]
@ljn917 That's what I suggested in the previous issue. But before that, the test I requested is better be performed.

**Comment by ljn917** [comment]
@isty2e I think it is better to fix the crash issue first. Maybe you can attach a debugger to leelaz and dump the backtrace if it crashes.

**Comment by isty2e** [comment]
@ljn917 I really don't care about the crash thing. It only happens when the MCTS is multithreaded and is specific to mac. If we're going to run leelaz with single thread then the issue becomes less prioritized. IMHO it is much more urgent to figure out how threading affects the self-play games.

**Comment by ljn917** [comment]
@isty2e The crash may mean the multithreaded code has a hidden bug, and only you can investigate it....

For the num of threads, I guess it is better to set it to 1, and then figure out the issue later.

**Comment by isty2e** [comment]
@ljn917 To determine whether we'll set -t 1 or -t 2, it is essential that we investigate the effect of multithreading first. It should be preceded before we decide, and it has the top priority. Other minor issues are to be settled after that.

**Comment by ljn917** [comment]
@isty2e If -t 2 had a bug, it would not be worth to consider at all

**Comment by isty2e** [comment]
@ljn917 The crash happens only for macs, and I don't think there's something wrong in terms of MCTS performance. Again, it is a minor issue, and it will have nothing to do with what I'm suggesting here.

**Comment by ljn917** [comment]
@isty2e I never think a crash is a minor issue.

**Comment by isty2e** [comment]
@ljn917 It will be, if we decide to forbid multithreading. Again I stress that that decision precedes everything.

**Comment by bood** [comment]
@ljn917 I'm on Mac too but never sees a crash. If you tell me how to reproduce, I can take a look into it. You probably should open an separate issue for that.

**Comment by ljn917** [comment]
@bood Please ask @isty2e . I did not see this issue on my linux

**Comment by isty2e** [comment]
@bood I have no idea how to reproduce it. I just complie following the instruction and simply run autogtp.

**Comment by bood** [comment]
`master` branch? and how often do you see it?

**Comment by isty2e** [comment]
@bood Yes, and I encountered it very frequently (after a couple of games) until I recompile with -t 1.

**Comment by Marcin1960** [comment]
@ljn917 It is essentially putting human knowledge in it, that passing is bad in general.

Not really. It would be a removal of an inherent bias, removal based on human knowledge but not passing any  human knowledge. 

Otherwise the whole project could be considered as phony, because it is conducted by humans with some knowledge, instead of being born from primordial slime.

**Comment by ljn917** [comment]
@Marcin1960 I think @isty2e means no pass in early games is human knowledge. If we do not allow passing, the NN will learn this through our heuristics, not through self-play.

**Comment by isty2e** [comment]
@Marcin1960 It is, because the idea is based on human knowledge that

1. Passing results in a lower winrate, and
2. Especially it is so for early stage of the game.

Furthermore, the 300 moves limit makes it even more artificial. At any rate, this is not considered _tabula rasa_.

**Comment by ljn917** [comment]
Close this as @gcp said no.
