### ISSUE TITLE
Suggestion: Forcing single threading

### ISSUE THREAD

**Issue by isty2e** [gcp/leela-zero#268]
I've claimed it elsewhere, but for clarification I post this issue.

Multithreaded MCTS is in general weaker than single threaded one when the number of playouts is fixed. Then, it will be beneficial to run two instances of autogtp with single thread each than one instance of autogtp with two threads, for example. These two generate self-play games at the same speed, but the games from the former are stronger than those from the latter. There will be nothing we lose, provided that everyone has no problem running multiple instances of autogtp.

**Comment by gcp** [comment]
It's not even needed to run multiple instances, the current autogtp in "next" can run multiple games in multiple threads.

That said, I've seen no proof that there's a significant effect for t=2, more like the opposite.

**Comment by isty2e** [comment]
@gcp But one particular thing is that while everyone is reporting that black is dominating, I'm not. And the only difference I see is that they run autogtp with -t 2, while I'm running with -t 1. I'd really like to test it especially for the winrate of the black, but I'm afraid I can't. I'm just waiting for someone to test it for like 20 games or so...

**Comment by SharlatanY** [comment]
@isty2e I'd be glad to help you out if you can tell me what I'll have to do exactly and if it works on Windows.
Just tried to start autogtp.exe with -t 2 but got told that "t" is an unknown option, so, I'm assuming there's more work involved...

**Comment by isty2e** [comment]
@SharlatanY If you run autogtp as it is, it is using two threads (-t 2). You need to modify the source to run it with a single thread.

In autogtp/Game.cpp, around line 35, there will be some lines like this:

>cmdLine.append(weights);
>cmdLine.append(" -p 1000 --noponder");

Here you can add 

>cmdLine.append(" -t 1");

and recompile autogtp to run it with a single thread. So you can run this version to check if self-play is that lopsided for black or not.

**Comment by SharlatanY** [comment]
@isty2e I see, so it's not just a param but I'll have to set up the whole build environment first and compile it myself... not much experience with that but I'll give it a try if I've got the time.

**Comment by gcp** [comment]
FWIW I will patch up autogtp to:

1) Use -t 1
2) By default set "-g" to detected cores / 2.
