### ISSUE TITLE
zero.sjeng.org error?

### ISSUE THREAD

**Issue by Marcin1960** [gcp/leela-zero#270]
"8891 in past 24 hours, 3009 in past hour"?

**Comment by l1t1** [comment]
because network file updated
<pre>

Network Hash |Games

ad8a1d025c81264d9dc14f655466f9303db0ea6de241c56bbe3122c71557e686 |9116 
6f274ab150b9c79a341cce67c97b9116a6fcf3b1a8c9a613f6f7a6709658750f | 137844 
</pre>

**Comment by Marcin1960** [comment]
Thanx

**Comment by roy7** [comment]
Hey that's odd. It only reports past 24/1 hour of the most recent network? I wonder why I did it that way. Odd. I'll look and see if I can fix it without causing a performance issue. :)

**Comment by roy7** [comment]
Hah, mystery solved. I think @gcp moved the prior network data out of the live web site database, so those rows weren't in there to count any more for the stats reporting.
