### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Azirine** [gcp/leela-zero#271]
The next branch is 60 commits ahead of master now, is there any reason for not compiling a new release?

**Comment by gcp** [comment]
Yes, pull request #238.

**Comment by gcp** [comment]
@killerducky What's your opinion on the resignation situation? I noticed that you measure incorrect resignations and they're low, but that's expected if black always wins. How do the correct vs incorrect ratios look if you resample to have an equal amount of black and white wins?

**Comment by killerducky** [comment]
I just restarted my autogtp with resign disabled. When I get off work in 6 hours I'll have some data and I'll improve the script to analyze incorrect resigns for white vs black.

Since we are getting a decent amount of white wins we know at least the threshold isn't totally wrong. My gut feel is that we picked a conservative enough value that it should be ok.

**Comment by earthengine** [comment]
I would suggest to postpond this until Saturday. As I am not available tonight and there still some bugs reported for the new MSVC stuff (making autogtp not compiling), I think it would be better to have all those solved tomorrow.

Another proposal, the MSI installer will not be in this release though.

**Comment by isty2e** [comment]
I see a few W+R games, though unlike others I'm getting a relatively even results unlike others (ca. 3:1).

**Comment by killerducky** [comment]
Ok I added more stats and I have 147 games. 5% might be a little high for the current code, I hope the FPU change will fix that. Summary of the key stat:

```
Of games White won:
    resign rate 5%: Incorrect uct resigns = 3/11 (27.27%)
    resign rate 2%: Incorrect uct resigns = 2/11 (18.18%)
    resign rate 1%: Incorrect uct resigns = 0/11 (0.00%)

```
I looked at the biggest comeback game. The evaluation isn't really wrong, it's just that Black blunders the game later. I don't think it would be so bad if games like this were cut, assuming such blunders
will be played in other games too and the net can learn from them. If games like this are left in the pool the value net will be confused by the earlier positions which seem to indicate Black was going to win the game, which is in fact normally true.

White resigns with a threshold of 2%:
http://eidogo.com/#1k3026DqG:0,257

Black blunders and white's eval has a huge jump from 0.014 to 0.764(!)
http://eidogo.com/#1k3026DqG:0,293

More detailed stats:
```
Resign rate: 0.05
Black won 136/147 (92.52%)
Of games Black won:
    Incorrect uct resigns = 0/136 (0.00%)
    Correct uct resigns = 116/136 (85.29%)
    No Resign = 20/136 (14.71%)
    Average game length = 240. Average game length with resigns = 108 (55.09% reduction)
Of games White won:
    Incorrect uct resigns = 3/11 (27.27%)
    Correct uct resigns = 0/11 (0.00%)
    No Resign = 8/11 (72.73%)
    Average game length = 147. Average game length with resigns = 38 (74.06% reduction)
Of all games:
    Incorrect uct resigns = 3/147 (2.04%)
    Correct uct resigns = 116/147 (78.91%)
    No Resign = 28/147 (19.05%)
    Average game length = 233. Average game length with resigns = 102 (55.99% reduction)

Resign rate: 0.02
Black won 136/147 (92.52%)
Of games Black won:
    Incorrect uct resigns = 0/136 (0.00%)
    Correct uct resigns = 79/136 (58.09%)
    No Resign = 57/136 (41.91%)
    Average game length = 240. Average game length with resigns = 173 (27.88% reduction)
Of games White won:
    Incorrect uct resigns = 2/11 (18.18%)
    Correct uct resigns = 0/11 (0.00%)
    No Resign = 9/11 (81.82%)
    Average game length = 147. Average game length with resigns = 97 (34.10% reduction)
Of all games:
    Incorrect uct resigns = 2/147 (1.36%)
    Correct uct resigns = 79/147 (53.74%)
    No Resign = 66/147 (44.90%)
    Average game length = 233. Average game length with resigns = 167 (28.17% reduction)

Resign rate: 0.01
Black won 136/147 (92.52%)
Of games Black won:
    Incorrect uct resigns = 0/136 (0.00%)
    Correct uct resigns = 59/136 (43.38%)
    No Resign = 77/136 (56.62%)
    Average game length = 240. Average game length with resigns = 195 (18.71% reduction)
Of games White won:
    Incorrect uct resigns = 0/11 (0.00%)
    Correct uct resigns = 2/11 (18.18%)
    No Resign = 9/11 (81.82%)
    Average game length = 147. Average game length with resigns = 146 (0.37% reduction)
Of all games:
    Incorrect uct resigns = 0/147 (0.00%)
    Correct uct resigns = 61/147 (41.50%)
    No Resign = 86/147 (58.50%)
    Average game length = 233. Average game length with resigns = 191 (17.85% reduction)
```

**Comment by WhiteHalmos** [comment]
+1 for 1%

**Comment by isty2e** [comment]
We can probably come back to this later when the FPU and related things are settled.

**Comment by isty2e** [comment]
Now everything seems to be resolved in the next branch. Will the next version released soon, or will it include distributed testing?

**Comment by gcp** [comment]
Yes, doing basic sanity tests now.

**Comment by marcocalignano** [comment]
@gcp should I rebase the new changes in your next branch?
If you agree you need to give me time over the weekend the rebase will have a lot of merging to go throu

**Comment by earthengine** [comment]
I managed to create the pull request for MSVC updates. So it is free to release now. Next release we will have MSI installer.

**Comment by gcp** [comment]
I'm already done on my side, I build from custom built dependencies with a bit newer versions, so I didn't need the update for the MSVC part. I'll pull that later.
