### ISSUE TITLE
git tech support for next branch

### ISSUE THREAD

**Issue by killerducky** [gcp/leela-zero#272]
Something weird is happening with the next branch. I'm not a git expert but it seems like maybe gcp's next branch has had a history rewrite or something? I don't think I've made any recent commits on next, and comparing my github next to gcp's the commit log messages are the same. (The hashes are different, should they be the same? Or maybe difference since they're different forks?)

(ETA: I looked at master and the sha hashes are identical. So something has happened between my next and gcp's next on github.)

https://github.com/gcp/leela-zero/commits/next
https://github.com/killerducky/leela-zero/commits/next

I did a clean clone of my repo, added gcp's as a remote, and tried to merge next:

```
git clone https://github.com/killerducky/leela-zero
cd leela-zero
git remote add upstream https://github.com/gcp/leela-zero
git fetch --all
git checkout master
git merge upstream/master
git checkout -b next origin/next
git merge upstream/next

Auto-merging training/tf/tfprocess.py
Auto-merging src/config.h
Auto-merging autogtp/main.cpp
CONFLICT (content): Merge conflict in autogtp/main.cpp
Auto-merging autogtp/Validation.cpp
CONFLICT (add/add): Merge conflict in autogtp/Validation.cpp
Auto-merging autogtp/Production.h
CONFLICT (add/add): Merge conflict in autogtp/Production.h
Auto-merging autogtp/Production.cpp
CONFLICT (add/add): Merge conflict in autogtp/Production.cpp
Auto-merging autogtp/Game.cpp
CONFLICT (content): Merge conflict in autogtp/Game.cpp
Auto-merging README.md
Automatic merge failed; fix conflicts and then commit the result.

```

**Comment by ljn917** [comment]
I also see weird things in the next. Some commits are missing or re-sorted.

**Comment by bood** [comment]
Same thing here when I tried to update the `next` branch with `git pull origin`

**Comment by gcp** [comment]
I did a rebase on master yesterday as I was preparing to merge next onto master. The git fallout of that was a bit more than expected.

**Comment by gcp** [comment]
Next has been merged to master. Sorry for the trouble that rebase caused.
