### ISSUE TITLE
通过对称增加盘数：To increased games by symmetrical

### ISSUE THREAD

**Issue by dongcijie** [gcp/leela-zero#273]
一盘围棋通过对称可以当八盘围棋用啊

A game of go can be used in eight sets of games by symmetry

**Comment by sethtroisi** [comment]
This is already done in playing: https://github.com/gcp/leela-zero/blob/master/src/Network.cpp#L460
and training: https://github.com/gcp/leela-zero/blob/master/training/tf/parse.py#L49

**Comment by l1t1** [comment]
I am not sure if the leelaz always  put first step in range of triangle (a1,k1,k10,)in a go board?
