### ISSUE TITLE
How can we notify/recommend updates?

### ISSUE THREAD

**Issue by isty2e** [gcp/leela-zero#277]
Clearly, LZ 0.7 behaves differently from 0.6 in may aspects. Therefore we would like to people be informed of the update. 

Other than forcing the required client version, what can we do for this? Clearly, it is hard for autogtp v4 and v6, but for future updates, we might want to notify people to update when one starts a new game.

How about, for example, adding "latest_client_version" field in addition to "required_client_version" so if there is an update the client can compare it with its version and notify, and possibly open the webpage for this?

**Comment by gcp** [comment]
I'm not sure what this gains you over the current method, which achieves exactly this already.

The idea is to have everyone on the latest update that is stable. That's why the server can enforce the client version. And it will enforce v6 + 0.7 if no issues pop in the coming hours.

**Comment by isty2e** [comment]
If the client version will be tightly restricted, indeed this would be unnecessary.

**Comment by isty2e** [comment]
So I posted this, with a situation in mind such that the client version is not strictly restricted but an update is out. Can I expect that is unlikely to happen?

**Comment by gcp** [comment]
I wouldn't generally enforce an update unless there were clear benefits, i.e. an important bugfix or speed update, important changed parameters, because it will stop people's instances (if they didn't update by themselves yet).

Imagine someone adds a graphical board to autogtp but nothing else is changed. In that case I wouldn't enforce an update. But do you really need to alert people to it then?

**Comment by isty2e** [comment]
Okay, closing this issue then.

**Comment by gcp** [comment]
The current situation is a nice example. People who just got AutoGTP v6 don't need to update, as it defaults to threads=1 so it doesn't suffer from the bug, but I still made a new release.
