### ISSUE TITLE
Virtual loss is broken

### ISSUE THREAD

**Issue by gcp** [gcp/leela-zero#278]
This might explain quite a few things, including the lopsidedness of the games played by master that was observed with t=2.

https://github.com/gcp/leela-zero/blob/13e8dbe37da43ef422c1ef67c1fd4b59580bf945/src/UCTNode.cpp#L328

The problem is that we are adding visits, but the score in the node is for black. So if we are white, we are actually adding wins...

**Comment by isty2e** [comment]
Indeed if this was the reason, many things can be explained... But it is fortunate that this was found before proceeding further.

**Comment by roy7** [comment]
Since I don't know anything about this area of the code, I'm curious, does this mean in some situations white would choose/rate moves that were best for the opponent instead of itself?

**Comment by gcp** [comment]
It's not immediately clear what impact it has. It changes the moves the program investigates if both threads clash on accessing a node - not their recorded score - but remember that at the root we proportionally pick the move that was most investigated, so it does have some effect there.

**Comment by roy7** [comment]
Well should be easy to test two clients, one with a fix and one without, both running -t 2 and see if one has evenish scores and the other has black domination.

**Comment by gcp** [comment]
That's what I'm doing right now.

**Comment by roy7** [comment]
Will be fantastic if this solves the black win % mystery.

**Comment by killerducky** [comment]
Seems like this would fix it? I'm at work so I can't test this.
```
    auto visits = get_visits() + m_virtual_loss;
    auto blackeval = get_blackevals();
    if (tomove == FastBoard::WHITE) {
        blackeval += m_virtual_loss
    }
```

**Comment by gcp** [comment]
Yes, but with a cast. I have a fix, I'm already testing it.

**Comment by roy7** [comment]
What did your tests end up showing?

**Comment by gcp** [comment]
Score for the same match as in the distributed testing thread went from 1:1 to 2:1 ratio in favor of the new network (i.e. same as what was seen there). I didn't even look at the color distribution, as the results in that test had a highly significant difference in outcomes disregarding color.

I didn't play all that much games, but I was 100% sure the code was wrong, and it's wrong for one color only, and we know white is having problems, and there's been several people indicating it was threading related...the evidence mounts up.

**Comment by Marcin1960** [comment]
There is a Polish proverb "Two heads are better than one" Here we have several :)

**Comment by isty2e** [comment]
With this bug, I wonder when we are going to allow only clients with version>=6. Hopefully in a day?

**Comment by Marcin1960** [comment]
Google people should join and leak some ideas. Maybe they already do?

**Comment by gcp** [comment]
>With this bug, I wonder when we are going to allow only clients with version>=6. Hopefully in a day?

Yes, very soon.

**Comment by gcp** [comment]
>Google people should join in and leak some ideas.

Someone from Google already submitted patches. Not the DeepMind people though. Apparently those are forbidden from talking about their own research papers: http://computer-go.org/pipermail/computer-go/2017-December/010567.html

**Comment by roy7** [comment]
I'm even more excited now to see how things go once this rolls out. To think with -t 2 default everyone had questionable white play happening and only black was really playing as intended, yet the network still managed to win and start to improve in ways humans can notice. And it wins some games vs weak bots on KGS alerady.

It'll have to unlearn some connections to which player's move it is, but I'm sure in time that'll fade.

With both sides playing proper now we will, I hope, see a dramatic increase in network improvements.

**Comment by WhiteHalmos** [comment]
Not to mention faster training and testing of new networks in the pipelines. Exciting!

**Comment by justinwong098** [comment]
@gcp 
>forbidden from talking about their own research papers

Have you tried reaching out to one of the first authors of the paper, David Silver or Julian Schrittwieser? They were able to answer some technical questions in their AMA, so maybe they're high enough in the hierarchy to disclose some information.

**Comment by Marcin1960** [comment]
Google management should wake up. They need all the sympathy they can get. What is a better PR than support for the grass-root, people's projects?

**Comment by bood** [comment]
@gcp I think this also have impact on the winning rate of previous networks as white is always likely to lose. The Elo graph may be not correct at all.

**Comment by gcp** [comment]
>The Elo graph may be not correct at all.

It's very inaccurate regardless, but I've run most tests with t=1.

**Comment by isty2e** [comment]
The current best network, for example, beats its predecessor with 60-26. Naively, this amounts to Elo rating difference of 145, but the winrate is somewhere between 60.6% and 76.9% with 95% confidence interval. This amounts to Elo rating difference of 75 and 209, so considering error accumulation, it is already very inaccurate.

On the other hand, if we played 400 games and it was still 69.8% (279-121), the range becomes 65.7% and 73.3%, with corresponding Elo ratings of 113 and 175.
