### ISSUE TITLE
Possible bug in UCTNode::dirichlet_noise ?

### ISSUE THREAD

**Issue by amirlb** [gcp/leela-zero#282]
I was reading the code for fun, and saw something strange: the child_cnt variable is not incremented during the last loop in the method (lines 229-235 in https://github.com/gcp/leela-zero/blob/master/src/UCTNode.cpp).

If I'm reading it correctly, this would make the noise not take Dirichlet form but be uniform among all the actions, with the uniform constant between 0 and 0.25, determined by a one-variable Dirichlet distribution.

Is this OK?

**Comment by isty2e** [comment]
It seems it is not uniform, because of child = child->m_nextsibling; is there, if I understand correctly. I had it printed and it was not, perhaps someone can confirm this.

**Comment by killerducky** [comment]
I think you're right. I'm working on something else closely related right now so I will try fixing this as well.

**Comment by sethtroisi** [comment]
I agree it looks like you just need to add 
```  child_cnt++;``` on 235

**Comment by isty2e** [comment]
Oh wait, I was so sleepy that I was not looking into it carefully and was printing score instead of eta_a. Yes you're right, and this can be problematic indeed.

**Comment by isty2e** [comment]
Oh you're right. In my previous (deleted) comment I was somehow printing score instead of eta_a for debugging.

**Comment by gcp** [comment]
This warrants another release.
