### ISSUE TITLE
Is it helpful if let leelaz always put first step in range of triangle (a1,k1,k10,)in a go board

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#286]
as https://github.com/gcp/leela-zero/issues/273 told mentioned,
games whose first step on other part of the board can done by symmetrical

**Comment by bood** [comment]
Since symmetrical is already taking into account, why bother?

**Comment by l1t1** [comment]
thanks
to eliminate possible duplication, but it seems useless since the  probability of  duplication is very small.
