### ISSUE TITLE
Miscounts in Games

### ISSUE THREAD

**Issue by polhode** [gcp/leela-zero#288]
I wanted to look at the games my computer was playing, so I pulled the moves it made one game at a day from the command line and transcribed it to ogs. It seems that three of the four games I pulled were accounted as wins for the wrong side.
I know my sample size is quite low, but as the classification of games as wins and losses is one of the most central parts of the training, I thought I should mention it.
Link to the four games I transcribed:
https://online-go.com/review/282578

**Comment by roy7** [comment]
For example the giant group on lower left is still alive until white captures it. In Tromp Taylor, there are no dead stones.

**Comment by polhode** [comment]
Thanks
I never heard of Tromp-Taylor scoring before, and it is not mentioned somewhere in the FAQ or the readme.
Unfortunately I am not qualified to update the FAQ in a way that would maintain the English/Chinese style of the FAQ.
