### ISSUE TITLE
Incomplete dump_training?

### ISSUE THREAD

**Issue by Alderi-Tokori** [gcp/leela-zero#29]
In the paper, they say the following thing : "The rules of Go are invariant under rotation and reflection; this knowledge has been used in AlphaGo Zero both **_by augmenting the dataset during training to include rotations and reflections of each position_**, and to sample random rotations or reflections of the position during MCTS (see Search algorithm)."

It seems to imply that each position generated during self-play was duplicated for every possible rotation*reflection, so each position translates to 8 different training examples. Maybe leelaz could do it, too when she dumps the training.

**Comment by gcp** [comment]
This is already implemented: https://github.com/gcp/leela-zero/blob/cc872f1c9c00c3c46edd58bdef274a11fcbe947f/training/tf/parse.py#L99

**Comment by gcp** [comment]
Note that it makes no sense to store them when generating the dataset. It just makes it bigger. The symmetries can be generated on the fly during training.

**Comment by Alderi-Tokori** [comment]
Yes, my bad, I only searched in the leela sources for it, I didn't think about looking into the parsing code.
