### ISSUE TITLE
Mac OS X 0.8 version:  ./autogtp  -g 2 outputs same 2 games, is this expected output? 

### ISSUE THREAD

**Issue by tonyxia2016** [gcp/leela-zero#290]
Mac OS X 0.8 version:  ./autogtp  -g 2 outputs same 2 games, is this expected output? 

./autogtp  -g 2
AutoGTP v7
Using 2 thread(s).
Best network hash: 2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c
Required client version: 4 (OK)
Already downloaded network.
./leelaz -r 1 -g -t 1 -q -d -n -m 30 -w 2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c -p 1600 --noponder
./leelaz -r 1 -g -t 1 -q -d -n -m 30 -w 2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c -p 1600 --noponder
Engine has started.
Infinite thinking time set.
Engine has started.
Infinite thinking time set.
1 (D5) 1 (D5) 2 (D10) 2 (D10) 3 (N4) 3 (N4) 4 (R16) 4 (R16) 5 (C14) 5 (C14) 6 (K7) 6 (K7) 7 (L7) 7 (L7) 8 (N19) 8 (N19) 9 (M18) 9 (M18) 10 (L3) 10 (L3) 11 (B11) 11 (B11) 12 (F1) 12 (F1) 13 (R9) 13 (R9) 14 (H2) 14 (H2) 15 (C8) 15 (C8) 16 (H16) 16 (H16) 17 (L16) 17 (L16) 18 (E13) 18 (E13) 19 (N3) 19 (N3) 20 (A17) 20 (A17) 21 (O15) 21 (O15) 22 (S3) 22 (S3) 23 (S6) 23 (S6) 24 (K8) 24 (K8) 25 (L19) 25 (L19) 26 (Q10) 26 (Q10) 27 (M5) 27 (M5) 28 (O19) 28 (O19) 29 (H18) 29 (H18) 30 (L8) 30 (L8) 31 (S7) 31 (S7) 32 (E15) 32 (E15) 33 (O17) 33 (O17) 34 (B4) 34 (B4) 35 (D11) 35 (D11) 36 (D12) 36 (D12) 37 (C10) 37 (C10) 38 (C11) 38 (C11) 39 (C12) 39 (C12) 40 (C5) 40 (C5) 41 (R12) 41 (R12) 42 (R4) 42 (R4) 43 (C6) 43 (C6) 44 (D6) 44 (D6) 45 (H17) 45 (H17) 46 (E11) 46 (E11) 47 (R14) 47 (R14) 48 (C9) 48 (C9) 49 (D9) 49 (D9) 50 (C11) 50 (C11) 51 (B9) 51 (B9) 52 (Q14) 52 (Q14) 53 (D11) 53 (D11) 54 (M16) 54 (M16) 55 (E10) 55 (E10) 56 (R15) 56 (R15)

**Comment by l1t1** [comment]
I think the log can be omitted

**Comment by tonyxia2016** [comment]
I think maybe there is something wrong here. From the second round, the games output is different. The different games output should be expected.


357 (M10) 357 (M10) 358 (pass) 358 (pass) 359 (J9) 359 (J9) 360 (pass) 360 (pass) 361 (H8) 361 (H8) 362 (pass) 362 (pass) 363 (G7) 363 (G7) 364 (pass) 364 (pass) 365 (J4) 365 (J4) 366 (resign) Game has ended.
Score: B+Resign
Winner: black
Writing fccb96dd32194fce9a5edc9ac81f9742.sgf
366 (resign) Game has ended.
Score: B+Resign
Winner: black
Writing 7a34b3090cbc4af49afdc9edd4f57fbf.sgf
Dumping fccb96dd32194fce9a5edc9ac81f9742.txt
Dumping 7a34b3090cbc4af49afdc9edd4f57fbf.txt
1 game(s) played in 33 minutes = 2000 seconds/game, 2732 ms/move, last game took 1998 seconds.
curl -F networkhash=2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c -F clientversion=7 -F sgf=@fccb96dd32194fce9a5edc9ac81f9742.sgf.gz -F trainingdata=@fccb96dd32194fce9a5edc9ac81f9742.txt.0.gz http://zero.sjeng.org/submit
Game data 6265b8b7a53309eb3bbe2a6c9e4625dda183c48ab8b18a73cfea9af9122d902c stored in database
Best network hash: 2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c
Required client version: 4 (OK)
Already downloaded network.
Stopping engine.
2 game(s) played in 33 minutes = 1001 seconds/game, 2736 ms/move, last game took 1998 seconds.
curl -F networkhash=2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c -F clientversion=7 -F sgf=@7a34b3090cbc4af49afdc9edd4f57fbf.sgf.gz -F trainingdata=@7a34b3090cbc4af49afdc9edd4f57fbf.txt.0.gz http://zero.sjeng.org/submit
./leelaz -r 0 -g -t 1 -q -d -n -m 30 -w 2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c -p 1600 --noponder
Engine has started.
Infinite thinking time set.
1 (E14) Game data 6265b8b7a53309eb3bbe2a6c9e4625dda183c48ab8b18a73cfea9af9122d902c stored in database
Best network hash: 2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c
Required client version: 4 (OK)
Already downloaded network.
Stopping engine.
./leelaz -r 1 -g -t 1 -q -d -n -m 30 -w 2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c -p 1600 --noponder
2 (S7) Engine has started.
Infinite thinking time set.
3 (B15) 1 (B14) 4 (L15) 2 (B5) 5 (F2) 3 (D14) 6 (S12) 4 (L13) 7 (T6) 5 (C1) 8 (S9) 6 (L11) 9 (T4) 7 (D2) 10 (F1) 8 (F1) 11 (M17) 9 (M19) 12 (F9) 10 (S1) 13 (J9) 11 (S11) 14 (O14) 12 (B6) 15 (C12) 13 (F5) 16 (R14) 14 (R9) 17 (S16) 15 (S5) 18 (F10) 16 (L10) 19 (Q4) 17 (D18) 20 (J7) 18 (B10) 21 (C8) 19 (H5) 22 (F15) 20 (F17) 23 (D10) 21 (Q7) 24 (H2) 22 (T2) 25 (A15) 23 (D9) 26 (L1) 24 (R6) 27 (L7) 25 (R14) 28 (K2) 26 (P9) 29 (O7) 27 (E14) 30 (Q10) 28 (P2) 31 (G18) 29 (G4) 32 (C9) 30 (M10) 33 (J18) 31 (O17) 34 (L17) 32 (S12) 35 (D5) 33 (B9) 36 (B3) 34 (E12) 37 (P17) 35 (N4) 38 (D3) 36 (O16) 39 (D7) 37 (S13) 40 (F18) 38 (P17) 41 (Q3) 39 (Q15) 42 (D6) 40 (P16) 43 (J16) 41 (N16) 44 (D18) 42 (S16) 45 (P16) 43 (S15) 46 (D8) 44 (K18) 47 (L14) 45 (B7) 48 (M14) 46 (D8) 49 (D9) 47 (L3) 50 (B8) 48 (C9) 51 (E8) 49 (J16) 52 (C7) 50 (R12) 53 (E6) 51 (C10) 54 (D8) 52 (O4) 55 (C6) 53 (C8) 56 (C8) 54 (Q6) 57 (L16) 55 (N17) 58 (K16) 56 (Q16) 59 (K15) 57 (L2) 60 (M16) 58 (R18) 61 (M15) 59 (R11) 62 (N15) 60 (N15) 63 (E9) 61 (Q12) 64 (F14) 62 (G12) 65 (K17) 63 (H8) 66 (E7) 64 (K16) 67 (F7) 65 (K15) 68 (L16) 66 (K17) 69 (D11) 67 (R15) 70 (B4) 68 (J15) 71 (E15) 69 (R16) 72 (B6) 70 (J17) 73 (E16) 71 (C4) 74 (R18) 72 (E11) 75 (G16) 73 (B11) 76 (K18) 74 (B4) 77 (F16) 75 (O13) 78 (Q18) 76 (B8) 79 (R16) 77 (C11) 80 (J17) 78 (Q11) 81 (K5) 79 (M7) 82 (Q16) 80 (F8) 83 (Q17) 81 (C7) 84 (Q15) 82 (F6) 85 (G4) 83 (E8) 86 (R17) 84 (R17) 87 (H17) 85 (L6) 88 (H18) 86 (R5) 89 (C4) 87 (K7) 90 (S17) 88 (H12) 91 (H19) 89 (F9) 92 (C3) 90 (H10) 93 (M10) 91 (R13) 94 (K4) 92 (C3) 95 (N2) 93 (T12) 96 (H12) 94 (F4) 97 (L9) 95 (F3) 98 (H16) 96 (B16) 99 (H15) 97 (E4) 100 (H5) 98 (D17) 101 (J5) 99 (B15) 102 (H4) 100 (C17) 103 (N4) 101 (O7) 104 (G5) 102 (D3) 105 (L4) 103 (O5) 106 (L5) 104 (E17) 107 (L6) 105 (D4) 108 (M5) 106 (P7) 109 (M4) 107 (P4) 110 (J4) 108 (O6) 111 (K17) 109 (O3) 112 (M18) 110 (P3) 113 (Q7) 111 (P6) 114 (B16) 112 (P5) 115 (F5) 113 (O4) 116 (F4) 114 (P6) 117 (C16) 115 (O2) 118 (K14) 116 (B3) 119 (K12) 117 (G8) 120 (H8) 118 (Q4) 121 (K13) 119 (N6) 122 (J14) 120 (E3) 123 (L18) 121 (E2) 124 (J15) 122 (F2) 125 (O9) 123 (G2) 126 (T16) 124 (R3) 127 (N12) 125 (S6) 128 (J17) 126 (P1) 129 (E12) 127 (O15) 130 (H16) 128 (P15) 131 (P18) 129 (N14) 132 (O12) 130 (M15) 133 (J16) 131 (C2) 134 (L19) 132 (B2) 135 (B5) 133 (P18) 136 (A5) 134 (O14) 137 (C5) 135 (P12) 138 (E4) 136 (B1) 139 (K17) 137 (C6) 140 (E5) 138 (N13) 141 (P15) 139 (C5) 142 (J17) 140 (O18) 143 (O11) 141 (Q18) 144 (Q14) 142 (Q17) 145 (P14) 143 (N18) 146 (P13) 144 (O8) 147 (E7) 145 (P14) 148 (H16) 146 (M14) 149 (H9) 147 (O19) 150 (H14) 148 (J1) 151 (P12) 149 (R19) 152 (O13) 150 (H2) 153 (G11) 151 (H3) 154 (N17) 152 (S17) 155 (P11) 153 (Q19) 156 (A6) 154 (K2) 157 (Q9) 155 (G1) 158 (N11) 156 (K3) 159 (Q11) 157 (E1) 160 (G7) 158 (O12) 161 (H11) 159 (L4) 162 (F8) 160 (P11) 163 (D17) 161 (P13) 164 (G8) 162 (A16) 165 (G15) 163 (O11) 166 (F6) 164 (O15) 167 (G12) 165 (S9) 168 (N5) 166 (C15) 169 (H18) 167 (C14) 170 (O4) 168 (K4) 171 (O3) 169 (S7) 172 (Q12) 170 (S19) 173 (O5) 171 (S8) 174 (G14) 172 (K5) 175 (P4) 173 (L5) 176 (R11) 174 (C16) 177 (Q8) 175 (N12) 178 (B11) 176 (M18) 179 (S11) 177 (L18) 180 (S10) 178 (M17) 181 (R12) 179 (O10) 182 (R13) 180 (F15) 183 (A9) 181 (A8) 184 (A4) 182 (M12) 185 (T8) 183 (S4) 186 (R10) 184 (F14) 187 (C10) 185 (R4) 188 (B10) 186 (Q3) 189 (B9) 187 (S3) 190 (B7) 188 (R2) 191 (F11) 189 (M16) 192 (J8) 190 (L17) 193 (K6) 191 (S2) 194 (F5) 192 (N7) 195 (T15) 193 (O1) 196 (O18) 194 (K6) 197 (N10) 195 (J6) 198 (T17) 196 (J7) 199 (B12) 197 (H7) 200 (A19) 198 (J8) 201 (P10) 199 (L7) 202 (D4) 200 (J5) 203 (B1) 201 (H6) 204 (B18) 202 (K8) 205 (O17) 203 (L1) 206 (P19) 204 (L8) 207 (M11) 205 (M8) 208 (L3) 206 (S10) 209 (C18) 207 (R10) 210 (S8) 208 (N9) 211 (J16) 209 (N8) 212 (L13) 210 (T3) 213 (S6) 211 (R1) 214 (H16) 212 (Q1) 215 (E18) 213 (O9) 216 (C11) 214 (R7) 217 (J16) 215 (O7) 218 (K8) 216 (R8) 219 (A12) 217 (P8) 220 (L8) 218 (Q8) 221 (M8) 219 (O8) 222 (R3) 220 (K14) 223 (R6) 221 (Q9) 224 (D6) 222 (Q10) 225 (K17) 223 (P10) 226 (M3) 224 (Q9)

**Comment by Mardak** [comment]
In previous versions, I noticed in #141 that if I started multiple ./autogtp to measure the overall game throughput of multiple instances, sometimes they would play the same moves. To fix that, I would just wait a few seconds before starting up the second instance.

**Comment by gcp** [comment]
Leelaz seeds its rng with time(0) modulated by thread_id. This can end up being the same. I'd consider this a bug.

**Comment by gcp** [comment]
Note that one reason why this is being noticed now is the change from default threads = 2 to threads = 1.

**Comment by gcp** [comment]
Ok I found some truly disgusting bugs in the random number generator. It's not affecting leelaz much, but yikes.

https://github.com/gcp/leela-zero/blob/2550517ad6f4691e0a43b466510bb254638f5b70/src/Random.h#L63

Guess one time which ACTUAL function this is resolving to?

**Comment by gcp** [comment]
Fixed in next, will be in next release.

**Comment by roy7** [comment]
Ah you already fixed, I was going to suggest mixing in process id somewhere since that'd be different for each process.
