### ISSUE TITLE
why generate the file 022b302c296b4788820ca87f7d12dbc1.txt.debug.0.gz

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#291]
the file isn't uploaded
<pre>

curl.exe -F networkhash=2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c -F clientversion=7 -F sgf=@022b
302c296b4788820ca87f7d12dbc1.sgf.gz -F trainingdata=@022b302c296b4788820ca87f7d12dbc1.txt.0.gz http://zero.sjeng.org/sub
mit
Upload failed. Curl Exit code: 52
Continuing...

</pre>

**Comment by l1t1** [comment]
the begining of the file is
<pre>
1
0.923566 0.928446 0.931919 11
0.0715592 0.0715149 0.0745254 10
0.916815 0.926541 0.934496 19
0.0789339 0.0820616 0.0918863 11
0.918546 0.921954 0.929629 12
0.0753645 0.079354 0.0864596 10
0.912243 0.918785 0.92352 62
0.0763539 0.0827979 0.0918227 10
</pre>

**Comment by killerducky** [comment]
It's for the resign analysis. I agree it would be better if it was never generated, but It should get deleted, is it not?

**Comment by gcp** [comment]
Is the resign analysis generated in production? It should not.

**Comment by killerducky** [comment]
I can fix this tomorrow, probably add a separate dump_debug GTP command in addition to dump_training.

**Comment by gcp** [comment]
Fixed in "next" branch.
