### ISSUE TITLE
could you supply a tool for batch upload failed games when network or server free?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#294]
as https://github.com/gcp/leela-zero/issues/136 mentioned, fail rate increase due to bad network or server pressure.
now the game's sgf files are saved, if you also save the data files, then we can offline play games
and then upload all of them .

**Comment by gcp** [comment]
I think autogtp was supposed to retry on network errors, so that sounds like some error case that isn't handled. No need for a separate tool.

**Comment by l1t1** [comment]
in my option,
an offline player is also useful, since network file usually isn't change in a day.
even a small bat can retry upload if data file can be saved

**Comment by BHydden** [comment]
The problem with this idea, apart from it being more work, is that if the server is already coming under heavy load, it probably won't appreciate whole batches trying to come in rather than individual games

**Comment by gcp** [comment]
The server isn't loaded at all.

**Comment by l1t1** [comment]
as the idea of offline play, if i have a strong compute, but it cannot access Internet,
if i could copy the files to it, it also can build games

**Comment by l1t1** [comment]
[today2.txt](https://github.com/gcp/leela-zero/files/1541908/today2.txt)
I played 6 games, 3 failed
and 
i cannot download network file using autogtp, so I downloaded it manually.
to make more games, i think we should collect max users.
