### ISSUE TITLE
autogtp is taking more than 2 minutes to make a single move instead of 5-10 seconds with the same net

### ISSUE THREAD

**Issue by emdio** [gcp/leela-zero#297]
So it usually takes less than 10 seconds per move on my laptop, at least till last night. But this morning I launched autogtp and it's taking more than 2 minutes per move.

Is this behaviour expected. maybe due to a new net?

PS; just in case, these are the first lines after launhcing autogtp:

$ ./autogtp -k ~/Documents/Leelaz
AutoGTP v7
Using 1 thread(s).
Best network hash: 2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c
Required client version: 4 (OK)
Already downloaded network.
./leelaz -r 1 -g -t 1 -q -d -n -m 30 -w 2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c -p 1600 --noponder
Engine has started.
Infinite thinking time set.
(E5) 2 (R13)

**Comment by kimitsu** [comment]
@emdio Wouldn't hurt to know your hardware and OS parameters, maybe the model of your laptop, your OS, memory size, graphics card and driver version?

**Comment by emdio** [comment]
Linux-x86_64
6 GB RAM
NVIDIA GF108M [GeForce GT 540M]
Intel(R) Core(TM) i5 CPU M 480  @ 2.67GHz
NVIDIA Driver Version: 384.90

**Comment by emdio** [comment]
@kimitsu just to make it clear; the issue is not that it takes 2 minutes to make a single move, but that yesterday, using the same net, it took only 5-10 seconds to make a move.

**Comment by OmnipotentEntity** [comment]
Does it persist after a reboot?  It might be a bug wrt degraded performance coming back from sleep/hibernate and your video drivers.

**Comment by emdio** [comment]
@OmnipotentEntity I tried the reboot and still the same. Actually, I did a "git pull" after the reboot, there were some changes in the repo, I recompiled leelaz and autogtp, but it still takes more than 2 minutes to make one single move.
The funny thing is that some 12 hours ago, with the same net, it was taking 5-10 seconds.

**Comment by emdio** [comment]
Now that I think about it, all this happened actually after a reboot (I rarely reboot). My guess is that after rebooting, some graphic card update has "taken effect", and now leelaz can't make use of the gpu.

When I run the nvidia-smi command while autogtp is running I get this line:

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |

**Comment by emdio** [comment]
The CPU usage just looks alright, with leelaz using one core:

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                     
 2055 milio     20   0 20,764g  57864  32432 R 100,0  1,0   0:10.04 leelaz

**Comment by gcp** [comment]
If you run leelaz from the command line it will tell you what OpenCL device it's detecting and using.

**Comment by emdio** [comment]
Ok, running leelaz from the command line I get:

$ ./leelaz -w ../weights.txt --noponder
Using 2 thread(s).
RNG seed: 10022107463526541319
Leela Zero  Copyright (C) 2017  Gian-Carlo Pascutto
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

Initializing OpenCL
Detected 1 OpenCL platforms
Platform version: OpenCL 1.2 CUDA 9.0.194
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce GT 540M
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 384.90
Device speed:  1344 MHz
Device cores:  2 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GT 540M
with OpenCL 1.2 capability
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64

**Comment by gcp** [comment]
That looks OK though.

**Comment by emdio** [comment]
If I check the GPU temperature after launching autogtp, it quickly goes from 56C to 64C and raising, so it seems the graphic card is properly being used.

**Comment by emdio** [comment]
As a side note; I've tried different proprietary drivers (I'm running xubuntu 17.10) but I get the same (lousy) performance.

**Comment by emdio** [comment]
And after an overnight... it solved by itself.
I just woke up my laptop (it was suspended), made a new attempt to launch autogtp, and now it's playing at a normal pace (some 10 seconds per move).

Hmmm, now GPU temperature is 84C, some 20C more than yesterday. So, maybe yesterday (for whatever reason) the GPU wasn't being used at its 100%? Probably I should find a way to monitor GPU usage on my laptop.

The nvidia-smi command still says:

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+


Ok, so I guess I'll just close this issue.

**Comment by emdio** [comment]
Ok, this is a behavior I've found in at least two computers with linux. I start the computer, launch autogtp, and it takes forever (above 2 minutes) to make one move. 
Now I suspend the computer, I "wake it up", launch autogtp again and now it works normally (10-15 seconds per move).
