### ISSUE TITLE
leela-zero-0.1-win32.zip can not run on win x64

### ISSUE THREAD

**Issue by aTan-aka-Xellos** [gcp/leela-zero#3]
Hello! 
Thank you for compiled version!
Could you please add x64 version too?
When I try to run x32 version on Win10 x64 I have next errors:

![689 26-oct-17 01 27](https://user-images.githubusercontent.com/7886823/32026442-1e5fa74a-b9ed-11e7-80b5-65d65329911d.jpg)
![688 26-oct-17 01 27](https://user-images.githubusercontent.com/7886823/32026444-1e7f0914-b9ed-11e7-87c9-678800f812ee.jpg)

Upd: googled this, not sure if related:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/06b66cae-d010-441d-bc72-64a8c7cd65bc/missing-vcruntime140ddll-and-ucrtbaseddll?forum=visualstudiogeneral

**Comment by gcp** [comment]
It has nothing to do with 32-bit vs 64-bit, there was a configuration error in the bundled OpenCL.dll. I believe this is now fixed, and I've updated the package on the release page. Please confirm whether it works for you.

There is no benefit to providing a 64-bit version as almost all computation is done on the GPU.

**Comment by aTan-aka-Xellos** [comment]
Now it's working! Thanks
Closing issue.
