### ISSUE TITLE
leelaz (next) segmentation fault

### ISSUE THREAD

**Issue by ashinpan** [gcp/leela-zero#308]
I built leelaz and autogtp (both next) on Linux Mint (18.3). When I run autogtp with leelaz, it produces the following output:

AutoGTP v9
Using 1 thread(s).
curl -s -J http://zero-test.sjeng.org/get-task/7

 -p 1600  -r 1  -m 30  -t 1  -d   -n   --noponder 
Segmentation fault

**Comment by odeint** [comment]
That is this issue [https://github.com/gcp/leela-zero/issues/249#issuecomment-350359462](https://github.com/gcp/leela-zero/issues/249#issuecomment-350359462) , which I believe is actually in autogtp, not leelaz.
