### ISSUE TITLE
Bug in scoring?

### ISSUE THREAD

**Issue by Neverever** [gcp/leela-zero#309]
Please take a look at this game B+3.5
http://zero.sjeng.org/view/302f5b282c82437e5e6fff97b40b82a24cc7022fbcd54d91357fa4acee0bf324

However, if you scroll to the end, white basically has no two eyes, all of it's groups were dead.
B should win more than 3.5

Could you take a look at the scoring system?

**Comment by zediir** [comment]
leelaz uses Tromp-Taylor scoring https://senseis.xmp.net/?TrompTaylorRules. "A player's score is the number of points of her color, plus the number of empty points that reach only her color." It does not take into account dead groups.

**Comment by sethtroisi** [comment]
https://github.com/gcp/leela-zero/issues/288

https://github.com/gcp/leela-zero/issues/264

TL;DR It uses Tromp-Taylor scoring rules https://senseis.xmp.net/?TrompTaylorRules

**Comment by Neverever** [comment]
Thanks, it looks like to be a common question.
Maybe worthwhile putting it in README section?
