### ISSUE TITLE
suggest to let leelaz play with other software

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#310]
for examle, from here(http://www.yss-aya.com/cgos/19x19/standings.html),
choose Opponent has similar Rate, to verify the leelaz rate.
the name can include the with first letters of hash value of weight file,for example:
leelaz-0.9w2184-1c1g

**Comment by killerducky** [comment]
WhiteHalmos is already doing this, here you go:

http://www.yss-aya.com/cgos/19x19/cross/LZ-2184b7-t1-p1600.html

https://www.reddit.com/r/cbaduk/comments/7ikllf/leela_zero_on_cgos/

**Comment by l1t1** [comment]
thanks
