### ISSUE TITLE
is it a bug that 0.9 version's winner resign 

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#312]
https://tieba.baidu.com/p/5471669195
<pre>
(;FF[4]GM[1]

AP[LeelaWatcher 1.0]

GN[Leela vs. Leela]
EV[Leela Zero Self Training]
RE[?]
DT[2017-12-09T03:58:32.783Z] PC[Location Unknown]
GC[]

PW[Leela] WR[?]
PB[Leela] BR[?]

HA[0] KM[7.5] SZ[19]
RU[Japanese]

;B[hn];W[qj];B[cm];W[rl];B[ec];W[fj];B[sp];W[qk];B[qa];W[fo];B[qb];W[qh];B[nb];W[qe];B[bf];W[dd];B[qi];W[eq];B[ej];W[ro];B[ai];W[ac];B[ql];W[rd];B[on];W[lc];B[pi];W[gd];B[cg];W[ld];B[ns];W[hf];B[km];W[hg];B[of];W[bp];B[nc];W[fl];B[dm];W[eh];B[hr];W[dp];B[ed];W[gj];B[ad];W[gl];B[re];W[fd];B[dk];W[dc];B[cd];W[fa];B[kb];W[pp];B[gm];W[mf];B[bm];W[oh];B[ri];W[ds];B[ci];W[kd];B[de];W[ne];B[be];W[ph];B[or];W[rp];B[ip];W[di];B[pj];W[sn];B[oq];W[pk];B[op];W[mg];B[in];W[pd];B[ef];W[qc];B[pm];W[ih];B[eb];W[il];B[cn];W[ok];B[np];W[po];B[lb];W[rr];B[mp];W[ma];B[mb];W[pr];B[pb];W[fm];B[pq];W[dj];B[bo];W[cj];B[gr];W[bj];B[od];W[cp];B[oe];W[cc];B[kn];W[rf];B[ee];W[iq];B[ir];W[gn];B[ib];W[rj];B[bi];W[ek];B[rc];W[qf];B[hc];W[qd];B[fq];W[hp];B[hq];W[hd];B[jq];W[nl];B[ic];W[oo];B[id];W[gc];B[an];W[gp];B[je];W[rq];B[bc];W[jo];B[fg];W[fr];B[fe];W[gq];B[no];W[kq];B[aj];W[ko];B[jn];W[nm];B[ho];W[ke];B[dl];W[jf];B[he];W[ge];B[ie];W[fp];B[kr];W[nn];B[fh];W[lr];B[lq];W[ei];B[kp];W[ch];B[gf];W[hm];B[if];W[bh];B[kf];W[ig];B[jg];W[lf];B[kh];W[bl];B[jh];W[bk];B[li];W[nh];B[gh];W[ii];B[lk];W[dh];B[ji];W[mi];B[mj];W[al];B[bg];W[ca];B[nj];W[ij];B[bb];W[lh];B[nd];W[ll];B[lj];W[qq];B[jf];W[ml];B[oj];W[lo];B[kl];W[io];B[jp];W[sc];B[jb];W[mn];B[rh];W[rb];B[lp];W[ap];B[md];W[ln];B[ra];W[qg];B[ah];W[kk];B[im];W[jk];B[jl];W[lm];B[lg];W[go];B[mh];W[jm];B[ni];W[ng];B[hh];W[sj];B[co];W[eo];B[me];W[ps];B[eg];W[si];B[fb];W[sg];B[fs];W[hi];B[dg];W[es];B[sh];W[gs];B[oi];W[cl];B[js];W[kj];B[lh];W[ao];B[sb];W[am];B[rc];W[sd];B[gg];W[fi];B[ea];W[rg];B[le];W[ag];B[hs];W[ak];B[pc];W[se];B[fs];W[sl];B[ah];W[bn];B[rb];W[hk];B[nk];W[ol];B[an];W[qr];B[af];W[qo];B[cs];W[bi];B[er];W[dr];B[os];W[cf];B[ag];W[in];B[og];W[qm];B[ai];W[dn];B[so];W[pf];B[nf];W[bn];B[ob];W[ls];B[an];W[br];B[pg];W[dq];B[do];W[pn];B[df];W[gs];B[ks];W[ha];B[qs];W[sr];B[en];W[pl];B[ga];W[em];B[mq];W[ss];B[gk];W[ia];B[fs];W[jl];B[rn];W[ep];B[ho];W[gi];B[ck];W[jj];B[kq];W[mk];B[ab];W[as];B[cb];W[sq];B[kc];W[jc];B[fn];W[bn];B[fa];W[jd];B[an];W[hn];B[jn];W[so];B[ka];W[gm];B[db];W[aj];B[kg];W[oa];B[sm];W[mr];B[mc];W[im];B[pe];W[bn];B[ki];W[ms];B[nq];W[om];B[km];W[jc];B[an];W[ql];B[cq];W[la];B[aq];W[pm];B[ld];W[ke];B[kl];W[dd];B[na];W[bq];B[pa];W[rm];B[cr];W[ma];B[ba];W[fc];B[bd];W[ik];B[sk];W[dn];B[gb];W[fk];B[aa];W[fc];B[el];W[bn];B[cc];W[bm];B[ ])

</pre>

**Comment by billyswong** [comment]
That guy mistook W+Resign as "white resign the game". Nothing to see here. People in the post have explained his issue.

**Comment by l1t1** [comment]
thanks
