### ISSUE TITLE
Training a new network 

### ISSUE THREAD

**Issue by thynson** [gcp/leela-zero#317]
Since there was a bug cause white weak  than black, recent networks believe winning probability of black is large than 80% at the openning of a game. Since the bug has been fixed for a while, have self plays been collected enough to train a new network, that generated from the latest version of leela-zero?

**Comment by SharlatanY** [comment]
There haven't been enough games from the newest LZ version to train a network solely from those but new networks are trained constantly and released if they prove to be at least 35 Elo stronger than the previous best.

**Comment by evanroberts85** [comment]
I guess the latest networks tested were not successful, which is a shame but it is still early days aftr the latest bugfixes. @gcp are you still testing using a 300k window and using 10k steps? How many failures have we had since 2184b7?

**Comment by BHydden** [comment]
2184b7 was the last network trained according to the graph. They aren't quick to train please be patient I expect we will see the results of the next trained network soon (whether it's an improvement or not)

**Comment by evanroberts85** [comment]
Training is pretty quick, testing can take quite a while. GCP was doing 2 or more tests a day and it has been two days since the 2184b7 release. On the other hand the last 4 “best” networks came an average of 4 days or so after the previous, so it would not be a surpise if we have to wait a few more days.

**Comment by ashinpan** [comment]
In my autogtp and leela zero webpage, a new networks has arrived. It is "eebb910dc02d50437b8fe78c43e4f77b3428b092e9477163aa16403238cea918"

**Comment by BHydden** [comment]
You're quick on the ball! Only 60 games played on it so far! It must be the new strongest network :-)

**Comment by kityanhem** [comment]
How many games is that new network trained?

**Comment by ashinpan** [comment]
@kityanhem The graph is not yet updated.

**Comment by evanroberts85** [comment]
Looking at the self play games, this new network look a good 2-3 stones
stronger, it now regularly protects cuts and captures and seems to have a
basic idea now of liberties.

**Comment by Marcin1960** [comment]
OK, LeelaZeroT now is playing against WeekBot50k[22k] on KGS with the newest network.

**Comment by thynson** [comment]
eebb910 is good! Still this network believe Black has 80% at the begining, it drops to around 50% quickly after several moves.
