### ISSUE TITLE
why one network file was skipped?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#318]
at http://zero.sjeng.org/
<pre>
Network Hash (100 Most Recent)

Games

eebb910dc02d50437b8fe78c43e4f77b3428b092e9477163aa16403238cea918 1339 
2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c 68921 
</pre>
but at http://zero.sjeng.org/networks/

<pre>
~ / networks / 
NameSizeModified

best-network77480102017-12-9 12:53:49

best-network.gz28030772017-12-9 12:53:49

eebb910dc02d50437b8fe78c43e4f77b3428b092e9477163aa16403238cea918.gz28030772017-12-9 08:22:38

edf2254aff9ea2cc877fd307310424fa9a734a5202987a5a6a8ecd57bd7570a0.gz28026502017-12-8 15:18:46

2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c.gz28034292017-12-7 13:07:53

</pre>

why edf2254aff9ea2cc877fd307310424fa9a734a5202987a5a6a8ecd57bd7570a0 was skipped?

**Comment by WhiteHalmos** [comment]
/networks is now the place where all testing networks are also stored. Thus we should no longer expect that it contains all the best networks. The homepage is where you should find the best networks.

**Comment by BHydden** [comment]
Only the new "best" networks get distributed so I'm guessing edf225 was not a significant improvement 2184b

**Comment by l1t1** [comment]
thanks

**Comment by roy7** [comment]
Yeah I removed the link to /networks/ off the main page to help reduce confusion. I might remove the directory listing from networks/ completely. We'll see.
