### ISSUE TITLE
How to use more threads(cores) and/or more gpu?

### ISSUE THREAD

**Issue by TasmaniaKrama** [gcp/leela-zero#320]
I have i5 with 4 cores and r9 380 series GPU. I am using this command with sabaki
-g --noponder -p 10000 -w eebb910dc02d50437b8fe78c43e4f77b3428b092e9477163aa16403238cea918
However I think it is only using 1 core and maybe 40% of gpu. Which commands should I change or add to increase core and gpu usage?

**Comment by kris-computer-go** [comment]
try leelaz --help

**Comment by TasmaniaKrama** [comment]
Thank you!
