### ISSUE TITLE
Compiler warnings from cl2.hpp

### ISSUE THREAD

**Issue by roy7** [gcp/leela-zero#326]
I saw someone in another issue cleaned up some compiler warnings. C++ is out of my skillset atm, so I'm just going to share these if someone else want to take a look. This is on Manjaro (Arch) Linux.

> g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o UCTNode.o UCTNode.cpp
> In file included from OpenCL.h:27:0,
>                  from UCTNode.cpp:42:
> ./CL/cl2.hpp:1831:5: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
>      const cl_type get() const { return object_; }
>      ^~~~~
> In file included from OpenCL.h:27:0,
>                  from UCTNode.cpp:42:
> ./CL/cl2.hpp:5857:63: warning: ignoring attributes on template argument âcl_int {aka int}â [-Wignored-attributes]
>      typename std::enable_if<!std::is_pointer<T>::value, cl_int>::type
>                                                                ^
> ./CL/cl2.hpp:6157:22: warning: ignoring attributes on template argument âcl_int {aka int}â [-Wignored-attributes]
>          vector<cl_int>* binaryStatus = NULL,
>                       ^
>

**Comment by ljn917** [comment]
pr #269

**Comment by roy7** [comment]
Haha. I'm dumb. Thanks @ljn917.
