### ISSUE TITLE
reuse MC tree

### ISSUE THREAD

**Issue by Liuweiming** [gcp/leela-zero#328]
I found that the program recreate [UCTSearch](https://github.com/gcp/leela-zero/blob/1894e17d8165b8f88b03f704155400091c07db7b/src/UCTSearch.h#L53): `auto search = std::make_unique<UCTSearch>(game);` before calling `think` and `ponder`, and that will rebuild a new MC tree. I think we should reuse the old MC tree in the last step, is that right?

**Comment by isty2e** [comment]
There is a relevant PR [#315](https://github.com/gcp/leela-zero/pull/315) here. I hope this would be implemented in a few days.

**Comment by gcp** [comment]
This likely won't be merged for quite a bit. Note that we already store all positions in a transposition table so the information *is* already reused.

**Comment by gcp** [comment]
PR #632 looks promising.

**Comment by Mardak** [comment]
This was fixed with #632
