### ISSUE TITLE
Testing old networks with newer Leela Zero

### ISSUE THREAD

**Issue by roy7** [gcp/leela-zero#337]
I decided to post this question as a new issue instead of piling on our other big "chat room" issues. :)

Should I add match requests for all the prior networks in the best networks list so we can update the actual results between those networks, given the older Leela Zero had some bugs when playing as white? That could also give us some match data in the matches database for a future ELO graph, if we do that.

**Comment by zediir** [comment]
If we wait until the next release it would take around 4 hours to calculate it with the current games/hour

**Comment by barrtgt** [comment]
if we have autogtp set to save the sgf files, does it save the test games as well?

**Comment by marcocalignano** [comment]
@barrtgt it should yes

**Comment by isty2e** [comment]
I don't think rating recalculation is necessary. Even with 400 games between two networks, the estimated Elo rating difference will be inaccurate anyways. For example, the recent match between 1607dbea and 163f2cef ended up with 245:168, which leads to the rating difference of 66. However, in a 90% confidence interval, the actual winrate is estimated to be in 55.2% and 63.2%, where corresponding rating differences are 36 and 94, respectively. When this kind of errors are accumulated the rating should be very inaccurate. Moreover, due to self-play bias, ratings should be calibrated later using anchors.

**Comment by roy7** [comment]
It isn't that I'm concerned about the exact ratings, it's more that if we get the data into the database we could automate the ELO graphing although all older networks gcp tested before that aren't uploaded to server would be missing.

**Comment by isty2e** [comment]
Hm, how about filling the DB tentatively based on previous match scores?

**Comment by roy7** [comment]
Now that you mention it, I could just hard code the old data for networks that were never uploaded via the current spreadsheet into the graph and auto generate everything else. Viewers wouldn't know the difference. :)

**Comment by isty2e** [comment]
Oh, I thought you were interested more in automation, and that's why I suggested that. Not sure if it's worth it though, maybe we can let @gcp decide.

**Comment by roy7** [comment]
Yes I want it all automated, but to get info on the graphs I'd need to add the networks to the networks database and the match data to the matches database. And many of the failed networks weren't uploaded to server or put into the networks database, so I don't know their hashes.

**Comment by isty2e** [comment]
That would be another reason for waiting for @gcp :)

**Comment by evanroberts85** [comment]
I think this would be worth doing, but only for the “best” networks. I notice @gcp has been a bit selective in which failed networks he has added to the graph recently anyway.

**Comment by WhiteHalmos** [comment]
+1 for automating for future reference and just filling in past results. They aren't accurate anyways but make for a nice graph. :)

**Comment by lwins-lights** [comment]
@isty2e Based on some assumption, Chernoff bound is telling us the actual error is not *so* bad, although it is indeed not so accurate.

**Comment by gcp** [comment]
> I notice @gcp has been a bit selective in which failed networks he has added to the graph recently anyway.

My problem is that I can't get Google Sheets to draw a scatter graph decently, and if I test multiple networks trained from the same database, I have no good way of plotting the result. Combine this with it now being much more possible to test multiple networks per "data dump...".

I'm not sure what's being asked of me here? All the networks are on the server so they could be used for a match? The failed networks won't do anything to the Elo graph.

**Comment by roy7** [comment]
@gcp I think we're talking about older failed networks that are on the graph (as drops from prior best network) but the network isn't uploaded to server in the networks database or networks/ folder. So we can't use automated match testing on them or automatically plot their data on a new automated chart.

As least something along those lines.

amCharts has a Scatter Chart if this is what you're looking for? https://www.amcharts.com/demos/scatter-chart/

**Comment by roy7** [comment]
Someone also suggested https://vega.github.io/vega-lite/ and sent me some sample code worked up to replace the current chart which I haven't played with yet. Vega is a new library/app to me.

**Comment by roy7** [comment]
Here's a demo of the Vega approach perhaps. 

https://vega.github.io/editor/#/examples/vega-lite/circle

**Comment by roy7** [comment]
I'm going to go ahead and remove all bad resigned game data from the match databases.

**Comment by roy7** [comment]
Because it's equally likely to hurt either side, it probably won't actually change anything. But still on principle... ;)

**Comment by gcp** [comment]
The old networks are now all on the graph.
