### ISSUE TITLE
Allow resigning in games with under 500 playouts?

### ISSUE THREAD

**Issue by roy7** [gcp/leela-zero#340]
https://github.com/gcp/leela-zero/blob/1894e17d8165b8f88b03f704155400091c07db7b/src/UCTSearch.cpp#L260

So accidentally learned that there's a minimum 500 playouts or else LZ can never resign because of the 500 visit minimum. Should this test be changed to the minimum of the playout cap or 500? So that if you are using -p 100, resignations are still possible. If someone wants no resignations even in a low playout game they could use -r 0.

**Comment by gcp** [comment]
I believe that condition dates back to having time control logic that plays obvious moves quicker.

Some guy spent a lot of time asking me to work on that, and the above is a safeguard so we don't reply after a very shallow search.

**Comment by roy7** [comment]
I resemble that guy. ;)

Still though, the 500 should be the floor of 500 or visit cap or playout cap as appropriate.

**Comment by sethtroisi** [comment]
Should it be 
min(500, cfg_max_playouts) or min(500, cfg_max_playouts / 2)

**Comment by roy7** [comment]
Thanks for addressing this in your own work @sethtroisi. I know it's minor and only people like me who abuse software in weird ways experience these sorts of bugs. ;) I'll close since you have a fix pending elsewhere.

**Comment by killerducky** [comment]
I vote cfg_max_playouts/2, and also cfg_maxvisits/2.

**Comment by gcp** [comment]
What's the reasoning of the /2? The count is done on the root node, not on the best move.

**Comment by killerducky** [comment]
I was anticipating the addition of time control heuristics, such as the PV cannot be overtaken by the 2nd best move. It might also happen in the current code if the time control starts forcing you to move before playouts/visits is reached.
