### ISSUE TITLE
Random seed coming back from autogtp not matching what was sent out

### ISSUE THREAD

**Issue by roy7** [gcp/leela-zero#341]
@marcocalignano I'm seeing negative numbers in the seeds I'm logging from matches. I'm now printing everything to my log, and I never send large negative numbers out.

For instance I see one client I sent 4596912049025179213 as the seed, but they sent me back  -303553439206216476. Smaller seeds like 1161586104763488976 work. I'm guessing it's an overflow issue? I'm sending 64 bit unsigned integers (as a string). Can you be sure you're storing them in a 64 bit unsigned integer if you are doing something with them before sending them back to me?

**Comment by roy7** [comment]
Ah ha, the problem is on my end not yours! I'm working on it...

**Comment by roy7** [comment]
@zediir I'm getting negative numbers (overflow?) from

> Long.fromString(req.body.random_seed, 10)

Smaller numbers fine, bigger ones end up negative when I convert from the string to the Long. I'm making the numbers successfully with:

> var random_seed = converter.hexToDec( "0x"+crypto.randomBytes(8).toString('hex') ).toString();

I'm guessing mongodb Longs are signed. So should I just drop off 1 bit or something?

**Comment by zediir** [comment]
can you get a hexstring out of what is stored in the database? If you can you could just let it save it as a signed integer in the database and then convert it to unsigned when you need it.

**Comment by zediir** [comment]
I got it. 

```
(new Uint32Array([monbodblong.getHighBits()]))[0].toString(16)+(new Uint32Array([monbodblong.getLowBits()]))[0].toString(16)
```
could that work

**Comment by roy7** [comment]
I"ll test after dinner, thanks. I didn't think about trying to convert the Long from mongodb back into hex. I'll experiment. As long as I can get back to the string I originally sent out, should be fine.

**Comment by roy7** [comment]
Your'e a hero again @zediir. This got me there:

> got raw seed: 18217425505450544944
> got seed: -229318568259006672
> fix seed: 18217425505450544944

> console.log("fix seed: " + converter.hexToDec( "0x" + (new Uint32Array([req.body.random_seed.getHighBits()]))[0].toString(16)+(new Uint32Array([req.body.random_seed.getLowBits()]))[0].toString(16) ).toString() );

**Comment by roy7** [comment]
Argh, nope.

got raw seed: 883863265504794200
got seed: 883863265504794200
fix seed: 55241454132270680

Sometimes it's still failing to reverse, but oddly enough, it's not on the negative ones. Sometimes I hate computers. :)

**Comment by roy7** [comment]
Hmm not just "small numbers". Since this tested fine:

> console.log("Small int test 777: " + seed_from_mongolong(Long.fromString("777", 10)));
> Small int test 777: 777

**Comment by roy7** [comment]
Maybe I need to stop being stubborn about storing the random seed as Long in the database, and just store it as a string?

**Comment by zediir** [comment]
I got it. You need to pad the lower 32 bits if they are under 28 bits.

```
var converter = require('hex2dec');
var mongodb = require('mongodb');

var Long = mongodb.Long;

var origInt = "883863265504794200";

var mongodblong = Long.fromString(origInt, 10);

var intstring = converter.hexToDec( "0x" + (new Uint32Array([mongodblong.getHighBits()]))[0].toString(16)+mongodblong.getLowBitsUnsigned().toString(16).padStart(8,"0"));

console.log(intstring);
```

**Comment by roy7** [comment]
Works great. Thank you! I'm just not a low level programmer. :)

> Broken int test 883863265504794200: 883863265504794200
