### ISSUE TITLE
GTP command "play white resign" generate a wrong SGF

### ISSUE THREAD

**Issue by marcocalignano** [gcp/leela-zero#343]
In validation mode two process play against each other and if white resign the black process receive the command "play white resign" this move should not appear in the SGF game log but the resutl in the SGF should be B+Resign. 
but fro this code 
in GTP.cpp here https://github.com/gcp/leela-zero/blob/1894e17d8165b8f88b03f704155400091c07db7b/src/GTP.cpp#L294-L296

with that command in the sgf is written a pass move and the game is not terminated so if a "final_score" command is given does not come out B+Resignation  but the point are counted.

**Comment by marcocalignano** [comment]
This would screw up the training of new networks if we use wrong sgf files?

**Comment by marcocalignano** [comment]
For example I did the following.
- open Leelaz and let her play the first black move 
- played a white move
- let her play another black move 
- have white resign
- asked final_score and White won for 6.5 points
Here is the SGF 

```
(;GM[1]FF[4]RU[Chinese]DT[2017-12-13]SZ[19]KM[7.5]PB[Leela Zero 0.9 ../autog]PW[Human]RE[W+6.5]

;B[qe];W[qf];B[fq];W[tt])


```

**Comment by kimitsu** [comment]
> This would screw up the training of new networks if we use wrong sgf files?
@marcocalignano this bug does not seem to happen in self-plays, so training data should not be affected.

**Comment by roy7** [comment]
The example SGF file shows white the winner by 6.5 points. Please don't tell me resignations on matches are still being submitted with wrong winners. If white resigned after B[fq], there should be no W[tt] and score should be RE[B+Resign].

**Comment by zediir** [comment]
The resignation should be submitted correctly in everywhere else but the sgf if I understood correctly.

**Comment by roy7** [comment]
Well looking in match_games, the most recent B+Resign "score" with RE[B+50.5] and game ending with a single W[tt] in the SGF, was:

> (;GM[1]FF[4]RU[Chinese]DT[2017-12-13]SZ[19]KM[7.5]PB[Leela Zero 0.9 5bcb392e]PW[Human]RE[B+50.5]\n\n;B[cc];W[br];B[dp];W[rr];B[pp];W[ec];B[ck];W[df];B[ci];W[jg]\n;B[ic];W[nb];B[ch];W[rn];B[pd];W[jm];B[em];W[fr];B[im];W[np]\n;B[gb];W[qg];B[kq];W[rf];B[iq];W[kc];B[qi];W[dc];B[bg];W[bn]\n;B[ib];W[qk];B[on];W[lp];B[hq];W[nr];B[mb];W[rl];B[nc];W[mc]\n;B[lc];W[md];B[oc];W[nd];B[lb];W[od];B[pc];W[pe];B[ob];W[fp]\n;B[ld];W[kj];B[fh];W[lm];B[le];W[nk];B[he];W[hg];B[hm];W[fn]\n;B[fm];W[en];B[dn];W[dm];B[do];W[dl];B[cm];W[cn];B[cl];W[db]\n;B[dk];W[el];B[dr];W[ek];B[gn];W[gm];B[gl];W[go];B[ho];W[ej]\n;B[cf];W[hp];B[ip];W[gp];B[fo];W[eo];B[ep];W[fo];B[fq];W[bp]\n;B[gq];W[fe];B[ng];W[ce];B[oh];W[dg];B[bo];W[mf];B[dh];W[lf]\n;B[co];W[oe];B[rq];W[kf];B[qq];W[fi];B[eh];W[gh];B[qn];W[me]\n;B[rm];W[qm];B[pm];W[sm];B[ro];W[qo];B[no];W[pn];B[po];W[qn]\n;B[mo];W[bf];B[mp];W[lo];B[lq];W[mq];B[cg];W[lr];B[qr];W[fg]\n;B[oo];W[om];B[be];W[cd];B[nm];W[nl];B[ol];W[ok];B[bd];W[rb]\n;B[qb];W[pl];B[rc];W[bc];B[kr];W[ln];B[mr];W[nq];B[ls];W[ao]\n;B[bm];W[an];B[am];W[gi];B[ap];W[om];B[qe];W[qf];B[pf];W[re]\n;B[qd];W[rd];B[sc];W[pr];B[pg];W[qs];B[qh];W[of];B[qp];W[mn]\n;B[rs];W[ss];B[rg];W[rh];B[ri];W[sg];B[si];W[ni];B[kb];W[ps]\n;B[ns];W[or];B[sq];W[so];B[ph];W[nh];B[og];W[nf];B[mg];W[lg]\n;B[mh];W[lh];B[mi];W[li];B[mj];W[nj];B[sh];W[rg];B[sd];W[kp]\n;B[se];W[jq];B[sf];W[jr];B[jp];W[js];B[ir];W[jo];B[is];W[rp]\n;B[ks];W[rs];B[cb];W[bb];B[ca];W[af];B[ba];W[ae];B[il];W[ad]\n;B[jl];W[kl];B[nn];W[fb];B[jn];W[ml];B[km];W[ll];B[gc];W[fc]\n;B[ms];W[op];B[pq];W[cj];B[dj];W[ei];B[di];W[eg];B[os];W[io]\n;B[sr];W[ag];B[oq];W[ah];B[ko];W[kn];B[jm];W[ko];B[kk];W[jk]\n;B[ik];W[lk];B[jj];W[ij];B[kk];W[ji];B[jk];W[tt])

The most recent score "W+Resign" is with white winning and RE[W+Resign] and end of match W[ao] (so looks like black resign since black didn't make a move). 

> (;GM[1]FF[4]RU[Chinese]DT[2017-12-13]SZ[19]KM[7.5]PB[Leela Zero 0.9 d5b7aec3]PW[Human]RE[W+Resign]\n\n;B[ic];W[bb];B[ib];W[db];B[eb];W[eq];B[lm];W[oq];B[kb];W[pn]\n;B[lc];W[ro];B[ci];W[co];B[mr];W[rf];B[he];W[or];B[pg];W[pf]\n;B[od];W[qf];B[md];W[cp];B[ml];W[rd];B[qk];W[kq];B[fl];W[jr]\n;B[gd];W[bd];B[kj];W[rb];B[ng];W[rk];B[gh];W[rj];B[df];W[ck]\n;B[mh];W[qj];B[bi];W[cn];B[fc];W[cf];B[ej];W[br];B[dc];W[cc]\n;B[fi];W[pb];B[no];W[gr];B[mp];W[dd];B[lo];W[pp];B[ho];W[ec]\n;B[oj];W[fb];B[gn];W[lr];B[jo];W[mq];B[gb];W[dl];B[nq];W[lq]\n;B[fo];W[nr];B[pk];W[rl];B[di];W[gq];B[of];W[qg];B[hg];W[rh]\n;B[ed];W[ea];B[on];W[ee];B[de];W[fd];B[fe];W[gc];B[ef];W[ce]\n;B[ed];W[fc];B[pm];W[rr];B[qn];W[rn];B[rm];W[qo];B[qm];W[po]\n;B[hk];W[sm];B[ob];W[pc];B[hc];W[bl];B[jg];W[oc];B[nc];W[pd]\n;B[nb];W[ph];B[pe];W[og];B[oe];W[qe];B[oh];W[oi];B[pg];W[ni]\n;B[pi];W[og];B[nh];W[pj];B[pg];W[qi];B[nm];W[og];B[ql];W[nj]\n;B[pg];W[ok];B[mj];W[mi];B[li];W[lh];B[kh];W[og];B[lg];W[mk]\n;B[lk];W[nk];B[nl];W[lj];B[ol];W[cg];B[mj];W[np];B[sl];W[lj]\n;B[sn];W[so];B[sm];W[hp];B[fm];W[io];B[ip];W[jp];B[in];W[iq]\n;B[io];W[bh];B[ch];W[dg];B[bg];W[bf];B[eg];W[ag];B[ai];W[dh]\n;B[cj];W[eh];B[bk];W[ei];B[dk];W[cl];B[el];W[fh];B[fg];W[gi]\n;B[fj];W[ee];B[mj];W[ak];B[bj];W[al];B[dj];W[lj];B[ed];W[kk]\n;B[ll];W[ee];B[mj];W[ff];B[gf];W[lj];B[ed];W[ki];B[mj];W[ee]\n;B[lj];W[oo];B[ed];W[pa];B[ah];W[ee];B[gj];W[bg];B[hi];W[lp]\n;B[mo];W[ko];B[kn];W[bq];B[kp];W[fp];B[gp];W[go];B[sk];W[gp]\n;B[sj];W[ko];B[eo];W[kp];B[ed];W[dm];B[ep];W[ee];B[ga];W[ed]\n;B[dq];W[dp];B[er];W[fq];B[dr];W[fr];B[bs];W[cq];B[en];W[cr]\n;B[pg];W[cs];B[rq];W[og];B[qr];W[qq];B[sr];W[rp];B[rs];W[pr]\n;B[pg];W[qs];B[ps];W[og];B[hb];W[sq];B[sp];W[os];B[sq];W[qs]\n;B[aj];W[rr];B[pg];W[ss];B[si];W[og];B[sh];W[ri];B[pg];W[em]\n;B[og];W[is];B[fa];W[oa];B[sg];W[na];B[sf];W[rg];B[rc];W[sc]\n;B[an];W[se];B[hm];W[hr];B[qd];W[qc];B[ap];W[bp];B[ma];W[es]\n;B[om];W[ds];B[da];W[eb];B[fn];W[ca];B[jb];W[dn];B[dq];W[dr]\n;B[af];W[ae];B[cm];W[nn];B[mn];W[bm];B[jk];W[dq];B[kl];W[jn]\n;B[ls];W[jm];B[km];W[im];B[sr];W[hn];B[ms];W[gm];B[gl];W[sq]\n;B[in];W[io];B[ji];W[mb];B[lb];W[la];B[mc];W[ma];B[ka];W[do]\n;B[aq];W[ar];B[ao];W[bo];B[bn];W[am];B[an];W[ao])

**Comment by marcocalignano** [comment]
@roy7 the validation match get the real winner and the right result and submit that to the server as separate variable even if the SGF is wrong. So if you look at the result or winner variable in the DB these are right the SGF no.

**Comment by roy7** [comment]
Ok then no harm done. These match SGFs are not used by training and the results passed in separate fields are what we use for win rates and choosing best networks. If resigns/scores/etc are wrong in Selfplay that'd be a lot more serious.

**Comment by kimitsu** [comment]
Still, it wouldn't hurt to fix this issue. I suggest that rather than black always saving the sgf, make it the last player to make a move (or resign) to save the sgf file?

**Comment by marcocalignano** [comment]
I think it is a Gtp command bug in Leelaz

**Comment by kimitsu** [comment]
@marcocalignano I don't believe "play xxx resign" is even in GTP specification. Unfortunately, the GTP specs page is down, but here are quotes from its cached version:
```
- play
arguments | Color and vertex of the move
effects | A stone of the requested color is played at the requested vertex. The number of captured stones is updated if needed and the move is added to the move history.
output | none
fails | syntax error, illegal move. In the latter case, fails with the error message ``illegal move''.
comments | Consecutive moves of the same color are not considered illegal from the protocol point of view.

- vertex
A vertex is a board coordinate consisting of one letter and one number, as defined in section 2.11, or the string ``pass''. Vertices are not case sensitive. Examples: ``B13'', ``j11''.

```

There's no command I see that can send resignation through GTP, the only part that deals with resignation is this:

```

genmove
arguments | Color for which to generate a move.
effects | A stone of the requested color is played where the engine chooses. The number of captured stones is updated if needed and the move is added to the move history.
output | vertex
  | vertexstring vertex - Vertex where the move was played or the string ``resign''.
fails | never
comments | Notice that ``pass'' is a valid vertex and should be returned if the engine wants to pass. Use ``resign'' if you want to give up the game. The controller is allowed to use this command for either color, regardless who played the last move.

```

**Comment by gcp** [comment]
https://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html

vertex$\vert$string vertex - Vertex where the move was played or the string ``resign''.

Leela stores resignation internally similarly to passing, which is what causes this problem. It has to be extended a bit to handle this correctly. AutoGTP has always checked the actual move played to score the game.

**Comment by marcocalignano** [comment]
Yes Autogtp evaluate the move not the SGF and seems that in selfplaying games since we use generate move resignation is also stored correctly in the SGF. But now the verification from the /next branch transmit to the server the correct winner the correct result but the wrong SGF, and we cannot use them for training

**Comment by kimitsu** [comment]
@gcp I read that line differently... "vertex" is clearly defined as a board coordinate or "pass" earlier in the document. The line in question speaks of the response of genmove, which can be vertex|string, I suppose | means "or". So "vertex" can be coordinate or "pass", and "string" can be "resign". Nothing is said that the controller can (or needs) to send "play (color) resign" to the engine, "play" command is defined earlier and there's no mention of "resign" in the entire document before "genmove".

@marcocalignano Self-plays are unusable for training anyway, they're run with different options (without noise) and don't even generate training data at the moment.

**Comment by marcocalignano** [comment]
@Kimitsu gtp is a protocol that a program (here called P) use to interact with the engine.
Now P receive a move from the user, P has to send it to the engine and ask for an answer. This is true even for a Pass move. If P receive a resign move from the user, P does not need to send it to the engine because P can write the SGF file and it knows the result and the winner. What is different with leelaz is the in out case autogtp know the result and the winner but leelaz write the SGF file so we need a "special"  GTP command to tell leelaz the the user resign so leelaz can write the correct SGF

**Comment by roy7** [comment]
@marcocalignano Here's an idea, since you have an open connection to both Leela processes that are running, what about sending the command to save the sgf to either process, depending on the result of the match? If I'm understanding right that one of them will get it right and the other one won't.

**Comment by marcocalignano** [comment]
And then check which I have to send?

**Comment by marcocalignano** [comment]
@roy7 can you check something for me in the DB?
If Black resign the result in the DB is B+Resign and the SGF is right.
I White resign the result in the DB is W+Resign and the SGF is wrong.

is this true?

**Comment by roy7** [comment]
I'm bogged down at work but newest game with a B+Resign "score" says RE[B+70.5] in sgf. Newest W+Resign says RE[W+Resign]. "winnercolor" is right for both.

**Comment by marcocalignano** [comment]
The problem with saving the SGF from the second process is that there the color are inverted

**Comment by marcocalignano** [comment]
So, since the problem happens only when White resign I decide in that case to fix the sgf like is done with the name.

**Comment by marcocalignano** [comment]
Now I am waiting for a match where White resign to test it ;)

**Comment by marcocalignano** [comment]
@roy7 can you check the SGF of the match file e19c991f528d3152dffa254d5c0bae317a16668a3018b4db2f44f4ce1ee9a528

**Comment by roy7** [comment]
RE[B+Resign]

**Comment by roy7** [comment]
> (;GM[1]FF[4]RU[Chinese]DT[2017-12-14]SZ[19]KM[7.5]PB[Leela Zero 0.9 e671af6f]PW[Leela Zero 251b7ca8]RE[B+Resign] \n\n;B[qd];W[bd];B[bc];W[qo];B[cd];W[pd];B[pe];W[dn];B[pc];W[od]\n;B[oc];W[eq];B[be];W[qc];B[qe];W[in];B[qb];W[rc];B[rb];W[pb]\n;B[ob];W[ic];B[hl];W[ek];B[pr];W[oj];B[hc];W[nd];B[ib];W[oq]\n;B[nc];W[lp];B[pq];W[ji];B[ii];W[je];B[jj];W[hp];B[or];W[nl]\n;B[hb];W[md];B[mc];W[ld];B[lc];W[kc];B[po];W[pn];B[kd];W[ke]\n;B[pp];W[jd];B[qn];W[qm];B[rn];W[rm];B[pm];W[on];B[om];W[nm]\n;B[nn];W[oo];B[no];W[op];B[nq];W[np];B[mp];W[qk];B[lq];W[kj]\n;B[kk];W[ki];B[lj];W[li];B[bl];W[ij];B[jk];W[ik];B[kb];W[il]\n;B[ej];W[fk];B[dk];W[dl];B[cl];W[el];B[ck];W[jb];B[fj];W[bp]\n;B[hj];W[hi];B[ih];W[gj];B[gi];W[hk];B[hh];W[mj];B[jh];W[lb]\n;B[lk];W[mi];B[mm];W[ml];B[ll];W[lm];B[km];W[ln];B[kn];W[lo]\n;B[hj];W[gk];B[kp];W[ko];B[jo];W[jp];B[kq];W[jn];B[mn];W[io]\n;B[bn];W[ka];B[hd];W[ph];B[pa];W[dp];B[hf];W[of];B[rf];W[rh]\n;B[oe];W[ne];B[mb];W[jq];B[nf];W[pf];B[mf];W[kg];B[jr];W[qf]\n;B[re];W[rg];B[kr];W[kh];B[hr];W[ir];B[iq];W[hq];B[is];W[gr]\n;B[ci];W[cr];B[ir];W[mk];B[ma];W[bo];B[ol];W[ok];B[pl];W[ql]\n;B[pk];W[pj];B[pn];W[cn];B[mo];W[jl];B[jo];W[bm];B[ip];W[ho]\n;B[hi];W[fi];B[fh];W[ei];B[dj];W[eh];B[fg];W[eg];B[ff];W[ef]\n;B[ee];W[de];B[dd];W[fe];B[ed];W[ge];B[he];W[gf];B[gg];W[ce]\n;B[df];W[cf];B[bf];W[dg];B[cg];W[ch];B[bg];W[bh];B[bi];W[hg]\n;B[ig];W[sc];B[dh];W[di];B[df];W[kl];B[lm];W[jm];B[dh];W[qj]\n;B[gq];W[fr];B[rd];W[sf];B[sb])

Looks good! Last move was by black.

**Comment by marcocalignano** [comment]
Cool the workaround work I make the pull request

**Comment by marcocalignano** [comment]
so the workaround is in #353
