### ISSUE TITLE
The Web Server may be down, too busy, or experiencing other problems

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#346]
curl.exe -F networkhash=1607dbea9c6f8f8e6137b2b167464d4003e5b43c1ec4d792959c6113ef863186 -F clientversion=8 -F sgf=@0a07
87699e28417598344cb000f3d2cd.sgf.gz -F trainingdata=@0a0787699e28417598344cb000f3d2cd.txt.0.gz http://zero.sjeng.org/sub
mit
<HTML><HEAD>
<TITLE>Network Error</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Network Error (tcp_error)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
A communication error occurred: ""
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may
wish to try again at a later time.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>

**Comment by roy7** [comment]
It's working at the moment and server wasn't restarted, it may have been a temporary network issue somewhere between your system and the server.

**Comment by evanroberts85** [comment]
The number of self play games in the past 24 hours is not always correct. Currently it is showing just over 9,000 when it should be around 24,000

**Comment by gcp** [comment]
I think that's because I'm clearing out old games on the server regularly, and the count looks what's in the DB versus what was actually submitted. That bug was fixed in several places but not everywhere I guess.

**Comment by roy7** [comment]
I don't try to store/monitor # of  games in any way other than what's in the DB that is under 24 and 1 hour old.

**Comment by l1t1** [comment]
another fail mode:


9 (S2) 480 (pass) 481 (pass) Game has ended.
Score: B+59.5
Winner: black
Writing 6304bdf4294b4bc9920cb3c0a477d4c7.sgf
Dumping 6304bdf4294b4bc9920cb3c0a477d4c7.txt
18 game(s) played in 1784 minutes = 5949 seconds/game, 14972 ms/move, last game took 4815 seconds.
curl.exe -F networkhash=fe7a6c2885c22dd0ac75c53d6577db2b9720463916e55e2cf2893edf4d924398 -F clientversion=8 -F sgf=@6304
bdf4294b4bc9920cb3c0a477d4c7.sgf.gz -F trainingdata=@6304bdf4294b4bc9920cb3c0a477d4c7.txt.0.gz http://zero.sjeng.org/sub
mit
<b>Upload failed. Curl Exit code: 52
Continuing...</b>
Best network hash: fe7a6c2885c22dd0ac75c53d6577db2b9720463916e55e2cf2893edf4d924398
Required client version: 8 (OK)
Already downloaded network.
Stopping engine.
./leelaz.exe -r 1 -g -t 1 -q -d -n -m 30 -w a0d3531fc3b7bb91a701e47870838840861ce5587d212fecfb7dbdc81607113f -p 1600 --n
oponder
Engine has started.
Infinite thinking time set.
