### ISSUE TITLE
why only 84 games can conclude that the newer network are better

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#347]
Matches (100 Most Recent) | Wins / Losses | Games
-- | -- | --
96bf20e7 VS 1607dbea | 75 : 9 (89.29%) | 84 / 400

**Comment by gcp** [comment]
Because statistics.

**Comment by l1t1** [comment]
thanks， 124 games show samilar rate

**Comment by syjytg** [comment]
l1t1, can you please tell me where to see the statistics you provided? Thanks.

**Comment by sethtroisi** [comment]
[zero.sjeng.org/](zero.sjeng.org/), the chart updates as games come in and now reads


Matches (100 Most Recent) | Wins / Losses | Games
-- | -- | --
fe7a6c28 VS a0d3531f | 313 : 83 (**79.04%**) | 396 / 400
