### ISSUE TITLE
Evaluation between more networks

### ISSUE THREAD

**Issue by ayssia** [gcp/leela-zero#349]
Let's assume there are three players A, B, C, playing rock-paper-scissors:

A plays 98% rock, 1% paper, 1% scissors.
B plays 98% paper, 1% scissors, 1% rock.
C plays 98% scissors, 1% rock, 1% paper.

If we evaluate with two networks, B should be ~700 elo higher than A, and C is ~700 elo higher than B, A is ~700 elo higher than C.
A -> B -> C -> A seems to be 2100 elo improvement, but actually it didn't improve at all.

Maybe we should evaluate networks with at least 2 previous version to get more precise result.

**Comment by Dorus** [comment]
Anything from the AlphaGoZero paper we missed that this would be needed? Other papres? If anything the AlphaZero paper showed evaluation is not even needed :)

**Comment by evanroberts85** [comment]
Not needed, Go is not rock paper scissors.

**Comment by Armavica** [comment]
> Not needed, Go is not rock paper scissors.

I would be very surprised if three Go players of non-transitive strengths could not be found. Is it obvious to you that this is not the case?

**Comment by marcocalignano** [comment]
> Go is not rock paper scissors.

Rock paper scissors has just three outcomes and from these you decide how wins. Go has (on 19×19 board): ~2.082 × 10^170 (i.e., a 2 followed by 170 zeroes).

**Comment by evanroberts85** [comment]
I can’t think of any clear examples in professional history. Some players seem to do slightly worse than expected against certain other players, but nothing clear and generally it is often put down to phychology rather than certain styles beating others.

**Comment by isty2e** [comment]
This theoretically can happen, but in practice, its necessity is questionable. Here are some reasons:

1. The Elo rating is already inaccurate. We just need to test if this network is better than the previous one, and precise rating calculation is currently not our aim. 
2. Though such nontransitive strength relation can be easily found for human go players, it is less likely to be found for LZ. Simply speaking, a network is trained to replicate the previous network reinforced with MCTS, so there is less difference in playstyle, I would say. Moreover, the MCTS itself stabilizes the whole self-play reinforcement training procedure, so forgetting effect is less likely to occur.
3. LZ is readily tested against other bots on KGS or CGOS. And LZ has beaten more and more bots as the training progresses: IdiotBot, BeginnerBot, WeakBot50k, and recently LibertyBot. Considering this, it is reasonable enough to say that LZ has been improving a lot.
