### ISSUE TITLE
autogtp Build error on Linux 14.04

### ISSUE THREAD

**Issue by michaelfu** [gcp/leela-zero#352]
Folks,

I got the following error when building latest autogtp:

roduction.cpp: In member function ‘virtual void ProductionWorker::run()’:
Production.cpp:57:27: error: no ‘operator++(int)’ declared for postfix ‘++’ [-fpermissive]
             (*m_movesMade)++;
                           ^
Production.cpp: In member function ‘void Production::printTimingInfo(float)’:
Production.cpp:185:21: error: no match for ‘operator==’ (operand types are ‘QAtomicInt’ and ‘int’)
     if (m_movesMade == 0 || m_gamesPlayed == 0) {
                     ^
In file included from /usr/include/qt5/QtCore/qlocale.h:45:0,
                 from /usr/include/qt5/QtCore/qtextstream.h:48,
                 from /usr/include/qt5/QtCore/QTextStream:1,
                 from Production.h:24,
                 from Production.cpp:25:

I followed the instructions to install qt5:

QMake version 3.0
Using Qt version 5.2.1 in /usr/lib/x86_64-linux-gnu

This is blocking me from submitting games as now it requires client to be at version 8.

Can someone please help?

Thanks.

**Comment by marcocalignano** [comment]
Your distribution is to old please update to 16.04 and QAtomicInt is supported since Qt5.3

**Comment by michaelfu** [comment]
Thanks, solved after installing a later version of qt.
