### ISSUE TITLE
When will a new weights.txt be published?

### ISSUE THREAD

**Issue by michaelfu** [gcp/leela-zero#355]
Seems the current best_v1.txt was created on Nov. 03. Considering now the ELO score is close to 3,000, shouldn't we have a stronger weights file?

Thanks.

**Comment by sethtroisi** [comment]
best_v1.txt was trained on human games as proof that the neural network architecture worked.

I don't think there are any plans to update it (or produce best_v2.txt)

zero.sjeng.org/networks contains the list of networks trained using self play games,

**Comment by roy7** [comment]
Correct, there won't be any further human-based weights files as part of the Leela Zero project to my knowledge.

**Comment by earthengine** [comment]
I think it would be good when the zero networks starts to beat the best_v1.txt. From then on the best network should be used to update the old best_v1.txt (and have it versioned).

**Comment by michaelfu** [comment]
Thanks for the clarification. Seems I misunderstood the purpose of best_v1.txt file. 

I still have a question, though. From https://en.wikipedia.org/wiki/Go_ranks_and_ratings the current elo score seems to correspond to pro player level. But the latest network seems still pretty weak comparing to best_v1.txt when I try them on my computer. How to explain it?

Thanks.

**Comment by marcocalignano** [comment]
@michaelfu The ELO value is **relative** to the starting point (complete randomness) so it is not an absolute ELO value. The 0 point in the graph is probably around -3000 ELO in absolute rating.

**Comment by michaelfu** [comment]
oh, thanks for the explanation!
