### ISSUE TITLE
could you publish the winrate to other soft of each network file?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#356]
for example, 
http://www.yss-aya.com/cgos/19x19/cross/LZ-1607db-t1-p1600.html

but omit the self-play games
like

Opponent | Rating | Result | Percent
-- | -- | -- | --
EsArgo1.10a2 | 1798 | 1 / 1 | 100.00
-- | -- | -- | --
nlp171106 | 2207 | 1 / 1 | 100.00
-- | -- | -- | --

**Comment by l1t1** [comment]
i think Gnugo is a good benchmark, as it can be downloaded

**Comment by WhiteHalmos** [comment]
CGOS is not directly related to this project, it's better to discuss this on reddit. See this thread for more information: https://www.reddit.com/r/cbaduk/comments/7ikllf/leela_zero_on_cgos/

**Comment by l1t1** [comment]
thanks

**Comment by l1t1** [comment]
it's better to play with similar soft, such as gnugo
http://www.yss-aya.com/cgos/19x19/cross/LZ-251b7c-t1-p1600.html
