### ISSUE TITLE
leelaz v0.9 for Windows crash when using time_settings

### ISSUE THREAD

**Issue by Nabeshin3D** [gcp/leela-zero#357]
May be related to #230 

Steps to reproduce:

cmd.exe command line:
```
"G:\Leela Zero\leelaz.exe" --gtp --noponder -w "G:\Leela Zero\fe7a6c2885c22dd0ac75c53d6577db2b9720463916e55e2cf2893edf4d924398"
```

Produces the following output:
```
Using 2 thread(s).
RNG seed: 6445319302278963936
Initializing OpenCL
Detected 1 OpenCL platforms
Platform version: OpenCL 1.2 CUDA 9.1.104
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce GTX 980 Ti
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 388.43
Device speed:  1228 MHz
Device cores:  22 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GTX 980 Ti
with OpenCL 1.2 capability
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64
Detecting residual layers...v1...64 channels...5 blocks
Transferring weights to GPU...done
BLAS Core: Nehalem
```

Supply the following commands:
```
version
time_settings 0 120 1
genmove b
```

Produces the following output:
```
version
= 0.9

time_settings 0 120 1
=

genmove b
Thinking at most 119.0 seconds...
NN eval=0.739109
Playouts: 2476, Win: 77.60%, PV: E4 F12 N18 J3
Playouts: 4999, Win: 78.54%, PV: E4 F12 N18 J3
Playouts: 7534, Win: 78.98%, PV: E4 F12 N18 J3
Playouts: 10035, Win: 79.13%, PV: E4 F12 N18 J3
Playouts: 12555, Win: 79.19%, PV: E4 F12 N18 J3
Playouts: 15018, Win: 79.14%, PV: E4 F12 N18 J3
Playouts: 17529, Win: 79.07%, PV: P5 K13 L3
Playouts: 20034, Win: 78.86%, PV: P5 K13 L3
Playouts: 22545, Win: 78.62%, PV: P5 E13 C9 J3
Playouts: 25036, Win: 78.32%, PV: D16 D15 C11 J3
Playouts: 27543, Win: 77.96%, PV: P5 E13 B7 L3
Playouts: 30046, Win: 77.62%, PV: P5 E13 N2 R11
Playouts: 32499, Win: 77.27%, PV: L17 C15 L18
Playouts: 34968, Win: 76.94%, PV: D4 F12 S7 J3 J2
Playouts: 37438, Win: 76.63%, PV: D4 F12 S7 J3 J2
Playouts: 39886, Win: 76.33%, PV: D4 F12 S7 J3 J2
Playouts: 42287, Win: 76.06%, PV: O3 C15 B13 L17 L18
Playouts: 44684, Win: 75.78%, PV: P16 Q8 G18 C11 B11
Playouts: 47066, Win: 75.52%, PV: P16 P13 S7 C11 B11
Playouts: 49410, Win: 75.30%, PV: B5 Q12 N18 C9 B9
Playouts: 51739, Win: 75.07%, PV: E14 Q12 G2 C11 B11 B12
Playouts: 54044, Win: 74.87%, PV: B5 Q12 N18 C9 B9
Playouts: 56329, Win: 74.65%, PV: E4 F12 F3 L17 L18 L3
Playouts: 58592, Win: 74.40%, PV: E4 F12 F3 L17 L18 L3
Playouts: 60775, Win: 74.19%, PV: E4 F12 F3 L17 L18 L3
Playouts: 62939, Win: 73.98%, PV: E4 F12 F3 L17 L18 L3
Playouts: 64961, Win: 73.79%, PV: O15 P17 N18 C9 B9 G2
Playouts: 67115, Win: 73.60%, PV: O15 P17 N18 C9 B9 G2
Playouts: 69300, Win: 73.44%, PV: E4 E7 D7 L3 L2 S13
Playouts: 71383, Win: 73.28%, PV: E4 E7 D7 L3 L2 S13
Playouts: 73429, Win: 73.11%, PV: E4 E7 D7 L3 L2 S13
Playouts: 75512, Win: 72.95%, PV: E4 E7 D7 L3 L2 S13
Playouts: 77593, Win: 72.82%, PV: E4 E7 D7 L3 L2 S13
Playouts: 79599, Win: 72.67%, PV: E4 E7 D7 L3 L2 S13
```

Then leelaz.exe crashes with an exception code of 40000015.

**Comment by earthengine** [comment]
This should be taken seriously. Yesterday I run it before I leave for work but when I am back it crashed.

**Comment by marcocalignano** [comment]
> The 0x40000015 error may be caused by windows system files damage. There can be many events which may have resulted in the system files errors. An incomplete installation, an incomplete uninstall, improper deletion of applications or hardware. It can also be caused if your computer is recovered from a virus or adware/spyware attack or by an improper shutdown of the computer. All the above activities may result in the deletion or corruption of the entries in the windows system files. This corrupted system file will lead to the missing and wrongly linked information and files needed for the proper working of the application.

can you try to download leelaz.exe again?

**Comment by Nabeshin3D** [comment]
I've redownloaded leelaz.exe and am still experiencing the same crash. 

An exception of code 40000015 I believe really just means the app terminated without telling the host why, akin to getting an "unknown error".  I'm not sure the code itself will be particularly helpful in diagnosing the issue.

**Comment by CamWagner** [comment]
LZ has a maximum number of playouts. I also cannot exceed 80,000 playouts at the start of the game.

**Comment by gcp** [comment]
It looks like the fix I did for this doesn't completely work.

**Comment by Neverever** [comment]
Got same issue on Windows 7
Will post update if I can extract anything useful from the crash.

**Comment by earthengine** [comment]
Yes I didn't see it crashing again.

**Comment by Nabeshin3D** [comment]
This seems to no longer be an issue for me in version 0.10.  Following the same steps I used initially, with the same network, leelaz.exe successfully generates a move after ~125000 playouts.  If nobody else experiences the problem in the next couple days I believe I can close this issue as resolved.

**Comment by gcp** [comment]
I did some testing to see what the exact maximum memory usage was in 32-bit mode and set the limit accordingly. I think you were crashing before due to out-of-memory (which happens at 2G in 32-bit mode).
