### ISSUE TITLE
Is it a must to play 400 games between networks?

### ISSUE THREAD

**Issue by ayssia** [gcp/leela-zero#360]
I think 100 games is enough if the win rate is above 65% or below 35%.

**Comment by evanroberts85** [comment]
Not a must for validating a best network, but useful for getting accurate Elo scores. Once everyone has updated 400 training games will happen much faster.

**Comment by isty2e** [comment]
Certainly we don't need to play all 400 games to determine a network is superior not if the margin is large, but for a given winrate (suppose 55%) more games are needed to assure statistical significance. In general, this is tested by SPRT.

That said, the best network can be refreshed once it passes SPRT, and we can run more matches further for future purposes. Unfortunately this doesn't seem to be automated yet. And I assume that we can stop the matchmaking if a new network turns out to be inferior to current one by SPRT.

**Comment by isty2e** [comment]
@roy7 One thing to consider is that a network can be stronger at longer games but weaker at shorter games, for example. Not sure if this can be seriously a problem, but it would be safer to set the minimal number of games to 100 or something. 

By the way, do you have an access to update the best network? fe7a is still there for hours.

**Comment by roy7** [comment]
Yes I can. Normally I leave it to @gcp but I know he's only human, not an advanced 24 hour AI. I'll go do it.

**Comment by isty2e** [comment]
Oh and in the match between ad8a and 6f27 resignation_percent is set to 3. Is it intentional?

**Comment by roy7** [comment]
It was set that way when the match was made, it's an older match, but the resignation bug should be fixed now. I no longer force every match to 0. There is a setting when matches are made so @gcp can make them all 0 moving forward if he wants, or whatever resignation_percent is appropriate for network testing purposes.

**Comment by isty2e** [comment]
I'm not sure if everyone using /next has updated, but at least when something happens wrong results can be fixed with sgf files, so it maybe okay...

**Comment by roy7** [comment]
get-task sends out required client version 10 so older /next users should be prompted to go update.

**Comment by marcocalignano** [comment]
@isty2e You cannot always fixed it with the SGF file see #343

**Comment by isty2e** [comment]
@marcocalignano I think technically we can deal with it, but in a nontrivial way. Anyway it would require some work presumably...

**Comment by marcocalignano** [comment]
But why we cannot fixit in the GTP protocol in leelaz?

**Comment by isty2e** [comment]
Eh, I was talking about already submitted broken games. It shouldn't matter too much anyways once things are settled.
