### ISSUE TITLE
Are network evaluation games also used for training data?

### ISSUE THREAD

**Issue by OmnipotentEntity** [gcp/leela-zero#363]
Just a thought I had, might be a good idea.  Could reduce the potential overfitting for self-play.  Eliminate the deadweight cost of network evaluations, allowing more evaluations for better statistics.

**Comment by evanroberts85** [comment]
But the value output from the neural network aims to give the chances of winning if both sides are even in strength. How then can you use evaluation matches where one network is stronger than the other to train this?
