### ISSUE TITLE
Is it possible to use older or inferior networks to train handicap games?

### ISSUE THREAD

**Issue by OmnipotentEntity** [gcp/leela-zero#364]
This might wind up being effective for training "come from behind" tactics, perhaps making Leela more useful for general game analysis?  And perhaps also useful to train on other komi values.

This would also have a side effect of increasing elo confidence.

**Comment by isty2e** [comment]
Probably not. I don't see it being beneficial for training, especially considering how the value head is trained. And note that LZ (and AGZ too) is specifically configured for 7.5 komi, and training with other komi values is impossible with the current ANN architecture.

**Comment by OmnipotentEntity** [comment]
Can't komi simply be another input to the NN, along with the board state and the current player?

**Comment by isty2e** [comment]
That is a rather a naive way of doing it, I would say. And note that such an approach will require much more training data. There are more elegant ways of doing it (you can refer to [this article](https://arxiv.org/abs/1705.10701), for example), but anyway adding it to the current NN would require a retraining process from scratch.

**Comment by OmnipotentEntity** [comment]
Interesting paper, thanks!

As far as retraining, yes, I am aware.  I was mentioning it now because I was under the impression that this network was a smaller, trial run to iron out bugs and so on and that the plan was the retrain from scratch after this one plateaus.

**Comment by Dorus** [comment]
This would make sense once we reach a point where LeelaZero does no longer improve at al. At that point we could switch to selfplay with handicap stones to train a new network more specialized in playing with or against handicap stones. I guess the same could be done with other variations like rule sets. Different board size wont work as the board size is trained directly into the network.

At least i think doing so would work and you done need to start training from the start all over for small variations like that. On the other hand, doing so now would only waste tons of computing resources as it would split our effort while focusing it all on a single network will probably yield more gain in all variations anyway. Once split you cannot really merge there progress back together again.

**Comment by earthengine** [comment]
Although we cannot have arbitrary size of the board, but we can have any board size that is smaller than the 19x19 one. The only thing need to do is to introduce another board position value: now with 4: black, white, empty and out-of-boundry.
