### ISSUE TITLE
why let four network play with current one, and show others when one's winrate over 55%

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#366]
Matches (100 Most Recent) | Wins / Losses | Games
-- | -- | --
5bcb392e VS fe7a6c28 | 336 : 64 (84.00%) | 400 / 400
be8b358e VS fe7a6c28 | 119 : 281 (29.75%) | 400 / 400
18ddf552 VS fe7a6c28 | 115 : 353 (24.57%) | 468 / 400
424208a5 VS fe7a6c28 | 100 : 292 (25.51%) | 392 / 400

**Comment by roy7** [comment]
Each one was with progressively more training steps.

**Comment by Dorus** [comment]
If only 1 network was tested, there would have been a 75% change on no improvement.

Do i understand training steps right that they are cumulative? So the first 3 networks took a massive dive, but the 4th jumped up from -30% to +34%?

**Comment by roy7** [comment]
I believe so. From the file names in the zip files, looked like 4 networks based on the same training, but it took 20K learning steps to get the big winner.

**Comment by gcp** [comment]
Correct. It's certainly not smooth progress, it's still taking semi-random leaps.
