### ISSUE TITLE
can't complie autogtp

### ISSUE THREAD

**Issue by ericyan71** [gcp/leela-zero#367]
I use vs2015, qt5.8, win10, the leela project can be compiled successfully, but when I compile project of autogtp, it was reported as below:
1>  Moc'ing Validation.h...
1>  Moc'ing Production.h...
1>  Performing Custom Build Tools
1>  系统找不到指定的文件。
1>  Performing Custom Build Tools
1>  系统找不到指定的文件。
 what happened ? thanks!

**Comment by qysnn** [comment]
If you are compiling next branch, it's normal because currently the VS project file is outdated and you can ckeck #323 . If you are compiling master branch, then you should check whether it compiled successfully or not because even with error messages it may still build successfully.

**Comment by klmsj** [comment]
gzip.exe and curl.exe should be exist

**Comment by ericyan71** [comment]
thank klmsj and qysnn,  the curl.exe and gzip.exe must exists in msvc directory, now I compiled autogcp successfully, thanks!

**Comment by marcocalignano** [comment]
@ericyan71 If it is solved can you close this issue?
