### ISSUE TITLE
how leela determine who win the game and how much who win?

### ISSUE THREAD

**Issue by ericyan71** [gcp/leela-zero#370]
I'm writing game ai for gomoku for months, I found to determine who win in gomoku is easy , but difficult in go, I look around the code of leela and I get lost, I can't find the code that calculate who win the game how much he win. could you tell me where to find these code？ thanks!

**Comment by isty2e** [comment]
LZ determines the game result with Tromp-Taylor scoring.

**Comment by zediir** [comment]
This is where it scores passed games https://github.com/gcp/leela-zero/blob/1894e17d8165b8f88b03f704155400091c07db7b/src/FastBoard.cpp#L339

**Comment by ericyan71** [comment]
isty2e, zediir, thanks, I read some function such as area_score, calc_reach_color, etc, but I'm still confused, giving the case that there are some stones of black without eyes in white territory，they are dead, it seems calc_reach_color doesn't concern these dead stone, so I wonder how LZ deal with this sutuation? (sorry my poor english, thanks)

**Comment by isty2e** [comment]
Again, Tromp-Taylor scoring. There is nothing like a dead stone in TT scoring.

**Comment by roy7** [comment]
@ericyan71 In Tromp-Taylor, all stones are alive at all times. If you feel an opponent's stone is dead, you must capture it. Empty space is only scored if it's touching only a single color. It's a scoring model that works great for Go AI.

**Comment by ericyan71** [comment]
great, thanks!
