### ISSUE TITLE
Seems the server have some difficulties playing the network test matches

### ISSUE THREAD

**Issue by Cabu** [gcp/leela-zero#371]
Could/Should that taks be distributed too?

**Comment by marcocalignano** [comment]
Yes but if all the autogtp crashed and not all came back you have only few autogtp that play matches

**Comment by evanroberts85** [comment]
The network matches _are_ distributed, albeit only among those running the /next client.

**Comment by Cabu** [comment]
I am running the windows client during the night (belgium) and run it on 6 of my 8 cores. I could run the specific client for the matches you you want/need it.

**Comment by evanroberts85** [comment]
@Cabu you need to download and compile the /next client from the following link if you want to help run the validation matches:
https://github.com/gcp/leela-zero/tree/next
