### ISSUE TITLE
On how the server distributes the test matches

### ISSUE THREAD

**Issue by isty2e** [gcp/leela-zero#372]
I believe the current goal is to find out which network performs the best among networks trained with different training steps. And to fulfill this goal, the current sequential distribution does not seem efficient.

I think the reason why we play 400 games is for better Elo rating calculation, since the other purposes can be satisfied by SPRT. Then it is efficient to quickly remove unnecessary matches. For this, I suggest the following procedure:

1. Evenly distribute the computational resource among matches, so that they can be evaluated with a similar speed.
2. Evaluate matches based on SPRT. The output of SPRT would be that a new network is improved/not improved/not sure. To avoid some issues, this can be done for the number of games is larger than 50, for example.
3. When one of the new network turns out to be not improved by SPRT, stop the match.
4. When there are many remaining matches, their winrates can be compared by a two proportion z-test, for example. We can abort inferior ones here until the best one survives.

**Comment by evanroberts85** [comment]
We are not even sure if @gcp even plans to do this kind of test very often, so I doubt roy will be feel like making the many needed changes just for am occasional marginal gain.

**Comment by isty2e** [comment]
I believe that for every evaluation process there will be several networks with different training steps. This can save a few hundred games, or even a thousand depending on the number of networks to be evaluated. If we get a bunch of networks everyday, this won't be negligible, and faster best-network update means we get better self-play games on average.

**Comment by evanroberts85** [comment]
I do not think gcp can train several networks every 10k or so games, so training several networks on the same data comes at the expense of having less frequent updates. Worth doing at the moment, probably not every day. We need to hear from @gcp  what his intentions are.

**Comment by isty2e** [comment]
He said training itself doesn't take too much of time, so I'd rather expect a frequent update at least on a daily basis. That seems like the bottleneck for now, so if the networks are not trained frequently I would be surprised.
