### ISSUE TITLE
next branch autogtp -k doesn't save sgf file

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#377]
my command and output
<b>
D:\tool\leela9>autogtp_next -k sgf
AutoGTP v10
Using 1 thread(s).
curl.exe -s -J http://zero-test.sjeng.org/get-task/7
{
    "black_hash": "4701bb9fe03a8bdaedbe82b9872f5ba2f1fd15e3a1244db7e2ead672a873a752",
    "cmd": "match",
    "leelaz_version": "0.9",
    "options": {
        "noise": "false",
        "playouts": "1600",
        "randomcnt": "0",
        "resignation_percent": "1"
    },
    "options_hash": "321436",
    "random_seed": "12646312123737214974",
    "required_client_version": "10",
    "white_hash": "1786fd1ce52031ef08c20cd455dd8225fba13182e9303937fb16d2efbf23797d"
}

Required client version: 10
 -p 1600  -r 1  -m 0  -t 1  -d   --noponder  -s 12646312123737214974
curl.exe -s -O -J -w %{filename_effective} http://zero.sjeng.org/networks/4701bb9fe03a8bdaedbe82b9872f5ba2f1fd15e3a1244d
b7e2ead672a873a752.gz
Curl filename: 4701bb9fe03a8bdaedbe82b9872f5ba2f1fd15e3a1244db7e2ead672a873a752.gz
Net filename: 4701bb9fe03a8bdaedbe82b9872f5ba2f1fd15e3a1244db7e2ead672a873a752
curl.exe -s -O -J -w %{filename_effective} http://zero.sjeng.org/networks/1786fd1ce52031ef08c20cd455dd8225fba13182e93039
37fb16d2efbf23797d.gz
Curl filename: 1786fd1ce52031ef08c20cd455dd8225fba13182e9303937fb16d2efbf23797d.gz
Net filename: 1786fd1ce52031ef08c20cd455dd8225fba13182e9303937fb16d2efbf23797d
./leelaz.exe -p 1600  -r 1  -m 0  -t 1  -d   --noponder  -s 12646312123737214974  -g -q -w 4701bb9fe03a8bdaedbe82b9872f5
ba2f1fd15e3a1244db7e2ead672a873a752
Engine has started.
Infinite thinking time set.
./leelaz.exe -p 1600  -r 1  -m 0  -t 1  -d   --noponder  -s 12646312123737214974  -g -q -w 1786fd1ce52031ef08c20cd455dd8
225fba13182e9303937fb16d2efbf23797d
Engine has started.
Infinite thinking time set.
1 (B Q2) 2 (W S18) 3 (B D2) 4 (W D4) 5 (B D5) 6 (W Q4) 7 (B B13) 8 (W Q14) 9 (B D3) 10 (W F18) 11 (B C16) 12 (W L17) 13
(B E4) 14 (W J3) 15 (B C4) 16 (W R9) 17 (B G18) 18 (W D18) 19 (B F17) 20 (W G17) 21 (B G16) 22 (W F16) 23 (B E17) 24 (W
H17) 25 (B E16) 26 (W D8) 27 (B F15) 28 (W E18) 29 (B D17) 30 (W C18) 31 (B E8) 32 (W H18) 33 (B D7) 34 (W G12) 35 (B D9
) 36 (W S4) 37 (B C11) 38 (W S12) 39 (B H12) 40 (W H13) 41 (B G13) 42 (W G5) 43 (B G11) 44 (W F12) 45 (B J13) 46 (W H14)
 47 (B G14) 48 (W F13) 49 (B H15) 50 (W J14) 51 (B J15) 52 (W K14) 53 (B K15) 54 (W L15) 55 (B L14) 56 (W K13) 57 (B L13
) 58 (W K12) 59 (B L12) 60 (W K16) 61 (B J12) 62 (W K11) 63 (B M15) 64 (W L16) 65 (B H11) 66 (W L11) 67 (B M11) 68 (W M1
6) 69 (B L10) 70 (W M12) 71 (B K10) 72 (W C17) 73 (B J11) 74 (W M4) 75 (B N16) 76 (W N15) 77 (B O15) 78 (W M14) 79 (B N1
4) 80 (W M15) 81 (B M13) 82 (W O16) 83 (B P16) 84 (W B16) 85 (B O17) 86 (W C15) 87 (B B15) 88 (W N17) 89 (B D15) 90 (W O
16) 91 (B C14) 92 (W P17) 93 (B N16) 94 (W R2) 95 (B O16) 96 (W O14) 97 (B N13) 98 (W O13) 99 (B N18) 100 (W Q16) 101 (B
 Q17) 102 (W R17) 103 (B P18) 104 (W Q18) 105 (B M17) 106 (W M18) 107 (B Q15) 108 (W P17) 109 (B R15) 110 (W Q17) 111 (B
 L18) 112 (W P14) 113 (B P15) 114 (W R14) 115 (B M19) 116 (W K18) 117 (B S14) 118 (W O18) 119 (B O19) 120 (W P19) 121 (B
 O18) 122 (W L19) 123 (B K19) 124 (W O12) 125 (B S15) 126 (W S16) 127 (B N12) 128 (W R13) 129 (B S13) 130 (W O4) 131 (B
R12) 132 (W Q12) 133 (B R11) 134 (W Q11) 135 (B S11) 136 (W R10) 137 (B T12) 138 (W S10) 139 (B C8) 140 (W O8) 141 (B G2
) 142 (W H2) 143 (B J8) 144 (W G3) 145 (B F3) 146 (W M8) 147 (B G4) 148 (W H4) 149 (B H3) 150 (W H6) 151 (B G3) 152 (W K
4) 153 (B H7) 154 (W J2) 155 (B J16) 156 (W K17) 157 (B J17) 158 (W J18) 159 (B O11) 160 (W P11) 161 (B B17) 162 (W B18)
 163 (B A16) 164 (W O10) 165 (B N11) 166 (W N10) 167 (B M10) 168 (W J7) 169 (B G19) 170 (W H8) 171 (B K7) 172 (W G7) 173
 (B J6) 174 (W H7) 175 (B K8) 176 (W K6) 177 (B L7) 178 (W H19) 179 (B L6) 180 (W J5) 181 (B L5) 182 (W F19) 183 (B L4)
184 (W L3) 185 (B K5) 186 (W O6) 187 (B M3) 188 (W M2) 189 (B N3) 190 (W N2) 191 (B L2) 192 (W K3) 193 (B N4) 194 (W O3)
 195 (B M5) 196 (W N5) 197 (B N9) 198 (W M4) 199 (B O9) 200 (W N8) 201 (B P10) 202 (W Q10) 203 (B P9) 204 (W P8) 205 (B
Q19) 206 (W R19) 207 (B S19) 208 (W P19) 209 (B Q8) 210 (W Q9) 211 (B R8) 212 (W S8) 213 (B Q19) 214 (W G9) 215 (B R18)
216 (W S17) 217 (B R19) 218 (W F11) 219 (B F10) 220 (W G10) 221 (B H10) 222 (W E10) 223 (B F9) 224 (W F8) 225 (B E9) 226
 (W H9) 227 (B J9) 228 (W H16) 229 (B S7) 230 (W R7) 231 (B Q7) 232 (W R6) 233 (B P7) 234 (W Q6) 235 (B O7) 236 (W N7) 2
37 (B P6) 238 (W N6) 239 (B P5) 240 (W S6) 241 (B Q5) 242 (W P4) 243 (B R5) 244 (W R4) 245 (B S5) 246 (W T5) 247 (B T6)
248 (W resign) Game has ended.
Score: B+Resign
Winner: black
Writing 2d899be629224ae7872855fe115126c8.sgf
Stopping engine.
curl.exe -F winnerhash=4701bb9fe03a8bdaedbe82b9872f5ba2f1fd15e3a1244db7e2ead672a873a752 -F loserhash=1786fd1ce52031ef08c
20cd455dd8225fba13182e9303937fb16d2efbf23797d -F clientversion=10 -F winnercolor=black -F movescount=248 -F score=B+Resi
gn -F options_hash=321436 -F random_seed=12646312123737214974 -F sgf=@2d899be629224ae7872855fe115126c8.sgf.gz http://zer
o-test.sjeng.org/submit-match
Match data c80d60d4951138a210a544ccdbec2f2641a6f4ace601585244a699f77b3c2009 stored in database
1 game(s) (0 self played and 1 matches) played in 70 minutes = 4253 seconds/game, 17149 ms/move, last game took 4233 sec
onds.
</b>
but there is no file in sgf directory

**Comment by l1t1** [comment]
btw ,I can view the game by http://zero.sjeng.org/view/89173489b68980364b0f72cd44cbacb77bda1368222bf295c25529e764f42f6e ,
so it is uploded

**Comment by roy7** [comment]
I believe only self play games are saved, not match games. I think someone is already working to fix this.

**Comment by l1t1** [comment]
@roy7 
so my running is useless for the  candidate network by now?

**Comment by roy7** [comment]
I meant saved by the -k command.

**Comment by marcocalignano** [comment]
@l1t1  Your game was upload to the database so it helped. The -k option is only there for you if you want to save the sgf in another dir before it gets deleted, so you can look at it later.  This feature works only with self-played games. I have a fix in my local repository ready to be pulled, but I wait for @gcp to merge #324 so I can take the improvement in the fix as well.

**Comment by klmsj** [comment]
I have fixed this, if you can not wait, you can checkout from my [repo](https://github.com/klmsj/leela-zero/tree/next)

**Comment by marcocalignano** [comment]
Fixed with  #353
