### ISSUE TITLE
Too many evaluation games for inferior networks

### ISSUE THREAD

**Issue by CamWagner** [gcp/leela-zero#378]
In the evaluation period, there are many networks which have 350+ eval games, but <40% win rates. Shouldn't sprt terminate them sooner?

**Comment by roy7** [comment]
Yes but I need a working sprt for the server first. I tried tonight without luck. Will solve it soon I am sure. Then we will eval early on bad networks.

**Comment by isty2e** [comment]
SPRT itself is not hard to implement, so I wonder what is the issue. Is there anything we can help?

**Comment by roy7** [comment]
Maybe you can spot my error @isty2e ? Instead of trying to port the C++ code from LZ to javascript, I took the python code from here:

https://chessprogramming.wikispaces.com/Match+Statistics#SPRT

and came up with a simple port here:

> function LL (x) {
>     return 1/(1+10**(-x/400));
> }
> 
> function LLR(W, L, elo0, elo1) {
>     if (W==0 || L==0) return 0;
> 
>     var N = W + L;
>     var w = W/N, l = L/N;
>     var s = w;
>     var m2 = w;
>     var variance = m2-s**2;
>     var variance_s = variance / N;
>     var s0 = LL(elo0);
>     var s1 = LL(elo1);
> 
>     return (s1-s0)*(2*s-s0-s1)/variance_s/2.0;
> }
> 
> function SPRT(W,L,elo0,elo1)
> {
>     var alpha = .95, beta = .95;
> 
>     var LLR_ = LLR(W,L,elo0,elo1);
>     var LA = Math.log(beta/(1-alpha));
>     var LB = Math.log((1-beta)/alpha);
> 
>     console.log(LLR_ + " " + LA + " " + LB);
> 
>     if (LLR_ > LB) {
>         return true;
>     } else if (LLR_ < LA) {
>         return false;
>     } else {
>         return null;
>     }
> }
> 
> console.log("10 15: " + SPRT(10, 15, 0, 35) + "\n");
> console.log("100 150: " + SPRT(100, 150, 0, 35) + "\n");
> console.log("65 5: " + SPRT(65, 5, 0, 35) + "\n");
> console.log("40 82: " + SPRT(40, 82, 0, 35) + "\n");
> console.log("100 100: " + SPRT(100, 100, 0, 35) + "\n");
> console.log("1 1: " + SPRT(1, 1, 0, 35) + "\n");

Which prints:

> -0.654158631134416 2.9444389791664394 -2.9444389791664394
> 10 15: true
> -6.541586311344159 2.9444389791664394 -2.9444389791664394
> 100 150: false
> 21.37578216697491 2.9444389791664394 -2.9444389791664394
> 65 5: true
> -5.481236735712218 2.9444389791664394 -2.9444389791664394
> 40 82: false
> -1.0079900268293571 2.9444389791664394 -2.9444389791664394
> 100 100: true
> -0.010079900268293572 2.9444389791664394 -2.9444389791664394
> 1 1: true

And of course those true/false results aren't working correctly. I probably have some super simple error?

**Comment by roy7** [comment]
I simply ignored the Draws parameter since Go has no draws, and replaced D anywhere in the Chess version with a 0 when writing my ported code.

**Comment by isty2e** [comment]
Eh, alpha and beta should be 0.05 instead 0.95, aren't they?

**Comment by roy7** [comment]
Err... let me try that... err...

**Comment by roy7** [comment]
> -0.654158631134416 -2.9444389791664403 2.9444389791664403
> 10 15: null
> -6.541586311344159 -2.9444389791664403 2.9444389791664403
> 100 150: false
> 21.37578216697491 -2.9444389791664403 2.9444389791664403
> 65 5: true
> -5.481236735712218 -2.9444389791664403 2.9444389791664403
> 40 82: false
> -1.0079900268293571 -2.9444389791664403 2.9444389791664403
> 100 100: null
> -0.010079900268293572 -2.9444389791664403 2.9444389791664403
> 1 1: null

All these answers make sense!

**Comment by roy7** [comment]
I won't have time tonight, maybe tomorrow I can go ahead and implement this on test server to short-circuit losing networks. I think @gcp will want winning networks to still play 400 for ELO purposes. But maybe we'll use a sprt pass to make it a best-network sooner.

**Comment by CamWagner** [comment]
Computing to 400 games for winning networks sounds great :). Can't wait for the /next branch to be released!

**Comment by isty2e** [comment]
Good to see it is working fine :)

If you have extra time, it would be also valuable to implement z-test also. A sample code can be found in the [@sethtroisi's repo](https://github.com/sethtroisi/leela-zero/blob/analysis/scripts/thread_compare.py), so if this is ported to JS we can select out the best performing one among winning ones, as requested [here](https://github.com/gcp/leela-zero/issues/372).

**Comment by roy7** [comment]
I just restarted test server, and of the 4 matches that aren't fully complete, 3 are SPRT fails and so are being skipped! Will add short circuit in a sec.

**Comment by roy7** [comment]
It... might... be working...

**Comment by roy7** [comment]
Too bad b2177533 isn't weaker!

**Comment by isty2e** [comment]
We'll see what happens tomorrow :)

**Comment by roy7** [comment]
@isty2e Thanks to you, more goodness: http://zero-test.sjeng.org/

**Comment by isty2e** [comment]
Seems good!

**Comment by billyswong** [comment]
b2177533 VS 4701bb9f has exceeded 400 matches and still going up. Is it intentional or bug?

**Comment by roy7** [comment]
Bit of both. When I restart the test server during coding, the server has no memory of how many matches it has requested but not yet seen come back in. So it'll request back up to 400, and any matches already under way will end up pushing it over 400.

**Comment by Uizmp** [comment]
b2177533 may not collect enough game produced by 4701bb9f self-match after 4701bb9f became the best network.

**Comment by akdtg** [comment]
What about a simple raw way to determine the moment to stop the network evaluation? 
For 55% of 400 games we need just to check results for 200 wins or 180 losses.
So the code will look like:

function shouldWeStop() {
    if (N_WINS >= 220) {
        return YES_ITIS_STRONGER;
    }
    else if (N_LOSSES > 180) {
       return YES_ITIS_WEAKER_OR_NOT_STRONG_ENOUGH;
    }
    else {
        return NO_CONTINUE_THE_EVAL_RUN;
    }
}

**Comment by marcocalignano** [comment]
@roy7 I think you should put the server code into the Git-Hub repository. It is better to collaborate that way (instead of posting the code here). And maybe if @gcp wants and trusts us, since you are the main developer of the server code and I am the one for te autogtp code, we could be granted write access to merge the pull-requests (only for these part of the code). It would speedup bug fixes and  improvements.

**Comment by sethtroisi** [comment]
I wrote the smallest version of SPRT I could in python

```
class Sprt:
    def __init__(self, winH0, winH1, alpha, beta = 0):
        self.p0 = winH0
        self.p1 = winH1
        self.winLog = math.log(self.p1 / self.p0)
        self.lossLog = math.log((1-self.p1) / (1-self.p0))

        if beta == 0:
            beta = alpha

        self.lower = math.log(beta / (1 - alpha))
        self.upper = math.log((1 - beta) / alpha)

        self.wins = 0
        self.losses = 0

    def addResult(self, win):
        if win:
            self.wins += 1
        else:
            self.losses += 1

    def status(self):
        llf = self.wins * self.winLog + self.losses * self.lossLog
        if llf < self.lower:
            return -1
        if llf > self.upper:
            return 1
        return 0
```

I'll write a js version for fun and we can compare results.

**Comment by sethtroisi** [comment]
JS version

```
function winProb(elo) {
  return 1 / (1 + Math.pow(10, elo / -400));
}

function SPRT(wins, losses, alphaElo, betaElo) {
   p0 = winProb(alphaElo);
   p1 = winProb(betaElo);

   winLog = Math.log(p1 / p0);
   lossLog = Math.log((1 - p1) / (1 - p0));
   
   alpha = 0.05;
   beta  = 0.05;
   lowerBound = Math.log(beta / (1 - alpha));
   upperBound = Math.log((1 - beta) / alpha);

   llr = wins * winLog + losses * lossLog;
   console.log("\t" + llr + " " + lowerBound + " to " + upperBound);
   if (llr < lowerBound) return -1;
   if (llr > upperBound) return 1;
   return 0
}
  
console.log("10 15: " + SPRT(10, 15, 0, 35) + "\n");
console.log("100 150: " + SPRT(100, 150, 0, 35) + "\n");
console.log("65 5: " + SPRT(65, 5, 0, 35) + "\n");
console.log("40 82: " + SPRT(40, 82, 0, 35) + "\n");
console.log("100 100: " + SPRT(100, 100, 0, 35) + "\n");
console.log("1 1: " + SPRT(1, 1, 0, 35) + "\n");
```
```
output:
	-0.6303285697452581 -2.9444389791664403 to 2.9444389791664403
10 15: 0

	-6.30328569745258 -2.9444389791664403 to 2.9444389791664403
100 150: -1

	5.689699243281497 -2.9444389791664403 to 2.9444389791664403
65 5: 1

	-4.848993941962274 -2.9444389791664403 to 2.9444389791664403
40 82: -1

	-1.0131046452224854 -2.9444389791664403 to 2.9444389791664403
100 100: 0

	-0.01013104645222486 -2.9444389791664403 to 2.9444389791664403
1 1: 0
```

**Comment by Dorus** [comment]
I've been thinking about this too. SPRT is just 2 standard deviations from the average right? The problem is, passing SPRT with 10 games still means you can fail SPRT at 20 games. Just a single extra loss can push you below the error margin.

To calculate how likely you are to pass SPRT by 400 games, you need to take into account how many more games you are about to play and then decide on an acceptable error margin.

It might be easier to use heuristics like 4 standard deviations. Or simply 220 games won. Or something like 60 more games won than lost up to a max of 220.

The most advanced way would be to check how many more games are needed and how many wins are needed for 220 wins. Then check if this is 2 standard deviations below the average.

js code as example:

    WillPassSprt(wins, losses, goal) {
      var n = Math.max(goal - wins - losses, 0) 'number of remaining matches
      var w = Math.round(goal * 0.55) - wins ' required nr of wins in remaining matches
      var stdev = sqrt((n/2)^2/n) ' stdev for remaining matches
      return n/2 - 2*stdev >= w ' do we expect to win enough remaining matches?
    }

This will be 95% certain we reach the 55% threshold.

**Comment by isty2e** [comment]
IMHO it would be just enough to run SPRT only after we get a certain number of games, like 50 or 100.

**Comment by Dorus** [comment]
@isty2e yeah but passing SPRT at 100 games does not guarantee you pass it at 400 games. Even with a 90-10 score, if the remaining matches are a coin flip, there is a 5% chance you wont make it (130 wins in 300 games). My code above actually checks that:

> WillPassSprt(90, 10, 400)
false
WillPassSprt(100, 10, 400)
true

Below 90 wins you cannot even pass the check:

> WillPassSprt(89, 0, 400)
false

**Comment by evanroberts85** [comment]
Sprt is already a confidence check, no need for extra confidence checks on top of it, which only makes things more complicated and worse.

**Comment by isty2e** [comment]
@Dorus Well that's what statistics is... There is nothing like 100% guaranteed something. By the way, SPRT is not "just 2 standard deviations from the average", rather a hypothesis test using log-likelihood. 90-10 definitely passes SPRT, not to mention 89-0.

**Comment by evanroberts85** [comment]
I supose early on less effort (i.e number of games) is required to build more confidence so continuing testing is more worthwhile, you could factor this into the calculation but i see little need.

**Comment by Dorus** [comment]
Passing SPRT at 400 is different from passing at at 100 or 120 or 140 or 160 ... or 380 or 400. The likelihood you pass it anywhere between 0 and 400 games is much higher than just passing it at 400.

I'm a little in doubt about SPRT now. Is SPRT really that you test for every event? As far as i understood in the alphago paper they only passed if 55% was reached after 400 games. 55% at 400 games is indeed "2 standard deviations from the average", that's where that came from.

I supposed the code i wrote is a bit of a reverse SPRT test then: stop (pass the network) when you are 95% sure to pass 55% by 400 games.

**Comment by isty2e** [comment]
@Dorus I'm not sure what you mean... Given a fixed winrate (>0.5), it is likely to pass SPRT when total number of games is larger. For example, 200-100 passes the SPRT(0, 35, 0.05, 0.05), whereas 20-10 doesn't. I don't see any reason not to use SPRT...

**Comment by roy7** [comment]
@marcocalignano I've thought about it. Will probably end up doing that. My code is embarrassingly bad I'm sure since I was learning node when I started writing it, lol. :)

@sethtroisi Thanks! When I'm back in there I'll maybe replace my raw copy/paste from the python version on that Chess site to use yours since it's less steps and you use better variable names.

**Comment by Dorus** [comment]
I guess i should calc the stDev for the goal too instead of using 55% fixed.
```Js
StDev(n) {
  return Math.sqrt(Math.pow(n,2)/n)
}

WillPass2stdev(wins, losses, goal) {
  var n = Math.max(goal - wins - losses, 0) // number of remaining matches
  var w = Math.round(2*StDev(goal) + goal/2) - wins // required nr of wins in remaining matches
  return n/2 - 2*StDev(n) >= w // do we expect to win enough remaining matches?
}
```

**Comment by gcp** [comment]
My preference would be to use SPRT fails to stop bad networks, but play 400 games on the ones that do not fail to draw a nice graph.

SPRT already includes confidence tests so as said, no reason to add any others. Especially as some naive tests will produce misleading confidence margins because they don't take into account that we are doing a test after every game and not setting the number of games in advance.

>Is SPRT really that you test for every event?

Yes, that's exactly the point: to get early termination *and* get correct confidence margins if you don't set the amount of samples in advance. Here, we don't necessarily need early termination for good networks (because we want to draw a better graph), but it's good for bad networks (don't waste time testing them).

**Comment by isty2e** [comment]
@gcp How about some z-tests between good networks? We'll need 400 games for only the best network.

**Comment by Dorus** [comment]
Oh, SPRT for fails make sense. In that case just add a fail function:

```Js
HasFailedSprt(wins, losses) {
  var n = wins + losses
  return n / 2 + 2*StDev(n) < losses
}
```

My function above was actually an success function for early network release :)

**Comment by roy7** [comment]
We had a SPRT pass for e671af6f by 96 games, so I rolled it out in the early 100s. Rollout isn't automatic yet but I happened to be watching it. :)

**Comment by marcocalignano** [comment]
@roy7 But I thought that @gcp said to do all the 400 games before updating the chart after one network pass the SPRT test, and Stop the networks that do not pass it.

**Comment by roy7** [comment]
@marcocalignano Yes we are leaving the winning networks running up to 400 full matches. Doesn't mean we can't release the network early for selfplay. The chart isn't automated yet anyway. If the SPRT was a fail, it'd have stopped sending out match requests.

**Comment by marcocalignano** [comment]
@roy7 but the only reason that we play 400 games is to get a better chart so the chart update has to wait till the end.

**Comment by zediir** [comment]
When next->master we won't be getting new self-plays anyway before the 400 games have been played.

**Comment by roy7** [comment]
@zediir True atm. :)

**Comment by evanroberts85** [comment]
First time I have seen the rectangular six shape in a Leela Zero game.
Black does not know how to kill, but on the other hand White knows how to
live!

**Comment by roy7** [comment]
Early abort triggered at 9 wins 29 losses. Sweet. The final score ended up 20 wins 68 losses because of matches already assigned before SPRT turned this match off. Still, that's a savings of 300 unneeded games. :)

**Comment by evanroberts85** [comment]
..which means an extra 300 self-play games 😀

**Comment by barrtgt** [comment]
It might be a little more efficient to test multiple new networks the same time, that way we can determine a more superior network earlier on.

**Comment by evanroberts85** [comment]
It looks like @gcp has automated training, so a new network match is
uploaded per hour. The question is as both 251b and 4d4a are being tested
against e617, what score does 251b need to pass given that 4d4a got around
56%?

**Comment by gcp** [comment]
Further discussion in #545.
