### ISSUE TITLE
node status not updated in play_simulation for two consecutive passes

### ISSUE THREAD

**Issue by chaosma** [gcp/leela-zero#38]
In play_simulation method from UCTSearch.cpp: 

When we have two consecutive passes, node->create_children will return false. In this case, the result.valid() is false, hence all its parent nodes will get invalid result and their node status will not be updated. 

My understanding is we need use the final result of game simulation to update the previous nodes when we descend along the game tree. In this case, we don't have a valid result returned, then how can we update the node in MCTS when the game simulation is finished (with two passes) ?

Update:
I read the paper, the result of self-play is never used in MCTS, but just used in training the network, so never mind for this question. Thanks!

**Comment by gcp** [comment]
You understood correctly. During the tree search, we only ever case about the evaluation from the value network, so there is no need to evaluate terminal nodes (the score is not going to change between the same position with one pass or two passes, presumably!).

There is a bit of control logic in UCTSearch.cpp that will count the score in the final position when the search wants to pass.

**Comment by gcp** [comment]
You called this one correctly. Not updating the node means that the search probabilities upwards in the tree get skewed, leading to issue #54.
