### ISSUE TITLE
Website charts

### ISSUE THREAD

**Issue by BHydden** [gcp/leela-zero#380]
I know it's a really small thing, but is there any chance the size of the two bottom charts on the side could scale dynamically?

**Comment by BHydden** [comment]
By charts I definitely meant tables 🤔

**Comment by roy7** [comment]
What do you mean by scale dynamically? They do that already, they resize however needed to fit the contents. No specific width/height settings are used.

**Comment by BHydden** [comment]
On my screen the tables are about half the width of the graph, but the right hand table uses two lines per entry and the left hand one uses one.

**Comment by BHydden** [comment]
Either you fixed that really fast, or else I'm insane because I just checked again and it looks good lol

**Comment by roy7** [comment]
Oh your screen is maybe less wide than mine then so there's word wrapping happening within some of the cells? I could use whatever the table setting is to prevent word wrapping if that'd help.

**Comment by BHydden** [comment]
Nope it appears I'm clearly delirious... sorry to bother you :P just checked both my devices again and they're spot on! :S sorry to bother you haha
