### ISSUE TITLE
Suggestion: Add Time Zone Info to Web Page

### ISSUE THREAD

**Issue by billyswong** [gcp/leela-zero#381]
Since there are now datetime for each hashes and matches, it's better we also mention the time zone they are in as a footnote or something for readers' benefit.

**Comment by evanroberts85** [comment]
Also for a cleaner style - the seconds are not needed and a 24h clock is better.

**Comment by isty2e** [comment]
Another little thing: AFAIK MM/DD/YYYY format is only used in the US. DD/MM/YYYY, or preferably YYYY/MM/DD (following ISO 8610) would be better. Or YY/MM/DD.

**Comment by evanroberts85** [comment]
for strftime (python, but should be similar in other languages) I would use
“%d %b - %H:%M” to give a nice format like
05 Dec - 21:33

year is not really needed

**Comment by gaieepo** [comment]
@evanroberts85 Year is actually needed since there is less than one month left to 2018. This project might last longer than we might have expected.

**Comment by evanroberts85** [comment]
If needs to be stored but not displayed, the networks are listed in order,
so it is pretty obvious what year each is.

**Comment by Armavica** [comment]
@isty2e ISO 8601 is actually YYYY-MM-DD, like the format already used for the news at the top of the page.

**Comment by roy7** [comment]
Yeah I'll clean this up sometime soon. I wasn't sure how to convert MongoDB's ISOTIME() into something the way I wanted easily (YYYY-MM-DD HH:MM) so I just did something simple so I could move on to other tasks.

**Comment by roy7** [comment]
I'll use http://momentjs.com/ when I have time later today.

**Comment by isty2e** [comment]
This shouldn't be an urgent issue, Please take it easy :)

**Comment by evanroberts85** [comment]
@roy7 Did you ever get to the bottom of why the last 24h game count sometimes drops right down? It is currently showing just 3,500 games.

**Comment by roy7** [comment]
It is when gcp deletes games from the db so it is no longer there to count.

**Comment by evanroberts85** [comment]
But I assume he is not deleting recent games?

**Comment by roy7** [comment]
He dumps the files out to the archive url provided by OGS and the copies he needs for training. They don't need to sit in the server database itself. But for 24 hour stats I just check database count of games.

**Comment by evanroberts85** [comment]
Does that affect the games count in the best network table?

**Comment by roy7** [comment]
No that is a permanent summary table updated each time a game is submitted. :)

**Comment by evanroberts85** [comment]
You could then use that data then, along with the time stamps to calculate
the rate of games for each network for historical comparison.

I would delete the 24h stat, better no stat than one that is inaccurate
quite regularly.

**Comment by roy7** [comment]
@gcp Do you want me to remove past 24 hour, or have you stop deleting data less than 24 hours old from database, or just not worry about it? ;)

**Comment by roy7** [comment]
New date formats are on http://zero.sjeng.org/. I didn't restart test server yet since we're mid-match and that'll cause lots of excess games to get played.

**Comment by evanroberts85** [comment]
The minute data for all the matches seem to be 12, so I think you may have
the formatting wrong.

**Comment by roy7** [comment]
Oops!

format("YYYY-MM-DD HH:MM") ... yeah ...

**Comment by roy7** [comment]
Fixed.
