### ISSUE TITLE
could you add a column in zero web page to show network's games amount?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#382]
for examle 

Best Network Hash (100 Most Recent)

Upload Date | Hash | Games | amt
-- | -- | -- | --
12/13/2017, 6:21:31 AM | 4701bb9f | 10408 |1030K

**Comment by yxh790820** [comment]
yes， i need it

**Comment by roy7** [comment]
Yeah it's on the list to figure out how to best do that. I could just sum up all the games to that point, but it won't match the amount of training games used in the networks when they were trained, so it might mislead people if they think that's what the # means.

**Comment by gcp** [comment]
A column of "submitted" games at time of upload would be possible, but it will be about 10-20k off from the amount of games used for training. Maybe that's good enough?

**Comment by l1t1** [comment]
thanks

**Comment by roy7** [comment]
Added.
