### ISSUE TITLE
why next branch also has self-game?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#383]
curl.exe -s -J http://zero-test.sjeng.org/get-task/7
{
    "cmd": "selfplay",
    "hash": "4701bb9fe03a8bdaedbe82b9872f5ba2f1fd15e3a1244db7e2ead672a873a752",
    "leelaz_version": "0.9",
    "options": {
        "noise": "true",
        "playouts": "1600",
        "randomcnt": "30",
        "resignation_percent": "1"
    },
    "options_hash": "16b7b7",
    "random_seed": "11100916500585786754",
    "required_client_version": "10"
}

Required client version: 10
 -p 1600  -r 1  -m 30  -t 1  -d   -n   --noponder  -s 11100916500585786754
Already downloaded network.
./leelaz.exe -p 1600  -r 1  -m 30  -t 1  -d   -n   --noponder  -s 11100916500585786754  -g -q -w 4701bb9fe03a8bdaedbe82b
9872f5ba2f1fd15e3a1244db7e2ead672a873a752
Engine has started.
Infinite thinking time set.
1 (B N2) 2 (W S16) 3 (B O3) 4 (W D4) 5 (B Q2) 6 (W A12) 7 (B N16) 8 (W C15) 9 (B A9) 10 (W D16) 11 (B M16) 12 (W H5) 13
(B F13) 14 (W R11) 15 (B B7) 16 (W Q4) 17 (B J3) 18 (W D18) 19 (B F12) 20 (W O13) 21 (B P9) 22 (W S12) 23 (B S11) 24 (W
S10) 25 (B J13) 26 (W J17) 27 (B O5) 28 (W F4) 29 (B R3) 30 (W G16) 31 (B P17) 32 (W Q16) 33 (B H8) 34 (W R7) 35 (B O7)
36 (W G3) 37 (B P4) 38 (W C9) 39 (B K15) 40 (W Q17) 41 (B S5) 42 (W M18) 43 (B H6) 44 (W B4) 45 (B K12) 46 (W Q6) 47 (B

**Comment by isty2e** [comment]
You have been here for long asking questions. You can read relevant issues, like [this one](https://github.com/gcp/leela-zero/issues/249). In short: The server requests clients what to do.

**Comment by l1t1** [comment]
thanks
