### ISSUE TITLE
it seems in recent versions of network, the smaller gz file is, the stronger it is

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#384]
I guess ,the file includes more 0, it can be compressed more , so 0's amounts of network file relate with its strength:)

4701bb9fe03a8bdaedbe82b9872f5ba2f1fd15e3a1244db7e2ead672a873a752.gz 2798724 2017-12-13 06:21:31 -->best 
bd08cfd438be41cf6038a1a96ea2e320609b7050a5917cbd00317935d0764bd6.gz 2798900 2017-12-13 06:21:23
d5b7aec30633d495bf1908a5ead955b02553188f63d56fd6d6ac13b5d0ee4232.gz 2800707 2017-12-13 06:21:08

----

b2177533a39a90af9943d1e0deb2e930f4a9b20825a19e7fc39358d836164f80.gz 2799438 2017-12-13 21:47:07 -->best
1786fd1ce52031ef08c20cd455dd8225fba13182e9303937fb16d2efbf23797d.gz 2800362 2017-12-13 21:46:59
1394f81ee6d865638c4134ac5fb5bc568ba37f1e60a895a393ee745da6a9c4f3.gz 2801101 2017-12-13 21:46:52

**Comment by ayssia** [comment]
I think it's just a coincidence.

**Comment by SharlatanY** [comment]
Maybe it'll get super strong if we replace every value with 0?
