### ISSUE TITLE
why network 251b7ca often create very short games?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#385]
d:\tool\leela8>autogtp -k sga
AutoGTP v8
Using 1 thread(s).
Best network hash: 251b7ca85b3fae0e19e55e9f79abdc5ec3d6832ad2819131581127a0c0c6b4b0
Required client version: 8 (OK)
curl.exe -s -O -J -w %{filename_effective} http://zero.sjeng.org/best-network
Curl filename: 251b7ca85b3fae0e19e55e9f79abdc5ec3d6832ad2819131581127a0c0c6b4b0.gz
Net filename: 251b7ca85b3fae0e19e55e9f79abdc5ec3d6832ad2819131581127a0c0c6b4b0
./leelaz.exe -r 1 -g -t 1 -q -d -n -m 30 -w 251b7ca85b3fae0e19e55e9f79abdc5ec3d6832ad2819131581127a0c0c6b4b0 -p 1600 --n
oponder
Engine has started.
Infinite thinking time set.
<b>1 (F8) 2 (S4) 3 (pass) 4 (pass) Game has ended.</b>
Score: W+7.5
Winner: white
Writing 59dc6c955f174b508f466cd734b3f383.sgf
Dumping 59dc6c955f174b508f466cd734b3f383.txt
1 game(s) played in 0 minutes = 47 seconds/game, 11750 ms/move, last game took 36 seconds.
curl.exe -F networkhash=251b7ca85b3fae0e19e55e9f79abdc5ec3d6832ad2819131581127a0c0c6b4b0 -F clientversion=8 -F sgf=@59dc
6c955f174b508f466cd734b3f383.sgf.gz -F trainingdata=@59dc6c955f174b508f466cd734b3f383.txt.0.gz http://zero.sjeng.org/sub
mit
Game data 0e6d13c55e184f822ca7edc417aaa4f6c5367a5f12d8f32f33a29ee8515f967f stored in database
Best network hash: 251b7ca85b3fae0e19e55e9f79abdc5ec3d6832ad2819131581127a0c0c6b4b0
Required client version: 8 (OK)
Already downloaded network.
Stopping engine.
./leelaz.exe -r 1 -g -t 1 -q -d -n -m 30 -w 251b7ca85b3fae0e19e55e9f79abdc5ec3d6832ad2819131581127a0c0c6b4b0 -p 1600 --n
oponder
Engine has started.
Infinite thinking time set.
<b>1 (L11) 2 (S4) 3 (J15) 4 (C3) 5 (D8) 6 (O2) 7 (P15) 8 (J5) 9 (pass) 10 (pass) Game has ended.</b>
Score: W+7.5
Winner: white
Writing 18e83ee71d2440d4b850ce3bc09b43ce.sgf
Dumping 18e83ee71d2440d4b850ce3bc09b43ce.txt
2 game(s) played in 3 minutes = 100 seconds/game, 14357 ms/move, last game took 153 seconds.
curl.exe -F networkhash=251b7ca85b3fae0e19e55e9f79abdc5ec3d6832ad2819131581127a0c0c6b4b0 -F clientversion=8 -F sgf=@18e8
3ee71d2440d4b850ce3bc09b43ce.sgf.gz -F trainingdata=@18e83ee71d2440d4b850ce3bc09b43ce.txt.0.gz http://zero.sjeng.org/sub
mit
Game data 1afbb73943942a5b3575fe7aa21d40b8b14d1431546a4ae43358dd7bbd0740f0 stored in database
Best network hash: 251b7ca85b3fae0e19e55e9f79abdc5ec3d6832ad2819131581127a0c0c6b4b0
Required client version: 8 (OK)
Already downloaded network.
Stopping engine.
./leelaz.exe -r 1 -g -t 1 -q -d -n -m 30 -w 251b7ca85b3fae0e19e55e9f79abdc5ec3d6832ad2819131581127a0c0c6b4b0 -p 1600 --n
oponder
Engine has started.
Infinite thinking time set.
1 (L12) 2 (S18) 3 (O8) 4 (D4) 5 (R13) 6 (B16) 7 (O14) 8 (R7) 9 (Q6) 10 (O2) 11 (K3)

**Comment by Dorus** [comment]
Cant say they do for me, games are 3-5kb as usual. Something is off on your pc probably? Might be worth it to dig into.

**Comment by l1t1** [comment]
the 4th and 3rd games are normal
