### ISSUE TITLE
suggestion for match

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#388]
each network have equal number of first step black and second white ,
if the win games of one excced 220  , the match end

**Comment by l1t1** [comment]
for example,in following table, line 1 and line 2 all useless, because
1 251b7ca8 has become best one, the match isn‘t train newer 
2 two networks are all out

2017-12-14 21:20 | 251b7ca8 VS e671af6f | 275 : 138 (66.59%) | 413 / 400 | PASS
-- | -- | -- | -- | --
2017-12-14 20:18 | 4d4a326f VS e671af6f | 225 : 180 (55.56%) | 405 / 400 |

**Comment by roy7** [comment]
Wining networks with SPRT PASS will still play up to 400 games because it'll give more accurate ELO values once we automate the graph.

**Comment by l1t1** [comment]
thanks
