### ISSUE TITLE
The number of MCTS simulations

### ISSUE THREAD

**Issue by panda0307** [gcp/leela-zero#389]
By comparison, the Leela 0110.exe on Windows is too faster(MCTS simulations) than the manner of source code, on the same computer, the same CPU, the same GPU.
So, I would like to know the difference between source code and the executable program. Why "source code" is slower and how to accelerate it? 
I would much appreciate it if someone could teach me. Thanks.
Thank you @gcp .

**Comment by roy7** [comment]
Leela is running tons of monte carlo rollouts while the GPU is busy doing policy and value network evaluations. Leela Zero on the other hand does no rollouts, it is limited by neural network speed which is way slower.
