### ISSUE TITLE
Two questions about auto-play games

### ISSUE THREAD

**Issue by pcengine** [gcp/leela-zero#39]
Dear Sir, 
          I have two questions about Leela-Zero:

1.  I ran the autogtp.exe files several times and generated several games (in sgf format), but how do I send these sgf files back to you or to some sort of servers? 

2. I need to click autogtp.exe icon again and again if I want to generate a few games. Is there a command that I  can tell leela-zero to run a few hundred games so that I don't need to click the autogtp.exe icon a few hundred times?

**Comment by pcengine** [comment]
I have read the readme file and found the following explanations:

_# Training
## Getting the data
At the end of the game, you can send Leela Zero a "dump\_training" command,
followed by the winner of the game (either "white" or "black") and a filename,
e.g:
    dump_training white train.txt
This will save (append) the training data to disk, in the format described below.
Training data is reset on a new game._

My question is, where to enter that "dump_training white train.txt"  command? 
I have generated 5 games in 30 minutes, but not sure how to send the sgf files back to you.

 [leelagames.zip](https://github.com/gcp/leela-zero/files/1465483/leelagames.zip)

**Comment by roy7** [comment]
Autogtp has been updated to be fully automatic but a new Windows executable has not been released yet. If you're using the windows binary that is the reason why. If you can give him a little time to release a new windows binary, or if you compile it yourself, then you can just leave it running forever.

**Comment by pcengine** [comment]
Great, thanks for your fast reply. I really appreciate it. I dont know much
about the compiling stuff, so I guess I will wait for the automatic version
for windows.
Thanks again and wish you all have a wonderful day.

2017年11月13日 下午1:30，"Jonathan Roy" <notifications@github.com>寫道：
