### ISSUE TITLE
question about leela gpu version

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#390]
in next branch of leelaz, a cpu only version is created ,it solved some gpu bug.
Closes issue #70. Will be used to address issue #359 and issue #375.
I wonder if the leela 0.11 has similar question?

**Comment by gcp** [comment]
If your GPU returns garbage result anything using the GPU will be affected.

**Comment by gcp** [comment]
One difference is that because normal Leela has a "fixed" network she can and does do a self-check on startup.

**Comment by l1t1** [comment]
thanks
