### ISSUE TITLE
Is -m 30 default with leelaz if not stated?

### ISSUE THREAD

**Issue by barrtgt** [gcp/leela-zero#391]
For instance if leelaz is run in sabaki? What about -n command as well? It looks like -m 0 is default, but I just want to make sure.

**Comment by Alderi-Tokori** [comment]
the -m and -n only have sense when generating training data as they're used to force exploration and selection of bad moves. When run in sabaki, Leela will most of the time be used to play games, so a default -m 0 makes more sense.

**Comment by barrtgt** [comment]
Right. I just wasn't sure if in the case it was omitted from the command line, what actions Leelaz would take.

**Comment by Alderi-Tokori** [comment]
Ah I see, yes the default is 0, you can see the configuration flags in GTP.cpp

**Comment by barrtgt** [comment]
Oh there it is. Thank you very much.

**Comment by ggPeti** [comment]
Or `leelaz -h`.
