### ISSUE TITLE
Questions about im2col in Im2Col.h

### ISSUE THREAD

**Issue by barrybecker4** [gcp/leela-zero#392]
I'm having difficulty understanding what this method does. What does im2col stand for?

Also how you you interpret this for loop?
  `for (int channel = channels; channel--; data_im += channel_size) `
It decrements channels on every iteration, but when does it terminate? Oh  - I guess it terminates when channel-- is 0 - it does the increment and termination check at the same time. 
Pardon my c++ ignorance, but what does data_im += channel_size mean when data_im is defined as
  `const net_t* data_im = input.data();`
Is it incrementing a memory pointer or the value pointed to in memory? input.data() returns the address of the first element in input, so I guess it is moving the pointer forward. Later when you access data_im[input_row * width + input_col], I guess it does a lookup starting from that new index position and not the very start of data_im.

Even if I can get to a point where I can understand all the code here, I still feel like I am missing the big picture. Any comments you can add about this methods purpose would be appreciated.
Thanks!

**Comment by Alderi-Tokori** [comment]
> it does the increment and termination check at the same time.
Not exactly, the syntax var-- is a post-decrementation, meaning the content of the variable is tested first, and modified after, so the loop terminates when channel itself is 0.

As for data_im += channel_size, your guess is probably correct, it increments the memory pointer so it points to the next channel to process.

From what I can tell by the name and my rapid look at the function, it seems to flatten the 3-D input into a 1-D vector.

**Comment by sethtroisi** [comment]
You can read about the algorithm here:
https://arxiv.org/pdf/1410.0759.pdf

It's covered extensively on page 3.

**Comment by sethtroisi** [comment]
There's a pull request with some comments if you want more info

https://github.com/gcp/leela-zero/pull/104

**Comment by barrybecker4** [comment]
Thanks for the info. Reading #104 and the references helped me a bit.
When you said that there was a PR with comments in #104 I thought the comments would be in the code not about the PR itself. I think it would be good to add a top level comment on that im2col method which has some of the points made in the PR comments and gives pointers to the relevant URLs so that others reading the code in the future won't we as confused as we were then we first read it. Same goes for other parts of the code that are based on academic literature.
