### ISSUE TITLE
how to understand the 1st line of match table

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#393]
current best-network is 3ba92804, why play 6f274ab1 VS 22373747 ?
2017-12-16 01:06 6f274ab1 VS 22373747 18 : 4 (81.82%) 22 / 400   
2017-12-15 21:19 a8670300 VS d11131e3 50 : 88 (36.23%) 138 / 400 fail 
2017-12-15 21:10 3ba92804 VS d11131e3 214 : 97 (68.81%) 311 / 400 PASS

**Comment by roy7** [comment]
We're going to slowly work through all of the prior networks that don't exist in the matches table yet so we have accurate ELO data for future use in automatic graphing.

**Comment by l1t1** [comment]
thanks

**Comment by l1t1** [comment]
and I check http://zero.sjeng.org/networks/
Index of /networks/

../
1394f81ee6d865638c4134ac5fb5bc568ba37f1e60a895a..> 13-Dec-2017 20:46             2801101
1607dbea9c6f8f8e6137b2b167464d4003e5b43c1ec4d79..> 09-Dec-2017 18:13             2802241
163f2cef6dfbf43def2c53b40c6c6e229e98db83276aeab..> 10-Dec-2017 09:44             2802826
1786fd1ce52031ef08c20cd455dd8225fba13182e930393..> 13-Dec-2017 20:46             2800362
18438584bd84d9a88cef7c8d931ae81cdd5708f6416cbaf..> 14-Dec-2017 18:08             2797161

found the table now is ordered by gz file name as following, could you order it by file datetime?

**Comment by roy7** [comment]
That's because we no longer server the directory though the game server process, it's handled by the web server. Can't control that I don't think. But we don't really consider /networks/ a public place people should load. If you want to download a best network or a network used in match testing, click the link from the main page.

**Comment by roy7** [comment]
@gcp if you wanted to, you can use this nginx module to sort contents of a directory by date instead of name.

https://www.nginx.com/resources/wiki/modules/fancy_index/

**Comment by gcp** [comment]
Fixed.
