### ISSUE TITLE
Automated ELO chart

### ISSUE THREAD

**Issue by roy7** [gcp/leela-zero#394]
Just opening a place to specifically discuss the chart(s) and such.

@isty2e I took the Vega Lite sample you provided and have been experimenting with it here:

http://zero-test.sjeng.org/view/player/elo.html

Can I customize the color scheme easily or do I need to do a filter like I did for line, and plot the 3 SPRT results separately and specify color for each that way?

**Comment by roy7** [comment]
Hmm got a division by 0 someplace. When there are pending matches with 0 games, the ELO goes to Inf or -Inf, and breaks the graph.

**Comment by roy7** [comment]
Fixed. If you've never won or loss, the ELO calculation is Inf or -Inf. I only calculate ELO for matches with at least 1 win and 1 loss now.

**Comment by sethtroisi** [comment]
Looks very nice (minus initial points without data)!

**Comment by isty2e** [comment]
For color schemes, [here](https://vega.github.io/vega-lite/docs/scale.html#scheme) is how to do it. In the color field of mark-point layer, you can add "scale": {"range": ["yellow", "red", "blue"]} so that 

```
            "color": {
              "field": "sprt", 
              "type": "nominal",
              "scale": {"range": ["yellow", "red", "blue"]}
            },
```

**Comment by roy7** [comment]
Thanks @isty2e! I went with blue for best network, green for unknown, and red for fail. Yellow looked kinda harsh. Open to any/all suggestions on the graph.

**Comment by isty2e** [comment]
By the way, you might want to apply [BayesElo](https://www.remi-coulom.fr/Bayesian-Elo/) rating instead of plain Elo rating, especially when the number of games is small. It handles situations like 10-0 well, and is considered more accurate in general.

**Comment by l1t1** [comment]
I use IE11, the page shows nothing
and use google chrome, it shows following
why?
![elo](https://user-images.githubusercontent.com/23301704/34068626-80092dd6-e279-11e7-9234-3e0045ea146f.png)

**Comment by l1t1** [comment]
and i saw the page source of IE
<pre>
<!DOCTYPE html>
<html>
<head>
  <title>Embedding Vega-Lite</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/vega/3.0.8/vega.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/vega-lite/2.0.3/vega-lite.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/vega-embed/3.0.0-rc7/vega-embed.js"></script>
</head>
<body>

  <div id="vis"></div>

  <script type="text/javascript">
    var yourVlSpec = {
      "$schema": "https://vega.github.io/schema/vega-lite/v2.0.json",
      "description": "Leela Zero Elo rating",
      "config": { 
        "point": { "size": 80 }
      }, 
      "data": {
        "url": "/data/elograph.json"
      },
      "layer": [
        {
          "transform": [
            { "filter": { "field": "best", "equal": "true" } } ],
          "mark": "line",
          "encoding": {
            "x": {
              "field": "net", 
              "type": "quantitative",
              "axis": {
                "title": "Number of accumulated games",
              }
            },
            "y": {
              "field": "rating", 
              "type": "quantitative",
              "axis": {
                "title": "Elo rating (0 = random play)"
              }
            },
            "color": {
              "value": "#0000ff"
            }
          }
        },
        {
          "mark": {"type": "point", "filled": true},
          "encoding": {
            "x": {
              "field": "net", 
              "type": "quantitative",
              "axis": {
                "title": "Number of accumulated games",
              }
            },
            "y": {
              "field": "rating", 
              "type": "quantitative",
              "axis": {
                "title": "Elo rating (0 = random play)"
              }
            },
            "color": {
              "field": "sprt", "type": "nominal", "scale": {"range": ["green", "red", "blue"]}
            },
            "tooltip": {
              "field": "hash", "type": "nominal"
            }
          }
        } 
      ]
    }
    var opt = {
      "width": 800,
      "height": 600,
      "actions" : {
        "export": false,
        "source": false,
        "editor": false
      }
    }
    vegaEmbed("#vis", yourVlSpec, opt);
  </script>
</body>
</html>

</pre>

**Comment by justinwong098** [comment]
Will you add more fields to the tooltip? Such as the Elo, and the number of accumulated games (in units of thousand games. e.g. 1090754 -> 1091).

**Comment by l1t1** [comment]
In my IE11, visit http://zero-test.sjeng.org/data/elograph.json can show data, it seems only graph has probem.

**Comment by isty2e** [comment]
For the tooltips, [vega-tooltip](https://github.com/vega/vega-tooltip) can provide advanced functions. I attach an example here.
[LZ_elo_plot.zip](https://github.com/gcp/leela-zero/files/1564598/LZ_elo_plot.zip)

**Comment by justinwong098** [comment]
@isty2e Yup. Your example is basically what I had in mind.
@l1t1 I found this link that shows that Vega is compatible with IE with one caveat. Maybe this is the issue? https://vega.github.io/vega/usage/#ie

**Comment by l1t1** [comment]
thanks @isty2e @justinwong098

**Comment by fishcu** [comment]
As someone who is red-green color blind (4% of population have it!), please consider using better colors for the graph! Maybe you can also change some of the dots into crosses, plusses, etc.? Some more tips here: http://blog.usabilla.com/how-to-design-for-color-blindness/

**Comment by isty2e** [comment]
Actually that’s one of the reasons I initially chose yellow for those points. What about grey then? I’m not perfectly sure if it would be perceptually pleasing for colorblind people though.

**Comment by evanroberts85** [comment]
gcp’s graph had interpolation, I think it helps it look much better, code and examples here:
https://vega.github.io/vega/examples/line-chart/

**Comment by marcocalignano** [comment]
@fishcu said it. I am one of the 4% and I cannot distinguish between green and red dots. 
I can help if you make suggestion I can tell you which I see and which no. 
Or maybe you do the "pass" + "line" in Green, the Red dots as "fail" and the blue as "???". Having the line thru the Green dots helps my brain to tell them apart from the red dots.

**Comment by billyswong** [comment]
What about keep blue and red as is and just change ??? to gray. I am not colorblind but I hope this will be easier than "tell them apart" by the line.

**Comment by marcocalignano** [comment]
Yeah, maybe it could work but I need to see it.

**Comment by isty2e** [comment]
With "natural" interpolation and grey color (I preferred darker one to default), i.e.,

```
          "mark": {
            "type": "line",
            "interpolate": "natural"
          },
...
          "color": {
            "field": "sprt", "type": "nominal",
            "scale": {"range": ["#404040", "red", "blue"]}
          },
```
it looks like the following. Is it okay?

![lz_plot_sample](https://user-images.githubusercontent.com/571680/34069734-37cfae98-e29a-11e7-8045-9e4fbb604965.png)

**Comment by marcocalignano** [comment]
I guess is better. Still have to concentrate thou.

**Comment by isty2e** [comment]
@marcocalignano There are some color schemes in ColorBrewer. Would you take a look at the color schemes [here](http://colorbrewer2.org/#type=qualitative&scheme=Set2&n=3) and what set of colors is comfortable for you?

**Comment by marcocalignano** [comment]
Unfortunately I need some example where the dots of different color are surrounded by white area because that is the real hard part! if green a read are close together and there is a bog red area in the same pic I can tell you which is red and which is green in out chart green and red dots are surrounded by white.

**Comment by isty2e** [comment]
Okay, what about this? They say it's colorblind friendly, but I'm not sure... By the way, changed the interpolation method from "natural" to "monotone", since it is somewhat better.

![s1](https://user-images.githubusercontent.com/571680/34069942-f5692eae-e29d-11e7-9caa-5c37b52acdcb.png)

**Comment by marcocalignano** [comment]
No the previous was better but maybe try to make a darker gray.

**Comment by isty2e** [comment]
A darker grey (#282828) version here:

![s2](https://user-images.githubusercontent.com/571680/34069974-47f10632-e29f-11e7-9136-d40876647bae.png)

You might try out yourself changing colors in line 75 and 52 of the following file, so if you happen to find a pleasing set of colors, let us know.

[elo.html.zip](https://github.com/gcp/leela-zero/files/1564699/elo.html.zip)

**Comment by marcocalignano** [comment]
I do not know how it look for you but this colors for the points are good for me"
["#59E817", "#C11B17", "blue"]}
The line can stay blue no problem.

**Comment by isty2e** [comment]
That looks okay, and colours seem that not that different from the previous one.

**Comment by marcocalignano** [comment]
to me they are!

**Comment by isty2e** [comment]
Yeah maybe due to the difference in brightness? Anyway we're both fine now :)

**Comment by roy7** [comment]
I will update to @isty2e new code later today when I am back home. He did the original sample I started working off of. Thanks for the color blindness feedback and everything. :)

**Comment by isty2e** [comment]
I tried to show only first 4 characters of hash in the tooltip, but it was not easy nor trivial. If this is impossible, would it be better to truncate the hash value in the jason, or provide a short hash as a field for this purpose?

**Comment by roy7** [comment]
@isty2e I can easily truncate the hashes in the json data itself.

http://zero-test.sjeng.org/view/player/elo.html

Has all of your work plus the colors @marcocalignano provided. 

@fishcu How do these colors look to you? I know there's a primary type of common color blindness, and then other types of uncommon color blindness, which have different effects on people's vision.

**Comment by isty2e** [comment]
@roy7 I think it is still safer to add another field, can be named "short_hash" or whatever, and then set tooltip options like:

```
    var tooltipOpt = {
      showAllFields: false,
      fields: [
        {field: "net", title: "Number of games"},
        {field: "rating", title: "Elo rating (0 = random play)"},
        {field: "sprt", title: "SPRT"},
        {field: "short_hash", title: "Hash"}
      ]
    };
```

We might have some use of hash field later, who knows.

**Comment by roy7** [comment]
If we need full hash later I can add it back in, in a few seconds. May as well save on the bandwidth while it isn't used. I'm showing it tooltips now with 6 letters.

**Comment by roy7** [comment]
Your copy had the data hard coded so I turned back on the data src= too. I think it's pretty much set atm?

**Comment by isty2e** [comment]
HASH can be Hash, with less capital letters? Now everything seems fine anyways once we are done with earlier matches.

**Comment by roy7** [comment]
Fixed. Guess I was looking at "SPRT" above it and went all caps, lol.

GCP dug up a bunch of old bad networks I might import into the system and run until SPRT fail as well. Then we can have historical data also tested and in here properly too!

**Comment by WhiteHalmos** [comment]
Wow, this looks great! Thank you all for your good work!

**Comment by roy7** [comment]
I'm think I'm going to stop calculating the prior game counts on the fly (was a quick solution for a Y axis since we had nothing stored), and actually enter all of the network data from [Andy Olsen's spreadsheet](https://docs.google.com/spreadsheets/d/1QhYWYQvXBhI5eHJm45fvf97CaV2rRmgrATwVgBFGKoU/edit#gid=806323235) since he has logged everything diligently since launch. That will make all of the data points (expect ELO) match GCP's chart and the spreadsheet exactly.

**Comment by roy7** [comment]
@isty2e Minor thing but the tooltip for final point on the line appears for the whole line if you point right at the line itself. Do you think we can show tooltips only for points and not for the line?

**Comment by Mardak** [comment]
@roy7 you can use different shapes similar to using different colors:
```js
vlSpec.layer[1].encoding.shape = {
  "field": "sprt", "type": "nominal",
  "scale": {"range": ["diamond", "triangle-down", "triangle-up"]}
}
```
![screen shot 2017-12-16 at 9 53 10 pm](https://user-images.githubusercontent.com/438537/34076994-b1a66fde-e2ab-11e7-869b-51e66b6aa322.png)

https://vega.github.io/vega-lite/docs/encoding.html#mark-prop

**Comment by roy7** [comment]
Do people like the marks @mardak suggested? I can pop those in place if so.

**Comment by billyswong** [comment]
I like the ??? stays circle, other two triangles are good.

**Comment by billyswong** [comment]
And I guess we can assume those recently failed networks share the same "training #" of the passed network submitted at nearly the same time?

**Comment by isty2e** [comment]
@roy7 Not sure, but probably not. The tooltip doesn't seem like being able to configured layer-specific, since it is bound to vlSpec.

**Comment by evanroberts85** [comment]
I think the circles look neater than the triangles. It would be better if
the training number for networks was in thousands, so 1105k rather than
1105000, which safari thinks is a telephone number.

**Comment by fishcu** [comment]
Thank you very much for the changes! I think the shapes introduced by @Mardak help a lot in reading the graph. The shape makes sense too (upwards trend, downwards trend, no trend). Vote to add that to the website. :)

**Comment by marcocalignano** [comment]
Can we reset the chart origin so the ELO reflects the real strength of the networks?

**Comment by BHydden** [comment]
I like the shape changes but would prefer either the current circle or a dash for neutral over the proposed diamond.

Also like @marcocalignano suggestion of changing the elo to reflect relative strength to a known system even if it is only ballpark.

**Comment by evanroberts85** [comment]
AlphaGo anchored with goratings by playing lots of games with Fan Hui (who
has a ranking on goratings). We can not do that. We could anchor with CGOS
instead by playing 400 games with GNU Go 3.7.11a?

**Comment by evanroberts85** [comment]
By convention, shapes used to plot the graph should be circles, the green and red shapes can be whatever.

**Comment by Mardak** [comment]
Oh, I was just giving an example of how to set the shapes for each of the 3. Personally, I would probably just make it easier to differentiate the green ??? and red FAIL for red/green colorblind:

<img width="922" alt="image" src="https://user-images.githubusercontent.com/438537/34081386-a230d526-e300-11e7-9faf-5427f4d3f600.png">

**Comment by nauzykaa** [comment]
For me it would be much nicer to name green as "neutral" instead of annoying "???".

**Comment by killerducky** [comment]
inconclusive (most accurate but long), unknown, TBD....

**Comment by barrtgt** [comment]
pending?

**Comment by Mardak** [comment]
"unsure" is probably the shortest that still makes sense for not-native-english speakers. Otherwise "vague" or "open" could be shorter.

**Comment by roy7** [comment]
Yeah I couldn't decide what to say so I put the ???.

**Comment by roy7** [comment]
@mardak Fails changed to triangle-down.

**Comment by killerducky** [comment]
@roy7 round Elo numbers to whole number?

**Comment by roy7** [comment]
Should I?

**Comment by roy7** [comment]
I guess I could round down to nearest 1000 to pretty it up. But we might also drop the 000s and move to a 1100K format anyway?

**Comment by killerducky** [comment]
Looks like you are talking about game numbers. I'm talking about Elo e.g. 3807 instead of 3807.72.

**Comment by roy7** [comment]
Ohh!

**Comment by roy7** [comment]
@killerducky Done

**Comment by isty2e** [comment]
You could also modify the tooltipOpt like:

```
      fields: [
        {field: "net", title: "Number of games"},
        {
          field: "rating", 
          title: "Elo rating (0 = random play)",
          **formatType: "number",
          format: ".0f"**
        },
        {field: "sprt", title: "SPRT"},
        {field: "hash", title: "Hash"}
      ]
```

There is no decimal mark this way :)

**Comment by roy7** [comment]
I  simply removed the decimals before printing the elo out as part of the data source. :)

**Comment by justinwong098** [comment]
Another small tweak: Can you add the change in score relative to the
previous best network, and add it to the tooltip? Similar to Andy Olsen's
Google Doc, under the column "Elo diff vs prev best".

**Comment by evanroberts85** [comment]
Once we are using the goratings.org scale used by google (which we can do
when we have enough games against GNU Go 3.8), It we be good to add dotted
horizontal lines showing the strengths of GNU Go, AlphaGo Lee and AlphaGo
Master, like google did for their charts.

Should be pretty easy to do with vega:
https://vega.github.io/vega/docs/marks/rule/
