### ISSUE TITLE
is LZ's MCTS a parallel MCTS?

### ISSUE THREAD

**Issue by ericyan71** [gcp/leela-zero#396]
hi, I think parallel MCTS is a difficult point, but very important, LZ's MCTS must be parallel, because I see  mutex here and there, I wonder what algorithm LZ's parallel MCTS used,  I'd appreciate if someone could tell me which paper LZ use.

thanks

**Comment by gcp** [comment]
LZ's MCTS will run parallel if multiple threads are enabled. The full tree search is parallelized, using virtual losses to avoid node contention.
