### ISSUE TITLE
Engine doesn't respect time_settings parameter

### ISSUE THREAD

**Issue by aTan-aka-Xellos** [gcp/leela-zero#4]
I've run leela-zero-0.1 version with next parameters:
--gtp --threads 4 time_settings 0 20 1 -w C:\Bots\leela-zero-0.1-win32\weights.txt --noponder
As I understand time_settings 0 20 1 means 1 bayomi, 20 seconds, 0 main time.
But engine always think 'Thinking at most 50.0 seconds...' as highlighted on screenshot.

Also behavior of --threads with 1, 2, 3, 4 value (my processor is 4 cores) is kinda strange and different than any other engine. I understand that it shouldn't behave the same way, but wondering why it happens.
- can't see direct relations between number of cores specified and core-load. for example threads 1 and threads  4 - difference in CPU load may be 10-20%
- this is the only engine which doesn't load CPU. The reason is that engine doesn't use Monte Carlo playouts?
- this is the only engine which use GPU load at 99% - neither usual leela neither other bots load GPU more than 80%
- almost no memory used (neither DRAM neither GPU)

This things are not very clear, why so different from other engines :)

![691 26-oct-17 10 54](https://user-images.githubusercontent.com/7886823/32041901-8990dede-ba3e-11e7-90b5-4a2083c3c947.jpg)

**Comment by gcp** [comment]
time_settings is a GTP command, not a command-line option. It has to be sent by the GTP interface. This is actually specifically pointed out in the README, "Usage" section. Configuring the time control for a GTP engine on the engine command-line is something that cannot possibly work correctly with the GTP protocol, and it's a mystery to me why some other engines even allow it.

I'll check if I can somehow make the engine error out if an unknown option is specified.

The engine is 99.9% limited on GPU power, so using multiple CPU cores won't do much unless the GPU is very fast and can't be fed by a single CPU core. (This might happen with smaller networks) All the time is spent evaluating very large neural networks.

For an explanation on how the engine works, please read the "Mastering the Game of Go without Human Knowledge" paper from DeepMind.

**Comment by yishn** [comment]
It's not problem to have a command line argument for setting an initial value for `time_settings` and allow GTP to override it if necessary, is it?
