### ISSUE TITLE
How to concatenate many SGF files in a single SGF file?

### ISSUE THREAD

**Issue by bclman** [gcp/leela-zero#40]
Are there any easy way to concatenate many SGF files in a single SGF file?

**Comment by gcp** [comment]
cat *.sgf > all.txt
    mv all.txt all.sgf

Works on any unix-like system. On Windows any unix-like shell should be able to do the same. Not sure how to do it with standard Windows commands. copy a.sgf+b.sgf+... works but not if you have thousands of files.

**Comment by zediir** [comment]
In powershell:

`Get-Content .\File?.txt | Set-Content .\Combined.txt`
