### ISSUE TITLE
Game Scoring bug?

### ISSUE THREAD

**Issue by billyswong** [gcp/leela-zero#400]
I was watching self-play games relayed on KGS. At the end of the game, Black resigned and White won. However KGS client estimated that Black should win by 2.5 points. I counted by hand and Black really should win. Is it just a bug of those OpenCL thing or other thing else? Because all "dead stones" had been cleared so there shouldn't be any miscalculation normally. A playout of "pass" should have told Black LZ that it will win immediately.

[Eidogo Link](http://eidogo.com/#lB9VKRVZ)

**Comment by killerducky** [comment]
I get W+18.5. KGS score estimator is bugged for area rules, don't use it. I'm not talking about it's usual badness, it is 100% broken for area rules. 

Also it's easier if you include a link to the kgs sgf file, or eidogo, instead of cut/paste text.

**Comment by billyswong** [comment]
Thanks for suggesting Eidogo. I recounted in gimp and it's 184 points for black. 184-7.5-(361-184)=-0.5. Yeah indeed black lost. It's crazy how come KGS client can be this bad. (Your program is doing territory scoring, so it's bugged in another way.)

**Comment by grolich** [comment]
Leela doesn't do Territory scoring. It uses Tromp Taylor scoring, which uses area scoring. (It actually uses some combination between Tromp Taylor and Chinese rules, but both are called area scoring).
