### ISSUE TITLE
when will leela zero self train win the best1 network?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#405]
I saw it beat many bots as
http://www.yss-aya.com/cgos/19x19/cross/LZ-HBest1-t1-p1600.html 
https://sjeng.org/zero/best_v1.txt.zip

**Comment by WhiteHalmos** [comment]
That is not a self-train network, best_v1.txt is supervised on human games.
See: https://www.reddit.com/r/cbaduk/comments/7kbrsl/lzhbest1t1p1600_human_supervised_learning_network/

**Comment by OmnipotentEntity** [comment]
The best_v1 network was trained with human data.
