### ISSUE TITLE
Uploading a match result multiple times

### ISSUE THREAD

**Issue by roy7** [gcp/leela-zero#406]
I'm not sure if it's someone testing something or what, but there's one specific client who uploads every result they get 4 times. I don't know if that's an autogtp bug or just a specific test someone is doing while they work on the client. :)

**Comment by killerducky** [comment]
Wasn't there a version at one time that had a problem where the random seed was the same for all threads?

**Comment by roy7** [comment]
I can see in my log though they were sent 1 match task, and uploaded back a match 4 times. They are only doing 1 task at a time. But every upload is 4 uploads. It's weird.

**Comment by ljn917** [comment]
Hope they are not on purpose #403

**Comment by marcocalignano** [comment]
@roy7 It is me. I am testing a new version of autogtp and I had this bug yesterday night (GMT+1).  I should have fixed it this morning. Maybe next time you check the IP Location if it is from "NetCologne GmbH" and the location is somewhere near Cologne Germany, then is very likely is me doing some experiment. But I mean no harm.

**Comment by roy7** [comment]
Wasn't hurting anything, I just happened to see it in the logs while I was testing. :)

**Comment by marcocalignano** [comment]
@roy7 I need you to check my last uploads: I sent and got the following: 
```
curl -F networkhash=3382a7d3e3d39b28891a262c0b371f0904888c763bec4124623307c3bd254339 -F clientversion=10 -F options_hash=16b7b7 -F random_seed=2036268488470619163 -F sgf=@3130b117f9644d458a28dc04e9b159b2.sgf.gz -F trainingdata=@3130b117f9644d458a28dc04e9b159b2.txt.0.gz http://zero-test.sjeng.org/submit

Game data 3e3a9993b2c8befe9e654aa4d17c7a2ed868cec2e938dd994f87148e068528d7 stored in database

curl -F networkhash=3382a7d3e3d39b28891a262c0b371f0904888c763bec4124623307c3bd254339 -F clientversion=10 -F options_hash=16b7b7 -F random_seed=2036268488470619163 -F sgf=@ad01a0ebec8e4708b976b6f97b8aa88d.sgf.gz -F trainingdata=@ad01a0ebec8e4708b976b6f97b8aa88d.txt.0.gz http://zero-test.sjeng.org/submit

Game data 3e3a9993b2c8befe9e654aa4d17c7a2ed868cec2e938dd994f87148e068528d7 stored in database

curl -F networkhash=3382a7d3e3d39b28891a262c0b371f0904888c763bec4124623307c3bd254339 -F clientversion=10 -F options_hash=16b7b7 -F random_seed=2036268488470619163 -F sgf=@a3f2e889d4fb4cbab39f4b1c116a37dd.sgf.gz -F trainingdata=@a3f2e889d4fb4cbab39f4b1c116a37dd.txt.0.gz http://zero-test.sjeng.org/submit

Game data 3e3a9993b2c8befe9e654aa4d17c7a2ed868cec2e938dd994f87148e068528d7 stored in database
```
Like you see I got the same answer even if the sgf where different. Can you have a look please?

**Comment by roy7** [comment]
I can when I get home from breakfast but how is your random seed the same for all 3?

**Comment by roy7** [comment]
I am going to guess your three sgf files are identical games?

**Comment by Ttl** [comment]
The random seed for those games is the same so they should be identical.

**Comment by marcocalignano** [comment]
Do we use the random seed or can I upload valid games without specifying that?

**Comment by roy7** [comment]
You can upload games without it, it's an optional field.

My assumption was if you are like doing offline games or something during a network outage, you'd generate your own random seed to use for each offline game.

**Comment by killerducky** [comment]
BTW there isn't any easy way for a user to recreate his own games because the random seed isn't stored locally. I was going to add it to the debug file I make but it might make sense to add it to the sgf file. And if we do add it to the sgf file I propose we just add the entire command line. 

This is valuable because if a user gets strange results we can ask them to rerun with various diagnostics turned on.

**Comment by marcocalignano** [comment]
@killerducky But if the seed is not specified at the command line it is generated by leelaz right?
If so can you write it in the debug file like that?
`rnd seed not specified at command line using : 447613`

**Comment by roy7** [comment]
I was thinking leelaz would always be given a seed, autogtp would make one if it needed one and then report it back to server like usual. (If you are generating a game without a fresh get-task selfplay that has a seed in it.)

**Comment by marcocalignano** [comment]
@roy7 How long before the next self-played game comes? Can I ask another URL so I can test this feature without waiting till all the matches are over?

**Comment by killerducky** [comment]
@marcocalignano I think it would be worth it to invest some time building some test infrastructure. Maybe a #ifdef that instead of calling the server creates a custom task of your own. And also skips the actual upload step. I've done this myself in an ad-hoc way to test autogtp debug file features.

**Comment by marcocalignano** [comment]
@killerducky I have to test the communication from the server and to the server so I cannot do that.

**Comment by roy7** [comment]
@marcocalignano http://zero-test.sjeng.org/get-task/0 will always return selfplay for now on.

**Comment by marcocalignano** [comment]
@roy7 thanks
