### ISSUE TITLE
what is the meaning of training in table of web page

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#408]
the values are all times of 1000,and first value is not equal to prior games

**Comment by l1t1** [comment]
the 1st value seems be 15000,not 0

**Comment by OmnipotentEntity** [comment]
Because there's a lag between when the network is trained and tested and released, other games come in from previous networks.

They had been reporting the number of games played when the network was released.  But it's more accurate to report the number of games played when the network was trained.  This also allows users to identify which games that the network was trained on.  Specifically, it's trained on (Training - 500k, Training].  This was not possible before.

**Comment by l1t1** [comment]
thanks

**Comment by roy7** [comment]
Moving forward with more automation we may not be able to easily store the # of training games a network was trained with, I manually input all of those numbers. But at least for the ones we did know I put in the exact figures. In the future the # of training games listed will be the # of games submitted at the time the network was uploaded. Not as accurate as actually knowing the # of training games, but more accurate than my prior "add up all prior networks games played" I started out with.

So the networks with even 1000s are where we had recorded data, moving forward networks without an even 1000s count will be the auto stored approximate numbers.

**Comment by billyswong** [comment]
@roy7 But manually type in a training # by the uploader for each time uploading a network should not be hard, should it?

**Comment by gcp** [comment]
"Manually typing in" is the opposite of automating.

**Comment by billyswong** [comment]
Or script/interface that submit new network together with a training count if the training process has been fully automated, doing training 24/7. I thought the training script do know the training count...

**Comment by roy7** [comment]
I only typed in the data for older networks which we had data for and needed numbers in there. Moving forward, it'll be set to the # of games in the system at time of upload. The training script doesn't actually know the # of total games that have been downloaded. It just takes in the input training examples, which are a rolling 300K game window. GCP was manually noting the # of games downloaded when doing the trainings by hand in the past.
