### ISSUE TITLE
Providing a Dockerfile

### ISSUE THREAD

**Issue by arnaudgo** [gcp/leela-zero#409]
Hello,

It would be nice to have a Dockerfile one could use on radeon or nvidia capable machines. It would ease the installation.

I'm facing with a problem for installing libboost-all-dev package on a workstation running under Debian etch. And it makes me think that if I could run leelazero in a container.

Arnaud

**Comment by arnaudgo** [comment]
Hello,

I meant Stretch (9.0), not Etch :-) So, the side note of the issue is that libboost-all-dev seems to be a broken package on Debian 9.0

Arnaud

**Comment by bood** [comment]
Added one in PR #441

**Comment by arnaudgo** [comment]
Thanks @bood it's actually this PR that made me check my issue again :) 
I just realized the computer I was trying to setup Leelazero on was non-OpenCL compatible. 
I won't go further with it. Still, I had a look at the PR again today and I can't see any Dockerfile ?

Arnaud

**Comment by bood** [comment]
It is definitely there
https://github.com/gcp/leela-zero/pull/442/files#diff-3254677a7917c6c01f55212f86c57fbf

**Comment by arnaudgo** [comment]
Thank you @bood and sorry :) for some reason I couldn't see it myself.

**Comment by gcp** [comment]
Dockerfile was merged.
