### ISSUE TITLE
Show time ago for the upload and test dates

### ISSUE THREAD

**Issue by Mardak** [gcp/leela-zero#411]
@roy7, here's some javascript that you could include on the page:

```js
// Largest value for each desired time unit
var TIME_UNITS = [
  [1000, "milliseconds"],
  [60, "seconds"],
  [60, "minutes"],
  [24, "hours"],
  [7, "days"],
  [52 / 12, "weeks"],
  [12, "months"],
  [Infinity, "years"]
];

/**
 * Convert some time delta in milliseconds into "ago" string with largest appropriate units.
 */
function deltaToAgo(delta) {
  if (Number.isNaN(delta)) {
    return "";
  }
  var unitIndex = 0;
  while (unitIndex < TIME_UNITS.length) {
    var divisor = TIME_UNITS[unitIndex][0];
    if (delta < divisor) {
      break;
    }
    delta /= divisor;
    unitIndex++; 
  }
  return delta.toFixed(1) + " " + TIME_UNITS[unitIndex][1] + " ago";
}

// Unit tests for deltaToAgo giving the expected output
for (var test of [
  [123, "123.0 milliseconds ago"],
  [1234, "1.2 seconds ago"],
  [12345, "12.3 seconds ago"],
  [123456, "2.1 minutes ago"],
  [1234567, "20.6 minutes ago"],
  [12345678, "3.4 hours ago"],
  [123456789, "1.4 days ago"],
  [1234567890, "2.0 weeks ago"],
  [12345678901, "4.7 months ago"],
  [123456789012, "3.9 years ago"],
  [1234567890123, "39.3 years ago"],
  [NaN, ""]
]) {
  console.log(deltaToAgo(test[0]) == test[1], test);
}

// Add an ago title to show on hover for each date <td>
Array.from(document.querySelectorAll("td")).forEach(function(td) {
  var match = td.textContent.match(/\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}/);
  if (match) {
    td.title = deltaToAgo(Date.now() - new Date(match[0] + ":00+0100"));
  }
});
```

Shows something like this (hover over the most recent start date):
<img width="204" alt="image" src="https://user-images.githubusercontent.com/438537/34083149-67b79220-e320-11e7-8283-321dce419ebc.png">

And the most recent upload date:
<img width="216" alt="image" src="https://user-images.githubusercontent.com/438537/34083152-81c90428-e320-11e7-99e5-ee520d286aa5.png">

And the oldest upload date:
<img width="340" alt="image" src="https://user-images.githubusercontent.com/438537/34083169-bab47902-e320-11e7-8e67-b1eb26166248.png">

At least works in Firefox and Chrome. Safari date parsing isn't great.

**Comment by Dorus** [comment]
Nice. Btw, up to a couple days or weeks, you might want to show the "xxx yyy ago" message by default and the actual time on mouse-over.

Much like how github does it with posting time. The post above is "3 hours ago" for me. I believe Js just replaces the actual date.

**Comment by Mardak** [comment]
@roy7 Here's an updated script with the new tooltip styles from https://github.com/gcp/leela-zero/issues/412#issuecomment-354657468. It will dynamically add/update the tooltip when hovering, so it will update from "13.4 minutes" to "13.5 minutes ago" for recent matches.

```js
// Largest value for each desired time unit
var TIME_UNITS = [
  [1000, "milliseconds"],
  [60, "seconds"],
  [60, "minutes"],
  [24, "hours"],
  [7, "days"],
  [52 / 12, "weeks"],
  [12, "months"],
  [Infinity, "years"]
];

/**
 * Convert some time delta in milliseconds into "ago" string with largest appropriate units.
 */
function deltaToAgo(delta) {
  if (Number.isNaN(delta)) {
    return "";
  }
  var unitIndex = 0;
  while (unitIndex < TIME_UNITS.length) {
    var divisor = TIME_UNITS[unitIndex][0];
    if (delta < divisor) {
      break;
    }
    delta /= divisor;
    unitIndex++; 
  }
  return delta.toFixed(1) + " " + TIME_UNITS[unitIndex][1] + " ago";
}

// Add an ago tooltip to show on hover for each date <td>
addEventListener("mouseover", function(event) {
  var td = event.target;
  var match = td.textContent.match(/^\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}/);
  if (td.nodeName == "TD" && match) {
    td.classList.add("tooltip");
    var tooltip = td.lastChild;
    if (tooltip.nodeName == "#text") {
      tooltip = td.appendChild(document.createElement("span"));
      tooltip.classList.add("tooltiptextright");
    }
    tooltip.textContent = deltaToAgo(Date.now() - new Date(match[0] + ":00+0100"));
  }
});
```

Firefox:
![screen shot 2018-01-01 at 10 42 43 am](https://user-images.githubusercontent.com/438537/34470190-cb338dd8-eee0-11e7-827e-950fdbbd39af.png)

Chrome:
![screen shot 2018-01-01 at 10 42 29 am](https://user-images.githubusercontent.com/438537/34470192-d0487306-eee0-11e7-8d68-ab22d7275696.png)

**Comment by roy7** [comment]
@mardak Added to test server! Thanks for making this so easy to plug in.

**Comment by Mardak** [comment]
Looks good on zero-test!
