### ISSUE TITLE
Zero biases in weight files

### ISSUE THREAD

**Issue by gaieepo** [gcp/leela-zero#413]
Haven't checked all but I have looked into four different weight files.

It seems that in those files all channel biases are remained 0.0, i.e. all line number 4N-1 (0<=N<=12).

223737476718d58a4a5b0f317a1eeeb4b38f0c06af5ab65cb9d76d68d9abadb6
3382a7d3e3d39b28891a262c0b371f0904888c763bec4124623307c3bd254339
6f274ab150b9c79a341cce67c97b9116a6fcf3b1a8c9a613f6f7a6709658750f
808ac5f35690774587d12f595d6e840801394ee30a26681e4712de1fc2acfb43

(I doubt this case occurs in many more weight files but since I haven't checked I am not absolutely certain about it)

I am not sure if whether I have made any mistakes here. Is it expected? I have not checked with code base yet. Hopefully someone can spot the reasons here.

**Comment by killerducky** [comment]
I don't know enough about Neural Nets to understand it, but see here:
https://github.com/gcp/leela-zero/blob/master/training/tf/tfprocess.py#L35

**Comment by gaieepo** [comment]
@killerducky that clears my doubt. indeed haven't looked into training section of the code. it seems all variables are initialized to zeros and no more updates after that. Thanks.

**Comment by gcp** [comment]
I defined the weights format before I remembered those weights are canceled out in the exact design of AlphaGo. There isn't really much overhead from them anyway.
