### ISSUE TITLE
SPRT Test bug?

### ISSUE THREAD

**Issue by ashinpan** [gcp/leela-zero#420]
As far as I know, the requirement for a new network to replace the incumbent one is to have 35 elos better. It means: if they play full 400 games, the new one should win at least 220 games. Then, when two networks are running very close and the reigning one has won 181 games, the candidate should *fail* instantly, for the latter has lost the chance to win 220 games. 

But in the match between dce293df (new) and 0eb8b23b (reigning), the match went on even though the latter had already won more than 181 games. 

I think this is a bug.

**Comment by gcp** [comment]
The match server sends out games to be played in parallel. It doesn't know in advance how many it will get back, and some can come back after the PASS/fail already happened.

**Comment by roy7** [comment]
SPRT doesn't know there will only be 400 matches though. I think the test is working as intended. The question is should we add another secondary fail situation if the current network hits 181 wins regardless of what SPRT says. But by that point you'll be in the 350+ total games ballpark, and all match games have already been send out. (Even on test server, we tend to have 50-80 matches outstanding at any given moment. On live server we'll blow through them super fast.)

**Comment by ashinpan** [comment]
At least, we can add the following condition at the match server side:

Among the games received back, if the candidate has not won 220 games but the reigning one has won 181 games, then the former should be declared *fail* and should be replaced by the next candidate to be sent out (I presume that you send out the next new network only when the present candidate fails).

**Comment by WhiteHalmos** [comment]
I think fewer custom parameters for corner cases will result in a more robust system. In this case as @roy7 mentioned, all the matches would have been sent out and it wouldn't save much if anything. It would just add needless complexity.

**Comment by gcp** [comment]
I don't think so. Assume we have 100 clients running matches. At 181 wins and 219 wins for current vs candidate respectively, there are still 100 games outstanding. You might as well end up with 181 vs 319. That's what the SPRT condition is for.

**Comment by roy7** [comment]
Just FYI on this specific case, SPRT popped off dce293 with 191 losses and 180 wins. At that point, 392 matches had been assigned already so another 21 should roll in over time but the last 8 weren't assigned out at all.

**Comment by ashinpan** [comment]
@gcp  I see your point. You let SPRT test override the 400 games rule of Deepmind, and I think this is reasonable. I will close the bug report.
