### ISSUE TITLE
small issue - the graph is off

### ISSUE THREAD

**Issue by Matuiss2** [gcp/leela-zero#427]
Its showing the newest networks wrongfully, the last one is over the 1.200.000 line of accumulated games on the graph when it should have been at 1.180.000.

**Comment by roy7** [comment]
I think 1.2M is the right edge of the map, it's just the number gets pushed left to fit within the graph borders. So the dot itself is in right place?

**Comment by grolich** [comment]
The scale the rest of the graph is displayed in definitely agrees with you @roy7. The right edge of the graph is the 1.2M mark

**Comment by Matuiss2** [comment]
oh boy I misread the graph I though the 1200000 line was the one before the edge....that's embarrassing, sorry
