### ISSUE TITLE
Best network match VS selfplay training discrepancy in the flow of the game

### ISSUE THREAD

**Issue by Cabu** [gcp/leela-zero#430]
Why selfplay matchs look like more random go but best network matches look like more like 'natural' go (at least in the beginning of the game)? This is not the first time I see that kind of discrepancy between the 2 type of plays. 

http://zero.sjeng.org/viewmatch/298fc2315f89fa5ad78863385a39ef9818728dc00f90a40660544cfca02b08eb
vs
http://zero.sjeng.org/view/6ed2d88391593b9ff6648e2f609ca420d5a7a1c9f1a595c48b8cb38e4bf95bb1

**Comment by isty2e** [comment]
> Match games are played at full strength (only 1600 playouts).
> Training games are played with some randomness in first 30 moves, and noise all game long.

It's even on zero.sjeng.org.
