### ISSUE TITLE
next: move timing is wrong

### ISSUE THREAD

**Issue by gcp** [gcp/leela-zero#431]
"10 game(s) (10 self played and 0 matches) played in 31 minutes = 191 seconds/game, 53 ms/move, last game took 339 seconds."

This is a fast machine but no way it gets a move in 53ms.

**Comment by SebastienFaurite** [comment]
Timing was wrong for me when I used nice on Windows under git bash

**Comment by SebastienFaurite** [comment]
OK now it is wrong also on Linux :

nice -19 ./autogtp

2 game(s) (2 self played and 0 matches) played in 15 minutes = 464 seconds/game, 40 ms/move, last game took 366 seconds.

And without nice -19 : it is the same

1 game(s) (1 self played and 0 matches) played in 10 minutes = 628 seconds/game, 27 ms/move, last game took 626 seconds.

**Comment by sethtroisi** [comment]
Recent code changes:
https://github.com/gcp/leela-zero/commit/168a8e49d9c37bd4bb1d1bd3f9e53e51844af886 and https://github.com/gcp/leela-zero/commit/4059d7e38bb43cc3c1d3433b48859c798eba2319

Also movesMade is being incremented at the end of games which is not as good as incrementing after each move (like it was before these two changes), because moves made in not yet complete games aren't counted so the value of ms/move will jump around more.

**Comment by marcocalignano** [comment]
@sethtroisi  So you want to give a pointer to Job so he can update m_movesDone in real time?

**Comment by killerducky** [comment]
I propose each thread calculate it's own ms/move, and then sum them, possibly with some special case code for when some threads haven't finished any games yet. After all threads have done 1 game this should be relatively stable.

**Comment by marcocalignano** [comment]
> possibly with some special case code for when some threads haven't finished any games yet

what do you mean?

**Comment by killerducky** [comment]
T0 900ms/move
T1 1000ms/move
T2 1100ms/move

1 / (1/900+1/1000+1/1000) = 321ms/move combined.

When one thread has undefined ms/move, you can't do a 1/X on that thread....

**Comment by sethtroisi** [comment]
@marcocalignano I liked that the old code gave a very stable ms/move time, Passing m_movesDone was the best way I could think of doing that, but I support any implementation that gives a stable timing (I could imagine potentially multiplying one thread's timing by number of threads)

@killerducky if you're going to sum a variables between the threads it seems like you should just sum the number of moves :)

**Comment by killerducky** [comment]
My proposal is more stable in the case you don't update moves live, only at end of games. Anyways it doesn't matter much.

**Comment by sethtroisi** [comment]
I see, one thread might have 100 moves / 120 seconds (from one game) combined with 200 moves / 230 seconds (from two games) in a 2nd thread.

then we get `(100 / 120 + 200 / 230) /2 = 851ms/move`
which is very close to `(100 + 200) / (120 + 230) = 857ms/move`

**Comment by marcocalignano** [comment]
But thus does not work: 
the first thread made 100 moves in 120 seconds while the second thread was making it moves so it actually did 100 + 100  moves in 120 second  + 100 move in 230 -120 seconds 
120 / 200 + 110 / 100  = 710 ms/move not counting all the threads that did not finished yet

**Comment by marcocalignano** [comment]
But so if you take the statistics of the master and the one from the next they differ right?

**Comment by marcocalignano** [comment]
I tested the ` m_management->incMoves() ` version and I got  2687 ms/move vs  1555 ms/move from the previous version. I will commit it in my /next branch and make a Pull request, but I ask you guys to test it against gcp/master and gcp/next to see if it is fix

**Comment by gcp** [comment]
Fixed in next.
