### ISSUE TITLE
next: segfault issue?

### ISSUE THREAD

**Issue by isty2e** [gcp/leela-zero#433]
Cloned the next branch after a series of commits and rebase today, and after building it on my mac fails to function properly. The log ends here:

> ...
> Engine has started.
> Infinite thinking time set.

I can execute leelaz and view heatmap, but for example, genmove b fails:

> Leela: genmove b
> Thinking at most 50.0 seconds...
> zsh: segmentation fault  ./leelaz --weights

**Comment by gcp** [comment]
Can you attach a debugger and get a stack trace?

**Comment by klmsj** [comment]
i have the seem problem,this is stack trace
![123](https://user-images.githubusercontent.com/16313502/34168318-37b8bb2a-e51f-11e7-9ec0-2ef9a6582dbd.png)

**Comment by klmsj** [comment]
![123](https://user-images.githubusercontent.com/16313502/34168518-a4bbee68-e51f-11e7-8070-c6fcf33ed36e.png)

**Comment by klmsj** [comment]
![234](https://user-images.githubusercontent.com/16313502/34168569-caa48400-e51f-11e7-870f-3ae910869bbb.png)

**Comment by isty2e** [comment]
I was having trouble making gdb working on mac due to code signing stuff. Hope @klmsj's results can help...

**Comment by gcp** [comment]
That should be enough to fix it, thanks.

**Comment by isty2e** [comment]
Seems like the bug is fixed. Closing this issue.
