### ISSUE TITLE
Is it useful to let current network play with prior ones?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#438]
from http://www.yss-aya.com/cgos/19x19/standings.html, It seems each new network are not obviously stronger than prior ones.

LZ-3382a7-t1-p1600 | 1664 | 105 | ######### | 1105
-- | -- | -- | -- | --
Odin_1.1.4_1T | 1661 | 340 | ######### |  
LZ-3ba928-t1-p1600 | 1635 | 101 | ######### | 1080
Aya783a_50 | 1618 | 26230 | ######### |  
LZ-2184b7-t1-p1600 | 1598 | 122 | ######### | 815
LZ-5bcb39-t1-p1600 | 1589 | 165 | ######### | 970
AyaBot | 1545 | 212 | ######### |  
LZ-1607db-t1-p1600 | 1507 | 110 | ######### | 890
LZ-96bf20-t1-p1600 | 1495 | 131 | ######### | 920
LZ-e671af-t1-p1600 | 1493 | 101 | ######### | 1035
LZ-d11131-t1-p1600 | 1487 | 110 | ######### | 1070
LZ-251b7c-t1-p1600 | 1483 | 110 | ######### | 1050
LZ-fe7a6c-t1-p1600 | 1476 | 169 | ######### | 955
LZ-4701bb-t1-p1600 | 1472 | 106 | ######### | 1000
LZ-eebb91-t1-p1600 | 1456 | 110 | ######### | 860
LZ-a0d353-t1-p1600 | 1449 | 174 | ######### | 945

I have an idea to let x play with x-1,x-2,x-10 ..,each play 10 matchs or more to the verify the elo value is right.

**Comment by roy7** [comment]
Remember this list is more accurate:

http://www.yss-aya.com/cgos/19x19/bayes.html

**Comment by killerducky** [comment]
@WhiteHalmos is running them. I am collecting the results in my spreadsheet. Ratings of early networks are dominated by noise from winning by luck when GnuGo times out. Starting from 3ba92804 the results look to be stabilizing, but they still have lots of noise. It will make more sense when we can beat the buggy bots like GnuGo.

Bayes Elo starting from 3ba92804:
1430
1485
1507
1553

**Comment by l1t1** [comment]
![2017-12-20_120350](https://user-images.githubusercontent.com/23301704/34190824-eabe96be-e57d-11e7-8db2-83becdd7b452.png)
I copied the data from Bayes, the long trend is right

**Comment by isty2e** [comment]
By the way, would running a number of LZ versions cause an inflation of CGOS ratings? I think it would hardly be the case for BayesElo, but for non-Bayesian ratings, I feel like it can be problematic somehow.

**Comment by killerducky** [comment]
GnuGo is anchored at 1800 in both rating systems to prevent that.

**Comment by isty2e** [comment]
In the long term, yes, the ratings will be properly set when the whole system reaches equilibrium, but short-term effects can be non-negligible. An extreme example would be the case where only several random players and a GNUGo anchor.

**Comment by gcp** [comment]
The errors on the CGOS ratings are very big, as you can see in the bayeselo calculation.
