### ISSUE TITLE
End game low win rate on both sides, makes many wrong resigns

### ISSUE THREAD

**Issue by earthengine** [gcp/leela-zero#443]
http://eidogo.com/#1ixhbuQvd

The above game, I have tested the position with the latest network 657f91c7, either played black or write, the estimated win rate are less than 1%, makes it resign when it shouldn't be.

Suggestion: have the win rates normalised so it sum up to 100%.

or, in the resign logic, use normalised win rates instead.

**Comment by gcp** [comment]
This isn't possible because the win rate is only given for the side to move.

Also this is completely pointless. It has to learn how to evaluate correctly.
