### ISSUE TITLE
Matches submitted with no movescount

### ISSUE THREAD

**Issue by roy7** [gcp/leela-zero#447]
Since the # of times I'll come in a bit under the requested # of matches felt odd, I added a lot more debug logging. I saw a client try to submit a match result, but the movescount was missing (so the server rejected it and sent them an error message.)

I'll keep logging to see if it happens more, or if I see any other different sort of failures.

Maybe it's just someone on a very old /next that doesn't send movecounts to the server?

@marcocalignano Is there ever a time movescount won't be sent to the server, that isn't an error on autogtp's end?

Actually, yes, every match submitted by that specific client is missing this parameter. I'm guessing they need to upgrade. :)

**Comment by marcocalignano** [comment]
@roy7 I think It is a bug fro mthe last pull request.I see if I can find a fast fix

**Comment by marcocalignano** [comment]
@roy7 is there an URL for matches only?

**Comment by roy7** [comment]
No sorry but I'll queue a bunch more up!

**Comment by marcocalignano** [comment]
Match data a142377a06d7f95df8745bf95293711268fba374dbdc1b1d9f1afc53af34a404 should have come with moves 203 right?

**Comment by roy7** [comment]
That one did upload correctly. :) (Most do, but some clients keep submitting matches with zero movescount.)

**Comment by marcocalignano** [comment]
@roy7 my last pull request was buggy I push the fix and make another PR! Good Night!

**Comment by roy7** [comment]
Thanks!

**Comment by roy7** [comment]
Fixed. https://github.com/gcp/leela-zero/pull/448

**Comment by killerducky** [comment]
How can I tell if my client has the problem or not? Does the server let the client know when there is a bad upload, and does the client error out when that happens?

**Comment by roy7** [comment]
@killerducky Every time you upload a match you get a result from the server. It'll say something like "match <hash> uploaded", or an error message like "No movescount provided".

**Comment by roy7** [comment]
I've still got 1 fast client who never provides movecounts with match submissions. @marcocalignano Is it time/safe to increase the required version on test server for get-task do you think? Maybe we can force them to update their /next branch. :)
