### ISSUE TITLE
why restart when Best Network is donwloaded?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#449]
Writing ecb11ea8d19542f3b109a39ca658f420.sgf
Dumping ecb11ea8d19542f3b109a39ca658f420.txt
20 game(s) played in 3105 minutes = 9316 seconds/game, 26698 ms/move, last game took 10674 seconds.
curl.exe -F networkhash=657f91c714d41ea1d0cf86ec5c2f1e69650cff3ee551dcf046b0062e4a285010 -F clientversion=8 -F sgf=@ecb1
1ea8d19542f3b109a39ca658f420.sgf.gz -F trainingdata=@ecb11ea8d19542f3b109a39ca658f420.txt.0.gz http://zero.sjeng.org/sub
mit
Game data c7dbfb57240fe7f90ef46f97e0da027c97d653f0f47cd68e4cd9194f765464d8 stored in database
<b>
Best network hash: 6140dc2e8327c5099b3ccd6d6faff8aa42299e33c807305495077af2f95a0934
Required client version: 8 (OK)
curl.exe -s -O -J -w %{filename_effective} http://zero.sjeng.org/best-network
Curl filename: 6140dc2e8327c5099b3ccd6d6faff8aa42299e33c807305495077af2f95a0934.gz
Net filename: 6140dc2e8327c5099b3ccd6d6faff8aa42299e33c807305495077af2f95a0934
Stopping engine.
./leelaz.exe -r 1 -g -t 1 -q -d -n -m 30 -w 6140dc2e8327c5099b3ccd6d6faff8aa42299e33c807305495077af2f95a0934 -p 1600 --n
oponder
Engine has started.
Infinite thinking time set.
1 (E17) Best Network has changed: restarting.
Stopping engine.
</b>
./leelaz.exe -r 1 -g -t 1 -q -d -n -m 30 -w 6140dc2e8327c5099b3ccd6d6faff8aa42299e33c807305495077af2f95a0934 -p 1600 --n
oponder
Engine has started.
Infinite thinking time set.
1 (D11) 2 (R16) 3 (D4) 4 (C4) 5 (Q17) 6 (Q16) 7 (D16) 8 (D5) 9 (Q4) 10 (Q3) 11 (E5) 12 (P17) 13 (P16) 14 (Q18) 15 (R17)

**Comment by gcp** [comment]
I think it's to prevent confusion in the client which network the games were played with, as well as getting games in with the best network ASAP.

**Comment by jjoshua2** [comment]
Does this mean that it's useless to contribute with a slow PC that takes 2 hours+ per game? Or is it actually better than nothing.

**Comment by marcocalignano** [comment]
The network is change maybe once every two days. So it is no problem even with a slow computer ti contribute. This "problem" is obsolete in the new next branch, and for this reason (and probably laziness) I didn't implement it better. Actually it was reported as a bug and fix before the release. I hope soon there will be a new release and the problem will just go away.
