### ISSUE TITLE
Spread the word

### ISSUE THREAD

**Issue by marcocalignano** [gcp/leela-zero#46]
Since looking at the statistics on the server there are 44 clients sending games at the moment. I was thinking to tell around about this project. I might have access to a big base of Go player. I might be able to contact someone on youtube that can promote our project. What I want to know is if I am allowed to do it.
Second would be really cool if the last autogtp version would be compiled under Windows and put on GitHub for downloading.

**Comment by lane-westlund** [comment]
There was already a post on the baduk subreddit, but I think we'll need something a bit easier to setup and run before we could get wider traction.

**Comment by gcp** [comment]
The current autogtp etc still point to the test server. I would rather not spread the word until we are confident that we're ready for a wider audience - but I think we will be very soon (matter of days). I fixed one of the last bugs in the training data recording yesterday, autogtp appears to be working reasonably, and dumping data from the server DB seems to work.

**Comment by Marcin1960** [comment]
When you are ready for a wider audience, I will spread the word in Polish, Russian and Czech sites.

**Comment by Alderi-Tokori** [comment]
I'll be able to spread the word to my club, which could potentially bring in a few more people, but I agree with lane-westlund that at some point a precompiled leelaz and autogtp for windows will really allow for a wider audience (most people would be fine with running an instance that's easy to set-up, but wouldn't bother/wouldn't know how to install all the dependencies themselves).

**Comment by gcp** [comment]
There are binaries for Windows up now.

**Comment by Geforce8472** [comment]
If you could somehow wrap this code up in a BOINC project there's a lot of crunchers out there that would gladly help you out with this.

**Comment by betterworld** [comment]
If you want to reach a large number of Go enthusiasts, you need to put this on Chinese, Korean and Japanese sites. Ideally the instructions should also be translated.

**Comment by roy7** [comment]
@gcp If it's useful for you, OGS uses the tool Pootle http://pootle.translatehouse.org/ for their community translations of the web site. Could be a way to let other people translate Leela/LeelaZ/autogtp into Korean, Chinese, and Japanese for you. Maybe even the Leela GUI and your web site, if you wanted to take it that far.
