### ISSUE TITLE
Keep away from bad chess advice

### ISSUE THREAD

**Issue by yxwsbobo** [gcp/leela-zero#460]
Do not use single PC training and upload

pc get a chess state from server, training one step and upload ,that's all. next training user new chess state

one chess step is a task, server send current chess state to client, pc client is only compute next step and return

I'm not good at English, forgive me

**Comment by kimitsu** [comment]
Why not use single PC training and upload?

server busy, must control each chess. if pc client is only compute next step, cannot use old think, play chess long

server also compute result and train. and, bad people play bad chess, hard to find. all chess become bad
