### ISSUE TITLE
why download the new network, still self-play old one?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#461]
Score: W+112.5
Winner: white
Writing e2bc72c9e7e74aa6919e5763ea9d3a52.sgf
Dumping e2bc72c9e7e74aa6919e5763ea9d3a52.txt
24 game(s) played in 4370 minutes = 10925 seconds/game, 29988 ms/move, last game took 46058 seconds.
curl.exe -F networkhash=6140dc2e8327c5099b3ccd6d6faff8aa42299e33c807305495077af2f95a0934 -F clientversion=8 -F sgf=@e2bc
72c9e7e74aa6919e5763ea9d3a52.sgf.gz -F trainingdata=@e2bc72c9e7e74aa6919e5763ea9d3a52.txt.0.gz http://zero.sjeng.org/sub
mit
Game data 9ef422b5cac39e95e2ad33cdee34ec21b46bef95b7d9f78295a5d97259f370c0 stored in database
Best network hash: 7ba9d22c1e095aaf856d9a19b858b7828035b8fb3268990e9d91287d00346bac
Required client version: 8 (OK)
curl.exe -s -O -J -w %{filename_effective} http://zero.sjeng.org/best-network
Network connection to server failed.
NetworkException: Curl returned non-zero exit code 18
Retrying in 30 s.
Best network hash: 7ba9d22c1e095aaf856d9a19b858b7828035b8fb3268990e9d91287d00346bac
Required client version: 8 (OK)
curl.exe -s -O -J -w %{filename_effective} http://zero.sjeng.org/best-network
Curl filename: 7ba9d22c1e095aaf856d9a19b858b7828035b8fb3268990e9d91287d00346bac.gz
<b>Net filename: 7ba9d22c1e095aaf856d9a19b858b7828035b8fb3268990e9d91287d00346bac</b>
Stopping engine.
./leelaz.exe -r 0 -g -t 1 -q -d -n -m 30 -w <b>6140dc2e8327c5099b3ccd6d6faff8aa42299e33c807305495077af2f95a0934</b> -p 1600 --n
oponder
Engine has started.
Infinite thinking time set.
1 (Q4) 2 (C5) 3 (N11) 4 (E17) 5 (N8) 6 (C17) 7 (R17) 8 (R5) 9 (R4) 10 (S4) 11 (R9) 12 (R15) 13 (A4) 14 (R3) 15 (F14) 16
(Q5) 17 (P4) 18 (P5) 19 (O4) 20 (Q17) 21 (O16) 22 (R16) 23 (S3) 24 (R2) 25 (S5) 26 (T4) 27 (T3) 28 (O5) 29 (T5) 30 (F7)
31 (N4) 32 (D3) 33 (Q13) 34 (O9) 35 (C4) 36 (D4) 37 (D5) 38 (O8) 39 (C3) 40 (C6) 41 (D2) 42 (E2) 43 (C2) 44 (N7) 45 (E3)

**Comment by gcp** [comment]
Looks like a bug but given the AutoGTP rework in next it's hard to say if this was already fixed or not.

**Comment by marcocalignano** [comment]
Since I do not see the output like in #449 something like "Best Network has changed: restarting." Or you are using an older client or your network was not properly downloaded.
