### ISSUE TITLE
A big thank you for being FOSS

### ISSUE THREAD

**Issue by sethtroisi** [gcp/leela-zero#462]
I'm really excited by this project and passionate about helping out.
I know that it takes a lot of effort to review all the pull requests and issues and I just want to say "thank you".

Thank you for accept pull requests.
Thank you for engaging in discussion about the various ideas in this project.
Thank you for taking the time to provide pointers and links to people wanting to learn.
Thank you for making the data available.
Thank you for making this project open source!

**Comment by marcocalignano** [comment]
YES!!!

Thank you also for contributing.
Thank you for bug fixing.
Thanks you for testing.
