### ISSUE TITLE
How to use caffemodel or tensorflow model in the program

### ISSUE THREAD

**Issue by qinxianyuzi** [gcp/leela-zero#463]
I used tensorflow to train the sgf files but I have no idea how to use the models. I guess the framework you use maybe not caffe or tensorflow.

**Comment by gcp** [comment]
The TensorFlow code writes out a weights file in a .txt and that can be loaded by Leela Zero.

Leela Zero uses custom OpenCL code for the DCNN.

**Comment by qinxianyuzi** [comment]
year, I see. Thank you very much.
