### ISSUE TITLE
Providing release tarballs with checksums and/or PGP signatures

### ISSUE THREAD

**Issue by arnaudgo** [gcp/leela-zero#465]
Hello,

What about providing every release with one checksum and/or PGP signature ?

Both serving different purposes, and even more because it's a distributed computing software, users do care to run the right binary (or compile the right sources) on their computer.

And besides the fact a limited community gets interested in leelazero, the distributed model makes it an interesting target. Probably not a threat for today, but well.... 
shaNsums might be useful.

Arnaud

**Comment by l1t1** [comment]
if we download them here, they would not be fake.

**Comment by arnaudgo** [comment]
Well, I'm not the one who knows better what the risk is and what the return of investment would be.
Providing either checksums for integrity or pgp signatures for authentication is not a big deal.
And you cannot control who mirrors what and where one downloads leelazero from... And, many people are not aware it's better to download from here. 
Anyway... as any feature request, it will have to be qualified :) 

Arnaud

**Comment by gcp** [comment]
HTTPS downloads from github are secure. If people download from other places they should expect to get malware.
