### ISSUE TITLE
glad to see 7ba9d2 Crushing challengers and gnugo

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#467]
2017-12-22 12:14 3437d438 VS 7ba9d22c 24 : 14 (63.16%) 38 / 400   
2017-12-22 10:06 3ce38532 VS 7ba9d22c 191 : 205 (48.23%) 396 / 400 fail 
2017-12-22 07:59 e062e3b3 VS 7ba9d22c 10 : 90 (10.00%) 100 / 400 fail 
2017-12-22 06:56 8e1d6f0b VS 7ba9d22c 11 : 93 (10.58%) 104 / 400 fail 
2017-12-22 04:47 0322f594 VS 7ba9d22c 64 : 98 (39.51%) 162 / 400 fail 
2017-12-22 02:40 ebb8644a VS 7ba9d22c 5 : 55 (8.33%) 60 / 400 fail 
2017-12-22 00:32 1a23a299 VS 7ba9d22c 53 : 90 (37.06%) 143 / 400 fail 
2017-12-21 22:23 3d86587c VS 7ba9d22c 270 : 228 (54.22%) 498 / 400   
2017-12-21 21:19 e033a3f7 VS 7ba9d22c 99 : 153 (39.29%) 252 / 400 fail 
2017-12-21 19:12 66cdeb92 VS 7ba9d22c 16 : 112 (12.50%) 128 / 400 fail 

http://www.yss-aya.com/cgos/19x19/cross/LZ-7ba9d2-t1-p1600.html

gnugo-3.8 1949 4 / 5 80.00 
gnugo-3.9.1 1926 1 / 1 100.00 
Gnugo-3.7.10-a1 1800 3 / 5 60.00

**Comment by evanroberts85** [comment]
Many of those games against GNU go were “won” on time, due to GNU Go getting confused by Leela trying to escape a ladder.

**Comment by WhiteHalmos** [comment]
Even removing the wins from time, here are the matchups:
gnugo-3.8 3/4 75%
gnugo-3.9.1 2/2 100%
Gnugo-3.7.10-a1 1/3 33%

Far from statistically significant, but quite nice to see.

**Comment by grolich** [comment]
Given that just a little while ago the results were 100-0 against LZ, it's definitely nice to see.
Would be even nicer to see the results of a larger sample.

Definitely seems like it's heading in the direction we want it...

For other hopefully good news regarding DeepMind's results being reproducible:
A week and a half ago David Silver was talking about the AlphaGo / The newest  AlphaZero results.
During the talk he was asked if they only had the one experiment they showed - and he answered "no", they had several, and the results were "very reproducible". 

At least that's a bit more reassurance than we had to go on (if still a bit vague...)

**Comment by killerducky** [comment]
I think it would be more accurate to count all LZ wins on time vs gnugo as wins for gnugo. Because every one of those I saw was a ladder being played out and a winning game for gnugo.

**Comment by gcp** [comment]
You can avoid those crashes by using GNU Go 3.8 compiled in 32-bits mode. 

```
leelaz-7ba9 v gnugo-l5 (43/1000 games)
board size: 19   komi: 7.5
              wins              black         white       avg cpu
leelaz-7ba9     12 27.91%       5  22.73%     7  33.33%    294.99
gnugo-l5        31 72.09%       14 66.67%     17 77.27%     80.52
                                19 44.19%     24 55.81%

leelaz-7ba9 v gnugo-l10 (42/1000 games)
board size: 19   komi: 7.5
              wins              black         white       avg cpu
leelaz-7ba9      9 21.43%       5  23.81%     4  19.05%    343.08
gnugo-l10       33 78.57%       17 80.95%     16 76.19%    250.45
                                22 52.38%     20 47.62%

```

Note no void games.

**Comment by l1t1** [comment]
thanks
