### ISSUE TITLE
if winrate of 3437.... reach 55% when games over 440,will it be selected as best?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#469]
Start Date	Network Hashes	Wins / Losses	Games	SPRT
2017-12-22 14:23	66b3d1fb VS 7ba9d22c	9 : 57 (13.64%)	66 / 400	fail
2017-12-22 12:14	3437d438 VS 7ba9d22c	243 : 203 (54.48%)	446 / 400	 
20

**Comment by Dorus** [comment]
247 : 208 (54.29%) | 455 / 400
-- | --


At 455 games it needs 249 wins (54.7%) but it only got 247 wins (54.29%). To be promoted with 54.29%, it would need like 550 games. This is all based on having 2stdevs above the average, that is 55% at 400 games but i'm not sure if the server has implemented the calculation for >400 games.

**Comment by roy7** [comment]
The server promotes off the sprt test so it will work for any number of games that meet the condition.

**Comment by Dorus** [comment]
252 : 209 (54.66%)

My math could be off (by 1?) but shouldn't this one pass the SPRT test?

If it does really only need 1 more. Could you schedule some extra games @roy7 :D

**Comment by roy7** [comment]
7ba9 is the king, baby! Long live the king!

**Comment by isty2e** [comment]
@Dorus It doesn't. 

@roy7 I'm not a big fan of monarchy :)

**Comment by Dorus** [comment]
@isty2e I guess my math is off then. Do you have the correct math handy somewhere?

If even wend up another win. Still no pass.


255 : 210 (54.84%) | 465 / 400
-- | --

**Comment by isty2e** [comment]
@Dorus #378 contains JS implementations by @roy7 and @sethtroisi, so please take a look at them.

**Comment by roy7** [comment]
@Dorus Here's my code and results.

> function LL (x) {
>     return 1/(1+10**(-x/400));
> }
> 
> function LLR(W, L, elo0, elo1) {
>     if (W==0 || L==0) return 0;
> 
>     var N = W + L;
>     var w = W/N, l = L/N;
>     var s = w;
>     var m2 = w;
>     var variance = m2-s**2;
>     var variance_s = variance / N;
>     var s0 = LL(elo0);
>     var s1 = LL(elo1);
> 
>     return (s1-s0)*(2*s-s0-s1)/variance_s/2.0;
> }
> 
> function SPRT(W,L,elo0,elo1)
> {
>     var alpha = .05, beta = .05;
> 
>     var LLR_ = LLR(W,L,elo0,elo1);
>     var LA = Math.log(beta/(1-alpha));
>     var LB = Math.log((1-beta)/alpha);
> 
>     console.log(LLR_ + " " + LA + " " + LB);
> 
>     if (LLR_ > LB) {
>         return true;
>     } else if (LLR_ < LA) {
>         return false;
>     } else {
>         return null;
>     }
> }
> 
> console.log("255 210: " + SPRT(255, 210, 0, 35));
> console.log("256 210: " + SPRT(256, 210, 0, 35));
> console.log("257 210: " + SPRT(257, 210, 0, 35));
> console.log("258 210: " + SPRT(258, 210, 0, 35));

2.194920951893808 -2.9444389791664403 2.9444389791664403
255 210: null
2.2920578859345406 -2.9444389791664403 2.9444389791664403
256 210: null
2.3892832863462403 -2.9444389791664403 2.9444389791664403
257 210: null
2.4865987645043335 -2.9444389791664403 2.9444389791664403
258 210: null

**Comment by Dorus** [comment]
If you put a four space indentation or put
\`\`\`Js
code
\`\`\`
it'll format better :)

```Js
function LL (x) {
  return 1/(1+10**(-x/400));
}

function LLR(W, L, elo0, elo1) {
  if (W==0 || L==0) return 0;

  var N = W + L;
  var w = W/N, l = L/N;
  var s = w;
  var m2 = w;
  var variance = m2-s**2;
  var variance_s = variance / N;
  var s0 = LL(elo0);
  var s1 = LL(elo1);

  return (s1-s0)*(2*s-s0-s1)/variance_s/2.0;
}

function SPRT(W,L,elo0,elo1)
{
  var alpha = .05, beta = .05;

  var LLR_ = LLR(W,L,elo0,elo1);
  var LA = Math.log(beta/(1-alpha));
  var LB = Math.log((1-beta)/alpha);

  console.log(LLR_ + " " + LA + " " + LB);

  if (LLR_ > LB) {
      return true;
  } else if (LLR_ < LA) {
      return false;
  } else {
      return null;
  }
}
```

Anyway i tried this code and it seems to be more strict than 55% at 400 games:
```
229 180 null
230 180 true
```

It requires 230/410=56.1% instead of 220/400=55% wins. That probably explains why my math was off, i assumed a 55% win at 400 games was a pass.
(That said this SPRT is probably correct. Because you allow early SPRT pass, you need to be slighly more strict near the end to get the same 95% confidence.)

**Comment by roy7** [comment]
Wow that's an awesome tip @dorus! Thanks!

**Comment by roy7** [comment]
The new net started out 5-0 and then on to like 9-1 I think, so I was all ready to say the king is dead... then next thing I know it's down under 55%. This is why SPRT is in charge and not me! Haha.

**Comment by isty2e** [comment]
By the way, recent suspicions led me to an idea that it would be better to check the validity of match games, since it is much easier to poison them and doing so is an effective way of stagnating things. I don't think that is happening right now, but better to prepare for it.

**Comment by Dorus** [comment]
9-0 should be a SPRT pass, but this SPRT function is hard wired to reject zero loss results, so the quickest SPRT win is 11-1 :)

  | 21 : 21 (50.00%)
-- | --


Unbelievable that a 9-1 result changed into a 21-21 result. Could be random luck but i suspect this network found a way to win early. Did it discover ladder wins??? 

Well, look at move 15-24!! http://zero.sjeng.org/viewmatch/ab7d95f604ae1d8aac93e1ffca6ec9438a907cc653c8330c1663f56cc43dac1b?viewer=wgo

**Comment by barrtgt** [comment]
You know that seems to be a common trend, at least whenever I watched, when a network looks very good at the beginning then declines over time.

**Comment by Marcin1960** [comment]
> @roy7 The new net started out 5-0 and then on to like 9-1 I think, so I was all ready to say the king is dead... then next thing I know it's down under 55%. This is why SPRT is in charge and not me! Haha.

OK, just to be sure LeelaZeroT / 3437d438 just started game on KGS against 4 kyu ayabot001.

**Comment by arnaudgo** [comment]
I'm afraid I'll be complete out off topic but if so, it's still peripheral.

Would it make sense to make play, from times to times, the strongest net of the moment against one of the weakest to see if the winning rate is significantly above ?

Giving an example of my words:

2017-12-16 06:01  a1151640 VS 1ac2638d | 135 : 18 (88.24%)
Following my suggestion would mean making 7ba9d22c play against 1ac2638d and see if it can reach, for example 100% of winning rate.

Is that kind of sanity check worth to ?

Arnaud

**Comment by Dorus** [comment]
@arnaudgo Download both networks, start up sabaki or any other gtp capable go gui and hook up both networks. Then let them play against eachother.

I've done that with a couple networks before, mostly to test if the new networks are stronger even with lower playouts, and i can tell you even at 120 playouts they defeated older networks at 1600 playouts :-)

**Comment by arnaudgo** [comment]
@Dorus yes, I think I'm able to do so. I was asking about that kind of systematic test ... Is it stupid ? Does it make sense ? 
I haven't looked at the sources and I have just overlooked the Nature publication. And of course, my knowledge of machine learning is quite limited :)

Arnaud

**Comment by Dorus** [comment]
> 7ba9 is the king, baby! Long live the king!

2017-12-22 19:45 | aaa33e89 VS 7ba9d22c | 136 : 90 (60.18%) | 226 / 400 | PAS
-- | -- | -- | -- | --

[The king is dead. Long live the king!](https://en.wikipedia.org/wiki/The_king_is_dead,_long_live_the_king!)

**Comment by l1t1** [comment]
thank all of you

**Comment by marcocalignano** [comment]
I would like to smoke one of this now!!!! 
http://top25.cigaraficionado.com/2015/the-king-is-dead-the-last-payday/
