### ISSUE TITLE
why the loser b9ec.. can challege next king?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#470]
tart Date	Network Hashes	Wins / Losses	Games	SPRT
2017-12-22 21:25	b9ec1bf1 VS aaa33e89	0 : 2 (0.00%)	2 / 400	 
2017-12-22 20:55	b9ec1bf1 VS 7ba9d22c	150 : 174 (46.30%)	324 / 400	fail
2017-12-22 19:45	aaa33e89 VS 7ba9d22c	150 : 99 (60.24%)	249 / 400	PASS

**Comment by gcp** [comment]
Bug in the match issuing. AFAIK this happened because all matches for aaa33 were already outstanding when b9ec1 got uploaded.

**Comment by roy7** [comment]
Is this really considered a bug though? If so, should a null network2 not start a match vs best network until all prior matches have met their quota of games to play? Basically null network2 means "play current best network when match starts", so it wasn't really a bug. Just not working as expected if we have different expectations. :)
