### ISSUE TITLE
why the winrate is 0 after 46 games

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#475]
2017-12-23 11:46 3efbdc20 VS 30f49ac5 0 : 46 (0.00%) 46 / 400   

if 3dfb is taken after 30f4, it should has similar elo as  30f4 

now it become

2017-12-23 11:46 3efbdc20 VS 30f49ac5 2 : 64 (3.03%) 66 / 400 fail 

it's still very strange

**Comment by MartinDevelopment** [comment]
Training a nn is like luck, sometimes you're lucky and it because a lot better and sometimes you are unlucky and it because a lot worse.

**Comment by evanroberts85** [comment]
First test in a new training run (3efb the first from 1.319m games) generally does very badly, no one has a solid explanation why.
