### ISSUE TITLE
Possible scoring problem

### ISSUE THREAD

**Issue by fsparv** [gcp/leela-zero#477]
Score at the end of this game should be B+353.5, shouldn't it? There are zero live white groups, and so under chinese scoring B gets every point (361) and white gets 7.5 komi yet Leela scored it B+283.5

http://zero.sjeng.org/view/8a083d3cc53d0439216813dc7f0c86463ea92ca3e11597d8866fe5fbd0ba3853?viewer=wgo
![screenshot from 2017-12-23 10-39-43](https://user-images.githubusercontent.com/1226061/34320718-3e81c0d0-e7ce-11e7-88dc-8541c5185bc2.png)

If LeelaZero is unable to get the right score in the end game thinking that a stone in an area prevents that area from scoring for the opponent that could explain a bunch of the really odd cases where it favors useless interior plays (several can be seen in this screen shot)

**Comment by MartinDevelopment** [comment]
All stones that aren't captured are considered alive, so the score is correct.

**Comment by roy7** [comment]
Leela Zero uses Tromp Taylor scoring, not Chinese. There are no dead stones in TT.

**Comment by fsparv** [comment]
Hm never heard of Tromp Taylor before. This perhaps explains the super long play outs (like this monstrosity) and strange inside plays. Seems like a very odd variant of go. It's probably easy to calculate this type of score, but I suspect when combined with the fact that the network will always be trained to expect it's own mistakes (such as filling in one of 2 eyes as white did in this game) it hampers the ability of the engine to see when a game is hopelessly lost leading to really long pointless end games.

**Comment by Dorus** [comment]
See also https://github.com/gcp/leela-zero/issues/122 https://github.com/gcp/leela-zero/issues/227 https://github.com/gcp/leela-zero/issues/264 https://github.com/gcp/leela-zero/issues/288 https://github.com/gcp/leela-zero/issues/309 https://github.com/gcp/leela-zero/issues/423

**Comment by jkiliani** [comment]
Tromp Taylor is covered in the FAQ, and there are very good reasons for using this scoring method. For high level play, the score is equivalent to Chinese scoring as long as all dead stones are captured. Current networks already know which stones are dead and resign eventually if behind in the endgame. The endgame could be shorter and will be again once resign threshold is raised from the current 1%.

**Comment by fsparv** [comment]
Interesting discussion in those, thanks. Still wonder if there isn't some room for improvement, but I see the complexity of the issue now. Thanks.

**Comment by fsparv** [comment]
As for the FAQ, I read that weeks ago... based on the linked issues it probably didn't have info about Tromp Taylor at that time :).
