### ISSUE TITLE
Carry forward visits not shown if not visited in new search

### ISSUE THREAD

**Issue by roy7** [gcp/leela-zero#479]
Not sure if this is working as intended, a display issue, or a bug in the search results itself, but note that my 2 visits from before are in the '4 visits' total count, but the move H11 is missing in the 2nd printout. I assume because H11 wasn't visited in the 2nd move search. K9 was visited in both, and so has a count of 2.

```
genmove b
Thinking at most 50.0 seconds...
NN eval=0.830676

 H11 ->       1 (V: 96.13%) (N: 12.26%) PV: H11 H12
  K9 ->       1 (V: 93.64%) (N: 13.04%) PV: K9 J10
2 visits, 821 nodes, 2 playouts, 50 n/s

= H11

undo
=

genmove b
Thinking at most 50.0 seconds...
NN eval=0.861155

  K9 ->       2 (V: 93.64%) (N: 11.25%) PV: K9 J10
  G7 ->       1 (V: 91.77%) (N: 21.56%) PV: G7 F8
4 visits, 821 nodes, 2 playouts, 66 n/s

= K9

```

**Comment by gcp** [comment]
The visit info is carried forward but the search tree itself isn't propagated.
