### ISSUE TITLE
autogtp only runs 1 game?

### ISSUE THREAD

**Issue by olbrichj** [gcp/leela-zero#48]
Okay I've tried running autogtp on my Mac. Leela Zero compiles with a few warnings, but doesn't look too bad. autogtp compiles fine.

executing it results in
```
autogtp v1
Best network hash: d645af975ed5b9d08530d092d484482d9aee014f9498c7afcde8570743f85751
Required client version: 1 (OK)
Already downloaded network.
Engine has started.
Infinite thinking time set.
1 games played.
```

It finishes afterwards and I would have to restart it. Is this desired behavior?

As of now 46 clients are listet on: http://zero-test.sjeng.org/
Since I haven't contributed yet, I kinda expected it to increase to 47, which it didn't.

ls output:
```
Game.cpp
Game.h
Game.o
Makefile
README.md
autogtp
autogtp.pro
d645af975ed5b9d08530d092d484482d9aee014f9498c7afcde8570743f85751
d645af975ed5b9d08530d092d484482d9aee014f9498c7afcde8570743f85751.gz
main.cpp
main.o
```

so it downloads the current best weights.

**Comment by marcocalignano** [comment]
Did you compile the leelaz binary and put it in the same directory as the autogtp binary?

**Comment by olbrichj** [comment]
That looks a lot better :) thx
I'll create a pull request on the readme

**Comment by gcp** [comment]
It's more an issue of lack of any error handling in autogtp right now.

**Comment by olbrichj** [comment]
agree, still for someone trying it out, they'll have a working readme and won't bug you as I did.
