### ISSUE TITLE
What resign threshold is Leela using in her kgs accounts?

### ISSUE THREAD

**Issue by grolich** [gcp/leela-zero#483]
Here's a game by LeelaZSlow on KGS:

http://files.gokgs.com/games/2017/12/23/LeelaZSlow-atarust.sgf

In it, LeelaZ looks like it's playing with -r 0 - since she goes on to filling her own liberties late in the endgame like that, but she then resigns after nearly all legal moves are gone. 
Was the resign threshold turned very low there?

Also, this game included an accepted undo request, but LeelaZ continued playing normally after that. So I hope that isn't a strange related bug. (More reasonable it's just still a problem which the network will learn or a very low resign threshold)

**Comment by Phelanpt** [comment]
I think it's at 10% (-r 10).

**Comment by OmnipotentEntity** [comment]
I can confirm that it's 10%.  Because I run the bot.

**Comment by Marcin1960** [comment]
20% in my case.
