### ISSUE TITLE
Check dead stones before scoring?

### ISSUE THREAD

**Issue by itmo153277** [gcp/leela-zero#487]
Example game: [http://files.gokgs.com/games/2017/12/24/LeelaZFast-x0000-2.sgf](http://files.gokgs.com/games/2017/12/24/LeelaZFast-x0000-2.sgf)
Suggestion: do not accept any dead stones (which would convert chinese rules into taylor rules) or do not accept the score in case if the result does not match an evaluation from the engine (in terms of W/L)

**Comment by grolich** [comment]
Well, we are trying to create an engine that can play Chinese rules. TT is just a good way to train programs that helps them handle prematurely ended games. Engines that are good in TT tend to do very well in Chinese rules as well. 

That said, it is possible with kgsgtp, when playing under Chinese rules, to ask the other player to continue playing until stones are removed after such a double pass; However, doing this in every game would make many human player not want to play with LZ...

Perhaps it is still a nice idea to add it in positions in which LeelaZ thinks it's winning, but the results of the marked dead stones say it's losing, and just accept the loss in all other situations.

**Comment by Dorus** [comment]
The W/L thing seems like a good idea. If there is a score dispute, simply continue the game and only accept once all stones are either removed or no dead groups are marked (so seki is possible).

There is also an option i've read about on other bots: If somebody dispute a score, the engine is replaced by another (stronger) engine that will then judge the position and play on if needed.

**Comment by gcp** [comment]
This is already supported: play until the scoring, and if the scores disagree, use kgs-genmove_cleanup. KGS supports this, for reasons only they understand, in rated games only.

In the end this is not an issue of the engine but of the GTP interface that must be able to deal with score disputes.
