### ISSUE TITLE
illegal move

### ISSUE THREAD

**Issue by ThorAvaTahr** [gcp/leela-zero#488]
Please help me find my error, but it appears as if leelazero plays an illegal move, repeating a move at D18 on move 10 and 253. I've tried to reconstruct the game but could not find, that this spot has become available again. 

AutoGTP v8
Using 1 thread(s).
Best network hash: 30f49ac57b5bc4db4ef7c67600df557479ebcf33666705df63975bc21b584
711
Required client version: 8 (OK)
curl.exe -s -O -J -w %{filename_effective} http://zero.sjeng.org/best-network
Curl filename: 30f49ac57b5bc4db4ef7c67600df557479ebcf33666705df63975bc21b584711.
gz
Net filename: 30f49ac57b5bc4db4ef7c67600df557479ebcf33666705df63975bc21b584711
./leelaz.exe -r 1 -g -t 1 -q -d -n -m 30 -w 30f49ac57b5bc4db4ef7c67600df557479eb
cf33666705df63975bc21b584711 -p 1600 --noponder
Engine has started.
Infinite thinking time set.
1 (N15) 2 (D2) 3 (P6) 4 (G8) 5 (O18) 6 (N3) 7 (D16) 8 (C17) 9 (D17) **10 (D18)** 11
(R15) 12 (C16) 13 (D15) 14 (C15) 15 (B11) 16 (Q16) 17 (R3) 18 (R16) 19 (L19) 20
(C14) 21 (C9) 22 (N11) 23 (D4) 24 (Q4) 25 (L3) 26 (R4) 27 (Q3) 28 (P4) 29 (S4) 3
0 (S5) 31 (S3) 32 (P3) 33 (F6) 34 (C4) 35 (R5) 36 (S6) 37 (C5) 38 (D5) 39 (C3) 4
0 (B4) 41 (D3) 42 (E5) 43 (B3) 44 (P8) 45 (E18) 46 (H5) 47 (H6) 48 (J6) 49 (G5)
50 (G4) 51 (F4) 52 (H4) 53 (F5) 54 (F3) 55 (E4) 56 (H7) 57 (Q8) 58 (Q7) 59 (P7)
60 (Q6) 61 (R8) 62 (O8) 63 (M6) 64 (O6) 65 (Q14) 66 (Q15) 67 (J3) 68 (P14) 69 (Q
13) 70 (P13) 71 (Q12) 72 (L5) 73 (P15) 74 (S15) 75 (P12) 76 (H2) 77 (M5) 78 (L4)
 79 (M4) 80 (M3) 81 (L6) 82 (K3) 83 (L2) 84 (K2) 85 (M9) 86 (K16) 87 (O10) 88 (O
15) 89 (P16) 90 (P17) 91 (O16) 92 (O17) 93 (N16) 94 (N17) 95 (M17) 96 (N18) 97 (
Q17) 98 (R17) 99 (Q18) 100 (P18) 101 (M18) 102 (M16) 103 (J17) 104 (M15) 105 (O1
4) 106 (J16) 107 (H17) 108 (H16) 109 (G17) 110 (Q2) 111 (M14) 112 (L14) 113 (L13
) 114 (M13) 115 (N14) 116 (K13) 117 (L12) 118 (K12) 119 (L11) 120 (K11) 121 (L15
) 122 (K14) 123 (L16) 124 (L10) 125 (M10) 126 (M11) 127 (P2) 128 (O2) 129 (K6) 1
30 (J5) 131 (L9) 132 (M12) 133 (R2) 134 (R18) 135 (K9) 136 (O7) 137 (H9) 138 (N1
0) 139 (N9) 140 (O9) 141 (P10) 142 (Q9) 143 (R9) 144 (Q10) 145 (R10) 146 (E8) 14
7 (G9) 148 (F9) 149 (H11) 150 (G13) 151 (H8) 152 (G7) 153 (J7) 154 (G6) 155 (F10
) 156 (E10) 157 (F11) 158 (C6) 159 (B5) 160 (B6) 161 (A4) 162 (E11) 163 (F12) 16
4 (E12) 165 (F13) 166 (G14) 167 (D7) 168 (E7) 169 (D8) 170 (E14) 171 (E6) 172 (D
6) 173 (Q1) 174 (R14) 175 (E13) 176 (D13) 177 (D14) 178 (C13) 179 (F14) 180 (F15
) 181 (E15) 182 (F16) 183 (C18) 184 (B18) 185 (D19) 186 (K17) 187 (K15) 188 (J14
) 189 (C11) 190 (Q11) 191 (R11) 192 (F17) 193 (F18) 194 (B8) 195 (B9) 196 (P11)
197 (O11) 198 (P9) 199 (O12) 200 (J8) 201 (K7) 202 (J10) 203 (J9) 204 (D12) 205
(E2) 206 (F2) 207 (K18) 208 (E9) 209 (B7) 210 (G12) 211 (G11) 212 (H12) 213 (J15
) 214 (H15) 215 (E3) 216 (P5) 217 (S7) 218 (S12) 219 (R12) 220 (S13) 221 (C7) 22
2 (E1) 223 (G16) 224 (G15) 225 (T5) 226 (R6) 227 (J11) 228 (J12) 229 (K10) 230 (
T6) 231 (L11) 232 (L12) 233 (B13) 234 (B14) 235 (B12) 236 (S1) 237 (R1) 238 (O1)
 239 (T2) 240 (T4) 241 (P1) 242 (B19) 243 (B17) 244 (B16) 245 (S11) 246 (A17) 24
7 (N19) 248 (O19) 249 (M19) 250 (C19) 251 (Q19) 252 (R19) **253 (D18)** 254 (F1) 255
 (C2) 256 (D1) 257 (G3) 258 (G2) 259 (O4) 260 (N4) 261 (F7) 262 (F8) 263 (K5) 26
4 (K4) 265 (J4) 266 (J2) 267 (T11) 268 (L17) 269 (T12) 270 (P19) 271 (T7) 272 (M
7) 273 (T13) 274 (T14) 275 (R13) 276 (S14) 277 (N5) 278 (N7) 279 (O5) 280 (O3) 2
81 (K8) 282 (C1) 283 (B1) 284 (R7) 285 (S8) 286 (A2) 287 (B2) 288 (D10) 289 (A6)
 290 (N13) 291 (O13) 292 (A13) 293 (T3) 294 (T5) 295 (D9) 296 (C10) 297 (B10) 29
8 (L7) 299 (L10) 300 (A14) 301 (A12) 302 (H3) 303 (N8) 304 (N12) 305 (L18) 306 (
L8) 307 (T1) 308 (N6) 309 (M8) 310 (H10) 311 (G10) 312 (D11) 313 (S16) 314 (E16)
 315 (E17) 316 (S17) 317 (C12) 318 (D6) 319 (A3) 320 (T16) 321 (G18) 322 (A7) 32
3 (M16) 324 (P7) 325 (A10) 326 (B6) 327 (J18) 328 (A8) 329 (C6) 330 (L1) 331 (T1
0) 332 (M2) 333 (H13) 334 (H14) 335 (T9)

**Comment by Mardak** [comment]
Black captured D18 when it played 185 (D19). (With previous stones 9 (D17), 45 (E18), 183 (C18).)

184 (W B18):
```
   a b c d e f g h j k l m n o p q r s t 
19 . . . . . . . . . . X . . . . . . . . 19
18 .(O)X O X . . . . . . X O X O X O . . 18
17 . . O X . . X X X . . X O O O X O . . 17
16 . . O X . O . O O O X . X X X O O . . 16
15 . . O X X O . . . . X . X . X O . O . 15
14 . . O X . X O . . O O X X X O X O . . 14
13 . . O O X X O . . O . O . . O X . . . 13
12 . . . . O X . . . O . O . . X X . . . 12
11 . X . . O X . X . O . O O . . . . . . 11
10 . . . + O X . . . + O X O X X O X . . 10
 9 . . X . . O X X . X X X X O . O X . .  9
 8 . . . X O . O X . . . . . O O X X . .  8
 7 . . . X O . O O X . . . . O X O . . .  7
 6 . O O O X X O . O X X X . O X O . O .  6
 5 . X X O O X X O O . O X . . . . X O .  5
 4 X . . X X X O O . + O X . . O O O X .  4
 3 . X X X . O . . X O X O O . O X X X .  3
 2 . . . O . . . O . O X . . O X . X . .  2
 1 . . . . . . . . . . . . . . . X . . .  1
   a b c d e f g h j k l m n o p q r s t 
```

185 (B D19):
```
   a b c d e f g h j k l m n o p q r s t 
19 . . .(X). . . . . . X . . . . . . . . 19
18 . O X . X . . . . . . X O X O X O . . 18
17 . . O X . . X X X . . X O O O X O . . 17
16 . . O X . O . O O O X . X X X O O . . 16
15 . . O X X O . . . . X . X . X O . O . 15
14 . . O X . X O . . O O X X X O X O . . 14
13 . . O O X X O . . O . O . . O X . . . 13
12 . . . . O X . . . O . O . . X X . . . 12
11 . X . . O X . X . O . O O . . . . . . 11
10 . . . + O X . . . + O X O X X O X . . 10
 9 . . X . . O X X . X X X X O . O X . .  9
 8 . . . X O . O X . . . . . O O X X . .  8
 7 . . . X O . O O X . . . . O X O . . .  7
 6 . O O O X X O . O X X X . O X O . O .  6
 5 . X X O O X X O O . O X . . . . X O .  5
 4 X . . X X X O O . + O X . . O O O X .  4
 3 . X X X . O . . X O X O O . O X X X .  3
 2 . . . O . . . O . O X . . O X . X . .  2
 1 . . . . . . . . . . . . . . . X . . .  1
   a b c d e f g h j k l m n o p q r s t 
```

**Comment by ThorAvaTahr** [comment]
ok, my bad, thanks for your reply, I must have missed a line in my own replay, but couldnt find it myself.
