### ISSUE TITLE
A segfault issue in the next branch

### ISSUE THREAD

**Issue by isty2e** [gcp/leela-zero#490]
```
./leelaz -w c99f1ae0531adc89303492983a621bae88b68a7782e77046e5bde0b520a63986

...

Leela: genmove b
Thinking at most 50.0 seconds...
NN eval=0.474739
Playouts: 987, Win: 51.08%, PV: D16 C17 Q16 C16 D4 C3 Q4
Playouts: 1981, Win: 50.92%, PV: Q4 R3 Q16 Q3 D16 C17 D4
Playouts: 2980, Win: 50.87%, PV: Q4 R3 Q16 Q3 D16 C17 D4 R17
Playouts: 3965, Win: 50.87%, PV: Q4 R3 D16 R4 Q16 C17 D4 D17 E17 E16
Playouts: 4834, Win: 50.92%, PV: Q4 R3 D16 R4 Q16 R17 D4 R16 R15
Playouts: 5700, Win: 50.97%, PV: Q4 R3 D16 R4 Q16 C17 D4 D17 E17 E16 F16
Playouts: 6581, Win: 50.99%, PV: D4 C3 Q16 D3 D16 C17 Q4 D17
Playouts: 7455, Win: 50.99%, PV: D4 C3 Q16 D3 Q4 R17 D16 R16 R15
Playouts: 8324, Win: 50.99%, PV: D4 C3 Q16 D3 D16 Q4 E3 C4
Playouts: 9285, Win: 51.01%, PV: Q4 R3 D16 R4 Q16 D4 R5
Playouts: 10263, Win: 51.04%, PV: D16 C17 Q4 D17 D4 Q16 E17
Playouts: 11234, Win: 51.03%, PV: D16 C17 Q4 D17 Q16 D4 E17
Playouts: 12081, Win: 51.02%, PV: D16 C17 Q4 D17 Q16 D4 E17
Playouts: 12955, Win: 51.01%, PV: D16 C17 Q4 D17 Q16 D4 E17
Playouts: 13828, Win: 50.99%, PV: D16 C17 Q4 D17 Q16 D4 E17
Playouts: 14702, Win: 51.01%, PV: D16 C17 Q4 D17 Q16 D4 E17
Playouts: 15579, Win: 51.03%, PV: Q4 R3 D16 R4 D4 Q16 R5 Q3
Playouts: 16567, Win: 51.03%, PV: Q4 R3 R4 Q3 P3 S4 D16 P4
Playouts: 17552, Win:   nan%, PV: D4 C3 D16 C4 Q4 Q16 C5

  D4 ->    1794 (V: 51.11%) (N:  9.70%) PV: D4 C3 D16 C4 Q4 Q16 C5
  Q4 ->    1789 (V: 51.08%) (N:  9.99%) PV: Q4 R3 R4 Q3 P3 S4 D16 P4
 D16 ->    1621 (V: 51.01%) (N:  9.99%) PV: D16 C17 Q4 D17 Q16 D4 E17 C16

...

18442 visits, 6606875 nodes, 18442 playouts, 368 n/s

= D4

zsh: segmentation fault  ./leelaz -w c99f1ae0531adc89303492983a621bae88b68a7782e77046e5bde0b520a63986
```

I wonder if this issue is reproducible for others. I'm on the next branch with 303 commits, and leelaz is compiled following the instruction in OS X.

**Comment by ljn917** [comment]
> Playouts: 17552, Win:   nan%, PV: D4 C3 D16 C4 Q4 Q16 C5

What happened with the NAN?

**Comment by Mardak** [comment]
I haven't hit a segfault on OS X, but I have seen something like your `Playouts: 17552, Win:   nan%, PV: D4 C3 D16 C4 Q4 Q16 C5`

**Comment by isty2e** [comment]
Yeah that’s also the problem... I thought the two things are tied together but it seems to be not the case then.

**Comment by gcp** [comment]
Can you attach a debugger? I presume the same problem happens on master.

**Comment by isty2e** [comment]
@gcp I just tested it with the same network, and it did not happen on master. I have never used gdb and had troubles making it working on mac (due to the code signing issue), but I will try if time permits.

**Comment by OmnipotentEntity** [comment]
Mac has a gui debugger that ships with xcode, you might have better luck with that.

**Comment by ljn917** [comment]
I believe the default debugger on Mac is LLDB

**Comment by isty2e** [comment]
@OmnipotentEntity @ljn917 Thanks for the information. I will give it a try with lldb. But there is a problem here: Yesterday it was reproducible but today it is not. How peculiar...

**Comment by gcp** [comment]
If you have the seed somewhere you should be able to reproduce the game.
Also setting SELFCHECK_PROBABILITY in config.h to 1.

**Comment by isty2e** [comment]
No problem detected by the self-check, and it was executed without a seed yesterday. Might take some time to reproduce.

**Comment by isty2e** [comment]
Okay I somehow found the stored console log but the issue was not reproducible even with the same random seed. This is puzzling.

**Comment by Mardak** [comment]
Is this the command you ran? `./leelaz -w c99f1ae0531adc89303492983a621bae88b68a7782e77046e5bde0b520a63986`

If so, does the output show something like:
```
Using 2 thread(s).
RNG seed: 13530983136773721919
Leela Zero  Copyright (C) 2017  Gian-Carlo Pascutto
```

**Comment by isty2e** [comment]
@Mardak Yes, and the seed was copy pasted when I was trying to reproduce.

**Comment by killerducky** [comment]
I don't think it will be reproducible if you're not using "-t 1". If you're trying to create the crash again consider using "-t 1" so that if it does crash again you have some chance to reproduce reliably with the seed.

**Comment by isty2e** [comment]
@killerducky Oh yes, you are right. I forgot that -t 2 was default.

**Comment by gcp** [comment]
Hitting a NaN will probably cause the crash because it will confuse parts of the program. But it would help to understand where the NaN came from.

**Comment by isty2e** [comment]
I totally agree, but I am having trouble reproducing it. What I am doing for now is running leelaz with single thread, genmove b, and see if the same thing happens, but somehow the error doesn't come out. Presumably it was a rare event?

**Comment by OmnipotentEntity** [comment]
It's entirely possible that the bug stemmed from a miscompilation or stale object file that was flushed after you recompiled master and then next again.

**Comment by isty2e** [comment]
@OmnipotentEntity I run next by default and the test with the master branch was done in a separate directory. Also I make clean every time before making after I run git pull, so it seems unlikely.

**Comment by ljn917** [comment]
There are two persons who saw this issue, so it is not likely an individual
mistake in my opinion.

I think the best beat now is to attach a debugger while running leelaz and
hope it catches the SIGFPE if NaN occurs.

BTW, I didn't find an easy way to enable FPE traps with clang. (I think you
compile with clang on Mac) That would be easier than using a debugger.

**Comment by isty2e** [comment]
Closing this since I have not been able to reproduce it in a consistent manner.
