### ISSUE TITLE
Feature request: Store winnercolor on selfplay games

### ISSUE THREAD

**Issue by roy7** [gcp/leela-zero#492]
We already store an explicit winnercolor field on match games, but not on self play games. Someone asked me what was white vs black win rate in self play training games and I realized I can't calculate that easily without running a regexp search in the database on sgf fields for all games.

**Comment by marcocalignano** [comment]
@roy7 solved by #486 check the game
e84b46ce69c4e5705fd83f482ef8bfdb17db13d12d848bf4a19e0118760f4516
