### ISSUE TITLE
Mismatch error when use CPU version of OpenCL 

### ISSUE THREAD

**Issue by bood** [gcp/leela-zero#494]
Was trying to create some kind of acceptance test on Travis, and since Travis does not have a GPU, one way of doing it is to install a CPU version of OpenCL.

I followed the instructions here:
https://askubuntu.com/questions/850281/opencl-on-ubuntu-16-04-intel-sandy-bridge-cpu

But ended up with this on `next` branch:
```
Error in OpenCL calculation: expected 2.503284 got 1.973696 (error=26.832283%)
Update your GPU drivers or reduce the amount of games played simultaneously.
terminate called after throwing an instance of 'std::runtime_error'
  what():  OpenCL self-check mismatch.
```

Why CPU version of OpenCL calculates wrong here? Is there a solution to this?
I remember @killerducky mentioned the reason once on reddit maybe, but cannot find it anymore.

**Comment by gcp** [comment]
The self check is exactly there to detect when the OpenCL implementation is broken.

**Comment by bood** [comment]
I wonder why intel released a buggy impl...
so the only way I can think of is to disable open cl for testing on  travis. Any concerns?

**Comment by gcp** [comment]
Not really. It won't test OpenCL support but if it can at least check if it compiles correctly that may be OK. The correctness is checked at runtime anyway, as you noticed.

**Comment by fishcu** [comment]
@bood, for running on CPU, you might try this commit instead: https://github.com/sethtroisi/leela-zero/commit/01efa33c24109cacaed73af19e06d54da652fb5a

Still hoping for a executable release for this. :)

**Comment by gcp** [comment]
@fishcu He wants to test OpenCL in continuous integration, he doesn't need non-OpenCL CPU support.

**Comment by fishcu** [comment]
I must have misunderstood the issue description.

Thank you for pointing me towards that other commit. Can I expect a CPU-only version with the next release, or is it still just for debugging? I might try building and hosting a release myself.

**Comment by gcp** [comment]
I'll do a CPU only version the next release, if only for people that want to play games without a GPU.

Depending on the speed difference with a low-end GPU, I might or might not include autogtp in that release package...

**Comment by bood** [comment]
So just compilation would be enough for CI?
I planned to add some tests as well, that's why I added google test for unit test, and perhaps also some bash scripts for smoke test. If you think it's unnecessary, I'll stop here and just do the compilations.

**Comment by fishcu** [comment]
"Depending on the speed difference with a low-end GPU, I might or might not include autogtp in that release package..."

With the commit I posted a few comments above (the one in sethtroisi's fork), I get about 12.5 seconds per move on a sandy bridge CPU (about 50s / move across 4 threads). If I can help you with any other benchmarks, please tell me!

**Comment by bood** [comment]
@fishcu I've already done some tests, see comments on commit 01efa33c24109cacaed73af19e06d54da652fb5a
