### ISSUE TITLE
does all.sgf.xz include the match games?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#495]
or only self-play games?
https://sjeng.org/zero/all.sgf.xz

**Comment by roy7** [comment]
Should only be training games. Match games aren't used for training.

**Comment by l1t1** [comment]
could you publish them, I wonder  the following games

2017-12-24 21:57 | 67fa5349 VS c99f1ae0 | 0 : 73 (0.00%) | 73 / 400 | fail
-- | -- | -- | -- | --

**Comment by OmnipotentEntity** [comment]
I have two:

B+0.5: http://eidogo.com/#3aMhOcY6h
B+Res: http://eidogo.com/#kUACzpZX

**Comment by l1t1** [comment]
thanks @OmnipotentEntity

**Comment by gcp** [comment]
I uploaded a dump to sjeng.org/zero

**Comment by l1t1** [comment]
thanks @gcp

**Comment by roy7** [comment]
Now you can click on the VS like http://zero.sjeng.org/match-games/5a4014ac12f0745adc9ce25b to see them all.
