### ISSUE TITLE
can't understand why visits in TT could greater than it in node

### ISSUE THREAD

**Issue by ericyan71** [gcp/leela-zero#496]
Hi, I’m here again, sorry for my question, I meet a problem when I learn the code in play_simulation and TTable, in function TTable::sync:
    if (m_buckets[index].m_visits > node->get_visits()) {
        /*
            entry in TT has more info (new node)
        */
        node->set_visits(m_buckets[index].m_visits);
        node->set_blackevals(m_buckets[index].m_eval_sum);
}
Why would the visits in TT be greater than it in node? I think this could be due to the multi thread, but I found it is the identical node used by any thread in the function play_simulation, so any changes occurred in other thread would been “seen” in this thread, so how this situation happened? I set a break in the code block of if, and program stop at the break point, so it really happened, could you please help me understand this problem? Thanks.

**Comment by oni-link** [comment]
> Why would the visits in TT be greater than it in node? 

Different nodes in the search tree can have the same hash, because you can reach the same board position with different move orders. These nodes would share an entry in the TTable, but the nodes could be visited a different amount of time, because different parts of the tree were searched.

**Comment by ericyan71** [comment]
@oni-link that's very kind of you!
