### ISSUE TITLE
Option for self-game only without playing matches

### ISSUE THREAD

**Issue by billyswong** [gcp/leela-zero#497]
Currently only computers that run the next branch do matches. As most matches end up as SPRT fail, for slow computers that are always too slow to finish one game *before* the SPRT has determined, their computation contribution seems a waste if they participate in matches too. After Leela Zero 0.10 is released, all clients will be matches-capable, and I don't want old display cards waste time on SPRT-failed matches while playing no self-games.

It will be better if we get some division of labour, especially when new net got uploaded so frequently now.

**Comment by gcp** [comment]
I'm not sure this is worth bothering much about: slow clients are already proportionally (to their speed) much less likely to finish their game in the timing window where the server is handing out matches.

Thus, simply handing out matches on first-come firsts-serve basis means most matches will be played by fast clients and only a few by slow ones.
