### ISSUE TITLE
Implement F(2x2, 3x3) Winograd convolution

### ISSUE THREAD

**Issue by Ttl** [gcp/leela-zero#498]
I implemented Winograd convolution to learn some OpenCL. It should work pretty well in theory as the runtime is dominated by the batched GEMM and transformations are only about 12% of the runtime. Batched GEMM I'm using is from CLBlast library which should be pretty fast.

On my slow laptop with Intel GPU it is about 40% faster, but on my desktop computer with 1050 Ti Winograd convolution is 5% to 50% slower depending on the network size.

If anyone wants to look at the code it can be found here: https://github.com/Ttl/leela-zero/tree/winograd

Also just a note that when GEMM is first called it will compile it causing the runtime to be longer. In benchmarks at least one NN evaluation should be run before netbench.

**Comment by gcp** [comment]
>On my slow laptop with Intel GPU it is about 40% faster, but on my desktop computer with 1050 Ti Winograd convolution is 5% to 50% slower depending on the network size.

The speed advantage on the Intel GPU is because my OpenCL direct convolution kernel is hampered by the fact that the execution units on Intel GPUs can't do effective SIMT and hence are presented as vector based rather than scalar based as on AMD and NVIDIA architectures. So it's more of a SIMD than a SIMT architecture, and it ends up not being able to use more than 1 ALU lane. CLBlast's GEMM kernels don't have this problem.

When you say transformations are only 12% of the run-time, was that measured on the Intel, the 1050 Ti, or both?

**Comment by Ttl** [comment]
Transformations are about 12% on both devices.

**Comment by gcp** [comment]
Ok. Consider doing a CLBlast tuning run with the exact matrix sizes you require?

How hard would it be to translate this back to CPU code? Could be a pretty large speedup on those.

**Comment by Ttl** [comment]
I'll test the tuning tomorrow. The matrix sizes are not nice powers of two so it might hit some edge case.

CPU implementation shouldn't be too hard. I think lot of code could be copy pasted.

**Comment by Ttl** [comment]
I did the tuning but it didn't change the results at all. I investigated a little bit more and it seems that for small matrices CLBlast GEMM spends more time in checking the inputs and copying the arguments to device than actually doing the matrix product. According to profiler runKernel takes only 20% of the execution time with 64 channel network. Biggest overhead seems to be creating new buffers for offsets, alphas and betas and transferring them to the device on each call.

I think I need to copy the OpenCL GEMM kernel from CLBlast and call it directly for this to be faster.

I did some benchmarks with the current implementation. It's much slower with 64 channel network but a lot faster with 256 channel network:
```
5x256
winograd: 1600 evaluations in  9.17 seconds -> 174 n/s
direct: 1600 evaluations in 16.42 seconds -> 97 n/s

6x128
winograd: 1600 evaluations in  5.57 seconds -> 287 n/s
direct: 1600 evaluations in  5.52 seconds -> 289 n/s

5x64
winograd: 1600 evaluations in  3.52 seconds -> 454 n/s
direct: 1600 evaluations in  1.70 seconds -> 940 n/s
```

**Comment by Ttl** [comment]
I transplanted the OpenCL SGEMM kernel from CLBlast to leelaz and now it is faster with every net size. Now transformations take 83% of processing time with 64 channel network and 55% with 128 channel one. There should be still plenty of optimizations left with them.

```
5x256:
winograd: 1600 evaluations in  7.81 seconds -> 204 n/s
direct: 1600 evaluations in 16.42 seconds -> 97 n/s

6x128:
winograd: 1600 evaluations in  3.23 seconds -> 494 n/s
direct: 1600 evaluations in  5.52 seconds -> 289 n/s

5x64:
winograd: 1600 evaluations in  1.40 seconds -> 1139 n/s
direct: 1600 evaluations in  1.70 seconds -> 940 n/s
```

Using it is now little bit more inconvenient since SGEMM tuners need to be known. With default tuner values it's slower than direct convolution on my PC. For release it's probably necessary to write also tuner for SGEMM in leelaz.

@gcp how I should proceed with this?

**Comment by Alderi-Tokori** [comment]
Looks pretty nice, if gcp validates this, you could make a pull request with the code :)

**Comment by Ttl** [comment]
Continued in #523.
