### ISSUE TITLE
Is 1000 playouts enough to self-train?

### ISSUE THREAD

**Issue by Alderi-Tokori** [gcp/leela-zero#50]
I see you the number of playouts per move in Leela zero's self training is 1000 down from the 1600 described in the paper. Are 1000 playouts enough to get meaningful data to make the network progress? If it is, it'd be a good way to speed up the game generation.

**Comment by gcp** [comment]
Nobody knows. The Zero paper doesn't mention how they arrive at this number, and I know of no sound background to estimate the optimal. I chose it based on some observations:

a) For the MCTS to feed back search probabilities to the learning, it must be able to achieve a reasonable amount of look-ahead on at least a few vriations. In the beginning, when the network is untrained, the move probabilities are not very extreme, and this means that the first 360~ simulations will be spent expanding every answer at the root. So if we want to expand at least a few moves, we probably need 2 to 3 x 360 playouts.

b) One person on computer-go, who ran a similar experiment on 7x7, reported that near the end of the learning, he observed increased performance from increasing the number from 1000 to 2000. So maybe this is worthwhile to try when the learning speed starts to decrease or flatten out. But it almost certainly isn't needed early on.

c) Obviously, the speed of acquiring data is linearly related to this setting.

So, the current number is a best guess based on these observations. To be sure what the best value is, one would have to rerun this experiment several times.

**Comment by OmnipotentEntity** [comment]
If you're going to want to change this value as training wears on would it be a good idea to push that with the weights and have autogtp use it?

**Comment by gcp** [comment]
I considered this but ended going for a slightly more generic solution in that the server can ask for an autogtp update.

**Comment by gcp** [comment]
Seems even 800 is enough :-) Has been discussed further in other threads.
