### ISSUE TITLE
terminate called after throwing an instance of 'cl::Error'

### ISSUE THREAD

**Issue by zhangl** [gcp/leela-zero#503]
root@localhost:~/leela-zero/autogtp# ./leelaz -r 1 -g -t 1 -q -d -n -m 30 -w 0c09415114c40d4df9314a80dcd4090f1f9b45ceeac2dc76900b5430c64fb5d6 -p 1600 --noponder

terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Aborted (core dumped)

autogtp also says *ERROR*: Could not talk to engine after launching.

My machine is Linux localhost 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bood** [comment]
do you have a gpu card？opencl driver also required

**Comment by zhangl** [comment]
the machine is in the cloud, I think it has no gpu

**Comment by gcp** [comment]
Please read the README.

**Comment by jeammimi** [comment]
If you have no gpu you must add --cpu-only to your command line.
