### ISSUE TITLE
why AlphagoZero use SGD instead of ADAM

### ISSUE THREAD

**Issue by ericyan71** [gcp/leela-zero#508]
an stupid question, why alphagozero use SGD, not ADAM? I guess we don't care too much about the learn rate if ADAM were used.

**Comment by isty2e** [comment]
From [one of gcp's comments](https://github.com/gcp/leela-zero/issues/78#issuecomment-353651540):

> Dynamic learning rates (Adagrad, Adam, AdaDelta) perform significantly worse than standard Momentum for this kind of training. You can verify this yourself. It's no coincidence the majority of papers about DCNN and Go didn't use it, in my experience, and the AlphaGo paper very specifically does not use it but uses a specific annealing schedule (that we unfortunately can't use as is).

I have no clue nor explanation why it is so, but we usually adopt a method that works best.
