### ISSUE TITLE
the server for next branch fail?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#516]
<b>
Network connection to server failed.
NetworkException: Curl returned non-zero exit code 18
Retrying in 30 s.
curl.exe -s -J http://zero-test.sjeng.org/get-task/7
{
    "cmd": "selfplay",
    "hash": "39fe0ce32dcd399f173a7d5cdf1dfe3b5db763e0e38340f36ecb9390fe955af8",
    "leelaz_version": "0.9",
    "options": {
        "noise": "true",
        "playouts": "1600",
        "randomcnt": "30",
        "resignation_percent": "1"
    },
    "options_hash": "16b7b7",
    "random_seed": "4712395990908974152",
    "required_client_version": "10"
}

Required client version: 10
 -p 1600  -r 1  -m 30  -t 1  -d   -n   --noponder  -s 4712395990908974152
curl.exe -s -O -J -w %{filename_effective} http://zero.sjeng.org/networks/39fe0ce32dcd399f173a7d5cdf1dfe3b5db763e0e38340
f36ecb9390fe955af8.gz
Network connection to server failed.
NetworkException: Curl returned non-zero exit code 18
Retrying in 45 s.
curl.exe -s -J http://zero-test.sjeng.org/get-task/7
{
</b>

but master branch works

Game data 6958dc0ea199547531f8ec8a3902b52c29b33b9592b83de8233bf5b77094e20a stored in database
Best network hash: 39fe0ce32dcd399f173a7d5cdf1dfe3b5db763e0e38340f36ecb9390fe955af8
Required client version: 8 (OK)
Already downloaded network.
Stopping engine.
./leelaz.exe -r 1 -g -t 1 -q -d -n -m 30 -w 39fe0ce32dcd399f173a7d5cdf1dfe3b5db763e0e38340f36ecb9390fe955af8 -p 1600 --n
oponder
Engine has started.
Infinite thinking time set.
1 (Q16) 2 (J7) 3 (D16) 4 (D4) 5 (Q4) 6 (D15) 7 (C16) 8 (C15) 9 (E15) 10 (E16) 11 (B12) 12 (J19) 13 (B15) 14 (B14) 15 (B1
6) 16 (E17) 17 (F15) 18 (G16) 19 (D3) 20 (D13) 21 (C14) 22 (D14) 23 (C13) 24 (P17) 25 (D12) 26 (E13) 27 (R11) 28 (E12) 2

**Comment by killerducky** [comment]
You are using an old version of the next client. Please either update your next branch, or just continue to use the master branch. It's easiest to just use master if you're not familiar with the process.

**Comment by l1t1** [comment]
seems fixed
Retrying in 67 s.
Maximum number of retries exceeded. Falling back to previous network.
./leelaz.exe -p 1600  -r 1  -m 30  -t 1  -d   -n   --noponder  -s 1157010521  -g -q -w 30004a1d5ca0849cf3df5432f425260f4
5bb315378d2dcda285e725ca2cb79ab
Engine has started.
Infinite thinking time set.
1 (B Q16) 2 (W D18) 3 (B Q4) 4 (W G15) 5 (B D4) 6 (W R3) 7 (B N17) 8 (W P15) 9 (B R4) 10 (W K10) 11 (B D16) 12 (W C3) 13
 (B G17) 14 (W C4) 15 (B D3) 16 (W K16) 17 (B Q15) 18 (W D5) 19 (B E5) 20 (W D6) 21 (B C2) 22 (W B2) 23 (B E6) 24 (W E12
) 25 (B D7) 26 (W Q3) 27 (B P3) 28 (W P4) 29 (B S3) 30 (W C7) 31 (B C8) 32 (W D2) 33 (B E2) 34 (W C1) 35 (B B7) 36 (W C6

**Comment by killerducky** [comment]
No, it is failing the upload. It gave up and started a new game. It will fail that upload also when your game is done. Your client does not have "movescount". See for example my client's upload command:

curl -F networkhash=39fe0ce32dcd399f173a7d5cdf1dfe3b5db763e0e38340f36ecb9390fe955af8 -F clientversion=10 -F options_hash=16b7b7 -F movescount=390 -F random_seed=16394604926587003755 -F sgf=@2d4a04f37b3748dabe25c695a8e5871c.sgf.gz -F trainingdata=@2d4a04f37b3748dabe25c695a8e5871c.txt.0.gz http://zero-test.sjeng.org/submit

**Comment by roy7** [comment]
I eventually gave up and stopped rejecting games with missing movecounts, but people do need to please stay up to date on the /next branch if they are using it.
