### ISSUE TITLE
why lz's mcts run so fast!

### ISSUE THREAD

**Issue by ericyan71** [gcp/leela-zero#517]
Hi I have a new question, I tested the speed of Network::get_scroed_move, and find it cost about 3ms on my 1080ti, then I run leelaz.ex with parameter -t 0, I think it would enforce MCTS runing in one thread, the simulation speed is 800 playout per second, I'm very confused, because in one single simulation, function playout_simulation would be runing until game is over, giving it is 300 moves one game for estimation, 300*3ms is about 1s, that's about 1po per second, that's a great gap compared with 800po/s,  even using multithread and cache, I can't understad how to catch up with the speed of 800po/s,  could you please teach me where to learn to understand this question? That's very kind of you, thanks.

**Comment by RavnaBergsndot** [comment]
LZ's MCTS doesn't run to the end of the game. It runs to the first leaf node it meets and only expands one leaf per simulation. See the Alphago Zero paper.

**Comment by RavnaBergsndot** [comment]
LZ's MCTS doesn't run to the end of the game. It runs to the first leaf node it meets and only expands one leaf per simulation. See the Alphago Zero paper.

**Comment by ericyan71** [comment]
thank @RavnaBergsndot , I got it. but I wonder what po AGZ use when they play with chinese KEJIE ?

**Comment by RavnaBergsndot** [comment]
From their AZ paper, Go runs 16k playouts per second on their 4TPU machine. Considering its moves usually took less than a minute when it played against Ke Jie, it should be less than 1 million playouts per move.

**Comment by grolich** [comment]
AGZ never played with Ke Jie.
That was a version of the older alphago, using a different sort of MCTS, where leaf nodes started rollouts to the end of the game.

LZ is modeled after alphago zero, not the version who played Ke Jie
