### ISSUE TITLE
Configuration question: FC size in value head

### ISSUE THREAD

**Issue by gaieepo** [gcp/leela-zero#518]
In both AGZ paper and LZ implementation, I see hidden FC size in value head as 256. At the beginning I suspect it corresponds with the number of filters as in other conv layers but in older versions and issues (e.g. #17 ), it seems to be not the case. It seems to be a fixed number no matter how we change the boardsize, block no. or filter no. Is my understanding correct? Assume I want to implement LZ algorithm on smaller boardsize, do I need to change this "256"? If yes, why LZ did not change it while it's using 64 filters. If not, why does it need to be 256 then. Thank you!

**Comment by RavnaBergsndot** [comment]
Deep learning is called "alchemy" by some people and it's not for no reason. I think it's chosen by Deepmind from their previous smaller scale experiments before the serious self-playing and training happened.

I'm also playing with my 9x9 AGZ clone and I chose 64, but my main goal is to find a network as small as possible given a certain playing strength requirement, so it might not mean much for your project.

**Comment by gcp** [comment]
The FC hidden layer size is somewhat arbitrary, but intuitively, for me, it represents the amount of different score states the program can recognize.

**Comment by gaieepo** [comment]
@gcp That gives me a clear direction. But could you clarify more on 'score states' in value head? I am still a bit blur about that.

**Comment by gcp** [comment]
A go game has a finite amount of possible score outcomes. White wins by 0.5, 1.5, 2.5 etc.

**Comment by gaieepo** [comment]
@gcp oh i get it. That makes a lot sense to me. Thank you!
