### ISSUE TITLE
could you release offical next bransh windows binary files?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#522]
I download it from somewhere else, it's too old and has some bugs.

**Comment by gcp** [comment]
Use the stable release instead of downloading random binaries.

**Comment by l1t1** [comment]
the stable can only selfplay

**Comment by roy7** [comment]
Yes but /next isn't ready for widespread final release yet. There's no problem with people running the /release Windows binary. We need all the self play games we can get. :)
