### ISSUE TITLE
Tech support for tensorflow, cuda, training/tf/parse.py setup

### ISSUE THREAD

**Issue by killerducky** [gcp/leela-zero#524]
I'm trying to get this running, can someone help? I think tensorflow expects cuda-8 but I installed cuda-9. I tried to uninstall cuda-9 and install cuda-8 but I'm having trouble. I'm running ubuntu 17.10.

```
https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1704&target_type=debnetwork
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1704/x86_64/7fa2af80.pub
sudo dpkg -i cuda-repo-ubuntu1704_9.1.85-1_amd64.deb
sudo apt-get update
sudo apt-get install cuda

https://developer.nvidia.com/rdp/cudnn-download
sudo dpkg -i /home/aolsen/Downloads/libcudnn7_7.0.5.15-1+cuda9.1_amd64.deb 
sudo dpkg -i /home/aolsen/Downloads/libcudnn7-dev_7.0.5.15-1+cuda9.1_amd64.deb 
sudo apt-get update
sudo apt-get install libcudnn7 libcudnn7-dev

~/.bashrc:
export PATH="$PATH:/usr/local/cuda/bin"
export CUDA_PATH="/usr/local/cuda"
export LD_LIBRARY_PATH="/usr/local/cuda/lib64"
source ~/.bashrc

training/tf/parse.py ../training/train_4701bb9f/train_4701bb9f_0
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory
(Note the .8.0, makes me assume it requires cuda-8, not cuda-9).

I think tensorflow requires cuda-8, not cuda-9.
sudo apt-get remove cuda
sudo apt-get remove cuda-repo-ubuntu1704 

https://developer.nvidia.com/cuda-toolkit-archive
https://developer.nvidia.com/cuda-80-ga2-download-archive
sudo dpkg -i /home/aolsen/Downloads/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
sudo apt-get update
sudo apt-get install cuda
(The above seems to reinstall cuda-9, not cuda-8).
```

**Comment by killerducky** [comment]
OMG this has hosed my ubuntu setup so that I cannot run leela anymore:

```
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Aborted (core dumped)

```

**Comment by sethtroisi** [comment]
I didn't find anything in my bash_history and not sure exactly how to help but here's the status I can see on my machine

    dpkg -l | grep -i cuda
    ii  cuda-8-0                                 8.0.61-1                                                   amd64        CUDA 8.0 meta-package
    ii  libcuda1-384                             384.98-0ubuntu0~gpu17.04.1                                 amd64        NVIDIA CUDA runtime library
    ii  libcudnn6                                6.0.21-1+cuda8.0                                           amd64        cuDNN runtime libraries

As you mentioned I believe I had installed cuda8.0 because tensorflow doesn't work with cuda9.0

**Comment by sethtroisi** [comment]
I've experienced openCL / nvidia being upset till I restarted (or logged out), so maybe try that.

I would try reinstalling opencl

`sudo apt install opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev zlib1g-dev`

**Comment by killerducky** [comment]
I was able to get leela/autogtp working again by just rebooting, so I'm not in panic mode anymore.

I think I should have done "apt-get install cuda-8" instead of just cuda to force it to install the older version. I will try that tomorrow.

**Comment by killerducky** [comment]
@sethtroisi any suggestions? Here are a few more things I tried:

`sudo apt-get install cuda-8` -- there isn't a cuda-8 package. I did see a cuda-repo-ubuntu1604, so I tried installing that, but it looks like it installed cuda-9 again.


```
aolsen@aolsen-ubuntu17:~$ dpkg -l |grep -i cuda |grep -v 9-1
ii  cuda-drivers                                  387.26-1                    amd64                       CUDA Driver meta-package
ii  cuda-repo-ubuntu1604                          8.0.61-1                    amd64                       cuda repository configuration files
rc  cuda-repo-ubuntu1704                          9.1.85-1                    amd64                       cuda repository configuration files
ii  libcuda1-387                                  387.26-0ubuntu1             amd64                       NVIDIA CUDA runtime library
ii  libcudnn7                                     7.0.5.15-1+cuda9.1          amd64                       cuDNN runtime libraries
ii  libcudnn7-dev                                 7.0.5.15-1+cuda9.1          amd64                       cuDNN development libraries and headers
ii  libcudnn7-doc                                 7.0.5.15-1+cuda9.1          amd64                       cuDNN documents and samples
aolsen@aolsen-ubuntu17:~$ sudo apt-get install cuda-repo-ubuntu1604 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  cuda-9-1 cuda-command-line-tools-9-1 cuda-compiler-9-1 cuda-cublas-9-1 cuda-cublas-dev-9-1 cuda-cudart-9-1 cuda-cudart-dev-9-1 cuda-cufft-9-1 cuda-cufft-dev-9-1 cuda-cuobjdump-9-1 cuda-cupti-9-1
  cuda-curand-9-1 cuda-curand-dev-9-1 cuda-cusolver-9-1 cuda-cusolver-dev-9-1 cuda-cusparse-9-1 cuda-cusparse-dev-9-1 cuda-demo-suite-9-1 cuda-documentation-9-1 cuda-driver-dev-9-1 cuda-drivers
  cuda-gdb-9-1 cuda-gpu-library-advisor-9-1 cuda-libraries-9-1 cuda-libraries-dev-9-1 cuda-license-9-1 cuda-memcheck-9-1 cuda-misc-headers-9-1 cuda-npp-9-1 cuda-npp-dev-9-1 cuda-nsight-9-1 cuda-nvcc-9-1
  cuda-nvdisasm-9-1 cuda-nvgraph-9-1 cuda-nvgraph-dev-9-1 cuda-nvml-dev-9-1 cuda-nvprof-9-1 cuda-nvprune-9-1 cuda-nvrtc-9-1 cuda-nvrtc-dev-9-1 cuda-nvtx-9-1 cuda-nvvp-9-1 cuda-runtime-9-1
  cuda-samples-9-1 cuda-toolkit-9-1 cuda-tools-9-1 cuda-visual-tools-9-1 freeglut3 freeglut3-dev libice-dev libsm-dev libwine libwine:i386 libxi-dev libxmu-dev libxmu-headers libxt-dev
  linux-headers-4.13.0-16 linux-headers-4.13.0-16-generic linux-headers-4.13.0-17 linux-headers-4.13.0-17-generic linux-image-4.13.0-16-generic linux-image-4.13.0-17-generic
  linux-image-extra-4.13.0-16-generic linux-image-extra-4.13.0-17-generic nvidia-387-dev nvidia-modprobe wine32:i386 wine64
Use 'sudo apt autoremove' to remove them.
The following packages will be upgraded:
  cuda-repo-ubuntu1604
1 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Need to get 0 B/2,820 B of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 307414 files and directories currently installed.)
Preparing to unpack .../cuda-repo-ubuntu1604_9.1.85-1_amd64.deb ...
Unpacking cuda-repo-ubuntu1604 (9.1.85-1) over (8.0.61-1) ...
Setting up cuda-repo-ubuntu1604 (9.1.85-1) ...

```

**Comment by killerducky** [comment]
Ok I'm getting closer. I think the key was doing dpkg --purge of all the cuda-9 stuff so when I install cuda it picks cuda-8. I couldn't force it to pick version 8 otherwise. I also had to downgrade from cudnn7 to cudnn6. 
```
    sudo apt-get remove cuda
    sudo apt-get remove cuda-repo-ubuntu1704
    sudo apt autoremove
    dpkg -l |grep "^rc" |cut -d " " -f 3 |grep cuda |xargs sudo dpkg --purge
    sudo dpkg -i /home/aolsen/Downloads/cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64.deb
    sudo dpkg -i /home/aolsen/Downloads/cuda-repo-ubuntu1604-8-0-local-cublas-performance-update_8.0.61-1_amd64.deb
    sudo apt-get update
    sudo apt-get install cuda
```

Next problem is this error:
```
training/tf/parse.py ../training/train_4701bb9f/train_4701bb9f_0.gz 
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
```
Debugging this now.

I guess I need to install a different version of tensorflow-gpu? I installed it like this:
```
sudo apt-get install python3-pip python3-dev
pip3 install tensorflow-gpu

```

**Comment by roy7** [comment]
@killerducky I had that problem too. The package has the wrong version and noone has gotten around to fixing it. See https://github.com/tensorflow/tensorflow/issues/14273. 

I had to compile tensorflow from source to get past that on my own install.

**Comment by killerducky** [comment]
Oh it's just a warning, the real error was I included the .gz extension on my command line. I think it is working now!

**Comment by killerducky** [comment]
(Note I gave it only a single game chunk file)

step 100, policy=5.88104 mse=0.0913282 reg=0.562902 total=6.53527 (0 pos/s)
step 200, policy=5.80454 mse=0.017777 reg=0.56035 total=6.38267 (851.794 pos/s)
step 300, policy=5.76848 mse=0.0109026 reg=0.555873 total=6.33526 (856.104 pos/s)

**Comment by killerducky** [comment]
I started to work on cleaning up my versions a bit more. Bad idea of course! I was trying to fix this warning: `./leelaz: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by ./leelaz)`

I decided to try uninstall and reinstall opencl, and I also removed a few lines from my .bashrc that I'm not sure I need:
```
    sudo apt remove opencl-clhpp-headers
    sudo apt remove opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev clinfo
    sudo apt install opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev clinfo
   
    #export PATH="$PATH:/usr/local/cuda/bin"
    export CUDA_PATH="/usr/local/cuda"
    #export LD_LIBRARY_PATH="/usr/local/cuda/lib64"
```
Now I get this:

```
clinfo
clinfo: /usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1: no version information available (required by clinfo)
Number of platforms                               0
```

@roy7 @sethtroisi any ideas?

**Comment by roy7** [comment]
No sorry. Whenever I update my server I end up with a headache of Leela no longer working and only some combination of rebooting + reinstalling openCL stuff eventually fixes it. If you didn't reboot, try that. ;)

**Comment by killerducky** [comment]
How do you usually go about reinstalling openCL?

**Comment by roy7** [comment]
Like you did. I remove packages and add packages and panic and eventually leela runs. I'm not a good system admin to give you useful answers. :( I'm just a hobbyist programmer. ;)

**Comment by killerducky** [comment]
I'm in the panic stage.  :)

**Comment by killerducky** [comment]
Ok I'm back. I think when removing stuff I must have removed some of the nvidia drivers. I removed and reinstalled nvidia and now it's working. I'm debating now if I should continue to my next goal which is to also install tensorflow/cuda/cudnn again...

```
http://www.linuxandubuntu.com/home/how-to-install-latest-nvidia-drivers-in-linux
    sudo apt-get purge nvidia*
    sudo add-apt-repository ppa:graphics-drivers
    sudo apt-get update
    sudo apt-get install nvidia-387
```
