### ISSUE TITLE
Heatmaps for a recent network. 

### ISSUE THREAD

**Issue by ywrt** [gcp/leela-zero#527]
Indulging curiosity, I grabbed a recent network (e5e72b39) and pulled together a set of [heatmaps](https://drive.google.com/file/d/1FHyYvNxstKFbu_zBFFfF9h4TfmBHEQKP/view?usp=sharing) for both the raw network and a range of playouts.

There's some interesting curiosities in there. E.g move 4, the raw network is focused on building the sides, or corner invasions. But the UCT search by 2500 playouts is totally focused on the center.
![move034](https://user-images.githubusercontent.com/5247963/34459543-f72ed018-ee46-11e7-8612-679081381d51.png)

It takes 50k playouts to become a  little less sure:
![move038](https://user-images.githubusercontent.com/5247963/34459540-bdc7c41a-ee46-11e7-8eaf-fd83cefcf6c6.png)

And by 100k playouts it's changed its mind, preferring a corner invasion:
![move039](https://user-images.githubusercontent.com/5247963/34459541-d6783346-ee46-11e7-881e-608e45775f93.png)

I found it interesting how often the search picked moves that are basically nowhere in the raw network output. e.g Move 8.

Full set of heatmaps to move 112 is [here](https://drive.google.com/file/d/1FHyYvNxstKFbu_zBFFfF9h4TfmBHEQKP/view?usp=sharing)

**Comment by isty2e** [comment]
The YouTube link seems broken now :(

**Comment by ywrt** [comment]
Does [this](https://drive.google.com/file/d/1FHyYvNxstKFbu_zBFFfF9h4TfmBHEQKP/view?usp=sharing) work instead?

**Comment by isty2e** [comment]
Yes, thank you. For this analysis, perhaps it can be helpful to check how the PV and leaf nodes evolve.

**Comment by Mardak** [comment]
Neat video. Just very roughly counting, it seems like if the move were to differ from the raw network, it would more likely happen around the jump to 10k playouts. Do you have the raw numbers for people to analyze? Has anyone analyzed generally what's the threshold of more playouts leading to a different play than the raw network vs move number?

Also, how are you generating the video? I wonder if it would be useful to have a view of 4 different amounts of playouts visible at once instead of over time. E.g., for a given position, split the circle into quarters assigning the top left quarter to 100 playouts, top right 1000 playouts, bottom right 10,000 playouts, bottom left 100,000 playouts. So then at a glance, one could see the differences across the playouts. Here's a quick mockup:
![screen shot 2017-12-30 at 11 13 40 pm](https://user-images.githubusercontent.com/438537/34460028-2cb39c90-edb7-11e7-8bc8-1fb4dd2b2e72.png)

**Comment by kris-computer-go** [comment]
It's very interesting indeed! What tool was used to created this heatmaps?
It will be even more exciting when LZ will be at high dan level :)

**Comment by jkiliani** [comment]
Great video, loved the idea! I'd also like to know what tool you used to produce this, it's very instructive about how the search works. Could you also add the network and UCT search value estimation to this animation?

**Comment by LetterRip** [comment]
Excellent tool, this would be wonderful to watch and use during match analysis, especially once LZ starts playing at the professional level.

**Comment by ywrt** [comment]
I just briefly hacked the code together somewhat. You can see the (rather untidy) current state at https://github.com/ywrt/leela-zero/tree/heatmap

**Comment by alreadydone** [comment]
Most plausible explanation to me is that LZ discovered some josekis that involves ladder, and playing in the center is the best way to make sure that ladders from the corners work/or does not work. Many people in the QQ group 462158519 observed that Leela Zero plays the center very often and have been suspecting this. Some people there are testing LZ on FoxGo against human players using a 20s time setting (forgot about the GPU) and she is now 4D, and people are chatting fervently in the QQ group.
Recent LZ weights have been executing ladders correctly to the end and led to many early resigns, and it seems that LZ is not far from mastering ladders.

**Comment by roy7** [comment]
I did a 1600 playout capped game vs Dark Go tonight on OGS (5d NN based bot) and LZ actually won it using 58da6176. I didn't realize she was up in the dans already.

**Comment by LetterRip** [comment]
@roy7 based on LZ's CGOS performance - she is probably 1d at most with 1600 playouts, and more likely 1k - she is about even or slightly stronger than fuego1604_10k (Bayes Elo 2098) - losing about half the time - LZ-39fe0c-t1-p1600 is 4 for 8 vs fuego and the stronger more recent bots are about the same.  Current LZ is probably somewhere between a true bayes elo of 2050-2200 - probably 2150 or so.
