### ISSUE TITLE
Incorrect SPRT calculation

### ISSUE THREAD

**Issue by Azirine** [gcp/leela-zero#529]
Currently the stats for 58da6176 are as follows:
Start Date | Network Hashes | Wins / Losses | Games | SPRT
2017-12-31 14:25 | 58da6176 VS 40b94cfe | 88 : 61 (59.06%) | 149 / 400 |  

As you can see, it hasn't passed SPRT yet, but if you do the binomial test, there is only a 1.64% chance of it being weaker than the last network, while I believe it should pass at <= 5%.

**Comment by gcp** [comment]
SPRT isn't the same as binominal test. The binominal test ignores that the evaluation is done for every incoming result and will vastly overstate the confidence.
