### ISSUE TITLE
Something wrong in the current strongest networks selfplay games?

### ISSUE THREAD

**Issue by MaxMaki** [gcp/leela-zero#530]
This is from reddit

https://www.reddit.com/r/cbaduk/comments/7n928m/very_weak_game_from_58da6176/

But if you look at these two games, these self-play games look extremely weird. Almost like random moves extend until the end of the game instead of only the first 30 moves. Someone running an modified old next client or something else?

A lot of first line moves, and completely random play past 30 moves. Usually the self-play games become more normal after the first 30, but these just seem extremely odd to what we've seen from the last 10-20 networks or so.

EDIT: Also seems to contain a lot of early passes in completely unfinished positions, something that hasn't been that visible in the latest networks.

http://zero.sjeng.org/view/9a8db302d32cf7e7464de5483b68a03f663d29297711e87c137dfc513383fca9?viewer=wgo

http://zero.sjeng.org/view/b4db7c394e885033afe398a0e9c8521efa6d7b81aca9e95a78495c9af9deb1ac?viewer=eidogo

**Comment by gcp** [comment]
Looks like someone running with a busted client / driver.

**Comment by gcp** [comment]
See #458.
