### ISSUE TITLE
Resign when Leelaz actually wins the game

### ISSUE THREAD

**Issue by arondes** [gcp/leela-zero#531]
I am using Sabaki 0.32.1 with leelaz 0.9 and GNU go 3.8
GNU go handicap 6 Black v.s. Leelaz White
Leelaz already won by a large margin, but then it resigned. See picture below:

![image](https://user-images.githubusercontent.com/17297973/34463286-aeab9272-ee91-11e7-8e7a-42e41131a166.png)

**Comment by gcp** [comment]
Sabaki bug. It doesn't give the correct moves, so Leela thinks she is black.

**Comment by gcp** [comment]
See pull request #528 and the linked issues.
