### ISSUE TITLE
Why LZ never resign before 92nd move? Is it hard-coded?

### ISSUE THREAD

**Issue by ayssia** [gcp/leela-zero#536]
http://zero.sjeng.org/viewmatch/2b11cd9d9412b7f7771632ddf2b0b8c7108be9a2a72ac12d78a448635144a0e9?viewer=wgo
http://zero.sjeng.org/viewmatch/d2d72a3a1c8ca31d98ad8b8a18ab79744327dfa580c20169db5f848a827ec44c?viewer=wgo
http://zero.sjeng.org/viewmatch/f6918ad13aa4f94636699c5bc25c6af5ee2cf8b6c158f52216477a88e4ec6998?viewer=wgo
http://zero.sjeng.org/viewmatch/09fa345f50ffa3c7f53ef7ae12e874d6477fa00d28eed30a6b675586ea3848c5?viewer=wgo
http://zero.sjeng.org/viewmatch/4f12dac937b839fb2279244da867ca070510795d3098bf68f7da08ee04f39d19?viewer=wgo
http://zero.sjeng.org/viewmatch/b339ec260f15bd0eb9a580efc588b2abc91407f0b25deb4ced2c161c7546aceb?viewer=wgo
http://zero.sjeng.org/viewmatch/609e13f8bc4e5948a5fcbb65fafb5d8ed9721d7c37c4c2a44c7cb89c3e39dfbd?viewer=wgo
http://zero.sjeng.org/viewmatch/5438424afc6833eb1ba803eb04a808e83ef27710bd1845ed969d7ccf9eb88889?viewer=wgo
http://zero.sjeng.org/viewmatch/f94050d9a2964c2e1c25ebb52a320fef0f067bb205dabb38fd9922164ac334ce?viewer=wgo
http://zero.sjeng.org/viewmatch/591b716ce8cf021925122a9abc54642255e7ce4b7529d9e7a3e264fed1721ee9?viewer=wgo
http://zero.sjeng.org/viewmatch/8cf6744bf230e506eb8912818b69f95443a3eb8d4289f5e4ffc4324e91ef16e7?viewer=wgo
http://zero.sjeng.org/viewmatch/acffc007353c36a7a5b008a24c30a6cbf311a8cdf85ee9cb934d0078dd017a84?viewer=wgo

All these games are ended at 92nd or 93th move, and they have early ladders. But most of these ladders ended before 92nd move, why LZ didn't resign immediately?

**Comment by gcp** [comment]
Yes:
https://github.com/gcp/leela-zero/blob/b9077b62c20a31d3ed7065b15cc2c136783824b3/src/UCTSearch.cpp#L248

Without this kind of threshold the bot can't play handicap games.

**Comment by roy7** [comment]
@dorus told me that 9 handicap game with LZ on KGS make her behave strangely anyway. I'm guessing because the board looks too different than anything she's ever learned. I'm not allowing my little LeelaZ bot at the moment to do handicaps. :)
