### ISSUE TITLE
Self Atari Issue

### ISSUE THREAD

**Issue by Splee99** [gcp/leela-zero#540]
Hi,
I have observed in many games that LZ played self atari. So for one of the self play games generated by autogtp, I decided to take a closer look. I have saved the game to http://eidogo.com/#zewEC6wa  .
Black played S3, which is self atari. Then white played R1, which ended the game with the result W+Resign. Replaying the game in Gogui showed that LZ didn't play S3 immediately at move 229 (as in the self play game), because S3 is evaluated correctly: S3 ->      74 (V: 28.69%) (N:  2.54%) PV: S3 R1 A9 L10 R18 L11. That may be because of the different random seed.
However, as I played further with LZ the evaluation of S3 changed:

genmove b
Thinking at most 49.8 seconds...
NN eval=0.110179
Playouts: 843, Win: 33.15%, PV: S3 L15 T1 L10 A9 M16 K14 K16 M13 L14 L13 K15
Playouts: 1840, Win: 38.22%, PV: S3 L15 T1 L10 G11 G10 L14 M16 K15 K16 M13 F11 E11 H11
Playouts: 2827, Win: 38.31%, PV: S3 L15 T1 M16 A9 F11 G11 E11 G10 H9 E12 D11 C11 R18 S18 R19
Playouts: 3832, Win: 36.33%, PV: S3 L15 T1 M16 F11 A5 A9 L10 R18 G11 G12 L11 L12 P19 Q19 M13
Playouts: 4815, Win: 33.71%, PV: S3 L15 T1 M16 F11 A5 A9 L10 R18 G11 G12 L11 L12 P19 Q19 M13

  S3 ->    4485 (V: 34.43%) (N:  1.41%) PV: S3 L15 T1 M16 F11 A5 A9 L10 R18 G11 G12 L11 L12 P19 Q19 M13
 N14 ->     203 (V: 20.74%) (N: 45.51%) PV: N14 L15 L14 M16 M13 M15 K15 L10 A9 L11 L12 F11
 L14 ->     187 (V: 27.88%) (N: 20.03%) PV: L14 N14 M13 L10 A9 F11
  T1 ->      72 (V: 33.71%) (N:  0.71%) PV: T1 L15 S3 M16
 L11 ->      36 (V: 28.58%) (N:  3.47%) PV: L11 L10 N14 L15 M16 K16 K15 L16 L14 M15 M13
  A9 ->      32 (V: 23.61%) (N:  5.80%) PV: A9 L15 L14 M16 K15 K16 M13 L16 N14 L10 R18 F11 E11 G12
 M13 ->      23 (V: 23.99%) (N:  4.02%) PV: M13 L10 N14 O14 O13 M16
 O11 ->      20 (V: 31.04%) (N:  0.75%) PV: O11 N14 L14 M13 L13 M12 L11 L10 A9 F11 E11
 G11 ->      18 (V: 32.55%) (N:  0.47%) PV: G11 N14 A9 M13 L11 L10 G10 H9 F11 F9 L14
 L15 ->      16 (V: 31.80%) (N:  0.39%) PV: L15 N14
  A5 ->      16 (V: 26.74%) (N:  1.97%) PV: A5 N14 L11 L10 L14 A4 A9 M13 L13
 F11 ->      15 (V: 28.34%) (N:  1.23%) PV: F11 N14 L14 M13 L11 L10 A9 L13 K13
  J1 ->      13 (V: 31.48%) (N:  0.53%) PV: J1 H1 K1 N14 L14 M13 L11 L10 A9 L13 K13
 R18 ->       8 (V: 14.16%) (N:  2.63%) PV: R18 L15 A9 M16 K16
  L2 ->       7 (V: 25.68%) (N:  1.05%) PV: L2 N14 L14 M13 L11 L10
  T9 ->       6 (V: 24.67%) (N:  0.87%) PV: T9 N14 L11 L10 L14 M13 L13
 L10 ->       5 (V: 25.42%) (N:  0.60%) PV: L10 L11 L12 L10 A9 N14
  G5 ->       3 (V: 16.37%) (N:  1.08%) PV: G5 F5 H4 N14
 A15 ->       2 (V: 14.85%) (N:  0.85%) PV: A15 A16 A9
5168 visits, 704223 nodes, 5001 playouts, 381 n/s

= S3

I'm not familiar with the MCTS algorithm and have several questions.
1. Is the tree re-used or randomly generated every time? I don't understand why the response to S3 was R1 in one occasion and L15 in another occasion. I would think it is important to estimate opponent's response accurately.

2. If let LZ play white after black S3, it choose R1 every time correctly. So I'm wondering if this is good work of the neural network. My question is then if further training can make LZ more accurately estimate opponent's response.

Thanks.

**Comment by Dorus** [comment]
I tried this myself and i got the following result:

On move 228 winrate is 7% and it doesn't really like S3

```
  0   0   0   0   0   0   0   0   0   0   0   0   0   0  17   1   5   2   0 
  1   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0 107   5   1 
  0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   2   0   0   0   0   0   0   7   0   0   0   0   0   0   2 
  6   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 
  1   0  33   0   2   1  15   0   0   0   0   6   9   0   0   0   0   0   2 
  0   0   0   0   0   1   1   0   0   0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0  51  18   1   0   3  57   0   0  26   2   9   0   0   0 
  0   0   0   0   0   0   1   0   0   0  20   0   0   0   0   0   0   0   1 
179   0   0   0   0   0   0   4   5   0   0   0   0   0   0   0   0   0 103 
  0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0   0   2   0   3   0   0   0   0   0 
  0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 
 45   0   0   0   0   3  28   0   0   0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 
  0   0   0   4   0   0   0   0   0   0   0   0   0   0   0   0   0  24   0 
  0   0   0   0   0   0   0   0   0   0  29   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0  10   2   0   8   0   1   0   0   0   0  19 
pass: 0
winrate: 0.068102
```
I ran it with 3600 playouts at this position. It does consider S3 but only as the 16th move. However other times i observed it as the 3th choice. So i can imagine it did play S3 in self play.

If you run move 229, you get a heatmap that strongly prefer the R1 capture:
```
  0   0   1   0   0   0   0   0   0   0   0   0   0   0  19   1   1   2   1 
  1   1   0   0   0   0   0   1   1   1   0   0   0   0   0   0  59   1   1 
  0   0   0   0   0   2   0   0   0   0   0   0   0   0   0   0   0   0   0 
  1   0   0   0  19   0   0   0   0   0   0  10   0   0   0   0   0   0  13 
  4   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0 
  4   0  87   0   1   1   9   0   1   0   0  42  13   4   0   0   0   0   9 
  0   0   0   0   0   3   8   1   1   0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   1   0   2   0   4   0   1   0   0   1   0   0   0   0   0 
  0   0   0   0   3  85   6   1   1   2  79   0   0   3   0   1   0   0   0 
  0   0   0   0   0   0   0   0   0   0  73   0   0   0   0   0   0   1   0 
  0   0   0   0   0   0   0   1   6   0   0   0   0   0   0   0   0   0   4 
  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0   2  12   0   4   0   0   0   0   6 
  0   0   0  10   0   0   0   0   0   0   0   0   0   0   1   0   1   0   0 
 17   0   0   0   1   1  13   0   0   0   0   0   0   0   1   0   0   0   0 
  0   0   0   0   1   0   0   0   0   0   0   0   1   0   0   0   0   0   0 
  0   0   0   4   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 
  0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0  14   3   0   0   0  16   0   0 173   0   2 
pass: 0
winrate: 0.598068
```

But, if you observe winrate: It wend from 7% (for black, so a 93% white win) to 60% white win.

Still, R1 is strongly preferred, so the search should instantly find it. If you do the heatmap on move 230:


```
  0   1   0   0   0   0   0   0   0   0   0   0   0   0  16   1   5   3   1 
  1   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0  82   4   1 
  0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   2   0   0   0   0   0   0   6   0   0   0   0   0   0   3 
  8   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 
  1   0  40   0   2   1  10   0   0   0   0   7  10   0   0   0   0   0   2 
  0   0   0   0   0   1   1   0   1   0   0   1   0   0   0   0   0   0   0 
  0   0   0   0   1   0   1   0   1   0   1   1   1   1   0   0   0   0   0 
  0   0   0   0   0  58  21   1   1   4  68   0   0  24   1   6   0   0   0 
  0   0   0   0   0   0   1   0   0   0  23   0   0   0   0   0   0   0   1 
235   0   0   0   0   0   0   5   5   0   0   0   0   0   0   0   0   0  35 
  0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0   0   1   0   1   0   0   0   0   0 
  0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 
 57   0   0   0   1   5  34   0   0   0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   1   3   1 
  0   0   0   5   0   0   0   0   0   0   0   0   0   1   1   2   2   2   2 
  0   0   0   0   0   0   0   0   0   0  15   0   0   0   0   2   5   0   0 
  0   0   0   0   0   0   0   0  10   2   0   2   0   1   0   2   0   0   0 
pass: 0
winrate: 0.000737
```
0.07% black win, thus the value net clearly recognize a less here.

Now i'm eager to say it wend from a white win to a white win. Possibly S3 is just a desperate move, if white does ignore it, black gets to capture on T1 and is able to win. So possibly it's one of those famous MCST tilt moves where it tries moves that fail if responded correctly, but win otherwise in situations where any other move is a loss anyway.

One other thing did pop up in my experiment: If you analyze move 229 before move 228, it will strongly prefer the game move. Probably because it reuses the old search that already has the game move included. I've seen similar problems with Leela 11: If you try a move of your own and then go back, that move you tried will be on top of the search for some time until it did enough playouts to burry that move again.

**Comment by Splee99** [comment]
Now I see there is another issue related to this. LZ never realized that black O1 group is alive in seki. By taking out the white stones S2 and T2 manually, you can see the black winrate goes up to 90%. In this case black really needs to avoid self atari at all cost. I'm not sure how Leela 0.11.0 handles this.

**Comment by Dorus** [comment]
Tromp taylor rules will deal with it as long as the player is smart enough to not put the stones in self-atari :)

As you can guess, Leela 11 is smart enough to not self-atari.

Leela 11 however not smart enough to score the game correctly. It insists the stones in the lower right are dead.

**Comment by Splee99** [comment]
I have let LZ play white and I played black. LZ didn't play S3 although it was in the list. Until the last dame was filled, LZ still thought white has 75% win rate.

**Comment by alreadydone** [comment]
Maybe you would be interested in analyzing this game, starting from move 293.  996c64b327d54211acfd3cbf521f14b5.sgf
http://eidogo.com/#BP6pU7eO:0,292
The lower-right white groups were dead but black played self-atari (twice!) but white didn't seize the opportunities. Finally black captured the smaller white group and escaped from a dangerous situation. The result of the match had swung back and forth within these few moves. Maybe the groups were just too long for the network to count their liberties.

**Comment by Dorus** [comment]
Q10 - T11 and black can approach without self Atari.

I also tried it and i get

```
  T2 ->    2744 (V: 82.74%) (N: 20.21%) PV: T2 Q1 A1 T11 R1 J19 T1 D18 H11 K9 H10 A13 F15 D15 R15
  T1 ->     310 (V: 81.39%) (N: 10.11%) PV: T1 Q1 F19 D18 R1 E19 T2 D19 H11 G19 H10
  Q1 ->     180 (V: 79.77%) (N: 11.85%) PV: Q1 T11 A1 A13 T10 T9 Q10 D18 T10
```
Q1 is only the third choice, T2 is 15x more likely to be played.

I'm more worried about the fact white does not find N1. Probably the group is too large for white to find the Atari and it thinks it is an invalid move.

```
  6   0   0   0   0   4   7   0  59   6   5   2   3   6   5   4   4   4   2 
  5   0   0  96   0   0   0   0   0   0  13   0   0   0  17   5   5   7  17 
  4   7   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   3 
  2   3   0   0   0   0   5   3   4   0   0  19   5   0   0   0   0   0   0 
  3   0   0  18   0  35   0   0   0   0   0   0   0   0   0   0   0   0   0 
  0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 
 90   0   3   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0  43   0   0   0   0   0   0   0   0   0   0  67 
  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  10   0   0   0 
  3   3   0   0   0   0   0   0   0  64   0   0   0  10   3   0   0   0   0 
  6   2   0   0   0   0   0   0   0   0   0   7   5   3   2   0   0   0   0 
  2   0   0   0   0   0   0   0   0   0   0   0   8   3   0   0   0   0   0 
  7   5   0   0   0   1   0   2   0   0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   2   0   0   0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 
  0   0   0   1   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0 
  0   0   0   1   2   0   0   0   0   0   0   0   0   0   0   0   0   0   1 
108   0   0   1   2   3  27  11   6   0   0   0   0   0   0   0   0   0   7 
pass: 5
winrate: 0.019972
```
As you can see, it has a heat of zero.

I tried to pump playouts, and it ran into the 50 seconds limit. Once i removed that too, it did find N1 after 24k playouts.

**Comment by Splee99** [comment]
With the latest weight, 830158693c473f9a7ac28970d43b6b1e80d7c980ffe10efb1cea813346e33e6b, Leela found N1 for the move 294 after 1578 playouts. Same for move 297 after 1716 playouts. For move 300 it took longer, 5525 playouts to find the move N1. Not bad for this new weight.

**Comment by Dorus** [comment]
So it was a weight problem and nothing to do with the search? If so this sounds resolved.

**Comment by MartinDevelopment** [comment]
It was never a problem to begin with. The stronger the network gets the easier it will be able to see these moves.

**Comment by Splee99** [comment]
My original seki is still not recognized. Not sure if new weight can help Leela to see seki.

**Comment by roy7** [comment]
Eventually the neural network might learn how to detect and handle seki. That's probably an advanced thing to learn later on though. LZ only learned better use of ladders a few days ago after all. ;)
