### ISSUE TITLE
Should noise be allowed to induce a serious blunder?

### ISSUE THREAD

**Issue by LetterRip** [gcp/leela-zero#542]
I suspect that the noise is causing blunders that are turning won games into lost games - that might be having two results.

1) she is less able to correctly evaluate the outcomes of games for her value function - since a game sample from before a blunder should result in a won game; but the result after the blunder is likely to be a lost game.

2) the value function will skew her to take moves such as filling captures that are unnecessary because due to the above blunders the value function is much more certain once a capture is taken.

Essentially she is learning that she has to protect against future blunders by  capturing as soon as feasible.

This suggests we should perhaps prevent the noise from inducing serious blunders - or alternatively make note of games with blunders and only allow positions sampled after the blunder to be used for the value function.

It might also be useful to go back through games in the current window and do an extremely fast check for blunders and annotate them.

**Comment by ggPeti** [comment]
Noise is useful exactly because it makes it possible to learn what a blunder is. Also, what you are proposing is to introduce human domain knowledge into a "zero" project. Leela Zero is "A Go program with no human provided knowledge."

**Comment by LetterRip** [comment]
"Noise is useful exactly because it makes it possible to learn what a blunder is. Also, what you are proposing is to introduce human domain knowledge into a "zero" project. Leela Zero is "A Go program with no human provided knowledge."

That isn't why we introduce noise.  Noise is so that the exact same sequence of moves isn't played every time, it is not meant to introduce blunders but rather to increase exploration of the move space.

The blunders are being injected by the humans (she makes blunders on her own as well, but she can learn from her own blunders since they are a result of faulty evaluation) and the noise induced blunders are likely corrupting her data and making it harder for her to learn.

**Comment by joseph-ireland** [comment]
Well the noise isn't added to play explicitly (except in the first few moves?) but to the search space. If the refutation of a blunder is given 0% probability by the network, then it won't be explored in the search, and the network can never learn to refute that blunder. The noise allows a chance for the MCTS to discover the blunder during self-play at the cost of an overall weaker, more thinly-spread search - but thats the price to pay. 

In my opinion, killing stones early is something else entirely. My guess is that even though it can read that the stones can't escape with mcts, it hasn't yet learned they are 100% dead in its evaluation network. This would mean that after its limited search, when it gets to the leaf nodes and stops looking ahead, it values taking the stones off the board more than risking them escaping in the distant future to play an alternate move. Once the raw network (without MCTS) learns they can never escape, then it will think its ok to leave them on the board for later.

**Comment by ggPeti** [comment]
There's aji - No stone is 100% dead until they are removed from the board. (They take away a liberty from their neighbors, so they can act as a tool for double atari or damezumari, they can be a ko threat factory, they can be revived when the opponent is overloaded by a double threat etc. etc.)

Both this and the original suggestion seems to revolve around the idea of efficient play. I agree that efficiency is key for a strong AI - but so is robustness. Any AI is only as strong as its weakest weakness. By having noise at all times during self-play we actually enable Leela Zero to see through the noise and learn the really important points of the game.

**Comment by gcp** [comment]
We're following the AGZ paper here. Note that the later papers use noise throughout the whole game, so that would be even "worse".
