### ISSUE TITLE
How to limit the time spent for each move when LZ runs in GTP mode?

### ISSUE THREAD

**Issue by michaelfu** [gcp/leela-zero#544]
I am playing with LZ's latest network in Sabaki by running it in GTP mode. However, LZ spends a lot of time thinking for each move. How can I make it move faster?

is setting --lagbuffer 2000 going to allow it to move in 2 seconds? I tried it but seems not work.

Thanks!

**Comment by MartinDevelopment** [comment]
No, you need to enter the GTP command time_settings

**Comment by roy7** [comment]
Use --playouts X --noponder where X is how many playouts per turn to allow. --lagbuffer is just a buffer on the max thinking time to account for network delays.

**Comment by michaelfu** [comment]
Thanks!
