### ISSUE TITLE
Possible performance gain with MSVC 2017/64bit

### ISSUE THREAD

**Issue by bood** [gcp/leela-zero#547]
Which MSVC version is used to build the release version? 
It is reported that with MSVC 2017/64 bit, performance is increased a bit (maybe around 20%).
I think current release is in 32 bit format.

I don't have any current data for comparison (will update when I have), but it is reported by quite a few people here.

**Comment by bood** [comment]
Machine: GTX 760  + i7 920

Version 0.9|speed ms/move
-|-
official|5538
MSVC 2017/32bit|4748
MSVC 2017/64bit|TBD

**Comment by gcp** [comment]
The official compile already is with MSVC2017 in 32 bit mode.

The only important thing really is the OpenBLAS version that is used. OpenBLAS is much better in 64-bit mode if you have an AVX capable CPU, because its AVX kernels only work in 32-bit mode.
