### ISSUE TITLE
Windows Bluescreen

### ISSUE THREAD

**Issue by FineArtz** [gcp/leela-zero#548]
When I ran autogtp.exe, my computer suddenly broke down. This happened twice in just three days.
  The version is AutoGTP v8 and it shows that leela.exe is run with `-r 1 -g -t 1 -q -d -n -m 30 -w 58da61769a5fb12ff555ee927f16b50d4c24de73a1170a85df1b0d2d706bdef3 -p 1600 --noponder `.
  What's the reason, or, how can I fix it?

**Comment by Dorus** [comment]
Probably a hardware or driver problem - software should never be able to cause blue screens - but software can be the trigger.

I would start off with updating the video card drivers and if that doesn't work, look into motherboard drivers.
