### ISSUE TITLE
About CUDA

### ISSUE THREAD

**Issue by KID1412999** [gcp/leela-zero#550]
Is there any plan of doing support with the   "CUDA"  (one of computing platform) ?

**Comment by gaieepo** [comment]
These are people working on that #196 
But for compatibility-wise, cudNN implementation is not applicable for all the agents.

**Comment by gcp** [comment]
To get a real speedup from CUDA one would need to use cuDNN but the license does not allow redistribution. Just using CUDA provides no benefit over OpenCL.
