### ISSUE TITLE
Increase selfplay diversity

### ISSUE THREAD

**Issue by marcocalignano** [gcp/leela-zero#552]
I was thinking that even if some network do not pass the SPRT test their ELO rating is still really close or even better then the current best network  (f2a66bb7). We could use these networks to generate 5% or 10% of selfplayed games to add diversity to the training set. 
With the /next autogtp client this would be ease to achieve. Every hour the server can queue 140 (since we have 1410 games/hour) games with the different network.

**Comment by evanroberts85** [comment]
Yea this occured to me to, I think it is a good idea.

**Comment by RavnaBergsndot** [comment]
I think this might work better when the progress slows down significantly. Currently there are always several older networks in the training window and they already provide a lot of variety.

**Comment by gcp** [comment]
The noise should make this useless. That said, if you buy this argument, I think I can make a strong argument to just always use the newest network as per the latest AZ paper. (It allows the trainer to "see" why a configuration with a low loss is still "bad" in strength)
