### ISSUE TITLE
work with smartgo

### ISSUE THREAD

**Issue by ThorAvaTahr** [gcp/leela-zero#553]
Is there a way to get this version of leelaz.exe to work as a gtp engine for Smartgo (version 3.1.3.) on windows?

(obscured user name:)

C:\Users\ ... \Downloads\leelazero\leelaz.exe

I have added the following options:
--gtp --weights "C:\Users\ ... \Downloads\leelazero\58da61769a5fb12ff555ee927f16b50d4c24de73a1170a85df1b0d2d706bdef3"

I get "_gtp not working_"

**Comment by d7urban** [comment]
SmartGo requires a dummy option as the first option. Just add anything (I use “leelaz”) before the gtp option.

**Comment by ThorAvaTahr** [comment]
thanks, that works!
