### ISSUE TITLE
Mismatch of game result between the website and the game sgf

### ISSUE THREAD

**Issue by Cabu** [gcp/leela-zero#556]
in 2018-01-04 08:58 | 6bc0a66b VS 55bf55dc I picked the game 5 | f2409a73f32dc7dc1706e41c2cef6ecb2d5844c4580fe4ba3d38aafc1b99ea37 | 55bf55dc | B+Resign | 158
but the viewer said the result is W+8.5 for a game where the end game has not been played out and white is clearly in a position to resign.
The sgf of the game start with: "(;GM[1]FF[4]RU[Chinese]DT[2018-01-04]SZ[19]KM[7.5]PB[Leela Zero 0.9 55bf55dc]PW[Leela Zero 6bc0a66b]RE[**W+8.5**];B[pd];W[pp];...".
The score in the sgf doesn't seem to represent the real score of the game...

**Comment by gcp** [comment]
There's a bug in the SGF writing on the master branch, where the score gets recorded as on the board instead of marking the resignation. This is fixed in master. The stored result in the DB is correct.
