### ISSUE TITLE
suggest encrypt the game data upload

### ISSUE THREAD

**Issue by hz86** [gcp/leela-zero#558]
game data encryption upload
train the client to merge autogtp.exe and leelaz.exe
use vmprotect to protect the client
ensure game data security!

**Comment by gcp** [comment]
Easily hacked by anyone motivated enough to care.

**Comment by Neverever** [comment]
This is an "Open Source" project.
Whatever encryption you put on game data, hackers can do the same encryption on corrupted game data.

**Comment by hz86** [comment]
Yes, it can not defend hackers, but it can prevent some of the troublemakers.
Training dedicated client encryption algorithm closed source.
Or find a way to solve malicious uploads
