### ISSUE TITLE
AutoGTP for Windows v2

### ISSUE THREAD

**Issue by kris-computer-go** [gcp/leela-zero#56]
I just finished a 1st AutoGTP game on my PC.
Since a NN is on early stage it requires not to huge resources - in my case CPU 20-30% GPU 5-10%.
So I've started 4 instances of AutoGTP at one time and now CPU usage is 100% and GPU 20-30%.

The question is if that's OK for the building the NN?

**Comment by jillybob** [comment]
I have noticed this too.  With one instance, CPU was ~40% and GPU was 10% usage. I now have 3 instances of AutoGTP running.

**Comment by gcp** [comment]
The program runs at fixed setting so it doesn't hurt to run multiple copies.
