### ISSUE TITLE
feature request: upload games when time limit is reached

### ISSUE THREAD

**Issue by alreadydone** [gcp/leela-zero#563]
Now that it seems that I will be able to keep contributing games through Big Red II in the foreseeable future, I would like to request the following feature of `autogtp` tailored to the supercomputer situation. The problem is that every job running on Big Red II will be aborted after a certain time limit set by the user at the time of job submission. When the job is aborted, all unfinished games will be terminated and never got uploaded.
One can argue that if the time limit is very long then the games that are terminated will be negligible. However if I submit a lot of long jobs, my priority will be lowered and the jobs take a lot of time to start running, so it is preferable to submit short jobs. With my current setting of 7h30min jobs running on 105x32=3360 cores, the number of wasted computing power per day is estimated to worth a whopping 3360/2/7.5x24=5376 games (~20% of computing power).
Therefore, in order to use the least amount of resource to generate as many games as possible, the best solution I can think of is to upload games when a time limit, passed to `autogtp` through a command line option, is reached. Then the server can hand out incomplete games for other clients to finish.
Meanwhile, I think it may be worth adding to the popular Windows client the following feature: when one attempts to close the `autogtp` window, automatically upload any unfinished games. This way, when people want to release their computing resources, they can safely close the window instead of hanging it by selecting texts and be sure their work is not lost.

**Comment by roy7** [comment]
At the moment the clients/servers don't support resuming partially finished games though. Only complete games get uploaded at all.

**Comment by marcocalignano** [comment]
I have an half implementation of resuming interrupted games, but I still didn't solve how to tell autogtp to stop the execution. Probably with a timeout option I could do save all the games and at the next start I can send all the completed games and resume the games from the hard drive. 
The question @alreadydone can you start the process after the timeout came? and if yes do you have access to the same  HD space you had in the previous process?
Also if you sysadmin does not allow to run multiple process on the same GPU you won't be able to do matches. 
I think if I do create a supercomputer autogtp I also need access to one unless you want to get my untested code and test it yourself.

**Comment by prusswan** [comment]
For now, a prompt or option to finish current jobs and quit would be useful. That way the program can be shut down in advance without losing work in progress.

**Comment by marcocalignano** [comment]
Since @gcp wants to release the /next branch soon and the solution for saving and resuming games is still unstable I think we will have that in the next /next branch

**Comment by alreadydone** [comment]
@prusswan The 32 instances on the same CPU node won't finish at the same time though. For GPU nodes this is less a problem, since 5-6 instances should fully occupy the GPU.

**Comment by killerducky** [comment]
> 3360/2/7.5x24=5376 (~20% of computing power).

You calculated based on how many games you actually submit per day? Which implies you get 5376*4 = 21.5K games per day? How long does it take a CPU to do one game? 

My calculation is (assuming you can do 1 game in 10 minutes):

Every 7:30=450 minutes, every CPU does an average of 45 games, and loses the last game which is on average 50% complete. So I get you lose (0.5/90) = 5.6% of your computing power.

To get up to losing 20% of computing power it would mean your CPUs only do 1 game in ~35 minutes, is that right? I guess it could be right since CPUs are slower...

**Comment by alreadydone** [comment]
@marcocalignano It looks like a wonderful solution to save interrupted games locally. Yes, all processes within all jobs have access to the same hard drive space. Every process saves sgf files in the same directory if `-k` is enabled.
What do you mean by "start the process after the timeout came"? If `autogtp` can launch `leelaz` it should be able to launch another process as well.
Maybe you can test you code on any Linux system. I don't think Cray Linux Environment is much different from more common Linux distributions. I am also willing to test it.
I learned about the option to only get self-play tasks, so I can switch to the /next branch autogtp even if I can't run two leelaz on GPU nodes.

**Comment by marcocalignano** [comment]
@alreadydone my question is after the process time comes to an end the system will stop autogtp. 
If you issue a new aprun command the new autogtp process will have access to the smae file like the previous

**Comment by jjoshua2** [comment]
Being able to save progress locally will help everyone who wants to use their computer to play games off and on too!

**Comment by zediir** [comment]
If this is corrent https://kb.iu.edu/d/avkm it should be possible to save it to the home directory and resume from there.

**Comment by alreadydone** [comment]
[**@killerducky**](https://github.com/killerducky) commented on [2018年1月4日 GMT-5下午5:16](https://github.com/gcp/leela-zero/issues/563#issuecomment-355414832 "2018-01-04T22:16:47Z - Replied by Github Reply Comments"):
> > 3360/2/7.5x24=5376 (~20% of computing power).
> 
> You calculated based on how many games you actually submit per day? Which implies you get 5376*4 = 21.5K games per day? How long does it take a CPU to do one game?
> 
> My calculation is (assuming you can do 1 game in 10 minutes):
> 
> Every 7:30=450 minutes, every CPU does an average of 45 games, and loses the last game which is on average 50% complete. So I get you lose (0.5/90) = 5.6% of your computing power.
> 
> To get up to losing 20% of computing power it would mean your CPUs only do 1 game in ~35 minutes, is that right? I guess it could be right since CPUs are slower...

Your calculation is off by a decimal point, 0.5/90 = 0.56%. These CPUs actually run far slower than you expect: one move takes ~32.5s for a each core and 3 hours are needed to finish one game on average (~335 moves). So 2.5 games are played during 7.5 hours and 0.5 games are wasted, yielding 0.5/2.5=20%.
In addition, the computing power wasted from network updates is 3 hrs/2 x frequency of updates, that is 6.25% assuming one update per day.

**Comment by sethtroisi** [comment]
This is just my opinion but I'm hoping I can convince you: It's inefficient to the point of being wasteful to run on CPUs / cloud.

I've done two analysis one on [cloud](https://www.reddit.com/r/cbaduk/comments/7j2sm9/running_leela_zero_on_google_compute_010game/dr3y9fx/) and one on older [GPUs](https://www.reddit.com/r/cbaduk/comments/7n4j8j/1_day_1451_games_7kwh_050/dryzikh/)

CPUs are not efficient at these calculations and it has real costs (in dollars, opportunity costs, setup costs, and to the environment*), please only run Leela on modernish GPUs.


*Indiana has very dirty sources[[1]](http://www.indiana.edu/~energyut/utilities/energy-usage/index.shtml)[[2]](https://www.eia.gov/state/analysis.php?sid=IN), "Indiana is the nation’s third largest coal consumer"

**Comment by alreadydone** [comment]
@marcocalignano Maybe the following plan works.
I think it's easy for autogtp write moves from each game to a separate file as the game progresses, but the files need to be locked so that another instance of autogtp won't pick up it to resume. When the time limit is reached and autogtp is terminated abnormally, hopefully the file automatically gets unlocked and any newly launched autogtp instance in a newly started job (maybe immediately, maybe some time later) will be able to pick it up (i.e. lock the file and resume the game); of course it should pick up the earliest file that is not locked, and if it runs with say -g 3 then it needs to pick up 3 files.
Complete games can be uploaded right away; I don't see any point to keep them and wait for the next autogtp to upload them.

**Comment by alreadydone** [comment]
@sethtroisi  
I don't think the energy consumption of a CPU is much greater than that of a GPU. Currently because I can only run one instance of leelaz on each GPU, the speed is only 1.86 s/move on a GPU, while it is 2.03 s/move on a CPU (16-core), not a big difference. Of course once I am able to run multiple instances I would much prefer GPUs, since they can do <0.84 s/move if fully occupied. Also, recently almost all GPUs on BRII are occupied while many CPUs are idle. The supercomputer is maintained by the university and they have a [system](https://kb.iu.edu/d/avmu#fair) to fairly distribute resources among researchers, and I just want to use it as efficient as possible when I am able to use it. I am now doing 1-day jobs so waste due to time limit is less significant (~6.25%).
I am interested in running your modification #196 for CUDA and cuDNN since these are installed on BRII, but I think I still need to install Theano. The GPUs in BRII are set in EXCLUSIVE_PROCESS mode and trying to run a second instance of leelaz will yield an error on clCreateContext. It looks like that your implementation only has one process (python) accessing GPU, so it may work fine on BRII, and I may give it a try at some point.

**Comment by sethtroisi** [comment]
@alreadydone, I'm like r/theydidthemath too much so here's some more data.

**Theoretically**
Top500[[1]](https://www.top500.org/system/178067) Big Red II has peak real performance of 597 TFlop/s and power consumption of 458 KW => 1.3 GFlops/watt

GTX 1080Ti[[2]](https://www.anandtech.com/show/11172/nvidia-unveils-geforce-gtx-1080-ti-next-week-699
) has peak performance of 11.3 TFlops/s and power consumption of 250 Watts = 45 GFlops/watt

This is a **35x difference in efficient**

I assume average power is lower for big red and 1080Ti Flops are lower but it's still looks like an order of magnitude less efficient.

**Experimentally**

Big Red is using "AMD Opteron 16-core Abu Dhabi x86_64 CPUs"[[1]](https://kb.iu.edu/d/bcqt) which appear to be 
AMD Opteron 6378s[[2]](https://www.newegg.com/Product/Product.aspx?Item=N82E16819113320), which have a TPD of 116 Watts[[3]](http://www.amd.com/en-us/products/server/opteron/6000/6300). 1.0 s/move/CPU Node[[4]](https://github.com/gcp/leela-zero/issues/458#issuecomment-355349648) * 335 moves/game * 2*100 Watts/CPU Node = 18.61 watt-hours/game (doesn't include any overheads)

GTX 1080TI + i5[[1]](https://www.reddit.com/r/cbaduk/comments/7n4j8j/1_day_1451_games_7kwh_050/
) = 7.03 kWh / 1451 games = **4.85 watt-hours/game**

This isn't an apples to apples comparison (you're getting the 40% speed up from cache-nn and winograd, and I'm getting the 260% speedup from cuDNN), but at the end of the day it's costing 4x as much energy for games trained, which in the end is completely dwarfed by the hypothetical opportunity costs (I've spent 20minutes writting this and that time could pay for all the electricity we're both going to use in the near future) so maybe this is a moot point for reasonable CPUs.


Extras,
[Bloomington](https://www.electricitylocal.com/states/indiana/bloomington/) vs [Seatle](https://www.electricitylocal.com/states/washington/seattle/) power rates

**Comment by jkiliani** [comment]
While I agree with @sethtroisi in theory about the power efficiency issue, sadly we don't have a whole bunch of big companies or universities owning supercomputers with GPU capacity supporting this project so far, and have to be glad for any support we get.

Hopefully for a future run with an Alphago dimensioned neural net, we'll have at least some industry support (Is there any chance some big tech companies are going to significantly donate GPU cycles, or international Go organisations, etc.?)

**Comment by ggPeti** [comment]
Let's not confuse separate things.

It is autogtp's job to generate and upload leelaz self-play data.
It is not autogtp's job to handle its own suspension or termination.

I'd look into your system's job schedule policy and tooling to see if there's already a solution to save process state. If there isn't, maybe try [CRIU](https://criu.org/Main_Page). Only by keeping the UNIX principle of one program for one task is it possible to build large, robust, extendable systems.

**Comment by killerducky** [comment]
@alreadydone If it takes 3 hours to do a game, how about submitting jobs to the pool that just request one CPU, do one game, and exit? I assume the job scheduler would support such a model?

**Comment by marcocalignano** [comment]
I have a version of autogtp with an option -t where you can specify a timeout (in minutes).
At the end of this timeout the current games are save on the hard drive (on the next move) and then exit.
On the next execution the game are resumed and continued. The only thing I want to test it and I see there are people here that can tell if a game is bad or not. (I do not see it much). Can I upload two game to the server so that you can check them if they seems ok or not?

**Comment by alreadydone** [comment]
Why not post the games? I may be able to identify some obviously problematic moves, and some people can run leelaz and try to reproduce the move once a suspicious move is identified. (https://github.com/gcp/leela-zero/issues/491, https://github.com/gcp/leela-zero/issues/540) Do you want us to compare moves before and after resuming?

**Comment by marcocalignano** [comment]
http://zero.sjeng.org/view/5ae0c2d56a7229da27f8e3888d4d88cd58eb43d75ac219823e09f26448e3d50f?viewer=eidogo

The interruption was at move 9

**Comment by marcocalignano** [comment]
No the interruption was at move 25 and there are two black moves 
@roy7 can you delete this game from the DB? I will save them locally from now on till I fix this bug.

**Comment by roy7** [comment]
@marcocalignano Deleted.

**Comment by alreadydone** [comment]
disregarding the double move at 25, move 128 looks bad to a human player, but it looks like black wins anyway. (The game is no longer accessible; I found that there is no way to save the sgf from the game viewer, but saving the page works.)

**Comment by marcocalignano** [comment]
@alreadydone after I find this bug I can give you a branch you can test with on you super machine

**Comment by alreadydone** [comment]
@marcocalignano Thanks!

**Comment by marcocalignano** [comment]
@roy7 Thanks!

**Comment by alreadydone** [comment]
Saving games locally is the better way to go. See #726.
