### ISSUE TITLE
Questions for developers who are also Go players, what are your ranks?

### ISSUE THREAD

**Issue by Neverever** [gcp/leela-zero#564]
As title.

In the AlaphaGo documentary movie, the dev team had limited knowledge about the game of Go, that's why they got Fan Hui (2P) into the team as adviser.

Just wondering for you all great developers, do you play Go? and what are your ranks?

**Comment by roy7** [comment]
I'm 13k on OGS. :)

**Comment by marcocalignano** [comment]
I am 19k on OGS :(

**Comment by MartinDevelopment** [comment]
I am 1d kgs

**Comment by Alderi-Tokori** [comment]
6k OGS !

**Comment by zediir** [comment]
14k OGS tough I haven't played for more than a year so I'm probably worse now.

**Comment by OmnipotentEntity** [comment]
I peaked at 2k on DGS.  I probably can't claim much higher than 6k currently.  I haven't seriously played in over 3 years.

**Comment by Cabu** [comment]
I was up to 8k on KGS. I am more around 10k now as I didn't played since some time.
