### ISSUE TITLE
Is it possible add komi as a input feature to leelazero?

### ISSUE THREAD

**Issue by zliu1022** [gcp/leela-zero#565]
Glad to see @gcp  has made decision to open sources leelazero and thanks all the contributor. As a go fans, my go-zero-dream will become true because of you. All of you are my hero.

Maybe it's an enhancement after I read AGZ paper, is it possible to add komi as input feature to CNN network. And the value head still output win or loss. I don't know whether it can work or not. Because as a go fans, I like the software still appear aggressive even in end-game or win rate is more than 90%, if there is komi input feature, at that time, komi can increase until winrate down to maybe 70%.

Is it possible? Is there anyone think about it?
Now leelazero is 5b64f, maybe in the future it will be increased to 6b128f or more, is it possible to add this idea at that time?

Thank you.

**Comment by evanroberts85** [comment]
Yea it is possible, and I think it should be considered for the next run when this project is more or less finished.

 I think you could train output for predicted score (and score confidence?) along with value and policy outputs. That way you could choose how greedy Leela is.
