### ISSUE TITLE
Live and Test server differ in assigning tasks

### ISSUE THREAD

**Issue by marcocalignano** [gcp/leela-zero#568]
Now mt autogtp is running on the live server with this url 
`zero.sjeng.org/get-task/7` and I get the following json:
```
{
  cmd: "match",
  required_client_version: "10",
  random_seed: "15659784512160555693",
  leelaz_version: "0.9",
  options: {
    playouts: "1600",
    resignation_percent: "1",
    randomcnt: "0",
   noise: "false"
 },
  options_hash: "321436",
  white_hash: "55bf55dcd0471f87db8521883cc3ab27bd64f50d191177542ce5da9872dc9ddd",
  black_hash: "505410a46f990ce734d22c8c040d38bbcf56fd939a2425d90c258258d1f77391"
}
```
options_hash: "321436",
white_hash: "55bf55dcd0471f87db8521883cc3ab27bd64f50d191177542ce5da9872dc9ddd",
black_hash: "505410a46f990ce734d22c8c040d38bbcf56fd939a2425d90c258258d1f77391"
}
but the task is different from the one given by the test server `http://zero-test.sjeng.org/get-task/7` :

```
{
  cmd: "match",
  required_client_version: "10",
  random_seed: "2999381895632309961",
  leelaz_version: "0.9",
  options: {
    playouts: "1600",
    resignation_percent: "1",
    randomcnt: "0",
    noise: "false"
  },
  options_hash: "321436",
  white_hash: "3177eb4936811aefdde4a89d286e468b71379a419ca08802bf970f7d882c3269",
  black_hash: "55bf55dcd0471f87db8521883cc3ab27bd64f50d191177542ce5da9872dc9ddd"
}
```
I am running matches with a old network that already failed.

**Comment by marcocalignano** [comment]
@roy7 could you have a look I always get matches from failed networks

**Comment by roy7** [comment]
The state of counting towards 400 match games is stored in the server process local memory. So when we split traffic, we will get 800 games basically. The two servers don't know what the other is doing.

If I can I'll go set the server to list to both 8080 and 8081 for now so it's all unified and any personal testing I need to do I'll do on a third secret port #.

**Comment by roy7** [comment]
Ultimately the test server is intended just to test things.

**Comment by roy7** [comment]
Ok that worked, whew. Right now a single process is handling both the live and test server web sites/ports. That will fix the match game assignment problem. Once we have a new release out there and noone is using test for live work, I'll split it back off.

**Comment by marcocalignano** [comment]
@roy7 thanks!
