### ISSUE TITLE
Why do games slow down as they increase in number of moves?

### ISSUE THREAD

**Issue by CamWagner** [gcp/leela-zero#57]
At the start of a self-play game, the moves are pretty quick. Why does each turn take longer as the game progresses? (if anything, I would expect them to speed up...)

(Also wow this game is 650+ moves long and still going)

**Comment by gcp** [comment]
The network right now is the smallest possible size, so all kinds of things that are normally completely negligible influence the runtime now. There is nothing that would speed up the program near the endgame (it does not do Monte Carlo game playouts) and some things that slow it down: state tracking to detect superko and a narrower search tree which means that there are more nodes to investigate to find the best move to search.

**Comment by gcp** [comment]
tux3 fixed the largest CPU bottleneck (state tracking for superko) so I think this is no longer a perceptible issue.
