### ISSUE TITLE
Question about UCTNode initialization

### ISSUE THREAD

**Issue by Akababa** [gcp/leela-zero#573]
What are the leaf nodes initialized with? I noticed LZ uses a score from 0 to 1 while AGZ uses a score from -1 to 1 and initializes with 0, which feels kind of arbitrary to me (why assume a draw prior?).

Thanks.

**Comment by Akababa** [comment]
Thanks, that makes a lot more sense

**Comment by gcp** [comment]
>AGZ uses a score from -1 to 1 and initializes with 0

Funnily I think that was missed in a lot of the discussion regarding that change.
