### ISSUE TITLE
Question: Root value calculation

### ISSUE THREAD

**Issue by Akababa** [gcp/leela-zero#579]
What is the root value of the search tree (for ex. the one used for resigning)? I suppose it could be either

- the expected value of the root state, as averaged over its children or memoized
- the largest mean action value amongst its children

However the former doesn't do justice to killer moves (ex. pass to win) and the latter is perhaps subject to positive bias.

Also any thoughts on using this value for training as opposed to the noisy +-1? Maybe an experiment could be run to see if it reduces value overfitting.

**Comment by killerducky** [comment]
It's the score of the best move the search found, same as your second option.
Resign code:
https://github.com/gcp/leela-zero/blob/master/src/UCTSearch.cpp#L252
bestmove is from here:
https://github.com/gcp/leela-zero/blob/master/src/UCTSearch.cpp#L170

**Comment by gcp** [comment]
Using +-1 is vastly superior according to everyone who has ever tested this.
