### ISSUE TITLE
Visual Studio fails to build

### ISSUE THREAD

**Issue by afalturki** [gcp/leela-zero#583]
Hello,

This is the first time I build a project like this with packages, so, I might be doing something stupid.

I'm trying to build the next branch of Leela Zero using Visual Studio 2017 but the solution fails to build. After a lot of looking around, I noticed that Nuget updates the version of Boost to boost.1.66.0.0 which is different from the version specified in the project file (boost.1.65.1.0).

Should the project file be updated to specify the newer version. Also, can I modify the version number myself safely or will there be compatibility problems if I do? 
  
**Update**:

I changed the boost version manually but the build still fails. I get the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6006	"cmd.exe" exited with code 2.	autogtp	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	171

**Comment by afalturki** [comment]
I changed the boost version manually but the build still fails. I get the folloing error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6006	"cmd.exe" exited with code 2.	autogtp	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	171

**Comment by bood** [comment]
I don't understand why VS would update boost for you? `nuget restore` should install the exact version of boost specified in msvc/VS2017/packages.config

**Comment by ericyan71** [comment]
it is because there are no cur.exe and gzip.exe in you project, the "cmd.exe" copy these two files to release directory,  you should download them ,and put them into the directory of "leela-zero/msvc/",

**Comment by Heiseikiseki** [comment]
Hello, I have the same problem. I did copy those two files but build  error with autogtp.
Error MSB6006 "cmd.exe" exited with code 3

**Comment by hz86** [comment]
autogtp Use QT library
1, install qt5.9 
2, vs2017 install qt tools

qt download
http://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe

**Comment by afalturki** [comment]
> I don't understand why VS would update boost for you? nuget restore should install the exact version of boost specified in msvc/VS2017/packages.config

I think you're right. I might have updated the version somehow myself and then got the version difference error.

> it is because there are no curl.exe and gzip.exe in you project, the "cmd.exe" copy these two files to release directory, you should download them ,and put them into the directory of "leela-zero/msvc/",

> autogtp Use QT library
1, install qt5.9
2, vs2017 install qt tools


THANK YOU! It worked! For those interested, the Qt install size is huge, so, make sure you install only what is really needed. Also, after installing the Qt Tools through the Visual Studio Marketplace,  you need to add the Qt version manually through QT VS Tools -> Qt Options, then right-click on the autogtp project, then click on Qt Project Settings and choose the version.

**Comment by barrybecker4** [comment]
How come this extra step is needed for Qt? Everything else was defined and downloaded based on the sln file. I'm new to VisualStudio - Is marketplace what you get by going to Tools | Extension and Updates | Online | Visual Studio Marketplace? I installed qt5.9 (just used default settings - since I did not know what the minimal set that was needed is) but I don't see anything that mentions Qt listed (even after restarting VS 2017). Can these instructions (whatever they are) be added to the readme for windows setup if they are needed?

**Comment by afalturki** [comment]
> I went to QT VS Tools -> Qt Options, but do not see an autogtp project to right click on. I see 2 tabs: Qt versions (empty) and default settings. Can these instructions (whatever they are) be added to the readme for windows setup if they are needed?

Sorry, my explanation was a bit confusing.
Did you install Qt 5.9.3 first from the link provided by @hz86?

After installing Qt 5.9.3 and Qt VS Tools, go to QT VS Tools -> Qt Options.
Under Qt Versions, click Add. Then, write a version name (5.9.3 for example) and choose the path to the installed Qt version (In my case it was: C:\Qt\5.9.3\msvc2017_64). Then press Ok twice to close the Options.
Open "leela-zero2017.sln", right-click the autogtp project under the Solution Explorer, then, click Qt Project Settings.
Under Properties, change Version to the version name you chose.

I hope this can help.

**Comment by barrybecker4** [comment]
Thanks. that worked. I can build successfully again now. I also selected version 5.9.3 It took about an hour to download and install. Even thought I only checked 5.9.3 when installing, its seems to have downloaded a tremendous amount of stuff - 36G in all! How can we do it without needing to pull that much?

**Comment by afalturki** [comment]
Glad that worked. Personally, I saw that 35GB figure, so, I stopped the install immediately and then started it again. However, I only chose the components I needed which reduced the install size to 8.7GB.

I did that by clicking the arrow to the left of Qt 5.9.3 and choosing the components manually.

What I chose was:

1. MinGW 5.3.0 32bit
2. msvc2017 64-bit
3. Sources

I'm not sure I really need all three but the others seemed unnecessary.

**Comment by afalturki** [comment]
@gcp Should Qt be added to the requirements list in the README file? I don't think knowing Qt is needed is trivial especially for those like me who are not very familiar with the code but are interested in running leelaz and autogtp with the latest improvements.

**Comment by gcp** [comment]
@afalturki Qt is listed as a requirement for AutoGTP: https://github.com/gcp/leela-zero/tree/master/autogtp

It should not be a requirement for Leela Zero.

**Comment by afalturki** [comment]
I see. Thanks for the clarification.
