### ISSUE TITLE
Would it be a good idea to allow multiple networks in "self" play?

### ISSUE THREAD

**Issue by earthengine** [gcp/leela-zero#587]
This idea is to change how the match and self play works.

Right now, only one network will be consider the "winner" and its self play will be used to train the next network.

However, some networks are not so sure to be better or worse than the winner, those are listed in the elo illustration as the "green" points. For me, this means the games played between them may not have less quality than the winner's self play, and as they are maybe good at different aspects it might make the network explore more possibilities.

So my proposal is:

* At any moment a group of networks get selected for reproduction
* The best network will be selected for reproduction automatically
* If a new network played with the "best" network so far have 45% or more win rate, it joins the group for reproduction, but only replace the "best" position if it have 55% or more win rate
* When the system decided to make a "top play" it choose two networks from the reproduction group randomly, and sent to the clients for a play
* The result of the top played games will be added to the statistics, and the game will be used for training the next network
* If any game in the reproduction group have the win rate dropped under 45% vs any other network in the group, it will be kicked off from the group
* Optionally, we can maintain a maximal size of the group, if a new network added to the group and it is full, the weakest network will be kicked off. But I doubt this is necessary as this group is maintained in the server and there are not too many networks for it to maintain.

All those changes happen in the server and no update for current autogtp is required. However, one thing to concern is that the real self play uses only half of the computing resource of the client than a match, so this may slow down the game generation.

A big motivation for this propocal is that the elo rate growth is slowing down right now, so I wonder if more diversity of playing styles may help.

**Comment by Dorus** [comment]
This has been suggested  (and rejected) many times before. For example in https://github.com/gcp/leela-zero/issues/552

#506 is somewhat similar too. The response is always the same:

> gcp commented 7 days ago
> We are following the AGZ paper here.

**Comment by gcp** [comment]
The problem of all these random theories is that there's no evidence they're any better than the most simple methods.

Without strong data that they are an improvement I couldn't be possibly less interested.
