### ISSUE TITLE
Variable komi

### ISSUE THREAD

**Issue by OmnipotentEntity** [gcp/leela-zero#588]
https://arxiv.org/abs/1705.10701

I was considering reworking this paper to function with LeelaZero and creating a pull request.  Assuming the the code quality isn't awful, would this be something that @gcp would be interested in accepting into the code base?

Or is the purpose of leela-zero to just be a reimplementation of AGZ?

This would require a NN retraining, but as you seem to be planning one anyway(?) when moving to 20x256 or 40x256 or something, I thought it might be something to consider.

**Comment by Alderi-Tokori** [comment]
I think if you were to do it, this would pretty much be a separate branch, since it changes entirely the value head and how the mcts behaves. Regardless, it would be very cool to have a leela zero implementing this which is apparently (according to the paper) better.

**Comment by gcp** [comment]
I'm not interested in this at all, and in any case it's not obvious how to integrate this with the AGZ method which requires training the policy network and value network simultaneously, because the optimal policy is very komi dependent.

**Comment by OmnipotentEntity** [comment]
For clarity, are you not interested in the paper, or are you not interested in variable komi?

**Comment by OmnipotentEntity** [comment]
Sorry for pinging you again @gcp, but just for clarity, are you not interested in the concept of variable komi entirely, or are you not interested in only specifically this paper/technique?

**Comment by gcp** [comment]
I'm sorry but this feels a bit like asking me if I'm interested in the concept of world peace.
