### ISSUE TITLE
leela-zero-0.4-windows  not working

### ISSUE THREAD

**Issue by chucklu** [gcp/leela-zero#59]
Hi,
   I  have download the zip file from the release page.
   I unzip it and open the autogtp.exe.
    
   But the autogitp.exe closed automatically,maybe something wrong with it.
   I have check the folder, didd not find any log.

Can you add some log to the exe?

**Comment by marcocalignano** [comment]
First chack the Readme for all the requirement maybe you miss one of the Library

**Comment by SebastienFaurite** [comment]
On Windows 10, autogtp.exe is blocked by smartScreen, I had to temporarily disable it.
There are three option to SmartScreen : Block, Warn and Off.

I was on Warn, so I had an error message. Maybe you are on Block, then it silently close the app.

You can see more info here :
https://www.howtogeek.com/75356/how-to-turn-off-or-disable-the-smartscreen-filter-in-windows-8/

**Comment by chucklu** [comment]
@SebastienFaurite  thanks, I have tiried to turn off the smart screen.
but the exe still exit automatically
![default](https://user-images.githubusercontent.com/3004057/32877477-b1098eda-cadc-11e7-97d5-b110c3e7eace.png)

**Comment by chucklu** [comment]
@SebastienFaurite  thanks, I have tiried to turn off the smart screen.
I believe the dll in folder is enough, but maybe you can help me check it.

$ ls -l
total 27524
-rwxr-xr-x 1 clu 1049089    39936 Nov 16 04:14 autogtp.exe*
-rwxr-xr-x 1 clu 1049089  3157504 Oct 23 13:55 curl.exe*
-rw-r--r-- 1 clu 1049089   236061 Oct 23 13:55 curl-ca-bundle.crt
-rwxr-xr-x 1 clu 1049089   102640 Aug 31 20:17 gzip.exe*
-rwxr-xr-x 1 clu 1049089   841728 Nov 16 03:49 leelaz.exe*
-rwxr-xr-x 1 clu 1049089   120334 Dec 29  2015 libgcc_s_dw2-1.dll*
-rwxr-xr-x 1 clu 1049089 12756285 Jun  3  2016 libopenblas.dll*
-rwxr-xr-x 1 clu 1049089  1540622 Dec 29  2015 libstdc++-6.dll*
-rwxr-xr-x 1 clu 1049089    79360 Dec 29  2015 libwinpthread-1.dll*
-rwxr-xr-x 1 clu 1049089  2983837 Oct  5 21:34 msys-2.0.dll*
-rwxr-xr-x 1 clu 1049089   112382 Aug 31 20:17 msys-gcc_s-1.dll*
-rwxr-xr-x 1 clu 1049089    89600 Oct 26 15:08 OpenCL.dll*
-rwxr-xr-x 1 clu 1049089  6097408 Nov  9 17:08 Qt5Core.dll*
-rw-r--r-- 1 clu 1049089        0 Nov 16 05:09 UNZIP-AND-LAUNCH-THE-AUTOGTP-EXE.txt

**Comment by chucklu** [comment]
@marcocalignano  What did you mean by requirement ?
I just try to run the release package, not compile the sourcecode.
I believe the dll in folder is enough, but maybe you can help me check it.

$ ls -l
total 27524
-rwxr-xr-x 1 clu 1049089    39936 Nov 16 04:14 autogtp.exe*
-rwxr-xr-x 1 clu 1049089  3157504 Oct 23 13:55 curl.exe*
-rw-r--r-- 1 clu 1049089   236061 Oct 23 13:55 curl-ca-bundle.crt
-rwxr-xr-x 1 clu 1049089   102640 Aug 31 20:17 gzip.exe*
-rwxr-xr-x 1 clu 1049089   841728 Nov 16 03:49 leelaz.exe*
-rwxr-xr-x 1 clu 1049089   120334 Dec 29  2015 libgcc_s_dw2-1.dll*
-rwxr-xr-x 1 clu 1049089 12756285 Jun  3  2016 libopenblas.dll*
-rwxr-xr-x 1 clu 1049089  1540622 Dec 29  2015 libstdc++-6.dll*
-rwxr-xr-x 1 clu 1049089    79360 Dec 29  2015 libwinpthread-1.dll*
-rwxr-xr-x 1 clu 1049089  2983837 Oct  5 21:34 msys-2.0.dll*
-rwxr-xr-x 1 clu 1049089   112382 Aug 31 20:17 msys-gcc_s-1.dll*
-rwxr-xr-x 1 clu 1049089    89600 Oct 26 15:08 OpenCL.dll*
-rwxr-xr-x 1 clu 1049089  6097408 Nov  9 17:08 Qt5Core.dll*
-rw-r--r-- 1 clu 1049089        0 Nov 16 05:09 UNZIP-AND-LAUNCH-THE-AUTOGTP-EXE.txt

**Comment by gcp** [comment]
The windows release zip should have all dependencies bundled.

What happens if you run autogtp.exe in a terminal? Do you get any relevant output?

**Comment by chucklu** [comment]
@gcp  I got the following message when I run the exe from cmd
>PS D:\ChuckLu\ProgramFiles\leela-zero-0.4-windows> .\autogtp.exe
autogtp v2
Unexpected output from server:

Could you tell me the server ip? 
I am not sure if I can access your server cause there is a [Great Firewall](https://en.wikipedia.org/wiki/Great_Firewall) in China.

**Comment by chucklu** [comment]
I have search the issues again, find someone met [this](https://github.com/gcp/leela-zero/issues/63) problem before.
I will try to fix it.

**Comment by gcp** [comment]
curl.exe should be included in the windows package.

The server is at http://zero.sjeng.org

It is the same server that hosts the regular Leela. It would be rather sad if it was banned in China!

**Comment by marcocalignano** [comment]
@gcp Maybe you can change the Readme and add that a curl.exe is also required.

**Comment by gcp** [comment]
It's included in the windows package. You can see it in the listing he provided, even.

**Comment by chucklu** [comment]
@gcp  @marcocalignano 
I am trying open the curl.exe with [dependency walker](www.dependencywalker.com).
It seems some dependency files for curl is missing.
I will check the detail.

**Comment by chucklu** [comment]
Missing the following files for curl.exe, have no idea about these files.
Maybe I need install [curl](https://curl.haxx.se/download.html) ?
API-MS-WIN-CORE-APIQUERY-L1-1-0.DLL
API-MS-WIN-CORE-APPCOMPAT-L1-1-1.DLL
API-MS-WIN-CORE-APPINIT-L1-1-0.DLL
API-MS-WIN-CORE-ATOMS-L1-1-0.DLL
API-MS-WIN-CORE-COMM-L1-1-0.DLL
API-MS-WIN-CORE-CONSOLE-L2-1-0.DLL
API-MS-WIN-CORE-CRT-L1-1-0.DLL
API-MS-WIN-CORE-CRT-L2-1-0.DLL
API-MS-WIN-CORE-DATETIME-L1-1-1.DLL
API-MS-WIN-CORE-DATETIME-L1-1-2.DLL
API-MS-WIN-CORE-DEBUG-L1-1-1.DLL
API-MS-WIN-CORE-DELAYLOAD-L1-1-1.DLL
API-MS-WIN-CORE-ENCLAVE-L1-1-0.DLL
API-MS-WIN-CORE-ERRORHANDLING-L1-1-1.DLL
API-MS-WIN-CORE-ERRORHANDLING-L1-1-3.DLL
API-MS-WIN-CORE-FIBERS-L1-1-1.DLL
API-MS-WIN-CORE-FIBERS-L2-1-1.DLL
API-MS-WIN-CORE-FILE-L1-2-1.DLL
API-MS-WIN-CORE-FILE-L1-2-2.DLL
API-MS-WIN-CORE-FILE-L2-1-1.DLL
API-MS-WIN-CORE-FILE-L2-1-2.DLL
API-MS-WIN-CORE-HEAP-L1-2-0.DLL
API-MS-WIN-CORE-HEAP-L2-1-0.DLL
API-MS-WIN-CORE-HEAP-OBSOLETE-L1-1-0.DLL
API-MS-WIN-CORE-INTERLOCKED-L1-2-0.DLL
API-MS-WIN-CORE-IO-L1-1-1.DLL
API-MS-WIN-CORE-JOB-L1-1-0.DLL
API-MS-WIN-CORE-KERNEL32-LEGACY-L1-1-1.DLL
API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-LARGEINTEGER-L1-1-0.DLL
API-MS-WIN-CORE-LIBRARYLOADER-L1-2-0.DLL
API-MS-WIN-CORE-LIBRARYLOADER-L1-2-1.DLL
API-MS-WIN-CORE-LIBRARYLOADER-L2-1-0.DLL
API-MS-WIN-CORE-LOCALIZATION-L1-2-1.DLL
API-MS-WIN-CORE-LOCALIZATION-L2-1-0.DLL
API-MS-WIN-CORE-LOCALIZATION-OBSOLETE-L1-3-0.DLL
API-MS-WIN-CORE-LOCALIZATION-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-MEMORY-L1-1-2.DLL
API-MS-WIN-CORE-MISC-L1-1-0.DLL
API-MS-WIN-CORE-NAMEDPIPE-L1-2-0.DLL
API-MS-WIN-CORE-NAMEDPIPE-L1-2-2.DLL
API-MS-WIN-CORE-NAMESPACE-L1-1-0.DLL
API-MS-WIN-CORE-NORMALIZATION-L1-1-0.DLL
API-MS-WIN-CORE-PERFCOUNTERS-L1-1-0.DLL
API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL
API-MS-WIN-CORE-PROCESSENVIRONMENT-L1-2-0.DLL
API-MS-WIN-CORE-PROCESSSNAPSHOT-L1-1-0.DLL
API-MS-WIN-CORE-PROCESSTHREADS-L1-1-2.DLL
API-MS-WIN-CORE-PROCESSTHREADS-L1-1-3.DLL
API-MS-WIN-CORE-PROCESSTOPOLOGY-L1-2-0.DLL
API-MS-WIN-CORE-PSAPI-ANSI-L1-1-0.DLL
API-MS-WIN-CORE-PSAPI-L1-1-0.DLL
API-MS-WIN-CORE-REALTIME-L1-1-0.DLL
API-MS-WIN-CORE-REGISTRY-L1-1-0.DLL
API-MS-WIN-CORE-REGISTRY-L1-1-1.DLL
API-MS-WIN-CORE-RTLSUPPORT-L1-2-0.DLL
API-MS-WIN-CORE-SIDEBYSIDE-L1-1-0.DLL
API-MS-WIN-CORE-STRING-L2-1-0.DLL
API-MS-WIN-CORE-STRING-OBSOLETE-L1-1-0.DLL
API-MS-WIN-CORE-STRINGANSI-L1-1-0.DLL
API-MS-WIN-CORE-SYNCH-L1-2-1.DLL
API-MS-WIN-CORE-SYSINFO-L1-2-1.DLL
API-MS-WIN-CORE-SYSINFO-L1-2-3.DLL
API-MS-WIN-CORE-SYSTEMTOPOLOGY-L1-1-0.DLL
API-MS-WIN-CORE-THREADPOOL-L1-2-0.DLL
API-MS-WIN-CORE-THREADPOOL-LEGACY-L1-1-0.DLL
API-MS-WIN-CORE-THREADPOOL-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-VERSION-L1-1-0.DLL
API-MS-WIN-CORE-WINDOWSERRORREPORTING-L1-1-0.DLL
API-MS-WIN-CORE-WOW64-L1-1-0.DLL
API-MS-WIN-CORE-WOW64-L1-1-1.DLL
API-MS-WIN-CORE-XSTATE-L2-1-0.DLL
API-MS-WIN-EVENTING-CLASSICPROVIDER-L1-1-0.DLL
API-MS-WIN-EVENTING-CONSUMER-L1-1-0.DLL
API-MS-WIN-EVENTING-CONTROLLER-L1-1-0.DLL
API-MS-WIN-EVENTING-OBSOLETE-L1-1-0.DLL
API-MS-WIN-EVENTING-PROVIDER-L1-1-0.DLL
API-MS-WIN-SECURITY-APPCONTAINER-L1-1-0.DLL
API-MS-WIN-SECURITY-AUDIT-L1-1-1.DLL
API-MS-WIN-SECURITY-BASE-L1-2-0.DLL
API-MS-WIN-SECURITY-BASE-PRIVATE-L1-1-1.DLL
API-MS-WIN-SECURITY-GROUPPOLICY-L1-1-0.DLL
API-MS-WIN-SERVICE-CORE-L1-1-1.DLL
API-MS-WIN-SERVICE-CORE-L1-1-2.DLL
API-MS-WIN-SERVICE-MANAGEMENT-L1-1-0.DLL
API-MS-WIN-SERVICE-MANAGEMENT-L2-1-0.DLL
API-MS-WIN-SERVICE-PRIVATE-L1-1-1.DLL
API-MS-WIN-SERVICE-PRIVATE-L1-1-2.DLL
API-MS-WIN-SERVICE-WINSVC-L1-2-0.DLL
API-MS-WIN-CORE-COM-L1-1-1.DLL
API-MS-WIN-CORE-DELAYLOAD-L1-1-0.DLL
API-MS-WIN-CORE-IO-L1-1-0.DLL
API-MS-WIN-CORE-LOCALIZATION-L1-1-0.DLL
API-MS-WIN-CORE-LOCALREGISTRY-L1-1-0.DLL
API-MS-WIN-CORE-REGISTRY-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-VERSION-PRIVATE-L1-1-0.DLL
API-MS-WIN-DEVICES-CONFIG-L1-1-1.DLL
API-MS-WIN-DEVICES-QUERY-L1-1-1.DLL
API-MS-WIN-POWER-BASE-L1-1-0.DLL
API-MS-WIN-POWER-SETTING-L1-1-0.DLL
API-MS-WIN-SECURITY-CREDENTIALS-L1-1-0.DLL
API-MS-WIN-SECURITY-CREDENTIALS-L2-1-0.DLL
API-MS-WIN-SECURITY-LSALOOKUP-L1-1-1.DLL
API-MS-WIN-SECURITY-LSALOOKUP-L2-1-1.DLL
API-MS-WIN-SECURITY-LSAPOLICY-L1-1-0.DLL
API-MS-WIN-SECURITY-PROVIDER-L1-1-0.DLL
API-MS-WIN-SECURITY-SDDL-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-EVENTINGCONTROLLER-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-NPUSERNAME-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-NTMARTA-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-REGISTRY-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-SAFER-L1-1-0.DLL
EXT-MS-WIN-APPXDEPLOYMENTCLIENT-APPXDEPLOY-L1-1-0.DLL
EXT-MS-WIN-APPXDEPLOYMENTCLIENT-APPXDEPLOYONECORE-L1-1-0.DLL
EXT-MS-WIN-AUTHZ-CONTEXT-L1-1-0.DLL
EXT-MS-WIN-CORE-WINRT-REMOTE-L1-1-0.DLL
EXT-MS-WIN-DOMAINJOIN-NETJOIN-L1-1-0.DLL
EXT-MS-WIN-FECLIENT-ENCRYPTEDFILE-L1-1-0.DLL
EXT-MS-WIN-GPAPI-GROUPPOLICY-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-APPCOMPAT-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-DATETIME-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-ERRORHANDLING-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-FILE-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-QUIRKS-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-QUIRKS-L1-1-1.DLL
EXT-MS-WIN-KERNEL32-REGISTRY-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-SIDEBYSIDE-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-WINDOWSERRORREPORTING-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-WINDOWSERRORREPORTING-L1-1-1.DLL
EXT-MS-WIN-KERNELBASE-PROCESSTHREAD-L1-1-0.DLL
EXT-MS-WIN-MRMCORER-RESMANAGER-L1-1-0.DLL
EXT-MS-WIN-NTDSAPI-ACTIVEDIRECTORYCLIENT-L1-1-0.DLL
EXT-MS-WIN-NTDSAPI-ACTIVEDIRECTORYCLIENT-L1-1-1.DLL
EXT-MS-WIN-NTUSER-MESSAGE-L1-1-1.DLL
EXT-MS-WIN-NTUSER-STRING-L1-1-0.DLL
EXT-MS-WIN-NTUSER-SYNCH-L1-1-0.DLL
EXT-MS-WIN-NTUSER-WINDOW-L1-1-1.DLL
EXT-MS-WIN-PROFILE-EXTENDER-L1-1-0.DLL
EXT-MS-WIN-PROFILE-LOAD-L1-1-0.DLL
EXT-MS-WIN-RPC-SSL-L1-1-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-SYSPARAMS-L1-1-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-WINDOW-EXT-L1-1-0.DLL
EXT-MS-WIN-SECURITY-CAPAUTHZ-L1-1-0.DLL
EXT-MS-WIN-SECURITY-CHAMBERS-L1-1-0.DLL
EXT-MS-WIN-SECURITY-EFSWRT-L1-1-1.DLL
EXT-MS-WIN-SHELL32-SHELLCOM-L1-1-0.DLL

**Comment by gcp** [comment]
These are AFAIK all part of the operating system.

Does the curl.exe work if you run it from the command line?

**Comment by chucklu** [comment]
@gcp  I can run the following command 
```cmd
PS D:\ChuckLu\ProgramFiles\leela-zero-0.4-windows> .\curl.exe --help
Usage: curl [options...] <url>
     --abstract-unix-socket <path> Connect via abstract Unix domain socket
     --anyauth       Pick any authentication method
```

**Comment by gcp** [comment]
It does not look like curl is the problem then.

The first thing autogtp does is call
curl.exe http://zero.sjeng.org/best-network-hash

and right now that should return
e6779c9becc10a7e147d3cb9c5177a45d3659f95856cd7199d98d0f9ecaf156e
1

**Comment by chucklu** [comment]
I  got timeout error message
PS D:\ChuckLu\ProgramFiles\leela-zero-0.4-windows> .\curl.exe http://zero.sjeng.org/best-network-hash
curl: (7) Failed to connect to zero.sjeng.org port 80: Timed out

**Comment by gcp** [comment]
Looks like you are firewalled :(

**Comment by chucklu** [comment]
But I can access the site, http://zero.sjeng.org.
Leela Zero is available from: Github.
A total of 19609 games have been submitted.
307 clients have submitted games.

**Comment by gcp** [comment]
I don't really understand how that can be. It is the exact same server, obviously.

**Comment by chucklu** [comment]
@gcp  I have a proxy ,which can run the command without timeout.
I  read the article [here](https://stackoverflow.com/questions/17819524/curl-through-proxy-syntax) 
.\curl.exe -x proxyhost:proxyport http://zero.sjeng.org/best-network-hash

Is it possible for you to support the proxy setting?
Maybe you can add a configuration file for user to configure the proxy.
When the autogcp.exe run ,you can read the proxy and use it for curl.exe

**Comment by gcp** [comment]
You can configure the proxy with an environment variable: http_proxy
Best to look at the curl docs for more information.

**Comment by chucklu** [comment]
I have add the http_proxy environment variable manually, and it works now.
![default](https://user-images.githubusercontent.com/3004057/32883449-68f0d714-caf2-11e7-97e5-c82092346322.png)

**Comment by chucklu** [comment]
@gcp  BTW, if you can output the timeout error message, it would be better.
