### ISSUE TITLE
leela-zero-0.10-cpuonly-win32.zip has no autogtp file

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#596]
I must also download leela-zero-0.10-win32.zip and replace files in that file.

AutoGTP v11
Using 1 thread(s) for GPU(s).
Starting thread 1 on GPU 0
{
    "cmd": "selfplay",
    "hash": "fca07541ac1c113dc9fb222f77c9fc52bc6100dce7a584dbde641ffe54499387",
    "leelaz_version": "0.9",
    "options": {
        "noise": "true",
        "playouts": "1600",
        "randomcnt": "30",
        "resignation_percent": "1"
    },
    "options_hash": "16b7b7",
    "random_seed": "6222607078752915720",
    "required_client_version": "10"
}

Got new job: selfplay
Net filename: fca07541ac1c113dc9fb222f77c9fc52bc6100dce7a584dbde641ffe54499387
net: fca07541ac1c113dc9fb222f77c9fc52bc6100dce7a584dbde641ffe54499387.
Engine has started.
Infinite thinking time set.

**Comment by l1t1** [comment]
and the file libopenblas.dll in two zip files are  identical
C:\leela10>fc /b libopenblas.dll libopenblas.dll_old
正在比较文件 libopenblas.dll 和 LIBOPENBLAS.DLL_OLD
FC: 找不到差异

**Comment by gcp** [comment]
This is intentional. There's no point in running the AutoGTP client if you don't even have 64-bit capability. It's extremely slow.

**Comment by l1t1** [comment]
@gcp if cpu version only leelaz file is diffrent,you can rename the zip file to leelaz.0.10.zip and remove dll from zip

**Comment by l1t1** [comment]
I run the cpuonly version, it does work with only two files in zip and a weight file. thanks.
