### ISSUE TITLE
0.10 crashes randomly

### ISSUE THREAD

**Issue by barrtgt** [gcp/leela-zero#597]
-k sgf -g 2
i7-7700K
RX 480

**Comment by jkiliani** [comment]
Could this be a case of a failed OpenCL check? Did you try to run LeelaZ separately, with full diagnostic output, instead of autogtp?

**Comment by barrtgt** [comment]
I'm not sure what you mean by full diagnostic output.

**Comment by jkiliani** [comment]
autogtp always runs leelaz in quiet mode, i.e. with console output suppressed. A while back, a self-check was implemented in next branch that tested whether OpenCL network evaluations were internally consistent. If not, leelaz exits with a warning, but that warning may be suppressed by quiet mode from autogtp. This self-check just went live with 0.10, so if you ran the 0.9 master branch up until now, the crash may mean your OpenCL was bugged all along.

**Comment by barrtgt** [comment]
Is there any way to run games back to back with leelaz? It gives me an error right away for -t 3:
`BLAS : Program is Terminated. Because you tried to allocate too many memory regions.`
It takes some time for the crash to happen with -g 2 with autogtp, and I cannot get the same result after a single game with leelaz.

**Comment by killerducky** [comment]
Are you on windows? Linux? Try this for Linux, I think it works for windows also but I forgot:

`echo "auto" | ./leelaz <args>`

That will cause leela to play a game against itself. You could run multiple of those in parallel to stress the system. Use some appropriate script to run them in a loop.

**Comment by barrtgt** [comment]
Running 3 instances of -t 2 gives me 
`Error in OpenCL calculation: expected 0.014708 got 0.000000 (error=1370.826782%)
Update your GPU drivers or reduce the amount of games played simultaneously.`
Not sure how to loop it for the 2 instance case.

**Comment by MaxMaki** [comment]
Got the newest drivers for the RX 480? If yes, have you overclocked the GPU or the CPU?
Update drivers, remove all overclocking on CPU and GPU and try if it still crashes randomly.

**Comment by barrtgt** [comment]
Currently running 17.12.1, which was released last month. I can try the newest optional 17.12.2, which means it's sort of a beta driver. No mention of OpenCL changes, but it's worth a shot.

**Comment by killerducky** [comment]
While it's too bad @barrtgt cannot run LZ, it's great news that the OpenCL bug auto detection logic is working! Otherwise barrtgt would have no idea he is submitting bad games.

IMO we should always assume there is some bug before entertaining conspiracy theories.

**Comment by barrtgt** [comment]
How often does it self-check? If the amount of moves that it produces a error is low enough, it will still provide enough valuable data. If I can't run -g 2, I could just do -g 1, which I think would be even more stable.

**Comment by bood** [comment]
The error message should not be suppressed even in quiet mode

**Comment by killerducky** [comment]
How about instead you run the bot on kgs or something? You would still contribute something but not risk injecting bad data.

IMO people with known buggy drivers should not run autogtp, but maybe @gcp can make an official statement about this.

**Comment by barrtgt** [comment]
We are improving with half the games being bad so I've heard. If a client is producing 99% good moves, it will be more beneficial to contribute than not I believe.

**Comment by MaxMaki** [comment]
barrtgt, have you overclocked the cpu or the gpu? if you have, disable those and try.
Overclocking might easily give random wrong computations.

If you haven't, why don't you try with -g1 instead and see if it crashes, if it still crashes after that it might be a good idea to not run it until the reason is found.

**Comment by barrtgt** [comment]
All stock, currently running with the 17.12.2 for the last hour and -g 2. Perhaps an executable to self-check extensively every move without uploading would be a good option for people before they run autogtp.

**Comment by gcp** [comment]
>IMO people with known buggy drivers should not run autogtp, but maybe @gcp can make an official statement about this.

I would think that inserting the self-check with the warning was a clear enough about that, but it seems not. Obviously you should not be knowingly submitting garbage!

**Comment by jkiliani** [comment]
@barrtgt It's unfortunately not correct that with "99% good moves" you'll still contribute. Each move includes 1600 NN calculations, which means that there's 16 playouts that can be anything from "slightly outside error margin" to completely wrong. The closer to the root node the faulty calculation happens, the more damage to the quality of the resulting search tree. So it is reasonable to exclude such clients from the distributed effort, although the exact calculation of when a mismatch happens will probably evolve further (It will have to for releasing Winograd transform pull request).

**Comment by bood** [comment]
I think the problem is the error message got suppressed when running with
autogtp

**Comment by jkiliani** [comment]
I agree, and I hope that the code gets changed in such a way that error messages (whether self-check fail, memory problem or something else) is output even with quiet mode.

@marcocalignano Would this be an easy fix?

**Comment by marcocalignano** [comment]
Is it an issue of `autogtp` or of the `-q` option in leelaz?

**Comment by bood** [comment]
-q option should not suppress the error message IMO

**Comment by jkiliani** [comment]
I just compiled the new master branch with standard options on my mac to test this (knowing it would fail OpenCL self-check). Starting autogtp, my output was

AutoGTP v11
Using 1 thread(s) for GPU(s).
Starting thread 1 on GPU 0
{
    "cmd": "selfplay",
    "hash": "65e94e52aea49bbe88b57b40a3bee6e689e9abbd94a69da8371d090d2ee69f07",
    "leelaz_version": "0.9",
    "options": {
        "noise": "true",
        "playouts": "1600",
        "randomcnt": "30",
        "resignation_percent": "0"
    },
    "options_hash": "cf1fad",
    "random_seed": "627319357659954597",
    "required_client_version": "10"
}

Got new job: selfplay
net: 65e94e52aea49bbe88b57b40a3bee6e689e9abbd94a69da8371d090d2ee69f07.
Engine has started.
Infinite thinking time set.
1 (B D16) 2 (W Q16) 3 (B H1)

At this point it quit with no message. When I started LeelaZ with no options other than the weight file, I got:

Leela: genmove B
Thinking at most 50.0 seconds...
NN eval=0.475274
Error in OpenCL calculation: expected 0.233134 got 0.000000 (error=23213.438416%)
Update your GPU drivers or reduce the amount of games played simultaneously.
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: OpenCL self-check mismatch.

When starting LeelaZ manually with -q, I got: 

Leela: genmove B
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: OpenCL self-check mismatch.
Abort trap: 6

So it seems autogtp is currently not configured to pass on exceptions thrown by LeelaZ.

**Comment by marcocalignano** [comment]
@jkiliani  please run leelaz again but this time adding the -q option see if the Error output is still printed.

**Comment by jkiliani** [comment]
I already did, that's the third test I posted. Running leelaz with -q will throw: 

Leela: genmove B
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: OpenCL self-check mismatch.
Abort trap: 6

**Comment by marcocalignano** [comment]
@jkiliani please go to https://github.com/gcp/leela-zero/blob/fbade9fcc8cb4746f9111213c1df1c7840136501/src/Network.cpp#L448 and https://github.com/gcp/leela-zero/blob/fbade9fcc8cb4746f9111213c1df1c7840136501/src/Network.cpp#L450 adn change `myprintf` with `printf`, recompile leelaz and try again with autogtp

**Comment by bood** [comment]
The other problem seems to be that autogtp is not reading from stderr of
leelaz. I can see from the code that only `readLine` is used, which read
from stdout only.

**Comment by gcp** [comment]
@marcocalignano let me know if you need a leela-side fix to detect this in autogtp.

**Comment by jkiliani** [comment]
@marcocalignano, @gcp printf did the trick: New output with autogtp:

AutoGTP v11
Using 1 thread(s) for GPU(s).
Starting thread 1 on GPU 0
{
    "cmd": "selfplay",
    "hash": "65e94e52aea49bbe88b57b40a3bee6e689e9abbd94a69da8371d090d2ee69f07",
    "leelaz_version": "0.9",
    "options": {
        "noise": "true",
        "playouts": "1600",
        "randomcnt": "30",
        "resignation_percent": "0"
    },
    "options_hash": "cf1fad",
    "random_seed": "16881595755172810460",
    "required_client_version": "10"
}

Got new job: selfplay
net: 65e94e52aea49bbe88b57b40a3bee6e689e9abbd94a69da8371d090d2ee69f07.
Engine has started.
Infinite thinking time set.
*ERROR*: Error in GTP response.
Error read 79 'Error in OpenCL calculation: expected 0.101121 got 0.140710 (error=39.150918%)
'
*ERROR*: Error in GTP response.
Error read 77 'Update your GPU drivers or reduce the amount of games played simultaneously.
'

**Comment by marcocalignano** [comment]
@gcp Yes the fix I mention above would works.
