### ISSUE TITLE
Accurate Anchored Elo

### ISSUE THREAD

**Issue by LetterRip** [gcp/leela-zero#598]
If we are interested in an accurate Elo comparison.  We could do simulations versus the specific versions and time controls listed in the paper.

5 seconds on 4 TPUs is 20,000 playouts (based on 1,600 payouts in .4 seconds - I could be miscalcuating since it might be 1,600 playouts per TPU in .4 seconds, in which case 4 TPU would be 80,000 playouts).

Here are the settings used in the first AlphaGo paper.  We can just use Fuego, Pachi, GnuGo, and the handicapped version of Pachi.

Short name	Player		Version		Time settings	CPUs	GPUs	KGS Rank	Elo

αdrvp		DistriBAlphaGo	See Methods	5 seconds 	1202 	176	N/A		3140
αrvp		AlphaGo 	See Methods	5 seconds	48	8 	N/A		2890
CS		CrazyStone	2015		5 seconds	32	N/A	6d		1929
ZN		Zen		5		5 seconds	8 	–	6d		1888
P C		Pachi 		10.99		400,000 sims	16 	N/A	2d		1298
F G		Fuego 		svn1989		100,000 sims 	16 	N/A 	N/A		1148
GG		GnuGo 		3.8		level 10	1 	– 	5k		431
CS4		CrazyStone	4 hcap stones	5 seconds	32 	N/A 	N/A 		2526
ZN4		Zen		4 hcap stones	5 seconds	8 	N/A 	N/A 		2413
P C4		Pachi		4 hcap stones	400,000 sims	16 	N/A 	N/A 		1756

**Comment by gcp** [comment]
See #480 and #555 etc.
