### ISSUE TITLE
The score maybe wrong in the evaluation match result

### ISSUE THREAD

**Issue by zliu1022** [gcp/leela-zero#599]
I check the match between 391 vs 763 for fun.
2018-01-06 10:43 | 391d850e VS 76347a12 | 232 : 186 (55.50%) | 418 / 400 |  
And find one match below
[1 | 033502ebf995545ac195bdd4e0cc2abfe94276b8fbd803c4f29d10f7654d80f8 | 76347a12 | B+2.5 | 319](http://zero.sjeng.org/viewmatch/033502ebf995545ac195bdd4e0cc2abfe94276b8fbd803c4f29d10f7654d80f8?viewer=wgo)
As the game was counted as Trump Taylor Rule rule, the result was B+2.5, but if it's counted as Chinese rule, it will be W+0.5.
So I guess if we use Chinese rule to judge evaluation match, we will get different result, maybe a little fast speed to upgrade weight.

And as AGZ paper, "However, all tournament and evaluation games were scored using Chinese rules.:", I think we'd better put this match result as Chinese rules.

**Comment by isty2e** [comment]
If my understanding is correct, the tournament and evaluation serve for rating calculation, not promotion. Also, the Chinese rule is not well defined for some cases, so I suppose it could not be used, at least for the early stage of the training.

**Comment by gcp** [comment]
Chinese rules can't be used for incomplete games. The AGZ paper talks about Chinese rules because some of the test opponents likely didn't support proper Trump Taylor.
