### ISSUE TITLE
0.10 Does not accept more than 2 threads with -t option

### ISSUE THREAD

**Issue by jillybob** [gcp/leela-zero#600]
Argument: -g -t 4 -r 10 -w 65e94e52aea49bbe88b57b40a3bee6e689e9abbd94a69da8371d090d2ee69f07 -p 20000 --noponder

https://i.imgur.com/z9Kmg04.png This is the console output I get, when I play my first move ( I am black). Zero stalls at "Thinking at most 50 seconds".

I have tried 0.9 with all the same settings and it works.

**Comment by MaxMaki** [comment]
Remove the -t 4 and it'll work i think. At least for me.

**Comment by jillybob** [comment]
Yes that works, thanks. I was checking CPU usage and it seems that it uses all threads of the CPU when -t is removed.

**Comment by killerducky** [comment]
@jillybob can you try running leelaz from a terminal with the same options (include the -t 4), and then type "auto" on the Leela prompt. Leela will play itself and you might see some error message if/when it crashes. Also if you add -l logfile you can upload the logfile here.

**Comment by jillybob** [comment]
Here is the result

https://i.imgur.com/7jkA1r7.png
I did try and add -l logfile but it did not record anything to it.

**Comment by gcp** [comment]
This looks like a bug in the used OpenBLAS for the Windows compiles.

**Comment by gcp** [comment]
This should be fixed by v0.10.1.

Even though Leela uses OpenBLAS in single thread mode, single-thread compiles seem broken, perhaps due to https://github.com/xianyi/OpenBLAS/issues/1253.
