### ISSUE TITLE
bug, (maybe), resignation_percent 0

### ISSUE THREAD

**Issue by Matuiss2** [gcp/leela-zero#601]
I have 10 instances of autogtp running now, but in one of then the resignation_percent is set to 0 when all other 9 are being set to 1, Is it intentional or is just a bug? 

All other instances(set as 1) have 6 games avg played already and the one that is set as 0 is starting the 2° game right now, so is kind of a big deal

**Comment by bood** [comment]
This is intentional, 10% (or 20% maybe) of the self-play games do not allow resign.

**Comment by Matuiss2** [comment]
Thanks

**Comment by marcocalignano** [comment]
But why not run one instance on autogtp with the option -g 10?
