### ISSUE TITLE
0.10 cpu version can't use more than 2 threads

### ISSUE THREAD

**Issue by zliu1022** [gcp/leela-zero#604]
I tried the latest 0.10 cpu version. Only -t 1 and -t 2 worked very well. But -t 3 or -t 4 will terminate.
When it runs well with 2 thread, system still has 50% empty memory.
It said "allocate too many memory", so for threads more than 2, how many memory will it need?

leelaz.exe -g -t 3 -w d:\go\leela-zero-0.9\weight\657f91c714d41ea1d0cf86ec5c2f1e69650cff3ee551dcf046b0062e4a285010
... ...
Thinking at most 50.0 seconds...
NN eval=0.370777
Playouts: 182, Win: 44.59%, PV: D16 C17 C16 B16 B17 B18 B15
Playouts: 374, Win: 45.78%, PV: D4 C3 D16 S4 C4
Playouts: 569, Win: 46.05%, PV: D4 C3 D16 S4 C4
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
Playouts: 738, Win: 46.18%, PV: Q4 R3 Q16 B4 R4

**Comment by jillybob** [comment]
This is the same as issue #600
