### ISSUE TITLE
How to get more good randomness?

### ISSUE THREAD

**Issue by Marcin1960** [gcp/leela-zero#606]
I was thinking about a proposal, made recently on the forum - to increase
noise in order to get new solutions.

I know (as a biologist) that random mutations are extremely inefficient, but
nonrandom mutations are much better.

My proposal is to accept new networks when they pass 50% level, no matter
how much. That way one can reduce sterilization of possible innovations, before
they take root, come closer to the AlphaGo Zero model, etc ...

Perhaps the "best network" by the present criteria is not really the best for generating new self-play games?

**Comment by MartinDevelopment** [comment]
Or we can be like AlphaZero and accept all new networks.

**Comment by Marcin1960** [comment]
@MartinDevelopment "and accept all new networks"

My proposal is an intentional compromise. To follow AlphaZero and preserve the current bias
in favor of better students.

**Comment by gcp** [comment]
Not interested at all, won't be implemented.

**Comment by Marcin1960** [comment]
Larger network? What parameters would you consider?
