### ISSUE TITLE
Failed to run leelaz 0.10 on WinXP

### ISSUE THREAD

**Issue by linffen** [gcp/leela-zero#607]
When I try to test leelaz-0.10-cpuonly on WinXP running on my laptop,
a pop-up window tells me that  leelaz.exe is not a valid Win32 application.
I know WinXP has been obsoleted, but someone like me still sticks to it.
It is delightful that leela-0.11.0 works well on WinXP. Why do not leelaz?
Are there any technical difficulties?

**Comment by gcp** [comment]
Windows XP requires using a specific toolchain and does not properly support modern C++ features that we require.
