### ISSUE TITLE
Where can i find new file Weights.txt after Zero train 18000 games? Need Zero for each level.

### ISSUE THREAD

**Issue by kityanhem** [gcp/leela-zero#61]
I think we should have a weights file for each stage like 10k games, 14kgames, 18k games, 20k games. And set it level. Not just build a strongest Zero. We need Zero for each level.
I played with Leela Zero when Zero is 3k on kgs. It's really excited.

**Comment by OmnipotentEntity** [comment]
A few million games will be required at least to get a good network.  Right now the engine is still playing almost randomly.  And because networks don't learn like humans do, 10kyu rated networks won't play like a human and won't really be good for humans to learn from.

**Comment by gcp** [comment]
http://zero.sjeng.org/networks has all the networks.

The networks don't magically appear after a set number of games, see issue #1 for how the training procedure works.

Zero is closer to 50 kyu right now than it is to 3 kyu. I think you played with a bot that used a network trained with supervised learning (i.e. from human games, so playing humanlike).
