### ISSUE TITLE
Is there any way to verify leelaz version?

### ISSUE THREAD

**Issue by pheasant75** [gcp/leela-zero#611]
I have pulled new changes and compiled it under ubuntu.  However, when I run it, I saw the message like:
Starting thread 1 on GPU 0
{
    "cmd": "selfplay",
    "hash": "65e94e52aea49bbe88b57b40a3bee6e689e9abbd94a69da8371d090d2ee69f07",
    "leelaz_version": "0.9",
    "options": {
        "noise": "true",
        "playouts": "1600",
        "randomcnt": "30",
        "resignation_percent": "1"
    },
    "options_hash": "16b7b7",
    "random_seed": "15666869194140759895",
    "required_client_version": "10"
}
Does it mean my leelaz version is still 0.9?

**Comment by isty2e** [comment]
The field name is misleading a bit, but it is actually the required leelaz version.

**Comment by jkiliani** [comment]
required client version refers to the version of autogtp, not the version of leelaz, and the new release has autogtp version 11.

**Comment by gcp** [comment]
Type "version" in the leelaz executable.

**Comment by pheasant75** [comment]
./leelaz -version doesn't work.  
Anyway, I am confident that I am running the updated version.  Since I did every step (pull, compile leelaz, compile autogtp, copy leelaz to autogtp folder).

**Comment by isty2e** [comment]
It is not passing the version as an argument. After you execute leelaz with any network file, you can type commands, such as "version".
