### ISSUE TITLE
0.10.1 reports "leelaz_version": "0.9"

### ISSUE THREAD

**Issue by JDJoe** [gcp/leela-zero#613]
0.10.1 reports "leelaz_version": "0.9"

**Comment by isty2e** [comment]
If you are referring the 0.9 to that in

```
{
    "cmd": "selfplay",
    "hash": "fca07541ac1c113dc9fb222f77c9fc52bc6100dce7a584dbde641ffe54499387",
    "leelaz_version": "0.9",
...
}
```

something like this, it does not mean that your leelaz version is 0.9.

**Comment by JDJoe** [comment]
Yes, this is what I was referring to. 
"leelaz_version" in not leelaz version? Rename it to shoe number or something :) 

Cheers!

**Comment by gcp** [comment]
It's the leelaz version requested by the server, not what you have.
