### ISSUE TITLE
-g and -k options ???

### ISSUE THREAD

**Issue by Voyz84** [gcp/leela-zero#614]
Where and How can i "specify the -g (-k) option" Please, i want to save games.

**Comment by zediir** [comment]
If you are on windows you can create a autogtp.bat-file in the same folder as your leelazero installation with the following content

`start autogtp.exe -g 4 -k sgf` and run that instead of autogtp.exe. Alternatively you can start autogtp from the windows commandline with the same options

**Comment by Voyz84** [comment]
Thx, ^^
