### ISSUE TITLE
Request: Stop at 128K steps rather than 256K steps

### ISSUE THREAD

**Issue by WhiteHalmos** [gcp/leela-zero#615]
Now that games are coming in almost twice as fast, what about switching back to training until 128K steps rather than waiting for the 256K steps network?

We are testing every 30k+ self-play games whereas Deepmind tested every 25k. It has been shown during the last month that testing more frequently results in more improvement.

**Comment by Dorus** [comment]
Just some number:

We're now at 4.4% match games. Possibly this will go down a little more depending on how many more people can upgrade.

A cycle takes 9,5 hours and 256k steps take about 4 hours. Removing that step would put us at 4,5 hours so we almost double the % of match games.

9.5/4.5*4.4% = 9.3%
(9.5/6)/(4.5/5)=1.75

So we would end up with about 9.3% match games and would generate 1.75 times as many networks.

**Comment by gcp** [comment]
30k is about where we want to be, I think.
