### ISSUE TITLE
Upload failed but Game data stored in database

### ISSUE THREAD

**Issue by SebastienFaurite** [gcp/leela-zero#617]
Hi,

I have got this uploading error. What is strange to me is that it says the data is stored in database. So what is he trying to do ?

Uploading game: 3872c8e5f3904e8199470f9e6581e1c9.sgf for network ffc1e51bf64e21e8b6504d9501c748d5e15534642d81b92a684f9d4456a77a8b
Game data e65bfacc82145d15b95d6cfc38d570b0ced5453f0afc8ede030ae4b7d095a54a stored in database
Upload failed. Curl Exit code: 7
Network connection to server failed.
NetworkException: Curl returned non-zero exit code 7
Retrying when next game is finished.

**Comment by gcp** [comment]
Connection lost while trying to perform a clean tear-down of the connection? Sounds like a non-issue.
