### ISSUE TITLE
CPU version may not suit for Test Matches

### ISSUE THREAD

**Issue by pangafu** [gcp/leela-zero#618]
Many CPU run a game longer than 30 minute, but many Network will failed in 50 match, it may just cost less then 10 minute. So we can see many test match still increased even network failed long long ago, that waste a lot.

Suggest disallow CPU version get test match job, or the slower client don't get test match job, just play self-game is ok.

**Comment by pangafu** [comment]
For example, before CPU version , test match end quickly， only 5 games or less waste.
2018-01-06 21:25	6e887fe3 VS 391d850e	6 : 43 (12.24%)	49 / 400	fail
2018-01-06 20:24	c60c525b VS 391d850e	3 : 43 (6.52%)	       46 / 400	fail

After CPU version, about 50 or more games waste in a test match.
2018-01-09 01:54	546ad2bf VS ffc1e51b	12 : 128 (8.57%)	140 / 400	fail
2018-01-08 10:53	de3d8758 VS 65e94e52	7 : 143 (4.67%)	150 / 400	fail

**Comment by marcocalignano** [comment]
@roy7 is already working on this on the server side see #545

**Comment by gcp** [comment]
On a modern Haswell/Skylake/Coffee Lake, the CPU version isn't much slower, or can be faster, than an old or tiny GPU. So filtering by CPI only solves nothing.
