### ISSUE TITLE
A simple question about tfprocess.py

### ISSUE THREAD

**Issue by isty2e** [gcp/leela-zero#619]
I have mainly used Torch instead of TF, so I am a bit not used to it. When trying to run some experiments, I was bit unsure about total loss. In TFProcess.process(), mse_loss is devided by 4.0 to scale into [0, 1] and to calculate the average loss. So the loss values are printed out in
```
print("step {}, policy={:g} mse={:g} reg={:g} total={:g} ({:g} pos/s)".format(
                steps, avg_policy_loss, avg_mse_loss, avg_reg_term,
                avg_policy_loss + avg_mse_loss + avg_reg_term,
                speed))
```
where in the total loss the mse_loss is scaled by 0.25. But the self.train_op is defined to minimize the total loss without scaling mse_loss (which is the correct behavior), so the actual total loss to be minimized and the printed total loss are different. Is my understanding correct?

**Comment by gcp** [comment]
Yes. In the display output the total={:g} sum should undo the MSE scaling to be correct. I'll fix that.

**Comment by gcp** [comment]
This will make it unintuitive that total= does not match the sum of the previous parts but we'll have to live with that if we want the MSE output to be comparable to most published stuff.
