### ISSUE TITLE
LeelaZ resign too 'easily' while playing handicap games

### ISSUE THREAD

**Issue by Cabu** [gcp/leela-zero#622]
LeelaZ resign too 'easily' while playing handicap games (I tested for >=5 stones) leaving no time to let the weaker player (me ~10kyu) to make my first big mistake or enough little mistake to nullify the stones advantage.
Could it be feasible to offset the winrate with a function of the handicap and the number of played move?

**Comment by killerducky** [comment]
Try "--resign 1" to lower the threshold from the default 10% to 1%. There are probably some code improvements we could do but that should get you going right away.

**Comment by gcp** [comment]
Resigning is already capped to not happen early in the game. As said above, when playing with handicap you probably want a much lower threshold than the default.

**Comment by gcp** [comment]
Maybe if no resignation threshold is specified, the engine could divide 10% by the number of handicap stones or something.

**Comment by Cabu** [comment]
I like that idea. I though about something more complex where the threshold get back up as the game move to the end. But simply dividing by the number of stone is easy and should work.

**Comment by sethtroisi** [comment]
Code would go here if you want to write a pull request https://github.com/gcp/leela-zero/blob/fbade9fcc8cb4746f9111213c1df1c7840136501/src/UCTSearch.cpp#L253

something like 

```
auto default_threshold = (float)cfg_resignpct / 100.0f;
auto handicap_threshold = resign_threshold / (1 + m_rootstate.get_handicap());
// Blend default_threshold with reduced handicap_threshold based on number of moves into game
auto blend_ratio = max<float>(1.0, ((float) m_rootstate.get_movenum()) / (0.6 * m_rootstate.board.get_boardsize() * m_rootstate.board.get_boardsize()));
auto resign_threshold = handicap_threshold + (default_threshold - handicap_threshold) * blend_ratio;
```

**Comment by gcp** [comment]
I don't want to override the behavior of the user specifies the resign percentage, as that would be even more confusing. Alternatively, we could change the description in the options to make it clear it is a kind of "base" percentage.

**Comment by sethtroisi** [comment]
What do you suggest for checking if the user has specified a resign percentage?

I can test if cfg_resignpct == 10 but this is duplicating the default value (10).
I can add another global default_resignpct.
or something else ...

**Comment by gcp** [comment]
Default it to -1 and check for that? Maybe a bit ugly, but I don't immediately know a better way.

>Also should resign rate be reduced when Leelaz is playing for the side who received the handicap?

No. (And I guess not the opposite either!)

**Comment by killerducky** [comment]
I'm in favor of changing the description of the --resign option because it will match what most users intuitively think of for resigning handicap games: "10% chance to win, taking into account how a handicap game usually plays out". Using the blending as in #626 is a proxy for this intuitive statement.

**Comment by RavnaBergsndot** [comment]
I have an idea: when playing handicapped games, how about we keep the resign threshold, but use a weaker network to model the weaker opponent in MCTS? For example, a simulation could look like this:

root (strong network) -> child (weak network) -> grandchild (strong network) -> ... -> leaf

I think it follows the same mindset when humans play handicapped games: stronger player would try to trick the weak player by having a mental model of "what might a weaker player do".

**Comment by Phelanpt** [comment]
> I think it follows the same mindset when humans play handicapped games: stronger player would try to trick the weak player by having a mental model of "what might a weaker player do".

For the record, the above is poor handicap gameplay skills. Proper handicap play as white doesn't rely on tricks, but on complicating the game. Trying to trick a weaker player by using their mentality induces bad habits as much as trying to use tricks against opponents of your own strength. 
This is an aside, though, as I don't know if it has any relevance to how to get LeelaZero to adjust better to handicap games. The approach above might be valid.
A "complicate the game" branch selection approach might not be feasible, as I don't think we have an easy measure of what the right complicated moves might be. 
(It just occurred to me that it might be possible to compare the highest and lowest win probabilities for the opponent responses, and choose the move that has the biggest difference between highest and lowest? Again, I don't know enough about the code to know if this approach is feasible)
