### ISSUE TITLE
when runing LZ, my 1080ti slower than 1060, why?

### ISSUE THREAD

**Issue by ericyan71** [gcp/leela-zero#623]
hello, I meet a strange problem, I have two old computer, one with 1080ti and the other with 1060, when I test them by using AIDA64, the single FLOPS of 1080ti is 12T, the one of 1060 is about 4.6T, that's very ok, but when I run leealz, or training a small network for testing, 1080ti is slower than 1060 by about 15%, I'm totally confused,  although the problem do nothing with LZ, I hope somebody can help me, thanks.

**Comment by Neverever** [comment]
how many games did you run to conclude that 1080ti is 15% slower than 1060 ?

It could be that your 1060 have encountered more "ladder" games (usually ended in < 100 moves)

P.S. I wish I have an "old" computer with 1080 ti on it

**Comment by ericyan71** [comment]
my 1080ti is always slower than 1060. for testing speed, I made a neuro network like AGZ, 5 block 64 filters with two head, and run this network 1000 times on two computers, 1080ti is still slower than 1060, maybe my computer main board is bad?

**Comment by marcocalignano** [comment]
Are the CPU and the opencl Nvidia driver he same on both computer?
