### ISSUE TITLE
Compress weight file using xz?

### ISSUE THREAD

**Issue by thynson** [gcp/leela-zero#625]
Most people in China do not have a very good connection to zero.sjeng.org. 

My PC connects to zero.sjeng.org at a speed of around 20k/s-30k/s, compressing a weight file using xz will reduce filesize  in around 400k, from around 2.8M to 2.4M. This could let the computers spend more time in selfplay and matches.

**Comment by thynson** [comment]
Using a Free CDN should be a better idea, but at least Cloudflare didn't serves well in China, due to GFW :(

**Comment by gcp** [comment]
A 16% reduction isn't worth it.

For what it's worth, I wanted to use zstandard for all compression in this project, but we ran into the problem very quickly that Ubuntu LTS ships with a zstd that cannot read files produced by the current version (it is not backwards compatible), so we settled on gzip.
