### ISSUE TITLE
How about change reward function of leela-zero in new turn

### ISSUE THREAD

**Issue by pangafu** [gcp/leela-zero#627]
In alphago zero paper, when game is end,  the game is then scored to give a final reward of rT∈ {−1,+1}. and in many computer go program match, we can see computer hold back when it gain huge superiority. 

So maybe we can change final reward bound with final score。For example, we can make base reward is {-10(loser), 10(winner)}, and add win score (+3.5 for example), so the last reward is {-13.5, 13.5}. If pass resign, we can set reward is {-20, 20}. in the last we can normalize reward to (-1.0, 1.0) when needed.

So the network we trained should tend to get higher reward, avoid to get lower reward, 
1. in the superiority situation , program tend to win more, and not hold back. 
2. In bad situation(when lose score large then 10), program should tend to pass resign. 
3. In balance situation( score in -10, 10), program tend to play to end, fight to get high score.

That maybe more reasonable for go program.

**Comment by gcp** [comment]
I'm not exactly sure what you're saying but including the score in the calculated value typically makes programs far weaker, because they will play losing lines that have a small probability of winning by a big amount.

**Comment by gcp** [comment]
If someone can demonstrate a working version that does not make the program weaker, I might be interested, but the odds are against you.
