### ISSUE TITLE
MCTS--virtual loss

### ISSUE THREAD

**Issue by panda0307** [gcp/leela-zero#631]
Somebody help.
AGZ paper says that it uses virtual loss to ensure each thread evaluates different nodes.
And what does "virtual loss" means? How it works? Does LZ use it?
Thanks a lot.
（Method => Search algorithm => Backup）

**Comment by kiudee** [comment]
The virtual loss is a small loss applied by a thread entering a subtree. While a mutex blocks all other threads from entering, a virtual loss will only deter them if the subtree is not very promising.

LeelaZero also a virtual loss as defined in `VIRTUAL_LOSS_COUNT` in UCTNode:
```C++
    // When we visit a node, add this amount of virtual losses
    // to it to encourage other CPUs to explore other parts of the
    // search tree.
    static constexpr auto VIRTUAL_LOSS_COUNT = 3;
```

**Comment by gcp** [comment]
The main point is that virtual loss spreads out the threads though the search tree. With a mutex one thread would be searching, and the others just spinning the lock.

**Comment by FrankRouter** [comment]
Why virtual loss is not used in computing puct?
