### ISSUE TITLE
Using ResNeXt instead of ResNet?

### ISSUE THREAD

**Issue by ayssia** [gcp/leela-zero#633]
ResNeXt is an improved version of ResNet. 

https://arxiv.org/abs/1611.05431
"In particular, a 101-layer ResNeXt is able to achieve better accuracy than ResNet-200 but has only 50% complexity."

https://github.com/facebookresearch/ResNeXt
https://github.com/soeaver/caffe-model/tree/master/cls/resnext

**Comment by jkiliani** [comment]
Interesting read, but time will tell if the approach is applicable for reinforcement learning. If more people end up using this and it becomes the state of the art network architecture, who knows. Is there any indication that there is widespread adoption of the ResNeXt architecture yet, e.g. citations of their paper?

**Comment by gcp** [comment]
Between AlphaGo and AGZ ResNets gained traction, and many people pointed out the benefits of BatchNorm, and it became gradually accepted that the combo allowed training much deeper networks.

So they just follow the sate of the art. It's very far from clear ResNeXT is that, though.

Also it's covered by Facebook patents and their extremely toxic patent grant so there's no way in hell that code is allowed anywhere near mine.
