### ISSUE TITLE
can king's brother be next king?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#635]
I saw a strange match between king's brother and king's father:
2018-01-12 10:12 
1e2b85cf
 VS 
ffc1e51b 
344 : 114 (75.11%) 458 / 400 PASS 
It seems the brother  has higher rate than the king.
2018-01-10 15:33 
46ff4b94
 VS 
ffc1e51b 
262 : 182 (59.01%) 444 / 400 PASS 

thus, if the king has no stronger son, then the brother seems be a better king

**Comment by zediir** [comment]
See #634 and #591
