### ISSUE TITLE
1e2b85cf is not shown properly on the graph

### ISSUE THREAD

**Issue by jslechasseur** [gcp/leela-zero#638]
Network 1e2b85cf apparently beats  ffc1e51b 76% of the time, but we don't seem to know how many training games it required. Also, it plays very differently. Chinese openings, mini chinese etc...

![buglz](https://user-images.githubusercontent.com/35378510/34887625-1d1500b6-f795-11e7-9245-bc83b1cbcfe8.jpg)

Also, where it appears in the test matches gives the uneasy feeling that we initially missed this network and kept using 46ff4b94 for selfplay.

![buglz2](https://user-images.githubusercontent.com/35378510/34887811-cc6acf32-f795-11e7-911d-e6dcaec58b5d.jpg)

**Comment by isty2e** [comment]
See #634 and #591 for details. It is a network trained on human games.
