### ISSUE TITLE
autogtp could pile up more work on my GPU

### ISSUE THREAD

**Issue by FlorinAndrei** [gcp/leela-zero#64]
I've a Titan X Pascal. When running autogtp.exe the memory usage on the GPU is a few percent points, GPU load is less than 10%, and power consumption is under 25% - all these measured with the GPU-Z app.

I think the software should pile up more work if the GPU can take it.

**Comment by gcp** [comment]
The current network is tiny because there is very little learning data yet, so the program ends up being completely CPU-bound on a fast GPU.

This will "fix" itself after a few epochs.

**Comment by FlorinAndrei** [comment]
Hmm. CPU usage is not too high either - 30 to 40% on an AMD FX-8350 eight-core.

**Comment by sbbdms** [comment]
You can create multiple instances of AutoGTP according to the CPU & GPU usage of your machine.

**Comment by gcp** [comment]
You can launch a second instance, it defaults to only 2 threads. (Some of the CPU usage you already see is from the GPU driver)

**Comment by Sivous** [comment]
How long will it take to update the neural network?

**Comment by gcp** [comment]
I'm not sure what you mean. It gets updated when it beats the old one by a significant %. It's not possible to know in advance how long this takes.

**Comment by sbbdms** [comment]
Maybe he means the interval of http://zero.sjeng.org/networks/.
The author mentioned that he will probably dump every 25k games or so. See #1

**Comment by gcp** [comment]
Latest release can play multiple games at once with the -g option.
