### ISSUE TITLE
1080ti slower than 1060 when using a small input data size

### ISSUE THREAD

**Issue by ericyan71** [gcp/leela-zero#641]
hello，I said days before that my 1080ti runs slower than 1060 when comparing the neuro network inference speed, I think maybe my mother board is bad, but yestady, someone tell me he has enounter the same problem just as me, so maybe it is not as simple as it looks.
 
After some trying, I found it maybe related to input data size. I build a neuro network like AGZ, using 5block 64filter and two head, and run it on two computer respectively. On each computer, I run twice, first using the input data with size of 1x19x19x18, and second using input size of 128x19x19x18. and the result listed below:

                  Input size   |   1x19x19x18  |   128x19x19x18
----------------------------------------------------------------------
1080ti + x5680 + 16g  |   1.08ms         |   13.6ms
1060 + i3 4160 + 8g    |   0.71ms         |   23.4ms

I found when the input data size is large ,the 1080ti is much faster than 1060, but when using small input, it is slower than 1060, how weird it is!

**Comment by ericyan71** [comment]
![result](https://user-images.githubusercontent.com/22901866/34903007-bc617686-f862-11e7-8f06-972c3590da8a.png)

**Comment by marcocalignano** [comment]
Could be related on how much time is actually spent on GPU and how much on CPU. I would think that with small input the CPU is busy transferring data in and out from the GPU more frequently than on when you have bigger inputs.

**Comment by ericyan71** [comment]
@marcocalignano I only tested the gpu time in my own test program, and in LZ, I only test the time of function of get_scored_move(), so my result doesn't include the time of cpu.

**Comment by gcp** [comment]
get_scored_moves() has to talk to the driver, the driver has to copy memory to the GPU, set up the kernels, pass the arguments, wait for the GPU to finish work, copy back the data, etc.

All that happens on the CPU.
