### ISSUE TITLE
why today(20180113) has no match?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#642]
(1065 match games in past 24 hours, 0 in past hour.)

**Comment by jkiliani** [comment]
Something to do with the learning rate change. There have been no specifics yet at which points the network is going to be sampled from now on.

**Comment by evanroberts85** [comment]
If 08753f80 is with a 10x lower learning rate, I am surprised that just 8k steps can still cause a 30+% drop in win rate

**Comment by roy7** [comment]
I broke the network uploading temporarily when we were adding something to the server. So a few networks didn't make it into the server.
