### ISSUE TITLE
Leelaz Version 0.10.1

### ISSUE THREAD

**Issue by marcocalignano** [gcp/leela-zero#643]
I was thinking that autogtp does not support version string with 3 numbers so if the server ask for version 0.10.1 autogtp will check only for 0.10. @gcp If you want I can write the patch for it based on master so will get release before the server changes the required version. But then you have to release a new autogtp (version 12) so you can force that too!

**Comment by gcp** [comment]
I guess we won't enforce 0.10 for now, and do a 0.11 + v12 release.

**Comment by marcocalignano** [comment]
OK. So I do this in /next then!
