### ISSUE TITLE
Error when starting autogtp with -g 3 or -g 4+

### ISSUE THREAD

**Issue by kiudee** [gcp/leela-zero#644]
I have been running on one instance (-g 1) for quite a while now and decided to try higher values for increased efficiency.

Setup
--------

- 1x GTX 1080, 6 core i7
- Tried with:
   - Current winograd branch (590ed7e7014d47c2d53f76163b84a95721a754d9)
   - Current next branch (918d7b8cefcf1d4863e8d9a12cac2840b7483dc9)
- Fedora 27 with opencl-headers 2.1

Problems
--------

When running `autogtp -g 4` it immediately exits with the error:
```
*ERROR*: Could not talk to engine after launching.
```

Running it with `autogtp -g 3` it works a while for selfplay games but exits with the same message as soon as it gets a request for a *match*.

The same errors happen if I run several terminals with one instance each.

**Comment by kiudee** [comment]
To get additional debug output I started 3 instances manually and then the last one outputs the following:
```
Detected 3 OpenCL platforms.
Platform version: OpenCL 2.0 pocl 0.14, LLVM 4.0.1
Platform profile: FULL_PROFILE
Platform name:    Portable Computing Language
Platform vendor:  The pocl project
Device ID:     0
Device name:   pthread-Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
Device type:   Unknown
Device vendor: GenuineIntel
Device driver: 0.14
Device speed:  3800 MHz
Device cores:  12 CU
Device score:  520
Platform version: OpenCL 1.1 Mesa 17.2.4
Platform profile: FULL_PROFILE
Platform name:    Clover
Platform vendor:  Mesa
Error getting device(s): clGetDeviceIDs: -1
Platform version: OpenCL 1.2 CUDA 9.1.98
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     1
Device name:   GeForce GTX 1080
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 387.34
Device speed:  1885 MHz
Device cores:  20 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GTX 1080
with OpenCL 1.2 capability.
Error creating OpenCL context: clCreateContext: -6terminate called after throwing an instance of 'std::runtime_error'
  what():  Error creating OpenCL context.
```

**Comment by marcocalignano** [comment]
Apparently your GTX 1080 has Id 1 and no 0 (like usually) so try the /next branch with the following command line:
`autotgtp -g 4 -u 1 `

**Comment by kiudee** [comment]
That worked - thanks a lot.
My main question now would be why it was successful in picking the GPU in the other cases?
It was using GPU because the GPU utilization went to about 75%.

**Comment by marcocalignano** [comment]
When you do nit use the option -u you do not choose any specific device and autogtp chooses the device with id 0. If you look at the debug output you can see that your device 0 is you CPU. Apparently you do not have enough memory to run 4 threads on the CPU. If you chosse to launch you threands on the device 1 (-u 1) you will rumm the threads on the GPU and I guess with a 1080 you could even try to run 6 or even 8.

**Comment by kiudee** [comment]
With `autogtp -g 5 -u 1` it errors out immediately with the same error.

**Comment by marcocalignano** [comment]
how much RAM do you have?

**Comment by kiudee** [comment]
8 MiB on the GPU and 16 GiB on the PC

**Comment by gcp** [comment]
>When you do nit use the option -u you do not choose any specific device and autogtp chooses the device with id 0

@marcocalignano Why not let Leela pick? It has logic to find the best device.

**Comment by kiudee** [comment]
I have not been able to find the source of the problem yet. On my windows pc at home (also a GTX 1080) it does not happen. I assume it could be an OpenCI issue.

**Comment by marcocalignano** [comment]
@gcp autogtp **do let** leelaz choose.

**Comment by kiudee** [comment]
I also think it is another problem. It never chose the CPU by mistake.

**Comment by kiudee** [comment]
I fixed the bug by removing the old `libOpenCL.so.1` files provided by the cuda driver and now am able to use `autogtp -g 8`.
