### ISSUE TITLE
9x9 version (let it be a small part of the distributed training project)

### ISSUE THREAD

**Issue by farteryhr** [gcp/leela-zero#647]
it plays faster. it trains faster. it gets stronger faster.
but traditional AIs will also have more chance, because of more dependence on computation power but less on the "feeling".
and it's also fun to know:
how fast will it surpass traditional AI?
will more "corner case" bother it?
how close to the perfect play can we get with ML?

**Comment by gcp** [comment]
I'm open to taking patches to make the board support more generic but I have no interested in doing any work for 9x9 myself.
