### ISSUE TITLE
"An error occurred"

### ISSUE THREAD

**Issue by d7urban** [gcp/leela-zero#649]
Got this in the output from autogtp when it tries to upload games. 

<!DOCTYPE html>
<html>
<head>
<title>Error</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>An error occurred.</h1>
<p>Sorry, the page you are looking for is currently unavailable.<br/>
Please try again later.</p>
<p>If you are the system administrator of this resource then you should check
the <a href="http://nginx.org/r/error_log">error log</a> for details.</p>
<p><em>Faithfully yours, nginx.</em></p>
</body>
</html>

**Comment by gcp** [comment]
There is some maintenance running on the server. It will be back to normal in a few hours.
