### ISSUE TITLE
Additional option? Handicap. 

### ISSUE THREAD

**Issue by Marcin1960** [gcp/leela-zero#65]
It would be nice to have additional option like "-e  x", where x stands for maximum
handicap. Part of the day I run leelaz bot on KGS ( as LeelaZeroT ) to promote CPU/GPU participation.

Some weaker players have tendency to get 9 or 8 stones handicap and occupy the bot several times a day making observation boring. If handicap limit is for example  3 ("-e 3") and  leelaz just exits by resignation, it would be great.

A question, what is your guess, after how many games will leelaz game get less random enough to be resemble regular player? 100K? 200K?

The advantage would be make players to be able to see/enjoy progress and encourage them to contribute by sharing their PCs.

**Comment by gcp** [comment]
This is really a stopgap measure because the KGS client interface is so terrible.

**Comment by Marcin1960** [comment]
Indeed.
