### ISSUE TITLE
Cannot compile autogtp -- cannot find QT headers

### ISSUE THREAD

**Issue by fishcu** [gcp/leela-zero#66]
I'm running Ubuntu 16.04. When running `qmake`, then followed by `make`, I get the following error:
`g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4 -I. -o main.o main.cpp
main.cpp:28:30: fatal error: QRegularExpression: No such file or directory
compilation terminated.
Makefile:205: recipe for target 'main.o' failed
make: *** [main.o] Error 1`

When running `qmake --version` or `qmake-qt4 --version`, in both cases I get:
`QMake version 2.01a
Using Qt version 4.8.7 in /usr/lib/x86_64-linux-gnu`

However, the `QRegularExpression` file is only installed for QT5, seemingly?
`locate QRegularExpression
/usr/include/x86_64-linux-gnu/qt5/QtCore/QRegularExpression
/usr/include/x86_64-linux-gnu/qt5/QtCore/QRegularExpressionMatch
/usr/include/x86_64-linux-gnu/qt5/QtCore/QRegularExpressionMatchIterator
/usr/include/x86_64-linux-gnu/qt5/QtGui/QRegularExpressionValidator`

I tried installing missing QT4 libraries (`sudo apt install libqt4*dev`), but that didn't help. Any ideas how to fix? Any further diagnostics I can provide?

Thank you for making this tool!

**Comment by uestccokey** [comment]
QRegularExpression need qt5

**Comment by gcp** [comment]
qmake -qt5

There isn't really anything in the source that needs Qt5 AFAIK, but the regular expression header got renamed between Qt4 and Qt5.

**Comment by fishcu** [comment]
`qmake -qt5` worked, thank you!

In that case, maybe `https://github.com/gcp/leela-zero/tree/master/autogtp` should be edited to say QT5 is a requirement, or the compilation instructions updated? Or maybe change the included header based on some `#if` flag?

**Comment by gcp** [comment]
"Yes" ☺

**Comment by fishcu** [comment]
Thank you, I missed this other report. Close if you like.
