### ISSUE TITLE
Possible go rule bug

### ISSUE THREAD

**Issue by pheasant75** [gcp/leela-zero#660]
In the following game, after black captures a white stone in move 209, white can place the stone in the space at the next move to capture a group of black stones.  The white did not play this move.  I was wondering if the white mistakenly believe the ko rule applies here.  
http://zero.sjeng.org/viewmatch/8eb7ab254be9ecf6618dc993502877fea3c0f0240112dcd39b87b86609196396?viewer=wgo

**Comment by gcp** [comment]
White has sente so he can kill the group at his leisure with T9. And note how the exchange is used to throw A4 in, too.
