### ISSUE TITLE
could you please publish the loss of plocy head and value head？

### ISSUE THREAD

**Issue by ericyan71** [gcp/leela-zero#665]
hi, I think many people are interested in these value, could you please show us these values? thanks.

**Comment by gcp** [comment]
https://sjeng.org/zero
https://sjeng.org/zero/tfsummary.tar.xz

**Comment by FFLaguna** [comment]
There have been some interesting changes in the past two weeks. Would you mind uploading these again when you have a chance? Thank you @gcp
