### ISSUE TITLE
Network prescreening at low playouts

### ISSUE THREAD

**Issue by jkiliani** [gcp/leela-zero#667]
I'm interested in conducting in experiment about how well the results of a match between two networks at 1600 playouts correlate with those of a match between the same two networks, but at much lower playout numbers. I read from a few people who tried this and said it works, so I would like to test this systematically. I have something like this in mind
![errorbar_correlation](https://user-images.githubusercontent.com/33714573/35098007-d452907e-fc52-11e7-9514-a11ca784a90b.png)

i.e. a scatterplot that shows the winrate or maybe Elo difference of a considerable number of past distributed matches at 1600 playouts, v.s. the winrate I get for the same matches with much lower playouts. Every match should have a 2-d error bar calculated from the (95%?) confidence interval from the testing sample.

I am hoping this experiment will show that a rough estimation of the quality of a network at 1600 playouts is possible with much fewer playouts, which would allow us to pre-screen networks at a fraction of the present computation cost, and only do 1600 playout matches in cases where the low playout match indicates they show promise. That in turn would let us test networks much more often.

@roy7: For this experiment I would ideally need access to a larger archive of past matches, specifically those with pass or null result, since their statistical error is much lower (>400 games). Is it a simple matter to use the SPRT code in autogtp to calculate confidence intervals? **Edit:** For a first try I won't bother with the error bars, and will simply plot elo differences as a scatterplot (and I can get the reference elo diff from the progress curve).

**Comment by Alderi-Tokori** [comment]
Interesting :) For the record, how much lower is "much lower"?

**Comment by jkiliani** [comment]
I'm thinking of starting with really low, 10-50. If it turns out that this produces poor correlation, I'll gradually go higher. My thinking is simply that many properties of a typical "fail" network, such as value overfitting, will likely be just as pronounced for low playouts as for high.

I could be wrong, but I think the potential benefits it this works merits a test.

**Comment by Alderi-Tokori** [comment]
Ah, I thought you had already done the test, my bad >< Anyway, 10-50 might be a little too low in my opinion, but we'll see, at least it will be fast to test it.

**Comment by jkiliani** [comment]
I'm unfortunately not blessed with a fast GTX 1080 ;-) so I have to start small. I just started the thread now to ask @roy7 if I could have a link to the match archive, since to test this I need high-playout matches with as large a sample size as possible.

**Comment by zediir** [comment]
I could do some of the tests if you give me a list of matches to run. How are you running them? Just building validation with `m_option = " -g  -p 10 --noponder -t 0 -q -d -r 0 -w ";`?

**Comment by jkiliani** [comment]
Haven't completely decided yet, but I'm leaning towards running the same parameters as the actual validation matches (isn't that r=1?). I'll be using ringmaster since it's so convenient for running multiple matches at the same time. As for a list of matches, I hope to test many or even all of the distributed validation pass matches since the 0.9 bug fixes. My idea is to prove that any of these promotions would have been possible to find with lower playouts as well. I'll start on this as soon as ringmaster finishes a current batch of scaling matches.

**Comment by zediir** [comment]
It's r=1 for 80% of the games (I think). I'm currently running it as -r 1 to test my supervised 5x64 because the net does not know to pass when losing so I would otherwise get really long games.

**Comment by evanroberts85** [comment]
If we stick with 1600 playouts, validation match games are going to be really slow when we move to 10x128. So if we could move to 400 playouts or less that will be a big benefit moving forward.

**Comment by gcp** [comment]
Self-play games will be just as slow, the ratio won't change.

**Comment by roy7** [comment]
@jkiliani I'm happy to provide whatever is needed. I'm just fuzzy on what you're asking me for. Do you need an endpoint to show every match we've done, beyond just the most recent 100? Or do you want 'all matches that didn't fail'?

**Comment by Mardak** [comment]
Are you testing with -r 1 as match games are typically run with resign 1%. You'll probably want `next` branch leelaz which has https://github.com/gcp/leela-zero/commit/d0eaa6b512f276f84a231aa915dadcc8f3070f22 fixes for low playout and resigning.

**Comment by jkiliani** [comment]
Yes I'm testing with -r 1. This is a sample command steer file for ringmaster for one of the matches: 

competition_type = 'playoff'
players = {
    'LZ-c83e1b6e' : Player("leelaz -g -t 1 -r 1 -p 5 -d -q --noponder -w c83e1b6e.txt"),
    'LZ-35df1f93' : Player("leelaz -g -t 1 -r 1 -p 5 -d -q --noponder -w 35df1f93.txt"),
    }

board_size = 19
komi = 7.5

matchups = [
    Matchup('LZ-c83e1b6e', 'LZ-35df1f93', alternating=True, number_of_games=400),
    ]

**Comment by roy7** [comment]
If you are doing this by hand I can give you a table like front page, but with every match. Or I could give you more of a raw csv or json dump format if you want to import it to something?

**Comment by roy7** [comment]
@jkiliani As a short cut to save time, I removed the 100 limit on the chart on port 8082.

http://zero.sjeng.org:8082/

If you go there now, the entire match history is visible. Maybe you can copy/paste that down or save the HTML so you have it all?

**Comment by jkiliani** [comment]
@roy7 Thanks, that's great! Yes, that's all I need for now, at the moment I'm just running the last 6 pass matches to the end, then I'll queue tests for the rest of the pass matches from the 0.9 bug fixes on.

At some point I'll look into adding the error bars, but for the moment that's not yet necessary.

**Comment by roy7** [comment]
Do note the commit @mardak listed for you. Prior to that, playout caps below 500 couldn't resign.

**Comment by jkiliani** [comment]
Yes my build includes that commit. Almost all of the matches I'm playing here end resignation.

**Comment by jkiliani** [comment]
The first match just finished: 
[Latest6_passmatch_5p.txt](https://github.com/gcp/leela-zero/files/1644636/Latest6_passmatch_5p.txt)

From the 6 matches so far, the largest difference in winrate between 1600p and 5p was 11%, in most cases the difference is within 5%.

I'm now queuing all remaining passing matches starting from 1607dbea vs eebb910d, with 400 games each, as well as the 11 latest failed nets against c83e1b6e.

**Comment by Mardak** [comment]
We also want to make sure networks that would have failed at 1600 playouts also fail quickly or at least don’t lead to significantly higher win rates that would cause the match queueing behavior to request more matches. A quick sanity check with a recent network match `bb9b898e VS c83e1b6e` which failed with 11.11% with various playouts of 1, 10, and 100:

```
./validation -p 1 -n bb9b898e7555824dfbf3ef6e6381d7fd25ea8e15374cf61d03e2df9796f8b60c -n c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43 -r 1
The first net is better than the second
bb9b898e v c83e1b6e ( 143 games)
              wins        black       white
bb9b898e   90 62.94%   42 63.64%   48 62.34%
c83e1b6e   53 37.06%   24 36.36%   29 37.66%
                       66 46.15%   77 53.85%
```

```
./validation -p 10 -n bb9b898e7555824dfbf3ef6e6381d7fd25ea8e15374cf61d03e2df9796f8b60c -n c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43 -r 1
The first net is better than the second
bb9b898e v c83e1b6e ( 400 games)
              wins        black       white
bb9b898e  225 56.25%   98 57.31%  127 55.46%
c83e1b6e  175 43.75%   73 42.69%  102 44.54%
                      171 42.75%  229 57.25%
```
```
./validation -p 100 -n bb9b898e7555824dfbf3ef6e6381d7fd25ea8e15374cf61d03e2df9796f8b60c -n c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43 -r 1
The first net is worse than the second
bb9b898e v c83e1b6e ( 50 games)
              wins        black       white
bb9b898e   12 24.00%    4 19.05%    8 27.59%
c83e1b6e   38 76.00%   17 80.95%   21 72.41%
                       21 42.00%   29 58.00%
```

So clearly 1 and 10 playouts are not good in this case as they had the network passing when it should have failed. I’ll do another check with `fb1a8a87 VS c83e1b6e` which failed 2.13%.

**Comment by jkiliani** [comment]
@Mardak I haven't had such a case yet, but apparently there are cases where the winrate at low playouts is very different from the winrate at high playout. I'm going to continue my run to get an idea on how often that happens.

**Comment by ThePokerDude** [comment]
@jkiliani Let's assume you get a good correlation between 1600 playout matches and 50 playout matches.
How would you use this information? 
Train networks as often as now but test it (on the server?) before you schedule a distributed match?
Train networks more often and test it (on the server?) before you schedule a distributed match?
Or is it just of curiosity?

**Comment by Mardak** [comment]
One desire from #545 was to get match results sooner, and the server tells clients how many playouts to use. Potentially the server can start each network by telling clients to use a low number of playouts to filter out FAIL networks within a few minutes. This would mean more resources are focused on selfplay or gives the ability to match up a lot more networks.

**Comment by Mardak** [comment]
Here's couple more networks that lost to `c83e1b6e`:
`fb1a8a87 VS c83e1b6e` 1 : 46 (2.13%)
```
./validation-p1 -n fb1a8a87bc85395f3646d84e529ea72ddb345c644613c76da6fd74a6ab87b137 -n c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43
The first net is better than the second
fb1a8a87 v c83e1b6e ( 2224 games)
              wins        black       white
fb1a8a87 1183 53.19%  544 53.49%  639 52.94%
c83e1b6e 1041 46.81%  473 46.51%  568 47.06%
                     1017 45.73% 1207 54.27%

./validation-p10 -n fb1a8a87bc85395f3646d84e529ea72ddb345c644613c76da6fd74a6ab87b137 -n c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43
The first net is worse than the second
fb1a8a87 v c83e1b6e ( 133 games)
              wins        black       white
fb1a8a87   55 41.35%   24 40.00%   31 42.47%
c83e1b6e   78 58.65%   36 60.00%   42 57.53%
                       60 45.11%   73 54.89%

./validation-p50 -n fb1a8a87bc85395f3646d84e529ea72ddb345c644613c76da6fd74a6ab87b137 -n c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43
The first net is worse than the second
fb1a8a87 v c83e1b6e ( 75 games)
              wins        black       white
fb1a8a87   25 33.33%   12 32.43%   13 34.21%
c83e1b6e   50 66.67%   25 67.57%   25 65.79%
                       37 49.33%   38 50.67%

./validation-p100 -n fb1a8a87bc85395f3646d84e529ea72ddb345c644613c76da6fd74a6ab87b137 -n c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43
The first net is worse than the second
fb1a8a87 v c83e1b6e ( 68 games)
              wins        black       white
fb1a8a87   21 30.88%   10 30.30%   11 31.43%
c83e1b6e   47 69.12%   23 69.70%   24 68.57%
                       33 48.53%   35 51.47%
```

`6087aa21 VS c83e1b6e` 2 : 47 (4.08%)
```
./validation-p1 -n 6087aa2183f5444f81974191ab87c2b9315476f7082f6b2bf97a8b72549833e9 -n c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43
The first net is better than the second
6087aa21 v c83e1b6e ( 1015 games)
              wins        black       white
6087aa21  548 53.99%  247 54.41%  301 53.65%
c83e1b6e  467 46.01%  207 45.59%  260 46.35%
                      454 44.73%  561 55.27%

./validation-p10 -n 6087aa2183f5444f81974191ab87c2b9315476f7082f6b2bf97a8b72549833e9 -n c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43 
The first net is worse than the second
6087aa21 v c83e1b6e ( 192 games)
              wins        black       white
6087aa21   86 44.79%   44 44.90%   42 44.68%
c83e1b6e  106 55.21%   54 55.10%   52 55.32%
                       98 51.04%   94 48.96%

./validation-p50 -n 6087aa2183f5444f81974191ab87c2b9315476f7082f6b2bf97a8b72549833e9 -n c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43
The first net is worse than the second
6087aa21 v c83e1b6e ( 64 games)
              wins        black       white
6087aa21   19 29.69%   10 30.30%    9 29.03%
c83e1b6e   45 70.31%   23 69.70%   22 70.97%
                       33 51.56%   31 48.44%

./validation-p100 -n 6087aa2183f5444f81974191ab87c2b9315476f7082f6b2bf97a8b72549833e9 -n c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43
The first net is worse than the second
6087aa21 v c83e1b6e ( 77 games)
              wins        black       white
6087aa21   26 33.77%   14 34.15%   12 33.33%
c83e1b6e   51 66.23%   27 65.85%   24 66.67%
                       41 53.25%   36 46.75%
```

Both cases had `-p 1` with the wrong winner (requiring over 1000 games to settle), but at least the winner is already correct when increasing to `p -10`. Even with `-p 100`, the win rate of the losing network is still quite a bit higher than the expected win rate from `-p 1600`.

I started running the same set of checks with a different winning network `0db82470`, and those seem to also have a flipped winner at `-p 1` but corrected at `-p 10`:

`cd4f6aac VS 0db82470` 5 : 46 (9.80%)
```
./validation-p1 -n cd4f6aac71ec8c412c6f92b96c3d5174afefec22ab4d0d9c823d285d79bfbba3 -n 0db82470729f053191d66e7c866cbeb7a036fb232ac5524eea62642bf6e7ada3
The first net is better than the second
cd4f6aac v 0db82470 ( 252 games)
              wins        black       white
cd4f6aac  147 58.33%   63 60.00%   84 57.14%
0db82470  105 41.67%   42 40.00%   63 42.86%
                      105 41.67%  147 58.33%

./validation-p10  -n cd4f6aac71ec8c412c6f92b96c3d5174afefec22ab4d0d9c823d285d79bfbba3 -n 0db82470729f053191d66e7c866cbeb7a036fb232ac5524eea62642bf6e7ada3
The first net is worse than the second
cd4f6aac v 0db82470 ( 144 games)
              wins        black       white
cd4f6aac   61 42.36%   31 42.47%   30 42.25%
0db82470   83 57.64%   42 57.53%   41 57.75%
                       73 50.69%   71 49.31%
```

`47fedc3b VS 0db82470` 2 : 47 (4.08%)
```
./validation-p1 -n 47fedc3b476fc5d47c2fb2b7e444ed067ab67125fa3e493ea6adbfba7afacdf7 -n 0db82470729f053191d66e7c866cbeb7a036fb232ac5524eea62642bf6e7ada3
The first net is better than the second
47fedc3b v 0db82470 ( 486 games)
              wins        black       white
47fedc3b  270 55.56%  131 55.74%  139 55.38%
0db82470  216 44.44%  104 44.26%  112 44.62%
                      235 48.35%  251 51.65%

./validation-p10 -n 47fedc3b476fc5d47c2fb2b7e444ed067ab67125fa3e493ea6adbfba7afacdf7 -n 0db82470729f053191d66e7c866cbeb7a036fb232ac5524eea62642bf6e7ada3
The first net is worse than the second
47fedc3b v 0db82470 ( 184 games)
              wins        black       white
47fedc3b   82 44.57%   38 44.19%   44 44.90%
0db82470  102 55.43%   48 55.81%   54 55.10%
                       86 46.74%   98 53.26%
```

**Comment by Mardak** [comment]
Oh, I suppose one thing to note is that we don't actually know what's the expected win rate for these failed networks as we only ran ~45 games. They stopped because they wouldn't reach 55%. The margin of error at 45 games with 2 stddev is 15%, so potentially the actual win rate of these failed networks is closer to 25%. The previously posted win rates at `-p 50` and `-p 100` are higher but also within that range.

**Comment by jkiliani** [comment]
@ThePokerDude If I achieved a good correlation setup, I would use it to train networks much more often on the server. I would then hand out each of these networks for screening to a single client, who could check whether they are likely to be decent. For those networks where the screening showed promise, I would then arrange a distributed test at 1600 playouts, with the queue prioritising the matches that showed the best win rates during screening.

But obviously, we're not there yet...

**Comment by jkiliani** [comment]
@Mardak I agree, and that is one thing which is going to hamper these correlation tests. For the recent failed nets, we just know that they are 95% certain to not be 35 elo better than the reference net, but they have larger error bars attached compared to 400 game matches...

**Comment by ThePokerDude** [comment]
@jkiliani + @Mardak As the results of network1 (black) vs network2 (white) aren't 100:0 or 0:100 there must be some random element. In the self play games it's determined by the seed only (if I understood correctly). Is it determined in the test matches also by the seed only?

If yes, I would do some preelimnary tests: can you reproduce a game's outcome given a seed?
If yes, you could use the same seeds used in test matches but lower the playouts. 
This way you could reduce the noise, because you would elimnate one factor which causes randomness.

**Comment by jkiliani** [comment]
@ThePokerDude There is a random element in the random symmetry applied to every neural network evaluation. I have noticed during scaling tests (i.e. a network against itself at different playouts) that the games tend to end up looking really similar, but I still never found an actual duplicate game.

**Comment by jkiliani** [comment]
I have cancelled the test for the history of passed nets at this point. For the most part, the newer nets win, though sometimes at quite different margins:
[Report_passednets_5p.txt](https://github.com/gcp/leela-zero/files/1645826/Report_passednets_5p.txt)

**Comment by jkiliani** [comment]
However, what was more surprising to me was the result of a matchup for 11 recently failed nets against c83e1b6e, including some also tested by @Mardak:
[Report_failednets_5p.txt](https://github.com/gcp/leela-zero/files/1645844/Report_failednets_5p.txt)

In no case is the failed net decisively defeated like it happened at 1600 playouts. On the contrary, the failed nets all seem to have a very similar strength at 5 playouts as c83e1b6e, in some cases it even looks like the failed net is likely to win.

Now, what are the implications of this? At least the idea of pre-screening networks at very low playouts seems to have problems. @Mardak's results suggest this may be fixed by going to considerably higher playout numbers, probably something in the range 50-400.

However, I think we may find a deeper meaning in those tests: Why would the pass results look similar at low playouts, but the failed nets look so different? I think what we see is that the strength of LZ's neural networks is composed of two components: The base strength, as measured by 1-5 playouts, and the MCTS strength or strength scaling, i.e. how well the network can make use of the search to enhance its strength. That we have so similar base strengths of all recently tested failed networks suggests that base strength is mostly deterministic as a function of the training dataset, while scaled strength is not and behaves in a chaotic way (i.e. very little difference in training step counts gives completely different strength at 1600 playouts).

**Comment by gcp** [comment]
At low playouts the strength of the policy network dominates. This should be obvious if you consider the p=1 edge case.

**Comment by jkiliani** [comment]
How do you define strength of the policy net? I thought the likely reason why some nets scale better than others is that the policy head of a strong network includes all reasonable candidate moves so the search can explore them and effectively find the best one, while a weaker network might have some strong candidate moves missing for common situations (with the obvious implications on search).

By the way, both 5903f263 and the other five bootstrapped nets tested this morning look to be better than 35df1f93 at 5 playouts. Not sure yet what the implications of this are.

 ![screen shot 2018-01-19 at 11 14 41](https://user-images.githubusercontent.com/33714573/35146004-085e15a2-fd0a-11e7-8624-dc2746dfedee.png)

**Comment by gcp** [comment]
Yes, that's a good question. (And a very relevant one for the AG Lee paper, where this issue bit them in the ass!)

My point was more than the accuracy of the value network has little influence if the tree search done is minimal. For p=1 it does nothing. For other low values of p, the "value" of the node has to overcome the bias given by the policy network. It's relevant for that that the UCT parameter was tuned for p=1600.

(This means that to get maximal LZ strength with a fixed network, and a timecontrol rather than fixed p, another cfg_puct and even cfg_softmax_temp might be better, something to keep in mind.)

**Comment by isty2e** [comment]
Or the question can be reversed: What is the optimal ratio between policy and value losses for a given playout? The weight for the MSE loss will clearly increase as the number of playouts increases. Of course this will be too costly to test, just saying for fun. Also they may not be independent of UCT parameters.

**Comment by Mardak** [comment]
Just to wrap up the testing of the failed networks with larger playouts of 500:

```
./validation-p500 -n bb9b898e7555824dfbf3ef6e6381d7fd25ea8e15374cf61d03e2df9796f8b60c -n c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43
The first net is worse than the second
bb9b898e v c83e1b6e ( 43 games)
              wins        black       white
bb9b898e    8 18.60%    3 15.00%    5 21.74%
c83e1b6e   35 81.40%   17 85.00%   18 78.26%
                       20 46.51%   23 53.49%

./validation-p500 -n fb1a8a87bc85395f3646d84e529ea72ddb345c644613c76da6fd74a6ab87b137 -n c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43
The first net is worse than the second
fb1a8a87 v c83e1b6e ( 38 games)
              wins        black       white
fb1a8a87    6 15.79%    0  0.00%    6 24.00%
c83e1b6e   32 84.21%   13 100.00%   19 76.00%
                       13 34.21%   25 65.79%

./validation-p500 -n 6087aa2183f5444f81974191ab87c2b9315476f7082f6b2bf97a8b72549833e9 -n c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43
The first net is worse than the second
6087aa21 v c83e1b6e ( 36 games)
              wins        black       white
6087aa21    5 13.89%    1  6.67%    4 19.05%
c83e1b6e   31 86.11%   14 93.33%   17 80.95%
                       15 41.67%   21 58.33%

./validation-p500  -n cd4f6aac71ec8c412c6f92b96c3d5174afefec22ab4d0d9c823d285d79bfbba3 -n 0db82470729f053191d66e7c866cbeb7a036fb232ac5524eea62642bf6e7ada3
The first net is worse than the second
cd4f6aac v 0db82470 ( 58 games)
              wins        black       white
cd4f6aac   16 27.59%    6 24.00%   10 30.30%
0db82470   42 72.41%   19 76.00%   23 69.70%
                       25 43.10%   33 56.90%

./validation-p500 -n 47fedc3b476fc5d47c2fb2b7e444ed067ab67125fa3e493ea6adbfba7afacdf7 -n 0db82470729f053191d66e7c866cbeb7a036fb232ac5524eea62642bf6e7ada3
The first net is worse than the second
47fedc3b v 0db82470 ( 32 games)
              wins        black       white
47fedc3b    3  9.38%    0  0.00%    3 15.79%
0db82470   29 90.63%   13 100.00%   16 84.21%
                       13 40.63%   19 59.38%
```

In the context of potentially doing early matches with lower playouts, just using the numbers above with 500 playouts, we could get results back ~3x faster (500/1600) but potentially there would be 5-10 incorrect wins associated to the should-have-failed network in the first 40 games at lower playout. If the network would have definitely failed, then just including them in the overall win rate probably doesn't matter much, but what if the matchup was closer to passing -- would these incorrect early wins cause a network to pass if it wouldn't have if all games were at 1600?

I suppose that could point to this issue's original topic of "prescreening" where I would assume that implies not tainting the actual win rate. However, with the results above, some amount of playouts will be required pointing to leveraging the distributed resources, so would each network do a distributed prescreening then an actual match if it passed the first step?

**Comment by jkiliani** [comment]
Thank you @Mardak for running these tests, this was very helpful since 500 playout matches are a bit out of reach for my computer. 

[Report_passednets_5p.txt](https://github.com/gcp/leela-zero/files/1648346/Report_passednets_5p.txt)
This is the update on the match series at 5 playouts I made for all the passed nets since 1607dbea. Out of 45 pass matches, 5 ended up scoring below 50 % at 5p. The worst case (LZ-30f49ac5 v LZ-696171c5) ended up with a winrate of only 36.7 %. So, 5 playouts will show most actually stronger nets as stronger, but misses still do occur.

The aim of this is to find and define a working screening procedure, which should be
1. Safe - as in a network that is actually stronger (at 1600p) will not be erroneously rejected
2. Effective - meaning that the procedure will reject at least a significant part of networks that are weaker at 1600p
3. Efficient - considering that all networks passing the screening will still have to pass an SPRT test at 1600p, the procedure should realise at least a reasonable performance gain compared to simply testing all new networks at 1600p in the first place.

The procedure should in my opinion consist of a modified SPRT test, maybe something like (-35,0), or possibly (-15,15)? If a network passes or the test reaches the game limit with null result, a 1600p match should be queued. If it fails, it gets deleted with no further testing. The modification to the SPRT bounds is necessary to make the procedure safe, i.e. build in a margin of error by which a passing network may perform worse in the screening than it would in a 1600 playout test.

My test series was designed to primarily determine whether testing at 5 playouts was anywhere close to useful for this purpose, and at this point I have to conclude it isn't... while it doesn't fail the majority of passed nets, it fails some of them, and it actually doesn't fail a lot of networks that are clearly losing at 1600 playouts.

@Mardak's results tell me that 500 playouts is probably both safe in not mistakenly failing better nets, and effective in failing at least the really bad networks. I'm a bit unsure about how efficient it is though, since we expend 500 playouts for every match in the first place, and another 1600 for every match that doesn't fail the screening. I plan to next conduct some tests in the 50-200 playout range, to find out how this affects the screening results, especially for the cases with problems at 5 playouts.

**Comment by evanroberts85** [comment]
The official validation matches should not be taken as a perfect reflection
of a networks actual strength - run the 400 games again and many of them
will not pass. You need to take this into account when doing a comparison.

The results for 500 playouts are also not close to being individually
statistically significant. That makes them very hard to analyse.

There is also the question of if you are running these with /next have
there been any code changes that may influence the result. Small changes
could potentially make a big difference to the result. It is also quite
possible that 500 favours network A, 1600 favours network B, then 3200
would favour A again.

**Comment by jkiliani** [comment]
> It is also quite possible that 500 favours network A, 1600 favours network B, then 3200 would favour A again.

That's an unproven hypothesis, and one that I personally find rather unlikely. The whole point of this thread is to investigate how useful low playout matches are for predicting high playout ones, and especially the ones by @Mardak show significant promise in my opinion. If you have evidence to support your claim I'd love to see it.

**Comment by evanroberts85** [comment]
I think the investigation is good. I just think not passing some tests that passed officially it not in itself meaningful, as this could happen anyway just by repeating the tests at 1600 playouts. We need more exact and precise analysis of the error difference between 1600 and lower playouts.

**Comment by jkiliani** [comment]
> We need more exact and precise analysis of the error difference between 1600 and lower playouts.

I agree, and I'm doing my best to provide such an analysis. However, if we can show enough initial promise, I hope that this investigation is picked up officially, since I just don't have the resources to repeat dozens of past matches at, say 400 playouts.

**Comment by jkiliani** [comment]
Continuing my investigation of the correlation of matches between high and low playouts, I repeated the 3 pass matches which scored the lowest win rates at 5p, this time repeating the matches at 50p and 100p:
<img width="509" alt="screen shot 2018-01-22 at 21 30 01" src="https://user-images.githubusercontent.com/33714573/35242947-79adddf6-ffbb-11e7-9292-eec8f865b96d.png">

While they still did not consistently reach pass scores, they didn't score in a range where any screening would fail them either (worst result was 49% for the passing net). I did not repeat all passing matches at 50 and 100 playouts, but the large majority of them already had win rates >50% even at 5p.  I would conclude that 50 playouts is most likely already safe enough to screen out networks scoring below 45%, or failing an SPRT (-35,0).

**Comment by jkiliani** [comment]
At low playouts, 7fde81e8 beats c83e1b6e conclusively, and the margin is bigger at lower playouts:

<img width="505" alt="screen shot 2018-01-22 at 21 48 53" src="https://user-images.githubusercontent.com/33714573/35243692-1a3f1bfc-ffbe-11e7-9f1c-5d3baf41e18b.png">

I would interpret this to mean c83e1b6e scales better than 7fde81e8 (at least with current UCT parameters)

**Comment by jkiliani** [comment]
Now, about the actual screening part: These are 5p results for recent failed nets, of the 3.01M training set:

<img width="491" alt="screen shot 2018-01-22 at 22 05 29" src="https://user-images.githubusercontent.com/33714573/35244537-c0b588a2-ffc0-11e7-8f44-011d3c625545.png">

**Comment by jkiliani** [comment]
... and for the 3.04M training set:

<img width="498" alt="screen shot 2018-01-22 at 22 06 45" src="https://user-images.githubusercontent.com/33714573/35244577-eabe87fc-ffc0-11e7-9832-d1e748e51615.png">

All of these nets would have (correctly) failed a (-35,0) SPRT. I'm running tests on the 3.05M training set now, but even if some of these end up passing, it's not a real failure of the screening procedure, since the net would still have to pass a test at 1600 playouts.

**Comment by evanroberts85** [comment]
My view is that any loss from having slightly less accurate results with
lower playout matches (and it looks like this would not be much), would be
more than made up with by being able to test more often, maybe even every
1k training steps.

**Comment by jkiliani** [comment]
@evanroberts85 That's exactly the point I'm trying to make. I think we're currently missing a lot of promising nets because not very many step counts are actually tested. I hope that if I can demonstrate a working screening procedure, @gcp would be able to produce many more nets for testing, without it digging into the computing resources available for self-play.

**Comment by killerducky** [comment]
I don't get the motivation to test more often. This is not a random process, if things are going as they should the networks will get stronger. There isn't a danger of missing one. The only thing it would buy is finding a candidate quicker, but we are already testing many candidates before finding one good enough.

**Comment by jkiliani** [comment]
How do you know the process doesn't have a significant random component? During the long final phase of 5x64, I couldn't detect a clear pattern to the strength of the network. Often enough two decent networks had a horrible one in between. I expected the network strength during a training set to follow a curve: First a rapid decline while the weights deviated from those of best-network, a depression during the adjustment phase, then an incline followed by a peak when the network adjusted optimally to the training data (sometimes enough for an SPRT pass), and finally another decline from overfitting. Unfortunately the training runs don't show such a clear pattern (or any clear pattern that I can make out), which suggests that the quality of networks has distinct chaotic properties. And if that's the case, the best way to find better nets (other than patience) is testing more often.

**Comment by jkiliani** [comment]
Again, all networks (with the possible exception of 3ed9b939) fail at 5 playouts for the current training set.

<img width="491" alt="screen shot 2018-01-23 at 01 08 17" src="https://user-images.githubusercontent.com/33714573/35251114-ff89de5c-ffd9-11e7-92ad-e13a2e0328da.png">

I'll continue to update this when hopefully a couple passing or null result nets come along soon... unfortunately I can't do more than 5p for a large number of nets, I may be able to do so for particularly interesting cases.

**Comment by evanroberts85** [comment]
It leaves me uneasy having to pick out the one good network among many bad one, with seemingly no pattern, but that is where we are. Testing more often will not only make it more likely to find the good networks but may make it easier to see if there are any patterns among the noise.

**Comment by roy7** [comment]
I'm quite interested in this suddenly for experimenting with training and needing to manually run validation tests. I'm tempted to drop to 5 playouts (or maybe 50 playouts) for my validations, given your work here so far. Just so I can more quickly assess results and then move to higher playouts if I find indications something worked.

**Comment by roy7** [comment]
Well, with 50 p, I'm at 17-4 so far with my 5x64 vs 6x64 net2net https://github.com/gcp/leela-zero/pull/704 test where the networks should, in theory, report identical results on every input. I was expecting roughly even win/loss rate. 25-11 now, at least -p 50 -g 4 is super fast to validate. ;) 34-15.

126-95... ok so I expected an early fail and that didn't happen. I should learn not to jump the gun!

So either the 5x64 and 6x64 net2net networks actually are different a little and this trick worked to tell faster, or this trick doesn't accurately judge that these two are identical. Hmm. Or they are the same and 126-95 is in the normal expectation if they are identical? validation isn't set up to test that, it's testing for 55% improvement.

**Comment by roy7** [comment]
I'll stop my test at:
```
135 wins, 108 losses
243 games played.
Status: 0 LLR 1.49015 Lower Bound -2.94444 Upper Bound 2.94444
```
since Marduk already did a -p 1 test suggesting 5x64 and 20x64 are the same using Net2Net. https://github.com/gcp/leela-zero/pull/704#issuecomment-359653124

**Comment by jkiliani** [comment]
For 4f35527d I repeated the test at different playouts:

<img width="498" alt="screen shot 2018-01-23 at 21 55 12" src="https://user-images.githubusercontent.com/33714573/35300287-4102e97e-0088-11e8-815e-5c0a99938529.png">

In general, the win rate of the low playout matches seems to approach the much lower (16.6 %) win rate of the match with increasing playout count. The only outlier is for p2, which is looked rather anomalous.

**Comment by jkiliani** [comment]
The 3.07 training set:

<img width="493" alt="screen shot 2018-01-23 at 21 54 29" src="https://user-images.githubusercontent.com/33714573/35300539-0490a692-0089-11e8-8148-e0443572c227.png">

**Comment by jkiliani** [comment]
... and the 3.09M training set:

<img width="497" alt="screen shot 2018-01-23 at 21 54 56" src="https://user-images.githubusercontent.com/33714573/35300627-4ef0a728-0089-11e8-9df5-2e2788c517aa.png">

Here, 35415bb0 and ab9824d7 scored high enough to not be screened out, as well as f8c5342a from the 3.07M set. In the case of ab9824d7 this was merited in retrospect since that network scored 34% in the distributed test. The other two seem to simply scale worse, so they aren't actually good even though they might look that way at 5 playouts. But false positives (unnecessary high playout test for a failing net) seem less problematic than a passing net missed by screening it out erroneously.

In general I have the impression that the win rates at low playouts are increasing over the last few training sets. Hopefully that's a good sign that we'll soon see an actual stronger net.

**Comment by jkiliani** [comment]
Plan change, I'll do a through scaling test for d9a5ed48 now :-)

**Comment by jkiliani** [comment]
I redid another long list of matches at 5 playouts, but unfortunately the results are disappointing: 

[Report_recent2.txt](https://github.com/gcp/leela-zero/files/1688754/Report_recent2.txt)

Most recent matches of networks that lost decisively to best-network are close in margin or even winning at this low playout count. A few isolated tests at considerably higher playouts (50 or 200) seem to improve the situation somewhat, but I don't have the resources to do this for a larger number of failed nets. It may be an interesting question why trained networks score so similarly at low playouts but very differently at high playouts (i.e., the scaling properties vary widely). However, given that I cannot prove the usefulness of this method for the purpose I originally proposed, I am closing this issue now.
