### ISSUE TITLE
leelaz crashes when using sabaki 

### ISSUE THREAD

**Issue by KarlMaoChina** [gcp/leela-zero#668]
hi there
I am trying to test the strength of current network by playing against other go engine on my computer.I load leelazero with these setting
-g --noponder --playout 10000 -t4 -w  c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43
Then leelaz thread had crashed after it gives following output
"Thinking at most 50.0 seconds...
NN eval = 0.500544"
Then there was no other output, I checked Task manager and found the leelaz thread has gone.
Sometime leelaz can play for a while (I mean play few moves before that crash happens )when using 1600 playouts. But it cannot generate any move and crash immediately after giving NN eval when using 10000 playouts.
Is there anything wrong with my setting? Thanks for answering.

**Comment by zediir** [comment]
What do you see if you start leelaz from the command line with the same settings and give it the `auto` command?

**Comment by KarlMaoChina** [comment]
@zediir 
do you mean run  leelaz.exe with "-auto -g --noponder --playout 1600 -t4 -w c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43"
command? sorry I am not a programmer. I tried this and the console had appeared and immediately gone. I don't really know how to run program with command line this so i written a .bat with "leelaz.exe" and these command. I guess that's correct?

**Comment by zediir** [comment]
I mean start it like `leelaz.exe -g --noponder --playout 10000 -t4 -w c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43`and then when it starts type `auto` and press enter.

**Comment by KarlMaoChina** [comment]
@zediir  thank you tried and it said
"Thinking at most 50.0 seconds...
NN eval=0.440025
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions."

**Comment by gcp** [comment]
Which version is this?

**Comment by zediir** [comment]
Are you using 0.10.1? someone had the same problem here https://github.com/gcp/leela-zero/issues/600#issuecomment-355970043

**Comment by KarlMaoChina** [comment]
@zediir @gcp 
I checked the latest version and it has already been fixed.Its my fault.Thanks for answering.
