### ISSUE TITLE
I found a thing that might be a bug

### ISSUE THREAD

**Issue by mark93192** [gcp/leela-zero#67]
![default](https://user-images.githubusercontent.com/22555961/32889912-ae69bd50-cb07-11e7-9cbf-2258fa62de86.png)
My computer got something like this, clearly violating the rules of go, so can you guys fix the bug, pls?

**Comment by gcp** [comment]
No, this is correct.

**Comment by WhiteHalmos** [comment]
Since there are no white stones on the board, black is given all the points: 19*19-7.5 = 353.5

**Comment by mark93192** [comment]
Thank you for the reply!
