### ISSUE TITLE
Error when trying to generate leelaz with msvc

### ISSUE THREAD

**Issue by Alderi-Tokori** [gcp/leela-zero#672]
Trying to compile the /next branch using leela-zero2017.sln, when trying to generate the executable, there is an include error when compiling OpenCL.cpp:
`1>..\..\src\OpenCL.cpp(288): fatal error C1083: Cannot open include file : 'clblast_level3/common.opencl' : No such file or directory`

Apparently, this file is missing from the external dependencies of the msvc project.

**Comment by Alderi-Tokori** [comment]
I already have it installed...

**Comment by Splee99** [comment]
Then I'm not sure what happened on your OpenCL.cpp file. On line 288 of my OpenCL.cpp I don't see any include statement.

**Comment by Alderi-Tokori** [comment]
Well mine is a little bit modified but I only changed the value of a few variables, nothing else. I'll investigate this further tomorrow.

**Comment by bood** [comment]
you may try the cmake approach too, see appveyor.yml in next branch

**Comment by gcp** [comment]
>On line 288 of my OpenCL.cpp I don't see any include statement

Then something is wrong on your side:
https://github.com/gcp/leela-zero/blob/next/src/OpenCL.cpp#L288

>Apparently, this file is missing from the external dependencies of the msvc project.

Is the file on disk? If it is, don't see why that include would fail.

**Comment by Alderi-Tokori** [comment]
>Is the file on disk? If it is, don't see why that include would fail.

This is my problem, I updated the .cpp and .h files on my windows machine but didn't realize there was a new folder in src to download. I'll close the issue, sorry for this (second time I do this kind of dumb mistake, shame one me :/ ).
