### ISSUE TITLE
A question in parsing game files

### ISSUE THREAD

**Issue by panda0307** [gcp/leela-zero#674]
I have a simple question:
In reinforcement learning, the self-play games(sgf) will be parsed for updating the parameters of networks.
I wonder whether it gets different positions or all positions(including same positions).
What is the difference between them? Is there a great impact on the training result?
Thank you!

**Comment by gcp** [comment]
>In reinforcement learning, the self-play games(sgf) will be parsed for updating the parameters of networks.

No, we parse the training data directly. The SGF does not have the accurate move probabilities from the search.

>I wonder whether it gets different positions or all positions(including same positions).

I don't understand the question. It gets random positions taken from the sample, rotated or mirrored in a random symmetry.

**Comment by panda0307** [comment]
Thank you. I didn't talk about the symmetry. 
I'm confused by the notes ("dump_supervised" function in "Training.cpp" file )
// Loop over the database multiple times. We will select different
// positions from each game on every pass.
