### ISSUE TITLE
Win rate for new networks between 50% and 55%

### ISSUE THREAD

**Issue by holicst** [gcp/leela-zero#676]
Hi,

I know that if a win rate is between 50% and 55% after 400 games then based on SPRT it is not sure that the new network is better, but I think it is almost sure that it is not worse than the existing champion. 

Would it actually have any drawbacks to promote new networks which end up between 50% and 55% win rate against the current best network?

If not then why not promote them?

Cheers,
Tamás

**Comment by evanroberts85** [comment]
Not better = worse

**Comment by holicst** [comment]
maybe a little bit better <> worse

**Comment by odinAuthor** [comment]
I think as long as networks are promoted often enough, there is enough variety in training data generation. The only reason to lower the bar for promotion would be to generate games with more variety and in that case I think it would be more clean to skip testing and just promote a network in regular intervals (which I think the Alpha Chess and Shogi paper did).

**Comment by odeint** [comment]
55% at 400 games makes sure that the probability is larger than 95% that the true win probability is >50%. The project seems to have started to extend the games to 1000 if win rate is between 50-55% at 400 games. I'm not sure which SPRT code is used exactly, but at 1000 games, a win rate of 53.2% (532/1000) would also ensure 95% confidence that the new network is better.

**Comment by Dorus** [comment]
I believe the 1000 game thing is only for historical reasons to figure out what was really the strongest net if we get no new promotions from here on. Those 1000 game limits are set by @roy7 

I'm not sure if promotions are possible from those 1000 games, at least not below 55% winrate. The last few nets we gave extra games ended with SPRT fail with <50% winrate.

**Comment by evanroberts85** [comment]
In theory if on average you had 20 networks being tested consecutively all
more or less equal with the current best, even 95% confidence is not really
enough.

**Comment by odeint** [comment]
> In theory if on average you had 20 networks being tested consecutively all
more or less equal with the current best, even 95% confidence is not really
enough.

As you say, that would be the case if all the actual true win rates are (close to) 50% and the higher rates are just statistical fluctuations. In our case it's actually better, since most networks' true win rates are more in the 20% range. Usually, we didn't even have anywhere near 20 networks close to 50-55% win rate between promotions.

**Comment by jkiliani** [comment]
At some (high) number of games, the termination criteria (95% confident to not be worse) and (95% confident to not be 35 elo better) would intersect, and a network somewhere around 52.5% would effectively pass and fail at the same time, correct?

**Comment by isty2e** [comment]
@jkiliani It's something like this (taken from #543):

![sprt_comparison](https://user-images.githubusercontent.com/571680/35147787-3a3b7224-fd53-11e7-9986-c33b73644d17.png)

The asymptote for the current one is at winrate of 52.5%.

**Comment by evanroberts85** [comment]
>
>
> That would be the case if all the actual true win rates are 50% and the
> higher rates are just statistical fluctuations. In our case it's actually
> better, since most networks' true win rates are more in the 20% range.
> Usually, we didn't even have anywhere near 20 networks close to 50-55% win
> rate between promotions.
>

I think it is actually worse. The fact that the distribution averages way
under 50% means that the chances of a strong network is considerably less
than a mediocre one. You can expect then that with high scoring networks
that it is more likely that their scores are inflated than deflated.

My knowledge of the maths behind this kind of statistics though is not
strong enough to give exact calculations.

**Comment by jkiliani** [comment]
@isty2e Yes I remember seeing this plot before. What I don't understand is why don't the asymptotes intersect? They should eventually, after all if you have the patience to run 100,000 tests, even a 51% winrate should be significant.

**Comment by Dorus** [comment]
Well the math is not that hard.


If you try a 49.999% network, it's 5% likely to pass. However a 49% network to pass is already less likely, a 45% is even less likely than that. At the same time, if you try many 49% or 45% networks, one will eventually pass.

However, most our nets are not 49%, they are 10-20%. These nets are so incredibly unlikely to pass by random chance.

Cgos ratings do suggest we sometime pass a slightly weaker net (even if only because some nets are stronger against each-other but weaker against other bots). This is nothing to worry about as long as the long-term trend is upwards. Having one network pass by 5% luck is possibly, having 2 in a row do that is very unlikely.

I will try to run a simulation and see when those lines intersect.

**Comment by isty2e** [comment]
@jkiliani That's because of the hypotheses compared in the current SPRT, i.e., it is required to be 95% likely that winrate is close to 55% than to 50%. I personally have no idea why SPRT(0, 35) is chosen, and that's the whole point of #543.

**Comment by evanroberts85** [comment]
The maths is considerably more complicated than that, the question is not
so much the 10-20% networks, but the distribution of 40+ percent networks.
Not that this really matters all that much, just an intellectual exercise.

**Comment by Dorus** [comment]
I tried to SPRT code:

![afbeelding](https://user-images.githubusercontent.com/4461459/35149064-0aee26e4-fd15-11e7-84ce-f8b28fef801a.png)

vertical = winrate
horizontal = games

200k games and it still did not end :)

**Comment by isty2e** [comment]
@Dorus They can never intersect.

**Comment by gcp** [comment]
>I personally have no idea why SPRT(0, 35) is chosen

It gives an early termination if it is 95% likely the network would be at 55% after 400 games, which corresponds to +35 Elo.

**Comment by gcp** [comment]
>even for matches with more games?

I don't plan to do "more games". We extended some matches to see which network is actually the best at the end. SPRT is completely irrelevant there.

**Comment by gcp** [comment]
Wontfix, for the explanation why see my first comment.

**Comment by isty2e** [comment]
It is indeed helpful for early termination, but what the SPRT does is not precisely to check "if it is 95% likely the network would (not) be at 55% after 400 games". It compares two hypotheses and does not test only one, and also it is not 55% nor 400 games. If the statement were to be true, 210-189 should fail, as an extreme case, for example.
