### ISSUE TITLE
please change the unit from M to K to distinguish different network file

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#678]
eg. now both 40a9ead and 7ad2442 are all 2.79M+1M , I unzip them and found they should 2.79M+1024K and 2.79M+1200K  etc

**Comment by gcp** [comment]
https://github.com/gcp/leela-zero-server/issues

**Comment by roy7** [comment]
Fixed https://github.com/gcp/leela-zero-server/commit/d2d3b21be8084bf2e7c6d8dfbaa64aa34afb5c32.
