### ISSUE TITLE
Running autogtp doesn't save .sgf files

### ISSUE THREAD

**Issue by Walther** [gcp/leela-zero#68]
I ran autogtp (v0.4) for a while on my Windows machine. The console prints the individual moves and after a game ends, mentions the dumping and sending the file to the server. However, this file is nowhere to be found - I assume the script automatically removes it or it's only in-memory.

It would be great to see the actual .sgf files accumulating in a folder, to be able to take a look at what kind of games are produced during the training.

**Comment by gcp** [comment]
autogtp cleans the files up automatically.

All games are uploaded periodically here: https://sjeng.org/zero/ (all.sgf.xz)

**Comment by chucklu** [comment]
Stopping engine.
curl.exe -F networkhash=e6779c9becc10a7e147d3cb9c5177a45d3659f95856cd7199d98d0f9ecaf156e -F clientversion=2 -F sgf=@e22cb3becaa54709bc96b78d51792898.sgf.gz -F trainingdata=@e22cb3becaa54709bc96b78d51792898.txt.0.gz http://zero.sjeng.org/submit
Game data 7394cf3eb802b5339c928efee3b34a0a0fa7ab702325ae528e77ccab8e5c1778 stored in database
1 games played.

It will make the auto gtp better.
Lots of people in China would like to check the played game after the game ended.

**Comment by fsparv** [comment]
Not presently tested on windows in any way at all, but if you have a *nix you can get sgf's with the GUI I wrote so I could see the games as they train: https://github.com/fsparv/LeelaWatcher there is an undocumented second argument for the name of the command to run which defaults to "./autogtp" which is what works for unix, so if windows folks want to experiment with feeding whatever the command on their end is it *might* work :)

**Comment by zediir** [comment]
Jep. Got it to work on windows. Thanks!

`D:\My Folders\Downloads\leela-zero-0.4-windows>java -jar LeelaWatcher-1.0.jar . autogtp.exe
autogtp v2
Best network hash: fe3f6afd23aab715be6743fd42c378ddfcd9b049ebe305478c335b8a9401ac13
Required client version: 2 (OK)
Already downloaded network.
Engine has started.
Infinite thinking time set.
1 (P9)
New Game Started!

        Move:P9
 2 (C15)        Move:C15
 3 (P12)        Move:P12
 4 (Q12)        Move:Q12
 5 (S7)         Move:S7
 6 (S17)        Move:S17
 7 (E16)        Move:E16
 8 (H4)         Move:H4`

**Comment by gcp** [comment]
The code for keeping the games was merged will be in the next release.
