### ISSUE TITLE
Autogtp and leelaz threads

### ISSUE THREAD

**Issue by marcocalignano** [gcp/leela-zero#685]
Autogtp does not specify leelaz thread on the command line so the default is use.
In the help it says 2 threads is the default even if I see only one thread for game.
Should autogtp increase the threads number on the command line? Should the server decide how many threads the client should have or should autogtp run a tune procedure at the beginning establiching the best threads number?

**Comment by Dorus** [comment]
I would love to see it auto decide on the right number :)

Only that i do like a way to quit autogtp without too much data loss. If it start multiple games i can only quit when one just completed but they almost never complete all at the same time.

That would be solver with an option to close leela after all game completed or to resume games after restarting the process.

Or just make it measure once at startup, as long as i can still manually suspend the leelaz.exe process without autogtp spawning extra processes,  can close it manually.

**Comment by gcp** [comment]
Didn't we set specifically set AutoGTP to 1?!? That should not have been changed.

There is absolutely no reason to ever use more than 1 thread when using AutoGTP, as it can play multiple games at once.

**Comment by roy7** [comment]
Yes at some point it was changed so all autogtp instances would run with 1 thread. Back when we had some thread related bug I think.

**Comment by gcp** [comment]
AutoGTP still does the right thing:
https://github.com/gcp/leela-zero/blob/master/autogtp/Management.cpp#L191

**Comment by gcp** [comment]
I increased the default to 2 (not threads, AutoGTP instances!) at some point, but people remarked that this made their computer unusable while AutoGTP is running, whereas it otherwise is fine if it just runs in the background (and you don't game). That's why we default -g 1.

**Comment by marcocalignano** [comment]
So no changes needed! I will close this.
