### ISSUE TITLE
how to verify the leelaz version

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#688]
I downloaded the latest 0.11 cpu win32 version, and put it in the directory of 0.10.1.
<b>
it shows following message
</b>
C:\leela10>autogtp -k sga
AutoGTP v11
Using 1 thread(s) for GPU(s).
Starting thread 1 on GPU 0
{
    "cmd": "selfplay",
    "hash": "c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43",
<b>    "leelaz_version": "0.10", </b>
    "options": {
        "noise": "true",
        "playouts": "1600",
        "randomcnt": "30",
        "resignation_percent": "0"
    },
    "options_hash": "cf1fad",
    "random_seed": "14739271295012192389",
<b>    "required_client_version": "11" </b>
}

Got new job: selfplay
Net filename: c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43
net: c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43.
Engine has started.
Infinite thinking time set.
1 (B K4) 2 (W D16) 

and I run it by itself, no version info outputs.
<pre>
C:\leela10>leelaz -w c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43
Using 2 thread(s).
RNG seed: 11334487319912817225
Leela Zero  Copyright (C) 2017-2018  Gian-Carlo Pascutto and contributors
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

Detecting residual layers...v1...64 channels...5 blocks.
BLAS Core: Nehalem

Passes: 0            Black (X) Prisoners: 0
Black (X) to move    White (O) Prisoners: 0

   a b c d e f g h j k l m n o p q r s t
19 . . . . . . . . . . . . . . . . . . . 19
18 . . . . . . . . . . . . . . . . . . . 18
17 . . . . . . . . . . . . . . . . . . . 17
16 . . . + . . . . . + . . . . . + . . . 16
15 . . . . . . . . . . . . . . . . . . . 15
14 . . . . . . . . . . . . . . . . . . . 14
13 . . . . . . . . . . . . . . . . . . . 13
12 . . . . . . . . . . . . . . . . . . . 12
11 . . . . . . . . . . . . . . . . . . . 11
10 . . . + . . . . . + . . . . . + . . . 10
 9 . . . . . . . . . . . . . . . . . . .  9
 8 . . . . . . . . . . . . . . . . . . .  8
 7 . . . . . . . . . . . . . . . . . . .  7
 6 . . . . . . . . . . . . . . . . . . .  6
 5 . . . . . . . . . . . . . . . . . . .  5
 4 . . . + . . . . . + . . . . . + . . .  4
 3 . . . . . . . . . . . . . . . . . . .  3
 2 . . . . . . . . . . . . . . . . . . .  2
 1 . . . . . . . . . . . . . . . . . . .  1
   a b c d e f g h j k l m n o p q r s t

Hash: 30C547108A9AF65F Ko-Hash: 9EC2A5B7968B5F23

Black time: 01:00:00
White time: 01:00:00

</pre>

**Comment by roy7** [comment]
When you run leelaz, type in 'version' to see it.

**Comment by l1t1** [comment]
@roy7 thanks
