### ISSUE TITLE
time_settings doesn't work

### ISSUE THREAD

**Issue by godmoves** [gcp/leela-zero#690]
It can set time correctly for the fist time, but the engine doesn't respond to `time_settings` command if I want to change time settings again.   
It seems that this problem occurs in Leela Zero 0.11 only.

**Comment by roy7** [comment]
I'm seeing a similar problem with my bots, might be https://github.com/gcp/leela-zero/issues/691#issuecomment-359153824.

**Comment by gcp** [comment]
I'll look into this on monday, but 2 recent changes that might have had an effect:

a) Some recent refactoring of TimeControl.cpp.
b) Tree reuse changes some management around GameState, which contains TimeControl.

Sounds like a good candidate for adding unit tests.

**Comment by gcp** [comment]
This is still completely broken. Now time settings changes take effect, but the clock always resets. @killerducky

**Comment by killerducky** [comment]
Ok I will look at it tonight.

**Comment by roy7** [comment]
Ug. Maybe time for an emergency revert to v10 for my little bots.

**Comment by gcp** [comment]
This should be fixed in "next" now.
