### ISSUE TITLE
Net missing

### ISSUE THREAD

**Issue by Dorus** [gcp/leela-zero#698]
![afbeelding](https://user-images.githubusercontent.com/4461459/35184514-ffc359e6-fdf6-11e7-9d8b-e29190afe454.png)

I get this message constant.

```text
Network connection to server failed.
NetworkException: Failed to fetch the network.
Rertying in n s.
```

 @roy7 @gcp 

Edit: After 3 failed attempts, the 4th got a self play games so at least leelaz is running a game again.

**Comment by MaxMaki** [comment]
I got exactly the same error message for a match, with the network.gz: not in gzip format, as well as the other error messages

**Comment by Dorus** [comment]
It just happened again. This time i got

```text
Maximum number of retries exceeded. Falling back to previous network.
```
I guess that means it is back to selfplay now too.

![afbeelding](https://user-images.githubusercontent.com/4461459/35184739-bd644f12-fdf9-11e7-9fe4-da0306f1911f.png)

**Comment by roy7** [comment]
I don't know what would cause that. The file is on server and gunzip --test says it's valid. The best-network.gz is also valid and is identical to the 7fde81e8 network file, i checked that too just in case.

I do see for 7fde81e8 I needed to re-tune so I'm guessing we've moved to a bigger network?

**Comment by Ttl** [comment]
I get this error too. It seems that the net is missing the first character. There is a net in /networks that starts with 2671f15, but autogtp is looking for 671f15. The first character is missing in autogtp.

**Comment by roy7** [comment]
Thank you, that's the problem. I'll go find where the typo network name is and fix it in database.

**Comment by roy7** [comment]
Fixed! Working now?

**Comment by roy7** [comment]
With 0 matches arriving I'm assuming not. Hmm.

**Comment by roy7** [comment]
What happens with tuning when two matches of different sizes match up? They both overwrite leelaz_opencl-tuning right? It doesn't store a weight per network size?

**Comment by Ttl** [comment]
If configuration with the same number of channels already exists it uses it. Otherwise the new configuration is appended to the tuning file.

**Comment by roy7** [comment]
Ahh that's a relief. Is it safe to run --full-tune multiple times and it'll only replace the matching one, and the older sizes will remain in the file?

**Comment by Ttl** [comment]
It should only overwrite the tuners with the same number of channels. Previous tuners should stay unchanged.

**Comment by roy7** [comment]
I gotta remember that for the future to pre-tune so bot doesn't have a long delay to tune a new network while trying to play games lol.

**Comment by akdtg** [comment]
Seems like net http://zero.sjeng.org/networks/f72fae404047f018b489149f2a66f5983127781e7fdd859257505c46fa2ccf1a.gz was missed from the matches queue, since 0cd26764 has appeared after 2671f15a

**Comment by roy7** [comment]
Correct, I don't see a match for it queued. @gcp

**Comment by roy7** [comment]
Could someone let me know the name of a 10 layer network so I can pro-actively go tune for it in case it promotes eventually?

**Comment by Ttl** [comment]
Only the number of channels affects the tuning. You don't need to tune for 10x128 if you have already tuned for any 128 channel network.

**Comment by akdtg** [comment]
@roy7, The compressed size of 10x128 nets  are about 1.5MB, just check top of the http://zero.sjeng.org/networks

**Comment by roy7** [comment]
Is the tuning only for filters and not layers? The tune with a 10x128 seems to replaced my prior 6x128 but left the 5x64 in there.

**Comment by gcp** [comment]
The layers are evaluated sequentially so the number of them has no effect on the optimal tuning.

**Comment by gcp** [comment]
I'm closing this. The missing network was a copypaste error from me when I manually queued matches for the 10x128 networks.
