### ISSUE TITLE
AutoGTP/Leela (0.11) on Windows 6 times slower compared to Ubuntu?

### ISSUE THREAD

**Issue by MaxMaki** [gcp/leela-zero#700]
I'm having a very weird situation where on the same computer Ubuntu gives me 1140ms/move on a GTX 1060, but when booting to Windows i'm getting around 7500/ms move.

Curiously the optimizer gives a very similar value for both Windows and Linux, but actually generating data is much slower.

There used to be a small different between Windows and Linux (10-20%), but since switching to the new version it's a ridicilous 600% difference.

GPU clocks are similar on both distros while running. I've noticed on 0.11 that the GPU load fluctuates a lot more on Windows than it does on Linux, but not so much that it should give over a 6x difference.

Does anyone else running Windows have the same problem? Does anyone else here have a Linux and Windows dual boot to check if this problem exists for them as well?

**Comment by MaxMaki** [comment]
After running the 0.11 and 0.10.1 AutoGTPs back to back with the same settings i'm getting 2300/ms move on AutoGTP 0.10.1 , but over 7000 on 0.11.

So 0.11 is basically unusable for me. The old version is 3 times faster on Windows.

**Comment by gcp** [comment]
Are you sure you are comparing the same size network? We just switched from 5x64 to 6x128.

Linux has always been a bit faster than Windows due to much larger overhead on the latter, but I've never seen differences as big as you describe, IIRC.

**Comment by MaxMaki** [comment]
Yes, both running 6x128

**Comment by zediir** [comment]
Similar for me. On Windows with the same network I'm getting around 2000 n/s and on linux I'm getting around 5000 n/s with the same settings. That's not taking into account that on linux I'm getting 7300 n/s with two gpus (gtx 1080) and on windows I'm getting under ~1500 n/s with two gpus.

**Comment by MaxMaki** [comment]
All of the suddent i'm getting roughly 1600ms/move on both 32-bit and 64-bit, i have absolutely no clue why this has changed. But it seems to be working now.

I'm very sorry. I did double run earlier several times to see that the 7500ms/move was repeating. But as soon as i made this post it seems to have disappeared..

I'm sorry for wasting your time, please close this issue.

**Comment by gcp** [comment]
For reference:

I get ~1800 ms/move on Linux with a GTX 1060.
I get ~2200 ms/move on Windows 10 with a GTX 1070.

So there's clearly a severe penalty for Windows, but it is not as big as reported here.

Note that ms/move is not comparable between 0.10 and 0.11 at all, due to tree reuse (which makes it slower, as we explore much more *new* moves).
