### ISSUE TITLE
Is this a bug? : "winograd_convolve3(output_channels, input, conv_weights[0], V, M, conv_out)"

### ISSUE THREAD

**Issue by sbf2000** [gcp/leela-zero#703]
When use 5 block,16filter network, the program is crashed, bacause input layer have 18 feature,V is too small.

**Comment by glinscott** [comment]
Interesting, I had to do this for the port to chess: https://github.com/glinscott/leela-chess/blob/master/src/Network.cpp#L716-L720

**Comment by sbf2000** [comment]
try:
auto V1 = std::vector<float>(WINOGRAD_TILE * 18 * tiles);
......
winograd_convolve3(output_channels, input, conv_weights[0], V1, M, conv_out)

Program is normally.

**Comment by gcp** [comment]
@Ttl Do you want to have a look at dealing with this edge case, and perhaps do the chess people a favor and look at the above as well? Humanity thanks you.

**Comment by gcp** [comment]
Oh, and I bet @glinscott has a problem because his input channels are *larger* than the residual stack!
