### ISSUE TITLE
AutoGTPv13/Leela (v0.11 GPU) 64-bit crash on Windows

### ISSUE THREAD

**Issue by FFLaguna** [gcp/leela-zero#706]
My Leela Zero 0.11 + AutoGTP v13 (Windows, 64-bit) crashed on its very first run between moves 33 and 34. The cmd window shows autogtp.exe crashed after posting "33 (B S17)" but before posting Move 34. I was running only one game, and used no commandline options.

I reran autogtp.exe and the next game crashed again, after posting Move 421 but before posting Move 422. The crashing module is **"leelaz.exe".**

I have no other information or reproducability steps.

Can I enable a crash log or something to provide more info in the future?

**Comment by FFLaguna** [comment]
My specs:

- Leela Zero 0.11 + AutoGTP v13 (GPU version)
- No command line options used, just "autogtp.exe"
- Windows 10 64-bit
- GTX 1070, not overclocked
- Intel i5-3570k, stable overclock for a long time
- No crashes on previous LZ versions, including Leela Zero 0.10.1 + AutoGTP v11 with -g 4.

**Comment by odeint** [comment]
Are you sure it is not the Windows console hanging with a white rectangle cursor somewhere? Check if leelaz.exe is still active in the task manager. I found that Ctrl-C can in that case resume the console output (usually it quits the program but in that edit-mode hangup it cancels that mode somehow).

**Comment by FFLaguna** [comment]
I'm familiar with the "white rectangle cursor" issue you mention, it's definitely not that.

Windows actually popped up with a prompt saying that leelaz.exe has crashed.

I have since run autogtp.exe -g 4 and I have submitted four games successfully so far.

**Comment by gcp** [comment]
Which GPU driver version?

**Comment by FFLaguna** [comment]
I've been running GTX 1070 driver version **390.65** (listed alternatively as 23.21.13.9065).

It's the most recent nVidia driver release, from January 8th, 2018. I installed it on Jan. 11th, been using it for a while.

**Comment by FFLaguna** [comment]
I've run just autogtp.exe (no command line options) again, and it generated three more games with no crashes. Here's my timeline:

1. Ran "autogtp.exe" with no command line options.
2. "leelaz.exe" crashed between Moves 33 and 34.
3. Ran "autogtp.exe" again with no command line options.
4. "leelaz.exe" crashed between Moves 421 and 422.
5. Ran "autogtp.exe -g 4".
6. Generated and uploaded four games with no crashes.
7. Stopped running LZ for a few hours.
8. Did a full tuning and got some extra GFlops
9. Ran "autogtp.exe" again with no command line options.
10. Generated and uploaded three games in a row, no crashes.

Wish I had more information for you.
