### ISSUE TITLE
AutoGTP: Perform start-up operations in fail-fast order (or multi-threaded perhaps) E.g. tuning after network connection

### ISSUE THREAD

**Issue by wctgit** [gcp/leela-zero#710]
Issue: I'm trying to use AutoGTP, and it fails at the stage of trying to establish a network connection. However, before it gets to this stage, it goes through the lengthy tuning process. Since I'm trying to reproduce the network problem, it's very very annoying to have to wait for the tuning process every time I start up AutoGTP.

Expected behaviour: Perform any start up procedures in a fail-fast manner, i.e. if something will take 10s to fail, and another thing 0.1s to fail, do the 0.1s thing first. (Assuming the tasks are not required to be in the other order, of course.) Alternatively, put activities that are relatively independent in separate threads so that they can fail independently. The latter is obviously harder to implement, but could potentially speed up startup even more than simple fail-fast ordering.

**Comment by gcp** [comment]
Tuning only has to be done once.

**Comment by gcp** [comment]
Tuning requires a network file, so that must be serialized. Self-play after tuning requires the tuning result, so that must be serialized as well. Unless I'm missing anything I do not think your suggestions work. Maybe @marcocalignano can see if I missed anything.

**Comment by marcocalignano** [comment]
For the the tuning phase autogtp make a connection to the server and download a self played work with the current best network. It then downloads the network (if it does not have it) and then start the tuning. 
So you connected to server already. Can you post the output of your autogtp where the error occurs please?

**Comment by wctgit** [comment]
I believe this problem is caused by the same underlying issue as #712, where under certain folders in Windows, unless the 'proper' Windows-like installation procedure is followed (universally handled by making an executable installer; maybe some time down the road...), there seems to be a restriction on the creation of files with names that do not have any extension. Thus, "leelaz_opencl_tuning" fails to get saved. Immediate fix could be to simply add ".txt" to the generated file name. Alternatively, invent a new filename extension for the opencl tuning text format. Another alternative might be to switch the format to something in XML and use an .xml extension. Or .json, or whatever.

But, as long as we don't have any control over where the user unzips the release bundle, I'm pretty sure this problem will keep biting us in the ass.

**Comment by roy7** [comment]
Since it's a text file, .txt seems easy enough?

**Comment by wctgit** [comment]
Perhaps my last comment wasn't clear. The delay I was experiencing was probably more related to the downloading of the network file, rather than the tuning. See the output listed in #712. After "Starting tuning process, please wait...", there was a delay of about 10 seconds, and only then did it say:

> gzip: 7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a.gz: No such file or directory
> Net filename: 7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a
> Network connection to server failed.
> NetworkException: Failed to fetch the network
> Retrying in 30 s.

Thus, I thought the delay was related to the tuning process, when actually it seems the tuning process hadn't occurred yet (for lack of the files to work on).
