### ISSUE TITLE
why leelaz 0.11 is slower than 0.10

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#717]
![2018-01-22_091545](https://user-images.githubusercontent.com/23301704/35201272-e88cce42-ff54-11e7-8ac8-51fb5ad1b567.png)
I first run version 0.10
when network is downloaded, I copy it to 0.11 directory.
then I run version 0.11
at first, 0.10 is about 10 steps lead
now 0.10 is about 20 steps lead

**Comment by l1t1** [comment]
run on same computer, they are all win64 version

**Comment by Splee99** [comment]
There is tree re-use code in 0.11, which is supposed to make the search more efficient.

**Comment by fell111** [comment]
I could be either tree-reuse or the tuning for networks. You need to redo the tuning if your previous tuning was for 5x64 networks.

**Comment by l1t1** [comment]
tuning is done after I run 0.11

**Comment by l1t1** [comment]
0.11 game is finished
<pre>
(B H1) 218 (W resign) Game has ended.
Score: B+Resign
Winner: black
Stopping engine.
Uploading game: 50e16d5d1d7d41bdb80d09065b1be72a.sgf for network 7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cf
e1c86575a
Game data de7a982d05388f9713d63eb1903f2a9517987b40778cc47dfd06b339228a1187 stored in database
1 game(s) (1 self played and 0 matches) played in 134 minutes = 8040 seconds/game, 36880 ms/move, last game took 8037 seconds.
</pre>

**Comment by l1t1** [comment]
I saw "2018-01-19 Leela Zero 0.11 + AutoGTP v13. Tree re-use code makes 0.11 slower but stronger than 0.10." on web page, thanks

**Comment by l1t1** [comment]
0.10 game is also finished
<pre>
9) 345 (B B8) 346 (W R15) 347 (B G13) 348 (W P18) 349 (B F16) 350 (W Q5) 351 (B T10) 352 (W resign) Game has ended.
Score: B+Resign
Winner: black
Stopping engine.
Uploading game: 2ec2e14f331d439887fb57dd00bc22f7.sgf for network 7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cf
e1c86575a
Game data 27c1882f1863370edc5c1a395c0e7de7ebb55c53294c9e7d5940290d307682f9 stored in database
1 game(s) (1 self played and 0 matches) played in 215 minutes = 12905 seconds/game, 36661 ms/move, last game took 12777
seconds.
</pre>

**Comment by gcp** [comment]
>You need to redo the tuning if your previous tuning was for 5x64 networks.

You don't need to do anything, the re-tuning is automatic.
