### ISSUE TITLE
what's different between "resignation_percent": "1" and "0"?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#719]
I got two games today. their info are diff.
1
{
    "cmd": "selfplay",
    "hash": "7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a",
    "leelaz_version": "0.10",
    "options": {
        "noise": "true",
        "playouts": "1600",
        "randomcnt": "30",
 <b>       "resignation_percent": "1" </b>
    },
    "options_hash": "16b7b7",
    "random_seed": "12703117826430416189",
    "required_client_version": "11"
}
2
{
    "cmd": "selfplay",
    "hash": "7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a",
    "leelaz_version": "0.10",
    "options": {
        "noise": "true",
        "playouts": "1600",
        "randomcnt": "30",
<b>        "resignation_percent": "0" </b>
    },
    "options_hash": "cf1fad",
    "random_seed": "14672172766107718977",
    "required_client_version": "11"
}

**Comment by Splee99** [comment]
Resignation percentage = 1 means LZ will resign when the winrate is lower than 1%. Resignation percentage = 0 means no resign allowed and LZ will play to the end.

**Comment by l1t1** [comment]
@Splee99
if both side don't  resign, must they  play 723 moves?

**Comment by l1t1** [comment]
why set different  Resignation percentage ?
to avoid wrong resign?

**Comment by roy7** [comment]
20% of games have a resignation percent of 0%, so the game must be played to the bitter end. This is to help LZ learn end game and scoring.

**Comment by l1t1** [comment]
@roy7 thanks
