### ISSUE TITLE
--full-tuner crashes with Error building kernels

### ISSUE THREAD

**Issue by Dorus** [gcp/leela-zero#729]
![afbeelding](https://user-images.githubusercontent.com/4461459/35244822-d317560a-ffc1-11e7-85e1-47a488a3c9f6.png)

![afbeelding](https://user-images.githubusercontent.com/4461459/35244829-d7aa189c-ffc1-11e7-8f76-5b09336f85fd.png)

Not sure what caused it, i tried to run it twice, same result.

**Comment by l1t1** [comment]
maybe some files are destoried

**Comment by gcp** [comment]
This is because your driver can't manage to compile some of the OpenCL kernels. However given that (from the screenshot), it errors out, we should catch the error and skip this kernel. It looks like the exception doesn't get caught.

**Comment by gcp** [comment]
Actually, nope, our code does the correct thing, skips the error and tries the next configuration. 

This error occurs after the tuning process, when we try to build the kernels that don't need to be tuned. The OpenCL compiler in the driver errors out, and the "Error building kernels" is supposed to be followed by the error, but as you can see there's nothing there.

So this is just the OpenCL driver being broken.

**Comment by gcp** [comment]
Closing this as it doesn't look fixable on our side.

**Comment by gcp** [comment]
Note that the tuning process completed, so the result will still have been saved to disk.

**Comment by gcp** [comment]
I ended up implementing a workaround for this. I don't have the affected card/driver version, so I can't verify it, but I think it will avoid this driver induced crash.

**Comment by alreadydone** [comment]
How long did it take to go from (1915/5247) to Error building kernels? If it's short then maybe some garbage left by some failed combination caused the remaining combinations to be skipped quickly?
