### ISSUE TITLE
why white pass and  black run a lot of moves

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#730]
resignation_percent !="0"
<pre>
{
    "cmd": "selfplay",
    "hash": "7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a",
    "leelaz_version": "0.10",
    "options": {
        "noise": "true",
        "playouts": "1600",
        "randomcnt": "30",
        "resignation_percent": "1"
    },
    "options_hash": "16b7b7",
    "random_seed": "7826618935244419708",
    "required_client_version": "11"
}

Got new job: selfplay
net: 7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a.
Engine has started.
Infinite thinking time set.
1 (B Q16) 2 (W D16) 3 (B Q3) 4 (W Q17) 5 (B P17) 6 (W R16) 7 (B R17) 8 (W Q18) 9 (B R18) 10 (W P18) 11 (B P16) 12 (W S18
) 13 (B O18) 14 (W S17) 15 (B Q4) 16 (W D4) 17 (B K3) 18 (W R15) 19 (B M3) 20 (W R5) 21 (B R8) 22 (W Q5) 23 (B D17) 24 (
W E17) 25 (B C17) 26 (W C16) 27 (B R19) 28 (W S19) 29 (B C3) 30 (W E16) 31 (B C4) 32 (W D6) 33 (B D5) 34 (W E5) 35 (B C5
) 36 (W E6) 37 (B C7) 38 (W O5) 39 (B P8) 40 (W O3) 41 (B P4) 42 (W C6) 43 (B B6) 44 (W Q7) 45 (B P5) 46 (W P6) 47 (B Q8
) 48 (W B7) 49 (B B8) 50 (W O4) 51 (B O6) 52 (W S3) 53 (B P7) 54 (W Q6) 55 (B S2) 56 (W N6) 57 (B O7) 58 (W R3) 59 (B P2
) 60 (W R2) 61 (B O2) 62 (W L5) 63 (B J5) 64 (W L7) 65 (B J7) 66 (W L9) 67 (B J9) 68 (W L11) 69 (B L17) 70 (W D3) 71 (B
E4) 72 (W C2) 73 (B D2) 74 (W E3) 75 (B F4) 76 (W F3) 77 (B E2) 78 (W F2) 79 (B B2) 80 (W G4) 81 (B F5) 82 (W G6) 83 (B
N5) 84 (W N4) 85 (B N7) 86 (W M5) 87 (B H3) 88 (W F6) 89 (B M7) 90 (W K7) 91 (B J6) 92 (W N2) 93 (B N3) 94 (W Q2) 95 (B
P3) 96 (W M2) 97 (B L2) 98 (W M4) 99 (B L3) 100 (W R4) 101 (B N1) 102 (W K9) 103 (B J10) 104 (W O11) 105 (B Q11) 106 (W
F9) 107 (B D8) 108 (W E8) 109 (B D9) 110 (W D7) 111 (B A7) 112 (W K12) 113 (B S6) 114 (W S5) 115 (B R13) 116 (W J17) 117
 (B L15) 118 (W C12) 119 (B F10) 120 (W G10) 121 (B G11) 122 (W E10) 123 (B F11) 124 (W E9) 125 (B G9) 126 (W G8) 127 (B
 H10) 128 (W M14) 129 (B L14) 130 (W L13) 131 (B J13) 132 (W N13) 133 (B G17) 134 (W G16) 135 (B H16) 136 (W H17) 137 (B
 G18) 138 (W F18) 139 (B J16) 140 (W G19) 141 (B M10) 142 (W M11) 143 (B N10) 144 (W L10) 145 (B M15) 146 (W G15) 147 (B
 N14) 148 (W M13) 149 (B O14) 150 (W M6) 151 (B N11) 152 (W O12) 153 (B O10) 154 (W N12) 155 (B R7) 156 (W B10) 157 (B S
14) 158 (W E12) 159 (B F13) 160 (W E13) 161 (B F14) 162 (W H18) 163 (B S15) 164 (W S16) 165 (B Q14) 166 (W K8) 167 (B H8
) 168 (W M8) 169 (B M9) 170 (W P10) 171 (B N8) 172 (W P11) 173 (B Q10) 174 (W D10) 175 (B B9) 176 (W C10) 177 (B K18) 17
8 (W A18) 179 (B H14) 180 (W J12) 181 (B H12) 182 (W K13) 183 (B P13) 184 (W K14) 185 (B H15) 186 (W E14) 187 (B F15) 18
8 (W F16) 189 (B J11) 190 (W Q19) 191 (B O8) 192 (W K5) 193 (B K6) 194 (W L6) 195 (B P9) 196 (W H2) 197 (B J2) 198 (W G3
) 199 (B H1) 200 (W G2) 201 (B H4) 202 (W T5) 203 (B T6) 204 (W G5) 205 (B A10) 206 (W A11) 207 (B A9) 208 (W R6) 209 (B
 S7) 210 (W C9) 211 (B C8) 212 (W F12) 213 (B B11) 214 (W B12) 215 (B A12) 216 (W A13) 217 (B A11) 218 (W B13) 219 (B O1
9) 220 (W Q15) 221 (B P15) 222 (W K17) 223 (B K16) 224 (W L8) 225 (B M1) 226 (W S1) 227 (B P1) 228 (W H7) 229 (B J18) 23
0 (W H19) 231 (B Q1) 232 (W J8) 233 (B H9) 234 (W R1) 235 (B G12) 236 (W G14) 237 (B G13) 238 (W J4) 239 (B K4) 240 (W H
5) 241 (B J3) 242 (W H6) 243 (B J4) 244 (W E11) 245 (B L18) 246 (W P12) 247 (B Q12) 248 (W T16) 249 (B T15) 250 (W E15)
251 (B J19) 252 (W F19) 253 (B R14) 254 (W J14) 255 (B H13) 256 (W O13) 257 (B C11) 258 (W D11) 259 (B J1) 260 (W B17) 2
61 (B L4) 262 (W J15) 263 (B C1) 264 (W K15) 265 (B G1) 266 (W K11) 267 (B F1) 268 (W K10) 269 (B P19) 270 (W T1) 271 (B
 M12) 272 (W L12) 273 (B N9) 274 (W F17) 275 (B O17) 276 (W C18) 277 (B L16) 278 (W D18) 279 (B B5) 280 (W C14) 281 (B E
1) 282 (W T2) 283 (B S9) 284 (W F8) 285 (B N2) 286 (W R18) 287 (B N16) 288 (W D13) 289 (B T7) 290 (W G17) 291 (B S12) 29
2 (W A19) 293 (B A1) 294 (W T18) 295 (B L19) 296 (W F4) 297 (B B18) 298 (W C19) 299 (B pass) 300 (W F7) 301 (B pass) 302
 (W B15) 303 (B A3) 304 (W B19) 305 (B E18) 306 (W T4) 307 (B pass) 308 (W E19) 309 (B C17) 310 (W D17) 311 (B M19) 312
(W pass) 313 (B A16) 314 (W A15) 315 (B pass) 316 (W M16) 317 (B M17) 318 (W N17) 319 (B R9) 320 (W pass) 321 (B N18) 32
2 (W B16) 323 (B pass) 324 (W A17) 325 (B A14) 326 (W T9) 327 (B S8) 328 (W pass) 329 (B C15) 330 (W D15) 331 (B T13) </pre><b>33
2 (W pass) 333 (B S10) 334 (W B14) 335 (B T11) 336 (W pass) 337 (B A5) 338 (W pass) 339 (B K1) 340 (W pass) 341 (B T10)
342 (W pass) 343 (B S11) 344 (W pass) 345 (B T8) 346 (W pass) 347 (B S13) 348 (W pass) 349 (B N15) 350 (W pass) 351 (B N
17) 352 (W pass) 353 (B Q9) 354 (W pass) 355 (B D1) 356 (W pass) 357 (B B1) 358 (W pass) 359 (B Q13) 360 (W pass) 361 (B
 B3) 362 (W pass) 363 (B K19) 364 (W pass) 365 (B A8) 366 (W pass) 367 (B O1) 368 (W pass) 369 (B A6) 370 (W pass) 371 (
B P14) 372 (W pass) 373 (B A4) 374 (W pass) 375 (B R11) 376 (W pass) 377 (B B4) 378 (W pass) 379 (B L1) 380 (W pass) 381
 (B A2) 382 (W pass) 383 (B G10) 384 (W pass) 385 (B O15) 386 (W pass) 387 (B C2) 388 (W pass) 389 (B T9) 390 (W pass)
</b>

**Comment by roy7** [comment]
White probably thinks it has won and black can't resign until odds of winning are under 1%. Maybe it has a 5% chance to win, so black keeps moving. White just ignores him.

**Comment by l1t1** [comment]
you are right
<pre>391 (B N19) 392 (W pass) 393 (B T12) 394 (W pass) 395 (B T14) 396 (W pass) 397 (B R10) 398 (W pass) 399 (B O16) 400 (W pa
ss) 401 (B R12) 402 (W pass) 403 (B M18) 404 (W pass) 405 (B M16) 406 (W pass) 407 (B K2) 408 (W pass) 409 (B B7) 410 (W
 pass) 411 (B resign) Game has ended.
Score: W+Resign
Winner: white
</pre>

**Comment by l1t1** [comment]
this is the game sgf
http://zero.sjeng.org/view/ba7fe56d1dc92b92174e70e4112583f77848102f31a7170053eb03e8bd1c0583?viewer=eidogo

**Comment by l1t1** [comment]
black fills its eyes, in Chinese rule, this is suicide

**Comment by Alderi-Tokori** [comment]
No it isn't, black didn't remove its last liberty.

**Comment by l1t1** [comment]
@Alderi-Tokori I think move 409 fill the last liberty.
![2018-01-24_105104](https://user-images.githubusercontent.com/23301704/35312030-7fb40812-00f4-11e8-969b-520a4f674186.png)

![2018-01-24_105139](https://user-images.githubusercontent.com/23301704/35312099-c30c70ae-00f4-11e8-8289-fc9f24ab61f0.png)

**Comment by roy7** [comment]
M2 is the last liberty.
