### ISSUE TITLE
why a new network need another tuning

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#734]
Ifound new best network file has born, so I canceled the old game, and start a new one.
I notice <b>Starting tuning process, please wait...</b>in the log
<pre>
{
    "cmd": "selfplay",
    "hash": "7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a",
    "leelaz_version": "0.10",
    "options": {
        "noise": "true",
        "playouts": "1600",
        "randomcnt": "30",
        "resignation_percent": "1"
    },
    "options_hash": "16b7b7",
    "random_seed": "5207927713810801602",
    "required_client_version": "11"
}

Got new job: selfplay
net: 7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a.
Engine has started.
Infinite thinking time set.
1 (B D3) 2 (W C3) 3 (B C4) 4 (W H13) 5 (B D4) 6 (W Q4) 7 (B R16) ^C
D:\tool\leela11>autogtp -k sga
AutoGTP v13
Using 1 thread(s) for GPU(s).
Starting tuning process, please wait...
Net filename: d9a5ed4897bca5499bcec21cdeadb0d180d9e0879be35af7de322537d666d75e
net: d9a5ed4897bca5499bcec21cdeadb0d180d9e0879be35af7de322537d666d75e.
./leelaz --tune-only -w d9a5ed4897bca5499bcec21cdeadb0d180d9e0879be35af7de322537d666d75e
Using 2 thread(s).
RNG seed: 4639718571818070783
Detecting residual layers...v1...128 channels...6 blocks.
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 8.0.0
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce GT 730
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 376.62
Device speed:  901 MHz
Device cores:  2 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GT 730
with OpenCL 1.2 capability.
Loaded existing SGEMM tuning.
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64
Tuning process finished
Starting thread 1 on GPU 0
{
    "cmd": "selfplay",
    "hash": "d9a5ed4897bca5499bcec21cdeadb0d180d9e0879be35af7de322537d666d75e",
    "leelaz_version": "0.10",
    "options": {
        "noise": "true",
        "playouts": "1600",
        "randomcnt": "30",
        "resignation_percent": "1"
    },
    "options_hash": "16b7b7",
    "random_seed": "9386011282114217536",
    "required_client_version": "11"
}

Got new job: selfplay
net: d9a5ed4897bca5499bcec21cdeadb0d180d9e0879be35af7de322537d666d75e.
Engine has started.
Infinite thinking time set.

</pre>

**Comment by marcocalignano** [comment]
And ten at the end 
> Loaded existing SGEMM tuning.
> Wavefront/Warp size: 32
> Max workgroup size: 1024
> Max workgroup dimensions: 1024 1024 64
> Tuning process finished

so no problem here!

**Comment by l1t1** [comment]
@marcocalignano thanks
