### ISSUE TITLE
GPU usage

### ISSUE THREAD

**Issue by ThePokerDude** [gcp/leela-zero#735]
I have a Ryzen 7 1700X and a Geforce GTX 1070
Before the update to Leela Zero 0.11 + AutoGTP v13 I usually opened 3 instances of autogtp which use around 70% of my GPU capacity and around 15-20% of CPU capacity (task manager).
After the update (no matter how many instances I open the GPU usage stays at around 35%.
Every additional instance however increases CPU usage by 6%.

Can I change the configuration or use a command to let Leela zero use more of the GPU?

**Comment by MaxMaki** [comment]
You can try running the full tuner, for some people it seems to be a big help, for others a very small one, but doesn't hurt trying.

remove the leelaz_opencl_tuning file, then run
leelaz --tune-only --full-tuner -w networkfile_of_current_network

Will take about 15-30 minutes, but only needs to be done once

**Comment by marcocalignano** [comment]
Try to start autogtp with -g 6 or -g 8

**Comment by ThePokerDude** [comment]
I tried both. First I run the full tuner an d then opened several instances of autogtp.
The I started autogtp with -g6.

My task manger still shows me 35% GPU usage.

**Comment by FFLaguna** [comment]
I know the answer to this.

Windows does _**not**_ show accurate GPU usage, period. If you google around about this, there are plenty of sources that confirm this. I'm not sure if it's due to a Windows bug, or a fundamental hardware limitation that prevents accurate measurement.

**Comment by sethtroisi** [comment]
To nitpick at Windows expense, it can't be fundamental hardware limitations, as Linux is able to do it.

**Comment by gcp** [comment]
On the Windows task manager, with an NVIDIA card, you can switch the what the GPU usage graphs show. If you switch it to "Compute_0", you will see that the card is in fact 100% loaded.

**Comment by ThePokerDude** [comment]
Thanks for the answers. "Compute_0" is the solution which I also found in a crypto mining forum.
It seems like three instances running parallel get the most out of my GPU.
