### ISSUE TITLE
could you release a leela 0.11  benchmark for refer

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#736]
I found latest network plus leelaz 0.11 is still weaker than leela 0.11 from http://www.yss-aya.com/cgos/19x19/cross/LZ-d9a5ed-t1-p1600.html
I wonder the rate of leela 0.11 vs  leelaz

**Comment by roy7** [comment]
A single game result is meaningless. Wait for it to get to 100 and appear on the Bayes ELO chart, then you'll have an idea how strong d9a5ed is.

**Comment by gcp** [comment]
Last time I tested Leela Zero was still a lot weaker than Leela 0.11. Leela 0.11 has a bigger network, human constructed inputs and a second Monte Carlo evaluation.
