### ISSUE TITLE
why  f0d5f0ab VS d9a5ed48 match isn't finished?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#738]
we can see from

2018-01-23 23:09 | f0d5f0ab VS d9a5ed48 | 208 : 184 (53.06%) | 392 / 400 |  
-- | -- | -- | -- | --

that the rate cannot reach 55% for it has lost 184(max lost=180=45%*400)
we also know that match cannot improve the network, so why not let they play more games instread of useless macths?

**Comment by roy7** [comment]
We always let non-failed matches creep up to 400.

**Comment by l1t1** [comment]
@roy7 but for what?

**Comment by roy7** [comment]
More accurate ELO measurements I guess?

**Comment by FFLaguna** [comment]
Are match games also part of the training pipeline?

**Comment by roy7** [comment]
No, match games aren't used for training. Only selfplay games.
