### ISSUE TITLE
Unexpected output from server

### ISSUE THREAD

**Issue by iteachcs** [gcp/leela-zero#75]
I got this error.  Is this a firewall issue on my side?  Thanks!

**Comment by gcp** [comment]
Try:

curl.exe http://zero.sjeng.org/best-network-hash

And see what output you get.

**Comment by iteachcs** [comment]
I got the follows.

fe3f6afd23aab715be6743fd42c378ddfcd9b049ebe305478c335b8a9401ac13
2

**Comment by gcp** [comment]
That is correct. No real idea what is going wrong then. Do you get the message immediately after startup?

**Comment by Joker2770** [comment]
I got the same problem,I delete the old network and it work.
I delete the file named e6779c9becc10........

**Comment by iteachcs** [comment]
Yes, I get the message immediately after startup.  Very strange problem then.

I do not have file named e6779c9becc10.

**Comment by iteachcs** [comment]
I know what the problem is.  curl is not on the path!  Anyway, Windows 10 does not have curl by default.  I downloaded the curl win64 binary from [https://curl.haxx.se/download.html](https://curl.haxx.se/download.html) using the curl Download Wizard.  curl.exe is found in the bin subdirectory of the unzipped directory.  Then you need to add curl's location to the PATH environment variable for Leela Zero to find it.  Now I am just wondering why other people did not have this issue?!

**Comment by roy7** [comment]
curl.exe is included in the leela-zero-0.4-windows.zip file

**Comment by iteachcs** [comment]
OMG.  curl is indeed in the zip file.  It turns out Leela Zero's curl.exe is in Quarantine by my over-zealous Symantec.  Anyway, hope this helps someone who has a similar issue. LOL!
