### ISSUE TITLE
a strange idea

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#750]
can we use a half game as input to selfplay.

for example.
when they played 100 moves copy to another instance, for randomize, they will  output different results.
so we can save time to finish two full game.

**Comment by gcp** [comment]
And half the game will be identical and thus useless.

**Comment by FFLaguna** [comment]
Might be a good way to pad the data for endgame scenarios.

**Comment by dtracers** [comment]
@gcp I feel that is a week argument.
Since we train on random positions you could remove the first half of the game from being used in training at all.

Also you could randomize history as long as it ended up in the same spot
