### ISSUE TITLE
Leela badly evaluate Pass and keep playing in its territory

### ISSUE THREAD

**Issue by Cabu** [gcp/leela-zero#752]
With 5773 Leela badly evaluate Pass and keep playing in its territory.
Here is the game played on KGS against a player.

(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]
RU[Japanese]SZ[19]KM[0.50]TM[1500]OT[5x30 byo-yomi]
PW[kawa]PB[goleelaz1d]WR[1d]DT[2018-01-26]PC[The KGS Go Server at http://www.gokgs.com/]C[goleelaz1d [-\]: GTP Engine for goleelaz1d (black): Leela Zero version 0.11
kawa [1d\]: h
]
;B[dd]BL[1488.827]
;W[jj]WL[1497.832]C[kawa [1d\]: hi
]
;B[dp]BL[1475.894]
;W[pp]WL[1494.588]
;B[pd]BL[1461.423]
;W[fp]WL[1488.572]
;B[dn]BL[1444.837]
;W[kp]WL[1478.549]
;B[qq]BL[1427.527]
;W[pq]WL[1475.106]
;B[qp]BL[1409.229]
;W[qn]WL[1474.266]
;B[qo]BL[1391.251]
;W[pn]WL[1465.819]
;B[po]BL[1372.522]
;W[oo]WL[1464.323]
;B[on]BL[1353.629]
;W[no]WL[1460.702]
;B[nn]BL[1334.771]
;W[nq]WL[1453.816]
;B[ql]BL[1315.25]
;W[ro]WL[1447.632]
;B[pr]BL[1295.627]
;W[or]WL[1444.494]
;B[pm]BL[1275.891]
;W[rn]WL[1436.854]
;B[mo]BL[1256.158]
;W[np]WL[1432.97]
;B[rp]BL[1236.317]
;W[rl]WL[1430.449]
;B[rk]BL[1216.187]
;W[rm]WL[1335.779]
;B[qk]BL[1204.038]
;W[qr]WL[1318.329]
;B[rr]BL[1189.822]
;W[ps]WL[1316.743]
;B[sq]BL[1173.889]
;W[so]WL[1231.085]
;B[sp]BL[1161.963]
;W[rs]WL[1229.337]
;B[sl]BL[1147.142]
;W[mn]WL[1195.679]
;B[mm]BL[1134.192]
;W[ln]WL[1189.651]
;B[lm]BL[1118.252]
;W[km]WL[1178.503]
;B[kn]BL[1101.786]
;W[lo]WL[1177.08]
;B[kl]BL[1084.429]
;W[jm]WL[1174.885]
;B[jl]BL[1066.113]
;W[il]WL[1168.792]
;B[im]BL[1046.744]
;W[jn]WL[1166.656]
;B[lk]BL[1028.08]
;W[ik]WL[1155.138]
;B[in]BL[1009.471]
;W[jo]WL[1151.097]
;B[gm]BL[990.178]
;W[fk]WL[1121.318]
;B[hp]BL[975.238]
;W[eo]WL[1111.776]
;B[do]BL[957.134]
;W[fm]WL[1103.432]
;B[fq]BL[939.002]
;W[gn]WL[1098.812]
;B[gp]BL[919.738]
;W[io]WL[1094.436]
;B[nd]BL[900.086]
;W[sr]WL[1075.599]
;B[ss]BL[882.662]
;W[om]WL[1072.677]
;B[nm]BL[863.859]
;W[sr]WL[1071.184]
;B[qd]BL[843.902]
;W[rq]WL[1068.22]
;B[lh]BL[824.023]
;W[fc]WL[1061.194]
;B[ic]BL[804.178]
;W[cf]WL[1057.278]
;B[ee]BL[784.242]
;W[cc]WL[1054.859]
;B[dc]BL[764.744]
;W[cd]WL[1052.55]
;B[he]BL[744.776]
;W[de]WL[1048.703]
;B[df]BL[724.797]
;W[ce]WL[1046.354]
;B[ed]BL[704.664]
;W[jh]WL[1020.646]
;B[kf]BL[687.988]
;W[li]WL[1018.034]
;B[mi]BL[669.642]
;W[jf]WL[990.195]
;B[je]BL[654.094]
;W[mh]WL[985.983]
;B[lg]BL[635.971]
;W[mj]WL[984.056]
;B[ni]BL[616.545]
;W[lj]WL[982.146]
;B[nj]BL[597.01]
;W[mk]WL[978.959]
;B[nk]BL[575.953]
;W[ie]WL[972.511]
;B[if]BL[555.765]
;W[jg]WL[969.866]
;B[id]BL[536.762]
;W[cl]WL[963.886]
;B[dg]BL[516.756]
;W[db]WL[960.579]
;B[eb]BL[497.51]
;W[cb]WL[957.743]
;B[fb]BL[477.876]
;W[ch]WL[952.104]
;B[dh]BL[457.589]
;W[ci]WL[948.943]
;B[cm]BL[438.366]
;W[hr]WL[946.829]
;B[gr]BL[418.198]
;W[hq]WL[942.994]
;B[gq]BL[397.338]
;W[ip]WL[937.894]
;B[bl]BL[377.181]
;W[gs]WL[922.491]
;B[fs]BL[357.793]
;W[hs]WL[920.742]
;B[iq]BL[338.074]
;W[ir]WL[916.476]
;B[jq]BL[318.225]
;W[jr]WL[915.069]
;B[kq]BL[297.883]
;W[kr]WL[913.747]
;B[lq]BL[277.018]
;W[lr]WL[910.194]
;B[lp]BL[256.312]
;W[mp]WL[887.531]
;B[fn]BL[238.966]
;W[en]WL[853.39]
;B[em]BL[224.348]
;W[fo]WL[840.649]
;B[fl]BL[207.147]
;W[el]WL[830.608]
;B[fn]BL[188.746]
;W[nl]WL[821.897]
;B[ol]BL[170.417]
;W[fm]WL[820.161]
;B[ep]BL[151.564]
;W[dm]WL[816.799]
;B[ck]BL[132.881]
;W[dk]WL[812.505]
;B[dl]BL[113.48]
;W[cq]WL[804.441]
;B[dr]BL[93.619]
;W[bo]WL[793.909]
;B[em]BL[73.992]
;W[cr]WL[781.935]
;B[ek]BL[54.952]
;W[hm]WL[743.982]
;B[fn]BL[40.941]
;W[go]WL[740.119]
;B[dq]BL[23.29]
;W[ar]WL[730.538]
;B[bs]BL[4.856]
;W[cs]WL[727.996]
;B[bp]BL[30]OB[5]
;W[cp]WL[724.542]
;B[co]BL[30]OB[5]
;W[bn]WL[721.289]
;B[ap]BL[30]OB[5]
;W[bq]WL[681.609]
;B[bm]BL[30]OB[5]
;W[fj]WL[657.852]
;B[hh]BL[30]OB[5]
;W[ml]WL[655.248]
;B[ll]BL[30]OB[5]
;W[gl]WL[652.853]
;B[fm]BL[30]OB[5]
;W[fh]WL[638.472]
;B[fg]BL[30]OB[5]
;W[gh]WL[623.54]
;B[gg]BL[30]OB[5]
;W[hi]WL[619.822]
;B[an]BL[30]OB[5]
;W[aq]WL[614.264]
;B[ih]BL[30]OB[5]
;W[ii]WL[611.075]
;B[gk]BL[30]OB[5]
;W[hl]WL[605.495]
;B[ej]BL[30]OB[5]
;W[ei]WL[599.766]
;B[di]BL[30]OB[5]
;W[cj]WL[578.191]
;B[dj]BL[30]OB[5]
;W[bj]WL[573.24]
;B[gj]BL[30]OB[5]
;W[gi]WL[564.99]
;B[fi]BL[30]OB[5]
;W[sm]WL[562.464]
;B[sk]BL[30]OB[5]
;W[fj]WL[559.443]
;B[eh]BL[30]OB[5]
;W[fi]WL[555.071]
;B[fk]BL[30]OB[5]
;W[es]WL[543.84]
;B[fr]BL[30]OB[5]
;W[ds]WL[538.507]
;B[er]BL[30]OB[5]
;W[ig]WL[524.593]
;B[hg]BL[30]OB[5]
;W[cg]WL[520.624]
;B[hj]BL[30]OB[5]
;W[ij]WL[510.673]
;B[kh]BL[30]OB[5]
;W[ji]WL[500.765]
;B[ki]BL[30]OB[5]
;W[kj]WL[494.387]
;B[kg]BL[30]OB[5]
;W[ea]WL[487.376]
;B[fa]BL[30]OB[5]
;W[da]WL[484.824]
;B[bk]BL[30]OB[5]
;W[ak]WL[481.121]
;B[al]BL[30]OB[5]
;W[aj]WL[478.862]
;B[cn]BL[30]OB[5]
;W[ao]WL[476.455]
;B[am]BL[30]OB[5]
;W[hn]WL[464.279]
;B[om]BL[30]OB[5]
;W[qm]WL[462.617]
;B[ho]BL[30]OB[5]
;W[jk]WL[457.274]
;B[hk]BL[30]OB[5]
;W[kk]WL[454.514]
;B[ok]BL[30]OB[5]
;W[]WL[454.514]
;B[im]BL[30]OB[5]
;W[in]WL[451.019]
;B[mc]BL[30]OB[5]
;W[]WL[451.019]
;B[ec]BL[30]OB[5]
;W[]WL[451.019]
;B[ef]BL[30]OB[5]
;W[]WL[451.019]
;B[ke]BL[30]OB[5]
;W[]WL[451.019]
;B[qb]BL[30]OB[5]
;W[]WL[451.019]
;B[lb]BL[30]OB[5]
;W[]WL[451.019]
;B[kc]BL[30]OB[5]
;W[]WL[451.019]
;B[nb]BL[30]OB[5]
;W[]WL[451.019]
;B[rc]BL[30]OB[5]
;W[]WL[451.019]
;B[ld]BL[30]OB[5]
;W[]WL[451.019]
;B[hb]BL[30]OB[5]
;W[]WL[451.019]
;B[jb]BL[30]OB[5]C[kawa [1d\]: ahouka
]
;W[]WL[451.019]
;B[gc]BL[30]OB[5]
;W[]WL[451.019]C[kawa [1d\]: nagaikise
]
;B[fd]BL[30]OB[5]
;W[]WL[451.019]
;B[re]BL[30]OB[5]C[kawa [1d\]: osomatu
]
;W[]WL[451.019]
;B[oc]BL[30]OB[5])

**Comment by gcp** [comment]
>RU[Japanese]

Leela plays according to Chinese rules.

**Comment by roy7** [comment]
If KGS bots can control what rulesets they accept, the bot operator needs to set Leela Zero bots to only accept Chinese rule games.
