### ISSUE TITLE
Resign incorrectly

### ISSUE THREAD

**Issue by stevevista** [gcp/leela-zero#758]
![2018-01-27 185547](https://user-images.githubusercontent.com/6763061/35471416-ac261d7e-0395-11e8-835c-3c35a50f1586.jpg)
I'm using leela-zero engine to generate games. B resign in this state. I think maybe the engine wrongly treat the white string on left as alive.

**Comment by roy7** [comment]
Remember in Tromp Taylor scoring all stones are alive. LZ only plays Tromp Taylor.

**Comment by fohristiwhirl** [comment]
It's closer than it looks but Black should still win by about 3.5 if there's a 7.5 komi.

Of course B needs to actually remove the white stones. Is this just something the neural net hasn't fully learned yet?

**Comment by billyswong** [comment]
Is it generated by autogtp or custom commands? What is the resign percentage and any sgf file?

**Comment by Dorus** [comment]
I tried the current network and it doesn't think black is losing yet. Win % is 25% for black and going up as black is allowed to remove stones, including the ones on g2.

I think the OP did not run any engine at all, just just requested the LZ board to evaluate the score. If you do that it will use Tromp Taylor scoring as @roy7 mentioned. All stones are alive and white would win after a double pass.

Luckily the engine has learned to not pass yet :)

**Comment by fohristiwhirl** [comment]
In case it matters, the SGF I gave is actually rotated 90 degrees from what LZ saw (because the screenshot is rotated).

**Comment by Dorus** [comment]
That reminds me to request the original SFG from the Op also :)


@stevevista hint: We need the SGF as well as more info on what you did to get it to resign. But most likely this is not a bug anyway.

**Comment by stevevista** [comment]
Sorry. I implemented methods like GTP "auto" commands, directly rendering to GUI, not implementing sgf saver yet.
It seems like the problems with my NN score prediction.
