### ISSUE TITLE
Snapback handling

### ISSUE THREAD

**Issue by arnaudgo** [gcp/leela-zero#760]
Hello,

In this game played on the 26th of January on OGS Leela resigned after W264.

https://online-go.com/game/11424738

W262 was not the winning move but might have lowered more winning rate.
W262 kills 3 stones, after LZ played moved 263, White captured the 4 stones in snapback then LZ resigned.
Maybe LZ could have found a better endgame move even if she was much behind even if there were no many points left... Also, I don't understand that much Chinese rules or Tromp-Taylor scoring.

I just raise it here in case it can be interesting food for thought. Otherwise, excuse me for my intervention :-)

Arnaud

**Comment by grolich** [comment]
I don't really see a problem here.
LZ was already lost before the snapback occurred (rule system doesn't matter for this distinction here), with nothing to do about it. 

It's very possible that the chance of the opponent playing the wrong move and not the snapback capture kept her chances just a bit above resignation, and she resigned afterwards.

LZ doesn't care about the winning margin at the end of the game, just winning chances, so if it thinks all roads lead to a loss, it would do things like these and weirder ones even if she knows she can be captured. AlphaGo was the same, and we are just replicating the experiment in a distributed environment.

For such a failure to be interesting, it would need to be falling into a snapback in a situation where it changes the result of the game. 
That would be interesting indeed.
