### ISSUE TITLE
why autogtp v13/0.11 download best netwrok before get job?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#770]
D:\>cd tool\leela10

D:\tool\leela10>autogtp -k sga
AutoGTP v11
Using 1 thread(s) for GPU(s).
Starting thread 1 on GPU 0
{
    "cmd": "selfplay",
    "hash": "714a9e64174a70e86c73f94940f0e9647f91f4d235d061a7099567fc0cb8741b",
    "leelaz_version": "0.10",
    "options": {
        "noise": "true",
        "playouts": "1600",
        "randomcnt": "30",
        "resignation_percent": "1"
    },
    "options_hash": "16b7b7",
    "random_seed": "6198289556216774822",
    "required_client_version": "11"
}

Got new job: selfplay
<b>download best netwrok</b>
===================
D:\tool\leela11>autogtp -k sga
AutoGTP v13
Using 1 thread(s) for GPU(s).
Starting tuning process, please wait...
<b>download best netwrok</b>

**Comment by Hersmunch** [comment]
A network is needed for the tuning process.

**Comment by l1t1** [comment]
@Hersmunch thanks
