### ISSUE TITLE
why 2 threads has samilar moves?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#772]
D:\tool\leela10>autogtp -k sga -g 2
AutoGTP v11
Using 2 thread(s) for GPU(s).
Starting thread 1 on GPU 0
{
    "cmd": "selfplay",
    "hash": "714a9e64174a70e86c73f94940f0e9647f91f4d235d061a7099567fc0cb8741b",
    "leelaz_version": "0.10",
    "options": {
        "noise": "true",
        "playouts": "1600",
        "randomcnt": "30",
        "resignation_percent": "0"
    },
    "options_hash": "cf1fad",
    "random_seed": "8179549823716733774",
    "required_client_version": "11"
}

Got new job: selfplay
net: 714a9e64174a70e86c73f94940f0e9647f91f4d235d061a7099567fc0cb8741b.
Starting thread 2 on GPU 0
{
    "cmd": "selfplay",
    "hash": "714a9e64174a70e86c73f94940f0e9647f91f4d235d061a7099567fc0cb8741b",
    "leelaz_version": "0.10",
    "options": {
        "noise": "true",
        "playouts": "1600",
        "randomcnt": "30",
        "resignation_percent": "1"
    },
    "options_hash": "16b7b7",
    "random_seed": "1524306218799140003",
    "required_client_version": "11"
}

Got new job: selfplay
net: 714a9e64174a70e86c73f94940f0e9647f91f4d235d061a7099567fc0cb8741b.
Engine has started.
Infinite thinking time set.
Engine has started.
Infinite thinking time set.
1 (B D16) 1 (B D16) 2 (W Q16) 2 (W Q4) 3 (B Q4) 3 (B D4) 4 (W C17) 4 (W Q16)

in which, move 1 are same(D16), move2 of thread0 and move3 of thread1 are same(Q4), and so on.

**Comment by Mardak** [comment]
What move would you expect from move 1 and 2? Have you looked at other games to see if your 2 games are significantly different?
