### ISSUE TITLE
Ideas to fight hdd bottleneck in training

### ISSUE THREAD

**Issue by Dorus** [gcp/leela-zero#774]
1) Shuffle games + moves on the hdd. (Like ~10k of them each time to make moving the window easy.)
2) Repack the games as 7zip.
3) Encode the the moves 4x smaller in mem (test if this is efficient on hdd too to store as binary. Might not since 7-zip stores ascii very efficient)
4) Un7-zip and decode moves back to tensorflow format on the fly.
5) Read the files on disk and pick n% random moves out of these (n% is the % of the total moves in the window you can keep in mem at once).
6a) From the n% random moves, pick random moves and pack them in tensorflow chunks. Discard these moves from mem. Repeat till mem is empty.
6b) Start over from reading from disk.
7) Read from disk and refill mem in parallel to creating chunks.
8) Spread files over multiple disks so they can be read in parallel.

Nr 3 might allow 4x larger n%. 7zip should decrease filesize by about 40%, the combination of this should make the reading from hdd about 6-7x faster.

For nr 1 and 2 all games need to be read and written again, but these two ideas can be combined anyway as they only need to be done once. If you do them in increment of 10k games, it becomes easy to just discard 10k of them once the window reaches 260k. The window would start at 250k and grow max 10k when new games arrive. Or use something like 9k games for a total of 243k+0-9k etc. Whatever feels best.

**Comment by gcp** [comment]
What makes you believe the training is HDD bottlenecked?

**Comment by jkiliani** [comment]
The bottleneck is RAM, correct?

**Comment by gcp** [comment]
RAM or CPU. You can trade them off against each other. The CPU aspect is a bit fuzzier, it's not like the machine is maximally loaded, TF just makes it easy to get bottlenecks in a single thread, it seems.

**Comment by gcp** [comment]
(I never really looked at SSD usage but I didn't notice any iowait in top on the training machine)

**Comment by Dorus** [comment]
I assumed HDD (SSD) read times where the bottleneck in "sampled uniformly at random from all positions from the most recent 500,000 games of self-play" (agz paper), or 250k games in our case.

If you use an SSD anyway, it's not required to shuffle the games as much on the disk, as an SSD can easily read from random positions anyway. All you need is store the moves in a way you can easily look up a single random move.

**Comment by gcp** [comment]
The bottleneck is that storing the data uncompressed balloons it up by a factor ~10, so we compress them, and that is more efficient when grouping multiple positions together. (In fact we group by 32 games)

**Comment by jkiliani** [comment]
How much does the compression rate suffer if you shuffle when putting the games from the database into chunks? You mentioned in https://github.com/gcp/leela-zero/pull/747 that this would entail a cost, did you try how bad the effect is?

**Comment by Dorus** [comment]
@gcp In that case, the idea to shuffle games + moves on the hdd would greatly improve the randomness in move selection right? You can then more freely pick multiple moves from the same zip file. As long as a single game is spread over multiple files at least.

**Comment by gcp** [comment]
>You mentioned in #747 that this would entail a cost, did you try how bad the effect is?

Not really, I would rather look at a solution that avoids breaking that in the first place.

**Comment by gcp** [comment]
>@gcp In that case, the idea to shuffle games + moves on the hdd would greatly improve the randomness in move selection right

This is what it already does. It makes no sense to make suggestions unless you understand what the code does and you can explain how the suggestion improves upon it.

**Comment by gcp** [comment]
I'm going to close this topic because it gives suggestions to address a nonexistent problem (HDD bottleneck) by making the actual problem (CPU/RAM bottleneck) far worse.

**Comment by gcp** [comment]
(And I know one could argue that we have a CPU/RAM problem because we chose to avoid a HDD/SDD problem. My point is that without understanding the current implementation or testing your idea the recommendations will be essentially random and useless)

**Comment by Dorus** [comment]
No problem, i ran this idea but @killerducky and we thought sharing it might be useful. Working on actual code for this would be pointless if HDD is not the bottleneck, so I'm happy i ran this by you before making any (feeble) attempt at it myself :)
