### ISSUE TITLE
See rating of Leela Zero to 15 significant figures instead of whole numbers as shown in the graph in zero.sjeng.org

### ISSUE THREAD

**Issue by syjytg** [gcp/leela-zero#775]
For those interested, https://docs.google.com/spreadsheets/d/1OocmdhCYmYetJMeWBqehSUUKyAlvKCFVqb_2txPzxp4

**Comment by Mardak** [comment]
Given the "ELO inflation" issue, significant digits past the decimal separator are probably quite inaccurate to begin with.

**Comment by gcp** [comment]
Not so much Elo inflation as simply the error margins on the measurement. (It's +-35 Elo, so showing significant digits is nonsense).
