### ISSUE TITLE
What's error is this?

### ISSUE THREAD

**Issue by dongcijie** [gcp/leela-zero#776]
2) 233 (B F12) 234 (W K2) 235 (B P6) *ERROR*: Error in GTP response.Error read 80 'Error in OpenCL calculation: expected 0.002508 got 0.002018 (error=24.252650%)'
*ERROR*: Error in GTP response. Error read 78 'Update your GPU drivers or reduce the amount of games played simultaneously.'
![error](https://user-images.githubusercontent.com/32858319/35542094-23f4e862-0599-11e8-94b1-57b871fb53e3.png)

PS: My GPU drivers is the latest.

**Comment by roy7** [comment]
A random CPU validation came up with a different result than the GPU did, suggesting the GPU had an error.

**Comment by gcp** [comment]
As the error explains: your GPU is returning incorrect results. Hardware, overclocking or driver issue.
