### ISSUE TITLE
How can this network get "pass"?

### ISSUE THREAD

**Issue by kityanhem** [gcp/leela-zero#778]
Very strange!

![strange](https://user-images.githubusercontent.com/22489225/35556858-0873a1fe-05d6-11e8-8a01-05c9c1ff843d.png)

**Comment by jkiliani** [comment]
It must both be very strong in the beginning, and it must have been really lucky. Look at the history of incoming results, you'll see that this net had 27:4 at one point...

**Comment by kityanhem** [comment]
I see. Can we make the old continue to play self-games?

**Comment by MartinDevelopment** [comment]
I don't get why we allow a network to pass before atleast 75 games. Even if it's at 80% there is still a chance it will go below 55%.

**Comment by jkiliani** [comment]
No point, besides it's only a little weaker. Since @gcp is considering testing the AlphaZero "always-promote" technique anyway, it won't do any harm to diversify self-play to a net that a bit weaker.

**Comment by Marcin1960** [comment]
Even equal networks will generate large false victories or losses. See on Google/images:

normal distribution tails heads

**Comment by gcp** [comment]
Yeah, not a big deal. It's been pointed out several times that the way the server handles promotion is sensitive to overestimating networks that win early in the game, because those results come in first.

**Comment by jkiliani** [comment]
@MartinDevelopment I think the problem is that SPRT assumes a standard distribution of game results based on a fixed prior probability. It doesn't take possible biases into account, such as some nets winning short games a lot due to better fighting abilities.

**Comment by Cabu** [comment]
It is possibly due to better fighting abilities, but also certainly about the network inability to see a lot of shicho, playing them until the end, and then abandoning once captured. I won a bunch of game against leela zero due to this :/

**Comment by gcp** [comment]
See also #764.
