### ISSUE TITLE
Different GPU and CPU usage with leelaz and autogtp?

### ISSUE THREAD

**Issue by barrtgt** [gcp/leela-zero#789]
Using leelaz.exe with:
`leelaz.exe -w weights1 -p 1600 -r 1 -m 30 -t 2 --noponder`
gives me about twice as much CPU and GPU usage as autogtp.exe with `-g 1`. Why is this the case?
I'm using the windows release 0.11.

**Comment by killerducky** [comment]
Because autogtp runs leelaz with `-t 1`.

**Comment by barrtgt** [comment]
I thought -t 2 was default now. Ok that would explain it. Thanks.
