### ISSUE TITLE
How about 64bit build?

### ISSUE THREAD

**Issue by Heiseikiseki** [gcp/leela-zero#79]
Hi, I saw the release version is x86 build.
Do you have any plan to release x64 version?
Is it slight faster?

And seems if only use CPU it just use about 10%~20%.
And if using GPU with CPU seems the the loading of my GTX1060 is below 30%.
Do you limit one game resource usage or not?
If yes can we choose mode to that it be faster?
or just execute multi autoGTP is better？

**Comment by gcp** [comment]
64-bit version is pointless.

Current version won't max out the GPU because the network is still small. You can run multiple instances.
