### ISSUE TITLE
leelaz 0.11 use more memory than 0.10

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#790]
in windows taskmgr, I saw they use 227680k vs 157280k, cpu are all 25

**Comment by CheckersGuy** [comment]
I guess memory usage highly depends on the number of playouts (more playouts = more nodes in the uct-tree). At how many playouts did you see more memory usage ?

**Comment by zediir** [comment]
Might have something to do with tree reuse

**Comment by gcp** [comment]
There's a whole bunch of changes that affect memory usage.
