### ISSUE TITLE
Should Leela be able to resign while doing kgs-genmove_cleanup moves?

### ISSUE THREAD

**Issue by Cabu** [gcp/leela-zero#795]
The kgs-genmove_cleanup, should play move to remove all dead stones. 
But in the code in GTP.cpp on line 390, you don't set UCTSearch::NORESIGN

389                game.set_to_move(who);
390                int move = search->think(who, UCTSearch::NOPASS);
391                game.play_move(move);

And on line 398 you specifically check for a resign:

396            if (cfg_allow_pondering) {
397                // now start pondering
398                if (!game.has_resigned()) {
399                    search->ponder();
400                }
401            }

**Comment by gcp** [comment]
Good question. If we're playing a human and disputing the score, then it's nice if kgs-genmove_cleanup resigns when we turn out to be wrong in the dispute.

But if you're coding a UI and want to use kgs-genmove_cleanup to determine life and death, then you don't want resignations.

**Comment by Cabu** [comment]
I think about KGS where I have seen multiple time Leela and the player unable to settle dead groups (I seen it 2 times without any seki in play).

**Comment by gcp** [comment]
I think it's ok to resign then?
