### ISSUE TITLE
Windows Task Manager doesn't show the correct GPU load for autogtp

### ISSUE THREAD

**Issue by Heiseikiseki** [gcp/leela-zero#796]
I notice that when I use autogtp -g 1 and autogtp -g 2 or 3 are all use 38% of GPU.(GTX1060) 
Is it normal for the 6 block network or because the new-version changed? In the past I can use close to 80% of the GPU resource.

**Comment by Cabu** [comment]
I did have the same problem, But re-doing a full tunning, the problem corrected itself with my GTX 960M.

**Comment by Heiseikiseki** [comment]
Just delete the leelaz_opencl_tuning file and restart the autogtp let it restart tunning but nothing changes.

**Comment by Cabu** [comment]
Don't let autogp do it (it does a quick tunning). Force it through leela with a command like 

leelaz.exe -w adf2d2f4f795dca5a37791b02023aec1ecf1a8bde8a7ad7e1a1b5206ab60fba5 --tune-only --full-tuner

**Comment by Heiseikiseki** [comment]
Thanks. I have tried it but still nothing changed. 
https://imgur.com/a/ucfgY

**Comment by marcocalignano** [comment]
Did you try `autogtp -g 6` or `autogtp -g 8`

**Comment by MaxMaki** [comment]
Firstly you'll get better information by running GPU-Z for the cards utilisation information. Check if that shows the same. Secondly, one thing i noticed for myself when running the newest version of autogtp in Windows was that the NVIDIA drivers felt the card was idle even when running 4-6 instances, and didn't use boost clocks at all. I had to change the NVIDIA drivers to always prefer maximum performance (Nvidia control panel), reboot the computer, and then i'd have boost clocks when running Leela.

**Comment by Heiseikiseki** [comment]
This is the GPU-Z screen shot. Also seems strange. The GPU load does not show proper. This is on 

`autogtp -g 1` some times 60% but some times always 0% like this. and for `autogtp -g 2
` seems the GPU load is 90% not same with Windows Task manager. 
https://imgur.com/a/cDwgM

**Comment by gcp** [comment]
In Windows, when using a NVIDIA card, you need to click on the details of the GPU graph and chance the display to "Compute_0".

**Comment by Heiseikiseki** [comment]
Thanks! it shows the correct GPU load on Windows task manger now.
