### ISSUE TITLE
Require client update

### ISSUE THREAD

**Issue by Dorus** [gcp/leela-zero#803]
I checked recent match games, and 1 in 20 (out of 20 games i checked :P) still runs Leela 0.10.1. It might be time to enforce updates, considering the new client is both stronger and faster.

**Comment by gcp** [comment]
There needs to be a new release first because 0.11 has broken timecontrols etc, and in next there's changes that make it about 200 Elo stronger.

**Comment by Dorus** [comment]
*Another 200 elo?*

Well fair enough. Now i cannot wait for the next release (that already contained a nr of exciting new things anyway.) 😄

**Comment by gcp** [comment]
FWIW I would like to see the outcome of #696 especially if a version can be found that gives good results also for very weak networks, before releasing. A while a thread like #809 is gobbledygook I *do* find it annoying that the default strategy (without setting the tuning variable) would be bad for new a from-scratch run.

**Comment by Dorus** [comment]
If the new version has good results with different networks, it's possibly that it fixed something that makes the network compensate for a MCTS problem. If so, a net that works well with one version might work bad with the other.

What i'm saying is, it would be crucial that all match games are done with the same version, is there a mechanism in place (like a new endpoint for the new version), to be able to only schedule match games on the new version?

I guess it would also be preferred to run self play games on the new version, but at least not as urgent.

**Comment by gcp** [comment]
We will enforce 0.12 probably fairly shortly after release, provided there's no issues like 0.11 had.

**Comment by gcp** [comment]
>If the new version has good results with different networks, it's possibly that it fixed something that makes the network compensate for a MCTS problem. If so, a net that works well with one version might work bad with the other.

It's not "good results with different networks". The method simply doesn't work if the policy is near-uniform. But our networks are only near-uniform in the very beginning, before they've learned anything.

**Comment by Dorus** [comment]
@gcp Can i suggest you release v0.12 asap instead of delaying it more? I know more goodness is coming in with new PRs, but there is already a lot of goodness in the current next build.

You could easily split off a release branch, possibly even one without the FPU code, and release that one tomorrow. Then once FPU and the other new code is completely ready, release it under v0.13. Adding extra releases shouldn't be very expensive.

**Comment by gcp** [comment]
@roy7 We should enforce the new versions now. I haven't seen any critical issues pop up.

**Comment by roy7** [comment]
@gcp Done!
