### ISSUE TITLE
What does V and N mean?

### ISSUE THREAD

**Issue by syjytg** [gcp/leela-zero#808]
For example Q16 -> 3541 (V: 48.72%) (N: 16.91%) PV: Q16 D16 D4 Q4 R3 R4 Q3 P3 P2 O2 O3 P4 N2 Q2 O1 R2 C17 D17

What does V and N mean?

Also does anybody know how to type commands in Sabaki, so I can type heatmap for example?

**Comment by Cabu** [comment]
Wild guess: V for victory probability after playout and N for victory probability by the network for that move.

**Comment by zediir** [comment]
Here's the part of the code that prints this https://github.com/gcp/leela-zero/blob/47ddf38327b80ec5f2303344d1d9c65e25f5a3fb/src/UCTSearch.cpp#L139

**Comment by syjytg** [comment]
I don't understand code so what does it mean?

**Comment by sethtroisi** [comment]
V is winrate estimate from playouts + neural net eval
N is neural net eval

**Comment by syjytg** [comment]
Thanks. So which one does LZ use to decide the best move? V?

**Comment by roy7** [comment]
N helps LZ know where to start searching, V guides the search, the move chosen will be the one who got the most # of playouts (playouts are weighted towards the higher V results).

In regards to Sabaki, check out https://github.com/yishn/LeelaSabaki.

**Comment by wpstmxhs** [comment]
Simply you can think V is value network evaluation and N is policy network evaluation(move possibilities).

**Comment by gcp** [comment]
V = value
N = network prior
