### ISSUE TITLE
Use different MCTS parameters for self-play and match/play

### ISSUE THREAD

**Issue by isty2e** [gcp/leela-zero#809]
While the recent strength gain due to the FPU and PUCT tuning is impressive, the impact of this on the whole procedure is unclear. FPU=parent-0.22 is stronger than FPU=parent since it effectively prunes bad moves so that the MC tree gets deeper, but even with the Dirichlet noise, its effect on exploration and thereby the training is somewhat unclear. We do have a stronger policy with the enhanced MCTS parameters, but it is also likely to explore less (especially when temperature=1), which might lead to potential overfitting problems.

Wouldn't it be safer to follow the AGZ/AZ parameters for this part, so that it becomes

- For evaluation/play, the MCTS parameters are set as-is, and
- For self-play, FPU=parent or 0.5, optionally with temperature=1 as in AZ, or gradually decreasing temperature over time?

**Comment by Eddh** [comment]
I don't know what is the current plan for doing a new run but I was thinking the safer way would be to try it before restarting. All discussion about the effect of new parameters on self-play and training is speculation until then.

**Comment by isty2e** [comment]
@Eddh That is exactly the reason why I thought using the AGZ/AZ parameters would be safer.

**Comment by Eddh** [comment]
Anyway I did some tests with parameters -m 30 -n and here are the results:
```

leelaz11 v leelaz_sqrt_totalvp (50/50 games)
board size: 19   komi: 7.5
                      wins              black         white       avg cpu
leelaz11                14 28.00%       7  28.00%     7  28.00%    603.28
leelaz_sqrt_totalvp     36 72.00%       18 72.00%     18 72.00%    603.76
                                        25 50.00%     25 50.00%

leelaz_tuned_red v leelaz_sqrt_totalvp (50/50 games)
board size: 19   komi: 7.5
                      wins              black         white       avg cpu
leelaz_tuned_red        26 52.00%       14 56.00%     12 48.00%    685.03
leelaz_sqrt_totalvp     24 48.00%       13 52.00%     11 44.00%    685.53
                                        27 54.00%     23 46.00%
```

So at least we know that in term of strength, the new parameters seem to fare the same when under the effect of randomness. I've been looking at the games and the noise seem to also do its job. Can't really say if its effect is reduced or amplified.

**Comment by jkiliani** [comment]
Is there any way to quantify how the FPU reduction affects exploration at the root node? Can the engine record what percentage of playouts end up being from root moves picked by noise, instead of the root priors? In this case, the share of "noised" playouts could be compared between different MCTS parameters...

**Comment by Eddh** [comment]
@isty2e that's why I am proposing to try the new parameters just before starting a new run. That way we don't lose too much if it ends up not working for self-play and we will have better information for the next run.

@jkiliani It would be interesting. Maybe run 2 games with same random seed, one with noise, the other without and compare ? (And then do that for a lot more couple of games I guess).

**Comment by jkiliani** [comment]
@Eddh I was more thinking along the line of comparing the share of noised priors between an engine with FPU reduction to one without. In that way, if it could be proven the FPU reduction does not significantly affect the exploration of moves generated by Dirichlet noise, it would alleviate the concerns from people who think the self-play reinforcement pipeline would by negatively affected by it.

**Comment by Eddh** [comment]
Maybe I misunderstand something but from what I understand there is no unnoised playouts. https://github.com/gcp/leela-zero/blob/master/src/UCTNode.cpp#L179
All the priors seem to have noise applied to them here. Maybe there are some who have absolutely 0 noise sometimes but it seems rare.

**Comment by jkiliani** [comment]
All playouts have the noise applied, but only for a minority of cases are the noised root moves actually applied, for the majority of playouts the root policy priors are picked. For that reason, I thought that measuring how many playouts are on root moves not represented in the policy priors might be a way to test the effectiveness of exploration at the root node. Would this work?

**Comment by Eddh** [comment]
I guess it could.

**Comment by gcp** [comment]
>All playouts have the noise applied, but only for a minority of cases are the noised root moves actually applied, for the majority of playouts the root policy priors are picked

I don't understand what you are saying. Root noise is always applied, @eddh is right here.

The idea of this whole topic that exploration being less would somehow change this effectively from the AGZ/AZ system is IMHO silly because PUCT and the FPU strategy weren't firmly defined there.
