### ISSUE TITLE
*ERROR*: The 'leelaz' process died unexpected.

### ISSUE THREAD

**Issue by killerducky** [gcp/leela-zero#815]
I've been getting this message occasionally lately, more context:
```
413 (B C7) 129 (B M4) 414 (W pass) 415 (B pass) Game has ended.
Score: B+1.5
Winner: black
*ERROR*: The 'leelaz' process died unexpected.
Stopping engine.
Uploading game: cf4c456e10134e20ac6a0cb1da3ebe4e.sgf for network 6349866983a43cbedd021ed805555077172ad4711dbd0dfafb61a9ea3c6239b7
130 (W B3) Game data 4b33ae62cdd1d87ba56dcf6b11c0bb3b372300aefbf7bbd112a7ddfba0c3d786 stored in database
186 game(s) (160 self played and 26 matches) played in 1023 minutes = 330 seconds/game, 1060 ms/move, last game took 911 seconds.
```

Running `autogtp -g 2 -k save -d save` on next commit `da2d383cdd541e4106b53ef0a2eaface8ba7a055`.

Autogtp keeps going so I don't really know how long or often this is happening, but this is the 3rd time I remember seeing it in maybe the past week.

**Comment by FFLaguna** [comment]
I just wanted to add that my crashes of "leelaz.exe" on Windows in Issue #706 were different in nature. My autogtp.exe did not try to upload the games after crashing. I do not remember if I had to CTRL+C to stop autogtp.exe, or if it exited at the same time on its own.

**Comment by killerducky** [comment]
I haven't been able to reproduce this. Closing for now.
