### ISSUE TITLE
OpenCL self-check is too strict when value is very close to zero

### ISSUE THREAD

**Issue by Ttl** [gcp/leela-zero#818]
Got this error earlier today: `Error read 119 'Error in OpenCL calculation: expected -0.000000 got 0.000001 (error=34028234663852885981170418348451692544000.000000%)`. Surely this is accurate enough?

Self-check currently gives error if the sign is different even if the absolute difference is minimal: https://github.com/gcp/leela-zero/blob/63517b19bbcba5d07ff68bb908994dfd835d229d/src/Network.cpp#L783-L785

**Comment by gcp** [comment]
The close to zero was supposed to be caught by https://github.com/gcp/leela-zero/blob/63517b19bbcba5d07ff68bb908994dfd835d229d/src/Network.cpp#L790 but the sign test is ahead of it.
