### ISSUE TITLE
Failed to upload a demo

### ISSUE THREAD

**Issue by sbbdms** [gcp/leela-zero#82]
![failed](https://user-images.githubusercontent.com/19167292/32957285-38b56c7c-cbf6-11e7-84b4-33f3668f8b57.png)
Is this caused by a network issue by accident?

**Comment by roy7** [comment]
That was me, I had to do something on the server that caused 1-2 minutes of upload downtime.

**Comment by sbbdms** [comment]
OK I see... Thanks for your answer :-)
