### ISSUE TITLE
Is random not enough in self-match?

### ISSUE THREAD

**Issue by fffasttime** [gcp/leela-zero#822]
http://zero.sjeng.org/viewmatch/d7c8c0eca8ac53f58772ecf477f89cebff5bcf557f4bb5e5cee448eb6f307b4f?viewer=wgo
http://zero.sjeng.org/viewmatch/98ccb2f9d60372c5d8eb0432f93ce1e0d7f748dc5551c33aa26b114b9bfaed6e?viewer=wgo
http://zero.sjeng.org/viewmatch/2594659b763694b501abbdffc772a03094c1af5e8c80b0a52cbfa7de379f92f5?viewer=wgo
http://zero.sjeng.org/viewmatch/52a0f22f9f76724aa3f41e8f7396e81a7ff10b840060a3bf668f5ec41016ffd5?viewer=wgo
http://zero.sjeng.org/viewmatch/180eb20c59e3c1c30e3bea753c63e012fecdeed6672dea118eae7071f29243b3?viewer=wgo
http://zero.sjeng.org/viewmatch/acbb1125fcce345dffc226a4eecc88080449a836163816db7f856a875c3fafdd?viewer=wgo

http://zero.sjeng.org/viewmatch/947d80de9d707f9a2155b8d982bf0d62eb85ad23ef2cecccedee145d060ed273?viewer=wgo
http://zero.sjeng.org/viewmatch/18db9d45fd0a58d1b34e6b637623bba7cc6f2981717ec21c44f54ab2558f376a?viewer=wgo

These are recent self-matchs. They are almost the same (only rotated or flipped). Is this a normal phenomenon?

**Comment by gcp** [comment]
These aren't self-play. They are evaluation matches.
