### ISSUE TITLE
Failure in building leela-zero on Linux Mint 18.2 

### ISSUE THREAD

**Issue by ashinpan** [gcp/leela-zero#83]
I have installed all dependencies, but my builds have been failing for around one week. Here is the build log as shown by the terminal:

------------------------------------------------

pan@pan-desktop ~/devel-leela/src $ make
make CC=gcc CXX=g++ \
	CXXFLAGS='-I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG'  \
	LDFLAGS=' -flto -g' \
	leelaz
make[1]: Entering directory '/home/pan/devel-leela/src'
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Network.o Network.cpp
In file included from OpenCL.h:27:0,
                 from Network.cpp:44:
./CL/cl2.hpp:1831:25: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
     const cl_type get() const { return object_; }
                         ^
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o FullBoard.o FullBoard.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o KoState.o KoState.cpp
KoState.cpp: In member function ‘bool KoState::superko()’:
KoState.cpp:63:41: error: ‘crbegin’ was not declared in this scope
     auto first = crbegin(ko_hash_history);
                                         ^
KoState.cpp:64:38: error: ‘crend’ was not declared in this scope
     auto last = crend(ko_hash_history);
                                      ^
KoState.cpp: In member function ‘bool KoState::superko(uint64)’:
KoState.cpp:72:41: error: ‘crbegin’ was not declared in this scope
     auto first = crbegin(ko_hash_history);
                                         ^
KoState.cpp:73:38: error: ‘crend’ was not declared in this scope
     auto last = crend(ko_hash_history);
                                      ^
KoState.cpp: In member function ‘bool KoState::superko()’:
KoState.cpp:69:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
KoState.cpp: In member function ‘bool KoState::superko(uint64)’:
KoState.cpp:78:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:52: recipe for target 'KoState.o' failed
make[1]: *** [KoState.o] Error 1
make[1]: Leaving directory '/home/pan/devel-leela/src'
Makefile:2: recipe for target 'default' failed
make: *** [default] Error 2

**Comment by gcp** [comment]
What goes "g++ -v" say?

**Comment by pholthuizen** [comment]
I have the same error when building on Debian.

**Comment by gcp** [comment]
You need a compiler with C++14 support (this is mentioned in the requirements). GCC 4.9 has only partial support for C++14.

**Comment by ashinpan** [comment]
g++ -v says:

--------------------------------

Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.9.4-2ubuntu1~16.04' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.4 (Ubuntu 4.9.4-2ubuntu1~16.04)

**Comment by pholthuizen** [comment]
is there a 64 bit compiled version somewhere available?

**Comment by sethtroisi** [comment]
It's ugly but I was able to compile by changing 
Line 2 of https://github.com/gcp/leela-zero/blob/master/src/Makefile
-	$(MAKE) CC=gcc CXX=g++ \
+	$(MAKE) CC=gcc-5 CXX=g++-6 \

**Comment by ashinpan** [comment]
I have used update-alternatives to change default gcc and g++ to gcc-7 and g++-7. Now the build is OK. I should close the issue now, I think.
