### ISSUE TITLE
why +128k networks are strong in average?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#833]
from recent matchs,
maybe you can use database sql to group by +nk to summary, such as
select avg(rate) from matchs group by substr(,,)

**Comment by l1t1** [comment]
I use the webpage data(only recent 100 records) and get following result:
``       CNT K                                              MAXR       AVGR       MINR
---------- ---------------------------------------- ---------- ---------- ----------
        14 64.0k                                         55.93      26.29       1.92
        14 48.0k                                         39.77      19.45        3.7
        15 8.00k                                         50.12      27.02       4.35
        15 16.0k                                         46.86      18.38        3.7
        14 32.0k                                         46.21       18.8          0
        14 128k                                          51.65      27.08       1.85
        14 96.0k                                         57.72      25.88       2.04

**Comment by l1t1** [comment]
may be @gcp can tell us the result of all data,
I also wonder the stats of best networks

**Comment by wpstmxhs** [comment]
Generally speaking, 128k networks are well trained enough.
128k means epoch.

But it's not always true that well-trained network is stronger than the others.
So we let them match each others to evaluate and see the result.
