### ISSUE TITLE
Assertion failed: get_visits() - 1 == parentvisits, file ..\..\src\UCTNode.cpp, line 325

### ISSUE THREAD

**Issue by sbf2000** [gcp/leela-zero#835]
update_root, 11144586 -> 4867423 nodes (43.7% reused)
Assertion failed: get_visits() - 1 == parentvisits, file ..\..\src\UCTNode.cpp, line 325

windows10

Platform version: OpenCL 2.1 AMD-APP (2527.8)
Platform profile: FULL_PROFILE
Platform name:    AMD Accelerated Parallel Processing
Platform vendor:  Advanced Micro Devices, Inc.

**Comment by ihavnoid** [comment]
Hmm what is the leelaz version?

**Comment by jun63cn** [comment]
sames here.  windows7  next b57247e

**Comment by Eddh** [comment]
Seems like it might be from this #816

**Comment by ihavnoid** [comment]
Do we have any non windows platform fails?  #816 looks like a platform independent change, so there should be somebody with the same failure on other operating systems...

**Comment by sethtroisi** [comment]
This is my change, I tested a number of games but must have missed some
edge case.

Are you running autogtp? Are you passing any interesting parameters to
Leelaz (huge number of players for example)?

**Comment by killerducky** [comment]
@sethtroisi I reproduced it, it happens when you use `-t 2` not `-t 1`.

```
gv=6 pv=4
leelaz: /home/aolsen/projects/lz-assert/leela-zero/src/UCTNode.cpp:328: UCTNode* UCTNode::uct_select_child(int): Assertion `get_visits() - 1 == parentvisits' failed.
```

**Comment by ihavnoid** [comment]
Looking at the code, I think the assertion can fail if there are two or more threads accessing the node at the same time.  If one thread acquired the lock while another thread is waiting the lock, the assertion will fail because the 'waiting' thread already incremented the 'visits' counters.

Can we rewrite that part of code to assume that the assertion may not hold true?  Or, is it just okay that we violate that assertion occasionally?

**Comment by ihavnoid** [comment]
Hmm, no wonder why I couldn't reproduce this - this should show up on a debug mode build, correct?  Is everybody else running a debug mode build?

**Comment by killerducky** [comment]
I commented out that assertion and ran again, now I get this one:
```
./leelaz -w ~/networks/latest.txt -p 10 --noponder

leelaz: /home/aolsen/projects/lz-resign2/leela-zero/src/UCTNode.cpp:343: UCTNode* UCTNode::uct_select_child(int): Assertion `value > -1000.0f' failed.
```

**Comment by ihavnoid** [comment]
@killerducky  How quickly did you get that assertion?

**Comment by killerducky** [comment]
I don't remember. I was also getting the best node assertion firing just below it. Probably none of this will happen with `-t 1`, so autogtp should be ok. I have to go to sleep and then work tomorrow, maybe @sethtroisi can look some more. For more than one thread it might be more complicated than just removing the assertions.

**Comment by ihavnoid** [comment]
Hmm I commented out the assert and it seem to be fine under debug mode.  I am running 'auto' for a dozen times using the same command line. that you put up there.  Anyway, I have to work tomorrow so I should go to sleep too. :)
