### ISSUE TITLE
/next branch show very different win rate from current

### ISSUE THREAD

**Issue by pangafu** [gcp/leela-zero#837]
I download and compiled /next branch yesterday, My environment is Ubuntu 16.04 + Nvidia 1070.
And I test 2 weight 647ec780 VS d6f3a68b, winrate like below:
2018-02-08 07:01 | 647ec780 VS d6f3a68b | 10 : 48 (17.24%) | 58 / 400 | fail

In my machine, I test PO 50, 100, 200, 1600, I found very different win rate from current, the result is:
PO 50:      647ec780 VS d6f3a68b = 23 : 17
PO 100:    647ec780 VS d6f3a68b = 24 : 16
PO 200:    647ec780 VS d6f3a68b = 20 : 20
PO 1600:  647ec780 VS d6f3a68b = 25 : 35

I know PO less than 1600 is none sense, but PO 1600 show a lot different from current, is there something wrong?

**Comment by pangafu** [comment]
I use gogui-twogtp to test, and test command is : 

/home/wukong/gogui/bin/gogui-twogtp -black "/home/wukong/leela-zero/src/leelaz -g -p 1600 --noponder -t 1 -q -d -r 1 -w /home/wukong/Hybrid_LeelaZero/best/647.txt"  -white "/home/wukong/leela-zero/src/leelaz -g -p 1600 --noponder -t 1 -q -d -r 1 -w /home/wukong/Hybrid_LeelaZero/best/d6f.txt" -games 60 -sgffile leelazero -size 19 -komi 7.5 -alternate -auto

The result of PO 1600 is below, please check:
[leelazero.zip](https://github.com/gcp/leela-zero/files/1709358/leelazero.zip)

**Comment by pangafu** [comment]
In additional, I test many PO 50 match between old weight yesterday, the data maybe useful, I post here:
PO 50:
--------------------------6B Weights--------------------------
d6f vs 54b = 18:12
54b vs 634 = 20:10
634 vs 257 = 16:14
257 vs adf = 15:15

--------------------------5B Weights--------------------------
0db vs 46f = 26:4
46f vs ffc = 19:11
ffc vs 65e = 17:13

The data show that the better weight show stronger even in very low PO.

**Comment by Eddh** [comment]
Yes the next branch will probably change the balance of strength between different networks a lot. This is because of fpu reduction in it, which has been shown to make the program stronger when using strong network. It changes the way leelaz search its move a lot and there has been a lot of discussions about it #696 . We still don't know all the side effects that it will have though.

**Comment by gcp** [comment]
See #696 etc.
