### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by szghds** [gcp/leela-zero#84]
curl.exe -F networkhash=fe3f6afd23aab715be6743fd42c378ddfcd9b049ebe305478c335b8a9401ac13 -F clientversion=2 -F sgf=@f9b1766395f74f3f88fde9130b9601f6.sgf.gz -F trainingdata=@f9b1766395f74f3f88fde9130b9601f6.txt.0.gz http://zero.sjeng.org/submit
<!DOCTYPE html>
<html>
<head>
<title>Error</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>An error occurred.</h1>
<p>Sorry, the page you are looking for is currently unavailable.<br/>
Please try again later.</p>
<p>If you are the system administrator of this resource then you should check
the <a href="http://nginx.org/r/error_log">error log</a> for details.</p>
<p><em>Faithfully yours, nginx.</em></p>
</body>
</html>

**Comment by roy7** [comment]
Sorry, that might be me restarting the server during some updating I just did. Did it clear up immediately on the next submission?

I wonder if curl has a command to auto retry or something.

**Comment by szghds** [comment]
![err](https://user-images.githubusercontent.com/26852818/32972264-61583e26-cc2c-11e7-9b88-ad94645d66b2.png)

**Comment by szghds** [comment]
Opening "http://zero-test.sjeng.org/" also appears "502 Bad Gateway""

**Comment by SebastienFaurite** [comment]
I had to restart autogtp
With this kind of error we could loose a lot of client, until they check and see that the computing is halted. There should be an auto retry.

**Comment by szghds** [comment]
Thank you

**Comment by roy7** [comment]
Zero-test is just for testing and no current autogtp should be connecting to it.

**Comment by iteachcs** [comment]
I found the statistics under http://zero.sjeng.org/
