### ISSUE TITLE
Could we have a --bench feature?

### ISSUE THREAD

**Issue by jjoshua2** [gcp/leela-zero#845]
Would be useful for integrated graphics to verify both that it is valid (especially the intel ones) and that it is faster than CPU only. Also, great to compare tunings, and graphics cards, thread count, etc. Maybe have an optional setting for roughly number of minutes that it will run so small differences can be found and variance is reduced, making the number more repeatable and averaged.

**Comment by Ttl** [comment]
There's already "netbench" command that reports how many nodes/s the program can do. It will also run the self-check with small probability and give error if the GPU result doesn't match the CPU result. Does it do what you want? If not, what exactly you want the command to benchmark?

**Comment by jjoshua2** [comment]
I tried netbench and it didn't do anything. I don't see it listed in help
either. Is it only in next. I have .11

**Comment by Ttl** [comment]
It's a GTP command. You need to start leelaz and type "netbench" to the leelaz command line.

You can change the number of evaluations by giving a number after the command. For example "netbench 10000" to do 10000 network evaluations.

**Comment by jjoshua2** [comment]
Thanks that seems like what I want. But could it just be listed in dash h?
I never saw it explained in the read me even.

**Comment by ihavnoid** [comment]
I agree that netbench is a useful way to evaluate performance, but depending on what you want to measure it isn't perfect either.  AFAIK it only runs the net evaluation part and does not run the actual search which is done on CPU, though I agree that typically the net evaluation is the performance critical piece.

**Comment by gcp** [comment]
It can't go in the -h because it's not a command line option.

**Comment by zediir** [comment]
list_commands doesn't show it.

**Comment by jjoshua2** [comment]
I was thinking of something like the stockfish bench that does an actual
search of 40 different positions and reports total time and positions per
second.

**Comment by Cabu** [comment]
Having a --bench command line lunching evaluation of some positions in a way leelaz should do it in a real game, taking into account everyting (nb threads, nb visits/playouts, even compiler optimization flags) and not just evaluating the network would be a great addition. It will let us evaluate different optimization strategies and have a benchmark to compare to.
