### ISSUE TITLE
Add option to autogtp to chose the number of cores

### ISSUE THREAD

**Issue by emdio** [gcp/leela-zero#86]
This can be useful for people who want to contribute but don't want/can't provide that much hardware.

AFAIK right now autogtp just takes all the cores it finds. I'm hardcoding this number in autogtp/GAme.cpp and recompiling it, but maybe this option could be available from the command line.

**Comment by zhu-jz** [comment]
It takes two threads though

**Comment by emdio** [comment]
"It takes two threads though"

What do you mean?

I modified this line (just added the "-t 1" part) and it for sures uses only one thread on my computer.

cmdLine.append(" -g -q -n -t 1 -d -m 30 -r 0 -w ");

**Comment by gcp** [comment]
By default it uses 2 threads because using more doesn't help in the GPU-limited case.

**Comment by Marcin1960** [comment]
In Windows Mask Manager you can set number of cores used by a process.

**Comment by gcp** [comment]
Regular Leela indeed does that, but it can run Monte Carlo simulations while the GPU is busy. Not so for Leela Zero.

**Comment by gcp** [comment]
Latest release has a -g setting that controls the number of games played at once.
