### ISSUE TITLE
[question] from stderr, meaning of "update_root, 9374671 -> 950315 nodes (10.1% reused)"

### ISSUE THREAD

**Issue by pnprog** [gcp/leela-zero#864]
Hi!

I had implemented support for Leela Zero in GRP last months and everything was ok. But yesterday, an user opened an issue because the analysis would not work with Leela Zera.

After further investigation, it appears this is due to that extra line `update_root, 9374671 -> 950315 nodes (10.1% reused)` appearing in the stderr. I don't know exactly where it is appearing (I can reproduce the bug) but it appears following a GTP **genmove** command for the second move. Could be related to this issue https://github.com/gcp/leela-zero/pull/799

Out of curiosity, I would like to know what does that mean and why I cannot reproduce it.

Thanks!

**Comment by zediir** [comment]
They must be using a debug build to get that line.

**Comment by gcp** [comment]
It means we were able to pick a node of the previous search tree as the new root node for a new search. The display is the number of nodes in the old tree, and the size of the new tree rooted in the subnode.

As said above, this output only appears in debug builds, so the user is using a debugging binary.

**Comment by pnprog** [comment]
Thanks for the quick reply!

**Comment by jun63cn** [comment]
I used a released build still get that line. why?  VS2015

**Comment by gcp** [comment]
>I used a released build

You mean you built your own release, right? It seems to project file you used doesn't correctly set NDEBUG in release mode.

**Comment by jun63cn** [comment]
Thanks for your reply, I see.
