### ISSUE TITLE
Unable to use multi GPUs

### ISSUE THREAD

**Issue by qysnn** [gcp/leela-zero#88]
It seems that autogtp will only use the first GPU available. This will be a problem if there are multiple instances of autogtp running. For example, I am testing on a 4 GTX-1080 machine with Ubuntu 16.04. When I run a single instance, the first GTX-1080 has an utilization level at approximately 30%. When I run three instances, the first GTX-1080 has an utilization level at approximately 50% and rest of the GPUs 0%.
By the way, should the autogtp be configured to use more capability of the computer? According to my test, one instance of autogtp will only use 2 threads and 15% of GPU.
![image](https://user-images.githubusercontent.com/27019112/32981678-967e9766-cc2d-11e7-8839-656375a4e8c9.png)

**Comment by killerducky** [comment]
Have you tried "--gpu arg"? See "leelaz--help". I don't have multiple GPUs so I can't test this.

**Comment by gcp** [comment]
AutoGTP has no support for this right now. There's some work underway to let it run multiple games in parallel, which could then be used for multi-GPU support.

**Comment by dwt** [comment]
I would much rather have an option to specify the GPU to use. I have a server with multiple GPUs and could run it pretty much continuously on the second GPU - but I can't use the main GPU as it is required for other machine learning tasks.

Allowing to select the GPU also could easily support scaling it on a multi GPU cluster by hand, so it would definitely help there.

**Comment by qysnn** [comment]
@dwt the `next` branch has implemented that feature. Please see #142.

**Comment by dwt** [comment]
> Am 23.11.2017 um 16:38 schrieb qysnn <notifications@github.com <mailto:notifications@github.com>>:
> 
> @dwt <https://github.com/dwt> the next branch has implemented that feature. Please see #142 <https://github.com/gcp/leela-zero/issues/142>.
> 
Cool, I’ll give it a shot.

**Comment by dwt** [comment]
Seems to work fine for me - I'll get back here if I find any problems.

**Comment by gcp** [comment]
Support for this is in release now.
