### ISSUE TITLE
[Question] proper way to set up komi with handicap game (area scoring)

### ISSUE THREAD

**Issue by pnprog** [gcp/leela-zero#880]
Hi all!

Leela Zero plays according to Chinese rule set (area scoring). So if I am not mistaken, then in case of handicap game, the number of stones should be added to the score of white.
So that White score, after removing all dead stones, will be the sum:

1. the number of empty points surrounded by white stones only
2. the number of living white stones on the board
3. the value of komi (for example 0.5)
4. the number of handicap stones (minus one stone for AGA rule set...)

For example, I remember that when playing with the Leela GUI, it reduces the black score by the number of handicap stones.

So I would like to know how Leela Zera manages that. When the **set_free_handicap** command is used to place, let's say, 9 handicap stones on the board, will Leela Zero automatically takes into consideration an extra 9 points to add to the score of white? Or should I increase the komi from 0.5 up to 9.5 to be in accordance to the rule set? (or 8.5 for AGA rule set?)

**Comment by gcp** [comment]
https://github.com/gcp/leela-zero/blob/5958e02cf539d42ee20704b664043036d5c3c18b/src/FastState.cpp#L150

Handicap compensation is accounted for automatically, separate from the komi.

**Comment by pnprog** [comment]
Thanks for your accurate answer!
