### ISSUE TITLE
New release of leela-zero.exe ?

### ISSUE THREAD

**Issue by Marcin1960** [gcp/leela-zero#881]
When it will take place?

**Comment by Tsun-hung** [comment]
I guess it will take place in 10 blocks  self-play(just kidding)

**Comment by Dorus** [comment]
Last i heard was gcp wanted to have FPU in first, but that seems to be delayed once again. I really hope we get a release soon, with or without FPU.

https://github.com/gcp/leela-zero/issues/803

**Comment by Splee99** [comment]
Why don't you just download and compile the next branch?

**Comment by Marcin1960** [comment]
I am trying.

**Comment by afalturki** [comment]
@Marcin1960 If you're using Windows 10, I made a guide for compiling and building the next branch. You can find it here:
https://www.reddit.com/r/cbaduk/comments/7wyayt/can_someone_make_a_spoonfeed_guide_for_compiling/du47v8w/

**Comment by Marcin1960** [comment]
@afalturki

Thank you. It looks promising, but I do not have enough space to install QT :(

Is it possible for you (or someone else) to compile 32 bit version of leela-zero, and make it available?

**Comment by zediir** [comment]
If you don't need to build autogtp you can build just leelaz and you won't need QT installed

**Comment by Marcin1960** [comment]
"If you don't need to build autogtp you can build just leelaz and you won't need QT installed"

I tried. Now I am unistalling Visual Studio. Unfortunately my OpenCL got messed up, I don't know why. So  it will keep me busy for a while.

Thank you Microsoft.

**Comment by MingWR** [comment]
I agree that releasing the next version soon is good idea, since it's a lot faster than the current one. If everyone can use the new version to help make self-play games, the training speed would be doubled.

**Comment by Dorus** [comment]
Doubling the search speed is a 100-200 elo increase in bots (that use time and not playout or visit limit), that alone is worth a new release even if e leave out FPU etc.

**Comment by Tsun-hung** [comment]
AFAIK, the double speed only come up at the opening of the game

**Comment by jjoshua2** [comment]
Can't we have an automated build server like abrok does for stockfish? Its not the fastest compile but it's always up to date at least. And a fair number of Windows users will use it because it's a pain to have a good build environment on Windows and official releases take too long.

**Comment by gcp** [comment]
AppVeyor should be able to make automated builds but right now it's stuck with an outdated OpenBLAS in Nuget.

I think everything is in place to make a new release.

**Comment by gcp** [comment]
Done.
