### ISSUE TITLE
What are the Max nodes in leela zero?

### ISSUE THREAD

**Issue by bjiyxo** [gcp/leela-zero#891]
I've heard #663 :

gcp commented 29 days ago
@zediir note the tree is limited to 100M nodes and one of your tests hit that limit. Might skew the result.

Are there any nodes limit now? 100M is too small for research purpose. If there is some limit there, could anyone point out the code?

**Comment by sethtroisi** [comment]
This is being worked on in https://github.com/gcp/leela-zero/pull/887

Right now the limit is ~500,000 positions evaluated with the neural net, leading to ~100,000,000 scores.
After https://github.com/gcp/leela-zero/pull/887 (or https://github.com/gcp/leela-zero/pull/574 or https://github.com/gcp/leela-zero/pull/878) is merged that limit will be increased some number.

In https://github.com/gcp/leela-zero/pull/887 I link to games with 250,000 and 500,000 playouts.

After https://github.com/gcp/leela-zero/pull/887, positions (ie what the AlphaGo Teaching Tool looks can) can be evalued with ~2M playouts on gaming machines. I'm not sure if this is directly comparable with AlphaGo's 10M playouts.
