### ISSUE TITLE
version number?

### ISSUE THREAD

**Issue by ThorAvaTahr** [gcp/leela-zero#893]
I am still getting the below text output running autogtp on the latest leelaz v0.12 and autogtp v14 version, stating this is running leelaz v0.10. Can someone confirm this is not due to some problem on my side?

_Infinite thinking time set.
{
    "cmd": "selfplay",
    "hash": "0fb68ccfbc643947bcac23c0aad4b9e43cfaa84cc01fe5da85ce06e843fabec5",
    "leelaz_version": "0.10",
    "options": {
        "noise": "true",
        "playouts": "1600",
        "randomcnt": "30",
        "resignation_percent": "1"
    },
    "options_hash": "16b7b7",
    "random_seed": "18274335488366539639",
    "required_client_version": "11"
}_

**Comment by akdtg** [comment]
This is not the state of your environment but the task from the server.
"leelaz_version" describes the minimum required version of leelaz, "required_client_version" - the minimum required version of autogtp.

**Comment by ThorAvaTahr** [comment]
Ok, understood, thanks
