### ISSUE TITLE
Post a 'new version release' announcement to let people know about it?

### ISSUE THREAD

**Issue by wctgit** [gcp/leela-zero#895]
Suggestion: Perhaps someone could put together a short blog-like article to publicly announce the new version release, and post it on a blog, or on GitHub if it allows such posts, or some other outlet which will function as an 'official announcement'? Doesn't have to be anything fancy, just a note that a) the project exists, and b) has made recent improvements in strength and performance. 

Then the rest of us can spread the link to the official announcement on various appropriate platforms. For example, I generally hang out on YouTube and a few other forums, so I might post it as a reply in a comment thread discussing Go/AI. Other folks might post it on their Facebook or Twitter timelines or whatnot.

This could potentially attract a spike in clients running AutoGTP, and perhaps more interest in fellow software development folks and/or Go enthusiasts. Word of mouth, and all that. :-)

**Comment by tterava** [comment]
There's always and update on zero.sjeng.org
Or if you want direct link to the release, you can link to the Releases section of Github.

**Comment by wctgit** [comment]
Yeah, I'm thinking more like a short blog post, something akin to a press release blurb, rather than a nondescript link to a nondescript page. It could even be done as an 'issue' post if no other method is readily available. It just has to be an 'official' announcement, something we could readily link share.

**Comment by gcp** [comment]
The github releases page already lists the highlights.

**Comment by wctgit** [comment]
Again, it's just a file listing and a list of changes, i.e. non-descript. It's not 'friendly' to non-programmers. The idea is to popularize Leela Zero outside of its current user base, to get more people running it. Sending a non-techie to the release page just leaves them wondering, "Uh, okay, what am I supposed to do here?" For the wider audience, you need some introductory sentences at least to describe what it is and why they might want to get involved. That's why a blog post would be much more appropriate as what I'm describing as an 'official announcement'. Something in vernacular English, preferably.

**Comment by FFLaguna** [comment]
I've definitely agreed this was an issue for a long time. wctgit said it best: "It's not 'friendly' to non-programmers'. Polishing this side of things will result in more people running autogtp.exe instead of closing the tab right away without downloading it at all.
