### ISSUE TITLE
Does Playout affect matching resault?

### ISSUE THREAD

**Issue by Heiseikiseki** [gcp/leela-zero#899]
Because I see other zero project started to swich to 400 or 800 playout,
so I am curious about how does playout affect the resault.
For example a network vs b network.
Use 800 playout and 1600 playout.
If a is better than b, does the resault changes on different playout?
If it does affect . How it affects.
For example for 40 400 800 1600 3200 all different or near the same?
and for self-playing is it more effective for us to switch to lower playout just as others project?

For reference : https://github.com/mokemokechicken/reversi-alpha-zero/blob/master/challenge_history.md

**Comment by gcp** [comment]
Yes. This has been discussed at length, search through the issues.

The most obvious example is that the strength of the value head does not matter with very few playouts.
