### ISSUE TITLE
Moderator decision on OGS

### ISSUE THREAD

**Issue by wctgit** [gcp/leela-zero#903]
Interesting game which was decided based on 'moderator decision' on OGS: https://online-go.com/game/11299602

I'm guessing because the time settings were so huge? @roy7, is this something that might benefit from putting 'reality checks' on RoyalZero's acceptable settings? The game was not ranked, so it makes no big difference anyway, but just thinking about usability and **ab**usability of the bot.

**Comment by FFLaguna** [comment]
That's strange. It was not ranked and had long time settings, but @roy7 has set up RoyalLeela so that it can play live games and many correspondence games simultaneously. Was this an OGS moderator error?

**Comment by roy7** [comment]
No idea, didn't know about this game and noone asked me about it.
