### ISSUE TITLE
what rate will not be failed early?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#906]
we see a lot network files failed at 50 or 100 games, is it possible they win at 400?

**Comment by ThorAvaTahr** [comment]
see for instance #676, the SPRT test is used with tuning parameters to get a 95% confidence that the network is better.

**Comment by jkiliani** [comment]
No. That's the point of the SPRT method, short for Sequential Probability Ratio Test. If there are a lot more losses than wins early on, it is statistically highly improbable that more samples would improve the result enough to win at 400. We're picking a 95% confidence threshold, so at the time a network is failed, there is already a less than 5% chance of it passing later. In this case, putting more games into testing such a network is just a waster of resources.

**Comment by Dorus** [comment]
A network that loses after 50 games must have gone like this one: 6 : 44 (12.00%)

To get 220 wins vs 180 losses it must now score 214 wins and max 136 losses, or 61%.

The odds that a network that would actually win 61% manages to go 6:44 is far less than 5%. I did some math and it wont even fit my calculator, but the odds are < 0.001%
