### ISSUE TITLE
Leela zero will kill itself while training

### ISSUE THREAD

**Issue by simonchih** [gcp/leela-zero#909]
I used Leela Watcher to see Leela zero training, but I find Leela zero sometimes will kill itself. Leela possibly put stone to the second eye and make two eyes to one eye. I wonder it is a bug? or just works as design? See sgf file below:
[sgf Link](https://onedrive.live.com/?id=E6174EBFB25B213A%21157&cid=E6174EBFB25B213A) (go into link and select "2018-02-23T09_30_27.176Z.sgf" to download)

Test Environment:
leela-zero-0.12-win64 with LeelaWatcher-1.1.0.jar
OS: Windows 10 x64
GPU: NVIDIA Geforce GTX 960M

**Comment by jkiliani** [comment]
Look at these games in edit mode, and you will notice that the player filling in their own eyes is always losing even before that. The suicide is a hail mary play that aims to extend the game when passing would lead to a loss. As far as I've seen, it happens most often in -r 0 games, where resignation is disabled.

**Comment by simonchih** [comment]
Thanks for response quickly.
