### ISSUE TITLE
SGF player name is very long

### ISSUE THREAD

**Issue by OmnipotentEntity** [gcp/leela-zero#91]
This can cause some formatting issues in certain SGF displaying programs.  This is due to the size of the network name.  What would be the best way to handle this?

I propose only displaying the first 7 letters of the network name, if it is a hash.  Is this acceptable?

**Comment by sethtroisi** [comment]
I'm all for it.

I'd suggest 8 or 16 letters which gives 32 or 64 bits of name and a longer runway (~77000 vs 5million vs 19000) till you'd expected a collusion

**Comment by gcp** [comment]
Fixed by merging #94.
