### ISSUE TITLE
Long delay after slow moves

### ISSUE THREAD

**Issue by tterava** [gcp/leela-zero#910]
If you take a long time to move against LZ with pondering enabled, it can take very long time before LZ even starts to think during its own turn. After you place a stone, it can take up to a minute before you get the normal GTP output: "Thinking at most x seconds..." and playout counts start to update.

Command line used: 
-g -r 3 -t 8 -d -m 10 -v 17000 --gpu 1 -w af9ce63c14d564dc43acc4affc3f8b86d25c29ffb1d10913f2a1ef563ed51804

This only happens if you take a long time to move and LZ has a lot of time to ponder.

**Comment by gcp** [comment]
Guessing it's related to tree reuse? Not sure why that would make the tree slower to destroy. Are we traversing more of it than we should?

**Comment by jkiliani** [comment]
Isn't there a maximum node count in the current implementation? What happens if this is reached during pondering?

**Comment by tterava** [comment]
I believe the first time it happened was with a build from next-branch about a week ago. I'll try and locate the exact build later tonight.

**Comment by tterava** [comment]
This issue first appears with commit 9a40afc.

Here's the steps I did to reproduce the error:
- Pick a normal midgame board position and launch LZ with command line from previous comment.
- After LZ has made a move, measure 2 minutes during with LZ will ponder.
- Make a move and measure the delay until "Thinking at most..." text appears in GTP console.

With commit 6b56e3f (and a few before it) it takes on my computer about 3-5 seconds until the text appears and LZ starts to calculate playouts. With commit 9a40afc it takes about 20 seconds, but in worst cases took up to 40 seconds before the text appears.

**Comment by killerducky** [comment]
I'll try to reproduce this tonight, but can you add `-l logfile.txt`, and upload the logfile here?

**Comment by tterava** [comment]
[logfile.txt](https://github.com/gcp/leela-zero/files/1752519/logfile.txt)

Here you go.

**Comment by killerducky** [comment]
The log file doesn't include output for the second genmove command. Looks like you did some setup, asked Leela for a move with `genmove b` (I assume that one worked ok), then Leela pondered. Then `play W P11`. I expect another `genmove b` and the output after that. Did it just get cut somehow?

**Comment by tterava** [comment]
[logfile.txt](https://github.com/gcp/leela-zero/files/1753042/logfile.txt)

I played a few additional moves and now it should show all the relevant parts.

In this part there's a 20 second gap between "genmove B" and "Thinking at most 49.9 seconds":
>>play W P11
= 

>>genmove B
Thinking at most 49.9 seconds...

**Comment by killerducky** [comment]
First I noticed the fast and slow case you get similar n/s throughput:
`17012 visits, 5529725 nodes, 17012 playouts, 2089 n/s`
`17015 visits, 5487354 nodes, 17015 playouts, 2085 n/s`
This leaves the update_root() call as the most likely difference.

I wasn't able to reproduce this, but I have two guesses. Problem is neither of these guesses explains why you only see the issue on the commit you identified... First it could just be a buffering issue and the text is actually displayed earlier but not flushed. @tterava are you using a GUI like Sabaki? I ran command line and didn't see any buffering issue. I think this is unlikely the real issue though.

Second it could be a memory problem. My ubuntu system has around 5GB of free RAM. When I ran the commands you did and let it ponder, I ran out of RAM sometime around 40-50M nodes, and started using swap space. I let it use about 1GB of swap space and my system was still ok, but other systems might start thrashing, or maybe you were running multiple leela/autogtp while this was going on (noticed you have 2 GPUs). @tterava can you open resource monitor, and do some experiments letting it ponder and stop it both before and after it runs out of RAM to see if that's the point causing it to slow down? I have an SSD, if you have a regular HDD maybe swapping is worse?

Right now LZ just has a hardcoded MAX_TREE_SIZE that aims to keep the tree at around 5.5GB. @gcp maybe it should also look at system RAM?

**Comment by thynson** [comment]
When I did some matches for next vs my modified version(#844), I encountered some situation randomly that leelaz think very low, below 200 playout/sec, while it should perform 3000 playout/sec.

It happens when I set playout limit greater than 9600 and after several `clear_board`(gogui-twogtp send `clear_board` command rather than terminate the client). The machine has 32GB memory.

It should related to this issue if this was a memory problem. I suspect that too many small object allocation/deallocation could cause memory be fragmented(and don't forget that each UCTNode also has a vector that store its child, so 48 byte plus up to 360*8 byte per node). 

Anyway, even if it's not a memory problem, it can be optimized better.

**Comment by tterava** [comment]
It doesn't seem to be a buffering issue, as the actual move takes considerably longer. The throughput timer seems to start when the text appears, so it doesn't count the long delay before the move. I looked at the commit that started causing this issue and I noticed it had some changes with stop_thinking(). To me it looks like LZ somehow doesn't behave nicely when it's told to stop pondering and start calculating next move. Maybe the main thread is occupied with other tasks and it simply doesn't have time to call stop_thinking() until it's finished with whatever it is doing?

I have 16 GB of ram and 2 minutes of pondering only takes 3.8 GB. At that point i had roughly 50% free, so it doesn't seem to be a memory issue. I also wasn't running multiple instances of leelaz at the time of testing.

I tried testing what happens with lower thread counts just now. Dropping down to 4 doesn't seem to make a difference, but when going all the way down to just 1 thread the delay gets a lot shorter, although it's still longer than usual (~12 seconds).

I'm running LZ with Ryzen 7 and Windows 10 if that makes any difference.

**Comment by tterava** [comment]
It seems the line which started causing the issue is 463 in UCTSearch.cpp.

I switched this line: 
} while(m_search->is_running());

back to this: 
} while(m_search->is_running() && !m_search->stop_thinking());

and the issue completely disappeared. Would be nice to know why though.

**Comment by tterava** [comment]
I'm haven't had this issue anymore in quite a while and i'm unable to reproduce it with the latest next-release. It may have been caused by using the outdated openBLAS dll from the nuget package or maybe some general driver issue with nvidia.

This issue can probably be closed as resolved.
