### ISSUE TITLE
leelaz.exe overwrites previous tuning files when different block/filter weights are loaded

### ISSUE THREAD

**Issue by FFLaguna** [gcp/leela-zero#912]
leelaz.exe currently overwrites previous tuning files if they were tuned for a different number of blocks/filters. This is semi-intended behavior, because different GPU performance gains can be made under varying block/filter counts. However, this causes several problems for people who run various block/filter sizes:

**1)** If somebody did a full tuning on 6x128, it will be overwritten and lost as soon as they run weights with a different block/filter count for the first time (for example, 10x256 weights).

**2)** In order to maintain full tunings for multiple block/filter combinations, currently users must maintain separate folders for each combination.

**3)** Even if a user does not use full tunings, each time they change weights their leelaz.exe will run quick tuning.

**4)** If someone uses leelaz.exe in a single folder and runs a GTP vs GTP game with two weights using different block/filter counts, then a minimum of one (max two) quick tunings will run from each leelaz.exe instance, overwriting the other's tuning file. Both instances are able to successfully play each other, but I don't know the exact consequences of this behavior.

**Solution:** I recommend modifying leelaz.exe to rename the tuning files to include the block and filter count in the filename, so that users only have to maintain and update a single folder regardless of block/filter changes.

**Comment by roy7** [comment]
The tuning file actually adds a new line when a new # of filters is detected. For instance, my tuning file currently has a 64 line and a 128 line. A new 20x256 network would add a new 256 line.

**Comment by FFLaguna** [comment]
Thanks, @roy7  

Let me double-check this works properly on my end before I close this issue.

**Comment by FFLaguna** [comment]
Closing this and making a new issue, as it is related but fundamentally different.

**Comment by Ttl** [comment]
There is nothing to tune for different block counts. Tuner finds optimal parameters for matrix matrix multiplication routine on GPU that is used as a part of the convolution operation. When number of channels change it changes the dimensions of the matrices being multiplied and the optimal parameters might be different. When number of blocks changes matrix multiplication is the same as before but it's just repeated different amount of times.
