### ISSUE TITLE
Is there a server failure?

### ISSUE THREAD

**Issue by qysnn** [gcp/leela-zero#92]
I just found that all 4 instances I was running quitted with the error "Unexpected output from server"
I refered to #75 and run "curl http://zero.sjeng.org/best-network-hash". Then I get
"fe3f6afd23aab715be6743fd42c378ddfcd9b049ebe305478c335b8a9401ac13
2"
I think this error is caused by a temporary submit server or connection failure. I tried to restart autogtp and it shows "autogtp v2" then hanged.

```
Score: W+55.5
Winner: white
Writing f12c16b867ce46afb0833ae5d21752cd.sgf
Dumping f12c16b867ce46afb0833ae5d21752cd.txt
Stopping engine.
curl -F networkhash=fe3f6afd23aab715be6743fd42c378ddfcd9b049ebe305478c335b8a9401ac13 -F clientversion=2 -F sgf=@f12c16b867ce46afb0833ae5d21752cd.sgf.gz -F trainingdata=@f12c16b867ce46afb0833ae5d21752cd.txt.0.gz http://zero.sjeng.org/submit
Game data a5dab027e06094c8411cc382f9fd8dacd2d040b7dc3368291f9d749b0057e79a stored in database
39 games played.
Unexpected output from server: 
<!DOCTYPE html>
<html>
<head>
<title>Error</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>An error occurred.</h1>
<p>Sorry, the page you are looking for is currently unavailable.<br/>
Please try again later.</p>
<p>If you are the system administrator of this resource then you should check
the <a href="http://nginx.org/r/error_log">error log</a> for details.</p>
<p><em>Faithfully yours, nginx.</em></p>
</body>
</html>
```

**Comment by roy7** [comment]
Yes, had unexpected server problems when testing something. Going to stop that for the night, so as soon as the server recovers it should be reliable again. Sorry. :(

**Comment by roy7** [comment]
Server seems up and running fine now. Going to stay far far away from it for rest of the night.

**Comment by sbbdms** [comment]
It seems that the server is meeting a problem again... My 3 AutoGTPs quitted successively :-(

**Comment by godmoves** [comment]
I met the same problem just now

**Comment by kityanhem** [comment]
![error](https://user-images.githubusercontent.com/22489225/32991649-e1f1a766-cd71-11e7-9641-5967a333248e.png)

**Comment by WhiteHalmos** [comment]
I'm sure it's know already but just in case, `sudo service nginx reload` is usually sufficient as opposed to needing to restart the server every time.

**Comment by roy7** [comment]
nginx is fine, the error was in the Leela Zero server software. It crashed while we were asleep. I'm unsure what caused the crash itself, but I did add some code to catch that sort of error in the future and continue normal running.

Some others have also put in pull requests for auto retry to the server plus continuing to play games offline and uploading them all in bulk when server comes back online.

**Comment by WhiteHalmos** [comment]
Thanks for getting it back up so quickly! 😊

**Comment by WhiteHalmos** [comment]
It's just me, but would you mind changing "automaticlaly" to "automatically"? 😅

**Comment by roy7** [comment]
Oops! Fixed. I edit that stuff with vim, so no spell checking. ;)

**Comment by sbbdms** [comment]
Why did the amount of total submitted games got lessened?
I noticed that the amount of total submitted games had reached 200k about two hours ago.
But now the amount was lessened:

> 2284 total clients seen. (746 in past 24 hours, 247 in past hour.)
> 188166 total submitted games. (37919 in past 24 hours, 1459 in past hour.)

**Comment by gcp** [comment]
See issue #137. It's a display issue.

**Comment by sbbdms** [comment]
That's fine :)
