### ISSUE TITLE
Only cpu version for linux?

### ISSUE THREAD

**Issue by emdio** [gcp/leela-zero#920]
So I see in the release section an only cpu version exists for windows, but I can't see a linux one.
Am I missing something?

I do know it can be worthless in order to generate training games, but it can allow more people to be able to play against leelaz, so make the project more popular.

**Comment by jkiliani** [comment]
For both Mac and Linux you have to compile yourself, whether you have a GPU or not. If you want to deactivate the GPU, you have to comment out #define USE_OPENCL in config.h before compiling leelaz.

**Comment by emdio** [comment]
"By the way, it's not worthless for training game generation"

In this case, shouldn't exist at least some info in the README file? We could be missing some potential contributors here.

**Comment by jkiliani** [comment]
Here is how my config.h looks after the modification:

```
/*
    This file is part of Leela Zero.
    Leela Zero is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    Leela Zero is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with Leela Zero.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef CONFIG_INCLUDED
#define CONFIG_INCLUDED

/*
 * We need to check for input while we are thinking.
 * That code isn't portable, so select something appropriate for the system.
 */
#ifdef _WIN32
#undef HAVE_SELECT
#define NOMINMAX
#else
#define HAVE_SELECT
#endif

/*
 * Features
 *
 * USE_BLAS: Use a basic linear algebra library.
 * We currently require this, as not all operations are performed on
 * the GPU - some operations won't get any speedup from it.
 * Also used for OpenCL self-checks.
 */
#define USE_BLAS

/*
 * We use OpenBLAS by default, except on macOS, which has a fast BLAS
 * built-in. (Accelerate)
 */
#if !defined(__APPLE__) && !defined(__MACOSX)
#define USE_OPENBLAS
#endif

/*
 * USE_MKL: Optionally allows using Intel Math Kernel library as
 * BLAS implementation. Note that MKL's license is not compatible with the GPL,
 * so do not redistribute the resulting binaries. It is fine to use it on your
 * own system.
 */
//#define USE_MKL
/*
 * USE_OPENCL: Use OpenCL acceleration for GPUs. This makes the program a lot
 * faster if you have a recent GPU. Don't use it on CPUs even if they have
 * OpenCL drivers - the BLAS version is much faster for those.
 */
#ifndef FEATURE_USE_CPU_ONLY
//#define USE_OPENCL
#endif
/*
 * USE_TUNER: Expose some extra command line parameters that allow tuning the
 * search algorithm.
 */
//#define USE_TUNER

#define PROGRAM_NAME "Leela Zero"
#define PROGRAM_VERSION "0.12"

/*
 * OpenBLAS limitation: the default configuration on some Linuxes
 * is limited to 64 cores.
 */
#if defined(USE_BLAS) && defined(USE_OPENBLAS)
#define MAX_CPUS 64
#else
#define MAX_CPUS 128
#endif

using net_t = float;

#if defined(USE_BLAS) && defined(USE_OPENCL) && !defined(USE_HALF)
// If both BLAS and OpenCL are fully usable, then check the OpenCL
// results against BLAS with some probability.
#define USE_OPENCL_SELFCHECK
#define SELFCHECK_PROBABILITY 2000
#endif

#if (_MSC_VER >= 1400) /* VC8+ Disable all deprecation warnings */
    #pragma warning(disable : 4996)
#endif /* VC8+ */

#endif
```
I never got error messages compiling this, did you change config.h in some other way?

**Comment by ihavnoid** [comment]
@pw31 - your message seems to suggest that your compiler is older than what the project assumes.  What's your gcc version?

**Comment by gcp** [comment]
The default compiler in Ubuntu 14.04 is gcc 4.8 or 4.9 or so which is way too old. You can update to 7.2.0 though through the toolchain-testing ppa.

However, you still won't be able to compile Leela Zero because the bundled boost is also much too old.

**Comment by pw31** [comment]
@gcp Thanks for your advice. As you guessed, version is gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4.
@jkiliani I copied your config.h - still same error.
This is the standard gcc compiler for Ubuntu, so very mainstream.  The project is potentially loosing a lot of contributors if you can't compile it on such systems. I might have a powerful parallel computer to use, that one has  gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18).
Is it really, really necessary to use latest compilers?
Regards, Peter

**Comment by akdtg** [comment]
The correct way to request a CPU-only build is to run cmake with FEATURE_USE_CPU_ONLY flag: 

cmake -DFEATURE_USE_CPU_ONLY=1 ..

**Comment by zediir** [comment]
If you need a newer gcc for Red Hat, look up Red Hat Developer Toolset. https://access.redhat.com/solutions/19458

**Comment by emdio** [comment]
@akdtg, shoudn't this info be in the README file?

**Comment by akdtg** [comment]
@emdio, sure, README should be updated in few areas

**Comment by gcp** [comment]
>This is the standard gcc compiler for Ubuntu, so very mainstream.

This is the standard gcc compiler on a 4 YEARS OLD Ubuntu LTS that has already been superseded by another LTS, and will be twice superseded by another.

**Comment by gcp** [comment]
>@akdtg, shoudn't this info be in the README file?

The correct information *already is* in the README.

**Comment by nhytgbvfredc** [comment]
* An OpenCL capable device, preferably a very, very fast GPU, with recent
drivers is strongly recommended (OpenCL 1.1 support is enough). Don't
forget to install the OpenCL driver if this part is packaged seperately
by the Linux distribution (e.g. nvidia-opencl-icd).
If you do not have a GPU, add the define "USE_CPU_ONLY", for example
by adding -DUSE_CPU_ONLY=1 to the cmake command line.
