### ISSUE TITLE
an idea to speed next match

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#922]
now we must began from 8k to 128k, and if new king is bron, he must wait his brother's match,
for example,
9ac646d7 is  4368+64K, after he be the king for 4 hours,  825cbda5  4368+128K is bron.
but 5ecbf715  4368+16K  was born only 30 minutes after c8b77402  4368+8K. 
if we began 4400+8K first, maybe we can get a new king shortly.

**Comment by Dorus** [comment]
Will you borrow us your crystal ball that predicts what net will pass, so we only have to test those? I'de use mine but it has never given reliable result.

**Comment by jkiliani** [comment]
Your irony is probably wasted when the post was created with Google translate. For some reason, Google translate makes posts about network promotion sound like a monarchy drama...

**Comment by CheckersGuy** [comment]
I couldnt even figure out what he was trying to say.

**Comment by l1t1** [comment]
as I predict, 4410+128k need 4 hours

Start Date | Network Hashes | Wins / Losses | Games | SPRT
-- | -- | -- | -- | --
2018-02-26 07:52 | e0bfa960 VS 92dd0397 | 21 : 35 (37.50%) | 56 / 400 |  
2018-02-26 03:38 | 92dd0397 VS 9ac646d7 | 230 : 191 (54.63%) | 421 / 400 | fail

next 8k weight will born in 1 hour

**Comment by jkiliani** [comment]
This is not about getting more weights out for testing as soon as possible. It's about testing weights that have a reasonable chance of success. Lately, we're having a lot of matches with winrates >40% which fail late, so we can't test as much as before without using too much resources on testing.

**Comment by Dorus** [comment]
So instead of generating 8k, 16k ... 128k, and then downloading all new selfplay games and start over, you suggest we generate 8k trough 64k, travel to the future to get new selfplay games, go back, generate the next 8k and then spend a few more hours on 128k.

That time travel step seems rather difficult. How does that work?

**Comment by bood** [comment]
You'll need extra resource to do this (two trains in parallel), which I don't think we have now.
