### ISSUE TITLE
curl --retry

### ISSUE THREAD

**Issue by roy7** [gcp/leela-zero#93]
Should curl --retry be used by autogtp in case server has an outage, it might try reconnecting for a while before autogtp aborts? There are various options that can be passed to curl, perhaps increase the # of tries over 5 since it'll do exponential backup by default.

And/or, should autogtp resume after a curl failure?

**Comment by gcp** [comment]
Sounds like a good idea yes.

**Comment by roy7** [comment]
Going to close this suggestion per the discussion at https://github.com/gcp/leela-zero/pull/130 and the more advanced things happening there.
