### ISSUE TITLE
Flags option proposal for leelaz.exe

### ISSUE THREAD

**Issue by Marcin1960** [gcp/leela-zero#931]
If it were up to me I would add the following option "-f flags". Easy to expand, the three specified flags are what I wish the most. And not only me!

-f  int1, int1, string1

Examples:

-f 1 = exit after one game, -f 0 = do not exit
-f 5, 3 = resign if handicap greater than 3, exit after 5 runs

Message sent for the start of the game:
-f 0, 0, "using  6x128 net, 92dd03, 64K"

-f 0,0,"", [additional options possible]

**Comment by gcp** [comment]
There is no point in asking for changes that boil down to "KGS sucks".

**Comment by killerducky** [comment]
@Marcin1960 IMO these sort of changes should go into a gtp wrapper. That would make it universal for all KGS bots.

**Comment by Marcin1960** [comment]
First flag has nothing to do with KGS. Making elaborate scripts to end playing is not very efficient.
