### ISSUE TITLE
why no.88 "best" weight is selected with a winrate of only 0.44

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#933]
did the standard of best file changed?

**Comment by Heiseikiseki** [comment]
see #78

**Comment by odeint** [comment]
Guys, this is worse than the reddit tbh, where is your attention span? Duplicate (#932) and everyone should already know why this happens from time to time (Hint: SPRT, #543 , #545 , etc).

**Comment by l1t1** [comment]
https://tieba.baidu.com/mo/q---201F473D94EAB63FDB35A35D15FF7BAB%3AFG%3D1-sz%40320_240%2C-1-3-0--2--wapp_1510352420785_338/flr?pid=118347711649&kz=5567255150&pn=0&pinf=1_2_20

**Comment by l1t1** [comment]
i saw some discuss in above post, so i guess sth changed
