### ISSUE TITLE
Benchmark command's quiet mode

### ISSUE THREAD

**Issue by akdtg** [gcp/leela-zero#935]
#857 sets the quiet mode:
```
+    if (vm.count("benchmark")) {
+        cfg_quiet = true;  // Set this early to avoid unnecessary output.
+    }
```
This way any error output will be omitted.
For example, if you missed the weight file option, leelaz will stop without any visible clue:

```
~/studio/leela-zero/build$ ./leelaz --benchmark

~/studio/leela-zero/build$ 
```

**Comment by gcp** [comment]
I guess a critical error like the weights file missing should never be silenced, perhaps?

**Comment by gcp** [comment]
Fixed by https://github.com/gcp/leela-zero/commit/92553d9b2481b216a337e5bd71b33de5dcc7ac46.
