### ISSUE TITLE
a91721af promoted with a winrate of 44.72% ?

### ISSUE THREAD

**Issue by Cabu** [gcp/leela-zero#937]
88 | 2018-02-26 09:52 | a91721af | 14620 | 4438683

2018-02-26 09:52 | a91721af VS 92dd0397 | 89 : 110 (44.72%) | 199 / 400 | fail

**Comment by jkiliani** [comment]
Please look at #932, #933 and #78 and then close this issue.

**Comment by marcocalignano** [comment]
@gcp maybe you set it to always promote the last network just to avoid have these issues come up every few days :laughing:

**Comment by billyswong** [comment]
Or someone write an update for FAQ / Readme
