### ISSUE TITLE
Leela Zero resigned while it's winning.

### ISSUE THREAD

**Issue by bjiyxo** [gcp/leela-zero#939]
I'm testing if Leela Zero's pondering is broken or not. However, I found a game that Leela Zero won but resigned with no reason. I'm testing on 92dd0397 on 1080Ti and ubuntu 17.10, and every move is in 20s(time_settings 0 20 1).

https://i.imgur.com/YwPtL76.png

[1GnpB1GW3.txt](https://github.com/gcp/leela-zero/files/1761037/1GnpB1GW3.txt)

You can check the file above and white definitely wins because black lower right is dead. However, white resigned. And if you watch the whole game with lz, you will find somehow white think it might lose from about 200 moves. But in fact, white wins a lot and played really wierd!
The following is the message that leela zero gave at the last position.

genmove w
Thinking at most 50.0 seconds...
NN eval=0.568538
Playouts: 13721, Win: 10.95%, PV: L19 H18 B13 M17 P19 N19 P10 T13 T16 T15 T11 T3
Playouts: 31176, Win:  9.45%, PV: L19 H18 P19 O10 P10 T13 T11 T16 T17 T15 N19 T3 O11 M17
Playouts: 48968, Win:  8.59%, PV: L19 H18 P19 O10 P10 T13 T11 T16 T17 T15 N19 T3 O11 M17
Playouts: 67555, Win:  8.05%, PV: L19 H18 P19 O10 P10 T13 T11 T16 T17 T15 N19 T3 O11 M17
Playouts: 84673, Win:  7.68%, PV: L19 H18 P19 O10 P10 T13 T11 T16 T17 T15 N19 T3 O11 M17
Playouts: 100553, Win:  7.37%, PV: L19 H18 P19 O10 P10 T13 T11 T16 T17 T15 N19 T3 O11 M17
Playouts: 115873, Win:  7.10%, PV: P10 O10 O11 H12 L19 H18 P19 T13 T16 T15 T11 M17 N19
Playouts: 129934, Win:  6.96%, PV: P10 O10 O11 H12 L19 H18 P19 T13 T16 T15 T11 M17 N19
Playouts: 144238, Win:  6.83%, PV: P10 O10 O11 H12 L19 H18 P19 T13 T16 T15 T11 M17 N19
Playouts: 161375, Win:  6.65%, PV: P10 O10 O11 H12 L19 H18 P19 T13 T16 T15 T11 M17 N19
Playouts: 178067, Win:  6.56%, PV: P10 O10 O11 L14 T16 T13 T15 T11 P19 M17 N19 H1 J2 J1
Playouts: 196070, Win:  6.45%, PV: P10 O10 O11 L14 L19 F19 P19 T13 T16 T15 N19 M17 T11 H1 J2 J1
Playouts: 214492, Win:  6.41%, PV: P10 O10 O11 T16 T17 T13 T15 T11 T16 M17 P19 T3 N19 H1 J2 J1 K1
Playouts: 229365, Win:  6.27%, PV: P10 O10 O11 T16 T17 T13 T15 T11 T16 M17 P19 T3 N19 H1 J2 J1 K1 H2
Playouts: 245632, Win:  6.17%, PV: P10 O10 O11 T16 T17 T13 T15 T11 T16 M17 P19 T3 N19 H1 J2 J1 K1 H2
Playouts: 260413, Win:  6.07%, PV: P10 O10 O11 T16 T17 T13 T15 T11 T16 M17 P19 T3 N19 H1 J2 J1 K1 H2
9.2s left
Stopping early.

 P10 ->   91720 (V:  6.18%) (N:  8.68%) PV: P10 O10 O11 T16 T17 T13 T15 T11 T16 M17 P19 T3 N19 H1 J2 J1 K1 H2
 L19 ->   32505 (V:  6.15%) (N:  5.18%) PV: L19 H18 P19 P10 Q10 O10 O11 T13 T16 T11 T15 R11 H1 M17 N19 O16 Q18 N15 J2 A6
  A1 ->    7239 (V:  6.19%) (N:  0.40%) PV: A1 O10 P10 T13 T16 T11 N19 H1 J2 J1 K1 T15 H2 M17
 M17 ->    6811 (V:  6.16%) (N:  0.91%) PV: M17 O10 P10 T13 P19 T11 O11 S2 T16 T15 N19 H1 J2 J1 K1 H2
 O10 ->    6745 (V:  4.24%) (N: 32.49%) PV: O10 T13 T11 T16 T17 T15 N19 H1 J2 J1 K1 H2 P19 M17 L19
 B13 ->    6182 (V:  6.19%) (N:  0.33%) PV: B13 O10 P10 T13 T16 T11 T15 H1 O11 J2 K2 K1 L1
 D14 ->    5577 (V:  6.20%) (N:  0.22%) PV: D14 O10 P10 O11 T16 T15 T11 T13 L3 M17 P19 T3 N19 H1
 G14 ->    3972 (V:  6.19%) (N:  0.21%) PV: G14 P10 Q10 O10 O11 T13 T16 T11 T15 R11 H1 M17 P19 L19 N19 H18
 C19 ->    3721 (V:  6.20%) (N:  0.13%) PV: C19 O10 P10 T13 T16 T11 T15 M17 P19 T3 N19 H1
  J2 ->    3594 (V:  6.09%) (N:  1.10%) PV: J2 O10 P10 T13 T16 T11 H1 T15 O11 T3 P19 M17 N19
 T17 ->    3562 (V:  6.20%) (N:  0.10%) PV: T17 O10 P10 T13 T11 M17 P19 O11 N19 T15 T16 H1 J2 J1 K1
 C13 ->    3448 (V:  6.19%) (N:  0.21%) PV: C13 O10 P10 H12 L19 H18 P19 M17 N19 T13 T16 T15 T11 H1 J2 J1
 T16 ->    3412 (V:  5.22%) (N:  8.27%) PV: T16 O10 P10 T13 T11 O11 T15 H1 P19 M17 N19 T3 L19 H18
  H2 ->    3203 (V:  6.12%) (N:  0.71%) PV: H2 O10 P10 T13 T11 O11 T16 H1 T15 J2 K2 J1 K1 M17 P19 T3
 A16 ->    2985 (V:  6.19%) (N:  0.17%) PV: A16 P10 Q10 O10 O11 T13 T11 R11 H1 T16 T17 T15 Q18 M17 P19 L19
 P19 ->    2977 (V:  5.75%) (N:  3.36%) PV: P19 P10 Q10 O10 O11 T13 T16 T11 T15 R11 H1 M17 N19 O16 L19 H18 Q18
 H15 ->    2812 (V:  6.18%) (N:  0.22%) PV: H15 O10 P10 T13 T16 T11 O11 T15 P19 M17 N19 H1
 G15 ->    2782 (V:  6.18%) (N:  0.21%) PV: G15 P10 Q10 O10 O11 T13 T11 R11 H1 T16 T17 T15 P19 M17 N19 L19 H18
 T19 ->    2768 (V:  6.20%) (N:  0.11%) PV: T19 O10 P10 T13 T11 T16 T17 T15 O11 H1 J2 J1 K1 H2
  E1 ->    2520 (V:  6.20%) (N:  0.12%) PV: E1 O10 P10 T13 L19 H18 P19 T11 T16 T15 N19 M17
 E16 ->    2512 (V:  6.17%) (N:  0.24%) PV: E16 O10 P10 T13 H1 T16 T17 T15 O11 T11 N19 M17 P19
 Q19 ->    2417 (V:  6.17%) (N:  0.25%) PV: Q19 O10 P10 T13 T16 O11 T11 T15 H1 M17 P19 L19 N19 H18 Q18
  H4 ->    2391 (V:  6.02%) (N:  1.13%) PV: H4 O10 P10 T13 T16 T15 T11 T3 P19 M17 N19 S2
 Q18 ->    2204 (V:  5.95%) (N:  1.41%) PV: Q18 O10 P10 O11 N19 T16 T17 T15 T11 T13 L19 H18 P19
 J15 ->    2123 (V:  6.17%) (N:  0.24%) PV: J15 P10 Q10 O10 T16 T13 O11 T11 T15 R11 H1 M17 P19 L19 N19 H18 Q18 O16 J2
 O16 ->    2070 (V:  6.18%) (N:  0.18%) PV: O16 O10 P10 T13 O11 T11 T16 T15 P19 H1 J2 J1
 A15 ->    2021 (V:  6.17%) (N:  0.20%) PV: A15 O10 P10 T13 T16 M17 P19 T11 T15 O11 N19 T3
  D1 ->    1970 (V:  6.17%) (N:  0.21%) PV: D1 P10 Q10 O10 O11 T13 T11 R11 H1 T16 T17 T15 Q18 M17 P19
 F14 ->    1931 (V:  6.17%) (N:  0.21%) PV: F14 P10 Q10 O10 O11 H12 T16 T13 T11 R11 H1 M17 P19
  B6 ->    1784 (V:  6.13%) (N:  0.39%) PV: B6 O10 P10 T13 L19 H18 Q18 T11 P19 T16 T17 T15 N19
 T18 ->    1765 (V:  6.19%) (N:  0.09%) PV: T18 O10 P10 T13 T16 T11 T15 O11 P19 M17 N19 T3
  O1 ->    1713 (V:  6.10%) (N:  0.48%) PV: O1 O10 P10 T13 T11 O11 T16 T15 P19 M17 N19 H1 J2
 F19 ->    1672 (V:  6.15%) (N:  0.28%) PV: F19 O10 P10 T13 T16 T11 T15 M17 P19 H1 J2 J1 K1
 L14 ->    1654 (V:  6.09%) (N:  0.50%) PV: L14 P10 Q10 O10 O11 T13 T16 T11 T15 R11 H1 M17 P19 L19 N19 H18 Q18
  L3 ->    1637 (V:  5.53%) (N:  2.73%) PV: L3 O10 P10 T13 O11 T11 T16 T15 P19 M17 N19 T3 L19
 E12 ->    1600 (V:  6.14%) (N:  0.29%) PV: E12 O10 P10 T13 T16 T11 O11 T15 P19 H1 J2 J1
  A6 ->    1545 (V:  6.02%) (N:  0.72%) PV: A6 O10 P10 O11 P19 T13 T11 T16 T17 T15 L19 H18 N19 M17
  O2 ->    1517 (V:  6.02%) (N:  0.71%) PV: O2 O10 P10 O11 N19 T13 T16 T11 T15 M17 P19 T3 L19 H18
  N2 ->    1488 (V:  5.99%) (N:  0.81%) PV: N2 P10 Q10 O10 O11 T13 T11 R11 H1 T16 T17 T15 Q18 M17 P19 H18
  H1 ->    1451 (V:  5.06%) (N:  4.08%) PV: H1 O10 P10 T13 T16 T11 O11 T15 P19 M17 N19 T3 L19 H18 Q18
 T11 ->    1410 (V:  5.41%) (N:  2.77%) PV: T11 P10 Q10 O10 O11 R11 H1 M17 P19 T16 T17 T15 N19 H18 L19 A15 Q18
 C14 ->    1382 (V:  6.14%) (N:  0.27%) PV: C14 P10 Q10 O10 O11 T13 T16 T11 T15 R11 H1 M17 P19 L19 N19 H18 Q18 O16 J2
 A17 ->    1316 (V:  6.18%) (N:  0.10%) PV: A17 O10 P10 T13 T16 T15 T11 O11 P19 M17 N19 T3 L19
  J1 ->    1297 (V:  6.01%) (N:  0.64%) PV: J1 O10 P10 O11 P19 T13 T16 T11 T15 H1 J2 H2
 E17 ->    1271 (V:  6.15%) (N:  0.20%) PV: E17 O10 P10 T13 T11 M17 P19 T16 T17 T15 N19 H1 J2 J1 K1 H2
  K2 ->    1258 (V:  5.98%) (N:  0.72%) PV: K2 O10 P10 T13 T16 T15 O11 T11 P19 M17 N19 H1
 G12 ->    1136 (V:  6.10%) (N:  0.30%) PV: G12 O10 P10 H12 T16 O11 P19 T13 T11
 K14 ->    1084 (V:  6.08%) (N:  0.35%) PV: K14 O10 P10 T13 T11 O11 T16 T15 P19 M17 N19 H1 J2
pass ->    1080 (V:  6.10%) (N:  0.30%) PV: pass O10 P10 T13 T11 T16 T17 T15 P19 M17 N19 H1
 E13 ->    1021 (V:  6.13%) (N:  0.21%) PV: E13 P10 Q10 O10 O11 T13 T11 R11 H1 T16 T17 T15 Q18 M17 P19 L19
 A18 ->    1013 (V:  6.16%) (N:  0.13%) PV: A18 P10 Q10 O10 O11 T13 T11 T16 T17 T15 Q18 P19 Q19 T3
  N1 ->     960 (V:  6.07%) (N:  0.35%) PV: N1 P10 Q10 O10 O11 T13 T16 T11 T15 R11 H1 M17 P19 H18 N19
 S19 ->     942 (V:  6.17%) (N:  0.10%) PV: S19 P10 Q10 O10 O11 T13 T16 T11 T15 R11 H1 M17 P19 H18 N19 L19 Q18 O16
 D19 ->     900 (V:  6.14%) (N:  0.16%) PV: D19 O10 P10 T13 L19 H18 P19 T11 T16 T15 N19
  K1 ->     892 (V:  6.04%) (N:  0.37%) PV: K1 P10 Q10 O10 O11 T13 T16 T11 T15 R11 H1 M17 P19 H18 N19
  A2 ->     876 (V:  5.94%) (N:  0.59%) PV: A2 P10 Q10 O10 O11 T13 T16 T11 T15 R11 H1 M17 P19 L19
 N15 ->     837 (V:  6.09%) (N:  0.26%) PV: N15 O10 P10 O11 L14 O16 N15 K14 T16 T13 T11
  D3 ->     777 (V:  6.15%) (N:  0.12%) PV: D3 O10 P10 T13 T16 T11 T15 O11 P19 M17 N19 H1
 Q10 ->     753 (V:  3.70%) (N:  4.61%) PV: Q10 O10 P10 T13 O11 T11 T16 R11 H1 M17 P19 T15 N19 H18
 J13 ->     748 (V:  6.06%) (N:  0.27%) PV: J13 P10 Q10 O10 O11 T13 T16 T11 T15 R11 H1 M17 P19 L19 N19 H18 J2
  L1 ->     694 (V:  6.08%) (N:  0.22%) PV: L1 O10 P10 T13 T16 T11 T15 O11 P19 M17
 T15 ->     661 (V:  6.12%) (N:  0.16%) PV: T15 P10 Q10 O10 T16 T13 O11 T11 P19 R11 H1 M17 N19 O16 L19
  L2 ->     614 (V:  5.60%) (N:  0.90%) PV: L2 O10 P10 O11 T16 T13 T11 T15 P19 M17 N19 T3
  M1 ->     576 (V:  5.98%) (N:  0.32%) PV: M1 O10 P10 T13 T16 T11 T15 O11 P19 M17
 N19 ->     568 (V:  4.33%) (N:  2.60%) PV: N19 P10 Q10 O10 O11 T13 T16 T11 T15 R11 H1 M17 P19 O16 L19
 O11 ->     562 (V:  5.40%) (N:  1.11%) PV: O11 P10 Q10 O10 T16 T13 T11 T15 P19 R11 H1 M17
  C1 ->     546 (V:  5.77%) (N:  0.58%) PV: C1 P10 Q10 O10 O11 T13 T16 T11 T15 R11 H1 M17 P19 L19 N19 H18 Q18
 G16 ->     526 (V:  6.04%) (N:  0.22%) PV: G16 O10 P10 T13 T16 T11 T15 O11 P19 M17 N19
 E14 ->     498 (V:  5.99%) (N:  0.26%) PV: E14 O10 P10 T13 O11 T11 T16 T15 P19 M17 N19 H1
  D2 ->     476 (V:  6.08%) (N:  0.16%) PV: D2 O10 P10 T13 T16 T11 O11 T15 P19 M17 N19
 K12 ->     439 (V:  5.80%) (N:  0.43%) PV: K12 O10 P10 O11 T16 T13 T11 T15 P19 M17
  M2 ->     395 (V:  5.42%) (N:  0.76%) PV: M2 O10 P10 T13 T16 T11 T15 O11 P19 M17
 H12 ->     203 (V:  5.23%) (N:  0.48%) PV: H12 O10 P10 O11 T16 T13 T11 T15 P19 M17 N19
 B19 ->      59 (V:  5.49%) (N:  0.11%) PV: B19 O10 P10 T13 T16 T11 O11 T15 P19 M17
 A19 ->      50 (V:  4.90%) (N:  0.15%) PV: A19 O10 P10 O11 T16 T13 T15 T11 P19
  A4 ->      33 (V:  4.60%) (N:  0.13%) PV: A4 O10 P10 T13 T16 T11 O11 T15
 R11 ->      26 (V:  1.03%) (N:  0.33%) PV: R11 O10 P10 O11 T16 T13 T15 T11 P19 Q10
263880 visits, 19344166 nodes, 263879 playouts, 6461 n/s

Eval (6.18%) looks bad. Resigning.
= resign

PS:By comparison,  zen7 says white is 99.7% win rate at the last move.

**Comment by akdtg** [comment]
The problem is that you judge the process from your human point of view. That is why you use incorrect conclusions like "Leela Zero won but resigned with no reason" and "black lower right is dead".

All is simple as:
1. The program uses Tromp-Taylor rules, so there are no dead stones on the board.
2. The current net do not see the way to get an advantage, so that is the reason to resign.

The NN is just a machine with the bunch of internal switches to produce the output from the input data, https://en.wikipedia.org/wiki/Chinese_room is the best analogy.

**Comment by billyswong** [comment]
The lower-right corner black group spans 13 lines. Very likely too big for LZ-6-blocks to read its life/dead status, thus assuming it's alive and judge accordingly.

**Comment by bjiyxo** [comment]
@wctgit The sgf file is 1GnpB1GW3.txt, which is in the content.

**Comment by Dorus** [comment]
This group is so big even the next 10 block network wont have it easy to identify as dead. The 6 block one wont be able for sure. The only way to correctly play out a game like this is to use -r 0 and actually let it play it out.

**Comment by bjiyxo** [comment]
@gcp I can't quite get it when #936 & #946 is similar to my issue and meanwhile my issue is invalid. Can you give a reason?

**Comment by gcp** [comment]
>Leela Zero resigned while it's winning.

>I found a game that Leela Zero won but resigned with no reason.

As you were already explained, this is wrong and the program is working correctly. Hence, closed invalid.
