### ISSUE TITLE
How about changing Network & OpenCL class to support multiple networks?

### ISSUE THREAD

**Issue by wpstmxhs** [gcp/leela-zero#945]
For general purpose, it seems good if `Network`, `OpenCL` class supports multiple networks at once.
Currently it does not support multiple networks. it only uses single network at once.

Maybe this is not important on the goal of Leela Zero project,
but for someone who wants to improve this project on his/her way, 
I suppose this change point.

**Comment by wpstmxhs** [comment]
I did it my way and made a bot which uses two different networks at once.
(i.e., zediir's 20 block network & current Leela Zero best 6 block network.)
But my patch is unofficial patch so I suppose contributors to make this change.

**Comment by Eddh** [comment]
Hmm that could be interesting. You could potentially use 20 block net at root to get better policies, 6 or 5 block net elsewhere. Is this what you are doing ?

**Comment by wpstmxhs** [comment]
No. I just mix two policy heads by averaging in weighted manner.
Because policy head is probability distribution of likely moves which sum is 1, 
I can mix two policy heads by averaging.

I did it like below:
`New Policy = ( 20 Block Policy * 2 + 6 Block Policy ) / 3`

**Comment by wpstmxhs** [comment]
Now It plays early 3-3 point like other Zero style bots, and It reads more accurate than original Leela Zero 6 block networks.

**Comment by wpstmxhs** [comment]
> Anyway, you could do a pull request for this.

I also want this. but this feature changes project a lot. many codes need to be changed for this. that's why I discuss.

**Comment by hydrogenpi** [comment]
can you attached a copy of your mixed network?

**Comment by jjoshua2** [comment]
I want to test using a different nets for opening and/or endgame. If there are any issues with networks not being big enough it would give 2x or 3x the number of weights to learn, without any slowdown. It may get 80% of the gain of doubling the blocks for little work.

**Comment by wctgit** [comment]
Interesting idea, @jjoshua2.

**Comment by jjoshua2** [comment]
@wctgit Not all of us are googlaires and can just throw double the money and gpu/tpus at the problem...

**Comment by gcp** [comment]
I wouldn't even merge this unless there's convincing data this is beneficial or more optimal than a single network.
