### ISSUE TITLE
Refocus 'excess visits/playouts' to top move instead of 'stop_thinking'

### ISSUE THREAD

**Issue by wctgit** [gcp/leela-zero#951]
[I have not looked at the code, so apologies if I'm misunderstanding how it really works.]

According to @OmnipotentEntity in https://github.com/gcp/leela-zero/issues/946#issuecomment-369078257:
> I've noticed something recently where evaluation will stop early. What's going on is in UTCSearch.cpp there's a function called `stop_thinking` and one of the things it does is estimate the number of playouts it has left to think. If the best move has so many playouts that, if another move gets 100% of the playouts from this point forward, it will still have the most, then the evaluation aborts early.
>
> It's designed to speed up moving when there is very little chance of the selected move changing.

My reply (the thread is closed, so I opened this new issue since it's separate from that thread):
> Hmm, while it seems like a good idea on the surface, I think it may backfire a bit because spending more time even on the **best** move will still sometimes find out better responses to the opponent's responses, hence different PVs, for example.
>
> Instead of stopping thinking altogether, it would be better just to devote all the remaining visits/playouts to the top move (since no other move will be able to displace it). **Those** playouts would not be wasted.

In summary, if a LZ is told to play 80,000 visits per move, then currently it will not use all those visits, if the top move already has more visits than any other move could accumulate. Instead, since the move choice cannot be displaced, `stop_thinking` is called, sacrificing those 'extra visits' for the sake of taking less time to play its move. 

_However,_ suppose 30,000 visits were deemed 'in excess'. If those 30,000 moves were devoted solely to the top move, that's 30,000 extra visits to more-fully explore the best PV within the top move branch. That might help LZ discover a strong counter-move by the opponent, and give it some time to pre-plan a response to that counter-move. It could easily result in a different PV being discovered, which might at least minimize the damage from a strong opponent's play. Or, perhaps it could find an even better second move it could play, after the opponent's most likely response, which could either help it regain some ground, or increase its advantage.

Therefore, I suggest making an option to devote those extra visits/playouts to the top move, rather than just conceding them to the opponent. There may be benefits to super-fast play, such as in games with short time controls, so perhaps the current behaviour still has a place, but I think the default behaviour if you specify V visits, or P playouts, should be to use all of them (or as many as possible, within time constraints).

**Comment by Cabu** [comment]
I think it will not work. For whatever reason right now, leela could read a shisho to the end and see that it will lose it but still play it to the end :( Thus even if these extra move will find a great counter-move, I fear that leela will stil play that move in the end :(

**Comment by gcp** [comment]
>If those 30,000 moves were devoted solely to the top move

Which would be an enormous waste of search effort. Best strenght is reached when they are distributed according to UCT.

> rather than just conceding them to the opponent. 

If the behavior bothers you it can be disabled. In real games (where Leela is not **handicapped** by limiting the playouts), using time wisely results in a stronger program.

**Comment by alreadydone** [comment]
@gcp When you already decided what move to play but you have time left for this turn, you stop considering other options for this turn, but instead consider possible responses from your opponent to your decided move. It's like pondering during your own time. I think this is what wctgit meant.
Although your opponent is also pondering during your time, you have the advantage that you know what you'll play but your opponent doesn't, so the suggested improvement should give you a slight advantage theoretically. How much is questionable though; people in [another thread](#918) is arguing about whether pondering yields an observable advantage.

**Comment by TFiFiE** [comment]
It seems to me that this issue is completely addressed by capping the number of visits rather than playouts. Any search opportunity lost as a result of the best move becoming out of reach and the opponent playing the expected response will always be compensated by not having the (now unplayed) visits count towards the limit on the next move.
