### ISSUE TITLE
Test "hybrid" 6B weights on CGOS

### ISSUE THREAD

**Issue by pangafu** [gcp/leela-zero#954]
To see the true power of the hybrid, I hybrid 2 weights and run it on cgos.
1. I make out 2 hybrid weight below:
[6w24_081&aed&a91&92d&9ac&8ee&f66&4d5&5e4.zip](https://github.com/gcp/leela-zero/files/1769458/6w24_081.aed.a91.92d.9ac.8ee.f66.4d5.5e4.zip)
[6w23_f66&081&9ac&8ee&4d5&5e4_1&0.5&0.5&0.5&0.5&0.5.zip](https://github.com/gcp/leela-zero/files/1769459/6w23_f66.081.9ac.8ee.4d5.5e4_1.0.5.0.5.0.5.0.5.0.5.2.zip)

W23 is inherited from No.86 weight (9ac646d7) and other 5 weight after it ,  W24 is inherited from No.86(9ac646d7) and No.87(92dd0397) and other 7 weights between them.
And you can see the PO 200 match log in the zip file. 

2. Then I put them run on CGOS, the parameter is : 
LZ-HY-W23-PO1600:  -g -p 1600 --noponder -t 1 -q -d -r 1 -w 
LZ-HY-W24-PO1600:  -g -p 1600 --noponder -t 1 -q -d -r 1 -w
LZ-HY-W24-NOLIMIT:  -g --noponder -t 4 -q -d -r 1 -w

My test machine is 1070 + ubuntu, there is many other leela zero weights run on cgos, such as LZ-0xx-p1600-t1-r1, StellarLZ-p6400, LeelaZero-test... I think LZ-HY-W23-PO1600 's parameter is same as LZ-0xx-p1600-t1-r1, so the result of them can compare.

3. After 3 day's match, after 100 games, the elo of hybrid weights on cgos is close to static, so we can see the result (http://www.yss-aya.com/cgos/19x19/standings.html)

LZ-HY-W24-PO1600   3030  
LZ-HY-W23-PO1600   3011

And other LZ-0XX-p1600-t1-r1 is not close to static(<100 games), the score of them are  all bellow the 2 hybrid weights, and to my experiment, the score of LZ-0XX-p1600-t1-r1 will continue to drop during 50 to 100 games process.

So after several test, in my opinion:
1. Hybrid can stronger the weights
2. Hybrid seem can promote 50+ cgos elo  of original weights (according to 150+ leela zero self elo)
3. NOLIMIT is also get the best CGOS ELO of leela zero, so in the high playout game, "Hybrid" is also work.
4. Hybrid can also get weaker weights, a stronger hybrid weight mix with an original weight, often get a weaker one.

**Comment by pangafu** [comment]
@gcp Maybe we can try "hybrid" in the end of 6 block, after hybrid -> self-play -> train several weights -> hybrid -> ..., maybe we can see the true limit of 6 block.

**Comment by pangafu** [comment]
Now I run W25-PO1600 and W25-NOLIMIT on CGOS, the W25 and po 200 match log is below(Thank 飞 to hybrid)
[6w25_b69-4fe-a55_1-0.5-0.5.zip](https://github.com/gcp/leela-zero/files/1769753/6w25_b69-4fe-a55_1-0.5-0.5.zip)

We can wait the CGOS result for a while...

**Comment by jjoshua2** [comment]
This is cool.  I hope we try promoting a hybrid one at end of 6 blocks. When you make w26 I'll run no limit on a 1080ti on Windows if you want.

**Comment by pangafu** [comment]
@jjoshua2 welcome~ If we find a new stronger hybrid weight, I will post here .
also you can hybrid by yourself with tools:
https://github.com/pangafu/Hybrid_LeelaZero

**Comment by jjoshua2** [comment]
I tried to use it on Windows and haven't gotten it to work yet. Gogui
requires java and there's weird character encoding errors

**Comment by Splee99** [comment]
I have run an even game of w24 and AQ and W24 won. This hybrid weight is like always created two major battle fields at same time and made opponents confused.

**Comment by pangafu** [comment]
@jjoshua2 maybe you should download java to run gogui.
Since the issue closed here, I will post new hybrid file in my github space, new W26 is come out, and please goto https://github.com/pangafu/Hybrid_LeelaZero/releases to download.
You are welcome to put it and run on CGOS with your 1080ti.
