### ISSUE TITLE
"Handicap Compensation"

### ISSUE THREAD

**Issue by billyswong** [gcp/leela-zero#955]
I saw people playing with LeelaZero in KGS with handicap stones and the score counting involves "handicap compensation".

From what I understand the neural net is learning Go in a fixed 7.5 black-to-white scoring difference, when people play handicap games with LeelaZero under Chinese rule, should they tune down the komi value so that the scoring difference remains a 7.5? (The game I witnessed set a 7.5 komi and the score counting added 7.5 komi + 2 handicap compensation = 9.5 points)

**Comment by killerducky** [comment]
It's handled by LZ already here

https://github.com/gcp/leela-zero/blob/5958e02cf539d42ee20704b664043036d5c3c18b/src/FastState.cpp#L151

**Comment by billyswong** [comment]
But it is for end score, while the neural net, no matter the policy head or the value head part don't really handle that. They are still computing winning percentage under the experience of fixed 7.5 point difference.

**Comment by killerducky** [comment]
Oh I see, you're right. Handicap games should be played with 5.5 komi for H2, 4.5 for H3, 3.5 for H4, etc.

**Comment by gcp** [comment]
I don't understand. If you lie about the komi, the counting for the score will be off. The network doesn't know or care about komi != 7.5 So where would be the gain?

**Comment by killerducky** [comment]
Oops you're right. So it's just that the game should be setup with komi - handicap right? For both the real game and for LZ?

**Comment by gcp** [comment]
Yes, I think that's what OP is saying.

This doesn't require any changes to Leela, it's a guideline for setting up handicap matches.

**Comment by petgo3** [comment]
For real handicap games in kgs, i inverted colors to the nn. I hope we have a net trained for -7.5 komi. Lz now tries to win with min 6 points  a h2 game.

**Comment by billyswong** [comment]
@petgo3 So that means people playing with your bot can and should set handicap games to 0.5 komi?

**Comment by petgo3** [comment]
Sure both possible now😁

**Comment by bood** [comment]
What if I set the beginning of the game like `(D4 B) (PASS W)` and still set the komi to 7.5? Any difference to `handicap 2 + komi 6.5`?
@billyswong @gcp

**Comment by billyswong** [comment]
@bood In theory the black player in your case can play a pass immediately and win, and the komi value doesn't matter.
@gcp I assume this issue is "properly" closed when there's an update to either the README or the FAQ on how to setup handicap games against LeelaZero correctly.
