### ISSUE TITLE
evals after MAX_TREE_SIZE decrease move quality 

### ISSUE THREAD

**Issue by sethtroisi** [gcp/leela-zero#956]
After the search tree is "full" (size >= MAX_TREE_SIZE) UCTSearch repeatedly adds playout "visits" to nodes biasing their score towards the initial neural net eval (and away from any playout data)

I artificially lowered the limit to demonstrate this here 

```NN eval=0.478301
Playouts: 3271, Win: 49.57%, PV: D4 Q16 Q4 D16 R17 R16 Q17 P17
Playouts: 6515, Win: 49.47%, PV: D4 Q16 Q4 D16 R17 R16 Q17 P17
Playouts: 9781, Win: 49.37%, PV: D4 Q16 Q4 D16 R17 R16 Q17 P17
Playouts: 13037, Win: 49.30%, PV: D4 Q16 Q4 D16 R17 R16 Q17 P17
Playouts: 16283, Win: 49.22%, PV: D4 C3
Playouts: 19520, Win: 49.15%, PV: D4 C3
...
Playouts: 62027, Win: 48.77%, PV: D4 C3
```

This is what I saw when doing high playout exploration of D4
initially the NN scores of Q16 the highest but after 1M playouts we see it has low combined score than D16.
After tree is full UCTSearch alternates between adding playouts to D16 and Q16 this slowly biases the score of Q16 up till it's greater than D16.

More theoretically I believe PV will converge to the nodes with the highest initial score (which might be the same as using `-p 1`)

I suggest immediately exiting UCTSearch after the max number of positions that fit in memory have been expanded. This means limiting leela-zero to ~100K playouts in the short term (and ~500K after small_nodes goes in)

**Comment by RavnaBergsndot** [comment]
I believe there was a similar phenomenon discussed in the computer-go mailing list. In that case, a traditional rollout based MCTS engine becomes weaker when fixing the tree size and increasing the playouts indefinitely. I don't remember if the behavior was converging back to playout=1 or not though.

**Comment by gcp** [comment]
>UCTSearch repeatedly adds playout "visits" to nodes biasing their score towards the initial neural net eval (and away from any playout data)

I don't understand. Why does this happen?

**Comment by sethtroisi** [comment]
I think the biggest culprit is that we can re visit a leaf node, add evaluations*, and increase it's playout count multiple times which UTCNode interprets as having more confidence in the eval.

**Comment by Eddh** [comment]
Are you running this on multiple threads ? What depth does the tree reach at max_tree_size ?

**Comment by sethtroisi** [comment]
(on my phone)

Even with rotations the eval of a leaf node is an approximate constant if you consider large number of playouts where it will be the average of all eight rotations.

I was wrong when i said it biases back to the initial eval (or that it behaves like -p1). It might be more true to say it acts like cfg_puct is dramatically reduced.

As playouts increases sqrt(visits)/(child visits) => 0 and all root nodes get explored. The unexplored node (of which there will be many) with the highest eval (averaged over the eight rotations), will get large number of playouts (assuming it has an eval above that of the deeply searched moves) and bias the root's score as well as potentially be chosen as next move.

With infinite playouts it might become alpha-beta over the expanded tree. For reasonable numbers it acts like cfg_puct is reduced and if a child with high eval but low policy score exists it will likely be chosen. Given how inaccurate the value network (and how many children there are) it's likely that such a child exists.

I'll include the dump stat log which shows how playouts end up distributed over additional root moves to depth 1

All of this is also true of the nodes selected at depth 2 and beyond (when playouts happen in parts of the tree that have been expanded). 

Maybe a different way to state the problem is average search depth increases up till max_tree_size then will be dramatically reduced implying that the move selection is now based on a swallower understanding

**Comment by TFiFiE** [comment]
What would happen if instead of no longer expanding nodes whenever the limit is reached, unpromising nodes start getting collapsed again? Or would the slowdown and/or memory fragmentation not make this worth it?

**Comment by sethtroisi** [comment]
@Eddh max_tree_size is a measure of total nodes. We don't have any metrics about depth.

I can hit the current max_tree_size with ~200,000 playouts (or ~60 seconds of thinking time)

**Comment by Eddh** [comment]
@sethtroisi I wondered about depth because I thought maybe after so many playouts we reach end games values which may have an impact. Can't we get some idea about it from the end output showing PV ?

**Comment by sethtroisi** [comment]
I'm away from computer currently but I'll post a dump_stat link later

**Comment by Mezoka** [comment]
This issue has been discussed in computer-go mailing list many years ago, one of the link I can find is : (may be more) [link](http://computer-go.org/pipermail/computer-go/2011-July/003915.html)
in which Pachi's author, Petr Baudis said : When Pachi runs out of memory, it stops the search. searching without growing the tree further is extremely harmful !

**Comment by sethtroisi** [comment]
@Mezoka, Thanks for the additional discussion. 

With `MAX_TREE_SIZE = 500'000` ~1,000 playouts
`echo "go" | ./leelaz  -w ../weights.txt -t1 -s1 --noponder -p 800`
```
 D16 ->     134 (V: 49.73%) (N: 17.37%) PV: D16 Q4 D3 Q16 C9 F17 D14
 Q16 ->     120 (V: 49.59%) (N: 16.17%) PV: Q16 Q4 D17 C4 E4 E3 F3 D3 O3
  Q4 ->     119 (V: 49.60%) (N: 16.08%) PV: Q4 D16 Q17 D4 R11 O3
  D4 ->      95 (V: 49.74%) (N: 12.18%) PV: D4 Q16 R4 D16 R14 O17
 D17 ->      44 (V: 50.14%) (N:  4.96%) PV: D17 D4 R16 Q4 C6 F3 C11 P16
 Q17 ->      43 (V: 50.38%) (N:  4.29%) PV: Q17 Q4 C16 D4 R6 O3 R11
 R16 ->      41 (V: 50.31%) (N:  4.23%) PV: R16 D16 Q3 D4 F17 C14 L17
  D3 ->      41 (V: 50.13%) (N:  4.55%) PV: D3 D16 R4 Q16 C14 F17 C9 P4
  Q3 ->      40 (V: 50.09%) (N:  4.48%) PV: Q3 Q16 C4 D16 R14 O17 R9
  C4 ->      38 (V: 50.32%) (N:  3.99%) PV: C4 D16 Q3 R16 P16 P17
  R4 ->      38 (V: 50.02%) (N:  4.49%) PV: R4 D4 Q17 D16 F3 C6 L3 Q15
 C16 ->      34 (V: 50.05%) (N:  3.97%) PV: C16 Q16 D3 Q4 O17 R14 J17 D5
```

`echo -e "time_settings 0 1 0\ngo" | ./leelaz  -w ../weights.txt -t1 -s1 --noponder -p 150000`
```
Playouts: 2754, Win: 49.62%, PV: D16 Q4 D3 Q16 C9 F17 D14 D18 C17 J17
Playouts: 5293, Win: 49.63%, PV: D16 Q4 D3 Q16 C9 F17 D14 D18 C17 J17
Playouts: 7714, Win: 49.65%, PV: D16 Q4 D3 Q16 C9 F17 D14 D18 C17 J17
Playouts: 10188, Win: 49.68%, PV: D16 Q4 Q17 D4 R6 O3 R12 K17 F17
...
Playouts: 37428, Win: 49.80%, PV: D16 Q4 Q17 D4 R6 O3 R12 K17 F17
Playouts: 39795, Win: 49.80%, PV: D16 Q4 C4 Q17 E3 C10 Q15
...
Playouts: 47215, Win: 49.81%, PV: D16 Q4 C4 Q17 E3 C10 Q15
Playouts: 49650, Win: 49.81%, PV: C16 Q16 D3 Q4 O17 R14 J17 D5 C5 C6
Playouts: 52118, Win: 49.81%, PV: C16 Q16 D3 Q4 O17 R14 J17 D5 C5 C6
Playouts: 54588, Win: 49.81%, PV: C16 Q16 D3 Q4 O17 R14 J17 D5 C5 C6
Playouts: 57036, Win: 49.82%, PV: C16 Q4 D3 Q16 O17 R14 J17
...
Playouts: 84214, Win: 49.83%, PV: C16 Q4 D3 Q16 O17 R14 J17
Playouts: 86702, Win: 49.83%, PV: C16 Q4 Q17 D4 R6 O3
...
Playouts: 130777, Win: 49.85%, PV: C16 Q4 Q17 D4 R6 O3

 C16 ->   32992 (V: 50.03%) (N:  3.97%) PV: C16 Q4 Q17 D4 R6 O3
 D16 ->   16133 (V: 49.75%) (N: 17.37%) PV: D16 Q4 C4 Q16 O3 R6 H3 C10
 D17 ->   10947 (V: 49.93%) (N:  4.96%) PV: D17 D4 R16 Q4 C6 F3 C11 P16 N17
 Q17 ->   10282 (V: 49.94%) (N:  4.29%) PV: Q17 Q4 C16 D4 R6 O3 R11 E16 G17 C17 C13
  Q4 ->    9699 (V: 49.58%) (N: 16.08%) PV: Q4 D16 D3 Q16 C14 F17 C8 K3 O3
 Q16 ->    9087 (V: 49.54%) (N: 16.17%) PV: Q16 D4 C16 Q4 J17 R14 O16 S16
 R16 ->    8706 (V: 49.92%) (N:  4.23%) PV: R16 D16 Q3 D4 F17 C14 M17 Q5 R5
  Q3 ->    8550 (V: 49.91%) (N:  4.48%) PV: Q3 Q16 C4 D16 R14 O17 R8 E4 E3
  C4 ->    7823 (V: 49.91%) (N:  3.99%) PV: C4 D16 Q3 Q16 R14 O17 R9 E4 G3
  D3 ->    6708 (V: 49.86%) (N:  4.55%) PV: D3 D16 R4 Q16 C14 F17 C9 P4 N3 R3
  D4 ->    6194 (V: 49.49%) (N: 12.18%) PV: D4 Q16 R4 D16 L3 C6 F4 B4 C3
  R4 ->    5235 (V: 49.81%) (N:  4.49%) PV: R4 D4 Q17 D16 F3 C6 L3 Q15 R13 R17 R18
  P3 ->     130 (V: 49.72%) (N:  0.15%) PV: P3 
 K10 ->     126 (V: 49.68%) (N:  0.17%) PV: K10 
 C15 ->     104 (V: 49.76%) (N:  0.11%) PV: C15 
 R15 ->     103 (V: 49.69%) (N:  0.13%) PV: R15 
 P17 ->      90 (V: 49.68%) (N:  0.12%) PV: P17 
  E3 ->      75 (V: 49.64%) (N:  0.11%) PV: E3 
 E17 ->      63 (V: 49.61%) (N:  0.10%) PV: E17 
 C17 ->      49 (V: 49.48%) (N:  0.10%) PV: C17 
  C3 ->      46 (V: 49.49%) (N:  0.09%) PV: C3 
```

C16 had previously been the WORST move evaluated

**Comment by sethtroisi** [comment]
@killerducky That's a reasonable way to resolve this. I'll run some tests tonight.

**Comment by Eddh** [comment]
It does seems bad that nodes that have not been searched a lot end up selected because of these "false visits". A visit where you add precision to node evaluation is not as valuable as a true visit.

**Comment by bjiyxo** [comment]
#918 Maybe my pondering issue has something to do with this. Lz often thinks more than 40000 playouts/move on my computer, so pondering maybe exceed this and sometimes get a bad result.

**Comment by sethtroisi** [comment]
@bjiyxo If you have a 64 bit machine then you need somewhere in the order of 400,000 playouts (you can also look for `1601 visits, 563325 nodes, 1600 playouts, 1259 n/s`) line after a move is played and see if it's >= 100,000,000 nodes

**Comment by bjiyxo** [comment]
@sethtroisi No. I observed many times, and it never exceeded 30M nodes. So there's nothing to do with my issue.

**Comment by marcocalignano** [comment]
Why don't we add some scoring value base on depth. So when the MAX_TREE_SIZE is reached the shallow branches can be 'cut'. It also make sense that a move with deeper evaluation is better than a move with smaller evaluation but the same scoring.

**Comment by Eddh** [comment]
@marcocalignano potentially there might be something there. Assuming we stop adding false visits when MAX_TREE_SIZE is reached, then the less visited paths have no chance of being ever chosen. We could cut some of them so that we can add true visits to the few most visited in order to better select between them. That's just theory and seems hard to implement though.

**Comment by gcp** [comment]
What I would suggest is that we detect when we are at MAX_TREE_SIZE / 2, and at that point, only link the best 1/10th of the nodes (per policy value), and maybe additionally drop everything with a policy score that is say 100 times smaller than the best.

@sethtroisi do you have an idea whether this would work as expected with #887?

**Comment by Eddh** [comment]
@gcp do the 0-policy nodes count ? There are a lot of them and they are not removed if I recall right.

**Comment by gcp** [comment]
What's a 0 policy node?

**Comment by Eddh** [comment]
I'm pretty sure there are a lot of nodes for which the network assign a policy that is completely 0.000f. I'll need to verify when I can.

**Comment by gcp** [comment]
That would be covered by the "100 times smaller than the best" rule.

**Comment by roy7** [comment]
@gcp

> Right now a network eval produces a policy score for all nodes, so you can't have a node that doesn't have an associated policy value?

It appears this is no longer the case now. I want to confirm that's intended and correct before I change some code to no longer use eval_state.

**Comment by marcocalignano** [comment]
So I went ahead and built a float `m_level` variable that increases of 0.1 down the tree so that I would do `m_level * node_score` to reward deeper trees. But I do not completely understand the node scoring functions and I do not know at which variable apply this factor. Anyone cna help, so I can make some experiment to see if this rea;;y improve the algorithm or not.

**Comment by Eddh** [comment]
It would be when you update() in UCTSearch I guess, but then you also need to modify that part because the average of rewards should be computed differently. Right now it's the total reward/visits (and there are virtual losses complicating that part too)

**Comment by gcp** [comment]
Underlying bug is fixed, discussion about solutions is in issue #980.
