### ISSUE TITLE
autogtp.exe sometimes stops while running

### ISSUE THREAD

**Issue by teddy-cc** [gcp/leela-zero#96]
As title, I run autogtp.exe on windows 10.  When program is running, sometimes it stops unexpectedly   and it can run continually if you press the enter key in the command window of  autogtp.exe.  The CPU usage rate is about 70-80%.
p.s. Sometimes the game ends very early likes 60 steps, but I see the game needs to continue.  
Is it a bug or  not?

**Comment by zhu-jz** [comment]
It's a feature of windows, if you click the cmd window, it stops.

**Comment by teddy-cc** [comment]
But I already check the programs is running.  I open two command windows,for a while, one or both of them has a chance of stopping and I check I don't click cmd windows during it.

**Comment by teddy-cc** [comment]
Maybe it cause by CPU sometimes is near 100% usage rate?

**Comment by OmnipotentEntity** [comment]
To answer your second question.  No, the network is just kinda dumb still.  We've seen 4, 3 and even 2 move games (including passes).

**Comment by teddy-cc** [comment]
![strange_b 17](https://user-images.githubusercontent.com/33782836/32990799-aa2c4108-cd6a-11e7-9f36-a713d74da42e.jpg)


I see.   And there is a new question.  The result of  game I attach is B+17.5 , but all white is died.

**Comment by marcocalignano** [comment]
black has to play k10 to kill if it passes white is alive and the result is right

**Comment by teddy-cc** [comment]
But with the network becomes stronger ,the game result also uses this method to decide.  Is it still OK when

**Comment by gcp** [comment]
The program only cares whether it wins or not, it doesn't care about the exact count. Thinking in terms of winning by a small or large margin is a crutch used by humans (this applies to most modern Go programs, not just Leela Zero).

If it would have mattered for the result, it would have killed the group.
