### ISSUE TITLE
Do we need to increase filter from 128 to 192 with 10b?

### ISSUE THREAD

**Issue by bjiyxo** [gcp/leela-zero#960]
http://computer-go.org/pipermail/computer-go/2018-February/010725.html
According to Remi Column(author of crazystone), he did Weights_31_3200 on cgos and reached 4068 on bayes elo (http://www.yss-aya.com/cgos/19x19/bayes.html). From the kifu on cgos, it looked like zero rather than Master! And he said Weights_31_3200 is 20 layers of 192. Our best lz bot on cgos is LZ-HY-W24-NOLIMIT(with hybrid one) and reach 3440(The difference is 628 between Weights_31_3200!), so it looked attractive to upgrade from 6b128f to 10b192f. Do you have any plan on upgrade 192f?

**Comment by zhu-jz** [comment]
Why not

**Comment by gcp** [comment]
No. There's nothing magic about increasing the filters compared to layers, and layers are more beneficial unless you believe that some features require more than 128 individual inputs to be effective. That doesn't make too much sense.

128x10 is a random point in the space of possibilities, 192x10 is just a random. Slower but expected to be a bit better. So would 128x15.

**Comment by gcp** [comment]
If you want to have a valid argument here, train two networks, one with 10x192, one with Yx128, where Y is chosen so that the calculation speed is the same. (I think that's Y around 18 or so?). Train them on existing data, and demonstrate that 10x192 is better than 18x128.

I expect you will fail.
