### ISSUE TITLE
6615567e promoted and then ignored

### ISSUE THREAD

**Issue by jkabrg** [gcp/leela-zero#966]
Sequence of events:
A starts match against B.
C starts match against D.
A wins match.
A gets promoted.
C wins match.
C gets promoted.
C plays match against E. (A ignored)

Which is what happened with:
A = 6615567e
B = 6615567e
C = 1a198f8d
D = 53f4cc79

This is "wrong" for two reasons:
In this example, A had a much higher win rate than C.
A and C were playing against different opponents.

**Comment by jkiliani** [comment]
Just Read #965. It's even in the title...

**Comment by jkabrg** [comment]
@jkiliani So is A being ignored on purpose? This is not a bug?

**Comment by jkabrg** [comment]
OK. Can I delete this?

**Comment by jkabrg** [comment]
The clue is that A and C were playing different opponents, and issue #965. `A` only exists in order to tease us.

**Comment by jkiliani** [comment]
Of course it isn't a bug. @gcp opened #965 specifically so people would read it before asking this question. Short answer: He's testing the strength of the 10 block bootstrapped net, but isn't quite ready to promote it yet while 6 blocks still have a bit of growth potential.
