### ISSUE TITLE
An idea to improve MCTS results

### ISSUE THREAD

**Issue by amirlb** [gcp/leela-zero#969]
I was thinking about the ladders problem as bit, and have an idea on how to help the net avoid playing the move it already knows loses. This may also help with other situations.
Unfortunately I don't have a good GPU so I can't show test results to confirm or refute this.

In situations where the ladder doesn't work but the policy network is not aware of this, the policy net gives a high prior to capturing the cutting stone with a ladder. This causes the first few hundred playouts to take this options. After a while all variations trying to capture with a ladder give a very low value, so the later playouts avoid this futile path. Since the final choice depends on the total number of visits, Leela zero would still try to use the ladder.

This leads me to believe that later playouts choose moves more intelligently than earlier ones. So using only the last playout's choice for the root if with high probability the best move the search found so far. Using just one move carries the risk that this is a purely exploratory playout. that is the first expansion of a move, which is risky. Taking the most common root child of (say) the last 100 playouts would probably be better than taking the root's child with the most playouts total. But having a fixed constant sounds odd, so my suggestion is to weigh later visits more than earlier ones in a continuous fashion. In detail:

Store on each node a weighted visit count in addition to the current visit count. When a child is visited, add 1 to the visit count and add the visit count to the weighted visit count. The weighed visit count will only be used in NodeComp and in randomize_first, and the regular visit count will be used for child selection.

WDYT everyone?

**Comment by alreadydone** [comment]
Previous works on ladders:
https://github.com/gcp/leela-zero/issues/844#issuecomment-364487041
https://github.com/gcp/leela-zero/issues/696#issuecomment-359189740
https://github.com/gcp/leela-zero/issues/696#issuecomment-363089234
https://github.com/gcp/leela-zero/pull/850
https://github.com/gcp/leela-zero/pull/866#issuecomment-365084942
I am not sure whether consensus is reached regarding which method works best, but [the 10b network](https://github.com/gcp/leela-zero/issues/965#issuecomment-369959538) seems to fare much better on ladders than 6b.

BTW searching issues in Gmail works much better than in GitHub if and only if you are watching this project...

**Comment by amirlb** [comment]
I'm also seeing discussion about post-processing the search tree in #860, this post probably belongs in that issue's thread (but I don't think it possible to demote it)

**Comment by alreadydone** [comment]
If you close this issue it won't show up when people look at the (open) issues.
