### ISSUE TITLE
Project transparency 

### ISSUE THREAD

**Issue by CamWagner** [gcp/leela-zero#97]
Because this project relies on volunteers, I feel like it would be beneficial to let us know what the state of things is a little more often. It's been mostly darkness for the last 2 days. Occasional updates would be nice. Such as the current win rate of the network and any progress towards training it. It feels like, "what's wrong?"

**Comment by bood** [comment]
If you go through issue #78, you can find some status updates there
http://zero.sjeng.org/ is a page setup by @gcp , but only with some numbers

But I agree, more status updates (with details) would motivate contributors in general.

**Comment by imsqueekyclean** [comment]
We are noticing a decrease in submitted games/h and /24h. Have there been a lot of server outages or something recently? Or people just losing interest this quickly? Maybe above issues has something to do with it?

**Comment by roy7** [comment]
The server had problems for about 30 minutes earlier today. So I imagine a lot of people's clients stopped running until they notice to restart them at some point. Currently if the game upload fails the client will just exit, instead of retrying.

**Comment by gcp** [comment]
This is a volunteer project from my side as well. Unless you're going to pay me to work on this full time (which I wouldn't even want) you're not going to get more updates until more things are automated. And while I'm answering questions like this one, I'm obviously not busy automating things.

**Comment by bood** [comment]
Please do let us know if you can use any help on automation @gcp
