### ISSUE TITLE
Feature request: Auxiliary outputs of winner of each point of the board

### ISSUE THREAD

**Issue by tapaniraiko** [gcp/leela-zero#98]
I would suggest adding a third type of outputs to the neural network: Who controls each point of the board at the end of the game, that is P(win_i) for all i=1...361 separately. It would be trained the same way as the value network (except that there is also the neutral case, e.g. seki liberties). There are many practical uses for such outputs:
- Allows for teaching tools:
    * Estimating the score during game play.
    * Visualization of who controls which areas of the board by using P(win_i) as a heatmap.
    * Measuring the value (in points) and visualizing the goodness (in affected area) of a move by comparing the heatmap to one produced by passing instead.
- Allows for new (unoptimal but still interesting) playing styles by using the trained network differently:
  * Maximizing the number of points (instead of probability of winning) by using sum_i P(win_i) to score the nodes in the tree search. This would be useful for handling different komis and handicap games without training separate networks for them.
  * Varying playing styles such as preferring to get territory on lines 1-3 vs center of board. Or preferring to play in points i that are likely to be controlled by a particular player, P(win_i) is high or low (build own vs invade).
  * Using nonlinearity such as sum_i [P(win_i) + alpha*P(win_i)*(1-P(win_i))] where alpha is between -1 (pessimistic, risk averse) and +1 (optimistic, risk seeking). Alpha could be automatically set to a value that makes the score estimate of the current root node to a draw. This would allow playing handicap games in a style that is closer to maximizing the winning percentage instead of maximizing points.
- Training with auxiliary tasks has been shown to speed up deep reinforcement learning in other tasks.

I get it that you would like to replicate AlphaGo Zero rather than implement original ideas, but training for these new outputs on the side would come almost for free. Fortunately this can also be included later with a reasonble computational cost by re-training with existing data, if you store all the self-play games.

**Comment by gcp** [comment]
As you point out, it's possible to train or run these kind of experiments afterwards. They're, as far as I'm concerned, completely out of scope for this project.

(To do this you would need to be able to correlate the SGF with the training data for each game, which you probably can't do right now from the split data dumps. But this information is kept on the server, so it would be recoverable at the end)

**Comment by TFiFiE** [comment]
To possibly get something going, [here](https://github.com/TFiFiE/leela-zero/commit/7b2387a1a45b270d283f370f635e096d672031c6)'s some starting work on this feature. Perhaps its development should get its own branch here.
