### ISSUE TITLE
Can someone build an AMI for AQ/Leela and other bots?

### ISSUE THREAD

**Issue by hydrogenpi** [gcp/leela-zero#985]
.

**Comment by hydrogenpi** [comment]
https://www.reddit.com/r/cbaduk/comments/82boiq/can_someone_build_an_ami_for_aqleela_and_other/

**Comment by gcp** [comment]
For the P3 instances there's a Linux "Deep Learning AMI". AFAIK you can follow the README instructions and Leela Zero will work on it with good performance.

**Comment by hydrogenpi** [comment]
Thanks, does that one have a GUI insofar as you know? The official amazon instructions is to use putty to connect to it from Windows. I don't know enough command in linux to be able to install the gui and also something like tightvnc to be able to remote into it with UI in the first place... once I can get past that hurdle then the rest shouldn't be too difficult.

**Comment by hydrogenpi** [comment]
what is the commands to install the nvidia telsa v100 drivers for ubuntu on the command line without gui?

**Comment by pheasant75** [comment]
I have successfully built one from this amazon image:
_Deep Learning AMI (Ubuntu) Version 5.0 - **ami-7336d50e**
Comes with latest binaries of deep learning frameworks pre-installed in separate virtual environments: MXNet, TensorFlow, Caffe, Caffe2, PyTorch, Keras, Chainer, Theano and CNTK. Fully-configured with NVidia CUDA, cuDNN and NCCL_
I spot requested a g3.4xlarge instance for less than $0.4 per hour.  Running the commands above with no issues (almost) except at the step "qmake -qt5".  I changed it to "qmake -makefile" and it seems to be fine.

It has a Nvidia Tesla M60 GPU.  I tried to run ./autogtp -g 1 -u 0 -u 1 and seems to be running as well, although the documentation says that it has only 1 GPU.  Maybe it is the same as running ./autogtp -g 2?

Here is what I got after 2 thread finished their first game respectively.
 2 game(s) (2 self played and 0 matches) played in 9 minutes = 294 seconds/game, 1022 ms/move, last game took 588 seconds.

I have created an image ami-ff6e9182 and share it publicly. You have to choose your region as US-East (N. Virginia) to see this.  Hope it works on other GPU instances as well.  If not, you can try to go through the commands mentioned in the readme.

**Comment by hydrogenpi** [comment]
pheasant75 , wow thanks very much for ami-ff6e9182 , I will give it a try now. 

BTW does it have a GUI enabled and installed? I'm trying to install teamviewer on it so that it is better to connect than VNC and RDP.

**Comment by pheasant75** [comment]
You can refer to this link.  I haven't tested it so I am not sure if it
will work for you or not.  Seems it will use remote desktop to connect so
you need to make sure your security group has RDP port enabled when you
request cloud instance.
https://comtechies.com/how-to-set-up-gui-on-amazon-ec2-ubuntu-server.html

Also, if you try to run LZ with gui, you might have to find that solution
as well.  I believe there is a fancy one (shows the win percentage) but it
is not supporting linux at this point.

**Comment by ValentinHirschi** [comment]
@pheasant75 Do you know how slower it would be to generate games with CPU on a c2.large instance? Because you can get them spot-requested for 0.03 $ / hour, which is more than 10 times cheaper than for the GPU-enabled g3.4xlarge one. So it may come out cheaper this way no?

**Comment by pheasant75** [comment]
@ValentinHirschi  I just launched an c4.xlarge instance (there are only c4 and c5), and the spot price is about $0.06 per hour (US East, N Virginia).  Rebuild leelaz with use opencl commented.  the xlarge instance is shown to have 4 vCPUs.
running ./autogtp -g 2 gives me approximately 26 moves total (~13 steps each) in 8 minutes.
running ./autogtp -g 4 gives me approximately 80 moves total in 16 minutes.
Note that I don't know if I can use more threads to play one game, so just test these setup.  And I didn't wait the game to finish, just estimate with the moves played.
Based on those data, I suppose that means $1.00 will give you ~30 games?

**Comment by ValentinHirschi** [comment]
OK, so very roughly, that puts the price-tag of a game on g3.xlarge at about 0.4$/(12 games an hour) =~ 0.03$  and on c4 at about 0.06$ / (3 games an hour) =~ 0.02$.
So very similar in the end, and it's more convenient to have one g3.xlarge instance rather than 8 c4 ones.
This begs the question of how well a nano instance would fare, but there I presume you would anyway be hitting your limit on the number of running instances.
That puts the price-tag of the 29M games needed by alpha-zero at 580k$... mhh not great.

Now, maybe one could use google's own weapons? :) Did anyone already try to apply for some free TPU time?
https://www.tensorflow.org/tfrc/
https://services.google.com/fb/forms/cloud-tpu-beta-request/
Though, I don't know leela-zero's  code, so I can't judge how easy it would be to hook it to a tensor-flow with a TPU back-end. Anyone?
