### ISSUE TITLE
Suggestion: Jump-start early training

### ISSUE THREAD

**Issue by tapaniraiko** [gcp/leela-zero#99]
In the beginning, the value-network is random. The tree search is no better than random policy. Using this data to train the policy network is thus meaningless (training target is no better than current guess).

Since the first phase is already based on random moves, and does not really train the policy network, one could generate the first batch of games by random playout, and train only the value outputs.

On the other hand, if you store and re-use all the self-play games, this jump-start has very limited value.

**Comment by gcp** [comment]
See issue #1. Before I got to implement this we already had 20k games and the program had started learning.
