### ISSUE TITLE
Next big Windows update will bring hardware-accelerated machine learning

### ISSUE THREAD

**Issue by afalturki** [gcp/leela-zero#992]
[Next big Windows update will bring hardware-accelerated machine learning](https://arstechnica.com/gadgets/2018/03/microsoft-pushing-machine-learning-as-big-developer-feature-for-next-windows-update/)

"The models themselves use a format called ONNX, developed by Microsoft, Facebook, and Amazon Web Services and supported by Nvidia, Qualcomm, Intel, and AMD."

Is this relevant in any way to Leela Zero?

**Comment by l1t1** [comment]
404

**Comment by afalturki** [comment]
oops. Sorry about that. Fixed

**Comment by gcp** [comment]
We are already doing hardware accelerated machine learning on all platforms.
