### ISSUE TITLE
Leelaz v12 release windows x64 crashed

### ISSUE THREAD

**Issue by jjoshua2** [gcp/leela-zero#994]
Was playing CGOS all day and it crashed after running about 24 hours in the middle of just a regular game.

I clicked debug and see different errors:

The thread 0x293c has exited with code 0 (0x0).

Unhandled exception at 0x00007FFF8A1B0730 (ntdll.dll) in leelaz.exe: 0xC0000005: Access violation reading location 0x0000096403B89018. occurred

It looks like it entered into ntdll and did `call        RtlpFreeHeap (07FFF8A1ADCC0h)` which ended up calling `call        RtlpInsertFreeBlock` and erroring with with instruction:
` mov         edx,dword ptr [rdi-8]`

Is this some sort of double free edge case maybe?

The lczero.exe code that broke in the call:
```
00007FF7880F50B3  mov         rcx,qword ptr [7FF7881BB528h]  
00007FF7880F50BA  call        qword ptr [7FF78812D128h] 
 ```

**Comment by jjoshua2** [comment]
If I have the leela-zero.pdb I can debug it better... I tried making one from the master branch with a release compile but it didn't work. Are these made with a debug build or does anyone have the actual pdb?

**Comment by gcp** [comment]
>I tried making one from the master branch with a release compile but it didn't work.

What's the problem there?

**Comment by jjoshua2** [comment]
The pdb says it can't find the right symbols. The exe is presumably fine

**Comment by killerducky** [comment]
I found a potential problem, both jjoshua2 and I had crashes on CGOS with bots that ponder. When a bot wins a game, CGOS does not inform the bot until the start of the next round. This means the bot could ponder the same position, worst case, the entire round time of 30 minutes.

I think it's possible to overflow m_visits by doing 2 billion visits. I was able to create some positions with very few legal moves and calculated it would overflow in around 200 minutes on my machine. Maybe in some other cases it could be faster than CGOS round time of 30 minutes.

I guess we should put some code in ponder to prevent it from thinking forever?

**Comment by killerducky** [comment]
Ok I looked at the logfile of my CGOS bot that crashed again. I think my system ran out of memory while pondering between rounds, and when the next round started it was very slow, maybe because the system was swapping.

Can we modify LZ to also look at available system memory when allocating nodes instead of a hard coded MAX_TREE_SIZE?

See below the end of the log. First a snippet of the pondering. You can see the opponent's eval is 0.00%, because LZ won this game by resign, but CGOS doesn't tell us so we continue pondering. Then you can see it hit the max 50,000,000 nodes. Then the next game starts, but for the first move even though we were given 12.5s to think, my computer only managed 8 visits. `8 visits, 2873 nodes, 7 playouts, 0 n/s`. By the next move you can CGOS tells us we've actually used 900-718=182 seconds. `time_left w 718 0`

```
 H15 ->   61725 (V:  0.00%) (N: 13.80%) PV: H15 H17 H2 N10 N9 H1 H3 G1 J1 J6 A3 J9 J7
  Q6 ->   61700 (V:  0.00%) (N: 13.79%) PV: Q6 N10 N9 H17 H15 J9 H1 G1 H2 H3 H4 J6 J7 J14 O15 N19
   <---cut other moves--->
442433 visits, 50074172 nodes

>>boardsize 19
=

>>clear_board
=

>>komi 7.5
=

>>time_settings 900 0 0
=

>>play b Q16
=

>>time_left w 900 0
=


  D4 ->       1 (V: 55.98%) (N: 23.90%) PV: D4
  Q4 ->       0 (V: 45.83%) (N: 17.38%) PV: Q4

2 visits, 721 nodes

>>genmove w
Thinking at most 12.5 seconds...
NN eval=0.458252
Playouts: 6, Win: 35.74%, PV: D4 R4 D16 P4
 
  D4 ->       5 (V: 50.79%) (N: 23.90%) PV: D4 R4 D16 P4
  Q4 ->       2 (V: 52.43%) (N: 17.38%) PV: Q4 D16 
8 visits, 2873 nodes, 7 playouts, 0 n/s 
  
= D4 


  R4 ->       4 (V: 48.17%) (N: 18.85%) PV: R4 D16 P4 R17
  Q4 ->       2 (V: 48.38%) (N: 18.05%) PV: Q4 D16
 D16 ->       1 (V: 51.83%) (N: 16.57%) PV: D16

8 visits, 2866 nodes

>>play b R4
= 

>>time_left w 718 0
= 


1 visits, 359 nodes

>>genmove w
Thinking at most 9.9 seconds...
NN eval=0.475713
Playouts: 7, Win: 37.23%, PV: D16 P4 R17 Q17

 D16 ->       5 (V: 51.56%) (N: 40.77%) PV: D16 P4 R17 Q17
 C16 ->       3 (V: 53.81%) (N: 31.15%) PV: C16 P4 R17
9 visits, 3213 nodes, 8 playouts, 0 n/s

= D16


  P4 ->       4 (V: 46.60%) (N: 40.01%) PV: P4 R17 Q17 R16
 C17 ->       3 (V: 48.67%) (N: 25.45%) PV: C17 D17 C16

8 visits, 2848 nodes

>>play b F3
=

>>time_left w 346 0
=



1 visits, 357 nodes
```

**Comment by jjoshua2** [comment]
My machine has 32gb of memory but maybe up to 20gigs was in use by other
processes. Ive seen leela using over 8 gigs before but never enough to slow
down.

But it did crash not just go slow.

**Comment by killerducky** [comment]
Hm so maybe something else is going on or maybe there are multiple issues. BTW I looked more and I see now there were instances where my bot did more than 50,000,000 nodes. See below the top few sorted. Maybe a memory leak? Or memory fragmentation? Anyone have some debug suggestions? I'm going to try going to latest next branch and lower the node limit manually to see if I can run stable.

```
117158 visits, 33327236 nodes
217241 visits, 33915420 nodes
442433 visits, 50074172 nodes
1160093 visits, 100000172 nodes
1340226 visits, 100000250 nodes
708527 visits, 100000298 nodes
1453941 visits, 100000326 nodes
```

**Comment by roy7** [comment]
Finding and fixing the problem is the priority of course, but for your CGOS bot maybe --visits 1000000 would help? Since visits and pondering can work together.

**Comment by zediir** [comment]
I had the same problem so I added

```
gameover {
  # send clear board to let the engine know it can stop pondering
  set msg [eCmd $inout "clear_board"]
```

to the gameover block in the tcl client to stop leela zero from pondering when a gameover is received.
