### ISSUE TITLE
Leela zero still do not know Ladder and draw

### ISSUE THREAD

**Issue by jungsup824** [gcp/leela-zero#995]
I have played Leela and AQ in sabaki. Leela zero is quite strong and win AQ sometimes but still do not know ladder and draw. 
![ladder problem](https://user-images.githubusercontent.com/34597284/37139076-8127b8e6-22e7-11e8-9256-829854724605.png)

**Comment by fergusyuen** [comment]
Yeah, it tried that once on mine too

**Comment by fergusyuen** [comment]
Are you using leela zero 0.12? I don’t how to use it in sabaki because I can’t find the openCL file. Do I just can’t see that file or you have another way to play leela zero0.12?
