### ISSUE TITLE
What constitutes a forced move?

### ISSUE THREAD

**Issue by barrtgt** [gcp/leela-zero#996]
Some moves are very quick to play now. So what exactly does the search/selection use to evaluate what to play quickly? The number of proportional visits to a move, its value, policy, or other?

**Comment by gcp** [comment]
In practice it is a result of high policy prior % combined with high winrate compared to alternatives. There's no hard definition, nor is there any programmed knowledge about this. It's just that the search decides that the overwhelming majority of effort has to be spend along a variation.

**Comment by barrtgt** [comment]
Is noise/temperature still a factor in the selection for these positions?
