### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by kennychenfs** [gcp/leela-zero#997]
I found Leela Zero's mistake.
It should choose to move in the list.
But I see it moving in a weird place.

**Comment by jkiliani** [comment]
I think you need to be a lot more specific here... what do you mean, do you have data, a .sgf file, debug output...?

**Comment by kennychenfs** [comment]
(;GM[1]FF[4]RU[Chinese]DT[2018-03-08]SZ[19]KM[7.5]PB[Leela Zero 0.12 75603ad2]PW[Leela Zero 0.12 75603ad2]RE[B+Resign]
C[Leela Zero options: -p 0 -v 3200 -r 10 -m 30 -t 1 -d -n --noponder -s 13923820129862026418 -g -q -w 75603ad2735612279eed11ffd69f3ea7a02574605dace846e055f992a445f49c]

;B[qp];W[qd];B[cp];W[dd];B[cc];W[af];B[dc];W[fd];B[ed];W[ee]
;B[ec];W[ff];B[gc];W[nd];B[fp];W[oq];B[pn];W[kq];B[cj];W[ql]
;B[qj];W[ol];B[nn];W[pi];B[qi];W[ph];B[qg];W[pj];B[rf];W[oo]
;B[on];W[dp];B[dq];W[cq];B[eq];W[co];B[bp];W[dn];B[bo];W[bn]
;B[cm];W[cn];B[bq];W[ek];B[mq];W[mr];B[dk];W[el];B[ej];W[fj]
;B[ei];W[fi];B[eh];W[fh];B[eg];W[fg];B[of];W[bk];B[ck];W[fn]
;B[pk];W[pl];B[ok];W[qk];B[nk];W[nl];B[mk];W[ml];B[lk];W[nh]
;B[ll];W[mm];B[ne];W[od];B[lg];W[bh];B[bj];W[rn];B[kh];W[nq]
;B[ce];W[df];B[cf];W[dg];B[cg];W[rp];B[kp];W[lp];B[jq];W[jp]
;B[ko];W[lo];B[ln];W[kn];B[jo];W[lm];B[ip];W[kr];B[ld];W[lc]
;B[kc];W[mc];B[kb];W[jn];B[in];W[im];B[hn];W[hm];B[rd];W[qe]
;B[re];W[rc];B[rb];W[qc];B[sc];W[li];B[mi];W[mh];B[lh];W[qb]
;B[pg];W[ki];B[ji];W[kj];B[ni];W[jj];B[oh];W[jh];B[jg];W[ii]
;B[md];W[de];B[ch];W[lb];B[la];W[nb];B[na];W[oa];B[ma];W[kd]
;B[ic];W[ig];B[ob])

**Comment by kennychenfs** [comment]
move 6 is weird.

**Comment by MartinDevelopment** [comment]
If you are talking about the first 30 moves, that is normal due to the randomness added to those first 30 moves.

**Comment by jkiliani** [comment]
Exactly, move 6 will have been low on the move output probability map, but it was still picked randomly. Games without -m option won't have such moves. This only diversifies the opening which helps training the neural net.

**Comment by kennychenfs** [comment]
It's useful.Thank you.
