### ISSUE TITLE
[Question] randomize first 30 moves and fpu_reduction compatibility

### ISSUE THREAD

**Issue by ThomasCabaret** [gcp/leela-zero#998]
Hi, a little question suggestion:
The actual effect of the fpu_reduction (with current training settings) is to prevent any visit of moves with a too low policy prior.
The aim of the "Randomize First 30 moves" option is to guaranty a better exploration during training and is based on choosing randomly the actual move, among the visited moves, proportionally to their visits count.
This randomizing option will guaranty that even options almost not visited have a non null probability to be chosen and gives so a non null chance to the program to actually later reassess what it thinks about the option.
But as mentioned above, fpu_reduction will keep to 0 the number of visits of nodes with low policy prior making them inaccessible to the randomizing option.
Maybe something should be worked out here? (disable fpu during the randomizing moves windows, or give a really small chance of being selected during the randomization even to moves with no visits?).
My guess is that guaranty a non null epsilon chance to every moves during training randomization is important, else it will not be able to reassess opening moves with an already too low policy prior.
What do you guys think?

**Comment by gcp** [comment]
The dirichtlet noise is there to ensure that occasionally an odd move gets good policy prior. Randomize is very unlikely (or not able) to pick a move with a very low prior anyway, regardless whether FPU reduction is in use or not.

**Comment by gcp** [comment]
>not to find "holes" in the knowledge

Which is further illustrated by it only being active the first 30 moves.

**Comment by ThomasCabaret** [comment]
@gcp Yes indeed, the dirichlet noise does the stuff, I am wondering "how much" it can actually influence the decision taken but anyway it clearly does the job. Thx.

**Comment by Friday9i** [comment]
One question linked to the randomization (not sure where I should post it, sorry if it's not the good place): why not more diversity in josekis, for example on the 3-3 invasion? It is always followed by a double hane (an extension is playable, but never played) and always answered by the capture of the outside stone (a hane on the otherside is playable, but never played). I don't understand why there is not more diversity, these alternative moves are perfectly legal, they seem credible (hence they should not be rejected a priori: on the opposite, they should be on the list of potential interesting moves) and hence, in my understanding, the added "noise" should allow them to be played quite regularly. But no, they are never played, I looked at dozens of games: never tested! Is it "normal" or should we suspect a bug?

**Comment by Eddh** [comment]
If you look at the AGZ paper the same joseki (3-3 double hane) was played quite often too (in training games at least). Frequency of 3% per corner for a large part of the training. Which is the most frequent among the joseki presented in AGZ paper. We may have a slightly higher frequency but it still seems normal. The difference can be explained by the early bugs or the different network sizes.

**Comment by Friday9i** [comment]
Thanks but it's not exactly my point: the 3-3 invasion + double-hane joseki is frequently played, a bit boring but not a big deal indeed. What I don't understand is why the 3-3 invasion is always followed by the double-hane joseki: the double-hane is the only played joseki after 3-3, I never saw another one. Isn't it strange that no alternatives are played?

**Comment by pheasant75** [comment]
@Friday9i I saw other variants of 3-3 invasion. It is the knight's move.  Popular after alphago.  Just that it is not frequently adopted in match games yet.

**Comment by Friday9i** [comment]
True, I saw the AG's knight move a few times for a short time about 2 weeks ago, but it now disappeared (totally?): it plays the double hane and (almost?) nothing else... Hence my question: why no variation at all when there is many acceptable variations in this joseki in answer to the 3-3 invasion?

**Comment by MartinDevelopment** [comment]
LZ says that this is the best variation it can come up with at the moment it plays. This changes with training.

**Comment by pheasant75** [comment]
@Friday9i In a chinese website, someone did the analysis of the self-play sgf.  He found that the alphago's 3-3 knight move was played before, but it is not been selected now.  
https://imgsa.baidu.com/forum/w%3D580/sign=d3e7d2d0f7edab6474724dc8c737af81/ee2e2834349b033b2c5d50c119ce36d3d439bddc.jpg
The x-axis for the left figure is the # of games played.
The entire post is at: https://tieba.baidu.com/p/5594841747

**Comment by Friday9i** [comment]
Thanks a lot pheasant75, very interesting link, it confirms LZ selects now only the double hane variation after 3-3 invasion (as you say MartinDev). However, I still don't really understand why it is not exploring alternatives (of course it is a consequences of weights driving to the double hane joseki and not to alterative joeskis, but why are weights driving things this way and not at all testing alternatives?). Anyway, it will probably evolve over time.

**Comment by ThorAvaTahr** [comment]
Please note that there are ladders involved in the 3-3 invasion joseki, especially in those with the knights, which has more complicated variations. It is quite possible that LeelaZero has not yet quite understood the intricacies of these variants. In fact it may be possible that the network is too small to understand them well (these ladders are fully across the board). The lack of this understanding may bias LZ to favor the double hane variant.

**Comment by Friday9i** [comment]
Possible. However, instead of playing double hane, the color outside could just extend: simple, no ladder involved, but never played. Also, after double hane, the color inside could hane on the other side: reasonably simple but not played also.

**Comment by pheasant75** [comment]
@ThorAvaTahr That is true. I remember watch two games played exactly the same way.  Ended with the ladder capture.  I believe it is from that 3-3 invasion with knight's move.
Wait! doesn't this makes the knight move more likely to be selected?  Since the one who makes the knight move are ones that benefit from the ladder capture.

**Comment by ThorAvaTahr** [comment]
@pheasant75 that should depend on whether the network thinks the ladder is good or bad. It could default to bad (or e.g. high-risk) in case it doesn't know and avoid it altogether, but I think this is over-analysing the question and simply the network doesn't know at this point. I remember from the AZ paper that 3-3 double hane is quickly gaining popularity in the first couple of million games and only later the knights-move becomes more favoured.
